### ISSUE TITLE
AJAX Add to cart on Checkout Page

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/Easy-Digital-Downloads#1059]
I ran into this while working on the Suggestions extension. I'm adding 'Add to Cart' buttons on the Checkout page, and when you have AJAX Add to cart buttons that do not redirect to the cart, it forces the user to manually refresh the cart in order for the items to show.

I know the core EDD plugin doesn't have Add to Cart buttons on the Checkout page but if an extension adds it, we may want to force the Checkout page to redirect to itself all the time when Add To Cart is used, much like the 'Remove' links on the cart table.

I did this on my template file for my extension which only runs on the checkout page.

``` javascript
<script type="text/javascript">
    // Causes the Checkout page to refresh if an item is added to the cart from the checkout page
    edd_scripts.redirect_to_checkout = '1';
</script>
```

I think this would provide a better user experience if a widget or extension has an 'add to cart' on the checkout page.

**Comment by kajalko** [comment]
I know the core EDD plugin doesn't have display in option enable ajax Downloads > Settings > Misc.
