### ISSUE TITLE
Incorrect path and URL constants when installing EDD via a symlink

### ISSUE THREAD

**Issue by benjaminprojas** [easydigitaldownloads/easy-digital-downloads#1084]
When installing EDD via a symlink, the constants EDD_PLUGIN_DIR and EDD_PLUGIN_URL are incorrect.  i.e. 
![laork9p c4tz](https://f.cloud.github.com/assets/962530/377375/a8a471ca-a4a2-11e2-8292-f12743eddecf.png)

A fix for this is to change the constants as follows:

``` php
// Plugin Folder Path
if ( ! defined( 'EDD_PLUGIN_DIR' ) )
    define( 'EDD_PLUGIN_DIR', WP_PLUGIN_DIR . '/' . basename( dirname( __FILE__ ) ) . '/' );

// Plugin Folder URL
if ( ! defined( 'EDD_PLUGIN_URL' ) )
    define( 'EDD_PLUGIN_URL', plugin_dir_url( EDD_PLUGIN_DIR )  . basename( dirname( __FILE__ ) ) . '/' );
```

**Comment by chriscct7** [comment]
How many people actually install WordPress this way? Is it a common practice?

**Comment by pippinsplugins** [comment]
It's common enough that I've seen it, but I haven't seen it in a year or so.

I'd like to get it resolved but it's not a priority.

**Comment by benjaminprojas** [comment]
I always do installs this way for development...

**Comment by pippinsplugins** [comment]
No one has been able to look into this further yet so punting to 2.4.3.

**Comment by cklosowski** [comment]
Ok this is going to kick off a failed build so i'm jsut going to cancel it, but, unit tests will load finally, but having issues with tests on getting page URLs after the Tests_Activation runs the `edd_install` method after we've already started the unit tests. This is a good start I believe and will get us heading in the right direction if someone wants to take up this torch and finish it up, be my guest.

*tosses in towel for a day or two*

**Comment by pippinsplugins** [comment]
@cklosowski Which part of the tests fail?

**Comment by cklosowski** [comment]
We have failures in the following, at least locally for me:
```
There was 1 error:

1) Tests_Activation::test_install
Undefined index: purchase_history_page

/Users/cklosowski/WordPress/src/wp-content/plugins/easy-digital-downloads/tests/tests-install.php:67

--

There were 5 failures:

1) Test_Misc::test_get_current_page_url
Failed asserting that 'http://example.org/' matches expected false.

/Users/cklosowski/WordPress/src/wp-content/plugins/easy-digital-downloads/tests/tests-misc.php:539

2) Test_Misc::test_cart_url_formats
Failed asserting that 'http://example.org/?cart_item=8&edd_action=remove&nocache=true' contains "page_id=3".

/Users/cklosowski/WordPress/src/wp-content/plugins/easy-digital-downloads/tests/tests-misc.php:565

3) Tests_Scripts::test_load_scripts_checkout
Failed asserting that false is true.

/Users/cklosowski/WordPress/src/wp-content/plugins/easy-digital-downloads/tests/tests-scripts.php:33

4) Tests_Scripts::test_register_styles_checkout_ssl
Failed asserting that false is true.

/Users/cklosowski/WordPress/src/wp-content/plugins/easy-digital-downloads/tests/tests-scripts.php:89

5) Tests_Widgets::test_cart_widget_function_bail_checkout
Failed asserting that a string is empty.

/Users/cklosowski/WordPress/src/wp-content/plugins/easy-digital-downloads/tests/tests-widgets.php:74
```
All are related to requesting page URLs for some of our pre-configured pages.

**Comment by cklosowski** [comment]
I'm actually going to hold off on this until we merge in #3976, which does a better job of isolating the testing of the install process, that might fix up the unit tests for this too.

**Comment by cklosowski** [comment]
Possibly related: #3286

**Comment by cklosowski** [comment]
I cannot get this to work great yet, still having some major issues with the unit testing suite, i'm punting to 2.6

**Comment by chriscct7** [comment]
Much to Benjamin's dismay, it's clear there isn't a huge usecase on this. Perhaps we should close this finally @cklosowski ?

**Comment by cklosowski** [comment]
Yeah I think only a few people have requested it, i'm going to close it for now.

**Comment by benjaminprojas** [comment]
I am dismayed.

**Comment by cklosowski** [comment]
I know @benjaminprojas :( I am a bit too, but something just isn't working correctly with all the included and required paths. So far, I've only seen you and me try to operate like this, and we haven't gotten many (if any at all) requests for it in support, which tells me it's not something widely used.

Just because it's closed now, doesn't mean it'll be closed forever.

**Comment by benjaminprojas** [comment]
Haha, it's cool. In all honesty, I've started using Local by Flywheel with the volumes add-on which mounts the folders instead of using symlinks. I'm virtually working the same way, and don't have this same issue any more. So for now, I'm good.
