### ISSUE TITLE
Deleting Easy Digital Downloads leaves behind user roles

### ISSUE THREAD

**Issue by stacigh** [easydigitaldownloads/Easy-Digital-Downloads#1203]
I was test driving this plugin to see if it was what I needed (awesome plugin but a little too much for what I needed this time). I deactivated and deleted the plugin but discovered that it left behind some user roles. It was a pretty simple fix to remove. I used:

```
$wp_roles = new WP_Roles();
$wp_roles->remove_role("shop_manager");
$wp_roles->remove_role("shop_accountant");
$wp_roles->remove_role("shop_worker");
$wp_roles->remove_role("shop_vendor");
```

Not sure if this was intentional or if it was an oversight but I thought I'd let you know about it.

**Comment by mtomas7** [comment]
This bug is still present on the WP.org version of EDD.

**Comment by chriscct7** [comment]
Did you check the "remove all EDD data" checkbox in the EDD settings before removing EDD? That's not checked by default, and must be checked for roles to be removed by default

**Comment by mtomas7** [comment]
I was looking at the settings but didn't spot easily an uninstall section or tab.

**Comment by chriscct7** [comment]
The checkbox is labeled "Remove Data on Uninstall?" in the current release, and is on the default home tab of the EDD settings page

**Comment by mtomas7** [comment]
Thank you! It's 3 AM, so it might be my bad.

**Comment by chriscct7** [comment]
Not a problem, I fully understand not seeing things at 3am (coming from a student whose literally overnighting for an exam in 6 hours right now ;-) )
