### ISSUE TITLE
Automatic product type handling

### ISSUE THREAD

**Issue by evertiro** [easydigitaldownloads/easy-digital-downloads#1391]
We need a better (automatic) way of adding and handling options on a per-product-type basis.

**Comment by pippinsplugins** [comment]
We haven't had many use cases for this yet (still nice though), so I'm going to punt for now.

**Comment by pippinsplugins** [comment]
Punting again as we still haven't had much real need for this.

**Comment by cklosowski** [comment]
Closing, still no real need or desire for this.
