### ISSUE TITLE
Plugin meta links should include donate button.

### ISSUE THREAD

**Issue by michael-cannon** [easydigitaldownloads/Easy-Digital-Downloads#1406]
On the plugins page, EDD's plugin meta links should include donate button.

I'll contribute code shortly.

**Comment by Ubrwgn** [comment]
I'm not a programmer, per se. But after setting up EDD for my boyfriend's site he suddenly wants to test it by first offering his guitar lessons with a donation button. I'm so confused. Are you planning on offering this as an EDD option soon? I'll keep researching in the meantime.

**Comment by sumobi** [comment]
@Ubrwgn If you need a donation button with EDD, check out this EDD extension: https://easydigitaldownloads.com/downloads/donations/
