### ISSUE TITLE
Discount Code Reports

### ISSUE THREAD

**Issue by sunnyratilal** [easydigitaldownloads/easy-digital-downloads#1427]
We should introduce reports for discount code usage.

I'm thinking of these:
- The amount of people who've used a discount code, this would be month by month and year by year.
- The products that have been purchased with a single discount code.

**Comment by pippinsplugins** [comment]
While I'm not sure we can get this finished for 2.3, I'd like to at least lay out how it's going to work and what kind of reports we're going to create.

**Comment by cklosowski** [comment]
Since we've not seen any progress, and we still need to determine how this data is going to look. Punting to 2.4.

Right off the bat, I'm pretty sure we'll need an upgrade routine to make sure we can easily (and performance friendly) pull all payments associated with a discount code.

**Comment by danieliser** [comment]
Extending on this idea, I'd like to be able to pull a list of all licenses in EDD SL that were generated using a particular code as well.

I'm thinking this needs to be built into a new EDD_Discount_Stats class in general.

**Comment by cklosowski** [comment]
We should also make discount columns sortable by Usage and dates.

**Comment by pippinsplugins** [comment]
Moving to 2.5 for the reports release.

**Comment by sunnyratilal** [comment]
I propose the following plan of action:

* Introduce `EDD_Discount_Stats` to handle all the sales/earnings queries
* Add `Discounts` option to the report type dropdown on the `Reports` admin page
* Add a dropdown of discount codes and date ranges to view sales/earnings for chosen discount codes

Do we allow a report to generated showing sales/earnings of any discount code?  I think until that's abstracted we should leave it out because that's going to be a super expensive query.

**Comment by pippinsplugins** [comment]
I like this plan.

**Comment by sunnyratilal** [comment]
This entire feature cannot be implemented until #5217 is implemented and we have some form of abstraction to move discounts outside of the payment meta.

We can either do the abstraction for discounts in 2.7 or this gets moved to 2.8?

**Comment by pippinsplugins** [comment]
Let's see how far we can get and then move the remainder to 2.8.

**Comment by sunnyratilal** [comment]
Closing as this is effectively a duplicate of #6303.
