### ISSUE TITLE
Add "Recount Earnings" Tool

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#1479]
There have been several times that I've needed to recalculate the earnings of a Download.

I'd like to introduce a link under the Tools menu to recalculate the earnings of all (or any specific) products).

It will basically query the logs and grab all sale entries and readd the earnings from that.

**Comment by chriswallace** [comment]
What causes this situation? Would a change in prices be the culprit? We recently changed prices and that's when I first noticed this issue occurring. It would be ideal to fix the root cause of the issue if we can pinpoint it.

**Comment by pippinsplugins** [comment]
We're still trying to track that down.
