### ISSUE TITLE
Settings refactor

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#1484]
I've discovered a few problems with the current settings API (excluding stupid code duplication).

I'm refactoring it and taking care of the following:
- [x] Removing all code duplication for settings sections and tabs
- [x] Storing all settings in a single option called `edd_settings` instead of one for each tab
- [x] Adding support for custom tabs via a simple filter
- [x] Adding sanitization callbacks for each tab
- [x] Adding sanitization filters for each field and filed type
- [x] Fixing a problem where settings can be overwritten by previous settings if moved from one tab to another

**Comment by littlepackage** [comment]
All callbacks seem to work except the checkbox callback, which saves as true and stays saved as true even when unchecked? Am I missing something?

```
add_settings_field(
       'edd_settings[enable]',
       'Enable',
       'edd_checkbox_callback',
       'edd_settings_' . $tab,
       'edd_settings_' . $tab,
       array(
              'id'              => 'enable',
              'desc'         => 'Check to enable',
              'section'     => $tab,
       )
);
```

**Comment by chriscct7** [comment]
The options for check boxes are deleted when hey are unchecked. So if checked the option is saved in the db as true. When its unchecked the option is deleted from the db completely

**Comment by littlepackage** [comment]
This is not occurring in my database. All other options are updating fine, just not the checkbox. Do you see anything wrong with my code there. It's strange that only the checkbox is having troubles updating in the database.
