### ISSUE TITLE
Better tax reports

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#1490]
We need to give better reporting options for taxes.

For example, we should allow site admins to generate a report for the total tax paid for any time period.

**Comment by pippinsplugins** [comment]
This is getting closer to being feasible with #1976.

**Comment by pippinsplugins** [comment]
Had a request for this today: https://easydigitaldownloads.com/support/topic/report-of-monthly-taxes/

**Comment by pippinsplugins** [comment]
Bumping to this 2.5 along with most other major reporting improvements.

**Comment by pippinsplugins** [comment]
Sadly punting once again.

**Comment by sunnyratilal** [comment]
@cklosowski Is this something you'd like to get into 2.9?

**Comment by jameslaws** [comment]
+1

**Comment by cklosowski** [comment]
I believe so but it will be FAR easier to query once we get custom tables for payments and cart items.

**Comment by cklosowski** [comment]
And by easier I also mean performant and accurate.

**Comment by cklosowski** [comment]
More requests and features wanted: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6223#issue-279403113

**Comment by sunnyratilal** [comment]
Closing as this is happening in #6301.
