### ISSUE TITLE
Revert #1163

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/Easy-Digital-Downloads#1540]
PayPal has removed their 9 item limit from their TOS.
As such, if it hasn't been done yet, #1163 needs to be reverted.

It's replacement seems to be an upper cap thats even harder to determine. Basically its whenever the posted URL to PayPal exceeds 255 characters. Somewhere around 20 itemized items depending on the length of the titles

Also see comment on:
https://github.com/woothemes/woocommerce/issues/3124#issuecomment-24357033

**Comment by jessetolz** [comment]
@pippinsplugins and @chriscct7 I put together TurtleTreeSeed.org and am hoping you can help me with the 9 item limit in WooCommerce PayPal Standard. It's quickly becoming a bottleneck in our workflow at the seed shop. Is what you'd referenced above (90a9125) a solution to this scenario? How do I implement, or can you at least point me in the right direction? Any help would be immensely appreciated!

https://github.com/easydigitaldownloads/Easy-Digital-Downloads/commit/90a91257e69596a56a7c28a313d72a6717f348c0

**Comment by pippinsplugins** [comment]
@jessetolz I"m sorry but we cannot assist with a WooCommerce issue. Please reach out to WooCommerce support.
