### ISSUE TITLE
Payment Gateways need more options and decisions

### ISSUE THREAD

**Issue by Ipstenu** [easydigitaldownloads/easy-digital-downloads#1882]
You already know my WePay debacle. If I deactivate the plugin, I no longer can see WePay on my reports, which.... Data nerd. So I made this mu-plugin:

```
    add_filter( 'edd_payment_gateways', 'wepay_fake_register_gateway' );   
    function wepay_fake_register_gateway( $gateways ) {
        $gateways['wepay'] = array( 
            'admin_label' => 'WePay (DEFUNCT)'
            );
        return $gateways;
    }  
```

And that works great, my logs etc are back, with two issues.

1) I can't 'hide' the checkbox. Fine, I'll force that with some CSS

``` php
/* EDD Stuff */
label[for="edd_settings[gateways][wepay]"],
input[id="edd_settings[gateways][wepay]"] {
    display: none;
}
```

It leaves a line break due to the `<br>` in there, but at least I can hide it. An option in the gateway array would go a long way to make this ... hide-able. Or active but inactive? Defunct? Some way to say "We had this, we don't, but we still need our old metrics for whatever purpose" (Actually I can think of legal reasons why I'd need this in certain situations)

But this brought up the second issue which was ...

2) You can select a default gateway from a gateway that isn't checked active. Logically if a gateway isn't checked, it shouldn't be an option for default. Not that I think anyone would be that silly, but a good decision (see?) would be "If this is not active, you can't use it, silly person."

_whew_

So at this point my genius escapes me. I spent most of tonight stepping backwards to see how you could even do that. My best thought is `edd_get_enabled_payment_gateways` would have a wrap for not just ones 'activated' by the `edd_payment_gateways` filter, but checked as well. However with that, then you **still** don't get the reports because they too use the enabled check... Perhaps that's the answer? Reports should list all gateways no matter what?

Though you may want to ajaxify it (god knows how, it's a mystery to me) so that it dynamically updates the list as you check/uncheck.

**Comment by chriscct7** [comment]
I think we should do a gateway class  where gateways would extend the parent gateway class, and could use things like gateway_supports and stuff. We could easily do backwards compat for this (we did it for both forms and fields in FES)

**Comment by chriscct7** [comment]
Also it would be cool if extensions could add properties to the overall parent gateway class.

**Comment by pippinsplugins** [comment]
I agree. I've been building a new gateway class in RCP and am going to use
that as a base for the Easy Digitial Downloads version most likely. It has
full backwards compatibility for the current gateway API.

**Comment by cklosowski** [comment]
#4195 Will handle doing things like this and make it more reasonable to configure gateways in the desired method. Closing this one, but leaving a reference to the `EDD_Gateway` issue so we can cross reference it.
