### ISSUE TITLE
Add support for In-Context PayPal checkout

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#1896]
PayPal introduced In-Context checkout today: https://www.paypal-pages.com/incontextcheckout/

Let's support it in core.

For Buy Now buttons, it should open the checkout modal on that same page.

**Comment by chriscct7** [comment]
PayPal no longer supports in-context checkout. They only support redirect to PayPal or login with PayPal (which still redirects to PayPal) for Standard
