### ISSUE TITLE
Update HTML Elements class

### ISSUE THREAD

**Issue by ghost1227** [easydigitaldownloads/Easy-Digital-Downloads#1907]
The HTML Elements class is a bit outdated and needs some overhauling.

- [ ] All fields should support label and desc (only text and textarea currently do)
- [ ] Why do some functions have fallbacks when others don't (see backwards compatibility check on text field)
- [ ] There's no function for handling radios (could be integrated into the checkbox function as an argument?)
- [ ] A good chunk of EDD core doesn't yet use the HTML Elements class (see payment details, for one)
- [ ] Registration form/shortcode

Thoughts? What else can be done to improve the class?

**Comment by pippinsplugins** [comment]
We've had some nice improvements here. I'm going to close this out, however. Each of the proposed improvements above should be handled as separate issues. We'll open new issues as appropriate.
