### ISSUE TITLE
Remove base64_decode/encode from file download process

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#1930]
We currently use base64_decode and base64_encode for encrypting download link expiration times. Over all, this works just fine, except that occasionally is causes problems with hosts that have anti virus systems setup. The base64 functions get flagged as malicious and the host then automatically deletes process-download.php, as reported in this case: http://wordpress.org/support/topic/process-downloadphp-gets-deleted-as-soon-as-i-upload-it?replies=12#post-5132492

We can easily replace base64 with something else that won't get flagged.

**Comment by pippinsplugins** [comment]
Hmm, so this is interesting. It just occurred to me that signed URLs in #603 does not actually fix this bug. Some servers will still delete the file since it contains `base64_*` functions for backwards compatibility.

What if we moved those functions to a separate file and then wrap the file in a `if( file_exists() )` check? That way it will load if present (so old URLs work) but will not fatal error the site if it gets deleted.

Any objections to that method?

**Comment by chriscct7** [comment]
Or we could just do https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/1930#issuecomment-33760897 and we'd never have to worry about it again.

**Comment by pippinsplugins** [comment]
No. We will never, ever, ever do that.

**Comment by chriscct7** [comment]
I know ;)

**Comment by cklosowski** [comment]
@pippinsplugins yeah I'm good with that. I realized that it wasn't fixing the greater issue in the first iteration. I hadn't thought of the ```file_exists``` method. I like that.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
Resolved in #3149

**Comment by pippinsplugins** [comment]
I have opted to place `edd_verify_download_link() in `deprecated-functions.php` and then wrapped the include for `deprecated-functions.php` in a `file_exists()` check.

The `base64_decode()` that was in`process-download.php` has been moved inside of `edd_Verify_dowload_link()` now, so if it triggers a file deletion, nothing terrible will happen.
