### ISSUE TITLE
Download Additions to a Payment  to be Recorded in Logs

### ISSUE THREAD

**Issue by atwellpub** [easydigitaldownloads/Easy-Digital-Downloads#1934]
Heya Group!

What I'm looking to do is manually add products to a payment and have a sale log created for that payment and download id. 

This way I can use the EDD_Logging class to detect that a payment id is associated with a download id even if the download was added manually to a payment. 

I took a look for hooks that I might could do this with and I didn't see any developed in yet. The closest I could get was to create a new sale log for each item in a payment cart when the payment is updated. 

```
/* check for new downloads manually added to payment - logs updated cart items */
add_action('edd_updated_edited_purchase', array($this ,'update_logs') );

function update_logs( $payment_id )
	{
		/* start logging engine */
		$edd_log = new EDD_Logging;
		
		$updated_downloads = isset( $_POST['edd-payment-details-downloads'] ) ? $_POST['edd-payment-details-downloads'] : false;
		if( $updated_downloads && ! empty( $_POST['edd-payment-downloads-changed'] ) )
		{
			foreach( $updated_downloads as $download ) {

				$date =  date('Y-m-d G:i:s', time()); 
				$log_data = array(
									'post_parent' => $download['id'],
									'log_type' => 'sale'
							);
				
				$log_meta = array(
						'payment_id'=> $payment_id
				);
				
				/*
				print_r($log_data);
				echo "<br>";
				print_r($log_meta);
				echo '<br>';
				var_dump($edd_log->insert_log( $log_data, $log_meta ));
				echo '<br>';
				*/
			}
		}
	}
```

Related to this ticket: https://easydigitaldownloads.com/support/topic/add-logs-when-updating-payments/#post-170247

**Comment by cklosowski** [comment]
Likewise, shouldn't deleting a download from a payment ID remove a sales log?

**Comment by pippinsplugins** [comment]
Yes.

**Comment by cklosowski** [comment]
Ok I've got the new logs being created when a download is added and then the payment is saved...just need to do the removal of a log when a download is deleted.

**Comment by pippinsplugins** [comment]
Excellent

**Comment by cklosowski** [comment]
Just pushed up a Work In Progress. A few things are needed here, like handling quantities, adding a limit/order by on the log query when deleting, and that should do it.

Currently it's working for non-quantity purchases. The way it does it is by adding every deleted item to a JSON object that we interpret during the update of the payment.

It loops through the deleted downloads, finding logs associated with this payment, that have a post parent of the post ID. As it goes through, it finds a log entry with the same price ID, and then deletes it, and decrements the purchase count and purchase value of the download.

Again WIP, not ready for prime time yet. But thought I would commit to get some eyes on it as it is so far.

**Comment by cklosowski** [comment]
Ok I have a quick question on new logs added...

Should the log date be the date the download was added to the payment, or the date of the initial payment creation?

**Comment by pippinsplugins** [comment]
Date added to payment.

**Comment by cklosowski** [comment]
That's what I was leaning with as well, only concern there was if it spans months, it could mess with reporting. We can start with this and see where it goes.

**Comment by pippinsplugins** [comment]
At first glance, this looks good. I will test it soon.

**Comment by pippinsplugins** [comment]
This is looking really good but I have found a bug.

If you add a new item to a payment that has an amount of `0.00`, the log gets created, the earnings get properly _not_ incremented, and the sales get incremented as expected, but the amount shown in the sales log is incorrect. It's showing as the default item price, not the `0.00` entered.

**Comment by pippinsplugins** [comment]
Ah, the log amount is always wrong. I just tested by adding an item that is normally $20 but setting the amount to $2. The total earnings for the download were incremented by $2, but the log amount shows $20:

![screen shot 2015-02-24 at 10 40 45 am](https://cloud.githubusercontent.com/assets/1034109/6353900/9d0f0176-bc11-11e4-9afe-bcd2195b8384.png)

![screen shot 2015-02-24 at 10 40 57 am](https://cloud.githubusercontent.com/assets/1034109/6353911/a5936774-bc11-11e4-8e5a-dd61ffed6af4.png)

**Comment by pippinsplugins** [comment]
Ah, actually this appears to be due to https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/2978

It only happens when you add two of the same product.

**Comment by pippinsplugins** [comment]
We can ignore that bug for now. It needs to be resolved at some point but is unrelated to this issue.

**Comment by pippinsplugins** [comment]
This is working beautifully.

**Comment by pippinsplugins** [comment]
I'm going to close this out for now. Reopen if any issues are noticed.
