### ISSUE TITLE
Introduce EDD_Template_Tag shortcode

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/Easy-Digital-Downloads#1938]
Lots of times, we get requests for ways of showing things like the total amount in sales a store has done on the frontend. Statistics like this are often too small to warrant having a standalone shortcode.

Starting with 2.0, the goal is to offer an [edd_template_tag] shortcode that lets EDD users show data from EDD core & it's extensions in a simple shortcode.

The shortcode usage will be [edd_template_tag tag="xxx"] where xxx is the data the user wishes to display.

Core will add a bunch of default tags like:
total-sales: shows total sales over a time period
number-of-purchases: for store, product
user-statistics: $ of sales, $ of orders etc

Extensions will also be able to add their own tags to show.

We'll likely use a simple switch statement, like the one in FES, for output:
switch ($tag){
case 'total-sales':
  // something
 break;
case 'another-case':
 // something
 break;
default:
do_action('edd_template_tag_'. $tag);
break;
}
where the default is used for extension tags.

**Comment by danieliser** [comment]
To me this sounds less like it should be shortcodes neccesarily and more like a group of helper functions. That limits usage by non admin persons as well.

In that sense they could make their own shortcodes and would have to decide for themselves who could use them.

**Comment by cklosowski** [comment]
I'm not sure this is a good plan. I see the use case, I just think there's too much potential for a massive headache in the support realm. We provide ample helper functions as it is to get this information. They can code it into their them (child theme) if they want. I think shortcodes would be overkill here.

**Comment by chriscct7** [comment]
I no longer support my own original proposal. Recommend closing

**Comment by cklosowski** [comment]
Sounds good, closing this out. Thanks!
