### ISSUE TITLE
Rework edd_get_sales_tax_for_year()

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#1976]
[edd_get_sales_tax_for_year()](https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/tax-functions.php#L187) currently retrieves all of the payments for the specified time period and then retrieves the taxed amount (stored in postmeta) for each payment.

This can result in thousands and thousands of queries being run when getting tax for a year.

**Comment by cklosowski** [comment]
Make sure we don't forget we'll have to update that meta when a payment is edited from the details view.

**Comment by cklosowski** [comment]
Ok, did some testing and this is what I got:
Pre-1976:
4227 Payments
Did calculation in 8.2657051086426 seconds

With the above changes:
9485 Payments
The calculation completed in just over 2 seconds.

**Comment by pippinsplugins** [comment]
Bitchin.

**Comment by cklosowski** [comment]
@pippinsplugins using ```$wpdb->get_var()``` drops the value in cache...do you think this is a problem? 

Source: http://codex.wordpress.org/Class_Reference/wpdb#SELECT_a_Variable

**Comment by pippinsplugins** [comment]
I don't think so. This query will only need to be run once every so often
so having the results cached should not be a problem.

**Comment by pippinsplugins** [comment]
@cklosowski I think we should rework the upgrade routine here to use direct DB queries to help avoid the slow down caused by re-indexing and cache busting, just like we did with the price log upgrade routine.

**Comment by cklosowski** [comment]
@pippinsplugins Sounds like a good plan

**Comment by pippinsplugins** [comment]
It'll make the upgrade routine much, much faster.

**Comment by cklosowski** [comment]
@pippinsplugins as discussed on Slack...we can't separate this out into direct DB calls as the `_edd_payment_tax` is a new `meta_key`, we can't issue a direct call to implicitly add if it doesn't exist, and we should be making sure that we work if someone restarts, or breaks, or something.

While not the most performant, I think this is the safest option.

**Comment by pippinsplugins** [comment]
Merge it in then! :)

**Comment by cklosowski** [comment]
Working on making sure my updates work, and that we've cleaned up when there are no payments, like we learned from the 2.2.6/7 instance ;)

**Comment by cklosowski** [comment]
Also, when I re-ran the tests here, I kept an eye on load and memory usage...Locally with 9500 payments, it didn't really even show a major increase to my resource utilization.

**Comment by cklosowski** [comment]
@pippinsplugins we good to close this one out?

**Comment by pippinsplugins** [comment]
Yep.

**Comment by pippinsplugins** [comment]
I'm re-opening this for some further discussion.

Previously, when a payment was created, the tax amount was stored in `_edd_payment_meta` with a key of `tax`. That was the original reason this issue was opened: it couldn't be queried on calculated against.

We have now moved the tax to it's own dedicated meta key called `_edd_payment_tax` and have removed it from `_edd_payment_meta`. The [upgrade routine](https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/release/2.3/includes/admin/upgrades/upgrade-functions.php#L779) we are running after 2.3 is installed goes through and removes the `tax` key from `_edd_payment_meta` and sets it as `_edd_payment_tax`.

We have updated `edd_get_payment_tax()` to use the meta new meta key but also has a fallback incase the meta is empty, causing it look in `_edd_payment_meta` for an old value:
```php
/**
 * Retrieves taxed amount for payment and then returns a non formatted amount
 *
 * @since 1.3.3
 * @param int $payment_id Payment ID
 * @param bool $payment_meta Get payment meta?
 * @return float $subtotal Subtotal for payment (non formatted)
 */
function edd_get_payment_tax( $payment_id = 0, $payment_meta = false ) {

	$tax = edd_get_payment_meta( $payment_id, '_edd_payment_tax', true );

	// We don't have tax as it's own meta and no meta was passed
	if ( false === $tax ) {

		if ( ! $payment_meta ) {
			$payment_meta = edd_get_payment_meta( $payment_id );
		}

		$tax = isset( $payment_meta['tax'] ) ? $payment_meta['tax'] : 0;

	}

	return apply_filters( 'edd_get_payment_tax', $tax, $payment_id );
}
```

There are a few issues here.

1. The fallback in `edd_get_payment_tax()` is kind of pointless since our upgrade routine goes through and deletes the key.

2. This will cause issues with any extension that is retrieving tax via `edd_get_payment_meta()`. We saw an instance of this this morning: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/commit/65588dc28a45e5162fe4230f3d6b1b4d2985dcf0#commitcomment-9866142

3. If an extension manually adjusts the `tax` key of `_edd_payment_meta`, EDD core will likely ignore it since we are now using a dedicated key. EDD Taxamo is an example of an extension that does this: https://github.com/rhyswynne/easy-digital-downloads-taxamo-integration/blob/master/taxamo-edd-integration.php#L459

**Comment by pippinsplugins** [comment]
For _1_, I'm proposing we not delete the existing meta data: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/release/2.3/includes/admin/upgrades/upgrade-functions.php#L832 - That way existing calls still work. In general I believe people are using the `edd_get_payment_tax()` helper function, and if they're not . . . that might be too bad.

**Comment by pippinsplugins** [comment]
Oh, one more point on this.

4. `edd_insert_payment()` must still support passing a single `tax` value in the purchase data. Right now it just sums the `tax` key in cart details. This is wrong:
```php
		$taxes     = $payment_data['cart_details'] ? wp_list_pluck( $payment_data['cart_details'], 'tax' ) : array();
		$cart_tax  = array_sum( $taxes );
		$cart_tax += edd_get_cart_fee_tax();
```

**Comment by JeroenSormani** [comment]
I'm all for this change, its definitely a improvement.
Leaving the `tax` key in the product meta is good for keeping backwards compatibility (code-wise).

**Comment by cklosowski** [comment]
@pippinsplugins @JeroenSormani, the problem with leaving the two, then lends us to the issue of...extensions (that we have confirmed) update the old tax key in the meta array...EDD's tax calculations will be done from `_edd_payment_tax` not the `tax` key of the `_edd_payment_meta` array, therefore any extension that is updating the taxes in the old place, will not be having their updated tax information pulled in yearly reports.

**Comment by cklosowski** [comment]
What if...we add a clause in `edd_update_payment_meta`, that pulls out the `$payment_meta['tax']` value and we be sure and update the `_edd_payment_tax` value as well?

**Comment by pippinsplugins** [comment]
@cklosowski I think we need to leave it and then just update retroactively if someone tries to update `_edd_payment_meta` directly. Could be messy, but we may just need to filter `update_post_meta` to detect it.

**Comment by cklosowski** [comment]
That's what i'm saying, when someone called `edd_update_payment_meta` with a `key` of `_edd_payment_meta` we pull the value of the `tax` key out of the array and update the `_edd_payment_tax` meta at the same time.

Since the function to get the tax is already pulling the updated meta...this should fix it?

**Comment by pippinsplugins** [comment]
I think we need to go further than just `edd_update_payment_meta()`. Not nearly enough people know that exists. There are undoubtedly extensions calling update_post_meta(). We will need to intercept those via the filters / actions in `update_metadata()`

**Comment by cklosowski** [comment]
@pippinsplugins ok, we can try that out. I'll write it up today.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by cklosowski** [comment]
Ok so we've updated it so that when either `_edd_payment_tax` or `_edd_payment_meta` is updated, we update the other option. That way we're not missing anything and we're compatible with any updates directly to the meta.

We're doing this on the `updated_postmeta` hook so even if someone updates payment meta using `update_post_meta` function instead of `edd_update_payment_meta` we'll catch it and make the necessary changes.

**Comment by pippinsplugins** [comment]
This should be ready to close out but I want to test it once more before doing that.

**Comment by pippinsplugins** [comment]
Works great!
