### ISSUE TITLE
Confirm that wp_session garbage collection is working correctly

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#2031]
It seems that the wp_session garbage collection isn't working correctly. I've seen numerous reports of sites having thousands and thousands, or millions even, rows in wp_options related to wp_session.

Every wp_session row _should_ expire and get automatically cleaned out via a cron job that runs twice a day. As far as I can tell, however, the cron is never firing.

**Comment by ghinaaltal** [comment]
hello guys,

please can anyone help me! 
I am the admin of a new website that is still new and have no post or news, the website is hosted on Linux, Ubuntu server. I noticed lately that the data base of the website is increasing rapidly day by day without performing any thing on the site..
and the wp_options table is full of this records:

_wp_session_expires_71d531600d0bdfdde3f08b1f580c5c7b
--
_wp_session_9998b4cdeb00519b1bced28c43702bef
_wp_session_expires_9998b4cdeb00519b1bced28c43702bef
_wp_session_ffe442604b947bb0893a03d3d7d70c73
_wp_session_41f9a4c1866351f75cef324c80014899
_wp_session_expires_ffe442604b947bb0893a03d3d7d70c73
_wp_session_expires_41f9a4c1866351f75cef324c80014899
_wp_session_9735cdb65c9e46c6a7e54ddefd76f0a7
_wp_session_expires_9735cdb65c9e46c6a7e54ddefd76f0a7
_wp_session_2530eafcd5d0790982c17f4d6c02500b
_wp_session_expires_2530eafcd5d0790982c17f4d6c02500b
_wp_session_590b5fca3e1b057511f5b0822edb969e
_wp_session_expires_590b5fca3e1b057511f5b0822edb969e
_wp_session_7b8d8eda21fe050e1067627a50c58571
_wp_session_expires_7b8d8eda21fe050e1067627a50c58571

how can I solved this issue, I highly appreciate any help there..
and please to show me in details how to solve it as am new in websites

**Comment by pippinsplugins** [comment]
@ghinaaltal you can use PHP sessions instead by adding this to your wp-config.php:
```
define( 'EDD_USE_PHP_SESSIONS', true );
```
The session rows should be automatically deleted each day when the expire. If that is not happening, please make sure your wp-cron is working properly.
