### ISSUE TITLE
Admin templates

### ISSUE THREAD

**Issue by elliott-stocks** [easydigitaldownloads/Easy-Digital-Downloads#2048]
I think it would be useful if we had more control over the admin templates.

Take the order details page for example, currently I'd have to add an action to each section if I wanted to change something. It would be easier if we could use the template (like we do with the checkout) and tweak it.

If I wanted to change the purchased files box and replace it with something completely different, is that possible with an action? I could add a new box but I'd have to hide the previous one (CSS?).

Something like -

`edd_get_template_part( 'admin', 'view-order-details' );`

Instead of -

`require_once EDD_PLUGIN_DIR . 'includes/admin/payments/view-order-details.php';`

Thoughts?

**Comment by pippinsplugins** [comment]
Unless others disagree, I'm going to propose `wontfix` on this.

**Comment by chriscct7** [comment]
I really don't like this idea. Its gonna cause a lot of support headaches for the users that use it and its something we can mitigate the need for with proper hooks

**Comment by chriscct7** [comment]
I vote close as proposed

**Comment by chriscct7** [comment]
Closing for lack of dissent, and lack of reason for this change. If reopening, please include an example usage.
