### ISSUE TITLE
Inconsistent file/folder names

### ISSUE THREAD

**Issue by elliott-stocks** [easydigitaldownloads/Easy-Digital-Downloads#2093]
I've noticed some file names are separated by underscores, but most have dashes.

A couple of examples -

`checkout_cart.php`
`EDD_SL_Plugin_Updater.php`

Also for custom templates the folder required is `edd_templates`. I think it's sometimes confusing and they should be consistent throughout. The WP standards state file names should use dashes - http://make.wordpress.org/core/handbook/coding-standards/php/#naming-conventions

I've noticed this within the style sheet too, such as -

`.edd-icon-remove`
`.edd-submit`
`#edd-payment-mode-wrap`

vs

`#edd_checkout_form_wrap`
`#edd_registration_form`

Usually classes/IDs use dashes not underscores.

**Comment by cklosowski** [comment]
Yes, btw, we should ALWAYS use ```-``` in CSS/HTML classes and attributes, never ```_```. jQuery can't parse data elements with ```_``` in the attribute name.

**Comment by pippinsplugins** [comment]
I did not know that.

**Comment by pippinsplugins** [comment]
I think we need to close this because we're not going to change any existing files, classes, or IDs for backwards compatibility. Going forward, however, we need to ensure we're maintaining consistency.
