### ISSUE TITLE
i18n PDF Exports contain ? instead of diacritic chars

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#2110]
As reported in https://easydigitaldownloads.com/support/topic/problem-with-polish-diacritics/

I was able to replicate on my local install.
http://cl.ly/image/0w1G1e213U0C

**Comment by sunnyratilal** [comment]
Going to go ahead and close this issue as PDF exports are being removed in 2.7 as per #1808
