### ISSUE TITLE
ReferenceError: inlineEditPost is not defined

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/Easy-Digital-Downloads#2163]
It seems that when SCRIPT_DEBUG is set to false, there's a JS error when clicking `Quick Edit` on the categories screen, and also other taxonomies.

ReferenceError: inlineEditPost is not defined

..."#edd_payment_status option:selected").val()=="publish"){e("#edd_payment_notific...

https://cloudup.com/c1iHpluvy80

EDD 1.9.8

JS Error:
`define('SCRIPT_DEBUG', false);`

No JS error:
`define('SCRIPT_DEBUG', true);`

**Comment by zanematthew** [comment]
I noticed the same issue, and was able to reproduce it, using the latest EDD, latest WP, script debug true/false (didn't seem to matter in my case), however I do have wp installed in its own directory, and I'm on WordPress Networking.

I've submitted a pull request, this does address the JS error, BUT once the user clicks "cancel" the row that was being edited is actually removed. My initial thoughts is that it could be the [implementation of the edit inline js](https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/assets/js/admin-scripts.js#L997).

I can look into this deeper at a later point in time, just wanted to bring it to everyone's attention.

**Comment by zanematthew** [comment]
Maybe worth re-opening?

**Comment by chriscct7** [comment]
What page were you on when you replicated this?

**Comment by zanematthew** [comment]
I was on: `wp-admin/edit-tags.php?taxonomy=download_category&post_type=download`

Also notice the quick edit doesn't work either here: `wp-admin/edit.php?post_type=download`
