### ISSUE TITLE
UTF issue with serialized data

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#2168]
It seems that UTF characters are causing serialization to break: https://easydigitaldownloads.com/support/topic/purchase-editing-bug-possibly-utf8-related/

**Comment by ghost1227** [comment]
@pippinsplugins where does the patch need to be applied?

**Comment by pippinsplugins** [comment]
The payment meta that we currently serialize.

**Comment by pippinsplugins** [comment]
Note: this might be fixed with the multibyte changes made in WP 4.2.

**Comment by cklosowski** [comment]
@pippinsplugins do we have someone who can verify? I never replicated this.

**Comment by pippinsplugins** [comment]
@cklosowski Only person we know of is the original poster of that forum thread.

**Comment by pippinsplugins** [comment]
I propose we punt this until we have another reliable report that will let us track it down.

**Comment by pippinsplugins** [comment]
Closing as invalid as we have never seen another report of this.
