### ISSUE TITLE
Improve query performance of EDD_API->get_user()

### ISSUE THREAD

**Issue by danielbachhuber** [easydigitaldownloads/Easy-Digital-Downloads#2192]
A neat hack: instead of storing the API key as the `meta_value`, store it as the `meta_key` so you can leverage WordPress' index on that column.

Implementing this would require an upgrade procedure and/or backwards compat fallback.

**Comment by cklosowski** [comment]
@ghost1227 I believe @pippinsplugins is thinking of getting ALL api keys, instead of one for a specific user, as getting it via PHP at that point would be faster than querying for a specific row based off meta_value? Am I right?

**Comment by pippinsplugins** [comment]
Correct.

**Comment by pippinsplugins** [comment]
@cklosowski Actually no, sorry, that's not correct. We need to change where we store API keys.

Instead of storing the key in `meta_value`, Daniel was suggesting storing them in the `meta_key` field.

When looking for a user that belongs to the API key, we look for a row where the `meta_key` matches the API key. Since `meta_key` has an index, it's much faster.

**Comment by cklosowski** [comment]
Ok, shouldn't be too bad of an update.

**Comment by cklosowski** [comment]
As @pippinsplugins states in our meeting, we should find a way to be backwards compat to the lookups if someone hasn't run the upgrade routine.

**Comment by pippinsplugins** [comment]
@cklosowski I just tested this again and it appears to have regenerated my API keys when running the upgrade. Was that intentional?

**Comment by cklosowski** [comment]
No it should have just copied it over. They didn't regenerate on my end.

**Comment by cklosowski** [comment]
i'll test this our shortly.

**Comment by cklosowski** [comment]
Not seeing this behavior, can someone else test it out @mindctrl @ghost1227 @chriscct7. See if this branch, when the upgrade routine runs, regenerates your keys?

1) checkout this branch
2) Go to your Profile and take note of your keys in notepad or something
3) run the Upgrade routine
4) Go back to your profile and take note of your keys
5) Verify keys are the same
6) ...
7) Profit?

**Comment by pippinsplugins** [comment]
@cklosowski it works properly for me now. Could you set the upgrade routine to complete after it runs? We don't want people seeing the notice.

**Comment by cklosowski** [comment]
It does: `edd_set_upgrade_complete( 'upgrade_user_api_keys' );`

We just haven't bumped versions yet, so it'll fail on that check

**Comment by pippinsplugins** [comment]
I don't think it should show the notice at all if the upgrade is complete,
regardless of the version.

**Comment by cklosowski** [comment]
We tried that last time, lead to issues, we put the `||` logic in because notices were disappearing...remember? Had to hotfix even same day

**Comment by mindctrl** [comment]
@cklosowski upgrade worked right. Keys were same before and after.

**Comment by cklosowski** [comment]
I think we still need to get the lookup working for people that haven't upgraded too. Will get that in today

**Comment by cklosowski** [comment]
Ok, API is now checking to see if the user has run the upgrade routine, and if not, it does the lookup the old way, otherwise looks up via the new method.

**Comment by pippinsplugins** [comment]
:+1:
