### ISSUE TITLE
Add Quantities to Fees

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/Easy-Digital-Downloads#2288]
Per #2283 we should allow fees to have quantities. There's alot of good reasons a fee should have quantity. Lets say I charge a handling fee. If I charge it per item, then I want my fee of $2, to be equal to $2 \* the number of items in cart. By default, fees should have a quantity of one.

**Comment by pippinsplugins** [comment]
This isn't going to happen for 2.3. There hasn't been enough demand for this to make it a priority.

**Comment by sunnyratilal** [comment]
@pippinsplugins @cklosowski What are your thoughts regarding this? Is this still something we'd like to pursue?
