### ISSUE TITLE
Date field on payments should be locale-agnostic

### ISSUE THREAD

**Issue by leewillis77** [easydigitaldownloads/easy-digital-downloads#2290]
Currently on the payment screen, the date of the payment is shown in the format "m/d/Y". This isn't the "normal" format in the UK (At least). E.g. the date in the screenshot below would normally be shown as 29/12/2013, not 12/29/2013 in the UK.

![update-payment-box](https://cloud.githubusercontent.com/assets/1097338/2977476/e6d6eaea-dbab-11e3-86b2-80caf0d35b16.png)

If that can't be properly localised (Does WP have a localised "short-date" format we can grab?), I think it should be shown in something that is less locale-specific, e.g. 'd M Y', e.g. 1 Feb 2014 which should avoid any confusion.

Obviously it's not just as straightforward as changing the format since dates can be entered into that field as well.

**Comment by pippinsplugins** [comment]
It's three years later and this has not popped up again so I'm closing as wontfix.
