### ISSUE TITLE
Introduce standard classes for errors, notices, etc

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/Easy-Digital-Downloads#2322]
We should take a hard look at our CSS and find ways to combine, reduce, and improve our CSS.

One thing that immediately comes to mind is I know we have a success (and I believe a fail) but a notice and info class should also be there, even if we dont use it, to help standardize extension notices.

**Comment by pippinsplugins** [comment]
Line breaks opened as a separate issue: #2322

This issue is now focused on just standardized classes.

**Comment by cklosowski** [comment]
As it stands we only use `.edd_error` and `.edd_success` 3 times, total ( 1 error and 2 success ). I'd say we're at a pretty low risk to rework these completley, starting with the fact that we used `_` in the class name when it should be `-`, as well as making them a bit cleaner.

I'm going to take some hints from the bootstrap notices to see if we can make this a bit more universal and repeatable:
![image](https://cloud.githubusercontent.com/assets/1390124/8193639/15ca7f70-142b-11e5-9a10-f5f04204de55.png)

**Comment by pippinsplugins** [comment]
I like those. If we do this, we should update the checkout errors to match.

**Comment by pippinsplugins** [comment]
note: we cannot change the class names on any existing error messages or notice, only add to them.

**Comment by cklosowski** [comment]
@pippinsplugins I'll leave the old incorrectly formatted classes in... but our styles will all be on the new ones. Poeple will just ahve to udpat eto get the new ones.

**Comment by cklosowski** [comment]
![image](https://cloud.githubusercontent.com/assets/1390124/8194724/51b5f940-1432-11e5-9e12-195a0009e925.png)
![image](https://cloud.githubusercontent.com/assets/1390124/8194732/5d10045c-1432-11e5-9f35-a94419a3033e.png)
![image](https://cloud.githubusercontent.com/assets/1390124/8194751/7ffb2014-1432-11e5-84b7-a008538ad068.png)

**Comment by cklosowski** [comment]
We've got a slight conflict in that we assign the `edd-success` class to the success page, so our success class will need to be something like `edd-confirm`

**Comment by pippinsplugins** [comment]
That's annoying

**Comment by cklosowski** [comment]
@pippinsplugins Yes, to avoid it, our notice classes are scoped to work on a `div` or `span`

**Comment by pippinsplugins** [comment]
@cklosowski see my comments on the comments. No existing classes can be removed.

**Comment by pippinsplugins** [comment]
@cklosowski If we remove the existing classes, we break everyone's sites who have styled based off of those classes. I'm sorry but that's not acceptable, not unless we can confirm that none of the popular themes are affected.

**Comment by cklosowski** [comment]
Then we cannot move foward with standarizing our notices. I'll close the issue

**Comment by cklosowski** [comment]
We'll have to stage this then, this release will add the new classes `edd-alert` is the primary and `edd-error`, `edd-success`, `edd-info`, `edd-warn` to the HTML elements. The old class (`edd_errors` and `edd_success`) will be left on it. The Styles themselves will be removed from the `edd.css` file.

**Comment by spencerfinnell** [comment]
Might make more sense moving forward to use:

`"edd_errors edd-alert edd-alert-error"`

To avoid future conflicts like `edd_success` -- or even more trendy CSS naming"

`"edd_errors edd-alert edd-alert--error"`

Adding

```css
div.edd-alert,
span.edd-alert
```

Is just asking for trouble. That's just twice as many things that have to be overwritten in a theme or plugin. If you prefix with `-alert` there shouldn't be a need to be that specific.

**Comment by pippinsplugins** [comment]
I like that @spencerfinnell

**Comment by cklosowski** [comment]
Will fix that once I'm online.

**Comment by cklosowski** [comment]
Updated, no more `div.` or `span.` and including `-alert` in the specific styles.

**Comment by pippinsplugins** [comment]
@cklosowski Can do you this test for me?

1. Checkout master
2. Copy edd.css to your theme folder
3. Checkout issue/2322
4. Confirm all notice / error styles still match the previous styles

**Comment by cklosowski** [comment]
In a few, onto another issue for 2.4, then I'll try it out.

**Comment by cklosowski** [comment]
Ok pulled the `edd.css` file from master, dropped it into my theme, then checked out `issue/2322` and these were the results:
![image](https://cloud.githubusercontent.com/assets/1390124/8220370/e57a52e6-1506-11e5-9af3-ca39c382e2fc.png)

![image](https://cloud.githubusercontent.com/assets/1390124/8220371/e9407bda-1506-11e5-98a9-04e4874f1bfb.png)

This was an odd one, not sure why, but I have all the proper classes on it... but it's pretty minor:
![image](https://cloud.githubusercontent.com/assets/1390124/8220378/fccdddc8-1506-11e5-9b58-7606050c5737.png)

**Comment by pippinsplugins** [comment]
Great, merging.

**Comment by chriscct7** [comment]
This change breaks the formatting of error messages for at least the following EDD extensions that we host, because of the removed p styling:
- Amazon s3
- Dropbox
- Checkout Fields Manager
- Frontend Submissions
- Balanced Gateway
- Stripe
- WePay
- Software Licensing
- Custom Prices

Chris K is working on a backwards compat fix. I'll update CFM and FES to use the new error message styles anyways. 

It would be great if the old styles could just be overriden by the new ones using precedent, that way people who write new extensions can just use like `edd-alert edd-alert-error edd_error` as their classes so that way if the user has new EDD install the new styling is used, else use the old styling. Would save extension authors the headache of dealing with backward compat.

**Comment by chriscct7** [comment]
This also by the way breaks shortcode-receipt.php from the look of it (untested)

**Comment by chriscct7** [comment]
Also appears to break edd_print_errors(), even in release/2.4 branch:
```
 // Loop error codes and display errors
		   foreach ( $errors as $error_id => $error ) {
		        echo '<p class="edd_error" id="edd_error_' . $error_id . '"><strong>' . __( 'Error', 'edd' ) . '</strong>: ' . $error . '</p>';
		   }
```

**Comment by chriscct7** [comment]
@cklosowski as for the earlier issue with the discount invalid not having formatting, you need to adjust: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/release/2.4/assets/js/edd-checkout-global.js#L191

**Comment by cklosowski** [comment]
Spoke with @chriscct7 and Here's what I've come up with a solution to allow backwards compat with no affects to the new styles:
![image](https://cloud.githubusercontent.com/assets/1390124/8225002/1f2c0b50-1544-11e5-9956-758471a0fd33.png)

Applying a `:not(.edd-alert)` to the `.edd_errors` and `.edd_success` styles (the old ones) means that old and new styles can co-exist in harmony for now.

**Comment by spencerfinnell** [comment]
Looks like a solid solution to me. :+1:

**Comment by pippinsplugins** [comment]
@chriscct7 Thank you for noticing all of the extensions that we missed.

@cklosowski looks good to me. I'm going to test more now to confirm.

**Comment by pippinsplugins** [comment]
Everything looks good here :+1:
