### ISSUE TITLE
loading admin styles/scripts only when necessary

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#2364]
As per this ticket https://easydigitaldownloads.com/support/topic/admin-scripts-not-enqueued-to-custom-post-type/#post-255502 It wouldn't hurt to check and see if any of this could be tightened up.

**Comment by JJJ** [comment]
I'm going to work _a little bit_ on this, specifically #3033.

Self-assigned this for now. Will work on a PR for #3033 to come up with some patterns.

**Comment by sunnyratilal** [comment]
Closing as this was implemented as part of #3033.
