### ISSUE TITLE
Bulk deleting on payments screen appends referrer causing request error (core bug)

### ISSUE THREAD

**Issue by ghost1227** [easydigitaldownloads/easy-digital-downloads#2387]
So a user just pointed out a fairly nifty bug on the Payments History screen... if you bulk delete a page, then another, then another.... the URL continuously appends the referrer... while KEEPING the original referrer query string. This quickly results in a URL that is too long for many servers to process.

**Comment by cklosowski** [comment]
Looks like there is a core patch that was submitted 3 months ago:
https://core.trac.wordpress.org/ticket/10762#comment:21

It might address this issue.

**Comment by cklosowski** [comment]
In an effort to get this on our radar, and if we can supply a fix for core, I am milestoning this for us to look at again.

**Comment by cklosowski** [comment]
There has been progress on the core fix, which includes a patch that might work. If we can get someone to test out the core issue, and once we put some eyes on the core issue, close this out.

**Comment by cklosowski** [comment]
As this is a long standing core issue that hasn't gotten any traction, and we've introduced tools to help clean up stores faster (reset store feature), I think we should just close this.

If it comes up, people can search the issues and find this as a reference.
