### ISSUE TITLE
EDD standards update: HTML_Elements implementation

### ISSUE THREAD

**Issue by ghost1227** [easydigitaldownloads/Easy-Digital-Downloads#2428]
Per #2427, we need to (at some point) standardize the usage of the HTML_Elements class introduced in 1.5. Much of EDD core doesn't implement it, and our codebase could be significantly cleaned up through proper utilization of the helper functions and classes we already provide. Additionally, as referenced in #1907, the HTML_Elements class still needs to be updated a bit...

**Comment by pippinsplugins** [comment]
Closing as too generic. Would love to see more of this happen but please open area-specific issues.
