### ISSUE TITLE
EDD standards update: settings calls

### ISSUE THREAD

**Issue by ghost1227** [easydigitaldownloads/Easy-Digital-Downloads#2429]
Per #2427, we need to (at some point) standardize the usage of the `edd_get_option()` function introduced in 1.8.4. We are expecting third-party developers to use it, but much of EDD core still uses the $edd_options global and inline conditional checks. Cleaning this up can only help the plugin overall.

**Comment by ghost1227** [comment]
@pippinsplugins what's the status on this?

**Comment by pippinsplugins** [comment]
#2872 is getting included in `release/2.3` and then #3011 will be 2.4.

**Comment by cklosowski** [comment]
@pippinsplugins It's been updated, looking over it, the change set here is super minor now that the other issue has been merged. Can you look at #3011 and see if we want it in 2.3?

**Comment by pippinsplugins** [comment]
Let's go ahead and just put it in 2.3. Will encourage us to get it done and done.
