### ISSUE TITLE
Non-strict comparisons for show_register_form can cause duplicated Personal Info sections

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#2442]
We have had several reports of the `Personal Info` section getting displayed twice on the checkout screen. I tracked it down to an issue with the `Product Support` extension (possibly among others).

In the `Product Support` extension, Web Dev Studios does this:

``` php
// Require user account for checkout
$edd_options['logged_in_only']      = true;
$edd_options['show_register_form']  = true;
```

Since we changed the options for the registration form around in EDD 2.0, #2174, setting `show_register_form` to `true` isn't technically the correct way to do it anymore, but shouldn't hurt anything either.

This, however, results in the duplicated `Personal Info` section because we are not doing string type comparisons when checking what the `show_register_form` option is set to:

``` php
        do_action( 'edd_purchase_form_before_register_login' );

        $show_register_form = edd_get_option( 'show_register_form', 'none' ) ;
        if( ( $show_register_form == 'registration' || ( $show_register_form == 'both' && ! isset( $_GET['login'] ) ) ) && ! is_user_logged_in() ) : ?>
            <div id="edd_checkout_login_register">
                <?php do_action( 'edd_purchase_form_register_fields' ); ?>
            </div>
        <?php elseif( ( $show_register_form == 'login' || ( $show_register_form == 'both' && isset( $_GET['login'] ) ) ) && ! is_user_logged_in() ) : ?>
            <div id="edd_checkout_login_register">
                <?php do_action( 'edd_purchase_form_login_fields' ); ?>
            </div>
        <?php endif; ?>

        <?php if( ( !isset( $_GET['login'] ) && is_user_logged_in() ) || ! isset( $edd_options['show_register_form'] ) || 'none' == $show_register_form ) {
            do_action( 'edd_purchase_form_after_user_info' );
        }

        do_action( 'edd_purchase_form_before_cc_form' );
```

This makes both `edd_purchase_form_register_fields` and `edd_purchase_form_after_user_info` actions fire, since the `true` boolean value validates as truthful when doing this `$show_register_form == 'registration'` and `'none' == $show_register_form`.

**Comment by tw2113** [comment]
Funnily enough, I was bitten by this exact issue tonight with that `$edd_options['show_register_form'] = true` bit from our plugin. However, due to the strict type checking added, we had NO forms showing up. I believe it didn't show up for us earlier, because the site had not updated itself lately, and just now did this week. Hoping to get a proper fix in for it.

**Comment by pippinsplugins** [comment]
@tw2113 In the support plugin? I actually fixed that for you guys and released an update several months ago (pinged the trello card numerous times with no answer so just did it).

**Comment by tw2113** [comment]
Yeah in the support plugin. I went to the trello card as well, don't recall getting any email notifs about this specific issue. Perhaps it was before I was set to? *shrug* anyways, I have 2.0.4 in our repo for it updated with changes from EDD staff and a couple bits from me, if we want to do another point release.

**Comment by pippinsplugins** [comment]
@tw2113 see Trello now. Apparently I got mixed up and missed your comments :(

**Comment by tw2113** [comment]
It happens. Will try to follow the notes provided today. Thanks Pippin.
