### ISSUE TITLE
Disable WP_Session start when not needed

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#2466]
It occurred to me today that we are setting up the WP_Session instance on `init`, which means sessions are loaded when loading feeds (RSS, Atom, etc) as well.

There's no reason sessions are needed during feed displays so we can save a bit of performances by disabling them when in a feed.

**Comment by cklosowski** [comment]
@pippinsplugins we did this in #4429, do we still need this one open?
