### ISSUE TITLE
Taxes differ on checkout and purchase confirmation

### ISSUE THREAD

**Issue by elliott-stocks** [easydigitaldownloads/Easy-Digital-Downloads#2473]
The taxes on the checkout page are calculated different to the purchase confirmation/invoices.

Testing with the latest dev build from Github, taxes are 20%.

For example (Product costs £430) -

Sub Total:  £430.00
Shipping:   £8.82
Taxes:       £87.76
Total:         £526.58

However the purchase confirmation and everything else after the purchase shows -

Subtotal:    £440.58
Shipping:   £8.82
Taxes:       £86.00
Total:         £526.58

It looks like taxes are being applied to fees (shipping) and then added to the subtotal. But on checkout the fees are added to the subtotal and then taxes are calculated.

The product also shows with taxes on the purchase confirmation, when it should be without (depending on the settings).

The tax should be calculated on the product + fees, so in this case the purchase confirmation is correct.

**Comment by pippinsplugins** [comment]
@cklosowski I'd like you to test this as well.

**Comment by cklosowski** [comment]
This seems to work much better for me, nice catch @elliott-stocks
