### ISSUE TITLE
Postal code validation for Argentina failes

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#2476]
Postal code validation for Argentina always fails due to the regex being incorrect in `edd_purchase_form_validate_cc_zip()`.

Reported and confirmed here: https://easydigitaldownloads.com/support/topic/checkout-error-the-zip-code-you-entered-for-your-credit-card-is-invalid

**Comment by lucasverra** [comment]
@cklosowski 2,5 yrs later, this is useful , TY
