### ISSUE TITLE
Register all of our meta keys with register_meta()

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#2480]
We need to do this.

**Comment by pippinsplugins** [comment]
This needs to happen for the WP REST API.

**Comment by cklosowski** [comment]
some of our meta is not registrable as it contains an ID related to the data it's stored for, but I'll work on getting the ones available registered.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by chriscct7** [comment]
> This needs to happen for the WP REST API.

Just want to point out that while using register_meta is a good idea, it does not affect the REST API at all. The REST API does not use the register_meta API, and requires register_api_field pending https://github.com/WP-API/WP-API/issues/1425

**Comment by cklosowski** [comment]
Thanks Chris. Good point. I still think we should move forward. The sanitization functions alone are a good side affect of this issue.

**Comment by cklosowski** [comment]
@pippinsplugins @chriscct7 you guys good with these callbacks I'm using on the meta, and with the two methods I've built into the class? The `intval` was an interesting one, without a wrapper it spits an error about the number of arguments not being met.

**Comment by cklosowski** [comment]
Ok, I've moved all but the bundle sanitization function from `metabox.php`. This one has to stay as it requires knowing the Post Id being updated, which the sanitization function doesn't pass through, so it can remove itself from the array of bundles if it's in there.

Other than that, all these are now ready to sanitize whenever an extension or core tries to modify this data.

**Comment by cklosowski** [comment]
@pippinsplugins take a look over those changes and let me know what you think.

**Comment by pippinsplugins** [comment]
Left a few comments on the PR for you.

**Comment by pippinsplugins** [comment]
This is breaking the ordering of files introduced in https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/3760

**Comment by pippinsplugins** [comment]
When saving, the order is kept but the ID shown is incorrect.

**Comment by pippinsplugins** [comment]
Fixed.

**Comment by pippinsplugins** [comment]
Two left overs that I'm not sure were missed or intentionally left.

1. `edd_metabox_save_check_blank_rows()` is not used and is now duplicated in `EDD_Register_Meta`
2. `edd_sanitize_bundled_products_save()` is still in metabox.php. Is this due to needing a post ID? We should still use the global so I don't see any reason it should be left behind.

**Comment by cklosowski** [comment]
1. Was intentially left in, in case someone else is using it in their meta box repeatable rows.

**Comment by cklosowski** [comment]
2. You cannot guarantee that the call to `update_post_meta` will be called while a post is in `global`, since this is called any time update_post_meta is called for this meta key, so relying on a global `$post` won't work.

**Comment by pippinsplugins** [comment]
1. Good idea.

2. Good point. Let's leave it.

**Comment by pippinsplugins** [comment]
Merged into `release/2.5`
