### ISSUE TITLE
My host installed PHP 5.4 in Apache 2.4 as FastCGI, so no apache_get_modules() available, so how can I use xsendfile in EDD anymore?

### ISSUE THREAD

**Issue by parcolee** [easydigitaldownloads/easy-digital-downloads#2487]
I’ve just had a look on some of your source codes in github, I’ve found that you detect the X-sendfile function with apache_get_modules().
 But there would be a big headache for me. The webhosting service I’m using now run PHP as CGI/FastCGI and not as an Apache API, so apache_get_modules() never work, no modules would be detected, even if I’ve x-sendfile module installed inside.

And also apache_get_modules() does not always work.
 Even after X-sendfile module has been installed, you would still have to enable X-sendfile in httpd.conf or .htaccess manually before you really can use it.
 But before you enable X-sendfile in httpd.conf or .htaccess (x-sendfile is still off), you would still can get ‘mod_xsendfile’ by apache_get_modules() even if you have installed the module but not enabled yet.
 So according to your codes, if you detect for the x-sendfile function by this way, in this case you may get some errors.

So apache_get_modules() is NOT SO RELIABLE in the most cases.
 just like my own case, x-sendfile installed and enabled, but no apache_get_modules() functions can be used caused by CGI PHP, so you have to still force me to use chunk reading by PHP and avoid me to use my own usable X-sendfile?
 Why don’t you just let use to choose forced download or x-sendfile with a drop down list in the EDD-settings page like what woocommerce is doing right now?

And can you add a disposable link function that one link only can be downloaded once and would be disabled immediately after downloaded once? I’m not meaning every customer order can be only downloaded once, but everytime when they want to download again, everytime give them a new generated link for them to download again, and old link can’t be download again.

And it’s beter to let us adjust the chunk size in chunk forced download mode too. My server gives me 150MB RAM for every PHP individual page load request. So don’t waste the memory and let us adjust to 10MB or even 50MB per chunk, to reduce reading overheads, reduce interval latency between chunks and also increase the bandwidth usage performance.

**Comment by pippinsplugins** [comment]
Closing as wontfix as we haven't seen anything related to this in nearly two years.
