### ISSUE TITLE
Reflect front-end tax settings in Downloads Cart widget

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/Easy-Digital-Downloads#2506]
Currently, the EDD tax settings allow you to "Display Tax Rate on Prices" which will output the price of an item with additional tax information near the button.

**When the tax amount is exclusive, this is not an issue.**

When the tax amount is inclusive, the purchase buttons will display that total amount including tax and output a notice saying that tax is included. However, on the Downloads Cart widget, the item price will display without the tax included. Example screenshot: http://glui.me/?i=s1nlwc9dbg0dbrc/2014-08-07_at_7.45_PM.png/ 

That item has been added to the cart. The top custom widget is its default purchase button while the second widget is the Downloads Cart widget. I'm proposing that the widget reflect tax settings when inclusive of tax.

Related ticket: https://easydigitaldownloads.com/support/topic/cart-widget-display-price-including-tax/

**Comment by cklosowski** [comment]
@sdavis2702 Can you look over this and see if your initial issues are still present?

**Comment by cklosowski** [comment]
What if our checkout widget looked something more like this when taxes were enabled?
![image](https://cloud.githubusercontent.com/assets/1390124/8145169/2d8bc9dc-11b2-11e5-9a8c-237607800368.png)

**Comment by pippinsplugins** [comment]
:+1:

**Comment by cklosowski** [comment]
Ok. There are some markup changes here. Will try and avoid breaking changes. But it's organized very poorly as all list items in a single UL.

**Comment by cklosowski** [comment]
Currently the cart widget shows a 'Subtotal' line. In reality, total makes more sense when no taxes are enabled.

After looking at this I think this logic should be in place:
1) If taxes are disabled
    Show the Total: line
2) If taxes are enabled
    Show Subtotal
    Show Taxes
    Show Total

**Comment by pippinsplugins** [comment]
I wonder if we will run into issues here where users get confused because it shows a certain tax amount but the tax amount is wrong. The tax amount won't usually be correct until the user reaches the checkout and enters their billing address.

**Comment by pippinsplugins** [comment]
Tax amount isn't updating with ajax properly.

**Comment by pippinsplugins** [comment]
The total and subtotal aren't updating either.

**Comment by cklosowski** [comment]
Ok, ajax should be working correctly, with all items updating correctly.

**Comment by pippinsplugins** [comment]
@cklosowski Looks like your CSS is affecting the checkout too:
![screen shot 2015-06-22 at 2 37 17 pm](https://cloud.githubusercontent.com/assets/1034109/8290993/3d6c7f7c-18ec-11e5-8ab7-01a94021af40.png)

**Comment by cklosowski** [comment]
Odd. Ok. Just need to target a little closer. Easy fix

**Comment by cklosowski** [comment]
Here is the view in Vendd btw Just so we know we're not conflicting too much. No changes have been made in Vendd to accommodate this markup change (yet).

![screen shot 2015-06-23 at 2 40 54 pm](https://cloud.githubusercontent.com/assets/1390124/8317956/f6fcc130-19b5-11e5-9419-40afc99154d9.png)

**Comment by cklosowski** [comment]
Just needs a little more testing, would love @SDavisMedia and @mindctrl to take a look at this. Sean this should fix that remove issue we saw when messing with Vendd prior to release.

**Comment by pippinsplugins** [comment]
This looks great to me.

**Comment by mindctrl** [comment]
Looks good here.

**Comment by SDavisMedia** [comment]
Works for perfectly for me. Looks like it killed some Vendd styling, though. So sad face. :+1:

**Comment by pippinsplugins** [comment]
Can you show us?

**Comment by SDavisMedia** [comment]
Looking to see exactly what happened now. Update shortly.

**Comment by SDavisMedia** [comment]
Alright it's three hiccups in the display:

1. The little arrows on the left of the line items shouldn't be there (they're there because no that HTML didn't exist before, so there was no CSS to remove them like I did for the other elements).

2. The new CSS is so aggressive that it overrides Vendd's widget li padding.

3. The subtotal should not be green anymore if that's not the final price. Before, it was actually the final price... which was flawed to begin with.

**The fix for all three needs to happen in Vendd. I'll make the necessary tweaks to go with the update.**

![screen shot 2015-06-29 at 9 03 13 pm](https://cloud.githubusercontent.com/assets/2359131/8422557/cdba22bc-1ea2-11e5-98a6-c3d4d8438879.png)

**Comment by SDavisMedia** [comment]
@cklosowski Here's the double class selector deal we talked about in Slack: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/release/2.4/templates/edd.css#L967

And removing on of those will actually give the line item's their padding back that's applied in Vendd (how the double class selector is even valid is beyond me). With that fixed, Vendd's display is not in bad shape at all. The little gray arrows are _that_ out of place. :+1:
