### ISSUE TITLE
Support for withholding / retention taxes

### ISSUE THREAD

**Issue by samuelaguilera** [easydigitaldownloads/easy-digital-downloads#2524]
Coming from [here](https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/2347#issuecomment-52894066) as suggested by @RaceRay

Taxes support in EDD could be greatly improved by adding support for [withholding/retention taxes] (http://en.wikipedia.org/wiki/Withholding_tax).

What are retention taxes?

Definition from spanish tax agency:

>Amounts of money that are subtracted from certain income by the party that pays a taxpayer. This practice is carried out in accordance with the provisions of the law, and the money is deposited with the Tax Agency as an on-account or "advance payment" against the tax that the taxpayer is required to pay.

In practice, a retention tax is a kind of tax that a person must apply when invoicing for services charged to a company. For example, if you want to charge for support or maintenance to a company, you're required by taxes law to apply this retention tax in your services invoices.

**The retention tax is only applied when the vendor is a physical person (not a company), the product is a service (support, maintenance, ...) and the customer is a company.**

All of this applies to Spain, and I think it should be the same o very close in all other EU countries, but honestly I don't know.

## Practical example of selling a service including discount and retention tax:

$100 Product price
-$10 Product discount
$90 Subtotal

Now you must apply for example 10% of retention tax named IRPF and 20% of VAT, this way:

-$9 10% IRPF retention (this is calculated over $90)
$18 20% VAT (this is calculated over $90 too)

$99 Total to pay

So the customer will ended paying $99 to the vendor, and $9 (in the name of the vendor) to the tax agency.

If you need any other detail about this, don't hesitate to ask me :)

**Comment by pippinsplugins** [comment]
I'm going to close this as wontfix. To my knowledge, this is the only request we've ever had for it and, considering how complicated adding new tax rates can be, there is not enough demand to warrant building this into core at this time.
