### ISSUE TITLE
Random AJAX content displayed during database upgrades

### ISSUE THREAD

**Issue by leewillis77** [easydigitaldownloads/Easy-Digital-Downloads#2577]
When I run the database upgrades after upgrading to EDD 2.1 every time the page refreshes I get a chunk of random code displayed, samples attached.
![screenshot from 2014-09-04 21 09 12](https://cloud.githubusercontent.com/assets/1097338/4156009/e7fa1cf4-346f-11e4-8a32-58f19a662c9c.png)
![screenshot from 2014-09-04 21 09 38](https://cloud.githubusercontent.com/assets/1097338/4156011/e8013bb0-346f-11e4-8ec5-26f37dfe689e.png)
![screenshot from 2014-09-04 21 11 41](https://cloud.githubusercontent.com/assets/1097338/4156010/e7fefea4-346f-11e4-97ce-cd9b106dd076.png)

**Comment by ghorbani77** [comment]
Easy Digital Downloads needs to complete a database upgrade that was previously started, click here to resume the upgrade.

**Comment by pippinsplugins** [comment]
@ghorbani77 Restart it and it should complete fine.

**Comment by enowtech** [comment]
> @ghorbani77 Restart it and it should complete fine.

Please how do one restart it?

Easy Digital Downloads needs to complete a database upgrade that was previously started, click here to resume the upgrade.

Each time I click on it, it just reloads to dashboard with same message still there.
