### ISSUE TITLE
WPML Compatibility

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#2597]
While EDD and WPML are partially compatible, we need to get them to be 100% compatible.

This is just a container issue to hold all commits / discussion about improved WPML compatibility.

Please link any support tickets that come in below.

**Comment by danieliser** [comment]
Can the language be set in a session / cookie? Thought that WPML already did this.

**Comment by pippinsplugins** [comment]
I'm pretty sure that is how they do it.

**Comment by pippinsplugins** [comment]
WPML recently released a new version of their bridge plugin that improved compatibility. Closing as fixed. We can reopen specific issues if we hear about them.

**Comment by endcore** [comment]
EDD 2.7
WPML 3.6.3
WPML EDD 1.2.2

Hi pippin,

sorry, the bug still exists. 

I fixed this temporarly by adding a "lang" Parameter to the recalculate_taxes ajax request in this file: edd-checkout-global.min.js

Please fix this for an upcoming version.

Thanks!
