### ISSUE TITLE
Item Amount is wrong on Reports->Logs page

### ISSUE THREAD

**Issue by slaFFik** [easydigitaldownloads/Easy-Digital-Downloads#2617]
That column in a table, when I have selected Sales filter, displays $0 for products that were bought using different checkout gateways (paypal and 2CO).
But what is more important, that `0` is not for all records. Some of them (for the same product) have the correct value in that column - that main price or so called "variables".

Using downloads variable pricing option, EDD 2.1.3, WP 4.0.

**Comment by slaFFik** [comment]
Still having this issue - for payments via 2CO. Paypal is ok. Not for old payments, but for new ones, like end of December

**Comment by pippinsplugins** [comment]
@cklosowski can you see any reason this would happen? I'm stumped.
