### ISSUE TITLE
Session cleanup SQL errors

### ISSUE THREAD

**Issue by elliott-stocks** [easydigitaldownloads/Easy-Digital-Downloads#2622]
I'm getting quite a lot of SQL errors in my logs due to the WP session cleanup.

`[17-Sep-2014 04:40:48 UTC] WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '_wp_session_-1'','_wp_session_expires_a6642455c0c83b5171cc6f6df24039d9','_wp_ses' at line 1 for query`

``` SQL
DELETE FROM om_options WHERE option_name IN ('_wp_session_expires_ae18550adf18c43806550554699a34e5','_wp_session_ae18550adf18c43806550554699a34e5','_wp_session_expires_6e1dc6097b031dc23dc62a60f3c0f3bb','_wp_session_6e1dc6097b031dc23dc62a60f3c0f3bb','_wp_session_expires_918485040372d1aa94275175cf3c43fa','_wp_session_918485040372d1aa94275175cf3c43fa','_wp_session_expires_9c775324d959a06935f612ecf4e12964','_wp_session_9c775324d959a06935f612ecf4e12964','_wp_session_expires_60e34434487834a57ed2711b8f728a5e','_wp_session_60e34434487834a57ed2711b8f728a5e','_wp_session_expires_-1'','_wp_session_-1'','_wp_session_expires_a6642455c0c83b5171cc6f6df24039d9')
```

If you take a look at the end of the query (I've shortened it for this example) there's a value `'','_wp_session_`, this is causing the error as it's being incorrectly escaped/quoted.

Maybe updating the query to use [placeholders](http://codex.wordpress.org/Class_Reference/wpdb#Examples_9) could fix it?

**Comment by vipinks** [comment]
This error also triggers in WP Session Manager Plugin, from where you have adapted the session class
