### ISSUE TITLE
Add admin page helper function for extension developers

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/Easy-Digital-Downloads#2657]
Enqueuing scripts for backend EDD work right now could be made easier for extension devs.

I'm thinking we could do something like edd_is_admin_page() but the problem with that function is it would let scripts load on all pages

What I'm thinking is something like edd_is_admin( $page ) where you pass in a param

The param could be a string, or an array of strings.
Possible values: 'download' (edit download page), 'order' (edit order page)', 'coupon' (edit coupon page), download_table (download table), etc

If the param is a string, for example, download, and we're on the edit download page it would return true, else return false.

If the param is an array, it would see if any are true, and if so return true, else false. 

To reduce the chance of issues with users on old versions of EDD not having that function, we could actually just impement this into edd_is_admin_page, and if theres a param do the new logic ^, else do the old one

This would make it easier to enqueue scripts just to specific EDD admin views
thoughts?

**Comment by chriscct7** [comment]
This is ready for merge in #3088

**Comment by pippinsplugins** [comment]
This shouldn't be a separate function. It should be part of the same function we already have.

**Comment by chriscct7** [comment]
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/commit/55c0e6cdadcd74f53d6c1615b9e90c104bde8444

**Comment by cklosowski** [comment]
Punting until 2.4, we need some more time to make sure this logic is solid.
