### ISSUE TITLE
Load textdomain on plugins_loaded

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#2677]
We need to load the textdomain on plugins_loaded, not init.

**Comment by corvannoorloos** [comment]
@pippinsplugins, this still needs to load on init for custom translations to work.

Also, see https://easydigitaldownloads.com/support/topic/change-language-of-the-plugin/ and http://geertdedeckere.be/article/loading-wordpress-language-files-the-right-way.

**Comment by chriscct7** [comment]
@corvannoorloos see https://wordpress.org/support/topic/loading-textdomain-after-plugins-loaded?replies=2 and http://ottopress.com/2013/language-packs-101-prepwork/
"Any calls to load_plugin_textdomain should be in a function attached to the “plugins_loaded” action hook."

Geert De Deckere's argument is counterintuitive. His argument is you want to run it as early as possible. plugins_loaded is done before init.

**Comment by corvannoorloos** [comment]
@chriscct7

> The user you linked to in the support forum doesn't have their WordPress install set to use French

Like I am, yes he probably does have:

`define( 'WPLANG', 'nl_NL' );`

Note, our difficulties aren't with using the provided translation files, but using a [custom](http://docs.easydigitaldownloads.com/article/231-using-your-own-translation-files) translation located in the wp-content root dir `wp-content\languages\edd\edd-nl_NL.mo`, which apparently only works on init.

**Comment by chriscct7** [comment]
We're going to have to investigate this, and if its a problem find a way around it. We have a lot of users running custom translations in this folder. There should be more support tickets if this is a problem for everyone. We can't change it off of plugins_loaded, because that's what we have to use to support the new WordPress plugin language packs that's being rolled out on WordPress.org over the next couple of months.

**Comment by chriscct7** [comment]
Going to set this to 2.3 so its hits the queue

**Comment by corvannoorloos** [comment]
> We can't change it off of plugins_loaded, because that's what we have to use to support the new WordPress plugin language packs that's being rolled out on WordPress.org over the next couple of months.

Thanks, and understandable.

> We have a lot of users running custom translations in this folder.

Not really sure about how many though. As with WordPress (`wp-content\languages\nl_NL.mo`) I assume few people are using this as a simple alternative (read hack) to using a filter and translating that from a custom plugin.
