### ISSUE TITLE
Merge a set of payment font icons into the EDD Font, remove current payment gateway images

### ISSUE THREAD

**Issue by adampickering** [easydigitaldownloads/easy-digital-downloads#2717]
Here's the project that has already created many payment gateway icons: http://www.orlandotm.com/payment-webfont/

We could merge these into the EDD icon font and create any that need to be created, i'm pretty good with SVG.

Thoughts? @pippinsplugins @spencerfinnell

**Comment by pippinsplugins** [comment]
@ghost1227 Could you please make a pull request for this?

**Comment by pippinsplugins** [comment]
We can't move forward with this anymore, at least not until the iconfont > SVG changes are finished in core.

**Comment by ghost1227** [comment]
Good. Iconfonts ended up being a horrible idea from a UX perspective. Once the SVG changes happen and we can use multi-color graphics, it'll be much more epic!

**Comment by adampickering** [comment]
If you need me to convert everything over to individual SVG images let me know!

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
We can't do anything here until core decides what the heck they're doing with dashicons.

**Comment by pippinsplugins** [comment]
See #4846
