### ISSUE TITLE
Make edd_update_payment_details testable & add tests

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#2749]
We need to introduce unit tests for the payment total updates made in #2589

**Comment by cklosowski** [comment]
This is going to be a bit of a rewrite...I don't think it's going to make 2.2.3, punting to 2.3

**Comment by pippinsplugins** [comment]
:+1:

**Comment by cklosowski** [comment]
Actually, after looking through this, it'd be better to use the
```
edd_get_total_earnings()
edd_increase_total_earnings()
edd_decrese_total_earnings()
```
functions.

These are already tested, and wouldn't require us to alter this process at all.

Thoughts @pippinsplugins

**Comment by pippinsplugins** [comment]
Works for me!
