### ISSUE TITLE
Inclusion of jquery-ui breaks some plugins on edd_is_admin_page() pages

### ISSUE THREAD

**Issue by maimairel** [easydigitaldownloads/Easy-Digital-Downloads#2760]
Hello, 

The jQuery-ui styles loaded on all admin pages by EED breaks many plugin styling that uses jQuery-ui.
So far I've already encountered a couple of plugins that broke because of this. Is there anyway this can be fixed soon?

Thank you :)

**Comment by cklosowski** [comment]
@pippinsplugins When you reworked the ```edd_is_admin_page()``` function just recently, did it help this case at all? Just curious.

**Comment by pippinsplugins** [comment]
No.

**Comment by pippinsplugins** [comment]
Duplicate of #3033
