### ISSUE TITLE
Allow creating new customer from Payment Details Screen

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/Easy-Digital-Downloads#2771]
With the new EDD Customers Class we need a way to create a new customer entry from the Payment Details screen. The current proposed 'metabox' has this view:
![image](https://cloud.githubusercontent.com/assets/1390124/5023494/c1e1ceea-6ab6-11e4-8c7d-965bc76d7606.png)

We need a front end UI as well as backend to create a new customer if the payment needs to be assigned to an email address not already registered as a customer.

**Comment by cklosowski** [comment]
Progress for this is in #2548

**Comment by pippinsplugins** [comment]
I'm loving how this is looking.

**Comment by pippinsplugins** [comment]
This could use some really serious testing, @mindctrl @sumobi @sdavis2702 @ghost1227 @chriscct7

**Comment by pippinsplugins** [comment]
This is now in `release/2.3`

**Comment by pippinsplugins** [comment]
No need for `Has PR` here. The PR was already merged.

**Comment by pippinsplugins** [comment]
This is working beautifully. I'm closing.
