### ISSUE TITLE
Not all schema markup removed when setting edd_add_schema_microdata to false

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#2777]
We have a filter called `edd_add_schema_microdata` that can be used to disable the output of the schema.org markup. Turns out it only disables _some_ of schema.org markup. Some of it is hardcoded.

`[downloads]` has some hardcoded schema. We should do a full scan to make sure we remove all schema if the filter is set to false.

**Comment by cklosowski** [comment]
We don't need to use the filter, we can just use the function to see if we should display microdata, the filter is within it:

```edd_add_schema_microdata()```

**Comment by pippinsplugins** [comment]
Let's get some more unit tests in here to test the filter and then we can call this good.

**Comment by cklosowski** [comment]
👍

**Comment by cklosowski** [comment]
While wrwiting up the unit test for this, I found a few discrpencies in how we're doing it, both from a testing perspective and consistency side.

Currently we base the original factor of showing microdata off ```did_action( 'wp_head' )``` which poses two changes we'll need to make:
1) We state that the function returns a ```bool``` but ```did_action``` returns a ```0``` or ```1```. Going to drop a ```(bool)``` to force the function to return ```true``` or ```false```
2) PHPUnit doesn't run ```do_action( 'wp_head' );``` therefore, we can't test against it. Going to drop a new tests that do both ```__return_true``` and ```__return_false``` to make sure the filters are applied correctly to the shortcodes.

**Comment by pippinsplugins** [comment]
Both changes seem fine to me.

**Comment by cklosowski** [comment]
Cool once #2913 passes CI, I'll merge into ```release/2.3```
