### ISSUE TITLE
Profile editor template allows email address to be deleted

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/Easy-Digital-Downloads#2783]
The template used by the `edd_profile_editor` shortcode allows a customer to remove their email address completely. Since WP requires an email address on an account, I think it makes sense to prevent a blank value from being submitted here. In our case, someone was able to erase their email address from their profile, because customers do crazy things, then couldn't use the password reset link after forgetting their password.

**Comment by pippinsplugins** [comment]
@cklosowski Could you give this one final test then we can close it out?

**Comment by cklosowski** [comment]
Looks good to me @pippinsplugins Nice work @ghost1227 and thanks @mindctrl
