### ISSUE TITLE
Variable pricing Add to Cart button reappears on refresh (instead of Checkout button)

### ISSUE THREAD

**Issue by sdavis2702** [easydigitaldownloads/Easy-Digital-Downloads#2788]
This only applies to variable pricing. When you click the Add to Cart button with AJAX enabled, it changes to a checkout button. Refresh the page and it changes back into an Add to Cart button. I think this only makes sense when the multi-select option is enabled, considering the purpose of multi-select is to be able to add (and purchase) more than one variable option.

Right now, this also works with multi-select disabled. That means you can add (and purchase) more than one of the variable pricing options no matter what. What's the point of the multi-select setting then? Having multi-select disabled is just a multi-select that requires more refreshes and clicks. Same abilities. :flushed:

**Comment by cklosowski** [comment]
Confirmed, it does occur. I think however, we need to check both multi-select.

To replicate.
Add a variable price to the cart.
Refresh the page.
You can then add the same price, or another one to the cart.

NOTE
If you have allow editing of quantities enabled, it shows as a single line item in the cart with a quantity, if you have it disabled, each addition is it's own line.

**Comment by cklosowski** [comment]
@sdavis2702 Try this branch out and see if it does what you were thinking.

**Comment by pippinsplugins** [comment]
This works mostly. The variable prices are still displayed, however, after refresh: 
![screen shot 2015-01-07 at 11 18 32 am](https://cloud.githubusercontent.com/assets/1034109/5649872/ff174c76-965e-11e4-9708-3e2536e7d4b4.png)

**Comment by pippinsplugins** [comment]
If we're not going to allow an item to be added to the cart again, shouldn't we hide the price options too?

**Comment by cklosowski** [comment]
Yeah we can, and probably should. Last I heard @sdavis2702 said you weren't too keen on this? I'm open to discussion on what we want to do here.

**Comment by sdavis2702** [comment]
I agree, @pippinsplugins. Sorry, @cklosowski... I missed your last reply. 

I see no reason why the other options shouldn't be removed. That's the logical approach, IMO.

**Comment by cklosowski** [comment]
Sounds good. I'll update it for testing.

**Comment by sdavis2702** [comment]
Just to make sure we're all on the same page, we're only talking about variable pricing with multi-option purchase mode disabled. of course the other options should stay put if multi-option purchase mode is enabled. And the Add to Cart button should not turn to a Checkout button.

**Comment by cklosowski** [comment]
correct. I think the behavior with multi is fine as is:
which means that the button will change to checkout when added, but on page refresh is 'Add to cart' again.

But yes, you are right. I'll have the push in a minute so we can all test it out.

**Comment by cklosowski** [comment]
Should we put some sort of messaging as in 'This item is alreayd in cart'? or maybe make the price options readonly?

It could be slightly confusing to just see 'checkout' under a product

**Comment by pippinsplugins** [comment]
For the time being, I'd leave it as just `Checkout` since that's been our standard behavior for a while.

**Comment by sdavis2702** [comment]
Ouch. Definitely a dilemma. I do think some kind of message is needed. I doubt many people will even refresh the page anyway but for the few who do, I do think they should be told what's going on. Maybe in the same area as the Added to Cart message.

**Comment by sdavis2702** [comment]
@pippinsplugins or that lol

**Comment by cklosowski** [comment]
I'm not saying change the text of the button


just something to not look as 'broken'

**Comment by cklosowski** [comment]
Pippin is right, we can't add to layout on a point release. Could mess with too may sites.

**Comment by sdavis2702** [comment]
:+1:

**Comment by cklosowski** [comment]
Ok @pippinsplugins and @sdavis2702 how's that work for you?

**Comment by sdavis2702** [comment]
I like it. I didn't realize all options were being removed, including the one that was selected, though it makes sense. So that kind of changes my option. Having just the checkout button there doesn't seem _that_ bad to me now. But yea, maybe a small message in the future.

**Comment by cklosowski** [comment]
Yep, I created #2935 so we can remember to address it.

**Comment by sdavis2702** [comment]
You da man!

**Comment by pippinsplugins** [comment]
:+1:

**Comment by cklosowski** [comment]
Found a small bug in this, that when you remove an item from the cart, if you have quantities enabled, the quantity input doesn't come back, just the ```Add to Cart``` button.
