### ISSUE TITLE
Payment History download ID search returns only returns one page

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/Easy-Digital-Downloads#2789]
Choose a download item that has recorded a high number of sales (might want to check on your personal sites... I think you need over 30). Get the download ID. Then go to the Payment History page and search for `#{download_ID}`. Only one page of results are shown with no pagination. 

Relevant ticket: https://easydigitaldownloads.com/support/topic/searching-payments-by-download-id/#post-358708

**Comment by cklosowski** [comment]
Will see if I can tackle this over the weekend.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by cklosowski** [comment]
The issue, I believe, lies in this part of the query:
```
["post__in"]=> array(38) { [0]=> string(3) "703" [1]=> string(3) "701" [2]=> string(3) "699" [3]=> string(3) "697" [4]=> string(3) "695" [5]=> string(3) "693" [6]=> string(3) "691" [7]=> string(3) "689" [8]=> string(3) "687" [9]=> string(3) "685" [10]=> string(3) "673" [11]=> string(3) "673" [12]=> string(3) "673" [13]=> string(3) "671" [14]=> string(3) "667" [15]=> string(3) "667" [16]=> string(3) "667" [17]=> string(3) "664" [18]=> string(3) "664" [19]=> string(3) "659" [20]=> string(3) "620" [21]=> string(3) "618" [22]=> string(3) "614" [23]=> string(3) "612" [24]=> string(3) "610" [25]=> string(3) "608" [26]=> string(3) "606" [27]=> string(3) "604" [28]=> string(3) "602" [29]=> string(3) "566" [30]=> string(3) "547" [31]=> string(3) "534" [32]=> string(3) "534" [33]=> string(3) "532" [34]=> string(3) "530" [35]=> string(3) "527" [36]=> string(3) "524" [37]=> string(3) "520" }
```

The query contains a ```post__in``` and is removing the ```post_parent``` as the qualifying attribute. We're not getting pagination because the query is told only to find the specified 30 posts...therefore causing no pagination as the entirety of the set has been found.

Will work from here to see if I can get it functioning correctly.

**Comment by cklosowski** [comment]
Yep, I was wrong, it's in the count function:
```edd_count_payments```

Looking for a good way to do this, with a meta query or join.

**Comment by cklosowski** [comment]
@sdavis2702 @pippinsplugins Can you guys test this out? I'm having some weird results, but I really really messed with my purchase logs by testing out #2942

**Comment by sdavis2702** [comment]
@cklosowski I'm trying to make sure I'm not doing anything wrong but issue/2789 is not giving me filtered results at all. What appears to be happening when I search a #{download_ID} is 1 full page of results are shown no matter what and the results are *not* just the ID I've search. Likewise, because there doesn't appear to be a rhyme or reason to the results, I'd expect more than one page to show. But again, it's showing 1 page no matter what. 1 full page of mixed results.

Is that what you're getting?

**Comment by cklosowski** [comment]
Nope, I'm getting a properly paginated search with the branch ```issue/2789```

**Comment by cklosowski** [comment]
And outside of the WP Admin, if I query the DB directly, i'm getting the results I am expecting.

**Comment by sdavis2702** [comment]
Alright yea there may have been a cache issue. I'm getting a full page of 30 results for just the product I've searched now. But I am not getting the pagination. Likewise, the quick link counts are still hanging at 0 for me. http://glui.me/?i=y9psb0u7unycxr5/2015-01-12_at_9.22_AM.png/

**Comment by cklosowski** [comment]
@sdavis2702 Can you run this query against your DB and tell me what you get? Are you sure that one has more than 30 purchases? And multiple quantities don't count in this instance. the purchase history log only counts for the single purchase, not the multiple lines of edd_log entries made.

```
SELECT p2.post_status,count( * ) AS num_posts FROM wp_posts p LEFT JOIN wp_postmeta m ON m.meta_key = '_edd_log_payment_id' AND m.post_id = p.ID INNER JOIN wp_posts p2 ON m.meta_value = p2.ID WHERE p.post_type = 'edd_log' AND p.post_parent = 148 GROUP BY p2.post_status;
```
As far as the counts up top. I'm not 100% sure on those. I'm having issues right now (as stated above) but I do see them being inconsistent. Not sure what to say on that since my queries are returning the right numbers. I'll work on that...but for now we need to make sure the query is working for you too...without WordPress in the way.

**Comment by cklosowski** [comment]
What I mean by the logs is...a purchase makes a single ```edd_purcahse``` entry, but the number of ```edd_log``` entires for a purchase are equal to the quantity...

So a purchase of a product with ```40``` quantity would still return a single ```edd_purcahse``` entry.

**Comment by pippinsplugins** [comment]
Search results work for me but pagination fails.

I have 30+ purchases of the same product but even changing per_page to 10 does not result in pagination options being displayed.

**Comment by cklosowski** [comment]
That's strange...Wonder why we're getting different results...30 separate purcahses or 30 receipts with the item on it @pippinsplugins

**Comment by pippinsplugins** [comment]
Separate purchases.

**Comment by sdavis2702** [comment]
@cklosowski Sorry. I don't know how to run a query against my DB.

Also, it's definitely 30+ purchases of a single item lol. I did them all manually. I add a new purchase and the new payment just hits the top of the list. The bottom one disappears into oblivion.

**Comment by cklosowski** [comment]
...Will have to look into this further than. I can't get it to do what you guys are saying...

**Comment by cklosowski** [comment]
ok @pippinsplugins and @SDavisMedia can we try this...again!? :P

**Comment by pippinsplugins** [comment]
Will test soon!

**Comment by pippinsplugins** [comment]
Search doesn't work at all for me now. It's always showing all items.

**Comment by pippinsplugins** [comment]
Scratch that, yes it does. I was entering `#:97` instead of `#97`.

I think we should go ahead and strip out `:` if it's there as well. It makes sense that someone would mistakenly enter a `:` since it's used in some of the other search methods.

**Comment by pippinsplugins** [comment]
Unfortunately, pagination still doesn't work.

I'm searching for a download that has 21 sales. Setting the `$per_page` parameter to `10` results in only 10 items and no pagination.

**Comment by cklosowski** [comment]
I'm really not getting how this isn't working for you guys, mine had 25 sales. pagination worked perfectly. I'll keep digging. are you sure you've cleared caches for possible counts and what not?

**Comment by cklosowski** [comment]
Download has 11 sales, 5 per page defined.

![screen shot 2015-11-10 at 8 51 54 am](https://cloud.githubusercontent.com/assets/1390124/11067138/59eb5ac8-8788-11e5-8094-c0cca655ef79.png)
![screen shot 2015-11-10 at 8 51 47 am](https://cloud.githubusercontent.com/assets/1390124/11067140/5c7b4ae6-8788-11e5-832e-5b11934f32b9.png)

**Comment by pippinsplugins** [comment]
@SDavisMedia @mindctrl can you guys test this again?

**Comment by SDavisMedia** [comment]
@pippinsplugins I still get 30 results and this notice at the top of the screen: 

`WordPress database error: [Table 'edd.wp_2_postmeta' doesn't exist]
SELECT p2.post_status,count( * ) AS num_posts FROM wp_posts p LEFT JOIN wp_2_postmeta m ON m.meta_key = '_edd_log_payment_id' AND m.post_id = p.ID INNER JOIN wp_2_posts p2 ON m.meta_value = p2.ID WHERE p.post_type = 'edd_log' AND p.post_parent = 148 GROUP BY p.post_status`

**Comment by cklosowski** [comment]
Ok I'll take a look at that error this afternoon

**Comment by cklosowski** [comment]
@pippinsplugins @SDavisMedia give that a shot, found a hard coded reference to the table `wp_2_postmeta` which would for sure throw things off in your environments, and explains why it worked in my environment.

**Comment by pippinsplugins** [comment]
There! we go! Now it works @cklosowski  :)

**Comment by SDavisMedia** [comment]
Same here. :+1:
