### ISSUE TITLE
Re-add download attribute

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#2798]
The `download` attribute for download links was added in #2393 then removed in #2794.

I'd like to see it added back in.

@chriscct7 has made a good start in #2795

**Comment by pippinsplugins** [comment]
This is not happening for 2.2.3.

**Comment by pippinsplugins** [comment]
#3091

**Comment by pippinsplugins** [comment]
#3255

**Comment by chriscct7** [comment]
#3512

**Comment by pippinsplugins** [comment]
Spent some time chatting with @cklosowski about this and we both agree that it needs to be done but are going to hold off a bit because we are tentatively planning on refactoring the download processing to abstract it a bit more, primarily for #3002

**Comment by chriscct7** [comment]
Can we go ahead and merge this into the 2.5 branch please? This pr affects some of the most volatile (in terms of code changes) area of EDD, and we've already had to resubmit this pr 5 times

**Comment by pippinsplugins** [comment]
No. The entire point of not merging it now is so that we can determine if
any changes here need to be made as we refactor the whole download
processor.

**Comment by pippinsplugins** [comment]
This is getting marked as `wontfix` because of issue detailed here: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/pull/3681#issuecomment-137552441
