### ISSUE TITLE
Improve tax handling to allow EU VAT regulation handling

### ISSUE THREAD

**Issue by jdevalk** [easydigitaldownloads/Easy-Digital-Downloads#2805]
To be able to handle all the new tax regulations in the EU per january 1st 2015, we need to add a few "basic" tax handling features to EDD:

- [ ] an option to change a specific tax rate at a specific date (to allow only updating these things like once a month).
- [ ] an option to have multiple types of tax rates per country.
- [ ] an option to specify the type of tax rate to use for a specific product category.

I could personally live without 2 and 3 above for a while, the first is the most "urgent" for me as it would otherwise soon become unmanageable.

**Comment by pippinsplugins** [comment]
I think this can be closed now and continued with #2819 (multiple rates per country) and #2820 (multiple tax types).
