### ISSUE TITLE
File downloads graph

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#2806]
A user has requested better reporting on file downloads: https://easydigitaldownloads.com/support/topic/better-statsreports-including-user-specific-options/

I rather like the idea of offering a graph that shows the number of downloads per day, hour, week, etc.

It would also be cool to have a "downloads by location" report that shows where downloads are coming from. This one is probably extension territory but the main file downloads graph should be core.

**Comment by pippinsplugins** [comment]
@ghost1227 How's your work on this coming?

**Comment by ghost1227** [comment]
https://github.com/Section214/Easy-Digital-Downloads/commit/91d71d1de85e99fef040743603d0f3df22c4bd19

**Comment by ghost1227** [comment]
So... not nearly ready to merge, but that PR is the current status of this issue. I've split the current `Reports` tab into two tabs, `Reports` and `Stats`. The `Stats` tab displays actual stats graphs (currently just `Earnings` and what will be `Downloads`. The `Reports` tab displays everything else that it does now.

Currently, the Downloads graph is just a tweaked version of the preexisting Earnings graph. After discussing it with @cklosowski, it looks like we need to setup a new helper function to query downloads by date similar to the `edd_get_sales_by_date` function (correct me if I'm wrong here @cklosowski). 

Which.... leads me to the issue I originally mentioned @pippinsplugins. I'm still not sure how to write the appropriate meta query to retrieve downloads by date.

**Comment by cklosowski** [comment]
I'll work up something tomorrow Dan

**Comment by ghost1227** [comment]
No problem, as long as progress is being made I'm happy.

**Comment by ghost1227** [comment]
@cklosowski any feedback?

**Comment by pippinsplugins** [comment]
@cklosowski @ghost1227 Can you guys get together on this sometime this week?

**Comment by pippinsplugins** [comment]
Punting to 2.4 due to lack of discussion.

**Comment by pippinsplugins** [comment]
Punting to 2.5, the reports release.

**Comment by pippinsplugins** [comment]
We have not seen any further requests for this so I'm going to close and mark as maybe later.
