### ISSUE TITLE
EDD Settings rich_editor allows an empty string as a valid setting

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/Easy-Digital-Downloads#2808]
When using the EDD ```rich_editor``` setting type, it's possible to delete the entire entry, allowing an ```empty``` setting. I'm proposing that if the setting be empty, that the rich editor fall back to it's default ```std``` value.

If you try and use the default EDD ones it doesn't seem to work, but register a setting as an extension and if your setting is blank, you're entry will also be blank, instead of using the ```std```.

What are your thoughts on breakage here?

**Comment by cklosowski** [comment]
@ghost1227 if you can close your PR #2824 and resubmit to 2.3 I'll take a look and see about merging.

**Comment by pippinsplugins** [comment]
@ghost1227 Could you resubmit to `release/2.3`?

**Comment by ghost1227** [comment]
Resubmitted as requested
