### ISSUE TITLE
Add more countries and states/provinces to Country dropdown

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/Easy-Digital-Downloads#2818]
In order to help @bseddon (EDD EU VAT) and me (EDD Block Countries Checkout) make our extensions as comprehensive as possible, and to further the original intent of #2805, we need to bolster the list of countries and states/provinces to be as comprehensive as possible. In particular, we need to ensure that areas of 0 VAT (like Canary Islands in Spain) are listed on the applicable dropdowns, so both of our extensions can filter on exceptions like that.

Here is a list, that I've compiled thus far, of no-VAT areas. It is not probably fully comprehensive, and some of these places (ex: Mount Athos and the Italian waters of lake lugano) I doubt anyone lives so we can probably safely avoid putting them on the list, but other places (ex canary islands, faroe islands) definitely need to be added. The list is below.

To help with our efforts WooCommerce has a fairly comprehensive list of countries and provinces we should compare ours to. Its here: https://github.com/woothemes/woocommerce/tree/4e99e629f527c9558a82a31852afe5059bfac48f/i18n

Finland:
- Åland

France:
- Overseas departments, such as Réunion and Guadeloupe

Germany:
- Büsingen am Hochrhein
- Heligoland

Greece:
- Mount Athos

Italy: 
- some parts bordering to Switzerland
- Campione d'Italia
- Livigno
- The Italian waters of Lake Lugano

Netherlands:
- Aruba
- Curaçao
- Sint Maarten
- The Caribbean Netherlands

Spain:
- Canary Islands
- Ceuta
- Melilla

United Kingdom:
- Gibraltar
- Channel Islands
- British Overseas Territories

**Comment by pippinsplugins** [comment]
I vote that we merge this in as @ghost1227 has done it. Any objections? If we choose to change the architecture of it later, we can.

**Comment by cklosowski** [comment]
Yeah I'm good with that @pippinsplugins, it's better, not perfect, but better. We can iterate on it later if necessary.

**Comment by cklosowski** [comment]
Going to merge this and close. If we need further discussion, let's open up a new issue and track from there.
