### ISSUE TITLE
Multiple tax rates per country

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#2819]
We should allow people to be able to set multiple tax rates per country using states/provinces and/or zip/postal codes. Furthers #2805.

As this will likely require a substantial overhaul (and lots of testing) of our taxes system, pegging 2.3

**Comment by pippinsplugins** [comment]
We're getting to close to 2.3 release date. Need to punt to 2.4.

**Comment by pippinsplugins** [comment]
This has not been needed nor requested by anyone that I'm aware of in over two years. Closing as wontfix.

**Comment by paparent** [comment]
@pippinsplugins Hi ! I don't know if it's related, or I should open a new tickets but.

I'm in Quebec (Canada), and depending the country, we have two taxes.. So for every sales in Canada, we have one tax (TPS) which is 5%. For sales in Quebec, we have that 5% of TPS, plus another one for quebec (TVQ), which is 9.975%. Is it doable with the current options? For international sales, no tax at all of course!

Thanks.
