### ISSUE TITLE
Unlink cart saving from cookies and users

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#2828]
I'm currently working on an extension to allow users to send a cart via email. This would be more of a marketing tool, and a generic use case would be a developer to a client stating "Get this stuff".

However, the cart saving is currently tied to either the User ID or a cookie. I'm proposing we drop the cookies altogether in favor of a 7 day transient (with cleanup via wpcron of course), and the ability to use the `edd_save_cart`  function as a logged in user, without tying the cart to my user. This could be achieved by adding an arguement like `user_id` that defaults to the logged in user, but if we pass in `0` or `false`, it would then revert to a generic cart, not just one associated with user meta.

Looking for some feedback on what you think. I don't think it'll disrupt too much honestly and would make the cart saving a bit more flexible in it's use cases.

**Comment by grappler** [comment]
Could you not share the cart with the custom add to cart links?

http://docs.easydigitaldownloads.com/article/268-creating-custom-add-to-cart-links

**Comment by cklosowski** [comment]
We've seen no need for this at this time, and I've stopped the developing of the sending cart extension as there was not enough interest. I'm closing this issue.
