### ISSUE TITLE
Better support of db upgrades for network WordPress multisite

### ISSUE THREAD

**Issue by stephenharris** [easydigitaldownloads/Easy-Digital-Downloads#2834]
For security (& maintenance) reasons I have removed the ability for plug-ins to be installed on my website (indeed, any files to be modified). Updates are done locally and pushed live via git. 

Update routines, however, still need to be run on the live site (i.e. changes to the database etc). After updating EDD, however, I found I was unable to do execute the necessary upgrade routine(s) because I did not have permission.

Digging into the source, this is because the upgrades page requires the "install_plugins" permission. WordPress by comparison doesn't seem to perform any user permission check (`.../wp-admin/upgrade.php`), but would "manage_options" suffice?

**Comment by pippinsplugins** [comment]
We'll add better MS upgrade options in the future. For now the original issue in this ticket is resolved with #3034
