### ISSUE TITLE
Second "upgrade database" link disappears after first upgrade routine

### ISSUE THREAD

**Issue by stephenharris** [easydigitaldownloads/Easy-Digital-Downloads#2835]
This a slight UX issue. Once I updated EDD, I had two messages informing me to upgrade:

> Easy Digital Downloads needs to upgrade the database, click here to start the upgrade.

and

>Easy Digital Downloads needs to upgrade the customer database, click here to start the upgrade

(So evidently it has been a while since I updated EDD :))

Clicking on the first link, the upgrade proceeds as normal, and then redirects the user. But the notice for the second upgrade routine has now disappeared, although it was never executed. This isn't a massive issue for me - I noticed the problem on my development site after seeing MYSQL errors and "manually" triggered the routine by visiting the appropriate url. But this may present a problem for some users.

**Comment by cklosowski** [comment]
@pippinsplugins We're going to hit this again with `2.3`. We have two upgrades that need to run. Each of them updates the DB on completion with the new version of EDD...so only one will show once it's completed.

I'll see if I can find a way around this in 2.3.

**Comment by cklosowski** [comment]
Going to tackle this later today. Thinking of creating an `edd_upgrades_completed` option taht will store the actions of the upgrades, so we can keep track of ones that have run.

**Comment by pippinsplugins** [comment]
Looks good. I'll test it on pippinsplugins soon to confirm.

**Comment by cklosowski** [comment]
sounds good.

**Comment by pippinsplugins** [comment]
Boom, worked perfectly: https://cloudup.com/cwkVTbv67bw
