### ISSUE TITLE
Add PHP 5.5, 5.6 and HHVM  to the travis-ci matrix

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/Easy-Digital-Downloads#2839]
Anyone opposed to adding PHP 5.5 to the Matrix? I know a couple of our local environments are using this version. Might be nice to get ahead and make sure we're testing for it as hosts are starting to adopt it.

**Comment by cklosowski** [comment]
So I've been getting some good community feedback about optimizing the build matrix from the community after my blog post about this. 2 suggestions stand out, what do you think?

1) Only run Multisite on one PHP version (suggested by @danielbachhuber)
2) Only run code coverage on one matrix build (probably only latest & 5.5?) as suggested by @bradt

**Comment by pippinsplugins** [comment]
Sounds good to me.

**Comment by cklosowski** [comment]
I'm much happier with this build setup, good compatibility checking, ~17 minutes to full build with code coverage run on a single mode and Multisite on a single mode.

Any objections to closing this one out @chriscct7 @pippinsplugins ?

**Comment by pippinsplugins** [comment]
I'm happy!

**Comment by bradt** [comment]
Nice, thanks for sharing!
