### ISSUE TITLE
Variable pricing ID starts at 0, newer downloads start from 1

### ISSUE THREAD

**Issue by sumobi** [easydigitaldownloads/Easy-Digital-Downloads#2874]
The issue from the customer:

<blockquote>
I have multiple products for sale on my Download page, when I changed the default item on the page by clicking on the right circle and then proceeding to update the page, the previous default item remains the same. However, when I view my product page, I noticed that the default item is now the right one that I chose. When editing the download, the circle is still highlighted on the previous default.
</blockquote>

See: https://easydigitaldownloads.com/support/topic/default-in-multi-option-download-not-updating-visually/ 

Note in the image below how the ID starts at `0`:
https://easydigitaldownloads.com/wp-content/uploads/2014/12/Screen-Shot-2014-12-12-at-12.05.53-PM.png

If you create a new download it starts at `1`. It seems that some downloads after upgrading to a newer version of EDD still have their ID at `0` which is causing a small issue with ordering.

**Comment by cklosowski** [comment]
yeah, but is actually in the logic around a default price Id of ```0```. It wasn't passing a boolean check.

**Comment by pippinsplugins** [comment]
@cklosowski Does this need anything else? Looks good to me.

**Comment by cklosowski** [comment]
@pippinsplugins that should do it :) was just wanting someone to take a peek at it, make sure my logic looked good.

**Comment by pippinsplugins** [comment]
Yep logic looks good. I'll merge it in.

**Comment by pippinsplugins** [comment]
Oh, I'm too slow.
