### ISSUE TITLE
Do not show bundled products in the products drop down (if on a bundle)

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#2882]
Bundles should not be allowed to be assigned to another bundle.

**Comment by ghost1227** [comment]
Still struggling with this one @pippinsplugins @cklosowski Love to be able to close it though... either of you mind giving me a hand?

**Comment by pippinsplugins** [comment]
Sure. Tell me what you have so far and what you've tried, then I can provide feedback.

**Comment by ghost1227** [comment]
I don't really have anything beyond what's already been merged, because I simply don't understand the ajax necessary. My JS skills are limited to the type of stuff I write for my extensions, and I have a VERY hard time understanding most of the EDD core JS, particularly when it starts involving AJAX.

**Comment by pippinsplugins** [comment]
Ok let's start simple.

Do you see and understand the JS that currently triggers the search?

**Comment by ghost1227** [comment]
I know where it IS, though I may not have been able to find it easily if you hadn't already pointed me to it. I understand parts of it in theory, but not necessarily in practice. I understand that when you start typing, it triggers `edd_download_search` and passes it the value of whatever is in the text field, and I understand most of the success function just from my own work with Select2 (it's not terribly dissimilar). Totally lost on how any of that function is related to a GET query (probably just my lack of understanding regarding AJAX generally).

I DO understand much of the `edd_download_search` function, though the use of the `wp_ajax` actions is beyond me still. Speaking of that function... why are we using direct wpdb calls? And the PHPDOC is wrong for that function too... it says states, not downloads.

**Comment by pippinsplugins** [comment]
Great, you're most of the way there.

Two exclude the current post ID from it, all you need to do is pass another parameter here: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/assets/js/admin-scripts.js#L1045

`s: val` is the current search term that's being entered. The `s` becomes `$_POST['s']` in the PHP. Simply add another key/value that is set to the ID of the current post, which is available in the EDD localized vars.

For example, if you added `current_id: edd_vars.post_id`, you could access that with `$_POST['current_id']` in the PHP.

Does that make sense?

**Comment by ghost1227** [comment]
A quick glance at the `edd_download_search` function looks like `s` becomes `$_GET['s']`, not `$_POST['s']`, right? Also, that all makes sense, but how do you exclude that? Would it just be:

    $items = $wpdb->get_results( "SELECT ID,post_title FROM $wpdb->posts WHERE `post_type` = 'download' AND `post_title` LIKE '%$search%' AND `post_title` NOT LIKE '%$exclude%' LIMIT 50" );`

where `$exclude = esc_sql( $_GET['current_id'] );`?

**Comment by pippinsplugins** [comment]
Sorry, you're right, it's `$_GET`, not `$_POST`.

To exclude it you just need to add ` AND post_id NOT IN($exclude_array)`

**Comment by ghost1227** [comment]
Right, ID not title... though why would it be an array? Aren't we just worried about the current ID?

**Comment by pippinsplugins** [comment]
Oops, `ID`, not `post_id`.

Set it up as an array and then explode it into a comma separated listed. Just makes it more flexible in the future in case we need to add additional exclusions later on.

**Comment by ghost1227** [comment]
OK, this is now ready to merge AFAIK

**Comment by cklosowski** [comment]
Will test this out a bit and then merge when passes.

**Comment by ghost1227** [comment]
@cklosowski passing!

**Comment by pippinsplugins** [comment]
@ghost1227 This is failing now. It causes it to not return any results.

Also `data` on line 1068 is undefined (it's `response` not `data`).

**Comment by ghost1227** [comment]
Roger that! Looking into it!

**Comment by ghost1227** [comment]
@pippinsplugins Are you testing with script_debug on? Because @cklosowski told me not to bother updating the minified scripts, so the last few changes aren't included in the attached admin.min.js. I can't duplicate your error... it works fine for me. Also, the error on line 1068 exists in release/2.3. I didn't make write that line so wouldn't have thought to see if it was wrong :stuck_out_tongue:

**Comment by pippinsplugins** [comment]
Yes I had script debug enabled.

**Comment by ghost1227** [comment]
That's weird... I can't duplicate your bug at all. It consistently returns everything BUT bundles. @cklosowski have you duplicated the bug? Any idea what causes it for Pippin?

**Comment by pippinsplugins** [comment]
@cklosowski Could you test and see if you get the same behavior?

**Comment by cklosowski** [comment]
Yes I will test it today.

**Comment by ghost1227** [comment]
@cklosowski feedback?

**Comment by cklosowski** [comment]
I'm getting:
```ReferenceError: data is not defined``` Script debug is on, so I'm not using minified versions.

**Comment by cklosowski** [comment]
The error is actually in the ```.fail``` catch:

```
					if ( window.console && window.console.log ) {
						console.log( response );
					}
```
 Fixes it, the ```console.log``` was trying to use ```data``` not ```response```. I assume because the ```success``` catch is using ```data```. Just a naming issue.

**Comment by ghost1227** [comment]
I did duplicate that error, but that predated my change and doesn't impact usability. I'll be happy to submit a PR for that, but it doesn't explain why @pippinsplugins couldn't get the PR to work at all.

**Comment by pippinsplugins** [comment]
@ghost1227 Could you go ahead and fix Chris's note and then I can test it again?

**Comment by ghost1227** [comment]
@pippinsplugins I did... this morning...

**Comment by cklosowski** [comment]
@ghost1227 Seeing one more thing now...I have 2 products that contain ```bundle``` in the name.

I get ```'No results found'``` as i type up until my string is ```bund```, then I get no updates to the ```results``` view, and checking the response in the inspector gives me this is the AJAX return:
```
<br />
<b>Notice</b>:  Undefined index: post_id in <b>/Users/cklosowski/WordPress/src/wp-content/plugins/Easy-Digital-Downloads/includes/ajax-functions.php</b> on line <b>441</b><br />
<br />
<b>Warning</b>:  explode() expects parameter 2 to be string, array given in <b>/Users/cklosowski/WordPress/src/wp-content/plugins/Easy-Digital-Downloads/includes/ajax-functions.php</b> on line <b>443</b><br />
[]
```

Seems like ```	$excludes = (array) $_GET['post_id'];``` should have a ternary giving a default value of an empty string...or false, and then we can run a check to see if ```$excludes``` is false prior to running the ```array_map```, and if it's ```false``` just make ```$excludes``` an empty array.

**Comment by pippinsplugins** [comment]
Bundles are still showing in search results to me: 
![screen shot 2015-02-13 at 10 06 51 pm](https://cloud.githubusercontent.com/assets/1034109/6198521/a8b0b7f6-b3cc-11e4-9f82-6cd5b6f3e18c.png)

**Comment by ghost1227** [comment]
@pippinsplugins Now I _know_ there's something screwy with your implementation. @cklosowski and I spent hours working on it and it works fine for both of use across WordPress versions and in every scenario we could throw at it.

**Comment by pippinsplugins** [comment]
It can't just be me. This happens on both my machines.

This is wrong:
```php
	$search   = esc_sql( sanitize_text_field( $_GET['s'] ) );
	$excludes = ( isset( $_GET['post'] ) ? (array) $_GET['post'] : array() );
	$excludes = array_map( 'absint', $excludes );
	$exclude  = implode( ',', $excludes );
```

We can't use `$_GET` here. We're doing a `POST` request to admin-ajax.php. `$_GET` will be empty and the `$_GET['post']` var will not be set. We're not on the edit screen during this request, we're in admin-ajax.php.

**Comment by pippinsplugins** [comment]
It should be
```php
	$search   = esc_sql( sanitize_text_field( $_REQUEST['s'] ) );
	$excludes = isset( $_REQUEST['current_id'] ) ? $_REQUEST['current_id'] : false;
	$excludes = array_map( 'absint', $excludes );
	$exclude  = implode( ',', $excludes );
```

**Comment by pippinsplugins** [comment]
There is also nothing in this that excludes other bundles from the search results (the purpose of the original issue). So far the changes are only to exclude the current item from the search results.

**Comment by ghost1227** [comment]
Using `$_GET` has worked fine for us... even on brand new downloads. And yes there is something that excludes other bundles. It was the first thing finished... https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/3c0d59f1621a621750a9fabee97d07ffe0b642c6/includes/class-edd-html-elements.php#L55-L65

**Comment by pippinsplugins** [comment]
Ah! Sorry, forgot about that change for excluding bundles. I was looking only at the search.

**Comment by ghost1227** [comment]
No problem... still curious why you're having issues though

**Comment by pippinsplugins** [comment]
I don't understand how `$_GET` can work here . . . it's not being done on the edit page, it's a remote request to another location . . .

**Comment by ghost1227** [comment]
Works fine! In `assets/js/admin-scripts.js` you're passing EVERYTHING to the `edd_download_search` action in the form of a `$_GET`request.

**Comment by pippinsplugins** [comment]
Now you're not . . . the only things that get sent are `action`, `s`, and `current_id`: https://cloudup.com/cz2wgQzNhv7

**Comment by ghost1227** [comment]
@cklosowski issue fixed
