### ISSUE TITLE
unapplied coupon code at checkout

### ISSUE THREAD

**Issue by norcross** [easydigitaldownloads/Easy-Digital-Downloads#2895]
when a user enters a coupon code, but does NOT press the "apply" button, the code is saved in the payment meta but not actually applied. expected action should be to either not save the meta, or apply the code.

**Comment by pippinsplugins** [comment]
I'd think that if a discount code is already applied, it should take precedence over a new one that is entered without being applied.

**Comment by cklosowski** [comment]
Ok, so only use existing, don't apply the new one that's been posted. Maybe I can find a way to put a filter on it, so people can alter that behavior if they want.

**Comment by pippinsplugins** [comment]
It could be done by hooking into one of the pre-checkout actions. If a
discount is present that doesn't exist in the session data, it could be
swapped.

**Comment by cklosowski** [comment]
Perfect, so we just need to make this not replace it if there's already a discount. Will have it done in a few.
