### ISSUE TITLE
Download History Shortcode should support an id parameter

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#2897]
As mentioned here: https://easydigitaldownloads.com/support/topic/want-to-show-specific-product-download-history/#post-393369 an id parameter on the download_history shortcode could be useful for people and adding it would be very low impact to do.

**Comment by danieliser** [comment]
Then again @pippinsplugins, you just made the case for this. Renewals is a perfect example. Say I want to show subscriptions & single item purchases separately. In that regard and exclude parameter would be relevant as well.

**Comment by pippinsplugins** [comment]
Eh . . . I'm not sure that's a good reason for this.

If someone wants to show subscription information, that should just be included in Recurring Payments (on the todo list).

I'm not yet convinced there is a general enough application for this.

**Comment by danieliser** [comment]
I am including something exactly like this in EDD Donations extension. Allowing users to see their own donations to one cause or all.
That said donations isn't the only use case I could see for this. And as such it may be better in the core.

**Comment by pippinsplugins** [comment]
I'll be happy to review suggested changes to make it work if someone wants to put together a proposal.

**Comment by pippinsplugins** [comment]
@cklosowski any thoughts on this?

**Comment by cklosowski** [comment]
I'm not sure a parameter on the shortcode itself makes sense...however I think something like viewing all purchases of a product by including a `download_id` as a query string item would make sense, so you'd have `purchase-history/?download_id=123` in the url, much like we do updating a recurring subscription or viewing a license management screen...is that meeting the needs?

**Comment by chriscct7** [comment]
Closing, as after many years the number of people with this need remains 2, and I know I ended up just building a custom shortcode to do what was needed, so there doesn't appear to be any need for Core

**Comment by cklosowski** [comment]
:+1: appreciate the grooming/pruning.
