### ISSUE TITLE
Multiple nested <form> tags after edd_recalculate_taxes

### ISSUE THREAD

**Issue by bseddon** [easydigitaldownloads/Easy-Digital-Downloads#2900]
After changing the selected country, which invokes edd_recalculate_taxes, I am seeing multiple nested <form> tags in the cart area.  I am seeing this with EDD 2.2 and I've not tried earlier versions. The screen shots show the html after refreshing the checkout page and then after changing the country.  Change the country again and the <form> tags nest ever deeper.

![image](https://cloud.githubusercontent.com/assets/1221824/5570532/bbba12c8-8f7a-11e4-8da1-29d6959bf0f5.png)

![image](https://cloud.githubusercontent.com/assets/1221824/5570534/c6d8ce38-8f7a-11e4-9025-66c8d5302051.png)

I have no idea if this is an issue of any merit.  I am seeing multiple postings to my site and in the course of looking for the cause saw this behavior.

**Comment by cklosowski** [comment]
Could use some testing by others @sumobi @sdavis2702 but I think this should do the trick.

**Comment by pippinsplugins** [comment]
Pretty sure that will do it.

**Comment by sdavis2702** [comment]
That fixed it for me. :+1:

**Comment by cklosowski** [comment]
OK, PR incoming then.

**Comment by cklosowski** [comment]
@sumobi merged this into master, can you test it out and close if it looks good for you too?

**Comment by bseddon** [comment]
I still see the problem in the master branch.  The master still shows EDD version 2.2.2 but I see the change documented in this post:

https://github.com/easydigitaldownloads/Easy-Digital-Downloads/commit/dad0e9072b6a275d1888fcb8aed3fa5948b4f9c8

If I can send a screenshot let me know.

**Comment by bseddon** [comment]
I take that back.  But I'm seeing some not 100% right.  This structure:

<div id="edd_checkout_cart_wrap">
	</div>

is nested between the <table> element and the <thead> element after selecting a country.  Minor glitch but thought I'd mention it.

**Comment by cklosowski** [comment]
You can attach the screenshot of what you are seeing by dragging and dropping into a comment. If you are seeing something not right, deff let us know.

**Comment by cklosowski** [comment]
Since there was a JS update, might be good to make sure all caches are cleared, since we don't change the EDD version constant until a release, it's possibly the browser isn't pulling it right? happens to me when I change branches sometimes.

**Comment by pippinsplugins** [comment]
@bseddon Makes sure you have `SCRIPT_DEBUG` set to `true` in your wp-config.

**Comment by bseddon** [comment]
Script debugging is enabled.  The patch appears in the downloaded edd-checkout-global.js.

You can see it here: www.lyquidity.com/wordpressbeta/

Select the 'Dummy App' from the menu bar then look at the html after the checkout is freshly minted and then after changing the country.  Here what I see initially:

![image](https://cloud.githubusercontent.com/assets/1221824/5617692/5c1c1228-9509-11e4-9cf5-80c2919f676f.png)

and then after changing the country:

![image](https://cloud.githubusercontent.com/assets/1221824/5617769/0e6babc8-950a-11e4-8881-ca41687f001b.png)

I'm not pretending this is an issue just that it an anomaly in the generation of the html by the function that's recalculating taxes.

**Comment by pippinsplugins** [comment]
Ah, yep, I see what you mean. That's definitely incorrect.

**Comment by cklosowski** [comment]
ok taking a look.

**Comment by cklosowski** [comment]
So it's not in our response, we do not have that duplicate div tab with corresponding ID in the html we return. I verified that Safari...handles this 100% differently and doesn't do that either. Going to keep browser testing...this seems to be something in the way the browse JS engines are handling the input.

Will keep digging.

**Comment by cklosowski** [comment]
I verified that our HTML response doesn't contain this empty ```div``` with the correponding ID. It appears to be in the JS engine of Chrome. I tried Safari, and it doesn't do this. It actually has a div with the table inside it.

Going to keep digging see if there is an actual solution, or just browser inconsistency.

**Comment by bseddon** [comment]
That seems to fix it (using Chrome).

**Comment by cklosowski** [comment]
Gonna close this again, if anyone opposes, just reopen.
