### ISSUE TITLE
Test with Edge

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/Easy-Digital-Downloads#2904]
With Windows 10 Microsoft will be releasing a new default browser (not IE which IE 11 will still be installed for backwards compatibility) that shares a lot with IE 11 including the JavaScript and CSS engines. Since this is going to be the new default browser for a lot of people we will need to thoroughly test EDD with it. We would test assuming nothing will work and prove everything works. 

Project Spartan is expected to be publicly unveiled at a Microsoft event in February. I should be able to get an early copy of it through UF's Microsoft DreamSpark program hopefully in Jan or Feb.

**Comment by pippinsplugins** [comment]
@chriscct7 Can you test this? You're the only one :D

**Comment by chriscct7** [comment]
I'm not running Windows 10 yet, as some of UF's programs aren't compatible yet.

**Comment by webifiedgeek** [comment]
I'm running Windows 10. What do you guys need tested?

On Mon, Sep 28, 2015 at 7:19 PM, Chris Christoff <notifications@github.com>
wrote:

> I'm not running Windows 10 yet, as some of UF's programs aren't compatible
> yet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/2904#issuecomment-143899817>
> .
>



-- 
Thanks,

Blake Pounds

LBS-ink - Innovating Today for Tomorrow
www.lbsink.com

WP Jack of Trades  - WordPress Handymen
www.wpjot.com

Follow me on Twitter @SparkySpikes

**Comment by pippinsplugins** [comment]
@webifiedgeek just general tests across the system to see if there are any issues.

**Comment by chriscct7** [comment]
Given lack of support tickets, we can close this and open tickets as they get reported.

**Comment by pippinsplugins** [comment]
:+1:
