### ISSUE TITLE
Enhancement to Purchase History > User

### ISSUE THREAD

**Issue by adampickering** [easydigitaldownloads/Easy-Digital-Downloads#2905]
When clicking on the username in Downloads > Payment History, the username is not clickable and does not take you to that user inside of WordPress > Users, that is the expected behaviour, instead it filters that users purchases. I think it should have under the username, users purchases, something like:

![img](http://dl.dropbox.com/u/1657501/Screenshots/ldutvddja_sd.png)

Reason I can see this being handy, I often want to limit access/block users accounts that have fraudulently purchased a product. The current way I have to search for the user is copy the email address of the purchase and search for the account in WordPress > Users, this does not always return results as the purchaser could have changed the email address associated with the account.

Thoughts?

cc: @spencerfinnell @pippinsplugins

**Comment by pippinsplugins** [comment]
Yep, see #2548 for how we're addressing this.
