### ISSUE TITLE
API 'yesterday' request fails on first of the month

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/Easy-Digital-Downloads#2906]
As reported on the Support Forums:
https://easydigitaldownloads.com/support/topic/new-month-breaks-api-edd-iphone-app/

When it's the first of the month, the 'Yesterday' reporting in the iOS app breaks, but this stems from the API itself.

**Comment by pippinsplugins** [comment]
I'm pretty sure it only happens when `yesterday` crosses a year boundary as well.

Related to #2553

**Comment by cklosowski** [comment]
Yep issue happens in the ```$dates['year']``` entry:

```
array(4) { ["day"]=> int(31) ["m_start"]=> int(12) ["m_end"]=> int(12) ["year"]=> string(4) "2015" } 
```

It's trying to get the date of items on December 31st, of 2015...

Will come up with a fix shortly.

**Comment by cklosowski** [comment]
Yep, it's a calculation error in the way we're checking the ```$month```. We've already got logic to account for last month being ```12``` in the ```$month``` assignment:

```$month              = date( 'n', $current_time ) == 1 && date( 'd', $current_time ) == 1 ? 12 : date( 'n', $current_time );```

Then we went to determine the ```$date['year']``` and if the ```$month``` was ```1``` AND ```date( 'd', $current_time ) == 1``` we did the Year -1...but since we've already determined ```$month``` was ```12``` not ```1``` we never account for positive checks, only the negative, therefore ```December 31st, of the current year```

**Comment by pippinsplugins** [comment]
See my comment here: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/commit/84de37d89bf98c9be743fa806ad689e2a7511b4f

**Comment by cklosowski** [comment]
See my rebuttal ;-)

**Comment by cklosowski** [comment]
We can't use the ```$month``` then, to calculate the year, as we've already altered it based off the day and month combination.

**Comment by pippinsplugins** [comment]
I must be missing something because I can't see how that could work.

The month is set like this:
```
$month  = date( 'n', $current_time ) == 1 && date( 'd', $current_time ) == 1 ? 12 : date( 'n', $current_time );
```
If the day is `1` and the month is `1`, we set it to `12`, otherwise we use the current month.

That's correct.

The year is then set like this:
```
$dates['year'] = date( 'd', $current_time ) == 1 ? date( 'Y', $current_time ) - 1 : date( 'Y', $current_time );
```

There if the day is `1`, we skip back a year, otherwise we use the current year. This doesn't take the month number into account in anyway.

It will work today, but it will not work on the 1st of any month except January. On February 1, 2015, for example, we would actually get `January 31, 2014`, not `January 31, 2015`.

See what I mean?

**Comment by cklosowski** [comment]
Yes but if you include month == 1 in the condition you'll never hit the case as we've already made sure it will never be 1 above.

**Comment by pippinsplugins** [comment]
As long as we check the month independently of the `$month` var we set, we can use it.

**Comment by cklosowski** [comment]
Yep. Just thought about that. Will update soon.

**Comment by pippinsplugins** [comment]
:+1:
