### ISSUE TITLE
Earnings Over Time Custom Time Frame Bug

### ISSUE THREAD

**Issue by fpcorso** [easydigitaldownloads/Easy-Digital-Downloads#2914]
First, I have just recently switched to EDD this past month from woocommerce and I really like this plugin. It works great for my needs and is an amazing plugin.

So, getting to the point, I like to review reports and data often and I particularly like comparing this month to last month. Using a custom date range in previous eCommerce plugins, I usually am able to see the two months in the same graph. As I started using this plugin in December, I have not had the chance to do this until today. I went to the Reports page and selected Earnings to show. I selected Custom for the range.

I then chose From Dec 1 2014 and To Jan 31 2015. This does not work. The resulting graph goes from Dec 1 2014 to Dec 31 2015. I reviewed the code and believe in file
`includes/admin/reporting/graphing.php` 
there is a bug at lines 101-104 copied here:
```php
} elseif( $y == $dates['year'] ) {
$month_start = $dates['m_start'];
$month_end   = 12;
} else {
```
As you can see, the file is setting the end month to december which is creating the issue in the graph.

I would very much appreciate if you can advise if this is indeed a bug or perhaps a user error of some sort. If it is a bug, can it be fixed?

**Comment by pippinsplugins** [comment]
I encountered this the other day and can definitely confirm there is some incorrect behavior going on.

**Comment by pippinsplugins** [comment]
@cklosowski Could you dig into this?

**Comment by cklosowski** [comment]
Yep on it.

**Comment by fpcorso** [comment]
Thanks guys, I appreciate you taking a look into this and fixing!
