### ISSUE TITLE
Use `get_posts()` in `edd_get_*_by()` functions.

### ISSUE THREAD

**Issue by Mamaduka** [easydigitaldownloads/Easy-Digital-Downloads#2918]
I've noticed that `edd_get_discount_by()` (introduced by dfbf41c) and `edd_get_download_by()` (introduced by 6867e95) are using `query_posts()`. We can use `get_posts()` instead, because there's no need altering global `$wp_query` and using current method is considered as bad practice.

I checked commit logs and related issues, but wasn't able to find the reason why `query_posts()` was used. Only reference I was able to find - https://github.com/easydigitaldownloads/Easy-Digital-Downloads/pull/2126#commitcomment-5691555.

I'm happy to send PR to close this issue as well.

**Comment by pippinsplugins** [comment]
I don't recall any reason query_posts was used. :+1: to changing to get_posts.

**Comment by Mamaduka** [comment]
@pippinsplugins commit is passing unit tests, but we can still add extra assertion to check agains 'name' field - `edd_get_download_by( 'name', 'Test Download Product' );`

**Comment by cklosowski** [comment]
:+1: @Mamaduka :ballot_box_with_check:

**Comment by pippinsplugins** [comment]
Looks good to me. @cklosowski Want to merge into master?
