### ISSUE TITLE
Cart Widget item count not correct with multiple price variants

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/Easy-Digital-Downloads#2920]
When you have variable pricing, and allow multiple price ids to be added to the cart, the ```Number of items in the cart:``` count is incorrect when you add more than price id:

![image](https://cloud.githubusercontent.com/assets/1390124/5607687/2a72760a-9422-11e4-8461-af92e10a7bef.png)

Refreshing the page, everything is good, so it's just a bit of JS work I think.

**Comment by mintplugins** [comment]
While you're taking a look at this, it might be worth checking into this issue as well:
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/2926

**Comment by cklosowski** [comment]
:+1:

**Comment by pippinsplugins** [comment]
Let's get this fixed for 2.2.3.

**Comment by cklosowski** [comment]
If someone can test this out, I'll merge it.

**Comment by pippinsplugins** [comment]
Looks good to me.
