### ISSUE TITLE
Indian states dropdown needs correction in some state names.

### ISSUE THREAD

**Issue by ashokrane** [easydigitaldownloads/Easy-Digital-Downloads#2923]
Adding a new state 'Telangana', correction of spelling in 3 other state names.

**Comment by pippinsplugins** [comment]
Would you be able to provide those corrections for us?

**Comment by ashokrane** [comment]
Absolutely. I already changed it locally. But couldn't commit as I 
assume I would need the necessary permissions for that. If not, let me 
know if I need to do something else to commit.

-- 
Regards,
Vishal Kothari

Website: http://www.tychesoftwares.com/
Facebook: https://www.facebook.com/TycheSoftwares
Twitter: @tychesoftwares

**Comment by pippinsplugins** [comment]
IT'd be excellent if you could submit a pull request.

**Comment by pippinsplugins** [comment]
Fixed in https://github.com/TycheSoftwares/Easy-Digital-Downloads/commit/9d24f344c47c8aad4c749568612d80353e451cee
