### ISSUE TITLE
Disabling AJEX seems to give an Empty cart after Checkout

### ISSUE THREAD

**Issue by UnholyWhiteGuy** [easydigitaldownloads/Easy-Digital-Downloads#2929]
Hello

After disabling AJEX for the shopping cart the page the buyers are sent to after completing their purchases is Empty, not sure what's causing the issue, but found it best to report it.

Seen on this site https://jszapp.com/autohotkey/2014/make-beautiful-graphical-user-interface-15-lines-less/ but at this time I have Enabled AJEX again...

**Comment by pippinsplugins** [comment]
Please open a ticket in the support forums:
https://easydigitaldownloads.com/support

GitHub is for development tracking only.
