### ISSUE TITLE
Cart Widget item count does not respect quantities

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/Easy-Digital-Downloads#2931]
When adding multiples of an item to the cart, using the 'quantities' field, the cart widget will only show 'Items in cart 1'.

Widget shows 3 items in cart:
![screen shot 2015-01-06 at 11 29 58 am](https://cloud.githubusercontent.com/assets/1390124/5633741/7ead59c6-9597-11e4-84a1-80adc0a83514.png)

Actual Cart:
![screen shot 2015-01-06 at 11 30 10 am](https://cloud.githubusercontent.com/assets/1390124/5633743/825ed298-9597-11e4-94de-6ff370b56711.png)

**Comment by pippinsplugins** [comment]
That's "fun".

**Comment by cklosowski** [comment]
@pippinsplugins I think the issue actually is in the ```edd_get_cart_quantity()``` function, it appears to be only counting the number of ```cart items``` which is actually incorrect for a quantity count. This would be a count of products, not quantity.

Would updating this to return the sum of all quantities be an issue do you think?

**Comment by pippinsplugins** [comment]
Let's update it.

**Comment by cklosowski** [comment]
:+1:

**Comment by pippinsplugins** [comment]
Ready for additional testing.

**Comment by pippinsplugins** [comment]
Aren't this and #2926 the same issue now?

**Comment by cklosowski** [comment]
@pippinsplugins yes, they are the same issue now I believe...we created them at separate times but after refactoring the cart count function I believe they are pretty much the same.

**Comment by pippinsplugins** [comment]
Merging then.

**Comment by pippinsplugins** [comment]
As @cklosowski proposed on #2926, I like `Item Name - X @ $X.XX - remove?`

**Comment by pippinsplugins** [comment]
Closing as resolved. If anyone has additional feedback or improvements, feel free to reopen.
