### ISSUE TITLE
Show message on items that are in the cart

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#2935]
In #2788 we've modified the way that the checkout/add to cart button works on variable price products without multi option mode checked.

When the page is refreshed, if it's in the cart, we just show the checkout button without options. This might look slightly jarring to a user, so we should add some sort of messaging about the item being in the cart.

We held off on this for `2.2.3` as it's possible it could break some layouts. So we'll push it during a larger point release.

We may want to build some unit tests around this logic too, to see what results we get with the item in the cart.

**Comment by pippinsplugins** [comment]
Tagging for 2.3 so it gets some attention.

**Comment by pippinsplugins** [comment]
I'm going to go ahead and punt this to 2.4.

**Comment by cklosowski** [comment]
This gives us, with a variable priced item, a notice when it's in the cart:
![image](https://cloud.githubusercontent.com/assets/1390124/8092181/f9b64cb4-0f6c-11e5-8f6e-5e0dc1a9c44a.png)

**Comment by pippinsplugins** [comment]
What about non-variable items?

**Comment by chriscct7** [comment]
I strongly disagree with the idea of an item is in cart message. I also disagree with changing the button to say checkout (on adding item to cart, a link could be added below the button to take you to checkout). If you look at studies done by Amazon, telling people items are already in the cart is a terrible way to improve ecommerce conversion rates. Amazon for example, doesn't change the button when you add an item to the cart, because some people avoid using the quantity fields and expect that they can just push the add to cart button twice to get the same effect. As Amazon wrote about it in one of their studies, they'd rather people correct over adding of items to cart on the checkout page than discouraging multiple purchase buys.

**Comment by cklosowski** [comment]
@chriscct7 nothing changed with the checkout, that's remained the same the whole time...

@pippinsplugins The scope isn't for those, as nothing radically cahnges. The point of this ticket is that:
1) Add variable priced item to cart - The button changes to checkout, and the rpices still show
2) Refresh teh page...just the checkout button.

This was the jaring UI.

**Comment by cklosowski** [comment]
@chriscct7 Cite your sources please. I don't want references to reports done by Amazon, without...reports done by amazon ;)

**Comment by cklosowski** [comment]
We can just leave the UX as it is right now, in that a page refresh is going to have a variable priced item with no price IDs, just a checkout button.

**Comment by pippinsplugins** [comment]
@cklosowski Thanks for the clarification, I missed that.

My only concern with this is that an element is getting added around the button. As we discovered when we added the quantity field, people get really picky about the purchase buttons changing, especially on sites that use themes that have precisely styled the button and the area around the button. Added a new div could break buttons out of their intended layout.

**Comment by cklosowski** [comment]
Nothing is added around the button, this just replaces the list of radio buttons with a div that has a message.

**Comment by cklosowski** [comment]
@pippinsplugins but if @chriscct7 can get me the report from Amazon, I'd love to look over their data that supports NOT having `item in cart` messaging.

**Comment by pippinsplugins** [comment]
Agreed.

I vote we punt to 2.5 for further consideration until we have solid data to suggest which way we should go.

**Comment by cklosowski** [comment]
:+1:

**Comment by pippinsplugins** [comment]
@easydigitaldownloads/core-devs I'd like everyone's opinion on this.

**Comment by SDavisMedia** [comment]
Considering the only time this matters at all is variable pricing without multi-select, why not leave the radio buttons in place on refresh but make them read-only and still have the chosen one selected and the button changed to checkout? 

No real estate adjustments are made. It's more clear than no options and a checkout button.

**Comment by spencerfinnell** [comment]
If it's true that not changing the button/showing a message really is better I think that's definitely the best solution. 

Even without the reports though, I do think it looks a bit weird with certain buttons randomly saying "Checkout" in the list.

**Comment by pippinsplugins** [comment]
I like that proposal.

**Comment by SDavisMedia** [comment]
But that's how it was originally (a year or so ago). That proposal means still showing the radio buttons that can be selected and the button still showing that you can add one of the options to the cart. Here's the problem though... you can't.

The Amazon study is all good but it applies to variable pricing **with** multi-select and single price items. Following that study with variable pricing **without** multi-select is broken functionality.

**Comment by SDavisMedia** [comment]
Unless we're willing to remove one price option form the cart to add a different price option...

**Comment by pippinsplugins** [comment]
>>>Unless we're willing to remove one price option form the cart to add a different price option...

No.

**Comment by pippinsplugins** [comment]
There are definitely cases where multiple price options should be permitted to be purchased at once.

**Comment by SDavisMedia** [comment]
Right, that's default variable pricing. But how that button behaves once and item is added to the cart should not be the same as how multi-select buttons behave. I don't see how we can have one answer for both scenarios.

**Comment by SDavisMedia** [comment]
Oops... meant that in reverse.

**Comment by cklosowski** [comment]
As far as I know, we've had zero feedback from customer's stating that they want changes like these. @easydigitaldownloads/core-devs should we just close this out and not change anything?

**Comment by ghost1227** [comment]
I'd say leave it as is. I predict more issues than solutions if we go forward with the proposed change.

**Comment by mintplugins** [comment]
Without overwhelming customer requests it probably makes sense to leave it as is.

**Comment by ghost1227** [comment]
If it ain't broke...

**Comment by ghost1227** [comment]
That said... if we _did_ want to go this route, why not just show the existing 'Added to cart' indicator below the button?

**Comment by sunnyratilal** [comment]
Leave as is

**Comment by pippinsplugins** [comment]
Closing as wontfix.
