### ISSUE TITLE
[downloads] pagination not working properly with default permalinks

### ISSUE THREAD

**Issue by sdavis2702** [easydigitaldownloads/Easy-Digital-Downloads#2938]
Pagination links in the [downloads] shortcode is converting `&` into `#038;` in the URL when Default permalinks is used.

**Note: this does not happen when the page using the [downloads] shortcode is set as the Front Page.**

**Comment by sdavis2702** [comment]
That fixed it for me. :+1:

**Comment by mindctrl** [comment]
Same here.
