### ISSUE TITLE
Currency not converted properly with Stripe payment gateway addon

### ISSUE THREAD

**Issue by NateWr** [easydigitaldownloads/Easy-Digital-Downloads#2940]
I wasn't sure whether you'd prefer a bug report for an extension on the forums or in this repo.

When using the Stripe gateway extension v1.6.6 a lowercase currency code `gbp` is entered into the payment meta. As a result, the appropriate currency symbol is not retrieved when the currency from the payment meta is passed through to `edd_currency_symbol`. This occurs, for example, on the purchase confirmation (`shortcode-receipt.php`) page with `edd_payment_subtotal()` and edd_payment_amount`.

The problem is generated at `edd-stripe.php::152`

    'currency'     => isset( $edd_options['currency'] ) ? strtolower( $edd_options['currency'] ) : 'usd',

The Stripe gateway requires lower-case currency codes, but as far as I can tell, the `$payment_data` here never gets sent to Stripe. I had no problems when I replaced line 152 with the following:

    'currency'     => isset( $edd_options['currency'] ) ? $edd_options['currency'] : 'USD',

I believe the other instances of the same code should be left alone as they all interact with Stripe.

I looked back in the history of EDD to see if this bug was exposed due to a change in `edd_currency_symbol` or `edd_currency_filter`, but couldn't find anything. Perhaps it was an update to the Stripe addon? Either way, I suspect the fix is with the Stripe addon rather than with EDD.

Let me know if you'd prefer I post this bug report on the Stripe addon forum.

**Comment by pippinsplugins** [comment]
This is related to the Stripe Gateway and has also already been fixed by updating that line with the `edd_get_currency() helper function.

The latest version of Stripe is 2.1.

**Comment by NateWr** [comment]
Oh well that's embarrassing. I guess I should activate my license key on my dev site more often.

**Comment by pippinsplugins** [comment]
No worries :)
