### ISSUE TITLE
Items purchased with quantities incorrectly increase earnings, sales, and show wrong price in list table

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/Easy-Digital-Downloads#2942]
As reported:
https://wordpress.org/support/topic/sales-log-incorrect-when-using-quantities?replies=7

When an item is purchased with quantities, it's getting a number of purchase log entries for the quantity, and the price is being listed as the full amount.

For example, if you purchase ```2``` of the same item for ```$1.00```, you'll get two log entries for ```$2.00```

I reproduced this as seen here:
![screen shot 2015-01-07 at 7 08 59 pm](https://cloud.githubusercontent.com/assets/1390124/5657087/59c42e26-96b6-11e4-9727-57f93049420e.png)
![screen shot 2015-01-07 at 7 02 37 pm](https://cloud.githubusercontent.com/assets/1390124/5657088/600b557a-96b6-11e4-941d-ddea6bf77256.png)
![screen shot 2015-01-07 at 9 44 53 pm](https://cloud.githubusercontent.com/assets/1390124/5657092/7b7c5d18-96b6-11e4-9d59-47b69bc9ca39.png)

*UPDATE*
After some discussion, we've decided that this should happen, but we need to show the correct item price, not the total amount of the line item. We've also improved the increase/decrease of sales counts and earnings totals.

**Comment by cklosowski** [comment]
We're going to have quite a bit of a touching point. Here's what I'm thinking so far @pippinsplugins 

1. Only one sale log entry should be created (done)
2. Now we have a dilemma that we ran on the payment details screen. When we have items with quantities, we need to expose the total sale, the quantity, and the item amount. That could make the list table hairy, and old data is going to be a problem
3. We need to update the old data to be correct, somewhoe
4. If we do single log entries for quantities, the sales reports look wrong as they don't have a quantities column, or an item price column, just a total column.

I see two was we can do this...
1. We continue with the current path. Single entry for each purchase...and add a quantity postmeta attribute.
2. We fix the ```item amount``` attribute of the current method (a log entry for each number of quantity) but with a corrected value using ```$download['item_amount']``` (which is the single item price) instead of ```$download['price']``` (which is the total of all quantities added up).

**Comment by pippinsplugins** [comment]
I'm leaning towards multiple log entries with a corrected amount. The amount correction is actually super simple because we're pulling the amount from payment meta, not log meta, so we actually don't need to update any past records.

**Comment by cklosowski** [comment]
Ok, I was thinking this as well.

Less invasive to just update what amount we record on the log.

**Comment by cklosowski** [comment]
Ok @pippinsplugins I think this covers all the cases we want to. can you run through it when you get a chance. Could use some testing too.

**Comment by pippinsplugins** [comment]
@cklosowski See my comments on a couple of the commits.

**Comment by cklosowski** [comment]
@pippinsplugins updated, let me know if that's what you were thinking.

**Comment by pippinsplugins** [comment]
@cklosowski Everything looks good to me here. I also tested it with Commissions and everything tracks properly.

**Comment by cklosowski** [comment]
Great! We feel good for a PR here?

**Comment by pippinsplugins** [comment]
Yep!
