### ISSUE TITLE
Undefined Variable 'transaction_id'

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/Easy-Digital-Downloads#2949]
When viewing the payment details in admin, it's possible to have an undefined variable notice when a transaction ID isn't available from the gateway just yet.

```Notice: Undefined variable: transaction_id in /Users/cklosowski/WordPress/src/wp-content/plugins/edd-stripe/edd-stripe.php on line 1661```

**Comment by pippinsplugins** [comment]
This is a bug with EDD Stripe I think, not core. At least that notice is from Stripe.

**Comment by cklosowski** [comment]
ah, I see what you mean. i'll repoen the stripe one.
