### ISSUE TITLE
EDD is tracking - need more info

### ISSUE THREAD

**Issue by slaFFik** [easydigitaldownloads/Easy-Digital-Downloads#2950]
Would be nice to have an explanation of how do you use tracked information, and which exactly data is sent to your servers.

I'm talking about this:
`Allow Easy Digital Downloads to track plugin usage? Opt-in to tracking and our newsletter and immediately be emailed a 20% discount to the shop for Extensions and Themes. No sensitive data is tracked.`

I tried to find information on site blog and in plugin admin area - failed.

Is it possible to have a link somewhere in plugin admin area?

**Comment by slaFFik** [comment]
I tried to find information on site blog and in plugin admin area - failed.

**Comment by chriscct7** [comment]
EDD is designed for simplicity and no-frills. Our design is influenced by the WordPress Core philosophy of only including things that the majority of users will actually use. 

We're not a fan of having links that the extreme vast majority of people  won't click on. If we weren't open source, I could see where this might be useful, but we're open source. There's a file called tracking.php that clearly shows what information is sent during tracking: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/admin/tracking.php#L66. 

Additionally. if people have questions about this, they're more than welcome to ask in our support forum :-)

**Comment by sdavis2702** [comment]
FYI, @slaFFik, I'm on the task of writing this documentation. Like @chriscct7 said, it most likely won't be linked in the admin area. But your point is well taken and I'll get a doc written up for sure. :+1:

**Comment by slaFFik** [comment]
@SDavisMedia I see that the EDD documentation was not updated with the info of what is tracked.
And yes, I saw that info in the code, but most of your users won't dive that deep.

**Comment by SDavisMedia** [comment]
@slaFFik Thanks for the reminder. http://docs.easydigitaldownloads.com/article/1419-what-information-will-be-tracked-by-opting-into-usage-tracking
