### ISSUE TITLE
Lowercase email addresses

### ISSUE THREAD

**Issue by dannyvankooten** [easydigitaldownloads/Easy-Digital-Downloads#2953]
I've had a couple of issues with custom add-ons where I was comparing email addresses and had to lowercase the values before executing the statement. 

Would it be a good idea to lowercase all email addresses before inserting them? Normalizing data is always good and since there's no real need for uppercased characters in an email address. :smile:

**Comment by cklosowski** [comment]
As the core WordPress does not normalize any emails before adding them...neither should EDD, in my opinion. If you insert a user in WordPress' default interfaces, capital letters are allowed, and thus, we should never alter that data either.

As long as it passes the ```is_email``` and ```email_exists``` checks, I see no issues with it the way it is.

@pippinsplugins?

**Comment by cklosowski** [comment]
And I did verify Core allows this locally first :) I wanted to make sure:

![image](https://cloud.githubusercontent.com/assets/1390124/5703861/ca6a4ada-9a39-11e4-8e10-85fc58a4e49d.png)

**Comment by pippinsplugins** [comment]
I agree with @cklosowski. We should not be modifying emails.
