### ISSUE TITLE
Can't change default price w/ variable prices

### ISSUE THREAD

**Issue by dannyvankooten** [easydigitaldownloads/Easy-Digital-Downloads#2958]
Clicking another price and saving the download just reverts to the second price for me. Not sure what the default price actually does but just thought I'd mention it here.

![image](https://cloud.githubusercontent.com/assets/885856/5734393/6df5124e-9be7-11e4-8a74-4b0a2973f6c7.png)

**Comment by pippinsplugins** [comment]
Does it happen on brand new products as well? I think we may have just fixed this for 2.2.3 and it only affected older products that were created before 2.2.

Possibly related to #2874

**Comment by cklosowski** [comment]
Yes, it was exactly that @pippinsplugins, fixed in 2.2.3 and only affected products created before 2.2.

**Comment by pippinsplugins** [comment]
:+1: going to close as a duplicate then. @dannyvankooten If you notice it still not working after 2.2.3 (going out today), let us know.
