### ISSUE TITLE
edd_empty_cart doesn't appear to be working as expected.

### ISSUE THREAD

**Issue by danieliser** [easydigitaldownloads/Easy-Digital-Downloads#2959]
How could this be done on the fly? I need to do this based on an if statement.

`/**
 * Limit cart to one Item if donation is added to cart. 
 */
function edd_donations_limit_one_item_checkout( $download_id, $options ) {
	if( edd_get_cart_quantity() >= 1 && edd_download_is_donation( $download_id ) ) {
		edd_empty_cart();
	}
}

add_action( 'edd_pre_add_to_cart', 'edd_donations_limit_one_item_checkout', 10, 2 );`

I assumed this would do the trick, but even though I modified the core edd_empty_cart to do a var_dump and be sure it was firing properly. It still didn't work even though the function ran.

I even went as far as adding edd_empty_cart to a plugins_loaded function and the cart still shows full on refresh.

Manually removing works fine. But I cant get the function to clear the actual cart contents.

**Comment by cklosowski** [comment]
Are you only wanting to restrict the cart to a single item?

**Comment by cklosowski** [comment]
Check out this snippet in the library, and make your changes from there:

https://github.com/easydigitaldownloads/library/blob/master/checkout/one-item-checkout.php

**Comment by pippinsplugins** [comment]
Note: the one liner above will only work once 2.2.3 is out due to this: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/commit/d2ef55ab8af28c2a70daee192ab82bdf3485ab48

It wasn't emptying because the cart contents were retrieved before `edd_pre_add_to_cart` fired.

**Comment by danieliser** [comment]
@cklosowski - Thanks for the response, yea that is what I started with, but as @pippinsplugins pointed out it doesn't work with the current release.

Yea, It seems that EDD->sessions isn't available yet during that hook, so even though the function fires properly, the session cart remains.

Does the nightly build address this already? I ask because it may be released before the EDD Donation extension is released, meaning I can leave my code as is and move on once I test with nightly,

If not I will just use edd_pre_add_to_cart_contents to filter out contents if the new item is a donation.

**Comment by cklosowski** [comment]
We just pushed 2.2.3 about an hour ago, so you should be ok.

**Comment by danieliser** [comment]
Lol faster than light. Very nice. will update immediately. I'm guessing though that that would make the requirement for EDD Donations to have v2.2.3 installed.

In that case to allow more backward compatibility I may do a version check there and do it both ways based on version.

**Comment by pippinsplugins** [comment]
That's correct, 2.2.3 will be required.

**Comment by danieliser** [comment]
Is it safe to assume I can use edd_pre_add_to_cart_contents in versions previous to 2.2.3? How far back will that go for version compatibility?

**Comment by danieliser** [comment]
NVM can just to a history or blame. Ill figure it out.
