### ISSUE TITLE
Chrome "my-plugin.zip is not commonly downloaded and could be dangerous"

### ISSUE THREAD

**Issue by jchristopher** [easydigitaldownloads/Easy-Digital-Downloads#2964]
This is the first time I received a report about this, but am curious if anyone else has seen it. I just got a note from a customer indicating they got an error message in Chrome regarding a zip download via EDD. Upon clicking the download link Chrome stepped in and said

> my-plugin.zip is not commonly downloaded and could be dangerous

There are two buttons below the red message, *Keep* and *Discard*. The customer was nervous enough to request a refund and after seeing the screenshot of the message I don't blame them. I did ask them about how the message showed up, figuring it was some sort of overly-suspicious browser plugin or something, but after Googling a bit I found this thread: https://productforums.google.com/forum/#!topic/webmasters/kaJ0cSw91Ng — in case that link goes dead at some point the interesting/accepted answer is this:

> Just speculating, but I would look at the content type.
> Your url says > Content-Type: application/x-zip-compressed
> Wordpress download zip says > Content-Type: application/zip

I've never seen this issue personally, and I've downloaded my own plugin in testing countless times, and no other customer has reported it, but I wanted to post here in case it comes up in the future (maybe Chrome is getting more aggressive?) or others have seen the issue as well (although I didn't see another Issue before posting this).

**Comment by pippinsplugins** [comment]
I've seen this one time.

I bet you're right on the content type issue.

**Comment by cklosowski** [comment]
This seems odd...here's our ```.zip``` filetype:

```
case 'zip'      : $ctype = "application/zip"; break;
```

Have we verified it's not an odd server config causing that specific content type..and Chrome is the only one balking currently?

**Comment by jchristopher** [comment]
My site is on Pagely; not sure if I have any ability to change anything should it be a server problem.

**Comment by pippinsplugins** [comment]
EDD, AffiliateWP, and PippinsPlugins are also on Pagely. I haven't seen any reports of it yet.

Do any of your other EDD extensions or plugins modify the file download behavior at all?

**Comment by cklosowski** [comment]
Well depending on when accounts were provisioned (hosting companies don't always run the exact same stack on every account...over time it evolves and sometimes they roll out changes to different systems) they may not have the same configuration as each other.

Is there somewhere we can replicate this? I'd love to look at the rest of the headers.

**Comment by pippinsplugins** [comment]
@jchristopher Are you able to reliably replicate this on your site?

**Comment by jchristopher** [comment]
No, I have't ever been able to reproduce it, and only had this one report from a single customer.

**Comment by pippinsplugins** [comment]
Ok. I'm going to punt it to 2.4 for further consideration. If we see it happen again and con look at the exact headers sent then, we may be able to fix it earlier.

**Comment by pippinsplugins** [comment]
We haven't seen this again. I'm going to close for now as invalid. Re-open if it surfaces again.

**Comment by jchristopher** [comment]
Me either. Will do. 

Jonathan Christopher
