### ISSUE TITLE
Select2 on Add Discounts Page Placeholder shows as selected option

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/Easy-Digital-Downloads#2965]
On new installs of EDD, when creating a discount, there is a bug since 2.2.3 in the select2 code that makes "No Downloads Found" to show like this:

![Bug in EDD 2.3](http://sc-cdn.scaleengine.net/i/65f45af4ef4a36803a97e8e55a090e10.png)

On installs with EDD already installed (and thus already having downloads) "select a download" also appears as an option when you view the discount, and if you're trying to make a discount that works for all products, that text will never match a download (so it will never be valid)

So when you save either of these discounts, they will never match. What this means is on fresh EDD 2.2.3 installs and new coupons for existing EDD installs, the coupons will always be invalid, even if they should be valid because "no downloads found" will never match anything.

Props to @syedbalkhi for the initial find & report.

**Comment by pippinsplugins** [comment]
Noticed this yesterday too.

**Comment by pippinsplugins** [comment]
^ That should fix it but need to make sure it doesn't cause any unintended side effects.

**Comment by pippinsplugins** [comment]
No issues that I can find, closing.
