### ISSUE TITLE
Update to HTTP protocol needed?

### ISSUE THREAD

**Issue by sumobi** [easydigitaldownloads/Easy-Digital-Downloads#2966]
A customer has suggested that we should update our HTTP protocol from 1.0 to 1.1 in the `includes/gateways/libraries/paypal/ipnlistener.php` file.

    $header .= "POST /cgi-bin/webscr HTTP/1.0\r\n";

Apparently this has been recommended by PayPal since last year.

**Comment by pippinsplugins** [comment]
Yes we need to take care of this.

**Comment by cklosowski** [comment]
The file mentioned doesn't exist...but we do call them on ```HTTP/1.0```

```
		$remote_post_vars      = array(
			'method'           => 'POST',
			'timeout'          => 45,
			'redirection'      => 5,
			'httpversion'      => '1.0',
			'blocking'         => true,
			'headers'          => array(
				'host'         => 'www.paypal.com',
				'connection'   => 'close',
				'content-type' => 'application/x-www-form-urlencoded',
				'post'         => '/cgi-bin/webscr HTTP/1.1',

			),
			'sslverify'        => false,
			'body'             => $encoded_data_array
		);
```

Will get this fixed.
