### ISSUE TITLE
[downloads] shortcode "category" parameter broken on parent categories

### ISSUE THREAD

**Issue by sdavis2702** [easydigitaldownloads/Easy-Digital-Downloads#2970]
An empty parent category does not show the downloads of its children with the `[downloads]` shortcode. Ticket: https://easydigitaldownloads.com/support/topic/shortcode-for-parent-category-stopped-working/

I've replicated the issue (and confirmed that it worked on 2.2.2 and before) and found that it takes the `relation` parameter to fix it. Anything *but* `AND` can be used and it'll work properly... which is right in line with [this change](https://github.com/easydigitaldownloads/Easy-Digital-Downloads/commit/efbc23013111596b42bea89f9093d4a2c86ee3cc?diff=unified) for 2.2.3.

**Comment by pippinsplugins** [comment]
I bet we aren't defaulting the new parameter.

**Comment by pippinsplugins** [comment]
Yep, we're explicitly setting it to only pull from the specified IDs, not the parents: 
```
'operator' => 'AND' === $atts['relation'] ? 'AND' : 'IN'
```

**Comment by pippinsplugins** [comment]
I think ^ might fix it.

**Comment by sdavis2702** [comment]
So with that adjustment, the `relation` parameter 1) only matters if it's being used [no default] and 2) if used, will only matter to specified IDs. Am I understanding that correctly?

**Comment by pippinsplugins** [comment]
We want the default behavior to be `OR`. Unless I'm wrong, specifying it as `IN` as we are now makes it not pull products from the parent categories, since the posts aren't technically assigned to those terms. I _think_ we fix this by getting rid of `IN` and only setting it to `AND` if the `relation` parameter is present and set to `AND`.

I may be completely wrong though. The arguments for tax_query are a bit confusing.

**Comment by sdavis2702** [comment]
Okay here's what I'm finding based on the code used. For my tests, I have 1 parent category and 2 child categories.

**Parent category:** EMPTY itself, 5 total downloads from children
**Child category one:** 4 downloads
**Child category two:** 2 download
_The two child categories share **1** of the aforementioned downloads making the total 5._

---

#### 2.2.2 and prior:
_(no `operator` key in the array)_

**[downloads category="parent-download-category"]**
:white_check_mark: Expected/Results: All 5 downloads display from child categories.

**[downloads category="download-category-one"]**
:white_check_mark: Expected/Results: All 4 downloads display.

**[downloads category="download-category-two"]**
:white_check_mark: Expected/Results: Both downloads display.

**[downloads category="download-category-one,download-category-two"]**
:white_check_mark: Expected/Results: All 5 downloads display.

**[downloads category="download-category-one,download-category-two" relation="AND"]**
Expected: 1 shared download displays.
:x: Results: All 5 downloads display.

**[downloads category="download-category-one,download-category-two" relation="OR"]**
:white_check_mark: Expected/Results: All 5 downloads display.

---

#### 2.2.3 (1st change):
Code adjustment: `'operator' => 'AND' === $atts['relation'] ? 'AND' : 'IN'`

**[downloads category="parent-download-category"]**
Expected: All 5 downloads display from child categories.
:x: Results: No downloads found.

**[downloads category="download-category-one"]**
:white_check_mark: Expected/Results: All 4 downloads display.

**[downloads category="download-category-two"]**
:white_check_mark: Expected/Results: Both downloads display.

**[downloads category="download-category-one,download-category-two"]**
Expected: All 5 downloads display.
:x: Results: 1 shared download displays.

**[downloads category="download-category-one,download-category-two" relation="AND"]**
:white_check_mark: Expected/Results: 1 shared download displays.

**[downloads category="download-category-one,download-category-two" relation="OR"]**
:white_check_mark: Expected/Results: All 5 downloads display.

---

#### 2.2.3 (2nd change):
2nd Code adjustment: `'operator' => 'AND' === $atts['relation'] ? 'AND' : ''`

**[downloads category="parent-download-category"]**
Expected: All 5 downloads display from child categories.
:x: Results: No downloads found.

**[downloads category="download-category-one"]**
:white_check_mark: Expected/Results: All 4 downloads display.

**[downloads category="download-category-two"]**
:white_check_mark: Expected/Results: Both downloads display.

**[downloads category="download-category-one,download-category-two"]**
Expected: All 5 downloads display.
:x: Results: 1 shared download displays.

**[downloads category="download-category-one,download-category-two" relation="AND"]**
:white_check_mark: Expected/Results: 1 shared download displays.

**[downloads category="download-category-one,download-category-two" relation="OR"]**
Expected: All 5 downloads display.
:x: Results: ALL downloads from completely unrelated categories!

**Comment by pippinsplugins** [comment]
Ah, just found this mention on the codex:
```
relation (string) - The logical relationship between each inner taxonomy array when there is more than one. Possible values are 'AND', 'OR'. Do not use with a single inner taxonomy array.
```

**Comment by pippinsplugins** [comment]
@sdavis2702 Could you give it another round of tests on `issue/2970`? I think it's all working so long as you don't use `exclude_tags` or `exclude_categories`. For some reason those always make it return zero results and I'm not sure why yet.

**Comment by sdavis2702** [comment]
Will do!

**Comment by sdavis2702** [comment]
Alright these results are _slightly_ different from everything above but the only part screwing up is comma separated categories:

`[downloads category="download-category-one,download-category-two"]`

It's acting as if "AND" is the assumed relationship and only showing what the two categories have in common.

---

#### 2.2.3 (1st change):
Code adjustment: `'operator' => 'AND' === $atts['relation'] ? 'AND' : 'IN'`

**[downloads category="parent-download-category"]**
:white_check_mark: Expected/Results: All 5 downloads display from child categories.

**[downloads category="download-category-one"]**
:white_check_mark: Expected/Results: All 4 downloads display.

**[downloads category="download-category-two"]**
:white_check_mark: Expected/Results: Both downloads display.

**[downloads category="download-category-one,download-category-two"]**
Expected: All 5 downloads display.
:x: Results: 1 shared download displays.

**[downloads category="download-category-one,download-category-two" relation="AND"]**
:white_check_mark: Expected/Results: 1 shared download displays.

**[downloads category="download-category-one,download-category-two" relation="OR"]**
:white_check_mark: Expected/Results: All 5 downloads display.

**Comment by pippinsplugins** [comment]
Is that one wrong? The default condition is AND, not OR. Perhaps the
default should be OR?

**Comment by sdavis2702** [comment]
Hmmm... good question. I always felt like OR was default for comma separated terms (hence my expectations on the 2.2.2 & prior section above).

I don't know... this is tricky. If I have five terms in a category and I want to display one of them, I put it in the `category` parameter. If I want to display two of those five terms, I naturally think to add it to the `category` parameter comma separated. There's nothing telling me that now I have to add the `relation` parameter with an OR value. I don't naturally feel like the comma separation narrows down the results... I feel like it should add more results (the downloads from the newly added terms in the parameter).

As a user, how do you see it?

**Comment by pippinsplugins** [comment]
I think I'm with you. I vote that `OR` be default.

**Comment by sdavis2702** [comment]
I agree totally.

**Comment by sdavis2702** [comment]
Alright, @cklosowski, just changing the default relation to `OR` should be the last of this thing. I just tested it locally and all results match expectations. :+1:
