### ISSUE TITLE
Duplicate array keys in country codes.

### ISSUE THREAD

**Issue by shazahm1** [easydigitaldownloads/Easy-Digital-Downloads#2971]
As noted in my comments here https://github.com/easydigitaldownloads/Easy-Digital-Downloads/commit/e96726a46238f0483f5b9908b8fc21384e2b396c#commitcomment-9331626 and here https://github.com/easydigitaldownloads/Easy-Digital-Downloads/commit/139196a76ffe94009a2550610d76978328dd9471#commitcomment-9331749 there are instances where there are duplicate array keys.

**Comment by cklosowski** [comment]
@shazahm1 does this look right to you?

**Comment by shazahm1** [comment]
That fixes the one. What about the other?

**Comment by cklosowski** [comment]
That leaves us with a single CI entry in they array. Is that not what your bug was for?

**Comment by cklosowski** [comment]
There are two commits. One for the function to only contain one CI key and the other is the unit test to verify that it only contains the one key.

**Comment by cklosowski** [comment]
There are two commits. One for the function to only contain one CI key and the other is the unit test to verify that it only contains the one key.

**Comment by shazahm1** [comment]
Yes, I saw both commit ... maybe I should have filed to bug reports, sorry.

There is a dupe array key in the edd_get_indian_states_list() function as I commented here:
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/commit/139196a76ffe94009a2550610d76978328dd9471#commitcomment-9331749

My guess the intention was to correct a misspelling.
