### ISSUE TITLE
EDD_Payments_Query download arg does not work.

### ISSUE THREAD

**Issue by danieliser** [easydigitaldownloads/Easy-Digital-Downloads#2973]
Consider the following example

	$args = array();
	if( !empty( $_REQUEST['donation_cause'] ) ) {
		$args['download'] = $_REQUEST['donation_cause'];
	}
	$payment_query = new EDD_Payments_Query( $args );
	$payments = $payment_query->get_payments();

This does not work. I have even manually dumped the args and it is there. The EDD_Payments_Query->download function does run, but returns no $sales inside the call to $edd_logs.

My real code is a bit more complex but even this completely basic example fails to return anything.

I am building a Donation History with this, and allowing filtering by each download/cause as well as end of year tax receipts.

On that note would any of the other API Classes be better suited for this, though this is not relevant as the Payments Query is not working as expected from inline documentation.

**Comment by cklosowski** [comment]
@danieliser try passing the $args in to the ```$payments = $payment_query->get_payments();``` line. let me know if that fixes it for you.

**Comment by danieliser** [comment]
@cklosowski I don't think that will make a difference. the get_payments function doesn't accept any arguments. I tried it anyways and it didn't work.

https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/payments/class-payments-query.php#L138

Also I can get list of all donations using my extensions of the Payment_Query class, which adds an is_donation parameter and filters only those that include a donation. But feeding nothing but download = ID# does nothing, same result when I add it to an already working function.

**Comment by danieliser** [comment]
Entering a valid ID# as the only parameter or an extra parameter causes 0 result during all of my testing.

**Comment by cklosowski** [comment]
This is working for me:
```
$args = array( 'download' => 514 );
$payments_query = new EDD_Payments_Query;
$payments = $payments_query->get_payments( $args );
```

Gives me ``array(20)...```, 20 purchases.

**Comment by cklosowski** [comment]
Why are we opening two issues that seemingly are related to your same 'problem'? IE: #2975. Does my suggestion work or no?

**Comment by danieliser** [comment]
Ok your example isn't working for me. It does return results, but my results sets are === between the following codes.

	$args = array( 'download' => 67 );
	$payments_query = new EDD_Payments_Query;
	$payments = $payments_query->get_payments( $args );

	$payments_query = new EDD_Payments_Query;
	$payments = $payments_query->get_payments();

Also no this is not in reference to that ticket. That one is for further extending the query builder. 

	if( !isset( $payment_query->args['has_donation'] ) ) {
	    $payment_query->args['has_donation'] = true;
	}

The above code is my current workaround without that filter. It is how I do what needs to be done without it in place. With that filter in place I can do it via the filter.

**Comment by pippinsplugins** [comment]
Test it without your Donations plugin active, just to make sure nothing there is interfering.

**Comment by danieliser** [comment]
Just tested it thoroughly. Disabled all plugins except a fresh copy of EDD master branch.

Getting the same result set. Still 0 diffs between them. But you can see that the get_payments() function doesn't accept any args so that would basically do nothing.

**Comment by danieliser** [comment]
This is the code im using for testing. If you see something I'm overlooking happy to close this.

	add_action('init', function(){
		$args = array( 'download' => 67 );
		$payments_query = new EDD_Payments_Query;
		$payments1 = $payments_query->get_payments( $args );

		$payments_query = new EDD_Payments_Query;
		$payments2 = $payments_query->get_payments();

		echo '<pre>'; var_export($payments1); echo '</pre>'; 
		echo '<pre>'; var_export($payments2); echo '</pre>'; 

	});

**Comment by pippinsplugins** [comment]
Do you have at least two products that have sales?

**Comment by danieliser** [comment]
Yea, I have 5 products. 2 non donations, 3 donations. I have about 30 transactions including various mixtures of donations, single donation purchases, mixed cart purchases with non donations etc. But the download with id 67 should only show up for 1 sale as that is all it has. Just created it for testing now.

**Comment by danieliser** [comment]
I was able to extend EDD_Payments_Query to load only purchases with donations, and user id etc. But I would like to extend it to show only download x if possible.

But at this point even if there is another way to do what i'm after this download arg doesn't seem to do anything that I can tell.

**Comment by pippinsplugins** [comment]
The `edd_pre_get_payments` action is the keys to the kingdom for all of this.

**Comment by danieliser** [comment]
Im confused? Im not hooking it in any way at this point. All plugins except EDD deactivated.

**Comment by pippinsplugins** [comment]
Try this: go to Downloads > Payment History. By default, it shows all sales. Yes? Good, now enter `#67` in the search field. Does it limit the sales to just that product? If so, EDD core works fine and something is wrong with your plugin's code. EDD core uses the exact same class for showing payments in payment history.

**Comment by danieliser** [comment]
No results at all for search. And as I said, at this point its just EDD and the 2015 wp theme.

**Comment by danieliser** [comment]
From the sound of it it should be working. I'm gonna do a fresh install of wp and edd from wp repo and then will have to add transactions and products but it will rule out anything on my end.

**Comment by danieliser** [comment]
Ok so after testing with fresh install and it working I'm back to square 1 with the other site. So the question then becomes, what would cause it to not find them with nothing activated and a fresh copy of EDD. I do see that new transactions are showing up so my new question is this.

What could be interfering with this parameters searching. I'm assuming its missing meta data, but where is that info assigned in the insert_payment process. It may be a malfunctioning filter, but I can't find where a download_id is assigned as post parent to a payment.

Thanks for your help guys. Closing the issue.

**Comment by sumobi** [comment]
@danieliser a stab in the dark here, but were your other payments made while in EDD test mode?

**Comment by danieliser** [comment]
@sumobi, that may be true and I have disabled it since during testing but would I not be able to query against test payments either?

IE would it not be able to search test payments while in test mode?

**Comment by danieliser** [comment]
And on that note, why does every query ive tried including using ending & beginning work, but fails to filter out by download id or ids

**Comment by sumobi** [comment]
Not sure, make a payment in test mode and see if you can query it. I vaguely remember not being able to do so with my test payments.

**Comment by danieliser** [comment]
They were queryable but not when passing in $args['download'] = 67. Passing any ID or array of IDs resulting in no results or a result set equal to if the download ID hadn't been passed.
