### ISSUE TITLE
Make EDD_Payments_Query default args extendable with new filter.

### ISSUE THREAD

**Issue by danieliser** [easydigitaldownloads/Easy-Digital-Downloads#2975]
Currently I am having to do things like this.

	$payment_query = new EDD_Payments_Query( $args );

	if( !isset( $payment_query->args['has_donation'] ) ) {
		$payment_query->args['has_donation'] = true;
	}

	$payments = $payment_query->get_payments();

I propose adding a new filter `edd_payments_query_default_args` which will allow extending of the allowed args.

This works much better for extending it when coupled with extra actions on `edd_pre_get_payments` and 'edd_payment' filter.

PR to follow.

**Comment by pippinsplugins** [comment]
Adding a filter is a bad idea, in my opinion. It makes it too easy for extensions to break some default behavior that is not designed to be flexible in that way.

If you want to set `has_donation`, just use the `edd_pre_get_payments` hook, exactly like you would `pre_get_posts`.

**Comment by danieliser** [comment]
So just hook in there and add extra args to the instance then? Ill give that a shot. This would simply allow extending it without writing a new class. Though a new extending class sounds like a better option in this case as I can put the logic there as well.

Ill close this one for now and see what I can do. Thanks.

**Comment by pippinsplugins** [comment]
Yep that'll do it.
