### ISSUE TITLE
Missing ID Check in Sales Log Table $amount assignment.

### ISSUE THREAD

**Issue by danieliser** [easydigitaldownloads/Easy-Digital-Downloads#2978]
Looking at these 3 lines here.  https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/admin/reporting/class-sales-logs-list-table.php#L302

This doesn't seem correct. It will default to showing the last items price not the correct items price.

This became apparent when using custom prices with the bonus product enabled. The second item in cart has cost of 0.00 and in the sales log table it shows $0.00 even though I just entered and test payed $1000.00.

I fixed this by changing it to this.

	foreach ( $cart_items as $item ) {
		if( $item['id'] == $log->post_parent ) {
			$amount = isset( $item['item_price'] ) ? $item['item_price'] : $item['price'];
		}
	}

Found this because I was using this code as a reference for another function. The above does resolve the issue both in sales log report table and in my usage.

**Comment by pippinsplugins** [comment]
That definitely appears to be wrong.

**Comment by danieliser** [comment]
Ok will submit a PR for it

**Comment by danieliser** [comment]
Just tested. looks good on my end.

**Comment by pippinsplugins** [comment]
:+1:
