### ISSUE TITLE
Undefined index notice on API / stats call with filter

### ISSUE THREAD

**Issue by barrykooij** [easydigitaldownloads/Easy-Digital-Downloads#2979]
**API URL:**
/edd-api/stats/?key=x&token=y&type=earnings&date=range&startdate=20150101&enddate=20150131

**Notice:**
Backtrace from warning 'Undefined index: earnings' at x/wp-content/plugins/easy-digital-downloads/includes/class-edd-api.php 1013:

**Backtrace**
x/wp-content/plugins/easy-digital-downloads/includes/class-edd-api.php 336 calling get_stats()
calling process_query()
x/wp-includes/plugin.php 496 calling call_user_func_array()
x/wp-includes/template-loader.php 12 calling do_action()
x/wp-blog-header.php 16 calling require_once()
x/index.php 17 calling require()

**Comment by pippinsplugins** [comment]
Any special PHP configuration here? This is an odd one because that notice is happening when the `earnings` key in the `$earnings` array is created. Setting the key shouldn't throw a notice like that.

**Comment by barrykooij** [comment]
No that I know of, PHP 5.4. I got quite a few notices. Want them all?

**Comment by pippinsplugins** [comment]
Yeah let's see them.

**Comment by chriscct7** [comment]
Verified. You can't manipulate an index before it's been instantiated. On that line, the first time it's run, ['earnings']['date]' hasn't been instantiated, and therefore you can't += add to it.

P.O.C: http://sandbox.onlinephpfunctions.com/code/b9fd2c6ea19dce6cf2300befdee826e1de7dc88e

The earnings index should be instantiated outside the while loop, like $earnings['earnings'] = array();
Inside the while loop, you should use array_key_exists, or isset and if the key doesn't exist/isset then instantiate the key for the unique date to 0, then add earnings to it.

``` php
$earnings['earnings'] = array();
while ( $d <= $num_of_days ) :
	$earnings_stat = edd_get_earnings_by_date( $d, $i, $y );
        if ( !isset( $earnings['earnings'][ date( 'Ymd', strtotime( $y . '/' . $i . '/' . $d ) ) ] ){
            $earnings['earnings'][ date( 'Ymd', strtotime( $y . '/' . $i . '/' . $d ) ) ] = 0;
        }
	$earnings['earnings'][ date( 'Ymd', strtotime( $y . '/' . $i . '/' . $d ) ) ] += $earnings_stat;
	$total += $earnings_stat;
	$d++;
endwhile;

// if you don't want the earnings key to be set if there's no earnings then do:
if ( !$total ){
   unset( $earnings['earnings'] );
}
```

**Comment by chriscct7** [comment]
The same situation also needs the same fix here: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/class-edd-api.php#L913

**Comment by barrykooij** [comment]
Wow, I totally forgot to reply to this issue :(

Still need my logs?

**Comment by chriscct7** [comment]
@barrykooij Yep :)

**Comment by chriscct7** [comment]
I'll start on a PR for the 2 I mentioned above, and then a separate ones for any more we find in Barry's logs

**Comment by pippinsplugins** [comment]
@chriscct7 Think you could get a PR submitted today?

**Comment by chriscct7** [comment]
@pippinsplugins Yes

**Comment by chriscct7** [comment]
I'm going to write this where the earnings key is unset if there's no earnings. If you want to keep it as an empty array if no earnings just let me know on the pr

**Comment by chriscct7** [comment]
Pull for the 2 issues sent as #3110. @barrykooij did you have those log files?

**Comment by pippinsplugins** [comment]
I've been testing this on pippinsplugins.com and it appears to be working well.
