### ISSUE TITLE
File size not sent to the browser during file download

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#2983]
It seems that the size of the file is not being properly sent to the browser when a file is being downloaded, as reported [here](https://easydigitaldownloads.com/support/topic/server-isnt-reporting-file-size-for-downloads/).

We should see if we can fix this.

**Comment by cklosowski** [comment]
Yeah setting a header of ```Content-Length``` should be what we need to do here.

**Comment by cklosowski** [comment]
@pippinsplugins Are there any plugins/extensions that would create an RSS feed of audio files that would be deemed as a 'podcast'? Wondering if we would even work with a ```Partial-Content``` request. I'm sure it's a super small edge case...but curious if we should add it here as well.

**Comment by pippinsplugins** [comment]
Not That I'm aware of.

**Comment by cklosowski** [comment]
Looks good to me, I'll merge the PR
![screen shot 2015-02-06 at 10 15 02 am](https://cloud.githubusercontent.com/assets/1390124/6083852/38140766-ade9-11e4-9b34-ed0004018ed4.png)
