### ISSUE TITLE
EDD_Payment_Stats triggers errors with no date passed.

### ISSUE THREAD

**Issue by danieliser** [easydigitaldownloads/Easy-Digital-Downloads#2984]
The following example returns errors with all debug enabled.

	$stats = new EDD_Payment_Stats;
	$total = $stats->get_earnings( 67 );

Warning: array_key_exists(): The first argument should be either a string or an integer in \wp-content\plugins\easy-digital-downloads\includes\class-edd-stats.php on line 141

The problem seems to be that EDD_Payment_Stats::get_earnings() defaults parameters for $start_date & $end_date to false.

After some digging I found this https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/class-edd-stats.php#L107

		if( empty( $_start_date ) ) {
			$this->start_date = 'this_month';
		}

		$this->start_date = $_start_date;

Which looks like it should be:

		if( empty( $_start_date ) ) {
			$_start_date = 'this_month';
		}

		$this->start_date = $_start_date;

This is just prior to the call to convert_date() which triggers the error when `false` is passed to array_key_exists.

**Comment by danieliser** [comment]
This fixes my issue.

**Comment by danieliser** [comment]
Looking at the rest of that same function where the error begins, it could also be replaced as:

		if( empty( $_start_date ) ) {
			$this->start_date = 'this_month';
		}
		else {
			$this->start_date = $_start_date;
		}

Your preference.

**Comment by pippinsplugins** [comment]
We can get this fixed for 2.2.5.

**Comment by danieliser** [comment]
Ok, NP. I will get a PR submitted.

**Comment by danieliser** [comment]
Preference for fix? Assuming the second.

**Comment by pippinsplugins** [comment]
Mobile so haven't read too closely. Pick one and I'll let you know when testing :)

**Comment by pippinsplugins** [comment]
@danieliser Still interested in writing up a PR for this?

**Comment by danieliser** [comment]
Absolutely. Will submit it today.

**Comment by danieliser** [comment]
Is there any reason we can't simplify this function? By that i mean currently it sets $this->start_date and then 2 lines later sets $this->start_date again using $this->convert_date.

I feel like it could be simplified to check for empty values and then set $this->start_date at the end only.

**Comment by danieliser** [comment]
I wrote it up in a more simplified manner. Since there are no other methods called between setting $this->start_date and setting it again later in the function there is no need to set the class variables twice.

I rewrote it to simply check for empty values before setting the class variables with convert_date.

**Comment by danieliser** [comment]
PR made. Sorry for the extra commit. Ended up having to reset my entire repo to get rid of some nasty looking & glitched commits.

**Comment by pippinsplugins** [comment]
Great, will review soon.

**Comment by pippinsplugins** [comment]
@danieliser Think you could get the PR re-submitted?

**Comment by danieliser** [comment]
Yes sorry, done.
