### ISSUE TITLE
NGINX Cross-Domain files are corrupted

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/Easy-Digital-Downloads#2985]
I host a file-for-delivery on Amazon. It worked great on Apache - but I just moved to NGINX and it no longer works. The files download but are corrupted.

I removed the lines Pippin recommended in the support ticket below and it fixed the issue:
https://easydigitaldownloads.com/support/topic/amazon-s3-downloads-not-working/page/2/#post-416472

I am using v2.2.3 of EDD

**Comment by pippinsplugins** [comment]
Does it only get corrupted when using the S3 add-on, or does it also get corrupted when using self-hosted files?

**Comment by mintplugins** [comment]
I'm linking directly to the file in an Amazon bucket - that's where it isn't working. But the same happens whether it is hosted on Amazon or anywhere foreign to the current WP installation.

When the file is hosted inside the current WP, it works correctly.

**Comment by pippinsplugins** [comment]
Linking via the S3 extension or without?

**Comment by mintplugins** [comment]
Without the S3 extension.

**Comment by pippinsplugins** [comment]
Bug confirmed again: https://easydigitaldownloads.com/support/topic/edd-file-download-with-amazon-3s-results-in-html-file/#post-430571

**Comment by mintplugins** [comment]
This is still an issue in 2.2.7 as it broke upon update. I see it is scheduled as a fix for 2.3 so no worries. Just updating.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by cklosowski** [comment]
@mintplugins Can you try adding the following line after the ```X-Accel-Redirect``` header?
```header( "Access-Control-Allow-Origin: *" );```

If you could, enable that line so that the Nginx check looks like this:
```
// We need a path relative to the domain
$file_path = str_ireplace( $_SERVER[ 'DOCUMENT_ROOT' ], '', $file_path );
header( "X-Accel-Redirect: /$file_path" );
header( "Access-Control-Allow-Origin: *" );
```

**Comment by pippinsplugins** [comment]
I'm going to punt this to 2.3 so that we can release 2.2.8.

**Comment by mintplugins** [comment]
Hey sorry - just seeing this now. Will try it now @cklosowski

**Comment by mintplugins** [comment]
Hmm, that doesn't seem to have fixed the issue

Screenshot of code:
http://cl.ly/image/2a093z0Q2n2i

What I am getting as a download now is the HTML output for my homepage.

When I comment out that 'elseif' it works again as it should:
http://cl.ly/image/062R461M1u3p

**Comment by cklosowski** [comment]
ok @mintplugins Thanks for testing that out. I just setup nginx on a VPS and I've been testing things out. I setup WordPress and EDD and linked to a Dropbox file (which should work just the same as Amazon), and this is what I came up with. Can you test this one? Sorry to have you keep trying things out but I want someone who has this as an issue live to try it out.

```
$site_url   = get_site_url();
if ( false !== strpos( $requested_file, $site_url ) ) {
	// We need a path relative to the domain
	$file_path = str_ireplace( $_SERVER[ 'DOCUMENT_ROOT' ], '', $file_path );
	header( "X-Accel-Redirect: /$file_path" );
}
```

**Comment by pippinsplugins** [comment]
`if ( false !== strpos( $requested_file, $site_url ) ) {` may need to check both http and https, similar to what we do above:
```
} else if( strpos( $requested_file, WP_CONTENT_URL ) !== false ) {

	/** This is a local file given by URL so we need to figure out the path */
	$file_path  = str_replace( WP_CONTENT_URL, WP_CONTENT_DIR, $requested_file );
	$file_path  = realpath( $file_path );
	$direct     = true;

} else if( strpos( $requested_file, set_url_scheme( WP_CONTENT_URL, 'https' ) ) !== false ) {

	/** This is a local file given by an HTTPS URL so we need to figure out the path */
	$file_path  = str_replace( set_url_scheme( WP_CONTENT_URL, 'https' ), WP_CONTENT_DIR, $requested_file );
	$file_path  = realpath( $file_path );
	$direct     = true;

}
```

**Comment by cklosowski** [comment]
Actually, strike that...just change the conditions to this:
```$direct && ( stristr( getenv( 'SERVER_SOFTWARE' ), 'nginx' ) || stristr( getenv( 'SERVER_SOFTWARE' ), 'cherokee' ) )```

**Comment by mintplugins** [comment]
No problem! Glad to help :) 

I changed the conditions to your last response and it is working great! I testing it over https and over http and it is working on both as well.

**Comment by pippinsplugins** [comment]
Great!
