### ISSUE TITLE
Addons Source Code

### ISSUE THREAD

**Issue by marcinant** [easydigitaldownloads/Easy-Digital-Downloads#2987]
Hello,

Short question. Where can I find source code of addons to EDD? For example Software Licensing Addon?

**Comment by chriscct7** [comment]
Hi there,
This repository is only for issues with EDD. For help with extensions please use our support forums. Our source code for extensions are available from the My Account page on our site after you purchase the extension.

**Comment by marcinant** [comment]
Ok. I'm going to open ticket on support forum.

However source code should be available as it's on GPL.

I understand that you provide updates, support and put some usage restrictions.
Unfortunately I'm not going to pay $82 for piece of code that can be useless as there is no trial or access to code.

**Comment by pippinsplugins** [comment]
The github repository for Software Licensing is private, sorry. GPL does not mean the code has to e publicly accessible; it means that it has to be free to modify without restrictions once obtains.

Note: we have a full 30-day refund policy so if you find the plugin does not work for you, we can process a complete refund for you.

**Comment by marcinant** [comment]
So why don't you provide some trial option?

I opened ticket on forum https://easydigitaldownloads.com/support/topic/source-code-localizations-and-multiple-types-of-license/ to describe my concerns more precisely.

Don't get me wrong. I understand GPL and it states:

"You may charge a fee for the physical act of transferring a copy, and
you may at your option offer warranty protection in exchange for a fee."

So, I could pay for transfer or copy, and/or declare to not redistribute, or contribute some code or translation (but not $82 as I don't need updates and support until I decide to use this addon).

However as I don't know if I'm going to use your product then your note about 30-day refund is not valid in my case:

"If you have problems getting extensions to work, we will be happy to provide a full refund within 30 days of the original purchase. After 30 days, no refunds will be given. Before a refund will be granted, you must allow us to try and help solve any problem you have by opening a support ticket. NOTE: **refunds will not be granted if you simply decide not to use the purchased products.** "

I already have my own server which hosts and provides upgrades for my WP plugins, however I don't have code to sell them. This is why I consider some integration with EDD. Though it is possible that I'll choose WooCommerce or I'll have to write my addon from scratch.

So, you will refuse to refund then, don't you?

**Comment by chriscct7** [comment]
Hi there,
In compliance with GPL, our price includes not only support and updates, but also the initial distribution of the extension. Therefore, regardless of whether or not you wish to use support or updates, you would still be charged.

We prefer if people have questions about the extensions to ask them in the forums before purchasing them. We do not provide refunds to people who simply decide not to use the extensions.

**Comment by chriscct7** [comment]
As this is not an issue with EDD core, I'll go reply to your support ticket

**Comment by marcinant** [comment]
Ok. Let's continue on support forum.

However to end topic here: @pippinsplugins info about refund is wrong, and for me $82 is just too much. It's a pity you don't offer any trial option.

**Comment by pippinsplugins** [comment]
I'm going to respond to your questions on the support forums :)
