### ISSUE TITLE
Reports should allow toggle between inclusive and exclusive of taxes

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/Easy-Digital-Downloads#2988]
Some people might want to see the reports exclusive of taxes, particularly if they are now having to deal with VAT MOSS so they can see "true revenue".

Inspiring ticket: https://easydigitaldownloads.com/support/topic/reports-excluding-vat/

**Comment by pippinsplugins** [comment]
:+1: This will be dramatically easier to do once #1490 is complete

**Comment by vpratfr** [comment]
+1 on this. 

This is very difficult to "guess" the real revenue when you sell from the UE as for some countries you have to charge VAT and for some other countries you don't. 

Report excl. taxes would solve this (either have an additional line on the graph or allow to switch between incl/exlc and defaulting to excl. seems to make more sense)

**Comment by cklosowski** [comment]
This adds a checkbox to the graph filters, allowing someone to exclude taxes from any earnings numbers.

It defaults to include (as that's what our current behavior is, we don't want to break backwards compatibility), so excluding is the action.

**Comment by cklosowski** [comment]
![screen shot 2015-06-08 at 10 09 23 pm](https://cloud.githubusercontent.com/assets/1390124/8050998/2121d32e-0e2b-11e5-9752-419d5a53112f.png)

![screen shot 2015-06-08 at 10 08 59 pm](https://cloud.githubusercontent.com/assets/1390124/8051001/2e93c562-0e2b-11e5-8cc9-8b8273a05f6b.png)

![screen shot 2015-06-08 at 10 09 09 pm](https://cloud.githubusercontent.com/assets/1390124/8051002/31959df8-0e2b-11e5-93f0-d34b406b5ce5.png)

**Comment by pippinsplugins** [comment]
@cklosowski Looks good but there is some weird behavior as well.

Earnings / sales for the year:
![screen shot 2015-06-09 at 9 08 19 am](https://cloud.githubusercontent.com/assets/1034109/8059737/2b463bd6-0e87-11e5-8c35-d899909fd28a.png)

Earnings / sales for the year excluding taxes:
![screen shot 2015-06-09 at 9 08 26 am](https://cloud.githubusercontent.com/assets/1034109/8059744/3591d442-0e87-11e5-9ae7-34e6ba48f6bd.png)

Looks like a number is going negative or to zero when tax is removed. I'm guessing it may be related to 0.00 sales.

**Comment by pippinsplugins** [comment]
February is when I ran the `wp edd payments --create` to make a bunch of test payments:
![screen shot 2015-06-09 at 9 11 02 am](https://cloud.githubusercontent.com/assets/1034109/8059812/87b57508-0e87-11e5-84a7-2b6de011d114.png)

Perhaps some data is missing from those.

**Comment by pippinsplugins** [comment]
Oh interesting. When I created those payments, I set them to $1.00 but set their tax to $5.00:
![screen shot 2015-06-09 at 9 13 18 am](https://cloud.githubusercontent.com/assets/1034109/8059876/d5ce7b22-0e87-11e5-93e9-b87113470a64.png)

That was dumb.

This does not represent a real scenario (that would never happen without manual data manipulation), so I vote we ignore it.
