### ISSUE TITLE
Filter for redirect to gateway

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/Easy-Digital-Downloads#2990]
We need a filter on scripts.php line 74 so we can make single page checkout:
```'redirect_to_checkout'    => ( edd_straight_to_checkout() || edd_is_checkout() ) ? '1' : '0',```

**Comment by pippinsplugins** [comment]
I propose that we pass the localized script variables through a filter so that they can be changed.

**Comment by pippinsplugins** [comment]
@chriscct7 ^^
