### ISSUE TITLE
Revert swap to semi-colons for CSV separator 

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#2997]
In 2.2 we changed the column separator to a `;` for the CSV exports per #2675 and #2680. This has caused a large number of tickets from users due to Excell and other spreadsheet applications not automatically recognizing the `;` as the separator.

We should revert the change and then use double quotes for all cell values. We'll need to make sure that all values are escaped to prevent premature column endings.

**Comment by cklosowski** [comment]
I think this should fix it, but i'll try and do some testing this week on it and get a fix in place.
