### ISSUE TITLE
Add batch processing to CSV export

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#2999]
We really need to add batch processing to the CSV exporter so that it can handle large amounts of data. Right now everything is done with a single process, which results in it crashing if there is too much data.

Ninja Forms has a great example of how this can work work with Ajax processing (see their submissions export).

**Comment by chriscct7** [comment]
Are we thinking like the updates batch update like routine in terms of UI or something more subdued, like an ajax loader of some sort with a amount done or to do ?

**Comment by pippinsplugins** [comment]
It should be based on the same API as the upgrades API.

**Comment by pippinsplugins** [comment]
This isn't super smooth yet but it is functional.

Some things to still consider:

- Should all export classes be moved to export folder? Will this break some extensions?
- Once the file is generated, redirect back to export page fails. Perhaps the export should be done via ajax?
- There's strange behavior when exporting specific statuses and dates. Seems to be missing data.

**Comment by pippinsplugins** [comment]
This is now fully functional for the payment history export. Not polished, but working.

**Comment by pippinsplugins** [comment]
@easydigitaldownloads/core-devs This is ready for testing in https://github.com/easydigitaldownloads/Easy-Digital-Downloads/pull/3472

**Comment by cklosowski** [comment]
Seems to work well for me:
![image](https://cloud.githubusercontent.com/assets/1390124/7999339/69ba8de0-0afe-11e5-8db7-efb5450ac105.png)

**Comment by cklosowski** [comment]
Exported 9560 payments without a problem.

**Comment by pippinsplugins** [comment]
Woot!

**Comment by mindctrl** [comment]
Looks good here too.

**Comment by pippinsplugins** [comment]
Merged into `release/2.4`

**Comment by mindctrl** [comment]
@pippinsplugins The datepicker doesn't work right in the Download History export. It leaves the dates blank and fills in the Payment History ones instead.

**Comment by cklosowski** [comment]
Sounds like a small ID targeting issue, shouldn't be to hard to resolve.

**Comment by pippinsplugins** [comment]
@mindctrl Thanks. I remember seeing that but forgot about it.
