### ISSUE TITLE
Filter purchases by country / state

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#3003]
We should introduce filter options in Payment History that allows site admins to locate payments for customers in specific countries / states. This is relatively easy for payments that have a billing address collected, so I don't see any major difficulties here.

[This ticket](https://easydigitaldownloads.com/support/topic/tax-reporting-by-state/) gives a really good reason for it:

> > > I wasn’t charging sales tax in 2014 but after speaking to my accountant they said I need to pay sales tax for the people in my state who bought my ebook. Only people who purchased in my state (Minnesota) need to be charged sales tax, and I’m happy to eat this cost and pay the sales tax myself despite not having charged it to them, but I need to try to figure out how many people from my state purchased the ebook. I have several thousand purchases in 2014 and so going through one-by-one isn’t really an option. Is there any way for me to retrieve customers, perhaps via SQL or some other method, of customers who entered a billing address which contained the state of ‘Minnesota’? I don’t require users to enter a billing address unless they pay by credit card and so obviously this would be difficult to do with PayPal, but for the customers who paid by credit card who I have a billing address stored in my database for, could I possibly query them to get a set of results?

**Comment by pippinsplugins** [comment]
Completely forgot this existed: https://wordpress.org/plugins/easy-digital-downloads-location-export/

**Comment by ghost1227** [comment]
Given the existence of that extension is this still being done?

**Comment by pippinsplugins** [comment]
I think it should still be supported.

**Comment by cklosowski** [comment]
Since there is an extension, and we're tight on 2.4 and Amazon, pushing to 2.5

**Comment by pippinsplugins** [comment]
:+1:

**Comment by sunnyratilal** [comment]
We'll add this as an advanced filter as part of #6086.

**Comment by sunnyratilal** [comment]
Merged.
