### ISSUE TITLE
HTML tags not rendering correctly in forum replies.

### ISSUE THREAD

**Issue by sumobi** [easydigitaldownloads/Easy-Digital-Downloads#3009]
When replying to a customer I noticed that HTML tags (tested with blockquotes and strong tags) weren't being rendered correctly. 

The first set of tags and the last set of tags worked, but if I used any of those tags between the first and last instances they were rendered as the tags themselves and therefore did not execute.

**Comment by cklosowski** [comment]
Shouldn't this be on the EDD-Site repo?

**Comment by pippinsplugins** [comment]
Seems invalid to me. @sumobi ?

**Comment by sumobi** [comment]
Whoops
