### ISSUE TITLE
EDD Stripe - PHP Notice when no keys saved in options

### ISSUE THREAD

**Issue by NateWr** [easydigitaldownloads/Easy-Digital-Downloads#3014]
Before any EDD options are saved in the database, lines 1503 and 1505 of `edd-stripe.php` will throw an undefined index notice.

```
		if ( edd_is_test_mode() ) {
			$publishable_key = trim( $edd_options['test_publishable_key'] );
		} else {
			$publishable_key = trim( $edd_options['live_publishable_key'] );
		}
```

Can be fixed by checking the `$edd_options` array first:

```
		if ( edd_is_test_mode() ) {
			$publishable_key = empty( $edd_options['test_publishable_key'] ) ? '' : trim( $edd_options['test_publishable_key'] );
		} else {
			$publishable_key = empty( $edd_options['live_publishable_key'] ) ? '' : trim( $edd_options['live_publishable_key'] );
		}
```

And I'm on version 2.1 this time. Promise! :)

**Comment by pippinsplugins** [comment]
This should be logged on the stripe gateway repository :)

**Comment by NateWr** [comment]
Did you put that one up on GitHub? I didn't find it in the [EDD repos](https://github.com/easydigitaldownloads?query=stripe).

**Comment by pippinsplugins** [comment]
It's here: https://github.com/easydigitaldownloads/edd-stripe

I've added you.

**Comment by VegasNews** [comment]
@pippinsplugins the above link is not working.

**Comment by pippinsplugins** [comment]
@VegasNews It's a private repo.

**Comment by VegasNews** [comment]
Ok, I was responding to the errors that was reported and to see if I can
contribute more to it as a developer. 

Anyway, thanks 

--- 

VEGAS NEWSPAPER TEAM #Online Celebrity News 

TEL: 702-919-NEWS 

TOLL: 855-459-NEWS 

WEB: VEGAS NEWSPAPER [3] 

_Don't forget to tell others!_ SHARE YOUR STORY ON SOCIALS 

Facebook: Vegas Newspaper [4] 

Twitter: Vegas Newspaper [5] 

On 2015-02-05 07:22, Pippin Williamson wrote: 

> @VegasNews [1] It's a private repo. 
> 
> --
> Reply to this email directly or view it on GitHub [2].
 

Links:
------
[1] https://github.com/VegasNews
[2]
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/3014#issuecomment-73063761
[3] https://www.vegasnewspaper.com
[4] https://www.facebook.com/vegasnewspaper
[5] https://www.twitter.com/VegasNewspaper
If you'd like to unsubscribe and stop receiving these emails click here: http://clicktrack.sendgrid.com/wf/unsubscribe?upn=s5UH8bhnBaopYjthcNSRcbrGd21JyLlDqIfnohRtZHTT43-2Fyhsvpb8Bam-2BaQ8PMkZiI1gtSJ7i8oe7RfYT1-2BHF0Wthz3pGkyJmgrqGwk-2BIGQSMuiNuwuU5n4p-2Bk0zTw2Um-2F-2FNpjocAfxCQ0KYBsbmSMNUxX6UD4KIuAeVd9bypdOKllQaQ-2F2cH6Iyj6v6Aqd641pu3-2BW2D-2F8shfDa7ym2Rq6h0ZxtuiSnnZiXQI-2BlR5J6ZGtCim6NlTbHB4eKls5zF18Z6vPNrTTP-2FXRfxJHsNo6d1ah31rsIYTZ4ZcZwVuBhgkOMgJLV8oFeDVjnCqT.

**Comment by pippinsplugins** [comment]
We always love help but for this particular gateway it has to be managed in-house, sorry.

**Comment by VegasNews** [comment]
I appreciate your response. 

Happy coding :) 
---

  

VEGAS NEWSPAPER TEAM #Online Celebrity News 

TEL: 702-919-NEWS 

TOLL: 855-459-NEWS 

WEB: VEGAS NEWSPAPER [2] 

_Don't forget to tell others!_ SHARE YOUR STORY ON SOCIALS 

Facebook: Vegas Newspaper [3] 

Twitter: Vegas Newspaper [4] 

On 2015-02-05 11:18, Pippin Williamson wrote: 

> We always love help but for this particular gateway it has to be managed in-house, sorry. 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1]
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/3014#issuecomment-73108119
[2] https://www.vegasnewspaper.com
[3] https://www.facebook.com/vegasnewspaper
[4] https://www.twitter.com/VegasNewspaper
If you'd like to unsubscribe and stop receiving these emails click here: http://clicktrack.sendgrid.com/wf/unsubscribe?upn=s5UH8bhnBaopYjthcNSRcUUHsoGBJLxX3p13dC-2FPPjMv9zGDpbrg0prYRHKxxW6239cldUHtjmuGVP67geGxkpMlHne-2FOOv6Pdgf0F0g2qZjNvt7DiZyXOql5omccc2hwYozga7iv4wHJJnU3U5KdD4IcaKxa0wvwLK-2FZmp8CEszJtYH8eD2qAYuHnwYCeBqmZLgIrfahrFaAiR4BTLD-2F5k2ggDopEODY4DtV8LKU8-2F7wtCGEDv2wvZepkkf0KOKgMwbgcCbjv-2FTRObjxp7kAT-2F-2Bbgc6OPIhoIsd4bLoeQwT86f5rvcJhikZ-2FGBXHf9t8EDUl03PSjgqQJFNlktMHA-3D-3D.
