### ISSUE TITLE
Register stylesheet

### ISSUE THREAD

**Issue by joelworsham** [easydigitaldownloads/Easy-Digital-Downloads#3016]
I'm a plugin developer, and in an extension I'm creating, I need access to the EDD stylesheet. For now, I've copy / pasted the code you use when determining the url for enqueing, but this isn't very safe, as it could change.

If you registered your 'edd-styles' stylesheet in 'init', it would be very easily accessible.

**Comment by pippinsplugins** [comment]
Thanks for the suggestion. While this is probably a good idea, another way you can do it is to just call `edd_register_styles()` inline or add it to an action.

**Comment by joelworsham** [comment]
Hmm good call. I didn't think about that. So for now I'm just calling that and then grabbing the stylesheet from $wp_styles.

Thanks for the advice!

**Comment by pippinsplugins** [comment]
We'll still look into registering it to make it more standardized.

**Comment by joelworsham** [comment]
Good deal.

**Comment by cklosowski** [comment]
Before I go and make a PR, can someone test out this branch? Make sure things are still working? I'm not having any issues with it.

**Comment by pippinsplugins** [comment]
Looks like it works just fine for me.
