### ISSUE TITLE
Introduce EDD_Customer class

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/Easy-Digital-Downloads#3018]
In working on #2548, I'm finding that we end up using the ```EDD_DB_Customer``` class to retrieve a customer, which is intended to be an abstraction layer for the custom table, not a true ```Customer``` Class.

Initially I'm looking to have a class that allows directly accessing the customer properties, as well as updating key attributes of the customer.

This is a blocker now for #2548.

**Comment by pippinsplugins** [comment]
This should mimic EDD_Download and EDD_Payment (WIP) as much as possible.

**Comment by cklosowski** [comment]
@pippinsplugins That's the plan.

**Comment by pippinsplugins** [comment]
This is looking really good.

First thing I notice that I think I'd like changed is how the `global $edd_customers_db` is setup in `EDD_Customer`. Instead of setting it up inside each method, how about just setting it up as a private or protected property and then setting it up once in the constructor.

**Comment by spencerfinnell** [comment]
I thought the same thing as @pippinsplugins 

Also should passing no ID set up a new customer similar to how the downloads class works? If no customer is found and `$field` is an email one could be generated.

**Comment by pippinsplugins** [comment]
We discussed creating new customers like that and ultimately decided it was
too risky.

**Comment by cklosowski** [comment]
@spencerfinnell Yeah, we determined that we'd rather have the creation be explicit, not implied.

@pippinsplugins I had it that way initially, trying to remember why I changed it. Let me do it again and see if it comes back.

**Comment by cklosowski** [comment]
Huh, seems the way I'm setting up the customer cleared up the initial reason for it being a ```global```. Yay for refactoring :)

Committing up with ```$this->db``` and no global, as a protected.

**Comment by pippinsplugins** [comment]
Woot!

**Comment by pippinsplugins** [comment]
How do you guys feel about the `EDD()->customers` object? Keep it?

**Comment by cklosowski** [comment]
@pippinsplugins I'm good with keeping it. It makes sense to have it there for some of the use cases, like dealing with the database directly. This is an ```EDD_Customer``` class, not ```Customers```.

My vote, it stays.

**Comment by pippinsplugins** [comment]
The reason I brought it up is because I'm thinking about the reason for having a global DB class to access customers. Since we have it, and we use the `EDD()->{object}` method elsewhere, I think we should be consistent and use it through `EDD_Customer` as well.

**Comment by cklosowski** [comment]
Ok then we'll need a few more methods, for things like "Count" etc, however I'm not sure if that all belongs in the ```EDD_Customer``` as they are more global values, not specific to the customer you are requesting in the Class.

**Comment by pippinsplugins** [comment]
Why? It's still referencing the same methods through the global as through
EDD ().

**Comment by pippinsplugins** [comment]
I think `$_id_or_email` should be passed with a default of `false` to the `__construct()` method.

**Comment by pippinsplugins** [comment]
Instead of throwing an exception in `__get`, could we return a `wp_error`if the property cannot be retrieved?

**Comment by pippinsplugins** [comment]
In the `create()` method, there is no need for `|| '' == trim( $args['email'] )`. The `empty()` check will catch empty strings.

**Comment by pippinsplugins** [comment]
We should probably sanitize / validate some of the fields passed to the `update()` method. For example, if the `email` field is not an email, we should bail.

**Comment by pippinsplugins** [comment]
The `attach_payment()` method should probably use the `update()` method in `EDD_Customer` instead of calling `$this->db->update` directly. There probably isn't really a downside to how it is, but it will ensure any validation we put in `EDD_Customer::update` is used as well.

**Comment by cklosowski** [comment]
Ok I'll address these today. Thanks :)

**Comment by cklosowski** [comment]
- [ ] $_id_or_email defaults to false
- [ ] Create method doesn't need to trim, only empty
- [ ] Sanitize for update method
- [ ] attach_payment should use the update method in SELF

**Comment by pippinsplugins** [comment]
@cklosowski Yes, let's update EDD_Download too.

**Comment by cklosowski** [comment]
Ok @pippinsplugins take a look at those few commits, I think that's a decent set of vars to be passing in the hooks. Had to update the code to make sure the hooks always fire as well, just good practice there. Fire on failure or success.

**Comment by cklosowski** [comment]
Correction on that last commit #2548

**Comment by pippinsplugins** [comment]
@cklosowski Those all look great.

**Comment by pippinsplugins** [comment]
@cklosowski I think we should go ahead and merge this into `release/2.3`.

**Comment by pippinsplugins** [comment]
This is now in `release/2.3`

**Comment by pippinsplugins** [comment]
I think we can go ahead and close this. I've been testing it out further and it looks great.

**Comment by cklosowski** [comment]
@pippinsplugins. Reopened? Got a big for me to fix?

**Comment by pippinsplugins** [comment]
Wifi died as I tried to comment.

I found a customer record that has a negative purchase value. We need to
make sure values cannot go negative.

**Comment by pippinsplugins** [comment]
Looks like the upgrade routine resolved the negative value but we should still confirm it can't go negative.
