### ISSUE TITLE
Remove JS "you must have at least one file" alert

### ISSUE THREAD

**Issue by sumobi** [easydigitaldownloads/Easy-Digital-Downloads#3019]
When you already have at least 1 file added to a download and you try and remove it you get a JS alert with "you must have at least one file". 

Considering you can add a download without adding file downloads I believe you should be able to remove the last file and save the download without receiving the JS alert. Currently the solution is to wipe out the file field and save the download.

**Comment by pippinsplugins** [comment]
:+1:
