### ISSUE TITLE
Don't create pending payments immediately with PayPal buy now

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#3021]
When using buy now buttons through PayPal, a pending payment is created at the moment the buy now button is clicked. This results in this:
![screen shot 2015-01-28 at 9 27 01 am](https://cloud.githubusercontent.com/assets/1034109/5940320/d842b62c-a6cf-11e4-8629-e12524220264.png)

We need to come up with a way to not create the pending payments until the IPN is successfully validated, or simply not show them in Payment History until they are actually confirmed. This could be done by using a different post status (perhaps `private`) and excluding that post status from payment history.

**Comment by sumobi** [comment]
:+1: Dealt with a couple of these tickets recently where the customer thinks this is a bug because all the blank customer details, not to mention the number that are generated. The customers are obviously just clicking the buy buttons, going to paypal and then abandoning.

**Comment by pippinsplugins** [comment]
At minimum, let's hide the payments.

**Comment by pippinsplugins** [comment]
A recent ticket that illustrates perfectly why we need to do this: https://easydigitaldownloads.com/support/topic/pending-payments-i-am-not-getting-paid/

**Comment by chriscct7** [comment]
Maybe the better option would be to have a lower timeout on buy it now pending -> failed

**Comment by pippinsplugins** [comment]
No, the timeout is set at 7 days to ensure echecks have enough time to be verified.

**Comment by chriscct7** [comment]
The suggestion was a lower timeout specifically for buy it now button orders, not all orders.

**Comment by chriscct7** [comment]
Oh I see what you're saying. Hmmm

**Comment by chriscct7** [comment]
I think the IPN for PayPal can tell you an echeck was used to pay on the return. We could detect that and if so do the longer pending, else do a shorter one, like an hour

**Comment by pippinsplugins** [comment]
This shouldn't be hard to do. We just need a "private" status that doesn't
show up in payment history.

**Comment by pippinsplugins** [comment]
This isn't really related to echecks (that is a good idea though). This is
to get rid of the assumption that something is broken when site admins see
tons of pending payments.

**Comment by chriscct7** [comment]
If we could detect echecks, we could lower the default time from pending->failed to like 1 hour, and anything that hits 1 hour would become failed, versus anything under that could be like an "in progress" status or something

**Comment by pippinsplugins** [comment]
It's not about echecks.

**Comment by chriscct7** [comment]
The issue isn't but part of the solution could be. If it wasn't for echecks, couldn't we have the pending->failed time be one hour? If we can find a solution to lower the amount of time a payment is in pending, there wouldn't be so many pending payments. Even if we introduce a private or in progress one, I think people would be curious as to why there are so many in there and so few get to completed.

**Comment by pippinsplugins** [comment]
No, we can't do one hour. There are many cases where an IPN fails temporarily and is then resent.

We also have to take into account people that use pending payments for taking orders via check, money order, or cash.

We will not change the pending > failed timing.

**Comment by chriscct7** [comment]
I still think there's a way we can improve it. We could add an on-hold status similar to WooCommerce.

**Comment by pippinsplugins** [comment]
The `on-status` status is exactly what I'm thinking about, except it won't be displayed in payment history. The problem with buy now buttons is that too many people click to "see what happens". That results in a large number of payments that causes admins to freak out and think something is failing with purchase verification.

**Comment by pippinsplugins** [comment]
I've opted to set Buy Now purchases as `private` and then exclude private items from default payment queries. This seems to work really well.

**Comment by pippinsplugins** [comment]
This has been merged into `release/2.3`.

**Comment by pippinsplugins** [comment]
`private` payments are still getting included in the `All` payments count. The site shown in this example has 2 payments, one of which is private:
![screen shot 2015-02-15 at 7 11 04 pm](https://cloud.githubusercontent.com/assets/1034109/6206056/792fa0b6-b546-11e4-8e5e-f2203e6eeb48.png)

**Comment by pippinsplugins** [comment]
Aside from that, everything works beautifully with this.
