### ISSUE TITLE
WP_CONTENT_URL does necessarily respect HTTPS URLs

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#3022]
Take this scenario:

1. Site is forced to load all pages over HTTPS
2. `site_url` and `home_url` options are `http://` NOT `https://`
3. `WP_CONTENT_URL` is `http://site.com/wp-content/` NOT `https://site.com/wp-content/`

The site is forced to HTTPS via an htaccess rule or perhaps a hosting config.

It turns out that this causes an occasional issue with our file download process. While parsing the URL of the download file, we compare it to `WP_CONTENT_URL` to determine if we can discover the absolute path to the file: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/process-download.php#L162

Since the site is forced to HTTPS, the file URL is `https://site.com/wp-content/uploads/edd/2015/01/file.zip` but `WP_CONTENT_URL` is `http://site.com/wp-content/`, causing this to fail:

```php
} else if( strpos( $requested_file, WP_CONTENT_URL ) !== false ) {

	/** This is a local file given by URL so we need to figure out the path */
	$file_path  = str_replace( WP_CONTENT_URL, WP_CONTENT_DIR, $requested_file );
	$file_path  = realpath( $file_path );
	$direct     = true;

}
```

When that fails, the download method falls back to `redirect`, which then results in a permission denied error due to our `.htaccess` rules.

We should implement a check to determine if the file URL is `https` and then compare it to an `https` version of `WP_CONTENT_URL.

Note: this problem is also fixed by simply updating `site_url` and `home_url` to `https://site.com` but it is best that we be proactive about preventing the issue.

**Comment by pippinsplugins** [comment]
@cklosowski Thoughts?

**Comment by cklosowski** [comment]
This looks like it should work...

I agree this is more of a configuration issue, and we can do our best to prevent it, but I think people misunderstand the implications of HTTPS and their configurations, so yeah, as long as this doesn't break normal configurations, let's do it.

**Comment by pippinsplugins** [comment]
Happy with the PR? If so I will go ahead and merge.

**Comment by pippinsplugins** [comment]
Looks like this does not quite work to fix the issue on the user's site. I'll dig further.

**Comment by pippinsplugins** [comment]
Scratch that, it does fix it.

**Comment by cklosowski** [comment]
:+1:
