### ISSUE TITLE
Load dashboard earnings / sales widget with ajax

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#3024]
While working on a site for a customer (where they claimed EDD was slowing down their site) I noticed that Jetpack site stats loads its widget with ajax after the dashboard is loaded.

I think we should consider doing the same since the initial loading of earnings stats can be quite time consuming. Once the stats are cached, load impact is minimal, but when not cached, there could be a very noticeable improvement.

Thoughts? Objections?

**Comment by cklosowski** [comment]
:+1:

**Comment by pippinsplugins** [comment]
I really like how Jetpack does it with a loading indicator that then gets replaced with the widget content.

**Comment by pippinsplugins** [comment]
![screen shot 2015-02-02 at 8 44 26 pm](https://cloud.githubusercontent.com/assets/1034109/6013569/4fa8b43c-ab1c-11e4-8c5f-acdf3e0bf81b.png)
![screen shot 2015-02-02 at 8 44 17 pm](https://cloud.githubusercontent.com/assets/1034109/6013570/4fb5145c-ab1c-11e4-9867-c724d2925f92.png)

**Comment by pippinsplugins** [comment]
Anyone want to give it a spin and lend feedback?

**Comment by cklosowski** [comment]
Looks good to me. Working beautifully

**Comment by cklosowski** [comment]
Seems to be saving me ~1/4 of a second locally:
![screen shot 2015-02-06 at 10 24 57 am](https://cloud.githubusercontent.com/assets/1390124/6083995/7f74a86c-adea-11e4-8db0-931be7bad44a.png)

**Comment by pippinsplugins** [comment]
That's a great improvement. On large sites that could easily equate to 3-5 seconds on load.
