### ISSUE TITLE
Unit test helpers

### ISSUE THREAD

**Issue by JeroenSormani** [easydigitaldownloads/Easy-Digital-Downloads#3032]
Hey,

What do you guys think about helpers for unit tests?
For reference, this is what Woo uses https://github.com/woothemes/woocommerce/tree/master/tests/framework/helpers

Right now the downloads/payments etc are made in the setUp of a unit test class, like this; https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/tests/tests-downloads.php#L17

Although working fine, as I was writing unit tests for a EDD extension, this was of no (quick) use for me. 

I've written some helpers, so if you guys are pro-helpers I can make a PR for that. 

Cheers!
Jeroen

**Comment by pippinsplugins** [comment]
I would _love_ to have helpers.

**Comment by JeroenSormani** [comment]
This already has been merged, issue never closed :smile:
