### ISSUE TITLE
Not sufficient permissions to access Upgrades, Tools and Add-Ons page due to `DISALLOW_FILE_MODS`

### ISSUE THREAD

**Issue by grappler** [easydigitaldownloads/Easy-Digital-Downloads#3034]
I clicked to run the upgrade process but got the error:
> You do not have sufficient permissions to access this page.

I deactivated all of the plugins and activated a default theme.

While trying to workout the issue I saw that the Tools and Add-Ons page was not displaying in the menu.

The reason for this is that I have defined `define('DISALLOW_FILE_MODS', true);` in wp-config.php.

EDD version 2.2.6

**Comment by pippinsplugins** [comment]
The Tools and Add-Ons page under the Downloads menu weren't displayed?

**Comment by pippinsplugins** [comment]
Ah, it's because the use the `install_plugins` capability. We should change that.

**Comment by pippinsplugins** [comment]
Fixed in #3039
