### ISSUE TITLE
Cannot update or publish products

### ISSUE THREAD

**Issue by diekemada** [easydigitaldownloads/Easy-Digital-Downloads#3040]
I cannot update or publish products. All other features are working in Word Press, however, when I try to make a change to a product and update it, or if I try to publish a new product, the program is unresponsive and nothing happens. It recognizes that changes were made because it asks me if I want to leave the page without saving changes. However, it does not allow me to save the changes.

**Comment by pippinsplugins** [comment]
Could you please open a ticket in the support forums? GitHub is for
development tracking only.

Http://easydigitaldownloads.com/support
