### ISSUE TITLE
Best practice advice for filtering cart tax

### ISSUE THREAD

**Issue by NateWr** [easydigitaldownloads/easy-digital-downloads#3042]
The EDD/Taxamo addon has [performance issues](https://github.com/rhyswynne/easy-digital-downloads-taxamo-integration/issues/1) that I'm investigating. The main issue is that it makes its API call in the `edd_get_cart_tax` filter.

Turns out `edd_get_cart_tax()` is called all over the place in the checkout (two dozen times by my count).

I'll propose storing the API call in the Taxamo addon so the request doesn't get sent out every time the filter is run. But I wondered if there was a better hook we were meant to use to replace tax in a cart. How do other tax-manipulating addons modify the tax value?

It looks like there isn't any level (`edd_get_cart_content_details()`, `edd_get_cart_fee_tax()` or `edd_get_cart_item_tax()`) where EDD stores or caches the value. So that means the checkout page is running all this code two dozen times, often just for bool checks. It looks like most of the database hits will be cached by WP, though, so maybe it's not that expensive to run over and over.

**Comment by NateWr** [comment]
By the way, here's a [little plugin](https://gist.github.com/NateWr/6796d65acd5c31306250) to count the occurrences when the filter is called.

**Comment by pippinsplugins** [comment]
I'd like to see this fixed by introducing a cart class that sets up each variable just once.

**Comment by cklosowski** [comment]
:+1: to a cart class like `EDD_Cart` that would help solve this. Going to create this issue for 2.7, and milestone it and this.
