### ISSUE TITLE
Cannot upgrade on multisite unless you're a super admin

### ISSUE THREAD

**Issue by Ipstenu** [easydigitaldownloads/Easy-Digital-Downloads#3044]
I get this as an admin: You do not have sufficient permissions to access this page.

Which makes sense in many ways, but seems sub optimal. I shouldn't get a notice to run the upgrades if I can't run it.

**Comment by chriscct7** [comment]
Duplicate of https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/3034 fixed by https://github.com/easydigitaldownloads/Easy-Digital-Downloads/pull/3039 by way of https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/2834
