### ISSUE TITLE
Restore edd_email_purchase_receipt filter

### ISSUE THREAD

**Issue by TheCrowned** [easydigitaldownloads/Easy-Digital-Downloads#3053]
Hi there,
somewhere before version 2.1 the filter edd_email_purchase_receipt allowed to prevent the purchase receipt from being sent upon purchase. Is there a specific reason why it has been deleted? Could it be restored?

**Comment by pippinsplugins** [comment]
You can add this to disable purchase receipts:
```php
remove_action( 'edd_complete_purchase', 'edd_trigger_purchase_receipt', 999 );
```

**Comment by TheCrowned** [comment]
Thanks! So silly of me not thinking about that, sorry!
