### ISSUE TITLE
Discounts that don't meet product requirements get submitted when clicking Purchase

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/Easy-Digital-Downloads#3057]
Steps to reproduce:

1. Create discount code and set Download Requirements to PRODUCT ABC
2. Add PRODUCT XYZ to cart and go to checkout
3. Try to apply discount code created in step 1 and get error "The product requirements for this discount are not met." 
4. Fill out remaining purchase details and click Purchase.

At this point, the checkout page reloads. You'll notice the code is attached to the cart, with the error messages at the bottom stating the discount code doesn't meet requirements.

If the customer doesn't go back and clear the coupon code field, it gets submitted, which probably makes some sense in case someone forgets to apply a coupon. But, it would be nice if the coupon code fails during apply, we blanked the field and/or did another check.

[Reported here](https://easydigitaldownloads.com/support/topic/user-cannot-purchase-after-discount-code-fails/)

**Comment by mindctrl** [comment]
It might be worth noting the customer details like email, name, etc. get cleared when this happens. If that needs to be in another issue, I can do that.

**Comment by pippinsplugins** [comment]
Sounds like the discount code is getting set in the cart session even when it's invalid. That's definitely a bug.

**Comment by cklosowski** [comment]
@pippinsplugins This _might_ have come in when we were fixing #2916, might be a good place to check.

**Comment by pippinsplugins** [comment]
Pretty sure you're right.

**Comment by cklosowski** [comment]
@mindctrl You are right, it's happening because if someone forgets to hit apply, we still try and attach it. I think we'll have to silently fail this though and just never attach it.

**Comment by cklosowski** [comment]
@mindctrl I'm not able replicate it, If I follow the steps you listed:

| If the customer doesn't go back and clear the coupon code field, it gets submitted, which probably makes some sense in case someone forgets to apply a coupon.

It clears for me.

**Comment by cklosowski** [comment]
Ok @mindctrl Can you check branch ```issue/3057``` and see if that fixes it for you?

**Comment by mindctrl** [comment]
@cklosowski this fix seems to be good. Tested various scenarios and all worked.

**Comment by cklosowski** [comment]
Awesome thanks I'll get a PR together.
