### ISSUE TITLE
Two error messages when trying to use a discount code that has been redeemed.

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/Easy-Digital-Downloads#3058]
If someone tries more than once to redeem a discount code that's limited to single use per customer, the cart throws 2 error messages:
```
Error: This discount has already been redeemed.
Error: One or more of the discounts you entered is invalid
```

Do we need both error messages? The second one is probably technical correct in the sense that the discount code is invalid for this purchase, though it is a valid code overall that exists in the system. But, it's not useful in this context when a better error message is already given.

**Comment by pippinsplugins** [comment]
While neither is technically wrong, it probably would be better to only show one of the errors.

**Comment by cklosowski** [comment]
We'll probably not want to limit it to just this case, we could also probably meet the same case with expiration, I would imagine.

Should we always just limit the Discounts errors to the first error we run into?

**Comment by pippinsplugins** [comment]
I think it makes sense to limit to one error.

**Comment by cklosowski** [comment]
@mindctrl can you take a look at this now? It was actually 100% broken on my end, not limiting to single use at all.

**Comment by pippinsplugins** [comment]
Should be fixed now. Ready for more testing from `release/2.4`.

**Comment by mindctrl** [comment]
Looks good to me now.

**Comment by pippinsplugins** [comment]
Looks good.
