### ISSUE TITLE
Rial currency problem

### ISSUE THREAD

**Issue by EhsaanF** [easydigitaldownloads/Easy-Digital-Downloads#3059]
Hi there and thanks to you guys for awesome advancing in a limited time span.
Your users in Iran are very happy from seeing that EDD development team cares about Iranian people.

There is a little issue with Rial currency, It's shown in Settings page as "Iranian Rial (ریال)" and that is correct, but in prices, it is "RIAL"  and that's not good.

In the meantime, change "RIAL" to "ریال" in prices in Front-End and Back-End.
We'll thank you if you fix this issue,
Thank you.

**Comment by pippinsplugins** [comment]
I think we actually used to have it that way but then an Iranian user requested it be changed to just `RIAL`. We'll look into it for the next release, thanks!

**Comment by EhsaanF** [comment]
Thanks, but is there a way to change it using hooks or filters?

**Comment by pippinsplugins** [comment]
Yes. See this guide: http://docs.easydigitaldownloads.com/article/272-adding-currency-support-eddcurrencies

**Comment by pippinsplugins** [comment]
According to Wikipedia, there is no official standard for the symbol that is used. Some use `RIAL`, some use `ریال`, and some use `IRR`.

For this reason, we're not going to change it in EDD core at this time. For anyone that does wish to change it, there is the documentation linked above and also the [Currency Converter extension](https://easydigitaldownloads.com/extensions/currency-converter/), which allows you to edit the symbol on any currency:
![screen shot 2015-02-10 at 11 11 43 am](https://cloud.githubusercontent.com/assets/1034109/6132038/a33ad59a-b115-11e4-8e17-585bb89642b5.png)
