### ISSUE TITLE
Can't use price="0" while using price_id in [purchase_link] shortcode.

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/Easy-Digital-Downloads#3064]
When specifying a price_id in the shortcode, if you also add the `price="0"` option, you can't add an item to the cart. EDD says "Please select an option".

Example shortcode:
`[purchase_link id="740" price_id="1" price="0"]`

**Comment by cklosowski** [comment]
Looks like we might be hitting this case:
```
	            if( ! form.find('.edd_price_option_' + download + ':checked', form).length ) {
	                 // hide the spinner
	                $this.removeAttr( 'data-edd-loading' );
	                alert( edd_scripts.select_option );
	                return;
	            }
```
Will have to investigate it further.

**Comment by cklosowski** [comment]
@mindctrl We made some updates to this area in the last EDD Release, can you verify this is still the case?

**Comment by mindctrl** [comment]
@cklosowski yes, still an issue. Some more info.

## Shortcodes used to test
![image](https://cloud.githubusercontent.com/assets/1254870/6768008/51de90ec-d028-11e4-90f7-34ee352695b0.png)

## Difference in output
![image](https://cloud.githubusercontent.com/assets/1254870/6768004/c59bff8e-d027-11e4-81b3-902cc3d6e4f7.png)

https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/f93ddb2f367b96fd448097b39800f5606b36bc26/includes/template-functions.php#L193

**Comment by cklosowski** [comment]
@mindctrl on `release/2.5` I cannot replicate this. When I use a shortcode of:
`[purchase_link id="10436" text="add this" style="button" price_id="1" price="0"]`

It's added to the cart without a problem. This was with Vendd and Twenty Twelve.

**Comment by mindctrl** [comment]
@cklosowski this looks good now in 2.5.

**Comment by cklosowski** [comment]
Ok closing it out.
