### ISSUE TITLE
Theme conflict: in-browser receipt and Twenty Fifteen

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#3066]
Clearly some issues here:
![screen shot 2015-02-08 at 8 18 17 pm](https://cloud.githubusercontent.com/assets/1034109/6100182/afa1290c-afcf-11e4-8e2e-3a563b7e1ce6.png)

**Comment by mindctrl** [comment]
What's the context there? Looks ok on my Twenty Fifteen site. I notice that screenshot has a sans-serif font, but the theme ships with serif. Looks like someone customized it? This is what I see on stock.

![image](https://cloud.githubusercontent.com/assets/1254870/6107990/73a59348-b03d-11e4-92e3-31b4382050a2.png)

**Comment by chriscct7** [comment]
Ditto, mine looks fine

**Comment by pippinsplugins** [comment]
Are you guys looking at the purchase confirmation screen? I'm referring to `site.com/?edd_action=view_receipt&payment_key=xx`

**Comment by mindctrl** [comment]
I see what you mean now. Same thing on my site.

**Comment by pippinsplugins** [comment]
This is due to some really strange styles in 2015:
![screen shot 2015-02-15 at 7 34 36 pm](https://cloud.githubusercontent.com/assets/1034109/6206161/ba659894-b549-11e4-9499-8b9ec374895e.png)

**Comment by pippinsplugins** [comment]
Get rid of the background color and the box shadow and it works.

**Comment by pippinsplugins** [comment]
Much better.
![screen shot 2015-02-15 at 7 37 37 pm](https://cloud.githubusercontent.com/assets/1034109/6206187/1ea8a79c-b54a-11e4-8d04-f5aff63a079e.png)
