### ISSUE TITLE
Buy Now purchase button goes to payment processor on $0 items

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/Easy-Digital-Downloads#3068]
Steps to reproduce:

- Create $0 item and configure button behavior as Buy Now, or disable it and create a manual purchase link using the purchase link shortcode. Example: `[purchase_link id="1082" text="Buy Now" style="button" direct="true"]`
- Add item to cart.

If you're using Paypal, you get sent to Paypal with a $0 item. If you're using Stripe, the payment popup appears asking for email and credit card info.

**Comment by cklosowski** [comment]
@mindctrl @pippinsplugins So i've got this working, however I have an edge case...

Setup a product with variable pricing...and one (or all) of the options are ```$0.00```.

This will always trigger ```straight_to_gateway``` if a ```price_id``` is not sent to the short code.

Thoughts on if we fix that somehow?

**Comment by pippinsplugins** [comment]
Let's add a check to see if all prices are free. If they are, disable buy now. You could use the `get_highest/lowest_price_option()` functions for this.

**Comment by cklosowski** [comment]
Ok that was my thought too, we can do that. Should have this done shortly for review.

**Comment by pippinsplugins** [comment]
We could also add some javascript to revert to add_to_cart for the action
if the selected price option is free.

**Comment by cklosowski** [comment]
@pippinsplugins Yes, was going to do that. also, should we make ```$download->is_free``` return true if all options are $0.00? I think that'd be the best option here.

**Comment by pippinsplugins** [comment]
Yes, I like that.

**Comment by cklosowski** [comment]
Ok @ghost1227 Can you test this with Purchase Limits? I've done some basic testing with it, seems to work fine.

**Comment by ghost1227** [comment]
Sure thing!

**Comment by cklosowski** [comment]
For those curious the major changes are:
* When outputting the ```purchase_link``` shortcode, we verify if the item is free, and therefore change the ```edd_action_input``` to ```add_to_cart```
* ```$download->is_free``` now checks the low and high price if no ```price_id``` is provided and the download has Variable Pricing. If the highest AND lowest prices are ```0.00``` we return ```true```
* If a Variable Price product has a free item in it's variations, when the button is clicked, if the item selected is free ( or only free items are selected for multi-purchase products ), we change the action to ```add_to_cart``` instead of ```straight_to_gateway```

**Comment by pippinsplugins** [comment]
:+1:
