### ISSUE TITLE
Turn off code coverage on feature development branches

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#3071]
We should turn off code coverage on feature development branches. Code coverage should be run on commits to master, release branches, and on pull requests. However, if you're trying to develop a feature on a branch, the travis tests go alot slower, and need to be manually cancelled alot of times because the code coverage is run. We don't need to see code coverage during development of a feature, since it will be run when the PR for the feature is finally made. By turning off code coverage on feature branches, the travis tests can run in 30 seconds instead of 6 or 7 minutes, which is useful when trying to develop a feature and fix issues that show up in the Travis builds.

**Comment by chriscct7** [comment]
We can use the environment variables TRAVIS_PULL_REQUEST and TRAVIS_BRANCH to turn off code coverage on builds not for prs, or pushes to master, release/2.3, release/2.4, release/2.5, etc.

**Comment by chriscct7** [comment]
http://docs.travis-ci.com/user/ci-environment/

**Comment by cklosowski** [comment]
Ok, this commit did not kick off a build. I'm going to make a pul request and see if it does one.

**Comment by cklosowski** [comment]
I went the route of still running coverage reports...but restricting builds to only PRs and only commits/merges to Master or `release/*` branches.

With this way, a CI build isn't done unless a PR is created, and any updates to that PR will run another build, but it stops there being 2 builds run for each PR created.
