### ISSUE TITLE
December month data is plotted in January month in the earnings graph

### ISSUE THREAD

**Issue by sudar** [easydigitaldownloads/Easy-Digital-Downloads#3072]
If you choose to plot the earnings in the reports page using a custom range that includes the year end then the earnings for the month of December are plotted in January.

Here is the screenshot of the earnings graph that explains the issue.

![screenshot 2015-02-10 09 58 15](https://cloud.githubusercontent.com/assets/103148/6121578/f70d1944-b10b-11e4-84a3-0eca7db55a82.png)

**Comment by cklosowski** [comment]
Going to have to punt this one. It's a bug we need to investigate further. I can't find a solution to it as our data looks sane, and with an updated jquery.flot It still isn't fixed.

**Comment by chriscct7** [comment]
@cklosowski were you able to replicate this?

**Comment by pippinsplugins** [comment]
I've replicated this consistently.

**Comment by pippinsplugins** [comment]
Similar and likely related report: https://easydigitaldownloads.com/support/topic/report-with-custom-dates-bug/

**Comment by pippinsplugins** [comment]
This is happening because the the December point is being placed on the 31st, whereas the other months are having their point plotted on the first of the month.

**Comment by pippinsplugins** [comment]
@easydigitaldownloads/core-devs Any one up for testing this?

**Comment by cklosowski** [comment]
@pippinsplugins taking a look now

**Comment by cklosowski** [comment]
Ok I cannot actually accurately test this. My data is so skewed from my 9k payment January (WP CLI) that it looks like this:
![image](https://cloud.githubusercontent.com/assets/1390124/8172167/cacac7cc-1372-11e5-92e6-0a6ff58fe386.png)

however, it appears to be doing them separately now. and the changes look good to me.

**Comment by pippinsplugins** [comment]
Merged.
