### ISSUE TITLE
Buy Now buttons does not support purchase form quantity field

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#3076]
The `Buy Now` buttons do not currently support the quantity field that is shown on the purchase form, as introduced in #2125.

Pre-click: https://cloudup.com/cMztW9MCF9X
Post-click: https://cloudup.com/cJx39uiL6mz

**Comment by pippinsplugins** [comment]
@cklosowski It's close but not quite: 
![screen shot 2015-06-12 at 4 41 19 pm](https://cloud.githubusercontent.com/assets/1034109/8140525/e9fc1b12-1121-11e5-8957-379926cc6cb3.png)

The item price is 0.50, so the total should be 1.00.

**Comment by cklosowski** [comment]
@pippinsplugins Ah, yes, fixing

**Comment by cklosowski** [comment]
![image](https://cloud.githubusercontent.com/assets/1390124/8142083/ef50fa10-1126-11e5-8a86-b4dc3cb5ddbe.png)

**Comment by pippinsplugins** [comment]
Hmm, not sure I think something has broken with buy now buttons, at least with variable prices enabled. The button starts as Buy Now but then changes to Add to Cart as soon as a price option is selected. Instead of processing buy now, it's going to checkout.

**Comment by pippinsplugins** [comment]
I don't think the break is related to changes here, just noting it here because this is where I noticed it.

**Comment by cklosowski** [comment]
I'm getting an Add to Cart button, but it's acting like a buy now and going to PayPal.

**Comment by pippinsplugins** [comment]
With variable prices?

**Comment by cklosowski** [comment]
@pippinsplugins Yes, with variable prices.
