### ISSUE TITLE
Adding extra columns to cart table breaks the layout if you have fees

### ISSUE THREAD

**Issue by nikolov-tmw** [easydigitaldownloads/Easy-Digital-Downloads#3079]
If you want to add one(or more) custom columns to the cart, you can use the `edd_checkout_table_header_first` and `edd_checkout_table_header_last` actions to add the `<th>` elements and the `edd_checkout_table_body_first` and `edd_checkout_table_body_last` actions to add the `<td>`'s.

However there are no corresponding actions for the fees part of the cart table, which results in the table layout braking like this: 
![Cart table broken layout]
(http://screens.paiyakdev.com/Screenshot-at-2015-02-11_11:17:39.png)

I think there should be similar actions fired at the beginning and end of the `<tr class="edd_cart_fee"...>` tags so that you can at least print empty `<td>` there.

I believe this is a fairly trivial fix that won't break anything, but will make things better for any plugins that are trying to add extra information to the products(and the title field is not enough).

**Comment by danieliser** [comment]
Ill second that. This will come in handy with the EDD Music store extension im working on allowing me to list tracks etc when entire album is purchased.

**Comment by cklosowski** [comment]
This will be able to be addresses once https://github.com/easydigitaldownloads/Easy-Digital-Downloads/pull/3493 is merged. You'll have two hooks (one before and one after) the fees rows, so you can add an empty column if you need to. It's a different hook as the data passed is different, but should allow you to do what's necessary.

**Comment by nikolov-tmw** [comment]
Awesome, thank you for the update! :+1:
