### ISSUE TITLE
Variable option file price assignments are incorrectly reassigned during download creation

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/Easy-Digital-Downloads#3082]
Steps to reproduce:

- Create new product with variable pricing enabled.
- Add two or more price options
- Add files to File Downloads and configure Price Assignments for each pricing option. [Screenshot](http://cl.ly/image/0o0k0p0c0g3H)
- Publish download

At this point the Price Assignments have been shifted and reassigned. [Screenshot](http://cl.ly/image/060w0h3k0q3o)

Related:
Fix the Price Assignments from above and update the product. Everything is saved properly.
- Now add a 5th price option.
- The last file download price assignment gets immediately changed to the 5th price option. It even updates the text as you're typing it. [Screenshot](http://cl.ly/image/0s1d012J3z1l).
- The 4th option disappears from the dropdown because it's being overwritten in the step above. [Screenshot](http://cl.ly/image/2G203l0k1E22).
- Updating the product brings it back, with the correct assignment, but the last item gets its price assignment rewritten to the 4th option. [Screenshot](http://cl.ly/image/1W1n0t1P2e0K)

**Comment by cklosowski** [comment]
Also noticed that we don't allow the `All` option to be in the dropdown until there are `$options` passed into the `EDD()->html->select` method. `All` should be supported even when no options are available.

**Comment by pippinsplugins** [comment]
Works beautifully for me. I'm going to merge into master.

**Comment by mindctrl** [comment]
Looks good here.
