### ISSUE TITLE
Enhancement: Give Option Name field focus when clicking Add New Price

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/Easy-Digital-Downloads#3083]
When creating new variable price options, it would be nice if the Option Name field received focus when clicking Add New Price.
![image](https://cloud.githubusercontent.com/assets/1254870/6150760/469119c4-b1df-11e4-8793-20d661d0ff21.png)

**Comment by pippinsplugins** [comment]
:+1:

**Comment by danieliser** [comment]
I can tackle this one.

**Comment by danieliser** [comment]
Got a PR for this. Would like to discuss a rewrite of the JS for the future though. See a lot of ways we can improve on whats there.

**Comment by danieliser** [comment]
Also not sure what you use to minify your JS currently so I am not submitting a minified version with this as to not break your routine.

**Comment by danieliser** [comment]
Ignore the first PR, had some code that PHPStorm decided to reformat for me. Didn't notice till I submitted the PR.

**Comment by pippinsplugins** [comment]
When submitting PRs, do not worry about .min files. We take care of those just before release.

**Comment by danieliser** [comment]
Good to know.

**Comment by danieliser** [comment]
PR has been updated to reflect the requested changes. Should be good for merge now.

**Comment by pippinsplugins** [comment]
Thanks @danieliser !
