### ISSUE TITLE
Travis-CI Skipping 2 HHVM builds

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/Easy-Digital-Downloads#3092]
WP_VERSION=4.0 WP_MULTISITE=0 and WP_VERSION=3.9.2 WP_MULTISITE=0 on hhvm aren't running on any of our builds, they're killing themselves before running PHPUnit

**Comment by cklosowski** [comment]
@chriscct7 Yes, I'm not sure the reasoning on this yet either. If you have an idea, let me know. I think it was due to some include failing, for some reason.

**Comment by chriscct7** [comment]
I don't think WP core's unit testing suite and HHVM below 4.1 are compatible.

**Comment by chriscct7** [comment]
Removing the 2 problematic ones from our build matrix in #3114

**Comment by cklosowski** [comment]
This looks right. Not running HHVM on Pre-4.1 versions of WP.
