### ISSUE TITLE
Add support for banning email domains

### ISSUE THREAD

**Issue by ghost1227** [easydigitaldownloads/Easy-Digital-Downloads#3094]
As suggested [here](https://easydigitaldownloads.com/support/topic/idea-for-banned-emails/), it'd be cool for people to proactively disallow email domains, not just retroactively ban individual emails

**Comment by chriscct7** [comment]
+1. We could just use the format *@domain.com to block all emails from domain.com

**Comment by ghost1227** [comment]
Done, including passing new unit tests.

**Comment by pippinsplugins** [comment]
Instead of making this a separate box, as proposed in #3095, I'd like to see this be part of the current banned emails setting. If you want to ban a domain, enter `@domain.com`. If you want to ban a specific email, enter `email@domain.com`. Having too separate boxes seems overkill to me and clutters the UI.

**Comment by ghost1227** [comment]
A big part of why I didn't combine them comes down to sanitization. If we have both types in one box, we can't use the current array mapping to validate input. Do you have a suggestion for how we can safely handle sanitization for both simultaneously?

**Comment by pippinsplugins** [comment]
If the email starts with `@`, sanitize it for a domain only, otherwise a whole email.

**Comment by ghost1227** [comment]
Does array_map have an is_domain arg like the is_email we're using?

**Comment by pippinsplugins** [comment]
No, you'll need to do your own check. Use `strpos`

**Comment by ghost1227** [comment]
We're currently using `$emails = array_filter( array_map( 'is_email', $emails ) );` to sanitize emails. If we're potentially mixing addresses and domains, that whole premise goes out the window and we have to iterate through the array testing one at a time, right? Because that command will automatically filter out any non-emails. Or am I missing something?

**Comment by pippinsplugins** [comment]
Just modify that to loop through and look at each one individually. `array_map` is just a convenient `foreach()` loop in essence.

**Comment by ghost1227** [comment]
This is the best I've come up with, but there HAS to be better...

```
foreach( $emails as $id => $email ) {
    if( ! is_email( $email ) ) {
        if( $email[0] != '@' ) {
            unset( $emails[$id] );
        }   
    }   
}
```

**Comment by pippinsplugins** [comment]
That's on the right track. You will want an `else` in there as well for ones that are emails to ensure they get sanitized. You also need to sanitize the ones that start with `@`.

**Comment by ghost1227** [comment]
But it's that sanitization I'm lost on.  Other than trim() is there anything else we CAN do to sanitize?

**Comment by pippinsplugins** [comment]
Run all emails and domains through `sanitize_text_field`

**Comment by ghost1227** [comment]
OK, updated the PR to merge the fields. Tell me if I missed anything!

**Comment by pippinsplugins** [comment]
The way domains are checked is potentially dangerous. Right now you have `stristr( trim( $email ), $banned_email )`. This works but could also result in a valid email getting improperly banned.

For example, let's say that you have banned `accounts@test.com` then a real customer tries to purchase with `software-accounts@test.com`. Both emails would get banned even though only the first one should be.

You need to check for exact matches on the entire email and then also check only the domain.

Make sense?

Aside from that, this looks great.

**Comment by pippinsplugins** [comment]
One more change too. Let's modify how the emails are sanitized a bit on save.

First, run all emails through `array_map( 'sanitize_text_field', $emails );`

Second, loop through and do an is_email check, just as you are doing. That will make it so `sanitize_textt_field` is only called once. Reduces some logic.

**Comment by ghost1227** [comment]
I am checking for both... `$banned_email == trim( $email ) || stristr( trim( $email ), $banned_email )`

**Comment by pippinsplugins** [comment]
I know. It's the second check that's dangerous.

My banned emails: https://cloudup.com/cpoxCWh2h8e
My email on checkout: https://cloudup.com/cM4F8YyLQdx

My email should be valid, but it's banned: https://cloudup.com/c7Bm6x7LAFw

**Comment by pippinsplugins** [comment]
It's banned incorrectly because of `|| stristr( trim( $email ), $banned_email )`.

**Comment by pippinsplugins** [comment]
That logic needs to be changed to `OR email domain matches banned domain`
