### ISSUE TITLE
Coupon appears to apply when product requirements not met

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/Easy-Digital-Downloads#3097]
When you make a coupon that excludes X, and then you go checkout with X and try to use the coupon, the coupon appears to apply but doesn't affect the overall cart total. When the coupon requirements aren't met, it shouldn't try to apply.

**Comment by cklosowski** [comment]
no discount is given though right?

**Comment by mindctrl** [comment]
Did you test this in master/2.2.8? There was an issue like this addressed there.

**Comment by pippinsplugins** [comment]
Correct, no discount is given. For example, here's a real purchase of EDD Core Extensions bundle: https://cloudup.com/cz7mxUavVOx

No discount but the code was applied.

**Comment by pippinsplugins** [comment]
My guess is that `edd_discount_product_reqs_met()` is returning `true` when it's not supposed to.

**Comment by pippinsplugins** [comment]
Requirements that discounts on the EDD site use: https://cloudup.com/ctWQiafmd3i

**Comment by pippinsplugins** [comment]
I can't make this happen. Works perfectly on my localhost.

**Comment by chriscct7** [comment]
What are you running on localhost? Master or release/2.3?

**Comment by chriscct7** [comment]
This might be a duplicate of the https://github.com/easydigitaldownloads/Easy-Digital-Downloads/pull/3069 issue if you're running master

**Comment by cklosowski** [comment]
@chriscct7 It's very likely it is a duplicate. Can you test out master, and now 2.3 as we've updated 2.3 with master after 2.2.8 went live?

**Comment by chriscct7** [comment]
Ask @pippinsplugins. Its on his site. I don't have a discount code that I can use to test it with

**Comment by pippinsplugins** [comment]
I tested both 2.3 and master. I couldn't make it happen in either.

**Comment by pippinsplugins** [comment]
Not closed, it still happens. I saw it happen on the EDD site today.

**Comment by pippinsplugins** [comment]
I just can't replicate it anywhere else :)

**Comment by chriscct7** [comment]
Yeah but is EDD running master? I think we already fixed this for 2.3 in #3069

**Comment by pippinsplugins** [comment]
It's in master

**Comment by cklosowski** [comment]
Ok the issue appears to be in the data sets:
The `$cart_ids` is coming through like so:
```
array(2) {
  [0]=>
  string(3) "561"
  [1]=>
  string(3) "559"
}
```

But the `$exclude_ps` is looking like this:
```
array(2) {
  [0]=>
  int(559)
  [1]=>
  int(561)
}
```

By that standard, the `if( $cart_ids == $excluded_ps )` check would fail.
