### ISSUE TITLE
Cache selectors in admin-scripts.js

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#3100]
As raised in https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/3065#issuecomment-73667590, there are a lot os selectors in our admin JS that could benefit from being cached instead of traversing the DOM every time.

Here's one example: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/assets/js/admin-scripts.js#L129-L135

**Comment by danieliser** [comment]
If there are no objections, I'll be glad to tackle this one. Another future enhancement would be to bring the entire JS code base up to standards with JSLint testing as well but thats another issue.

**Comment by pippinsplugins** [comment]
Go for it!

**Comment by danieliser** [comment]
Awesome. Will start this week on it.

Although a seperate issue in general but kind of relevant to this, I have seen several mentions of a general refactoring of the JS. Is this something that is still being discussed? As I said I can see dozens of places that we can improve both performance and extendability in both admin and front end. This would lead to the ability for extensions to tap in to those functions and extend them as needed which could both increase feature sets and decrease performance hogging duplication of code. 

I have a great deal of JS and jQuery experience and would love to take on a refactor of the edd code.

**Comment by pippinsplugins** [comment]
General refactoring is fine as long as it serves a greater purpose than just refactoring for the sake of refactoring. As long as there are performance or reliability improvements, refactors are welcomed, just open a separate issue for each location.

**Comment by danieliser** [comment]
I will agree with that to a point. But you yourself have stated many reasons that is not the case https://pippinsplugins.com/refactor-your-code-over-time/ :+1: 

That said I have never worked on the EDD JS, and from a developer who has written both jQuery plugins and plugins based around them, there is a lot of room here to both improve and grow.

One thing is that the current code base utterly fails JS standards testing. This not only makes maintaining it tougher, but also makes it more prone to breakage.

My suggestion is simply to allow a new set of eyes to go over it. There are a lot of ways it can currently be improved.

- Using custom events is basically the same as adding hooks and filters in WP. Allows it to be extended in many ways that currently are not possible.
- JS Linting the code will make it both more readable & more reliable in general.
- There are several sections of code ( not including .show() / .hide() ) that have performance implications
- Reduce duplication of code, which is not a large issue in the current code base, but when you consider it is not extendable currently, extensions have to duplicate functionality to get the results they are after.

Consider the changes I submitted on #3083, by adding in a custom event, now users, developers and the like can do additional work without having to piggyback the add click event.

I will put together some ideas for future work on the matter and see where it goes from there.

**Comment by pippinsplugins** [comment]
If something "utterly fails JS standards testing", that is far from refactoring for the sake of refactoring :)

**Comment by danieliser** [comment]
Fair enough. :+1:

**Comment by chriscct7** [comment]
After this is done, we need to throughly test this on any extensions that enqueue or use the EDD js files.

**Comment by danieliser** [comment]
Are you talking about a major refactor, or the original issue at hand? The refactor will require extensive testing for sure, but that is likely a v2.5+ issue leaving ample time for said testing.

The current issue shouldn't require too much testing as it will simply be preventing extra dom transversals for subsequent usages. Testing for this issue should be limited to the EDD core scope but I see no issue testing it against any extensions you believe need to be tested.

**Comment by pippinsplugins** [comment]
This is a pretty minor one in terms of testing, so I don't see much likely hood for problems.

**Comment by chriscct7** [comment]
I was referring to the refactor

**Comment by danieliser** [comment]
Agreed. It will need extensive testing. One of the first things that needs to be done is to try and make a list of things that need to be accounted for and tested. That way we know ahead of time what and don't miss anything in the cracks.

**Comment by cklosowski** [comment]
Did some work on this. So far I've found the ones that are repeated more than once and tried to cache them for later use. The most optimization came in the `EDD_Customers` object, which is the JS for the customers view. I was able to create a single item in the object just for all the repeated selectors (since there was a lot of reuse of targets by design), and cached them as their own separate object, so they can be reused by other parts of the object.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
Much better.

**Comment by danieliser** [comment]
Damn I forgot about this one. I have a set of changes locally for this, @cklosowski did your changes address this fully or just one subset of the overall JS?

**Comment by cklosowski** [comment]
It addressed changes only in `assets/js/admin-scripts.js`. If you have a set, push em up and put a PR, just note this issue and that we have two, no harm in having both, and picking the best of both worlds if we can.

**Comment by danieliser** [comment]
@cklosowski Actually that works out, because mine mainly focused on the front end. My changes in admin were minimal so far.

**Comment by cklosowski** [comment]
SWEET! Thanks for the PR, will take a look in a bit.

**Comment by cklosowski** [comment]
Reopening to take a look at the changes @danieliser has as well.

**Comment by cklosowski** [comment]
@danieliser do you have this ready for a PR?

**Comment by danieliser** [comment]
@cklosowski Will try to get it cleaned up tonight and tomorow to have it submitted for testing. Sorry been out all day.

**Comment by cklosowski** [comment]
No worries. We've merged my changes to make beta 1. But once yours are submitted well review.

**Comment by pippinsplugins** [comment]
I'm closing this. If further improvements get submitted, we can put them in 2.4.1/2/3.
