### ISSUE TITLE
Download Stats are being increased when in TEST mode

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/Easy-Digital-Downloads#3101]
When a purchase is made in test mode, a download's earnings and purchase count are being increased. This should not happen.

FYI: Sales logs **are not** affected by this issue.

**Comment by pippinsplugins** [comment]
We still increment customer stats in test mode:
```php
	// Increase the customer's purchase stats
	$customer = new EDD_Customer( $customer_id );
	$customer->increase_purchase_count();
	$customer->increase_value( $amount );
```

Thoughts?

**Comment by cklosowski** [comment]
I think we shouldn't increase any stats of downloads, store, or customer when in test mode...

This is the bulk of support tickets of people who want to reset their account...b/c they test on live sites

**Comment by pippinsplugins** [comment]
:+1:

**Comment by cklosowski** [comment]
Sorry accidentally deleted my comment. My vote was to *not* increase stats when in `TEST` mode.

**Comment by pippinsplugins** [comment]
Ok, in that case, let's get some other feedback.

**Comment by sdavis2702** [comment]
I don't think any of the stats should be affected by Test Mode. 

Sure, I've seen a few tickets where users either didn't understand Test Mode or switching away from Test Mode and going live resulted in numbers that weren't accurate. But I 100% feel that Test Mode should work, and not affect stats at all.

**Comment by ghost1227** [comment]
I'm going to defer to group consensus. Either way we set it up causes potential problems for a subset of our users, so I don't see any reason one way is preferable to the other. As @chriscct7 brought up, the only _ideal_ solution would be to make it configurable. Unfortunately, that causes all sorts of other issues, so a lot of work would have to be done to optimize/rework how the queries are done and/or how test mode data is stored.

**Comment by pippinsplugins** [comment]
What about this issue.

With the new customer management UI, we have a screen that looks like this:
![screen shot 2015-02-16 at 11 43 08 am](https://cloud.githubusercontent.com/assets/1034109/6216567/047ba400-b5d1-11e4-8f64-afb7b3645b4d.png)
Imagine the customer has made two purchases while `Test Mode` is enabled. The sales will show up in the table, but `Completed Purchases` will be 0. Is that too confusing?

**Comment by ghost1227** [comment]
@pippinsplugins regarding the new UI issue, what if we simply added a class to rows that were purchased while test mode was enabled to add highlighting or something?

**Comment by pippinsplugins** [comment]
@ghost1227 That's an interesting idea. I like it, but let's do that later, perhaps for 2.4.

Can each person vote pick A or B for me? Which ever has the most votes is the way we'll go.

A. Increase stats regardless of test mode status.

B. Never increase stats of any kind when Test Mode is enabled.

**Comment by sdavis2702** [comment]
B

**Comment by mindctrl** [comment]
B for now.

**Comment by chriscct7** [comment]
B

**Comment by cklosowski** [comment]
B, until we come up with a better TEST mode.

**Comment by ghost1227** [comment]
Since @pippinsplugins said I have to vote, and I said I'd side with the majority, and the majority already said B, I guess I'm voting B too!

**Comment by cklosowski** [comment]
:sheep:  :P j/k

**Comment by pippinsplugins** [comment]
Ok, B it is.
