### ISSUE TITLE
Type handling issue with edd_get_purchase_form_user

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/Easy-Digital-Downloads#3112]
It seems like ```$valid_data``` defined by ```edd_purchase_form_validate_fields()``` on line 32 of https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/process-purchase.php#L32 can return false however, ```edd_get_purchase_form_user()``` which calls uses ```$valid_data``` on line 46 doesn't handle if ```$valid_data``` is a boolean as opposed to an array. We should add some protection there.

**Comment by pippinsplugins** [comment]
Yep, but not for 2.3.

**Comment by chriscct7** [comment]
Agreed. I think we should fix this in 2.4 though. Its only a matter of time before this causes a problem for someone

**Comment by pippinsplugins** [comment]
:+1:

**Comment by cklosowski** [comment]
Not to mention we assume that `$valid_data` has keys later:
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/process-purchase.php#L93

Going to tackle this now.
