### ISSUE TITLE
CLI Class needs unit tests

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#3116]
"add another issue for unit tests for CLI and assign it (and API) to me. I'll take care of them sometime this weekend or monday at the latest" - @ghost1227

**Comment by cklosowski** [comment]
Since these are nice to have, i'm dropping them into 2.4...we're WAY overloaded for 2.3 and running short on time.

**Comment by chriscct7** [comment]
The agreement with @ghost1227 was if he didn't have his pull request done by this upcoming weekend, it would be punted to 2.4.

**Comment by ghost1227** [comment]
I also said that this and the API unit tests would get written by Monday night. It'll be in before 2.4, whether or not you merge it is your call.

**Comment by pippinsplugins** [comment]
2.4 please

**Comment by pippinsplugins** [comment]
Removing milestone until @chriscct7 can get to this.

**Comment by chriscct7** [comment]
Realistically this is never going to get or need unit tests, as long as the underlying functions it is calling are unit tested. Unless someone sees a current need to separately test the cli commands from the functions those commands are calling, closing
