### ISSUE TITLE
The download class doesn't have a post_status key as used in edd_get_purchase_link

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/Easy-Digital-Downloads#3144]

**Comment by pippinsplugins** [comment]
Anytime creating an issue like this, please link to the actual error on scrutinizer so others can see it.

**Comment by pippinsplugins** [comment]
Is there a way we could automatically setup the properties of `WP_Post` without manually declaring every one of them? We can't extend WP_Post since it is marked as `final`

**Comment by pippinsplugins** [comment]
By the way, this isn't just for `post_status`, it's for all properties on `WP_Post` that we don't explicitly setup.

**Comment by chriscct7** [comment]
https://scrutinizer-ci.com/g/easydigitaldownloads/Easy-Digital-Downloads/issues/release/2.3/files/includes/template-functions.php?orderField=path&order=asc#inspectioncomment-557442657

We should set them all explicitly up, so that other developers looking at that class understand they are there

**Comment by pippinsplugins** [comment]
I'm fine with just adding them.
