### ISSUE TITLE
Notice at class-edd-license-handler

### ISSUE THREAD

**Issue by JeroenSormani** [easydigitaldownloads/Easy-Digital-Downloads#3148]
Hey,

I'm getting this notice when deactivating a license. Took a screenshot to hopefully make things a bit more clear.
![screen_shot_2015-02-15_at_11_26_32](https://cloud.githubusercontent.com/assets/5774447/6202943/fb8c81dc-b505-11e4-9563-227fd753f1db.png)

I don't know if `success` is deprecated for the deactivate response, or was never there. I did notice a `success` param at the activation response.

A easy fix would be to add a `isset`, but that might not be the best solution as it might be dead code. 

Hope that makes sense.

To be clear, this error is in the `easy-digital-downloads/includes/class-edd-license-handler.php`

@pippinsplugins

**Comment by pippinsplugins** [comment]
Whoops!

**Comment by pippinsplugins** [comment]
Turns out this is a Software Licensing bug. I'll get it fixed.
