### ISSUE TITLE
Test Mode is confusing. Let's move it. 

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/Easy-Digital-Downloads#3154]
Test mode was originally designed to let site owners test their cart. Basically when it was originally conceived it was designed to let people add items to cart and checkout (to the sandbox version of their gateway). At one point we used to remove all sales and earnings data when test mode was flipped off. Then that got removed. Now, if someone has test mode on, earnings and sales data don't appear.

The problem is, that many users are confused by test mode. Alot of people start testing their site with test mode off, requiring them to install a plugin to reset all of their data. Then we get the problem that with test mode on, you can't test things like reports, because that data isn't being kept.

One of the ideas we could consider for 2.4, is removing test mode. This would involve a couple changes. Obviusly there would be no more test mode setting. We would add a new "Sandbox mode: on/off" for each gateway. Finally we would add a simple "reset all store data" option. I'd like to see that implemented as a tab in the settings panel.

Why it's own panel. Well, test mode is really confusing right now, particularly when you have extensions. Let's say I have Frontend Submissions turned on. When I turn on test mode, how should that impact Frontend Submissions? Should it not save user meta? And when I turn test mode off, what happens to the vendors made in test mode? Do they stays as vendors.

I think we could just have an intuitive tab with checkbox options. 
Reset EDD core (sales data, reports, customers, etc) would be hte default checkbox, with a submit button. Then extensions can register more checkboxes in there. 

For example, with FES enabled, the panel might be:
Reset EDD core
Delete all vendor accounts
Delete all vendor products

etc etc. 

Or alternatively, we could just have a reset button and that triggers a edd_reset_store function. Extensions could hook into a do_action in that function and make choices on what it should reset.

Either way, even if we don't do this idea, we should come up with a way of making test mode more intuitive. If we keep it, a user should be able to turn test mode on, and test every aspect of EDD, and then be able to turn it off or reset EDD and with no consequences be good to go.

**Comment by danieliser** [comment]
I'd like to see a full reset option anyways, no matter the outcome of this. During extension development I am consistently having to manually go in and remove data everywhere. Often this means messing around in phpmyadmin.

+1

**Comment by pippinsplugins** [comment]
For starting on this, we will move `Test Mode` to the gateways tab and also make it so stats (earnings, sales, etc) always increment.

**Comment by chriscct7** [comment]
We'll also implement a reset edd button

**Comment by pippinsplugins** [comment]
:+1:

**Comment by danieliser** [comment]
+1 to that. sounds like a huge time saver.

**Comment by pippinsplugins** [comment]
With #3374, we now always increment stats.

The next decision to make is how to present test mode (for enabling sandbox credentials) to users.

**Comment by cklosowski** [comment]
@pippinsplugins #3374 also moved the setting to the Gateway tab.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
I think we can close this one out.
