### ISSUE TITLE
Past orders merged with user account based on email address

### ISSUE THREAD

**Issue by NateWr** [easydigitaldownloads/Easy-Digital-Downloads#3162]
I'm 99% sure this is intended, but wanted to describe what happened with 2.3 beta 1 so you're aware.

In a test environment I have consistently made purchases under an email address, then gone in and deleted that user and done it again, over several months. That's left a bunch of payments attached to the email address but no user.

When I upgraded to 2.3 beta 1, all these past orders were put under the control of a new user I signed up with using that email address.

This is great, and I presume intended. I just wanted to let you know in case there was any kind of unexpected data merging here. Customer panels look great. Thanks!

**Comment by pippinsplugins** [comment]
Yep, intended :) it's part of the customer DB upgrade
