### ISSUE TITLE
Tools tabs display poorly on mobile

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#3163]
As shown [here](https://s3.amazonaws.com/f.cl.ly/items/2G0210102T0w3I45210T/IMG_0077.jpg), the tools tab displays poorly on small screens. Let's fix that.

**Comment by ghost1227** [comment]
Any recommendations?

**Comment by chriscct7** [comment]
When you fix this, can you please @chriscct7 me. Gotta fix it in another extension as well

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
Improvement for tabs:
![screen shot 2015-05-25 at 1 49 00 pm](https://cloud.githubusercontent.com/assets/1034109/7801143/c038dbb6-02e5-11e5-8930-a9130dd85ec1.png)

**Comment by pippinsplugins** [comment]
![screen shot 2015-05-25 at 2 12 45 pm](https://cloud.githubusercontent.com/assets/1034109/7801298/261460a2-02e8-11e5-9c33-8a7035dcabb3.png)

**Comment by pippinsplugins** [comment]
Anyone care to review?

**Comment by ghost1227** [comment]
Reviewed... Looks beautiful to me! Everything seems to work well... anything specific beyond testing on various devices for functionality I should be looking for?

**Comment by pippinsplugins** [comment]
@ghost1227 mostly just testing. Also pay attention to general usability and see if you notice any areas that could be improved further.

**Comment by pippinsplugins** [comment]
Closing as done. Re-open if you notice any issues.
