### ISSUE TITLE
API keys are difficult to generate / select on mobile

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#3164]
As described in [this ticket](https://easydigitaldownloads.com/support/topic/getting-api-keys-for-edd-iphone-app/#post-443004), it's really difficult to generate and select API keys from mobile.

 Related to #3163

**Comment by ghost1227** [comment]
Any recommendations?

**Comment by pippinsplugins** [comment]
Let's look at putting each key on a separate line and ensure each can be
selected easily

**Comment by ghost1227** [comment]
Instead of doing three cells, doing one cell with the public, secret and token on separate lines?

**Comment by pippinsplugins** [comment]
That's an option. Might just look at replicating the standard posts table's mobile view.

**Comment by chriscct7** [comment]
Maybe instead on mobile a click to copy button.

**Comment by pippinsplugins** [comment]
Either click to copy or we could put the key inside of an input field. That'd fix the selection issue.

**Comment by spencerfinnell** [comment]
A click to copy/copy to clipboard implementation could be extended to #3339 as well.

**Comment by cklosowski** [comment]
:+1: for Click to Copy.

**Comment by cklosowski** [comment]
I think we need to take both approaches. Make them easily selectable, but also offer a click to copy. Most click to copy solutions require flash and javascript. While JS is required for WP To work, flash is not, so we should have the fallback work just fine.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
Work in progress in `issue/3164`
![screen shot 2015-05-03 at 8 33 15 pm](https://cloud.githubusercontent.com/assets/1034109/7448009/a5fba24c-f1d3-11e4-818b-90d7dcce5ad2.png)

**Comment by pippinsplugins** [comment]
I'm not sure we should add `Click to Copy`. To do that in a cross-browser compliant manner, we have to add a new JS file (unless someone knows of some magic I don't). Considering how rarely this page is interacted with, I don't think that's a worthy tradeoff.

**Comment by chriscct7** [comment]
Put the JS inline?

**Comment by pippinsplugins** [comment]
It's a whole JS plugin, not just a few lines.

**Comment by chriscct7** [comment]
Ah, I forgot NPAPI was removed from Chrome. Else that would've been awesome (for everyone but IE users).

What's the issue with a new JS file specifically?

**Comment by pippinsplugins** [comment]
It's just extra stuff for a page that most users only ever use once.

**Comment by chriscct7** [comment]
So we just load it for that page. What's the problem with that?

**Comment by pippinsplugins** [comment]
It still increases the size of the EDD install base.

I'm not saying it's a significant impact, just that it _is_ an impact that
should be considered.

**Comment by mindctrl** [comment]
While click to copy is slick, I'm hesitant to add a whole new 3rd party JS plugin to maintain/update/deal with for how little this is used. I think the input field method here works fine.

**Comment by pippinsplugins** [comment]
@mindctrl Thanks for the feedback.

**Comment by cklosowski** [comment]
:+1: for skipping click to copy. I think it's unnecessary in such a small location that isn't heavily used. Inputs work just fine.

**Comment by pippinsplugins** [comment]
Sweet, then #3382 ready for review.

**Comment by cklosowski** [comment]
Can we actually also improve them here too:
![image](https://cloud.githubusercontent.com/assets/1390124/7458394/04d2ad18-f249-11e4-89bf-34118db408e9.png)

Just thinking we could drastically improve the hit area with an input there on mobile, than how it currently stands as spans.

**Comment by pippinsplugins** [comment]
Ah yes, good catch.

**Comment by pippinsplugins** [comment]
![screen shot 2015-05-15 at 2 41 39 pm](https://cloud.githubusercontent.com/assets/1034109/7660533/85972c88-fb10-11e4-8622-24f54e7cb5e3.png)

@cklosowski How's that?

**Comment by cklosowski** [comment]
Much better.
