### ISSUE TITLE
Introduce edd_update_option

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/Easy-Digital-Downloads#3181]
We desperately need an edd_update_option function as many extensions and even some core unit tests need to adjust the value of options. 

Just a simple function that takes in the key and the values and returns the result.

**Comment by pippinsplugins** [comment]
Yep, we've needed one for a while now.

**Comment by pippinsplugins** [comment]
@cklosowski #3182 is finished and the build is passing (I updated all unit tests to use the new functions). Could you review it and merge if you approve?

**Comment by cklosowski** [comment]
Reviewing now @pippinsplugins
