### ISSUE TITLE
Allow quantity data to be exported in payment history

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/Easy-Digital-Downloads#3185]
Exporting payment history doesn't include quantity sold.

Related. When multiple items are purchased, they're grouped together in a single row in the payment history export. Anything that deals with exporting quantity data would probably mean splitting each item sold out into its own row.

This data might look something like this:
`Item sale price - Quantity sold - Amount - Transaction ID`

But how do you record the total transaction amount? New line for that transaction ID? Thoughts?

**Comment by pippinsplugins** [comment]
I believe we have another issue related to splitting items out into multiple rows.

**Comment by cklosowski** [comment]
This will be fixed alongside #3444

**Comment by pippinsplugins** [comment]
This has been completed.
