### ISSUE TITLE
Proposal: Remove Price Inclusive of Tax Option

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#3186]
This ticket, proposes the idea of removing the price inclusive of tax option but _without_ removing any of the existing functionality we have in EDD core (it may take a couple read through for this to be understood)

People use the "enter price inclusive of tax" option for 2 main reasons:
- They are required to show the price inclusive of tax, by law, on the product page
- It's easier to setup a product so the total price at checkout will be a specific number (say 19.99)
- Let's people charge the same total price everywhere in the world regardless of the tax amount

The main problems with this option are:
- It causes alot of bugs with the tax api
- Its the root cause of a rounding issue #3104 
- It makes for alot of complications inside EDD core when figuring out the item price
- It forces us to back calculate the product price and the amount of tax inside of it on the checkout page
  - It causes alot of complexity for all of our extensions

What if we could provide all the benefits of this option, without providing the option? 
This ticket, proposes the idea of removing the price inclusive of tax option.

Here's how it would work:
- On the edit product page, we'd add a new column next to the price called "Price after tax", where we'd use a bit of JS to automatically calculate the price after tax by adding the price to the left + the tax for the product based on the base country. This lets people instantly see how much their product will cost after checkout. 
- We continue using the "display product price inclusive of tax" on the product page, but we'd simply the logic greatly, to simply just $product_price_to_show = $product_price + $product_price \* $tax_rate;
- On checkout, since all product prices are entered exclusive of tax, our logic here is greatly reduced, because we don't need to back calculate anything, which solves the problem completely about taxes after discount calculations
- We'd use an update routine to set all currently set prices inclusive of taxes and back calculate and save the amounts exclusive of taxes

This lets people get all of the legal and convenience benefits of entering the product prices inclusive of tax on the backend without actually offering that option. It would take the entire tax API and simplify it so greatly, @pippinsplugins might actually start liking that API

Removing this option and providing complete backwards compatibility in terms of functionality and code really isn't as hard as it sounds.

We could rip out so much code (thousands of lines of pure tax calculation torture), headaches, heartaches, and needless complexity while providing everything we provide right now in terms of functionality. 

The end result? Putting the Easy back in Easy Digital Downloads.

**Comment by chriscct7** [comment]
As for the same total everywhere crowd, I feel this a minority of users compared to the other two use cases, and I haven't come up with a solution for them yet, but I think its something we can come up with a solution for. If there's a problem there is a solution waiting to be discovered.

**Comment by pippinsplugins** [comment]
No, this cannot be removed. EU users will flip us the bird over and over and over.

**Comment by pippinsplugins** [comment]
OK just re-read what you wrote.

Honestly, I think that's probably just asking for far more trouble than it's worth.

**Comment by chriscct7** [comment]
Why? We're providing the same output they had before

**Comment by pippinsplugins** [comment]
I'll look at it again later before jumping to any further conclusions :)

**Comment by chriscct7** [comment]
Sure. If you have any questions let me know. The idea is premised on the point that no existing functionality would be lost. Anything you can do today, you'll be able to do tomorrow. The only difference is how the number calculations themselves work and how the numbers are inputted.

**Comment by bseddon** [comment]
For what it is worth, I agree with Pippin's first reaction.  The reality is that some users want and expect to be able to enter a 'final' number and have everything workout from there.  While they may be a minority, that doesn't seem to be a reason to drop the functionality.  There would be tons of functionality you would drop if this is the rationale for selecting product features.

In some European countries (e.g. Germany, Denmark) it is the law that prices are shown inclusive of VAT.  Therefore the mindset is that product prices are entered with tax and that tax is computed.  If the buyer wants to see a price without tax, the net price is computed.

An issue right now is that the inclusive price is always calculated.  That is, if I have an entered price of 9.99 then the price shown at checkout is the computed net price plus the computed tax.  This algorithm can give the wrong answer.  Surely the correct thing to do is to fix the gross price when this is the value the user has entered then compute the tax and compute the net value by subtracting the computed tax.  This way when the user has selected the option to enter values including tax, the answer will always be correct. It then doesn't matter whether the tax is rounded up or down as the net is computed from it.

Another reason to fix the issue, is that WooCommerce gets it right.

**Comment by chriscct7** [comment]
@bseddon thanks for your thoughts.

Yep, we have an open issue for the rounding issue ( #3104  , although WooCommerce miscalculates the amount of tax included, something I'll explain whenever I get a chance on #3165 ).

This issue doesn't seek to drop any functionality, just rework how the code works for calculating taxes and re-thinking the input. As mentioned above we're still working on a final price for everywhere solution

**Comment by Netzberufler** [comment]
Since I am a European user with a theme shop located in Germany I might be able to add some value here.

What makes it different for EU based shops is that every country has a different tax rate, but we always need to display the end price the customer is charged on the website.

If we sell B2C we have to charge the tax where the consumer is located. Example: If I sell my theme from Germany to a consumer based in the UK, I have to charge 20% tax, when I sell to Italy it is 22% and so on.

Example:
The price entered inclusive of tax is $60 ( => end price charged for customer).

Germany:
Item Price: $50.42
Tax (19%): $9.58
Total: $60

United Kingdom:
Item Price: $50.00
Tax (20%): $10.00
Total: $60

Italy:
Item Price: $49.18
Tax (22%): $10.82
Total: $60

I have literally  over 20 different item prices at my shop, based on the country of the actual customer. It will only work by calculating it backwards.

**Comment by chriscct7** [comment]
Right, that's what EDD does right now. The proposed issue is with a scenario like that but with discounts applied

**Comment by chriscct7** [comment]
Yeah, that's the problem we're working on :)

**Comment by Netzberufler** [comment]
I'm sorry, your solution sounded to me like it would not account for different tax rates. 

In my opinion the current system is working really fine and there were a lot of improvements so far. There are only very few issues left: e.g. https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/3165

**Comment by chriscct7** [comment]
Yeah that's correct. This isn't a solution, its just a ticket to track ideas we had on an idea we came up with during a dev session, and to see if it could be made feasible.

The current implementation to support inclusive prices requires a ton of code (we could remove 95% ish of the current tax code if we moved to just non-inclusive) and it causes alot of bugs, not just from the ones reported here on GitHub, but added complexity for determining product prices when used inside of extensions, which is really complicated for extensions to do because of the complexity in back converting the product price, to a point where most extensions just ignore the price is inclusive of taxes.

The more likely thing is we'll end up rewriting the tax system again in 2.4 or 2.5 to make these calculations simpler, but in the meantime, we're using this to keep track of any thoughts that solve the multiple country taxes, same final price issue

**Comment by Netzberufler** [comment]
Okay, then I'd like to share my idea. Not sure if it is possible to change that, but when I would start from the ground up this would be my solution.

I would account for the "prices inclusive of tax" feature at the very top of the whole calculation. Therefore I would change the function edd_get_cart_item_price() and add the backward calculation of the price at the bottom of the function.

```
if( edd_prices_include_tax() ) {
	$tax= edd_get_cart_item_tax( $download_id, $options, $price );
	$price-= $tax;
}

return apply_filters( 'edd_cart_item_price', $price, $download_id, $options );
```

As result the item price will always be without tax and all extensions should work fine. They do not have to account for the "prices inclusive of taxes" feature at all. 

The rest of the calculation from subtotal to the total amount is the same, no matter if prices are entered inclusive or exclusive of tax. You should be able to get rid of most complexity in these functions.

I would also write two taxing functions. The first one would be used in edd_get_cart_item_price() and has only the task to calculate the right price backwards if "prices inclusive taxes" are activated.

The second taxing function is the normal taxing function which calculates the taxes for the checkout cart. Since the item price is always exclusive of taxes, this function has not to make any difference between "Prices inclusive/exclusive taxes".

**Comment by MartinStehle** [comment]
I have the same interests as Netzberufler. What is the status now in case of "prices including tax"? I would be very glad about a solution for that.

**Comment by pippinsplugins** [comment]
In the upcoming 2.5 release, the subtotal is hidden from checkout if you use prices inclusive of tax.

**Comment by pippinsplugins** [comment]
I personally feel that we should close this as `wontfix` and not consider the removal of the price inclusive option.

**Comment by MartinStehle** [comment]
Neither wontfix nor removal is right for me here. The approach Netzberufler commented on 3 Mar 2015 is the right step. Was it implemented or will it be implemented in EDD?

**Comment by pippinsplugins** [comment]
@MartinStehle The approach that @Netzberufler proposed has already been done (in a slightly different way).

**Comment by cklosowski** [comment]
We've decided that we cannot do this due to the multitude of countries/regions that require that pricing be inclusive of taxes.
