### ISSUE TITLE
VAT plugin and 2.3

### ISSUE THREAD

**Issue by bseddon** [easydigitaldownloads/Easy-Digital-Downloads#3190]
The request to check the VAT plugin against the 2.3 branch has been received.  The result is that there is an issue in the VAT report by country (fixed) because the tax total has been moved from the payment meta structure to be a record in post meta.

Are there any other changes to be aware of?

The cause of the issue found is that the report accesses the tax element in the payment meta structure directly.  Is there a 'get_total_tax' function (or similar) I should be using to protect the plugin from changes like this?

I also checked our VAT reporting plugins ([ECSL](https://wordpress.org/plugins/vat-ecsl/) and [MOSS](https://wordpress.org/plugins/vat-moss/)). These seem to be OK.

**Comment by pippinsplugins** [comment]
For the tax changes, see https://github.com/easydigitaldownloads/Easy-Digital-Downloads/pull/3189

No changes should be required in your plugin, but they will be encouraged.

That's the only major change that I'm aware of that might impact you/

**Comment by chriscct7** [comment]
2.3 has been released
