### ISSUE TITLE
Add category / tag support to products end point of REST API

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#3191]
The products endpoint of the REST API should support querying products that belong to specific tags or categories.

Requested [here](https://easydigitaldownloads.com/support/topic/rest-api-how-can-i-get-products-from-a-specific-category/).

**Comment by cklosowski** [comment]
This will either have to be part of the `v2` endpoints, or we'll need a new endpoint. the current products endpoint doesn't accept anything more than a product ID.

**Comment by pippinsplugins** [comment]
Let's make it part of v2.

**Comment by pippinsplugins** [comment]
See #3734 too.

**Comment by garubi** [comment]
Wow! Great!
