### ISSUE TITLE
Add Multiple Items to Cart

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/Easy-Digital-Downloads#3192]
Right now if you wanted to add multiple price_ids to the cart in a single add_to_cart call you can't. We used to allow this but removed it in https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/76d7232f929e3362db039071d09b34b91d6009b9/includes/cart/functions.php#L139

For example, let's assume I have a variable priced product, where 2 of 30 price options are often purchased together. I want to make a call to add_to_cart that adds these both to the cart at the same time.

Right now, you can't do something like this:
```php
$options = array(
	'price_id' => array( 0, 1 )
);
edd_add_to_cart( $post_id, $options );
```

As opposed to calling edd_add_to_cart individually for every option I want to add, I'd really like EDD to do that work for me.

With this pull request, you can now do the above.

In addition, you can also pass in an array for the quantities and price_id and EDD will match them up and add them to the cart:

For example:
```php
$options = array(
	'price_id' => array( 0, 1 ),
	'quantity' => array( 2, 3 )
);
edd_add_to_cart( $post_id, $options );
```

Adds variable option 1 with a quantity of 2, and option 1 with a quantity of 3

Checks have been put in place to ignore extra quantity array items (the array of quantities is larger than the array of price ids). Further, if the quantity array is smaller than the price_id, the remaining items are mapped to the last quantity.

So lets say I want to add 3 options with a quantity of 2, and 1 option with a quantity of 4.
```php
$options = array(
	'price_id' => array( 4, 1, 2, 3 ),
	'quantity' => array( 4, 2 )
);
edd_add_to_cart( $post_id, $options );
```

In this situation, price_id 4 will have a quantity of 4, and price_ids 1, 2, and 3 will have a quantity of 2.

Unit tests have been added for over and undersized quantities, mapped quantities to price_ids (arrays are same size) and the lack of any declared quantity. If no quantity index is passed, it is assumed the quantity requested is 1, which is the EDD default for add_to_cart with 1 price_id

Further, tests have been added for the new helper function implemented that resizes the array as a helper function to PHP's `array_combine` function, so that you don't have to manually unset array items to match the sizes so you can `array_combine` them.

This was inspired by https://twitter.com/nikolovtmw/status/564837836411920384 who was trying to do https://gist.github.com/nikolov-tmw/700e2599147cb836c710

The PR for this needs to be fixed for a couple issues found but supports full backwards compatibility as well as adding the above mentioned enhancements

**Comment by chriscct7** [comment]
The pull request for this is #3070

**Comment by danieliser** [comment]
Not sure if this is valid place for this, but I would like to be able to add multiple items in one call as well. Using the current direct links 
checkout?edd_action=add_to_cart&download_id[]=6310&price_id[]=&download_id[]=5674&price_id[]=2

**Comment by chriscct7** [comment]
This isn't for links, this is for the edd_add_to_cart function

**Comment by danieliser** [comment]
Ok. I know i have seen a similar issue with the links on here somewhere, couldn't find it when I posted that. No worries.

**Comment by pippinsplugins** [comment]
We're going to go with the following logic:
```php
// to add multiple items
edd_add_to_cart( array( 
    2215 => array(
        'price_id' => 2,
        'quantity' => 2
    ),
    2215 => array(
        'price_id' => 1,
        'quantity' => 2
    )
) );

// To add a single item
edd_add_to_cart( 2215, $options );
```

**Comment by danieliser** [comment]
That looks solid. Should make processing easy as well. Are you gonna abstract the add functionality for use in a foreach or simply turn a sinlge item into an array before the foreach?

**Comment by cklosowski** [comment]
After some discussion, @pippinsplugins and I have decided to only support sending a single download ID, however in the options you can set price IDs...so:

```edd_add_to_cart( $download_id, array( 1, 2 ) );```

With this as well, we'll allow adding multiple price IDs from the customer Add to Cart URL with the format of:
```http://local.dev/edd/checkout/?edd_action=add_to_cart&download_id=16&edd_options[price_id]=0,2```

**Comment by pippinsplugins** [comment]
Works beautifully.

**Comment by pippinsplugins** [comment]
Note: I've updated the issue title to better represent the actual change we've made.
