### ISSUE TITLE
Proposal: Standard class for all table outputs

### ISSUE THREAD

**Issue by aky01** [easydigitaldownloads/easy-digital-downloads#3199]
Greetings!

it would be super useful if we had a class added to all table outputs so that we may target all for styling if possible. Right now all tables are produced with all different unique ID's (obviously) but no class - if we had a class for example of edd_table then we could easily target all tables produced by EDD without touching anything else that outputs a table etc. 

Jonathan

**Comment by chriscct7** [comment]
What tables are you referring to?

**Comment by aky01** [comment]
All tables that are output by EDD. Just a class that would be common to all tables produced.

**Comment by pippinsplugins** [comment]
I agree and would propose a simple `edd-table` class.

**Comment by aky01** [comment]
Yes perfect - thanks guys!
