### ISSUE TITLE
Senegal zip code regex might be off

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/Easy-Digital-Downloads#3200]
https://easydigitaldownloads.com/support/topic/problem-with-checkout-form-not-accepting-senegal-post-codes/

**Comment by cklosowski** [comment]
We're currently verifying 5 Digits:
```"SN" => "\d{5}",```

**Comment by chriscct7** [comment]
According to Wikipedia and alot of country regex sites, this is correct as is http://en.wikipedia.org/wiki/List_of_postal_codes

**Comment by pippinsplugins** [comment]
I think this is a close as invalid.
