### ISSUE TITLE
Proposal: Allow discount codes to be applied to completed purchases

### ISSUE THREAD

**Issue by syedbalkhi** [easydigitaldownloads/easy-digital-downloads#3202]
Often we get customers who forgot to enter the discount code (asking for a partial refund). Instead of refunding the purchase and making the customer buy again, we simply refund them the payment difference using the payment processor.

However it's not possible to apply that discount code post-purchase for EDD records / reporting.

It would be nice to have the ability to enter discount code by editing the payment. Perhaps the update payment metabox where it says Discount Code: None (can have the edit link next to it? -- very similar to how Visibility does in the Posts section).

**Comment by pippinsplugins** [comment]
We definitely need to add this.

Related to #2721 and #2625

**Comment by cklosowski** [comment]
:+1:

**Comment by zackkatz** [comment]
:+1:

**Comment by pippinsplugins** [comment]
I built a small add-on that adds this: https://github.com/easydigitaldownloads/edd-add-discount-to-payment

An actual implementation may need to be more robust.

**Comment by mindctrl** [comment]
Note from meeting: do we consider supporting recurring payments? If not, at least initially, we should make it clear in the UI.

**Comment by sunnyratilal** [comment]
Set to the 3.0 milestone as this was implemented with the merge of Manual Purchases into Core in #5295.
