### ISSUE TITLE
Add better handling for Buy Now

### ISSUE THREAD

**Issue by ghost1227** [easydigitaldownloads/Easy-Digital-Downloads#3204]
Currently, using the product list and grid shortcodes, products set to Buy Now still get labeled as 'Add to Cart'. We should research ways of handling this better to identify products as direct purchase vs cart.

**Comment by pippinsplugins** [comment]
Are you specifically referring to the text displayed on the button?

**Comment by ghost1227** [comment]
Yes. If there are other issues, let me know and I'll look into them.

**Comment by ghost1227** [comment]
@pippinsplugins ping

**Comment by pippinsplugins** [comment]
@ghost1227 Waiting on a refresh for the `release/2.4` branch on this.

**Comment by ghost1227** [comment]
@cklosowski  refreshed ping

**Comment by cklosowski** [comment]
merged and closing
