### ISSUE TITLE
Add support for Buy Now to free products

### ISSUE THREAD

**Issue by ghost1227** [easydigitaldownloads/Easy-Digital-Downloads#3205]
Currently, free products are exempt from buy now due to lack of email collection for logged out users. We should add a system in which logged out users are directed to an email collection form when they 'purchase' a free product with buy now enabled, then auto-create the purchase record.

**Comment by pippinsplugins** [comment]
Whether this happens as part of core or as part of a free extension, I'd love to see this happen. There are a couple of extensions that have tried to do this, but none of them are great. I'd love to see it done really well once and for all.

**Comment by pippinsplugins** [comment]
@ghost1227 and I discussed this and he's going to build it as an extension, so closing this.
