### ISSUE TITLE
Download Details widget should use taxonomy labels

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/Easy-Digital-Downloads#3212]
...and any other widgets this applies to. For example, the Download Details widget can display categories and tags, both of which are labeled with the taxonomy type. However, changing the taxonomy labels does not affect the labels found in this widget. I'm thinking it should.

Ticket that better explains how I found this: https://easydigitaldownloads.com/support/topic/change-category-and-tag-label/

**Comment by cklosowski** [comment]
So in working on this I found an interesting issue, we're using two different naming conventions on our taxonomies.

```
'name' => sprintf( _x( '%s Categories', 'taxonomy general name', 'edd' ), edd_get_label_singular() ),
'singular_name' => _x( 'Category', 'taxonomy singular name', 'edd' ),
```

Our `name` elements for `download_tag` and `download_category` both contain the post type singular label (by default `Download`). However our singular name contains just the label `Category`.  This leads to this type of situation on our Download Details Widget if we start using the registered labels:

With 1 Category Assigned (notice `Category:`)
![image](https://cloud.githubusercontent.com/assets/1390124/7401594/45a2198c-ee7a-11e4-9d94-ebd3d1cb4ccc.png)

With 2 Categories Assigned (see `Download Categories:`)
![image](https://cloud.githubusercontent.com/assets/1390124/7401611/6635996c-ee7a-11e4-8676-77fc30772e27.png)

The same goes for our tags.

I'm not sure where we want to take this but my opinion is we should either include the singular label in it, or not at all and just use `Category/Categories`.

**Comment by pippinsplugins** [comment]
I vote for just `Category/Categories`.

Customers on the frontend don't care to see `Download`.

**Comment by cklosowski** [comment]
:+1: That's the way i'm leaning too. Will let @SDavisMedia chime in and then make the move going forward.

**Comment by SDavisMedia** [comment]
I agree with you guys. :+1:

**Comment by cklosowski** [comment]
Sweet, moving forward :)

**Comment by cklosowski** [comment]
@pippinsplugins If you are good with this, let's merge it into `release/2.4` for greater testing.

**Comment by pippinsplugins** [comment]
Merged.

**Comment by pippinsplugins** [comment]
Seems to work great.
