### ISSUE TITLE
Don't check if ajax calls work if Airplane Mode plugin is active

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/Easy-Digital-Downloads#3215]
If the Airplane mode plugin is installed and enabled we should ignore the test. It's kind of annoying to see the error all the time.

**Comment by chriscct7** [comment]
Pull request submitted: #3216

**Comment by cklosowski** [comment]
We've set feature freeze for 2.3, punting to 2.4.

**Comment by cklosowski** [comment]
Strike that, we'll go 2.3.3

**Comment by pippinsplugins** [comment]
Oops, resubmitting to `master`.

**Comment by chriscct7** [comment]
Implemented in #3281
