### ISSUE TITLE
Proposal: Move Discounts Page to using the post edit screen

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#3222]
As proposed in #3198, we could move the edit discounts page to using a post edit screen.

The proposed reason for this is code reduction and to use the discount tag and categories to filter discounts on the discounts table.

After an extensive review of the discounts UI code, the code reduction argument should be avoided completely. At most, we're talking about removing 10 lines of code at most if we want to maintain backwards compatibility, while adding at least several hundred to use the edit screen, remove unwanted metaboxes, and registering and styling the desired metaboxes. Moving to the post edit screen will add at minimum a couple hundred lines of code. While not changing because of lines of code isn't a counterargument, lets not let ourselves believe that doing this is in any shape or form going to make the code any less complex or reduce the lines of code. The exact opposite will be true.

I've also thrown out the proposed suggestion that it's makes it easier for extension authors to add custom fields. It's just as easy to echo in a do_action the same HTML you would echo out in a metabox you would need to register. And the save function, for backwards compatibility reasons, would be written the same both ways anyway. There's really no difference.

So far, the only valid argument to doing it thus far, is that we obtain the metaboxes for tags and categories quite easily for the discount post type, with the idea that we use them to filter discounts on the discounts page. As a reminder, doing this is going to require even more code, and before anyone considers starting on a pr for this, it should be clearly written out how the UI to filter the discounts in the table using categories and tags is done. The only way that UI will be easy is if we let people filter using only 1 category and tag, at least that I can think of.

I'm against this idea, because frankly, if we move to using it, what is the net gain for developers and users? What extra functionality do we actually get from moving to it? We're going to add several hundred lines of code to get this new view, then even more to remove default metaboxes and CSS we don't want. And at the end of the day, the UI becomes more complicated for users. If we really want users to use discount tags and categories, we could simply add a dropdown for both, with like a couple dozen lines of code, providing a much better experience without any of the needed hassle.

I still think the better way to handle decluttering the discounts page is to just hide the single use discounts, but that's a thought I will continue on the other issue.

**Comment by pippinsplugins** [comment]
Punting this to 2.7. Too little time.

**Comment by pippinsplugins** [comment]
I don't think there's a big enough justification for doing this so am going to close as wontfix.
