### ISSUE TITLE
Integrate Amazon Payments into core

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#3223]
It'd be awesome to support Amazon Payments in EDD core: https://payments.amazon.com/home

**Comment by pippinsplugins** [comment]
Relevant API  doc: http://docs.developer.amazonservices.com/en_US/off_amazon_payments/index.html

**Comment by pippinsplugins** [comment]
Since this is a core gateway, it will need to support:
- [ ] standard purchases
- [ ] transaction ID tracking
- [ ] refund processing
- [ ] chargeback tracking
- [ ] recurring payments (done in EDD Recurring)

**Comment by chriscct7** [comment]
Do we want to also use FPS for automatic instant split with commissions?

**Comment by pippinsplugins** [comment]
Possibly but that's probably a secondary feature.

**Comment by cklosowski** [comment]
It looks like we'll be following this flow:
http://docs.developer.amazonservices.com/en_US/apa_guide/APAGuide_BuyerExperience.html

Assuming we're following the "Buyer experience with Pay with Amazon" method, about half way down that doc.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by cklosowski** [comment]
So the Amazon API requirements show PHP 5.3:
https://github.com/amzn/login-and-pay-with-amazon-sdk-php

**Comment by pippinsplugins** [comment]
We can enable it only on sites that support 5.3

**Comment by cklosowski** [comment]
Ok I'm good with that, just needed to make sure we're documenting this requirement :)

**Comment by pippinsplugins** [comment]
We'll need to adjust the endpoints based on the region. We have to provide separate endpoints for:
- GB
- DE
- Others

**Comment by pippinsplugins** [comment]
For EU merchants that use VAT, we have to extract the billing address from the API.

**Comment by pippinsplugins** [comment]
New PHP SDK (I think we should use this): https://github.com/amzn/login-and-pay-with-amazon-sdk-php

**Comment by pippinsplugins** [comment]
Magento version if we want a reference: https://github.com/amzn/amazon-payments-magento-plugin

**Comment by pippinsplugins** [comment]
Good, thorough setup documentation that we could use as a reference when building our documentation: https://github.com/amzn/amazon-payments-magento-plugin/wiki/Configuration

**Comment by pippinsplugins** [comment]
Note for docs: for recurring payments, there is a default of $500 per month per customer. To raise it, merchant must be approved by Amazon.

**Comment by pippinsplugins** [comment]
Let's support authorize and authorize and capture.

**Comment by cklosowski** [comment]
@pippinsplugins I'm going to assign this over to myself while I'm working on it.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
I have this nearly working but am getting a `Constraint` error when trying to process the charge:
```
          PaymentPlanNotSet
          The buyer has not been able to select a Payment method for the given Order Reference.
        
        
          ShippingAddressNotSet
          The buyer has not selected a shipping address from the Amazon AddressBook widget.
        
```

This just means that the payment / address hasn't been selected. . . .but it has. Not sure what's up yet.

**Comment by pippinsplugins** [comment]
Ok tracked that down.

**Comment by pippinsplugins** [comment]
Just discovered that the readme on Github has a lot of great info: https://github.com/amzn/login-and-pay-with-amazon-sdk-php

**Comment by pippinsplugins** [comment]
IPN testing tool: https://sellercentral.amazon.com/hz/me/hmi/ipn/main

**Comment by pippinsplugins** [comment]
Our registration URL: https://sellercentral.amazon.com/hz/me/sp/signup?solutionProviderId=A3JST9YM1SX7LB&marketplaceId=AGWSWK15IEJJ7&solutionProviderToken=AAAAAQAAAAEAAAAQnngerc8vYweGDt8byl2smgAAAHBgMm923quugHaGmPi%2B3sqo93TSL1aKwU85v71Zh7EXVK8De%2FuahjCFHft3cxN3rwAF4Iwg03sDW0jnkLULmFk7M1Fr69IV2XF477m0kU1EM0Z%2FbQssHdLai%2Fzoce1jZVmw8So3F2jhiDyfTHUK2AYP&solutionProviderOptions=lwa%3Bmws-acc%3B

Should be shown on settings.

**Comment by pippinsplugins** [comment]
Details for testing failures / declines: https://payments.amazon.com/documentation/lpwa/201750790

**Comment by pippinsplugins** [comment]
@cklosowski Any thoughts on how to handle buy now buttons? Open Amazon authentication then return and show the wallet / address on the product page?

**Comment by pippinsplugins** [comment]
Email with additional account details for testing EU accounts: https://secure.helpscout.net/conversation/96483220/10551/

**Comment by pippinsplugins** [comment]
This has been merged into release/2.4. If there's any major work that has to be done still, it can continue to be worked on in the issue/3223 branch

**Comment by pippinsplugins** [comment]
We have chosen to NOT add support for Buy Now buttons in amazon at this time.

**Comment by pippinsplugins** [comment]
Only thing left on this is testing with EU seller / buyer accounts for VAT addresses. https://secure.helpscout.net/conversation/96483220/10551/

**Comment by mindctrl** [comment]
Can we make the order of the keys and IDs match the order of the way they display on Amazon, to lower copy/paste errors?

In Amazon
![amazon](http://f.cl.ly/items/3e0d2A3r2k0D1L3f3r1e/Image%202015-06-25%20at%2010.24.26%20AM.png)

In EDD
![edd](http://f.cl.ly/items/281K0w3p1A3S3K2U2e0I/Image%202015-06-25%20at%2010.26.23%20AM.png)

Basically just move Client ID to the bottom?

**Comment by pippinsplugins** [comment]
I thought about that the other day (then promptly forgot). Agree 100%.

@cklosowski could you take care of re-ordering them?

**Comment by mindctrl** [comment]
"Merchant" is misspelled under the Seller ID field.

**Comment by cklosowski** [comment]
:+1:

**Comment by mindctrl** [comment]
Some issues around permalinks.

Example. if you change permalinks from 'pretty' to the default after having set up Amazon, it breaks the payments. You get 503 errors in the console. The setting in the payment gateways tab doesn't update to reflect the new structure. Can we refresh/flush that somehow?

**Comment by mindctrl** [comment]
Thoughts on shortening the connect button and moving some text to the label?
![button](http://f.cl.ly/items/2m342k3o332a0J3h0s2K/Image%202015-06-25%20at%2012.35.56%20PM.png)

**Comment by cklosowski** [comment]
@mindctrl this has already been shortened quite a bit, and is more in line with what the action does. It connects their seller account with the EDD branded process.

**Comment by mindctrl** [comment]
@cklosowski right, it's just that full sentences in buttons, with commas, looks kinda weird. That example moves the same text below. Button could maybe say "Connect Easy Digital Downloads to Amazon" instead? Like this:
![shot](http://f.cl.ly/items/253w013X2B1Y3F2d2B2q/Image%202015-06-25%20at%2012.51.26%20PM.png)

**Comment by pippinsplugins** [comment]
I like `Connect Easy Digital Downloads to Amazon`

**Comment by cklosowski** [comment]
@pippinsplugins we shouldn't be saving those urls for the endpoints, they are just for display. I'll try and fix them up so they don't populate the input.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by cklosowski** [comment]
Ok @mindctrl @pippinsplugins I've made a new settings type called `faux_input` (name up for discussion) that outputs an input field with no name, so it's never saved, but is readonly and the `std` value passed is the value. This allows people to output copy/pasteable data easier in our settings.

For the time being, since we're using `popup` not `redirect` as the auth method, we don't need to really tell them to update anything on the Amazon side of things but we'll want to warn them that they need to update their `Amazon Redirect URI` in the Seller Central Account once we do support `redirect`

**Comment by cklosowski** [comment]
As a note, I've added these changes into `issue/3223` that I recreated until we're good with them.

**Comment by pippinsplugins** [comment]
@cklosowski Wouldn't it make more sense to support faux inputs on all field types (at least input and textarea)? Seems like passing `readonly` to the arguments should automatically make it a faux field.

**Comment by pippinsplugins** [comment]
@cklosowski HTML entities are not properly encoded for the payment note: https://cloudup.com/c9B-I08zk7T

**Comment by cklosowski** [comment]
Entities should be fixed now.

**Comment by cklosowski** [comment]
Still looking into the EU/DE endpoints.

**Comment by pippinsplugins** [comment]
UK/DE endpoint bug opened as separate issue #3540

That closes this out.

**Comment by pippinsplugins** [comment]
This has been tracked down.
