### ISSUE TITLE
iOS App Enhancements

### ISSUE THREAD

**Issue by zackkatz** [easydigitaldownloads/Easy-Digital-Downloads#3224]
I would *love* to have a few more items on the Home screen of the iOS app:

* Average earnings (past week/month/quarter/year)
* Projected earnings (this week/month/quarter/year)
* Refund data (not sure in what form)

That way, I no longer have to do calculations! :1234:

**Comment by pippinsplugins** [comment]
These are definitely on our todo list :)

Since the app has it's own repository, I'm going to close this one and move it there. Thanks @zackkatz !
