### ISSUE TITLE
Suggestion: Allow auto-installing addons from the dashboard

### ISSUE THREAD

**Issue by aristath** [easydigitaldownloads/Easy-Digital-Downloads#3225]
Just a suggestion...

Since we already have a menu for this on Downloads => Addons, we could allow automatically installing addons.

I've already build this as a separate plugin consisting of 2 parts: a server-side plugin & a client: https://github.com/aristath/edd-remote-installer

I'm using it on my theme on https://github.com/presscodes/maera/tree/master/includes/remote-installer and so far it's working great...

The server-side plugin creates a json array that is then parsed by the client plugin to create the list of addons. It also integrates with the Software Licensing addon.
My implementation is a bit crude and basic, but it can very easily be adapted and extended. :smile:

**Comment by pippinsplugins** [comment]
It's not permitted to do this with the plugin hosted on WordPress.org so this has to be closed as wontfix, sorry.

**Comment by aristath** [comment]
Right... I forgot about that.
Thanks for replying!

**Comment by pippinsplugins** [comment]
I wish it was allowed :)

**Comment by aristath** [comment]
Yeah, me too!
On that note though, I always found it weird though that this plugin was allowed: https://wordpress.org/plugins/edd-beta-tester/ considering it's based on the github plugin updater (which is also not allowed on w.org)

**Comment by pippinsplugins** [comment]
Those are much more closely scrutinized now and not always permitted.
