### ISSUE TITLE
Display notice about files not being protected on NGINX

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#3226]
Since file downloads do not get automatically protected when running on NGINX, we should display a notice to site admins to let them know that they need to add a redirect rule to their site's config.

We will display a link to the help doc: http://docs.easydigitaldownloads.com/article/682-protected-download-files-on-nginx

**Comment by sdavis2702** [comment]
Obviously, I don't know the scope of this issue. But I think it's worth a really hard look at what can be done automagically. I know this issue was created to handle the problem at hand right now but I hope we can dig a little deeper into a better solution in the near future.

**Comment by pippinsplugins** [comment]
Agreed. If we can do something automatically, that'd be best.

**Comment by pippinsplugins** [comment]
![screen shot 2015-03-06 at 3 31 02 pm](https://cloud.githubusercontent.com/assets/1034109/6536755/ddc2c6a6-c415-11e4-8ce2-3ca03a5b5b89.png)

**Comment by sdavis2702** [comment]
Nice and bold and red and easy to understand. :+1:

**Comment by zanematthew** [comment]
@pippinsplugins Not sure if this is the best place to inform you, but there wasn't any nginx rules for WP networking here: https://docs.easydigitaldownloads.com/article/682-protected-download-files-on-nginx so this is what I used https://gist.github.com/zanematthew/5e7f446723f528f7ad96

```
# Block direct EDD downloads for WordPress Networking
location ~ ^/wp-content/uploads/sites/(.*)/edd/(.*?)\.zip$ {
    rewrite / permanent;
}
```

**Comment by pippinsplugins** [comment]
Thanks for that!

@topher1kenobe could you update the doc with this?
