### ISSUE TITLE
Item quantity fields not showing with [purchase_link] shortcode

### ISSUE THREAD

**Issue by sdavis2702** [easydigitaldownloads/Easy-Digital-Downloads#3230]
Make sure Item Quantities are enabled in the EDD settings. Set up a variable pricing product with multi-purchase mode enabled. View the single download page to confirm that the item quantity fields display for each variable pricing option. Once confirmed, use that product's [purchase_link] shortcode in a separate Post/Page. The item quantity fields don't seem to show.

I've was able to replicate just fine. 

Ticket: https://easydigitaldownloads.com/support/topic/purchase-link-shortcode-missing-quantity-adjustments/

**Comment by pippinsplugins** [comment]
Let's get this fixed in 2.3.3.

**Comment by pippinsplugins** [comment]
@sdavis2702 Fixed.
