### ISSUE TITLE
Disable Buy Now buttons when Taxes are enabled

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#3235]
We gets users every now and then that encounter issues with trying to use Buy Now buttons and taxes but then not seeing taxes get calculated. This is because the general Checkout process is required for calculating the taxed amount.

I'm proposing that we automatically disable the buy now options if taxes are enabled. In the future, once we have introduced a way to calculate taxes and use buy now buttons, we can remove this.

[Example case](https://easydigitaldownloads.com/support/topic/paypal-standard-not-passing-tax-to-paypal/#post-459754).

**Comment by mindctrl** [comment]
Looks like it still bypasses the cart and goes straight to PayPal if using the `direct="true"` option on the purchase_link shortcode.

**Comment by cklosowski** [comment]
@mindctrl Try that on for size

**Comment by mindctrl** [comment]
@cklosowski looks good now.

**Comment by cklosowski** [comment]
:+1: thanks
