### ISSUE TITLE
Username field on the Customers UI drops value on second edit

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/Easy-Digital-Downloads#3237]
When viewing a customer:
1. Click edit customer
2. Without changing anything hit cancel
3. Click edit customer 

The username value will be lost.

**Comment by chriscct7** [comment]
Someone should verify this on their install. It could be just mine. Really easy to do though

**Comment by pippinsplugins** [comment]
I'm not able to replicate this right now, but I do remember seeing it at least once.

@cklosowski can you replicate?

**Comment by mindctrl** [comment]
It looks like a display issue. If you cancel, then edit again, it shows a blank field. [Screencast](http://cl.ly/0Z3u3F3W2r2S).

Note, if you save the customer with the blank field, it doesn't disconnect the user. So it just looks like a display thing.

**Comment by pippinsplugins** [comment]
Ah, nice catch.
