### ISSUE TITLE
Why first price_id is "1" and not "0"?

### ISSUE THREAD

**Issue by KingYes** [easydigitaldownloads/Easy-Digital-Downloads#3239]
Hi @pippinsplugins !

I see from the last updates of EDD, you change the first `price_id` to `1`. I have a lot's of code base of `0` price id.

Can you just add some filter to setup this by my theme (for fallback)?

The code you write are there: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/admin/downloads/metabox.php#L443

Thanks

**Comment by pippinsplugins** [comment]
The price ID of `0` will still work fine. We only changed new products to start at 1 due to #1066

**Comment by KingYes** [comment]
But I need for new products to start at `0`. How I can fix this?

**Comment by pippinsplugins** [comment]
That's not supported any more, sorry. Do you have some custom code that is
interacting with the prices?

**Comment by KingYes** [comment]
Yes ! For example I added my custom auto discount for some price_id, and it's not work for me anymore. What I do for now, it's change from the PhpMyAdmin, but it's not good.

What you think I need to do?

**Comment by pippinsplugins** [comment]
Can you show me an example of how you did it?

**Comment by KingYes** [comment]
```
class MyClass {
	// .. codes ..
	public function apply_discount( $download_id, $options ) {
		$fee_id = 'my-custom-id';
		$is_lower_price = edd_has_variable_prices( $download_id ) && isset( $options['price_id'] ) && '0' === $options['price_id'];

		if ( ! $is_lower_price ) {
			EDD()->fees->remove_fee( $fee_id );
		} else {
			EDD()->fees->add_fee(
				array(
					'amount' => - 10,
					'label'  => __( 'My Label', 'textdomain' ),
					'id'     => $fee_id,
				)
			);
		}
	}
	
	public function __construct() {
		add_action( 'edd_post_add_to_cart', array( &$this, 'apply_discount' ), 10, 2 );
	}
	// .. codes ..
}
```

It's just for example, but I have more things for this.

**Comment by pippinsplugins** [comment]
Are you trying to add a special fee to a particular price ID?

**Comment by KingYes** [comment]
Yes, I did.

**Comment by pippinsplugins** [comment]
I'd recommend updating your products to use the new price IDs if possible.

**Comment by KingYes** [comment]
But I have a lots payments with your Software Licenses (EDD_SL). And how I can make sure all will be work perfect (Limit uses and more stuff)?

**Comment by pippinsplugins** [comment]
You'll need to do it on a per-product basis. It has only been changed for new products.

**Comment by KingYes** [comment]
But what I can to do with your EDD_SL plugin?

**Comment by pippinsplugins** [comment]
You need to check the `$download_id` parameter and see if it is one that has 0 or 1 for the starting ID.
