### ISSUE TITLE
Admin-ajax blocked message - hhvm + forge + laravel + SSL 

### ISSUE THREAD

**Issue by bearded-avenger** [easydigitaldownloads/Easy-Digital-Downloads#3241]
Getting this notice on the backend that says AJAX is blocked. 

AJAX isn't blocked, and works. edd_test_ajax_work() is failing. Is this due to SSL in the backend perhaps?

Just a heads up!

**Comment by pippinsplugins** [comment]
We have seen some false positives with the `edd_test_ajax_works()` function. Not really sure why.

Do you have HTTPS on the backend and not the frontend?

**Comment by bearded-avenger** [comment]
It's full SSL front and back. I think it might be the sslverify arg. https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/65163c94a5fac0128efe6e21cbb8e5dbab5eb2d3/includes/ajax-functions.php#L41

I think this changed as of 3.6 or 3.7 and not needing it anymore, but I realize EDD has to support a wider audience.

**Comment by adampickering** [comment]
+1 :+1:  Having the same issue with "Your site appears to be blocking the WordPress ajax interface." when upgrading from 2.2.8 to 2.3.2 I see a commit https://github.com/easydigitaldownloads/Easy-Digital-Downloads/pull/3266 not sure if it's related.

Our site is using SSL and is NGINX + HHVM

**Comment by pippinsplugins** [comment]
Would either of you have a site you could send me login credentials for?

**Comment by pippinsplugins** [comment]
@adampickering Thanks for the credentials via Skype. I'll look asap.

**Comment by pippinsplugins** [comment]
Punting to 2.3.5 since I can't get into a site and test this yet ( @adampickering  see Skype)

**Comment by bearded-avenger** [comment]
I can get you login Pippin. I think this *might* be related to a tweet I just sent EDD.

https://twitter.com/eddwp/status/580148963325702144

**Comment by pippinsplugins** [comment]
@bearded-avenger Is this fixed now with your login redirect fix?

**Comment by bearded-avenger** [comment]
Yeah I don't have any more issues, although I will say that the function is still returning a false positive 
http://cl.ly/image/353m1h020W02

**Comment by pippinsplugins** [comment]
Mind if I log in and take a look?

**Comment by bearded-avenger** [comment]
Yeah man go right ahead.

**Comment by bearded-avenger** [comment]
I will say that we had to send in a bug report to Laravel because the default php session path was off. So it could very well be something related to Forge's default image.

**Comment by pippinsplugins** [comment]
@bearded-avenger Actually looks like it was reporting properly. Ajax was disabled in Downloads > Settings > Misc.

Once I turned it back on, System Info reported it properly: https://cloudup.com/chisGUzWbNG

I tested checkout after turning it on and everything appears to be running properly.

I was never shown the notice.

**Comment by bearded-avenger** [comment]
:( This week has just been poopy. Sorry to waste your time on that man.

**Comment by pippinsplugins** [comment]
No worries at all! Adam was having a similar issue so there may still be a
bug here.

**Comment by adampickering** [comment]
Let me know if you need anything :)

**Comment by pippinsplugins** [comment]
@adampickering I left you a message on Skype.

**Comment by adampickering** [comment]
No longer an issue now that i've moved to Pagely VPS.

Go ahead and close.

**Comment by pippinsplugins** [comment]
OK we will go ahead and close then reopen if necessary.
