### ISSUE TITLE
Payment History - search by discount code

### ISSUE THREAD

**Issue by mgibbs189** [easydigitaldownloads/Easy-Digital-Downloads#3243]
Here's the idea:

![search by discount code](http://i.imgur.com/1rzTEMU.png)

It'd be great to be able to find payments having a specific discount code.

I think it'd also be very useful on the Discount Codes page, since the numbers in the **Uses** column could link directly to a filtered list as well.

Thoughts?

**Comment by chriscct7** [comment]
I like the idea but that's gonna be a super expensive meta query

**Comment by pippinsplugins** [comment]
No it won't. The discount code is logged in payment meta already.

**Comment by chriscct7** [comment]
That's exactly what I said o.O. It's an _expensive meta query_. To search orders for a discount, you have to query all orders then query the post meta for discount on each order.

**Comment by pippinsplugins** [comment]
It's expensive but not too bad. As long as we only run the query when doing a discount search, it should be fine.

**Comment by mgibbs189** [comment]
Feature-wise, do you guys think this would be a worthwhile addition? I noticed other tickets involving Discount Code reports, but nothing specific to filtering posts.

**Comment by chriscct7** [comment]
It depends on how many orders there are. If there's 100k orders looking for 19 instances of a coupon code is very costly. Feature wise, I love the idea

**Comment by mgibbs189** [comment]
Is it stored as a raw value somewhere, or is it only serialized within _edd_payment_meta?

If the latter, then it will be a lot more overhead (RAM) to load all the data and parse them with PHP.

**Comment by pippinsplugins** [comment]
I definitely think it's worthwhile. I've wanted to find customers that
redeemded a specific code before.

**Comment by cklosowski** [comment]
It's not too bad. We can do it one of two ways.

1) Use a WP_Query with meta query
2) Using $wpdb, directly search for `post_id` where `meta_key = ... AND meta_value = ...`, giving us a set of payment IDs to work with. Benifit here is it's two selects on Indexed columns, and even then, using $wpdb correctly is cached by core.

**Comment by chriscct7** [comment]
Meta Queries have performance issues when there's a lot of posts that qualify to have their meta searched. The latter is far more preferable

**Comment by pippinsplugins** [comment]
Working great!

**Comment by pippinsplugins** [comment]
We need to trim the search value.

`discount: special` fails.
`discount:special` works.
