### ISSUE TITLE
Welcome screen for 2.4

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#3246]
In order to give translators time to translate it, we should really try and get the welcome screen for 2.4 done at least a few weeks before the final release.

**Comment by cklosowski** [comment]
As discussed at LoopConf we should look into adding some of our top extensions to the getting started tab of this.

Thoughts @pippinsplugins @sumobi @SDavisMedia ? Could use a CSS overhaul to start with.

**Comment by pippinsplugins** [comment]
I think we should put them just before the "Need help" section: https://cloudup.com/cj2Y5240cht

**Comment by cklosowski** [comment]
👍

**Comment by SDavisMedia** [comment]
I like that placement.

**Comment by pippinsplugins** [comment]
@SDavisMedia @mindctrl @cklosowski could you guys give this a look (in release/2.4 branch)?

**Comment by chriscct7** [comment]
Syncronization > Synchronization 

" Payments allows your customers to easily pay with their debit or credit cards, at not extra cost to you"
that sentence is kinda misleading. People might interpret that as meaning no transactional cost

"their purchase pain free." 
The word pain when referring to a positive feature is a bad choice. "effortlessly" would be better

**Comment by mindctrl** [comment]
Some notes:

* `at not extra cost to you` should be `at no extra cost to you`
* "Customer > User Syncronization" heading. Should be *Synchronization*

**Comment by pippinsplugins** [comment]
Fixed.
