### ISSUE TITLE
Micro Data Applies to Pages

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/Easy-Digital-Downloads#3253]
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/c8b4ea9c528d8967cb1718a11883c8eb1cfd100f/includes/template-functions.php#L702

`is_singular()` should check `is_singular( 'download' )` -- if you are using the [downloads] shortcode on a page it will get wrapped since a page is singular. 

Like the title check:

https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/c8b4ea9c528d8967cb1718a11883c8eb1cfd100f/includes/template-functions.php#L677

This is adding extra/unexpected markup to the download grid and breaking things in Marketify.

**Comment by adampickering** [comment]
Ping @pippinsplugins

**Comment by pippinsplugins** [comment]
Is this the cause of the downloads grid issues?

**Comment by pippinsplugins** [comment]
@spencerfinnell Can you test it now from `master` and confirm it's resolved for you?

**Comment by mindctrl** [comment]
@pippinsplugins related to microdata. On search results that return no posts, and on 404 pages, there's a debug notice: `PHP Notice:  Trying to get property of non-object in /wp-content/plugins/easy-digital-downloads/includes/template-functions.php on line 677`. Can open a new issue if needed.

**Comment by pippinsplugins** [comment]
Let's fix it here.

**Comment by spencerfinnell** [comment]
@pippinsplugins Yep master is working for me. Yeah, it's the thing causing the downloads to appear in one column.

**Comment by pippinsplugins** [comment]
Great, thanks, we will get an update pushed out today.

**Comment by pippinsplugins** [comment]
@mindctrl Can you test again now?
