### ISSUE TITLE
Can't add new downloads to an existing payment if you've removed all downloads first

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/Easy-Digital-Downloads#3256]
Steps to reproduce:

* Edit existing payment and remove all downloads in the *Purchased Downloads* box.
* Add a new item to the payment and click *Add Download to Payment* button.

At this point, nothing happens. The download isn't added to the payment. No JS errors in the console.

[Reported here](https://easydigitaldownloads.com/support/topic/bug-if-all-payments-have-been-removed-from-an-order-cannot-add-new-payments/#post-463142)

**Comment by cklosowski** [comment]
We'll have to look into this...I believe that it wouldn't have worked in 2.2.x either. Do you mind testing @mindctrl if I don't get to it first

**Comment by mindctrl** [comment]
@cklosowski just tested 2.2.8. Doesn't work there either.

**Comment by pippinsplugins** [comment]
It fails in both because we use the .clone() method in jQuery. When there is no row, there is nothing to clone.

**Comment by sudar** [comment]
I faced the same issue in v2.3.1 as well.

**Comment by pippinsplugins** [comment]
We haven't fixed it yet.

**Comment by cklosowski** [comment]
@mindctrl ok this commit makes it so you cannot delete all items from a payment. You'll have to at least have one. So to do what they want, they can just add their new one and then delete the original item.

**Comment by pippinsplugins** [comment]
Looks good. I vote we close this out.

**Comment by cklosowski** [comment]
👍
