### ISSUE TITLE
time formatting removing zero

### ISSUE THREAD

**Issue by norcross** [easydigitaldownloads/Easy-Digital-Downloads#3257]
currently, the time field is removing the zero if present. see attached screenshot, the time should be 10:06
![screen shot 2015-03-12 at 9 12 11 pm](https://cloud.githubusercontent.com/assets/98561/6631593/076cd95e-c8ff-11e4-939d-13361228bdc0.png)

**Comment by cklosowski** [comment]
It's that darn `increment` and `type` attributes.

We should just get rid of those.

**Comment by norcross** [comment]
@cklosowski can you force two digits with those attributes?

**Comment by cklosowski** [comment]
Maybe, I think we can try adding the attribute `pattern="[0-9]*"` or a combination of attributes to make it happen.

**Comment by norcross** [comment]
cool deal. not a major problem (I think) but just something I wanted to report while I remembered it.

**Comment by cklosowski** [comment]
Bumping for 1.3.6

**Comment by cklosowski** [comment]
Looks like this is actually a bug in FireFox. I had assumed it was a generic HTML5 issue but appears someone else is noticing it's the way it's formatted for output by the browser.
https://bugzilla.mozilla.org/show_bug.cgi?id=1005603

Chrome is showing it with leading zeros, as well as Safari
Safari:
![image](https://cloud.githubusercontent.com/assets/1390124/6990487/d734ee78-da21-11e4-88c5-e740d02173e7.png)

Chrome:
![image](https://cloud.githubusercontent.com/assets/1390124/6990491/e9a9bd54-da21-11e4-80b9-876ff6b838d8.png)

**Comment by cklosowski** [comment]
@pippinsplugins how do we want to proceed with this? We'd have to remove the 'number' type from the input to make this function as we expect in Firefox

**Comment by pippinsplugins** [comment]
I'm fine with removing the number type.

**Comment by cklosowski** [comment]
the only downside with removing the number type, is it allows with creating a max of higher than 59

**Comment by pippinsplugins** [comment]
HIgher than 59? 59 what? Digits?

**Comment by norcross** [comment]
you could do a check on save and if it's higher than 59, save it as 59

**Comment by cklosowski** [comment]
The value, with the 'number' type you can set a max of '59' like we do, I think @norcross has the solution, we just always revert to 59 if they put a higher value, or '00' if they put a lower one

**Comment by cklosowski** [comment]
I went back and forth on this, I don't like removing the number and items like that as it makes editing on mobile terrible...but I think that's a SUPER edge case.

This restricts it to 2 characters, and if at any point the number is over/under the bounds of the 24H time format, it goes back to `00 or 23` for hours, and `00 or 59` for minutes.

**Comment by cklosowski** [comment]
@norcross @pippinsplugins Thoughts?

**Comment by pippinsplugins** [comment]
Works for me :+1:

**Comment by norcross** [comment]
+1
