### ISSUE TITLE
All my customers are removed after the new update

### ISSUE THREAD

**Issue by KingYes** [easydigitaldownloads/Easy-Digital-Downloads#3258]
Hi @pippinsplugins !

I just upgrade EDD in my production, and I can't manage my customers. In order (Payment) view, I see the select with the list of the customers, but it's empty. And I see "No customers found". And when I press the button in "View Customer Details" I this link: `http://domain.com/wp-admin/edit.php?post_type=download&page=edd-customers&view=overview&id=0`

What you think the problem?

**Comment by pippinsplugins** [comment]
@KingYes This likely means that the original upgrade routine that created the customer's table in version 2.1 was never run.

Do this:
1. Visit `http://trunk:8888/wp-admin/index.php/?page=edd-upgrades&edd-upgrade=upgrade_customers_db` to trigger the original upgrade routine. Wait for it to finish and then proceed to next steps.
2. Run `delete_option( 'edd_completed_upgrades' )`
3. Click on the link to begin the new customer upgrade routine and let it finish. Once it's done, everything should show up fine.

**Comment by KingYes** [comment]
Work's perfect. I just use the first step, and all work's good.

Thanks :)

**Comment by pippinsplugins** [comment]
Make sure you do the last one too to ensure stats are correct.
