### ISSUE TITLE
File Download Limit not observed in 2.3

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/Easy-Digital-Downloads#3259]
It looks like the File Download limit isn't working in 2.3.

* Create new download, set file download limit to 1.
* Purchase and download the item.
* Download item again. And again.

The limit worked in 2.2.8.

[Reported here](https://easydigitaldownloads.com/support/topic/file-download-limit-a-problem-after-upgrade-to-version-2-3/). Customer mentions link expiration doesn't work either. Will test that shortly.

**Comment by chriscct7** [comment]
It looks like function that checks to see if the download count is checked edd_is_file_at_download_limit is only called via a deprecated function for legacy downloads. @mindctrl can you test if legacy links respect the limit?

I think we forgot to implement the checks for expiration and download limits for the new download links

**Comment by mindctrl** [comment]
It looks like the old style links are limited as they should be.

**Comment by chriscct7** [comment]
Looks like both expiration and download count checks are missing for new urls. Wrote #3259 to fix

**Comment by pippinsplugins** [comment]
The expiration is checked in `edd_validate_url_token()`

**Comment by chriscct7** [comment]
File download count check implemented in https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/3260
