### ISSUE TITLE
Option to auto-update a plugin

### ISSUE THREAD

**Issue by jdevalk** [easydigitaldownloads/Easy-Digital-Downloads#3264]
Given that we [know it's possible to auto-update plugins by filtering a flag](https://make.wordpress.org/plugins/2015/03/14/plugin-automatic-security-updates/), it'd be cool if we could do that through EDD as well.

**Comment by chriscct7** [comment]
You mean auto update EDD? Or plugins sold via software licensing?

**Comment by jdevalk** [comment]
Plugins distributed through EDD, not necessarily sold...

**Comment by pippinsplugins** [comment]
Distributed through EDD would still be with Software Licensing regardless of price (if updates are involved).

I'd love to look into possibilities for this but we'll want to move it over to Software Licensing repo, unless you are thinking of something outside of SL. Are you?

**Comment by jdevalk** [comment]
Hmm guess you're right, SL is better :D

**Comment by chriscct7** [comment]
Moved it to that repo. Closing this one
