### ISSUE TITLE
Add hooks to the fees row in the checkout cart template

### ISSUE THREAD

**Issue by topher1kenobe** [easydigitaldownloads/Easy-Digital-Downloads#3265]
We need hooks right before and right after the TD rows for Gateway Fees.

**Comment by topher1kenobe** [comment]
Around these rows:
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/templates/checkout_cart.php#L56-L62

**Comment by pippinsplugins** [comment]
:+1:
