### ISSUE TITLE
Improve API call for customer count in EDD Stats API

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/Easy-Digital-Downloads#3284]
Right now, the stats API uses the following query to get the customer count:
```$count = $wpdb->get_col( "SELECT COUNT(DISTINCT meta_value) FROM $wpdb->postmeta WHERE meta_key = '_edd_payment_user_email'" );```
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/49bba4499763ed571e7a9fa336e24ddd902663ba/includes/class-edd-api.php#L1110

This is great in that it works for everyone even if they didn't run the EDD 2.3 updates.

On the downside, there's 2 significant issues with it:
- It's not cached
- Its a huge set of data (we ask MySQL to find all records, then limit it)

Instead, what we should do is for the 99.999% who did the update routine use the customer count from EDD_DB_Customers, which is both cached and far more efficient (we don't need to sort out duplicates)

So our code will be something like:

```php
		if ( version_compare( $edd_version, '2.3', '<' ) || ! edd_has_upgrade_completed( 'upgrade_customer_payments_association' ) ) {
			global $wpdb;
			$stats = array();
			$count = $wpdb->get_col( "SELECT COUNT(DISTINCT meta_value) FROM $wpdb->postmeta WHERE meta_key = '_edd_payment_user_email'" );
			$stats['customers']['total_customers'] = $count[0];
			return $stats;
		} else {
			$customers = new EDD_DB_Customers();
			$stats['customers']['total_customers'] =  $customers->count();
			return $stats;
		} 
```

PR incoming

**Comment by chriscct7** [comment]
#3285 solves this

**Comment by pippinsplugins** [comment]
Good catch, @chriscct7.

**Comment by cklosowski** [comment]
Looks good to me. Merged
