### ISSUE TITLE
Airplane mode (0.1.1) crash with EDD 2.3.3

### ISSUE THREAD

**Issue by juanfraa** [easydigitaldownloads/Easy-Digital-Downloads#3287]
Airplane mode: In version 0.0.1, the method enabled didn’t exist. There
was a method named check_status() which returned ‘on’ and ‘off’.

If somebody using Airplane Mode 0.0.1 updates to the latest version of
EDD, the WP dashboard breaks up.

**Comment by juanfraa** [comment]
Reference: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/pull/3288

**Comment by chriscct7** [comment]
Solved with #3288
