### ISSUE TITLE
Tax rates regions feature doesn't work

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/Easy-Digital-Downloads#3292]
When trying to type in the country dropdown, you get `Uncaught TypeError: Cannot read property 'replace' of undefined` in admin-scripts.min.js. Same thing when clicking Add Tax Rate button.

With debug enabled, it shows line 1055 in admin-scripts.js as the source of error. https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/assets/js/admin-scripts.js#L1055

Also, visual bug - http://cl.ly/image/0a0y46430m37

[Reported here](https://easydigitaldownloads.com/support/topic/unable-to-add-tax-rates/).

**Comment by pippinsplugins** [comment]
This is happening because Chosen somehow got enabled. It's not supposed to be.

**Comment by pippinsplugins** [comment]
Looks like this happened due to the select2 debacle https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blame/master/includes/admin/settings/register-settings.php#L1508
