### ISSUE TITLE
Unable to add a tax rate

### ISSUE THREAD

**Issue by bseddon** [easydigitaldownloads/Easy-Digital-Downloads#3293]
If confirmed, this issue is fairly serious.

Just had an issue reported against my VAT plugin because the user is unable to add tax rates when using 2.3.3.  I can confirm the problem but in trying to find out what changed in 2.3.3 so I can address the issue, I am able to see the same issue in a virgin copy of EDD 2.3.3 (see screenshot) and WP 4.1 that does not, and has never had, my VAT plugin activated.

It will be great if you are able to confirm this issue.  It  doesn't affect existing users but it seems any new users are unable to add country specific tax rates.  If you can suggest a fix I will be grateful so I'm able to apply it to the VAT plugin and help the user.  In the meantime I've recommended the user reverts to EDD 2.2.8 which does not exhibit this problem.

![edd-tax-problem](https://cloud.githubusercontent.com/assets/1221824/6758638/77d99b4a-cf31-11e4-9419-4471b1b404e3.png)

**Comment by liviucmg** [comment]
I can confirm the issue, and can beta-test if needed. Thanks!

**Comment by pippinsplugins** [comment]
Already fixed: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/3292

The update is going out today.
