### ISSUE TITLE
Add new general logging system

### ISSUE THREAD

**Issue by ghost1227** [easydigitaldownloads/easy-digital-downloads#3294]
Currently, we don't have a good method of logging general errors in EDD. Things like gateway and API errors are easily tracked, but what happens when you integrate with a third-party service and that service throws an error? Right now, there's not any easy way of notifying the site operator that there has been a problem. You could always display the error on the frontend (in the case of checkout errors), but usually that kind of error isn't relevant to the end user.

I propose the addition of a new logging system based on the current gateway log structure. The gateway logs are ideal due to the nature of the currently tracked data (identification of the transaction which caused the error, date, time, etc), and given it's already structured to handle multi-type data (strings or arrays being the most commonly returned data). The new system would also necessitate addition of a new function `edd_log_extension_error( <Extension Name>, $error );`.

**Comment by ghost1227** [comment]
@pippinsplugins has suggested using the function `edd_log_error` instead of `edd_log_extension_error`. Given we are currently using `edd_log_gateway_error`, and given this function would be exclusively used by extensions, I think inclusion of the extra word makes sense. Thoughts?

cc: @cklosowski

**Comment by chriscct7** [comment]
I like the idea of an edd_log_extension_error function (even more if we have an output of all the errors in a tab of the tools section, with a line for "has extension errors" on the system info)

**Comment by cklosowski** [comment]
I'd actually say we go a step further and `edd_log_error` can take a parameter of what type...`gateway` or `extension`. That can then make it much easier for us to control how logging happens.

**Comment by pippinsplugins** [comment]
I like the idea of adding a new parameter. The `edd_log_gateway_error()` function can just become a wrapper then.

**Comment by pippinsplugins** [comment]
I'm not sure it should be called `Extension Error`. That really doesn't mean much to an end user.

**Comment by ghost1227** [comment]
So tell me what you want me to do :grinning:

**Comment by pippinsplugins** [comment]
I think I'd just call it `edd_log_error`

**Comment by ghost1227** [comment]
@pippinsplugins how about `edd_log_error( $type, $title, $description, $data, $payment_id )` where `$type` is a string identifying 'gateway' or a specific plugin name?

**Comment by pippinsplugins** [comment]
Sure

**Comment by spencerfinnell** [comment]
Should `$payment_id` be its own argument? What if I want to log an error about a failed user creation, failed cart recovery, etc.

**Comment by cklosowski** [comment]
I agree with @spencerfinnell, the point of a general error logger is to not restrict to set data types. `$payment_id` would limit us to being payments only. that would be something stored in the `$data` as an item in an array or something simliar

**Comment by ghost1227** [comment]
@cklosowski That function was intended to represent a global logging function (replacing the current `edd_log_gateway_error()` function). The function itself would assume `$payment_id` is null unless `$type == 'gateway'`

**Comment by pippinsplugins** [comment]
@ghost1227 Could you update your PR to reflect comments / decisions above?

**Comment by ghost1227** [comment]
@pippinsplugins I'm not sure what was decided... @cklosowski and @spencerfinnell seem to disagree with the recommendation I originally made to you. Are we using that format or not?

**Comment by pippinsplugins** [comment]
It needs to be named with a generic name instead of `_extension_`

**Comment by pippinsplugins** [comment]
I'm going to punt this until we have a more formalized proposal.

**Comment by pippinsplugins** [comment]
Closing in favor of #4864
