### ISSUE TITLE
EDD 2.3.4 - Fatal error when using EDD Download Images

### ISSUE THREAD

**Issue by juanfraa** [easydigitaldownloads/Easy-Digital-Downloads#3296]
Once you update to 2.3.4, and having the EDD Download Images(1.1.3, the latest version) extension installed you get the following fatal error:

Fatal error: Call to undefined function edd_get_label_singular() in /thepath/wp-content/plugins/edd-download-images/edd-download-images.php on line 90

**Comment by pippinsplugins** [comment]
Thanks for the headsup! We'll get the extension updated to ensure that doesn't happen again!

**Comment by juanfraa** [comment]
Actually, nevermind, the problem was that EDD became inactive after the update.. There must been some kind of problem during the update..

**Comment by pippinsplugins** [comment]
It was due to the extension not properly checking if EDD is active before
calling an EDD function. Andrew, the author of the extension, is working on
fixing it now.

**Comment by cklosowski** [comment]
@sumobi did this get fixed?
