### ISSUE TITLE
Have the default gateway always show first in the list on the checkout page

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/Easy-Digital-Downloads#3297]
If you have 3 gateways enabled, let's say PayPal, the manual gateway and the Stripe extension, and you set the default gateway to the Stripe extension, on the checkout page you get a UI oddity that the default item is the last like this:

![screenshot-from-2014-10-28-221046](https://cloud.githubusercontent.com/assets/1324637/6765830/3e52ac00-cfc6-11e4-95fd-6f9752813848.png)

We should change it so that the default gateway is always the first item in the list like this:

![screenshot-from-2014-10-28-221548](https://cloud.githubusercontent.com/assets/1324637/6765828/37bd46fc-cfc6-11e4-8967-f0efe574ceb3.png)

**Comment by sdavis2702** [comment]
I think that's a great enhancement. Makes perfect sense.

**Comment by cklosowski** [comment]
:+1:

**Comment by cklosowski** [comment]
Actually I have a better way to do this, which will allow getting the list of enabled gateways sorted in a few different ways.

**Comment by cklosowski** [comment]
This allows it to be reusable and testable.

**Comment by pippinsplugins** [comment]
Looks good @cklosowski
