### ISSUE TITLE
Allow hiding of empty cart widget. Show on add to cart.

### ISSUE THREAD

**Issue by danieliser** [easydigitaldownloads/easy-digital-downloads#3305]
The following filter makes this quite easy to do.

```
add_filter( 'dynamic_sidebar_params', 'hide_empty_cart_widgets' );

function hide_empty_cart_widgets( $params ) {   
    if( strpos( $params[0]['widget_id'], 'edd_cart_widget' ) !== false && ! edd_get_cart_contents() ) {
        $class = 'class="edd-cart-empty ';
        $params[0]['before_widget'] = str_replace( 'class="', $class, $params[0]['before_widget'] );
    }
    return $params;
}
```

Using it now for a new theme. Then in the EDD add to cart js we simply remove that class from any widgets.

This can be hidden globally or users can choose to over ride it per sidebar using CSS.

**Comment by danieliser** [comment]
Adding this to the AJAX success function seems to do the trick as far as JS goes.

	if ($('.widget.edd-cart-empty').length) {
		$('.widget.edd-cart-empty, .widget .edd-cart-empty').removeClass('edd-cart-empty');
	}

**Comment by danieliser** [comment]
If you don't see a place for this in core, I believe I could quite easily make it into a feature plugin for w.org

**Comment by pippinsplugins** [comment]
Hey @danieliser, I'm not sure if this should go in core or not but I'm certainly up for considering it. Let's get feedback from the others to see what they think.

**Comment by pippinsplugins** [comment]
@cklosowski @chriscct7 @ghost1227 @sumobi @sdavis2702 @mindctrl Any thoughts here?

**Comment by danieliser** [comment]
@pippinsplugins No problem, I have it working quite well in my new theme. Can turn it into a free plugin if thats the consensus.

**Comment by cklosowski** [comment]
@pippinsplugins @danieliser Could we have it a widget option? Just a simple checkbox that says `Hide if empty`

This way it's in core, can be useful, but we'll default it to unchecked.

**Comment by pippinsplugins** [comment]
I like the idea of it being a widget option. That way we don't change existing behavior for current usrs.

**Comment by danieliser** [comment]
@pippinsplugins @cklosowski Ok let me see what I can do. The only thing is that I'm not sure when the filter im using is run. If it runs before the widget render function is called, how can we ensure that its enabled properly from inside the widget? Open to suggestions on that.

**Comment by danieliser** [comment]
The filter in question 'dynamic_sidebar_params' runs for the wrapper itself which may be before the render function is called. So will have to find the appropriate place to call it.

**Comment by turtlepod** [comment]
Why not just add body class, something like "edd-cart-empty" and change/remove it when item added to cart?
This will make it easier to style with display none/even other design implementation.

I think it's a good idea to add body class even if you have hide if empty cart widget option.

**Comment by mindctrl** [comment]
No need for a body class. This should be as easy as adding an option to the widget and returning early in the widget method by checking `edd_get_cart_contents()`.

**Comment by mindctrl** [comment]
Oh I see what you were wanting. You'd need a page reload doing it the way I said if you want it to pop in when a new item added. No bueno.

**Comment by cklosowski** [comment]
While a class would work. This should still be a widget option. That way the feature can be turned on and off.

**Comment by danieliser** [comment]
Which leads me back to my initial issue. The correct filter to hide the widget by default runs before access to check the widget option is available. Open to suggestions though. I considered simply adding a new wrapper to the existing widget content, but this wouldn't hide the widget, just its content, meaning if the current theme styled the widget container then it would simply be an empty box there. We need to hide the entire thing for this to work effectively with all themes.

I'm sure there is a solution, I just haven't come up with it yet.

**Comment by danieliser** [comment]
What if the option wasn't added to the widget but to the EDD Global options? Would be a sitewide option rather than a per widget instance option though.

**Comment by danieliser** [comment]
Alternatively this could be done with JS, by hiding the widget after the page loads rather than during rendering.

**Comment by cklosowski** [comment]
@danieliser Personally it needs two things...and this is how I see it:
1) Each widget instance should allow hiding an empty cart widget
2) There should be JS that is condintionally loaded/executed, that when the cart is empty, and the instance of that widget it configured to hide itself when empty, is then hidden.

This isn't too difficult and can be done by adding an option to the widget configuration, and then when that widget configuration is checked, a specific class is added to the cart widget upon display, that can the interact with the JS part of this equation.

So yes, it needs a per instance option (not global) and yes, it needs to work without a page refresh.

**Comment by danieliser** [comment]
@cklosowski Can do 1 easily. For 2 do you recommend adding the JS ( no more than 2-3 lines needed ) or would you prefer it be added via a script tag in the footer. Seems the conditional check and including it in the existing JS file that will be loaded already seems to be the most efficient way to go. Won't add enough in size to even be concerned about making it a seperate file that only loads if needed.

**Comment by cklosowski** [comment]
@danieliser Yeah I think that's probably best. Seems like we're on the right track.

**Comment by cklosowski** [comment]
@SDavisMedia would love your eyes on this one. I did it from a purely markup perspective :), just uses CSS to show/hide, and some JS to add/remove classes. and a `div` as a wrapper for the content.

**Comment by pippinsplugins** [comment]
This works really well for me.

**Comment by sunnyratilal** [comment]
All working as expected here. Nice work @cklosowski 👍

**Comment by SDavisMedia** [comment]
Sorry for the delay, guys.

This needs to remove the entire widget if possible, as in the element with the `widget_edd_cart_widget` class. Reason being, many themes style the actual widget wrap itself, along with all the junk in it. That way all widgets (not just EDD) have consistent styles. Here's what happens in Vendd and Marketify:

<img width="863" alt="screenshot 2017-01-13 22 50 15" src="https://cloud.githubusercontent.com/assets/2359131/21953061/b8112210-d9e2-11e6-9bfd-89e2de628d3f.png">

<img width="811" alt="screenshot 2017-01-13 22 51 00" src="https://cloud.githubusercontent.com/assets/2359131/21953067/c64e5f5a-d9e2-11e6-9a6d-8309cb0a72b0.png">

**Comment by sunnyratilal** [comment]
@SDavisMedia 

The only way to do that is by the following snippet:
```php
function edd_cart_widget_class( $params ) {
	if ( strpos( $params[0]['widget_id'], 'edd_cart_widget' ) !== false ) {
		$cart_quantity = edd_get_cart_quantity();
		$class = empty( $cart_quantity ) ? 'cart-empty' : 'cart-not-empty';
		$params[0]['before_widget'] = preg_replace( '/class="(.*?)"/', 'class="$1 edd-hide-on-empty ' . $class . '"', $params[0]['before_widget'] );
	}

	return $params;
}
add_filter( 'dynamic_sidebar_params', 'edd_cart_widget_class' );
```

This alter the widget wrapper but there is no way to check if the `Hide if cart is empty` option was checked because we don't have access to the widget instance from `dynamic_sidebar_params`. So, correct me if I'm wrong, but I don't see a better solution other than what @cklosowski has proposed.

**Comment by pippinsplugins** [comment]
@sunnyratilal We could add another class to the widget if it should be hidden when empty and then check it for it in the same way you're checking for the class above.

**Comment by cklosowski** [comment]
I think I know a way around this. Give me a few minutes to work through it.

**Comment by sunnyratilal** [comment]
Tested and working.

**Comment by sunnyratilal** [comment]
Will merge once unit tests pass

**Comment by pippinsplugins** [comment]
This works great now!

**Comment by sunnyratilal** [comment]
Merged into `release/2.7`.

Nice work @cklosowski! 👍

**Comment by SDavisMedia** [comment]
Very nice. Working perfectly for me now. :tada:

**Comment by danieliser** [comment]
Lol, looks like we ended up back where we started haha. Looking at the original issue this was the same solution we ended going away from for various reasons. In any case if you guys are good with it I am too. Glad to see its making it into core.

One question I didn't see an immediate answer to. Is this all optional? IE is there a setting to enable/disable this. If not may want to consider it before pushing. I would also disable it by default so as to not change the expected behavior for existing sites.

Nice work guys. :100:

**Comment by pippinsplugins** [comment]
@danieliser heh.

**Comment by cklosowski** [comment]
It's close to the original one yes. But we had to add in it being on a per
widget instance basis so it's a check box on the widget controller. So the
original idea needed some work to support getting the instance options and
the support for it without inline JS

**Comment by mindctrl** [comment]
It looks like you can remove the widget entirely, if wanted, by hooking into `widget_display_callback`.

```
add_filter( 'widget_display_callback', function( $instance, $widget ) {
	if ( 'edd_cart_widget' === $widget->id_base && true === $instance['hide_on_empty'] ) {
		return false;
	}
	return $instance;
}, 10, 2 );
```

**Comment by cklosowski** [comment]
Yes but this will remove all the markup so when items are added it won't
show.
