### ISSUE TITLE
Numeric Keyboard

### ISSUE THREAD

**Issue by BurlesonBrad** [easydigitaldownloads/Easy-Digital-Downloads#3308]
After [reading this article from Lema](http://chrislema.com/wordpress-mobile-ecommerce/) and a few more from Zurb, I decide I wanted to make the correct keyboards come up on tablets and cell phones.  Bring up a checkout page on your table or phone. Now tap in the email field.  This code <input type="email"> brings up a specific keyboard which is figure 'B'.  Now go to the name field.  This code <input type="text"> brings up a different keyboard which is figure 'A'. Now check out the bottom two keyboards.  (note: all phones have their own style, but the same principles remain) Look at figures 'C' and 'D'.  'C' is the keyboard that comes up regardless of what *hairbrain* option of code I use.  Figure 'D' is the actual correct keyboard that should come up when a user taps in the CC or CVC field.
![keyboard-inputs](https://cloud.githubusercontent.com/assets/6208757/6855629/f80a6606-d3c7-11e4-8024-9f80d38ceed9.png)

The bottom right (D) is the correct keyboard that I had to force open, but needs to come up _*by default*_ for both the Credit Card & CVC field.
Here's what I've tried:
1. `<input type="number">`
2. `<input type="number" pattern="[0-9]*">`
3. `<input type="text" pattern="[0-9]*">`
4. `<input type="number" pattern="[0-9]* pick_20_more_variations">`
5. Hell, I even went out on a limb and did `<input type="tel">`

### Alas! The damn thing will not change!

So... How in the dickens do 'other folks' manage to pop up the numeric keypad to enter digits?

**Comment by BurlesonBrad** [comment]
I've also tried [this article by Brad Frost](http://bradfrost.com/blog/mobile/better-numerical-inputs-for-mobile-forms/) to no avail.  Then there's [this *humorous* article as well](http://seesparkbox.com/foundry/cracking_the_code_for_a_numeric_keyboard) where this dude tried everything under the sun ~ a bit like I'm _still_ doing. :+1: 

...I tried messing around with this as well, and I got nowhere
input type="number" inputmode=”numeric” pattern="[0-9]*"

Look at what Amazon Mobile brings up.  This is *EXACTLY* how it's supposed to be done!
![amazon-ck-out-keyboards]

![amazon-ck-out-keyboards](https://cloud.githubusercontent.com/assets/6208757/6859130/9833c9cc-d3e3-11e4-8635-64cc66cfb418.png)

## If Amazon.com can make it come up, then we can too!

...uh..ok, now...how?

**Comment by chriscct7** [comment]
Hi Brad,
This type of query should be handled on the support forum at easydigitaldownloads.com/support as we only use issues for core dev things to fix and the like, not support. If you could, open a ticket there please and we'll see what we can do with helping you out on this.

Thanks!
