### ISSUE TITLE
Add mobile phone input field types to checkout fields

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#3309]
As pointed out on #3308, the fields for things like credit card number and etc should use the numeric displays on mobile devices, and the email display for the email fields. We should also verify all fields comply with Dashlane and other common password apps's autofilling for credit cards.

We should also look at accessibility labels for the checkout form and using the new a11y javascript functions in 4.2 for the checkout field js

**Comment by sdavis2702** [comment]
And whatever's done in EDD should also be done in extensions that use their own forms. Stripe, for example, adds its own CC form.

**Comment by chriscct7** [comment]
Agreed

**Comment by pippinsplugins** [comment]
Punting to 2.6.

**Comment by cklosowski** [comment]
For the inputs like Credit Card Number and CVC we can use `type="tel"` with specific patterns for both.
CC: `pattern="[0-9]{13,16}"`
CVC: `pattern="[0-9]{3,4}"`

Buy using those it means on mobile we'll see this:
![img_1963](https://cloud.githubusercontent.com/assets/1390124/15301243/a2f6af70-1b61-11e6-8931-b5a225a3c8d7.jpg)

This is on our default CC form supplied with EDD. We'll need to migrate this to stripe when we get to that point.

**Comment by pippinsplugins** [comment]
Any concerns with Internet Explore and changing the input type?

**Comment by topher1kenobe** [comment]
I just tested with IE11 on Win7 and it worked flawlessly.  IE has a weird little UI thing where it shows an X in the field when the field is focused, but that's unrelated to this ticket.
![selection_430](https://cloud.githubusercontent.com/assets/341412/15368889/1e3d9fde-1cfe-11e6-8623-90e1f7ba1220.png)

**Comment by pippinsplugins** [comment]
Does anyone happen to have a Windows phone to test with?

**Comment by mintplugins** [comment]
Tested on IE 11.306 - (Desktop, not Windows Phone) and everything works properly.

**Comment by topher1kenobe** [comment]
I have a friend with a windows phone. I'm going to email him steps to test and see what we get.

**Comment by pippinsplugins** [comment]
@topher1kenobe any luck with your friend?

**Comment by pippinsplugins** [comment]
Merging for beta 1 tomorrow.

**Comment by topher1kenobe** [comment]
Windows Phone shots look awesome. Sale went through flawlessly.

![wp-screen-08](https://cloud.githubusercontent.com/assets/341412/15673255/69b49bf2-2703-11e6-9db2-f52d21cf417b.jpg)
![wp-screen-07](https://cloud.githubusercontent.com/assets/341412/15673257/6eec254a-2703-11e6-88a7-ea80f9f30f01.jpg)
![wp-screen-06](https://cloud.githubusercontent.com/assets/341412/15673261/755b76f6-2703-11e6-9181-03d49a60375d.jpg)
![wp-screen-05](https://cloud.githubusercontent.com/assets/341412/15673262/7684633a-2703-11e6-80a3-63b6c0c6c980.jpg)
![wp-screen-04](https://cloud.githubusercontent.com/assets/341412/15673263/7781f0a4-2703-11e6-98c9-16d888e32aeb.jpg)
![wp-screen-03](https://cloud.githubusercontent.com/assets/341412/15673265/785a73e8-2703-11e6-8f61-b50bf414bb1a.jpg)
![wp-screen-02](https://cloud.githubusercontent.com/assets/341412/15673269/793d01ea-2703-11e6-9d93-3f2adc5a67d6.jpg)
![wp-screen-01](https://cloud.githubusercontent.com/assets/341412/15673270/7a5d12a4-2703-11e6-9285-75539d63708b.jpg)

**Comment by pippinsplugins** [comment]
Great1

**Comment by chriscct7** [comment]
What's up with that CC icon location?

On Tue, May 31, 2016 at 9:05 AM, Pippin Williamson <notifications@github.com

**Comment by pippinsplugins** [comment]
CSS bug. Different issue we can address separately.
