### ISSUE TITLE
Prevent New Download Drafts by introducing a `create` method.

### ISSUE THREAD

**Issue by dancameron** [easydigitaldownloads/Easy-Digital-Downloads#3312]
Here's the backtrace on one of the incidents...

```
[28-Mar-2015 00:48:02 UTC] backtrace: Array
(
    [0] => EDD_Download->__construct
    [1] => edd_is_bundled_product
    [2] => EDD_Software_Licensing->activate_license
    [3] => EDD_Software_Licensing->remote_license_activation
    [4] => call_user_func_array
    [5] => do_action('edd_activate_license')
    [6] => edd_get_actions
    [7] => call_user_func_array
    [8] => do_action('init')
    [9] => require_once('wp-settings.php')
    [10] => require_once('wp-config.php')
    [11] => require_once('wp-load.php')
    [12] => require('wp-blog-header.php')
)
```

Looks like edd_is_bundled_product doesn't sanity check the id and a new download is created just by passing any string/int.

https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/99f7940daa4d3e009e801bd1f20d7c4b9b3c7259/includes/download-functions.php#L487

I'll create a PR.

**Comment by dancameron** [comment]
Added Pull Request 3313 to address this specific issue, however...

I think this is a rather big problems:

1. There are  a lot of functions that could cause a drafted download, it's why [this issue](https://easydigitaldownloads.com/support/topic/new-drafts-of-new-download-product-created-automatically/page/2/) has been around for so long. 
2. The solution I used for that function isn't idea because you don't want to force a query on every function call. Although it's very likely the $post object is cached at that point.

I'll look over the __construct and see if I can think of a better solution since that's where the focus should be.

**Comment by cklosowski** [comment]
I think we should use this issue as the basis for making a `create` method within the `EDD_Download` class, and then remove the `false` to create a draft part. This leaves us with an EXPLICIT call to create a new download, instead of automatically doing it when the conditions are right.

**Comment by cklosowski** [comment]
@pippinsplugins ^^^

**Comment by pippinsplugins** [comment]
I agree @cklosowski

**Comment by pippinsplugins** [comment]
@dancameron I like the start you have in #3318.

One thing we really need to support is adding prices, files, etc. We could do this either by allowing additional arguments to be passed to the `create()` method, or we could do it similar to how `EDD_Customer` works and introduce methods for `set_price()`, `set_files()`, etc.

I'm in favor of the second option.

If we add additional methods for setting the meta data, we'll do that as a separate issue. If we allow meta data to be passed into the `create()` method, we'll need to do it here.

Thoughts @dancameron @cklosowski ?

**Comment by dancameron** [comment]
I personally like being able to create a download/whatever from a single method. It's what I'm going on SI ([example](https://github.com/SproutApps/sprout-invoices/blob/master/models/Client.php#L89)). I also have `set_*` methods for each data/meta-store.

Maybe this is a third option because you'll want to create the `set_*` methods anyway, I'd just add the extend the creation of a download to be able to set everything up in one go, instead of having to iterate through each `$download->set_*` necessary.

**Comment by pippinsplugins** [comment]
I like the idea of having separate methods and also supporting them in the `create()` method. :+1:

**Comment by cklosowski** [comment]
Could we do something like we did with `EDD_Customer` [https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/class-edd-customer.php#L130](here)

We use it in our `create()` method as well as the `__construct()` to make sure we're getting the same expected results wether we're creating or instantiating an existing customer:
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/class-edd-customer.php#L219

**Comment by pippinsplugins** [comment]
:+1:

@cklosowski Do you want to head this one up on Monday (or anytime before)?

**Comment by cklosowski** [comment]
@pippinsplugins yep, can do, Monday sounds good.

**Comment by pippinsplugins** [comment]
Thanks!

**Comment by cklosowski** [comment]
@pippinsplugins can you test out this branch, see what you think of this methodology?

**Comment by pippinsplugins** [comment]
The `@since` tag should be `2.3.6` for the `setup_download()` method.

**Comment by pippinsplugins** [comment]
The `$data` parameter should be allowed to be left empty in order to create a standard draft.

**Comment by pippinsplugins** [comment]
Everything else looks great!

**Comment by cklosowski** [comment]
@pippinsplugins fixed those two, going to submit it as a PR

**Comment by pippinsplugins** [comment]
Done and done!
