### ISSUE TITLE
edd_get_purchase_link sets data-price attribute to 0 if used with price=false option

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/Easy-Digital-Downloads#3319]
If you use `edd_get_purchase_link` with `price=false` because you want to display the price outside the button, the `data-price` attribute gets set to 0 and you can't use features like Stripe Checkout. Looking at the code I don't see any reason why we can't set the data-price to the actual price at all times. Thoughts?

**Comment by cklosowski** [comment]
@mindctrl can you take a look and see if that fixes your issues?

**Comment by cklosowski** [comment]
Oh, not good yet, give me a few. Causing issues with variable pricing.

**Comment by cklosowski** [comment]
I think this should work now @mindctrl. I'm going to write a couple unit tests though to make sure this is working as expected, if possible.

**Comment by mindctrl** [comment]
@cklosowski looks good for most cases, though if you enable multi-option purchase mode on an item and select multiple options, Stripe Checkout only pulls in one of the prices. That might be a Stripe extension issue, but wanted to mention it just in case.

**Comment by cklosowski** [comment]
Yeah, that's true. did you try it out on master too to see if it's doing the same there or I introduced that with this iddue?

**Comment by cklosowski** [comment]
Ok thanks @mindctrl

**Comment by pippinsplugins** [comment]
@cklosowski Could you do a quick test with this and Stripe Checkout before we merge it?

**Comment by cklosowski** [comment]
@pippinsplugins looks good to me, if @mindctrl is good i'll merge

**Comment by pippinsplugins** [comment]
:+1:

**Comment by cklosowski** [comment]
Merging
