### ISSUE TITLE
Additional Filters in Templates

### ISSUE THREAD

**Issue by EngageWP** [easydigitaldownloads/Easy-Digital-Downloads#3320]
Hey guys. Throughout the templates, there are quite a few headers, messages, etc. that are hard coded in without any filters to change the text. This means users have to override the template (overkill) or use jQuery (no) to change the text. I think adding filters for these things would be great. I'd be happy to submit them if you let me know the proper way you like to receive pull requests (I'm new at PR's so bear with me).

**Comment by michaelbeil** [comment]
Hey @EngageWP, you can read all about contributing here: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/CONTRIBUTING.md

## Making Changes

* Fork the repository on GitHub
* Make the changes to your forked repository
  * Ensure you stick to the [WordPress Coding Standards](https://codex.wordpress.org/WordPress_Coding_Standards)
* When committing, reference your issue (if present) and include a note about the fix
* If possible, and if applicable, please also add/update unit tests for your changes
* Push the changes to your fork and submit a pull request to the 'master' branch of the EDD repository

**Comment by shazahm1** [comment]
Just thinking outloud... so ignore me if you want...

You don't really need to add edd specific filters to accomplish. They can be easily overridden with a gettext filter or with the Say What? plugin (which uses the gettext filter). That said, I guess an edd specific filter could be more performant.

**Comment by EngageWP** [comment]
Sure, they aren't entirely necessary but I personally like having a lot of hooks for things like this. I think they contribute to the overall "framework" aspect.

**Comment by EngageWP** [comment]
I submitted a PR to add a variety of new filters so I guess this issue can be closed.

**Comment by pippinsplugins** [comment]
@EngageWP Reopening this since we always leave issues open until the PR is merged for it.

**Comment by pippinsplugins** [comment]
Thanks for the suggestion @EngageWP and thank you for the PR!

I'm inclined to agree with @shazahm1 about using `gettext`.

Filters do make it easier for some text strings, but introducing filters for every single text string in the plugin is overkill. If we introduce these, we need to introduce them every where else too.

Another way to translate them is to use a translation file.

I'm recommending closing as `wontfix` but will wait for @cklosowski to weigh in.

**Comment by EngageWP** [comment]
Hey @pippinsplugins. Sorry for the premature close on this.

It's understandable that adding that many filters would be overkill. My only question about `gettext` would be that it would effect every instance of a string with a specific domain, no? My thinking with the filters is that they target one specific string only and are easier to use than `gettext`, especially for people who aren't comfortable with PHP beyond "copy and paste" because they won't be responsible for determining the plugin domain and writing out extra conditionals.

The PR was more or less to throw the idea out there. I appreciate the feedback on it.

**Comment by pippinsplugins** [comment]
You can do it on a per-text-domain and per-text-string basis.

**Comment by pippinsplugins** [comment]
@cklosowski Could you read up above and let me know your thoughts.

**Comment by mindctrl** [comment]
Chiming in as someone who fields support requests to change these things. It's easier to explain to non-technical folks how to copy a template and edit it than it is to tell them how to create a plugin with a function to filter the text. We have these steps documented already, so from that perspective we would rarely tell the customers to use the filter instead. It's just easier to point them to the documentation. We also point customers to Say What, as someone mentioned previously, which is even easier.

**Comment by EngageWP** [comment]
Hi, @mindctrl. I'd disagree with it being easier for a non-technical user (or even a developer) to change the template. Not necessarily. With a bit of explanation, even non-technical users should be able to add a simple plugin. I also believe all types of users have an easier time with copying a simple filter to a plugin or a functions.php file than they would navigating the EDD files to copy and modify an entire template. It's more work, more technical and more to get lost in, at least in my opinion. Additionally, copying a template would require a bit of additional work when switching themes, something non-technical users may not be aware of. This process just seems like overkill for changing a few strings. For example, WooCommerce includes a number of filters to modify headlines and such, avoiding the need to override templates for basic changes.

These filters would replace the need for using gettext(), which not everyone may be aware of either. Ultimately, @pippinsplugins and @cklosowski will make the right call; I just wanted to propose the idea.

**Comment by pippinsplugins** [comment]
For fun, I'd like to see a bench mark on this comparing the use of `gettext` for changing these strings and using filters. If gettext is significantly slower, we can add filters. If it's the same or just minimally slower, we'll leave it as is.

**Comment by cklosowski** [comment]
I see both sides of this argument.

1) For this PR
@EngageWP is correct that this WOULD make it easier for people to change themes and not lose their information or have to recopy the file over to the new theme, etc. Now, the biggest question here is how bad do we think that impact is...and then how far do we take this. That's a whole different discussion I think.

2) Against the PR
@mindctrl and @pippinsplugins are correct that we do field a lot of questions in the support forums about how to change these strings, and as someone who has done support for this site before, asking someone to create a plugin is instantly a turnoff and they then go down the rabbit whole of either how to create a plugin file, or installing pluginception. Neither of which non-developers are comfortable with (at least for our userbase).

A large number of these users are comfortable with Child themeing already as it takes much less work (than plugin creation), or are using a child theme from a theme framework to begin with.  This leads me to stick with using the current method of making this a template decision, not filters.

The other thing I'd be concerned with here is the growing number of users who are using EDD with WPML and other multiple translation plugins. With a filter on this, it could cause a potential pain point with them, and we've already done a lot of work to repair our reputation with the translation community in the past few releases.

Those are my thoughts @pippinsplugins. Let's discuss this today if you want, get a final go/no-go.

**Comment by mindctrl** [comment]
@EngageWP we run into folks who white screen their sites trying to add plugins. I think that's less likely when editing an exact example in the template. But I do see the value in doing it in a plugin or another method, due to the theme switch thing. Hmm we also have a filter in `edd_get_theme_template_paths` for adding additional template locations. We have all kinds of ways to touch this thing.

If we add the filters here, we could add your examples in https://github.com/easydigitaldownloads/Easy-Digital-Downloads/pull/3322 to help shore up our documentation.

Out of curiosity I'd like to see those benchmark results Pippin mentioned.

**Comment by pippinsplugins** [comment]
I've just reviewed this all again and I'm still in favor of `wontfix`.

**Comment by mindctrl** [comment]
@pippinsplugins same here.
