### ISSUE TITLE
Total price in payment area

### ISSUE THREAD

**Issue by michaelbeil** [easydigitaldownloads/Easy-Digital-Downloads#3321]
When viewing the total price, the fifth number of the price cannot be seen when it is something like 139.64. All that is visible is 139.6. 

![screen shot 2015-03-31 at 11 15 51 am](https://cloud.githubusercontent.com/assets/4752949/6923510/d1c83bf2-d797-11e4-8c72-9657a5ea446e.png)

It'd be great if the number field was slightly wider.

**Comment by pippinsplugins** [comment]
Let's get that fixed!

**Comment by michaelbeil** [comment]
Great! Thanks @pippinsplugins.

**Comment by juanfraa** [comment]
@pippinsplugins A simple css would do the trick. Would you like to define a new css class for that input or use another one (say edd_price or another)?

**Comment by michaelbeil** [comment]
Either could work @juanfraa. Not sure what @pippinsplugins' thoughts are.

**Comment by cklosowski** [comment]
Yeah this is being caused by a core css style:
```
input.small-text {
	width: 50px;
	padding: 1px 6px;
}
```

**Comment by cklosowski** [comment]
I'll try and come up with a better solution

**Comment by cklosowski** [comment]
This looks like it should do it:
![image](https://cloud.githubusercontent.com/assets/1390124/7007956/47f662ae-dc43-11e4-880c-077dabdb7646.png)

**Comment by michaelbeil** [comment]
all good, other than the 'addming' commit message ;P.

[x] @cklosowski 
[x] @michaelbeil
[ ] @pippinsplugins

**Comment by cklosowski** [comment]
:P Damn commit messages. Always throwing extra letters in when I type.

**Comment by michaelbeil** [comment]
it's probably your keyboard. time for a new one? (hint: @pippinsplugins)

**Comment by michaelbeil** [comment]
:+1:
