### ISSUE TITLE
PayPal split costs for free items

### ISSUE THREAD

**Issue by elliott-stocks** [easydigitaldownloads/Easy-Digital-Downloads#3325]
If I have 4 products in my cart and enter a discount code which makes three of them free, PayPal will spilt the  cost between all the products. This makes it confusing, as it appears like you're paying a discounted price per item.

For example -

Product 1: £10
Product 2: £10
Product 3: £13
Product 4: £10

I have a flat rate discount code of £33, making the total cost £10. When I go to PayPal the £10 is spilt between the number of products.

![paypal-items](https://cloud.githubusercontent.com/assets/1441538/6953551/fb7f7fe8-d8c1-11e4-942a-79970ec03cc2.png)

Ideally it'd be nice if we could only show the products in PayPal which require a payment. In this case product 4.

**Comment by pippinsplugins** [comment]
Is your discount code specific to a particular product?

**Comment by elliott-stocks** [comment]
Nope, no requirements on the discount code.

Also noticed on the payment confirmation page it does this -

![edd-cart](https://cloud.githubusercontent.com/assets/1441538/6953812/d4e93142-d8c3-11e4-8cf3-c17c3a87f289.png)

**Comment by chriscct7** [comment]
This looks like expected behavior. It has to apply evenly to all products that it's applicable to, because otherwise extensions like commissions can't calculate the correct commissions earned on a product if its by % of product price

**Comment by pippinsplugins** [comment]
I think @chriscct7 is right here.

Unless the discount is specific to certain products, it gets evenly divided across the products in the purchase.
