### ISSUE TITLE
Variable file price assignments options get removed from dropdown when deleting a file row.

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/Easy-Digital-Downloads#3328]
Steps to reproduce:
* Add multiple variable price options
* Add multiple files in the File Downloads meta box and assign them to the price options.
* Delete one of the rows in the File Downloads meta box.

Note the options in the dropdown get affected. See this [screencast](http://cl.ly/0v3k0u3H3O0o). Watch the first row when I remove the last one.

Possibly related to/introduced here. https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/3082

**Comment by cklosowski** [comment]
@mindctrl I cannot replicate this on current master. When I delete the new file, the first remains as it was.

**Comment by cklosowski** [comment]
N/M I could, but it took me adding two new rows.

**Comment by cklosowski** [comment]
Should be good to test @mindctrl

**Comment by mindctrl** [comment]
@cklosowski still seeing a bug here. [Screencast](http://cl.ly/2y040X2j063U)

**Comment by cklosowski** [comment]
are you working off `.min` JS? or maybe cached JS? I can't replicate that anymore on branch `issue/3328`

**Comment by mindctrl** [comment]
@cklosowski I think my JS was cached, though I had disabled it. Shrug. It looks like it's working now.

**Comment by cklosowski** [comment]
Cool thanks for rechecking.

**Comment by mindctrl** [comment]
@cklosowski can we milestone this for 2.3.8 now?

**Comment by cklosowski** [comment]
@mindctrl Sorry totally missed that note for 2.3.8. I'll flag it 2.3.9, and if we don't have one, we'll go with 2.4. Either way it'll go in next release.
