### ISSUE TITLE
Reports inaccurate when not 'day_by_day'

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/Easy-Digital-Downloads#3334]
The reports that do not use `day_by_day` are calculating incorrectly for the months due to the fact that the `$end_date` is calculating the month wrong:

```
$date        = mktime( 0, 0, 0, $i, 1, $y );
$end_date    = mktime( 0, 0, 0, $i + 1, $num_of_days, $y );
```

For instance, if we use January we get the timestamps of:
`1388534400 - 01/01/2014 @ 12:00am (UTC)`
`1393804800 - 03/03/2014 @ 12:00am (UTC)`

This is causing the stats to be off on these report graphs. The `$end_date` needs to find the last date of the current month, at 11:59:59pm:
`$end_date    = mktime( 23, 59, 59, $i, $num_of_days, $y );`

**Comment by cklosowski** [comment]
Ready for your review @pippinsplugins

**Comment by pippinsplugins** [comment]
Ah! Good catch,
