### ISSUE TITLE
Better Coupon Endpoint

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#3338]
Once https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/3337 is done, we should look at improving the coupon endpoint, for v2.

Right now, the sales API tells you the coupons used on a sale, but not how much they impacted the total of the sale. This is making things like writing a report that shows you which discount codes are used on higher value purchases, or most often, or lead to better returns, etc pretty difficult (since you then have to call the api to get the rules for a discount code and then the extending program has to then manually write its own rules for calculating the discount codes for figuring out how much each code took off).

Like if I know code xxxx is used and code yyyy is used on a sale, I have to right now call the coupons endpoint for each to retrieve the coupon rules, and then I have to calculate how much each would affect the sale I'm looking at manually (using my own custom implemented logic).

That gets really expensive and unnecessarily complicated when there's alot of coupons. It'd be nice, since EDD knows this information, if it would tell you how much each coupon took off.

In v1, coupons are shown like this on the sales endpoint:
```
'coupons' => array(
     'coupon1',
     'coupon2'
);
```

In v2, we'd do:
```
'coupons' => array(
     'coupon1' => 8.3,
     'coupon2' => 1.2
);
```

**Comment by pippinsplugins** [comment]
Makes sense to me.

**Comment by chriscct7** [comment]
Dependent on #3337

**Comment by pippinsplugins** [comment]
API versioning is going into 2.4 but I'm going to propose that we wait to introduce this until 2.5 so that we can make other API changes at the same time. Better to have one new version instead of two or three in a short time.

Any objections?

**Comment by pippinsplugins** [comment]
We'll need to store the discount amounts for each discount code in payment meta data to make this possible.

**Comment by pippinsplugins** [comment]
Or we could just show the amount set on the discount code, opposed to the actual value of the discount on the cart.

**Comment by cklosowski** [comment]
Couple issues with the latter of those @pippinsplugins is that the discount could have been removed from the system or modified, so looking up it's discounted amount (from the discount post type) might not be possible or accurate.

I'm not sure that's a case to completely go with future payments having this data only though. I vote we use it, and just account for discount posts types that have been removed.

**Comment by pippinsplugins** [comment]
The approach taken in the PR won't work. See https://github.com/easydigitaldownloads/easy-digital-downloads/pull/4620#discussion_r64749463.

**Comment by pippinsplugins** [comment]
Merging into `release/2.6` for beta 1.
