### ISSUE TITLE
Add shortcode to publish metabox

### ISSUE THREAD

**Issue by sumobi** [easydigitaldownloads/Easy-Digital-Downloads#3339]
Here's a nice way of showing the shortcode (From GiveWP, see far right). We should consider doing this for EDD and possibly even go as far as removing the shortcode from the main downloads page. Would make it cleaner.
 
![screen shot 2015-04-09 at 3 25 40 pm](https://cloud.githubusercontent.com/assets/52581/7076118/c331a128-decc-11e4-8c85-76e12d858c94.png)

**Comment by sumobi** [comment]
Or do it like this at least which is much nicer IMO

![screen shot 2015-04-09 at 3 36 32 pm](https://cloud.githubusercontent.com/assets/52581/7076329/3e72afca-dece-11e4-988b-a6a6b6a29f8a.png)

**Comment by chriscct7** [comment]
+1

**Comment by pippinsplugins** [comment]
I really like this.

**Comment by sunnyratilal** [comment]
:+1:

**Comment by cklosowski** [comment]
Yes, I personally would lot to remove it from the list table, or make it hidden until a click. We're wasting a ton of space with that column.

**Comment by spencerfinnell** [comment]
Agreed @cklosowski -- even removing the text/style/color attributes would help. 

I know I'm not the average user but I know I've never used it. Might be better as a quick plugin or code snippet to add it to the columns for those who tend to use it a lot.

**Comment by ghost1227** [comment]
Something like this?

![](http://f.cl.ly/items/1U0K1I2P0E2Z1F0E043S/Screen%20Shot%202015-05-27%20at%202.56.23%20PM.PNG)

**Comment by spencerfinnell** [comment]
Maybe a "View" link to toggle the input? Similar to the Edit/Browse links above it.

**Comment by ghost1227** [comment]
I just copied Andrew's example... but...

**Comment by ghost1227** [comment]
Something like this @spencerfinnell?

![](http://cloud.section214.com/image/471k0w3K0R0t/Screen%20Shot%202015-05-27%20at%203.30.03%20PM.PNG)

![](http://cloud.section214.com/image/1a0Q423S2n1o/Screen%20Shot%202015-05-27%20at%203.30.31%20PM.PNG)

**Comment by mindctrl** [comment]
This is cool, though you could argue a shortcode that displays a purchase link has nothing to do with publishing the content and is unrelated to everything else in that box.

**Comment by ghost1227** [comment]
TECHNICALLY you could argue that the shortcode makes it possible to 'publish' the product wherever you want. But... it wasn't my idea to put it there, I just did the implementation. :wink:

**Comment by ghost1227** [comment]
Also, there isn't really anywhere it's 'better' suited on that page, and adding a whole new metabox for it is just silly.

**Comment by mindctrl** [comment]
@ghost1227 you could, but the purchase_link shortcode doesn't output all the product information. [downloads id=xx] would make more sense in that context. But I agree that it's likely the best place on that page all things considered.

**Comment by pippinsplugins** [comment]
I think I'd rather see the short code in the pricing meta box, or perhaps the settings box.

**Comment by ghost1227** [comment]
So like this?

![](http://cloud.section214.com/image/3s2K3y47331l/Screen%20Shot%202015-05-27%20at%204.35.56%20PM.PNG)

**Comment by pippinsplugins** [comment]
Yeah, I like that a lot

**Comment by ghost1227** [comment]
Well it's committed!

**Comment by ghost1227** [comment]
Just to clarify... the code is committed, not me :wink:

**Comment by pippinsplugins** [comment]
Merged in and tagged with `Needs Testing` for further review before we close it.

**Comment by pippinsplugins** [comment]
@ghost1227 Looks great to me. Closing.
