### ISSUE TITLE
Selected image size doesn't get inserted into File URL field in Download Files box

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/easy-digital-downloads#3341]
Upload an image in the File Downloads box, [select a size](http://f.cl.ly/items/2G171D2C0h0A19361U3x/Image%202015-04-10%20at%209.58.02%20AM.png) and choose _Insert into download_. Instead of inserting the selected size, it inserts the original full size upload.

Use case for this working: photo site that sells various sizes at different costs and the file sizes are handled automatically by the theme or plugin doing their `add_image_size` stuff.

**Comment by cklosowski** [comment]
We're only storing the attachment ID, not the thumbnail selected in that dropdown. I believe that was added just recently into the WP Core media selector. We'll have to add a way to log/store if an image thumbnail name was selected in that dropdown, and know to deliver it.

This isn't going to be a small change. I could be wrong, but it's a new feature, not a broken feature, IMO.

**Comment by cklosowski** [comment]
@pippinsplugins how do  you feel on this one? It's a case where users who sell photos want to be able to use the registered thumbnail size as the download. I'd almost like to see that in core, but part of me leans towards extension?

**Comment by pippinsplugins** [comment]
I think this should be core. We have enough people selling images that's
not really a small niche.

**Comment by cklosowski** [comment]
Ok, will try and come up with a UI for that. Would be nice if someone could quickly change which thumbnail size to offer, but we're back to cluttering up that space again with info. Will see what we can do

**Comment by pippinsplugins** [comment]
I'd think just showing it inside of the select image modal would be best.

**Comment by cklosowski** [comment]
It already shows there when you select an image, it's a matter of where do we store it, how do we store it, etc.

**Comment by cklosowski** [comment]
guessing it'll just be another price ID option

**Comment by pippinsplugins** [comment]
Why? The final UI shouldn't change at all. It just needs to store the URL to the selected size, not to the fullsize image. That's it :)

**Comment by cklosowski** [comment]
Punting for now I want to tackle this but we have a couple options:
1) Just rely on the new URL provided for the thumbnail
2) Save the thumbnail ID and pull it dynamically at the time of file download, this way if something changes in the urls, etc we're not saving it just in the URL field.

**Comment by cklosowski** [comment]
This is looking a little harder than simply grabbing the right size, the item we're iterating on as the selection, going to have to rework our media manager integration.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by mindctrl** [comment]
@cklosowski thanks for looking at this. Aside from grabbing the selected image URL, can you make a little checklist of other things that need to be updated to account for this so I can better wrap my head around it?

**Comment by cklosowski** [comment]
I think we have a couple options here and it comes down to our download process as well as the UI:
- [] Store the selected thumbnail size (text identifier) of the selected thumbnail in addition to the attachment ID
- [] Update the URL to be the properly sized image URL
- [] When requested, check for a size as well as the attachment ID to deliver the download.

I don't like the idea of just storing the URL and going off that because things change, http scheme, domains, etc.

**Comment by cklosowski** [comment]
Punting this to 2.5.3 as we get close to locking down 2.5, I like it but not until I can figure out this media uploader thing.

**Comment by cklosowski** [comment]
I'd like to tackle this alongside #4606. We can do some good updates to the metabox/file selection interface here.

**Comment by SDavisMedia** [comment]
Just ran into this in support. https://secure.helpscout.net/conversation/267268321/45138/?folderId=321418

**Comment by cklosowski** [comment]
@SDavisMedia @mindctrl Mind giving this a shot?

**Comment by mindctrl** [comment]
@cklosowski I'm seeing a notice when downloading:

`Undefined index: url in /wp-content/plugins/easy-digital-downloads/includes/process-download.php on line 98`

Otherwise it seems to be working well.

**Comment by cklosowski** [comment]
Weird.  Getting those. Can you add a screenshot of your download file
configuration?

**Comment by SDavisMedia** [comment]
I'm getting the same behavior John described. I get the error when trying to download the file (appears to be the correct file) from the purchase receipt.

My product configurations is extremely basic:

![7ae8597d6e75aac6f898fa876ef5a9b9 _image 202017-01-16 20at 203 15 31 20pm](https://cloud.githubusercontent.com/assets/2359131/22002205/cc3ab95e-dbfe-11e6-80d6-1872e337f960.png)

**Comment by cklosowski** [comment]
Thanks @SDavisMedia looking.

**Comment by SDavisMedia** [comment]
Now I get the following error at the same part of the process:

```
Notice: Undefined variable: attached_file in /Applications/MAMP/htdocs/edd/wp-content/plugins/easy-digital-downloads/includes/process-download.php on line 105
```

**Comment by cklosowski** [comment]
@SDavisMedia ok, ready for one more test. I'm not seeing this error so I'm just putting in a bunch of fallback code to cases you're seeing.

**Comment by SDavisMedia** [comment]
All checks out for me! :+1:
