### ISSUE TITLE
Provide filter for both `where` and `join` in `edd_count_payments` function

### ISSUE THREAD

**Issue by sudar** [easydigitaldownloads/Easy-Digital-Downloads#3344]
Right now the `edd_count_payments` function provides filter only for the `where` function and not for the `join` clause. Relevant code.

https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/payments/functions.php#L506

`where` clause without `join` will be useless in most scenarios when we filter things in the payment history screen.

Example: I need this filter payments by campaign in my EDD Campaign Tracker extension

We have two options.

- Use a single filter, but pass two parameters. In that case the name of the filter should be changed.
- Use two filters.

I am ready to send a pull request once a decision is made on one of the above two options.

**Comment by pippinsplugins** [comment]
Let's use two filters.

**Comment by cklosowski** [comment]
Two filters would be ideal, allows for maximum extensibility, and less confusion I think on what's expected. :+1:

**Comment by sudar** [comment]
I have the PR ready for this. See #3352 

Let me know if anything else needs to be done for the PR to be merged.

**Comment by pippinsplugins** [comment]
@sudar This has been merged in for 2.3.9.
