### ISSUE TITLE
Update Browser.php for 2.4

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/Easy-Digital-Downloads#3345]
Browser.php hasn't been updated in a while. There's been alot of improvements to it during the last few years.

This issue will track the updating of it to 1.9.0 (modified for PHP 5.2 support by me) to the current 1.9.5 possibly 1.9.6 by 2.4's launch.

This will be comprised of two phases. 

The first phase consists of updating the code formatting to bring to standards. This drops the filesize almost in half, by removing unbelievably amounts of whitespace, but more importantly will make it way easier for us to do phase 2 because it will be a heck of alot easier to read the diffs.

The second phase (**this one**) consists of a seperate PR which may or may not be ready by 2.4. I'm going to do alot of testing with it to ensure PHP compatibility and just generally debugging and testing in general.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by chriscct7** [comment]
The first phase pr is in as #3346

**Comment by chriscct7** [comment]
Phase 1 completed. Dropped a ton of whitespace, and its a heck of alot more readable, way easier to diff on for Phase 2.

Going to start prepping that pr tomorrow

**Comment by pippinsplugins** [comment]
This was completed for EDD 2.3.8

**Comment by chriscct7** [comment]
Phase 1 was completed. This ticket is for phase 2, which I'm working on as a PR for 2.4

**Comment by pippinsplugins** [comment]
No, we need a separate issue for 2.4.

One issue per release. We don't use PRs as issue tracked.
