### ISSUE TITLE
Notices filling my log because of edd_get_cart_item_discount_amount()

### ISSUE THREAD

**Issue by bseddon** [easydigitaldownloads/Easy-Digital-Downloads#3347]
The function edd_get_cart_item_discount_amount( $item = array() ) calls edd_get_cart_item_price() passing in the 'options' element from the $item array.  However if the edd_get_cart_item_discount_amount() function is called without any parameters and the $item array is initialized as an empty array and the result is a notice written to the log file.

It will be great if the use of $item['options'] can be guarded to prevent the notices.  For example replace line 1093 in discount-functions.php with something like:

$price = edd_get_cart_item_price( $item['id'], isset($item['options']) ? $item['options'] : array() );

**Comment by pippinsplugins** [comment]
Thanks for the heads up, we'll get it fixed.

**Comment by cklosowski** [comment]
I actually think we can make this much cleaner, by just returning 0 if our `$item` is an empty array. If that's an empty array, then there's no need to find the cart item price, because we have no item to identify. If we could also throw in a check for the `options` key, to be thorough, but that would help take care of the case of using `edd_get_cart_item_discount_amount()` with no arguments.

**Comment by cklosowski** [comment]
Yep, confirmed. not only does it throw an error for the `options` but also for the `id`:
```
............................I........E

Time: 7.36 seconds, Memory: 39.25Mb

There was 1 error:

1) Tests_Discounts::test_get_cart_item_discounted_amount
Undefined index: id

/Users/cklosowski/WordPress/src/wp-content/plugins/Easy-Digital-Downloads/includes/discount-functions.php:1093
/Users/cklosowski/WordPress/src/wp-content/plugins/Easy-Digital-Downloads/tests/tests-discounts.php:229
```

Going to code this up and also add a unit test to make sure it's not going to happen again without us seeing it.

**Comment by cklosowski** [comment]
It should be noted though, that calling `edd_get_cart_item_price` without the options, will always return `0` as it cannot decide what price ID to use.

**Comment by cklosowski** [comment]
It should be noted though that calling `edd_get_cart_item_price` on an item that has variable pricing, will return `0`.
