### ISSUE TITLE
[downloads] pagination container outputs HTML when empty

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/Easy-Digital-Downloads#3348]
Noticed this while working on Vendd because it was screwing with some of my hacky CSS. 

Use the `[downloads]` shortcode in a manner that requires **no** pagination. The HTML [here](https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/49bba4499763ed571e7a9fa336e24ddd902663ba/includes/shortcodes.php#L531) is still output on the page and shouldn't be.

**Comment by sdavis2702** [comment]
It would be awesome if this could be milestoned 2.3.7. I need the adjustment for Vendd's release which is aimed for May 4th. :grin:

**Comment by spencerfinnell** [comment]
Would also be helpful if it wasn't in the `.edd_downloads_list` wrapper, but I know that might affect too many things to move out.

**Comment by pippinsplugins** [comment]
Milestoned.
