### ISSUE TITLE
product quantity fields allow 0 but do not adjust the quantity

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#3349]
This applies to quantity fields on all purchase buttons. You can manually enter 0 but EDD will not accept that. Instead, it will use the last acceptable quantity from that field. In most cases, that's 1.

This is most important at the checkout cart as at least one user has assumed changing a quantity to 0 would remove it from the cart and it doesn't. 

Relevant ticket: https://easydigitaldownloads.com/support/topic/number-field-zero-issue-checkout-cart/

**Comment by ghost1227** [comment]
So would we rather set minimum to 1 (my recommendation), or somehow rig it so that entering 0 removes it?

**Comment by pippinsplugins** [comment]
Minimum of 1 makes sense to me.

**Comment by SDavisMedia** [comment]
Agreed... minimum of 1.

**Comment by cklosowski** [comment]
Closing as won't fix. Minimal return on investment since there is a 'remove' link right there.
