### ISSUE TITLE
Include unformatted amount in edd_recalculate_taxes response

### ISSUE THREAD

**Issue by bseddon** [easydigitaldownloads/Easy-Digital-Downloads#3353]
When an EU users buys a product it necessary to confirm their billing address country is the same as their IP address country or have them confirm these countries are different.  The VAT plugin does this.

But now suppose the user who should be prompted to confirm there is a difference in the two countries is given a discount code worth 100% of the purchase price.  When the user enters the code, the difference in the country codes is no longer relevant because no VAT is due.  However, so as far the checkout process code (JavaScript) is concerned, the user should still be required to confirm the country difference because it doesn't know the cart total is now zero.

The AJAX call to edd_recalculate_taxes() returns the current cart amount so in principle the cart total value could be used by the JavaScript code to determine if tax is still due.  However this value is a formatted amount because it is used to update total value at the end of the checkout form. 

You might think it will be possible to strip the formatting from the formatted cart total but this is not straight forward because the formatting of the value will depend upon the country selection, a selection that may change during the life cycle of the checkout form prior to a purchase.  So even if the locale used on the server to format the total may be known when the checkout form is first generated, the locale may not be the same when a user changes their country selection.

It will be great if the edd_recalculate_taxes function response can be augmented to include the cart total as an unformatted number as well as a formatted number.  It will also be ideal that the tax amount (unformatted) is also included in the response.  The tax amount is the real value upon which a decision about whether it is necessary to ask the user to confirm their billing and IP address countries are different should be based.  If the cart total is zero the tax is likely to be zero but perhaps there are scenarios in which the tax is not zero even if the cart total is zero.

**Comment by pippinsplugins** [comment]
Makes sense to me! I'm going to rename the issue title to properly reflect the suggested change.

**Comment by cklosowski** [comment]
Can we rename this to `total_raw`? Plain might not translate well and `raw` is a pretty commonly used term in software for 'unformatted data'

**Comment by pippinsplugins** [comment]
I like that much better.
