### ISSUE TITLE
Schema markup missing "priceCurrency"

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#3355]
It looks like we're adding `itemprop="price"` which is correct. But we're also putting the currency symbol in there. Instead, the `priceCurrency` property should be used in ISO 4217 format to describe the `price` property.

Validators don't seem to be enforcing this, though, which is weird. Not sure what to make of that considering `priceCurrency` is required.

**Comment by SDavisMedia** [comment]
Looks like we may also need to look into the `AggregateOffer` property when variable pricing is used. Right now we still use the Price property but AggregateOffer appears to be designed for price variations and has its own set of required properties, like `lowPrice`.

**Comment by cklosowski** [comment]
Starting to look into this one. We're going to have to think carefully about it, as it's going to have to cause us to rewrite quite a bit of the purchase button code.

**Comment by SDavisMedia** [comment]
It also looks like we're not including `itemprop="price"` at all for non-variable pricing items. Hopefully I'm tripping. Can you confirm that, @cklosowski?

**Comment by cklosowski** [comment]
@SDavisMedia yeah i think you are right. but there's a lot here to get it right. I'm moving to 2.4. With our past rush jobs on Schema, I want to make sure we get this right. I'm no expert on schema so if someone wants to jump on this I'd be happy to have the help

**Comment by SDavisMedia** [comment]
I'm with you 100%. It's sort of new to me too. Reading docs on it while implementing it is the name of the game for me. Good call pushing it back. We need to get it right because what we learn here will come in handy for the EDD Reviews rewrite. I'll help get it in there too.

**Comment by cklosowski** [comment]
@SDavisMedia thanks, pushed, and we'll regroup once we've had some time to do research on how to do this right.

**Comment by pippinsplugins** [comment]
Punting to 2.5 due to lack of time to do adequate research.

**Comment by pippinsplugins** [comment]
Correction: 2.4.3

**Comment by cklosowski** [comment]
:+1:

**Comment by pippinsplugins** [comment]
Needs to go to 2.5.

**Comment by pippinsplugins** [comment]
Another related PR: https://github.com/easydigitaldownloads/easy-digital-downloads/pull/4567

**Comment by pippinsplugins** [comment]
Merged #4567 into `release/2.6`
