### ISSUE TITLE
Editing Customer seem to corrupt the details in Purchase History

### ISSUE THREAD

**Issue by shazahm1** [easydigitaldownloads/easy-digital-downloads#3356]
I needed to update a user's email address.

The first thing I did was went to the Users admin page, searched for the old email address and then updated to the user with the new email address.

I then went to the Purchase History admin page and searched for the new address expecting to find the purchases. No luck. A bug???

So, I searched by the old email address and the purchases were found. I clicked on the View Order Details link of one of the purchase records. I then clicked the View Customer Details link and then click the Edit Customer link. I changed the email and clicked the Update Customer button.

Now all the records on the Purchase History for this customer seems to be corrupt. Please see the screenshot. Notice the email address, they are all change to just "r" except the top one I'll explain that next.

![2015-04-20_10-44-48](https://cloud.githubusercontent.com/assets/1185008/7232578/6b72dade-e74a-11e4-92f3-ecb4bcb60036.jpg)

Here's a screenshot one of the records:

![2015-04-20_10-48-14](https://cloud.githubusercontent.com/assets/1185008/7232756/5980c114-e74b-11e4-978a-6bf0ea2a57fd.jpg)

Notice the value for the address and discount code. This happened simply by editing the customer record.

What is curious is that searching by the new email address brings up the correct purchase history records.

Ok, so I thought I'd just edit each purchase record to fix them. This does not seem possible. I removed the "r" from each of the address fields and left them empty. After clicking the Save Payment button now all the fields show "A", the discount code too. Please see the screenshot:

![2015-04-20_10-58-04](https://cloud.githubusercontent.com/assets/1185008/7233017/baaa5c38-e74c-11e4-9a50-756e658c8bb0.jpg)

Lastly, it seems that the email address is not changed for the software license key. Should changing the email address also change this??? At this point I hesitate to try updating the email address assigned to the several license keys assigned to products this custom has purchased. However, that said, the email address is updated for the software license key is updated after clicking the Save Payment button.

**Comment by pippinsplugins** [comment]
I know that we do need to update customer records when the user record is updated.

I have _not_ ever seen the corruption happen . . .  Updating the email address should never have caused that. Can you re-test on a staging site and see if it happens every time?

**Comment by cklosowski** [comment]
We also have a ticket open to update the Customer/User profiles when edited in #3364

**Comment by cklosowski** [comment]
It looks like something is messing with a data type...the characters `A and r` seem to possibly be looking at an index of `Array`? Is it possible that a datatype is getting mixed up in a plugin conflict or error we're not catching?

**Comment by pippinsplugins** [comment]
That'd be my guess as well.

**Comment by shazahm1** [comment]
I haven't had a whole lot a time to debug... but, I did do a couple var dumps in this file:

`/public_html/wp-content/plugins/easy-digital-downloads/includes/admin/payments/view-order-details.php`

I dumped `$payment_meta`. Result:

```
array(9) {
  ["currency"]=>
  string(3) "USD"
  ["downloads"]=>
  string(71) "a:1:{i:0;a:3:{s:2:"id";i:2723;s:7:"options";a:0:{}s:8:"quantity";i:1;}}"
  ["user_info"]=>
  string(171) "A:6:{s:2:"id";i:693;s:5:"email";s:25:"[REDACTED]";s:10:"first_name";s:7:"[REDACTED]";s:9:"last_name";s:6:"[REDACTED]";s:8:"discount";s:4:"none";s:7:"address";b:0;}"
  ["cart_details"]=>
  string(393) "a:1:{i:0;a:9:{s:4:"name";s:4:"Form";s:2:"id";i:2723;s:11:"item_number";a:3:{s:2:"id";i:2723;s:7:"options";a:0:{}s:8:"quantity";i:1;}s:10:"item_price";d:9.9900000000000002131628207280300557613372802734375;s:8:"quantity";i:1;s:8:"discount";d:0;s:8:"subtotal";d:9.9900000000000002131628207280300557613372802734375;s:3:"tax";d:0;s:5:"price";d:9.9900000000000002131628207280300557613372802734375;}}"
  ["tax"]=>
  int(0)
  ["fees"]=>
  array(1) {
    ["edd_sl_renewal"]=>
    array(2) {
      ["amount"]=>
      string(5) "-2.00"
      ["label"]=>
      string(24) "License Renewal Discount"
    }
  }
  ["key"]=>
  string(32) "[REDACTED]"
  ["email"]=>
  string(24) "[REDACTED]"
  ["date"]=>
  string(19) "2014-05-14 08:26:58"
}
```

Then I dumped `$user_info`. Result:
```
A:6:{s:2:"id";i:693;s:5:"email";s:25:"[REDACTED]";s:10:"first_name";s:7:"[REDACTED]";s:9:"last_name";s:6:"[REDACTED]";s:8:"discount";s:4:"none";s:7:"address";b:0;}
```

Note that capital `A`. I changed that to a lowercase `a` in the DB by editing the postmeta and it unserialized correctly.

I also did the same for those that started with an `r` and changing it to an `a` in the postmeta also fixed the records.

I though about the `A` and `r` being the index of an array too but I'm not sure how that would affect the serialization of an array. Suggestions an where to look?

I do have several EDD extensions installed and all up to date.

**Comment by cklosowski** [comment]
Something is wrong in the way your Payment Meta is being setup then, there shouldn't be nested serialized data like that. When you do a get_payment_meta, it should come back as an array. Have you tried deactivating other plugins, one by one in a staging to see if the array comes back correctly? If you do this with JUST edd core does it still happen?

**Comment by shazahm1** [comment]
@cklosowski 

On newer pushases the payment meta is an array. Sample from the newest purchase:

```
array (
  'currency' => 'USD',
  'downloads' => 
  array (
    0 => 
    array (
      'id' => '2709',
      'options' => 
      array (
      ),
      'quantity' => 1,
    ),
  ),
  'user_info' => 
  array (
    'id' => 7125,
    'email' => '[REACTED]',
    'first_name' => '[REACTED]',
    'last_name' => '[REACTED]',
    'discount' => 'none',
    'address' => false,
  ),
  'cart_details' => 
  array (
    0 => 
    array (
      'name' => '[REACTED]',
      'id' => '2709',
      'item_number' => 
      array (
        'id' => '2709',
        'options' => 
        array (
        ),
        'quantity' => 1,
      ),
      'item_price' => 19.989999999999998436805981327779591083526611328125,
      'quantity' => 1,
      'discount' => 0,
      'subtotal' => 19.989999999999998436805981327779591083526611328125,
      'tax' => 0,
      'fees' => 
      array (
      ),
      'price' => 19.989999999999998436805981327779591083526611328125,
    ),
  ),
  'key' => '',
  'email' => '[REACTED]',
  'date' => '2015-04-26 22:22:13',
)
```

I have purchase going back to EDD 1.3 (I think). Those older records look like the one in my previous reply.

So, I assume the payment meta is being properly set up. My assumption is the payment meta had a different structure at some point... maybe because older records did have nested serialized arrays that is why they would become corrupt now when they are edited. The code is expecting an array when editing old records and it is getting a serialized array instead.

**Comment by shazahm1** [comment]
@cklosowski 

What function sets up the user_info in the payment meta?

**Comment by shazahm1** [comment]
I'll spin up a mirror site sometime this week leaving only EDD core active and using the default theme to see what happens when editing an older purchase and new new purchase and report back.

**Comment by cklosowski** [comment]
The data for the user_info is pretty standard across the setups. What gateway are you using? Is that the same gateway as you were using during the 1.3 purchases? I'm curious to see what happens with nothing else in the way. If this is an old data issue, maybe @pippinsplugins has seen this before?

**Comment by shazahm1** [comment]
I use the PayPal (the one bundled with EDD) and Stripe gateways. Back then I only used the bundled PayPal gateway.

**Comment by pippinsplugins** [comment]
Nope, I've never seen this.

**Comment by pippinsplugins** [comment]
@shazahm1 have you ever seen this again?

**Comment by shazahm1** [comment]
@pippinsplugins Sorry, no, for two reasons. I never did find time to set up a mirror to test further and I have not needed to update a customer account since. Well, I did just add a secondary email to a customer and everything seemed fine.

**Comment by pippinsplugins** [comment]
Ok then I'm going to close as fixed. If it ever comes up again, we can re-open.
