### ISSUE TITLE
Allow all Logs to be Exported

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#3359]
I think just a simple export button, maybe with a from/to and/or a dropdown of common ranges would be sufficient

**Comment by pippinsplugins** [comment]
Which logs? Sales? Downloads? All of them?

**Comment by chriscct7** [comment]
All logs

**Comment by mindctrl** [comment]
Would love to see this too.

**Comment by pippinsplugins** [comment]
We have to get our batched export API finished before we can do this.

**Comment by cklosowski** [comment]
With our batch exporter completed, we can do this now.

**Comment by sunnyratilal** [comment]
@pippinsplugins @cklosowski How should the `Error Message` for a `Payment Error` be handled in the CSV export?  Currently, I've just eliminated it from the export as it's _usually_ serialised data and doesn't really make sense to be in the export. Thoughts?

**Comment by pippinsplugins** [comment]
I would not include support for payment errors.

**Comment by sunnyratilal** [comment]
Ready for testing.

**Comment by pippinsplugins** [comment]
@sunnyratilal could we please remove the payment errors export per my comment above?

**Comment by sunnyratilal** [comment]
@pippinsplugins PR updated.

**Comment by pippinsplugins** [comment]
Thanks.

**Comment by pippinsplugins** [comment]
Working well here!

**Comment by cklosowski** [comment]
Looks good on my end too. was just about to close this out :) you beat me to it @pippinsplugins
