### ISSUE TITLE
Improve EDD Add-Ons page in Admin

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/Easy-Digital-Downloads#3361]
It's been a while since we've improved the Add-Ons page in the EDD Admin page display, after some discussion with the team we're going to look at improving it by doing 2 things:
1) Link to the Starter Package
2) Separate into two tabs (Popular and New)

This should help people see what's available easier and be less overwhelmed during the on-boarding process.

This needs to be done after the implementation of https://github.com/easydigitaldownloads/EDD-Site/issues/554

**Comment by sumobi** [comment]
As @pippinsplugins has suggested the starter package will be the first shown. We should also highlight it in some way, perhaps with a different color background, while all the rest could have white background (I think this will look nicer than the current grey). Make them look more like cards.

**Comment by pippinsplugins** [comment]
Feed (on staging) now shows the starter package first (wrong image still): http://staging.easydigitaldownloads.com/?feed=addons

**Comment by cklosowski** [comment]
Ok, so this will put that starter package first for customers who will not take this update. Are we building a new view for the tabbed interface for the users who upgrade?

**Comment by cklosowski** [comment]
Ignore that previous statement, I see waht you are saying in the other ticket.

**Comment by pippinsplugins** [comment]
:)

**Comment by cklosowski** [comment]
Ok, so here's where it's at. Old on the Left, New on the Right:
![image](https://cloud.githubusercontent.com/assets/1390124/7285750/bb89791c-e8fb-11e4-9985-a2a6641530a7.png)

**Comment by spencerfinnell** [comment]
Does there need to be an &mdash; before the Browse Extensions button?

**Comment by pippinsplugins** [comment]
Love it.

**Comment by cklosowski** [comment]
@spencerfinnell I was wondering teh same. I'm going to remove it...it's a bit disjointed IMHO.

**Comment by cklosowski** [comment]
Yep @spencerfinnell looks much better:
![image](https://cloud.githubusercontent.com/assets/1390124/7287276/e6d2edea-e907-11e4-8b85-7df7b17b2be7.png)

**Comment by spencerfinnell** [comment]
Looks great.

**Comment by cklosowski** [comment]
Just 'intentionally' broke this as it's going to use the live URL. That way we don't forget...if you want to change it to use the staging, edit;
`add-ons.php:91` to use the staging url.

**Comment by pippinsplugins** [comment]
Looks superb.

We'll close this out as soon as the RSS is made live on the EDD site.
