### ISSUE TITLE
Tags order

### ISSUE THREAD

**Issue by franceimage** [easydigitaldownloads/Easy-Digital-Downloads#3363]
Would it be possible to remove the tags hiding the real last tag in alphabetical order ?

At the moment, this is what you see 

![edd github tags](https://cloud.githubusercontent.com/assets/3442039/7323731/1e870fd2-eab1-11e4-91c8-c70981812672.png)

This order is exactly what you get when you use github API to [check for tags](https://github.com/franceimage/wp-alt-repositories) and it's not that easy to [sort them by create date](http://stackoverflow.com/questions/19452244/github-api-v3-order-tags-by-creation-date)
The first tag on the list should be 2.3.7

Cheers

**Comment by pippinsplugins** [comment]
We don't control the tags order so not much we can do here.
