### ISSUE TITLE
Download History in API 

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/Easy-Digital-Downloads#3365]
Right now we let people export download history as a CSV.
Let's let people access that via the api as well

**Comment by pippinsplugins** [comment]
@ghost1227 This is concerning file downloads, not sales. Sales are already accessible in the API.

**Comment by ghost1227** [comment]
and your point?

**Comment by pippinsplugins** [comment]
The pull request was for sales, not file download logs.

**Comment by ghost1227** [comment]
Bet me

**Comment by ghost1227** [comment]
oh wait... i think i completely misunderstood the point of this issue

**Comment by ghost1227** [comment]
this is supposed to be the data from `edit.php?post_type=download&page=edd-reports&tab=logs` isn't it...

**Comment by pippinsplugins** [comment]
That was my point :)

Yes, this issue is related to pulling the FILE download history via the API.

**Comment by ghost1227** [comment]
Well dammit

**Comment by ghost1227** [comment]
@pippinsplugins resubmitted as requested

**Comment by pippinsplugins** [comment]
In `issue/3365` for testing.

**Comment by pippinsplugins** [comment]
Working perfectly. Merged into release/2.5 and closing.

**Comment by pippinsplugins** [comment]
After a  quick call with @topher1kenobe, we feel the endpoint should be changed from `downloads` to `download-logs`. We use `download` frequently to refer to a product so having `/downloads/` creates confusion and is unclear whether it refers to download products or file downloads.

The other option I like is `/edd-api/file-downloads/`

Opinions @easydigitaldownloads/core-devs ?

**Comment by chriscct7** [comment]
+50k

**Comment by pippinsplugins** [comment]
@chriscct7 Which of the two do you prefer?

**Comment by spencerfinnell** [comment]
Haven't ever looked at the API so not sure if this type of endpoint would even work, but what about `/logs/downloads/`, which would allow expansion for the other available logs.

**Comment by pippinsplugins** [comment]
@spencerfinnell At the moment, no, that wouldn't work but I can see that being a great idea for a v2 or v3.

**Comment by chriscct7** [comment]
I personally strongly prefer Spencers but since that is impossible for the current generation we can at least make the endpoint look close to that so my preference is logs-downloads so that when we do move to it its not such a huge jump

**Comment by chriscct7** [comment]
Then when we do update all we're doing is changing a - to a /

**Comment by cklosowski** [comment]
I too, would prefer @spencerfinnell's suggestion, but for now I'm for `download-logs`.

**Comment by pippinsplugins** [comment]
Works for me.

**Comment by cklosowski** [comment]
Could we introduce the `logs` endpoint, and pass in `?type=download`?

**Comment by cklosowski** [comment]
this way we can have the `logs` endpoint for future use, and don't have to make a new endpoint for people later for other log types.

**Comment by cklosowski** [comment]
We need to come up with a good endpoint here, we have 3 ideas, please vote on one of these three:
1. `file-downloads`
2. `download-logs`
3. `logs-downloads`

**Comment by mindctrl** [comment]
Make it as clear as possible. 2 and 3 aren't clear and could be confused with download products in some way. 4 is the clearest. 1 is ok.

**Comment by shazahm1** [comment]
+1 for option 4

**Comment by pippinsplugins** [comment]
4.

**Comment by topher1kenobe** [comment]
4

**Comment by chriscct7** [comment]
3

**Comment by spencerfinnell** [comment]
4 for now.

**Comment by pippinsplugins** [comment]
4 it is.

**Comment by michaelbeil** [comment]
May the 4th be with you.

**Comment by cklosowski** [comment]
Going with 4 then. I found a small bug when you pass in an invalid customer id, in that it returns data. If an invalid customer ID is passed in, no data should be shown.

**Comment by cklosowski** [comment]
Ok @easydigitaldownloads/core-devs this should be ready, are we good to close this out now that we've decided on an endpoint and fixed that invalid customer ID thing?

**Comment by pippinsplugins** [comment]
Yep yep!
