### ISSUE TITLE
Race condition with edd_get_next_payment_number()

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#3367]
Through two separate support tickets, I've discovered that `edd_get_next_payment_number()` is susceptible to race conditions.

We use `EDD_Payments_Query` to determine the next payment number by pulling up the latest payment number.

If a site is processing a large number of payments, has a strong database cache, or a combination of both, it's possible for two payments to get assigned the same number since the number returned by `EDD_Payments_Query` is actually one (or more) numbers behind the actual latest.

To resolve this, we should look at making the query more efficient. I suspect we could resolve this by getting rid of `EDD_Payments_Query` and instead using a direct query on the `wp_postmeta` table to find the row with a key of `_edd_payment_number` and grabbing just the most recent row.

Tickets: 
https://easydigitaldownloads.com/support/topic/duplicate-invoice-numbering/
https://easydigitaldownloads.com/support/topic/urgent-duplicated-payment-ids/

**Comment by chriscct7** [comment]
What if we just stored the last number as an option?

**Comment by pippinsplugins** [comment]
That could work though we'd still run into potential race conditions there.
Definitely faster than querying wp_postmeta though!

**Comment by chriscct7** [comment]
My thoughts exactly

**Comment by cklosowski** [comment]
I agree, this should reduce it enough. Not remove it entirely, but it's a good start.

**Comment by cklosowski** [comment]
Ok @pippinsplugins I think this should help avoid the race condition.

This allows a backwards compatibility check and if the option doesn't exist, creates it from the last payment, or if no past payments exist, starts at the `$start` value.

**Comment by chriscct7** [comment]
@cklosowski see the comments on that pr
