### ISSUE TITLE
Update Browser.php library

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#3381]
Browser.php hasn't been updated in a while. There's been alot of improvements to it during the last few years.

This issue will track the updating of it to 1.9.0 (modified for PHP 5.2 support by me) to the current 1.9.5 possibly 1.9.6 by 2.4's launch.

This will be comprised of two phases.

The first phase, which is completed ( #3345 ) , consists of updating the code formatting to bring to standards. This drops the filesize almost in half, by removing unbelievably amounts of whitespace, but more importantly will make it way easier for us to do phase 2 because it will be a heck of alot easier to read the diffs.

The second phase (**this one**) consists of a seperate PR which may or may not be ready by 2.4. I'm going to do alot of testing with it to ensure PHP compatibility and just generally debugging and testing in general.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by sunnyratilal** [comment]
@chriscct7 Would you be able to have an updated `Browser.php` ready for 2.6.12?

How much needs to be modified in order for it to be used with EDD safely?

**Comment by chriscct7** [comment]
Huh? Nothing needs to be modified, it works perfectly fine. Not sure why this is on a point release. I was going to work on updating the library to make it do better OS/browser detection but I won't have time to re-investigate this for a while.

**Comment by chriscct7** [comment]
Unless someone has a specific enhancement needed on this, this issue should be closed and we can open a new GH ticket if someone finds something to fix/add.

cc: @easydigitaldownloads/core-devs
