### ISSUE TITLE
UI improvements to the download statistics meta box

### ISSUE THREAD

**Issue by jancbeck** [easydigitaldownloads/Easy-Digital-Downloads#3385]
In the German localization - and I suspect this counts for any non-English localization with longer label names - the statistics meta box label and the value directly touch each other, making them hard to read.

![bildschirmfoto 2015-05-04 um 11 26 29](https://cloud.githubusercontent.com/assets/865311/7456184/7addd634-f250-11e4-83f6-37a57d4a0475.png)

Either add a little padding or get rid of the width. The WP-core publishing meta box doesn't use a fixed width either so those UIs could be more unified. Oh and I just noticed that WP-core sets the value in bold while EDD boldens the value.

![bildschirmfoto 2015-05-04 um 11 29 38](https://cloud.githubusercontent.com/assets/865311/7456248/0d140258-f251-11e4-8c1e-fefcf4cae6e3.png)

Perhaps the cart and chart-area dashicons make sense here as they are used in the customer view.

![bildschirmfoto 2015-05-04 um 11 34 55](https://cloud.githubusercontent.com/assets/865311/7456327/a32ca222-f251-11e4-8875-4284805564ef.png)

**Comment by cklosowski** [comment]
Oh that does look terrible. Going to milestone this for 2.5, see what we can come up with.

**Comment by SDavisMedia** [comment]
I'm gonna go ahead and mimic the Publish box, icons, bolding, etc., unless anyone objects.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by SDavisMedia** [comment]
Proposed.

![screen shot 2015-08-25 at 9 16 35 pm](https://cloud.githubusercontent.com/assets/2359131/9484199/b7897544-4b6e-11e5-9f56-15860ec1e94c.png)

**Comment by pippinsplugins** [comment]
@SDavisMedia Could you set your language to German and confirm it still works well since that's what revealed the original issue here?

**Comment by SDavisMedia** [comment]
@pippinsplugins It wasn't happening because of the language. It was happening because the label had a hardcoded 70px width. The German word just happened to be right at the 70px or so mark. The code is gone now. https://github.com/easydigitaldownloads/Easy-Digital-Downloads/commit/0afdd66c158876c32a7cd1ea1478d25ad743ed19#diff-1c9c760368af32c531a54d869c3cf1acL206

They'll never touch/overlap again. It just flows inline. 

![screen shot 2015-08-25 at 10 44 18 pm](https://cloud.githubusercontent.com/assets/2359131/9485142/e60670e6-4b7a-11e5-8c09-fb11d3e6b51c.png)

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
Drop that into a PR if you could and thanks!

**Comment by SDavisMedia** [comment]
@pippinsplugins Just doing my job! Done. :+1:

**Comment by jancbeck** [comment]
Looks great, thanks!

**Comment by SDavisMedia** [comment]
No problem!

**Comment by spencerfinnell** [comment]
The extreme nitpick would be no `&mdash;` between the value and the link, but otherwise looks awesome!

**Comment by shazahm1** [comment]
Just randomly stumbled on this...

but why put the view sales log link by the number of sales... well, I understand why.. but wouldn't it be more consistent to have it with the other view links?

**Comment by SDavisMedia** [comment]
@spencerfinnell I didn't really see a reason for it to be there either but the sales count does kind of get lost in there considering the sales log link and sales label are way more dominant than [especially] a 1 or 2 digit quantity.

![screen shot 2015-08-26 at 9 30 04 am](https://cloud.githubusercontent.com/assets/2359131/9496295/3cb037b0-4bd5-11e5-80ae-e033d29ef5f1.png)

**Comment by SDavisMedia** [comment]
@shazahm1 I actually agree with that. The detailed earnings report is not beside the earnings total. Same scenario IMO. @pippinsplugins?

**Comment by SDavisMedia** [comment]
![screen shot 2015-08-26 at 9 35 07 am](https://cloud.githubusercontent.com/assets/2359131/9496390/ca873372-4bd5-11e5-82d5-7f6814916097.png)

**Comment by pippinsplugins** [comment]
How about we link sale count and link earnings. That would make it consistent with the Downloads list table: 
![screen shot 2015-08-26 at 9 36 19 am](https://cloud.githubusercontent.com/assets/1034109/9496431/ef2a0240-4bd5-11e5-8ab8-bd61dc73c588.png)

**Comment by pippinsplugins** [comment]
Or like @SDavisMedia proposed. I like both.

**Comment by spencerfinnell** [comment]
I like the separate list of links below.

**Comment by SDavisMedia** [comment]
![screen shot 2015-08-26 at 9 40 37 am](https://cloud.githubusercontent.com/assets/2359131/9496573/929916f0-4bd6-11e5-8613-c2da90dec9d9.png)

I vote left.

**Comment by mindctrl** [comment]
I like the right one, because it puts the related things together, is easier to grok at a quick glance, and is less cluttered. I'm just not sure if it'll hold up visually once we hit $1 billion in earnings. :laughing:

**Comment by SDavisMedia** [comment]
@mindctrl I could just as easily lean that way. :confounded:

**Comment by spencerfinnell** [comment]
Yeah I'm a little torn as well. Probably leaning to the right though.

**Comment by SDavisMedia** [comment]
Right it is!

**Comment by pippinsplugins** [comment]
Right is right!

_will see myself out now_

**Comment by chriscct7** [comment]
Yeah I prefer right
