### ISSUE TITLE
Add item_id support to EDD_License

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#3386]
The EDD_License handler currently passes `item_name` to the Software Licensing API.

This limits us on the ability to change Download product names on the EDD site, since the name passed to `EDD_License` is used to look up the license key.

We need to add support for passing the product ID (as `item_id`) so that we can start updating extensions.

Two extensions (as examples) that need updated:

- Wysija needs to be updated to MailPoet (formerly Wysija)
- Mail Chimp needs to be updated to MailChimp

The product names can't be changed until a few weeks after an update is pushed out with item_id support.

**Comment by cklosowski** [comment]
:+1: Been thinking about this a lot lately.
