### ISSUE TITLE
Re-work the ajax works test

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#3387]
The `edd_test_ajax_works()` function throws false positives pretty frequently. Let's see if we can identify why this happens and fix it.

**Comment by pippinsplugins** [comment]
I've come across a site where this test causes extreme slow downs: https://easydigitaldownloads.com/support/topic/admin-area-is-super-slow/

**Comment by pippinsplugins** [comment]
On the site above, it's failing because it is timing out:
```
object(WP_Error)#311 (2) { ["errors"]=> array(1) { ["http_request_failed"]=> array(1) { [0]=> string(20) "connect() timed out!" } } ["error_data"]=> array(0) { } }
```

**Comment by pippinsplugins** [comment]
I think we should go ahead and disable this test completely until we can track down a more reliable way to do it.

**Comment by cklosowski** [comment]
:+1: I'm with you @pippinsplugins This causes more support and confusion than is worth having. We can reintroduce it later once we've fixed it up.

**Comment by pippinsplugins** [comment]
Let's remove it then.

**Comment by cklosowski** [comment]
I'm going to punt this to 2.5, and create a new 2.4 issue to remove it.

**Comment by chriscct7** [comment]
Yeah I agree. Though I do think we should in 2.5 seriously work on bringing this back. While it did cause an increase in false positives, it did completely remove the issues caused by people being unaware of their ajax not working

**Comment by pippinsplugins** [comment]
Yep, agreed.

**Comment by cklosowski** [comment]
@chriscct7 No one is discounting the fact that it does hold value. Just need to make solid.

**Comment by chriscct7** [comment]
@cklosowski I wasn't suggesting anyone was, I was explaining why we're doing this. People who are contributing to EDD but don't moderate our support forums wouldn't have a clue why we're working to bring this back (since to them all the context on this ticket they have is its a bug). Was kinda explaining for them. Its something I've learned to start doing based on core trac tickets #blamenacin

**Comment by michaelbeil** [comment]
I like the way you're thinking @chriscct7.

**Comment by pippinsplugins** [comment]
I have seen very, very few instances of ajax not working now so I think we can consider not bringing this back at all.

Any recent tickets that anyone can think of?

**Comment by cklosowski** [comment]
I've not seen a rumbling of this in a while, I'm going to close and un-milestone this for now. If we see it coming back, we can look into addressing it.
