### ISSUE TITLE
Need filter for including custom variables in reporting graphs

### ISSUE THREAD

**Issue by sudar** [easydigitaldownloads/Easy-Digital-Downloads#3388]
We need a filter that would allow us to add custom variables in reporting graphs

https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/8e59c4a58cd635e229b34258a758fb6ba9025331/includes/admin/reporting/graphing.php#L722

**Comment by cklosowski** [comment]
shouldn't need a hook to make graphing work, we use this for Software Licensing and Commissions:
https://github.com/easydigitaldownloads/EDD-Commissions/blob/master/includes/reports.php

**Comment by pippinsplugins** [comment]
To elaborate on @cklosowski's comment, when working with custom graphs, it's better to just build your own using the `EDD_Graph` class than modify existing graphs.

**Comment by sudar** [comment]
@cklosowski @pippinsplugins 

Thanks for the pointers. I was able to achieve what I wanted to do without using this filter.
