### ISSUE TITLE
Add PayPal Language Option

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#339]
PayPal has an interesting behavior that causes it to display the PayPal page in the language of the seller's account. It would make most sense for the page to be displayed in the language of the buyer. I'm not sure if this is a PayPal bug directly, or just something it does.

The language of the checkout page can be forced like this:

``` php
function pw_edd_force_us_language( $paypal_args, $purchase_data ) {
    $paypal_args['lc'] = 'us';

    return $paypal_args;
}
add_filter('edd_paypal_redirect_args', 'pw_edd_force_us_language' );
```

I'm debating whether it would be a good idea to include a setting in Downloads > Settings > Payments for controlling this language. It would be off by default.

**Comment by Gregfrench77** [comment]
Hi guys, I have this typical issue. My Paypal account is in Thailand and my clients are like me french.
When my clients want to pay, they arrive on a thai paypal and they are escaping!
I use EDD that is great but I don't know where to make this modification. I'm lost.
Could you please help me to change that?
