### ISSUE TITLE
Improve UI for adding downloads to payments

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/Easy-Digital-Downloads#3390]
When manually adding new items to payments, if the first item in the dropdown is a variable product, you can't select the variable options without first selecting a different product then switching back to the first product. We should probably have a placeholder as the first item if possible.

[Screencast](http://cl.ly/0h2Y0D1h2b2D) of the issue.

**Comment by pippinsplugins** [comment]
One simple way to fix this is to simply change the first item to "Choose Download".

**Comment by pippinsplugins** [comment]
We removed the `Select a product` option in the product drop down field in #2965.

I'm going to re-add it and then adjust how the discounts save.

**Comment by pippinsplugins** [comment]
Ok ready for testing!

**Comment by cklosowski** [comment]
@pippinsplugins will test this out tonight or tomorrow.

**Comment by mindctrl** [comment]
@pippinsplugins this created a bug in the discount code edit screen. Download Requirements and Excluded Downloads don't get saved.

**Comment by pippinsplugins** [comment]
@mindctrl Hmm, it was working for me. I'll test again to replicate.

**Comment by pippinsplugins** [comment]
@mindctrl Could you test again now?

**Comment by mindctrl** [comment]
@pippinsplugins looks good now.

**Comment by pippinsplugins** [comment]
@cklosowski Ready for merge if you're happy.

**Comment by cklosowski** [comment]
Just a slight change to the CSS, when variable pricing dropdowns come in, things look odd being bottom aligned, moving to middle.

**Comment by cklosowski** [comment]
If you guys are good with this CSS update @pippinsplugins and @mindctrl I'll merge this into the release.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
I'm good with it.
