### ISSUE TITLE
Viewing a receipt from purchase history should have a different URL

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#3391]
Right now if you go through the purchase history to view a receipt it's loading the `purchase-confirmation` template, which if a user has Google Analytics Goal pages setup, it's triggering a goal completion unless they do some work to try and avoid it.

Also, it's just confusing to have the user end at a `Purchase Confirmation` page when it's really a `Purchase Receipt`

**Comment by ghost1227** [comment]
@cklosowski You doing this?

**Comment by pippinsplugins** [comment]
It's free game.

**Comment by cklosowski** [comment]
I'll do this, but it's slated for 2.5, not 2.4. If it goes along side #2304 I'll do it for 2.4. But until that changes, no one on core team should be working on 2.5 until 2.4 is shipped. Just a lot to do in a very little time.

**Comment by pippinsplugins** [comment]
Moved to 2.6 along with #https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/2304 and #3529

**Comment by pippinsplugins** [comment]
Too late in 2.6 cycle to get this.

**Comment by cklosowski** [comment]
Marking as a Dup of #2304 where we will tackle this.
