### ISSUE TITLE
easy-digital-downloads.php issue

### ISSUE THREAD

**Issue by bedakb** [easydigitaldownloads/Easy-Digital-Downloads#3392]
After Easy Digital Downloads activation, site goes down and I got this error:

Warning: require_once(/home/alb/public_html/wp-content/plugins/easy-digital-downloads/includes/process-download.php) [function.require-once]: failed to open stream: No such file or directory in /home/alb/public_html/wp-content/plugins/easy-digital-downloads/easy-digital-downloads.php on line 323

Fatal error: require_once() [function.require]: Failed opening required '/home/alb/public_html/wp-content/plugins/easy-digital-downloads/includes/process-download.php' (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/alb/public_html/wp-content/plugins/easy-digital-downloads/easy-digital-downloads.php on line 323

**Comment by chriscct7** [comment]
Please open a support ticket on easydigitaldownloads.com/support
