### ISSUE TITLE
Multiple tax rates with same id in taxes settings

### ISSUE THREAD

**Issue by bseddon** [easydigitaldownloads/Easy-Digital-Downloads#3395]
Suppose I have have three tax rates.  In the table the fields are indexed by a number representing the respective row.  Suppose now I delete the row with index '2'.  After this action I have two rows with indexes '1' and '3'.

Next suppose that I add a new rate.  The JavaScript code in admin-scripts.js responsible for adding the new row is the function that responds to the 'Add Tax Rate' button:

`$('#edd_add_tax_rate').on('click', function() {...});`

This function determines the index to assign to the new row by counting the existing rows.  In the scenario above, the index of the new row will be '3' which is the same as the index of the last row.

This does not cause an instant failure but it does seem to mean the form data sent to the server will contain only values for the second of the rows with an index of '3' which I think explains why some times I lose rate settings.

![image](https://cloud.githubusercontent.com/assets/1221824/7570742/58b01990-f80a-11e4-95e1-c4c35350610b.png)

**Comment by pippinsplugins** [comment]
Good catch!

**Comment by cklosowski** [comment]
We should reindex these on removing...we've done this in the price row functions for the downloads, I'll fix it up.
