### ISSUE TITLE
Downloads as Posts

### ISSUE THREAD

**Issue by rubycool** [easydigitaldownloads/Easy-Digital-Downloads#3396]
I'm having trouble after creating a new download. I want them to show as posts, but the only way I can do this is by creating a post and using the download shortcode. Any idea what is wrong? I'm using the Digital Store theme from the same company as easydigitaldownloads.

**Comment by pippinsplugins** [comment]
HI @rubycool,

Please go ahead and open this as a support ticket at https://easydigitaldownloads.com/support

Github is used for development tracking, not support.
