### ISSUE TITLE
Customer Page shows wrong total for Customer

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/Easy-Digital-Downloads#3404]
This is an error that is only happening with one of our customers. 

The customer has made 3 Payments. 
Payment 1 and Payment 3 were logged into the "Customer". 
Payment 2 was not logged into the "Customer". 

So I manually re-attached Payment 2 to the Customer on the "View Order Details" page for the Payment (as recommended in https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/3364)

Now all the 3 Payments are listed for the customer. However, it says the "Completed Sales" for that customer are only 2 and the "Lifetime Value" is only the value of Payment 2. 

![fzvj30xl0g](https://cloud.githubusercontent.com/assets/1638128/7636086/b906b2e8-fa32-11e4-9f95-e7fcb174b553.png)

**Comment by chriscct7** [comment]
How long ago was did you attach it? Customer totals are cached for 60 minutes for performance

**Comment by chriscct7** [comment]
@mintplugins Might want to install https://wordpress.org/plugins/transients-manager/ and delete the transient for that customer rather than waiting till it expires

**Comment by mintplugins** [comment]
It's been at least an hour since I did it now. But I will try deleting the transient manually as well. Do you happen to know the name of the transient I'd be looking for?

**Comment by pippinsplugins** [comment]
It's randomly generated. Try deleting all transients with an expiration./

**Comment by mintplugins** [comment]
@pippinsplugins @chriscct7 Okay I deleted all Transients with an expiration but the miscalculation on the Customer page still exists.

**Comment by pippinsplugins** [comment]
Are you sure it connected the payment?

**Comment by pippinsplugins** [comment]
Per [this comment](https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/3364#issuecomment-99164199), I believe this can be closed as invalid.
