### ISSUE TITLE
Improvements to Products Endpoint in API

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/Easy-Digital-Downloads#3407]
The products endpoint in the EDD API has quite a bit of duplicated code, and no places to filter the data returned for each product, making it impossible for extensions liked Software Licensing to return information in the Products Endpoint.

**Comment by pippinsplugins** [comment]
Anything else you'd like to change with it?

**Comment by cklosowski** [comment]
Not at this time, i'm good with it as is.
