### ISSUE TITLE
Move EDD_API off of template_redirect to improve performance

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#3410]
We could dramatically improve the performance of the EDD_API if we removed its dependence on `template_redirect`.

I'd love to see it use it's own, custom endpoint processing that runs during the `wp` hook.

This will have to be done carefully as a lot of the API currently depends on the presence of the `$wp_query` global, which I don't believe is available during `wp`.

**Comment by cklosowski** [comment]
@ghost1227 looks like you just changed the hook, if I'm reading @pippinsplugins issue correctly, we need some additional changes? Or did it all checkout?

**Comment by ghost1227** [comment]
It needed testing, he never had any issues i'm aware of with the initial commit, and all my tests worked perfectly.

**Comment by pippinsplugins** [comment]
@cklosowski I'm not sure if it needs more than that.

**Comment by cklosowski** [comment]
Cool I'll tag it for needs testing and run it through the endpoints I have in Postman.

**Comment by cklosowski** [comment]
Awesome, seems to still work just fine.

For those curious, this is my Postman collection (for use with the newest version of Postman)
https://www.getpostman.com/collections/da62bf3f6323d5cfae8b

Found another bug during the process, that's unrelated #3770

**Comment by cklosowski** [comment]
Weird issue with the merge, was showing a ton of other commits along with Dan's Moved to a 2nd branch and will merge in once CI completes. Leaving `Needs Testing` label for now, but all appears ok.

**Comment by ghost1227** [comment]
I know. I screwed up my fork. If you resubmitted a clean pull, this one's all yours.

**Comment by pippinsplugins** [comment]
When testing, let's do some comparisons on the request times to see how much of a change this makes.

**Comment by pippinsplugins** [comment]
Also need to test with following extensions that modify or add to API:
- [ ] commissions
- [ ] software licensing
- [ ] reviews
- [ ] recurring payments (release/2.4 branch)

**Comment by pippinsplugins** [comment]
All extensions work just fine here.

**Comment by pippinsplugins** [comment]
I tested this 11 times on each version (master branch vs release/2.5).

Request times for `release/2.5` using `wp` hook.

0.0273659229279
0.0276408195496
0.0351130962372
0.0283081531525
0.03102684021
0.028048992157
0.0273940563202
0.0269241333008
0.0269830226898
0.0301189422607
0.0272679328918

Avg: 0.1580959558

Request times for `master` using `template_redirect` hook.

0.0294721126556
0.0282800197601
0.0274350643158
0.0278131961823
0.0298891067505
0.0296399593353
0.029659986496
0.0276598930359
0.0280838012695
0.0272150039673
0.0278480052948
0.0276770591736

Avg: 0.03097029166

While local is not the best test, that's still almost a 2x improvement!

**Comment by pippinsplugins** [comment]
Whoops, I think I mixed those up. I've done it again with 20 tests on each version:

_template_redirect_

0.02920794487
0.029128074646
0.0283479690552
0.0277938842773
0.0285429954529
0.0282740592957
0.0324380397797
0.0280120372772
0.0269742012024
0.0273830890656
0.0276551246643
0.0275580883026
0.0281538963318
0.026734828949
0.0283827781677
0.0290858745575
0.0452950000763
0.0276999473572
0.029914855957
0.0276870727539

Avg: 0.0292134881

_wp_

0.0283570289612
0.0273690223694
0.0337290763855
0.0268881320953
0.0284929275513
0.0272388458252
0.0271260738373
0.0281090736389
0.0288209915161
0.0273370742798
0.0268058776855
0.0281949043274
0.030081987381
0.0279672145844
0.0278642177582
0.0375831127167
0.0441789627075
0.0289828777313
0.0299601554871
0.0272269248962

Avg: 0.02961572409

**Comment by pippinsplugins** [comment]
Nearly identical.

@cklosowski could you test it as well?

**Comment by cklosowski** [comment]
Sure which endpoint are you hitting? Also, I'm fine with this change regardless of the performance, as this would help avoid any other plugins/themes really messing with our API load.

**Comment by pippinsplugins** [comment]
/products/ with SL, Commissions, Reviews, and Recurring Payments activated.

**Comment by cklosowski** [comment]
k thanks, i'll test it out today

**Comment by cklosowski** [comment]
Yeah i'm happy with this, seeing an improvement for sure. Closing out.
