### ISSUE TITLE
Proof of Delivery Report

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#3413]
Starting in July, PayPal has implemented some big changes that affect EDD users.

Specifically, intangibles are now covered under Buyers protection, and are refundable and challengable for up to 180 days like tangible goods already are.

However, sellers will continue to be ineligible for Sellers Protection on non-tangible goods.

The important thing here is for the 180 challenge period, PayPal will now let people challenge that they did not receive a digital good, as a standard buyer's Item Not Received Purchase Protection Claim. This is a key issue for EDD (since we're a digital goods eCommerce plugin).

Here's what PayPal has advised to provide as proof of delivery in the amended section 11.4 of the PayPal terms of service effective date of July 1:
(and I quote)
""Proof of Delivery" for intangible or virtual items or services is documentation satisfactory to PayPal that the item or service was provided to the buyer such as proof of download including the date of fulfillment."

Right now, EDD tracks when someone downloads an item. 

What we should do, is on digital downloads, provide a link, on the edit order page for each order that says "Proof of Delivery Report" or something like that.

This should spit out a sample PDF or similar listing the dates and times of the downloads, and the ip address downloaded, and perhaps things like the key used to download the item

While PayPal is the one making the changes, there's no reason we can't make this report (which doesn't use PayPal specific data to make) available for all gateways.

As this is a compliance issue with an upcoming implementation date, we should get this done in 2.4 so users are ready once the changes start.

**Comment by pippinsplugins** [comment]
I don't agree that we need to provide a report for this, instead I feel we should just document how to retrieve the information necessary to send to PayPal.

All of the necessary information is already available.

**Comment by chriscct7** [comment]
I think it would be nice to just have all of that data in one place. How many times have we all had a challenged order and it would have been nice to just have a 1 button push solution to generating all the evidence you need for a dispute.

**Comment by pippinsplugins** [comment]
Nice, sure. Mandatory? Definitely not.

If we're going to do that, I'd prefer to see it as part of our Fraud Monitor extension (the one we use and are getting ready to expand). It only makes sense to be part of that in my opinion.

**Comment by chriscct7** [comment]
That's fine, I just think wherever it goes we should be ready for when the changes take into effect on PayPal, because that's our core gateway, on July 1.

**Comment by pippinsplugins** [comment]
Punting to 2.5. Most likely this will all happen as part of the fraud monitor extension anyhow, but will leave open for review.

**Comment by ThomasPe** [comment]
Regarding buyers protection, I think in order to support this EDD will need to collect a billing address to enable this, right? Is this currently planned?

**Comment by chriscct7** [comment]
Sellers Protection is the one EDD has to work on. Buyers protection is automatic. We don't need a billing address for that.

**Comment by pippinsplugins** [comment]
I believe this should be closed. We provide sufficient proof of file access / usage.
