### ISSUE TITLE
Sales log shows item price instead of sale price

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/Easy-Digital-Downloads#3418]
Go to Downloads > Reports > Logs, select Sales for the log type and select an item. The log shows the item price instead of the price the item was sold for. Example: buy item at a discount then view the log. The discounted sale price isn't shown.

**Comment by cklosowski** [comment]
yeah, I think there was a reason for this. I'd have to go back and look at it, maybe performance.

**Comment by yafred** [comment]
It works as designed 

https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/2.3.8/includes/admin/reporting/class-sales-logs-list-table.php#L303

However, I think there is an issue with the header: *Item Amount* may be misleading
If Item Price is what you want to display, may be *Item Price* would be a better header.

**Comment by mindctrl** [comment]
@yafred right, but I think a sales log should show the actual sale price, not the regular item price.

**Comment by yafred** [comment]
@mindctrl I see what you mean

In the line https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/2.3.8/includes/admin/reporting/class-sales-logs-list-table.php#L303

> $amount = isset( $item['item_price'] ) ? $item['item_price'] : $item['price'];

'item_price' is the price of the item
'price' is the price with discount (if any)

following would do what you are after

> $amount = isset( $item['price'] ) ? $item['price'] : $item['item_price'];

(It would be interesting to know what the purpose in the first place to avoid side effects if you change it)

**Comment by cklosowski** [comment]
I actually see benefit to showing both. Two columns:
`Item Price` and `Sale Price` would allow someone to quickly see how often items are being discoutned, etc.

**Comment by cklosowski** [comment]
The reasoning for this, there are some older versions of EDD that `price` isn't in existence, which is why it falls back to `item_price`.

**Comment by cklosowski** [comment]
Here's a real-world use case...like when a Software Licensing renewal goes through:
![screen shot 2015-09-17 at 4 57 41 pm](https://cloud.githubusercontent.com/assets/1390124/9948999/7242f6c6-5d5d-11e5-9d89-dd2554efba08.png)

**Comment by cklosowski** [comment]
Or here is one with a disount code appiled to a single purchase record.
![screen shot 2015-09-17 at 5 04 41 pm](https://cloud.githubusercontent.com/assets/1390124/9949073/3800b718-5d5e-11e5-9262-7d12c4c84e39.png)

**Comment by pippinsplugins** [comment]
+:1: to showing both values.

**Comment by pippinsplugins** [comment]
@mindctrl Could you test @cklosowski's PR?

**Comment by mindctrl** [comment]
When purchasing mulitple quantities of an item, the Sale Amount reflects the order total for that item on each one.

![image](https://cloud.githubusercontent.com/assets/1254870/9970403/ee33d852-5e22-11e5-927f-a753ab88a24e.png)

If you're just viewing that log, you'd think the total sale amount was $160, but it was $40.

**Comment by mindctrl** [comment]
To clarify, no discount was applied to that purchase. Might be separate issue? Otherwise, everything else looks good.

**Comment by mindctrl** [comment]
Multiple quantities with discount applied:
![image](https://cloud.githubusercontent.com/assets/1254870/9970555/c49948a0-5e23-11e5-8159-7da9e2c9e24e.png)

I bought 2 x $10 = $20, with a 50% discount for a grand total of $10. The line items should show $5 each?

**Comment by pippinsplugins** [comment]
Maybe we should show all of the following:

- subtotal (item price)
- discount
- taxes
- total

All of that information is available. Might as well show it now.

**Comment by pippinsplugins** [comment]
Discount and taxes would need to be divided by the quantity.

**Comment by cklosowski** [comment]
I'm not sure we need all those columns. I think we just need to take the price and divide by quantity, that should take care of it. Showing too much here could get REALLY overwhelming, especially on smaller screens.

**Comment by cklosowski** [comment]
![screen shot 2015-09-25 at 12 51 46 am](https://cloud.githubusercontent.com/assets/1390124/10095576/a5f1b814-631f-11e5-9152-615f43ec9283.png)

**Comment by pippinsplugins** [comment]
That looks correct to me.

**Comment by mindctrl** [comment]
@cklosowski looks good here.

**Comment by pippinsplugins** [comment]
Everything looks great.
