### ISSUE TITLE
Slashes added to customer name in Customer Details editor

### ISSUE THREAD

**Issue by zackkatz** [easydigitaldownloads/Easy-Digital-Downloads#3420]
When editing a customer with an apostrophe in their name, slashes are added to the name.

![before](https://cloud.githubusercontent.com/assets/870979/7710779/4e32f0c2-fe23-11e4-8f4b-cf59549481ed.png)

![after](https://cloud.githubusercontent.com/assets/870979/7710778/4e1df00a-fe23-11e4-9214-0a2da3416e8c.png)

**Comment by pippinsplugins** [comment]
Thanks for the heads up!
