### ISSUE TITLE
Set Download post type labels for Featured Images

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#3422]
In WordPress 4.3, post types will support custom labels for featured images: https://core.trac.wordpress.org/ticket/19257#comment:14

Let's hop on this right away and set it to `Use as Download Image`, etc. We should use the get label functions here to properly respect sites that have changed the labels of the downloads post type.

**Comment by pippinsplugins** [comment]
This was approved for WP 4.3 and has been merged into trunk.

**Comment by pippinsplugins** [comment]
Definitely doing this now that 4.3 is out and this was indeed included.

**Comment by pippinsplugins** [comment]
@SDavisMedia want to tackle this one?

**Comment by SDavisMedia** [comment]
Absolutely.

**Comment by SDavisMedia** [comment]
@pippinsplugins Should be all good here. Testing with my own labels and they adjust fine.

**Comment by pippinsplugins** [comment]
@SDavisMedia could you go ahead and open the PR?

**Comment by SDavisMedia** [comment]
Done for `release/2.5`.

**Comment by pippinsplugins** [comment]
Excellent, thanks!

**Comment by SDavisMedia** [comment]
Once merged, we've gotta remember to update the doc. http://docs.easydigitaldownloads.com/article/273-modify-the-download-post-type-admin-labels

**Comment by topher1kenobe** [comment]
Doc updated, but not published until 2.5 drops

**Comment by pippinsplugins** [comment]
:+1:
