### ISSUE TITLE
"Apply to whole country" tax setting not saved when adding country

### ISSUE THREAD

**Issue by dmgawel** [easydigitaldownloads/Easy-Digital-Downloads#3425]
**Bug description**
"Apply to whole country" tax setting is not saved when adding a new tax rate.

**How to reproduce bug?**
Go to Plugin Settings -> Taxes. Add a new tax rate using "Add Tax Rate" button. Select country and enter some rate. Check "Apply to whole country". Save changes. After refresh "Apply to whole country" for created rate is disabled. You have to check it again and save.

**Plugin version**
2.3.8

**Comment by pippinsplugins** [comment]
I've just replicated this.

**Comment by cklosowski** [comment]
The issue is an index is not being applied correctly in the `.clone` in the jQuery, should have a fix shortly.
