### ISSUE TITLE
Add hooks to allow email address to be used for log in form plugins

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#3429]
We see tickets about this at least once a month or so. It'd be nice to support.

**Comment by chriscct7** [comment]
I think rather than us adding the ability to do this in core, we should pick a couple plugins that do it in the repo, and add the hooks needed to work. Allowing an email address to be used as the username is a security risk

**Comment by pippinsplugins** [comment]
I'm not opposed to that.

**Comment by chriscct7** [comment]
This should apply to other login forms, not just the checkout one

**Comment by pippinsplugins** [comment]
Yes, all of them.

**Comment by chriscct7** [comment]
^ That was just to clarify the title change

**Comment by ghost1227** [comment]
Any thoughts on which one/ones to support? Or write our own?

**Comment by chriscct7** [comment]
I'd say the top 5 by downloads. I feel like those who want to do this don't want 2 plugins for the same thing.

**Comment by cklosowski** [comment]
So I just tested this with the EDD Profile Editor shotcode, and I can login with the email address of a user just fine.

Is this issue even necessary anymore?

**Comment by SDavisMedia** [comment]
I actually can't replicate this either. I've tried the profile editor, the login shortcode, and the checkout login form. They all accept email address instead of username.

**Comment by cklosowski** [comment]
Thanks @SDavisMedia , going to close this out and remove it from the milestone then, since it appears we're all good.
