### ISSUE TITLE
Trashed downloads can be purchased with custom add to cart links

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#3431]
If a download is not published, we prevent the add to cart buttons from being shown, but we're not actually preventing them from being added to the cart, which means custom add to cart links still work.

https://easydigitaldownloads.com/support/topic/trashed-downloads-being-purchased/

**Comment by sumobi** [comment]
Looks like this issue is back, customer is on v2.5.11 and they have a buy button on their sales page that allows a user to purchase a trashed download: 

https://secure.helpscout.net/conversation/190346712/31800/?folderId=180506

**Comment by pippinsplugins** [comment]
@sumobi you didn't do it while logged in as an admin did you? That would be permitted.

**Comment by sumobi** [comment]
@pippinsplugins Ahh is that why. I didn't test myself, the customer kept purchasing the trashed download from their sales page which had a purchase link shortcode on it. Meanwhile, I was purchasing the correct download from the download page. 

What would be a reason to allow an admin to purchase a trashed download? I don't think this should be allowed. In my case, it lead to hours of trying to find a non-existent bug.

**Comment by pippinsplugins** [comment]
The main reason we support it is for allowing admins to purchase draft and private products. Logic here:
```php
function edd_add_to_cart( $download_id, $options = array() ) {
	$download = get_post( $download_id );

	if( 'download' != $download->post_type )
		return; // Not a download product

	if ( ! current_user_can( 'edit_post', $download->ID ) && $download->post_status != 'publish' ) {
		return; // Do not allow draft/pending to be purchased if can't edit. Fixes #1056
	}
...
```

**Comment by sumobi** [comment]
In that case I propose we modify the code to disallow trashed downloads. Private and draft downloads I can understand, that's useful. Trashed downloads are ones an admin simply doesn't want anymore. Would you agree?

**Comment by cklosowski** [comment]
I think I agree here. 'Trashed' is a status I wouldn't imagine an admin needing to purchase. `Draft`, `Private`, and `Pending` I could see. but not `Trashed`.

**Comment by pippinsplugins** [comment]
I agree, allowing `trashed` is silly.

**Comment by pippinsplugins** [comment]
This has been fixed through the `can_purchase()` method of `EDD_Download`.
