### ISSUE TITLE
User ID marked as -1 for payment with same email, but different other data

### ISSUE THREAD

**Issue by bizzthemes** [easydigitaldownloads/easy-digital-downloads#3437]
Recently, a bug surfaced, where user ID for payments with same email, but different other data gets stamped as -1 and doesn't get existing user ID per email assigned. In admin, this is marked as guest payment, but this "guest" gets user id -1 assigned, whereas it should get ID from existing user with same email address.

Check this:

edd_get_payment_user_id( $payment_id ); // returns -1

**Comment by chriscct7** [comment]
There doesn't appear to be a bug here. edd_get_payment_user_id returns -1, which is user id of a guest user in EDD when the payment isn't attached to a customer. If they didn't login, regardless of the fact they have an account on your site with the same email, that's a guest purchase, and EDD treats it as such.

**Comment by bizzthemes** [comment]
This is definitely a bug. When user goes to see the purchase history in his account, he cannot see anything for purchase, where he was marked as guest.

**Comment by chriscct7** [comment]
No, its doing exactly what it's designed to do. If a user is not logged in while purchasing a product, that is a guest purchase. Ergo when they login to their account it will not show up because it is a guest purchase. I think the only thing that needs to be fixed here is that the transaction should not show for the logged in user, as it was a guest purchase account. If you want to force users to login, and thus force tie payments to accounts, you can disable the guest checkout feature on the settings panel

**Comment by bizzthemes** [comment]
Say what you want, but I'll call it a bug. Why aren't other purchases marked as "guest", even though registration process is the same (not logged in) - only marked as guest when user data submitted on second purchase is different from first one and email is the same. Customer details are shared in admin and shown correctly, but not in the front-end, where edd_get_payment_user_id( $payment_id ); returns -1.

**Comment by pippinsplugins** [comment]
There is a potential issue here, but it's not with the `edd_get_payment_user_id()` function. The issue you're eluding to, @bizzthemes, is that the payment did not get connected to the user account when it should have.

Are you seeing this with new purchases that are coming through or existing purchases that were there before the upgrade to EDD 2.3?

**Comment by bizzthemes** [comment]
Issue was not present before 2.3. Thanks @pippinsplugins for clarification. I only used `edd_get_payment_user_id()` to highlight the issue.

> the payment did not get connected to the user account when it should have.

Exactly. Why mark the user with ID -1, when email is the same. Perhaps it would be great to prompt user to login, when they try to register with email address that already exists.

**Comment by pippinsplugins** [comment]
@bizzthemes You didn't answer my question. Is this happening with new purchase records or existing ones only?

**Comment by bizzthemes** [comment]
New ones.

**Comment by pippinsplugins** [comment]
Does a customer record exist in Downloads > Customers for the new email you're using?

**Comment by bizzthemes** [comment]
yes

**Comment by pippinsplugins** [comment]
Can you show me a `print_r( get_post_custom( $payment_id ) )` for each?

**Comment by mj2000** [comment]
The problem also occurs when user buying and is registred by EDD Auto Register (I didn't test without it) and than when status is changed manually. User on purchase list is changed to Guest.

**Comment by pippinsplugins** [comment]
I'm not sure if this still happens but I've milestoned it to ensure we review it further.

**Comment by pippinsplugins** [comment]
Having done numerous tests recently with the Recurring Payments plugin and the Auto Register plugin, I'm confident this issue is resolved. If you see it again, please re-open.
