### ISSUE TITLE
Customer Profile - Lifetime value doesn't reflect subscription payments.

### ISSUE THREAD

**Issue by danieliser** [easydigitaldownloads/Easy-Digital-Downloads#3462]
Have several users on subscriptions using recurring payments extension. Their profiles show only the initial purchase for lifetime value opposed to the total of all payments made.

**Comment by chriscct7** [comment]
This should be on the recurring payments extension as this will be custom to that extension. Moving it there.

**Comment by danieliser** [comment]
@chriscct7 - Shouldn't it instead be pulled from a meta field for the customer similar to the download total sales meta stat?

In which case it wouldn't be since that meta would simply be a total of all payments made by the customer. I don't think it should be reliant on the extension as it's simply a total of all payments. Seems like any extension that had custom payments would need to create a patch, opposed to the core simply calling that stat from a different method. Make sense?

**Comment by pippinsplugins** [comment]
It will pull from the meta field, but it's EDD Recurring that needs to increase the value in that meta field.

**Comment by danieliser** [comment]
Ahh, figured that since EDD recurring created a payment, that the insert_payment would be the method that increased the customer meta as part of its process. Seems like the best place for it no? Abstract it into the core methods so that extensions wouldn't have to manage it separately?

**Comment by pippinsplugins** [comment]
It happens when the payment is marked as complete. Subscription payments don't get marked as complete, they get marked as a subscription.

Any extension that creates `complete` payments will automatically increment stats.

**Comment by danieliser** [comment]
Gotcha. Seems though like subscription shouldn't be the status, but rather a tag of sorts, since it could also fail, be denied, completed, pending etc. No?

**Comment by pippinsplugins** [comment]
I don't recall exactly why it was done that way, but it was :)
