### ISSUE TITLE
Default price ID not being selected on front end reliably

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#3463]
The price selected as the default is not always being selected on the front end. You can see this live on the EDD site: 

https://easydigitaldownloads.com/downloads/checkout-fields-manager/

![screen shot 2015-05-29 at 5 04 06 pm](https://cloud.githubusercontent.com/assets/1034109/7893559/bb6c8dac-0624-11e5-9f63-f49792461923.png)

Related https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/2958 and https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/2874

**Comment by mindctrl** [comment]
In the case of the EDD site, I think it's just a JS issue where the `selected` class isn't being added to the parent label. https://github.com/easydigitaldownloads/EDD-Site/blob/81635e8f4563599ef205cf68f5ab0c87f8e54a75/js/dev/theme.js#L136

The input is actually checked.

![screenshot](http://f.cl.ly/items/3I3I3e1b3P0g062i332E/Image%202015-05-29%20at%207.51.36%20PM.png)
