### ISSUE TITLE
New EDD settings styles feedback

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/Easy-Digital-Downloads#3467]
Sorry I didn't catch these before they went out. I would have given some feedback.

First, I think the labels are way too light. It'll look fine in a pic like [this](http://glui.me/?i=wuln8v7o2icdt5k/2015-06-01_at_11.46_AM.png/) but when the page is a sea of light gray, it's hard to scan. This is what the Extensions tab looks like in the settings.

Secondly, WordPress' core `.description` class already attempted to handle this kind of "secondary" styling but our updates didn't do anything to adjust that. So we end up with [this](http://glui.me/?i=qmqvb669jh0m4lb/2015-06-01_at_11.48_AM.png/). The order of importance is confusing there.

If we want the labels lighter, I don't think we should go any lighter than `#888`. Even then, that's still lighter than WP's descriptions at `#666`. 

Lastly, the Section Titles are the scan points, not the settings themselves. One should be able to scroll the page and be able to spot section titles so they know where they are. Being lighter than the setting labels is backwards, in my opinion. Even the fact that they're in italics is backwards considering they're the same size as the setting titles. They should at least be bigger if they are going to be lighter and in italics. See <a href="http://glui.me/?i=s7gkbmhcn3jqy89/2015-06-01_at_11.53_AM.png/">here</a>.

I do agree that the settings pages were becoming hard to read/scan. But I think the section titles should have been the focus, and making them stand out a little more.

**Comment by pippinsplugins** [comment]
Let's tweak them some more for 2.4.

I agree with @SDavisMedia

**Comment by ghost1227** [comment]
This (indirectly) also goes back to this behemoth: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/1960

**Comment by pippinsplugins** [comment]
@ghost1227 Which thankfully just had some super awesome work on it :D

**Comment by sumobi** [comment]
:+1: to all of the above

**Comment by cklosowski** [comment]
This a little better?
Old:
![image](https://cloud.githubusercontent.com/assets/1390124/8171904/9282e2e8-1370-11e5-8342-818a08a39812.png)


New:
![image](https://cloud.githubusercontent.com/assets/1390124/8171898/7dbf171e-1370-11e5-99d7-1b43a65043a6.png)

**Comment by pippinsplugins** [comment]
Much better.

**Comment by SDavisMedia** [comment]
Definitely much better but I still have some beef with this. [The change](https://github.com/easydigitaldownloads/Easy-Digital-Downloads/commit/37bba16ffce47347b1be1c7ff04aad9f67cb4047) actually introduced new markup to the settings table, specifically EDD's default section titles. Now there's a host of extensions adding sections to the Extensions tab and of course, the section titles don't have the markup. That's inconsistency in a single tabbed interface. Huge deal? No. But change wasn't that pressing to begin with.

**Comment by pippinsplugins** [comment]
@SDavisMedia that's a good point. I thinking we should consider reverting the change completely.

**Comment by SDavisMedia** [comment]
I agree 100%.

**Comment by pippinsplugins** [comment]
@cklosowski any objections?

**Comment by cklosowski** [comment]
@Pippinsplugins. Nope. Revert is fine by me

**Comment by pippinsplugins** [comment]
Reverted:
![screen shot 2015-06-17 at 9 34 38 am](https://cloud.githubusercontent.com/assets/1034109/8209709/1d11dbbc-14d4-11e5-864f-97b67a6693c0.png)

**Comment by cklosowski** [comment]
Reverted in 2.4 release, but punting to 2.4.2

**Comment by SDavisMedia** [comment]
@pippinsplugins @cklosowski Few things to look at here. Labels are the same style as WP core descriptions. They all start on a new line with the exception of checkboxes and text fields with the `small-text` class. Section titles are bigger and italicized (pure but generic CSS... not markup changes).

![screen shot 2015-06-27 at 2 25 17 am](https://cloud.githubusercontent.com/assets/2359131/8390982/55414e30-1c74-11e5-942e-b44ea02d3de6.png)

**Comment by ghost1227** [comment]
Dunno about anyone else, but I LOVE it!

**Comment by mindctrl** [comment]
I'd like to see us take a cue from core here. I don't think section titles should be italicized, and settings names shouldn't be bolded.

![image](https://cloud.githubusercontent.com/assets/1254870/8391877/f5219ed6-1ca2-11e5-8f87-51f1877dfccb.png)

**Comment by SDavisMedia** [comment]
@mindctrl Settings names are bold (font-weight: 600) in core already, or maybe I'm missing something.

**Comment by mindctrl** [comment]
@sdavismedia you're right. I had a plugin stomping on the settings name styles. Kind of a shame because I got used to it not being bold.

**Comment by pippinsplugins** [comment]
Loving the improvements

**Comment by cklosowski** [comment]
:+1: This looks much better, nice work.

**Comment by cklosowski** [comment]
Moving to 2.4 and merging.

**Comment by SDavisMedia** [comment]
:dancer:
