### ISSUE TITLE
Earnings reports with custom date ranges sometimes exclude selected dates

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/Easy-Digital-Downloads#3471]
If you run an earnings report with custom dates that go from one month to another, but are less than ~30 days total, the dates that cross into the second month are excluded from the report.

Example:
A report from May 29, 2015 - June 2, 2015 will only include up until May 31. June 1-2 will not be on the report. ![Screenshot](http://f.cl.ly/items/0D1z0J271V1j1m1x2A2f/Image%202015-06-03%20at%2011.20.35%20AM.png)

Using this example, this will happen until you set the start date to May 2 or earlier, at which point it includes the full range.

**Comment by pippinsplugins** [comment]
Definitely need to get this fixed

**Comment by mindctrl** [comment]
Possibly related, but can split off to another issue if needed.

I've seen several times, but can't reliably replicate, when selecting a custom range like `Sept 1 - Sept 10`, the range on the report is 1-9. The 10th, current day, doesn't show. Customer reported seeing the same same thing.

**Comment by pippinsplugins** [comment]
Sounds related to me.

**Comment by cklosowski** [comment]
ok digging into this...looks like we're getting some odd behavior on the 2nd month...

I did October 15th - November 15th. And got the dates:
October 15th - October 31st, and then November 15th.

In the data you see only this number of object pairs, and in the graph you see all the missing 'points' on the graph:
![screen shot 2015-11-11 at 12 14 49 pm](https://cloud.githubusercontent.com/assets/1390124/11100324/d4207720-886d-11e5-9988-57e0f8f86647.png)

**Comment by cklosowski** [comment]
@SDavisMedia @mindctrl @brashrebel could you guys test this out for me a bit? I've merged it into `release/2.5`

**Comment by SDavisMedia** [comment]
Not at all sure what you're saying here: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/3471#issuecomment-155882646

As for the original issue with the second month not showing, I was able to replicate on `master` and it is working properly on `release/2.5`.

I could *not* replicate the related issue where the last day of the custom range did not show.

**Comment by cklosowski** [comment]
@SDavisMedia Yeah tough to explain, but the gist:
The loop saw Month 1 and Month 2, then determined it needed loop through all the remaining days in month 1, and the chosen days in month 2. Only problem is, when it got done with the days in Month 1, it was going straight to the last day of month 2, instead of starting off at the first of the month :musical_keyboard:

**Comment by cklosowski** [comment]
@mindctrl does this work for you now?

**Comment by mindctrl** [comment]
@cklosowski looks good now. Thanks.
