### ISSUE TITLE
Remove edd_test_ajax_works function until reworked

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/Easy-Digital-Downloads#3475]
The `edd_test_ajax_works()` function causes some confusion as it doesn't consistently work correctly and gives false positives. At this time we cannot get it to be 100% accurate so let's remove it until we can rework it to be more accurate, as discussed in #3387

**Comment by cklosowski** [comment]
To be clear I don't think we need to fully rip out the code, just make it so we aren't running the test and showing the notice to the end user. That way we don't have to start from scratch.

**Comment by pippinsplugins** [comment]
:+1:
