### ISSUE TITLE
Pending Payments getting set to Abandoned before campaign complete 

### ISSUE THREAD

**Issue by mperriton** [easydigitaldownloads/Easy-Digital-Downloads#3479]
Hi there

is there a way to stop EDD from setting pending orders to abandoned after 7days? 

We have a scenario where we are using EDD on a crowdfunding site, and we have campaign contributors cards verified when they enter a pledge, which get saved as a pending payment.  The pending payment gets set to complete once the campaign has expired if the pledge total is reached and the card charged successfully.  In many cases, a campaign will run longer than 7 days, and we don't want these payments marked as abandoned until after the campaign has completed. 

any suggestions

regards
Maria Perriton

**Comment by pippinsplugins** [comment]
Maria,

Your pledges should be marked as `Preapproved` not as pending.

If you're using Stripe, this is an option you can enable in the Stripe settings.

If you're using PayPal Adaptive Payments, it can be enabled in settings.

If you;re using any other gateway, you'll likely need to get in touch with the gateway developer for assistance. If it's one of our official gateways, open a support ticket and we'll be happy to help: https://easydigitaldownloads.com/support

Note, Github is for development tracking only. For support inquiries, please use the support page linked above. Thanks!
