### ISSUE TITLE
Trying to purchase a download through PayPal with no title results in empty cart

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#3481]
If you create a product but do NOT give it a title, like this https://cloudup.com/ccBLpddpZa9, and then try to purchase it through PayPal, PayPal will display a "Your cart is empty" error message:

![screen shot 2015-06-05 at 1 38 03 pm](https://cloud.githubusercontent.com/assets/1034109/8012586/5c3d5e10-0b88-11e5-8db8-d2627d078e6f.png)

We should set the PayPal `item_name` field to the download ID if no title is present.

**Comment by pippinsplugins** [comment]
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/3481

**Comment by PareshRadadiya** [comment]
#3596

**Comment by cklosowski** [comment]
Once merged in, i'll write up a unit test for the new function added in #3596

**Comment by pippinsplugins** [comment]
Re-opening in order to write unit tests.

**Comment by pippinsplugins** [comment]
This is throwing an undefined index of `name` on checkout now: 

Notice: Undefined index: name in /Users/pippin/Sites/edd/wp-content/plugins/easy-digital-downloads/includes/cart/functions.php on line 576
