### ISSUE TITLE
Earnings report for last week becomes the last week of the last month 

### ISSUE THREAD

**Issue by michaelbeil** [easydigitaldownloads/Easy-Digital-Downloads#3482]
Today is June 5, 2015, and it happens to be a mixed week where the end of May was at the beginning of the week (if you are a Sun-Sat kinda person, however EDD respects the Mon-Sun week, so it's mostly irrelevant). When I run a report on last week's earnings, I receive the last week in April (24-30) as a result, instead of the expected result May 25-31. 

![screen shot 2015-06-05 at 2 15 06 pm](https://cloud.githubusercontent.com/assets/4752949/8013461/049ea02c-0b8f-11e5-9840-e581b291df2e.png)
 
Related: #3471

**Comment by pippinsplugins** [comment]
I'm going to test the PR on November 2nd to confirm it's working as expected.

**Comment by pippinsplugins** [comment]
I've just confirmed that this is working properly now so I'm merging and closing.

**Comment by cklosowski** [comment]
WOOT!
