### ISSUE TITLE
Add generic way to prefil checkout fields from session data

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#3485]
We need to have a way to prefill checkout fields from session data to help facilitate plugins that need to set up customer details before reaching the checkout screen.

This is necessary to complete #3223

**Comment by pippinsplugins** [comment]
When logged in, user details aren't always getting pre-filled.

**Comment by mindctrl** [comment]
Getting undefined variables for the address fields. Fails here as it's never empty. https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/8f4ff659e4a6460cc2ac56932430e718e8376544/includes/checkout/template.php#L303

**Comment by pippinsplugins** [comment]
@mindctrl Could you test it again now?
