### ISSUE TITLE
Remove inline styles from [downloads] shortcode

### ISSUE THREAD

**Issue by sumobi** [easydigitaldownloads/Easy-Digital-Downloads#3489]
I propose we remove the inline styles from the [downloads] shortcode. 

By that I mean the `style="width: <?php echo $column_width; ?>; float: left;">` here:

https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/shortcodes.php#L489

CSS should be kept to stylesheets. For theme developers it means filtering the entire shortcode just to remove the hardcoded styles. I for one do not want to use `float: left`. Yes, you can override the float and width properties but I believe it shouldn't be there in the first place and means adding more CSS.

We don't need the `width` CSS rule either either. A CSS class is already applied to the wrapper div which lists the column count so this can be used: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/shortcodes.php#L484-L486

Compatibility wise it shouldn't affect many themes. Since the float is just moved to the stylesheet, and the columns all have the same widths, I don't see many layouts breaking. The only layouts I can think that will break are those who have filtered the entire shortcode (I know I did in Shop Front) using the `downloads_shortcode` filter:
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/shortcodes.php#L567

PR coming soon to show how I think we should tackle this, we can remove a bunch of code and it will look exactly the same.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by SDavisMedia** [comment]
Nice. Love this.

**Comment by pippinsplugins** [comment]
If we move inline to edd.css, the columns will break for anyone that has copied edd.css to their theme.

**Comment by sumobi** [comment]
We could include a compatibility function inside EDD that detects if a theme is using the EDD stylesheet within the theme. If this is the case we can inject a couple of lines of CSS into the head for pages that use the [downloads] shortcode. We'd document this in the release notes and eventually remove the injected CSS after 2-3 major revisions, giving theme developers plenty of time to update their CSS file.

**Comment by SDavisMedia** [comment]
Unfortunately, I don't think it's the theme developers we have to worry about. I see a lot of users overriding the CSS file from their themes for a couple of reasons:

1) Because they don't really understand CSS, so they think it makes more sense to do it this way than from their own custom CSS.

2) They're more comfortable with tweaking what's already there than they are writing selectors from scratch to override.

**Comment by sumobi** [comment]
@SDavisMedia Good point, forgot about that, though I still think the above could fix it. We can just leave it in, or take it out at a later date. New blog post idea: educating customers on the best way to make small CSS tweaks

**Comment by sumobi** [comment]
The main benefit for this is the introduction of flexbox which we can all use now. Theme developers won't be able to use flexbox and make some nice layouts for downloads, unless the inline CSS is gone (there's also those pesky clearing divs which we'll tackle later). The only solution is to filter the downloads shortcode which equates to more code to maintain, should the downloads shortcode ever change.

**Comment by SDavisMedia** [comment]
I agree totally. Vendd was a challenge for those reasons and the amount of CSS I used just to "agree with" the CSS that was already inline (but tweak it just a bit) was ridiculous. I think it's worth the blog post, make a docs series (I already have plans to write some) and the code approach you suggested.

**Comment by sumobi** [comment]
:+1: Flexbox is super easy to implement, inline CSS makes it super hard to override. EASY digital downloads. That is all :)

**Comment by pippinsplugins** [comment]
:)

**Comment by spencerfinnell** [comment]
The detection method doesn't seem horrible to me. A filter could be added for a couple of versions so authors could update their edd.css file and then stop the automatic output and then over time just phase it out completely.

**Comment by sumobi** [comment]
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/pull/3747

**Comment by pippinsplugins** [comment]
@sumobi I really like how you've done this in #3747

**Comment by sumobi** [comment]
@pippinsplugins thanks

**Comment by pippinsplugins** [comment]
PR here https://github.com/easydigitaldownloads/Easy-Digital-Downloads/pull/3747

**Comment by SDavisMedia** [comment]
This is looking good to me. Vendd seems to work perfectly with all of the support column options. Very nice, @sumobi! :+1:

**Comment by sumobi** [comment]
@SDavisMedia Woot!

**Comment by pippinsplugins** [comment]
Awesome.

**Comment by pippinsplugins** [comment]
@SDavisMedia Did you happen to test with any other themes?

**Comment by SDavisMedia** [comment]
@pippinsplugins Absolutely. I checked through several. But I just decided to check more and realized Digital Store removes the default EDD stylesheet for some reason. 

Simple solution would be to just add the new CSS to Digital Store stylesheet. I'll add it for an update.

**Comment by SDavisMedia** [comment]
All good now. This really should not affect many themes as most of them left the default shortcode display alone anyway. Vendd is one of the few that actually uses the shortcode instead of making custom grid displays.

**Comment by pippinsplugins** [comment]
Awesome. I'll test again on my end then merge and close.

**Comment by pippinsplugins** [comment]
@sumobi Works perfectly. Love it.

**Comment by sumobi** [comment]
Yeehawwww
