### ISSUE TITLE
Add primary columns to WP_List_Tables

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#3492]
WP core is working on responsive list tables: https://core.trac.wordpress.org/ticket/32395#comment:25

It should work out of the box but it is better if we define a [primary column](https://core.trac.wordpress.org/ticket/25408).

**Comment by pippinsplugins** [comment]
@mindctrl or @topher1kenobe one of you want to tackle this? I can help if you're unsure what to do from the ticket above.

**Comment by mindctrl** [comment]
I'll take it.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
@mindctrl Think you could hit this up next week?

**Comment by mindctrl** [comment]
@pippinsplugins :+1:
