### ISSUE TITLE
Right-click "Save Link As" in Firefox on WPEngine results in files named "index.php"

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#3498]
There's a strange bug that results in files getting named "index.php".

It appears to only happen in Firefox when customers right-click and choose "Save Link As". It also appears to be limited to WPEngine, or perhaps NGinx.

Ticket that reported the issue: https://secure.helpscout.net/conversation/96429143/10523/

**Comment by ankitrox** [comment]
I am having same issue, but my site is hosted on AWS EC2 instance. I tried to rename that index.php file to index.zip and surprisingly zip file was ok.

so only issue is extension of the file is getting changed.

**Comment by SDavisMedia** [comment]
Think this is related? https://secure.helpscout.net/conversation/106380533/13238/

**Comment by pippinsplugins** [comment]
@SDavisMedia Very possibly.

**Comment by mindctrl** [comment]
Another one in Safari 9. https://secure.helpscout.net/conversation/136337769/20553/

**Comment by mindctrl** [comment]
Some additional info from customer:

> "I have discovered that if you click "Download Linked File" (and not "Download Linked File As..." this can be seen in one of my screenshots) the file downloads with the correct filename."

**Comment by akyusa01** [comment]
Here's another ticket: https://secure.helpscout.net/conversation/179645160/29659/

**Comment by cklosowski** [comment]
There isn't really a way around this. The browser simply looks at the path in the URL (of which ours is `index.php?...` so it's naming it what the file technically is. The only way to do this would be to name the endpoint the `.zip` file which isn't possible as it isn't a real file (to secure it).

**Comment by sunnyratilal** [comment]
I agree with @cklosowski - this is more of a browser/server issue than an issue on our end that we can fix.
