### ISSUE TITLE
Introduce credit card format helper functions

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/Easy-Digital-Downloads#3502]
Based off the information in #3499

**Comment by cklosowski** [comment]
There are some issues with the regex in the ones provided in #3499.
American Express can have 15 or 16 numbers
The Diners Club is failing validation on the test cards that Stripe offers as valid formats

Working through the changes now.

**Comment by benjaminprojas** [comment]
@cklosowski just so you know, I pulled the regex directly from the jquery.creditCardValidator.js file.  If the regex is not working here, it may not work there either...

**Comment by cklosowski** [comment]
Yeah I figured it was coming from a source. I went and grabbed a bunch of card formats for the types you had listed and tweaked a couple I think JCB and DIner's club were the only ones that needed a slight change.

**Comment by cklosowski** [comment]
Credit cards are wicket tricky

**Comment by benjaminprojas** [comment]
@cklosowski https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/assets/js/jquery.creditCardValidator.js#L16 
Totally agree on them being tricky...

**Comment by cklosowski** [comment]
@pippinsplugins ready for another check, and merging if you are good with it.

**Comment by pippinsplugins** [comment]
Merged!
