### ISSUE TITLE
Create EDD_Metabox base class

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#3506]
The `metabox.php` file is nearing a point where it's difficult to maintain with many functions and the order of the hooks/actions not necessarily in the same order.

@pippinsplugins and I have discussed possibly making a base class called `EDD_Download_Metabox` that would allow us to handle some of the validation configuration and registration of a metabox, but leave the details of the metabox up to an individual class to extend it. This would make editing and maintaining a specific metabox much easier as we only have to open a single file for the metabox we're looking to make changes to, instead of finding it in a 1000+ line file.

**Comment by pippinsplugins** [comment]
Closing in favor of #4781
