### ISSUE TITLE
Disable buy now buttons if multiple payment gateways are enabled

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#3516]
It doesn't make sense to support buy now buttons if multiple payment gateways are activated.

**Comment by chriscct7** [comment]
We have 3 options:
- Disable buy now
- Let user pick which gateway to use for buy now (which might not be a bad idea) given we're going to have 2 core gateways with buy now support
- Show multiple buy now buttons (like when you go to a site and they have a buy now with paypal, buy now with amazon and add to cart button.

**Comment by pippinsplugins** [comment]
Punting to 2.6. This isn't a tiny feature and we haven't had any recent tickets from this.

**Comment by mintplugins** [comment]
Customer Ticker regarding this here:
https://secure.helpscout.net/conversation/213683592/36044/?folderId=180499

**Comment by sunnyratilal** [comment]
@easydigitaldownloads/core-devs Could we vote on the best way forward with this please based on the three options @chriscct7 has provided.

My personal preference is option 1.

**Comment by pippinsplugins** [comment]
I vote option 1 at this time.

**Comment by SDavisMedia** [comment]
I'm with option 1 for now. Option 2 with a super sweet modal might be nice in the future.

**Comment by pippinsplugins** [comment]
>>>Will we be incorporating any note/message to admins to communicate that buy now buttons are disabled when they turn on that second gateway?

Instead of just hiding the settings, I think we should gray them out and provide a tooltip with an explanation of why they are disabled.
