### ISSUE TITLE
Generic Alerts HTML function

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#3521]
I think a useful enhancement would be a function you pass in a alert status (success,error, etc) and a message and the function would return the full HTML that can be used to make a full error. This way we don't have to hardcode the error HTML all over the place, and it works as a helper in case we want to make any future changes. I know its late, but it would be cool to do this in 2.3 along with the new error HTML so that way any extensions already updating to use the new classes can use the helper

**Comment by chriscct7** [comment]
So for example sending in "error" and "My error message" would return "<div class="edd_errors edd-alert edd-alert-error">My error message</div>". This would completely future proof any changes we want to do

**Comment by pippinsplugins** [comment]
Isn't this really the same as registering an error and then just calling `edd_print_errors()`?

**Comment by chriscct7** [comment]
No, this is much more basic. edd_print_errors only works if you want to show errors. What if, for example, an extension wishes to inject an edd formatted success message? The proposed function would take in a type (error/success/notice) and message and output the HTML for it. edd_print_errors could be rewritten to use it.

**Comment by chriscct7** [comment]
For example, right now FES (one of our extensions) uses javascript to inject error messages during form validation. Instead of FES hardcoding the format: ```<div class="edd_errors edd-alert edd-alert-error fes-form-field-error"><p class="edd_error">' + message + "</p></div>```, it would simply do ```edd_get_alert_html( 'error', $message )```, and thus regardless of whenever EDD changes the formatting on the error messages, FES would automatically be using the correct version,

**Comment by pippinsplugins** [comment]
Ah, I see.

I'm not sure I agree with the need for this. Why not just register an error and then use `edd_print_errors()`? They can be used exactly the same.

**Comment by chriscct7** [comment]
Because that can only be used to show error messages. What if you need to show a success message?

**Comment by cklosowski** [comment]
We updated the JS one to detect the type of message based off having success, error, warning, etc and change the class based off that. Maybe we could look into that and make it an ddd_print_messages, that helps with helping devs output messages.

**Comment by cklosowski** [comment]
Closing this as there hasn't been a real need for it. With adding the classes around everything that we did, if someone needs to display an error the classes exist for htem.
