### ISSUE TITLE
Add parameter to disable pagination for [download]

### ISSUE THREAD

**Issue by kiarashi** [easydigitaldownloads/easy-digital-downloads#3522]
If possible, please add an extra parameter inside the download shortcode that will either display the pagination or not. E.g. [download pagination=yes/no/false/true]

**Comment by cklosowski** [comment]
I think this could be a useful addition. i'll slate it for a future release.

**Comment by pippinsplugins** [comment]
I've updated the title to reflect the change.

**Comment by cklosowski** [comment]
This was completed in #3894 with EDD 2.5.7
