### ISSUE TITLE
Cart empty message when items shown in cart 

### ISSUE THREAD

**Issue by jameslaws** [easydigitaldownloads/easy-digital-downloads#3525]
We had a customer share this screencast: https://www.sugarsync.com/pf/D7578192_91741837_6174484

What I assume is happening is their session has expired or something so it's not registering that the items in the cart are actually there and it displays the cart is empty message. This is not intuitive for the customer however since the items are most definitely visibly in the cart.

In known cases, the customer, after much time and frustration, opens a new browser and is able to complete their transaction. My guess is that in large unknown numbers, the customer just leaves and the sale is loss.

Has anyone else experienced this?

**Comment by pippinsplugins** [comment]
Hmm, that's odd. Usually that would happen for one of two reasons:

1. The session has expired while on the checkout. This is unlikely unless he let it sit for 24 hours
2. The ajax requests are being made across protocol (https to http)

Do you have the whole site on SSL or just the checkout?

**Comment by jameslaws** [comment]
Whole site is on SSL.

**Comment by jameslaws** [comment]
I wouldn't say that this is reported frequently, but I wouldn't call it uncommon either. We hear about it several times every month. My bigger concern is about all the times we don't hear about it.

**Comment by pippinsplugins** [comment]
Have you been able to replicate it?

**Comment by pippinsplugins** [comment]
@jameslaws did this go away for good or is it still present?

**Comment by bhays** [comment]
I also have the same issue on a site with EDD. I have yet to duplicate the bug on my own, but from my client, I have heard many reports of users getting an empty cart upon submitting payment via checkout.

The site is served entirely over HTTPS.

As a test, I've recently implemented `define('EDD_USE_PHP_SESSIONS', false);` via wp-config, but I have yet to know if that's helped.

**Comment by cklosowski** [comment]
This is over 2 years old, and we have some extensive documentation on it. Any reports should look here first:
http://docs.easydigitaldownloads.com/article/185-shopping-cart-is-empty-at-checkout

If you still have problems, please use https://easydigitaldownloads.com/support.
