### ISSUE TITLE
Get customer purchases go wrong 

### ISSUE THREAD

**Issue by bighug** [easydigitaldownloads/Easy-Digital-Downloads#3527]
This is a huge bugs, when user update their email, then buy something new, the new order or new item was not listing in user purchased ( like functions edd_get_users_purchases ). I notice that you have a database upgrade by concat payment_ids in _edd_customers but this just fix old user's order. This still error with new purchase. Please check and fix this issue.

**Comment by chriscct7** [comment]
Duplicate of https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/3364
