### ISSUE TITLE
EDD always tracking

### ISSUE THREAD

**Issue by stephenharris** [easydigitaldownloads/Easy-Digital-Downloads#3530]
It seems since this commit: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/commit/e7ac73c76ce5648ca4357f3497303532787b9564 EDD is tracking all sites regardless of whether they have opted-in or not. 

`edd_get_option()` will always return a value so the `isset` check will always return true.

**Comment by chriscct7** [comment]
Good catch. Fixing

**Comment by chriscct7** [comment]
Solved in https://github.com/easydigitaldownloads/Easy-Digital-Downloads/commit/269147be5b3b468bcea63f83fa113b346967eb4a

**Comment by pippinsplugins** [comment]
Thanks for catching that!
