### ISSUE TITLE
Checkout Custom Fields showing twice

### ISSUE THREAD

**Issue by sunnyratilal** [easydigitaldownloads/Easy-Digital-Downloads#3536]
When a user has the Guest Checkout disabled and has Login and Registration forms both set to shown and they register custom fields using the tutorial [here](https://easydigitaldownloads.com/docs/custom-checkout-fields/): the fields are shown twice.

As shown in the screenshot below, `ASQ Section ID#` is shown on both forms.

This is due to the `edd_purchase_form_user_info` action being called twice. Once [here](https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/release/2.4/includes/checkout/template.php#L209) and second time [here](https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/release/2.4/includes/checkout/template.php#L500)

![](https://cldup.com/rwoU81FJAF.png)

It should only be shown in the `Personal Info` section.

**Comment by pippinsplugins** [comment]
@sunnyratilal I don't think this is a bug in core but rather an issue with the tutorial. Agree or disagree?

**Comment by pippinsplugins** [comment]
This was a bug in the tutorial, not core.
