### ISSUE TITLE
Add Biographical Info + Avatar inside the edd_profile_editor shortcode

### ISSUE THREAD

**Issue by kiarashi** [easydigitaldownloads/Easy-Digital-Downloads#3539]
If possible, please add an option so that customers can add/edit their Biographical Info + Avatar as well.

**Comment by chriscct7** [comment]
That doesn't really have anything to do with EDD's core project. As it wouldn't be used by enough ℅ of  our users closing. It would be better off as an extension

**Comment by kiarashi** [comment]
Actually it will be more of an Enhancement and I don't see why it can't be part of the core. It's also something that will be useful as I'm currently creating an author widget for both non-fes users and fes users alike. 

It's not much trouble either because only a few lines of code will be added. E.g.

edd/includes/shortcode on line 728

$biographical_info      = ( isset( $data['edd_biographical_info'] ) ? sanitize_text_field( $data['edd_biographical_info'] ) : '' );
$user_url      = ( isset( $data['edd_user_url'] ) ? sanitize_text_field( $data['edd_user_url'] ) : '' );

and inside the $userdata array:
'description'  => $biographical_info,
'user_url '	   => $user_url,

**Comment by kiarashi** [comment]
I happened to stumble upon a solution to add my code above without modifying the core. :)

**Comment by pippinsplugins** [comment]
Glad to hear it!
