### ISSUE TITLE
Add ability to sort Discounts

### ISSUE THREAD

**Issue by syedbalkhi** [easydigitaldownloads/Easy-Digital-Downloads#3544]
I see a lot of discussion related to discount in #3198 and #1427 

While those seem like more complex job, I have a simpler solution for time being that applies to those of us who're not using any mass coupon generator extension but still have say 50+ coupons.

It'd be nice to have sorting ability in ascending / descending order for each tag (i.e uses, start date, expiration date, status, etc).

This way, I can easily click on Uses and it'll show me the most used coupons at the top in descending order.

**Comment by pippinsplugins** [comment]
That'd be nice and easy to do, and helpful :+1:
