### ISSUE TITLE
post_status of logs connected to payments should match payment

### ISSUE THREAD

**Issue by ericnicolaas** [easydigitaldownloads/easy-digital-downloads#3549]
If you have a payment that has been completed, and you change it to pending, the `edd_log` records associated with that payment are not changed -- they remain with a `post_status` of `publish`. 

While I appreciate this is probably a rare circumstance (I do it regularly for testing purposes), it seems like the desired behaviour should be to have the `edd_log` status match whatever the `edd_payment` status is.

Thoughts? Happy to work on a PR if I have the time (releasing a new product this week, so a tad busy).

Cheers, 
Eric

**Comment by ericnicolaas** [comment]
I should add a quick note about where this becomes a problem: 

We support a fork of Astoundify's Crowdfunding plugin, which uses the `$edd_logs->get_connected_logs()` to fetch the number of purchases of a particular campaign (a.k.a. download). The problem is that this will count pending logs if the payment has been switched to pending. So it's a problem there, and in any other situation where people may want to obtain an accurate account of completed purchases of a particular download. 

Cheers, 
Eric

**Comment by pippinsplugins** [comment]
This is tricky.

If a payment is refunded, the log gets deleted.

If a payment is pending, it should not have any logs.

If a payment is `Preapproved`, it should have logs. Is that what you mean by pending?

**Comment by ericnicolaas** [comment]
Not quite. What I mean is that you have a payment that was completed, but has been reverted back to pending. Logs are kept as published.

**Comment by pippinsplugins** [comment]
Why would you revert a payment to pending?

**Comment by pippinsplugins** [comment]
(I don't disagree that logs should be updated, just curious on the use case)

**Comment by ericnicolaas** [comment]
I change statuses mostly to facilitate testing. 

In the Crowdfunding plugin, a few things are done on the transition of a payment to or from publish or preapproval status (updating the backer count, updating a tally of the total amount of preapproved payments), so when there are problems with any of this, my hacky way of getting to the bottom is by transitioning payment states and `var_dump`ing all over the place.

I know that probably makes me an edge case. That said, if the option is there for people to revert payments from Complete to Pending (or any other Status to Status change), it makes sense to ensure that those transitions really do make the transition. I could also see these kinds of transitions being more common for people using Manual Purchases often. Example off the top of my head: Someone pays you with a cheque so you create a manual purchase and mark the payment as complete, but then the cheque bounces. 

I don't think a resolution for this needs to be super complex. The way I see it, `edd_undo_purchase_on_refund()` could be refactored to handle transitions to pending, refunded and cancelled (maybe revoked too?). Seems to me each of these would require the same things to happen: undo the download purchases, decrease store earnings, decrease customer value and purchase count, and delete the earnings transient. 

Cheers, 
Eric

**Comment by pippinsplugins** [comment]
I have not seen any new cases of this being an issue so am going to go ahead and close as wontfix.
