### ISSUE TITLE
Select Payment Method shown incorrectly when only one gateway is enabled

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#3551]
We've accidentally introduced a bug with the payment method selection.

When you only have one gateway enabled, there is not supposed to be a `Select Payment Method` option, but there is now:
![screen shot 2015-07-02 at 9 51 49 am](https://cloud.githubusercontent.com/assets/1034109/8479853/fdbfbedc-209f-11e5-8cf8-fda35f57f1d6.png)

Also, if the `Default Gateway` option is set to a non-enabled gateway, an empty radio button gets displayed and causes a notice:
```
NOTICE: wp-content/plugins/easy-digital-downloads/includes/gateways/functions.php:60 - Undefined index: paypal
require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/vendd/edd_templates/edd-checkout.php'), get_template_part, locate_template, load_template, require('/themes/vendd/content/content-checkout.php'), the_content, apply_filters('the_content'), call_user_func_array, do_shortcode, preg_replace_callback, do_shortcode_tag, call_user_func, edd_checkout_form_shortcode, edd_checkout_form, do_action('edd_payment_mode_select'), call_user_func_array, edd_payment_mode_select, edd_get_enabled_payment_gateways
```

![screen shot 2015-07-02 at 9 52 06 am](https://cloud.githubusercontent.com/assets/1034109/8479859/04f9b8e2-20a0-11e5-81ea-90d10ab4bade.png)

**Comment by pippinsplugins** [comment]
I suspect this was caused by changes introduced in https://github.com/easydigitaldownloads/Easy-Digital-Downloads/commit/0e1276d766b7d6b2460efbdf1073b4081d0c7fa9

**Comment by mindctrl** [comment]
Seeing an undefined index on this when the default gateway is something that's not enabled, which I set accidentally when making changes:
![image](https://cloud.githubusercontent.com/assets/1254870/8480132/17982880-20aa-11e5-8550-c28fceb5d131.png)

Settings:
![image](https://cloud.githubusercontent.com/assets/1254870/8480183/36f8e20a-20aa-11e5-9121-32b62050669c.png)

**Comment by pippinsplugins** [comment]
@mindctrl After pulling the changes? I'm not seeing a notice any more.

**Comment by mindctrl** [comment]
@pippinsplugins yes, and just now I switched the default gateway to one that is enabled, then back again to one that isn't, and the empty radio showed back up. Testing another site to make sure. Can you test this again to make sure?

**Comment by mindctrl** [comment]
Confirmed on another site, but only under certain conditions. If PayPal Standard is the default gateway, but it's not enabled, the empty radio shows up and the undefined index: paypal shows up.
![image](https://cloud.githubusercontent.com/assets/1254870/8480525/36dcebfc-20ac-11e5-97a2-0b96ef1a1e0c.png)

Admittedly an edge case, and I found it by mistake, but it's still there.

**Comment by pippinsplugins** [comment]
Kk testing further shortly.

**Comment by pippinsplugins** [comment]
@mindctrl test `isse/3551` again?
