### ISSUE TITLE
Default gateway can be set to inactive gateway

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#3554]
Right now, you can have a gateway unchecked, and still select it as a default gateway. This leads to some issues in the code where we have to do a bunch of detecting on which ones are enabled, before we use the selected default as the default.

We should improve the gateway enabling interface to better meet the needs of users so that it's easier for them to quickly enable/disable gateways and not let them assign a default gateway to one that's disabled.

**Comment by cklosowski** [comment]
This became very evident in #3551

**Comment by sunnyratilal** [comment]
PR ready for testing

**Comment by sunnyratilal** [comment]
**To Test:**

1. Uncheck Amazon on the Payment Gateway settings
2. Set Amazon as the default gateway
3. A notice should show with the text `Amazon has been enabled as it was disabled but selected as the default gateway.`

**Comment by pippinsplugins** [comment]
PR looks good at first glance.

**Comment by pippinsplugins** [comment]
Actually  . . . I wonder if we should change this a bit.

Right now it automatically enables the gateway that gets selected if it's not already enabled. This could result in problems due to merchant account details not being entered.

I think it would be better to revert the Default Gateway to the first enabled gateway and then show a message saying the default cannot be set to that since it's not enabled.

**Comment by cklosowski** [comment]
I agree with that @pippinsplugins. @sunnyratilal let's get that changed up.

**Comment by cklosowski** [comment]
That should take care of it, if you set the default to one that's not selected, you get an error, and it reverts to the first enabled one. If you check one and set at the same time, it'll save, and if you disable a gateway and it's set as the default, it sets the default to the first one in the list.

**Comment by pippinsplugins** [comment]
@cklosowski close but not quite.

Disable `PayPal Standard` (first gateway in the list) and then try and set the default to `PayPal Express` (another disabled gateway further down the list).

Default should go to the first active  gateway, but it instead goes to PayPal Standard, which is disabled.

**Comment by ghost1227** [comment]
Another 'bug', though technically not a real bug I suppose, is that if you disable ALL gateways, it throws the 'can not set default gateway' error. I think this could actually be handled better, perhaps a general error indicating that a gateway needs to be set?

**Comment by SDavisMedia** [comment]
I ran into the same exact bugs as Pippin and Dan originally. Both have been addressed with the last commit. Very slick. :+1:

**Comment by sunnyratilal** [comment]
👍 from me

**Comment by pippinsplugins** [comment]
Merged!
