### ISSUE TITLE
Add ABSPATH check to Amazon Gateway files

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/Easy-Digital-Downloads#3558]
They need a `if ( ! defined( 'ABSPATH' ) ) exit;`

**Comment by pippinsplugins** [comment]
Don't tag for 2.4.1, that was just released.

**Comment by chriscct7** [comment]
Ah missed that.

**Comment by pippinsplugins** [comment]
:)

**Comment by cklosowski** [comment]
Are we talking about adding it to the files from Amazon themselves? We have it in our inclusion of the Gateway.
