### ISSUE TITLE
Ability to add products to bundles from individual product screen

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/Easy-Digital-Downloads#3559]
Based on a customer request, opening for discussion of possible enhancement to bundle management. 

**Use case**
On a regular basis (weekly/monthly), new products are added to the site. These products are, depending on various things, included in 4-5+ other bundles. Right now, every time a new product is added to the site, you have to edit each of those bundles and add it to them.

**Requested feature**
The ability to add an item to existing bundles from the add/edit screen of the individual product, instead of going to 5 different products and doing it all there.

Thoughts?

**Comment by pippinsplugins** [comment]
I get the use case but I don't see this working very well from a UI perspective, especially if someone has a lot of bundles.

When creating or editing products, no one expects to have options to edit another product from the same screen. I don't see this as any different.

That's my two cents

**Comment by mindctrl** [comment]
I agree the UI would be tricky. I think it would need to be a select2 multiselect type field to have a decent UI and to accommodate many bundles, but I'm good with not adding this in core. Have only seen a couple requests for it and we have bigger fish to fry.

**Comment by cklosowski** [comment]
If the bundle does not have variable pricing, when creating or editing a single product (not a bundle), we could provide a list of checkboxes (like categories) with each bundle on the site, then we can show which bundles it belongs to, and which it doesn't. Checking a box would add it to that bundle upon saving.

I actually think this would be better served as a helper plugin, or something. Not for core.

@pippinsplugins @mindctrl ?

**Comment by pippinsplugins** [comment]
I agree with it being a help plugin. Would create too much UI clutter for core.

**Comment by cklosowski** [comment]
Ok, closing this out as it's been decided to not put it in core. If we get many requests for it we can look into it as an add-on plugin.
