### ISSUE TITLE
Improve Batch Exporter Extensibility

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/Easy-Digital-Downloads#3561]
There are a few changes we need to make to the batch exporter to allow it to be super extensible by other plugins.

Mainly adding some hooks to allow including specific extensions of the `EDD_Batch_Export` class and set properties specific to the type of export, instead of a general collection of properties.

**Comment by cklosowski** [comment]
This is needed to release an update for the Commissions extension, fixing a major issue with the generation of large mass payment files.

**Comment by cklosowski** [comment]
@pippinsplugins can you take a look at this issue branch and see if this works for you. The core reports still export, working on getting the Commissions one working with it now.

**Comment by pippinsplugins** [comment]
See my inline comments.

**Comment by pippinsplugins** [comment]
This great, let's get a PR and get it merged.
