### ISSUE TITLE
Session ID error with wp_debug on...

### ISSUE THREAD

**Issue by itibook** [easydigitaldownloads/Easy-Digital-Downloads#3570]
Hi there,

I am getting the following issue when I have wp_debug turned on... no idea if it's a huge issue, but thought I'd let you know...

ciao

Luca

Warning: session_start(): The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in /nas/wp/www/staging/addendio/wp-content/plugins/easy-digital-downloads/includes/class-edd-session.php on line 288

**Comment by pippinsplugins** [comment]
I've heard of this happening once.

Does it go away if you add `define( 'EDD_USE_PHP_SESSIONS', false)` to wp-config.php?

**Comment by itibook** [comment]
That fixes it... :-)

**Comment by pippinsplugins** [comment]
Glad to hearit.

**Comment by Hanistips** [comment]
Hello.
So I'm getting the same message above my home page.
and I cant visit other pages in my website.

Adding...

define( 'EDD_USE_PHP_SESSIONS', false) to wp-config.php

Is not helping at all.

**Comment by pippinsplugins** [comment]
Please open a support ticket. Github is for development tracking.
