### ISSUE TITLE
Change "User" heading to "Customer" in the Payment History screen

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/Easy-Digital-Downloads#3571]
Now that we Customers, let's change the User column heading to Customer to clarify it.

**Comment by pippinsplugins** [comment]
I've actually done more than just update the column name. I've also updated the column values to pull the name from the customer record instead of the user record.

**Comment by pippinsplugins** [comment]
@mindctrl could you give this some testing this week?

**Comment by mindctrl** [comment]
Looks good here.
