### ISSUE TITLE
Tag latest release

### ISSUE THREAD

**Issue by michaelbeil** [easydigitaldownloads/Easy-Digital-Downloads#3573]
I just noticed that the latest release tag is back on 2.3.8. Would be good to update to the most recent version.
![screen shot 2015-07-06 at 2 45 53 pm](https://cloud.githubusercontent.com/assets/4752949/8531559/eb6a0886-23ed-11e5-8ce6-a9abc7e88cd3.png)

**Comment by cklosowski** [comment]
You're talking about the Github specific 'Release' view? We do have all the proper tags made in the git repository here:
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/tags

**Comment by cklosowski** [comment]
Since tags for each release do exist, and Github doesn't allow us to log a 'release' (specific to the Github interface) from an existing tag, closing it out. Tags can be pulled from the URL provided above.
