### ISSUE TITLE
Conflict with bbPress profile display

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#3578]
The API keys section appears to cause an issue with the profile screen in bbPress for admins and super admins: https://wordpress.org/support/topic/easy-digital-downloads-bug-on-bbpress-user-edit-page

**Comment by pippinsplugins** [comment]
Proposed solution in #3583

**Comment by cklosowski** [comment]
Oh, it's pulling in the Profile Editor from wp-admin, but not in an admin state. Need to verify that we're not opening up any risks here having the `upgrade-functions.php` file loading on the front end.

**Comment by cklosowski** [comment]
I'm actually thinking we just pull the `edd_has_upgrade_completed()` function out into a both front and backend include, so that it's available for front and backend use. It's a compatibility function, not an upgrade function.

**Comment by cklosowski** [comment]
thoughts @pippinsplugins?

**Comment by cklosowski** [comment]
Yeah I'm going to go this route I think.
