### ISSUE TITLE
Downloading .zip file in editor

### ISSUE THREAD

**Issue by samikeijonen** [easydigitaldownloads/Easy-Digital-Downloads#3579]
When I download .zip file in "editor content" for download post type, I get 404 when trying to download the file. Download path is .../edd/...

This could be a problem in my host also. But I was wondering can this be issue in EDD. You can see the example in my site when you try to **Download blank child theme for Kuorinka**.

https://foxland.fi/downloads/kuorinka/

**Comment by pippinsplugins** [comment]
That's because all files uploaded to a Download product are automatically placed in the `/uploads/edd/` folder.

If you want a publicly accessible file, upload it outside of the edit screen.

**Comment by samikeijonen** [comment]
It just weird that images works but not .zip files. Are all .zip files somehow protected?

**Comment by pippinsplugins** [comment]
Images are intentionally excluded. See https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/admin/upload-functions.php#L152

**Comment by samikeijonen** [comment]
Got it, thanks.
