### ISSUE TITLE
URLs to remove Fees and Items can be caught by caching

### ISSUE THREAD

**Issue by jdevalk** [easydigitaldownloads/Easy-Digital-Downloads#3580]
It generates URLs with `p` or `page_id` instead of normal URLs. Should be easy enough to fix :)

**Comment by pippinsplugins** [comment]
@jdevalk Why is that a problem? Is the `p` or `page_id` incorrect?

**Comment by jdevalk** [comment]
No, the caching exclusion doesn't work because the URL doesn't contain `/checkout/`, which it would otherwise...

**Comment by pippinsplugins** [comment]
Ah! that makes sense.

We'll get it fixed!
