### ISSUE TITLE
Specifying customer in customers endpoint of REST API fails

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#3584]
The `customers` end point of the REST API allows for a `customer` parameter to be specified. Usually this is set to an email address.

Since 2.4, this request is no longer working.

When testing locally, I'm seeing an SQL error:

WordPress database error: [You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''\'mollyw@test.com\''} ) ORDER BY id DESC LIMIT 0,10' at line 1]
SELECT * FROM wp_edd_customers WHERE 1=1 AND `email` IN( {'\'mollyw@test.com\''} ) ORDER BY id DESC LIMIT 0,10;

**Comment by pippinsplugins** [comment]
Reported https://secure.helpscout.net/conversation/102860950/12288/

**Comment by PareshRadadiya** [comment]
#3587

**Comment by pippinsplugins** [comment]
Thanks @PareshRadadiya, we'll take a look soon!
