### ISSUE TITLE
Extension for CorvusPay payment gateway

### ISSUE THREAD

**Issue by Crowdfunders** [easydigitaldownloads/Easy-Digital-Downloads#3585]
Do you have plan to develop extension for CorvusPay payment gateway?

CorvusPay is the most popular payment gateway in Croatia. Here you can see more about CorvusPay.
http://www.corvuspay.hr/

You can also see more about CorvusPay through extension for WooCommerce plugin.
https://cs.wordpress.org/plugins/corvuspay-woocommerce-integration/

**Comment by chriscct7** [comment]
This repository is for developers to focus on issues with core. Please open a support ticket at easydigitaldownloads.com/support for support, presale and other general questions. Thanks!
