### ISSUE TITLE
Adding comments to Manual Purchases extension

### ISSUE THREAD

**Issue by Crowdfunders** [easydigitaldownloads/Easy-Digital-Downloads#3586]
I use EDD plugin with Astoundify plugin for crowdfunding purpose.
I have also add Manual Purchases extension.
Do you have plan to develop Manual Purchase extension so campaign contributors also can leave comments which will show on platform in addition with the paid sum?

**Comment by chriscct7** [comment]
This repository is for developers to focus on issues with core not with extensions. Please open a support ticket at easydigitaldownloads.com/support for support, presale and other general questions. Thanks!
