### ISSUE TITLE
[purchase_link] direct to gateway option doesn't work on variable products

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/Easy-Digital-Downloads#3592]
Instead of going direct to the gateway, the item gets added to the cart.

Example shortcode:
`[purchase_link id="897" price_id="1" direct="true"]`

[Reported here](https://secure.helpscout.net/conversation/102335965/12136/).

**Comment by pippinsplugins** [comment]
@mindctrl Could you test #3601?

**Comment by mindctrl** [comment]
@pippinsplugins will test today.

**Comment by mindctrl** [comment]
@pippinsplugins commented on PR and forgot to update here. Looks good, just needs formatting.

**Comment by pippinsplugins** [comment]
@mindctrl :+1:

**Comment by pippinsplugins** [comment]
@mindctrl @PareshRadadiya The changes in this do not work for me. Makes variable prices just get added to the cart.

**Comment by mindctrl** [comment]
@pippinsplugins working for me here still. Cached JS on your end maybe?

**Comment by pippinsplugins** [comment]
Weird, I'll try again.

**Comment by pippinsplugins** [comment]
Nope, definitely does not work for me. Confirmed it's not caching.

**Comment by pippinsplugins** [comment]
`master` works just fine though, it's just this branch/pr that doesn't work.

**Comment by pippinsplugins** [comment]
OH wait, I see it.

@mindctrl Test the default purchase buttons (not the short code versions). Those fail with the changes in #3601

**Comment by pippinsplugins** [comment]
New PR submitted that works in base cases.

**Comment by mindctrl** [comment]
@pippinsplugins Good catch. This looks good. Only thing to note is if `direct` = anything at all, it sends to the gateway. Example: `direct="false"` or `direct="moo"` sends to gateway. But this is also the case in 2.4.2.

**Comment by pippinsplugins** [comment]
Yep, different issue.
