### ISSUE TITLE
problems with multiple instances of the cart widget

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#3593]
So it appears that if more than one cart widget is on a page, the second (and beyond) widget in the HTML flow will not display or behave properly. Here's what I see so far:

* The second widget [specifically] does not display a title: http://glui.me/?i=ypc8f0vqffffcgv/2015-07-09_at_12.56_PM.png/
* Once you add an item to the cart and the widget updates (NO page refresh), the cart items are missing from the second widget and beyond: http://glui.me/?i=ga7qhlotrlt6zo9/2015-07-09_at_12.58_PM.png/
* Refresh the page and the cart items show up (still not second widget title): http://glui.me/?i=ztc92e627eq3pwo/2015-07-09_at_12.59_PM.png/

**Comment by cklosowski** [comment]
ive tracked this down just need to get a fix in place.

**Comment by SDavisMedia** [comment]
@cklosowski Okay so the title issue is fine and adding items to the cart is fine as well. There are problems when you remove them, though. I recorded a video so you can see the issues: http://quick.as/mz64i6lgq

**Comment by cklosowski** [comment]
@SDavisMedia interesting, my removeal causes a page refresh in some cases, which we coded up in a previous issue. I'll dig in further.

**Comment by SDavisMedia** [comment]
I think I remember that, actually. Wonder why it's not doing it now. 🤔

**Comment by cklosowski** [comment]
@SDavisMedia I think it's a combination of the items in the cart and the item we're looking at currently. It only refreshes the page if the item you're removing is the item your on, to take care of refreshing any of the purchase link options data. Just need to make our `remove` JS follow through to all of the cart widgets.

**Comment by cklosowski** [comment]
@SDavisMedia Ok pushed up some changes, should be fixed.

**Comment by SDavisMedia** [comment]
Working perfectly now. 👌

**Comment by cklosowski** [comment]
Merging then
