### ISSUE TITLE
[downloads orderby="random"] with pagination results in repeated results

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/easy-digital-downloads#3600]
When using something like the following:

`[downloads orderby="random" number="3"]`

Provided there are more than three downloads, three random selections will be shown and pagination will appear below. However, the issue is that when clicking through the paginated results, each page shows three random downloads from the _entire_ pool as opposed to just showing the next three. Example:

Page 1 shows IDs: 4, 17, 9
Page 2 shows IDs: 11, 24, 4
Page 3 shows IDs: 17, 2, 11

...and so on. Also, navigating back to a previously visited page will show different random downloads than it did before. This is a little problematic as users not only will see some downloads repeatedly but will not easily be able to view all existing products. In the example above, if 30 products existed, 10 pages would be created for the pagination. But clicking through every single page would not necessarily mean one had viewed every single available download since each click grabs 3 randomly from the pool of 30.

**Comment by cklosowski** [comment]
I'm not sure how we could fix this...each page in the WordPress pagination query isn't aware of the previous or next. They are not stateful.

**Comment by brashrebel** [comment]
Could we manipulate the pagination links to pass IDs to exclude on subsequent pages? If each page passed an array of IDs to the next page...and they were somehow associated with the page number...well that wouldn't work great. It would allow for navigating in one direction pretty well but skipping around and going back pages would be odd.

I can't think of much else.

**Comment by pippinsplugins** [comment]
Theoretically we could but it seems kind of silly. The whole point of random is to make it, well, random. I get the reason someone would want it to not be random across subsequent page loads but .... you know, random :D

**Comment by spencerfinnell** [comment]
What about disabling pagination if the order is set to random? Can still set a limit, but don't output the actual pagination links.

**Comment by pippinsplugins** [comment]
That seems like the most logical approach.

**Comment by spencerfinnell** [comment]
Yep and just make sure it's documented.

**Comment by brashrebel** [comment]
I agree that that makes more sense. Pagination is kind of silly if you're just getting the same downloads and if someone is using orderby=random then we can presume providing a comprehensive selection is not important.

Should a pagination boolean attribute be considered for the shortcode?

**Comment by spencerfinnell** [comment]
I think setting orderby=rand should be enough and automatically disable pagination.

**Comment by cklosowski** [comment]
Yeah best solution I can think of too. Milestoning for 2.6.

**Comment by pippinsplugins** [comment]
This is ready for testing.
