### ISSUE TITLE
Discount Codes changing to inactive

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/Easy-Digital-Downloads#3606]
A user pointed out that twice now he's had a core discount code change itself from active to inactive without him doing anything to make that happen. He's using **no start date and no end date**.

I went to my own discounts and the first thing I noticed was that one of my two test discounts for testing was inactive. It had absolutely no reason to be. It also has no start or end dates entered. The only difference between the inactive discount and the active one is that the inactive one specifies downloads that it applies to.

Any ideas?

**Comment by pippinsplugins** [comment]
Mystery to me! Will have to dig in.

**Comment by tucsonjhall** [comment]
My codes stopped working all of a sudden. If I let it go for a bit, I get the following error:

user_info in /var/www/vhosts/cactusware.com/httpdocs/app/plugins/easy-digital-downloads/includes/discount-functions.php on line 853 success

**Comment by pippinsplugins** [comment]
@tucsonjhall That appears to be unrelated but when does that notice show up? When entering a discount on checkout?

**Comment by tucsonjhall** [comment]
Correct. Enter the discount code, click Apply and the preloader spins forever. I've tried recreating the discount code, with no luck so far.

**Comment by pippinsplugins** [comment]
Does it work if you disable all other plugins?

**Comment by tucsonjhall** [comment]
When I enter a discount code, it sits on the checkout page and does little.
However, if I refresh the page, it has successfully gone through,

http://www.screencast.com/t/HGBaqfRsdpM

I have not disabled all plugins simultaneously. I have done one at a time
with no change.

On Wed, Jul 15, 2015 at 2:40 PM, Pippin Williamson <notifications@github.com
> wrote:

> Does it work if you disable all other plugins?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/3606#issuecomment-121758517>
> .
>



-- 
John Hall
jhall@cactusware.com
http://www.cactusware.com

**Comment by pippinsplugins** [comment]
Do you have any code in your theme that ties into EDD?

**Comment by tucsonjhall** [comment]
I will check. Thanks much.

**Comment by cklosowski** [comment]
I've not duplicated this, but I'll look into it for sure, see if I can uncover any possibilities here.

**Comment by tucsonjhall** [comment]
My apologies for not getting back to you. It was just resolved last week and it was on our side - something about the database not being updated. Don't know if it was in WP or other, but apparently had nothing to do with the plugin. My apologies.

**Comment by pippinsplugins** [comment]
@tucsonjhall thanks for the update!
