### ISSUE TITLE
email logos not showing up in email template

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/Easy-Digital-Downloads#3607]
I'd normally ask y'all to check this in Slack but it's the weekend. Here's a ticket: https://secure.helpscout.net/conversation/104088275/12661/ I'm getting the same behavior.

Can you all upload an image logo to the email template (yes, the Default Template) and confirm that it shows properly in emails?

**Comment by pippinsplugins** [comment]
Shows on preview: 
![screen shot 2015-07-12 at 3 48 26 pm](https://cloud.githubusercontent.com/assets/1034109/8639972/741a9524-28ad-11e5-97c9-2e7efdfa9db1.png)

Are you testing locally and sending email to your live inbox? That will not work unless the file is hosted on a live server as well. Viewing a locally hosted file through gmail does not work.

**Comment by SDavisMedia** [comment]
Ah... that's probably what it is then. I'll check with the user and see if that's the case with his testing.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
It's tripped me up so many times.

**Comment by SDavisMedia** [comment]
This ended up being a user error / my local testing coincidence. So false alarm. :+1:

**Comment by pippinsplugins** [comment]
:+1:
