### ISSUE TITLE
Tax state text input field doesn't show saved value

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/Easy-Digital-Downloads#3613]
Found in testing for `2.4.2`, exists in `2.4.1`, when you change to a country without a state dropdown, a text input is displayed. The value entered there is saved, but the value isn't re-displayed after you save it (but it does exist in the db).

**Comment by pippinsplugins** [comment]
Good catch.

**Comment by cklosowski** [comment]
Thank @mindctrl  ;)
