### ISSUE TITLE
Amazon Payments: names not stored properly if customer enters three names

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#3617]
As noticed by Amazon testers:
>>>If a person has three names the first two get taken for the first and last. Might be better to take the first chunk and then the remainder as the last. Example: 'Brienne of Tarth' will show up in EDD as 'Brienne of'

**Comment by cklosowski** [comment]
We should probably separate `Brienne of Tarth` to `Brienne of` and `Tarth`, is that the recommended course of action?

**Comment by pippinsplugins** [comment]
Yep.

**Comment by chriscct7** [comment]
No, it should be the reverse. The first word to the first name and anything left over to last name. That's the industry standard for splitting a name field.

**Comment by chriscct7** [comment]
Example "Oscar De La Hoya", first name = Oscar, last name = "De La Hoya"

**Comment by chriscct7** [comment]
That's actually also what Amazon recommended: "Might be better to take the first chunk and then the remainder as the last"

**Comment by cklosowski** [comment]
Ok sounds good

**Comment by pippinsplugins** [comment]
Ah yes, I agree with @chriscct7

**Comment by chriscct7** [comment]
Would we expect saluations in the name field on an amazon return? Example "Mr Someone Somebody" or something like that?

**Comment by pippinsplugins** [comment]
No, I don't think saluations are ever returned unless the customer entered it manually in the name field.
