### ISSUE TITLE
edd_get_payment_statuses() missing statuses

### ISSUE THREAD

**Issue by DevinWalker** [easydigitaldownloads/Easy-Digital-Downloads#3623]
It appears there are more statuses used than what is in the array within the edd_get_payment_statuses() on https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/payments/functions.php#L600

For instance:

* preapproval 
* cancelled

Found on https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/admin/payments/class-payments-table.php#L440

Shouldn't those be included in the array as well?

**Comment by chriscct7** [comment]
No, since pre-approved and cancelled are not used by any of our core gateways. They must be added to the payment status list by extensions that use them (this way they don't show in the set order status to dropdowns, etc)

**Comment by pippinsplugins** [comment]
What @chriscct7 said is correct. Those statuses originally came from the crowd funding add-ons and have still only ever been used in those scenarios. At some point we should consider formalizing them better though.

**Comment by DevinWalker** [comment]
Thanks that's good to know guys.

**Comment by chriscct7** [comment]
Not a problem :-)
