### ISSUE TITLE
Images in downloads aren't displaying in https

### ISSUE THREAD

**Issue by fxbenard** [easydigitaldownloads/Easy-Digital-Downloads#3625]
Not sure if it's a bug but my site is setup in https and adding images to a download will show them in http.

**Comment by pippinsplugins** [comment]
What does the `Text` tab show, https or http after update?

**Comment by fxbenard** [comment]
still http

**Comment by pippinsplugins** [comment]
If you manually change to https, does it work?

**Comment by fxbenard** [comment]
It works perfectly if I change manually to https.

**Comment by pippinsplugins** [comment]
Do you get the same behavior on non-EDD posts and pages?

**Comment by fxbenard** [comment]
Ok made a test with both a new post and a new downloads with 2 differents new images freshly imported, both in https. 
Something wrong with my last import probably, let's close this if you want. I'll reopen it in case it happens again.
Thanks for the fast check

**Comment by pippinsplugins** [comment]
OK let us know if it is a valid issue!
