### ISSUE TITLE
Logic seems backwards in edd_store_discount

### ISSUE THREAD

**Issue by danieliser** [easydigitaldownloads/Easy-Digital-Downloads#3626]
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/discount-functions.php#L255

Shouldn't that be ??

if ( ! empty( $discount_id ) && edd_discount_exists( $discount_id )  ) {

**Comment by danieliser** [comment]
Doing it the way it is now causes an extra lookup before even checking that the ID is empty. if statements process from left to right. so if the first check fails it automatically skips the rest. Saves a query if the id is empty.

**Comment by pippinsplugins** [comment]
`if ( ! empty( $discount_id ) && edd_discount_exists( $discount_id ) ) {` would be better :)

**Comment by danieliser** [comment]
:+1:
