### ISSUE TITLE
Technical Debt Cleanup - Remove conditionals for old WordPress versions

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#3627]
There are situations in the codebase where we specifically have logic based on what WP Version someone is running, for instance:
```
if ( $wp_version >= 3.3 && function_exists( 'wp_editor' ) ) {
```

Since we require `3.9.2 or higher` per our .org page, we should really clean up all these items to help get rid of these lines of code.

**Comment by pippinsplugins** [comment]
Once unit tests pass, we should be able to merge this.

**Comment by michaelbeil** [comment]
Looks good.

**Comment by SDavisMedia** [comment]
All good here.
