### ISSUE TITLE
Change EDD logo on welcome screen

### ISSUE THREAD

**Issue by sumobi** [easydigitaldownloads/Easy-Digital-Downloads#3628]
About time we updated the logo (and anywhere else it's shown). I'm opting for SVG so it scales nicely.

Out with the old:

![screen shot 2015-07-22 at 4 10 31 pm](https://cloud.githubusercontent.com/assets/52581/8817819/81fe2ae8-308c-11e5-8fe1-a3596d1e726a.png)

And in with the new:

![screen shot 2015-07-22 at 4 10 57 pm](https://cloud.githubusercontent.com/assets/52581/8817820/81fe8e52-308c-11e5-98fb-3126600544c2.png)

I don't think we need the version number anymore, it's shown in the heading, the line below, and on the plugins page.

**Comment by pippinsplugins** [comment]
:+1:
