### ISSUE TITLE
Change logo on exported reports pdf

### ISSUE THREAD

**Issue by sumobi** [easydigitaldownloads/Easy-Digital-Downloads#3630]
Related: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/3628

Old:

![screen shot 2015-07-22 at 4 30 35 pm](https://cloud.githubusercontent.com/assets/52581/8818098/c049984c-3090-11e5-9048-bdda6588ea17.png)

New:

![screen shot 2015-07-22 at 4 42 05 pm](https://cloud.githubusercontent.com/assets/52581/8818097/c048b06c-3090-11e5-9d65-cd152dca0c4c.png)

**Comment by pippinsplugins** [comment]
Good catch.
