### ISSUE TITLE
Opt-in not sent when opt-ing in from settings screen

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#3634]
If a user dismisses the opt-in notice shown after install, they are permitted to opt-in later from the settings screen.

I'm pretty confident the opt-in is not working when someone does it from settings.

**Comment by cklosowski** [comment]
It's sending the data when the opt-in from the settings is checked. If you're testing it locally however, it will wait a week from your last check-in before doing it again due to this clause:
```
		// Send a maximum of once per week
		$last_send = $this->get_last_send();
		if( $last_send && $last_send > strtotime( '-1 week' ) )
			return;
```

**Comment by cklosowski** [comment]
When I remove the last check, and opt-out, then back in, I see the request being sent:
` 'body' => string 'success' (length=7)`

**Comment by cklosowski** [comment]
Un-milestoning, if we notice something else with it, we'll set it for a release.

**Comment by cklosowski** [comment]
Note though, that when testing, the sending of data checks when the last sent data was, and if it's less than 1 week ago, it will not send on re-opting-in.

**Comment by pippinsplugins** [comment]
This has been fixed. See #4635 #4720 #4740
