### ISSUE TITLE
Download links break with qTranslate and (possibly) WPML

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#3635]
According to [this support ticket](https://secure.helpscout.net/conversation/105455458/13022/), there is an issue with file download links when a site uses WPML.

For a site that has French and English, as an example, the download links in one language work but not the other.

The proposed solution is to simply add the language parameter to the download URL.

**Comment by brashrebel** [comment]
I believe [this ticket](https://secure.helpscout.net/conversation/113583242/15056/) is also related.

**Comment by mindctrl** [comment]
Related: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/2597

**Comment by pippinsplugins** [comment]
Another ticket, but this time with qTranslate: https://secure.helpscout.net/conversation/135443323/20322/

**Comment by pippinsplugins** [comment]
For the user with a problem with qTranslate, the `/en/` parameter causes a 404 error with nginx, not a permission denied.

**Comment by pippinsplugins** [comment]
I've tracked down and resolved the qTranslate issue. Now to resolve WPML.

**Comment by spencerfinnell** [comment]
Not sure if it works already or not but might want to give Polylang a test too.

**Comment by pippinsplugins** [comment]
I'm testing with WPML right now and so far cannot make it fail. Will keep digging.

**Comment by pippinsplugins** [comment]
@spencerfinnell last time I tried it worked properly.

**Comment by pippinsplugins** [comment]
I can't break WPML. It works perfectly for me.

**Comment by pippinsplugins** [comment]
@brashrebel Note: https://secure.helpscout.net/conversation/113583242/15056/ is a different issue. That's a problem with Content Restriction.
