### ISSUE TITLE
Bugs/Fixes to Earnings by Category admin report

### ISSUE THREAD

**Issue by MythThrazz** [easydigitaldownloads/Easy-Digital-Downloads#3636]
Hello,

I'm lead Wordpress Developer at CreativeMinds, we're using the Easy Digital Downloads to sell our plugins. We were happy that you've added the "Earnings by Category" report, but quickly we've found out that it's missing the date filters which were our core use case. 

So we've decided to add it, thinking about maybe creating an add-on of it, but quickly we've discovered that the report is using the old (soon to be deprecated as the comment says) function for stats instead of the EDD_Stats class.After using this class and the date selector from the Earnings report we've managed to quickly add the filter to the report, so no need for an add-on :)
 
Later during the testing, we've found out that there's a bug in the EDD_Stats class, which caused the transactions containing the same download_id more than once being multiplied (Select query was missing "DISTINCT").

**Comment by cklosowski** [comment]
Would you mind submitting your changes as a Pull Request to the branch `issue/3636`? Then I can pull them down easily and test them.

**Comment by MythThrazz** [comment]
Done.

**Comment by cklosowski** [comment]
@MythThrazz made a couple changes here, fixed up some UX issues with the control order and whitespace. Things look like they are working alright for you on this PR?

**Comment by cklosowski** [comment]
@pippinsplugins @mindctrl Could you guys poke around on this and see if the changes that @MythThrazz and I made are working correctly for you?

**Comment by MythThrazz** [comment]
@cklosowski I was on a short vacation and didn't have time version after merge yet. I'll try to find time when I dig myself out of the pile of tasks.

**Comment by cklosowski** [comment]
@MythThrazz no worries! thanks for getting back to us. I didn't change much, just some general whitespace cleanup and restructured the order of the controls to follow our standards (was a bug on our end not giving you a way to put them in the correct order)

**Comment by mindctrl** [comment]
@cklosowski still testing this in `issue/3636`? It's totally broken for me.

-----------

![image](https://cloud.githubusercontent.com/assets/1254870/11131664/c5d3f68c-8959-11e5-8cd5-d2b98b191444.png)

Getting JS errors in the console. `Uncaught TypeError: Cannot read property 'grid' of null in jquery.flot.pie.js?ver=4.3.1:661`

**Comment by cklosowski** [comment]
Yeah `issue/3636` should be the one, let me bring it up to speed with `release/2.5`. That could be b/c of 0 sales...do you have something with sales?

**Comment by mindctrl** [comment]
Test Cat 1 definitely has sales.

![image](https://cloud.githubusercontent.com/assets/1254870/11131968/403231cc-895b-11e5-9be6-6e150b4bdb52.png)

**Comment by mindctrl** [comment]
My issue was no sales for the selected range. Chris is working on some messaging for when no sales are present in the current view.
