### ISSUE TITLE
Taxonomies with numeric slugs are assumed to be a term_id in the [downloads] shortcode

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/easy-digital-downloads#3638]
If a taxonomy slug is a number, the query assumes it's a term_id instead of the slug.

Example: customer has parent/child categories like this:
-- year
---- 2015

 `[downloads category="2015"]`

Results in the query fetching term_id 2015 instead of get_term_by 2015.

@sunnyratilal found this due to a ticket that came in. We talked about adding another check for the slug if it's numeric, but the concern there is adding another query. Talked with @cklosowski and he wants to take a look at it.

We could flip the conditionals around and check for slug first, but that makes it less efficient in cases where someone supplies an ID. I wonder how often IDs are supplied here? Seems like a less user friendly method than slug. So maybe not a lot? Other ideas?

**Comment by pippinsplugins** [comment]
Blargity blarg blarg.

**Comment by pippinsplugins** [comment]
We could use `is_int()`:
```php
$i = (int) 'two';
var_dump( is_int( $i ) && ! empty( $i ) );
```
Return: `false`;
```php
$i = (int) '22';
var_dump( is_int( $i ) && ! empty( $i ) );
```
Return: `true`;

**Comment by pippinsplugins** [comment]
@mindctrl mind giving this a test?

**Comment by mindctrl** [comment]
@pippinsplugins it still seems to be assuming a numeric is the ID and not the slug.

I have a category named "100". Its ID is 213.
![image](https://cloud.githubusercontent.com/assets/1254870/15148507/85389cc8-1693-11e6-9a56-b256165b0530.png)

When I use the following shortcodes to test:
![image](https://cloud.githubusercontent.com/assets/1254870/15148535/9a108066-1693-11e6-87e8-093658fbbd5a.png)

Here's what I get:
![image](https://cloud.githubusercontent.com/assets/1254870/15148547/a4e2dd2c-1693-11e6-9d17-ef4cd4c49653.png)

It's only pulling in the items if the numeric is the term ID.

**Comment by pippinsplugins** [comment]
Hmm, was working for me. Will test further.

**Comment by pippinsplugins** [comment]
Oh, I see what I did.

Hmm, unfortunately I don't think there's a way to fix this without calling `get_term()` and seeing if it has results. That adds an extra query for each term specified.

**Comment by mindctrl** [comment]
The extra query was my concern. I think I'm fine with us not fixing this and if we run across it tell people to use the ID. I've only seen this come up once.

**Comment by pippinsplugins** [comment]
This does still make an improvement.

Previously slugs like `two` would be interpreted as an ID since it passes the `is_numeric` test. Now `two` will be properly detected as a slug.

**Comment by pippinsplugins** [comment]
@mindctrl and I have agreed that we're not going to account for slugs like `100`. This is still an improvement. Anyone that uses integers for slugs will just need to term IDs.
