### ISSUE TITLE
Variable typo in edd_is_admin_page

### ISSUE THREAD

**Issue by DevinWalker** [easydigitaldownloads/Easy-Digital-Downloads#3639]
`$ivew` should be `$view` on the last conditional check here: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/admin/admin-pages.php#L215 

PR coming in 1 sec.

**Comment by pippinsplugins** [comment]
Thanks @DevinWalker !

**Comment by DevinWalker** [comment]
No problem :+1:
