### ISSUE TITLE
Register a more EDD-specific downloads shortcode

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#3641]
Apparently the Download Monitor plugin also uses the `[downloads]` shortcode. That causes a conflict. @pippinsplugins suggested sort of a wrapper shortcode like `[edd_downloads]` for cases like this. Feasible? 

Ticket: https://secure.helpscout.net/conversation/106908148/13384/

**Comment by zackkatz** [comment]
Sounds very feasible to me: one line of code ;-)

**Comment by cklosowski** [comment]
Backwards compatibility is where we run into issues. We cannot get rid of the `[downloads]` short-code without ample warning. We'll most likely have to live with both for quite some time.

**Comment by SDavisMedia** [comment]
@cklosowski I'm not sure if we'd ever need to get rid of `[downloads]` or even broadcast that the more specific one exists. From the way @pippinsplugins mentioned it, I thought it would just be for special use cases.

**Comment by mindctrl** [comment]
I think we're not talking about getting rid of it, just adding a fallback one for when another plugin overrides it.

**Comment by pippinsplugins** [comment]
We will never get rid of `[downloads]`, we will simply register `[edd_downloads]` as a second short code that does exactly the same thing for scenarios where `[downloads]` is overwritten by another plugin.

**Comment by zackkatz** [comment]
You could also wrap the `add_shortcode( 'downloads', 'edd_downloads_query' );` line in a filter that would allow people to prevent EDD from registering `[downloads]`. 

```
if( apply_filters( 'edd_use_downloads_shortcode', true ) ) {
  add_shortcode( 'downloads', 'edd_downloads_query' );
}
add_shortcode( 'edd_downloads', 'edd_downloads_query' );
```

Yes, that's terrible, but you know what I mean.

**Comment by spencerfinnell** [comment]
Seems like a decent time to look at abstracting out some of the crazy amount of code inside the shortcode callback as well.

**Comment by cklosowski** [comment]
@spencerfinnell :100:

**Comment by pippinsplugins** [comment]
Oh yes

**Comment by pippinsplugins** [comment]
I'm not going to refactor the code in this issue. That should be a separate issue.

**Comment by pippinsplugins** [comment]
Merged.

`[edd_downloads]` and `[downloads]` are now both available.
