### ISSUE TITLE
clone_repeatable() does not work with Chosen drop downs

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#3645]
If you try and create a repeatable field with a product drop down that uses chosen, the `clone_repeatable()` function will fail with an error:
```
Uncaught TypeError: Cannot read property 'replace' of undefined
https://edd.com/wp-content/plugins/easy-digital-downloads/assets/js/admin-scripts.js?ver=2.4.2 line 42
```

**Comment by cklosowski** [comment]
@pippinsplugins I had to fix something like this for fraud monitor, I'll get it figured it. It's because you have to actually rerun the `.chosen()` function on the element after it's cloned.

**Comment by pippinsplugins** [comment]
@cklosowski I believe this is ready to go, yes?
