### ISSUE TITLE
Session cookies are not HTTP only

### ISSUE THREAD

**Issue by JJJ** [easydigitaldownloads/easy-digital-downloads#3649]
Related to #3648, session cookies are not using the `$httponly` parameter. Should they be? I haven't dug too deeply; maybe it would affect EDD AJAX functionality?

See some of the work that went into WordPress years ago:

https://core.trac.wordpress.org/ticket/7677

**Comment by pippinsplugins** [comment]
Hmm, good question. I'm not sure.

I can't think of any case where we access the cookies via `document.cookie` but it's certainly not out of the question that someone may be doing it.

Does anyone happen to know if setting `HttpOnly` makes it inaccessible through jQuery.cookie()?

**Comment by cklosowski** [comment]
`HttpOnly` are NOT accessible to client side scripts:
http://stackoverflow.com/questions/28066064/is-it-possible-to-read-httponly-cookies-with-jquery

**Comment by cklosowski** [comment]
Closing out as there is some inherent risk to stopping the cookies from being accessed by client side scripts like JavaScript.
