### ISSUE TITLE
Move away from deprecated is_a

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/Easy-Digital-Downloads#3651]
PHP strict error:
`is_a(): Deprecated. Please use the instanceof operator`

Using it here: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/2.4.2/includes/class-edd-download.php#L159

Also here: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/2.4.2/includes/class-edd-cli.php#L579

**Comment by shazahm1** [comment]
As of PHP5.3 is_a() is not deprecated. WP core still uses the function to.

ref: http://php.net/manual/en/function.is-a.php

**Comment by mindctrl** [comment]
Oh you're right. I had flipped back to 5.2.17 for testing. I think we can close this now.
