### ISSUE TITLE
Add hook for removing items from payment

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/Easy-Digital-Downloads#3652]
When editing a payment, and removing downloads from it, we don't have a hook in the removal process. We should add one in there so actions can be taken as things are removed from the payment, like deleting licenses in SL:

https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/admin/payments/actions.php#L174

We should also update the array of data to include the cart index, to help with removing specific items from the cart.

**Comment by pippinsplugins** [comment]
:+1:
