### ISSUE TITLE
Issue with unix timestamp token for save cart

### ISSUE THREAD

**Issue by xowia** [easydigitaldownloads/easy-digital-downloads#3653]
Before somedays, we have submitted a issue to flox.io that are using your cart saving feature. That allows user to save their cart and can restore their cart by using a link. Here I'm going to paste the report that reported to flox.io and the referred me to submit this bug to you. So here is the report-

"Greetings,

I found a bug that can be critical and can affect the user's data (i.e. User's Cart). So now let me explain the issue.
User can add item to their carts and can save it for later purchase. When user save their cart, a link unique link generate so that user can visit same link later and can have access to their cart to purchase item.

If you will take a closer look then you will notice, this link contains a unix time stamp and the format of the link is -
https://store.flox.io/checkout/?edd_action=restore_cart&edd_cart_token=UNIX_TIMESTAMP

Unix timestamp is nothing but the unique cart token that allow user to have access to their cart. When you visit generated link once then the cart will expire automatically. That means if you can visit cart of another user using the saved link so the link will be useless for the original user because it will expire.

So now let me explain it further. As I told Unix timestamp is unique value and when user save the cart, the time and date format convert to Unix timestamp and will become the token (Hope so I don't need to explain it.)

and now attacker can expire all the carts by using bruteforce (timestamp) technique and can access all the carts by same techniques.

Let me know if you required any further information.

Thank You
"

**Comment by pippinsplugins** [comment]
Yep, you're absolutely right. We'll get that fixed!

**Comment by pippinsplugins** [comment]
We no longer use timestamps alone for the cart tokens. This was fixed in 4ae3fb2849952797b9868e3ed0008d97ffe12a19
