### ISSUE TITLE
When new user created, check for guest purchase with same email and auto link.

### ISSUE THREAD

**Issue by danieliser** [easydigitaldownloads/Easy-Digital-Downloads#3654]
Currently creating a purchase before a user leaves the customer profile with no attached user ID. When a new user is created do a quick lookup and auto associate the user ID with the existing customer profile.

**Comment by pippinsplugins** [comment]
That already happens during user creation: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/user-functions.php#L357
