### ISSUE TITLE
Unnecessary edd_add_ons_init() function

### ISSUE THREAD

**Issue by DevinWalker** [easydigitaldownloads/Easy-Digital-Downloads#3656]
Is this function needed anymore? Looks like `edd_add_ons_check_feed` is no where to be found.

https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/admin/add-ons.php#L24

**Comment by DevinWalker** [comment]
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/pull/3657

**Comment by pippinsplugins** [comment]
Whoops!
