### ISSUE TITLE
Inserting invalid string on start and/or end time on purchase payment page leads to fatal error

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/Easy-Digital-Downloads#3658]
?post_type=download&page=edd-payment-history

To replicate: Paste (not try to type) in a string into the fields.

Result: 
![screenshot at 01-39-30](https://cloud.githubusercontent.com/assets/1324637/8950678/b861c364-3592-11e5-89bb-258b7e838163.png)

**Comment by chriscct7** [comment]
Moving this to 2.4.3. Just needs a type check on the construct of the library.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by cklosowski** [comment]
As @chriscct7 and I discussed, it'd be good to get other date formats supported in our date picker implementation, but for now we can rely on `m/d/Y` to get our date format from these selections.

**Comment by cklosowski** [comment]
Ok latest updates have taken care of the date formatting, also, added in some checks on the stats class. checking for wp_error (when the date is a string like `something`) as well as if the strototime doesn't come out anything good.

**Comment by pippinsplugins** [comment]
Changes in https://github.com/easydigitaldownloads/Easy-Digital-Downloads/commit/a5924eeb2cb0bdae24775dd3d145ffc2e8a2032a have broken today and last month stats.

![screen shot 2015-08-18 at 12 45 29 pm](https://cloud.githubusercontent.com/assets/1034109/9337917/afb1828e-45a7-11e5-94cf-779e395fe202.png)

**Comment by pippinsplugins** [comment]
It's the `strtotime( $this->start_date )` and strtotime( $this->end_date )` that makes it fail.
