### ISSUE TITLE
Add edd_get_current_customer_id()

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/Easy-Digital-Downloads#3662]
Sort of like get_current_user_id but for EDD. Wrapper to getting it out of the EDD session if it exists

**Comment by pippinsplugins** [comment]
We don't know the customer ID from the session.

**Comment by chriscct7** [comment]
```$customer = EDD()->session->get( 'customer' );```

**Comment by pippinsplugins** [comment]
Not following. The customer ID is not stored in session, how are you expected us to get it?

**Comment by chriscct7** [comment]
It's definitely stored in eh session on the checkout page because EDD uses it here: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/checkout/template.php#L157

That line would be replaced as in the above example, and we could also consider storing the customer id in the session starting when a known user enters a site

**Comment by pippinsplugins** [comment]
That's for detecting a preset customer. That is only there if an extension has set the `customer` key in order to prefix the checkout fields.

**Comment by chriscct7** [comment]
Ah ok

**Comment by chriscct7** [comment]
Closing for now, since I don't have time to follow up on this, but we should talk about the ability to session detect a customer after summer finals
