### ISSUE TITLE
Add KRW Currency

### ISSUE THREAD

**Issue by sunnyratilal** [easydigitaldownloads/Easy-Digital-Downloads#3663]
The Korean Won currency (KRW) has been requested by a customer.

https://secure.helpscout.net/conversation/108774528/13825/

**Comment by pippinsplugins** [comment]
We can't add it yet. See WooCommerce's issue on the same currency: https://github.com/woothemes/woocommerce/issues/7941

**Comment by chriscct7** [comment]
Until it appears on this list: https://www.paypal.com/selfhelp/article/FAQ2390/2 there's no point in keeping a ticket open for it.
