### ISSUE TITLE
Filter edd_format_amount_decimals not work correctly

### ISSUE THREAD

**Issue by cryptoapi** [easydigitaldownloads/Easy-Digital-Downloads#3664]
If use -
<?php
        add_filter( 'edd_format_amount_decimals', 'currency_decimals' );
	function currency_decimals( $decimals ) 
        {
		return 8;
	}
?>

It display prices in format 0.00000000 but when you save price for example, 10.12345678, it convert to 10.12000000

**Comment by chriscct7** [comment]
Not really sure how much of a bug this is. The format is just to pad 0's for display. Its not really for storing numbers > 2 decimal places as those numbers will be rounded to 2 in our tax calculation. The filter is designed for people who enter $10.00 and want to show $10 not to add additional decimal places (which would require altering the step on the back end price input field which we don't do).

**Comment by pippinsplugins** [comment]
I believe the rounding is happening in `edd_sanitize_amount`.

**Comment by cryptoapi** [comment]
Bitcoin/Litecoin cryptocurrency have 8 digits precision.

We have Bitcoin/Altcoin Gateway addon for Easy Digital Downloads.
https://wordpress.org/plugins/gourl-bitcoin-payment-gateway-paid-downloads-membership/

----

For example, WooCommerce already have "Number of Decimals" on settings page - 
![capture2](https://cloud.githubusercontent.com/assets/8633086/9033923/aa71992a-39c3-11e5-8441-61b1d0731744.PNG)

It useful to add similar option to EDD.

 -----

Tested "edd_sanitize_amount", still not work correctly -

<?php
add_filter( 'edd_format_amount_decimals', 'currency_decimals' );
add_filter( 'edd_sanitize_amount', 'currency_decimals' );
function currency_decimals( $decimals ) 
{
return 4;
}
?>

![capture](https://cloud.githubusercontent.com/assets/8633086/9033792/6bb2840c-39c2-11e5-895e-44a5b6f7bbdd.PNG)

**Comment by pippinsplugins** [comment]
Ah, you need to use both of these:

- `edd_format_amount_decimals`
- `edd_sanitize_amount_decimals`

**Comment by cryptoapi** [comment]
I use both. It still work incorrectly. See screenshot/code above. 
Item price: 0.0101 BTC, Total: 0.0100 BTC

I.e. edd_sanitize_amount_decimals - work with item price but still not work with "Total" price on checkout page.

**Comment by pippinsplugins** [comment]
The code you showed above is not correct:
```
add_filter( 'edd_format_amount_decimals', 'currency_decimals' );
add_filter( 'edd_sanitize_amount', 'currency_decimals' );
```

The second filter needs to use `edd_sanitize_amount_decimals`

**Comment by cryptoapi** [comment]
Sorry, I used all time "edd_sanitize_amount_decimals".
It is not work - 

<?php
add_filter( 'edd_format_amount_decimals', 'currency_decimals' );
add_filter( 'edd_sanitize_amount_decimals', 'currency_decimals' );
function currency_decimals( $decimals ) 
{
return 4;
}
?>

Item price: 0.0101 BTC, Total: 0.0100 BTC. Screenshot above.

**Comment by pippinsplugins** [comment]
It worked the last time I did it (for a bitcoin gateway). We'll have to look into it further.

**Comment by cryptoapi** [comment]
I made quick debug and found that problem is in function -
function edd_currency_decimal_filter( $decimals = 2 )  {}
file: includes/formatting.php
It use all time decimals = 2

It called by function edd_get_cart_content_details() {}, file cart/functions.php

**Comment by cklosowski** [comment]
It doesn't always return `2`
```
function edd_currency_decimal_filter( $decimals = 2 ) {

	$currency = edd_get_currency();

	switch ( $currency ) {
		case 'RIAL' :
		case 'JPY' :
		case 'TWD' :

			$decimals = 0;
			break;
	}

	return apply_filters( 'edd_currency_decimal_count', $decimals, $currency );
}
```

by default it resorts to 2. but you can use the filter `edd_currency_decimal_count` to set the number of decimals you want to use. We pass both the currency and the decimals to it, you would need something like the following:
```
function ck_make_eight_decimals( $decimals ) {
    return 8;
}
add_filter( 'edd_currency_decimal_count', 'ck_make_eight_decimals', 10, 1 );
```
Here is it working:
![screen shot 2015-08-03 at 10 32 31 am](https://cloud.githubusercontent.com/assets/1390124/9043532/f9808060-39ca-11e5-8ee6-d73b843fa0a6.png)

**Comment by cryptoapi** [comment]
You can test with 00000 as decimals.

For example, create Product with price 1.12345678 and go on Checkout page.
You will see Total: 1.120000000

**Comment by cklosowski** [comment]
Working as expected  on my end.
![screen shot 2015-08-03 at 11 02 05 am](https://cloud.githubusercontent.com/assets/1390124/9044093/20a80e66-39cf-11e5-9525-badeb41f1c6f.png)

**Comment by cryptoapi** [comment]
thanks, I updated reply.

**Comment by cklosowski** [comment]
I'm not seeing why you need 3 filters. I'm using 1 filter...the one I showed you and it's working on all areas.

**Comment by cryptoapi** [comment]
Thank you

**Comment by cklosowski** [comment]
No worries, If there's a need for the 3 filters, then by all means let me know, but try out this one filter and let me know if that works for you. It shouldn't take 3 to get this to work :)
