### ISSUE TITLE
Payment record post_title not updating with user first/last name

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#3667]
I'm jumping straight to an issue here since everyone is spread out today. Feel free to close if there's a simple explanation!

When a new payment record is created, its post_title is `FirstName LastName`. If you go and edit the user's profile and change the first and last name, their payment titles are not update to reflect the change.

Is this intentional? Should it update?

Relevant ticket: https://wordpress.org/support/topic/payment-title-not-updating?replies=1

**Comment by cklosowski** [comment]
I'm not sure it's relevant. We don't really use those titles for anything I don't believe. All relevant data is pulled from the payment meta. @pippinsplugins? The concern I have here is someone with a ton of payments is going to cause DB updates on a row that isn't really used for much other than being required by WP.

**Comment by pippinsplugins** [comment]
It should update. We use those fields to let you search payments by customer names.

**Comment by pippinsplugins** [comment]
But perhaps we should restructure that.

**Comment by cklosowski** [comment]
Yeah I think we should restructure that data, string parsing is messy and non-predictable if something goes wrong.

**Comment by cklosowski** [comment]
I'm closing this one out. With the new EDD 3.0 moving payments to a custom table, this `post_title` is no longer relevant.
