### ISSUE TITLE
Extending the dashboard Sales Summary widget

### ISSUE THREAD

**Issue by EngageWP** [easydigitaldownloads/Easy-Digital-Downloads#3669]
Hey, guys. I want to create a plugin that adds some payment-related data to the dashboard. I'd prefer to add everything to the Sales Summary widget rather than creating a separate widget because it falls in line with sales. To do this, though, I'd need at least one hook that doesn't currently exist.

My idea is to add a couple `do_action()`s to dashboard-widgets.php, passing along the EDD_Payment_Stats and EDD_Payments_Query objects to be used within the callback. If there's interest in this, I can submit a PR.

Thanks!

**Comment by pippinsplugins** [comment]
I don't see any reason why not!
