### ISSUE TITLE
Harden [purchase_history] user ID check

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/Easy-Digital-Downloads#3673]
Did I say that right? Opening up this issue as per @cklosowski's instructions. Here's the relevant ticket: https://secure.helpscout.net/conversation/104479535/12771/

**Comment by cklosowski** [comment]
Yeah, there's a chance we could end up sending `0` as the user ID when searching for a customer. There's no reason we should even get to the Customer Class with a user_id of `0`. If we get `0` as the user ID, we can simply just return 0.
