### ISSUE TITLE
Adding ?discount=code to the static home page causes is_home to be set to true

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#3674]
Go to: https://easydigitaldownloads.com/?discount=test

It should show https://easydigitaldownloads.com/ but instead shows the blog.

I've fixed this in AffiliateWP so will bring changes across.

Ticket: https://secure.helpscout.net/conversation/108643009/13789/

**Comment by cklosowski** [comment]
:+1:
