### ISSUE TITLE
Amazon address widget not needed in all cases

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/Easy-Digital-Downloads#3685]
This is described here: https://payments.amazon.co.uk/developer/documentation/lpwa/201749840#201750470

We'll possibly need to add it in for the Simple Shipping extension, but we'll be able to get billing address informaiton logged via the data sent back from Amazon (#3686)

**Comment by pippinsplugins** [comment]
Needs to be enabled if taxes are enabled.

**Comment by cklosowski** [comment]
But wouldn't billing information be the record of truth for taxation? not the delivery address?

**Comment by pippinsplugins** [comment]
The address widget only shows one address (I think).

**Comment by pippinsplugins** [comment]
Related #3621

**Comment by pippinsplugins** [comment]
See #3721
