### ISSUE TITLE
Retrieve billing address from Amazon

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/Easy-Digital-Downloads#3686]
Currently we're relying on a partial shipping address for the billing information. We need to update the `scope` used in our token authentication that allows billing address information so we can get rid of the shipping address widget (#3685).

**Comment by pippinsplugins** [comment]
I can't find any way to make it work without the address widget. It always shows me an error if I don't enable the address widget.

**Comment by pippinsplugins** [comment]
Supposedly to enable the wallet without an address all you have to do is include the `onOrderReferenceCreate` callback. Still fails for me.
```
onOrderReferenceCreate: function(orderReference) {
	orderReference.getAmazonOrderReferenceId();
},
```

![screen shot 2015-08-17 at 9 32 22 am](https://cloud.githubusercontent.com/assets/1034109/9307236/e51ffd32-44c2-11e5-9365-bdae6db19f8b.png)

Documentation: https://payments.amazon.co.uk/developer/documentation/lpwa/201749840#201750470

**Comment by pippinsplugins** [comment]
Ok figured it out. Had to remove `amazonOrderReferenceId: edd_amazon.referenceID,`.

**Comment by pippinsplugins** [comment]
@mindctrl and/or @SDavisMedia could you give this a test?

Testing instructions:

1. Disable taxes and make a purchase. The address widget should _not_ be shown.
2. Enable taxes and make a purchase. The address widget _should be_ shown. Full address should show in Billing Address of `View Order Details` once complete.

**Comment by SDavisMedia** [comment]
Alright so the address widget is showing for me with taxes enabled (not showing when taxes are disabled) but the address is not showing when I view order details. I'd wait for @mindctrl's test though because I don't have a real SSL. I just have SSL forced on checkout and WP HTTPS installed to handle the non-secure resources. Not sure if that has anything to do with it. I was able to complete test transactions, though, and no test address was shown in the payment history.

**Comment by pippinsplugins** [comment]
@SDavisMedia not showing in order details even when it was collected on frontend (when taxes are enabled)?

**Comment by pippinsplugins** [comment]
Clarification: it should only ever be shown and collected when taxes are enabled.

**Comment by SDavisMedia** [comment]
Correct. With taxes enabled, the address widget appears on the front-end and a saved address checked: http://glui.me/?i=gvhownf6p7raspj/2015-08-17_at_11.39_AM.png/ I'm just not seeing the address populated on the admin View Order Details screen once the transaction is complete.

**Comment by mindctrl** [comment]
Seeing same thing Sean is. Looks good on front end, but not showing up in the order details in admin.

Also seeing this debug notice: `PHP Notice:  Undefined index: IsSample in /public_html/wp-content/plugins/easy-digital-downloads/includes/gateways/libs/amazon/IpnHandler.php on line 414`

**Comment by pippinsplugins** [comment]
Are you guys testing with SCRIPT_DEBUG enabled?

**Comment by SDavisMedia** [comment]
Wow... okay so it's working perfectly now. Taxes enabled, shows the addresses on the front-end. Complete the transaction and the address fields are populated on the back-end View Order Details.

Absolutely nothing was done different from this morning to now. Maybe @mindctrl was right that they had something going on.

**Comment by pippinsplugins** [comment]
I did re-minify scripts and styles so that could have been it too.

**Comment by SDavisMedia** [comment]
Gotcha. Well all good here. Super smooth.

**Comment by pippinsplugins** [comment]
:+1:
