### ISSUE TITLE
Update Amazon registration URLs for EU and DE

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/Easy-Digital-Downloads#3687]
The links on the `Connect` button for setting up Amazon need to change when it's DE or EU:
[EU only]: in the product configuration, the link "Register with Amazon > Connect Easy Digital Downloads to Amazon" should point to the registration pipeline in Europe, as we don't support this kind of registration.
DE: https://payments.amazon.de/preregistration/lpa
UK: https://payments.amazon.co.uk/preregistration/lpa

**Comment by cklosowski** [comment]
I've updated it to use different urls based on the site base country (like the widget endpoints), however we're awaiting some feedback from the Amazon team to make sure this is 100% correct in implementation.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
Amazon has told us that the query args can be left on the URL but they won't be picked up at this time due to some internal issues.
