### ISSUE TITLE
edd_items_in_cart cookie not removing after checkout

### ISSUE THREAD

**Issue by cspicuzza** [easydigitaldownloads/easy-digital-downloads#3688]
After checkout edd_items_in_cart is not removing itself.  Even if I manually delete it using inspector, it keeps coming back.  The cart appears to be empty but the cookie is still there.  

I'm on a development server with no caching.  I'm using the latest version of EDD and WP.  I also tried using the constant EDD_USE_PHP_SESSIONS set to true and false.  The cookie domain and path look to be correct.

Any ideas?

**Comment by pippinsplugins** [comment]
@cspicuzza That's actually correct behavior. We keep it set so that purchase receipts properly bypass cache.
