### ISSUE TITLE
Unused output in `edd_get_purchase_link()`

### ISSUE THREAD

**Issue by felixarntz** [easydigitaldownloads/Easy-Digital-Downloads#3694]
I just stumbled across something weird:

In [this line](https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/template-functions.php#L185) the function `printf()` is called, however the second and third parameter are never used (since there is no placeholder for them in the first parameter) which makes no sense to me. Not sure if this is a bug or just old code.

I encountered it since a client asked me to replace the "Checkout" text on buttons with a "Go to Checkout" text, so I browsed around and found this. For the actual use case it would be great if we were able to filter the "Checkout" text.

**Comment by JeroenSormani** [comment]
This doesn't seem relevant anymore, the line isn't showing any unused parameters anymore. @felixarntz  can you confirm?

**Comment by PatelUtkarsh** [comment]
Yes line is checked with echo statement.

```						<?php echo '<i class="edd-icon-ok"></i> ' . __( 'Added to cart', 'easy-digital-downloads' ); ?>
```

**Comment by felixarntz** [comment]
Sorry for my late response, yep the issue is gone now.
