### ISSUE TITLE
Sales log entries not deleted when purchase is refunded

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#3698]
When a payment is refunded, the sale log is supposed to be deleted. This is not happening and is very likely one of the causes for incorrect earnings / sales counts (exacerbated by recounting sales and earnings).

We will need to add an upgrade routine to go back through all refunded payments and delete the sale logs.

**Comment by pippinsplugins** [comment]
Related #2815

**Comment by pippinsplugins** [comment]
@mindctrl I'd like you to give this a really thorough once-over.

Here's how I'd recommend testing it.

1. checkout `master`, make some purchases and then refund them. Note how sale logs are _not_ deleted when refunded.
2. checkout `issue/3698` and make a purchase then refund it. Note how sale log is deleted.
3. Run the upgrade routine and confirm that sale log from _1_ is now deleted.
4. Confirm that no other sale logs were deleted.

**Comment by mindctrl** [comment]
@pippinsplugins my upgrade routine isn't completing.

Starts out at:
`http://edd-sl/wp-admin/index.php?page=edd-upgrades&edd-upgrade=remove_refunded_sale_logs`

then:
`http://edd-sl/wp-admin/index.php?page=edd-upgrades&edd-upgrade=remove_refunded_sale_logs&step=2&total=0`

And it goes back to dashboard, the notice is still there. Does same thing if I click again. Are you seeing that?

**Comment by pippinsplugins** [comment]
Do you have any refunded orders?

**Comment by pippinsplugins** [comment]
Oh, the notice will show until the EDD_VERSION number is updated.

**Comment by mindctrl** [comment]
Ah that's right. This looks good to me. Old sales logs are removed properly. No extras were deleted.

**Comment by pippinsplugins** [comment]
Excellent.
