### ISSUE TITLE
Purchase History Table bug

### ISSUE THREAD

**Issue by chcnetconsulting** [easydigitaldownloads/easy-digital-downloads#3701]
Hi,

We have a problem with purchase history, if we want to search for all purchases of one specific email address. The overview (i.e. nr of found records) is correct, but the table doesn't show the selected records. 
isEmail is recognized, but the WP_Query, that has to select the correct records, simply returns ALL of them. It seems to me that WP_Query does not respect the email address filtering.

Do you guys have a solution for that?

Kind regards
Christoph

**Comment by chcnetconsulting** [comment]
Followup:
With this code I was able to fix that email selection issue. meta_key and meta_value stay empty, although email is recognized... Really seems to be kind of a bug?

add_action('edd_pre_get_payments', 'dj_pre_get_payments');
function  dj_pre_get_payments($atts) {
        // Bugfix easy digital download - searching for emails doesn't work
        if (strpos($atts->args['s'], '@')!== false) {
            $atts->args['meta_key'] = '_edd_payment_user_email';
            $atts->args['meta_value'] = $atts->args['s'];
        }
}

**Comment by pippinsplugins** [comment]
The search is working for me without any changes.

What version of EDD are you using?

**Comment by chcnetconsulting** [comment]
2.3. this iis working on another Installation also, but not in this one...
Same Version. Want to debug?
Am 13.08.2015 15:41 schrieb "Pippin Williamson" <notifications@github.com>:

**Comment by pippinsplugins** [comment]
Update to the latest (2.4.2) and see if it still fails.

**Comment by pippinsplugins** [comment]
Closing due to lack of feedback.
