### ISSUE TITLE
Refunding a renewal shouldn't disable the license

### ISSUE THREAD

**Issue by dannyvankooten** [easydigitaldownloads/Easy-Digital-Downloads#3703]
Only if the license is actually expired, it should.

In my case, someone accidentally renewed twice so their expiration date was set to 2 years from now (since our licenses are valid for 1 year). Refunding the second renewal disabled the license, while it should have deducted a year from the expiration date.

**Comment by pippinsplugins** [comment]
@dannyvankooten please  re-open on Software Licensing: https://github.com/easydigitaldownloads/edd-software-licensing/issues

**Comment by dannyvankooten** [comment]
Oopsie :)
