### ISSUE TITLE
PHP Notice:  Undefined index: plugin

### ISSUE THREAD

**Issue by stephywells** [easydigitaldownloads/Easy-Digital-Downloads#3708]
When a plugin is in need of an update, I'm seeing this notice:
PHP Notice:  Undefined index: plugin in /Users/Steve/Sites/wordpress/wp-admin/includes/update.php on line 281

Pull request on the way.

**Comment by pippinsplugins** [comment]
Hi @stephywells, this is actually a WP core issue: https://core.trac.wordpress.org/ticket/31784

I don't see any harm in the PR though so I will go ahead and merge it.

**Comment by stephywells** [comment]
Thanks!
