### ISSUE TITLE
Multiple API pings per page load

### ISSUE THREAD

**Issue by stephywells** [easydigitaldownloads/Easy-Digital-Downloads#3710]
When I view the plugins page, wp_remote_post is triggered twice for each add-on I have installed.
[14-Aug-2015 19:25:08 UTC] https://easydigitaldownloads.com/edd-sl-api/ Content Restriction 
[14-Aug-2015 19:25:09 UTC] https://easydigitaldownloads.com/edd-sl-api/ Manual Purchases 
[14-Aug-2015 19:25:09 UTC] https://easydigitaldownloads.com/edd-sl-api/ PDF Invoices 
[14-Aug-2015 19:25:09 UTC] https://easydigitaldownloads.com/edd-sl-api/ Software Licensing 
[14-Aug-2015 19:25:16 UTC] https://easydigitaldownloads.com/edd-sl-api/ Content Restriction 
[14-Aug-2015 19:25:17 UTC] https://easydigitaldownloads.com/edd-sl-api/ Manual Purchases 
[14-Aug-2015 19:25:17 UTC] https://easydigitaldownloads.com/edd-sl-api/ PDF Invoices 
[14-Aug-2015 19:25:18 UTC] https://easydigitaldownloads.com/edd-sl-api/ Software Licensing 

This is adding a lot of time to the page load. I'm planning on adding more add-ons as well so this will add even more time to my page load.

I'm launching a new plugin and am hoping to use EDD to do it. Before I spend time on adding transients to save the API responses in the EDD_SL_Plugin_Updater class, I want to make sure that's a direction your team is okay with going. I've done this in Formidable in order to reduce the load on our API site as well. Let me know if I can add these transients in. Thanks!

**Comment by pippinsplugins** [comment]
Are you seeing it on every page load or just one time (with follow up loads pulling from cache)?

**Comment by stephywells** [comment]
I'm seeing it on every page load. Is there already some caching in place?

**Comment by pippinsplugins** [comment]
We hook into WP core's transients API.

Do you have `set_site_transient( 'update_plugins', null )` uncommented at the top of the plugin updater class? That would cause it to run on every page load.

**Comment by stephywells** [comment]
No, that line is commented, and I've disabled all other plugins. The transient is getting set twice on the page load, so the remote post is also being triggered twice. In Formidable, I'm saving the response from wp_remote_post into a different transient to prevent any of the add-ons from checking in more than once every 12 or 24 hours. This looks like it would be a lot of strain on the api site.

**Comment by pippinsplugins** [comment]
Do you have object caching enabled from anywhere?

**Comment by pippinsplugins** [comment]
Note: it's NOT supposed to check on every page load.

**Comment by stephywells** [comment]
No caching enabled. This is on a local site so there isn't any hosting caching either.

**Comment by pippinsplugins** [comment]
Are the requests made on every page or just plugins.php?

**Comment by stephywells** [comment]
Only on plugins.php.

**Comment by pippinsplugins** [comment]
Can you install Query Monitor, https://wordpress.org/plugins/query-monitor/,
and see if it's setting transients on every page load?

**Comment by stephywells** [comment]
Yep, it is.

On Mon, Aug 17, 2015 at 4:37 PM, Pippin Williamson <notifications@github.com

**Comment by pippinsplugins** [comment]
That means that something with the object cache on the server is messing up.

Is site on Pagely by chance? I had the exact same thing happen to pippinsplugins.com recently and it was due to a server issue.

**Comment by stephywells** [comment]
No, it's MAMP without any caching setup. But since there will be a lot of server variation that will be triggering the checking, would it be best to have an additional transient layer to save the server response?

**Comment by stephywells** [comment]
I thought I responded to this, but I'm not seeing my response. This is a
local site and not on Pagely. Do you think this checking should allow for
sites with this issue since it could be installed on a wide variety of
servers?

**Comment by stephywells** [comment]
I'm having the same problem on a 1&1 server (not my choice). The plugins page is taking ages to load since there are about 10 EDD plugins. Each one adds a couple seconds to the page load.

**Comment by pippinsplugins** [comment]
Could I get access to it? I have three plus sites with 10-30 add ins and
don't see this.

**Comment by stephywells** [comment]
Sure. Where can I send access?

On Tue, Aug 25, 2015 at 1:41 PM, Pippin Williamson <notifications@github.com

**Comment by chriscct7** [comment]
Send us a ticket at easydigitaldownloads.com/support please :)

**Comment by pippinsplugins** [comment]
Thanks @stephywells, I'm logging in now.
