### ISSUE TITLE
Email template headings should only show if a heading exists

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/Easy-Digital-Downloads#3713]
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/templates/emails/header-default.php#L81-L93

In the default email template, these lines output the email heading. However, some extensions send out emails that don't have a heading defined. Unless we can have a fall back heading or get some way to make it so there always will be one, we should make this section conditional.

The problem is that this section has styles applied to it which make it take up a bunch of space even when no text is present. So the tops of these emails includes an unnecessary amount of white space.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by mindctrl** [comment]
@brashrebel want to test that PR?

**Comment by brashrebel** [comment]
Just tested with Sales Recovery and it worked great. Perfect.

**Comment by pippinsplugins** [comment]
:+1:
