### ISSUE TITLE
Discounts apply on carts for which the items in the cart are not applicable to the discount

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/Easy-Digital-Downloads#3714]
This might be a bug specifically with bundles, but if you make a discount and set it to not apply to a bundled product (and possibly a regular one), then the discount still appears to apply to the cart but correctly doesn't affect the cart totals. 

Example: welcometoedd is invalid for bundles, but it can still be applied to a cart containing a bundle and it looks like it applies, but as you notice it correctly doesn't affect the price:
https://db.tt/qIfcolVG

**Comment by pippinsplugins** [comment]
Related #3097

**Comment by pippinsplugins** [comment]
Invalid I think. It's a bug on the EDD site only. Localhost: 
![screen shot 2015-08-15 at 7 42 51 pm](https://cloud.githubusercontent.com/assets/1034109/9291450/cf45d2fe-4385-11e5-8105-2894d3f19f8b.png)
I don't know why it happens on EDD live, but it's not in core (as far as I can tell.
