### ISSUE TITLE
Error messages after trying to set up my 1st product and setting up funtions.php

### ISSUE THREAD

**Issue by KCHosting** [easydigitaldownloads/Easy-Digital-Downloads#3720]
Warning: include(/home/kchosi4n/public_html/woocommerce/wp-content/themes/WooCommerce/EDD_SL_Theme_Updater.php): failed to open stream: No such file or directory in /home/kchosi4n/public_html/woocommerce/wp-content/themes/WooCommerce/functions.php on line 26

Warning: include(): Failed opening '/home/kchosi4n/public_html/woocommerce/wp-content/themes/WooCommerce/EDD_SL_Theme_Updater.php' for inclusion (include_path='.:/usr/local/lib/php') in /home/kchosi4n/public_html/woocommerce/wp-content/themes/WooCommerce/functions.php on line 26

Fatal error: Class 'EDD_SL_Theme_Updater' not found in /home/kchosi4n/public_html/woocommerce/wp-content/themes/WooCommerce/functions.php on line 31
![edderror](https://cloud.githubusercontent.com/assets/12685026/9301992/b6ff59f6-4487-11e5-8626-e83b5ba83483.png)

**Comment by pippinsplugins** [comment]
@KCHosting That error message is coming from your theme, not Easy Digital Downloads. Please contact the author of your theme.

**Comment by KCHosting** [comment]
Yes, after I tried to edit functions.php as you described. Can you point me again to the link to make the edits from? I went to bed after trying to get this resolved late last night.

**Comment by pippinsplugins** [comment]
Edits to the functions.php file? That's part of your theme.

You can edit it from Appearance > Editor.

**Comment by KCHosting** [comment]
Yes, that's what I was doing based on advise from one of your posts about setting EDD up.
