### ISSUE TITLE
Purchase Shortcode placement on edit screen

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#3726]
Sorry, I missed this issue: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/3339 

Just wondering why something like this wasn't considered.

![screen shot 2015-08-19 at 2 12 41 am](https://cloud.githubusercontent.com/assets/2359131/9350594/d73f31b4-4617-11e5-8031-fef424314f91.png)

That seems like the most logical placement to me. I'm only thinking of this because I honestly I don't like its placement in the Download Settings. It's not a setting and for it to be something that appears after a download is created, I don't think it should be halfway down the screen in a settings metabox.

Thoughts? Close if I'm a weirdo!

**Comment by pippinsplugins** [comment]
I don't really love the current placement, but I have to say that I _really_ dislike that proposal :D

Maybe a better option would be to have a separate metabox for it in the top right?

**Comment by SDavisMedia** [comment]
I don't think it belongs in a meta box at all. It's not a setting. It's updated information that should be 1) clearly presented to the user on save/refresh, 2) easily accessible when visiting the edit screen, and 3) in an area where information about the download (like the permalink) is presented.

**Comment by pippinsplugins** [comment]
Download Stats isn't a setting either yet it has its own box.

**Comment by SDavisMedia** [comment]
Okay well I said my piece, that's all I can do. I don't see the point in moving it from one meta box to another so we can close this issue.

**Comment by pippinsplugins** [comment]
@SDavisMedia sorry if that sounded blunt, didn't mean it that. It's not a setting, that's correct and a good observation. I don't think, however, that meta boxes need to be restricted to settings or "changeable" data.

A metabox is simply a UI separation element that we can use to present information, editable or not.

The point of the issue that you have raised, at least in my interpretation, is that the current position of the short code doesn't make sense as it is not a setting. That's 100% accurate since we currently have it in a box called "Download Settings".

Moving it to the top of the screen and putting it in a box called "Purchase Shortcode" would make logical sense.

The only difference, to me, between putting it in a dedicated box and putting it between the title and content area like your screenshot is simply UI consistency.

A metabox would match WP core UI. A greyed-out input field below the title would not.

**Comment by SDavisMedia** [comment]
I honestly don't think it would need to be in a grayed out input field... or any type of input field for that matter. It could just as easily display exactly like the permalink. http://glui.me/?i=ym2gjzhj6yrck9m/2015-08-19_at_11.21_AM.png/ That matches the UI both visually and logically (based on what it is) than anything else in my opinion.

I do understand that meta boxes don't have to be settings but if you look around in EDD and standard post types, they're literally not being used for anything but settings.

I do think it would be okay in the Download Stats meta box but then the name couldn't be Download Stats. Download Info or something similar would make more sense. But even with that, I am considering how difficult it is for some people to copy text that requires a scroll from a text input. That's bad UI to me.

**Comment by spencerfinnell** [comment]
Is there any information on how often it's actually used? In my opinion it could be put up in the "Help" tab (as it already is I think), or even better add a TinyMCE button that will automatically generate it and put it where the cursor is. Cut out the copy/paste issue once and for all.

**Comment by spencerfinnell** [comment]
Wait.... this already exists on Post/Page screens... why not just put it on downloads as well?

**Comment by SDavisMedia** [comment]
I don't think there's any info on how often it's used. The Help Tab is probably the last place anyone would look, honestly.

We don't need a button to add the shortcode to the download. We need to provide the shortcode to the user once it's generated. There's no other place to get it besides the TinyMCE button on other post types since it has been removed from the download listing (I agree with that change). 

I think it's exactly like the permalink/shortlink presentation, hence my proposal.

**Comment by spencerfinnell** [comment]
If it's not being used to put in the current download, why would they copy/paste it from the Download screen? If they are putting it anywhere else on their site (Post/Page) then they will have the button to find/insert it automatically.

**Comment by pippinsplugins** [comment]
I think @spencerfinnell raises a good point.

Is there anywhere that a short code would be added that does not have the TinyMCE option?

**Comment by SDavisMedia** [comment]
That is absolutely true. No part of you still thinks it should be handed to them somewhere, considering it exists for a published download?

**Comment by SDavisMedia** [comment]
@pippinsplugins Perhaps a developer may want it for some `do_shortcode()` fun? There are functions for that but I do think that if it exists, it should be given to them. I think everyone agreed on that when it was first added to the downloads table.

**Comment by pippinsplugins** [comment]
I'm not suggesting we remove it entirely, but it does interest me to know whether people actually use one vs the other (method for getting the short code).

**Comment by mindctrl** [comment]
People use them in widgets too.

**Comment by pippinsplugins** [comment]
@mindctrl aha! Yes, thank you for reminding me of that. Completely forgot that.

**Comment by mindctrl** [comment]
I like the wider display concept that Sean put forth. I like being able to see the whole shortcode instead of it getting cut off visually, and it makes it easier to know that you've highlighted the whole thing to copy/paste. Maybe another meta box below the description? Maybe time to rethink all of our admin boxes? :)

**Comment by SDavisMedia** [comment]
I've only ever used the TinyMCE button one time in my life (30 years) and that was yesterday lol. I've gone to grab the shortcode at least a few dozen times, though. I just couldn't tell you why... I forget. :see_no_evil:

**Comment by spencerfinnell** [comment]
I've never used either methods. 

Widgets are an interesting scenario, though. I still vote for an editor button. The popup could be altered to display the short code as well (plenty wide enough to allow easy copying) but also allows you to still insert to the download easily.

**Comment by SDavisMedia** [comment]
@spencerfinnell I love that idea.

**Comment by pippinsplugins** [comment]
I've used the TinyMce numerous times, though I'm not really a good test candidate since I've always been familiar with it being there.

@spencerfinnell @SDavisMedia are you guys referring to enabling the Insert Download short code on the Download post type and then moving the short code display into the popup window?

**Comment by spencerfinnell** [comment]
@pippinsplugins Yep

**Comment by SDavisMedia** [comment]
Yea and I do think it makes sense to have it on Downloads. In my themes, I disable the auto output of the button. So for long sales copy people may want to insert it in the content.

The button text is "Insert Download"... don't really wanna screw with that. I feel like it's okay to put the shortcode behind that and just inform anyone who asks about it (will probably be few).

**Comment by mindctrl** [comment]
Hmm... I'm not convinced hiding the shortcode behind an editor button is right.

If I want to use the shortcode in a widget (this happens more than we think I'm sure), I have to edit the product, click the button, grab the shortcode, close the modal, exit the download, possibly contend with a browser warning about leaving an unsaved page, then go to the widget screen to put it where I want it.

I don't see an issue with a shortcode display being on that modal, I'm just not convinced it should be the primary/only place.

**Comment by SDavisMedia** [comment]
I'm 100% sold on adding the Insert Download button to Downloads. That's definitely a separate issue, though.

My heart is still with what I suggested originally. I'm open to the modal, though. I'm gonna be straight up here... I don't see how any solution is more logical than what I suggested.

**Comment by chriscct7** [comment]
I think my thing I don't like about @SDavisMedia's proposal is it takes up alot of room at the top and I'm not sold on how many people actually use it. What I think could be done is a "show shortcode" link, maybe on the bottom of the publish box or something like that where when you click it it expands to open. Just a thought

**Comment by pippinsplugins** [comment]
I don't like hiding it behind the modal for the exact reasons that @mindctrl pointed out.

@chriscct7 I'm 100% with you about the space issue.

What about adding it in the same way as @SDavisMedia proposed but further down, perhaps below the editor?

**Comment by chriscct7** [comment]
I just think that it takes up too much room like that, and its not something I really think the majority of users actually use, and if you get a ton of plugins like (for example) Yoast's SEO plugin that use alot of big metaboxes, then its just more clutter for alot of users. I think a expand to see link is fine, but personally not a fan of the button or the open by defaultness.

**Comment by spencerfinnell** [comment]
What about a button next to the "View Download" and "Get Shortlink" buttons? "Get Shortcode" and it pops up similarly?

But again, it all comes down to how many people actually use it. Could easily be a small plugin for those that miss the meta box.

**Comment by SDavisMedia** [comment]
Thoughts?

![screen shot 2015-08-27 at 9 03 38 am](https://cloud.githubusercontent.com/assets/2359131/9522455/8b9e2e0c-4c9a-11e5-9b09-f57ade299b9d.png)

**Comment by pippinsplugins** [comment]
@SDavisMedia I like that a lot. We should probably change it to `Get Purchase Shortcode` or similar. `Get Shortcode` is a bit too generic.

**Comment by spencerfinnell** [comment]
To me the rich popup still makes more sense so you can configure it. But I think this is also a pretty good solution as well.

**Comment by SDavisMedia** [comment]
@spencerfinnell I think that can still be a separate issue, focusing on providing a way to _build_ a shortcode on download pages just like you can posts and pages. I think this here is more about just providing the default shortcode.

@pippinsplugins PR sent

**Comment by pippinsplugins** [comment]
For no reason other than priority, I'm punting this to 2.8.

**Comment by SDavisMedia** [comment]
refreshed with `release/2.6` just to try an stay up to date

**Comment by SDavisMedia** [comment]
This works just fine still but what really needs to happen, whether the purchase shortcode moves to this location or not, is that it should update the shortcode parameter values based on the settings (think Add to Cart vs. Buy Now). Issue 3996 will address that. These issues should probably be done together.

**Comment by SDavisMedia** [comment]
Let's close this. It's not worth the move and I haven't seen a single person stumble over its placement in 2 years. (I swear it was a daily issue before that, it seems).
