### ISSUE TITLE
RESOLVED! EDD_DB->update() DB error. Duplicate entry for key mail

### ISSUE THREAD

**Issue by rene-hermenau** [easydigitaldownloads/Easy-Digital-Downloads#3727]
User purchased item with wrong spelled mail address test@testr.com

Later user tried to download this items from his account but he was not able due to this wrong address so he created account test@test.com. 

Of course he is still not able to download items from his account because the edd items are still linked to the old account test@testr.com

Now i tried to change the user account of the purchased items to this new created account  test@test.com but edd is throwing an db error and operation is unsuccessfull:

``Duplicate entry 'test@test.com' for key 'email'``

DB operation is:
``UPDATE `awdopye8_edd_customers`
SET `name` = 'chris black', `email` = 'test@test.com', `user_id` = 0
WHERE `id` = '622'``

Screenshot of query monitor:
http://take.ms/GguuE

**Comment by rene-hermenau** [comment]
I had to remove the customer completely and unlink all purchases from him. Than recreate this customer again and the binding to the purchases was successfully.

This error should not happen, at least there should be an error message thrown. Without debug mode on and query monitor i would have not been able to see the error message.

**Comment by rene-hermenau** [comment]
Close it! I tried to change the customer details. Was not aware that i can change the customer easily by just using the drop down menu on the order page. *feeling dumb*

**Comment by pippinsplugins** [comment]
:+1:
