### ISSUE TITLE
WP 4.3 changed wp_new_user_notification()

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#3728]
Before WP 3.4, the `wp_new_user_notification()` function allowed us to pass a text string as the second parameter, such as `Password entered at checkout`.

After 4.3, the second parameter is a boolean on whether or not the email should be sent to the user as well.

We will have to send our own custom email since our customer's are entering their password during checkout.

See this ticket for more info https://secure.helpscout.net/conversation/113669097/15076/

**Comment by chriscct7** [comment]
I disagree. The reason it got removed from core is insecure. Since customers registering at checkout have to type the password in (its not autogenerated), then there's no need to email them the password they just set anyways.

**Comment by pippinsplugins** [comment]
I didn't say that we are going to email the password, just that we need to adjust the email.

**Comment by pippinsplugins** [comment]
We haven't emailed the password for over a year (I think that came out with 2.3).

**Comment by chriscct7** [comment]
I'm confused why we need to adjust the email though. We should just need to set the second param to false.

**Comment by pippinsplugins** [comment]
The email indicates the user needs to set a password. The password is set
on checkout.

**Comment by chriscct7** [comment]
Right, so we don't need to make a custom email, we just need to set the second parameter to 'admin'.

**Comment by pippinsplugins** [comment]
Well maybe. Depends on whether we want the customer to be emailed like they
used to be.

**Comment by chriscct7** [comment]
Before they were just emailed the username they set and told the password was the one they set at checkout. I think we just should kill the notification for users. There's no point to it imo.

**Comment by chriscct7** [comment]
I'm confused since we removed the password, what benefit does it provide to users that we would be updating our code to continue supporting? It's basically an email with just the username they set right?

**Comment by pippinsplugins** [comment]
The password is defined by the customer when they register an account on checkout. It's not auto generated like in core.

**Comment by chriscct7** [comment]
Note: Me and Pippin talked on Slack and the confusion about the ticket has been cleared up

**Comment by pippinsplugins** [comment]
I think we can go ahead and merge this even with the potential backtracking in WP core. My changes will work even if core backtracks.

**Comment by spencerfinnell** [comment]
Link to the trac ticket?

**Comment by chriscct7** [comment]
https://core.trac.wordpress.org/ticket/33654
