### ISSUE TITLE
Default price ID can't be saved if price ID is 0

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#3729]
This is left over from when price IDs changed from starting with 0 to starting with 1.

This ticket has solution: https://secure.helpscout.net/conversation/107252968/13478/

Related #3463 #2958

**Comment by pippinsplugins** [comment]
@mindctrl could you give this a test?

**Comment by mindctrl** [comment]
@pippinsplugins this fix didn't work for the customer the other day. I'll do some more digging.

**Comment by pippinsplugins** [comment]
@mindctrl it fixed it for the customer that @SDavisMedia worked with (ticket linked above). Note that the PR is slightly different than the fix I suggested.

**Comment by mindctrl** [comment]
I see now. Will test.

**Comment by mindctrl** [comment]
@pippinsplugins this works. Customer confirmed today.

**Comment by pippinsplugins** [comment]
Great. Will go out with 2.4.4
