### ISSUE TITLE
Bundled download selections rearranged on save

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/Easy-Digital-Downloads#3731]
If you add downloads to a bundle, the order in which they're displayed is changed on save. For example, say you had four products, 3 downloads and 1 bundle:

- 1 Download
- 2 Download
- 3 Download
- Bundle (consists of the three downloads above)

If you save the three downloads to the bundle in the order 2, 1, 3, they will be rearranged to 1, 2, 3 when you save the bundle.

This is a problem because in all other instances, the order in which you add items is the order that they display elsewhere. As in if you add the individual products to your cart 3, 2, 1, they will show that way at checkout, on the purchase confirmation page, and even in the email. The same behavior is true here. But because they are reordered on save, they will always appear in numerical order.

Relevant code: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/5a68bbde63c1e9e2826f8981e03f1c336d006710/includes/admin/downloads/metabox.php#L228
Reference: http://php.net/manual/en/function.array-values.php

**Comment by cklosowski** [comment]
So, I think this is a UX issue for sure...but we'll have to tackle it as such, in that it's a Chosen issue. Given there are a number of issues with have with Chosen and the multi-selecton option (can't arrange them, cannot use variable pricing, issues with width and placeholders)...I'd propose we take a new approach to the multi-select option of the download list.

Avoid chosen, possibly give a repeatable row system, where we can also allow the selection of price options. What do you guys think about that?

**Comment by shazahm1** [comment]
+1 a thousand times :)

**Comment by pippinsplugins** [comment]
@cklosowski I like that idea.

**Comment by cklosowski** [comment]
Thoughts on this as the solution?

![screen shot 2015-10-30 at 11 35 17 am](https://cloud.githubusercontent.com/assets/1390124/10854672/635f056e-7efa-11e5-92c1-8f49622a451b.png)

**Comment by SDavisMedia** [comment]
@cklosowski I like it! I really don't see the benefits of Chosen for this anyway. Seems logical to switch and also add variable pricing support.

**Comment by SDavisMedia** [comment]
It also solves the problem of people not realizing that it is a search field.

**Comment by pippinsplugins** [comment]
This looks great to me!

Minor note: it is still using `chosen`, it just isn't using a `multi-select chosen` :)

**Comment by cklosowski** [comment]
Right, sorry, still using chosen, just not the multiselect.

**Comment by SDavisMedia** [comment]
Everything is working perfectly for me. :+1:

**Comment by pippinsplugins** [comment]
Works beautifully and soooooo much better.

**Comment by mindctrl** [comment]
Getting an undefined variable on `$key` here: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/commit/640beb03fa504b0bf11a23845ecb7b7899533a82#commitcomment-15221571

**Comment by pippinsplugins** [comment]
@mindctrl try now.

**Comment by mindctrl** [comment]
@pippinsplugins that fixed that, but I do see something else. Can you test to see if adding a new row in the bundle works when you search for an item that isn't in the list of 20 or 30 we pull in? It's like the ajax query isn't firing off to find items not in the pre-populated list.

**Comment by pippinsplugins** [comment]
@mindctrl do you see the same thing in license upgrades of Software Licensing?

**Comment by mindctrl** [comment]
@pippinsplugins no, the search in SL upgrade paths box still works.

**Comment by pippinsplugins** [comment]
@mindctrl Please try `issue/3731`
