### ISSUE TITLE
Reformat the Welcome Page to use core WP markup and styles

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/Easy-Digital-Downloads#3736]
Recently done in FES. Pretty simple to implement.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by SDavisMedia** [comment]
@pippinsplugins This is ready for testing on `issue/3736`.

Cleans up the visual layout and structure, takes advantage of core classes, and fixes the overlapping EDD logo on smaller screens.

**Comment by pippinsplugins** [comment]
Looks excellent. PR against `master` please!

**Comment by SDavisMedia** [comment]
Oops. My branch was based on `release/2.5`. I'll get it sorted in a few.

**Comment by SDavisMedia** [comment]
Done. :+1:

**Comment by pippinsplugins** [comment]
@SDavisMedia Looks like you pulled in the welcome screen text from a previous version. Can you remove that?

**Comment by SDavisMedia** [comment]
@pippinsplugins Not sure I follow. Here are the differences between `master` and `issue/3736`. https://github.com/easydigitaldownloads/Easy-Digital-Downloads/pull/3898/files?w=1

If I'm overlooking something please point it out and I'll surely get it taken care of. But if you're looking at the PR up there, it's looking like certain text replaced other text but it just shifted it around.

**Comment by pippinsplugins** [comment]
No idea what I saw before but looks fine now.
