### ISSUE TITLE
[purchase_link] shortcode text attribute not honored after 2.4.3 update

### ISSUE THREAD

**Issue by felixarntz** [easydigitaldownloads/Easy-Digital-Downloads#3738]
I just noticed that the `[purchase_link]` shortcode does not work properly since the latest 2.4.3 update. I'm using it with a custom "text" attribute, but it is not applied any longer, however it was applied before the update. Right now I'm always seeing the default button text which is stored in the EDD options, regardless of what I specify in the shortcode.

I looked into the code already, but I could not figure out what causes it not to work yet...

**Comment by mindctrl** [comment]
@felixarntz what's your full shortcode look like?

**Comment by pippinsplugins** [comment]
I bet this is only true for buy now buttons and is likely due to https://github.com/easydigitaldownloads/Easy-Digital-Downloads/commit/dc5bdf4db98fdeb00b9279889e211205c43afd81#diff-978209e01c6c9e4491c170874c427461

**Comment by felixarntz** [comment]
@pippinsplugins yes, that was my impression too since I use the `'direct' => true` argument on that shortcode, and the lines you referred to were basically the only ones changed.

My shortcode is `[purchase_link id="342" direct="1" text="Ausweis jetzt bezahlen"]`

**Comment by pippinsplugins** [comment]
Thanks for the PR @felixarntz! We'll test it out!

**Comment by mindctrl** [comment]
Also [reported here](https://secure.helpscout.net/conversation/115201229/15487/).

**Comment by pippinsplugins** [comment]
@mindctrl have you had a chance to test PR?

**Comment by mindctrl** [comment]
@pippinsplugins looks good here.

**Comment by pippinsplugins** [comment]
:+1:
