### ISSUE TITLE
Use is_ssl() instead of $_SERVER["HTTPS"] check

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/Easy-Digital-Downloads#3740]
On some systems the $_SERVER["HTTPS"] variable doesn't get set, and results in some weird cross domain issues or 'bad requests'. It also apparently works better behind proxies ([reference](https://github.com/pippinsplugins/Restrict-Content-Pro/pull/214)).

We use it in `edd_get_current_page_url()`, and a couple other places, I think.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by cklosowski** [comment]
I fear we may have made this obsolete with the recent release in 2.4.4 in issue #3769. We'll just want to be sure that we're still happy with `edd_get_current_page_url()` when this merge is all said and done.

**Comment by mindctrl** [comment]
@cklosowski didn't you merge this in already?

**Comment by cklosowski** [comment]
Yes I did, then I merged in master, which has the release from #3769, which further altered this function. I'm reviewing the merge right now, to make sure we're not seeing any artifacts of a wonky merge.

**Comment by cklosowski** [comment]
yeah merge looks good, i'm closing this one out as the generation of the URLs with these functions has been tested well in the 2.4.4 and 2.4.5 releases.
