### ISSUE TITLE
Changing quantity is broken with custom cart HTML

### ISSUE THREAD

**Issue by atimmer** [easydigitaldownloads/Easy-Digital-Downloads#3741]
When you overwrite the `checkout_cart.php` template with a template of your own and you use a list instead of a table changing the quantity doesn't work.

**Comment by pippinsplugins** [comment]
Looks good to me. We'll get some extra testing on this and then merge it in!

**Comment by pippinsplugins** [comment]
This is working perfectly for me. Merging.
