### ISSUE TITLE
Batch export fails silently occasionally

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#3745]
I've run across several cases where the batch export has failed silently. When this happens, the export file is downloaded fine by contains no data.

I believe the problem is due to the temporary file not being able to be written to / read from properly.

I've seen this 3-4 times now, including once with Commissions.

Let's do a few things:

1. Add a constant or a filter that lets us forcibly disable batch export and fall back to standard export.
2. Let's add some write / read tests to help determine if the file can be created. Perhaps display an error message if a problem is encountered

@cklosowski I would like this to be a top priority when you are back.

**Comment by cklosowski** [comment]
Sounds good. I'll get something going on that.

**Comment by cklosowski** [comment]
@pippinsplugins if you could test out this branch and see what you think. I'm using mamp pro so the easiest way was to change who the apache and mysql services are running as:
![image](https://cloud.githubusercontent.com/assets/1390124/9618404/1bc730cc-50bb-11e5-8fdc-a5c5a2b568f5.png)

My stuff has always run as me...then I changed it to `www` user.

**Comment by cklosowski** [comment]
Added a check so if the resulting range and status return 0 results, we give an error message as well, instead of an empty file.

**Comment by pippinsplugins** [comment]
@cklosowski Good work here.

Could we please make the error match the styling of admin notices?

![screen shot 2015-09-02 at 6 22 45 pm](https://cloud.githubusercontent.com/assets/1034109/9647153/ab698ec0-519f-11e5-9527-aff06b7db50b.png)

**Comment by cklosowski** [comment]
@pippinsplugins yes, do you want it up at the top of the page or inside the `metabox` wrapper? Since we have multiple forms on the page, I thought it would be good to keep it in the same box.

**Comment by pippinsplugins** [comment]
I like it where it is.

**Comment by cklosowski** [comment]
Ok then I'll just update the styles and call it good.

**Comment by cklosowski** [comment]
Ok now the problem is, since it's a metabox, white background...the white background of the error message blends into the metabox:
![image](https://cloud.githubusercontent.com/assets/1390124/9667992/d814e7e6-5233-11e5-90f7-7ec3850a9659.png)


As @pippinsplugins and I have discussed, since multiple export metaboxes can appear on the screen, the error needs to be somewhat inline with the export form, not at the top of the page as it would disassociate the error from the export that was run.

**Comment by cklosowski** [comment]
Here is what we mean by inline:
![image](https://cloud.githubusercontent.com/assets/1390124/9668013/f9085c26-5233-11e5-88dc-51440c4656af.png)

**Comment by SDavisMedia** [comment]
Does it absolutely have to match admin notices? That look feels a bit forced to me. I have an idea that I'll do a quick Photoshop mock up for.

**Comment by cklosowski** [comment]
:+1: I'm open to any suggestions. Would love to see what you come up with. I'm not sold on having to match Admin notice styles. We're pullling them out of their context so I think it's ok to move away from it, personally.

**Comment by SDavisMedia** [comment]
Dang never mind... looks like WP ditched the old light red notices in certain places (like a failed media upload error) and replaced them with the new notice style too: http://glui.me/?i=hwj4opqveqo7hs1/2015-09-03_at_2.14_PM.png/ So never mind my idea.

Is this notice going to appear after a page load or is it a `slideDown()` type thing?

**Comment by cklosowski** [comment]
It's just a `.append()`.

**Comment by SDavisMedia** [comment]
Here's a possibility to completely avoid changing the way the notices look.

![screen shot 2015-09-03 at 2 35 09 pm](https://cloud.githubusercontent.com/assets/2359131/9668770/1dfb5c44-5249-11e5-8088-98c055aefafd.png)

Very similar to what you see [here](http://glui.me/?i=hjz3mpiwiupss4e/2015-09-03_at_2.36_PM.png/) and [here](http://glui.me/?i=9hgq24d938ivfgt/2015-09-03_at_2.37_PM.png/).

**Comment by SDavisMedia** [comment]
I was too aggressive with the padding up there. 

![screen shot 2015-09-03 at 2 38 08 pm](https://cloud.githubusercontent.com/assets/2359131/9668832/72d065fc-5249-11e5-8587-0d65f182c3e9.png)

**Comment by pippinsplugins** [comment]
I love that.

**Comment by cklosowski** [comment]
:+1: Styles pelase!

**Comment by SDavisMedia** [comment]
Sweet! This notice is still inside of the meta box, just made too look like it's not.

Wrap the notice itself in an additional `div` and give it a class. I went with `notice-wrap`. Then apply this CSS:

```
.notice-wrap {
    background-color: #f4f4f4;
    padding: 12px 12px 4px;
    margin: 20px -12px -23px;
    border-top: 1px solid #eae9e9;
}```

Ummm I actually think that was it.

**Comment by cklosowski** [comment]
Nice, I'll add that in and test it out

**Comment by cklosowski** [comment]
Love it:
![image](https://cloud.githubusercontent.com/assets/1390124/9669300/feefa9da-523a-11e5-9b45-b89dfee0a405.png)

@pippinsplugins ?

**Comment by cklosowski** [comment]
With this, do you think maybe we could add some verbage for success too? That gives a notice that the export is being downloaded...however if it fails to, `click here` to download it?

**Comment by SDavisMedia** [comment]
Not sure what makes the bottom margin negative not work (leaving the white space below the notice area). If the negative bottom margin is in place properly and it's just not working, change its value to 0 (to ensure the margin is forced visible for everyone) and consider applying a bottom border the same color as the top border.

**Comment by pippinsplugins** [comment]
For success I don't think there is any need. The big in-your-face download dialog is pretty clear.

**Comment by pippinsplugins** [comment]
If it fails, however, that is a good point. Maybe there should be a dialog.

**Comment by cklosowski** [comment]
Maybe we start with this, we can add success in later if this doesn't fix it for people. The framework is in place for a successful download:

**Comment by pippinsplugins** [comment]
Sounds good to me.

**Comment by cklosowski** [comment]
Ok how's this look @pippinsplugins @SDavisMedia 

In progress:
![image](https://cloud.githubusercontent.com/assets/1390124/9672713/bed8e3b8-5251-11e5-82ff-f68ba8dc50fe.png)

Error:
![image](https://cloud.githubusercontent.com/assets/1390124/9672715/c531830a-5251-11e5-932b-f3a7bcbe90c7.png)

**Comment by pippinsplugins** [comment]
I really like that.

**Comment by cklosowski** [comment]
tested out Mailchimp and commissions. Apart from some small Style updates, it still functions perfectly.

**Comment by SDavisMedia** [comment]
Love it, @cklosowski.

**Comment by cklosowski** [comment]
Ok this is ready for testing. We'll have some small updates for the Mailchimp and Commissions extensions once it's out, but I'm ready to call this 'Ready for testing'

**Comment by pippinsplugins** [comment]
Works perfectly for me. Merging.
