### ISSUE TITLE
Missing a ton of actions regarding the change of earnings/sales of products

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#3748]
Logging this so I remember to fix this later. Noticed this while working on some FES bug fixes and its something I want to work on fixing.

Right now it is incredibly difficult to run an action on the action of increasing/decreasing the sales/earnings of downloads. There's no hooks anywhere useful for this, making extensions like FES and Commissions work unnecessarily hard to run actions when trying to tie the value of a user to a download.

We should add hooks (so far):
Download class:
- increase_sales()
- decrease_sales()
- increase_earnings()
- decrease_earnings()

In payments actions:
- right below edd_increase_purchase_count() in edd_complete_purchase()
- right below edd_undo_purchase() in edd_undo_purchase_on_refund()

In payments functions:
- right below edd_undo_purchase() in edd_delete_purchase()
- right below edd_decrease_purchase_count() in edd_undo_purchase()

**Comment by pippinsplugins** [comment]
We should have these as separate actions. Up until now, we have relied on `edd_complete_purchase` for this.

**Comment by pippinsplugins** [comment]
@chriscct7 Review #4558 for me?
