### ISSUE TITLE
Quick editing categories and tags doesn't work

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/Easy-Digital-Downloads#3751]
When trying to quick edit categories or tags, this error pops up in the console.

`Uncaught ReferenceError: inlineEditPost is not defined in wp-content/plugins/easy-digital-downloads/assets/js/admin-scripts.min.js?ver=2.4.3 line 1`

New install, default theme, only EDD active. With script debug enabled, it points to here:
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/2.4.3/assets/js/admin-scripts.js#L1056-L1057

**Comment by pippinsplugins** [comment]
:+1:
