### ISSUE TITLE
Checkout Form Field/Label Review

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/Easy-Digital-Downloads#3754]
Gonna try not to be longwinded here. 

The way we handle the HTML and CSS for some of the checkout fields needs improvement. One very specific case is with the Agree to Terms checkbox and label.

Throughout the checkout form, we put labels above text box inputs (name, email, etc.) and that's totally fine. It's a logical HTML flow. Then we wrote CSS for that HTML structure which is also fine. But when we got down to the Agree to Terms checkbox and label (typically the only checkbox on the form), instead of taking a logical approach, we just matched the already established structure.

The label is above the checkbox in the HTML flow but we want it displayed to the right of the checkbox. To make that happen, we then right somewhat aggressive CSS to force the alignment. The better solution would have been to allow the checkbox to be above the label in the HTML flow. The consistency across _different types_ of inputs/labels was not that important.

Because of the approach we took, extensions like EDD MailChimp that add a checkbox and label to the checkout form have to decide between an illogical HTML structure (which no one is going to naturally do at first) or having the correct structure and being inconsistent with the Agree to Terms elements. We can see that causing a problem here: https://github.com/easydigitaldownloads/edd-mail-chimp/issues/2

Because this issue will never go away unless we fix it, I want to get it right in core and just deal with the consequences. And I'd also like to review the rest of the HTML and CSS of the checkout form and make sure it's truly designed to be extensible without unnecessary sacrifices in HTML structure or corrective CSS.

---

- [x] Find all extensions that add a checkbox to the checkout form

**Comment by pippinsplugins** [comment]
Let's do it.

We could include a little CSS to help with backwards compatibility that targets the previous HTML structure. If we can make it appear that no changes were made for most sites, the better.

**Comment by SDavisMedia** [comment]
I agree totally. Sweet deal.

**Comment by SDavisMedia** [comment]
Themes overriding the edd.css file or themes/plugins attempting to correct the checkbox/label layout with CSS or using the wrong structure:

- [ ] Digital Store

**Comment by SDavisMedia** [comment]
@easydigitaldownloads/core-devs I've checked every EDD theme I have installed (all of the popular ones) as well as everything I know of that adds a checkbox and label above the purchase button on checkout. The Agree to Terms elements and newsletter elements are all I'm tracking. Anything else? Testing is appreciated.

Also, there were "tax optin" checkbox/label styles in the CSS file. Research says this option no longer exists. Can someone confirm that?

**Comment by SDavisMedia** [comment]
Cc: @spencerfinnell

**Comment by spencerfinnell** [comment]
Can these be wrapped in a `div` too? They are already siblings of a `div` so shouldn't affect any existing stuff.

And a class with dashes if I'm being picky (which I am)

**Comment by SDavisMedia** [comment]
@spencerfinnell it doesn't appear to affect anything else. Try that.

**Comment by pippinsplugins** [comment]
Merged in but open for final testing.

**Comment by cklosowski** [comment]
This has been runnig for 2 weeks, i'm closing it as I think we're good here.
