### ISSUE TITLE
Add drag-and-drop to files

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#3760]
We added drag-and-drop ordering to variable prices, now it's time to add the same to the files.

**Comment by pippinsplugins** [comment]
PR from @ghost1227 works great for me.

**Comment by cklosowski** [comment]
PR works great here too. just waiting for the PR to be updated with `release/2.5` so it merges cleanly and we'll go from there.

**Comment by cklosowski** [comment]
@mindctrl You are really good at breaking changes in this area :P could you play with this too?

**Comment by pippinsplugins** [comment]
@mindctrl @SDavisMedia we need both of you to test this before we release beta.

**Comment by mindctrl** [comment]
Looks good here. Tried lots of reordering, adding, removing, testing with Software Licensing, changing file source for updates in Software Licensing, etc. It all worked fine.

**Comment by cklosowski** [comment]
Closing this out.

**Comment by pippinsplugins** [comment]
The `ID` column doesn't show the proper IDs after a save. It always reverts to 0, 1, 2, 3, etc.

**Comment by pippinsplugins** [comment]
Nevermind, false alarm.
