### ISSUE TITLE
Incoherent estimate of revenue/sales in report when toggling "taxes"

### ISSUE THREAD

**Issue by vpratfr** [easydigitaldownloads/easy-digital-downloads#3762]
Hi,

The report for earnings and sales gives different estimations when checking/unchecking the "Exclude taxes" checkbox.

In the screenshots below, notice that the estimated number of sales is different between the 2 which leads of course to a different revenue estimate.

The estimated number of sales should be the same with or without taxes of course.

Here is with taxes:

![image](https://cloud.githubusercontent.com/assets/2526465/9679503/5ba9b99a-52ef-11e5-8b7b-d58826721dbb.png)

Here is without taxes:

![image](https://cloud.githubusercontent.com/assets/2526465/9679492/3b279f34-52ef-11e5-8da8-76a7428c98fc.png)

**Comment by pippinsplugins** [comment]
Huh . . . that's interesting and clearly not right.

**Comment by cklosowski** [comment]
I'm seeing the proper calculations, my sales counts don't change when I do this.

@vpratfr can you verify if this is still an issue on the latest EDD?

**Comment by cklosowski** [comment]
Punting until we get some more feedback here. I'm not able to replicate this behavior.

**Comment by cklosowski** [comment]
Closing for lack of feedback.
