### ISSUE TITLE
EDD_Payment_Stats class doesn't take into account fees added via Fees API

### ISSUE THREAD

**Issue by MythThrazz** [easydigitaldownloads/easy-digital-downloads#3763]
We've noticed that the discounts applied with EDD Discounts Pro are not reflected in the Earnings By Category report which uses the EDD_Payment_Stats class (see #3636 ). 

The problem is that the get_earnings() method doesn't allow to filter the earnings and take the discounts into account. 

To fix this probably the changes in both the EasyDigitalDownloads (new filters) and EDD Discounts Pro (applying the discounts) are required.

**Comment by pippinsplugins** [comment]
@MythThrazz Are you seeing this on `get_earnings()` for a specific product or global store earnings?

**Comment by MythThrazz** [comment]
@pippinsplugins It's for the specific product.

**Comment by pippinsplugins** [comment]
@MythThrazz Ah I see what you mean.

@chriscct7 does Discounts Pro set the `download_id` for fees yet? I forget if that's done or not.

**Comment by MythThrazz** [comment]
@pippinsplugins Is there any progress on that?

**Comment by pippinsplugins** [comment]
@MythThrazz Not yet, sorry.

**Comment by pippinsplugins** [comment]
Milestoned for 2.6

**Comment by cklosowski** [comment]
@pippinsplugins @chriscct7 take a look at that commit, do you think those filter params are enough to do what is needed inside plugins like Discounts Pro? There isn't a great way for Core to determine actions to take, so I think adding filters and having the extensions do the work themselves is the best appraoch.

**Comment by pippinsplugins** [comment]
@cklosowski I don't think it should be on Discounts Pro to adjust the earnings. Instead core should automatically include fees / discounts in the earnings calculation when those fees are assigned a download ID.

**Comment by cklosowski** [comment]
@pippinsplugins we'd have to go by 'cart_details' fees, not fees added with a download ID. There's no way to tell for sure if a regular fee with a download ID is supposed to go with a cart item specifically if there are variable prices involved.

We can iterate through the cart details and get an one specific cart items fees though. I'll code that up. but the filters will stay in place I think to facilitate anyone adding an item fee, without attaching it to an item (in case someone is doing this).

**Comment by cklosowski** [comment]
@pippinsplugins Ok, added the fees calculation to the download specific earnings stats...however I'm not positive doing this for the non-specific ones is going to very performant...

**Comment by cklosowski** [comment]
At this point I think only supporting the fees modifications to the `get_earnings

**Comment by pippinsplugins** [comment]
@cklosowski I concur.

**Comment by cklosowski** [comment]
ok @easydigitaldownloads/core-devs this is ready for some testing then.

**Comment by pippinsplugins** [comment]
This looks good to me, merged into `release/2.6`.

**Comment by SDavisMedia** [comment]
Looking good for me. The only issue is the average earnings data doesn't account for fees. Opening a separate issue for that, though.
