### ISSUE TITLE
Help resolving Warning: session_start(): The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in wp-content/plugins/easy-digital-downloads/includes/class-edd-session.php on line 288

### ISSUE THREAD

**Issue by Hanistips** [easydigitaldownloads/Easy-Digital-Downloads#3768]
Hello.
So I'm getting this message above my home page.
and I cant visit other pages in my website.

THE MESSAGE: 
Warning: session_start(): The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in /home/*****/public_html/wp-content/plugins/easy-digital-downloads/includes/class-edd-session.php on line 288

****************************
Adding...

define( 'EDD_USE_PHP_SESSIONS', false) to wp-config.php

Is not helping at all.

**Comment by pippinsplugins** [comment]
Please go ahead and open a support ticket at https://easydigitaldownloads.com/support
