### ISSUE TITLE
edd_get_current_page_url() returns primary site URL in multisite with sub domains

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#3769]
I don't know if this is always the case, but I have at least one reported case of the `edd_get_current_page_url()` returning the primary site URL instead of the current site when in a multisite environment running subdomains.

For example, site is running at `store.domain.com`. On checkout, instead of returning `store.domain.com`, it is returning just `domain.com`.

This was causing the remove from cart links to not work.

See [ticket](https://wordpress.org/support/topic/remove-link-in-checkout-missing-subdomain) on WordPress.org for more info.

**Comment by cklosowski** [comment]
@pippinsplugins why aren't we using something like `site_url()` for the base? The real problem on subdomain multi-site installs is that the `$_SERVER['SERVER_NAME']` variable is pulled from the vhost configuration, and many times, that is simply the primary domain name, as the subdomains are wildcards, there is not a config file for every subdomain.

**Comment by cklosowski** [comment]
The detail is that on things like Apache `$_SERVER['SERVER_NAME']` pulls from the `ServerName` value in the VHOST config.

**Comment by pippinsplugins** [comment]
I honestly don't remember why `site_url()` wasn't used since the beginng.

**Comment by pippinsplugins** [comment]
We also have issues with the `edd_get_current_page_url()` function returning a port number, such as in this ticket: https://secure.helpscout.net/conversation/118695079/16322/

**Comment by pippinsplugins** [comment]
@cklosowski Just had another report of an issue with this (see ticket above). Let's get this fixed up and then shipped ASAP.

**Comment by chriscct7** [comment]
So there's a couple more bugs here (most of these are edd_get_checkout_uri() vs edd_get_current_page_url()) that need to be fixed (migrating over from the HelpScout ticket): 

1. When edd_get_current_page_url() calls home_url on the frontpage it should return right after that. Instead it continues on, and would therefore end up with a final url like: http://www.example.com://www.example.com

2. Despite the fact these functions are used to retrieve urls interchangeable on pages that need cache bursting (ex: the remove action link if/elses between the two), nocache is not available on edd_get_current_page_url() when it should be

3. Again despite the fact these functions are used interchangeably, they are significantly different in how they create a link. This is a problem.

4. We're lacking unit tests on both of these two functions which are pretty major functions in EDD in terms of how many other functions rely on these and the functionality they provide. We're for sure missing one on edd_get_current_page_url() where the page requested from is the homepage as it should have caught that bug if the unit test existed/was setup correctly

5. Finally the way we do SSL detection is completely different between edd_get_current_page_url() and edd_get_checkout_uri(). If possible, these differences should be minimized as much as possible.

**Comment by pippinsplugins** [comment]
Excellent points @chriscct7, let's fix it.

WP core testing suite provides a nice `goto()` helper function that we can use to test these.

**Comment by cklosowski** [comment]
No need for high priority, it's marked as urgent and is on my list for today to tackle ;)

**Comment by pippinsplugins** [comment]
@cklosowski I'm still seeing `nocache=true` appended to the remove URLs even when `No cache on checkout` is disabled.

**Comment by pippinsplugins** [comment]
It's hardcoded into `edd_remove_item_url()` at the moment.

**Comment by pippinsplugins** [comment]
I suppose that doesn't hurt anything so we can leave it there, but shouldn't it be a timestamp so that the URL changes?

**Comment by pippinsplugins** [comment]
Actually, we should leverage the new `edd_add_cache_busting()` function. Right now we retrieve the current URL, which has an option to add cache busting to it. Instead of adding the arg manually, let's pass the remove URL through `edd_add_cache_busting()`. That way it's done in the same place across the system.

**Comment by cklosowski** [comment]
@pippinsplugins the time was a wrong assumption on my end. nocache is a variable that caching mechanisms listen to, and `true` is the correct standard on that. not a timestamp, that was my bad.

**Comment by cklosowski** [comment]
Ok updated @pippinsplugins take a look, making a PR for this.

**Comment by pippinsplugins** [comment]
Looks good :+1:

**Comment by cklosowski** [comment]
@mindctrl mind taking a few minutes to test out general usage of this PR? Things like remove URLs in chckout and widget, making sure ajax works accross the board, etc?

**Comment by mindctrl** [comment]
@cklosowski this looks good to me. Couldn't break anything.

**Comment by pippinsplugins** [comment]
Everything has worked in my testing too.

**Comment by cklosowski** [comment]
Sweet, @pippinsplugins can you merge in to master then?

**Comment by pippinsplugins** [comment]
Holding for final testing from @SDavisMedia

**Comment by SDavisMedia** [comment]
@pippinsplugins This is gonna take me a bit to get set up. I don't have the right kind of MS environment. Trying to get a new test area set up now.

**Comment by pippinsplugins** [comment]
:+1:
