### ISSUE TITLE
Add extra meta key for downloads that are free/price 0.00

### ISSUE THREAD

**Issue by kiarashi** [easydigitaldownloads/Easy-Digital-Downloads#3775]
Is it possible to add an extra meta key for downloads that don't have a price (are free)?

I'd like to display downloads that are free in a seperate section on my website. But I'm having troubles displaying it with the usual Order & Orderby Parameters from Wordpress.

**Comment by mindctrl** [comment]
@kiarashi the fastest way from a technical perspective is to just add them to a specific category or tag, unless you have another reason to add extra meta. If you have any other questions, feel free to open a [support ticket](https://easydigitaldownloads.com/support/).

**Comment by kiarashi** [comment]
Would it be possible to do it with meta_query then?

	'meta_key'   => 'edd_price',
	'orderby'    => 'meta_value_num',
	'meta_query' => array(
		array(
			'key'     => 'edd_price',
			'value'   => ?
			'compare' => 'IN',
		),
	),

When I used value 0 or 0.00 it didn't quite work. Do you perhaps have an idea what I should use as a value? If not, it's not such a bad idea to use an extra category. :)

**Comment by pippinsplugins** [comment]
Try with `'compare'=>'>'` and `'value'=>0`

**Comment by kiarashi** [comment]
Sadly that doesn't work. 

I looked into the database with phpmyadmin and noticed there's no edd_price meta field for items with a price tag of 0/0.00. That's probably why it won't work.

**Comment by pippinsplugins** [comment]
Is it a single or variable priced item?

**Comment by kiarashi** [comment]
It's single.

**Comment by pippinsplugins** [comment]
Save the price as 0.00 instead of 0. That should add the meta key

**Comment by kiarashi** [comment]
So simple; worked flawlessly. Thank you!

**Comment by pippinsplugins** [comment]
Glad to hear it!
