### ISSUE TITLE
Add extension update information to system info

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/Easy-Digital-Downloads#3776]
Conversation started here: https://github.com/easydigitaldownloads/EDD-Site/issues/744

This is just useful information to have in the system info when working in support. If an EDD extension needs an update, let's show that. 

`Easy Digital Downloads - Some Extension: 1.2.3 (needs update)`

Or something similar to that. As of now, unless we know the current version number off the top of our head, we have to go find the extension and check. Maybe we can even show what the current version number is.

**Comment by ghost1227** [comment]
AWESOME idea! Done!

**Comment by SDavisMedia** [comment]
Thanks, @ghost1227!

**Comment by cklosowski** [comment]
Leaving 'Needs Testing' since we're so far out. Will remove label and close once we're closer to release.

**Comment by cklosowski** [comment]
yeah i'm loving this update to the system info. Nice work @ghost1227, closing this one out for the cycle.
