### ISSUE TITLE
Credit card expiration year should allow more than 10 years out

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/Easy-Digital-Downloads#3779]
Relevant code: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/checkout/template.php#L272

**Comment by chriscct7** [comment]
Is there a reason it needs to be moved out longer? Most credit cards expiration dates fall within 3 years of card issuance. If anything, the checkout field for cc expiration date year should be shortened to current - 3 years from now, with a filter to let those who (for some reason) need longer ranges have tem

**Comment by pippinsplugins** [comment]
@chriscct7 See https://secure.helpscout.net/conversation/118743657/16337/

**Comment by SDavisMedia** [comment]
@chriscct7 Doesn't hurt anything at all and prevents that. ^^^

**Comment by chriscct7** [comment]
It makes for a longer dropdown which is annoying. The longest a debit card can have is 30 years (PayPal's self issued debit card)

On a second note here, is the UI better to have 30 years in a dropdown, or the number 20 and a text/number input for the last 2 years?

**Comment by pippinsplugins** [comment]
I don't see a longer drop down as a negative here.

**Comment by cklosowski** [comment]
Yes, I'm with the idea that this is still a dropdown. We can revisit at a later date.
