### ISSUE TITLE
Improve the check for receipt visibility

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/Easy-Digital-Downloads#3781]
There are cases where our receipt visibility check fails. I've opened some tickets in other repos, but ultimately this is an EDD core issue.

References:
https://github.com/easydigitaldownloads/edd-free-downloads/issues/18

https://github.com/easydigitaldownloads/edd-auto-register/issues/8

What I've found is that the receipt isn't visible on the purchase confirmation screen if a purchase is attached to a user account when purchased while logged out. This happens with Auto Register and with Free Downloads. Customers come to the site, don't log in, and purchase things with the email address of their existing user account.

The part of our check that fails is the `$customer_id` check here: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/2.4.3/includes/shortcodes.php#L653

I have a proposal for fixing this in an incoming PR. Definitely needs more eyes on it.

**Comment by pippinsplugins** [comment]
@mindctrl I would LOVE to see this improved and the proposal looks good. I left a few comments on the PR for you.

**Comment by pippinsplugins** [comment]
Looking really good though I have found a bug.

1. Make a purchase as a guest
2. Make a new purchase as a guest but create an account during checkout
3. Visit purchase history and click View Order Details on the purchase made in step 1. It cannot be viewed.

**Comment by pippinsplugins** [comment]
Wait, maybe ignore me. Might have confused myself. Testing again.

**Comment by pippinsplugins** [comment]
All clear!

**Comment by pippinsplugins** [comment]
This looks perfect.

@mindctrl Could you give this one more test now that @cklosowski has added his changes as well?

Note: I've merged `master` into this so you will see the account verification stuff too.

**Comment by SDavisMedia** [comment]
I was able to replicate the issue on master testing with Free Downloads and then confirm that it works properly on EDD `issue/3781`. :+1:

**Comment by pippinsplugins** [comment]
Merging.
