### ISSUE TITLE
Undefined Indexes when assigning new user ID to customer details

### ISSUE THREAD

**Issue by christ0ph3r** [easydigitaldownloads/easy-digital-downloads#3784]
There is 6 undefined index errors when debug is on.  To repeat this error go to a customer and disconnect the user.  Then assign a new user and you will see the errors.

**Comment by christ0ph3r** [comment]
Notice: Undefined index: line1 in  in ../wp-content/plugins/easy-digital-downloads/includes/admin/customers/customer-actions.php on line 86

Notice: Undefined index: line2 in ../wp-content/plugins/easy-digital-downloads/includes/admin/customers/customer-actions.php on line 87

Notice: Undefined index: city in ../wp-content/plugins/easy-digital-downloads/includes/admin/customers/customer-actions.php on line 88

Notice: Undefined index: country in ../wp-content/plugins/easy-digital-downloads/includes/admin/customers/customer-actions.php on line 89

Notice: Undefined index: zip in ../wp-content/plugins/easy-digital-downloads/includes/admin/customers/customer-actions.php on line 90

Notice: Undefined index: state in ../wp-content/plugins/easy-digital-downloads/includes/admin/customers/customer-actions.php on line 91

**Comment by cklosowski** [comment]
Fixed this along side #4777

**Comment by michaelbeil** [comment]
Can confirm that there are no notices when disconnecting a customer from a user account and then connecting the customer to a new user account.

**Comment by SDavisMedia** [comment]
Replicated the 6 notices. Can't replicate on `issue/4777`. :+1:
