### ISSUE TITLE
window.location.reload() not executed when removing a 100% discount

### ISSUE THREAD

**Issue by felixarntz** [easydigitaldownloads/Easy-Digital-Downloads#3788]
I encountered an issue where the `window.location.reload()` that is supposed to happen when removing a 100% discount does not get executed.

See [this line](https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/assets/js/edd-checkout-global.js#L283): The problem happens when using a different decimal separator other than the dot (for example in German it would be `0,00`) - this setting is not honored here. An alternative solution, bypassing the need to honor the setting would be to check the `data-total` attribute of the node instead of the node text since this is always a non-formatted number.

**Comment by pippinsplugins** [comment]
Thanks for the report! We'll get it fixed!

**Comment by ghost1227** [comment]
@pippinsplugins Problem with using the `data-total` attribute is that at present it doesn't seem to take discounts into account. In other words, if I have a $1.00 item in the cart, and add a 100% discount, the `data-total` attribute still shows as `1`.

**Comment by pippinsplugins** [comment]
That should be fixed then :)

**Comment by pippinsplugins** [comment]
Let's get this in for 2.5.8

**Comment by cklosowski** [comment]
👍

**Comment by pippinsplugins** [comment]
PR works perfectly.
