### ISSUE TITLE
Remove 'Confirm Password' field in standard checkout template

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/Easy-Digital-Downloads#3794]
There has been a movement for a better UX when it comes to entering passwords, and the new trend is to not have a confirm field, but to also include an `eye` icon, to unmask the password if the user requests to. Mail chimp does this for logging in, but it's also used on registration forms. We should do this to reduce the friction of signing up for an account.

![screen shot 2015-09-11 at 7 57 04 pm](https://cloud.githubusercontent.com/assets/1390124/9829599/6bc5bc04-58bf-11e5-894c-f1ef48f6a972.png)

![screen shot 2015-09-11 at 7 57 08 pm](https://cloud.githubusercontent.com/assets/1390124/9829602/6eb0c508-58bf-11e5-9151-384033bf43ba.png)

**Comment by michaelbeil** [comment]
:+1:

**Comment by pippinsplugins** [comment]
I'd suggest that we avoid showing exact steps needed to make a strong password and instead show a general strength indicator like WP core. At least in my opinion, it seems much less overwhelming to the user.

**Comment by pippinsplugins** [comment]
We can probably use core's password JS / HTML even to make use of the generator and indicator.

**Comment by cklosowski** [comment]
Yeah, I was just giving an example. Not a specific guideline of how this should play out.

**Comment by pippinsplugins** [comment]
This and #3732 are both resolving the same issue in slightly different manners. Closing this in favor of #3732
