### ISSUE TITLE
Settings, Reports, Tools admin page need headings

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#3795]
Just noticed that the Settings, Reports, and Tools admin pages do not have headings. I believe they should. On some screen sizes, you wouldn't even know where you are in the dashboard unless you were already familiar with the UI.

![screen shot 2015-09-13 at 2 28 35 am](https://cloud.githubusercontent.com/assets/2359131/9835733/7f3f938a-59bf-11e5-82a8-e0e9b86c6ead.png)

**Comment by pippinsplugins** [comment]
I _think_ they used to but we removed them because of the real estate they take up. Not opposed to playing with re-adding them.

**Comment by SDavisMedia** [comment]
@ghost1227 I think they should be branded. If the admin page is not directly tied to an EDD custom post type, the verbiage should connect it to EDD. Which means we should look at all of the admin pages, like Customers. Right now, the Extensions page is the only one with a branded heading.

**Comment by ghost1227** [comment]
@SDavisMedia Using full name would make for some LONG titles... using 'EDD' would cause consistency issues. What are you anticipating?

**Comment by zackkatz** [comment]
Having a horizontal logo doesn't take much space and enforces branding. Here's what I did with IDX+:

![](https://www.evernote.com/l/AATnnaWw0FtHO44I8H9LU2ZsCkZcCC3TG0QB/image.png)

**Comment by SDavisMedia** [comment]
I do something similar in Volatyl.

![screen shot 2015-09-13 at 7 56 20 pm](https://cloud.githubusercontent.com/assets/2359131/9840094/91453fa2-5a51-11e5-98cb-92f4c080ee96.png)

I don't think branding with graphics is necessary, though. I think "Easy Digital Downloads Settings" is acceptable. Longer than normal, sure. But I think that just comes with having a long name.

Thoughts? @cklosowski @mindctrl @pippinsplugins

**Comment by spencerfinnell** [comment]
Agreed just using the full name seems like the best option. Not sure about a logo.

**Comment by chriscct7** [comment]
The graphics is cool, but if its done, it needs to be done via a helper
function where the string for the header is sent in, that way extensions
can easily call a helper function to output the page title and graphic on
their pages, so if in the future we want to drop the logo or change it, it
doesn't break anything

**Comment by SDavisMedia** [comment]
To be clear, I'm not in favor of a graphic.

**Comment by ghost1227** [comment]
A significant part of WHY EDD is designed the way it is comes down to maintaining a uniform appearance with WordPress core. Core doesn't use graphics, I can't imagine us doing it either.

**Comment by SDavisMedia** [comment]
Agreed.

**Comment by spencerfinnell** [comment]
@ghost1227 @SDavisMedia Agreed.

**Comment by chriscct7** [comment]
Fair enough, my point was more of if we did, it needed to be designed in a
way that would make it easy to be uniform. That being said at some point we
might want to consider helper functions for titles (just in case we change
our mind on this in the future or need to do some a11y stuff), for this and
also for registering submenu items since we're thinking of splitting those
up

**Comment by ghost1227** [comment]
@chriscct7 what are you envisioning? I can't think of anything that'd be more efficient than a simple filter... and even that seems excessive for this.

**Comment by chriscct7** [comment]
Sorry if I didn't make that more clear: If we're not doing icons, then there's no point to a helper on the menu titles.

**Comment by pippinsplugins** [comment]
While graphics work really well, I agree that they do not jive well with core experience, so :-1: from me on graphics.

**Comment by ghost1227** [comment]
We could do something like this...
![](https://s3.amazonaws.com/f.cl.ly/items/022W0F0y1s1a2a1b383C/Image%202015-09-16%20at%206.48.58%20PM.png)

**Comment by pippinsplugins** [comment]
I like that @ghost1227 

For small screenshots, we could either hide the title or force it to sit above the tabs.

**Comment by ghost1227** [comment]
I'll adjust the PR.

**Comment by ghost1227** [comment]
@pippinsplugins @SDavisMedia PR updated

**Comment by ghost1227** [comment]
Also added a class to facilitate adjusting it on mobile... feel free to tweak though!

**Comment by SDavisMedia** [comment]
Why are we putting the heading beside the tabs? It already has a place to go and it does not take up much real estate... no more than any other heading does. I don't understand what we're doing here.

**Comment by pippinsplugins** [comment]
I'm fine with either.

**Comment by mindctrl** [comment]
I'm with Sean. I like headings at top like most/rest of core does.

**Comment by spencerfinnell** [comment]
Agreed it should be on top, and I think it should be "Easy Digital Downloads - Settings", or just "Settings"

**Comment by sunnyratilal** [comment]
@SDavisMedia PR ready.

Question about the `nav-tab-wrapper` though, is that _supposed_ to be a `h1`?

**Comment by SDavisMedia** [comment]
@sunnyratilal Reports and Tools would need this treatment as well.

As for `nav-tab-wrapper`, I'm almost positive that should be an `h2`. I've always used `h2` in my own projects and I learned how to do it from multiple resources floating around.

**Comment by SDavisMedia** [comment]
@sunnyratilal sweet sweet! Can we adjust [this](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/issue/3795/assets/css/edd-admin.css#L1001) to 70%? That should finish it off. The responsive font-size for the nav tabs are a bit small on mobile now.

**Comment by sunnyratilal** [comment]
@SDavisMedia That's all done. Are we good to merge?

**Comment by SDavisMedia** [comment]
@sunnyratilal Yessir! :+1:

**Comment by sunnyratilal** [comment]
Merged!
