### ISSUE TITLE
Bad breakpoint on the edit customer screen

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#3798]
As the width of the browser continues to be reduced, the white div overflows to the right. Instead, the buttons at the top should either be horizontal or remain to the right of the white div.

![image](https://cloud.githubusercontent.com/assets/1324637/9842239/4f92a22a-5a79-11e5-8cf1-e5ecd06d87f3.png)

**Comment by chriscct7** [comment]
The width in the screenshot is a Google Chrome 45 calculated 793px

**Comment by chriscct7** [comment]
All breakpoints under 811px have the vertical menu wierdness. All breakpoints under 700px have the overflowing white container div issue

**Comment by pippinsplugins** [comment]
@SDavisMedia I've gotten pretty close to having this. Could you work a bit of your magic on it now? The edit view needs some work and the tabs across the top need help.

**Comment by SDavisMedia** [comment]
Sure thing.

**Comment by cklosowski** [comment]
@SDavisMedia I worked a bit into this, could you improve it a bi tmore?

**Comment by SDavisMedia** [comment]
Gonna work on this now.

**Comment by SDavisMedia** [comment]
@pippinsplugins @cklosowski take that for a spin

**Comment by SDavisMedia** [comment]
@chriscct7 you intend to adopt the EDD core markup for this in FES? That would be a good move.

**Comment by pippinsplugins** [comment]
@SDavisMedia looks perfect to me!

**Comment by chriscct7** [comment]
@SDavisMedia They've been using roughly the same markup since it was introduced. Unfortunately, the way the customers page in EDD is currently done, in order to use the same layout, an extension has to pretty much duplicate 90% of the code. It'd be easy to reduce the amount of code they have to duplicate by moving the whole thing into a class with an object key or construct argument that would hold the prefix to use for things like translation and filter names, but that can't really be done without breaking bc of people calling those functions directly. Doing it though would allow FES and anyone else using it to shed about a thousand lines of code though.

**Comment by pippinsplugins** [comment]
@chriscct7 Not true any more. We fixed it so that extensions can reuse it. Recurring Payments, for example, reuses it.
