### ISSUE TITLE
Allow individual items to be re-priced when viewing a payment.

### ISSUE THREAD

**Issue by DevinWalker** [easydigitaldownloads/easy-digital-downloads#3802]
Scenario: An admin goes in and adjusts a payment amount manually:

![9-16-2015 1-18-50 pm](https://cloud.githubusercontent.com/assets/1571635/9917322/c30cd3da-5c75-11e5-89d0-11e2562290a9.png)

Problem: The income stats for the individual forms remain unchanged:

![9-16-2015 1-19-04 pm](https://cloud.githubusercontent.com/assets/1571635/9917332/d0dbdf56-5c75-11e5-89ad-3d5af577913c.png)

The total income does update here: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/admin/payments/actions.php#L301

... But the individual downloads are not also updated.

**Comment by pippinsplugins** [comment]
@DevinWalker That's intentional. The total purchase price is the accumulated amounts from all items.

To reduce the amount on the item, you would need to remove and re-add the item. That would trigger the stats change.

That's a rather crappy user experience though. Perhaps we should support changing the amounts on individual items?

**Comment by DevinWalker** [comment]
Gotcha. For Give it makes sense that we have the ability to adjust the total based on this field because there's only ever one donation form per transaction. For EDD, there can be one or many downloads per transaction. Perhaps something like this would be better:

![9-16-2015 2-06-00 pm](https://cloud.githubusercontent.com/assets/1571635/9918556/62662598-5c7c-11e5-9bf2-0e454d33adf2.png)

Clicking the "Edit Amount" would make the total editable within an input field. The user then could click "Update Payment" and see the new totals.

**Comment by pippinsplugins** [comment]
I'd prefer the amount just be shown as an input field. Seems more intuitive to me.

**Comment by DevinWalker** [comment]
Yeah I'm overthinking it...

**Comment by pippinsplugins** [comment]
No worries :)

**Comment by cklosowski** [comment]
@DevinWalker @pippinsplugins Retitled this one. I think we'll work towards a 're-price' column that allows the individual product price to be updated, therefore allowing us to alter the download stats.

**Comment by pippinsplugins** [comment]
Related https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4120

**Comment by pippinsplugins** [comment]
Changed this to high priority as it's a blocker to getting us accurate reports. Right now if a partial refund is processed, there is no way to update the earnings on the product, giving us inaccurate stats.

**Comment by cklosowski** [comment]
So this starts bringing in a few other issues we'll probably have to resolve at the same time.
1) We'll need to account for quantities, and allow per unit price changes
2) We'll also probably need to add the tax on the payment into an editable field
3) Since we would then have an item price, and a tax field, maybe we'd be best to have a 'total' column that's not editable but is calculated based off the item price * quantities + tax?

Just laying out some ideas, adding an editable field here opens a few other things we'll have to improve, as long as we're aware of that change.

**Comment by pippinsplugins** [comment]
I vote three fields:

- Item Price
- Tax
- Quantity

Total can be ineditable.

**Comment by cklosowski** [comment]
Ok i'll work that up.

**Comment by cklosowski** [comment]
# Status Update
This reworks the display of the purchased items of the `view-order-details.php` for admin view of payments. I've reworked the CSS and markup as well as updated `EDD_Payment` to allow modifying specific aspects of cart items.

## Completed
- [x] Update CSS/JS/HTML for the new view
- [x] Update the recalculation button JS
- [x] Add `EDD_Payment::modify_cart_item` which allows editing the `item_price`, `quantity`, `discount`, and `tax` of an item. Total is calculated based off this information.
- [x] Modifying an item also corrects any sales log counts by removing or adding the necessary number (if needed)
- [x] Modifying an item increases or decreases the download earnings and sales for that item as well (if needed)
- [x] Unit tests for modifications are added for modifying `quantity` and `item_price`

## Remaining
- [ ] Fix up `includes/admin/payments/actions.php` to determine if an item was modified, so it can use `EDD_Payment::modify_cart_item`
- [ ] Add unit tests for modifying `tax` and `discount`

**Comment by sunnyratilal** [comment]
UI looks really slick @cklosowski 👍

**Comment by cklosowski** [comment]
Ok, this is ready for some testing @easydigitaldownloads/core-devs. Both from a UI/UX perspective, and from a functional standpoint. Be sure to clear any local cache of the `.js` files as there have been some hefty modifications to the selectors used.

**Comment by pippinsplugins** [comment]
@cklosowski this is looking really good!

Just found an issue: download earning stats are not incremented / decremented properly.

When I decrement the quantity, say from 4 to 3, on an item and click save, the earnings stats _increase_ instead of decrease.

**Comment by pippinsplugins** [comment]
Another item: adjusting the item quantities does not trigger the `Recalculate` button to show up. Adjusting the item price does show it properly.

**Comment by pippinsplugins** [comment]
Looks like amounts changed by item quantities do not get taken into account during `Recalculate` as well.

**Comment by pippinsplugins** [comment]
Once this is all working (don't worry about it yet), we'll have to work on some small screen styling:
![screen shot 2017-01-23 at 12 26 48 pm](https://cloud.githubusercontent.com/assets/1034109/22217150/8a484124-e167-11e6-9c53-949b128739ec.png)

**Comment by cklosowski** [comment]
yeah, minimal screens just need some updates to it. I tested this up to a 11" Macbook Air.

**Comment by pippinsplugins** [comment]
Looks like stats changes are backwards for taxes too. I added tax to a product that previously had no taxes and my earnings went _down_ instead of up.

**Comment by cklosowski** [comment]
@pippinsplugins @sunnyratilal ready for more.

**Comment by sunnyratilal** [comment]
Just tested and it all seems to be working fine on my end

**Comment by SDavisMedia** [comment]
Just FYI I'm working on the final style cleanup here. I've made slight changes to tidy up the full view before the moving to the responsive view, though. Doesn't look like much but if you have beef with any of it, please let me know. Biggest change (the only thing you may not like) is what I did with the price options:

<img width="1035" alt="screenshot 2017-01-23 16 39 16" src="https://cloud.githubusercontent.com/assets/2359131/22229115/815037f2-e18a-11e6-8dd6-474b5e9d6565.png">

Text wrap with the product title and price option is pretty common. In my opinion, it's ugly. I think this helps pretty up the wrap since it's almost inevitable. Also makes for much easier scanning of the products and their price options.

Moving on to responsiveness so just drop a line if you think I need to reverse that.

**Comment by cklosowski** [comment]
Looks great from the screenshots. Will check it tonight when back at the
desk.

**Comment by SDavisMedia** [comment]
Alright, this is up and ready for @cklosowski's JS to make it all work again because I broke it. Looks pretty good, though.

<img width="1038" alt="screenshot 2017-01-24 15 47 36" src="https://cloud.githubusercontent.com/assets/2359131/22272008/80489ba2-e24c-11e6-8679-8eb7bb09af99.png">

**Comment by cklosowski** [comment]
@SDavisMedia @pippinsplugins @sunnyratilal this is ready for some testing.

**Comment by pippinsplugins** [comment]
The box title along with the column title seems a bit redundant:
![screen shot 2017-01-24 at 7 00 13 pm](https://cloud.githubusercontent.com/assets/1034109/22273638/64a4c694-e267-11e6-9799-4d18b4a6b82d.png)

**Comment by pippinsplugins** [comment]
What if we remove the box title entirely?

**Comment by sunnyratilal** [comment]
My personal preference would be rename `Download Purchased` to simply `Download`

**Comment by SDavisMedia** [comment]
I think `Purchased Downloads` can definitely go.

**Comment by sunnyratilal** [comment]
I've tested and there's some great work that's happened here.

Kudos @cklosowski and @SDavisMedia! 💯

**Comment by cklosowski** [comment]
@SDavisMedia @pippinsplugins @sunnyratilal Yes?
![screen shot 2017-01-24 at 8 51 43 pm](https://cloud.githubusercontent.com/assets/1390124/22274880/fb189fd8-e276-11e6-8f77-ef508fda6b01.png)

**Comment by SDavisMedia** [comment]
I like it but as soon as responsiveness kicks in, we're gonna lose those headings as I move them down to just above the fields for clarity on mobile. So what we need to do is keep everything we have and hide things when necessary. So for full screen, it should look like what you have there but the main heading can stay hidden. Then when responsive, the headings you see there are already set to go away and the main heading should come back.

I can whip that up on your green light.

**Comment by cklosowski** [comment]
Go for it @SDavisMedia. I'll leave it up to you. I won't commit what I have since it sounds like deleting the markup for the `h3` is not what's needed (which is what I did :P )

**Comment by SDavisMedia** [comment]
@cklosowski that'll do it

**Comment by cklosowski** [comment]
Looks amazing @SDavisMedia:
Larger screens:
![screen shot 2017-01-24 at 11 43 18 pm](https://cloud.githubusercontent.com/assets/1390124/22278123/f90476f0-e28e-11e6-92a0-51d5779b808e.png)

Responsive:
![screen shot 2017-01-24 at 11 43 24 pm](https://cloud.githubusercontent.com/assets/1390124/22278130/fd2f626c-e28e-11e6-8cf7-e81a439b6ddb.png)

**Comment by cklosowski** [comment]
I'm good with this @easydigitaldownloads/core-devs if you guys are.

**Comment by sunnyratilal** [comment]
Yep! Happy here!

**Comment by pippinsplugins** [comment]
I'm _thrilled_ here. This is as perfect as it's going to get! Merging.
