### ISSUE TITLE
Quick edit on Downloads triggers JS error

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#3807]
I'm not sure when this started happening but it's definitely occurring with 2.4.5.

If you click Quick Edit on a download, a JS error is thrown:

![screen shot 2015-09-17 at 3 26 10 pm](https://cloud.githubusercontent.com/assets/1034109/9945015/7790c656-5d50-11e5-9321-0f48814d550b.png)

**Comment by pippinsplugins** [comment]
Comments from @themotionclub that might help: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/commit/0f5e0c4c5aef56ad1ba8c0a4c98231023e652cee#commitcomment-13290798

**Comment by mindctrl** [comment]
I don't get that JS error (with or without script debug), but I do see that it's broken. I think I see why, but need more eyes since I'm not getting that JS error on a fresh install and not sure why the line was there originally. PR incoming.

**Comment by cklosowski** [comment]
No JS error on my end, but I do see that the item does not expand for a quick edit. With john's fix, it works..but seeing a PHP notice. looking into it.

**Comment by cklosowski** [comment]
Ignore the PHP error, was something I had sitting in an `mu-plugins` test for a customer. carry on :)

**Comment by cklosowski** [comment]
:+1: working great for me.
