### ISSUE TITLE
Force license keys to expire at 23:59:59

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#3816]
[This ticket](https://secure.helpscout.net/conversation/121097499/17010/) brought up an issue with license keys expiring a few hours too early (in this case due to recurring payments being processed later in the day). We should adjust our expiration dates to always be at the end of the day, `23:59:59` so that they never expire an hour or two early.

EDD core does the same thing with discount codes.

This will need an upgrade routine to adjust all non-expired license keys.

I would also propose that we only set the expiration to the end of the day if the length of the license key is greater than `1 day`.

**Comment by cklosowski** [comment]
Um, this belongs in EDD SL repo :)

**Comment by pippinsplugins** [comment]
DOH!
