### ISSUE TITLE
Redirect loop when verifying user if no purchase history page is set in options

### ISSUE THREAD

**Issue by thomasgriffin** [easydigitaldownloads/Easy-Digital-Downloads#3817]
I don't know exactly when this got implemented, or how exactly users are "verified" - is this a setting I can turn off?? - but if you do not have a page set for your purchase history in the EDD settings, clicking on the user verification link causes an infinite redirect loop.

It also sends out a zillion "Verify your account" emails, none of which have the proper URL because of no purchase history page being set. Very frustrating for the user, and very frustrated that this was something that appeared to be turned on by default.

Can someone explain how this works?

**Comment by pippinsplugins** [comment]
@thomasgriffin I'm going to ping you on slack to go over the fine details of this. Will explain there.

Is there a reason you don't have a purchase history page set?
