### ISSUE TITLE
Abstract customer UI

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#3820]
The customer UI is great . . . but it's impossible to re-use in extensions.

All of the class names, IDs, etc, are all `customer`. This means that all of the CSS and HTML needs updated to use generic class names.

For example, instead of `edd-customer-card-wrapper` as the class for the main DIV wrapper, we should use `edd-object-card-wrapper`

I'm not sure `object` is the best descriptor but it needs to be something general so we can re-use it.

I'm trying to re-use the UI in [Recurring Payments](https://github.com/easydigitaldownloads/edd-recurring/issues/72) and it's brutally painful.

**Comment by spencerfinnell** [comment]
`edd-item-card-wrapper`?

Though I think `object` makes plenty of sense.

**Comment by pippinsplugins** [comment]
I like both item and object.

**Comment by cklosowski** [comment]
:+1:

**Comment by spencerfinnell** [comment]
Are any other plugins besides FES 2.3 using this currently?

I think switching from IDs to classes would be nice, and prefixing anything else that isn't already. IDs as selectors are bleh.

**Comment by pippinsplugins** [comment]
Software Licensing uses it.

EDD Wallet (new one coming) uses it.

**Comment by chriscct7** [comment]
FES shouldn't be dependent on any changes to abstract the customer ui. For
the most part it duplicates all of the css exactly because of the talk of
future abstracting it

**Comment by pippinsplugins** [comment]
@mindctrl @SDavisMedia I'd like your help testing this. No need to code anything, just giving UI a full once over to make sure I didn't break anything.

**Comment by SDavisMedia** [comment]
Looks like Commissions lost some formatting. Everything else seems fine.

![screen shot 2015-09-23 at 11 20 25 am](https://cloud.githubusercontent.com/assets/2359131/10051045/1dbd872e-61e5-11e5-9d4d-b334f2e5889c.png)

**Comment by cklosowski** [comment]
@spencerfinnell There are some IDs as selectors for when using the AJAX save but for the most part the overall ID usage could be discontinued. IDs are blech for CSS selectors, but much more performant for jQuery selectors.

**Comment by SDavisMedia** [comment]
Looks like customer notes header and wrapper also need to be changed.

**Comment by SDavisMedia** [comment]
I just adjust the elements that seem to have been missing. I noticed they were missing when making adjustments for the Commissions tab mentioned above and in the issue here: https://github.com/easydigitaldownloads/EDD-Commissions/issues/95

With my latest changes here in EDD, everything looks good on my end. And with this merged, the changes I made in Commissions will also display properly.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by cklosowski** [comment]
going to bring this up to speed with master and release/2.5, it's been looking good to me.

**Comment by cklosowski** [comment]
Once CI Passes i'll merge into `release/2.5`

**Comment by pippinsplugins** [comment]
This is all in `release/2.5`

**Comment by pippinsplugins** [comment]
Just did some more testing. Looks like we can safely close this.

**Comment by pippinsplugins** [comment]
Somehow we've broken then completely in `release/2.5` now:
![screen shot 2015-12-08 at 10 57 06 am](https://cloud.githubusercontent.com/assets/1034109/11662051/82e82b72-9d9a-11e5-85bc-92486466a57e.png)

**Comment by mindctrl** [comment]
@pippinsplugins not seeing that on customer screens locally. Looks like browser cache?

**Comment by pippinsplugins** [comment]
Hmm, I've tried clearing cache numerous times without luck. Pretty sure I saw it locally too.

**Comment by pippinsplugins** [comment]
Nevermind, it was cache.
