### ISSUE TITLE
Remove user_id value when deleting user account

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#3824]
When a user account is deleted that is associated with a customer record, the `user_id` column stays unchanged.

This causes unexpected results with customer records who have had their user account deleted.

We should remove the ID from the `user_id` column when the user account is deleted.

**Comment by cklosowski** [comment]
This is a pretty small change. I think we should get it in for 2.5.

**Comment by pippinsplugins** [comment]
I'm fine with that.
