### ISSUE TITLE
Quantity not added with variable prices and multi-purchase mode on when ajax is disabled

### ISSUE THREAD

**Issue by wpweb101** [easydigitaldownloads/Easy-Digital-Downloads#3826]
Hi

There is still problem in some other cases.

I have disabled AJAX from the global setting page.

See this Screenshot : http://awesomescreenshot.com/06958vl1af

Now on front-side, In Variable Download with multiple purchase option, I selected two different quantiites as per screen shot below :

http://awesomescreenshot.com/0da59cgu2c

But now when I click on add to cart button, it only add 1 product into the cart of both Variable Download Options.

See this Screenshot : http://awesomescreenshot.com/0e559chk28

**Comment by pippinsplugins** [comment]
Duplicate: of https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/3804

**Comment by pippinsplugins** [comment]
Re-opening as we've now split the original issue into two separate bugs.

**Comment by cklosowski** [comment]
@wpweb101 @pippinsplugins this should be ready for some testing.

**Comment by pippinsplugins** [comment]
@cklosowski This isn't working for me. I'm testing with Vendd currently.

**Comment by pippinsplugins** [comment]
It works properly when adding the first price option in the list is added; it does not work with any other price options.

**Comment by cklosowski** [comment]
Working fine on Vendd for me. Will retest though. I was able to add any and all price options.

**Comment by pippinsplugins** [comment]
I also tested on Twenty Fifteen and saw the same behavior.

**Comment by cklosowski** [comment]
Here's what I'm seeing:
![screen shot 2015-11-14 at 8 31 47 pm](https://cloud.githubusercontent.com/assets/1390124/11167046/d570625e-8b0e-11e5-81fc-fb09161142e8.png)


![screen shot 2015-11-14 at 8 31 58 pm](https://cloud.githubusercontent.com/assets/1390124/11167044/c933d6a6-8b0e-11e5-9879-455b41d6a34d.png)

**Comment by cklosowski** [comment]
ok I see what you mean. working on it.

**Comment by cklosowski** [comment]
@pippinsplugins give that a shot.

**Comment by pippinsplugins** [comment]
@cklosowski There we go!
