### ISSUE TITLE
Undefined index: user_info in discount-functions.php on line 853

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#3836]
For some reason I can't figure out, on one of my installs, if a user enters a discount coupon without being logged in, this error comes back from ajax:

Undefined index: user_info in discount-functions.php on line 853

I did a print_r($payment_meta ); and it shows this array with these empty key/values in the console ajax error:

"Array
(
    [key] => 
    [email] => 
    [date] => 
)"

Any ideas why there might be no user_info key in the array?

**Comment by mintplugins** [comment]
Additionally, I've tested it with all plugins de-activated and using the twenty fifteen theme. The same issue occurs. I assume this is because the Payment itself doesn't have the user_info saved?

We set up some of our payments manually using the EDD Manual Payments add-on. I'm not sure if that might be relevant.

**Comment by sunnyratilal** [comment]
@mintplugins Does this issue still exist? I tried just now to replicate it and I can't replicate.

**Comment by mintplugins** [comment]
@sunnyratilal I can't remember where this was happening now :P 

We can close it for now and re-open if we see it again.
