### ISSUE TITLE
Wrap edd_price_range() Output with .edd_price

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/Easy-Digital-Downloads#3839]
I think global styles applied to `.edd_price` would also want to apply to a range. Either wrap the whole output, or add `.edd_price` to the high and low span wraps.

Thoughts?

**Comment by pippinsplugins** [comment]
If starting over, yes, I think `.edd_price` should be used as the wrapper. Since we can't know how adding it would impact variable pricing styling in existing themes and sites, I vote that we just apply it to the high and low spans.

**Comment by pippinsplugins** [comment]
Ready for testing.
