### ISSUE TITLE
Ajax call to load dashboard sales widget fires on every page

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#3850]
![screen shot 2015-09-29 at 9 33 46 am](https://cloud.githubusercontent.com/assets/1034109/10167239/4cb77934-668d-11e5-9098-75a05b43fdc6.png)

It's firing on every page, not just the dashboard.

**Comment by mindctrl** [comment]
@cklosowski this is what broke the widget. I think we can change this to read a var from edd_vars and avoid traversing the DOM.

**Comment by cklosowski** [comment]
Ok thanks @mindctrl I'll work on this again.
