### ISSUE TITLE
shortcode-login.php improvement proposal

### ISSUE THREAD

**Issue by DevinWalker** [easydigitaldownloads/easy-digital-downloads#3854]
Hey Guys,

I noticed a few CSS conflicts with various themes like twenty twelve and the `required` and `password` classes used within the html. In twentytwelve and other themes it turns the text red. You get around this at checkout by specifying the text as black using `edd-input` alongside that class. I suggest either prefixing the classes like `edd-password` and `edd-required` or adding the `edd-input` class alongside. I think it would be preferable to prefix those classes.

![prefix](https://cloud.githubusercontent.com/assets/1571635/10178181/1c24f6cc-66b3-11e5-8997-07c0a0fa0db4.png)

I also noticed the legend tag is seemingly improperly wrapped in a span tag. Is there any specific reason for this?

![9-29-2015 1-59-32 pm](https://cloud.githubusercontent.com/assets/1571635/10178193/2e0802c6-66b3-11e5-964e-5995ebfa87e2.png)

**Comment by pippinsplugins** [comment]
I completely agree on the class, though we'll have to be careful about potential backwards compat there. Since it's a small class that is rarely styled directly, it's probably safe to change.

For the legends, see #3568

**Comment by DevinWalker** [comment]
Good to know the legends is already on the radar. I agree, some themes may already have those classes styled, hopefully minorly only though.

**Comment by pippinsplugins** [comment]
I'm going to tag this for 2.6, same version as the legends issue is tagged for.

**Comment by cklosowski** [comment]
In `2.6.5` the `<span>` will be removed from the `<legends>` with #4540

**Comment by sunnyratilal** [comment]
When updating the `required` class, the JavaScript will also need updating as we reference the `required` class throughout the checkout JS

**Comment by sunnyratilal** [comment]
Merged into `release/2.7`
