### ISSUE TITLE
Wallet Extension

### ISSUE THREAD

**Issue by atdewitz** [easydigitaldownloads/Easy-Digital-Downloads#3857]
Wallet does not appear as a payment gateway even when there are sufficient funds in an account.

When adding funds manually to a customer account, it sends an email, like so, to the wrong customer: 

Dear ,

The site admin has credited your wallet $0.00.

**Comment by pippinsplugins** [comment]
@atdewitz I saw you opened a ticket in our support system a few minutes ago. We will answer you there.

Please note that github is _not_ for support. It is for development tracking only.
