### ISSUE TITLE
If a payment fails, the coupon uses should be decremented by 1

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/Easy-Digital-Downloads#3859]
Scenario:
User checks out an item with a coupon (which let's say has a usage limit of 1), and their card is declined.

Current: User goes to retry payment, and gets coupon isn't valid (because EDD increments the number of times a coupon has been used right before gateway).

Proposed: if and only if a payment is failed, EDD should decrement the usage of the coupons on an order by 1, so that the user can re-checkout using the same coupon

**Comment by pippinsplugins** [comment]
I'd propose a slightly different fix: discounts shouldn't ever increment or be recorded as used until the payment is marked as complete.

**Comment by pippinsplugins** [comment]
Moved to 2.5.3. Not enough time to put more in 2.5

**Comment by chriscct7** [comment]
That's a bad idea. Let me explain a situation where that could cause catastrophic issues.

Let's say I limit a coupon to 10 uses, and I have PayPal standard active. On PayPal standard, users can pay using an eCheck which takes 7 days to clear, so if the coupon wasn't decremented until after the payment, 100 users could use the coupon via eCheck, because the payment itself doesn't clear PayPal for 7 days, so those users can cancel the order at any point during those 7 days. 

Further on sites with large volume, this would provide to be hugely problematic as it would let more than the intended number of people use the coupon, if say on a limit 10 coupon, 100 people simultaneously checkout

**Comment by pippinsplugins** [comment]
Good point.

**Comment by dannyvankooten** [comment]
I was just about to open an issue for this as I ran into this last week as well. Nice to see you're one step ahead of me!

**Comment by pippinsplugins** [comment]
Ready for testing.

**Comment by cklosowski** [comment]
@pippinsplugins This looks to take care of a single use discount for a specific customer to see if they've used a discount code before, however it doesn't appear to take care of the situation where a payment fails and we increase the usage of a discount by 1. The scenario that:

1. User checks out with a code that has 10 uses.
2. Payment fails
3. Code now has 9 uses left (we aren't setting it back to 10 after the failure)

The `_edd_discount_uses` meta needs to be somehow handled in the case of a failed payment.

**Comment by cklosowski** [comment]
Going to see if I can tackle this quick.

**Comment by pippinsplugins** [comment]
Ah yes, thanks.
