### ISSUE TITLE
Running EDD_Payment_Stats::get_sales() twice in a row renders error.

### ISSUE THREAD

**Issue by topher1kenobe** [easydigitaldownloads/Easy-Digital-Downloads#3860]
$stats = new EDD_Payment_Stats; 
    
    echo $stats->get_sales( 0, 'August 1, 2015', 'August 31, 2015' );
    echo $stats->get_sales( 0, 'this_year' );

renders:

2
Warning: date() expects parameter 2 to be long, string given in /home/topher1/edd.derosia.com/wp-content/plugins/easy-digital-downloads/includes/class-edd-stats.php on line 469

Warning: date() expects parameter 2 to be long, string given in /home/topher1/edd.derosia.com/wp-content/plugins/easy-digital-downloads/includes/class-edd-stats.php on line 481
0

The values are proper, the error is not.

**Comment by topher1kenobe** [comment]
This appears to hold true for all methods in this class that accept dates like that.

**Comment by mindctrl** [comment]
Just noticed if you re-order your get_sales calls, it works as expected.

**Comment by topher1kenobe** [comment]
@mindctrl confirmed.

**Comment by cklosowski** [comment]
@topher1kenobe was this cleared up with the PR #3861?
