### ISSUE TITLE
Running EDD_Payment_Stats::get_earnings() twice in a row give different values.

### ISSUE THREAD

**Issue by topher1kenobe** [easydigitaldownloads/Easy-Digital-Downloads#3861]
echo $stats->get_earnings( 0, 'August 1, 2015', 'August 31, 2015' );
    echo '<br>';
    echo $stats->get_earnings( 0, 'this_year' );

This renders 
30
0

    echo $stats->get_earnings( 0, 'this_year' );
    echo '<br>';
    echo $stats->get_earnings( 0, 'August 1, 2015', 'August 31, 2015' );

This renders
35
30

**Comment by spencerfinnell** [comment]
The arguments passed to the method aren't used when making the query. It uses the class's property.

https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/6f799788b0c9601f8666209386d0a9262e708c1f/includes/payments/class-payment-stats.php#L124-L125

https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/6f799788b0c9601f8666209386d0a9262e708c1f/includes/payments/class-payment-stats.php#L95

**Comment by spencerfinnell** [comment]
Oh I see, happens in `setup_dates`

**Comment by pippinsplugins** [comment]
Let's get this fixed in 2.5

**Comment by cklosowski** [comment]
@topher1kenobe can you test out this issue branch? `issue/3861` and also retest #3860 with this branch? See if it was a two-fer.

**Comment by pippinsplugins** [comment]
This is working properly for me now. :+1:
