### ISSUE TITLE
EDD_Payment_Stats::get_earnings() should always return a float.

### ISSUE THREAD

**Issue by topher1kenobe** [easydigitaldownloads/Easy-Digital-Downloads#3862]
get_earnings() returns a float if there's change, but an integer if there isn't.

I think I'd like to see it always be a float, even if the change is .00

**Comment by pippinsplugins** [comment]
I don't believe this is valid any any more. The value is returned through `round()` so it will be a float:
```php
return round( $earnings, edd_currency_decimal_filter() );
```
