### ISSUE TITLE
Unnecessary code

### ISSUE THREAD

**Issue by sumobi** [easydigitaldownloads/Easy-Digital-Downloads#3865]
As far as I can see, these 2 lines do nothing:

https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/template-functions.php#L187-L188

When adding a download to the cart, the "Added to cart" message along with the checkmark is the only thing shown. I have a feeling that the anchor link is supposed to wrap around the "Added to cart" text. I think we should just remove it since the button turns into "checkout".

**Comment by pippinsplugins** [comment]
Pretty sure that can go. Let's have one or two others test and verify.

**Comment by mindctrl** [comment]
This looks good to me.
