### ISSUE TITLE
Earnings by Category estimate bug

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#3867]
On the Earnings by Category report, the "Monthly Sales Avg" and "Monthly Earnings Avg" columns it seems to be basing the estimate for the entire month based on the estimate through that day in the month. For example, on a site that makes $3000 a month, instead of an estimated earnings of $3000, on the 2nd day of the month it would show $200. Same for sales

**Comment by pippinsplugins** [comment]
@chriscct7 Do you see the same thing on the store-wide estimations?

**Comment by chriscct7** [comment]
You mean on the bottom of the earnings report? If so, no, that works fine

**Comment by pippinsplugins** [comment]
Yep, that's what I meant.

**Comment by pippinsplugins** [comment]
Moving to 2.5.4

**Comment by sunnyratilal** [comment]
@chriscct7 @pippinsplugins This is ready for some testing. I've adjusted the calculations so they _should_ be correct.

**Comment by pippinsplugins** [comment]
@sunnyratilal I don't think this is working right.

What I see on `release/2.7`:
![screen shot 2016-12-26 at 10 34 21 am](https://cloud.githubusercontent.com/assets/1034109/21484376/f209bdd2-cb56-11e6-83b4-a54238f8705e.png)

What I see on `issue/3867`:
![screen shot 2016-12-26 at 10 35 14 am](https://cloud.githubusercontent.com/assets/1034109/21484379/03bdbace-cb57-11e6-9502-c410d3572cc2.png)

**Comment by pippinsplugins** [comment]
How can the average monthly earnings be greater than the total earnings?

**Comment by chriscct7** [comment]
Does average monthly earnings take into account refunds?

**Comment by sunnyratilal** [comment]
@pippinsplugins The calculations are based off our current estimation function - I'll take another look at the maths. (@chriscct7 would probably need your input here too)

@chriscct7 Only payments with a status of `publish` or `revoked`.  The earnings figures are pulled directly from `EDD_Payment_Stats->get_earnings()`

**Comment by sunnyratilal** [comment]
@pippinsplugins @chriscct7 Calculations have been adjusted.

**Comment by pippinsplugins** [comment]
@sunnyratilal numbers look better now. New issue: the `Monthly Average Earnings` column should never change. It's a monthly average, not an average for the current view. Right now it changes based on the date range selected.

**Comment by sunnyratilal** [comment]
@pippinsplugins Ready for another test.

**Comment by pippinsplugins** [comment]
@sunnyratilal I'm getting a fatal error now:

Fatal error: Uncaught Error: Call to a member function get_sales() on null in /Users/pippin/Sites/edd/wp-content/plugins/easy-digital-downloads/includes/admin/reporting/class-categories-reports-table.php:259 Stack trace: #0 /Users/pippin/Sites/edd/wp-content/plugins/easy-digital-downloads/includes/admin/reporting/class-categories-reports-table.php(396): EDD_Categories_Reports_Table->reports_data() #1 /Users/pippin/Sites/edd/wp-content/plugins/easy-digital-downloads/includes/admin/reporting/reports.php(258): EDD_Categories_Reports_Table->prepare_items() #2 /Users/pippin/Sites/edd/wp-includes/class-wp-hook.php(298): edd_reports_categories('') #3 /Users/pippin/Sites/edd/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array) #4 /Users/pippin/Sites/edd/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #5 /Users/pippin/Sites/edd/wp-content/plugins/easy-digital-downloads/includes/admin/reporting/reports.php(106): do_action('edd_reports_vie...') #6 /Users/pippin/Sites/edd/wp-includes/class-wp-hook.php(298): ed in /Users/pippin/Sites/edd/wp-content/plugins/easy-digital-downloads/includes/admin/reporting/class-categories-reports-table.php on line 259

**Comment by cklosowski** [comment]
Refreshed the branch from `release/2.7`

**Comment by cklosowski** [comment]
Fatal error should be fixed now @sunnyratilal @pippinsplugins

**Comment by cklosowski** [comment]
Having an issue with 'last month' here:
![screen shot 2017-01-13 at 12 20 01 pm](https://cloud.githubusercontent.com/assets/1390124/21942510/a4ab85ba-d98a-11e6-88b8-7ebc75ff1cb6.png)

But I have earnings from last month:
![screen shot 2017-01-13 at 12 20 21 pm](https://cloud.githubusercontent.com/assets/1390124/21942527/b58d3aae-d98a-11e6-8861-6dcdc6caa684.png)

**Comment by pippinsplugins** [comment]
Fatal error is gone but something is still super off here.
![screen shot 2017-01-16 at 11 08 28 am](https://cloud.githubusercontent.com/assets/1034109/21992464/295a8db2-dbdc-11e6-8104-b4b1b9af33f4.png)

Look at `Total Sales` and `Total Earnings` and then the estimates. The estimates are super high.

There's a _total_ of 40 sales in this site spread over 3 months
![screen shot 2017-01-16 at 11 09 24 am](https://cloud.githubusercontent.com/assets/1034109/21992488/47db0122-dbdc-11e6-844b-c77050d92b0c.png)

**Comment by cklosowski** [comment]
Something does seem to be slightly off with the estimates. My guess (without much investigation yet) is that it's related to counts of sales logs? I'm using the WPCLI commands to generate a bunch of sales across the last 180 days, yet all individual item sales are all lumped into the same date.

If I look at general reporting, which uses the sales stats classes, it looks fine, but stats for a single item are all relying on the sales log dates, not the actual payments dates. That'd be my guess if you're using the WP CLI command to generate them @pippinsplugins

**Comment by pippinsplugins** [comment]
I'm not generating any logs with WP CLI. My graphs are built from real purchases only.

**Comment by sunnyratilal** [comment]
I'm using `edd_get_average_monthly_download_sales()` and `edd_get_average_monthly_download_earnings()` for the estimates.

I can't seem to replicate the inconsistencies with the estimates.

**Comment by cklosowski** [comment]
Actually these look right by my data. I always forget we base the averages from the `post_date` field for the published product, which for me it's only a couple months old, however I've generated sales from before that month, so by the function it's right.

**Comment by cklosowski** [comment]
@pippinsplugins is it possible that data could be off based off adding/removing items from a download on payments that existed prior to it's publish date? I'm just trying to narrow down discrepancies. I did compare `release/2.7` to `issue/3867` and it's far more accurate on the issue branch than it is on the release branch or master.

**Comment by pippinsplugins** [comment]
Definitely possible.

Could we get a test from @SDavisMedia and @mintplugins please?

**Comment by mintplugins** [comment]
I have a category with 2 actual sales showing "Total Sales" as "0" when generating a Category Report.

**Comment by mintplugins** [comment]
Here are the steps I took:

Brand new store:
- Created 2 new products in 2 different categories. 
- Purchased Both Immediately. 

Category report:
<img width="929" alt="screen shot 2017-01-25 at 12 38 24 pm" src="https://cloud.githubusercontent.com/assets/1638128/22307489/2df64474-e311-11e6-8b77-637e063b38a9.png">

- Changed post date of both products to be published 1 year ago. 

Category report:
<img width="1274" alt="screen shot 2017-01-25 at 3 17 39 pm" src="https://cloud.githubusercontent.com/assets/1638128/22307569/8051732e-e311-11e6-93d5-a617c2a5cb64.png">


This seems to show that in month 1, the averages are correct. In month 12, the averages are still correct because $100/12 is $8.33.

**Comment by mintplugins** [comment]
However, it's kinda confusing because the monthly sales average is 0. Obviously some kind of rounding is happening there. I wonder if we should not round that. The Monthly Sales Average should read as 0.083 - correct?

**Comment by cklosowski** [comment]
@mintplugins Yeah, seems like maybe if the average sales per month is lower than 1, we shouldn't round it...

**Comment by cklosowski** [comment]
Try that @mintplugins

**Comment by sunnyratilal** [comment]
Fixes the rounding up for me - all good here 👍

**Comment by mintplugins** [comment]
Fixes the confusion with 0 sales:

<img width="1263" alt="screen shot 2017-01-26 at 10 43 36 am" src="https://cloud.githubusercontent.com/assets/1638128/22338007/504694f4-e3b4-11e6-990b-8ba96adc38e6.png">

**Comment by cklosowski** [comment]
@sunnyratilal  @pippinsplugins we good here

**Comment by cklosowski** [comment]
@chriscct7 as well, since you reported it :P

**Comment by sunnyratilal** [comment]
Yep all good here

**Comment by pippinsplugins** [comment]
:+1:

**Comment by cklosowski** [comment]
Merging!
