### ISSUE TITLE
Discount Description

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#3871]
A user suggested having a textarea for describing what a discount has been created for. I like the idea. https://secure.helpscout.net/conversation/127499503/18175/

Perhaps a textarea field could be added to the Add/Edit Discount screen and maybe even show the description on the discounts table?

Thoughts?

**Comment by shiftwebsolutions** [comment]
This would be a great addition! With a ton of coupon codes, it would be helpful for a marketing manager to be able to write notes and track the details of each coupon.

**Comment by pippinsplugins** [comment]
I'm not opposed to adding one, do I do wonder how often it would actually be used.

Restrict Content Pro supports discount descriptions and, as far as I can tell, it's a feature that is very, very rarely used.

It's definitely useful for specific cases, such as @shiftwebsolutions needs, but I'm not sure it's a feature that's needed 80%+ of the time.

**Comment by SDavisMedia** [comment]
I think most people use the name as sort of a short description. I do, at least. A description would probably be useless for those who don't need it and extremely helpful for those who do. Lifhtweight extension territory, perhaps.

**Comment by pippinsplugins** [comment]
Right, that was my thought. The name field is never shown publicly.

**Comment by shiftwebsolutions** [comment]
I do use the name as a short description, obviously. But the purpose of a larger text area is to allow more notes and details about each coupon code. For someone who does a lot of marketing and experimenting, it helps to be able to write more details about the coupon.

**Comment by pippinsplugins** [comment]
@shiftwebsolutions we can definitely consider it. Thank you for the feedback.

**Comment by JeroenSormani** [comment]
@shiftwebsolutions this code snippet should work in your case :smile: 
https://gist.github.com/JeroenSormani/4096cf0fbe0097384626

**Comment by pippinsplugins** [comment]
I don't think we've had enough requests to warrant building this. I'm closing as wontfix for now but we can reopen if there is enough demand for it.
