### ISSUE TITLE
Typo in class-edd-stats.php

### ISSUE THREAD

**Issue by christophherr** [easydigitaldownloads/Easy-Digital-Downloads#3873]
Hi,
I am translating text strings on translate.wordpress.org and found a typo in
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/class-edd-stats.php#L91

It should say 'Last Quarter" instead of 'Last Quater'.

**Comment by pippinsplugins** [comment]
#3874
