### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by christophherr** [easydigitaldownloads/Easy-Digital-Downloads#3875]
Hi, 
I´m opening this issue for typos following Pippin's comment here: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/pull/3874#issuecomment-145414349

**Comment by pippinsplugins** [comment]
Thanks @christophherr! Could you submit those as pull requests? We'll be happy to merge them in.

**Comment by christophherr** [comment]
PR #3878 submitted. 

There are about 40% of text strings left to translate.

There are quite a few single-line sentences that don't end with a period. 
I am not sure whether that is by design or not. 

While I believe using "log in to" is a bit more correct than using "log into", I don't want to start a philosophical debate about it. (Reference: http://english.stackexchange.com/questions/5302/log-in-to-or-log-into-or-login-to)

There are a bunch of text strings in includes/admin/settings/register-settings.php that seem to be a bit off. Should I submit a PR with my suggestions?

**Comment by pippinsplugins** [comment]
Thanks for those!

**Comment by cklosowski** [comment]
so @pippinsplugins is this merged?

**Comment by cklosowski** [comment]
I mean I see the PR is, but there was quite a few commits so I just want to make sure before I close it out.

**Comment by pippinsplugins** [comment]
Yes merged.
