### ISSUE TITLE
Column classes

### ISSUE THREAD

**Issue by kiarashi** [easydigitaldownloads/Easy-Digital-Downloads#3876]
Not sure if it's mentioned before but there are some problems with column classes.
There are extra quotes around the number of columns.

https://cloud.githubusercontent.com/assets/7079137/10288799/64a3434e-6b9b-11e5-88b2-a99253ea9248.png

**Comment by mindctrl** [comment]
@kiarashi I'm not seeing that locally. Could you go ahead and open a support ticket with some more details so we can track it down? https://easydigitaldownloads.com/support/
