### ISSUE TITLE
Logged in user, different email address, new customer

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/Easy-Digital-Downloads#3881]
When a logged in user makes a purchase, but uses a different email address on the checkout form, it creates a 2nd customer for this new email address, attaches the payment to them, and makes the customer attached to the user id (leaving 2 customers with the same user id). We should attach to the same customer.

**Comment by pippinsplugins** [comment]
This is related to #3755

**Comment by pippinsplugins** [comment]
Works perfectly.
