### ISSUE TITLE
Improve extension license key activation and add weekly status checks

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#3889]
We run into issues all the time where people aren't seeing updates for extensions. Most of the time this is because they had them active on a development URL, they migrated their database (thus keeping stored statuses), and now updates never show up because the URL isn't valid for the license.

We need to implement a weekly cron job that checks the status of all entered license keys and then shows a notice of some kind to the site admin if it is not valid.

This will help with renewals (since we can show a license is expired) and it will help ensure users get updates properly since they'll be more likely to update the license with the proper URL.

We will need to ensure proper documentation is linked to from the notices to help people renew keys or change the URL for a license.

While doing this, we should also improve the overall licenses screen because it's really crappy.

**Comment by pippinsplugins** [comment]
@SDavisMedia This is ready for your magic. A few notes:

1. Uncomment line 111 of `class-edd-license-handler.php` to easily test license key messages:
```php
add_action( 'admin_init', array( $this, 'weekly_license_check' ) );
```

2. The HTML for each license key field is controlled by the `edd_license_key_callback()` function in `register-settings.php`

**Comment by SDavisMedia** [comment]
On it.

**Comment by SDavisMedia** [comment]
Also note that this notice should probably be reworded: *Your license key for Commissions License Key is not active for this URL.* I don't think `$args['name']` works well here: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/e8fd23ac018b3df8d64aece9e4c7ba52fbcc5160/includes/admin/settings/register-settings.php#L1687

**Comment by pippinsplugins** [comment]
Looking good!
![screen shot 2015-10-07 at 2 04 13 pm](https://cloud.githubusercontent.com/assets/1034109/10348046/6c86c7f4-6cfc-11e5-891f-b2126e8b1892.png)

**Comment by mindctrl** [comment]
`weekly_license_check` got uncommented here. We want that?

**Comment by pippinsplugins** [comment]
Nope!

**Comment by SDavisMedia** [comment]
@pippinsplugins refactored some CSS... doesn't change anything visually

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
Looks like there is a PHP notice when saving other settings tabs. Oops

**Comment by pippinsplugins** [comment]
This is now merged into `release/2.5` and is ready for additional testing.

**Comment by cklosowski** [comment]
As @mindctrl pointed out, it looks a little 'cluttered', is it possible to make the notice wrapper go through the entire row, and not just the text field column? that might help i tout.

**Comment by SDavisMedia** [comment]
I should note before going at this again that it is cluttered because the content is cluttered by default... always has been with the table layout. Something like this would be much better as a grid display with separate blocks for each extension. 

Right now, the different extensions aren't enclosed by any visual borders. So when you add edges to one element, it will automatically appear to encroach on nearby elements.

**Comment by pippinsplugins** [comment]
An option we could consider is building a new table display similar to taxes.

Any thoughts or opinions on that?

**Comment by pippinsplugins** [comment]
Grid display would also work.

We should be able to make it entirely custom.

**Comment by SDavisMedia** [comment]
I'm good with either. Since we can go custom there, I would honestly like to. Thoughts @cklosowski @mindctrl?

**Comment by cklosowski** [comment]
I'd love to see what you come up with for a custom view.

**Comment by mindctrl** [comment]
Hmm yeah custom sounds nice.

**Comment by pippinsplugins** [comment]
Anyone want to take lead on mocking it up?

**Comment by SDavisMedia** [comment]
Well duhhhhh I'll do it. All the code should be there for me already. Just need to write some new HTML. Probably repeat as much markup as possible from the extensions page. I'll make it a priority since it's for 2.5.

**Comment by pippinsplugins** [comment]
@SDavisMedia You may want to write just the plain HTML and then we can merge it in. It'll be a bit more complex than just changing the HTML since we have to work with the EDD_License_Handler class.

**Comment by pippinsplugins** [comment]
We'll have to rework a bit of how the settings themselves are added to the page.

**Comment by SDavisMedia** [comment]
Got it. I'll build a frame.

**Comment by cklosowski** [comment]
I'm seeing a small issue with the check of `$license->license` for `invalid` vs `expired`. If a license is expired, the `license` attribute returns `invalid` not expired. The `error` attribute of the object states `expired`, so we should move the `expired` check to the `invalid/site_inactive` part of the switch, and just throw an `if` clause in there for checking if the error is `expired`, otherwise.

**Comment by cklosowski** [comment]
Ok narrowed it down...if the license key you add to the License page is ALREADY expired, you get the `invalid` status, so you don't see the note to renew, just that you need to activate it for this site, which is incorrect.

If a license key is expired when it's added, the expired message should show. I'll try and fix that up quick.

**Comment by cklosowski** [comment]
Basically the `actiavte_license` returns a `license` attribute of `invalid` not `expired` when you try and activate it.

**Comment by cklosowski** [comment]
```
{
  "success": false,
  "error": "expired",
  "expires": "2015-11-16 23:59:59",
  "license_limit": 1,
  "site_count": 0,
  "activations_left": 1,
  "license": "invalid",
  "item_name": "Amazon S3",
  "payment_id": "######",
  "customer_name": "Chris Klosowski",
  "customer_email": "chris@easydigitaldownloads.com"
}
```

**Comment by pippinsplugins** [comment]
@cklosowski Changes fix it for me.

I see a different issue now those.

I entered a fake license key and got an improper error message:
![screen shot 2015-11-24 at 9 18 49 am](https://cloud.githubusercontent.com/assets/1034109/11371117/74eca9a8-928c-11e5-909b-cb64aff41aa3.png)

**Comment by cklosowski** [comment]
Ok my changes wouldn't have made this happen, it's also what the SL API returns when you try and activate a license when it's not valid:
```
{
  "success": false,
  "error": "missing",
  "license_limit": false,
  "site_count": 0,
  "expires": false,
  "activations_left": "unlimited",
  "license": "invalid",
  "item_name": "Amazon S3",
  "payment_id": false,
  "customer_name": " ",
  "customer_email": null
}
```
I think we just need a message for the error of `missing` to state that it's not a valid license.

**Comment by cklosowski** [comment]
Notice that in the above, the `license` is set to `invalid` which in switch for this page, just loads up the `go activate it` message.

**Comment by cklosowski** [comment]
Ok, it's now capturing the `missing` status on activation.

**Comment by pippinsplugins** [comment]
@easydigitaldownloads/core-devs How do we feel about leaving this as is for 2.5 and then improving further later on? This is still a massive improvement.

**Comment by SDavisMedia** [comment]
@pippinsplugins In regard to the HTML structure changes or other things? If the former, please yes.

**Comment by pippinsplugins** [comment]
The former.

**Comment by cklosowski** [comment]
I'm good with this as is, we can update the markup in future versions, the key was getting the backend stuff in place.

**Comment by cklosowski** [comment]
Closing this out as we're happy with it as is. Opened up #4050 to do further improvements.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
There's some odd behavior going on when license keys are invalid. See #4050 for comments from Sean.

**Comment by SDavisMedia** [comment]
@cklosowski Been playing with with the adjustments after our testing and one thing I can't do for sure is get the proper output for an expired license.

But with all of this, a big problem is that licenses are jumping back and forth between the proper output and having nothing but the key in the field and I don't know why.

I think to test this for sure, someone else needs to test every single license status at the same time. I'm trying to do that and getting super inconsistent behavior.

**Comment by cklosowski** [comment]
@SDavisMedia let me know if those changes we made last night work for you.

**Comment by SDavisMedia** [comment]
@cklosowski Everything appears to be working perfectly now. Does the mismatch situation need to repeat the license key in the error message? That's the only thing I wouldn't mind seeing changed. Everything else is good.

**Comment by cklosowski** [comment]
@SDavisMedia are you saying, remove the license key in the item_name_mismatch case?

**Comment by SDavisMedia** [comment]
@cklosowski If you all agree that it's cool to do so. It's long and a bit obnoxious IMO. I'll admit that my motive is having as little word wrap in that area as possible but I still think it's excessive.

**Comment by cklosowski** [comment]
I can live with that. @pippinsplugins you good with removing the license key from the `item_name_mismatch` error? It's in the text field still, so it's a bit redundant.

**Comment by cklosowski** [comment]
How about this?

![screen shot 2015-12-18 at 4 52 05 pm](https://cloud.githubusercontent.com/assets/1390124/11909693/b3015cf6-a5a7-11e5-81e3-20874dd569ae.png)

The namestring we get is `<Product Name> License Key`, so we can just shorten it to this I believe.

**Comment by SDavisMedia** [comment]
Spoke to you about this on Slack but I'll say here I like that. :point_up_2:

**Comment by cklosowski** [comment]
:+1: I'll commit that up then.

**Comment by pippinsplugins** [comment]
Pretty sure we can close this out now.
