### ISSUE TITLE
Standardize edd_get_cart_contents()

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/Easy-Digital-Downloads#3893]
Right now `edd_get_cart_contents()` returns an array of items if there are items in the cart, but `false` if there are none. We should really standardize this output, and return an empty array `array()` if there are no items in the cart. This way we don't have to do extra checks when iterating over it, and can avoid a `mixed` return type.

The good part is that `array()` and `false` both are met with an `empty()` check, so we shouldn't have to refactor much else when using it.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
Changes in #3932 look good. Anything else you want to change or are we good?

**Comment by cklosowski** [comment]
Nope that's all I wanted to do, closing out.
