### ISSUE TITLE
Add non-item to EDD_HTML_Elements::discount_dropdown()

### ISSUE THREAD

**Issue by topher1kenobe** [easydigitaldownloads/Easy-Digital-Downloads#3895]
Right now, if EDD_HTML_Elements::discount_dropdown() is called, it lists ONLY discounts, with no non-item option (like "Choose a discount").  This means that if the drop list is part of a form, that form WILL be using a discount.  The only workaround right now is to make a discount that does nothing, and choose that if you don't want a discount.

**Comment by mindctrl** [comment]
We're forcing `'show_option_none' => false` [here](https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/class-edd-html-elements.php#L212). Ideally we could control both of the all/none options, and any other features in `select()`.

**Comment by pippinsplugins** [comment]
Could probably just remove that.
