### ISSUE TITLE
Report for earnings, date range = this year completely broken

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#3897]
![image](https://cloud.githubusercontent.com/assets/1324637/10402486/b7b1fe90-6e93-11e5-9e7f-1e88ffdaa5d5.png)

**Comment by chriscct7** [comment]
Custom end year does the same thing because it seems to default to 2014. Maybe this_year is doing the same thing

**Comment by pippinsplugins** [comment]
@chriscct7 Works for me on latest `master`.

**Comment by pippinsplugins** [comment]
Closing as invalid.
