### ISSUE TITLE
HTML showing inside sales summary dashboard widget

### ISSUE THREAD

**Issue by sumobi** [easydigitaldownloads/easy-digital-downloads#3900]
HTML showing inside sales summary dashboard widget. Anyone seen this before?

![screen shot 2015-10-12 at 1 12 30 pm](https://cloud.githubusercontent.com/assets/52581/10419943/01550dca-70e3-11e5-95ee-e5da4d231d26.png)

**Comment by pippinsplugins** [comment]
I've never seen this before. Does it happen to you everywhere or just in
that one site?

**Comment by sumobi** [comment]
@pippinsplugins totally missed this. Only sites that have no purchases I believe. Log in to the RCP site (I used Chrome) and wait for the heartbeat. It should change from $0.00 values to what you see above.

**Comment by pippinsplugins** [comment]
I still can't make it happen . .

**Comment by sumobi** [comment]
That's odd. I see the same issue in Firefox, Safari and Chrome. It takes a few seconds for it to change.

**Comment by pippinsplugins** [comment]
Just tested this again and still cannot replicate it . . .

**Comment by sumobi** [comment]
@pippinsplugins It took a while, over 5-10minutes, but logged into RCP site in Chrome (+ on new laptop) and it eventually changed. Maybe leave the dashboard open in Chrome and wait a bit longer.

**Comment by sumobi** [comment]
and don't forget to click your heels together 3 times

**Comment by pippinsplugins** [comment]
It's been sitting for 15 . . . no HTML.

**Comment by pippinsplugins** [comment]
Still all good: https://cloudup.com/cegi--01zWU

**Comment by sumobi** [comment]
Hmm you testing the RCP site? I see no recent purchases in your screenshot

**Comment by sumobi** [comment]
Just replicated on @wordmaid's laptop also

**Comment by sumobi** [comment]
@pippinsplugins I'll try and replicate it again on a live site. I have seen it before somewhere else, just can't remember where. It's entirely possible it's limited to the RCP site in some way.

**Comment by sumobi** [comment]
@pippinsplugins can't replicate on live site anymore, or locally. Guess it's only limited to RCP site now. Feel free to close.

**Comment by pippinsplugins** [comment]
I just replicated this! No idea how but I saw it.
![screen shot 2016-03-23 at 9 45 58 am](https://cloud.githubusercontent.com/assets/1034109/13988918/2139998e-f0dc-11e5-8774-c21c31223f3b.png)

**Comment by SDavisMedia** [comment]
I tried so hard to replicate this last night. Nothing.

**Comment by pippinsplugins** [comment]
This is the new white whale.

**Comment by sumobi** [comment]
Get your harpoons ready

**Comment by spencerfinnell** [comment]
There is no default `<span class="currency">` around the currency is there? Didn't see one in any of the filters, and it can be replicated by mocking that + the heartbeat:

```
<?php
add_filter( 'edd_usd_currency_filter_before', function( $cur ) {
	return '<span class="currency">' . $cur . '</span>';
});
?>

<span class="test"></span>

<script>
(function($) {
	$( '.test' ).text( '<?php echo html_entity_decode( edd_currency_filter( edd_format_amount( 0 ) ), ENT_COMPAT, 'UTF-8' );  ?>' );
} (jQuery) );
</script>
```

Prints:

```
<span class="currency">$0</span>
```

**Comment by sunnyratilal** [comment]
Found where this is originating from. It's actually from themedd: https://github.com/restrictcontentpro/rcp-site-child/blob/master/includes/edd-functions.php#L929

Next step is finding out why it's displaying the `span` intermittently.

**Comment by sumobi** [comment]
@sunnyratilal I think you're right. It's probably the silly function that uses the currency filter which I'm using on the front-end of the child theme (not specific to themedd). And of course the dashboard widget is using that filter also, doh. Sunny harpooned it I think.

**Comment by SDavisMedia** [comment]
nice @sunnyratilal

**Comment by sunnyratilal** [comment]
As this is not an EDD specific issue are we good to close this issue?

**Comment by pippinsplugins** [comment]
Yes I think so.
