### ISSUE TITLE
Missing Personal Info fields when using "Login Form Only" with guest checkouts enabled

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/Easy-Digital-Downloads#3902]
When EDD is configured to:
- allow guest checkouts
- show only the login form on the checkout screen

the `Personal Info` section doesn't show on the checkout screen. This effectively makes it unusable unless you do have a login. 

##### EDD Config
![image](https://cloud.githubusercontent.com/assets/1254870/10433404/a1d278fe-70df-11e5-9078-f918ce185328.png)

##### Checkout
![image](https://cloud.githubusercontent.com/assets/1254870/10433428/c8ffefa6-70df-11e5-8a5f-f97fe3a575ad.png)

When configured in this way, the `Personal Info` fields should be displayed so that customers who do not have a login can still purchase. Like this:

![image](https://cloud.githubusercontent.com/assets/1254870/10433475/25bb7f8a-70e0-11e5-80ca-025742178b4f.png)

**Comment by pippinsplugins** [comment]
Replicated.

**Comment by mindctrl** [comment]
This works now. Opened https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/3905 for UI work related to this for 2.6 milestone.

**Comment by SDavisMedia** [comment]
Yes, all good here. :+1:

**Comment by pippinsplugins** [comment]
Great, will let @cklosowski review and merge.

**Comment by cklosowski** [comment]
Looks good to me, verified and tested it out.
