### ISSUE TITLE
Profile editor HTML structure should match the rest of EDD

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/easy-digital-downloads#3904]
Super strange mix of markup in the profile editor form:

https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/fbe20f79334ef6bd21f6a9810e8e5977bef116df/templates/shortcode-profile-editor.php#L28

Would be nice if each field was wrapped in a `p` individually like the login and register forms:

https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/fbe20f79334ef6bd21f6a9810e8e5977bef116df/templates/shortcode-register.php

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
Before:
![screen shot 2016-08-12 at 11 32 35 am](https://cloud.githubusercontent.com/assets/1034109/17629539/7e803b8e-6080-11e6-9c71-6ed7f4952e79.png)

After:
![screen shot 2016-08-12 at 11 31 19 am](https://cloud.githubusercontent.com/assets/1034109/17629517/63488ef2-6080-11e6-9770-e880c855e84e.png)

Thoughts?

**Comment by pippinsplugins** [comment]
See exact changes https://github.com/easydigitaldownloads/easy-digital-downloads/commit/80e633fe0bb112fd93abd7d264782e7a60f1b390

**Comment by spencerfinnell** [comment]
Awesome, helps a lot. We'll remove our CSS shims in the next release of Marketify.

**Comment by sumobi** [comment]
Great improvement 👍

**Comment by SDavisMedia** [comment]
I'll have to update all of the themes but it's worth it. :+1:

**Comment by pippinsplugins** [comment]
@spencerfinnell @sumobi @SDavisMedia happy with this PR? I'd like to merge it as soon as possible.

**Comment by pippinsplugins** [comment]
Vendd before:
![screen shot 2016-10-14 at 11 25 13 am](https://cloud.githubusercontent.com/assets/1034109/19394964/e8447056-9200-11e6-9bd4-1f5089cd18a7.png)

Vendd after:
![screen shot 2016-10-14 at 11 25 45 am](https://cloud.githubusercontent.com/assets/1034109/19394986/fa0dfd02-9200-11e6-8d94-373cfa1f62cd.png)

Will definitely need some CSS updates.

**Comment by SDavisMedia** [comment]
@pippinsplugins The HTML looks perfectly fine to me. I see no issues with merging. I'll style based on `release/2.7`.

**Comment by pippinsplugins** [comment]
Ok merging. Will leave open for testing and possible tweaks.

**Comment by sumobi** [comment]
@pippinsplugins @cklosowski This doesn't appear to have been merged. The 2.7.5 changelog says:

> Tweak: Updated Profile Editor markup to match current EDD markup format.

Still has old code:

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/templates/shortcode-profile-editor.php

**Comment by ghost1227** [comment]
@pippinsplugins assigning you since you wrote the original patch

**Comment by pippinsplugins** [comment]
How the heck . . .

**Comment by pippinsplugins** [comment]
Github is telling me there's nothing possible to merge from `issue/3904` . . . . yet the files are clearly different.

**Comment by pippinsplugins** [comment]
@ghost1227 please take over and see what you can find.

**Comment by ghost1227** [comment]
@pippinsplugins Definitely lost all the markup somewhere. Not sure what happened, but I rewrote the markup for the current `master` branch (and fixed a mistyped ID in the original).

**Comment by pippinsplugins** [comment]
@SDavisMedia could you look over this please and confirm it's good to go (again)?

**Comment by SDavisMedia** [comment]
Yup. Everything is still looking good on my end. :+1:
