### ISSUE TITLE
State / Province TEXT field not populating saved data

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/Easy-Digital-Downloads#3906]
If a customer account has a country like Afghanistan selected where there is no set list of states/provinces/etc., the checkout form switches the State / province field to a text field, which is fine.

But a logged in user can have saved address data from previous purchases or from using the profile editor. The saved State/Province field data is not populating at checkout.

**Comment by pippinsplugins** [comment]
Good catch.
