### ISSUE TITLE
New customer not created from existing WordPress user

### ISSUE THREAD

**Issue by stephywells** [easydigitaldownloads/Easy-Digital-Downloads#3916]
edd_insert_payment( $payment_data ) will only link up with an existing customer or the current user. Since 2.4.8, new customers aren't being created. I'm doing an import into EDD, and since today, every payment shows up on my customer page instead of creating a new customer for a user that exists in WordPress.

$payment_data = array(
....
'user_id'       => $user->ID,
'user_email'    => $user->user_email,
'user_info'     => array(
  'id'            => $user->ID,
  'email'         => $user->user_email,
  'first_name'    => $user->first_name,
  'last_name'     => $user->last_name,
  'discount'      => 'none'
),
);
edd_insert_payment( $payment_data );

**Comment by pippinsplugins** [comment]
@stephywells are you logged in while doing the import?

**Comment by pippinsplugins** [comment]
Related #3881

**Comment by stephywells** [comment]
Yes, I am logged in while importing.

**Comment by pippinsplugins** [comment]
We'll get it tracked down and fixed today.

**Comment by pippinsplugins** [comment]
@cklosowski We need to fix the case on `customer` here too: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/97b950a3fa44a46c678b1e9c1d8c3befc7e7635e/includes/payments/functions.php#L181

**Comment by pippinsplugins** [comment]
Oh, @stephywells, looks like your `email` parameter is incorrect. It should be `user_email` not `email`.

Does that fix it?

**Comment by stephywells** [comment]
No, that doesn't fix it. Thanks so much for looking into this!

**Comment by pippinsplugins** [comment]
We'll keep digging!

**Comment by stephywells** [comment]
It looks like email is right inside the user_info array.
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/process-download.php#l100

How about this in place of this line so the user id with the payment is used instead of the current user?
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/97b950a3fa44a46c678b1e9c1d8c3befc7e7635e/includes/payments/functions.php#L180-182

		if ( empty( $customer->id ) && is_user_logged_in() ) {
			if ( ! empty( $payment_data['user_info']['id'] ) )  {
				$customer  = new EDD_customer( $payment_data['user_info']['id'], true );
			} else {
				$customer  = new EDD_customer( get_current_user_id(), true );
			}
		}

**Comment by cklosowski** [comment]
@stephywells Yes that's the line we're working with. The goal was to fix a bug of creating a new customer when a different email was used than that of the currently logged in `user/customer`. Just need to get it to identify when it's not a checkout session and we should be good to go. Working on a fix now and will release it today.

**Comment by stephywells** [comment]
Perfect! Thank you!

**Comment by cklosowski** [comment]
@stephywells @pippinsplugins here's my proposed fix:
```
if ( empty( $customer->id ) && did_action( 'edd_pre_process_purchase' ) && is_user_logged_in() ) {
	$customer  = new EDD_customer( get_current_user_id(), true );
}
```

This way the `edd_insert_payment()` doesn't look at the `get_current_user_id()` unless we've detected that the `edd_process_purchase_form()` function has been run, which does not happen when importing using the CSV Manager. By doing this, it will detect no customer was found, then follow our current logic of creating a customer, using the specified User ID based on the `$payment_data['user_info']['id']`

**Comment by stephywells** [comment]
Much better! Works great. Thanks again!

**Comment by cklosowski** [comment]
No worries, you tested this fix out and it's working @stephywells? It fixed things on my end from the import and front end use cases.

**Comment by stephywells** [comment]
Yep, works for me.

**Comment by cklosowski** [comment]
Added a bit more hardening to it, this way it checks the user first (when doing a processing a purchase) and then goes to the user email lookup, then creates a new customer. Will prevent using the email of an existing customer and having your payment attached to them.
