### ISSUE TITLE
[edd_receipt] shortcode options not working as expected 

### ISSUE THREAD

**Issue by DevinWalker** [easydigitaldownloads/Easy-Digital-Downloads#3919]
**Scenario:** A user doesn't want to display a receipt item like the date so they use the shortcode like this: `[edd_receipt price="false" date="false"]`

**Problem:** EDD isn't taking into account true/false values as strings rather than booleans and not respecting them:

![10-14-2015 4-21-53 pm](https://cloud.githubusercontent.com/assets/1571635/10500818/3cb8349c-7290-11e5-99ef-ddddf7781c13.png)

**Solution:** `filter_var( $edd_receipt_args['date'], FILTER_VALIDATE_BOOLEAN )`

Please verify so I can submit a PR

**Comment by pippinsplugins** [comment]
@DevinWalker Sounds great to me!

**Comment by pippinsplugins** [comment]
Thanks @DevinWalker! We'll get it in 2.5

**Comment by DevinWalker** [comment]
Awesome

**Comment by SDavisMedia** [comment]
Working just fine here. :+1:

**Comment by pippinsplugins** [comment]
:+1:
