### ISSUE TITLE
Add html5 required attribute to edd_get_cc_form fields

### ISSUE THREAD

**Issue by DevinWalker** [easydigitaldownloads/Easy-Digital-Downloads#3920]
The fields output within `edd_get_cc_form` are required, how about adding the required attrbute? http://www.wufoo.com/html5/attributes/09-required.html

**Comment by DevinWalker** [comment]
Decent article about this here: https://www.2checkout.com/blog/article/api-best-practices-part-ii-using-html5-field-validation/

**Comment by DevinWalker** [comment]
LMK if you're into this and I'll submit a PR

**Comment by pippinsplugins** [comment]
I don't see any reason not to do this.

**Comment by DevinWalker** [comment]
I added the attribute to the first name and email address field as well:

![10-16-2015 11-12-04 am](https://cloud.githubusercontent.com/assets/1571635/10549583/ccafdc28-73f6-11e5-84a3-51e1a6a8b830.png)

**Comment by michaelbeil** [comment]
That is slick @DevinWalker!

**Comment by DevinWalker** [comment]
@michaelbeil glad you like it :+1:

**Comment by pippinsplugins** [comment]
@DevinWalker I think we should probably only output the `required` attribute if the field is set as required with `edd_field_is_required()` otherwise we will almost certainly run into users that have made certain fields not required. With this they'd be unable to remove the `required` attribute.

**Comment by DevinWalker** [comment]
Good idea...

**Comment by pippinsplugins** [comment]
:+1:

**Comment by DevinWalker** [comment]
OK I surrounded the require field output with conditional checks now.

**Comment by SDavisMedia** [comment]
Worked perfectly for me. Checked the behavior of the new attributes as well as their removal when the fields are not on the required list. :+1:

**Comment by pippinsplugins** [comment]
Works great here too. Merged and closed.
