### ISSUE TITLE
Multiple slug for EDD.

### ISSUE THREAD

**Issue by KienTrong** [easydigitaldownloads/Easy-Digital-Downloads#3924]
Hi there, nice plugin and got some awesome addons too :) @pippinsplugins 

Is there a way to add multiple slug for EDD, and all of them are download item.

domain.com/themes/abc
domain.com/plugins/acb

I was trying to remove 'Download' post type slug and add category ( themes, plugins ... ) to the slug without success.

Thanks

**Comment by chriscct7** [comment]
Hi there,
Please note that github is not for support. It is for development tracking only.

Please open a support ticket at easydigitaldownloads.com and one of our support agents will be happy to help you at

Thanks
Chris
