### ISSUE TITLE
Amazon Payments onSignIn is deprecated 

### ISSUE THREAD

**Issue by geoffdutton** [easydigitaldownloads/easy-digital-downloads#3933]
I was having issues with the onSignIn callback that's passed to the OffAmazonPayments.button code (the JavaScript that generates the Amazon button). Here's a quote from the Amazon Payments team:

> The "onSignIn" method has been deprecated to obtain the orderReferenceId. The orderReferenceId has to be obtained from the Address or Wallet widget. Below are good documentations to get you started as well as a walkthrough:
> 
> https://payments.amazon.com/documentation/lpwa/201749840#201749950

I will attempt to create a pull request, but I think we just need it to forward to the wallet widget page after the state=return_auth&access_token=<Amazon access token> rather than passing an amazon_reference_id

Any other thoughts?

**Comment by pippinsplugins** [comment]
Thanks for the headsup! We'd be happy to accept / review a pull request. We can also look into it as well.

**Comment by sunnyratilal** [comment]
Based on this guide https://payments.amazon.co.uk/developer/documentation/lpwa/201953150, it seems that the `onSignIn` callback isn't deprecated as they are actively using it in their code samples and I don't see mention on this page anywhere of the callback being deprecated.

**Comment by pippinsplugins** [comment]
Going to close as invalid for now.
