### ISSUE TITLE
If default variable price isn't set, then $_POST[ '_edd_default_price_id' ] isn't set and a notice occurs.

### ISSUE THREAD

**Issue by Shelob9** [easydigitaldownloads/Easy-Digital-Downloads#3942]
I'm testing with EDD 2.4.9 and WP 4.3.1 I forgot to select a default price option when creating a download with variable prices. I got a notice that the index `_edd_default_price_id` was not set on l138 of `/includes/admin/downloads/metabox.php L138` This caused a PHP notice.

**Comment by pippinsplugins** [comment]
Duplicate of #3931
