### ISSUE TITLE
Clicking on Customer within Payment History Should Go to Customer's Profile

### ISSUE THREAD

**Issue by DevinWalker** [easydigitaldownloads/Easy-Digital-Downloads#3949]
**Scenario:** I'm viewing my payment history and I click on a Customer. 

**Problem:** My thought is that this should go to the customer's profile rather than showing all that cusotmer's transactions. I can already view this user's transactions from their profile. 

![10-27-2015 4-33-10 pm](https://cloud.githubusercontent.com/assets/1571635/10775774/9c3ea3b4-7cc8-11e5-8099-2ae82e9fd450.png)

**Comment by chriscct7** [comment]
There's a PR for this already at https://github.com/easydigitaldownloads/Easy-Digital-Downloads/pull/3799 that needs an update

**Comment by DevinWalker** [comment]
Oh nice!

**Comment by pippinsplugins** [comment]
Done in 9e1361d627610cbd043b6c305dfe1d9765bafdaa and #3799
