### ISSUE TITLE
WordPress 4.4 CSS bug and EDD tabs

### ISSUE THREAD

**Issue by DevinWalker** [easydigitaldownloads/Easy-Digital-Downloads#3952]
WordPress 4.4 changes tabs from h1 to h2 - with 4.4 beta2 I see:

![10-28-2015 5-34-19 pm](https://cloud.githubusercontent.com/assets/1571635/10807201/40dbb07a-7d9a-11e5-9644-fca8bd9f5bb2.png)

**Comment by DevinWalker** [comment]
It's also appearing under Downloads > Reports, Tools, anywhere where tabs are used with h2s

**Comment by pippinsplugins** [comment]
I noticed this last night as well.

**Comment by pippinsplugins** [comment]
Thanks @DevinWalker, I believe the changes in #3958 resolve this but will leave open for another look to confirm.

**Comment by cklosowski** [comment]
Yes they seem to have been fixed with that merge. I'm going to close this, thanks @DevinWalker
