### ISSUE TITLE
Sales dashboard widget is loaded on non-dashboard pages

### ISSUE THREAD

**Issue by ericnicolaas** [easydigitaldownloads/Easy-Digital-Downloads#3955]
The AJAX call that loads the dashboard widget is fired regardless of whether you're on the dashboard. Basically fires anywhere that `admin-scripts.js` is loaded.

Cheers, 
Eric

**Comment by pippinsplugins** [comment]
@ericnicolaas This has been resolved in the upcoming 2.5 release https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/3850

**Comment by ericnicolaas** [comment]
Nice :+1:
