### ISSUE TITLE
multiple customers per same user_id

### ISSUE THREAD

**Issue by selu91** [easydigitaldownloads/Easy-Digital-Downloads#3956]
Hello,

Is it possible to have multiple customers ( records in wp_edd_customers ) using same user_id ( record from wp_users ).

I see in our database that this is happening, creating problems in loading the purchase history.

Im asking if this is a normal behaviour, which makes me think our logic of thinking that only one customer is available per user is wrong, or it is a bug in the plugin ? 

Thank you !

**Comment by pippinsplugins** [comment]
No, a user ID should only ever be associated with a single customer record.

There was a bug with our migration process that resulted in this happening.

To resolve it for those customers/users, do this:

1. Pick a customer record to keep
2. Unassociate the `to throw away` customer record with the user account
3. Move all purchases from `to throw away` customer  to the `to keep` customer
4. Delete `to throw away` customer
