### ISSUE TITLE
Login on checkout : existing customers should be able to use their emails

### ISSUE THREAD

**Issue by Nikeo** [easydigitaldownloads/Easy-Digital-Downloads#3957]
This follows a Helpscout discussion (id : 8503 ) with John.

## Use case : an existing clients wants to buy another product, renew a license or upgrade.

On checkout, many existing clients don't remember their username and have to follow a password renewal process to access their EDD account.

Currently, the only way to login on checkout is to use a username + password as described with the screenshots below.

It would be better to enable either username or email during the checkout login. 

### On checkout, users already registered can login by clicking on the login link
![login_issue_on_checkout](https://cloud.githubusercontent.com/assets/3038156/10820406/5c2829fe-7e4d-11e5-8fee-dcfe37be3e49.png)

### Then here if they here they have the choice between an email or a username
![login_issue_on_checkout_2](https://cloud.githubusercontent.com/assets/3038156/10820408/5c2dbfae-7e4d-11e5-81a7-136038982b01.png)

### If they try to login with their email, they get the following error message
![login_issue_on_checkout_3](https://cloud.githubusercontent.com/assets/3038156/10820407/5c2cbff0-7e4d-11e5-8356-bd99f31b21f9.png)

**Comment by pippinsplugins** [comment]
Hi @Nikeo, thanks for the feedback!

We actually already have an issue logged for this( #3429) so I'm going to close this as a duplicate.

**Comment by Nikeo** [comment]
ok fine @pippinsplugins 
looking forward for the enhancement :)
