### ISSUE TITLE
North/South Korea country codes reversed

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/Easy-Digital-Downloads#3961]
'KP' is North Korea
'KR' is Sourth Korea

**Comment by cklosowski** [comment]
@SDavisMedia can you submit a PR for this and i'll get it merged in to `release/2.5`?

**Comment by SDavisMedia** [comment]
@cklosowski PR sent to `release/2.5`. Not 100% sure if that's where you wanted it but that's where it is, yo!
