### ISSUE TITLE
Export customers by taxonomy

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/easy-digital-downloads#3964]
Currently it is possible to export a CSV of customers and restrict the results by specific downloads. This could be enhanced by adding additional factors such as download category. Might look something like this:
<img width="560" alt="screenshot 2015-10-30 16 14 26" src="https://cloud.githubusercontent.com/assets/4993131/10856965/a3206b6c-7f21-11e5-8e02-1ed63ecfc6af.png">

**Comment by pippinsplugins** [comment]
I like this idea.

**Comment by sunnyratilal** [comment]
Title adjusted to export by taxonomy. We display `Earnings by Taxonomy` as a report so exporting should be allowed by taxonomy too for consistency.

**Comment by sunnyratilal** [comment]
Implemented & merged.
