### ISSUE TITLE
Eliminate use of WP_CONTENT_URL

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/Easy-Digital-Downloads#3971]
WP_CONTENT_URL is getting either deprecated or overhauled in 4.4 (a core trac ticket I'm working on). It is not, and has not, been the recommended way of getting the content url since content_url() was introduced in WordPress 2.6. Among many other issues, WP_CONTENT_URL does not respect https. Use of it should be swapped for content_url(): https://codex.wordpress.org/Function_Reference/content_url

**Comment by chriscct7** [comment]
There's currently 4 uses of it in EDD core

**Comment by pippinsplugins** [comment]
:+1:

**Comment by SDavisMedia** [comment]
I had no issues with the image related ones. Not sure how to test the other changes, though I couldn't find any issues with the file download process.

**Comment by pippinsplugins** [comment]
@SDavisMedia That's what we're looking for so good good

**Comment by cklosowski** [comment]
Sweet, @pippinsplugins you good if I merge this in then?

**Comment by pippinsplugins** [comment]
Go ahead1
