### ISSUE TITLE
Better handling of installation and removal for network activated and multisite installs

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/Easy-Digital-Downloads#3976]
Identified by the rtCamp crew

If you setup a Multisite, and network enable EDD, sub sites that are created don't get the custom tables for customer's created due to the fact that the `_edd_installed` transient will return `false`.

https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/install.php#L193

**Comment by pippinsplugins** [comment]
I propose we alter `edd_after_install()` to also include a check to see if the table exists and then create it if not. This should happen for all DB tables we have now and in the future, so perhaps a `maybe_create_table()` method in the base class that is then run inside of `edd_after_install()`.

**Comment by cklosowski** [comment]
@pippinsplugins that could work, are we then going to just ignore that check of the transients, so admin_init always checks for the tables existing? or should be put a timed option in that pulls the option, checks the last time we looked for the DB tables, and if it's past that time (weekly maybe?) we run the install of the tables if they don't exist?

**Comment by pippinsplugins** [comment]
I think we need to just make sure the function runs 100% of the time on sites that haven't run it yet. Perhaps instead of checking the transient it should check an option.

**Comment by cklosowski** [comment]
@pippinsplugins yeah I like checking an option, could we possibly make that option a timestamp in the future...like `WEEK_IN_SECONDS`, so on admin init, we check if the current time is greater than the last check + week in seconds, and if so, we check if the table exists, if not create it?

**Comment by cklosowski** [comment]
That way we're always checking, if someone deletes it...or setup a multisite in the past, this will backfill the table?

**Comment by pippinsplugins** [comment]
I like the `WEEK_IN_SECONDS` option.

**Comment by cklosowski** [comment]
As a note, we also need to delete our custom tables when a subsite is deleted. I'll add that in here as well.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
@cklosowski I've tested:

- [x] Activating on a single site in the network.
- [x] Network activating then using it on an existing site in the network. All settings, pages, and tables created properly once visiting dashboard.
- [ ] Network activating and then checking for install status without visiting site dashboard. _Did not work_. Install routine did not run on sites in the network.
- [x] Network activating then creating a new site in the network.
- [x] Deleting a site in the network. Customers table was properly deleted.

There was one nuance I found.

`edd_install()` is setup to fire `edd_run_install()` on each site in the network by looping over the sites:
```php
function edd_install( $network_wide = false ) {
	global $wpdb;

	if ( is_multisite() && $network_wide ) {

		foreach ( $wpdb->get_col( "SELECT blog_id FROM $wpdb->blogs" ) as $blog_id ) {

			switch_to_blog( $blog_id );
			edd_run_install();
			restore_current_blog();

		}

	} else {

		edd_run_install();

	}

}
register_activation_hook( EDD_PLUGIN_FILE, 'edd_install' );
```

This did not happen to me. The install routine was triggered by visiting the site's dashboard, at which point install ran properly.

I don't believe the `$network_wide` parameter was set to `true`.

There is another concern with this: it could potentially crash on large networks. Perhaps we should limit the foreach to 100 sites?

**Comment by pippinsplugins** [comment]
Correction: the foreach loop is running, but the customer table creation is failing. Settings and pages are created properly on each site in the network when network activated.

**Comment by cklosowski** [comment]
Correct the table is created once admin is visited and then continually checked once a week. This stays true to our old method and I think is the best bet for the table creation.

As far as the number of sites, yeah maybe limit to 100 as that's the safest for that limit.

**Comment by pippinsplugins** [comment]
The code looks to imply that the table would be created during network activation. Where's the catch I'm missing?

**Comment by cklosowski** [comment]
No it doesn't the table install stayed on admin_init. The network activation is just the installing of the options and defining of the settings so that the pages are created and options saved.

**Comment by pippinsplugins** [comment]
OH! Now I see it. Thanks

**Comment by cklosowski** [comment]
#1084 is nearly done, but I'm wondering if the more isolated tests in this issue will help that one pass correctly, once this is approved and merged I'll go back to testing that one out.

**Comment by pippinsplugins** [comment]
I'm going to run through this again though would also love two other sets of eyes to test as well.

**Comment by cklosowski** [comment]
For sure, this is a big update and we all have different environments (slightly) so I'd love some tests on this.

**Comment by mindctrl** [comment]
The first time I visit a site after network activating, I get a notice about the customer table missing.

![image](https://cloud.githubusercontent.com/assets/1254870/11302116/6f7971d4-8f69-11e5-80ea-717fafaeffe9.png)

But then I reload the page and it goes away. Table gets created. Purchases work fine. Customers are added. Is the initial error expected, or did something get tanked on my site?

**Comment by pippinsplugins** [comment]
@mindctrl That's because the table is created via a function tied to admin_init. It's created after the first page load. It was the only way to ensure the table gets created across all sites in a network reliably.

**Comment by mindctrl** [comment]
Ok, great.

This looks good. Only thing I'm seeing now is the dashboard stats are hanging, but I think that's already fixed in the release branch. Just dropping a note here to check it after merge.

**Comment by cklosowski** [comment]
@mindctrl Yeah I havne't pulled the `release/2.5` branch in to this in a while. Did you get that memory limit thing figured out? Or should I reduce the number of sites I auto install for on the network activation?

**Comment by cklosowski** [comment]
I'll look into the notice thing, i don't think it should show a notice...but let me review it.

**Comment by cklosowski** [comment]
Oh that's a DB error...ok we're expecting that, sorry.

**Comment by mindctrl** [comment]
@cklosowski my memory issue is ok now. Successfully network activated. I think 100 should be doable on most sites. Anyone running 100 sites probably already has more than the minimums configured for memory limits.

**Comment by cklosowski** [comment]
Sounds good. @pippinsplugins I'm good to merge this if you are ready

**Comment by pippinsplugins** [comment]
Merged.
