### ISSUE TITLE
Welcome page needs additonal CSS specificity

### ISSUE THREAD

**Issue by pderksen** [easydigitaldownloads/Easy-Digital-Downloads#3978]
In other words, EDD's welcome page CSS is messing with my plugins' welcome page CSS.

Couple ways to go about this...

1) Change the `about-wrap` generic WP class within inline styles here to `edd-about-wrap`:

https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/admin/welcome.php#L100-L121

Then update the various `<div class="wrap about-wrap">` containers to `<div class="wrap about-wrap edd-about-wrap">`

2) Just load/enqueue your welcome page inline styles on EDD welcome pages only. Not sure if this is straight-forward.

Thanks!

**Comment by SDavisMedia** [comment]
I automatically assumed we were only loading on EDD's page. I never cared for the admin head styles and wondered why they weren't in edd-admin.css. We'll definitely get this taken care of. Sorry about that!

**Comment by pippinsplugins** [comment]
@SDavisMedia could you look at this sometime this week or next? We'll get it in 2.5

**Comment by SDavisMedia** [comment]
Absolutely.

**Comment by pderksen** [comment]
Awesome thanks guys.

**Comment by SDavisMedia** [comment]
@pderksen I've taken care of this in `issue/3978`. Can you verify that your plugin pages are no longer interrupted?

**Comment by pippinsplugins** [comment]
@SDavisMedia Looks good from my end.

**Comment by pderksen** [comment]
@SDavisMedia Tested locally. Works just fine. Thanks!

**Comment by SDavisMedia** [comment]
@pderksen Sweet, thanks!
