### ISSUE TITLE
Download links break if campaign variables are added to them

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#3981]
I just discovered that file download links break (by giving a permissions error) if UTM tracking parameters are added to them.

We should look at allowing UTM variables on download URLs since that will be a common occurrence.

We could probably resolve it by simply stripping the UTM variables off the URL before we validate the token.

**Comment by pippinsplugins** [comment]
The Better Google Analytics plugin automatically adds the UTM links to outgoing emails: https://wordpress.org/plugins/better-analytics/

**Comment by cklosowski** [comment]
@pippinsplugins I would propose we strip any query string items with `utm_` in there. Might be even better to set an array of whitelisted query string parameters for download links, and then strip them based off that whitelist. Make it filterable as well so things can be added to them.

**Comment by pippinsplugins** [comment]
@cklosowski How about we strip _all_ query args that are no intentionally added by EDD.

**Comment by cklosowski** [comment]
@Pippinsplugins yeah let's just strip all that aren't ours.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by mindctrl** [comment]
Related: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/2597

**Comment by pippinsplugins** [comment]
Time for testing!
