### ISSUE TITLE
Error: Please enter billing state / province when taxes are enabled

### ISSUE THREAD

**Issue by samikeijonen** [easydigitaldownloads/easy-digital-downloads#3982]
When taxes are enabled at least these fields are required when using Stripe:
- Billing City
- Billing Country
- Billing State / Province

When a user select State / Province that is not US (like Germany) Billing State / Province gets label `nostates`. 

But the field is still required and we get this error at this point when trying to purchase:

```
Error: Please enter billing state / province 
```

**Comment by pippinsplugins** [comment]
This is a tricky one.

The `nostates` return means that EDD does not have a known list of states / provinces for that country and so a plain input field is given for the customer to enter their state or province.

Many countries will still expect a value to be entered there.

Perhaps the best solution is to have a list of countries that do _not_ need a state/province entered and only show the error if one of those countries is not selected.

**Comment by samikeijonen** [comment]
Yeah it's a tricky one. Users have reported that even if they write state / province for example the same as Billing City they still got the same error. They do this because in their county there is no states / provinces. Not in Finland either.

At first I had no idea what users were talking about when they had problems at checkout. But now pretty much all comes down to this.

**Comment by pippinsplugins** [comment]
A quick and dirty fix for your site would be to make the field not required: http://docs.easydigitaldownloads.com/article/256-modifying-the-required-checkout-fields

**Comment by samikeijonen** [comment]
Thanks! That's what I would have asked next:)

**Comment by cklosowski** [comment]
@samikeijonen would #5169 have resolved this? It will go with `2.6.12`

**Comment by pippinsplugins** [comment]
I'm 99% certain this is now resolved thanks to #5169. Closing as fixed.
