### ISSUE TITLE
Add CSV Product Export

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#3985]
CSV product export is currently handled by EDD CSV Manager, which we all know has some pain points. We should make use of our new bulk processing API and add this to core.

I've set this for 2.5 simply because we've had 5+ tickets in the last month about CSV Manager not working. I'm going to write this now and get it in.

**Comment by pippinsplugins** [comment]
I have this nearly complete. There are just a few column values that are not being populated properly.

**Comment by cklosowski** [comment]
Merged into `release/2.5` for further testing, seems to be working great alongside #3633

**Comment by pippinsplugins** [comment]
I'd like for @SDavisMedia and/or @mindctrl to give this a quick look before we close it out.

**Comment by mindctrl** [comment]
@pippinsplugins found an issue here where columns get shifted, possibly due to quotes/shortcodes in post_content. Reproduced on two sites.

Steps to reproduce:
- Create new download
- Insert an audio playlist in it. Example: [playlist ids="44884,44865"]
- Publish post
- Export CSV

The CSV columns get broken:
![image](https://cloud.githubusercontent.com/assets/1254870/10983443/7b173f4c-83e0-11e5-9c52-07158260a7e0.png)

Results in all following data getting shifted over to the right one column.

**Comment by mindctrl** [comment]
Actual shortcode from previous screenshot was `[playlist ids="276,278"]`

**Comment by mindctrl** [comment]
More data:

This:
`This is a "test" dude. "What we have here," moo.`

Results in:
![image](https://cloud.githubusercontent.com/assets/1254870/10983515/e4fd31fa-83e0-11e5-9e27-6fc663311802.png)

**Comment by pippinsplugins** [comment]
@mindctrl try again now on `issue/3985`

**Comment by pippinsplugins** [comment]
@cklosowski Could you test this once more as well?

**Comment by pippinsplugins** [comment]
Once 2.5 goes out, we need to remember to update `EDD CSV Manager` to remove the product export from there.

**Comment by pippinsplugins** [comment]
This has all been merged into `release/2.5` but still needs further testing to confirm everything is finalized.

**Comment by cklosowski** [comment]
Looks good to me, the one thing I see missing is the bundle data coming in. Is that something we're not supporting, since it would need to be configured after the other products are imported, and their IDs might be different?

**Comment by pippinsplugins** [comment]
Maybe the export could contain the product names that are bundled?

**Comment by cklosowski** [comment]
maybe, or that's just a caviet of the import. Id be nice to work, but I think is something that could be reworked.

**Comment by pippinsplugins** [comment]
I'm fine adding it later as well.

**Comment by pippinsplugins** [comment]
Closing as done.
