### ISSUE TITLE
Verification URL missing from email when email template is set to plain text

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#3988]
If the email template is set to plaintext, the account verification email loses it's verification URL. Instead of  the text being clickable, it shows like this:
![screen shot 2015-11-05 at 9 06 50 am](https://cloud.githubusercontent.com/assets/1034109/10971946/96249fd0-839c-11e5-8177-46ecd66258e5.png)

The account can't be verified since no URL is available.

I propose we fix this by adding a plain text version of the URL to the bottom of the email:

>>>Link not showing? Click here: URL HERE

**Comment by pippinsplugins** [comment]
My proposal:
![screen shot 2015-11-05 at 9 12 16 am](https://cloud.githubusercontent.com/assets/1034109/10972105/552b3178-839d-11e5-9c49-5bd5a77f81a8.png)
Plaintext:
![screen shot 2015-11-05 at 9 13 30 am](https://cloud.githubusercontent.com/assets/1034109/10972144/81611b7c-839d-11e5-82e0-6d90c7f748fb.png)

**Comment by cklosowski** [comment]
We say `click here` twice, can we change the backup text to something like `Visit the following URL`

**Comment by cklosowski** [comment]
there are some email clients that don't auto link URL strings.

**Comment by pippinsplugins** [comment]
I like that change for the text.
