### ISSUE TITLE
[edd_profile_editor] doesn't update name on customer record

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/Easy-Digital-Downloads#3997]
When updating the name fields in the profile editor, the user account gets updated but the customer record does not. This is not consistent with the email field, which does get updated on both user and customer records.

**Comment by pippinsplugins** [comment]
Ready for review.

**Comment by cklosowski** [comment]
@pippinsplugins this is already merged, you merged mine a while back: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/shortcodes.php#L833

**Comment by cklosowski** [comment]
#4177 was already closed for this: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/pull/4269
