### ISSUE TITLE
Product price is being rounded up/down

### ISSUE THREAD

**Issue by CodedInk** [easydigitaldownloads/Easy-Digital-Downloads#4002]
I cannot figure out why if I enter 9.99 in the back-end it shows as 10.00 on the pricing table?
If I enter 9.48 then it rounds down to 8.00 on the pricing table?

**Comment by pippinsplugins** [comment]
Hi @CodedInk.

For support requests like this, please open a ticket from our support page (which I see you just did): https://easydigitaldownloads.com/support

We will answer you there as soon as we are able.
