### ISSUE TITLE
Use <select> instead if <input type="text"> for "state" on profile editor when possible

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/easy-digital-downloads#4013]
Currently there is an inconsistency when it comes to customers declaring their state. On the checkout form, after country has been specified, the state field becomes a select populated with available states if they are available, otherwise it becomes a text input. When using [edd_profile_editor] however, the state field is always a text input.

It would be nice to make this a select field when possible. Displaying a text field instead allows for inconsistencies and typing errors. It also outputs the state code instead of the state name which, according to a customer I've been helping, is not always ideal. Some countries (Japan in this case) do technically have state codes but they are apparently not used much and displaying the state name would be much preferred.

I have a PR coming for consideration.

**Comment by pippinsplugins** [comment]
@brashrebel See https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/3982

**Comment by brashrebel** [comment]
@pippinsplugins yeah, I read through that. It seemed like a different issue though. This is just an enhancement to make the profile editor make state a select field _if possible_. I've got it working locally, just need to make a PR. Unless I'm missing something and shouldn't bother.

**Comment by pippinsplugins** [comment]
Oh, sorry, I missed the `profile editor` part :)

:+1:

**Comment by brashrebel** [comment]
Just made a PR.

**Comment by SDavisMedia** [comment]
This isn't ready for testing yet. https://github.com/easydigitaldownloads/Easy-Digital-Downloads/pull/4014

**Comment by cklosowski** [comment]
Pushing to 2.6 to match #4014 since they are related.

**Comment by cklosowski** [comment]
Thought of a little issue here when AJAX is disabled. I'll work up a fix on that.

**Comment by SDavisMedia** [comment]
Only issue I'm having is that with AJAX disabled, [edd_profile_editor] doesn't adjust the state/province field when you switch between counties. Is that the issue you found, @cklosowski.

Everything else seems to be working great.

**Comment by cklosowski** [comment]
@SDavisMedia yes that's the problem. @pippinsplugins and i were just talking about this, and we think we're just going to leave like that. Thoughts? I think we'd like to eventually get rid of the 'Disable AJAX' option, in the future.

**Comment by SDavisMedia** [comment]
I don't think there's anything wrong with that for now. They can save the form with the new country selected and then edit the state/province field once it reloads.

**Comment by cklosowski** [comment]
Yep that's my thought. I'm going to merge this in then.
