### ISSUE TITLE
Error while saving Issue

### ISSUE THREAD

**Issue by christ0ph3r** [easydigitaldownloads/Easy-Digital-Downloads#4015]
I recently started noticing error while saving issues on one of my sites.  Today I started debugging and EDD seems to be the issue.   I tested on another host, digital ocean with only EDD and 2015 theme.  I just spun up a brand new droplet with wordpress and issue persists still.   It happens when saving pages, posts, and custom post types.

```
### Begin System Info ###

-- Site Info

Site URL:                 http://104.236.186.247
Home URL:                 http://104.236.186.247
Multisite:                No

-- Hosting Provider

Host:                     DBH: localhost, SRV: 104.236.186.247
                 
-- WordPress Configuration

Version:                  4.3.1
Language:                 en_US
Permalink Structure:      /%year%/%monthnum%/%day%/%postname%/
Active Theme:             Twenty Fifteen 1.3
Show On Front:            posts
Remote Post:              wp_remote_post() works
Table Prefix:             Length: 3   Status: Acceptable
WP_DEBUG:                 Disabled
Memory Limit:             40M
Registered Post Stati:    publish, future, draft, pending, private, trash, auto-draft, inherit, refunded, failed, revoked, abandoned, active, inactive

-- EDD Configuration

Version:                  2.4.9
Upgraded From:            None
Test Mode:                Disabled
Ajax:                     Enabled
Guest Checkout:           Enabled
Symlinks:                 Disabled
Download Method:          Direct
Currency Code:            USD
Currency Position:        before
Decimal Separator:        .
Thousands Separator:      ,
Upgrades Completed:       upgrade_payment_taxes,upgrade_customer_payments_association,upgrade_user_api_keys,remove_refunded_sale_logs

-- EDD Page Configuration

Checkout:                 Valid
Checkout Page:            http://104.236.186.247/checkout/
Success Page:             http://104.236.186.247/checkout/purchase-confirmation/
Failure Page:             http://104.236.186.247/checkout/transaction-failed/
Downloads Slug:           /downloads

-- EDD Gateway Configuration

Enabled Gateways:         None

-- EDD Tax Configuration

Taxes:                    Disabled
Tax Rate:                 0
Display On Checkout:      Not Displayed
Prices Include Tax:       No

-- Must-Use Plugins


-- WordPress Active Plugins

Easy Digital Downloads: 2.4.9

-- WordPress Inactive Plugins

Akismet: 3.1.5
Hello Dolly: 1.6

-- Webserver Configuration

PHP Version:              5.5.9-1ubuntu4.13
MySQL Version:            5.5.46
Webserver Info:           Apache/2.4.7 (Ubuntu)

-- PHP Configuration

Safe Mode:                Disabled
Memory Limit:             256M
Upload Max Size:          2M
Post Max Size:            8M
Upload Max Filesize:      2M
Time Limit:               30
Max Input Vars:           1000
Display Errors:           N/A

-- PHP Extensions

cURL:                     Not Supported
fsockopen:                Supported
SOAP Client:              Installed
Suhosin:                  Not Installed

-- Session Configuration

EDD Use Sessions:         Enabled
Session:                  Enabled
Session Name:             PHPSESSID
Cookie Path:              /
Save Path:                /var/lib/php5
Use Cookies:              On
Use Only Cookies:         On

### End System Info ###
```

**Comment by christ0ph3r** [comment]
![error](https://cloud.githubusercontent.com/assets/5915361/11131681/b4643fba-8940-11e5-83cf-ebf312673009.png)

**Comment by pippinsplugins** [comment]
@christ0ph3r Can you please elaborate on the issue? What exactly happens when you try to save?

**Comment by christ0ph3r** [comment]
Sorry, I circled it.  Little hard to see at first.

![error2](https://cloud.githubusercontent.com/assets/5915361/11131794/4cc0050a-8941-11e5-8596-2f7162bbd808.png)

**Comment by christ0ph3r** [comment]
Data saves fine but there is an error.  And its slowing down my site it seems every time I update anything.

**Comment by pippinsplugins** [comment]
If you deactivate EDD, the issue goes away?

**Comment by christ0ph3r** [comment]
yes it only happens when EDD is installed

**Comment by christ0ph3r** [comment]
2.4.2 works

2.4.3 works

2.5.4 error

2.4.5 error

2.4.6 error

2.4.7 error

2.4.9 error

**Comment by christ0ph3r** [comment]
this commit causes the issue

https://github.com/easydigitaldownloads/Easy-Digital-Downloads/commit/3b3e4fb7b4b41dd6e27c5e8a17235e1cfe66cc32

If I comment out 

```
$default_cols = $this->get_csv_cols();
$default_cols = empty( $default_cols ) ? 0 : 1;
```

and put the old code back

```
$default_cols = empty( $this->get_csv_cols() ) ? 0 : 1;
```


the error goes away

**Comment by chriscct7** [comment]
What version of WordPress are you running?

**Comment by christ0ph3r** [comment]
4.3.1 . Its at the beginning of this issue with the other specs as well

**Comment by christ0ph3r** [comment]
actually I am still getting the error.  Commenting out didnt work, I thought it did.  Not sure if it was that commit but once I get to 2.4.4 things go wrong

**Comment by chriscct7** [comment]
Can you please log out, completely clear out your cookie and then log back in. That error in WordPress actually isn't from saving, it's from a failure to validate the nonce when WordPress attempts to autosave the post. It's probably slowing down your site because if that fails, heartbeat is also going to fail as well, but this actually isn't an EDD issue at all, since EDD's code doesn't have anything to do with or hook into that particular part of WordPress. It's either coming from heartbeat_autosave() which calls wp_autosave() and the error string is present in both in core

**Comment by christ0ph3r** [comment]
This is an EDD issue from what I see.  This only happens when EDD is installed and activated.  I do not get this error when EDD is deactived ever.

<h5>Steps to produce the issue:</h5>

1.  Install wordpress

2.  Plugins > add new > search edd > install

3.  Activate plugin

4.  Add a new page and put some random text as title and content and press publish

5.  Then press update and error will occur and every update after that

<h5>This is what I have done so far to test:</h5>

1.  Cleared cookies, cache, history, flash cookies, everything I could possibly clear

2.  Logged in with 4 different computer with different operating systems.

3.  Tested on newest mozilla and ie with no browser extensions and default browser settings.

4.  Tested it on php 5.5 and php 5.3 .

5.  Tested 50 popular plugins (I only get issue when EDD is installed )

6.  Had two other people test and 1 of them with a different ISP in another country

7.  Tested on multiping hosting companies

If I install an older version then whats in wordpress.org plugin search the error is not present https://github.com/easydigitaldownloads/Easy-Digital-Downloads/releases/tag/2.4.2 

I have ran EDD for a long time and this issue just started happening.

I am happy to send logins if anyone wants to look.

**Comment by cklosowski** [comment]
I saw the 'Error updating' on steps 4 and 5, however the next auto saved worked fine, here's the status I got from the admin-ajax.php call:
```
{"wp-refresh-post-lock":{"new_lock":"1447440411:1"},"wp_autosave":{"success":true,"message":"Draft saved at 11:46:51 am."},"wp-auth-check":true,"server_time":1447440411}
```
The initial save seems to say there was an error, but I cannot find any errors in my logs, and the next autosave, which took a couple minutes, to actually run (there were 2 auth checks without an autosave that ran, and then finally the autosave).

**Comment by cklosowski** [comment]
While typing that again, it worked:
```
{"wp-refresh-post-lock":{"new_lock":"1447440516:1"},"wp_autosave":{"success":true,"message":"Draft saved at 11:48:36 am."},"wp-auth-check":true,"server_time":1447440516}
```

**Comment by cklosowski** [comment]
It seems that on pages, there is something that triggers an autosave immediately after the page finishes loading after 2nd update...step 5 in your steps @christ0ph3r. This autosave has a `success: false`, but not even sure why it's running since it's JUST after the page is loaded, usually this should delay a minute or two

**Comment by cklosowski** [comment]
Still no PHP errors in the logs when this happens though.

**Comment by cklosowski** [comment]
@pippinsplugins @chriscct7 I'll dig into this one further.

**Comment by cklosowski** [comment]
Ok interesting note, I went back and installed 2.4.2, and the immediate 'autosave' isn't actually run on this version, but in 2.4.3, as soon as you Click publish -> wait for the page to load, then click Update, the next page refresh immediately kicks off an autosave.

**Comment by cklosowski** [comment]
The version issue for me is between 2.4.3 and 2.4.2.

**Comment by cklosowski** [comment]
For some reason we're getting the 2nd case here as the `wp_autosave` is returning a value of `0` for our data, which is populated:
```
		$saved = wp_autosave( $data['wp_autosave'] );

		if ( is_wp_error( $saved ) ) {
			$response['wp_autosave'] = array( 'success' => false, 'message' => $saved->get_error_message() );
		} elseif ( empty( $saved ) ) {
			$response['wp_autosave'] = array( 'success' => false, 'message' => __( 'Error while saving.' ) );
		} else {
			/* translators: draft saved date format, see http://php.net/date */
			$draft_saved_date_format = __( 'g:i:s a' );
			/* translators: %s: date and time */
			$response['wp_autosave'] = array( 'success' => true, 'message' => sprintf( __( 'Draft saved at %s.' ), date_i18n( $draft_saved_date_format ) ) );
		}
```

**Comment by cklosowski** [comment]
Ok, I think this is a core bug, that for some reason doesn't present itself without EDD, not sure why...but tracking it down, we know that `0` is what the `wp_autosave` function is returning.

Well when the `wp_autosave` runs `wp_create_post_autosave` there is a case that checks if the auto save is different from the draft...and returns `0`:
```
		if ( ! $autosave_is_different ) {
			wp_delete_post_revision( $old_autosave->ID );
			return 0;
		}
```
This would bubble up to an `empty()` check to being true, and that generic error we see instead of an actual error. Thoughts @pippinsplugins @chriscct7 @christ0ph3r

**Comment by cklosowski** [comment]
Seems like the `} elseif ( empty( $saved ) ) {` check in `heartbeat_autosave` should be checking for `false` not `empty()` as basically what is being seen is the autosave draft it makes for each author on the initial page load returns that it's not different than the last autosave created.

**Comment by cklosowski** [comment]
Found the bug:
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/commit/0f5e0c4c5aef56ad1ba8c0a4c98231023e652cee

The issue is we shouldn't be including `inline-edit-post` when we're on the edit screen, as it's only used for the Quick Edit of categories and tags. I'll log this for 2.5.

**Comment by cklosowski** [comment]
@christ0ph3r could you test this branch/PR out and let me know if that improves it for you?

**Comment by christ0ph3r** [comment]
Your PR is working great and the error no longer exists.

I really appreciate you digging into this so quickly.

:+1:

**Comment by SDavisMedia** [comment]
That fixes it for me too. :+1:

**Comment by cklosowski** [comment]
Awesome. Thanks guys. That one was bugging me so glad I could get it out of the way. 😉
