### ISSUE TITLE
Purchase Emails are not being sent! HELP! 

### ISSUE THREAD

**Issue by glennlouisparker** [easydigitaldownloads/Easy-Digital-Downloads#4020]
This plugin has been setup and running for some time now...

I've installed a testing email plug-in to be sure it was NOT the server. And sent out test emails to a number of email address. ALL came thru!

SO it's not the email on the server... Works perfect. Running on GoDaddy server... With email...

I've checked GLOBAL SPAM filters to be sure I was not tagged as SPAM... NOTHING comes up for my server IP, domain or email addresses...

Tested the template that is sent out to be sure it wasn't spammy no issues their ether.

Over the past 3 months about 10% of purchasers say they never get their email with the download
link

Then over the past 2-3 weeks it started to be 60% now it's almost 100% if not 100% I have to manual
send them the link to their product!

Now nothing has changed, any plug-ins I don't need are turn off.

All other aspects of the plug in are working, purchase with link-back to the main site that you can download your item!

I'm lost how to trouble shoot the plug-in or if their is simple fix, a bit of FLUFF in the system that I can clear. Cache or Temp files... ?!?!?

Any help or suggestions are greatly appropriated!!

Links to documentation, like issues or anything!

And thank you!

**Comment by pippinsplugins** [comment]
Our support team will be happy to assist you and get the issue resolved but we will have to ask that you open a support ticket: https://easydigitaldownloads.com/support

GitHub (where you are at) is for development tracking only.
