### ISSUE TITLE
Remove No Gateway blocker when order total is free

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#4026]
When the order total is 0.00, we should remove the "Error: You must enable a payment gateway to use Easy Digital Downloads" and allow checkout since on free orders we use the core free order gateway. It's reasonable to expect a store where all products are free and thus do not want any gateways active.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by ghost1227** [comment]
@pippinsplugins Do we really need to do anything here but remove the `edd_no_gateway_error` function?

**Comment by pippinsplugins** [comment]
@ghost1227 We still need it to show the error on orders > 0

**Comment by ghost1227** [comment]
Oh! silly me...

**Comment by pippinsplugins** [comment]
Works great.
