### ISSUE TITLE
Payments list table date filters off by 1 day

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/Easy-Digital-Downloads#4030]
When testing out #3471 @mindctrl found that the payments list table is incorrect when filtering it by date.

I have 1 payment in this install made on the 17th of November:
![screen shot 2015-11-18 at 1 16 21 pm](https://cloud.githubusercontent.com/assets/1390124/11253092/c44ce5c0-8df6-11e5-9a6f-59ce863d5f6a.png)

But when I ask for payments from Nov 1 - Nov 17th, it doesn't show up:
![screen shot 2015-11-18 at 1 16 09 pm](https://cloud.githubusercontent.com/assets/1390124/11253106/ce6b9d9e-8df6-11e5-90b3-33947ee0a4a3.png)

If I do the 18th, it does:
![screen shot 2015-11-18 at 1 18 22 pm](https://cloud.githubusercontent.com/assets/1390124/11253115/dcda1cac-8df6-11e5-85bb-2b0e26f19947.png)

**Comment by pippinsplugins** [comment]
Ready for testing.
