### ISSUE TITLE
Review accessibility

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#4031]
There are a lot of elements throughout EDD that are not properly setup for accessibility.

We need to do a thorough review of the entire codebase and resolve as much as we can.

The [WP Accessibility plugin](https://make.wordpress.org/accessibility/wp-accessibility-plugin/) will help a lot with this.

One of the primary issues we have is the use of mostly-useless title attributes. See [this core ticket](https://core.trac.wordpress.org/ticket/24766) for a detailed discussion.

**Comment by chriscct7** [comment]
We should also utilize https://make.wordpress.org/accessibility/2015/04/15/let-wordpress-speak-new-in-wordpress-4-2/

**Comment by pippinsplugins** [comment]
:+1:

**Comment by tw2113** [comment]
I realize it doesn't add much, but I want to give a :+1: to this as well. :)

**Comment by samikeijonen** [comment]
I'll start doing accessibility reviews on EDD Core. This is divided in two main areas:

1. **Admin**: There are lot's of admin pages. And inside those pages there are more or less functionality that needs to be checked.
2. **Front end**: Theme needs to handle most of front end but for example checkout page, shortcode outputs etc. needs to be checked.

Basically I'll go over every required `a11y` [checklist](https://make.wordpress.org/themes/handbook/review/accessibility/required/) and test EDD using keyboard only and screen readers.

Let me know if you have topics where would you like me to start. I'll start opening issues next week. Or even this week.

**Comment by pippinsplugins** [comment]
Excellent @samikeijonen!

Let's start with the most used pages first:
- Downloads list
- Download edit screen
- Payment History
- View Order Details
- Customers list
- Customer details screen

**Comment by samikeijonen** [comment]
Sounds good, I'll start with those.

**Comment by samikeijonen** [comment]
Okay, we have started doing `a11y` review. Slowly but still. This is just the beginning but we need to start somewhere. 

I'd like to wait for new PR before we know that we have right direction and some of those are merged.

**Comment by pippinsplugins** [comment]
Fantastic.
Let me know if you need anything!

**Comment by samikeijonen** [comment]
If you can test `a11y` PRs at some point that would be great. For me it's easier to move on after that.

**Comment by pippinsplugins** [comment]
@samikeijonen Yep! I've made it through some of them and will get the rest before 2.6 is finished.

**Comment by cklosowski** [comment]
@pippinsplugins @samikeijonen I knwo a bunch of PRs were submitted for `a11y`, how are we looking for this issues specifically stated for `release/2.6` changes? Are we good to close this one?

**Comment by pippinsplugins** [comment]
Everything that has been reported is merged in I believe.

**Comment by cklosowski** [comment]
Ok I'm going to close this for now @samikeijonen if you find something we've missed please ping me or reopen it.

👍

**Comment by samikeijonen** [comment]
Sure. I'm about the start accessibility talk  in meetup 😃

**Comment by samikeijonen** [comment]
Just a note that this is just a beginning of accessibility checks in EDD. We are probably not even done with [most used pages yet](https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4031#issuecomment-185255849).

But I'll open new issues when I have time to start another `a11y` round.

**Comment by pippinsplugins** [comment]
@samikeijonen thanks!
