### ISSUE TITLE
Issue with year_end in reporting breaking some earnings reports

### ISSUE THREAD

**Issue by fpcorso** [easydigitaldownloads/easy-digital-downloads#4035]
Hey everyone,

I was reviewing my earnings reports today and realized some are now broken when viewed in certain orders. It seems to be stemming from the year_end but I am not sure on that.

The steps I took to discover the error:

* Went to Reports page and Reports tab.
* Select "Earnings" and click Show
* Select "This Quarter" and click Filter
* Notice year_end becomes 2016 correctly in url
* Now, Select "Last Quarter" or "This Year" and click Filter
* year_end becomes 2007 and this_year is still 2015
* No data is shown on graph nor is any value shown for total earnings or total sales

This is what is shown after following these steps:
![broken_this_year_example](https://cloud.githubusercontent.com/assets/9730040/11347115/fb3504b4-91ed-11e5-82fa-bb0cc628aaa2.png)

If I go to another page and come back, and go directly to one of the broken graphs without going to "This Quarter" first, the graph shows correctly, as shown below:
![correct_this_year_example](https://cloud.githubusercontent.com/assets/9730040/11347148/2a960adc-91ee-11e5-8b28-5485234287a5.png)

EDD version: 2.4.9
WP version: 4.3.1
Possibly related to #3897 

Let me know if you need any additional information.

**Comment by pippinsplugins** [comment]
Thanks for the report, we'll look into it!

**Comment by cklosowski** [comment]
I belive this has to do with the URLs being used as the parser, and when certain items are selected from the time reports for the time period, we're not clearing some of the $_GET parameters, but will have to investigate. I've seen this before, but never got a chance to debug it further.

**Comment by brashrebel** [comment]
Just encountered a similar problem with a customer. Could be related though I'm unable to replicate currently. Here's the screenshots they provided:
![ss](https://cloud.githubusercontent.com/assets/4993131/12531121/4960cb66-c1c1-11e5-9f04-1c182579ea1e.jpg)
![ss2](https://cloud.githubusercontent.com/assets/4993131/12531120/495f59fc-c1c1-11e5-9cb6-f27e2faca568.jpg)
![ss3](https://cloud.githubusercontent.com/assets/4993131/12531119/495eb8bc-c1c1-11e5-9b97-95a81d0ecaa0.jpg)

As you can see, modifying the end date in this custom range changes the results in unexpected ways. The customer indicated the most recent actual sale occurred on 1/19/2016.

Anything I can do to help test this?

**Comment by pippinsplugins** [comment]
@brashrebel I believe that screenshot is from @fpcorso (the customer that opened the ticket and this issue) :)

Definitely something weird here.

@fpcorso @brashrebel can you identify any particular point that breaks it? For example, does December - February work? If so, what about November - February? Does it always break when crossing year boundary?

**Comment by brashrebel** [comment]
@pippinsplugins actually these screenshots were from a totally different customer. I can ask them to try different date ranges.

**Comment by pippinsplugins** [comment]
Cool, that would be great!

**Comment by cklosowski** [comment]
Ok I've replicated this. It's simply a fact that we're not resetting query string parameters correctly.

**Comment by cklosowski** [comment]
@easydigitaldownloads/core-devs I've got a proposal as well as I do this. Do we think that we should extend the `day by day` reporting to a 3 month span? This would allow a `This Quarter` and `Last Quarter` report to show daily stats. Is that something we want to try?

**Comment by sunnyratilal** [comment]
I think a `Day by Day` would be good

**Comment by michaelbeil** [comment]
👍🏼 for 'Day by Day'.

**Comment by pippinsplugins** [comment]
This appears to have broken default report views:
![screen shot 2016-06-13 at 3 24 54 pm](https://cloud.githubusercontent.com/assets/1034109/16021975/3257242c-317b-11e6-8bc0-ecc7c15f92b6.png)

**Comment by SDavisMedia** [comment]
I was able to replicate but the fix is producing errors and no graph data for me:

![screen shot 2016-06-13 at 4 14 39 pm](https://cloud.githubusercontent.com/assets/2359131/16026267/0ce17646-3182-11e6-916d-e736ae563e33.png)

**Comment by SDavisMedia** [comment]
That fixed it. 👍  Looking good on my end.

**Comment by cklosowski** [comment]
Thanks @SDavisMedia

**Comment by pippinsplugins** [comment]
This has somehow killed the `Estimated earnings` on graphs:
![screen shot 2016-06-14 at 11 22 54 am](https://cloud.githubusercontent.com/assets/1034109/16050731/5bf39b92-3222-11e6-9ebb-9d750aea4ed1.png)
It's not there anymore.

**Comment by cklosowski** [comment]
@pippinsplugins Strange, will look into that.

**Comment by cklosowski** [comment]
Should be fixed @pippinsplugins 

![screen shot 2016-06-14 at 10 12 38 am](https://cloud.githubusercontent.com/assets/1390124/16052316/8dacae6c-3218-11e6-888a-101c2ff80288.png)

**Comment by pippinsplugins** [comment]
Looks good.

**Comment by michaelbeil** [comment]
Works great!
