### ISSUE TITLE
Sub sections are a bit understyled

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/Easy-Digital-Downloads#4040]
It'd be nice if the subsections titles were more styled in feature\sub-sections. Right now, it's very easy to overlook those

**Comment by chriscct7** [comment]
![image](https://cloud.githubusercontent.com/assets/1324637/11410873/078b3f24-9399-11e5-8a36-b4bdb9669f53.png)

**Comment by cklosowski** [comment]
Well we haven't released this yet so log a note on the issue that feature is for.

**Comment by cklosowski** [comment]
Please leave feedback on #1960, the issue for the feature branch.

**Comment by chriscct7** [comment]
It'd be ic
