### ISSUE TITLE
edd_get_payment_status should be able to take a payment ID

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#4041]
Right now edd_get_payment_status only works if you have the post object of a payment, which is annoying since it's a really nice function to convert the payment status to the display status name with. We should allow edd_get_payment_status to take either a payment ID or a post object

**Comment by pippinsplugins** [comment]
Agreed. I've run into this numerous times.

**Comment by cklosowski** [comment]
@pippinsplugins seems to work great for me. Merging.
