### ISSUE TITLE
Add array_convert to Customer and other EDD classes

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#4042]
array_convert in the upcoming payments class makes it really easy to then just send the result into json encode. We should let all of our classes do this, and consider the introduction of an edd_array_convert function which could be used for class that use one of our class query functions that return multiple custom objects. For example, EDD()->customers->get_customers

**Comment by pippinsplugins** [comment]
:+1:

**Comment by cklosowski** [comment]
I like the idea of an `edd_array_convert()` where you pass it an object. Good idea.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by chriscct7** [comment]
I'd be nice if edd_array_convert supported an array of objects, like when you get back an array of customer objects from a get customers call

**Comment by cklosowski** [comment]
As per feedback, changing it to `edd_oject_to_array`

**Comment by pippinsplugins** [comment]
@cklosowski Something isn't working here.
![screen shot 2016-05-18 at 11 23 48 am](https://cloud.githubusercontent.com/assets/1034109/15366672/07e41ff0-1ceb-11e6-9f9f-6f4110d4ed37.png)

**Comment by cklosowski** [comment]
@pippinsplugins Payments have their own array convert...due to the nature of them. For `EDD_Payment` it needs to be done with it's own method.

Can you try customers and downloads?

**Comment by cklosowski** [comment]
The issue with payment is the massive use of `magic methods` because of the `save` methodology.

**Comment by cklosowski** [comment]
I'll update the code so that if it's a payment that's detected it uses it's own method.

**Comment by pippinsplugins** [comment]
@cklosowski ah right. Ok a customer works.

Let's be proactive here and detect if it's an `EDD_Payment` object. If it is, return through the helper method.

**Comment by cklosowski** [comment]
@pippinsplugins already on it, testing now and will push up once confirmed.

**Comment by cklosowski** [comment]
ok, updated to have any thing that is `EDD_Payment` or extends `EDD_Payment` to use it's own internal conversion method...and added unit tests for it.

**Comment by pippinsplugins** [comment]
Works perfectly. Let's merge once unit tests pass.
