### ISSUE TITLE
Amazon Payments - Address not showing if Ajax is disabled

### ISSUE THREAD

**Issue by osthafen** [easydigitaldownloads/easy-digital-downloads#4043]
Using the amazon payment and having edd_is_ajax_disabled set to true (so edd-ajax.js isn't loaded ) the site with the included script throws an error "**Uncaught TypeError: Cannot read property 'taxes_enabled' of undefined**" at position `if( '1' == edd_scripts.taxes_enabled ) {` [/includes/gateways/amazon-payments.php#L625](https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/4680af0dda261d5741aeb35272c76d1a563d1e84/includes/gateways/amazon-payments.php#L625)
The script interrupts and the following divs stay empty:
`<div id="edd-amazon-address-box"></div>
<div id="edd-amazon-wallet-box"></div>`

Solution: define the necessary variables after "var edd_scripts;" like:
`edd_scripts.ajaxurl = <?php edd_get_ajax_url(); ?>`

**Comment by pippinsplugins** [comment]
Thanks for the report! We'll try and get that resolved son.

**Comment by cklosowski** [comment]
Going to see if I can tackle this for the 2.6 beta.

**Comment by cklosowski** [comment]
@easydigitaldownloads/core-devs this is ready for some testing if someone could hit it up in the AM prior to beta going out.

**Comment by pippinsplugins** [comment]
Merged into `release/2.6`

**Comment by pippinsplugins** [comment]
Confirmed that this works fine.
