### ISSUE TITLE
Sale logs not deleted when payment changed from complete to pending

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#4052]
If a completed payment is changed back to `pending`, the sale log entries and sale counts / earnings for products are not decremented.

When changing a complete payment to pending, the following should happen:

1. Status changed to pending
2. Delete sale logs
3. Decrement sale count on products in payment
4. Decrease earnings on products in payment
5. Delete `_edd_completed_date` meta key/value.

**Comment by SDavisMedia** [comment]
@cklosowski Replicated on `2.3.9` and then tested in `master`. Verified that changing the payment record from complete to pending did the following:

1. deleted the sales log
2. decremented the product sales count in all locations
3. decreased the product earnings in all locations
4. removed the `_edd_completed_date` meta value from the payment record

All good. :+1:

**Comment by pippinsplugins** [comment]
:+1:
