### ISSUE TITLE
When switching reports, keep the previously-specified date range

### ISSUE THREAD

**Issue by zackkatz** [easydigitaldownloads/Easy-Digital-Downloads#4056]
1. Select License Renewals report
2. Set filter to "This Year"
3. Select License Upgrades report

**What happens:** Date range resets to "This Month"

**What I want to happen:** Retain the "This Year" date range previously specified

**Comment by pippinsplugins** [comment]
@zackkatz This is for Software Licensing so I'm closing this one and will re-open there.

**Comment by pippinsplugins** [comment]
https://github.com/easydigitaldownloads/EDD-Software-Licensing/issues/396

**Comment by zackkatz** [comment]
Thanks, didn't realize it was EDDSL.
