### ISSUE TITLE
Pagination with edd_get_users_purchases

### ISSUE THREAD

**Issue by kiarashi** [easydigitaldownloads/easy-digital-downloads#4059]
I copied the file inside templates/history_downloads.php and tried to change the number of downloads per page. 

$purchases = edd_get_users_purchases( get_current_user_id(), 20, true, 'any' );

Changing 20 to 5 (for example) doesn't seem to work. Is this a bug or am I doing it wrong?
If I'm doing it wrong, any other way to change the number of downloads per page?

**Comment by pippinsplugins** [comment]
That should work. What's the behavior you get? Does it display more than 20?

**Comment by kiarashi** [comment]
I wanted to display less than 20 but I went ahead and made a few test purchases, enough to pass the 20 and it turns out, it also display more than 20 on the page. The pagination doesn't show up.

**Comment by pippinsplugins** [comment]
Can  you test it with the default theme? It shows up for me.

**Comment by kiarashi** [comment]
Even with a standard wp theme, it still doesn't show up.

![img-pagination](https://cloud.githubusercontent.com/assets/7079137/11883441/44c722f0-a513-11e5-99ff-740efe01213d.png)
.

**Comment by cklosowski** [comment]
@kiarashi  This looks like you are using `$purchases` as the source of the count, but showing the `downloads`. A users `purchases` are not the same as the users `downloads` in all cases. The pagination would not always work considering that `1 purchase` could have `many` downloads on it, so it wouldn't paginate correctly.

**Comment by kiarashi** [comment]
Hi Cklosowski, 

It's not my code. `$purchases` comes from edd's core file:
.../plugins/easy-digital-downloads/templates/history_downloads.php

:)

**Comment by cklosowski** [comment]
@kiarashi correct. I just was meaning in that screenshot the line you highlighted, I'll get this fixed up.

**Comment by pippinsplugins** [comment]
I can't replicate this. It works fine for me.

**Comment by pippinsplugins** [comment]
I'm going to close as `worksforme`. We can re-open later if necessary.
