### ISSUE TITLE
Customize product preview with oEmbed in 4.4

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#4064]
WordPress 4.4 supports oEmbed for post objects. Let's expand it to include support for embedding products on other sites along with their prices and purchase buttons.

https://make.wordpress.org/core/2015/10/28/new-embeds-feature-in-wordpress-4-4/

**Comment by cklosowski** [comment]
👍 great idea.

**Comment by leewillis77** [comment]
Came here to raise this (+1)

**Comment by pippinsplugins** [comment]
:)

**Comment by BurlesonBrad** [comment]
@pippinsplugins @cklosowski Something in my cranium wants to use this as a way to satisfy:
Always Be Learning
Contribute
Challenge My Self
Now, being a very slow learning, time constrained, dad of three, thick headed, and perseverantly stubborn kinda guy, I ask for a bit of help from support & 'Phil' gave me a few generalized links.  But, would either of you two coding super rocket ninja geniuses have any other helpful 'breadcrumbs' that would help me learn, and contribute to EDD getting their products to work w/ oEmbed?

**Comment by pippinsplugins** [comment]
Happy to help though I haven't even look into the API to see how it works yet.

**Comment by pippinsplugins** [comment]
Initial pass at this:
![screen shot 2016-04-05 at 9 38 57 pm](https://cloud.githubusercontent.com/assets/1034109/14304247/d80bcebc-fb76-11e5-995d-f8f78d98d1eb.png)
I've opted to only add the price and not purchase buttons to keep it nice and simple for now.

**Comment by pippinsplugins** [comment]
@easydigitaldownloads/core-devs anyone else have any feedback on this?

**Comment by BurlesonBrad** [comment]
Sorry.  gimme a sec.....

**Comment by BurlesonBrad** [comment]
Ok.... Instead of Site Icon & Site Name in the lower left, I think it should *indeed* need to have some type of CTA ~*as in a button of some sort* 

Existing oEmbeds have the featured image & the excerpt ~ I think those would be critical.
Then afterwards, instead of the ```site_icon``` & ```blog_name```, shouldn't the priority of *"digital-real-estate"* be some type of **actionable** item? *(not just the site name?)*

....just my two cents.  And, **_yes,_** you might need a refund :laughing:

**Comment by spencerfinnell** [comment]
Was going to say the same -- a purchase link/button should be able to be added right? A direct link to the checkout on single priced items, and a more details button for variable pricing?

**Comment by cklosowski** [comment]
I'm with @spencerfinnell and @BurlesonBrad here. I think a CTA is crucial. I dig the idea of it being a link that puts the item directly in the cart for single priced items or a view details for variable.

**Comment by pippinsplugins** [comment]
Purchase buttons are definitely possible but tricky. Single price items are easy. Variable priced items not so much. For variable priced items, we'd need a separate link for each price.

**Comment by cklosowski** [comment]
@pippinsplugins yes, or link to the product itself where someone can make a decision.

**Comment by pippinsplugins** [comment]
The title is already a link.

**Comment by cklosowski** [comment]
Ok, we will have to work through something then.

**Comment by cklosowski** [comment]
The challenge we have with putting a purchase link is styling...since this is technically displaying on someone else's site, we've got to send styles along with it I think.

**Comment by pippinsplugins** [comment]
I don't think we should show purchase buttons at this time.

**Comment by cklosowski** [comment]
Agreed, I think we can itterate on this. There are some challenges we have with the nature of being an oEmbed. I say we leave it as it currently stands and test.

**Comment by SDavisMedia** [comment]
@pippinsplugins: You closed this just before I was commenting. Working very well for me... super slick. I'd love to see the comment output removed in the future, though. It's not a key feature of product page output, could very well be present because of trackbacks/pingbacks and not standard comments, and just isn't logical IMO.

**Comment by pippinsplugins** [comment]
@SDavisMedia Oh, good point! I'll log an issue for those.
