### ISSUE TITLE
Allow post__in orderby in [downloads]

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/Easy-Digital-Downloads#4068]
Since you can pass a list of IDs it would be nice to be able to preserve the order.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by spencerfinnell** [comment]
I have a PR ready for this. Should I wait until 2.6 is being actively worked on?

**Comment by pippinsplugins** [comment]
`release/2.6` would be great, thanks.
