### ISSUE TITLE
Issues w/ comments in WordPress 4.4

### ISSUE THREAD

**Issue by mattgrshaw** [easydigitaldownloads/easy-digital-downloads#4069]
Since upgrading to WP 4.4, I noticed that the comment count was way higher than what it should be.

I deactivated all plugins to see if that fixed the problem, and when I went back to the comments page I saw a ton of the following error in debug mode:

`Notice: map_meta_cap was called incorrectly. The post type edd_payment is not registered, so it may not be reliable to check the capability "edit_post" against a post of that type. Please see Debugging in WordPress for more information. (This message was added in version 4.4.0.) in /Users/.../wp-includes/functions.php on line 3787`

All of the stuff EDD stores in the wp_comments table was also visible on this page as if they were normal/approved comments. Reactivating EDD hides the comments and the error, but the comment count still reflects the amount of items stored in the DB by EDD.

**Comment by cklosowski** [comment]
@pippinsplugins I'm pretty sure this isn't something we can avoid. EDD uses comments to handle the payment notes, and we've got some code in our plugin to not count these towards comments.

With EDD deactivated, there's no way to negate them from counting.

I cannot replicate the counts being off in my environments, however.

**Comment by pippinsplugins** [comment]
@cklosowski Yep, this came up in a support thread too. Unfortunately nothing we can do about it with EDD deactivated except delete those comments.

@mgshaw are your comment counts cached?

**Comment by mindctrl** [comment]
I see comments counts being off in 4.4 while EDD is activated.

![image](https://cloud.githubusercontent.com/assets/1254870/11701368/216be5ba-9e9d-11e5-8bf7-c7adb59f0056.png)

![image](https://cloud.githubusercontent.com/assets/1254870/11701378/30faa6b0-9e9d-11e5-88d9-6be5a16306d6.png)

**Comment by mgshaw** [comment]
@pippinsplugins I don't think so, I just cleared out all the caches and can still reproduce.

**Comment by pippinsplugins** [comment]
OK so counts are wrong, but that pretty much has to be a WordPress core bug.

When EDD is deactivated, we cannot affect anything with the display or counts of comments, so it's a WP core bug with not properly counting non-default comment types.

**Comment by mgshaw** [comment]
Makes sense. I'll close this out then and will look into it further and create a ticket on trac if necessary.

**Comment by chriscct7** [comment]
Just an FYI this also occurs on the dashboard on the activity widget. Does anyone know if there's a Trac ticket for this?

**Comment by chriscct7** [comment]
Core ticket is https://core.trac.wordpress.org/ticket/36208

**Comment by chriscct7** [comment]
Reopening. Nothing to do on our end yet, but in case the solution core proposes needs us to do something we should have the ticket open as a reminder. Also makes it easier for people to find when searching for it

**Comment by pippinsplugins** [comment]
This is no longer an issue.
