### ISSUE TITLE
Prices not incrementing when doing add_download on payment with EDD_Payment

### ISSUE THREAD

**Issue by topher1kenobe** [easydigitaldownloads/Easy-Digital-Downloads#4075]
I have a Pending payment.  I added a download with add_download.  It added the download but did NOT change the payment total.

**Comment by cklosowski** [comment]
@topher1kenobe can you test this again against `release/2.5`? I remember we talked about this but cannot remember if it worked for you again.

**Comment by topher1kenobe** [comment]
This issue appears to be resolved after testing.
