### ISSUE TITLE
Removing download causes PHP Notice

### ISSUE THREAD

**Issue by topher1kenobe** [easydigitaldownloads/Easy-Digital-Downloads#4076]
I have a payment with 2 downloads.  I remove one, AJAX makes it disappear, and then I Update the payment.  I get this:

Notice: Undefined index: price_id in /home/topher1/edd.derosia.com/wp-content/plugins/easy-digital-downloads/includes/payments/class-edd-payment.php on line 734

Notice: Undefined index: price_id in /home/topher1/edd.derosia.com/wp-content/plugins/easy-digital-downloads/includes/payments/class-edd-payment.php on line 764

**Comment by cklosowski** [comment]
I've fixed this in `release/1.5` as it's related to #2667. Let's keep all discussions there.
