### ISSUE TITLE
Remove all transients with `edd_` on uninstall

### ISSUE THREAD

**Issue by slaFFik** [easydigitaldownloads/Easy-Digital-Downloads#4079]
I've deactivated EDD and than deleted it.
Transients Manager plugin shows me, that `edd_cache_excluded_uris` has a `Does not expire` expiration and still in DB.
IMO, it should be deleted as well.

And according to this search https://github.com/easydigitaldownloads/Easy-Digital-Downloads/search?utf8=%E2%9C%93&q=edd_cache_excluded_uris this transient is only set and no deletion logic at all.

**Comment by pippinsplugins** [comment]
We'll get it taken care of.

**Comment by cklosowski** [comment]
We'll take this opportunity to run the uninstaller and make sure no transients with the prefix of `edd_` remain after the uninstall functions are run.
