### ISSUE TITLE
Fatal error in earnings by category reports

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/Easy-Digital-Downloads#4081]
Just had this reported by a customer and confirmed on multiple local test sites. With no other plugins active, visiting Downloads - > Reports and selecting Earnings by Category returns this:
<img width="999" alt="screenshot 2015-12-13 14 00 22" src="https://cloud.githubusercontent.com/assets/4993131/11768673/144e4906-a1a2-11e5-9360-07b69efe1d7c.png">

**Comment by pippinsplugins** [comment]
Looks like something that broke after the update to WP 4.4

**Comment by cklosowski** [comment]
@brashrebel Can you test this again? I cannot replicate it, i'm running trunk WP Core.

**Comment by cklosowski** [comment]
Oh, I see, it's in EDD master. This is already fixed in `release/2.5`.

**Comment by cklosowski** [comment]
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/commit/07efd56a0ec8d38149e9d8163013a7b465ef3710#diff-29e28a1c545fe9b80f89116df4608f66
