### ISSUE TITLE
FES Emails

### ISSUE THREAD

**Issue by Ziccco** [easydigitaldownloads/Easy-Digital-Downloads#4082]
I have updated my FES to the lastest version 2.3.6. When I go into the settings for permissions and emails its not working to turn on/off. When I click OFF the buttom becomes gray, and when I press the save button it turns back to ON. 
![fes](https://cloud.githubusercontent.com/assets/16292220/11786302/19cded8e-a286-11e5-8990-b129b891dba5.jpg)

**Comment by mindctrl** [comment]
Hi @Ziccco, please open a support ticket here: http://easydigitaldownloads.com/support/

This repo is for Easy Digital Downloads core development.
