### ISSUE TITLE
Rewrite FAQs on WordPress.org

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#4083]
The FAQs tab on WordPress.org have not been changed in several years. It's time to bring them up to date!

https://wordpress.org/plugins/easy-digital-downloads/faq/

@easydigitaldownloads/core-devs Please every one drop in your thoughts and suggestions for items that should be covered.

**Comment by pippinsplugins** [comment]
Some I have:

- Where is documentation
- Payments are pending
- Which gateways are supported
- Are recurring payments supported
- Is an SSL certificate required
- How to setup an affiliate system
- How are products displayed

**Comment by cklosowski** [comment]
Great idea.

- What themes work with EDD

**Comment by pippinsplugins** [comment]
Good one.

**Comment by cklosowski** [comment]
I think this would be a good one for @topher1kenobe to head up, has a more 'docs' feel to it.

**Comment by sumobi** [comment]
How about:

> Will it work with my theme? (styling etc)

**Comment by SDavisMedia** [comment]
Importing from another store system.
