### ISSUE TITLE
Force deactivation of the old Recount Tool in 2.5

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/Easy-Digital-Downloads#4084]
Since we've added the recount tool to EDD Core in #3633, we should forcibly deactivate the old repo we have, to avoid confusion.

**Comment by chriscct7** [comment]
Is that actually allowed under wp.org guidelines? We might have to settle for just an admin notice

**Comment by pippinsplugins** [comment]
We can remove the action but can't deactivate the plugin.

**Comment by cklosowski** [comment]
Yep, was planning on removing it's hooks.

**Comment by cklosowski** [comment]
Ok, so we can't unhook the legacy recount tool, because we didn't assign the instantiated object to a variable that's accessible (oops). We'll just put up a notice to the users that have it active that it's now built into core and they should deactivate the old one.

Also, this converts all our echoing of HTML in our admin notices to use output buffering. A much cleaner editor experience, and less risk of any errors/notices getting in the way of the HTML output, to follow suit with much of our other HTML outputting via PHP.
