### ISSUE TITLE
[edd_receipt payment_key="true"] Issue

### ISSUE THREAD

**Issue by DevinWalker** [easydigitaldownloads/Easy-Digital-Downloads#4091]
By default, when you install EDD the Purchase Receipt page has: `[edd_receipt]` but if users customize it to display the payment key (it's set to false by default: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/shortcodes.php#L654) 

`[edd_receipt payment_key="true"]`

Then you get errors... see: https://github.com/WordImpress/Give/issues/443

The issue appears to be the order of conditions here: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/shortcodes.php#L660-L666

I've fixed this by moving the session elseif before the param

**Comment by pippinsplugins** [comment]
Ah, we should change the shortcode parameter.

**Comment by cklosowski** [comment]
Confirmed this fixes it.
