### ISSUE TITLE
Always show bulk actions when used for navigation

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/Easy-Digital-Downloads#4092]
In multiple reports and all logs in EDD, `WP_List_Table` is used and the `bulk_actions()` method is utilized as a convenient way to output the select field for navigating to other views in the right place. However, bulk actions only display if there are items to show in the table which makes sense when the bulk actions are actually actions but not when they are navigational as they are in EDD.

I'm making a pull request right now with a simple solution that will ensure these navigation items always show.

**Comment by pippinsplugins** [comment]
Thanks @brashrebel !
