### ISSUE TITLE
API HTTP Headers

### ISSUE THREAD

**Issue by sunnyratilal** [easydigitaldownloads/Easy-Digital-Downloads#4099]
Currently, when querying data via the EDD API, `HTTP 200 OK` is returned for every request.

If, for example, we have a user that doesn't have the required caps to access certain data such as `sales` or `earnings`, a `HTTP 200 OK`is still returned, this should actually be 'HTTP 401 Unauthorized'.

**Comment by pippinsplugins** [comment]
Whoops!

**Comment by mindctrl** [comment]
Shouldn't it be a 403 Forbidden?

**Comment by pippinsplugins** [comment]
Both could be argued to be correct I think. 401 would be if credentials were incorrect. 403 would be if credentials are correct but the user doesn't have the necessary permissions.

**Comment by cklosowski** [comment]
Correct:
`401` Means you didn't provide authentication where as `403` means the authentication provided was not credentialed to view the resource.

**Comment by cklosowski** [comment]
This is odd, b/c we're sending a status number to our `output` method:
`$this->output( 401 );`

And then in `output` we use `status_header( $status_code );`, which is a WP Core function that set's the header and description.

**Comment by cklosowski** [comment]
I'm seeing the correct responses. @sunnyratilal where are you getting the errors, is this during the iOS development process you noticed this?

![screen shot 2016-02-04 at 11 53 32 am](https://cloud.githubusercontent.com/assets/1390124/12825948/0223a60a-cb36-11e5-9357-42a77ca2fa10.png)

**Comment by cklosowski** [comment]
I will make it so invalid auth returns a 403 not a 401 though.
