### ISSUE TITLE
MailChimp extension broke, probably with last update

### ISSUE THREAD

**Issue by samglover** [easydigitaldownloads/Easy-Digital-Downloads#4100]

**Comment by mindctrl** [comment]
@samglover this is for Easy Digital Downloads plugin development. You'll want to open a support ticket here so we can help you fix it: https://easydigitaldownloads.com/support

**Comment by samglover** [comment]
Just FYI, I would have done that in the first place but I didn't see a link to the support page anywhere in the plugin.
