### ISSUE TITLE
Product page title showing <span itemprop="name">...</span> code

### ISSUE THREAD

**Issue by DustinWStout** [easydigitaldownloads/Easy-Digital-Downloads#4101]
On the product pages (single) it's showing `<span itemprop="name">[TITLE]</span>` rather than just the title as it should. I can't figure out why this is happening. 

Link to example: http://beta.dustn.co/downloads/flat-minimal-social-media-icons/

Theme: Altitude Pro Child Theme (Genesis 2.2.5)
WordPress Version: 4.4

<img width="764" alt="screen shot 2015-12-30 at 10 41 24 pm" src="https://cloud.githubusercontent.com/assets/2152604/12061916/09032a96-af47-11e5-9168-cfb63b56372b.png">

**Comment by pippinsplugins** [comment]
@DustinWStout This is caused by an error in your theme. See http://sumobi.com/how-to-fix-the-strange-html-markup-in-download-titles/

**Comment by DustinWStout** [comment]
Thanks @pippinsplugins. I looked at the article from @sumobi and don't know how I didn't find it before. However, I'm using a modified version of your single-download.php and have the following for the title:

`<h1 class="entry-title"><?php the_title_attribute(); ?></h1>`

That doesn't seem to have fixed it. It still outputs the same thing.

**Comment by pippinsplugins** [comment]
@DustinWStout Please go ahead and open a support ticket for us. GitHub is a development tool and not a location to get support. Thanks.
