### ISSUE TITLE
Admin Chosen JS unused variable.

### ISSUE THREAD

**Issue by danieliser** [easydigitaldownloads/Easy-Digital-Downloads#4103]
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/d02aefe0d5d9b82c70e2a44880d1bafd191897c9/assets/js/admin-scripts.js#L1134

I believe its supposed to store e.which for reuse a few lines below. So either need to remove that variable or replace the further calls to e.which with lastKey.

**Comment by pippinsplugins** [comment]
AH yes, it should use `lastkey`.
