### ISSUE TITLE
Replace $edd_options[ $key ] with edd_get_option()

### ISSUE THREAD

**Issue by grappler** [easydigitaldownloads/easy-digital-downloads#4104]
I hooked into `'edd_get_option_' . $key` to change the page id depending on the language used in Polylang.

Everything works fine in the front end but in the backend it does not work. The reason is that `global $edd_options;` is still being used in the callbacks.

To fix this we can replace `global $edd_options;` with `$edd_options = edd_get_option( $args['id'] );`and replace `$edd_options[ $args['id'] ]` with `$edd_options` in `/includes/admin/settings/register-settings.php`

Let me know what you think and I can create a PR.

**Comment by pippinsplugins** [comment]
@grappler Good catch! I'd love a PR :)

**Comment by cklosowski** [comment]
@grappler, can you resubmit the PR towards master? now that 2.5 is out this should be fine to merge in.

**Comment by grappler** [comment]
I have resubmitted the PR.

**Comment by cklosowski** [comment]
Merged in https://github.com/easydigitaldownloads/Easy-Digital-Downloads/commit/2ad8530a5f517c2ea922ab0db3fa69b2b1dda8b0, thanks @grappler

**Comment by grappler** [comment]
Can we reopen this as the commit was reverted? https://github.com/easydigitaldownloads/Easy-Digital-Downloads/commit/659dbf4b98641537cce692e8636c363d409f448c What information was there that the settings were not saving? I retested the code again and I am able to save the settings.

**Comment by pippinsplugins** [comment]
@grappler Re-opened.

I'm not sure if it was your commit or the manual merge (there was a nasty merge conflict) but it definitely caused settings to not save / display properly. It failed because of how the callback methods were changed. I can elaborate more when re-addressed.

**Comment by grappler** [comment]
How can I help get this merged in again?

**Comment by pippinsplugins** [comment]
We'll need to resubmitted against the `release/2.6` branch.

**Comment by grappler** [comment]
Ok, I have created a new PR

**Comment by pippinsplugins** [comment]
Thanks!

**Comment by cklosowski** [comment]
Ok, I've taken a look at this and I know why it's not working...these sanitize callbacks are for when saving settings. They are callbacks for when we iterate over each setting saved on a page, we break it out, and then sanitize each field, and then build the `$edd_options` array back up. By using the function to get the EDD options, we're actually negating the save, since it's never looking at the values that were passed in the `$POST` request.

**Comment by grappler** [comment]
@chriscct7 I had another look at it and realized I forgot to change a few variables in a few callbacks. That is why certain settings were not working. I have updated the PR and all of the settings should work now.

**Comment by cklosowski** [comment]
@grappler Probably meant to ping me :P I'll pull it down and take a look at it. Thanks.

**Comment by cklosowski** [comment]
@grappler there are still settings I cannot save. For example, I cannot save any of the checkboxes in `Settings -> Misc -> Checkout Settings`. Can you try and merge the latest `release/2.6` into your branch and test it?

**Comment by grappler** [comment]
@cklosowski I merged the latest `release/2.6` and updated the PR. The checkboxes in `Settings -> Misc -> Checkout Settings`work fine for me. It is strange as all of the checkboxes use the same callback. Could there be a plugin running that is overriding the settings?

**Comment by SDavisMedia** [comment]
Assuming the final place for testing on this is `release/2.6`, I am not having issues saving any settings.

**Comment by pippinsplugins** [comment]
@SDavisMedia Nope, it's in a PR still https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4424

**Comment by mintplugins** [comment]
Tested and I am not able to save checkboxes on the "Settings" > "Misc" > "Checkout Settings" page.

**Comment by SDavisMedia** [comment]
Testing on `issue/4104` not only did I _lose_ some settings that were previously set, I cannot save other settings. For example, I lost the following just switching branches:

* Base State / Province
* All checkboxes

I also cannot save checkbox settings as well as Base State / Province (though I am able to change other select menus... the ones that _did not_ lose their values when I switched to `issue/4104`). 

Switching back to another branch brought all the settings back.

**Comment by mintplugins** [comment]
Just pulled in the latest and it is now working well for me. Settings are saving everywhere for EDD settings now.

**Comment by SDavisMedia** [comment]
The update fixes it for me as well.

**Comment by michaelbeil** [comment]
All settings save fine here on `issue/4104`.

**Comment by cklosowski** [comment]
Ok, @grappler for easier testing, i've been pulling all your updates to the PR into an issue branch `issue/4104` Things seem to be working fine. I'm going to close your current PR and create one from the issue branch.

Your commit history will stay in tact, so you'll still get the 'kudos" on the fixes :) Thanks for your help getting this updated. I'll try and have it merged into `release/2.6` shortly.

**Comment by pippinsplugins** [comment]
One small comment on the PR, otherwise everything seems to work fine here.

**Comment by grappler** [comment]
Thank you! Look forward to seeing this 2.6 :grinning:
