### ISSUE TITLE
Save used tax rate to payment meta

### ISSUE THREAD

**Issue by flowdee** [easydigitaldownloads/easy-digital-downloads#4105]
Saving the tax rate - which was used on creating a payment - to the payment meta as well as currently the tax amount would be very helpful.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by flowdee** [comment]
Do you want to give me a tip which place would be the best to save the tax rate to the payment meta? Then I'm going to take a look and create a pull request. 

If you think it's a bit complicated then I'm going to wait :smile:

**Comment by pippinsplugins** [comment]
It should get stored in it's own row.

**Comment by cklosowski** [comment]
:+1: for it's own row. I'd like to get away from having nested serialized array data. This will make it much easier to isolate the data later.

**Comment by pippinsplugins** [comment]
I've gotten started on this in the `issue/4105` branch but have run into a problem with reliably saving it across gateways. Since not all gateways create payments in the same way, we can't reliably set it. This may have to come after we introduce the new `EDD_Gateway` class.

**Comment by cklosowski** [comment]
We should be able to do this now with `EDD_Payment`.

**Comment by sunnyratilal** [comment]
Tracking PR opened at #5403

**Comment by sunnyratilal** [comment]
@pippinsplugins @cklosowski Ready for testing

**Comment by pippinsplugins** [comment]
@sunnyratilal This looks like it should work fine, but I'd like to keep this open in regards to changes coming with `EDD_Cart` and `EDD_Gateway`.

Ideally the tax rate doesn't depend on `$_POST` data inside of `edd_insert_payment()` since that won't be reliable in all scenarios.

**Comment by cklosowski** [comment]
Ok I've updated this to not rely on `$_POST`. It also adds in sending the postal code which has been requested before in #4877 to allow developers who want to do finer grain tax calculations than just country/state.

**Comment by cklosowski** [comment]
Also added in a little bit of markup on the view order details that displays the tax rate if there is one:
![screen shot 2017-01-24 at 11 16 43 am](https://cloud.githubusercontent.com/assets/1390124/22255875/de2b2346-e226-11e6-9a38-9d6b91514799.png)

**Comment by cklosowski** [comment]
@sunnyratilal @pippinsplugins ready for  quick test and review of the code.

**Comment by pippinsplugins** [comment]
I don't love the rate UI.

How about adding it in parentheses after `Tax`, so `Tax (6%):`?

**Comment by spencerfinnell** [comment]
Might not even need parentheses.

**Comment by cklosowski** [comment]
It looks super odd without parenthesis...and naming it `tax` gives us two references to `tax`

**Comment by cklosowski** [comment]
So it'd be:
`Tax: <input field> Tax (6%)`

**Comment by spencerfinnell** [comment]
`Tax: <input field> 6%` looks funky?

**Comment by cklosowski** [comment]
correct.

**Comment by cklosowski** [comment]
This is the requested above...not in love with it...even less:
![screen shot 2017-01-24 at 1 15 45 pm](https://cloud.githubusercontent.com/assets/1390124/22260445/4360cec2-e237-11e6-9bc5-d188807dd62f.png)

**Comment by cklosowski** [comment]
@spencerfinnell the reason it looks odd is because it's so disjointed from the row...seeing a random `6%` hanging out after the input looks like it's disconnected from whatever is being reference.

**Comment by cklosowski** [comment]
Here is after:
![screen shot 2017-01-24 at 1 17 53 pm](https://cloud.githubusercontent.com/assets/1390124/22260533/89eb05d8-e237-11e6-9db7-240ce9a132e9.png)

**Comment by spencerfinnell** [comment]
If the percentage is now being stored as well should that be a separate input field then? If you change the actual dollar amount but not the percentage that would be confusing. 

I think either both fields need to be editable or neither.

**Comment by pippinsplugins** [comment]
>>>I think either both fields need to be editable or neither.

I agree.

**Comment by cklosowski** [comment]
I disagree...the field will not be editable yet. It should only be allowed to be changed by the fields for address.

**Comment by cklosowski** [comment]
I'd even love to get rid of tax and total being editable since in #3802 will allow indifivul items to be updated for all of this information.

**Comment by spencerfinnell** [comment]
I agree it should be a historic recording of the original purchase and not editable.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by cklosowski** [comment]
I think showing it for now is ideal and once we are comfortable with the above mentioned issue we can take `View Order Details` a step further and allow fully automated `Tax`, `Total` calculation for both the overall payment as well as the individual line items.

**Comment by cklosowski** [comment]
@SDavisMedia @pippinsplugins @spencerfinnell Ok, so if we settle on one...which of the following:

Camera 1:
![screen shot 2017-01-24 at 1 15 45 pm](https://cloud.githubusercontent.com/assets/1390124/22260847/b4223492-e238-11e6-999d-f6384bd4d0ed.png)

Camera 2:
![screen shot 2017-01-24 at 1 17 53 pm](https://cloud.githubusercontent.com/assets/1390124/22260852/b994895c-e238-11e6-9474-5a2e52c884e1.png)

**Comment by pippinsplugins** [comment]
🎉

**Comment by sunnyratilal** [comment]
Second one has my vote

**Comment by cklosowski** [comment]
🎉  It is! Thanks!

**Comment by cklosowski** [comment]
UI updated and ready for some final testing.

**Comment by pippinsplugins** [comment]
Works great. Merged and closing.
