### ISSUE TITLE
Shop Worker user role still access to Payment History

### ISSUE THREAD

**Issue by KienTrong** [easydigitaldownloads/Easy-Digital-Downloads#4111]
Let say our website has user X with Shop Worker user role.

On your document page that user can only access to Downloads and Add New : https://easydigitaldownloads.com/wp-content/uploads/2013/02/Shop-Worker-620x157.png

On our website that user can access to Payment History too : http://cl.ly/093U22202N3M

Thanks.

**Comment by pippinsplugins** [comment]
@KienTrong That's a case of the documentation being wrong. Shop workers are expected to be able to access payment history. I'll update the documentation.
