### ISSUE TITLE
Forms within paragraphs

### ISSUE THREAD

**Issue by corvannoorloos** [easydigitaldownloads/Easy-Digital-Downloads#4112]
While I believe it's technically allowed to do so, browsers have some difficulties rendering them.

![4-1-2016 7-55-31](https://cloud.githubusercontent.com/assets/1499293/12084828/bd24fb5c-b2b8-11e5-8c7b-68aa3adfb2f1.png)

```
<p class="(\w+)">\s+<form
<p(*.?)>\s+<form
```

As the ones I could find aren't used, I think it would be safe to simply remove them.

Note 2.5 also includes a new occurrence. (of course happy to add a pr, but wasn't sure whether to wait until 2.5 has been merged)

**Comment by pippinsplugins** [comment]
Let's get this fixed in 2.5.5

**Comment by cklosowski** [comment]
Looks good to me, tested out the forms, nothing seems to break on our end. None of the `p` tags had classes so we weren't targeting them.

**Comment by cklosowski** [comment]
Merging and closing out.

**Comment by corvannoorloos** [comment]
Thanks!
