### ISSUE TITLE
"No checkout page has been configured" can't be properly dismissed

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/Easy-Digital-Downloads#4115]
Customer reported that the notice can't be dismissed when a checkout page hasn't been configured. Looks like the conditional [here](https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/2.4.10/includes/admin/class-edd-notices.php#L44) is wrong.

**Comment by pippinsplugins** [comment]
Let's get this fixed in 2.5.5

**Comment by pippinsplugins** [comment]
Moving to 2.5.8
