### ISSUE TITLE
Item tax is lost when a download is added to an existing purchase

### ISSUE THREAD

**Issue by bseddon** [easydigitaldownloads/easy-digital-downloads#4120]
In the back-end, on the view-order page, an administrator is able to add a download to an existing purchase and set a price.  However, when this action is taken, the item level tax is set to zero for all items in the cart.

This is a problem for me because it's necessary to create the EU VAT MOSS report based on item level tax information.  The tax rate that applies to different items in the cart may not be the same and need to be reported separately in the MOSS report.  This makes the tax amount recorded at the level of the purchase an inappropriate value to use.

Since the tax is removed from all items of a purchase when a new item is added, this action invalidates the tax reported for all items in the purchase.

To reproduce this, begin by reviewing the tax information available on an existing record.  For example:

$meta  = edd_get_payment_meta( $payment_id );
print_r( $meta );

Next, add a download to an existing purchase (the price doesn't matter) then check the tax information available when the new download has been added.  What I see is that before the download is added, items in the cart_details array have a tax value assigned.  After, the tax value is zero.

**Comment by pippinsplugins** [comment]
@bseddon Are you seeing this on `master` or `release/2.5`?

**Comment by bseddon** [comment]
I see it in 2.4.10.  A user of a VAT-MOSS plugin reported a problem with a report produced using the plugin that on examination was caused by the loss of the tax information.

Are you suggesting it may be addressed in 2.5?  I can try it if you think it may be.

**Comment by cklosowski** [comment]
@bseddon please see if it does. We updated the process of adding an item to a payment to use the new `EDD_Payment` class, which _might_ resolve this, but if it doesn't, I'd like to know earlier rather than later.

**Comment by bseddon** [comment]
I have downloaded 2.5rc1 and repeated adding a download to an existing purchase.  It seems that the tax value of existing items is no longer removed which is good news.  The observation I have is that tax is not calculated for the newly added item though this is not a new problem.

**Comment by cklosowski** [comment]
@bseddon Correct, we've never calculated tax on adding a download, it needs to be added into the arguments sent for the item. We played with this idea for 2.5 `EDD_Payment`, however since most interactions with adding items to a cart/payment were already calculating taxes we felt it was best to not interrupt that flow and change it.

**Comment by bseddon** [comment]
I don't follow your concern.  The item is being added on the view order page so surely EDD controls every aspect of the process to add an item include the function called to compute the tax and any parameters that function requires.  Is it not the case that this value can be computed in the same way it is computed when an item is added to the cart?  Granted the challenge will be to base the tax rate on the country recorded in the user-info array rather than the billing country as happens in the checkout process.

If this tax cannot be added to a line, it will be great that either:

  the ability to add a download can be disabled using a setting; or 
  a warning is displayed so the user is aware no tax has been applied to the line; or
  a field is added to allow an administrator to add an amount of tax that has been computed manually.

This is important for VAT MOSS reporting if it is to be correct because the rules require that we are able to identify the tax applied to each line item if the tax authority of a member state requests an audit.

**Comment by bseddon** [comment]
Do you know if it is possible to intercept the addition of a download using an action?  EDD is pretty rich with extension points in the backend maybe this is covered.  If so, I will be in a position to create an action or filter to compute the tax.

**Comment by mindctrl** [comment]
We've had another request to control the tax on line items when adding new items to an existing payment.

**Comment by pippinsplugins** [comment]
I believe this is resolved fully now with 2.7 so closing as fixed.
