### ISSUE TITLE
Front end submission php fatal error

### ISSUE THREAD

**Issue by Alexlim91** [easydigitaldownloads/Easy-Digital-Downloads#4121]
Hi,

I facing one problem with Front end submission after update to new version.

When i go to upload an items at the front page after fill all information then it show this error message "php fatal error" (Please check picture "32"below)
![32](https://cloud.githubusercontent.com/assets/14208881/12142050/f5edd262-b4af-11e5-90b2-f71673caa7d1.png)

Besides that, I also facing one problem when i go to update particular items on admin site. Here is the way:
Go to my admin site > EDD > All items> choose any items > then direct update button then it show "server error" I got contact my hosting provider they said there is the problem of edd plugin. (Please check picture below "blob" and "screenshot 2016" )
Blog:
![blob](https://cloud.githubusercontent.com/assets/14208881/12142025/c8d37b74-b4af-11e5-8cc7-f61109a3cfb3.jpg)
screenshot 2016:
![screenshot 2016-01-06 10 03 23](https://cloud.githubusercontent.com/assets/14208881/12142046/eae97f38-b4af-11e5-9047-d90470f69bdd.png)

Thank You

**Comment by chriscct7** [comment]
Hi @Alexlim90, please open a support ticket here and we'll dig into it for you: http://easydigitaldownloads.com/support/

This repo is for Easy Digital Downloads core development.

**Comment by Alexlim91** [comment]
Why closed it?

**Comment by Alexlim91** [comment]
I got submit. No people reply. I had waiting long time already

**Comment by pippinsplugins** [comment]
@Alexlim91 We'll be with you as soon as we can. Please be patient as we have many requests to work you. You are not being ignored.
