### ISSUE TITLE
explode() expects parameter 2 to be string, null given - error

### ISSUE THREAD

**Issue by Zwilla** [easydigitaldownloads/Easy-Digital-Downloads#4126]
explode() expects parameter 2 to be string, null given in class-edd-customer.php :501

array_filter() expects parameter 1 to be an array or collection in class-edd-customer.php :501

501: $notes_array = array_reverse( array_filter( explode( "\n\n", $all_notes ) ) );

**Comment by pippinsplugins** [comment]
@Zwilla Is that showing at the top of a customer details screen? Did that just happen after updating to EDD 2.5?

**Comment by mindctrl** [comment]
`explode()` is on 501 in version 2.4.10. Need more info.

**Comment by pippinsplugins** [comment]
#4127 should fix it. This does not appear to be anything new in 2.5 though.

**Comment by Zwilla** [comment]
Shows version 2.4.10 on plugin-page
I saw the error on hhvm-error.log
