### ISSUE TITLE
Remove "Max Uses" column from Discount Codes list

### ISSUE THREAD

**Issue by mgibbs189** [easydigitaldownloads/Easy-Digital-Downloads#4128]
When `Max Uses` is set, the `Uses` column adjusts to show (USES/MAX_USES).

This makes having a separate `Max Uses` column redundant, taking up valuable space. Thoughts?

<img src="http://i.imgur.com/u2i8VVt.png" width="319" height="261" />

**Comment by pippinsplugins** [comment]
I agree 100%.

**Comment by pippinsplugins** [comment]
Thanks @mgibbs189 !
