### ISSUE TITLE
Deactivate license button now missing in 2.5

### ISSUE THREAD

**Issue by bseddon** [easydigitaldownloads/Easy-Digital-Downloads#4133]
I've just been updating my settings code to take advantage of the new sections (simple to do which is great).

However, I noticed that I'm now not able to deactivate any licenses.  The reason is a backwards incompatible change from 2.4.10 -> 2.5.  The test in 'edd_license_key_callback' (register-settings.php) now expects the result of the 'is_valid_license_option' option to be an object.  Until now, a simple meta_value of 'valid' has been sufficient but the value returned from the option *must* be an object.

It is probably a good idea to allow the license validation record to have more detail but I think it's going to be a problem for those of us who already have a record in the options table which is not an object because now we are unable to deactivate our licences to, for example, move them to another domain.

**Comment by pippinsplugins** [comment]
@bseddon I believe ^ will fix it.
