### ISSUE TITLE
easy digital downloads update bug

### ISSUE THREAD

**Issue by jusboyka** [easydigitaldownloads/Easy-Digital-Downloads#4140]
There is a bug with the display of the beat store payment history and customers the menu shows up distorted
![edd bug](https://cloud.githubusercontent.com/assets/16600271/12202334/3cd094c2-b621-11e5-9f4c-80f5460c19e2.png)
![edd bug 1](https://cloud.githubusercontent.com/assets/16600271/12202335/3cd0985a-b621-11e5-8d9b-d68111b6a4a3.png)

**Comment by pippinsplugins** [comment]
@jusboyka if you increase the size of your browser window, does the problem go away?

**Comment by jusboyka** [comment]
the screenshot is a full screenshot. when i shrink the size of the window it goes back to normal but increasing does not work

**Comment by pippinsplugins** [comment]
@jusboyka does the problem happen on 2.4.10 as well?

**Comment by jusboyka** [comment]
I think it was ok on that version I'm not 100% sure but I updated to 5 & then 5.1

**Comment by pippinsplugins** [comment]
Could you please test? I'm not able to replicate this issue.

**Comment by jusboyka** [comment]
how do I go back to previous versions?

**Comment by pippinsplugins** [comment]
@jusboyka They can be downloaded from here: https://wordpress.org/plugins/easy-digital-downloads/developers/

**Comment by jusboyka** [comment]
will affect the products I have uploaded to the beat store

**Comment by jusboyka** [comment]
i've tried 2.51, 2.4.9, 2.4.8,2.4.6,2.4,2.39 still the same issue

**Comment by mindctrl** [comment]
@jusboyka this sounds like a browser cache issue or a conflict with another plugin or theme. Does it look right if you clear your cache and temporarily deactivate all other plugins and switch to the default Twenty Sixteen theme? Feel free to open a support ticket [here](http://easydigitaldownloads.com/support/).

**Comment by jusboyka** [comment]
I can try that but i never had any issue before the update and I have viewed it in more than 1 browser and the issue is the same

**Comment by SDavisMedia** [comment]
@jusboyka I agree with @mindctrl. This is probably a conflict with another plugin or theme. Considering it's happening across multiple versions and browsers but only for you, it's most likely a conflict specific to your site. Regardless of what it is, we need to troubleshoot in the correct support channel. 

If you haven't done so already, please go ahead and open a support ticket and we'll go from there: https://easydigitaldownloads.com/support/

**Comment by jusboyka** [comment]
ok thanks for all the help
