### ISSUE TITLE
Buy Now links going to empty checkout

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#4141]
We've seen several reports of Buy Now links sending customers to an empty checkout screen instead of PayPal since updating to 2.5.

**Comment by pippinsplugins** [comment]
One ticket: https://secure.helpscout.net/conversation/159043844/24896/?folderId=180499

**Comment by pippinsplugins** [comment]
When this happens, the customer is sent to the checkout screen with `?payment-mode` appended to the URL.

**Comment by pippinsplugins** [comment]
So far I cannot replicate this behavior.

**Comment by pippinsplugins** [comment]
Another ticket: https://secure.helpscout.net/conversation/158886693/24857/?folderId=180504

**Comment by cklosowski** [comment]
I cannot replicate this either.

**Comment by pippinsplugins** [comment]
Replicated it! It only happens when logged out.

**Comment by pippinsplugins** [comment]
https://secure.helpscout.net/conversation/159261027/24962/?folderId=180499

**Comment by cklosowski** [comment]
The issue was that the `EDD_Payment` class was returning a failure on an empty post_title for the payment, this now allows it to be empty.
