### ISSUE TITLE
Format variable pricing placeholder amount

### ISSUE THREAD

**Issue by corvannoorloos** [easydigitaldownloads/Easy-Digital-Downloads#4145]
I realize there's `edd_format_amount`, but I'm probably overlooking when the placeholder amount is being used.

Can the placeholder amount be formatted/translated?

![8-1-2016 19-27-20](https://cloud.githubusercontent.com/assets/1499293/12206114/669df9ca-b63f-11e5-977e-f3fc5184dfa3.png)

**Comment by pippinsplugins** [comment]
How would you like to change the format of it?

**Comment by corvannoorloos** [comment]
I wanted to change the decimal separator of the placeholder

**Comment by pippinsplugins** [comment]
Ok that sounds like a bug in our place holder. We can get that fixed in a future version.

**Comment by corvannoorloos** [comment]
Thanks!
