### ISSUE TITLE
edd_is_payment_complete returning false

### ISSUE THREAD

**Issue by stephywells** [easydigitaldownloads/Easy-Digital-Downloads#4150]
PDF invoices aren't downloading on my site because edd_is_payment_complete is always returning false after the download link is clicked. Changing === to == solved the problem for me in this line:
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/payments/functions.php#L757

I'm not seeing anywhere that is sanitizing the payment id or forcing it to be an integer before sending through edd_is_payment_complete. It looks like this should be done inside EDD to make sure it's always correct.

**Comment by pippinsplugins** [comment]
@stephenharris Could you var dump the `$payment_id` and `$payment->ID` and post the results?

**Comment by stephywells** [comment]
I'm getting string(6) "194572" int(194572)

**Comment by pippinsplugins** [comment]
That would do it! We'll fix in 2.5.3.

**Comment by stephywells** [comment]
Thanks!

**Comment by pippinsplugins** [comment]
^ that should take care of it.

**Comment by stephywells** [comment]
Looks great! Thanks again!
