### ISSUE TITLE
Download links missing from email receipt for some users

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#4155]
We've seen several reports of file download links missing from the emailed purchase receipt.

https://wordpress.org/support/topic/problem-for-new-update
https://secure.helpscout.net/conversation/159245209/24947/?folderId=180499

**Comment by pippinsplugins** [comment]
Links work properly for me with Mandrill.

**Comment by pippinsplugins** [comment]
They work fine for me with Amazon S3.

**Comment by pippinsplugins** [comment]
They work fine for me with Dropbox File Store.

**Comment by pippinsplugins** [comment]
I've also tested with file downloads restricted to a single price option.

**Comment by mindctrl** [comment]
Another one https://secure.helpscout.net/conversation/159381677/24993/?folderId=180499

**Comment by pippinsplugins** [comment]
And another: https://wordpress.org/support/topic/253-version?replies=1#post-7867977

**Comment by pippinsplugins** [comment]
^ those two are from the same user.

**Comment by pippinsplugins** [comment]
I saw a mention of one user resolving this by disabling symlinks.

**Comment by mindctrl** [comment]
Symlinks already disabled on the one above.

**Comment by pippinsplugins** [comment]
Another potential report: https://wordpress.org/support/topic/problem-in-v253

**Comment by pippinsplugins** [comment]
Could be related to #4160

**Comment by mindctrl** [comment]
[Customer](https://secure.helpscout.net/conversation/159245209/24947/?folderId=386431) said email links were not missing from the copy the admin gets.

**Comment by pippinsplugins** [comment]
Another potential report: https://secure.helpscout.net/conversation/158834689/24843/?folderId=180505

**Comment by pippinsplugins** [comment]
I've just about tracked this down. It only happens when using Buy Now buttons.

**Comment by pippinsplugins** [comment]
Here's something REALLY weird.

After the payment goes from `Pending` to `Complete`, it's getting reverted back to `Pending`.

**Comment by pippinsplugins** [comment]
Oh I see why; the buy now buttons are causing some payments to be given a `future` status` since the creation date is in the future.

**Comment by pippinsplugins** [comment]
That was it! Setting the timezone properly in `edd_build_straight_to_gateway_data()` fixes it.

**Comment by pippinsplugins** [comment]
This is till happening in 2.5.4 for some usrs.

**Comment by pippinsplugins** [comment]
Unfortunately this is still happening to some users. Likely related to #4178

**Comment by pippinsplugins** [comment]
Resolved through #4178
