### ISSUE TITLE
Goal link is showing 0 and marking campaigns as successful 

### ISSUE THREAD

**Issue by bbnomics** [easydigitaldownloads/Easy-Digital-Downloads#4159]
I'm having an issue with the goal amounts remaining on the campaign immediately after the two latest updates. no matter the goal amount, it keep reverting back to 0 and marking the campaign as successful even though it hasn't ended.

**Comment by pippinsplugins** [comment]
@bbnomics It sounds like you're referring to the Crowd Funding or Donations plugin. This page is for EDD core development only. Support for the plugin and all extensions is handled through our website. Please open a ticket there: https://easydigitaldownloads.com/support
