### ISSUE TITLE
New feature - Filter for payment's default currency

### ISSUE THREAD

**Issue by daigo75** [easydigitaldownloads/Easy-Digital-Downloads#4164]
Ref. https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/4162#issuecomment-170660140

Why
--
The filter allows plugins that implement multi-currency features feature to take action when a payment doesn't have a currency associated to it (an error condition that must be handled). A call to the filter implies that the payment has no currency associated to it. The shop owner can, therefore, be informed about the issue. The multi-currency solution can provide an interface to allow the shop owner to rectify the order, by manually choosing the currency.

Pull request coming shortly.

**Comment by pippinsplugins** [comment]
Seems like a good idea to me.
