### ISSUE TITLE
Buy Now buttons creating pending payments instead of private payments

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#4171]
Buy Now buttons are supposed to set payment records as `private` but since 2.5 they are getting set as `pending`.

**Comment by cklosowski** [comment]
We tested this with the buy now bug issue we saw on Saturday Your fix with mine combined was giving payments set to private. Have they tested and replicated on 2.5.3?

**Comment by cklosowski** [comment]
```
21532	1	2016-01-12 05:14:40	2016-01-12 12:14:40		Admin User		private	closed	closed		admin-user-16			2016-01-11 22:14:40	2016-01-12 05:14:40		0	https://local.dev/edd/?post_type=edd_payment&#038;p=21532	0	edd_payment		1
```

![screen shot 2016-01-11 at 10 12 18 pm](https://cloud.githubusercontent.com/assets/1390124/12255434/e501e6a0-b8b0-11e5-9697-c3f56d4f8b24.png)


Getting set to private for me on `master`

**Comment by pippinsplugins** [comment]
@cklosowski I was testing prior to my changes I think.

**Comment by pippinsplugins** [comment]
Looks like this is invalid and works fine.
