### ISSUE TITLE
edd_get_payment_currency_code not returns currency code

### ISSUE THREAD

**Issue by upsellpl** [easydigitaldownloads/Easy-Digital-Downloads#4176]
As in subject - function edd_get_payment_currency_code for EDD 2.5.3 not returns currency code (tested for PLN).

**Comment by pippinsplugins** [comment]
This has been fixed in https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/4162

**Comment by upsellpl** [comment]
I've just updated EDD to 2.5.5 and still got this issue...

**Comment by pippinsplugins** [comment]
Is the payment marked as complete?

**Comment by upsellpl** [comment]
It's called inside edd_complete_purchase action. I think that payment
status should not be important in this function.

2016-01-13 16:58 GMT+01:00 Pippin Williamson <notifications@github.com>:

**Comment by pippinsplugins** [comment]
Are you seeing this happen with some custom code you're running or an extension?

**Comment by upsellpl** [comment]
It happen in WP Tao (https://wordpress.org/plugins/wp-tao/) which is integrated with EDD. You can find the integration code inside includes/events/payment.php file.

**Comment by pippinsplugins** [comment]
That's failing because `$payment_id` was not passed to `edd_get_payment_currency_code()`. See this line: https://plugins.trac.wordpress.org/browser/wp-tao/trunk/includes/events/payment.php#L83

**Comment by upsellpl** [comment]
Thx Pippin! So before EDD 2.5 that function returns default currency code and I assume it works correctly (it wasn't). I will fix that in WP Tao.
