### ISSUE TITLE
profile editor shortcode not updating customer record first and last name

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/Easy-Digital-Downloads#4177]
Ticket: https://secure.helpscout.net/conversation/159506290/25034/

Using the `[edd_profile_editor]` shortcode, a user can edit his or her profile including first and last name. Editing this form updates the WordPress user profile as well as the customer record. However, even though the fields in the shortcode will save and the WP user profile will reflect the changes, the customer record will NOT show changes to the first and let name.

WP 4.4.1 - EDD 2.5.3

**Comment by pippinsplugins** [comment]
Let's get that fixed.

**Comment by cklosowski** [comment]
@SDavisMedia that should do it.
