### ISSUE TITLE
Timezone sometimes set improperly when payments are created 

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#4178]
In 2.5, we changed when the default timezone is set. It appears that we now have some cases where the timezone is set after the date is generated, resulting in some payments getting dates in the future.

**Comment by cklosowski** [comment]
Going to add the time zone check at the top of `edd_insert_payment` as well, so that we can assure it's been run.

**Comment by pippinsplugins** [comment]
Unfortunately this appears to still be happening for some sites. Re-opening for further investigation.

**Comment by pippinsplugins** [comment]
https://wordpress.org/support/topic/problem-in-v253/page/1 (see last few comments)

**Comment by pippinsplugins** [comment]
It still fails when using `WP-Parsidate` and the timezone is set to `Tehran`.

**Comment by pippinsplugins** [comment]
When we looked at it earlier, we were seeing differences in the date generated when creating purchases. Now, however, they are the same regardless of whether `WP-Parsidate` is active or not:

```
string '2016-01-13 12:37:01' (length=19)
string '2016-01-13 12:37:41' (length=19)
```

**Comment by pippinsplugins** [comment]
This problem happens for me even if `WP-Parsidate` is not active.

**Comment by pippinsplugins** [comment]
#4182 Resolves the problem *when not using WP-Parsidate*. The problem still occurs, however, when  `WP-Parsidate` is activated.

If we can confirm that the changes here resolve the problem for all instances except when using the `WP-Parsidate` plugin, I think we can put in a plugin compatibility layer that is something like this:

```php
function edd_parsidate_set_timezone() {

	if( ! class_exists( 'WP_Parsidate' ) ) {
		return;
	}

	date_default_timezone_set( edd_get_timezone_id() );

}
add_action( 'edd_pre_process_purchase', 'edd_parsidate_set_timezone' );
```

I tested and this `edd_parsidate_set_timezone()` function does not appear to work, but something similar should work.

**Comment by pippinsplugins** [comment]
@easydigitaldownloads/core-devs I would like to test #4182 with *every single* timezone. If we can confirm it works as expected with all timezones, we can then work on just fixing the conflict with the `WP-Parsidate` plugin.

**Comment by sumobi** [comment]
"Manual offsets" group all working

**Comment by sumobi** [comment]
"UTC" group working (there was 1)

**Comment by SDavisMedia** [comment]
Africa all working.

**Comment by sumobi** [comment]
Pacific all working

**Comment by sumobi** [comment]
indian all working

**Comment by SDavisMedia** [comment]
America all working.

**Comment by SDavisMedia** [comment]
Antarctica all working.

**Comment by SDavisMedia** [comment]
Arctic working.

**Comment by sumobi** [comment]
Europe good

**Comment by sumobi** [comment]
Australia is great

**Comment by sumobi** [comment]
Atlantic is ace

**Comment by SDavisMedia** [comment]
Asia is golden.

That's all timezones confirmed working properly on `issue/4178` with wp-parsidate **deactivated**. :+1:

**Comment by sumobi** [comment]
Wait, we were supposed to test 4178? :scream: 


jk

**Comment by samikeijonen** [comment]
Finland, we have a problem :)

I didn't read all the topics because kind of hurry at the moment. But here is the issue.

- New purchase.
- It doesn't get tracker in Payment history admin page.
- There is no links in email receipt for .zip files.
- There is no links in `[purchase_history]` for .zip files.

Just let me know how you want me to test this.

**Comment by pippinsplugins** [comment]
Sami, are you on 2.5.5? Can we get a list of plugins from you?

**Comment by samikeijonen** [comment]
Yes I'm on 2.5.5, I updated my reply. Plugins active at the moment:

```

-- WordPress Active Plugins

Akismet: 3.1.7
Easy Digital Downloads: 2.5.5
Easy Digital Downloads - Mail Chimp: 2.5.5
Easy Digital Downloads - PDF Invoices: 2.2.12 (needs update - 2.2.15)
Easy Digital Downloads - Software Licenses: 3.4.6
Easy Digital Downloads - Stripe Payment Gateway: 2.3.8
Easy Digital Downloads - Taxamo Integration: 1.6.2
Easy GitHub Gist Shortcodes: 1.0
EDD Download Info: 1.1
EDD Feedback: 1.0.4
EDD Members: 1.1.4
EDD Software Licenses Changelog: 0.1.0
EDD Versions: 1.0.1
Envira Gallery: 1.4.1.1
Envira Gallery - CSS Addon: 1.0.7
Envira Gallery - Gallery Themes Addon: 1.0.7
Foxnet Themes Shop Plugin: 0.1.2
GistPress: 2.0.3
Gravity Forms: 1.9.15
Gravity Forms MailChimp Add-On: 3.7.1
Jetpack by WordPress.com: 3.8.2
Members: 1.1.1
Message Board: 1.0.0-pre-alpha
Miohki Backticks: 0.1.0
Simple Analytics: 1.0.3
Testimonials: 1.5.4
User Switching: 1.0.9
WP Migrate DB Pro: 1.5.3
WP Migrate DB Pro Media Files: 1.4.1
Yoast SEO: 3.0.7
```

**Comment by samikeijonen** [comment]
Ah at least PDF invoices needs update.

**Comment by pippinsplugins** [comment]
Would you be able to test this issue branch to see if it resolves the
problem for you?

**Comment by samikeijonen** [comment]
Sure.

**Comment by samikeijonen** [comment]
Works for me!

But the purchase made on master branch version 2.5.5 do not show up in Payment history. But if that has a future date that will show up there after a while I guess.

**Comment by pippinsplugins** [comment]
Excellent. That tells us what we need.

**Comment by jameslaws** [comment]
I'm on 2.5.5 and on EST, but transactions are being posted 5 hours in the past.

**Comment by pippinsplugins** [comment]
James, thanks. Same behavior we've been seeing. This issue branch fixes it.
Should see a point release later today.

**Comment by jameslaws** [comment]
Awesome! Thanks for everything. The only real downside is that I thought we just had a killer day until I realized that a bunch of those transactions were technically for the next day. ;)
