### ISSUE TITLE
Unnecessary (huge) downloads query that may cause memory limit exhausted

### ISSUE THREAD

**Issue by felixarntz** [easydigitaldownloads/Easy-Digital-Downloads#4183]
In the Add Discount form, a huge query is made to return all downloads (with `'nopaging' => true`). It looks to me that the resulting variable is not used at all. This query can be completely removed as far as I can see.

I would never have detected this, but if there are a lot of downloads available on a site, this query may even cause a 'Memory Limit exceeded' error (happened on 256 MB Memory Limit for me).

**Comment by pippinsplugins** [comment]
Thanks for noticing that! I've merged your PR and we'll include it in 2.5.7
