### ISSUE TITLE
Wrong date format in last_week reports

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/Easy-Digital-Downloads#4192]
Reported by a customer:

"I wanted to point out, however, that there's a tiny glitch. In the file, \admin\reporting\graphing.php, on line 691, the later half of the code currently uses 'Y-n-d h:i:s' for formatting $base_time when viewing a report by last_week. The format should be 'Y-m-d h:i:s' instead because part of the get_weekstartend() function involves taking a substr() $base_time and assumes that month will be in 2-digital format. Formatting the date using "n" excludes the leading 0."

Incorrect format [here](https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/2.5.6/includes/admin/reporting/graphing.php#L693).

**Comment by cklosowski** [comment]
`get_weekstartend()` is really only concrened with the line before it:
```
$base_time = $dates['range'] === 'this_week' ? current_time( 'mysql' ) : date( 'Y-n-d h:i:s', current_time( 'timestamp' ) - WEEK_IN_SECONDS );
$start_end = get_weekstartend( $base_time, get_option( 'start_of_week' ) );
```
That's the line we should be updating to use `m` instead of `n`
