### ISSUE TITLE
Symlinks with Redirect giving 403 in some cases

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#4193]
From Support request https://secure.helpscout.net/conversation/159523379/25044/?folderId=375162

Users getting a 403 with download method of redirect and symlinks enabled. Only way to get this to work was with the following:

`add_filter( 'edd_symlink_file_downloads', '__return_false' );`

Which is the same as turning off the option. 

```
-- Webserver Configuration

PHP Version:              5.6.15
MySQL Version:            5.5.42
Webserver Info:           Apache
```

It could be that the permissions are incorrectly set on the folder as well, going to make sure of this with the user too.

**Comment by pippinsplugins** [comment]
Pretty sure this is resolved through #4328. Closing as duplicate.
