### ISSUE TITLE
Clicking Purchase button multiple times on checkout results in Empty Cart error

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/easy-digital-downloads#4194]
If you click the purchase button on the checkout page multiple times, it results in an Ajax error stating `Error: Your cart is empty`. Then it reloads the checkout page and where you see an empty cart notice.

**The payment DOES go through.** Just once.

[Screencast](http://cl.ly/3Y1r0K1h2T3i).

Thoughts on preventing more than one click?

**Comment by pippinsplugins** [comment]
I thought we already blocked it. Let's make sure we are.

**Comment by pippinsplugins** [comment]
Ready for testing. Let's please test with Stripe and PayPal Pro / Express gateways.

**Comment by cklosowski** [comment]
With stripe...it didn't give me any errors, and only created one payment...but I see this: https://cloudup.com/csMfDPufhya

**Comment by pippinsplugins** [comment]
@cklosowski That's because the Stripe add-on adds it's own ajax indicator (I think).

**Comment by cklosowski** [comment]
:+1: Will keep testing with other platforms too.

**Comment by cklosowski** [comment]
This still wasn't working consistently for me, I changed it to use the `prop` function instead, and it's working better. This is how we're doing it on the `add to cart` buttons too.

**Comment by pippinsplugins** [comment]
:+1:
