### ISSUE TITLE
UX improvements to customer details metabox on payment details

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/easy-digital-downloads#4197]
Thinking about #4067 and customers who have asked me about how to move a payment from one customer to another led to thoughts on improving the customer details metabox on the payment details screen.

I've had customers ask me if editing the existing customer email and name is the proper way to do it. It's not. They need to create a new customer and assign it in the dropdown. One didn't even notice the dropdown was there...

Here's our existing UI:
![image](https://cloud.githubusercontent.com/assets/1254870/12358722/aba3b284-bb7c-11e5-8693-9de67edfcf8d.png)

It's pretty straightforward I think, but we made it and use it every day so maybe it's not as clear as it can be. I don't recall the exact reason we decided not to update the email from `customer => user` being discussed in #4067, but if someone wants to change the customer on one record and does it the wrong way as described above, they could lock the existing user account out of its own purchases and not even realize what happened.

Since changing customer records doesn't happen often, and there is at least _some_ confusion about how to do it properly, I propose we change the UI a bit to make it clearer how to assign a different customer.

Something like this would make it clearer, I think:
![image](https://cloud.githubusercontent.com/assets/1254870/12358844/41044672-bb7d-11e5-964e-4f328db383ed.png)

In the above screenshot, the customer name and email would link to the customer card. This is probably the use case for 99% of the time someone views that section. I don't think we need the dropdown to always show.

Changing the customer would involve clicking the `Assign to another customer` link, which would then swap out the linked customer name/email with the dropdown we have now. This action and change in UI would clarify the steps needed to do this properly, and would very likely prevent someone from doing it the wrong way.

**Comment by pippinsplugins** [comment]
I like the proposed change. One reason in particular: it makes it so the email address can be fully viewed and copied from the details screen now, which hasn't been possible since we changed it to a drop down.

**Comment by cklosowski** [comment]
I like this too, one suggestion is to not link the email address. Right now to copy and paste with this solution, you have to copy the `(` and `)` characters, then remove them, if we either remove those, or remove the link, we should be able to copy easier maybe:
`Customer name - customer@domain.com`. This way we can just select the email if we want, and still leave the whole thing a link.

**Comment by pippinsplugins** [comment]
I've answered numerous tickets recently where store owners asked how they could move a purchase from one customer to another, which hints at the current UI not being intuitive enough.

The proposal @mindctrl made would make this much more clear.

**Comment by pippinsplugins** [comment]
@cklosowski Looking good!

Could we put `Select customer` and drop down on a single line please?
![screen shot 2017-01-09 at 2 48 39 pm](https://cloud.githubusercontent.com/assets/1034109/21782926/c882ef40-d67a-11e6-9f89-5684323c2b93.png)

**Comment by cklosowski** [comment]
@pippinsplugins sure, I was just following the way we did it for the New Customer, our labels are above their inputs. Do we want to change those too?

**Comment by pippinsplugins** [comment]
Yeah we should make it consistent.

**Comment by cklosowski** [comment]
Ok, Since `new customer` exists already the argument could be made that `Select a customer` on as it is, is more consistant.

**Comment by cklosowski** [comment]
We actually have CSS in place to make those above the inputs, so do we want to alter the existing behavior?

**Comment by cklosowski** [comment]
@SDavisMedia @pippinsplugins Fixed:
![screen shot 2017-01-09 at 3 07 57 pm](https://cloud.githubusercontent.com/assets/1390124/21785591/6dd420ca-d67d-11e6-97f3-774851b16826.png)

![screen shot 2017-01-09 at 3 07 53 pm](https://cloud.githubusercontent.com/assets/1390124/21785595/70349840-d67d-11e6-8bbe-22966fb462b7.png)

**Comment by SDavisMedia** [comment]
I definitely like it. Checked it out on my machine and I think it looks really good.

**Comment by cklosowski** [comment]
Cool, closing this out and merging.

**Comment by pippinsplugins** [comment]
I'm good with that.

**Comment by pippinsplugins** [comment]
This appears to have been reverted or lost somehow. Changes are not showing in `release/2.7` any longer.

**Comment by SDavisMedia** [comment]
Looks like they were lost here: https://github.com/easydigitaldownloads/easy-digital-downloads/pull/5407

**Comment by cklosowski** [comment]
@SDavisMedia @pippinsplugins Ah, must have gotten removed in fixing a merge conflict. I'll fix it up.

**Comment by pippinsplugins** [comment]
Looks good.
