### ISSUE TITLE
Add delete option to View Order Details screen

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#4203]
At the moment there is no way to delete a payment from the `View Order Details` screen. When needing to delete a payment, this is really annoying.

**Comment by SDavisMedia** [comment]
I don't like that placement either but it seems like the lesser of several evils. I don't like the link above the resend and save buttons. Below is a bit awkward, especially as a left-aligned link.

The only thing I'm really happy with is a dedicated postbox in the bottom right corner of the entire screen specifically for deleting the payment. I don't think it should be a very convenient action to take. My 2 cents.

**Comment by pippinsplugins** [comment]
That was exactly my struggle with this: where to put it or where to move `Resend Receipt`.

I wouldn't be opposed to a dedication box in the bottom.

**Comment by mintplugins** [comment]
Personally, I feel like "Resend Receipt" is out of context there - like it doesn't really belong. Whereas "Delete" would belong there because it's a similar action to saving a payment.

I could see a new metabox for Receipts being below like @pippinsplugins mentioned.

**Comment by pippinsplugins** [comment]
I think I prefer `Resend Receipt` being separate instead of `Delete` as well. That better follows core. `Resend Receipt` would need to be up top, not at the bottom like @SDavisMedia suggested for the delete link.

**Comment by SDavisMedia** [comment]
I agree. Didn't think you guys would want to move Resend Receipt to a dedicated box.

I'm all for Save Payment as a right aligned button, Delete Payment as a left aligned link, and Resent Receipt in its own box. :+1:

**Comment by pippinsplugins** [comment]
Proposal for final design:
![screen shot 2016-04-14 at 12 37 50 pm](https://cloud.githubusercontent.com/assets/1034109/14537755/0204f5e0-023e-11e6-92b6-c827b8e87b6c.png)

**Comment by mintplugins** [comment]
Looks fine to me. Would be cool to have a hook so that PDF invoices and others can put links there too maybe?

**Comment by pippinsplugins** [comment]
There is a hook before and after:

- edd_view_order_details_resend_receipt_before
- edd_view_order_details_resend_receipt_after

**Comment by michaelbeil** [comment]
:+1: looks good.
> I'm all for Save Payment as a right aligned button, Delete Payment as a left aligned link, and Resent Receipt in its own box.
