### ISSUE TITLE
Download links give permission denied when qTranslate-X

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#4210]
We've just had a customer report (and I replicated) that file download links break when the `qTranslate-X` plugin is activated, or at least causes the links to break when the language parameter is included in the URL.

qTranslate-X is apparently a new version of qTranslate: https://wordpress.org/plugins/qtranslate-x/installation/

We previously fixed this conflict in https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/3635, https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/1365, and https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/164

**Comment by pippinsplugins** [comment]
@mindctrl Think you could work on this? Fix should be nearly identical to previous fix.

**Comment by mindctrl** [comment]
@pippinsplugins do you recall which URL option was being used?
![image](https://cloud.githubusercontent.com/assets/1254870/12789513/2bc5b3e2-ca6c-11e5-8086-efdc38444b20.png)

**Comment by mindctrl** [comment]
Happens on pre-path mode. Does not happen on query mode.

**Comment by mindctrl** [comment]
I feel dirty, but it works. I didn't see another clean way.

**Comment by pippinsplugins** [comment]
I'm okay with dirty, even like it sometimes.

@cklosowski any objections to merging?

**Comment by cklosowski** [comment]
I'm good with this, merging.
