### ISSUE TITLE
Extensions tab with no legacy extensions looks off

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/Easy-Digital-Downloads#4211]
When you are viewing the new Extensions tab, with only extensions that support subsections it looks a little weird to have a main:

![screen shot 2016-01-18 at 3 56 17 pm](https://cloud.githubusercontent.com/assets/1390124/12404815/3641d098-bdfc-11e5-8c60-e9bc360bbf1b.png)

We should look at hiding that save button or simlar if we're on a main without any settings.

**Comment by pippinsplugins** [comment]
How about defaulting to the first sub section and not showing `Main`?

**Comment by cklosowski** [comment]
@pippinsplugins We can look into that as a solution, I'll have to dig into the subsection code to see where we want to handle that.

**Comment by cklosowski** [comment]
@mindctrl are we good here? Can I merge this and close it out?

**Comment by mindctrl** [comment]
@cklosowski looks great here.
