### ISSUE TITLE
Empty Cart after clicking purchase link

### ISSUE THREAD

**Issue by stevenbhn** [easydigitaldownloads/Easy-Digital-Downloads#4213]
We are having an issue (since most recent update) where a few particular downloads, when the purchase button is clicked, goes to an empty cart page. Sometimes these work and sometimes they don't. We have disabled all caching plugins, tested on several machines and all major browsers and the issue persists. We have not added any other plugins and the edd plugin has worked fine for us for a few years. 

As requested by Pippin, we added the following to our wp-config.php file:

define('EDD_USE_PHP_SESSIONS', flase);

But this has not helped.

This has been happening for 5 days since the update and has had a big impact on our sales.

Can anyone please help?

thanks
Steven

**Comment by pippinsplugins** [comment]
Steven,

That line for wp-config.php should be `define('EDD_USE_PHP_SESSIONS', false);`

Also, let's please continue this through the support ticket that you opened. Github is for development tracking only, not support.
