### ISSUE TITLE
Introduce a new filter `edd_recalculate_total()`

### ISSUE THREAD

**Issue by felixarntz** [easydigitaldownloads/easy-digital-downloads#4216]
For a current project, I'm in need of a filter like `edd_recalculate_total` which would be run in the method of the same name in `EDD_Payment`. I have built some custom logic concerning prices and I need to be able to adjust the way the total amount is calculated.

I'm proposing something like this (in `EDD_Payment`):

``` php
private function recalculate_total() {
    $this->total = apply_filters( 'edd_recalculate_total', $this->subtotal + $this->tax + $this->fees_total, $this->ID, $this );
}
```

With the payment object as parameter, one would have access to everything possibly required to adjust the total amount calculation.

**Comment by cklosowski** [comment]
@felixarntz The idea behind the recalculation being private is that it's not able to be modified.

If you need to modify the end result of the total of the payment, you should be modifying the prices of the items on the payment itself, not modifying the total. This could lead to differences in the stats you see in total earnings and product sales earnings. The end `total` of a payment is a sum of it's parts, not a canonical value.

thoughts @pippinsplugins ?

**Comment by cklosowski** [comment]
I'm not opposed to a way to do this, i'm just not sure it's entirely sure it belongs in the `recalculate_total` method. Could it possibly live inside the `save` or something of the likes?

**Comment by felixarntz** [comment]
@cklosowski the reason I need to do this is actually described more precisely in #4200. I need to be able to define fees with taxes where the taxes are included _in_ the amount that I give the fee. EDD currently does not allow that, so I used some filters to create a kind of hacky solution - it's not nice, but it works for my cause. The filter I mention above is the only thing that is missing for me to actually get it to work in a "relatively" proper way.
I guess the filter could be added before inserting the payment as well, but personally I think the `recalculate_total()` method fits it best since this ensures that the total will be "fixed" (fixed in my case) everywhere. I still understand your concern since the method is private and people could easily screw up their payments using this filter. Let's continue thinking about it

**Comment by pippinsplugins** [comment]
Both sides are valid.

I _think_ I'm okay with adding the filter. Anyone that uses it assumes all responsibility for discrepancies it may cause to stats. As long as we're okay with that, I vote we add it.

**Comment by felixarntz** [comment]
Pull-request in case it's approved...

**Comment by cklosowski** [comment]
Ok, thanks for the PR. I see both sides, and while i'm not a fan of dropping a filter on a private method, I think the justification for lack of needs is there in the Fees class.

Also I see that Its not effectivly altering the total, but altering the values within the object, so the proper subtotals, taxes, and fees are applied.

Thanks for explaining your needs @felixarntz

**Comment by pippinsplugins** [comment]
Let's leave this open for a bit, I may have reversed my opinion.

**Comment by sunnyratilal** [comment]
@pippinsplugins @cklosowski Any further thoughts with regards to this?

I think we should close this out if we don't see this being merged into core.

**Comment by cklosowski** [comment]
I'm still on the fence...I'm not a fan of a filter in a private method...@felixarntz the most recent changes to the Fees API haven't made this possible yet, I assume?

**Comment by pippinsplugins** [comment]
Let's close as wontfix for the time being.

**Comment by felixarntz** [comment]
@cklosowski Haven't had a look recently. I'll put it on my list :)
