### ISSUE TITLE
SiteOrigin Pagebuilder causes unexpected output in [downloads] shortcode

### ISSUE THREAD

**Issue by topher1kenobe** [easydigitaldownloads/easy-digital-downloads#4218]
Causes line breaks to be inserted between pagination links on the [downloads] shortcode

**Comment by gregpriday** [comment]
Let me know if you guys need any help on this, or if there's anything we need to fix in Page Builder.

**Comment by pippinsplugins** [comment]
Thanks for the help offer @gregpriday !

**Comment by pippinsplugins** [comment]
I have not seen any new reports of this issue. Closing as fixed.
