### ISSUE TITLE
edd_download_files stores the HTTP scheme in the database

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/Easy-Digital-Downloads#4222]
If you have a site that's HTTP, then setup a download, and then add an SSL full time to the site and you'll get a mismatch issue on the download, reported here:
https://secure.helpscout.net/conversation/162223800/25756/?folderId=375162

**Comment by pippinsplugins** [comment]
Good catch!

What about removing the protocol during the download process?

**Comment by cklosowski** [comment]
@pippinsplugins that could be a good solution.

We'd want to only remove the protocol and use the site's protocol, if the domain on the download file is the same as the site, otherwise downloading from an external source and swapping out scheme's could be problematic.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by cklosowski** [comment]
Going to wait for #4328 as it contains a check for urls that are local...will be useful and make this much faster. So once that's merged I'll do something with this.

**Comment by topher1kenobe** [comment]
On this one can we simply make all the urls start with // and let the protocol take care of itself?

**Comment by cklosowski** [comment]
Not really as we need a fully qualified URL, but what we're going to do is strip the scheme and replace it with the scheme requested, this will prevent any past/future changes to the site's scheme from getting in the way without messing with the saving of the download files process in the meta.

**Comment by pippinsplugins** [comment]
I've merged this into `2.5.10-beta` and am sending it to a few users.

**Comment by pippinsplugins** [comment]
I just ran another test on this and it looks good.

On `master`, a file that is using the wrong scheme failed to download. On `issue/4222`, both files download properly.
