### ISSUE TITLE
Add a method in EDD_Payment for making as refunded

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/Easy-Digital-Downloads#4223]
We currently have a method of marking a payment as complete, but the other action that has the most hook points is a 'refund'.

We need to add a refund_payment method in `EDD_Payment` to allow for extensions to easily hook when a refund is being processed.

**Comment by pippinsplugins** [comment]
@cklosowski I get `refund failed` when trying to refund a payment now: https://cloudup.com/cRcPQPzwpNh

**Comment by pippinsplugins** [comment]
Ok actually looks like the refund processed but it showed the wrong admin notice.

**Comment by cklosowski** [comment]
I got the proper notice in admin, I'll try again.

**Comment by pippinsplugins** [comment]
Just tried it again. It refunded fine but I get an undefined index now:

Notice: Undefined variable: message in /Users/pippinwilliamson/Sites/trunk/wp-content/plugins/edd-recurring/includes/admin/class-admin-notices.php on line 53

**Comment by cklosowski** [comment]
@pippinsplugins this was a bug in recurring, I found it and fixed it in `issue/203` of recurring

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
Heh, major bug.

Refunding a payment causes the sale count on each item in the payment to decrease by `3`, not `1`.

**Comment by pippinsplugins** [comment]
Hmm, maybe not all the time. It definitely happened on one particular sale but I just tried again and it didn't do it.

**Comment by pippinsplugins** [comment]
OK all is good. I forgot that I had had quantities enabled and then later disabled them.

**Comment by pippinsplugins** [comment]
@cklosowski just one item I noticed: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/pull/4228#discussion_r51338394

**Comment by cklosowski** [comment]
@mindctrl this could use some testing, if you have some bandwidth. Pretty major addition to the platform.

**Comment by cklosowski** [comment]
@pippinsplugins your comment here: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/4223#issuecomment-177048269), was probably caused by that bug I found in the `edd_undo_purchase` where, things were looping through each download in the payment, and then the function was doing the same, but for a specific download ID...should be resolved now.

**Comment by pippinsplugins** [comment]
@cklosowski Agreed.

**Comment by mindctrl** [comment]
@pippinsplugins @cklosowski this looks good to me. Tested refunds from UI and programmatically. All sales and earnings were updated properly. Anything else to look for?

**Comment by pippinsplugins** [comment]
@mindctrl Beautifully. That's all we needed!
