### ISSUE TITLE
Updating _edd_payment_meta mysql data causes blank fields in order details

### ISSUE THREAD

**Issue by christ0ph3r** [easydigitaldownloads/Easy-Digital-Downloads#4226]
I am trying to work on localhost and ran into an issue after doing string and replace on URLS in mysql.

```
UPDATE wp_options SET option_value = replace(option_value, 'https://example.com', 'http://dev.example.com/example/wordpress');

UPDATE wp_posts SET guid = replace(guid, 'https://example.com','http://dev.example.com/example/wordpress');

UPDATE wp_posts SET post_content = replace(post_content, 'https://example.com', 'http://dev.example.com/example/wordpress');

UPDATE wp_postmeta SET meta_value = replace(meta_value, 'https://example.com', 'http://dev.example.com/example/wordpress');




UPDATE wp_options SET option_value = replace(option_value, 'http://example.com', 'http://dev.example.com/example/wordpress');

UPDATE wp_posts SET guid = replace(guid, 'http://example.com','http://dev.example.com/example/wordpress');

UPDATE wp_posts SET post_content = replace(post_content, 'http://example.com', 'http://dev.example.com/example/wordpress');

UPDATE wp_postmeta SET meta_value = replace(meta_value, 'http://example.com', 'http://dev.example.com/example/wordpress');
```

I then went to payment history and clicked an order.  The order detail fields are now blank.

![selection_038](https://cloud.githubusercontent.com/assets/5915361/12495024/2df1973c-c042-11e5-9445-eeb2dcb73977.png)

I can make new payments and the data shows up in the fields. I then tested on new payments by changing _edd_payment_meta data.  I changed the persons name.  I also tried changing a few other things and every time an even minor change occured all the fields went blank.   I tried this with only EDD and 2016 wp theme.

Is there way to change this data without making order detail fields go blank?

The reason I need to change the URLS for EDD is because I have a custom field that has URL in  _edd_payment_meta .

**Comment by mindctrl** [comment]
@christ0ph3r you'll need to use a tool that searches and replaces serialized values. Try https://github.com/interconnectit/Search-Replace-DB or https://wordpress.org/plugins/better-search-replace/.

For question like this, feel free to open a support ticket at https://easydigitaldownloads.com/support/. We handle support there and development issues here.

**Comment by christ0ph3r** [comment]
Thank you for pointing me in the right direction.  I did not know about this.  I thought this was a bug so thats why I posted here.  Both of these tools work well.
