### ISSUE TITLE
Bug in edd_download_redirect_to_checkout filter implementation

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/easy-digital-downloads#4227]
When using the filter [here](https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/f2f1f7db7322f5abe2d5900be0c40895978aed21/includes/template-functions.php#L211) to control the redirect behavior of a single product, it doesn't work because the JS depends on  `edd_scripts.redirect_to_checkout` being set [here](https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/2.5.6/assets/js/edd-ajax.js#L176). But that doesn't get set because of the check [here](https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/2.5.6/includes/scripts.php#L79).

**Comment by cklosowski** [comment]
So basically if you have the site set to not redirect to checkout, but you want a single product to redirect to checkout it's not possible as the localized scripts are checking the store level, instead of also checking the product/purchase link level?

**Comment by pippinsplugins** [comment]
Correct. The filter works to disable redirect to checkout on individual products but it does not work to enable.

**Comment by sunnyratilal** [comment]
Merged into `release/2.7`
