### ISSUE TITLE
Wrong currency in [purchase_history]

### ISSUE THREAD

**Issue by fxbenard** [easydigitaldownloads/Easy-Digital-Downloads#4230]
Some $ are showing up and I use €

Same in product details

http://d.pr/i/12YaI

**Comment by pippinsplugins** [comment]
Do you use any of the multi currency plugins or did you change the currency of your site?

**Comment by fxbenard** [comment]
No plugin at all! Just the regular settings.

The last update seems to be the culpit. Currency setting was reinitialized without notice. Putting back € seems to solve the issue everywhere.

**Comment by pippinsplugins** [comment]
Hmm, I can't think of any reason that would have changed . . .

**Comment by fxbenard** [comment]
Me either but it happened. Let's close ans stay aware
