### ISSUE TITLE
Improve category and tag taxonomy labels

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/Easy-Digital-Downloads#4232]
We've seen this confusion quite a bit. The labels for categories and tags are simply "Categories" and "Tags". This causes confusion in places like the menu editor, where you can't tell the difference between the core categories and tags for posts and the ones for downloads.

**Comment by spencerfinnell** [comment]
:+1: Also confusing in plugins like FacetWP where you are presented with lists of all registered taxonomies.

**Comment by pippinsplugins** [comment]
If I recall, they're named as `Categories` and `Tags` because that's what we want them to show as under the Downloads menu. I don't believe there's a way to change the label elsewhere but leave it there.

**Comment by spencerfinnell** [comment]
'menu_name' - the menu name text. This string is the name to give menu items. If not set, defaults to value of name label.

https://codex.wordpress.org/Function_Reference/register_taxonomy

**Comment by pippinsplugins** [comment]
Oh fantastic. I forgot that existed.

I vote we make `menu_name` `Categories` and `Tags` but change the others to `Download Categories` and `Download Tags`.
