### ISSUE TITLE
Settings location for email receipt template and preview/test buttons

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/easy-digital-downloads#4233]
A customer pointed this out.

With the addition of subsections in #4058, the placement of Email Template, Logo, and Preview buttons seems to disconnected from where they go. They're related to the purchase receipt, but they show in the first Email Settings section instead of the Purchase Receipts section. Should we move them to the Purchase Receipts section?

**Comment by pippinsplugins** [comment]
Whoops. Yes, I think we should move them.

**Comment by cklosowski** [comment]
Technically logo and template are used for emails like license renewals as well so they aren't specifically for purchase receipts.

**Comment by pippinsplugins** [comment]
Punting to 2.6 for further discussion.

**Comment by sunnyratilal** [comment]
@pippinsplugins @cklosowski What's the general direction we want to take here?

**Comment by pippinsplugins** [comment]
@sunnyratilal let's not worry about this for now.

**Comment by SDavisMedia** [comment]
Logo and Template shouldn't move. They're general settings for emails.

**Preview Purchase Receipt** and **Send Test Email** need to move the the Purchase Receipts section, though. And when that happens, the Preview of the email needs to pull the **Purchase Email Heading** setting value. Right now, it displays "Purchase Receipt" as the email heading no matter what.

(this just caused some confusion for a user)

**Comment by pippinsplugins** [comment]
PR submitted that moves the settings around a bit into a more logical configuration.

**Comment by SDavisMedia** [comment]
@pippinsplugins can we include having the email preview pull the **Purchase Email Heading** value in this PR too?

**Comment by pippinsplugins** [comment]
@SDavisMedia done.

**Comment by SDavisMedia** [comment]
@pippinsplugins it pulls the value now but doesn't read email tags like the real email does.

**Comment by pippinsplugins** [comment]
@SDavisMedia added.

**Comment by SDavisMedia** [comment]
@pippinsplugins Perfect. :+1:
