### ISSUE TITLE
Editing Purchased Downloads does not save in certain scenarios

### ISSUE THREAD

**Issue by mgibbs189** [easydigitaldownloads/Easy-Digital-Downloads#4236]
Let's say I have a product with 2 price variations:

```
Basic ($10)
Professional ($20)
```

A user purchases the Basic license. Shortly afterwards, an admin wants to upgrade their license to Professional for free.

On the payment detail screen, the admin removes the Basic item from the `Purchased Downloads` box, replacing it with Professional (with `Item Price = $10`).

After saving, the `Purchased Downloads` box reverts to showing the Basic license.

**Comment by pippinsplugins** [comment]
I've replicated and confirmed the bug.

**Comment by mgibbs189** [comment]
Thanks Pippin.

On further investigation, it looks like the **last items** are always the ones that get removed. For example, if a purchase includes the following items (variations):

```
A
B
C
D
E
```

and I try removing `B` and `C`, the list looks like this after saving (bad):

```
A
B
C
```

instead of this (good):

```
A
D
E
```

Does that make sense?

**Comment by pippinsplugins** [comment]
Yes it does. We'll get it fixed up asap!

**Comment by cklosowski** [comment]
@mgibbs189 I tested this out, and I had 6 products on a payment:
![screen shot 2016-01-25 at 11 53 21 am](https://cloud.githubusercontent.com/assets/1390124/12560904/6e80057a-c35a-11e5-954f-bb2b4c7431eb.png)

Then went and removed the 2nd and 3rd items, and saved, and this was the result:
![screen shot 2016-01-25 at 11 54 26 am](https://cloud.githubusercontent.com/assets/1390124/12560920/7e53ca9a-c35a-11e5-8854-48a52eb7b299.png)

It appears to have saved correctly. Does this only happen with Software Licensing enabled maybe? Is it only variable priced products? Just curious if your example above was only variable priced.

**Comment by mgibbs189** [comment]
@cklosowski No, I'm not using Software Licensing.

In my example above, `A, B, C, D, and E` are all the same product, just different variations.

**Comment by cklosowski** [comment]
Oh, cool thanks @mgibbs189 I'll test out with that. Appreciate you getting back to me.

**Comment by cklosowski** [comment]
Confirmed, thanks @mgibbs189 I'll work up a fix for it.

**Comment by cklosowski** [comment]
I think this is a bug in the `EDD_Payment` class, I'm going to add a unit test for this specific scenario and see where it goes.

**Comment by cklosowski** [comment]
@mgibbs189 can you test out `issue/4236` for me see if that resolves the issue you're seeing?

**Comment by cklosowski** [comment]
I added a few unit tests to verify removing via price_id and index were correct.

**Comment by cklosowski** [comment]
Just realized that we have to be sure the `cart_details` index doesn't change as there are items that rely on this data, correct @pippinsplugins? So even when removing a download, the `cart_index` keys have to remain as they were, so that the indexes still align.

**Comment by mgibbs189** [comment]
@cklosowski Sure, testing now...

**Comment by mgibbs189** [comment]
@cklosowski Doesn't quite work. Screencast: http://d.pr/v/10eYF

Notice how the items re-order on save. Towards the end, I try deleting the $10 item. Notice how it still remains after save.

**Comment by cklosowski** [comment]
Pulled my latest? I found I can't reorder the `cart_details`

**Comment by cklosowski** [comment]
@mgibbs189 Ok, I think I see where it's going wrong now...seems that I need one more check, it's finding the ID and the price ID in there, which are now the same as you've added the same price point multiple times, need to verify the 'amount' too.

**Comment by mgibbs189** [comment]
@cklosowski Yep, I'm at 009656c - let me know when you need some re-testing

**Comment by cklosowski** [comment]
Yeah writing up another unit test to test multiples of the same Price ID but with amounts to identify those.

**Comment by cklosowski** [comment]
@mgibbs189 try with the latest push?

**Comment by mgibbs189** [comment]
@cklosowski Works :+1:

**Comment by pippinsplugins** [comment]
All works great for me!

**Comment by cklosowski** [comment]
thanks @mgibbs189 and @pippinsplugins
