### ISSUE TITLE
Suggestion: store EDD stats into a custom table

### ISSUE THREAD

**Issue by mgibbs189** [easydigitaldownloads/Easy-Digital-Downloads#4237]
Hey guys,

I've noticed that, between `_edd_transient_edd_stats` and `_edd_transient_timeout_edd_stats`, over 5000 rows are being added to the options table (on a relatively small site).

This might be a good fit for a custom stats table (or maybe just a custom transients table). I'd imagine it would be a lot more efficient if the timeouts were stored alongside the data.

**Comment by pippinsplugins** [comment]
@mgibbs189 Are your transients not getting replaced or deleted automatically? We only have a few different transients that we use for stats so there shouldn't be anywhere near that number left over in the DB.

**Comment by mgibbs189** [comment]
@pippinsplugins That's a possibility. I'll manually flush transients and keep an eye on the table. Will re-open this ticket if necessary.

Thanks

**Comment by pippinsplugins** [comment]
:+1:
