### ISSUE TITLE
accepted payment method icons need transparent backgrounds

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#4238]
Right now, the .gif files actually appear to be icons with a white background. The icons have rounded corners so the white background pokes through on all four corners. That's no good from a designer's perspective.

Excuse the ugly screenshot but you can see it here in the dashboard settings:

![screen shot 2016-01-25 at 8 48 20 am](https://cloud.githubusercontent.com/assets/2359131/12557598/7b5e8484-c340-11e5-9c22-dd49d62124a6.png)

**Comment by cklosowski** [comment]
:+1: might be nullified once #2717 (and dashicons for that matter) is figured out but this is a good short term solution

**Comment by cklosowski** [comment]
@SDavisMedia can you do this? I don't have a Creative Suite license anymore, just have Illustrator.

**Comment by SDavisMedia** [comment]
Sure thing... anyone know where we got the icons from? They might just need to be replaced unless we have some files somewhere.

**Comment by cklosowski** [comment]
the files are in the repo, https://github.com/easydigitaldownloads/Easy-Digital-Downloads/tree/master/templates/images/icons

**Comment by SDavisMedia** [comment]
@cklosowski Not sure what's important about those files. Editing them to cut the white corners is probably not the best route, if that's what you're implying. Should be a last resort. I'll shoot for a better solution and only do that if it comes down to it.

**Comment by cklosowski** [comment]
Ok perfect. I assumed that would be the easiest method.

**Comment by pippinsplugins** [comment]
Merged into master!

I'm going to leave the `.gif` versions in the plugin just in case anyone is loading them manually.

**Comment by michaelbeil** [comment]
@pippinsplugins What about theses instances within edd.css?

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/templates/edd.css#L409-L419

**Comment by cklosowski** [comment]
Woot! no more iPhone 3GS!
