### ISSUE TITLE
Product search on Export Customers to CSV brings up customers, not downloads

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#4240]
The `Export Customers to CSV` option lets you export the customers of a specific product to a CSV file. When searching for a product, however, it is returning search results of customer emails, not products.

**Comment by cklosowski** [comment]
this is happening due to the following JS:
```
		if( container.attr( 'id' ).indexOf( "customer" ) >= 0 ) {
			search_type = 'edd_customer_search';
		}
```
Bascially when we introduced the customer dropdown, we added a clause for the ajax to identify if it was a 'download' or a 'customer' dropdown. We might have to rethink this approach a bit.

**Comment by pippinsplugins** [comment]
@mindctrl could you test the PR here please?

**Comment by mindctrl** [comment]
@cklosowski I'm seeing double products in the search results.

![image](https://cloud.githubusercontent.com/assets/1254870/12650184/d32b5626-c5af-11e5-89e8-6b3ed9a46dfc.png)

**Comment by cklosowski** [comment]
Well thats odd. I'm not seeing that behavior @mindctrl, looking it over.

**Comment by cklosowski** [comment]
![screen shot 2016-01-28 at 10 16 27 am](https://cloud.githubusercontent.com/assets/1390124/12652484/386c964c-c5a8-11e5-9a6d-88bab0ee98f6.png)

I had to update the JS, can you make sure you're getting the updated JS with a browser cache clear @mindctrl ?

**Comment by mindctrl** [comment]
I actually had products with duplicate names, from testing. Sorry. This is good.

**Comment by cklosowski** [comment]
As a note, this adds a new extendable 'search-type' to our chosen fields. Now someone could request a select box and in the `data` arguement supply `'search-type' => 'discount'`, and then build an ajax hook for `edd_discount_search` and return discount codes or something similar to that.

**Comment by cklosowski** [comment]
@pippinsplugins ready to merge whenever you are.

**Comment by pippinsplugins** [comment]
Merging.
