### ISSUE TITLE
Allow access to .jpeg files in .htaccess rules

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/Easy-Digital-Downloads#4242]
We allow access to `.jpg` files in the protected directory rules, but not .jpeg files. [Reference](https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/2.5.6/includes/admin/upload-functions.php#L153). I've seen this cause problems several times for folks uploading `.jpeg` files.

Let's add `.jpeg` to the allowed filetypes.

**Comment by pippinsplugins** [comment]
:+1:
