### ISSUE TITLE
Incorrect item price stored in sale log when adding new download to payment

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#4244]
When adding new downloads to a payment record, the item price is sometimes stored incorrectly. I believe it is limited to items with variable prices.

This item has variable prices of $10 and $20. The $20 (price ID 2) option was added to the payment and saved:
![screen shot 2016-01-27 at 8 48 18 am](https://cloud.githubusercontent.com/assets/1034109/12592817/f84e0d32-c4d2-11e5-88f8-ad5d0c8f252c.png)

The sales log was created with the $10 amount:
![screen shot 2016-01-27 at 8 50 13 am](https://cloud.githubusercontent.com/assets/1034109/12592830/07a07fd6-c4d3-11e5-9ae8-8b07fbfd914a.png)

The earnings on the item was properly adjusted by $20.

**Comment by pippinsplugins** [comment]
My guess is this is due to the price ID being incorrect in `edd_record_sale_in_log( $item['id'], $this->ID, $price_id, $log_date );` during the `save()` method.

**Comment by pippinsplugins** [comment]
Looks like it's perhaps worse than I thought.

No sale log entry was created at all.

**Comment by pippinsplugins** [comment]
Sale logs definitely not getting created anymore.

**Comment by pippinsplugins** [comment]
@cklosowski Can you hit this?

**Comment by cklosowski** [comment]
Yeah I've confirmed the same thing, working on it.

**Comment by cklosowski** [comment]
Sales logs for items added to downloads. Sales logs are being recorded when purchasing, just to clarify for the sake of the issue.

**Comment by cklosowski** [comment]
I see the issue, the logs are getting marked with a status of `future`

![screen shot 2016-02-09 at 12 33 03 pm](https://cloud.githubusercontent.com/assets/1390124/12928196/50cff85c-cf29-11e5-85d1-11feef472c90.png)
