### ISSUE TITLE
PHP Notice:  Undefined variable: file_path

### ISSUE THREAD

**Issue by sumobi** [easydigitaldownloads/Easy-Digital-Downloads#4246]
When using Free Downloads with EDD I'm seeing this notice when downloading the file.

    PHP Notice:  Undefined variable: file_path in /wp-content/plugins/easy-digital-downloads/includes/process-download.php on line 203

Possibly related:
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/4113
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/3286
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/4109

**Comment by pippinsplugins** [comment]
This is happening because none of these conditionals are validating as `true`:
```php
if ( ( ! isset( $file_details['scheme'] ) || ! in_array( $file_details['scheme'], $schemes ) ) && isset( $file_details['path'] ) && file_exists( $requested_file ) ) {

	/** This is an absolute path */
	$direct    = true;
	$file_path = $requested_file;

} else if( defined( 'UPLOADS' ) && strpos( $requested_file, UPLOADS ) !== false ) {

	/**
	 * This is a local file given by URL so we need to figure out the path
	 * UPLOADS is always relative to ABSPATH
	 * site_url() is the URL to where WordPress is installed
	 */
	$file_path  = str_replace( site_url(), '', $requested_file );
	$file_path  = realpath( ABSPATH . $file_path );
	$direct     = true;

} else if( strpos( $requested_file, content_url() ) !== false ) {

	/** This is a local file given by URL so we need to figure out the path */
	$file_path  = str_replace( content_url(), WP_CONTENT_DIR, $requested_file );
	$file_path  = realpath( $file_path );
	$direct     = true;

} else if( strpos( $requested_file, set_url_scheme( content_url(), 'https' ) ) !== false ) {

	/** This is a local file given by an HTTPS URL so we need to figure out the path */
	$file_path  = str_replace( set_url_scheme( content_url(), 'https' ), WP_CONTENT_DIR, $requested_file );
	$file_path  = realpath( $file_path );
	$direct     = true;

}
```

**Comment by pippinsplugins** [comment]
I'm proposing that we set a default of `$file_path = $requested_file` before the conditionals to ensure that `$file_path` is always defined. In the majority of cases the file path simply represents the file's public URL so it should still download properly.

**Comment by cklosowski** [comment]
@pippinsplugins yeah I'm good with that as the default.
