### ISSUE TITLE
Run maybe_unserialize on setup_user_info of EDD_Payment

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/Easy-Digital-Downloads#4248]
Identified by @norcross here: https://github.com/easydigitaldownloads/EDD-Software-Licensing/issues/430

**Comment by cklosowski** [comment]
@norcross this seem like it should do the trick? I replicated it in the unit tests without my fix in place, then put the fix in place and unit test passed. If you're good with this I'll merge it.

**Comment by norcross** [comment]
I actually patched my version in production and it's been working for me.

**Comment by cklosowski** [comment]
@norcross sweet thanks, @pippinsplugins review whenever you can and merge then.
