### ISSUE TITLE
Improve custom earnings report graph

### ISSUE THREAD

**Issue by mgibbs189** [easydigitaldownloads/Easy-Digital-Downloads#4250]
Things get real messy when trying to view an Earnings report over an extended period of time.

<img src="http://i.imgur.com/Hctkjux.png" width="680" height="291" />

I'd be happy to help improve this feature, but we'll need a direction on how to proceed. E.g. we need to define some "break points" of when to automatically switch the graph from day / week / month / quarter / year modes. Or maybe make it a user option...

**Comment by cklosowski** [comment]
Something seems off here, It looks like tis' doing day-by-day? If the span of the earnings goes over a 2 month period, it's supposed to avoid day-by-day calculation.

@mgibbs189 can you confirm that's doing a day by day? Seems like a bug to me in the way the date range calculations are being determined.

**Comment by cklosowski** [comment]
I'd look at the year spanning code that determines `$day_by_day` variable, and go from there, I don't think we need to rework this as it didn't used to do this type of detail on larger data sets, just need to fix the bug we introduced.

**Comment by pippinsplugins** [comment]
I think @cklosowski is right. I saw this happen yesterday too.

**Comment by mgibbs189** [comment]
Yeah, that sounds about right.

Whatever logic is in place to choose between day-to-day or monthly seems off.

**Comment by cklosowski** [comment]
@mgibbs189 @pippinsplugins how do we feel about this one now?

**Comment by pippinsplugins** [comment]
Looks good to me.
