### ISSUE TITLE
Fix translation issues with missing domains and markup

### ISSUE THREAD

**Issue by fxbenard** [easydigitaldownloads/easy-digital-downloads#4256]
Running the last version with 100% French translations some tabs don’t get translated even if they are in the .mo file.

http://d.pr/i/1frsL

**Comment by pippinsplugins** [comment]
Thanks for the headsup! We'll get it fixed!

**Comment by cklosowski** [comment]
Probably some markup in the way, I'll dig into it.

**Comment by mindctrl** [comment]
While we're looking at this, can we generalize the issue and hit some other textdomain issues? Specifically a customer can't translate this: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/2.5.6/includes/user-functions.php#L499  and there are some other strings in that file missing the domain.

**Comment by cklosowski** [comment]
@mindctrl yeah i'll update the title to reflect this.

**Comment by grappler** [comment]
I was having problems loading a translation. The reason was that I had the latest translation in `/wp-content/languages/plugins/` but EDD was loading the older file from the language folder in EDD.

@fxbenard Could that be the reason for your issue. Does your translation work when you delete the mo file from the EDD language folder?

**Comment by fxbenard** [comment]
@grappler Yes perfect

**Comment by pippinsplugins** [comment]
The loading had to be adjusted because of Language Packs. See here for a detailed break down of the order: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/easy-digital-downloads.php#L344

**Comment by grappler** [comment]
That would make sense if the translations are updated before every release but the last translation update in EDD was 5 months ago. I downloaded the de_CH translation from translate.w.org and added it to the langage pack folder. I suppose @fxbenard and I should move our more complete translations to the custom directory.

I may need to open a new issue for this but it is a bit confusing have the EDD translation in two places: translate.w.org and on transifex.

**Comment by pippinsplugins** [comment]
Language Packs have definitely made it more confusing.

Note: if you have a completed translation, please submit it to translate.wordpress.org :)

**Comment by fxbenard** [comment]
@grappler French is 100% in Glotpress, and uses the LP. I got confused with the new order with language packs - The opt-out doesn't seems to be working as soon as you reach 100% in GP once and the pack have been pushed. Edd translation is no more supported in TX, the project is closed (except for me) to translations. it's more confusing to see translators asking to translate it in TX than the translations being stuck in GP ;)

**Comment by grappler** [comment]
Ah, so it turns out that WP checks if the plugin has a translation file first before checking for language packs. So if EDD ships with old translations then the translation packs are worthless.

@fxbenard A temp solution that I have implemented is this small snippet.
```
add_filter( 'edd_languages_directory', function( $edd_lang_dir ) {
	$edd_lang_dir = WP_LANG_DIR . '/plugins/';
	return $edd_lang_dir;
} );
```

@pippinsplugins My proposed solution would be to regularly update the incomplete translations from translations.w.org before releases and remove translations that have been translated completly.

**Comment by fxbenard** [comment]
@grappler good workaround, thanks for the snippet.

The idea behind translate is to keep dev out of the process of translations, asking @pippinsplugins to update translations there will not work and there is no real process for doing it.
Also as long as there is no way for @pippinsplugins to know when a LP hits 100% once again it's kind of boring for him to check before each release which languages hits 100% or not and remove them from the languages folder.

**Comment by pippinsplugins** [comment]
These are the main issues I have with language packs. They're awesome for serving updates to users but they're difficult for plugin developers to keep up with.

@grappler We do try and pay attention to which ones are updated, but it's difficult for sure. Is the language pack that you're testing in this particular scenario 100% or partial?

**Comment by grappler** [comment]
I was looking at the de_CH translation which was a partial translation but the translation on the translation pack was further translated then the version included in the plugin.

Could you not use something like https://github.com/markoheijnen/grunt-glotpress to download all of the translations regardless if they are complete or not?

**Comment by pippinsplugins** [comment]
@grappler Yep! We can definitely do that. I didn't realize that tool existed.

**Comment by cklosowski** [comment]
@grappler I'm not able to get the WordPress.org translations to honor that `grunt-glotpress` task. It seems they aren't allowing access to the data properly. I'll keep trying to get it to pull in our translations.

**Comment by cklosowski** [comment]
Ok dug into this more, and it looks like the .org glotpress install is doing things slightly differently. The grunt task is looking for `data.translation_sets`, however the .org response doesn't have anything in `data.translation_sets`.

https://translate.wordpress.org/api/projects/wp-plugins/easy-digital-downloads

This leaves us with no translation files. I'll have to keep digging into this to see if there is a way to get to it, if we can for 2.6. Going to focus on a few other projects first.

**Comment by grappler** [comment]
Jetpack uses this export script https://github.com/Automattic/jetpack/blob/master/tools/export-translations.php

**Comment by cklosowski** [comment]
Thanks will look into that this week. See if it's something we can use.

**Comment by cklosowski** [comment]
@grappler This has the same problem, it's just a PHP script that pulls the same thing as the glotpress grunt task. Something is up with plugins not having any data in the `translation_sets`.

https://github.com/Automattic/jetpack/blob/master/tools/export-translations.php#L82

Since the API isn't returning any `translation_sets`, we have nothing to pull.

**Comment by cklosowski** [comment]
Found a few text domains that were still `edd`.

**Comment by cklosowski** [comment]
This should fix all the missing and incorrect Text domains. the Issue linked above by @mindctrl was fixed in a previous issue.

**Comment by cklosowski** [comment]
Ok I think i found the URL to pull in translations:
https://translate.wordpress.org/api/projects/wp-plugins/easy-digital-downloads/dev, that will pull our dev translations into EDD Core.

**Comment by cklosowski** [comment]
Ok @grappler I've got the grunt task working, took a little bit to figure out how to make it work the way we wanted to, do we need to include the .po AND .mo files to make this work for you guys?

**Comment by cklosowski** [comment]
Actually, I would love it if @fxbenard and @grappler could explain exactly what we can do to help out here. What files do we need to include...what %'s do we need to include, etc.

**Comment by grappler** [comment]
For me it is important that the files that the translations that are included are up to date. We could include all languages other than those that 100%.

**Comment by fxbenard** [comment]
Not sure pulling from dev is the best choice, as stable is used for the language pack and dev is often not 100% translated

**Comment by cklosowski** [comment]
@fxbenard Ok I can pull from stable, that'll work.

@grappler The system built that we are using is an upstream grunt task that only accepts a minimum_translation level. So we can't state to only include things less than 100. Just over a certain percentage.

**Comment by grappler** [comment]
@cklosowski If this PR gets accepted then it could work. https://github.com/markoheijnen/grunt-glotpress/pull/27

**Comment by cklosowski** [comment]
Yeah, awesome job submitting a PR for that. Keep me posted, if that get's merged we'll update our end to allow the maximum_percentage and we can then re-pull the necessary files.

**Comment by markoheijnen** [comment]
We are friends right? Saying upstream seems like there is a doubt when there is not 😉.
To be serious, Give me a day or two to look into it. You would have to add an additional task to delete all files first so languages that have more then 100% are removed.

**Comment by cklosowski** [comment]
@markoheijnen :) Appreciate the library, it's super handy. I'll be sure to get a task written to delete them.

**Comment by fxbenard** [comment]
FYI: in WordPress 4.6, the order will be turn around. First language pack, then the plugin languages folder.
