### ISSUE TITLE
Email address on checkout not validating

### ISSUE THREAD

**Issue by akyusa01** [easydigitaldownloads/Easy-Digital-Downloads#4258]
https://secure.helpscout.net/conversation/166426421/26769/?folderId=180499

I have replicated the issue. 

On checkout user can enter me@me.coma. When admin edits user under WP user screen, email address is updated, but editing the customer will not fix the email address, it will remain with the original .coma.

**Comment by cklosowski** [comment]
@akyusa01 This is by design, currently we only update the User when the customer is updated, we do not update the customer when the user is updated.

#3364.

We've got an open issue #4067 for this already.

**Comment by cklosowski** [comment]
Am I missing something else here though?

**Comment by akyusa01** [comment]
Closing since #4067 is open and active.
