### ISSUE TITLE
Overflow non existing sessions caused by cronjob

### ISSUE THREAD

**Issue by markoheijnen** [easydigitaldownloads/easy-digital-downloads#4263]
I'm seeing an overflow of non existing sessions in `notoptions` cache key due to a manual cronjob that is getting run every minute. Instead of using WordPress to call it, I decided to build a small PHP script that uses curl to make the calls instead.

I currently send an own created cookie so for me it's fixed. I do wonder if others have seen this before so thats why I created this ticket. A solution in EDD would be to not load the session when DOING_CRON.

I also wondered how this would work in a normal situation since all sessions will end up in `notoptions` which is autoloaded. One really small part of the fix is to move `read_data` inside the isset Cookie check inside the `WP_Session` class to delay the get_option call.

Also in my case I don't even use EDD on the frontend yet, so maybe we could use a magic get method to retrieve only the session when needed?

**Comment by pippinsplugins** [comment]
@markoheijnen Could you show us an example of your cron job?

**Comment by markoheijnen** [comment]
https://gist.github.com/markoheijnen/bad7e461bc41d3990f40. Rule 17-19 was added to prevent it.

**Comment by pippinsplugins** [comment]
I think I just saw this same thing happen on one of our sites.

**Comment by cklosowski** [comment]
I rather like the idea of using `DOING_CRON` to detect when we shouldn't load sessions. I think that would help out quite a bit. I think paired with #4284 we could see some real improvements.

**Comment by pippinsplugins** [comment]
This has not been seen again. I'm going to close as invalid now.
