### ISSUE TITLE
Recount Stats - Reset Store Not Working

### ISSUE THREAD

**Issue by akyusa01** [easydigitaldownloads/Easy-Digital-Downloads#4264]
Resetting store data does not remove the data from the edd_license_log custom post type.

https://secure.helpscout.net/conversation/167111421/26888/?folderId=180499

**Comment by pippinsplugins** [comment]
@akyusa01 This actually needs to be logged on Software Licensing.

Logged: https://github.com/easydigitaldownloads/EDD-Software-Licensing/issues/436
