### ISSUE TITLE
Free download in completely free download site causes memory exhaustion

### ISSUE THREAD

**Issue by polevaultweb** [easydigitaldownloads/Easy-Digital-Downloads#4270]
This error is occurring since EDD 2.5.

When a free download is triggered, in a site that only has free downloads, `update_status()` (since 2.5) results in a memory exhausted fatal error. 

This is a site that has had 200k free downloads (edd_payments). I've done some digging and it looks like `edd_get_total_earnings()` will always check the option `edd_earnings_total`, and if it is zero it will try and calculate it from the db. However, that option will always be zero for this site. But during its calculation of getting payments it silently fails eventually from memory issues.

I've fixed the issue in the short term by manually updating the `edd_earnings_total` to 1, but wanted to bring the issue to your attention :)

**Comment by pippinsplugins** [comment]
Thanks for the headsup! We'll get it fixed.

**Comment by pippinsplugins** [comment]
We could fix this by changing `if( ! $total ) {` to a strict type check.

**Comment by polevaultweb** [comment]
And making sure you pass `false` as the default to `get_option()` in the line above

**Comment by polevaultweb** [comment]
Happy to test a PR on this

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
That should do it!
