### ISSUE TITLE
Bug in Email download links

### ISSUE THREAD

**Issue by profclimber** [easydigitaldownloads/Easy-Digital-Downloads#4272]
There is somehow a bug in the download links.

This should be the link: https://www.photohanke.nl/index.php?eddfile=767%3A705%3A1%3A1&ttl=1455052894&file=1&token=4e82cb981dae583cf9e4a908156c9dc8

And somehow in the email the token changes: https://www.photohanke.nl/index.php?eddfile=767%3A705%3A1%3A1&ttl=1455050022&file=1&token=b836fd2e8ad833fdef51a95bc21c6889&utm_source=email&utm_medium=email

any ideas?

**Comment by pippinsplugins** [comment]
@profclimber See https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/3981
