### ISSUE TITLE
Check if price is set before saving

### ISSUE THREAD

**Issue by pdewouters** [easydigitaldownloads/Easy-Digital-Downloads#4282]
It would be good to have a pre-save check to verify if a price has been set, and if not show a message "are you sure you want to publish this download with a price of 0"
Could be a setting/filter/plugin

**Comment by pippinsplugins** [comment]
@pdewouters For some cases, yes, I would agree, but we actually have a remarkably large number of users that use EDD with free products, so a notice like that would probably be a hassle.

**Comment by pdewouters** [comment]
Understandable. I'll add it in separately then.

**Comment by pippinsplugins** [comment]
:+1:
