### ISSUE TITLE
Session cookies are created on every page load

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/easy-digital-downloads#4284]
We've had two reports recently about the fact that a session cookie gets created on every page load, making it hard to cache. One came through a Pagely customer and another was from Pressjitsu.

One report:

> The use of sessions in EDD prevents any page from being cached because it's issuing a unique cookie to every visitor. It would be best if EDD initialized this unique session ONLY when the user has taken any sort of action, like add something to the cart. That way, the majority of the users can enjoy fast cached responses throughout the whole website, while those with intent to buy something will get their unique cookies.

Other report:

> The site is setting edd_wp_session cookies for every visitor, which makes thing a lot more painful, as nothing could be cached at the Nginx level & every request is dynamic.

If you use `EDD_USE_PHP_SESSIONS` set to false and fall back to `WP_Session`, you always get a cookie because it creates one in `__construct()`. [Link](https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/2.5.6/includes/libraries/class-wp-session.php#L105).

**Comment by cklosowski** [comment]
We've got to make sure if we make any changes to this, that it doesn't break extensions that require the sessions, things like User History.

**Comment by pippinsplugins** [comment]
Let's try and resolve this in a point release that has almost nothing else in it. For now, milestoning for 2.5.9

**Comment by cklosowski** [comment]
looking into this I can almost get there. I can get sessions/cookies to only be created when adding to the cart, however for some reason the cookies don't carry over to page refreshes. All AJAX requests know about the current cart contents, but the front of site has no idea about it, which is strange.

**Comment by chriscct7** [comment]
This is going to break any extensions that rely on EDD sessions from the sound of it outside of the normal checkout flow

**Comment by pippinsplugins** [comment]
@chriscct7 Yes it will and we'll have to deal with that. Unfortunately, breaking caching on _every_ single page of _every single_ EDD site is far worse.

**Comment by cklosowski** [comment]
Every time I try and get this done, something major breaks in the cart system. I've taken a few stabs at it between getting other issues resolved. I'm going to punt (for now) and we can look to get this in a future release.

It's not that it's not important, it's just important to get right.

**Comment by bmoredrew** [comment]
Thanks for the effort everyone. Is there something we can do on an individual site level? My client has a pretty large site in terms of traffic that just falls over on Pagely when we try to implement EDD, so all the pieces are in place just kind of sitting there for a one day hopeful fix/use.

**Comment by cklosowski** [comment]
Drew,

At this point, we've already released some restrictions that stop it from
loading on the RSS feeds. On the EDD Site specifically we've stopped it
from starting sessions on the homepage with something like the following:
```
function eddwp_maybe_start_session( $start_session ) {
if ( '/' == $_SERVER['REQUEST_URI'] ) {
$start_session = false;
}
return $start_session;
}
add_filter( 'edd_start_session', 'eddwp_maybe_start_session', 10, 1 );
```

Chris Klosowski
cklosowski@gmail.com
@cklosowski

**Comment by pippinsplugins** [comment]
@bmoredrew One major improvement you could make is to prevent sessions from starting on specific pages, such as pages that will never have an add to cart button on them: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4429

**Comment by mindctrl** [comment]
This issue was mentioned to one of our customers by Pagely again. The sessions are preventing her site from being cached.

**Comment by pippinsplugins** [comment]
@mindctrl go ahead and show her how to exclude certain pages (such as home if possible) from starting caches.

**Comment by pippinsplugins** [comment]
WooCommerce 2.5 included a complete rewrite of their session manager. They originally used a very similar system to ours. Let's look at what they did to see if that will help.

https://woocommerce.wordpress.com/2015/10/07/new-session-handler-in-2-5/

**Comment by sunnyratilal** [comment]
Woo use a custom table to store this data and have a custom implementation built which handles sessions via this new table: https://github.com/kloon/woocommerce-large-sessions

**Comment by bcole808** [comment]
+1 to address this because EDD currently breaks nginx caching on every single page load for our site. We have a lot of pages that have nothing to do with store purchases, so this is important for our site. 

The quick fix I'm implementing is to add the following filter which prevents a session from being started unless the request is related to purchasing EDD products. 

On our site, I believe that the three rules below capture all possible requests that are related to product purchases (We are using very few EDD extensions, however). In case I've overlooked something.... please let me know! 

```php
function restrict_edd_session_creation($use_session) {

    // Allow session if the user has an item in their cart
    if ( isset( $_COOKIE['edd_items_in_cart'] ) ) {
        return $use_session;
    }

    // Allow session if this is an EDD ajax request
    if ( defined('DOING_AJAX') && DOING_AJAX && false !== strpos($_REQUEST['action'], 'edd_') ) {
        return $use_session;
    }

    // Allow session if this is a checkout/invoice/payment page
    if ( false !== strpos($_SERVER['REQUEST_URI'], '/checkout') ) {
        return $use_session;
    }

    // Otherwise, no EDD sessions allowed!
    return false;

}

add_filter('edd_start_session', 'restrict_edd_session_creation');

```

**Comment by pippinsplugins** [comment]
That looks like it may work as a solution for this. Nice.

**Comment by sunnyratilal** [comment]
PR opened and ready for testing

**Comment by pippinsplugins** [comment]
Removed PR and testing labels since the PR needs adjustment.

**Comment by cklosowski** [comment]
This is having the same problem I saw before, I can add to the cart, but then when I go to the checkout, it's empty. The AJAX request seems to get the session, but the browser doesn't seem to know about the session that was created during the AJAX request.

**Comment by sunnyratilal** [comment]
Tested and working _very_ well! Nice work @cklosowski 👍

**Comment by pippinsplugins** [comment]
I will test tomorrow.

**Comment by pippinsplugins** [comment]
Just pushed a small change to fix sessions not starting when custom add to cart links are used on pages other than the checkout, such as `site.com/?edd_action=add_to_cart&download_id=23`

**Comment by pippinsplugins** [comment]
Another item we'll need to take care of is the `EDD_USE_CART_COOKIE` constant and `edd_use_cart_cookie` filter. We introduced those in 2.5 as a method for site owners to disable the `edd_items_in_cart` cookie that broke caching on sites.

We needed to give site owners a way to remove that cookie since our sessions were _always_ getting started. Now that we have session starting working properly, we need to remove the option to disable the cart cookie since disabling it _completely_ breaks sessions.

I'm going to:

1. Make the constant and filter not do anything
2. Show deprecated notices with link to the dev blog post (which I'm writing later this week) on any site that is using the constant or filter to disable the cookie

**Comment by pippinsplugins** [comment]
Deprecation added for the constant and filter.

**Comment by pippinsplugins** [comment]
Dev blog post drafted: https://easydigitaldownloads.com/development/?p=170

**Comment by pippinsplugins** [comment]
This is triggering a fatal error when `EDD_USE_PHP_SESSIONS` is defined as `false`.

[20-Jan-2017 14:53:11 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get_queried_object() on null in /app/public/wp-includes/query.php:45
Stack trace:
#0 /app/public/wp-content/plugins/easy-digital-downloads/includes/class-edd-session.php(349): get_queried_object()
#1 /app/public/wp-content/plugins/easy-digital-downloads/includes/class-edd-session.php(78): EDD_Session->should_start_session()
#2 /app/public/wp-content/plugins/easy-digital-downloads/easy-digital-downloads.php(150): EDD_Session->__construct()

**Comment by sunnyratilal** [comment]
Looks like `get_queried_object()` is called way too early - before `WP_Query` is set up.

Currently, when `EDD_USE_PHP_SESSIONS` is `false`, we call `EDD_Session::init` on `plugins_loaded` but when `true` it's loaded on `init`.

**Comment by cklosowski** [comment]
This seems to resolve it being called to early, see if that works @sunnyratilal @pippinsplugins

**Comment by spencerfinnell** [comment]
@cklosowski That won't work with the default permalink structure.

**Comment by cklosowski** [comment]
@spencerfinnell well for  few major versions, default has been altered from the query string params. I looked at `url_to_postid` but it's too early for that as well.

**Comment by pippinsplugins** [comment]
@cklosowski It's been a while since I played with but could we load EDD_Session on `init` even when EDD_USE_PHP_SESSIONS is `false`?

**Comment by cklosowski** [comment]
@pippinsplugins I'll give that a shot to see if that works.

**Comment by spencerfinnell** [comment]
That was going to be my next question as well. Seems like that would allow for the fewest special cases.

**Comment by cklosowski** [comment]
@pippinsplugins @spencerfinnell honestly, this seems to be working fine, I'll commit it up so we can have some more people test it out.

**Comment by pippinsplugins** [comment]
This appears to work perfectly for me!

Something did just occur to me: we will likely break any plugin that sets EDD session data before items are added to the cart.

@cklosowski @sunnyratilal could you both do some testing to confirm that session vars can still be set before items are added to the cart? We may need to call `EDD()->session->set_cart_cookie( true );` any time something is added to the session instead of just when adding items to the cart.

**Comment by cklosowski** [comment]
Even doing that isn't seeming to work. @sunnyratilal can you give it a shot? I just used this to determine if it was working:
```
function test_stuff() {
	if ( isset( $_GET['test-stuff'] ) ) {
		EDD()->session->set( 'testing-cookie', 'testing-value' );
	}
        var_dump(EDD()->session->get( 'testing-cookie' );
}
add_action( 'init', 'test_stuff' );
```

Basically visit with `?test-stuff=true` in the URL, and then see the cookie saved there in the session....then remove the query string, and visit the same page. My guess is, it's gone for you too?

**Comment by sunnyratilal** [comment]
@cklosowski the cookie is gone when removing the query string

**Comment by cklosowski** [comment]
Ok that sounds like what I was seeing too @sunnyratilal.

@pippinsplugins going to try and have to think through this, honestly, I'm ok if this doesn't make Beta 1....but it HAS to make Beta 2.

**Comment by pippinsplugins** [comment]
>>>honestly, I'm ok if this doesn't make Beta 1....but it HAS to make Beta 2.

Nope, this will be in beta 1 or not in at all.

**Comment by pippinsplugins** [comment]
It's too important to the fundamental foundation of every EDD store to not have in beta 1.

**Comment by cklosowski** [comment]
Then I need someone to take over on it, Ive got too much time to invest
finishing up a few other things to have it ready in time, and frankly I'm
out of ideas on where to take it without rewriting the whole session
handling.

**Comment by cklosowski** [comment]
Ok, I determined why my test wasn't working, and it actually affects many things...anything that tries to run `EDD()->session->set()` will typically run on `init` or later, but this means that `headers_sent()` will return true, including things like Discounts Pro, Cart Resuming, and SL actions.

We cannot run `$_COOKIE['cookie-name']` on things after the headers were sent. Which means, that we cannot use the method to always set the `items-in-cart` cookie whenever `set()` is run.

We'll have to find another way around this.

**Comment by pippinsplugins** [comment]
:(

**Comment by sunnyratilal** [comment]
Closing this in favour of #5418 as this requires a fundamental rebuild to how sessions work.
