### ISSUE TITLE
Creating Composer site stack, including Easy Digital Downloads as a wordpress-plugin type

### ISSUE THREAD

**Issue by corvannoorloos** [easydigitaldownloads/Easy-Digital-Downloads#4285]
Attempting to create a [site stack](http://composer.rarst.net/recipe/site-stack) with Composer I was wondering if it would be possible to change Easy Digital Downloads' `composer.json` type to `wordpress-plugin` instead of `project` and require [`composer/installers`](https://github.com/composer/installers)?

Could someone tell if this would be the best way to accomplish this (unsure if this would break any add-ons)? Preferably without needing WordPress Packagist.

**Comment by pippinsplugins** [comment]
I don't know enough about composer to know the `why` here, so educate me :)

**Comment by michaelbeil** [comment]
I believe @corvannoorloos wants to change `"type": "project",` to `"type": "wordpress-plugin",` and add `"require": { "composer/installers": "*" }` which tells composer to load the custom installers.

**Comment by corvannoorloos** [comment]
> ...and add `"require": { "composer/installers": "*" }` which tells composer to load the custom installers.

I would prefer the default `"composer/installers": "~1.0"` instead of its latest, but yes. Exactly this.

> I don't know enough about composer to know the `why` here, so educate me :)

No legend here as well, but in short Composer is dependency manager especially for PHP.

AFAIK after this change it would be possible not only to include Easy Digital Downloads using [WordPress Packagist](http://wpackagist.org/) (a wordpress.org mirror for Composer), which is already possible, but also to grab the development version directly from GitHub **and move it into the correct directory** and version control a **complete** site from a single file.

**Comment by michaelbeil** [comment]
I updated the composer.json @corvannoorloos. Can you test #4287?

**Comment by corvannoorloos** [comment]
Works for me :+1: (but I'm certainly not all knowledgeable)

Here's my site's `composer.json`. Note the [`dev-` prefix](https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository) for including a branch:
```json
{
   "name": "corvannoorloos/example-website",
   "repositories": [
      {
         "type": "git",
         "url": "https://github.com/michaelbeil/Easy-Digital-Downloads"
      }
   ],
   "require": {
      "johnpbloch/wordpress": "^4.4.2",
      "easydigitaldownloads/Easy-Digital-Downloads": "dev-composer-additions"
   },
   "extra": {
      "installer-paths": {
         "wp-content/plugins/{$name}": [
            "type: wordpress-plugin"
         ]
      }
   }
}
```

**Comment by michaelbeil** [comment]
Good deal @corvannoorloos.

**Comment by pippinsplugins** [comment]
@corvannoorloos I know what Composer is, I just wasn't aware of the `wordpress-plugin` categorization specifically or what effect that had.

**Comment by corvannoorloos** [comment]
@pippinsplugins I thought as much :)

**Comment by corvannoorloos** [comment]
Not entirely related to the original question, but Composer is suggesting its [name](https://getcomposer.org/doc/02-libraries.md#every-project-is-a-package) to be lowercase.
```json
{
  "name": "easydigitaldownloads/easy-digital-downloads",
  "type": "wordpress-plugin",
}
```

**Comment by michaelbeil** [comment]
I changed the name with reference to the Composer convention @corvannoorloos :smile:. See https://github.com/michaelbeil/Easy-Digital-Downloads/commit/360129823c7a14c14969e50607fed14f367fcca9.

**Comment by corvannoorloos** [comment]
@michaelbeil thanks :)
