### ISSUE TITLE
tags name do not appear in downloads detail page!

### ISSUE THREAD

**Issue by davood206** [easydigitaldownloads/Easy-Digital-Downloads#4288]
why Tags are not appear in download detail page?
when I add several tags to download both from front end and backend, only semicolons between tags appear.  like this  :  , , , , ,
why name of tags don't appear, I changed several themes but nothing happened.

Thank YOU.

**Comment by mindctrl** [comment]
@davood206 please open a support ticket here: http://easydigitaldownloads.com/support/
