### ISSUE TITLE
New User Notification Email URL Not Linked

### ISSUE THREAD

**Issue by DevinWalker** [easydigitaldownloads/Easy-Digital-Downloads#4291]
It would be nice to have this URL clickable / linked:

![2-12-2016 3-42-38 pm](https://cloud.githubusercontent.com/assets/1571635/13023701/2bcfdc4c-d1a0-11e5-888c-3ea02c06a1bf.png)

**Comment by pippinsplugins** [comment]
I agree, let's link it. I see you committed a fix. Could you drop that in a PR?

**Comment by pippinsplugins** [comment]
Nevermind, you already did :)
