### ISSUE TITLE
Inline documentation often uses "object" when name of class would be more useful.

### ISSUE THREAD

**Issue by Shelob9** [easydigitaldownloads/Easy-Digital-Downloads#4296]
For example in the main EDD singleton wrapper, [the return is documented as `object`](https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/easy-digital-downloads.php#L434) but phpStorm doesn't know what object that is so, it's not useful to me...

![Necessary Meme]
(http://apimeme.com/meme?meme=Brace+Yourselves+X+is+Coming&top=Brace+Yourself&bottom=Pull+Requests+Are+Coming)

**Comment by pippinsplugins** [comment]
Thanks @Shelob9 !
