### ISSUE TITLE
Create edd_sanitize_key

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/Easy-Digital-Downloads#4299]
With https://github.com/easydigitaldownloads/Easy-Digital-Downloads/commit/1b0fb2ef891a0d77fe07a8d085099324d4e679bd taken from #3921, we've inadvertently broken extensions that have uppercase letters and urls in their keys (like payment icons).

We should introduce an `edd_sanitize_key` that mimics `sanitize_key` except for the `strtolower` will be removed and it needs to support `/` and `.` characters

**Comment by mindctrl** [comment]
@cklosowski this is working for me. Maybe we can get a few more eyes on it just to be sure. @SDavisMedia @pippinsplugins

**Comment by pippinsplugins** [comment]
Looks great to me.
