### ISSUE TITLE
Introduce customer meta table

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#4311]
We really need to introduce a customer meta table that allows us to store various (arbitrary?) pieces of information for customer records.

This can be based off of how we did it for AffiliateWP: https://github.com/AffiliateWP/AffiliateWP/issues/537

One example of something that relies on a customer meta table: storing the customer ID from Stripe that is associated with the EDD customer.

**Comment by cklosowski** [comment]
:heart:

**Comment by crsmoore** [comment]
You already know how much I would love this one. :+1:

**Comment by cklosowski** [comment]
Going to make a checklist of things I See (feel free to alter if needed)
- [ ] Update `uninstall.php` with any tables we need to remove, including the new `customermeta` table.

Ok only one thing I saw so far. Looking good. I say let's get the uninstall stuff written and merge this in so we can start knocking out some of the dependent issue, and further refine it after we use it a bit.

**Comment by pippinsplugins** [comment]
Merged into `release/2.6`. Closing this out. We will re-open if needed as we work with it in related issues.

**Comment by SDavisMedia** [comment]
Instructions from @pippinsplugins to reopen this and report that when switching to branch `issue/3755` (support additional emails), I'm facing this output on the custom management table: http://glui.me/?i=9zgggk8hurvmmnz/2016-05-25_at_11.44_AM_(1).png/

**Comment by pippinsplugins** [comment]
@cklosowski I think we need to set up an automatic upgrade system that triggers anytime the `EDD_VERSION` constant is changed, similar to how we did it in AffiliateWP: https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/admin/class-upgrades.php

That way we can make database changes without requiring users click a link to run it.

**Comment by cklosowski** [comment]
So like we did with Recurring Payments as well.

**Comment by pippinsplugins** [comment]
@cklosowski take a look at #4616

**Comment by cklosowski** [comment]
@pippinsplugins manually reset my `edd_version` option, delete the customermeta table and then checked out this PR. Upon a refresh, table was created and the version was updated.

:+1:

**Comment by cklosowski** [comment]
We will just need to make sure when we release the beta that we update the `EDD_VERSION` constant to be `2.6-beta1` so that the routines trigger.
