### ISSUE TITLE
FES - hide blank fields

### ISSUE THREAD

**Issue by kiarashi** [easydigitaldownloads/Easy-Digital-Downloads#4312]
Inside FES there's an option called: Show custom fields on the download?
With the latest version, when the option _"Allows widgets to output data from this field, as well as shows this field's value when the FES setting Show Custom Meta is on."_ is enabled but the field is blank, the field is still visible on the frontend.

Please tweak the code a little for all your fields so that empty fields are hidden even if the option mentioned above is enabled.

For example in edd-fes/classes/fields/radio.php

```
<?php if ( $single ) { ?>
		<table class="fes-display-field-table">
		<?php } ?>

		<?php if( ! empty( $value ) ) { ?> // add this line
			<tr class="fes-display-field-row <?php echo $this->template(); ?>" id="<?php echo $this->name(); ?>">
				<td class="fes-display-field-label"><?php echo $this->get_label(); ?></td>
				<td class="fes-display-field-values">
					...
				</td>
			</tr>
		<?php } ?>
```

**Comment by pippinsplugins** [comment]
@kiarashi This GitHub repository is for the core Easy Digital Downloads plugin only. Please send reports for extensions to EDD support: https://easydigitaldownloads.com/support
