### ISSUE TITLE
Searching payments by user id not returning results

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/Easy-Digital-Downloads#4320]
When you search the payments with a numeric value, it should be doing a search based on the purchase user id, however no results are showing. The counts are working correctly, just no results are being put on the page.

**Comment by cklosowski** [comment]
Looked into this further...our `user` search requires `user:` to be the prefix...when finding payment, however the payment counts looks for just an numeric ID as the query for a user...where as in the payments query, a simple numeric string is searching by payment ID...

**Comment by cklosowski** [comment]
Ok, so dug into this...and I think we have to leave this a 'little' broken, and here's what the expected results should be. Replace all instances of `#` as an `integer`
To search for a user `user: #`. This will generate the proper list of payments and pagination (and counts) for all payments for that user ID.
To search for a single payment `#`. This will return the result of that single payment, but the counts will actually read as all payments of the matching user ID...there's no way around this without breaking backwards compatibility with `edd_payment_counts()`, which is VERY risky.

This means, if I search for `123`, I'll get payment ID `123` listed in my list table, but the counts and pagination will be based off all the payments found for user `123`. Keep in mind, we aren't returning this data or showing it, or anything more than using it for the pagination, due to the fact that `edd_payment_counts()` uses an `integer` search as a `user id`, where as `EDD_Payment_Query::search()` uses an `integer` as a `__posts_in` search.

**Comment by cklosowski** [comment]
@mindctrl @SDavisMedia are you guys good with this conclusion?

**Comment by SDavisMedia** [comment]
@cklosowski haha sucky choice to make but I like leaving it somewhat broken. 

To be clear, when searching just `#`, there's no way at all to keep it from returning purchases by that user ID right?

**Comment by cklosowski** [comment]
@SDavisMedia Currently searching for a number only will return that payment ID, not the user's payments...you need `user: #` for that. When initially debugging, I looked at the count function first and assumed that a numeric search meant search Users...but after I dug in, I found that in the actually query for payments it means search for payments with that ID, whereas the counts use the number search as user.

**Comment by SDavisMedia** [comment]
@cklosowski I get that. And I'm cool with leaving it "broken" like that. What I'm saying is when you search `#` and we get the results for that payment ID, even though the user's payments whose ID matches that integer are not literally displayed in the table, is it possible to remove them from the count? So essentially making it a little less broken and possibly avoiding a high count and maybe pagination when there's really only one result showing?

**Comment by SDavisMedia** [comment]
That's probably a super edge case anyway so I guess it doesn't matter much.

**Comment by cklosowski** [comment]
@SDavisMedia No, we cannot, that's the bug...if we make that work, we'd end up breaking the `edd_payment_count()` for anyone who's using it expecting a numeric search to be a user ID instead of a payment ID.

**Comment by SDavisMedia** [comment]
Okay so I take it that means there are scenarios where searching `#` for a user happens besides at the payment record table listing? Does this happen in code scenarios or something? I asked because it doesn't matter if it breaks user ID searching if it doesn't visually display data anyway.

**Comment by cklosowski** [comment]
Yes, there are areas where we use `edd_payment_counts()` for getting the number of payments for a user Id.

**Comment by SDavisMedia** [comment]
Gotcha! Yup, I'm all good with that then. I was only considering the table listing scenario at first. Makes perfect sense to leave it as is all things considered.

**Comment by mindctrl** [comment]
@cklosowski looks good to me.
