### ISSUE TITLE
Better errors when using "Forced" with deliverables outside wp-content.

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#4321]
**The Issue:**
If a store owner has done all of the following, the file a customer downloads will be corrupted:
1. Set File Downloads to be "Forced" in "Downloads" > "Settings" > "Misc" > "File Downloads"
2. Have uploaded a deliverable-file outside wp-content (using FTP or other non-standard way)
3. Have entered the URL to that deliverable-file into the "Files" Metabox on the "Edit Download" screen

The error message can sometimes be found in the code of the downloaded deliverable file itself and points here: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/744243f55420578bff5e69052dbbdf58b896749e/includes/process-download.php#L165

**The Reason:**
Files hosted outside/above the "wp-content" directory need to use the **absolute** server path instead of the URL.

**Potential Solutions** 

Option 1: Fix it.
This solution would involve making files hosted outside "wp-content" able to be properly downloaded using their URL. Perhaps by guessing/converting the URL to a server path. The correct way to do this is currently unknown and would require brainstorming/testing.

Option 2: Better Errors:
In this proposed solution, we would not make the downloads work in this case, but output better errors for the Site Owner and for the Customer so they understand that what they are setting up will not work correctly. 

Error to the Site Owner:
@chriscct7 has proposed to use javascript validation to make sure that the URL is inside wp-content and display an error if not.

Error to the Customer:
@pippinsplugins has proposed returning proper 404 Headers to the customer if the file is not found. This would make it much easier to debug and troubleshoot when dealing with this issue.

**Comment by pippinsplugins** [comment]
Problems with symlinked filed downloads could be improved through better error messages too: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/4328

**Comment by mintplugins** [comment]
This is one of the error messages that has been found during the process of finding this bug:

`PHP Warning: filesize(): stat failed for https://github.com/{redacted}/natural-lite/archive/master.zip in /wp-content/plugins/easy-digital-downloads/includes/process-download.php on line 199`

See full discussion leading to this ticket here:
https://eddwp.slack.com/archives/edd-support/p1455901084001739

**Comment by mintplugins** [comment]
That type of file will now redirect instead of using forced. This change was made here: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4329

I believe this is now resolved through 4329. We can close this and re-open if customer complaints come through. I haven't seen any for a long while though.
