### ISSUE TITLE
100% discount when using taxes disables purchase

### ISSUE THREAD

**Issue by samikeijonen** [easydigitaldownloads/Easy-Digital-Downloads#4325]
I'll try to explain an issue that I noticed.

1. Enable taxes.
2. Send user 100 % discount.
3. User haven't logged in or is new user.
4. User enters 100 % discount code on checkout page.
5. Total sum gets to 0$ as it should be.
6. User enters emails address and first name.
7. User click Purchase button and nothing happens. User can't complete the purchase.

This is because when taxes are enabled there are required billing details fields: city, zip code, country and state. And when user enters 100 % discount code billing details fields are hidden using `display: none`. Therefore user can't enter those details when using 100 % discount code. 

Hope this makes sense. I tested this with Test and Stripe Payment gateways.

**Comment by pippinsplugins** [comment]
@samikeijonen Thanks. This is the second report of this I've seen. We'll dig into it.

**Comment by pippinsplugins** [comment]
Hmm, I just tested this and did not replicate the problem. The purchase went through fine.

**Comment by pippinsplugins** [comment]
@samikeijonen Does this happen with only EDD activated?

**Comment by samikeijonen** [comment]
I had only EDD and Stripe activated when testing.

**Comment by pippinsplugins** [comment]
@samikeijonen Still works fine for me. Could I get screenshots of all of your settings?

**Comment by cklosowski** [comment]
I'm not able to replicate this. I've used Stripe and EDD, taxes enabled, 100% discount, and the purchase works fine. I've set stripe as the only payment gateway.

**Comment by samikeijonen** [comment]
Here is screenshot of tax setting page:

![screenshot 2016-02-23 08 57 00](https://cloud.githubusercontent.com/assets/1820415/13243972/804afd38-da0b-11e5-9545-53ee4b404494.png)

And here is screenshot for payment gateway settings:

![screenshot 2016-02-23 08 59 52](https://cloud.githubusercontent.com/assets/1820415/13244023/d3ba6382-da0b-11e5-9207-db72bcac55af.png)

Also one of my customer reported the same issue so I might not be imagining this after all:)

**Comment by pippinsplugins** [comment]
I've replicated this on a customer's site. It's happening because the following JS errors are getting thrown:

```
An invalid form control with name='card_city' is not focusable.
An invalid form control with name='card_zip' is not focusable.
```

**Comment by pippinsplugins** [comment]
I've tracked this down. It's due to the `required` attribute we added recently in #3920

See http://stackoverflow.com/questions/22148080/an-invalid-form-control-with-name-is-not-focusable

HTML5 freaks out if you have a required field that is not able to be focused.

When hiding the address and gateway fields, we need to remove all `required` attributes.

**Comment by cklosowski** [comment]
@pippinsplugins @samikeijonen can you guys test this out? `issue/4325` branch should do the trick and just make sure you aren't using minified scripts.

**Comment by pippinsplugins** [comment]
Looks good to me.

@samikeijonen Could you confirm it fixes the issue for you?

**Comment by samikeijonen** [comment]
I'll check it out!

**Comment by samikeijonen** [comment]
Works for me.

**Comment by pippinsplugins** [comment]
:+1:
