### ISSUE TITLE
EDD Download Link Problem 

### ISSUE THREAD

**Issue by niamulrox** [easydigitaldownloads/Easy-Digital-Downloads#4326]
Hi,
When anyone purchase there its sending a email with download link. I had tested that in several browser its downloadable from any browser even without login to account. But its very disgusting as If some one share his download link then people will download product from my server with his link with out any cost. 

You should check user session and if it same user then able to download but from different browser or any user who did not purchase will not be able to download with the product download link. 

From MISC setting I already set to Forced ... But the problem still exists and I think its a BIG.

Thanks

**Comment by pippinsplugins** [comment]
@niamulrox Please open a support ticket: https://easydigitaldownloads.com/support

We will be happy to help but Github is only for development tracking; not support. Thanks!
