### ISSUE TITLE
Symlinked file downloads result in 0 byte downloads because of 400 forbidden

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#4328]
The `Symlink File Downloads` option combined with `Download Method` being set to `Redirect` is causing 0 byte / corrupted file downloads because the server is returning a 400 Forbidden error when attempting to send the file to the browser.

@cklosowski and I have both replicated the problem and several users have reported that disabling symlink file downloads also solves the problem.

The location of the file on the server does not appear to affect the outcome.

I have also tested on several versions of PHP with the same results.

We've had numerous reports of this problem in the last few days. There appears to be an influx of reports since 2.5.8/9 was released. Number of tickets reporting the issue have been logged on Trello: https://trello.com/c/Qbv5Kb5d/29-zero-byte-file-downloads

Possibly introduced with changes for #4246

**Comment by pippinsplugins** [comment]
@SDavisMedia @mindctrl @mintplugins We need to get this tested extensively please.

Please test the following download file configurations:

Download Method: Redirect
Symlinks: Disabled

- Dropbox File Store (with and without forced download settings)
- Public Dropbox link (copied straight into product)
- Amazon S3
- Regular upload to EDD folder
- Regular upload to media library
- Relative path to file in wp-content
- Absolute path to file above wp-content

Download Method: Redirect
Symlinks: Enabled

- Dropbox File Store (with and without forced download settings)
- Public Dropbox link (copied straight into product)
- Amazon S3
- Regular upload to EDD folder
- Regular upload to media library
- Relative path to file in wp-content
- Absolute path to file above wp-content

Download Method: Forced

- Dropbox File Store (with and without forced download settings)
- Public Dropbox link (copied straight into product)
- Amazon S3
- Regular upload to EDD folder
- Regular upload to media library
- Relative path to file in wp-content
- Absolute path to file above wp-content

**Comment by mindctrl** [comment]
#### Download Method: Redirect
**Symlinks: Enabled**
All work fine.

**Symlinks: Disabled**
All work fine.

#### Download Method: Forced
**Dropbox public pasted link, force download off and on:** throws a notice: `PHP Warning:  filesize(): stat failed for https://www.dropbox.com/s/uoqjkbv0i5i4dzu/test.png?dl=1 in /Users/jp/Sites/edd-sl/wp-content/plugins/easy-digital-downloads/includes/process-download.php on line 199`.
File still downloads.

**Dropbox selected from media picker, force download off and on:** works

**Relative path to file in EDD protected folder, throws notice: (you didn't ask to test this, but I did anyway)** `You don't have permission to access /wp-content/uploads/edd/2015/09/huckster-0.11.zip on this server.`

**Relative path to file in wp-content folder:** works

**Absolute path to file above wp-content:** works

**Comment by pippinsplugins** [comment]
For filesize issue, see related https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/4329

**Comment by mintplugins** [comment]
## Download Method: Redirect Symlinks: Disabled
	
•	**Dropbox File Store**
•	With Forced in Dropbox Settings: **Successfully Downloads as Forced**
•	Without Forced in Dropbox Settings: **Successfully Downloads as Redirect**

•	Public Dropbox link (copied straight into product) - **Successfully Downloads as Redirect**
•	Amazon S3 - **Successfully Downloads as Redirect**
•	Regular upload to EDD folder - **Successfully Downloads as Redirect**
•	Regular upload to media library - **Successfully Downloads as Redirect**
•	Relative path to file in wp-content - **Successfully downloads as Redirect**
•	Absolute path to file in wp-content -** Successfully downloads as Forced**
•	Relative path to file above wp-content - **Successfully downloads as Redirect**
•	Absolute path to file above wp-content - **Successfully downloads as Forced**

## Download Method: Redirect Symlinks: Enabled
•	**Dropbox File Store**
•	With Forced in Dropbox Settings: **Successfully Downloads as Forced**
•	Without Forced in Dropbox Settings: **Successfully Downloads as Redirect**

•	Public Dropbox link (copied straight into product) - **Successfully Downloads as Forced**
•	Amazon S3 - **Successfully Downloads as Redirect**
•	Regular upload to EDD folder - **Successfully Downloads as Redirect**
•	Regular upload to media library - **Successfully Downloads as Redirect**
•	Relative path to file in wp-content - **Successfully downloads as Redirect**
•	Absolute path to file in wp-content - **Successfully downloads as Forced**
•	Relative path to file above wp-content - **Successfully downloads as Redirect**
•	Absolute path to file above wp-content - **Successfully downloads as Forced**

## Download Method: Forced
•	**Dropbox File Store**
•	With Forced in Dropbox Settings: **Successfully Downloads as Forced**
•	Without Forced in Dropbox Settings: **Successfully Downloads as Redirect**

•	Public Dropbox link (copied straight into product) - **Successfully Downloads as Forced**
•	Amazon S3 - **Successfully Downloads as Redirect**
•	Regular upload to EDD folder - **Successfully Downloads as Forced**
•	Regular upload to media library - **Successfully Downloads as Forced**
•	Relative path to file in wp-content - **FAILED: “filesize(): stat failed … process-download.php on line 199”**
•	Absolute path to file in wp-content - **Successfully downloads as Forced**
•	Relative path to file above wp-content - **FAILED: “filesize(): stat failed … process-download.php on line 199”**
•	Absolute path to file above wp-content - **Successfully downloads as Forced**

**Comment by cklosowski** [comment]
Where do we stand with this @easydigitaldownloads/core-devs.

Are we good with it's current level of accuracy or do we want to go further, knowing that these `filesize` methods will be fixed in #4329

**Comment by pippinsplugins** [comment]
@cklosowski Can we please get the `filesize` fixes merged into the same branch so we can test all file types listed above?

**Comment by cklosowski** [comment]
Sure I'll just code them in the same branch, I was goign to do them separate...I'll update the existing PR

**Comment by pippinsplugins** [comment]
My test results:

**Download Method: Redirect
Symlinks: Disabled**

Dropbox File Store (with and without forced download settings) -- **worked**
Public Dropbox link (copied straight into product) -- **worked**
Amazon S3 -- **worked**
Regular upload to EDD folder -- **worked**
Regular upload to media library -- **worked**
Relative path to file in wp-content --  **worked**
Absolute path to file above wp-content **FAILED** and gave a 404 error: https://cloudup.com/cZfIfFgHtZi

**Download Method: Redirect
Symlinks: Enabled**

Dropbox File Store (with and without forced download settings) -- **worked**
Public Dropbox link (copied straight into product) -- **worked**
Amazon S3 -- **worked**
Regular upload to EDD folder -- **worked**
Regular upload to media library -- **worked**
Relative path to file in wp-content --  **worked**
Absolute path to file above wp-content **FAILED** and gave a 404 error: https://cloudup.com/cZfIfFgHtZi

**Download Method: Forced**

Dropbox File Store (with and without forced download settings) -- **worked**
Public Dropbox link (copied straight into product) -- **worked**
Amazon S3 -- **worked**
Regular upload to EDD folder -- **FAILED** and gave a 404 error: https://cloudup.com/cydzqKs_fJR
Regular upload to media library -- **worked**
Relative path to file in wp-content --  **worked**
Absolute path to file above wp-content **FAILED** and gave a 404 error: https://cloudup.com/cZfIfFgHtZi

@cklosowski Can you look at those failed items please?

**Comment by cklosowski** [comment]
@pippinsplugins already have been. Trying to figure out why it's doing that.

**Comment by pippinsplugins** [comment]
👍

**Comment by cklosowski** [comment]
@pippinsplugins you're up man, I can't get this to work for everyone involved. I've gotten it most of the way there but i apparently can't match the exact stuff you guys are seeing. Tossing my white towel in so someone else can pick up the pieces and see why this won't work 100% for all cases.

**Comment by mintplugins** [comment]
My test results up to https://github.com/easydigitaldownloads/Easy-Digital-Downloads/commit/7f3754d8abc736bdac23cdcc205270a152135925:

I have taken out everything that "Works as described in EDD" and only left in the ones that are acting strange. I know there are some workarounds in place but I'm not sure which ones those are so I am using "Works as described in EDD" as the expected behaviour for all downloads:

## Download Method: Redirect Symlinks: Disabled
	
•	Public Dropbox link (copied straight into product) - **Downloads as Forced**
•	Absolute path to file in wp-content - **Downloads as Forced**
•	Absolute path to file above wp-content - **Downloads as Forced**

## Download Method: Redirect Symlinks: Enabled
•	Public Dropbox link (copied straight into product) - **Downloads as Forced**
•	Relative path to file in wp-content - **404 Failed**
•	Relative path to file above wp-content - **404 Failed**

## Download Method: Forced
•	Amazon S3 - **Downloads as Redirect**
•	Regular upload to media library - **Downloads as Redirect**
•	Relative path to file in wp-content - **Downloads as Redirect**
•	Relative path to file above wp-content - **Downloads as Redirect**

**Comment by pippinsplugins** [comment]
@mintplugins For the two 404s you got, what did the URL in the browser look like?

**Comment by mintplugins** [comment]
@pippinsplugins 

1: http://localhost/edd/wp-content/uploads/edd/symlinks/filename.png
2: This is now downloading a blank 0 kb file (not sure why it's changed)

**Comment by pippinsplugins** [comment]
Just to confirm I get the same results as Phil, here are my tests:

**Redirect with Symlinks:**
- Relative path: Forbidden
- Absolute path: Works

**Redirect without Symlinks:**
- Relative path: works
- Absolute path: 404

**Forced:**
- Relative path: 404
- Absolute path: 404

**Comment by pippinsplugins** [comment]
When it's a non-local file, we still need to output the file download headers, so this is running too early:
```php
// If the file isn't locally hosted, process the redirect
if ( filter_var( $requested_file, FILTER_VALIDATE_URL ) && ! edd_is_local_file( $requested_file ) ) {
	edd_deliver_download( $requested_file, true );
	exit;
}
```
It has to run after 
```php
nocache_headers();
header("Robots: none");
header("Content-Type: " . $ctype . "");
header("Content-Description: File Transfer");
header("Content-Disposition: attachment; filename=\"" . apply_filters( 'edd_requested_file_name', basename( $requested_file ) ) . "\"");
header("Content-Transfer-Encoding: binary");
```

**Comment by pippinsplugins** [comment]
Relative and absolute paths appear to be failing for me primarily because of `header("X-Sendfile: $file_path");`

**Comment by pippinsplugins** [comment]
According to XSendFile documentation, only files that are within the bounds of whitelisted file patches can be sent with the `X-SendFile` header: https://tn123.org/mod_xsendfile/

Adding paths to the whitelist requires custom file configurations. That makes me think we should remove it completely and not use it. Perhaps we could add support for it later via an add-on.

**Comment by pippinsplugins** [comment]
Ok I think I have this worked out now. 

@cklosowski @mintplugins can you both please test?

**Comment by mintplugins** [comment]
Up to https://github.com/easydigitaldownloads/Easy-Digital-Downloads/commit/43c3acd10d992bca9c85faf87720c3d5b5534683, Symlinks and relative URLs are still giving 404s

**Comment by pippinsplugins** [comment]
@mintplugins If you inspect the table row for the file you're testing, does it show an `attachment_id` field? If so, does the value of that field match up with the expected attachment ID of the file?

**Comment by mintplugins** [comment]
I checked and the attachment ID in the database matches the value I entered into the download. I feel like that may not be what you are asking though. Am I missing anything here?

**Comment by pippinsplugins** [comment]
@mintplugins Do your absolute path downloads work?

**Comment by mintplugins** [comment]
@pippinsplugins yeah - they download as forced no matter what though

**Comment by pippinsplugins** [comment]
@cklosowski Can you replicate the 404 with relative paths?

**Comment by cklosowski** [comment]
With Redirect and Symlinks on, I get a 403 on a file that's located relative in the `/wp-content` folder

**Comment by cklosowski** [comment]
Same thing when it's in my EDD Folder:
```
Forbidden

You don't have permission to access /wp-content/uploads/sites/2/edd/symlinks/woocommerce-subscriptions_df0b52e9618b01a13.zip on this server.

Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.
```

**Comment by pippinsplugins** [comment]
The forbidden error is expected if your htaccess file hasn't been updated with the proper rules. It should be only `-Indexes` when using `Redirect`. Double check the rules. I found I had to update mine manually.

**Comment by cklosowski** [comment]
:+1: Will check that today.

**Comment by cklosowski** [comment]
@pippinsplugins This is what I'm looking at in the `/wp-content/uploads/sites/2/edd/.htaccess` Is there another one I should look for.

![screen shot 2016-03-11 at 4 05 03 pm](https://cloud.githubusercontent.com/assets/1390124/13718009/144809f0-e7a3-11e5-8920-37ad2b2e1f07.png)

**Comment by pippinsplugins** [comment]
That's it. So with that htaccess, you still get the forbidden error?

**Comment by cklosowski** [comment]
@pippinsplugins correct. I get the `403` when I have that `.htaccess` in place. I'll go through again today and test things out again, just to be sure.

**Comment by cklosowski** [comment]
@pippinsplugins these are the only ones that 403:
![relative-errors](https://cloud.githubusercontent.com/assets/1390124/13786336/4feea1c8-ea94-11e5-9a7e-3fa61cef2350.png)

**Comment by cklosowski** [comment]
@mintplugins @pippinsplugins can you guys test this latest commit out?

**Comment by pippinsplugins** [comment]
Relative and absolute paths both work for me with Forced, Redirect, and Redirect + Symlinks :+1:

**Comment by mintplugins** [comment]
**Redirect + Symlink:**
Success for everything except relative paths.
Failure for relative paths: They are now downloading empty 0kb files for me 

Here's a screenshot of my relative path:
<img width="655" alt="screen shot 2016-03-15 at 3 15 05 pm" src="https://cloud.githubusercontent.com/assets/1638128/13790938/20ae86da-eac1-11e5-8606-f06780184143.png">

<img width="649" alt="screen shot 2016-03-15 at 3 19 40 pm" src="https://cloud.githubusercontent.com/assets/1638128/13790983/62943a36-eac1-11e5-94b0-22c96f9155a1.png">



**Forced**: 
Success for all (although relative files are opening as "redirect")

**Redirect (without symlinks):**
Success for all (although absolute files are opening as "forced").

**Comment by cklosowski** [comment]
At this point we're awaiting some feedback from users who are willing to test out these fixes. @pippinsplugins should we get the remaining issues merged into a `2.5.10-beta` branch, (which is from `master`) so we can test the release out with some customers? That way we can give them a .zip of the release candidate.

**Comment by pippinsplugins** [comment]
@cklosowski yes please

**Comment by pippinsplugins** [comment]
I've merged this into `2.5.10-beta` and am sending it to a few users.

**Comment by pippinsplugins** [comment]
One beta tested said he was going to test soon but I have not heard an update from him yet.

**Comment by pippinsplugins** [comment]
Merged into master.

**Comment by nbastreet** [comment]
i'm using the latest version and when i use redirect method with symlink enabled, the size of download is 0 bytes. how can i solve this problem? any server configurations is needed?

**Comment by pippinsplugins** [comment]
Hi there!

Please go ahead and open a support ticket through our support portal: https://easydigitaldownloads.com/support

we use GitHub for development tracking only.
