### ISSUE TITLE
Wrong end date in payment export function - missing payments in csv

### ISSUE THREAD

**Issue by rene-hermenau** [easydigitaldownloads/Easy-Digital-Downloads#4333]
End time of the date object must be 23:59:59 when the data filter is used or data result gets empty for end day in the time frame.  
See: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/pull/4332

Example: 

Filtering data from 10/01/2016 to 10/02/2016 does not contain purchases from 10/02/2016 without that fix. (This should be save as long as it is never be tried to filter by time)

![Alt text](https://monosnap.com/file/uEHbN0wwZemFsReSSwZKWOIZkQc4X6.png)

**Comment by pippinsplugins** [comment]
Thanks for the headsup, we'll get it fixed.

**Comment by pippinsplugins** [comment]
PR: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/pull/4332

**Comment by mindctrl** [comment]
@cklosowski this looks good to me for both #4333 and #4334.
