### ISSUE TITLE
Broken end date in payment history. Not all purchases shown

### ISSUE THREAD

**Issue by rene-hermenau** [easydigitaldownloads/Easy-Digital-Downloads#4334]
Wrong end date in payment history. 
As a result the payment history is not showing all purchase made in the selected time frame.
See: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/pull/4330

Examples

![Alt text](https://monosnap.com/file/EXuu8ebQcxzUakwbYtSqWXquc5vr8g.png)

![Alt text](https://monosnap.com/file/EUMdDg8Tgg7gbIHQ1KKTN0sxh4EUPU.png)

**Comment by pippinsplugins** [comment]
@rene-hermenau Are you on the latest version? We just addressed this in #4030

**Comment by rene-hermenau** [comment]
Yes, Latest stable version
