### ISSUE TITLE
Misleading title attribute for Send Test Email

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/easy-digital-downloads#4341]
Oops! The Send Test Email button is highly confusing. As you can see [here](https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/emails/template.php#L112) the title attribute states `This will send a demo purchase receipt to the emails listed below.` but where this button appears in the settings there are no emails below. Unless I'm mistaken this button triggers an email to the addresses listed in Emails - > New Sale Notifications - > Sale Notification Emails which is obviously a different site section. I'd make a PR but I'm not exactly sure what the best way to improve this is.

**Comment by pippinsplugins** [comment]
Related: #4233

**Comment by pippinsplugins** [comment]
Looks like we opened a new issue on this, to which I've submitted PR. Marking as duplicate.

#4481
