### ISSUE TITLE
Login/Register Default Redirects

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/Easy-Digital-Downloads#4342]
Any thoughts on setting the default login/register redirects to the homepage? Not sure about you but we get a couple a week about people wondering why they are left on a blank page or see the message about being logged in.

**Comment by pippinsplugins** [comment]
I'd prefer we set the default to the account page with the home page as a fallback.

**Comment by spencerfinnell** [comment]
Do you mean Purchase History? There isn't a setting for the profile editor shortcode page is there?

**Comment by pippinsplugins** [comment]
Yes, Purchase History.

Profile editor does not have a setting.

**Comment by spencerfinnell** [comment]
Cool! Works for me. As long as it's taking them to a new page. :)

**Comment by SDavisMedia** [comment]
The doc blocks would need updating on both functions. 

I think it would be nice if `$redirect` was filtered.

**Comment by spencerfinnell** [comment]
There is an existing function that returns the desired result but looks like it's meant for something pretty specific and has a very specific filter: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/45aaece5aff1c51ca400c59838f22a7134450121/includes/user-functions.php#L888

Maybe make a separate `edd_get_purchase_history_page()` function with the appropriate filter? cc @pippinsplugins

**Comment by pippinsplugins** [comment]
It would be nice to have a dedicated function for it, though that can come later.

**Comment by pippinsplugins** [comment]
Merged in for 2.6!
