### ISSUE TITLE
Add action to edd_update_payment_details in order to validate and save custom data

### ISSUE THREAD

**Issue by flowdee** [easydigitaldownloads/Easy-Digital-Downloads#4347]
In my case I'm trying to add a custom input field by using the **edd_view_order_details_update_inner** action and now I need to validate and save the given data. 

![update_payment_details_action](https://cloud.githubusercontent.com/assets/2278756/13290049/78d26e76-db12-11e5-979a-6fbf5858bad7.png)

Tried using the **edd_update_payment_details** action but unfortunately it doesn't execute?! 

Correct me if I'm wrong but shouldn't there be an additional action inside the [edd_update_payment_details](https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/cbd63c71c415f9d29464730aeb404818a334e847/includes/admin/payments/actions.php#L22) function which allows us to validate and work with the given $data? 

Right now there are a few actions which only come along with the $payment_id.

**Comment by cklosowski** [comment]
You can use the action `edd_updated_edited_purchase`, which will pass you a `$payment_id` in order for you to make changes to it, and then your data you are processing will be in `$_POST` with the name of the input field you've created.

You would simply use something like:
```
function ck_save_my_meta( $payment_id ) {
    $my_meta = ! empty( $_POST['my_meta'] ) ? sanitize_text_field( $_POST['my_meta'] ) : false;
    if ( false !== $my_meta ) {
        $payment = new EDD_Payment( $payment_id );
        $payment->update_meta( '_my_meta_key', $my_meta );
    }
}
```

**Comment by flowdee** [comment]
Thanks @cklosowski this will be fine for me too!
