### ISSUE TITLE
Nigerian Currency

### ISSUE THREAD

**Issue by izikenmichael** [easydigitaldownloads/Easy-Digital-Downloads#4348]
There is no option for nigerian currency in the currency option. can it be fixed?

**Comment by mindctrl** [comment]
Hi @izikenmichael, 

You can add custom currencies to your site following the instructions [here](http://docs.easydigitaldownloads.com/article/272-adding-currency-support-eddcurrencies).

In the future, feel free to open support tickets on our site here: http://easydigitaldownloads.com/support/

We use Github for development purposes only.
