### ISSUE TITLE
Payment object doesn't setup fees_total

### ISSUE THREAD

**Issue by dancameron** [easydigitaldownloads/Easy-Digital-Downloads#4350]
I'm adding downloads to a payment after purchase (to handle bundles easily), this is done with `$payment->add_download()` after `edd_insert_payment`. Anyway, I found out that modifying the payment will cause the total to be recalculated incorrectly based on the fees_total not being setup during instantiation.

```
		$this->fees_total      = $this->setup_fees_total();
```

```


	/**
	 * Setup the payment fees
	 *
	 * @since  XXX
	 * @return float The fees total for the payment
	 */
	private function setup_fees_total() {
		$fees_total = (float) 0.00;

		$payment_fees = isset( $this->payment_meta['fees'] ) ? $this->payment_meta['fees'] : array();
		if ( ! empty( $payment_fees ) ) {
			foreach ( $payment_fees as $fee ) {
				$fees_total += (float) $fee['amount'];
			}
		}

		return $fees_total;

	}
```

**Comment by pippinsplugins** [comment]
@dancameron Thanks for the headsup! We'll get it fixed for next point release.

**Comment by pippinsplugins** [comment]
PR looks good too so just need to test and confirm there are no nuances.

**Comment by cklosowski** [comment]
@dancameron this looks good but we can simplify it as `setup_fees` has already been run and defaults to an empty array for fees, we can just do a `foreach` on `$this->fees as $fee`. If we want we could throw a `! empty()` check prior, but no need to do the validation of it again.

**Comment by dancameron** [comment]
That's what I originally had but I didn't want that method to be dependent
on another loading first. I doubt it would be an issue since they're
private but it's just a thought I had that convinced me to change it.
On Thu, Feb 25, 2016 at 8:01 AM Chris Klosowski <notifications@github.com>
wrote:

> @dancameron <https://github.com/dancameron> this looks good but we can
> simplify it as setup_fees has already been run and defaults to an empty
> array for fees, we can just do a foreach on $this->fees as $fee. If we
> want we could throw a ! empty() check prior, but no need to do the
> validation of it again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/4350#issuecomment-188853394>
> .
>
-- 
Typos sent from my iPhone.

**Comment by cklosowski** [comment]
@dancameron I can live with that justification... @pippinsplugins?

**Comment by pippinsplugins** [comment]
I'm fine with it.
