### ISSUE TITLE
Conflict with WP-Members plugin (customer missing)

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/Easy-Digital-Downloads#4353]
**The Issue:**

Purchases (when the user signs up upon checkout) don't have the customer attached if this 3rd party plugin is active:
https://wordpress.org/plugins/wp-members/

<img width="1242" alt="screen shot 2016-02-25 at 11 19 04 am" src="https://cloud.githubusercontent.com/assets/1638128/13327124/9a10cdae-dbb6-11e5-8dca-304281f66e20.png">

**Recommended Action:**
Find what is happening during the sign-up process and create a workaround specific for this plugin.

**Comment by pippinsplugins** [comment]
@mindctrl I just tested it and it worked properly for me.

I purchased while logged out and created an account during checkout.
![screen shot 2016-02-25 at 1 15 10 pm](https://cloud.githubusercontent.com/assets/1034109/13331148/d18ac1b2-dbc1-11e5-816b-3740a9e1e1bc.png)

**Comment by pippinsplugins** [comment]
Any specific settings?

**Comment by mindctrl** [comment]
@mintplugins ^^

**Comment by mintplugins** [comment]
My mistake. After confirming I found this was actually caused by some strange cacing behaviour with W3 Total Cache...closing.

**Comment by Misplon** [comment]
@mintplugins If you have a moment, do you think you can share with us what you adjusted in W3 Total Cache to resolve?

**Comment by Misplon** [comment]
Resolved using: http://docs.easydigitaldownloads.com/article/299-w3-total-cache-config. Thanks guys.
