### ISSUE TITLE
Support HTML in edd_new_user_notification email

### ISSUE THREAD

**Issue by akyusa01** [easydigitaldownloads/Easy-Digital-Downloads#4365]
Original ticket: https://secure.helpscout.net/conversation/175033312/28661/?folderId=750133

The function is performing the echo including the html characters:

![screen-shot-2016-02-25-at-12-30-12-pm](https://cloud.githubusercontent.com/assets/9019502/13351972/4ac4a412-dc58-11e5-9eee-5c9e4bf4db5f.png)

**Comment by pippinsplugins** [comment]
This email is never sent as HTML so we need to remove all HTML from it.

**Comment by sunnyratilal** [comment]
As there is a HTML link in there, shouldn't we just add the email headers so it's treated as HTML to keep the login link valid?

**Comment by pippinsplugins** [comment]
@sunnyratilal We certainly could! I'm not opposed to doing that.

**Comment by cklosowski** [comment]
I like the idea of turning it into an HTML email @sunnyratilal the number of clients NOT supporting HTML email is so low that I feel like it should be HTML by default, especially with a call to action URL

**Comment by sunnyratilal** [comment]
Should we update it to the use the EDD emails class while we're at it?

**Comment by cklosowski** [comment]
Sure, @pippinsplugins you good with that? I think EDD Emails should power any email we send.

**Comment by pippinsplugins** [comment]
I'm good with that.

**Comment by cklosowski** [comment]
User Email:
![screen shot 2016-03-09 at 5 37 41 pm](https://cloud.githubusercontent.com/assets/1390124/13655571/a837493c-e61d-11e5-936e-50af098ad19e.png)

Admin Email:
![screen shot 2016-03-09 at 5 37 32 pm](https://cloud.githubusercontent.com/assets/1390124/13655575/aee94c62-e61d-11e5-8cf6-9fd12d37218a.png)

Thoughts @akyusa01 @pippinsplugins @sunnyratilal ?

**Comment by SDavisMedia** [comment]
I personally dig this. Ready to test if you wanna push something up.

**Comment by cklosowski** [comment]
@SDavisMedia yeah I wnat to rework the text for the headers to be 'less scary' for the user end...maybe something like `Your account info`

**Comment by SDavisMedia** [comment]
@cklosowski `Your account info` sounds good to me

**Comment by akyusa01** [comment]
looks good to me!

**Comment by pippinsplugins** [comment]
I like it.

**Comment by akyusa01** [comment]
tested this morning, works perfectly
