### ISSUE TITLE
HTML validation fails if schema.org itemtype is missing

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/easy-digital-downloads#4373]
`add_filter( 'edd_add_schema_microdata', '__return_false' );` is a useful snippet for removing Schema.org attributes, however currently it results in HTML validation errors. [This tool](https://developers.google.com/structured-data/testing-tool/) demonstrates the problem. The issue is that some schema.org properties remain but are essentially orphaned because the type they belong to gets removed by the above filter. An example (not sure if it occurs elsewhere) is [here](https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/template-functions.php#L268). The `$schema` variable only outputs the `itemtype` conditionally. The rest gets output no matter what. Basically there doesn't seem to be a straightforward way to truly remove all Schema.org markup.

**Comment by pippinsplugins** [comment]
@brashrebel test again for me now?

**Comment by brashrebel** [comment]
This does solve the one occurrence found in that function, yes. However, the following instances still output Schema attributes no matter what:

- [ ] shortcode-content-excerpt.php [here](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/issue/4373/templates/shortcode-content-excerpt.php#L4) and [here](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/issue/4373/templates/shortcode-content-excerpt.php#L8)
- [ ] shortcode-content-full.php [here](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/issue/4373/templates/shortcode-content-full.php#L1)
- [ ] shortcode-content-price.php [here](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/issue/4373/templates/shortcode-content-price.php#L2)
- [ ] shortcode-content-title.php [here](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/issue/4373/templates/shortcode-content-title.php#L1)

**Comment by cklosowski** [comment]
@brashrebel can you check those out? Just check off the ones above after you verify.

**Comment by pippinsplugins** [comment]
Assuming tests pass, this looks good to me.
