### ISSUE TITLE
edd-admin.css CSS coding standards

### ISSUE THREAD

**Issue by samikeijonen** [easydigitaldownloads/easy-digital-downloads#4374]
`edd-admin.css` file is kind of hard to read and maintain. Do you think it would be a good idea to follow more closely [CSS coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/css/)?

Something similar than in `edd.css` file.

**Comment by pippinsplugins** [comment]
Yes.

**Comment by cklosowski** [comment]
Merged in https://github.com/easydigitaldownloads/easy-digital-downloads/commit/43aa82f3f2779da04d1fa9da6e477d5dcccf6ac4

**Comment by cklosowski** [comment]
On second thought, leaving it open and Needs Testing so we can make sure as we work through the release we don't notice anything.

**Comment by pippinsplugins** [comment]
This is all working fine.

**Comment by SDavisMedia** [comment]
No issues here.

**Comment by cklosowski** [comment]
Thanks @pippinsplugins and @SDavisMedia, closing.
