### ISSUE TITLE
Change message on account page for password

### ISSUE THREAD

**Issue by akyusa01** [easydigitaldownloads/easy-digital-downloads#4376]
Original Ticket: https://secure.helpscout.net/conversation/175925713/28854/

Message shows "Please note after changing your password, you must log back in." which is misleading as the user is still logged in.

![account local testing 2016-02-29 11-37-08](https://cloud.githubusercontent.com/assets/9019502/13401103/d014dc7c-ded8-11e5-983b-5013c3b657d5.png)

**Comment by michaelbeil** [comment]
I believe when a user changes the password, he/she is automatically logged out.

**Comment by akyusa01** [comment]
Hey man :)  I tested on my local with the latest version and didn't get logged out.  But as soon as the profile editor loads, you have that message there whether you are there to change your password or now.

**Comment by pippinsplugins** [comment]
Let's get it fixed in 2.6

**Comment by pippinsplugins** [comment]
There is actually no requirement that the user has to log back in, so I vote we remove the message instead of forcing them to log back in.

**Comment by michaelbeil** [comment]
👍
