### ISSUE TITLE
Record edits to core EDD files

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/easy-digital-downloads#4378]
I don't know exactly where we'd store it. A new option I guess? But it would be fairly straightforward to tap into whenever the `recently_edited` option is updated with something like the `pre_update_option_*` filter. The option stores a serialized array which includes the path to the file that was edited. Would be cool to add this to the System Info so we can tell in support whether the files have been edited.

**Comment by brashrebel** [comment]
I don't really know what the ideal implementation for this would be but my first thought is a new option would be created when any edd core file or extension is edited the first time and updated for any changes after. This option wouldn't have any admin UI but would be used to populate a new `-- File Edits` section on the System Info. The option would store an array of the files that have been edited and probably that's it. I don't think any other information can be easily obtained.

Is this a smart way to handle this or would something else make more sense?

**Comment by pippinsplugins** [comment]
I really like the fundamental idea of doing something like this though we'll have to discuss in depth to figure out exactly how we want to implement it.

**Comment by cklosowski** [comment]
Since WPCLI now supports via the checksums API, I'm closing it:
https://developer.wordpress.org/cli/commands/plugin/verify-checksums/

While it won't be available on all instances, I think its good enough for us for now. We've had less and less issues with modification of core files.
