### ISSUE TITLE
Testing IF statement on inexisting price returns true

### ISSUE THREAD

**Issue by joviczarko** [easydigitaldownloads/Easy-Digital-Downloads#4383]
Is this behaviour a feature or a bug?

`if ( edd_price( get_the_id(), 0, 2 )`  Will return true even if the price is not set.

`edd_price( get_the_id(), 1, 2 );` Will display first price when price ID2 is not set.

Only way to test if ID2 price exists is by price name
`if ( edd_get_price_option_name( get_the_id(), 2) )`

Also `if ( edd_get_price_option_name( get_the_id(), 2) )` returns true even if the product does not have variable pricing checked.

**Comment by pippinsplugins** [comment]
@joviczarko That is intentional.

**Comment by joviczarko** [comment]
@pippinsplugins  OK. Sorry for bothering then :+1:
