### ISSUE TITLE
Add campaign tracking to links in contextual help menus

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/easy-digital-downloads#4386]
Throughout EDD there's a handful of links in the contextual help menus. We have no idea whatsoever how much that help content gets used so in order to get _some_ data we should at least be tracking the links back to our site.

**Comment by brashrebel** [comment]
@cklosowski want me to handle this?

**Comment by pippinsplugins** [comment]
All yours @brashrebel
