### ISSUE TITLE
How can i set license to a wordpress web page

### ISSUE THREAD

**Issue by zozii** [easydigitaldownloads/Easy-Digital-Downloads#4387]
Hi dear support
I have this problem... i will sell my website with woocommerce plugin installed(all the products included) and with the hosting on the server. I want to add license to the woocommerce or at this Theme and then the other Administrator won`t be able to use the dashboard whithout me (the license). Is there any license/plugin/or other security method which i can use it to make my idea true?
...I can not control the page becuse they will have access to the server and they can easy change the Admin password.
Thanks

**Comment by michaelbeil** [comment]
Hi there. Please send support inquiries to https://www.easydigitaldownloads.com/support. We use GitHub to track core development issues only :). 
Thanks :+1:
