### ISSUE TITLE
EDD has 2 (almost identical) functions for returning the success page URL

### ISSUE THREAD

**Issue by sumobi** [easydigitaldownloads/easy-digital-downloads#4389]
It turns out that the new version of EDD Recurring prevents a conditional redirect from working in EDD Conditional Success Redirects. This is because EDD Recurring uses `edd_get_success_page_url()` to get the URL of the success page. In the CSR plugin it uses the `edd_get_success_page_uri` filter available within the `edd_get_success_page_uri()` function.

These two functions appear almost identical, they're just written slightly differently. Both return the success page URL such as `http://site.com/checkout/purchase-confirmation/`.

`edd_get_success_page_uri()`
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/checkout/functions.php#L63

`edd_get_success_page_url()`
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/checkout/functions.php#L179

For now, I'm going to add the extra filter to CSR to fix the redirect, but we should probably deprecate one or the other. EDD core doesn't use `edd_get_success_page_url` anywhere, perhaps we should deprecate that one and make it return `edd_get_success_page_uri`.

**Comment by pippinsplugins** [comment]
Let's make `edd_get_success_page_url()` simply return `edd_get_success_page_uri()` and deprecate it.

**Comment by sumobi** [comment]
:+1:
