### ISSUE TITLE
Will not proceed to payment page

### ISSUE THREAD

**Issue by psyd2u** [easydigitaldownloads/Easy-Digital-Downloads#4391]
I have setup my first download and went to test purchase it.  I entered the receiving email address and the first and last name and clicked "Purchase." The button changed to "Please Wait" with a rotating circle next to it but would not advance beyond there.  I am using an incognito window and using a different email address than the PayPal or website email addresses.  Please help!

**Comment by SDavisMedia** [comment]
Hi @psyd2u. Please go ahead and open a support ticket using our [support form](https://easydigitaldownloads.com/support). This area is reserved for development discussion only.

Before opening your ticket, temporarily deactivate **all** other plugins besides EDD and test the functionality once more. Be sure to let us know the results of that test when you submit the support ticket.
