### ISSUE TITLE
EDD_API hooks fire when extending the class

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#4397]
We discovered in Recurring (https://github.com/easydigitaldownloads/edd-recurring/issues/250) that if you extend the `EDD_API` class, it's filters and hooks fire twice (logically) and things like the api key fields on the admin profile editor show twice. We should make those not fire twice.

Credit: @mintplugins

**Comment by pippinsplugins** [comment]
@cklosowski Looks good. Anything else to move out of the class or done?

**Comment by cklosowski** [comment]
@pippinsplugins no I think this should be fine to move out, the rest makes sense to keep in the Class.

**Comment by cklosowski** [comment]
Also we have unit tests for creating keys, it's why I had to go back and make it backwards compatible ;), to fix the unit tests.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
Everything works well here for me. Just needs the unit tests.

**Comment by pippinsplugins** [comment]
Nvm, we have tests for these :)
