### ISSUE TITLE
Move edd-ajax.min script to footer

### ISSUE THREAD

**Issue by bizzthemes** [easydigitaldownloads/easy-digital-downloads#4401]
Is there any special reason that edd-ajax.min script is in header? It depends on jQuery so it also pulls jQuery to header. It would be much better to put it in footer.

**Comment by cklosowski** [comment]
Will need to do some testing with major extensions. I'll try that out and
see if we have any negative consequences.
-- 
Chris Klosowski

**Comment by pippinsplugins** [comment]
I'm not entirely sure but I suspect moving it to the footer may cause issues with the elements that we hide dynamically through JS. It would cause them to show and then be hidden after the page is rendered. Will need to test to confirm.

**Comment by bizzthemes** [comment]
Not sure about showing / hiding stuff with Ajax before content is rendered, this is a CSS territory.

**Comment by pippinsplugins** [comment]
We use a combination of JS CSS to hide some elements as a way to 100% support sites that have javascript disabled.

**Comment by pippinsplugins** [comment]
PR submitted that appears to work fine.

We need to do a sweep through our extensions and check for cases of their JS using `edd_global_vars` and/or `edd_scripts` to ensure those do not fail now.

**Comment by pippinsplugins** [comment]
Known extensions that use one of the above and _must_ be tested with this PR:

- [ ] 2Checkout
- [ ] Discounts Pro
- [ ] Gateway Fees
- [ ] PayPal Pro / Express
- [ ] Simple Shipping
- [ ] Stripe
- [ ] Volume Discounts
- [ ] Bookings
- [ ] Reviews
- [ ] Wish Lists

**Comment by sunnyratilal** [comment]
Comment updated as Reviews doesn't rely on EDD's JS

**Comment by cklosowski** [comment]
Just updated the branch with `release/2.7`, going to start doing some testing.

**Comment by cklosowski** [comment]
I'm getting some _really_ odd UX when I am using Volume Discounts. I'm not sure if it's 100% related to these changes, but it's seeming like it's VERY laggy in figuring out the details and not always saving my changes to the quantities. I'll have to get in depth with this.

**Comment by cklosowski** [comment]
Merged in latest 2.7 and seems to be working as I expect now.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by sunnyratilal** [comment]
Tested and all working good too.

**Comment by pippinsplugins** [comment]
@sunnyratilal looks like the PR never got merged :(

**Comment by pippinsplugins** [comment]
This has to be moved to 2.8 now. We cannot include it in a point release.

**Comment by cklosowski** [comment]
I've had to revert this for now, as it's caused some problems with gateways like Stripe. Reopening it so we can further investigate.

**Comment by cklosowski** [comment]
Ok, I was able to but this pack into `release/2.8`.
