### ISSUE TITLE
Allow PayPal payments to be refunded inside the WordPress admin

### ISSUE THREAD

**Issue by thomasgriffin** [easydigitaldownloads/easy-digital-downloads#4403]
Merry Christmas from myself and all the devs at Awesome Motive. :gift:

https://github.com/easydigitaldownloads/Easy-Digital-Downloads/pull/4402

Feel free to ask any questions or discuss. This is battle tested (10+ months used in production) and works very well.

**Comment by pippinsplugins** [comment]
@thomasgriffin This all looks really, really excellent. There are a few small tweaks I'll want to make, but we can take care of those ourselves. Thanks!

**Comment by pippinsplugins** [comment]
I've manually merged the PR into `issue/4403` so we can continue work on it.

**Comment by pippinsplugins** [comment]
@easydigitaldownloads/core-devs this is ready for extensive testing.

**Comment by cklosowski** [comment]
Is it possible to make the descriptions a little less redundant? they all contain the string:
`Necessary if you want to refund PayPal payments inside the WordPress admin.`

We could make like a header possibly? Or something so we just don't repeat that over and over.

**Comment by pippinsplugins** [comment]
![screen shot 2016-05-23 at 8 57 47 am](https://cloud.githubusercontent.com/assets/1034109/15473198/86f64dd6-20c4-11e6-8772-6d61990b01bf.png)

**Comment by cklosowski** [comment]
Looks good @pippinsplugins Thanks, will continue testing.

**Comment by cklosowski** [comment]
Works great! I'd love for someone else to test this out too, but i'm good with these changes.

**Comment by pippinsplugins** [comment]
They worked for me as well.

**Comment by mintplugins** [comment]
Once we rewrite the doc for getting paypal API keys, we should consider updating the link to "Your Paypal Account". The current link to the Paypal docs appears to be out-dated. I wasn't able to get my API keys by following it.

https://developer.paypal.com/docs/classic/api/apiCredentials/#creating-an-api-signature

**Comment by pippinsplugins** [comment]
I think we should leave `Test` since that makes it more clearly related to `Test Mode`. I do like the idea of saying `Test Keys (Sandbox)`.

**Comment by pippinsplugins** [comment]
Merging into `release/2.6`. We'll close after we update the URL for how to generate API keys to point to our new doc: https://trello.com/c/3MZNlwNJ/231-how-to-get-api-keys-for-paypal

**Comment by pippinsplugins** [comment]
Actually will wait for tests on merge conflict resolution to pass.

**Comment by pippinsplugins** [comment]
Merged.

**Comment by pippinsplugins** [comment]
Tests passing!

**Comment by pippinsplugins** [comment]
We need to update the wp_remote_post() requests to use the helper functions for the return checking. 

For WordPRess 4.6, the `wp_remote_post()` and `wp_remote_get()` functions are being updated to return an object instead of an array. The returned object implements array access so the following should still work, but to be safe we need to update all of our code to use the helper functions for retrieving the body, response code, headers, etc.

```php
$request = wp_remote_post( $this->api_endpoint, array( 'timeout' => 45, 'sslverify' => false, 'httpversion' => '1.1', 'body' => $args ) );

if( 200 == $request['response']['code'] ) {  }
```

That should become:

```php
$request = wp_remote_post( $this->api_endpoint, array( 'timeout' => 45, 'sslverify' => false, 'httpversion' => '1.1', 'body' => $args ) );

if( 200 == wp_remote_retrieve_response_code( $request ) ) {  }
```

The return types are changing as part of a bigger project to introduce support for parallel requests (which is really cool): tps://core.trac.wordpress.org/ticket/33055
