### ISSUE TITLE
Unsupported Currencies?

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#4406]
We have support in core for Indian Rupee and Iranian Rial but I can't find a single PayPal doc that says either of those two currencies are supported. They're not supported for PayPal personal accounts https://www.paypal.com/selfhelp/article/FAQ2390/2 and they aren't supported for business accounts https://www.paypal.com/cgi-bin/webscr?cmd=p/sell/mc/mc_wa-outside from what I can find

**Comment by pippinsplugins** [comment]
Tagging for review in 2.7

**Comment by sunnyratilal** [comment]
PayPal operate a bit oddly in India.

Indian PayPal accounts are restricted to in-country customers, so only Indian customers can purchase through PayPal with INR. They limit who can and cannot pay in INR.

I have a feeling it's the same story for the Iranian Rial.

**Comment by pippinsplugins** [comment]
>>>I have a feeling it's the same story for the Iranian Rial.

I believe that is the case.

Let's go ahead and close.
