### ISSUE TITLE
Add downloads using 'Bundle'

### ISSUE THREAD

**Issue by akyusa01** [easydigitaldownloads/easy-digital-downloads#4408]
Original ticket: https://secure.helpscout.net/conversation/181090889/29944/

User is worried as wants to use Recurring and access to all, but the 'add products' under the bundle option only shows the latest 10, the rest has to be typed in for searching.  Is there an option we can add to let them control how many show in the dropdown?

**Comment by chriscct7** [comment]
Theres a filter for this, the name of which eludes me at the moment.
However the reason we don't show them all by default is performance. If a
site has say 500 products, listing them all has performance considerations.
You can kill the server either on the. PHP side when doing the mysql query
overruns time allowances or on the client browser side when rendering that
many items in the DOM freezes the browser.

**Comment by pippinsplugins** [comment]
We've discussed the option of making a way to add a product to an existing bundle when creating a product. It's not something I'm too inclined to add at this time as it's a pretty rarely needed feature, but would be a great place for a free extension to come in.

**Comment by pippinsplugins** [comment]
I'm going to go ahead and close this as wontfix for now as it's a definite edgecase and not something that affects a large percentage of users.
