### ISSUE TITLE
wpautop in email templates messes with custom HTML template overrides

### ISSUE THREAD

**Issue by benjaminprojas** [easydigitaldownloads/Easy-Digital-Downloads#4418]
@cklosowski @pippinsplugins @chriscct7 

Throughout the process of generating the purchase email (and other EDD emails), the wpautop function is used multiple times.  This really messes with custom HTML templates, unless the templates remove all line breaks/whitespace in the HTML code.

I'd like to submit a PR to make wpautop optional.  Thoughts?

Here are the offending lines: 

https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/emails/template.php#L95

https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/emails/template.php#L165

https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/emails/template.php#L226

https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/emails/class-edd-emails.php#L358

**Comment by pippinsplugins** [comment]
@benjaminprojas I'd be fine with a filter to make it optional.

**Comment by pippinsplugins** [comment]
Looks good to me, I'm merging it.
