### ISSUE TITLE
In edd_email_preview_template_tags default to default gateway

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/Easy-Digital-Downloads#4419]
In edd_email_preview_template_tags() we should probably default to the default gateway, not assume PayPal, in case a site owner only uses (for example) Stripe, and wants to test emails that contain Stripe tags: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/f2f1f7db7322f5abe2d5900be0c40895978aed21/includes/emails/template.php#L65

**Comment by pippinsplugins** [comment]
:+1: merged.
