### ISSUE TITLE
Switch to using new IPN endpoints for PayPal Standard

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#4422]
As part of https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&id=FAQ1916&viewlocale=en_US, PayPal now strongly recommends using new endpoints. We can only, and we should, switch over to using these on the closest release after September 30th.

> The ipnpb.paypal.com and ipnpb.sandbox.paypal.com endpoints only accept HTTPS connections. If you currently use www.paypal.com, you should move to ipnpb.paypal.com when you update your code to use HTTPS.

**Comment by pippinsplugins** [comment]
I don't see any reason not to do this a bit soon so bumping this up to 2.7 instead of 2.8.

**Comment by lalunecreative** [comment]
Paypal started sending out email notices to start upgrading BEFORE the September date to avoid any problems or cutoffs. After September 30th, paypal will stop working on sites using the old method unless the upgrades are completed. Updated link - https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&ID=FAQ1766&viewlocale=en_US

Might be advisable to move this one up sooner than later?

**Comment by pippinsplugins** [comment]
The IPN endpoint does not have to be updated before September 30th.

**Comment by lalunecreative** [comment]
Ah yeah I just saw the 2018 cutoff date. That's a ways out. The email didn't specify that specifically, just the cut off date for the 30th when it goes live.

**Comment by ghost1227** [comment]
This seems to work, but i'll admit I'm not a pro with IPN issues...

**Comment by sunnyratilal** [comment]
Rather than merge here, we can just put this into `EDD_Gateway` at #4195

**Comment by cklosowski** [comment]
Since `EDD_Gateway` was pushed to 2.8, do we want to merge this now @sunnyratilal and @pippinsplugins?

**Comment by chriscct7** [comment]
Note, the IPN endpoint date has been changed again. 

The IPN must changed before **June 30, 2017**. This is now a different date than the previous Jan 1, 2018 date referenced above, which is still the date you have to update PayPal Merchant API certificates.

A list of all security related changes required by Jan 1, 2018, their descriptions, and respective cutoff dates can be found on the official security roadmap page: https://www.paypal-knowledge.com/infocenter/index?page=content&id=FAQ1913&expand=true&locale=en_US

IPN date: https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&id=FAQ1916&viewlocale=en_US (midway down page in orange background)
![image](https://cloud.githubusercontent.com/assets/1324637/22278575/78eb156a-e292-11e6-8b1a-2f83d9e668fd.png)

Certificate date: https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&id=FAQ1915&viewlocale=en_US

**Comment by cklosowski** [comment]
Thanks @chriscct7.

So that leads me to believe we should ship these endpoint changes now, and in the future we should also show a warning or something when the site is not on HTTPS, since PayPal will not support HTTP sites past that date.

**Comment by chriscct7** [comment]
That's a different change. Use of PayPal's HTTPS endpoints for IPN is required by June 31, 2017. Use of SSL on the site in general isn't required until the next PCI DSS major version, which won't be until at least summer 2018. 

On that note someone should correct this doc as it's wrong: http://docs.easydigitaldownloads.com/article/1244-do-i-need-ssl-if-i-use-paypal

**Comment by chriscct7** [comment]
Basically all we need to do now for the June update is update the URL our PayPal IPN is getting sent to to one of their HTTPS ones.

**Comment by cklosowski** [comment]
Sounds good. Leave it to PayPal to make it as confusing as possible.  Flagging for Needs Docs so we can be sure to update it along side this.

**Comment by chriscct7** [comment]
I'd as a sidenote strongly recommend this go out in 2.7 (or if its going to be a while for that) next point release, as the only change here is just replacing a URL.

**Comment by cklosowski** [comment]
That's what I'm advocating for. URL changes in 2.7.

**Comment by sunnyratilal** [comment]
@cklosowski Happy to get this merged in as-is and then we'll port over to `EDD_Gateway` when the 2.8 cycle begins.

**Comment by sunnyratilal** [comment]
Merged into `release/2.7`
