### ISSUE TITLE
Multi-option purchase mode in variable pricing

### ISSUE THREAD

**Issue by michaelbeil** [easydigitaldownloads/easy-digital-downloads#4423]
When a download has variable pricing with the multi-option purchase mode enabled, a default is set and we see the download display with the available pricing options on the front-end.

Settings:
![screen shot on 2016-03-23 at 18-10-37](https://cloud.githubusercontent.com/assets/4752949/14003950/8f7eb54e-f124-11e5-8df6-abb1a07d64a3.png)

Display on front-end:
![screen shot on 2016-03-23 at 18-23-12](https://cloud.githubusercontent.com/assets/4752949/14003932/6bfc91f4-f124-11e5-95c9-edd4febd21c7.png)

An issue occurs when a user deselects a checkbox, and decides to click the purchase button with no checkboxes selected. A warning pops up, the user clicks ok, and then attempts to select an option to make a purchase. When clicking the purchase button, the screen scrolls to the top of the page and a `#` is added to the URL. Only until the user refreshes the page, can a purchase can be made.  

![screen capture on 2016-03-22 at 13-10-52](https://cloud.githubusercontent.com/assets/4752949/14003981/d3832518-f124-11e5-8304-2cff6c8c54e2.gif)

You can test here: https://easydigitaldownloads.com/demo/downloads/another-sample-product.

**Comment by sunnyratilal** [comment]
PR ready for testing.

**Comment by pippinsplugins** [comment]
PR works perfectly for me, merging.
