### ISSUE TITLE
Add way to blacklist URLs from triggering a session start

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#4429]
Sometimes there are pages where we never want a session to start (think high traffic landing page). To aide in this, we should add a way to blacklist URLs from starting sessions.

This will be a simple, filtered array of URLs / slugs. If we detect we're on a black listed URL, we prevent the session from starting.

Related: #4428 and #4284

**Comment by pippinsplugins** [comment]
@cklosowski Any further feedback here or are you fine with merging?

**Comment by cklosowski** [comment]
Let me run one more test @pippinsplugins. I'll merge if all is well.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by cklosowski** [comment]
Working much better. Merging.

**Comment by cklosowski** [comment]
@pippinsplugins quick thing...`@since 2.5.11` please.
