### ISSUE TITLE
Conditionally applying discounts

### ISSUE THREAD

**Issue by EngageWP** [easydigitaldownloads/Easy-Digital-Downloads#4432]
Hey, EDD crew. I want to put together a plugin to add some additional discount requirements, but I've run into the issue of not having a good place to hook into to verify those requirements before applying the discount. I looked at the `edd_is_discount_valid` filter, but that does not allow me to access the $_POST data when a discount is applied.

To throw out an idea for making this possible, a fourth, optional argument ($_POST) could be passed to `edd_is_discount_valid()`, and made available to the filter. This would give access to verify checkout input against custom discount meta, and return true/false accordingly.

In my case, for example, I'm checking to see if a customer's email is in a list of required emails for the discount the customer tries to apply. If it is not, the `edd_is_discount_valid()` function should return false (not a valid discount). The trouble here is accessing the posted data to check the customer's email against the list of email requirements for the discount.

Any thoughts? Perhaps this is already possible, and I'm just missing something? I'd be happy to submit a PR for this if it's something that is appropriate to add.

**Comment by chriscct7** [comment]
On that hook, use $user

$by_user_id = is_email( $user ) ? false : true;
$customer = new EDD_Customer( $user, $by_user_id );

The object will give you the email address

**Comment by EngageWP** [comment]
Awesome! So I guess I was overlooking something. Thanks a lot for your help, Chris.

**Comment by chriscct7** [comment]
Not a problem
