### ISSUE TITLE
Creating a payment sometimes doesn't save the correct user_id or customer_id

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#4435]
Related to #4434, there are cases where EDD isn't saving the correct user_id or customer_id (not sure which one yet, possibly both, probably user_id only). 

You can replicate this several different ways. For example:
- Disable guest checkout, set allow registration to true
- Buy a product while logged out, using the registration form to create a new user that the payment should be assigned to.

Or even easier:
- Install manual payments
- Create a new user manually in wp-admin
- Insert a payment manually for the user by using their email address

The result is the payment is not linked to the customer

This bug is impacting several of our extensions that rely on EDD to correctly identify the customer using the payment's user_id.

Briefly reading through the functions that process a payment, we switch between $payment_data['user_info']['user_id'] and $payment_data['user_info']['id'] to represent the customer's user_id all over the place (starts as the former, and by the time it goes into the payment class it should, and appears to be in the latter). My guess is somewhere along the lines, this is what causes the problem.

**Comment by chriscct7** [comment]
Another report: https://secure.helpscout.net/conversation/185898165/30859/?folderId=367285

**Comment by chriscct7** [comment]
Possibly related: https://secure.helpscout.net/conversation/185825189/30846/?folderId=180499

**Comment by pippinsplugins** [comment]
The manual payments scenario can be ignored. I've already fixed that in Manual Payments 2.0 (in development still).

**Comment by pippinsplugins** [comment]
@chriscct7 I just tested this on `master` and it worked properly.

![screen shot 2016-03-28 at 1 17 32 pm](https://cloud.githubusercontent.com/assets/1034109/14085785/8119883c-f4e7-11e5-8882-f3ca28b717f5.png)
![screen shot 2016-03-28 at 1 17 43 pm](https://cloud.githubusercontent.com/assets/1034109/14085784/81192982-f4e7-11e5-8aca-5575b453790c.png)
```php
<?php
$p = new EDD_Payment( 3771 );
var_dump( $p->user_id );
```
`string(2) "79"`

**Comment by pippinsplugins** [comment]
@chriscct7 Can you try and replicate this again?

@cklosowski could you also try please?

**Comment by cklosowski** [comment]
Testing now.

**Comment by cklosowski** [comment]
Things connected just fine for me. No issues with the first scenario:
1) Disabled Guest Checkout
2) Made a purchase registering on the checkout
3) User ID is assigned to the payment

![screen shot 2016-04-04 at 8 51 23 am](https://cloud.githubusercontent.com/assets/1390124/14253928/67bace5e-fa42-11e5-8ae5-4131bc80c7cb.png)
![screen shot 2016-04-04 at 8 51 05 am](https://cloud.githubusercontent.com/assets/1390124/14253936/6c55e304-fa42-11e5-85e5-a831c1956a86.png)


```
$payment = new EDD_Payment( 22087 );
var_dump( $payment->user_id );
var_dump( $payment->customer_id );
exit;

string(2) "81"
string(4) "1110"
```

**Comment by chriscct7** [comment]
Was able to replicate it earlier. It's really narrow. Took me a while to
get it. I'll give it another stab this weekend

**Comment by chriscct7** [comment]
I've seen this on 2 more sites now, another CFM users, and also on Desktop servers's site. The issue on DS's site is that the meta key that EDD Payment class pulls the user_id from is empty, so while the correct user is attached, the user_id isn't. You can tell payments which this occur to because those users:
- Won't be able to see EDD Invoices (because it checks against the user_id saved to the payment)
- Has a payment edit screen where the View Customer Download link has an arg for the user_id of 0

**Comment by chriscct7** [comment]
The specific meta key is `_edd_payment_user_id`

**Comment by pippinsplugins** [comment]
I bet we can fix this by pulling the user ID from the customer record if the meta value for `_edd_payment_user_id` is empty.

**Comment by pippinsplugins** [comment]
@cklosowski unless you disagree, I think we can merge this as is and mark as completed.
