### ISSUE TITLE
Reports: Filter by download

### ISSUE THREAD

**Issue by flowdee** [easydigitaldownloads/easy-digital-downloads#4436]
The reports are fine as they are when showing earnings vs. renewals vs. upgrades.

Additionally it would be very helpful to filter the statistics listed above, by a specific download. This way I can get an idea about which of my products are most valuable and which maybe not and should be dropped.

**Comment by pippinsplugins** [comment]
Do you want to see the reports for multiple downloads at once or just a single download?

**Comment by flowdee** [comment]
a list for multiples would be fine too. It's just important to get the total numbers for each download. Showing each options too would be the best case.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by sunnyratilal** [comment]
Closing as this will be implemented in #6298.
