### ISSUE TITLE
Download Details widget won't save "Current" Display Type

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/Easy-Digital-Downloads#4437]
If you select "Current" as the Display Type, it reverts to "Specific" when saved.

![image](https://cloud.githubusercontent.com/assets/1254870/14080474/6609a5b8-f4d3-11e5-9ffc-7dba7a200b17.png)

**Comment by abhilash88** [comment]
Facing the same issue. "Specific" is always checked when the Save button is clicked.

**Comment by cklosowski** [comment]
@mindctrl Can you test this out for me?

**Comment by mintplugins** [comment]
@cklosowski All is working as it should here!

**Comment by pippinsplugins** [comment]
Merging.
