### ISSUE TITLE
Sales/Earnings graph not working for individual products

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/Easy-Digital-Downloads#4439]
https://cloudup.com/cMVk8PMdwKm

**Comment by akyusa01** [comment]
I think I have another one: https://secure.helpscout.net/conversation/187724472/31203/

**Comment by cklosowski** [comment]
@easydigitaldownloads/core-devs could use some testing here to make sure I didn't miss anything.

**Comment by pippinsplugins** [comment]
Looks to work perfectly for me.

**Comment by mintplugins** [comment]
Looks good here

**Comment by cklosowski** [comment]
@mintplugins you shouldn't, the only way to get to a products earnings is via it's download edit screen. Just click on the Earnings or Sales number in the upper right metabox.

**Comment by mintplugins** [comment]
Yeah I did that. I'm just wondering about your screenshot. In the dropdown it says "Products"

**Comment by cklosowski** [comment]
@mintplugins Oh, that is on PippinsPlugins.com where the 'Downloads' label is 'Products'.

**Comment by mintplugins** [comment]
Ahh cool. Yep looks good to me then!
