### ISSUE TITLE
New Tool: Remove Expired Discounts Codes

### ISSUE THREAD

**Issue by danieliser** [easydigitaldownloads/easy-digital-downloads#4441]
This may not be of major use to everyone, but would be useful to nearly anyone creating discount codes.

In my case we generate discounts over an API so have nearly 15k expired codes. I know I can write my own script to do this, but would be a great addition to the expanding tools menu.

**Comment by pippinsplugins** [comment]
I can definitely see this being useful. May not be a candidate for core but definitely as a free add-on.

**Comment by pippinsplugins** [comment]
Closing as wontfix as this is add-on / tool territory.

**Comment by danieliser** [comment]
Sounds good. Leaving the code I use here just in case someone else needs it in the future.

https://gist.github.com/danieliser/e3d4f02171e665d6d8c35ab88b8b4ad4
