### ISSUE TITLE
In Customer details page icons are not focused

### ISSUE THREAD

**Issue by samikeijonen** [easydigitaldownloads/easy-digital-downloads#4443]
In Customer details page there are dashicons with links (Profile, Notes, Tools, Delete). I'd add hover and focus styles for those links.

Also HTML semantic feels weird for me. Now the icons list are like this:

```
<ul>
<a><li><span class="dashicon"></span></li></a>
<a><li><span class="dashicon"></span></li></a>
<a><li><span class="dashicon"></span></li></a>
</ul>
```

I'd change it to something like this:

```
<ul>
<li><a><span class="dashicon" aria-hidden="true"></span><span class="screen-reader-text">Info text</span></a></li>
<li><a><span class="dashicon" aria-hidden="true"></span><span class="screen-reader-text">Info text</span></a></li>
<li><a><span class="dashicon" aria-hidden="true"></span><span class="screen-reader-text">Info text</span></a></li>
</ul>
```

**Comment by samikeijonen** [comment]
Also when you click any of the icons, you lose the focus. Focus could switch to element `edd-item-card-wrapper` or the first focusable element inside it.

**Comment by pippinsplugins** [comment]
Thanks @samikeijonen! Milestoned for 2.6

**Comment by samikeijonen** [comment]
I'll create PR as soon as I have time :)

**Comment by pippinsplugins** [comment]
Great! Please submit against the `release/2.6` branch.

**Comment by samikeijonen** [comment]
Hmmm I think I broke the internet:) In PR #4445 I tried to fix this but it seems I got all the balls rolling.

**Comment by pippinsplugins** [comment]
New one looks good!

**Comment by pippinsplugins** [comment]
Looks good, merged!
