### ISSUE TITLE
Attachment ID not overwritten by external URL

### ISSUE THREAD

**Issue by moorscode** [easydigitaldownloads/easy-digital-downloads#4444]
Situation:
We use multiple download links on a download but on some download (which evidently have an attachment set somehow) the downloads don't work anymore because they are overriden by the attachment.

We are using The EDD Amazon S3 plugin to upload all our downloads to amazon.

Tracked the problem to the following commit:
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/pull/4335/commits/ab834e7dd034b783180a179bab392cf32629107d

EDD Version: 2.5.10
EDD Amazon S3 version: 2.2

I'd prefer to have a filter allowing to override the attachment retrieval if this is intended behaviour and needed in other cases.

**Comment by pippinsplugins** [comment]
@moorscode have I understood you correctly that your files have an attachment ID stored and so you need to disable attachment look up during download?

**Comment by moorscode** [comment]
That is correct, I need the remote URL to not be overridden (by the attachment lookup).

**Comment by pippinsplugins** [comment]
Quick way to fix that:

1. Delete the row from the files section
2. Add a new file and select the S3 file.

When doing that, no attachment ID will be saved.

**Comment by pippinsplugins** [comment]
I'm not 100% sure this still applies but let's make sure and fix it if so.

**Comment by pippinsplugins** [comment]
PR looks good to me but let's get some additional tests on it.

**Comment by cklosowski** [comment]
@easydigitaldownloads/core-devs could we get a couple tests on this?

To test it out, setup a download to use a file updated into EDD. Then copy and paste an external URL like: `https://downloads.wordpress.org/plugin/wp-plugin-banner.1.0.2.zip`. But just copy and paste that URL into the file URL field, not adding a new one and deleting the old.

On Master:
You will always get the file uploaded into EDD.

On issue/4444:
You should initially get the file uploaded in EDD, then when you replace the URL with the external URL, and click 'Update'. You should be able to download the new file delivered from WordPress.org.

**Comment by sunnyratilal** [comment]
@cklosowski Just tested and worked as expected. 👍

**Comment by pippinsplugins** [comment]
I'd like a test from @SDavisMedia too.

**Comment by SDavisMedia** [comment]
All good here. :+1:

**Comment by sunnyratilal** [comment]
Merged into `release/2.7`
