### ISSUE TITLE
Change output of edd_get_download

### ISSUE THREAD

**Issue by topher1kenobe** [easydigitaldownloads/easy-digital-downloads#4446]
Right now edd_get_download() returns a WP_Post Object, whereas EDD_Download returns an EDD_Download Object. 

We should make edd_get_download() return a new EDD_Download Object.

**Comment by sunnyratilal** [comment]
PR: #6172

**Comment by SDavisMedia** [comment]
I searched the code base for instances of `edd_get_download()` to see where and how it was being used. I found [this](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/eb8b28ede254335113a7ef76a95bf733b8912de2/includes/process-purchase.php#L1152) and [this](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/218fb75ed701a18aa2774fd5018e64e8641ec18b/includes/template-functions.php#L989) where the function's value is treated as boolean (not sure if I'm saying this correctly). `edd_get_download()` was previously `NULL` if no ID or a bad ID was passed. After this change, `edd_get_download()` will return an object (I think) if no ID or a bad ID was passed.

Is that going to be a problem in the aforementioned cases (or others)?

**Comment by cklosowski** [comment]
@SDavisMedia is correct here @sunnyratilal. If you pass in an ID that does not belong to a `download` post type, an empty `EDD_Download` object will be returned, instead of `null`, so the `! $download` checks will fail. Also the call to `edd_get_download` has to be outside of the `if` statements to support PHP < 5.4

We need to have a way to detect that the `EDD_Download` object that was found in `edd_get_download()` is a download before we return it as an object.

**Comment by cklosowski** [comment]
Ok @sunnyratilal @SDavisMedia I refactored this, to do checks and never return an empty object...

It follows the same return behavior as before, where it will return `null` when no download is found by that ID or name. Also added some unit tests.

Sean, you mind looking this over and verifying it will still work in your linked instances above?

**Comment by SDavisMedia** [comment]
Looks great to me. If the download ID is bad or missing, `NULL` is returned. If the ID is present and accurate, the `EDD_Download` object is returned. If a you pass a product slug instead of an ID, you still get the `EDD_Download` object (nice). :+1:

**Comment by SDavisMedia** [comment]
Both check out against the logic I pointed out in the two links as well. 👍
