### ISSUE TITLE
Past customer detail missing on Payment History & sales summary also wrong  

### ISSUE THREAD

**Issue by santhosh-r-wiredelta** [easydigitaldownloads/Easy-Digital-Downloads#4449]
The problem is with purchases and customers not matching fully, leading to wrong stats and problems sending out emails, etc. 
List out major issues in given follow :
1) Easy Digital Downloads Sales Summary -> it show wrong caculation  
2) Payment History -> past customer name is missing but current customer working fine
3) Payment History -> Past View Order Detail is empty
How to fix this issue

**Comment by pippinsplugins** [comment]
Hi there!

Please go ahead and open a support ticket through our support portal: https://easydigitaldownloads.com/support

we use GitHub for development tracking only.
