### ISSUE TITLE
Migration error with .htaccess

### ISSUE THREAD

**Issue by rigelreyes** [easydigitaldownloads/Easy-Digital-Downloads#4450]
I migrated a WP site using EDD via FTP from one host to another. Now in the new host I get this message:

```

> The Easy Digital Downloads .htaccess file is missing from /home/becamela/public_html/wp-content/uploads/edd!
> First, please resave the Misc settings tab a few times. If this warning continues to appear, create a file called ".htaccess" in the /home/becamela/public_html/wp-content/uploads/edd directory, and copy the following into it:
> Options -Indexes
> deny from all
> 
> Order Allow,Deny
> Allow from all
> 

```

I already looked for this issue in EDD support forums without success, trying the download methods forced and redirect on EDD settings, rewritten the .htaccess file, and asking the hosting for the options directives and the say that all directives work properly. Everything I´ve try without success. I´ve my .htaccess file properly placed and with this content:

`Options -Indexes
deny from all
<FilesMatch ‘\.(jpg|png|gif|mp3|ogg)$’>
Order Allow,Deny
Allow from all
</FilesMatch>`

The hosting awsered to this issue like this:
The cPanel username of this account is "rarrucha" but the plugin is detecting a different username. Please try contacting with the plugin developer to find out what is causing such issue and the fix.

Please help!!!!

**Comment by mindctrl** [comment]
Hi @rigelreyes,

Go ahead and open a support ticket and someone will help you out: https://easydigitaldownloads.com/support/

We use Github issues for development tracking only.

Thanks.
