### ISSUE TITLE
show variable pricing option in download logs

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#4457]
If you go to Downloads -> Reports -> Logs and view any of the tables, the **Download** column never shows the selected option for a variable pricing download. It only shows the download entry's title. Could be enhanced to show the option.

![screen shot 2016-04-04 at 12 15 32 pm](https://cloud.githubusercontent.com/assets/2359131/14260149/f590f3ae-fa5e-11e5-9ad2-e023d203a8aa.png)

**Comment by pippinsplugins** [comment]
We can definitely make that happen.

**Comment by sunnyratilal** [comment]
@SDavisMedia The variable pricing option is already displayed. Looks like it was addressed in #4458.

<img width="460" alt="image" src="https://user-images.githubusercontent.com/1525554/32699051-5c5afcb2-c7a7-11e7-9a65-e44e82d0fdeb.png">

**Comment by SDavisMedia** [comment]
@sunnyratilal this should probably be enhanced to show it on the File Downloads filter as well. Looks like I opened this issue just for `Sales` filter but `File Downloads` could use it too, I think.

Thoughts?

**Comment by cklosowski** [comment]
I agree, we should have it in the file download logs as well.

**Comment by SDavisMedia** [comment]
All good here for both `Sales` and `File Downloads`. Can't find any other logs that need this change. :+1:
