### ISSUE TITLE
sales logs show incorrect Item Amounts with variable pricing

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#4458]
This seems related to another issue I opened some time ago. Can't find it at the moment but when I do, I'll link it.

-----

**Replicate**
1. Set up a variable pricing product with multi-option purchase mode on. Make sure at least two of the options have different prices.
2. Complete one purchase with at least two of the different price options selected.
3. Downloads -> Reports -> Logs and filter by Sales.

**Problem**
What you'll see is that the price of the first variable pricing item added to the cart will be the price shown in the Item Amount column on the Logs table.

![screen shot 2016-04-04 at 12 55 37 pm](https://cloud.githubusercontent.com/assets/2359131/14261249/95effa8e-fa64-11e5-9c7a-1efe6faf3bdd.png)

![screen shot 2016-04-04 at 12 55 49 pm](https://cloud.githubusercontent.com/assets/2359131/14261255/9a9a5976-fa64-11e5-9065-32996aa72135.png)

-----

The price, or Item Amount used is always the first one added to the cart. This can easily be seen by making the same purchase again but adding the options to the cart in a different order.

**Comment by SDavisMedia** [comment]
Also let me note here that this is most likely not specific to the Item Amounts. As mentioned above, I have another issue somewhere (can't remember the repo or if it has been addressed or not) where there's a table listing multiple variable pricing items from a single purchase and the table shows the variable pricing options of the first item added to the cart on every subsequent item. As in...

**Purchased:**
Variable Pricing - Option One
Variable Pricing - Option Two

**Displaying on the table:**
Variable Pricing - Option One
Variable Pricing - Option One

So again, it's the first one added to the cart that seems to dominate. I suspect the only reason we don't see the same exact thing in my screenshot above is because #4457 hasn't been enhanced yet. 

Hope this makes sense.

**Comment by pippinsplugins** [comment]
I'm pretty sure we've seen and fixed this before so somewhere we've had a regression.

**Comment by SDavisMedia** [comment]
@pippinsplugins Found what I was referring to above in Commissions. May or may not be related. https://github.com/easydigitaldownloads/EDD-Commissions/issues/96

**Comment by pippinsplugins** [comment]
@SDavisMedia Probably not caused by the same thing but very similar.

**Comment by cklosowski** [comment]
Updated to properly detect if the item has variable pricing and also adds the variable price ID name to the download column.

Other improvements are switching to the `EDD_Payment` and `EDD_Customer` class for the data.
![screen shot 2016-05-04 at 12 28 12 pm](https://cloud.githubusercontent.com/assets/1390124/15026586/ea3d5054-11f3-11e6-8519-8e30d92b236f.png)

**Comment by pippinsplugins** [comment]
Confirmed PR fixes it.
