### ISSUE TITLE
Plugin update POST firing twice on "Dashboard" > "Updates"

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#4459]
Plugins built using the EDD_SL_Plugin_Updater class "Phone Home" twice when on the "Dashboard" > "Updates" page or the "Plugins" page. This may be un-necessary. 

The "plugins_api" hook is what's causing it to "phone home" twice on plugins and updates pages. If we cache the result of that for 24 hours in a transient (but not the result that comes through "pre_set_site_transient_update_plugins"), then "Dashboard" > "Updates" page will check for updates every time but only once every 24 hours on the "Plugins" page - and in turn only once every 24 hours will it check twice on the "Dashboard" > "Updates" page as well.

**Comment by mintplugins** [comment]
PR: ​https://github.com/easydigitaldownloads/Easy-Digital-Downloads/pull/4460

**Comment by pippinsplugins** [comment]
Let's get this in. Left a few small tweaks on the PR.
