### ISSUE TITLE
EDD Recount tool (customers) doesn't' have filters for post types.

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#4462]
Found this with recurring, there isn't  filter to include post types other than `edd_payment` in the `edd_get_payments()` calls.

**Comment by cklosowski** [comment]
Either the above @pippinsplugins or, we just make `Recurring` filters `edd_get_payments()` to include it's own post type for any call to `edd_get_payments().

**Comment by pippinsplugins** [comment]
Let's just make sure there is a filter to set the post statuses.

**Comment by cklosowski** [comment]
@pippinsplugins sounds good.

**Comment by cklosowski** [comment]
Easiest way to test is alongside Recurring issue 316
