### ISSUE TITLE
Past customer detail missing on Payment History & sales summary also wrong  

### ISSUE THREAD

**Issue by santhosh-r-wiredelta** [easydigitaldownloads/easy-digital-downloads#4470]
The problem is with purchases and customers not matching fully, leading to wrong stats and problems sending out emails, etc. 
List out major issues in given follow :
1) Payment History -> past customer name is missing but current customer working fine
2) Payment History -> Past View Order Detail is empty
How to fix this issue

**Comment by mindctrl** [comment]
@santhosh-r-wiredelta as mentioned in #4449, please open a support ticket at easydigitaldownloads.com/support.

Possibly related to https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4435.
