### ISSUE TITLE
Payment status ignored on download links

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#4473]
While we don't show links to downloads when a payment isn't completed, we should also be verifying it upon download as well.

**Comment by cklosowski** [comment]
Committed the fix so we can deploy, we should build a comprehensive set of unit tests around the file download process and URL generation (logging it)

**Comment by mintplugins** [comment]
Looks good - I have no permission to download file if the payment status is not complete. I do when it is complete.

**Comment by boluda** [comment]
Since updated to 2.5.11, there is a conflict with EDD recurring payments.
If a payment is "Renewal" I have no permission to download the files. It only affects customers who renewed at least once. Not sure if it's related with this issue, but I think it can be related.

**Comment by pippinsplugins** [comment]
@boluda We're addressing that in an update for Recurring Payments today.

**Comment by boluda** [comment]
@pippinsplugins Great!

**Comment by cklosowski** [comment]
@boluda that release should be out the door. Thanks for helping us test it out.

**Comment by boluda** [comment]
Glad to help!
