### ISSUE TITLE
Harden Discount Creation Process

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#4485]
Ran into an issue where a user was including a URL encoded character in a discount code: `25%25hrs`

The `%25` caused the discount to be invalid and so will anything else on this list: http://www.degraeve.com/reference/urlencoding.php

Suggestions from @cklosowski: only allow a-zA-Z0-9 and also throw a notice to admin when an invalid code is detected.

**Comment by cklosowski** [comment]
I've also noticed that you can create a discount, without entering anything into the discount title or code. We should prevent a discount from being created if the required fields aren't met...That brings up, what's a required field for a discount? I would think:

Title
Code
Discount type
Discount amount

The rest we can actually use defaults for, and make optional for the creation process.

**Comment by pippinsplugins** [comment]
>>>Title
>>>Code
>>>Discount type
>>>Discount amount

Seems right to me.

**Comment by sunnyratilal** [comment]
PR at #5323

**Comment by pippinsplugins** [comment]
Works great  for me!

**Comment by SDavisMedia** [comment]
All good for me on `issue/4485`. Validation works perfectly. :+1:

**Comment by pippinsplugins** [comment]
Merging then!
