### ISSUE TITLE
Disabling API request logging does not work

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#4486]
I've tried to disable API request logging using this filter:

``` php
add_filter('edd_api_log_requests', '__return_false' );
```

But even with that in an mu-plugin, it fails to disable logging.

**Comment by pippinsplugins** [comment]
Scratch that, it works in an mu plugin, just fails in plugins loaded after EDD core. We may want to look at adjusting the `$log_request` parameter to be set later so that we can disable it through a plugin that uses `plugins_loaded` or similar.

**Comment by NateWr** [comment]
I just ran into this myself, where I've added a custom endpoint and want just those requests to not be logged. I'm setting `EDD_API->log_requests = false` directly during my endpoint processing, but it'd be great to have an "official" way to change this that's forward-compatible.

Even just a `EDD_API->disable_log()` method would be handy so I know you're committed to keeping that function around.

**Comment by ericnicolaas** [comment]
@NateWr's approach is perfect. It also makes it possible to disable logging on certain endpoints, instead of disabling logging on _every_ endpoint. Obviously the `edd_api_log_requests` should still work, but I like having the option of keeping logging enabled for all but a few endpoints.

**Comment by sunnyratilal** [comment]
Ready for testing.

**Comment by pippinsplugins** [comment]
@sunnyratilal Having that method is nice but we still need to be able to disable it globally with the filter.

**Comment by sunnyratilal** [comment]
I'm at a loss here as to why the filter isn't working...

I've changed filter priorities, even have the entire `EDD` object instantiate on `plugins_loaded` but nothing seems to be doing the trick for me. 🤔

**Comment by cklosowski** [comment]
This filter is working fine on my end. I've dropped it into an MU plugin that I have in my local testing environment. With the filter set as above in the description, logs are not made on API Requests...when I remove that filter, it starts logging again.

**Comment by cklosowski** [comment]
ignore my comment....derp. read @pippinsplugins 2nd comment.

**Comment by cklosowski** [comment]
Give that a shot.

**Comment by sunnyratilal** [comment]
Filter works fine for me too

**Comment by pippinsplugins** [comment]
💰
