### ISSUE TITLE
Offer variation reporting

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#4487]
We should offer a pie chart for sales and another one for earnings of each variation of a download representative of the whole download. That way store owners could make informed decisions on adjustments on price or discontinuation of  variations

**Comment by pippinsplugins** [comment]
Definitely.

**Comment by mindctrl** [comment]
Closing this in favor of https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4889
