### ISSUE TITLE
Recount earning/sales tool for all downloads doesn't work

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#4488]
This might be caused by the fact that the new (correct) counts for earnings/sales would be 0. Probably a bad check

**Comment by pippinsplugins** [comment]
@chriscct7 Could you elaborate a little? Do you mean that you want everything to be 0 when done but it's not 0>

**Comment by chriscct7** [comment]
No, I mean if you have a bunch of orders, then delete them all via SQL and attempt to force a recount of the earnings and sales, even with the payment posts and meta removed, the recount fails to reflect the now-absent payments.

**Comment by pippinsplugins** [comment]
Which values did you delete, just the wp_posts entries with a `post_type` of `edd_payment`?

**Comment by chriscct7** [comment]
Deleted all posts with post type of WP payment, all associated post meta and all rows of customers table

**Comment by pippinsplugins** [comment]
Ah, that's why. The recount for individual products depends on the `edd_log` post type that has a log type of `sale`. You needed to delete those too.

**Comment by chriscct7** [comment]
I stand corrected. The following are done.

Any post in the post types edd_payment, edd_log, and edd_licenses are deleted, as well as any post meta associated to them. Additionally, any customers are deleted, along with any comments of type "edd_payment_note". Also any users, along with their associated meta, attached to the associated customers are deleted.

**Comment by pippinsplugins** [comment]
Hmm, ok, will try and replicate.

**Comment by chriscct7** [comment]
I've replicated this behavior when instead of using our importer, I use the EDD cli importer you guys wrote. If you use that to import payments and then use the SQL @cklosowski had for removing them, then recount earnings you'll see the same thing

**Comment by pippinsplugins** [comment]
@cklosowski any insights here?

**Comment by mintplugins** [comment]
I believe this is the same issue. 

1. Make a test purchase using the test gateway.
2. Refund it by manually updating the payment status.
3. Run the "recount all earning for all downloads".

The product's earning (in the product edit screen) will not reflect the refund. This only doesn't work for the "recount Earning and Sales for All Downloads" option. 

It works fine if you use the "Recount Earnings and Sales for A Download" option.

**Comment by michaelbeil** [comment]
Can confirm that this happens, but only with the test payment gateway.

**Comment by cklosowski** [comment]
So in some testing, this is only occurring when a download ONLY has refunded payments. I did this:
1) Make a purchase of a download
2) Refund that purchase
3) Recount all downloads
4) Earnings not corrected
5) Make another purchase
6) Recount all downloads
7) Earnings reflect correctly

This is due to the fact that we're looking for sales logs when we do the recount...so because we didn't have any logs for that download, it skipped over recounting. Will have to fix that up but @mintplugins @michaelbeil can you guys confirm that for me?

**Comment by mintplugins** [comment]
@cklosowski If I have 2 completed payments for "Product A" and refund one, I don't even have to do a recount as it is properly reflected immediately after the refunded payment is updated.

**Comment by cklosowski** [comment]
@mintplugins give this another try please?

**Comment by mintplugins** [comment]
Testing now

**Comment by mintplugins** [comment]
Using Recount All stats for All Downloads now works to reset refunded payments when they are the only purchased product. 

I also confirmed that when there is more than 1 payment it still does not require a recount. 

This looks all good to me!

**Comment by cklosowski** [comment]
Thanks @mintplugins
