### ISSUE TITLE
Deleting customers doesn't delete their subscriptions

### ISSUE THREAD

**Issue by boluda** [easydigitaldownloads/easy-digital-downloads#4489]
I noticed when I delete customers, even if I select "Delete all payments and records" in the UI, their subscriptions remain, obviously linked to nobody. I'm not sure if that's intencional.

**Comment by cklosowski** [comment]
I'll move this over to the Recurring repo so we can look into if this should/shouldn't happen or how we should handle it. I believe the logic should happen there, not in the core plugin.
