### ISSUE TITLE
The payment notes are included in normal comment count

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#4493]
On the comments page of WordPress, even though they're not displayed in the table, the number of payments logs is included in the count for comments.

**Comment by pippinsplugins** [comment]
Do you mean payment notes?

**Comment by chriscct7** [comment]
Yep sorry

**Comment by sunnyratilal** [comment]
This is weird it's _stopped_ working, we have the code in place for it to disregard comments of type `edd_payment_note`.

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/payments/functions.php#L1672-L1726

**Comment by cklosowski** [comment]
Looks like the `$pagenow` changed for editing comments.

**Comment by sunnyratilal** [comment]
Merged
