### ISSUE TITLE
EDD Emails-->Purchase Receipts & New Sale Notifications - Not Going Out!

### ISSUE THREAD

**Issue by GiantRecords** [easydigitaldownloads/easy-digital-downloads#4495]
Hello,
Completely new on EDD and trying to get my first Digital Download setup and working. Got everything and the confirmation page all adjusted and looking good. However when trying to customize the Emails for both Purchase Receipts & New Sale Notifications I have done something that now neither is being sent (or received anyway).

On the Purchase Receipts in Settings I did change the From Name, From Email, Purchase Email Subject and Purchase Email Heading fields to be more appropriate for the site. Plus put some details in the Purchase Receipt (body) to make the emailed receipt better. After doing so - I went and did another order to check it all out. But now the emails are no longer being sent.

Any ideas on what I might have done wrong or broken on this. I really appreciate any help I can get so we can get our first download fully working.
Thanks
David Huff
Giant Records

**Comment by michaelbeil** [comment]
Hi @GiantRecords!

Please go ahead and open a support ticket through our support portal: https://easydigitaldownloads.com/support

We use GitHub for development tracking only.
