### ISSUE TITLE
edd_get_ip Modification

### ISSUE THREAD

**Issue by nosegraze** [easydigitaldownloads/easy-digital-downloads#4498]
I'm using Varnish, which has `$_SERVER['HTTP_CLIENT_IP']` and `$_SERVER['HTTP_X_FORWARDED_FOR']` coming back as:

`<ip here>, 127.0.0.1`

The two IPs can cause issues for payment gateways and anything else that validates IPs (Taxamo integration).

It'd be great to check for multiple IPs like this and only grab the first result.

(Or just put `$_SERVER['REMOTE_ADDR']` first in the if statement, as that always comes back as expected and can't be modified by the client.)

**Comment by pippinsplugins** [comment]
Good idea, thanks!

**Comment by pippinsplugins** [comment]
I'm fairly certain this is fixed since https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4642
