### ISSUE TITLE
Fees cannot be processed by 3rd parties (no filters)

### ISSUE THREAD

**Issue by daigo75** [easydigitaldownloads/easy-digital-downloads#4500]
The logic to handle fees is pretty much hard-coded, without filters that allow their manipulation.

Proposed fix in [pull request 4490](https://github.com/easydigitaldownloads/easy-digital-downloads/pull/4490).

**Comment by pippinsplugins** [comment]
Thanks @daigo75, we'll get these in with 2.6.

**Comment by daigo75** [comment]
Thanks @pippinsplugins. Speaking of 2.6, when is the expected release date? Also, are there radical changes I should know about? From 1.9 to 2.4 was all smooth sailing, then 2.5 introduced breaking changes and now I'm keeping my eyes open.

**Comment by pippinsplugins** [comment]
It's planned for the end of May.

No significant changes are planned for 2.6. Make sure you've subscribed to our dev blog. We'll always post significant changes there: https://easydigitaldownloads.com/development/

**Comment by pippinsplugins** [comment]
Merged into `release/2.6`
