### ISSUE TITLE
The function "edd_readfile_chunked" has single EQUALS sign in If Statement

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#4504]
The edd_readfile_chunked function has a single equals sign in an if statement on line 712 of process-download.php

**Comment by mintplugins** [comment]
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/process-download.php#l712

**Comment by pippinsplugins** [comment]
@mintplugins That's not a bug, I don't believe. It sets `$size` to the file size and checks if it returned a value at the same time.

**Comment by mintplugins** [comment]
Closing.
