### ISSUE TITLE
Flat rate discounts can apply > than cart total

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#4506]
If you make a flat rate discount for $80 and apply it to a cart of $50, it correctly gives the order total remaining at checkout as $0, incorrectly lists the amount of discount applied at $80 instead of $50 and then shows the order total was -$30 on the purchase history shortcode

When a flat rate discount is applied, it should only apply up to the value of the cart at the time, re-evaluating whenever the taxes, cart total/quantity/items change, or when fees reapply

**Comment by pippinsplugins** [comment]
@chriscct7 Could you test this PR?

**Comment by mintplugins** [comment]
Tested https://github.com/easydigitaldownloads/easy-digital-downloads/pull/4545 and it fixes the issue here.

**Comment by pippinsplugins** [comment]
Great, merging.
