### ISSUE TITLE
EDD_Payment: Populate user_info, first_name, last_name, and email from attached customer ID if missing

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#4508]
If the meta data for `user_info`, `first_name`, `last_name`, and/or `email` is missing, we should automatically populate that information from the attached customer record when instantiating `EDD_Payment`.

**Comment by pippinsplugins** [comment]
See https://github.com/easydigitaldownloads/edd-recurring/issues/376

**Comment by cklosowski** [comment]
@pippinsplugins @mintplugins you ugys mind looking over this? I was trying to find a good way to ensure this without blasting away any data we already did have.

**Comment by pippinsplugins** [comment]
@cklosowski you're pulling from `EDD_Customer` even when `user_info` is not empty. I feel it should only be when it is empty.

**Comment by cklosowski** [comment]
@pippinsplugins We're pulling from the customer when `user_info` is empty OR `items are not there`, which is a potential problem in things that expect `first_name` or `last_name` to be set, but aren't for some reason.

**Comment by cklosowski** [comment]
The code finds things that are not set, and makes sure somehting exists...

**Comment by pippinsplugins** [comment]
ah! I missed that.

**Comment by pippinsplugins** [comment]
Works nicely.
