### ISSUE TITLE
Reporting: Incorrect earnings across a custom date range

### ISSUE THREAD

**Issue by sumobi** [easydigitaldownloads/easy-digital-downloads#4513]
Reporting is giving incorrect earnings across a custom date range. It's ignoring the days in both the first and last filter.

Eg:

1 January 2016 to 6th April 2016 = $100,000

Now modify the filter's end date to 30th April and you'll get the exact same amount:

1 January 2016 to 30th April 2016 = $100,000

Or:

7th January 2016 to 30th April 2016 = $100,000

However, if you run a custom filter within the same month, it will work fine. Eg:

1st April 2016 to 6th April 2016 = $10,000
1st April 2016 to 30th April 2016 = $100,000

Adding screenshots to show it happening (Chris K), Notice the date ranges are different in the filters, but the graphs are exactly the same:
![screen shot 2016-06-08 at 9 54 02 am](https://cloud.githubusercontent.com/assets/1390124/15902878/02484696-2d5f-11e6-86d3-b728980fb54d.png)

![screen shot 2016-06-08 at 9 53 48 am](https://cloud.githubusercontent.com/assets/1390124/15902886/0767d48e-2d5f-11e6-830c-b53db1ed3c1f.png)

**Comment by cklosowski** [comment]
Ok I've identified _why_ this happens. Right now, if you span more than 2 months in your custom date range we set the `$day_by_day` variable to `false`, a the data in the graph becomes completely incoherent at a certain point. However, the logic of how we calculate the data also changes, in that we no longer pass in each individual date of the month to calculate totals, we pass in `month` and `year` to get the earnings for the month defined.

Here is how we handle a `$day_by_date` query:
```

				if ( $day_by_day ) {

					$d = $dates['day'];

					if( $i == $month_end ) {

						$num_of_days = $dates['day_end'];

						if ( $month_start < $month_end ) {

							$d = 1;

						}

					} else {

						$num_of_days = cal_days_in_month( CAL_GREGORIAN, $i, $y );

					}
```

and how we handle a non-`$day_by_day`:
```
				} else {

					$sales = edd_get_sales_by_date( null, $i, $y );
					$sales_totals += $sales;

					$earnings = edd_get_earnings_by_date( null, $i, $y, null, $include_taxes );
					$earnings_totals += $earnings;

					if( $i == $month_end && $last_year ) {

						$num_of_days = cal_days_in_month( CAL_GREGORIAN, $i, $y );

					} else {

						$num_of_days = 1;

					}

					$date = mktime( 0, 0, 0, $i, $num_of_days, $y ) * 1000;
					$sales_data[] = array( $date, $sales );
					$earnings_data[] = array( $date, $earnings );

				}
```

I think what we need to do is change to always look day by day, and sum up the totals, just changing how we store them based off our `$day_by_day`. This way our reporting that is supposed to stop on the `1st` or `10th` of the month, won't actually calculate to the end of the month.

**Comment by pippinsplugins** [comment]
@sumobi could you please test this?

**Comment by sumobi** [comment]
@cklosowski I'm seeing these notices when defining a custom range

    PHP Notice:  Undefined index: range in wp-content/plugins/Easy-Digital-Downloads/includes/admin/reporting/graphing.php on line 274

    PHP Notice:  Undefined index: range in /wp-content/plugins/Easy-Digital-Downloads/includes/admin/reporting/graphing.php on line 292

**Comment by cklosowski** [comment]
Update incoming.

Chris Klosowski
cklosowski@gmail.com
@cklosowski

**Comment by sumobi** [comment]
From what I've tested all seems to be good so far

**Comment by cklosowski** [comment]
@pippinsplugins can you look at this too? @sumobi is getting those two notices above, however I'm not getting them. He's seeing it just by visiting the `Downloads > Reports`

**Comment by sumobi** [comment]
Fixed!

**Comment by cklosowski** [comment]
Merging into 2.6 and closing, then I'll get working on the #4035 fix with this rolled into it.

**Comment by pippinsplugins** [comment]
:+1:
