### ISSUE TITLE
Function edd_get_variable_prices() returns prices even if variable prices is disabled

### ISSUE THREAD

**Issue by Just-m** [easydigitaldownloads/easy-digital-downloads#4515]
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/62f4ad4c0e95f86667cb2ab2687fcd3c770e154f/includes/download-functions.php#L236

It might be policy to not remove variations immediately just in case someone changes his/her mind, but using the above mentioned function results in wrong data. The deleted variations also show up.

It could be solved by adding an edd_has_variable_prices() check to the function but I am too unfamiliar wiht the software structure to know if that would be the way to go.

**Comment by pippinsplugins** [comment]
@Just-m It doesn't return deleted variations. The only way that could happen is if your database is aggressively cached and the cache simply hasn't updated yet.

**Comment by Just-m** [comment]
I did some more testing.

This happens when you disable 'variable pricing' without deleting the variations first.
`edd_has_variable_prices()` will correctly return `false`
`edd_get_variable_prices()` will return an array of variations.

I was looking for a function that would return $9.00 if it was a single price, and $9.00 - $19.00 in case of variations. 
`edd_price()` only returns one price, which is not enough in all cases
`edd_price_range()` returns $9.00 - $9.00 on a single price, which is too much

Then I tried to use `edd_get_variable_prices()` to create the format I was looking for, but it showed prices no longer valid.

I ended up using:
```
			if( edd_has_variable_prices( $id ) ) {
				$price = edd_price_range($id);
			} else {
				$price = edd_price( $id, false);
			}
```
not sure it is the best way but it works.

**Comment by pippinsplugins** [comment]
Ah! Yes, that makes sense. I don't see any reason we can't take care of that.

**Comment by sunnyratilal** [comment]
Tested and confimred working

**Comment by topher1kenobe** [comment]
Confirmed improper on master.

**Comment by topher1kenobe** [comment]
Confirmed issue/4515 fixes.
