### ISSUE TITLE
edd_new_user_notification() does not set email headings properly

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#4516]
The new user notification email does not set the header properly.

Example:
![screen shot 2016-04-25 at 7 48 53 am](https://cloud.githubusercontent.com/assets/1034109/14787865/31184b14-0aba-11e6-88f7-515ecf72be02.png)

This happens because we're not setting up a new instance of the `EDD_Emails` class.

**Comment by pippinsplugins** [comment]
@topher1kenobe can you please test this

**Comment by topher1kenobe** [comment]
@pippinsplugins I was never able to replicate locally, only on his site.  Is there something I could do to trigger it?

**Comment by pippinsplugins** [comment]
As long as it works properly locally, that will be sufficient.

**Comment by topher1kenobe** [comment]
I get these:

Notice: Undefined variable: from_name in /home/topher_edd/edd.derosia.com/wp-content/plugins/easy-digital-downloads/includes/user-functions.php on line 492

Notice: Undefined variable: from_name in /home/topher_edd/edd.derosia.com/wp-content/plugins/easy-digital-downloads/includes/user-functions.php on line 501

I'll turn off debug and try again

**Comment by topher1kenobe** [comment]
Actually, the email went through fine.  It looks the same as master for me, I have a logo instead of that text.

**Comment by pippinsplugins** [comment]
Screenshot please.
