### ISSUE TITLE
Add SSL notice in PayPal settings for IPN verification

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#4519]
To prepare for the SSL requirement for IPN verification coming from PayPal in September, 2016, we should add notice text to the IPN verification settings in the PayPal gateway settings:
![screen shot 2016-04-27 at 3 44 11 pm](https://cloud.githubusercontent.com/assets/1034109/14867607/ea4067c2-0c8e-11e6-88e9-18ca3bee5789.png)

**Comment by cklosowski** [comment]
@pippinsplugins is this the matter of detecting if SSL is disabled, show a notice that IPN Verification requires SSL?

**Comment by pippinsplugins** [comment]
Yes.

**Comment by cklosowski** [comment]
@easydigitaldownloads/core-devs Thoughts on this notice when the `is_ssl` check fails (site isn't configured for SSL)
![screen shot 2016-05-16 at 10 34 51 am](https://cloud.githubusercontent.com/assets/1390124/15297962/d8fe5cfe-1b51-11e6-8b1f-8a721bef98d2.png)

**Comment by SDavisMedia** [comment]
I don't see anything wrong with that.

**Comment by mindctrl** [comment]
@cklosowski Maybe link to our docs? http://docs.easydigitaldownloads.com/article/1199-do-i-need-ssl or http://docs.easydigitaldownloads.com/article/994-how-to-set-up-ssl or something like that?

**Comment by cklosowski** [comment]
@mindctrl Yeah I'll do that too

**Comment by pippinsplugins** [comment]
I don't think the message is very clear.

It needs to convey several pieces of information:

1. SSL is only required for IPN verification.
2. IPN Verification !== IPN processing for marking payments as complete.

Can we update both the non-SSL notice and the description of the setting to better explain exactly what it does?

**Comment by spencerfinnell** [comment]
Agreed with @pippinsplugins -- the notice should also only display if there is no SSL and the setting is unchecked. 

Is it feasible to invert the setting as well? I know I always harp on this but for some reason reversed check boxes kill me. I think it would make creating an easy to understand description easier as well.

**Comment by spencerfinnell** [comment]
Doesn't look like it without an upgrade routine after looking at how checkboxes are stored. Nevermind!

**Comment by pippinsplugins** [comment]
How's this? Note: I have not inverted the settings.
![screen shot 2016-05-20 at 3 18 16 pm](https://cloud.githubusercontent.com/assets/1034109/15441028/2b5763de-1e9e-11e6-8a53-97c0fc45dd9e.png)

**Comment by michaelbeil** [comment]
Looks good to me.

**Comment by cklosowski** [comment]
I'm good with that @pippinsplugins

**Comment by stephenharris** [comment]
Is this related to [this announcement](https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&id=FAQ1916&viewlocale=en_US)? If so, the date has been moved recently to June 30th 2017. But also, I think SSL is not required on the server, just the endpoint needs to be https rather than http:

> When used for IPN postbacks, www.paypal.com will only accept HTTPS connections.

and

> If you are using PayPal’s Instant Payment Notification (IPN) service, you will need to ensure that HTTPS is used when posting the message back to PayPal for verification
> --  https://devblog.paypal.com/upcoming-security-changes-notice/#ipn

**Comment by pippinsplugins** [comment]
@stephenharris Yes it is related to that announcement. Good to see the date changed. @topher1kenobe could you get the doc updated please?

We did more digging and were able to (almost positively) determine that the IPN URL has to use https. Happy to be wrong though!

**Comment by stephenharris** [comment]
This seems to clarify they meant only validation requests **to** Paypal. From the "In A Nutshell" paragraph here: https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&id=FAQ1916&viewlocale=en_US

> In the past, PayPal has allowed the use of HTTP for these postbacks. For increased security going forward, only HTTPS will be allowed for postbacks to PayPal. **At this time, there is no requirement for HTTPS on the outbound IPN call from PayPal to the merchant’s IPN listener**

**Comment by pippinsplugins** [comment]
It does appear that way.

@chriscct7 can you verify?

**Comment by chriscct7** [comment]
That's affirmative. They moved back the dates. They've also dropped the initially proposed requirement that the originating POST back IPN verification call, separate from the one mentioned above, must originate over https. This means, for now, PayPal will not require PayPal Standard customers to use an SSL certificate on their site

However, this does mean that this: 
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/gateways/paypal-standard.php#L283

Needs to be changed so that the protocol used when determining the url to post to is always https:// which is what we currently default to, but I'm gonna explicitly set it to false in a pr so we don't forget that its there for a reason later.

**Comment by pippinsplugins** [comment]
Pinging @topher1kenobe

**Comment by topher1kenobe** [comment]
Visually this looks pretty janky to me. Some margin above the alert would be nice.
![Uploading Screen Shot 2016-05-27 at 1.01.31 PM.png…]()

**Comment by pippinsplugins** [comment]
To sum up, I believe the action needed here is:

1. Ensure our IPN verification calls go to https:
2. Remove the warning message we added
3. Update our http://docs.easydigitaldownloads.com/article/1244-do-i-need-ssl-if-i-use-paypal 

Yes?

**Comment by topher1kenobe** [comment]
Sounds right to me.

**Comment by pippinsplugins** [comment]
Done.
