### ISSUE TITLE
Change plugins screen description 

### ISSUE THREAD

**Issue by michaelbeil** [easydigitaldownloads/easy-digital-downloads#4521]
Per a discussion in Slack, @wordmaid brought up a good point that we should change the copy of the description that shows in the plugin dashboard that is taken from the header in easy-digital-downloads.php. 

Currently it is `Serve Digital Downloads Through WordPress`.

Proposed descriptions:
- `Sell digital products with WordPress, easily.`
- `An eCommerce system that allows you to sell digital products, easily.`
- `A free eCommerce system that allows you to sell digital products, easily.`
- `The easiest way to sell your digital products through WordPress.`
- `Easily sell digital products with WordPress.`

The final proposal seems to have the most traction.

**Comment by chriscct7** [comment]
I strongly think it should be "The world's easiest way to sell digital downloads through WordPress" as that would match our existing branding on the homepage of our website.

**Comment by pippinsplugins** [comment]
I agree with @chriscct7 unless we also choose to change the description on the site.

**Comment by wordmaid** [comment]
I think "The world's" is a bit redundant. I think it could simply be "The easiest way to sell digital products with WordPress." Obviously a good point for discussion.

**Comment by pippinsplugins** [comment]
I like that @wordmaid

**Comment by michaelbeil** [comment]
I like that too @wordmaid. 

We can wait for further consensus.

**Comment by cklosowski** [comment]
:+1: to the modifications that @wordmaid suggested:

`The easiest way to sell digital products with WordPress.`

**Comment by BurlesonBrad** [comment]
_....after using Woo's API manager for plugins and themes...._
I'm pretty sure it should read nothing short of

# THE WORLD

...all caps | italicized | bold | underlined | my space blinky text | and all capital letters...

_but that's just an educated opinion from **both** sides of the fence_

:laughing: :+1:
