### ISSUE TITLE
Negative value on price

### ISSUE THREAD

**Issue by raphcadiz** [easydigitaldownloads/easy-digital-downloads#4523]
The user is able to input a negative value of price, sample "-23" I think this is something we shouldn't let the user to do

**Comment by pippinsplugins** [comment]
Confirmed.

**Comment by cklosowski** [comment]
Being that I'm going to do this via the `register_meta` attributes, I'm going to do it within #4807

**Comment by cklosowski** [comment]
Ok pushed an update to `issue/4807` that should resolve this and not allow negative values.

**Comment by sunnyratilal** [comment]
Just tested - all good

**Comment by pippinsplugins** [comment]
All good here!
