### ISSUE TITLE
edd_format_ammount doens't add a currency symbol as described in the docs

### ISSUE THREAD

**Issue by rnovotny** [easydigitaldownloads/easy-digital-downloads#4524]
http://docs.easydigitaldownloads.com/article/551-edd-format-amount

It won't by default send a currency symbol, just the price:

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/formatting.php#L111

**Comment by pippinsplugins** [comment]
That's a documentation error. To add the currency sign, use `edd_currency_filter( $amount )`.

**Comment by topher1kenobe** [comment]
Docs are now updated. http://docs.easydigitaldownloads.com/article/551-edd-format-amount
