### ISSUE TITLE
Free Downloads - custom button text not appearing

### ISSUE THREAD

**Issue by garnetsolutions** [easydigitaldownloads/easy-digital-downloads#4525]
Hi - I just purchased the Free Downloads extension for WordPress and am trying out my first download. I have click "Insert Download" from inside a post and filled in the information, including custom text for the button. However, the button says "Download Now". Why is the custom text not working?

**Comment by pippinsplugins** [comment]
Hi there!

Please go ahead and open a support ticket through our support portal: https://easydigitaldownloads.com/support

we use GitHub for development tracking only.

**Comment by garnetsolutions** [comment]
Thanks! I couldn't find a Support link on the easydigitaldownloads.com
site. That's how I ended up at Github.

Ellie

On Fri, Apr 29, 2016 at 11:08 AM, Pippin Williamson <
notifications@github.com> wrote:

> Hi there!
>
> Please go ahead and open a support ticket through our support portal:
> https://easydigitaldownloads.com/support
>
> we use GitHub for development tracking only.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4525#issuecomment-215747594>
>



-- 
Ellie Boynton
President, Garnet Solutions
Phone: 617-216-6163
Website: http://garnet-solutions.com
Email: ellie@garnet-solutions.com
LinkedIn Profile <http://www.linkedin.com/profile/view?id=68078357>
