### ISSUE TITLE
Free Downloads question about multiple downloads

### ISSUE THREAD

**Issue by garnetsolutions** [easydigitaldownloads/easy-digital-downloads#4526]
Hi - My client wants me to set up a email-before-download kind of function whereby the user is only asked once for their email information. After the first download where they provide the email, they should be able to download all other PDF documents on the website without entering their email. Can Easy Digital Downloads in combination with the Free Downloads extension work this way? Thank you!

**Comment by pippinsplugins** [comment]
Hi there!

Please go ahead and open a support ticket through our support portal: https://easydigitaldownloads.com/support

we use GitHub for development tracking only.
