### ISSUE TITLE
Make Download ID more visible

### ISSUE THREAD

**Issue by topher1kenobe** [easydigitaldownloads/easy-digital-downloads#4529]
Right now the only way for a store owner to get a download ID is to look at a URL for the admin page. That's either by loading that page, or hoverng over a link for it. I'd like to see it either in the admin listing or in the Publish box when editing a doc.  Example image attached.
![selection_358](https://cloud.githubusercontent.com/assets/341412/14962548/60cac676-106d-11e6-8286-55ccc11d4dd9.png)

**Comment by pippinsplugins** [comment]
:+1:

**Comment by WPprodigy** [comment]
The quick links / row actions could maybe work for the admin listings section: 

![](http://cld.wthms.co/n9DB/19W8K8Q3+)

Alternatively, it could get it's own column as well http://cld.wthms.co/10AUn/1MbJaFx5 (probably not first).

**Comment by pippinsplugins** [comment]
I like the idea of showing it in the list table row actions too.

**Comment by spencerfinnell** [comment]
I would definitely say Row Actions over another column.

**Comment by pippinsplugins** [comment]
Merged into `release/2.6`!

**Comment by pippinsplugins** [comment]
![screen shot 2016-05-16 at 9 25 40 am](https://cloud.githubusercontent.com/assets/1034109/15292322/3120ce26-1b48-11e6-96ef-0f326f66c814.png)
