### ISSUE TITLE
Recurring Payments with Stripe not working

### ISSUE THREAD

**Issue by mdpradeep** [easydigitaldownloads/easy-digital-downloads#4532]
I have deployed EDD, EDD Recurring Payments plugin + Stripe plugin. However, EDD and the Stripe plugin integration does not seem to be working. When I make a purchase through credit card, I get a blank screen after entering the credit card details, etc (I am using 4242424242424242). Also, the webhooks are not working. It gives me a "file not found" error. I have gone through the documentation on EDD to configure keys, etc, but it did not help me. Is there something obvious I am missing ? Can you point me to some doc/tutorial on how to set this up ??

**Comment by mdpradeep** [comment]
The stripe setting is fine now.  The error I see in the logs when I do a purchase is as below:
```
2016/05/03 09:58:52 [error] 1680#0: *844 FastCGI sent in stderr: "PHP Fatal error:  Call to undefined function Stripe\HttpClient\curl_init() in /home/ubuntu/eComm/Products/wp-content/plugins/edd-stripe/vendor/stripe/stripe-php/lib/HttpClient/CurlClient.php on line 55" while reading response header from upstream,
client: 59.95.69.238, server: 146.148.63.220, request: "POST /Products/?page_id=5&payment-mode=stripe HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host:
"146.148.63.220", referrer: "http://146.148.63.220/Products/?page_id=5&payment-mode=stripe"
```

**Comment by mdpradeep** [comment]
Figured it out. After upgrading curl library, this went through.

**Comment by cklosowski** [comment]
Ok. In the future. Please open a support request at easydigitaldownloads.com/support for issues like this. GitHub is for development only and this repository is for the core Easy Digital Downloads project, not stripe or recurring.
