### ISSUE TITLE
Fes Translation

### ISSUE THREAD

**Issue by mmosa** [easydigitaldownloads/easy-digital-downloads#4533]
Hello
I am using (Edd Fes) plugin.
  I tried to translate it and after a few days it got translated.
Into "Arabic language"
After I finished

Problems have   arisen.
Links do not work well. (For approved vendors) (or reject them)

Page "vendors" is in disarray!
and ... @!@

Please help me.
what should I do?
![fes](https://cloud.githubusercontent.com/assets/19174280/14994012/d846b73a-1182-11e6-9fcf-61346e1ff43d.png)

**Comment by pippinsplugins** [comment]
Hi there!

Please go ahead and open a support ticket through our support portal: https://easydigitaldownloads.com/support

we use GitHub for development tracking only.

**Comment by mmosa** [comment]
But only pre-sale questions possible!
The rest of the questions are FAQ!

**Comment by pippinsplugins** [comment]
See the bottom of the page for opening a ticket. You need to first enter a subject.
