### ISSUE TITLE
Likely outdated mail subscribe link on welcome screen

### ISSUE THREAD

**Issue by rene-hermenau** [easydigitaldownloads/easy-digital-downloads#4534]
welcome.php -> `Get Alerted About New Tutorials` contains link http://eepurl.com/kaerz which leads to 
![Alt text](https://monosnap.com/file/enpqJV8H0tX6ER5ApKeDs1ds0xI7cP.png)

![Alt text](https://monosnap.com/file/dbQvICuqgah5AWOW3cHjFrun2fGQ3G.png)

Probably no one will use that large form to subscribe

**Comment by cklosowski** [comment]
@SDavisMedia do we have a URL for the mailing list landing page?

**Comment by SDavisMedia** [comment]
@cklosowski Not yet.

**Comment by cklosowski** [comment]
Ok if we can have one by 2.6 I'll update it for that. Otherwise we'll punt until that's ready.

**Comment by pippinsplugins** [comment]
Looks like all of those merge fields were made public accidentally. I'll fix that then this is okay to leave until we have the dedicated page.

**Comment by pippinsplugins** [comment]
Better.
![Uploading Screen Shot 2016-05-04 at 10.35.34 AM.png…]()

**Comment by pippinsplugins** [comment]
Committed fix to release/2.6 for `https://easydigitaldownloads.com/subscribe`.
