### ISSUE TITLE
Deleted Downloads Remain in Cart

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/easy-digital-downloads#4539]
If you add some downloads to the cart, delete the downloads (I reset the database) and view the cart again the deleted items still appear in the cart: https://cldup.com/2EpImrOYxE.png

`edd_get_cart_contents()` should filter published downloads only (or at least in the cart template).

**Comment by cklosowski** [comment]
a little Work In Progress, pausing and committing up what I have for now to focus on 2.6.3 release.

**Comment by pippinsplugins** [comment]
@cklosowski see comment on PR

**Comment by cklosowski** [comment]
Fixed.
