### ISSUE TITLE
Ensure Amazon Gateway details exist if active

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#4542]
If the Amazon gateway is active but no details have been filled out, it will put errors in the console. We should check to make sure the Amazon details are not empty prior to enqueueing any JS related to it. 

Additionally, a notice on the checkout about the fields being blank could be helpful to the Site Owner.

**Comment by sunnyratilal** [comment]
Tested and working as expected! 👍

**Comment by sunnyratilal** [comment]
Merged into `release/2.7`
