### ISSUE TITLE
edd fes issue get stock

### ISSUE THREAD

**Issue by sameern72** [easydigitaldownloads/easy-digital-downloads#4546]
in any product page.

http://www.4framess.com/downloads/exhibition-stall-4efs0011-3/

Catchable fatal error: Object of class WP_Error could not be converted to string in /home1/ozowavec/public_html/4framess.com/wp-content/plugins/edd-fes/classes/fields/taxonomy.php on line 209

disable plugin is resolving issue. but while again installing fes .problem is same. please help to resolve this issue.

**Comment by pippinsplugins** [comment]
Hi there!

Please go ahead and open a support ticket through our support portal: https://easydigitaldownloads.com/support

we use GitHub for development tracking only.
