### ISSUE TITLE
Flot options

### ISSUE THREAD

**Issue by kiarashi** [easydigitaldownloads/easy-digital-downloads#4547]
If possible, can we have more flot options?
Especially line colors, width, fill, curved lines, etc. Same for "points".

http://docs.easydigitaldownloads.com/article/498-edd-graph

**Comment by pippinsplugins** [comment]
@kiarashi Are you wanting these for an add-on that is utilizing the EDD_Graph class?

**Comment by kiarashi** [comment]
Yes, that's right. 
The commission extension uses the EDD_Graph class.
Right now, we're stuck with WP standard and plain styling, while with _flot_ some really awesome stuff is possible.

**Comment by kiarashi** [comment]
Just a quick question, are the extra flot options added inside 2.8?

**Comment by cklosowski** [comment]
No, it was removed from the milestone for the meantime.

**Comment by kiarashi** [comment]
Will it be added in the future or is it too complicated to add these options? 
No pressure or anything. I'm just wondering if I should continue to wait or look for another solution. :)

**Comment by cklosowski** [comment]
I do believe that's it's a beneficial change, so we'll probably still include it.

**Comment by cklosowski** [comment]
With the new EDD Graphing for reporting in EDD 3.0, this will become a moot point. The new graphing API isn't going to use Flot anymore, we'll be moving to ChartJS
