### ISSUE TITLE
Extentions extension settings for subsections - checkbox is not saved if it's unchecked

### ISSUE THREAD

**Issue by metodiew** [easydigitaldownloads/easy-digital-downloads#4554]
I've noticed that one one the extensions I'm working at doesn't save the checkboxes and I was thinking that I'm doing something wrong. This might be still the case, though :)

While I was updating the Extensions subsction, following the instructions from here
https://easydigitaldownloads.com/development/2016/01/07/updating-extension-settings-for-subsections-in-2-5/ I've noticed the example code also have issues.

Steps to reproduce:
1) copy the example code
2) Go to Extensions tab, check the checkbox and save.
3) Uncheck the checkbox, edit the text from the input field and save.
4) You'll see the text is updated, but the checkbox still stays checked.

I'll be more than happy to work on a fix, if this issues is confirmed

**Comment by pippinsplugins** [comment]
@metodiew We've seen this a few times now. You said `one of the extension`. Does that mean the other extensions works fine? Is there anything different in the settings code?

**Comment by metodiew** [comment]
Sorry, a long day and bad choice of words :)

The extension itself is not related, because I've noticed that issue with the example code from the URL above, so it looks like a EDD issue

**Comment by pippinsplugins** [comment]
Could you test your extension against the `release/2.6` branch? Does it work there? We've been making some changes to the settings save process that are related to this.

**Comment by metodiew** [comment]
Now, I've tested it one more time and it's working with the latest `master` and `release/2.6`. It might be some issue on my local installation. As I said, it was a long day :)

Thanks for the quick reaction, I'll the issue :+1:

**Comment by pippinsplugins** [comment]
:+1:
