### ISSUE TITLE
a11y: Active tab doesn't fit div area

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#4557]
![image](https://cloud.githubusercontent.com/assets/1324637/15130860/83cf093c-1619-11e6-847b-4d1ebffa644c.png)

See how tab select doesn't fit button tab size

**Comment by pippinsplugins** [comment]
Related: #3798

**Comment by sunnyratilal** [comment]
This bug doesn't exist anymore: 
![image](https://cloud.githubusercontent.com/assets/1525554/19908782/aa59fd44-a07c-11e6-9e6a-cfc83bca603c.png)

@chriscct7 are you still seeing it?

**Comment by sunnyratilal** [comment]
Closing as bug doesn't exist anymore.
