### ISSUE TITLE
Improve placeholders on product dropdown to help indicate searchability

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#4560]
We see a lot of users misunderstand that the product drop down is searchable, resulting in them opening a ticket to ask how they can select products not included on the list.

To improve this, we should adjust the placeholders shown on the product drop down.

**Comment by pippinsplugins** [comment]
Before:
![screen shot 2016-05-11 at 11 51 48 am](https://cloud.githubusercontent.com/assets/1034109/15189134/c5967c0a-176e-11e6-96d7-d2a0491bc7df.png)

After:
![screen shot 2016-05-11 at 11 47 21 am](https://cloud.githubusercontent.com/assets/1034109/15189116/b6babb92-176e-11e6-99c1-a42b11229494.png)

**Comment by pippinsplugins** [comment]
Oh, changed search placeholder to `Type to search all Downloads`

**Comment by michaelbeil** [comment]
Works great!

**Comment by mintplugins** [comment]
Works good here
