### ISSUE TITLE
Add "author" paramater support to [downloads] shortcode

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#4570]
It would be nice to have the option to filter downloads by a specific author in the [downloads] shortcode. 

Currently, this could be done with the 'edd_downloads_query' filter here:
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/shortcodes.php#L496

However, adding support for it as a shortcode paramater should be pretty straightforward to add.

**Comment by cklosowski** [comment]
I had to do this for someone recently, I believe it should just be as easy as something like this:
```
	/**
	 * If the `author` attribute is in the shortcode, filter by it
	 */
	public function downloads_by_author( $query, $atts ) {

		if ( isset( $atts['author'] ) ) {
			$query['author'] = absint( $atts['author'] );
		}

		return $query;

	}
```

Obviously not in a filter function like this, but it's not hard at all.

**Comment by michaelbeil** [comment]
Works well here.

**Comment by mintplugins** [comment]
Working well here as well with author IDs

1. Is it possible to make it work for usernames as well:
[downloads author="the_persons_username"]

2. Is it possible to make it work for multiple IDs or usernames:
[downloads author="the_persons_username1, the_persons_username2"]
[downloads author="1, 2"]
[downloads author="1, the_persons_username2"]

**Comment by pippinsplugins** [comment]
To support usernames, we'll need to set `author_name` if the value passed is not an int.

**Comment by cklosowski** [comment]
Let me see if I can cook something up for that.

**Comment by cklosowski** [comment]
@pippinsplugins there is some odd behavior with mixing the `author` and `author_name` attributes, mixing them sometimes give's odd results, especially with logins that are email addresses (in my testing). I'm going to write it so that if a non-numeric is seen, we lookup by the login and get the ID for the user.

**Comment by pippinsplugins** [comment]
:+1

**Comment by SDavisMedia** [comment]
All gravy here. I tried every combination I could think of with three different authors. :+1:
