### ISSUE TITLE
Rename Download List Table Taxonomy Headers

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/easy-digital-downloads#4578]
With #4232 and #4529 in now I think it would make sense to rename to "Download Categories" and "Download Tags" headers in the List Table. 

![3120ce26-1b48-11e6-96ef-0f326f66c814](https://cloud.githubusercontent.com/assets/4752949/15304102/0f995ca8-1b81-11e6-9780-76ae717a856a.png) 

None of the other columns are prefixed and it takes up probably 20% of the width currently.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by michaelbeil** [comment]
This is good to be merged once the unit tests are updated.

**Comment by sunnyratilal** [comment]
Post type labels unit tests failed because I added an extra label. Will rewrite the tests and then rebuild

**Comment by sunnyratilal** [comment]
Merged
