### ISSUE TITLE
Replace all instances of get_post_meta() for payments with edd_get_payment_meta()

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#4580]
There are a few places where get_post_meta() is still used for retrieving payment meta data. These should all be replaced with `edd_get_payment_meta()` to aide in the gradual process of [moving to custom tables](https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4576).

**Comment by sunnyratilal** [comment]
All working good here 👍

**Comment by sunnyratilal** [comment]
Merged into `release/2.7`
