### ISSUE TITLE
Checkboxes not able to be unchecked when single extension using subsections

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#4589]
Due to the changes in https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4211, if you have a single extension that makes use of the extensions tab AND it uses subsections, you cannot uncheck checkboxes.

This is due to the fact that the section isn't in the `referrer` so we are looking at the wrong whitelist when unsetting checkboxes.

**Comment by pippinsplugins** [comment]
Replicated the problem and this fixes it for me.

**Comment by cklosowski** [comment]
@mindctrl @SDavisMedia @mintplugins can you guys replicate, and then test this out please?

**Comment by SDavisMedia** [comment]
I can't replicate the original issue on `master`. Tried Free Downloads, Software Licensing, and Commissions.

**Comment by cklosowski** [comment]
@SDavisMedia can you verify with Mailchimp?

**Comment by SDavisMedia** [comment]
@cklosowski Everything's working properly with MailChimp as well.

**Comment by pippinsplugins** [comment]
@SDavisMedia I replicated it on `master`. Can you confirm you only had _one_ extension active? Example, only MailChimp.

**Comment by SDavisMedia** [comment]
@cklosowski @pippinsplugins replicated and confirmed `issue/4589` fixes the problem.

**Comment by mintplugins** [comment]
Replicated on Master. Confirmed https://github.com/easydigitaldownloads/easy-digital-downloads/pull/4590 fixes it. I was not able to save checkboxes and now I can.

**Comment by topher1kenobe** [comment]
I'm testing with ONLY Software Licensing on master and can't replicate.

**Comment by cklosowski** [comment]
@topher1kenobe can you try with Mailchmp? that is one we know has the issue.

**Comment by topher1kenobe** [comment]
ok, this is new.  I had 2 extensions, set a checkbox, removed the second extension, and was able to uncheck the box.

Boxes checked WHILE there's only one cannot be unchecked.  Replicated that way.

I'll test the branch.

**Comment by topher1kenobe** [comment]
issue/4589 fixes for me.

**Comment by cklosowski** [comment]
@topher1kenobe perfect, that's the bug we're trying to fix, thanks!

**Comment by pippinsplugins** [comment]
I'm going to go ahead and merge this then and deploy to .org.
