### ISSUE TITLE
Change "Disable Guest Checkout" to "Require Login"

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#4591]
Currently the setting for "Disable Guest Checkout under "Settings" > "Misc" > "Checkout Settings" is a double negative. If it were a positive, it would be more clear. Currently, we are checking a box to turn it off - which is hard to understand.

I recommend changing the name of the option from "Disable Guest Checkout" to "Require Login".

**Comment by SDavisMedia** [comment]
@pippinsplugins I adjusted the tooltip title to match the setting title adjustment. All good here, though. :+1:

**Comment by pippinsplugins** [comment]
Good catch,

**Comment by mintplugins** [comment]
Fixed docs here: 
http://docs.easydigitaldownloads.com/article/1080-buy-now-buttons
http://docs.easydigitaldownloads.com/article/868-misc-settings
http://docs.easydigitaldownloads.com/article/1219-checkout-fields-manager-field-types

**Comment by pippinsplugins** [comment]
:+1:
