### ISSUE TITLE
Remove comment / trackback counts from oEmbed previews

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#4592]
Comments and trackbacks have no purpose for the vast majority of EDD installs. Let's remove those details from the oEmbed previews if we can.

The Product Reviews extension could then add in review counts in place of comments.

Related: #4064

**Comment by pippinsplugins** [comment]
Thanks for the PR @Defrothew! We'll get it tested and included in the 2.7 release.

**Comment by cklosowski** [comment]
We're moving this up to EDD 2.6, Testing it now.

**Comment by cklosowski** [comment]
This works great, going to merge this when it passes CI
