### ISSUE TITLE
Title issues with New User email alerts

### ISSUE THREAD

**Issue by topher1kenobe** [easydigitaldownloads/easy-digital-downloads#4596]
When someone uses [edd_register] to create a new user it send an email to the user.  For one customer the title is incorrect saying "Sales Invoice"
<img width="660" alt="screen shot 2016-05-19 at 4 06 59 pm" src="https://cloud.githubusercontent.com/assets/341412/15408933/90253516-1de0-11e6-9c07-34eb443a98f5.png">

For me at http://topher1kenobe.is-a-geek.net/edd-registration/ I get no title at all.
<img width="671" alt="screen shot 2016-05-19 at 4 07 14 pm" src="https://cloud.githubusercontent.com/assets/341412/15408952/aabbef82-1de0-11e6-831a-89988cd0935c.png">

This had a previous fix at https://github.com/easydigitaldownloads/easy-digital-downloads/pull/4517/commits which is indeed in the latest version.

**Comment by pippinsplugins** [comment]
@topher1kenobe can you please get me the support ticket that reported this?

**Comment by cklosowski** [comment]
@pippinsplugins @topher1kenobe When registering via the `[edd_register]` shortcode I'm actually seeing with Topher is seeing, no header, but I'm not getting that 'Sales Invoice' that this person is seeing:
![screen shot 2016-05-25 at 11 06 22 am](https://cloud.githubusercontent.com/assets/1390124/15550993/c1686b5c-2268-11e6-8c20-937c982661b9.png)

**Comment by pippinsplugins** [comment]
So header definitely isn't always getting set

**Comment by pippinsplugins** [comment]
No idea why cc8cfeae0958f66873ed47c90c8e73fd25df3dc7 fixed it before but reverting to `EDD()->emails` works properly for me now.

**Comment by cklosowski** [comment]
Testing now.

**Comment by cklosowski** [comment]
![screen shot 2016-05-25 at 3 39 00 pm](https://cloud.githubusercontent.com/assets/1390124/15558413/d7875968-228e-11e6-9946-fc55c2540e0a.png)

Looks better, only thing I can think now is that I did this via the `[edd_register]` shortcode, yet the password states `Password entered at checkout`. Going to see if we can fix that quick

**Comment by cklosowski** [comment]
When registered via checkout
![screen shot 2016-05-25 at 4 02 46 pm](https://cloud.githubusercontent.com/assets/1390124/15558841/2454ba6c-2292-11e6-83c3-6af5a52d4e35.png)

When registered via the `[edd_register]` shortcode
![screen shot 2016-05-25 at 4 03 23 pm](https://cloud.githubusercontent.com/assets/1390124/15558858/39f66d48-2292-11e6-83f8-dc94912d412c.png)

**Comment by pippinsplugins** [comment]
:+1:
