### ISSUE TITLE
EDD_Payment_Stats: Unused variable & duplicate add/remove `post_where` filter

### ISSUE THREAD

**Issue by DevinWalker** [easydigitaldownloads/easy-digital-downloads#4599]
This variable is not being used for anything and is being immediately overwritten in the if/else: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/payments/class-payment-stats.php#L110

As well, these two filters are unnecessary since the entire if/else is being wrapped with the same filters: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/payments/class-payment-stats.php#L183-L185

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/payments/class-payment-stats.php#L112 and https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/payments/class-payment-stats.php#L218

**Comment by cklosowski** [comment]
Closing in favor of this PR, for easier testing. Kept your commits in tact @DevinWalker
