### ISSUE TITLE
Add customer creation date to REST API

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#4602]
The creation date for customers is not shown in the REST API response for the customers endpoint. It should be.

**Comment by cklosowski** [comment]
Added this in https://github.com/easydigitaldownloads/easy-digital-downloads/pull/4588/files#diff-a25b2b11b0be82e1706c4c1643f0c1f0R260

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
It's not showing for me.

**Comment by cklosowski** [comment]
Will be merged in with #4588

**Comment by pippinsplugins** [comment]
Oh wait, I was on v1 of the API :P

**Comment by pippinsplugins** [comment]
No customers are returned if a date is not specified.
