### ISSUE TITLE
Deprecate `id` from customer data and add multiple emails support

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#4603]
The `id` field is supposed to be the ID of the customer record. Right now it's showing the same value as the user ID.

**Comment by cklosowski** [comment]
Will fix this once #4588 is merged in so I can fix it in both `V1` and `V2` in teh same commit.

**Comment by pippinsplugins** [comment]
`V1` should not be changed, only `V2`.

**Comment by cklosowski** [comment]
Ok, then I'll fix it along in #4588

**Comment by topher1kenobe** [comment]
If the customer is a guest their user_id is 0, which causes this line to NOT set the id == $customer_obj->id, rather leaving it empty.

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/2.6/includes/api/class-edd-api-v2.php#L283

**Comment by cklosowski** [comment]
According to the notes in this copy from `v1` we had the idea to deprecate the `id` field anyway as it's redundant of the `customer_id` field. Since we're breaking things, why not just get rid of it while we have the chance?

**Comment by cklosowski** [comment]
![screen shot 2016-06-07 at 9 51 47 pm](https://cloud.githubusercontent.com/assets/1390124/15883126/0fc07d26-2cfa-11e6-84d9-3803eacc51da.png)

**Comment by pippinsplugins** [comment]
Excellent, let's get rid of it completely.

**Comment by cklosowski** [comment]
@topher1kenobe can you take a look at this again? We've gone ahead and simply removed that `id` column as you pointed out, it's redundant, also, the `user_id` will always report at least `0` or the `user_id` value. this way the data matches that of the database values (which are `0` for non-connected customers). 

We've also gone ahead and added support for an `additional_emails` attribute, that will always be an array, empty if there are no additional emails, or an array of email addresses if they have more than one associated with their account. Here is an example output from my dev environment that demonstrates them both I believe:
```
{
  "customers": [
    {
      "info": {
        "customer_id": "1116",
        "user_id": 0,
        "username": "",
        "display_name": "",
        "first_name": "testing",
        "last_name": "user",
        "email": "testing4645@local.dev",
        "additional_emails": [],
        "date_created": "2016-06-06 23:21:08"
      },
      "stats": {
        "total_purchases": "1",
        "total_spent": "1215.000000",
        "total_downloads": 0
      }
    },
    {
      "info": {
        "customer_id": "1115",
        "user_id": "1",
        "username": "admin",
        "display_name": "Site",
        "first_name": "Site",
        "last_name": "Admin",
        "email": "cklosowski@gmail.com",
        "additional_emails": [
          "cklosowski+testing@gmail.com"
        ],
        "date_created": "2016-06-01 18:15:13"
      },
      "stats": {
        "total_purchases": "1",
        "total_spent": "1215.000000",
        "total_downloads": 0
      }
    }
  ],
  "request_speed": 0.0346949100494
}
```

**Comment by cklosowski** [comment]
Updated the Docs to reflect that the `id` field is going away, and moved the `customer_id` field to the first item in the values.
