### ISSUE TITLE
Make Purchased Products column in payment export able to be parsed

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#4623]
In order to better facilitate exporting and importing payments between EDD stores, we have to make the `Purchased Products` column more import friendly. 

The value of the export currently comes in like this:

`Product Name - Price Option Name - Amount`

If there are multiple products, it looks like this:

`Product Name - Price Option Name - Amount / Product  2 Name - Price Option Name - Amount`

This makes it nearly impossible to import properly in #3620.

I propose that we do a few things:

1. Fix a bug that causes two hyphens on products that don't have a price option
2. Add a `raw` column that is just the purchased product names
3. Somehow add price options and amounts so we can parse them in the import

**Comment by pippinsplugins** [comment]
PR: https://github.com/easydigitaldownloads/easy-digital-downloads/pull/4609

**Comment by pippinsplugins** [comment]
Now we have two columns:

- Products (verbose)
- Products (raw)

The verbose column is unchanged. The raw column is nothing but product names.

**Comment by mintplugins** [comment]
When I do a test export of payments, this is what my Products (verbose) and Products (raw) columns look like. I'm not totally sure if this is expected or not - I still see 2 hyphens in Products (verbose):

<img width="1236" alt="screen shot 2016-06-01 at 1 22 31 pm" src="https://cloud.githubusercontent.com/assets/1638128/15719048/1ffe0e86-27fc-11e6-94f2-1b5ba5b03196.png">

**Comment by pippinsplugins** [comment]
Are the prices in the raw column part of the product names?

**Comment by mintplugins** [comment]
@pippinsplugins  Yes they are - sorry that's confusing.

**Comment by pippinsplugins** [comment]
In that case it worked properly :)

**Comment by pippinsplugins** [comment]
I think we can close this now. It's in `release/2.6`.
