### ISSUE TITLE
Redundant edd_payment_tax postmeta

### ISSUE THREAD

**Issue by metal450** [easydigitaldownloads/easy-digital-downloads#4626]
Upon upgrading from EDD 1.5.1 to 2.5.16 and diffing my database, I found many thousands of newly-created postmeta entries of the form:

(44232, 1097, '_edd_payment_tax', '0')

Since taxes are completely disabled on my installation, it seems like it would be much cleaner to avoid these redundant "zeroes" for each and every purchase - instead just presuming a default tax of "0" when no such meta is present.

**Comment by pippinsplugins** [comment]
@metal450 That is intentional and necessary for proper reporting. See https://github.com/easydigitaldownloads/easy-digital-downloads/issues/1976
