### ISSUE TITLE
Price Options Don't Reappear When Removing Item From Cart

### ISSUE THREAD

**Issue by metal450** [easydigitaldownloads/easy-digital-downloads#4629]
EDD 2.5.16, WP 4.5.2, Digital Store (theme) 1.3.6

Upon adding an item to the cart, the price options disappear and the "add to cart" button changes to "checkout" (as desired).  Upon removing it from cart (via the widget), the "checkout" button changes back to "add to cart" (as desired), but the price options do not reappear.  This means that unless the user explicitly refreshes the page, they will not be able to re-add to the cart.

Screen capture: http://screencast.com/t/hiXoIU7VcR

**Comment by pippinsplugins** [comment]
@metal450 I _think_ that is a bug specific to the Digital Store theme. As a quick test, do you get the same behavior with Twenty Sixteen?

**Comment by metal450** [comment]
I don't have TwentySixteen installed (can test tomorrow if necessary?), but it does happen on TwentyTwelve, so it doesn't appear to be just Digital Store...

**Comment by cklosowski** [comment]
this appears to only affect using the shortcode for a purchase link. When viewing the product page itself, everything works as designed. I'll keep digging into this, but on the downoad single page itself the page refreshes, on the homepage with a shortcode, it does it all via ajax.

**Comment by SDavisMedia** [comment]
Replicated and confirmed page refresh/fix in `issue/4629`. :+1:

**Comment by cklosowski** [comment]
@metal450 does this solution meet your requirements?

**Comment by metal450** [comment]
@cklosowski Thanks for the follow-up; I'll report back if I still see this issue after the next chance I get to update WP/EDD/DigitalStore, but due to other commitments it might be some months until I can evaluate, so for now if your testing shows this as resolved, feel free to go ahead and close it :)

Thanks again!
