### ISSUE TITLE
Usage tracking opt-in not sending initial checkin

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#4635]
Right now, our opt-in usage tracking isn't sending the initial checkin (and subsequently never sends another one) due to this logic issue:
```
if( ! $last_send || $last_send > strtotime( '-1 week' ) ) {
```

Because the first checkin will do a `get_option` and return `false` since the option doesn't exist, we need to do an `is_numeric` check instead, to make sure we're doing a numerical comparison before the `>` check.

**Comment by cklosowski** [comment]
PR against `master`, milestoned @pippinsplugins

**Comment by pippinsplugins** [comment]
Looks good, let's merge once unit tests deploy.
