### ISSUE TITLE
history-downloads template and price option names

### ISSUE THREAD

**Issue by metal450** [easydigitaldownloads/easy-digital-downloads#4638]
I see in the history-downloads.php template that it's supposed to show the price option name along with the download name.  However, the check on line 43 (EDD 2.5.16) returns false for purchases of price option "0"; this causes the price option name to be omitted in those cases.  So for instance, if you have a user who's purchased price options 0, 1, and 2...the first row won't show the price option name, but the next 2 will.

As there's no filter on the $name that gets printed here (line 49), it appears that the only way to fix this for now is to actually edit the core plugin's template.

**Comment by pippinsplugins** [comment]
Thanks for the report! We'll look into it and get it addressed soon after 2.6.

**Comment by sunnyratilal** [comment]
@metal450 I'm unable to replicate this.

The check on [line 43](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/templates/history-downloads.php#L43) just ensures that the price ID isn't empty. Could you share a screenshot of the behaviour you're experiencing please?

**Comment by metal450** [comment]
I'm not actually using this template anymore myself, but here are some quick screenshots:

Product w/ 2 price options: "Single Domain" and "Multi Domain": http://screencast.com/t/CxqhYzsMa
History of 4 orders: 3 w/ price option "single domain", 1 w/ price option "multi domain": http://screencast.com/t/Hk4BXWKvJbN
Download History template only shows "Multi Domain" for that 1 order - doesn't show "Single Domain" for any of the 3x other orders: http://screencast.com/t/2HH8EGMimI
