### ISSUE TITLE
Expired discount blocking checkout

### ISSUE THREAD

**Issue by flowdee** [easydigitaldownloads/easy-digital-downloads#4640]
Last week I created a discount code which was limited to yesterday. After creating it I added it to the checkout form in order to validate the code is working. I think I didnt click on remove code after this.

Now a customer mails me that he cant finish the checkout because at the end of the page, right above the buy now button there was the following notice:

`This discount is expired.`

At the top table no discount code was listed and he told me he didn't apply one earlier.

In order to find out which code might be producing this issue, I debugged the **edd_is_discount_active** function and print the **$code_id** which was the code I created last week and which expired the day before.

I can't imagine why this happens. At the one hand the customer told me he didn't apply this coupon, on the other hand WHEN the code was applied, shouldn't it be added to the table at the top? at least as "wrong code" or something.

The only way to get it working was to reactivate the discount code and remove the expiration date.

Any idea? Is there a way to delete already applied and maybe "hanging" discount codes?

**Comment by pippinsplugins** [comment]
Was it that one customer only or all customers?

**Comment by flowdee** [comment]
Heared it from this customer and then checked it on my own, even with a different browser and the issue appeared for me too.

**Comment by cklosowski** [comment]
So, I'm guessing, that the discount was valid at the time of adding it, and your session has stayed valid past the expiration?

**Comment by flowdee** [comment]
The discount was valid when adding right. But this was about 5 days ago. Don't think the session will stay that long active?

But shouldn't be there some mechanism which checks if a discount is invalid and than kick it out of a session or something? At least the invalid discount which is hanging in the session should be shown at the product table or on any place I have a chance to remove it manually, or not?

**Comment by pippinsplugins** [comment]
This was caused by the cron job we implemented to update discounts to expired when their expiration date is reached. That caused a number of issues but have now all been resolved.
