### ISSUE TITLE
Improve inline help throughout the plugin

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/easy-digital-downloads#4641]
One of the best ways we can improve the customer experience and lower the volume of support requests is to make it easier to understand what settings mean and how things work. After chatting with @pippinsplugins we've decided to add some inline tooltips throughout the plugin to make it easier to get quick information about various things in the plugin. We want to make this a priority.

Something like this, which we're starting to implement in RCP. 

![image](https://cloud.githubusercontent.com/assets/1254870/15716645/251206da-27f1-11e6-9554-4c6d2d29ca53.png)

It's pretty quick and easy to add and doesn't require a lot of code. We're using the jQuery TipTip library. Example code required to add the tooltip in the screenshot:

```<span alt="f223" class="rcp-help-tip dashicons dashicons-editor-help" data-tip="<?php _e( '<strong>Subscription level</strong>: a subscription level refers to a membership option. For example, you might have a Gold, Silver, and Bronze membership level. <br/><strong>Access Level</strong>: refers to a tiered system where a member\'s ability to view content is determined by the access level assigned to their account. A member with an access level of 5 can view content assigned to access levels of 5 and lower.', 'rcp' ); ?>"></span> ```

@samikeijonen we'd love your thoughts on accessibility.

**Comment by cklosowski** [comment]
I rather like this idea, however I am concerned about the accessibility.

**Comment by pippinsplugins** [comment]
The method above is identical to how WooCommerce does it. Not saying they've nailed it just because they're Woo, but I think it's likely that it's fine.

**Comment by samikeijonen** [comment]
I'm sure tooltip can be accessible, like in this [example](http://a11y.nicolas-hoffmann.net/dialog-tooltip/). I can ask around more info about it.

**Comment by cklosowski** [comment]
Ok @pippinsplugins and @samikeijonen, @mindctrl.

We should outline a few areas we see the most support requests about clarification. Since this is the initial addition of them, we could do a super sharp focus on the top 10-20 pain points and add them in those first. And then follow up once we get some feedback.

**Comment by cklosowski** [comment]
# Areas to add tooltips for
- [ ] Price assignments for files (Edit/Add Download)
- [ ] Bownload link expiration time (Settings)
- [ ] Button behavior (Settings & Edit/Add Download)
- [ ] File Download Method (Settings)
- [ ] IPN verification (Settings)
- [ ] File Download Limit (Edit/Add Download)
- [ ] Disable the automatic output of the purchase button (Edit/Add Download)
- [ ] Purchase Shortcode (Edit/Add Download)

**Comment by cklosowski** [comment]
I'm also going to add new attributes to our settings registration `tooltip_title` and `tooltip_desc`, which allows our settings as well as extension settings to include their own tooltips easily within the settings tabs.

**Comment by mindctrl** [comment]
In RCP we're going to use the jQuery Tooltip library included in WP core instead of the TipTip one mentioned above.

**Comment by pippinsplugins** [comment]
This is now merged into `release/2.6`.

**Comment by SDavisMedia** [comment]
This looks really good to me. Super helpful only when needed.

I don't particularly care for the inconsistency in how we write Ajax/AJAX here: http://glui.me/?i=jzrn68w3setx3kq/2016-06-20_at_10.54_PM.png/

Two periods at the end of the cart saving tooltip: http://glui.me/?i=0kjcza10cvpz7zp/2016-06-20_at_10.56_PM.png/

"Value" is spelled wrong in the File Download Limits tooltip: http://glui.me/?i=ng17zf6focgn9xu/2016-06-20_at_10.58_PM.png/

**Comment by pippinsplugins** [comment]
Ajax: It should be `AJAX` since it is an abbreviation.

**Comment by pippinsplugins** [comment]
I'm going to go ahead and generate a new pot file and get it pushed to .org.

**Comment by cklosowski** [comment]
Closing this out for now. I think we've hit the areas needed.
