### ISSUE TITLE
Possible for edd_get_ip() to return a CSV of IP addresses

### ISSUE THREAD

**Issue by zackkatz** [easydigitaldownloads/easy-digital-downloads#4642]
`edd_get_ip()` can use the `$_SERVER['HTTP_X_FORWARDED_FOR']` value as the IP address. This can cause problems because `$_SERVER['HTTP_X_FORWARDED_FOR']` [allows returning a comma-separated value](https://en.wikipedia.org/wiki/X-Forwarded-For#Format), not just a single IP.

This causes problems with payment gateways that verify the IP addresses, like PayPal, which threw this error message: "Invalid IP: The IP Address provided is invalid."

I'll submit a patch in a few minutes that fixes the problem.

**Comment by pippinsplugins** [comment]
@zackkatz Thanks for the catch!

We'll get this reviewed and included in a release soon after 2.6.

**Comment by sunnyratilal** [comment]
Works fine for me 👍

**Comment by sunnyratilal** [comment]
Due to the format of `$_SERVER['HTTP_X_FORWARDED_FOR']`, we should wrap the `$ip_array[0]` in a `trim` function so it reads `trim( $ip_array[0] )` just to avoid any whitespace

**Comment by pippinsplugins** [comment]
Let's also get some unit tests in for this with various (good and bad) formats.
