### ISSUE TITLE
Roles are being initialized on every admin request

### ISSUE THREAD

**Issue by bcole808** [easydigitaldownloads/easy-digital-downloads#4646]
The function [edd_install_roles_on_network() in includes/install.php](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/install.php#L309-L335) creates user roles and permissions if missing. This line
```
if( ! in_array( 'shop_manager', $wp_roles->roles ) ) {
```
always evaluates to false and thus always triggers role creation on every admin page load because `$wp_roles->roles` is now a multi-dimensional array and so we need to update this to check for array keys. 

Steps to re-create:

1. Install WP 4.5.2
2. Install Easy Digital Downloads and activate
3. Set a debug breakpoint inside `edd_install_roles_on_network`
4. Load Dashboard pages and see that the function keeps re-creating roles. 

I will open a pull request momentarily with a fix for this issue... this problem has been preventing me from being able to customize the capabilities for the EDD roles.

**Comment by pippinsplugins** [comment]
Good catch!

We'll put this in 2.6.

**Comment by pippinsplugins** [comment]
I've confirmed the bug and the fix.

Merged into `release/2.6`.
