### ISSUE TITLE
Updating buy now payment in PayPal Standard should use EDD_Payment

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#4650]
When processing a Buy Now payment in PayPal Standard, we update the purchase meta in order to set the customer email and name.

In this scenario, however, the customer ID does not get set for the purchase.

We can easily resolve this by using EDD_Payment instead of manually adjusting meta.

We also need to update the rest of PayPal IPN processing to use EDD_Payment, but that can be done mostly separately.

**Comment by pippinsplugins** [comment]
Ticket from customer that is seeing a bug due to this: https://secure.helpscout.net/conversation/209510095/35345/?folderId=180505

**Comment by pippinsplugins** [comment]
Tested this on the customer site above and it appeared to work fine.

**Comment by mintplugins** [comment]
Just tested this on my local MAMP in Paypal sandbox mode (not sure if that's the problem) but no customer was created.

**Comment by pippinsplugins** [comment]
@mintplugins local won't work since it requires the PayPal IPN to be processed.

**Comment by pippinsplugins** [comment]
I just tested this on a live site and confirmed it works as expected.
