### ISSUE TITLE
Ability to see all purchases that used a discount code.

### ISSUE THREAD

**Issue by danieliser** [easydigitaldownloads/easy-digital-downloads#4654]
A link from the discounts lists/search results to see all purchases that used that code would be awesome. Currently quite difficult to track down where a code was used and by who.

**Comment by pippinsplugins** [comment]
You can already :)

Enter `discount: {code}` in the search on `Downloads` > `Payment History`.

**Comment by danieliser** [comment]
Too easy. Is there a list somewhere, I obviously didn't find it :).

**Comment by danieliser** [comment]
Though a link from the dicounts screen would be nice.

**Comment by SDavisMedia** [comment]
@danieliser It's in the Help tab on the Payment History screen. "Nicely" tucked away from everyone's view haha. A link from the Discounts page would definitely be nice.
