### ISSUE TITLE
How use score instead discount?

### ISSUE THREAD

**Issue by hamedmoody** [easydigitaldownloads/easy-digital-downloads#4655]
Hi
i am write a plugin that work with user score. user earn score from manu items such as write comment, daily login, buy product, marketting and ...
i want to use score in selling instead discount when user want buy any product. How can i implement this plugin?
Thanks

**Comment by mintplugins** [comment]
Hey there,

This GitHub issue area is only used to report issues/bugs/feature requests for Easy Digital Downloads. It isn't a place to get support for writing custom code. Sorry about that. 

If you'd like to hire someone to help you write your plugin for you, there's a group of great coders who know and work with Easy Digital Downloads available for hire here:
https://easydigitaldownloads.com/consultants/

**Comment by hamedmoody** [comment]
sorry i didn't khnow,Thanks for your help

**Comment by mintplugins** [comment]
No problem! :)
