### ISSUE TITLE
Improve UX for "Buy Now" setting

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#4665]
Right now, if taxes are enabled or the payment gateway does not support "Buy Now", the Buy Now option disappears altogether. If the user doesn't have an understanding of that, they may be confused as to why the option doesn't show. 

I would propose that, instead of making it disappear altogether, we grey the option out and leave a note (tooltip?) as to why it is disabled.

For context, here is the area I am referring to:
<img width="298" alt="screen shot 2016-06-08 at 1 51 38 pm" src="https://cloud.githubusercontent.com/assets/1638128/15904977/13a548a4-2d81-11e6-89f6-c13ac6bf706f.png">

**Comment by cklosowski** [comment]
@mintplugins can you test this out for me? Check the wording too.

**Comment by mintplugins** [comment]
@cklosowski Love it. Working great here and the descriptions look good to me too. I just capitalized the "N" in Buy Now and changed the word "getting" to "buying" in the phrase 

"greatly speeding up the process of buying the product".

**Comment by cklosowski** [comment]
Ok I'm going to go ahead and merge this in then and close it out. thanks @mintplugins
