### ISSUE TITLE
Feature Request: Shortcode [edd_login] - When the user logs in they get redirected to a defined page.

### ISSUE THREAD

**Issue by adampickering** [easydigitaldownloads/easy-digital-downloads#4666]
## How it currently works.

When a user logs into the site using the shortcode [edd_login] this is what happens.

![edd-login-no-redirect](https://cloud.githubusercontent.com/assets/746776/15905425/d27c46f0-2d82-11e6-95ee-c7920c6247e8.gif)

Its not pretty.

### What I'd like to see happen:

Inside of WordPress > Downloads > General Settings > Page Settings > Login Redirect

Display an option where the site admin can choose a page that the user is redirected to upon login.

![screen shot 2016-06-08 at 2 13 22 pm](https://cloud.githubusercontent.com/assets/746776/15905533/2de7b04c-2d83-11e6-92e7-66cbdfb9ac20.jpg)

Thoughts @SDavisMedia @spencerfinnell @pippinsplugins @cklosowski

**Comment by SDavisMedia** [comment]
@adampickering I definitely love the idea of a page dropdown in admin. Much easier. You never replied in Slack when I asked if you knew about the `redirect` attribute, though. So just FYI, `[edd_login redirect="http://google.com/"] is totally legit.

**Comment by michaelbeil** [comment]
I like the idea of adding a login redirect to the settings panel.

**Comment by pippinsplugins** [comment]
I'm fine with adding a setting for this. Any value supplied by the shortcode should take precedence though.

**Comment by cklosowski** [comment]
Yes, agree with @pippinsplugins I love the idea of having a 'fallback' redirect page which can be overridden by the attr in the shortcode.

**Comment by pippinsplugins** [comment]
PR looks good @crissoca, thanks! We'll test to confirm and then get this included shortly after 2.6.

**Comment by sunnyratilal** [comment]
Tested and works fine for me

**Comment by pippinsplugins** [comment]
@sunnyratilal could you change the text for the setting header: https://github.com/easydigitaldownloads/easy-digital-downloads/pull/4695/files

**Comment by sunnyratilal** [comment]
Merged

**Comment by pippinsplugins** [comment]
Re-opening until we get some unit tests in.

**Comment by cklosowski** [comment]
Added some unit tests. closing.

**Comment by pippinsplugins** [comment]
Re-opening until PR is merged.
