### ISSUE TITLE
New filter hook for 'edd_price_options' classes

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#4669]
I am proposing a new filter hook which would allow the adding/removing of css classes for the variable price div (edd_price_options).

I think if we set it up as an array it makes it easy to add/remove classes and then implode them upon output. 

I am thinking we call the hook: "edd_price_options_classes" and pass the classes array and the download_id to the filter hook.

Here is a screenshot of the proposed code change:
<img width="862" alt="screen shot 2016-06-09 at 10 08 13 am" src="https://cloud.githubusercontent.com/assets/1638128/15932882/705c8378-2e2b-11e6-939a-6985b4b3b55d.png">

Any thoughts or changes?

**Comment by shazahm1** [comment]
$css_classes should be sanitized before being output using [sanitize_html_class()](https://codex.wordpress.org/Function_Reference/sanitize_html_class).

**Comment by mintplugins** [comment]
@shazahm1 great catch - thanks!

**Comment by mintplugins** [comment]
PR: https://github.com/easydigitaldownloads/easy-digital-downloads/pull/4670
