### ISSUE TITLE
Allow new public API query modes to be added

### ISSUE THREAD

**Issue by ericnicolaas** [easydigitaldownloads/easy-digital-downloads#4673]
Currently, there is no easy way to add a new _public_ API endpoint (i.e. one that doesn't require API keys). I think there are valid reasons for wanting to add new public endpoints (one example below), and it makes sense to add that possibility when we can already declare new endpoints that are not public.

I have a working version of this and will put together a PR. 

**Example where this would be useful:** I want to add a `versions` endpoint that prints out a simple array of all products + their current version. This information is already available in the `products` mode, but by adding a mode that _only_ returns versions, the request speed can be much faster. The `versions` endpoint will then be used to check for updates to our plugins, doing away with the current technique we used (based on the Software Licensing sample plugin). The end result should be less load on our server and faster experiences in wp-admin for users who have multiple plugins installed.

**Comment by pippinsplugins** [comment]
Oh, I love this!

I think we should go ahead and include this in 2.6.

**Comment by ericnicolaas** [comment]
Updated PR with 2.6 for the `@since` tag.

**Comment by pippinsplugins** [comment]
Thanks!

**Comment by cklosowski** [comment]
@easydigitaldownloads/core-devs This is pretty awesome, could you guys hit this up and just test the current API endpoints to make sure that things are still working as expected?

**Comment by mintplugins** [comment]
Tested all built-in endpoints and they all work properly:

Private (needs API key):
- stats
- sales
- customers
- discounts
- file-download-logs

Public:
- products

When adding the code (https://github.com/easydigitaldownloads/easy-digital-downloads/pull/4674) for the versions endpoint it works publicly as well:
