### ISSUE TITLE
Show error notice when attempting to update customer email to existing value

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/easy-digital-downloads#4684]
If you edit a customer and enter an email address that already exists then hit the update button the previous value remains and no information is provided regarding the problem. We should display a simple error message informing the user that the email they entered is already in use on another customer record.

**Comment by pippinsplugins** [comment]
@brashrebel did you happen to test this on `release/2.6`? I don't believe this exists anymore with 2.6.

**Comment by mintplugins** [comment]
Tested this on 2.6 branch and confirmed fixed. 

It will gracefully give this error now:
"Email address is already associated with another customer."

For reference the ticket related to this is here:
https://secure.helpscout.net/conversation/214026581/36094/?folderId=180504

**Comment by pippinsplugins** [comment]
:+1:
