### ISSUE TITLE
Cart keys are not exposed on cart hooks

### ISSUE THREAD

**Issue by Shelob9** [easydigitaldownloads/easy-digital-downloads#4685]
I am looking to add upsell links inside of the cart. I'm adding a link to change to a variable price with a higher price. `edd_checkout_cart_item_title_after` is the perfect hook for this, but it doesn't give me the cart key, which makes removing the currently selected price ID after adding the new price ID in my AJAX callback possible.

So I added the cart key to that hook, and will submit a PR in hopes of y'all adding it, since it is a pretty useful improvement. I'll probably even abstract this to an add-on if you are so kind as to merge that PR.

**Comment by pippinsplugins** [comment]
Good idea!

We can include this in 2.6.
