### ISSUE TITLE
System info always shows Must-Use Plugins section

### ISSUE THREAD

**Issue by jaredatch** [easydigitaldownloads/easy-digital-downloads#4690]
System Info report always shows Must-Use Plugins section due to a typo.

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/admin/tools.php#L649

`if( count( $muplugins > 0 ) ) {` should be `if( count( $muplugins ) > 0  ) {`

**Comment by pippinsplugins** [comment]
Good catch!

**Comment by michaelbeil** [comment]
Good catch @jaredatch!
