### ISSUE TITLE
What's New page for 2.6

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#4709]

**Comment by michaelbeil** [comment]
> input field will not properly set the phone’s keyboard
> input field will **now** properly set the phone’s keyboard

> can now effortless handle the import for you
> can now **effortlessly** handle the import for you

> purchase reecords
> purchase **records**

> Perhaps you are transition from another eCommerce system, or from a separate Easy Digital Downloads store; whatever the reason, Easy Digital Downloads now allows you to easily import purchase records from a CSV file
> Perhaps you are **transitioning** from another eCommerce system, or you are migrating from a separate Easy Digital Downloads store; whatever the reason, Easy Digital Downloads now allows you to easily import purchase records from a CSV file
