### ISSUE TITLE
Fatal Error trying to Import Settings

### ISSUE THREAD

**Issue by ADukal** [easydigitaldownloads/easy-digital-downloads#4729]
First time I use this option:
**Export Settings from a live site** > **Import that Settings in a Localhost replica**
and the result is:
**Fatal error: Cannot use object of type stdClass as array in F:\www\store\wp-content\plugins\easy-digital-downloads\includes\gateways\functions.php on line 52**
After that all the Wordpress Admin seems to be broken, each page I try to load or change ends with the same message.
I'm using EDD Version 2.6.1 in both sites.

**Comment by cklosowski** [comment]
Looking at it (from mobile) I think this might have been an issue prior to 2.6. we will get that fixed up though. Looks like the settings import isn't getting the gateways setup correctly.

**Comment by ADukal** [comment]
As the Error refers to the gateways functions I guess the trouble probably was originated because I didn't installed the MercadoPago plugin in my localhost. Not sure really but I'm trying to figure how to fix it to keep working on my localhost without making a fresh installation.

**Comment by cklosowski** [comment]
Ok so we just need to harden the function checks to account for settings containing gateways that may not exist due to the import. Thanks for the details!

**Comment by ADukal** [comment]
You're welcome.

**Comment by cklosowski** [comment]
To test this, export your settings from one EDD site, and import those settings. Pretty simple to replicate.
