### ISSUE TITLE
Bad display of tooltip infos in 2.6

### ISSUE THREAD

**Issue by fxbenard** [easydigitaldownloads/easy-digital-downloads#4731]
I tried on several installs, several locales and always the same result.

The text expand in full window size and under the menu

![2016-06-28_11-22-22](https://cloud.githubusercontent.com/assets/802114/16410502/13cbc9fa-3d23-11e6-827c-cdfb763a2c46.png)
French version
![2016-06-28_11-20-44](https://cloud.githubusercontent.com/assets/802114/16410501/13c3ff72-3d23-11e6-9a77-4e2a701546db.png)
US version

**Comment by pippinsplugins** [comment]
I saw that when css was cached. Have you tried a hard refresh / cache purge?

**Comment by fxbenard** [comment]
OK - Cache cleared, all Firefox modules deactivated/activated and back on track. False alarm. Thanks

**Comment by pippinsplugins** [comment]
:+1:
