### ISSUE TITLE
Discounts become inactive on upgrade

### ISSUE THREAD

**Issue by psahalot** [easydigitaldownloads/easy-digital-downloads#4735]
I upgraded to 2.6 and an active discount got deactivated. Thought, it might be because 2.6 was a major upgrade. 
But, the same thing happened when upgrading to 2.6.1 and 2.6.2

**Comment by cklosowski** [comment]
Did these discounts have expiration dates or usage limits on them?

**Comment by psahalot** [comment]
Yes, the expiration date is set to June 30, 2016. No usage limits.

**Comment by cklosowski** [comment]
What timezone is your site set to?

**Comment by cklosowski** [comment]
Just to clarity. there was a cron added to the daily tasks to look for discounts past their expiration or at their usage limit and mark them as inactive. This was a measure to clean up the discount codes in #3198 because normally codes were never marked as expired until their expiration date was queried.

**Comment by pippinsplugins** [comment]
Another report: https://secure.helpscout.net/conversation/221290632/37130/?folderId=180499

**Comment by pippinsplugins** [comment]
We should add `if( ! empty() )` checks around the SQL queries so they only run if IDs were found.

**Comment by sunnyratilal** [comment]
I think it's an issue with the `meta_query`.  Calling the function on `init` just to see if it runs, it deactivated all discounts I created which were set to expire tomorrow (1st July).

**Comment by sunnyratilal** [comment]
Running an `if( ! empty() )` would still cause the SQL query to run because the IDs of the discounts are being returned from `edd_get_discounts`

**Comment by pippinsplugins** [comment]
@sunnyratilal Pretty sure that's backwards now. The expiration date needs to be in the past.

**Comment by sunnyratilal** [comment]
Yes you're correct - my mistake. Currently incorrect discounts are being pulled from `edd_discount_status_cleanup`.  However, the correct discounts are being returned from `edd_is_discount_expired`.

**Comment by sunnyratilal** [comment]
Think I got it, incorrect date formats are being compared.

The date format stored in `_edd_discount_expiration` is `06/30/2016 10:00:00` whereas the format returned from `current_time( 'mysql' )` is `2016-06-30 18:05:54`.

**Comment by cklosowski** [comment]
This is our fault we store an odd format on the post meta. We should
convert it if possible.

-- 
Sent from Gmail Mobile

**Comment by sunnyratilal** [comment]
I've got a commit ready which works in the mean time, should we add an upgrade routine instead which just converts the date format of all the discounts?

**Comment by pippinsplugins** [comment]
Let's make converting the dates a separate issue.

**Comment by cklosowski** [comment]
Yea separate issue as well need a lot of compatibility done.

-- 
Sent from Gmail Mobile

**Comment by sunnyratilal** [comment]
@cklosowski Expressed concerns regarding the date format, however, we're storing the date in the specific format: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/discount-functions.php#L227 so currently a string comparison is the best we can do to address this issue

**Comment by pippinsplugins** [comment]
@cklosowski can you double check this? Looks good to me. Nice work @sunnyratilal

**Comment by pippinsplugins** [comment]
![screen shot 2016-06-30 at 4 15 49 pm](https://cloud.githubusercontent.com/assets/1034109/16504508/ef9ea9f0-3edd-11e6-84a8-07a57101496a.png)
