### ISSUE TITLE
New: If enabled, send checkin data when Easy Digital Downloads is upgraded.

### ISSUE THREAD

**Issue by paranoidddd** [easydigitaldownloads/easy-digital-downloads#4740]
Dear Developers,

What does this mean? This is in the changelog.

Can you point me to the file(s) where this code exists?  Looked in commit history but could not find it.

Assuming this feature is opt-in?

Thanks kindly.

**Comment by cklosowski** [comment]
@paranoidddd 

Easy Digital Downloads has an **opt-in** usage tracking that sends some information to the development team so we can know where to best put our efforts. As you said, yes, this is opt-in. If you choose not to send the data, it doesn't get sent. This data is only sent once per week, and only when the option is enabled.

This setting is located in `Downloads > Settings > General`. On my site, this is checked, signifying an `opt-int`
![screen shot 2016-06-30 at 12 10 44 am](https://cloud.githubusercontent.com/assets/1390124/16479748/29b7f74a-3e57-11e6-87c0-9a0b795ae07a.png)

In 2.6.1 we made a small change that sends this data (again, only when the setting is enabled) when EDD is upgraded. This gives us some insights into the rate at which sites are being upgraded.

If you have any more questions about our opt-in usage tracking, please feel free to contact us via our support form:
https://easydigitaldownloads.com/support

**Comment by cklosowski** [comment]
Just realized you asked for files as well:
Our primary tracking class is here: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/admin/tracking.php

The change that was made to send on upgrade is here:
https://github.com/easydigitaldownloads/easy-digital-downloads/commit/bc559343a4a2a867842287d30856799e3f591c91
