### ISSUE TITLE
reset download total earning and total sale

### ISSUE THREAD

**Issue by hamedmoody** [easydigitaldownloads/easy-digital-downloads#4741]
Hi
after some time(i don't know how much and how) total earning and total sale reset to 0 and destruct out statisctics

**Comment by cklosowski** [comment]
You can try and use the recount tools located in `Downloads->Tools`.

If that doesn't resolve the issue please submit a support ticket via our website:
https://easydigitaldownloads.com/support

**Comment by hamedmoody** [comment]
Thanks
