### ISSUE TITLE
edd_stats_{key} transients are a problem

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#4742]
In the last week I have handled two customer tickets where they reported excruciatingly slow admin areas. The problem stemmed from the plugin update checks running on every page do to there being so many transients in the database. The `update_plugins` transient (for some reason or other) cannot be stored when there are thousands of transients in the DB already.

The issue comes from the `edd_stats_{key}` transient.

Let's use the live EDD site for an example. Yesterday I deleted _all_ transients from the site. Today there are already 208 transients, and the vast majority of them are `edd_stats_{key}` transients that are generated from our various reporting views:

![screen shot 2016-06-30 at 9 13 23 am](https://cloud.githubusercontent.com/assets/1034109/16491268/ec280b6c-3ea2-11e6-86b6-1d35aaf0f247.png)

We need to either find a better way of caching these stats (perhaps in a single transient instead of unique transients) or we need to add a cron job to clear them out.

**Comment by cklosowski** [comment]
A single one will be problematic as creating too large of a single entry
can cause database replication to fail in enterprise environments and
managed hosts. I think we need to go with a cleanup routine

-- 
Sent from Gmail Mobile

**Comment by sunnyratilal** [comment]
Seems Woo store all their data in one transient: https://github.com/woothemes/woocommerce/blob/master/includes/admin/reports/class-wc-admin-report.php#L325

**Comment by pippinsplugins** [comment]
I don't think a single transient will hurt us. What's the most data we're going to see, a few dozen (hundred at most) keys? There are much, much bigger data sets stored than that.

**Comment by chriscct7** [comment]
Won't the number of keys will be the same as the number of transients we currently store right? So thousands?

**Comment by pippinsplugins** [comment]
Moving up in priority. This caused the live EDD site to grind to a halt almost due to there being over 2,000 transients, almost all from EDD stats.

**Comment by pippinsplugins** [comment]
RCP and AffWP sites also had over 1,000 transients.

**Comment by pippinsplugins** [comment]
Another example of this being a problem. Main EDD site had nearly 3,000 transients that were significantly affecting performance.
![screen shot 2016-08-30 at 2 44 10 pm](https://cloud.githubusercontent.com/assets/1034109/18104410/9cc1338e-6ec0-11e6-9788-bbc4927af65a.png)

**Comment by SDavisMedia** [comment]
Running `edd_daily_scheduled_events` doesn't appear to be deleting `edd_stats_{key}` transients for me. Running `edd_cleanup_stats_transients()` didn't do the trick either.

**Comment by pippinsplugins** [comment]
@SDavisMedia did you have expired transients at the time? It only looks for ones that are expired.

**Comment by pippinsplugins** [comment]
I just ran it manually on the live site, which had 5 expired stat transients. All 5 were deleted properly.

**Comment by SDavisMedia** [comment]
@pippinsplugins I had no clue they needed to be expired. I'll test again.

**Comment by pippinsplugins** [comment]
Yep, expired only.

**Comment by SDavisMedia** [comment]
@pippinsplugins Working great here.

**Comment by pippinsplugins** [comment]
Merged!
