### ISSUE TITLE
Change role checked when deleting a payment.

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#4744]

**Comment by pippinsplugins** [comment]
When a payment is deleted, we check if the user can `edit _shop_payments`. We should be using `delete_shop_payments`.

See https://github.com/easydigitaldownloads/easy-digital-downloads/pull/4732

**Comment by topher1kenobe** [comment]
Verified on master that shop_accountant can delete payments.

**Comment by michaelbeil** [comment]
Works as expected with the fix.
