### ISSUE TITLE
Warning: array_key_exists() on activation in WPMS sub-domain

### ISSUE THREAD

**Issue by bobbingwide** [easydigitaldownloads/easy-digital-downloads#4753]
When I activated EDD, having installed a local Git repo at the latest level ( v2.6.3, head 8cb0101 ), I noticed the following warning message.

```
Warning: array_key_exists() expects parameter 2 to be array, boolean given in 
<b>C:\github\easydigitaldownloads\easy-digital-downloads\includes\install.php</b>
on line 335.
```

### Problem explanation
In this instance, the value of wp_roles->roles was false. 
This can occur when no user roles have been defined for the site. 
get_option will return false, but EDD expects an array.

### Workaround
run with WP_DEBUG false, or simply ignore the message the first time you see it.

### Problem recreation

I recreated the problem by removing the roles that EDD creates and deleting the option ( from wp_6_user_roles, 6 being the site ID. ).

An easier way is to activate EDD in another site.

![image](https://cloud.githubusercontent.com/assets/2474435/16541400/4a759d4c-4079-11e6-9fec-1491e4ddbced.png)

As an aside, the screen capture also shows two messages about tracking plugin usage.

**Comment by sunnyratilal** [comment]
Good catch! We'll get the PR tested.

**Comment by bobbingwide** [comment]
BTW. In the original message you'll see I was attempting to run EDD symlinked. 
I later realised that this is still not supported and have now switched to using a clone.
