### ISSUE TITLE
Notice from purchase_link with invalid sku parameter

### ISSUE THREAD

**Issue by bobbingwide** [easydigitaldownloads/easy-digital-downloads#4755]
When attempting to use the purchase_link shortcode with an invalid sku parameter ( e.g. `[purchase_link sku=SKU]` )
the following Notice was displayed.

`Notice: Trying to get property of non-object in C:\apache\htdocs\wp-a2z\wp-content\plugins\easy-digital-downloads\includes\shortcodes.php on line 61`

Note: WP_DEBUG is true

**Comment by cklosowski** [comment]
Merging this into master once CI passes.
