### ISSUE TITLE
Date strings not properly parsed in product import

### ISSUE THREAD

**Issue by topher1kenobe** [easydigitaldownloads/easy-digital-downloads#4757]
If you do a product import with a date format like this: 5/06/16 the import will fail but report success.

**Comment by topher1kenobe** [comment]
I was not able to make this fail on master. I have a theory. At the same time we were working on this, we were also discovering that an invalid status would ALSO fail, and report success.  I'm beginning to think this wasn't an issue at all. Which doesn't mean tightening the logic around the date is bad.

Testing on this branch next.

**Comment by topher1kenobe** [comment]
UPDATE: I was wrong, I *did* make it fail on master. And it's verified fixed on this branch.

**Comment by cklosowski** [comment]
Fixing merge conflicts then will merge the PR.
