### ISSUE TITLE
Remove option to disable AJAX

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#4758]
We have offered an option to disable AJAX since the very beginning. This option was first implemented to help resolve issues for users whose sites did not work with AJAX processing for one reason or another. These types of cases are becoming more and more rare and disabling AJAX is perhaps causing more headaches than it was originally designed to resolve.

For example, I found a report today that log in on checkout does not work if AJAX is disabled. And a second ticket today had a similar issue, also caused by disabling AJAX.

For backwards compatibility, we may want to still support disabling it via a filter, but the option in settings should go away.

**Comment by pippinsplugins** [comment]
Note: if this is merged, anyone that has disabled ajax will automatically have ajax re-enabled since there would not otherwise be a way to turn it on.

**Comment by pippinsplugins** [comment]
Let's get this merged in as early as possible for 2.7.

**Comment by SDavisMedia** [comment]
Seems good here. With ajax confirmed disabled, checking out `issue4758` removed the setting and everything automatically operates using ajax. :+1:

**Comment by spencerfinnell** [comment]
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/64d11791d42897a8b0b3da62ecf071baf91feec6/includes/template-functions.php#L175

Will need some attention right? If AJAX is "required" by default then the rest of the `edd-no-js` stuff can technically be removed as well.

**Comment by spencerfinnell** [comment]
Or maybe it makes more sense to leave everything else alone in case this has to be reverted.

**Comment by pippinsplugins** [comment]
@spencerfinnell we can slowly start removing items but I'd like to leave it for a bit, since ajax could still be disabled via a filter.

**Comment by pippinsplugins** [comment]
Merged!

**Comment by cferdinandi** [comment]
I was wondering why jQuery as being loaded on all of my pages now, and just realized this is.

Supremely disappointed with this one. I've worked hard to make my site (which is themed around NOT needing jQuery for the web) jQuery-free, and this change breaks that.

I'm ok with jQuery loading on checkout, but is there a way to prevent it from loading on every single page?

**Comment by pippinsplugins** [comment]
@cferdinandi jQuery is needed anywhere a purchase button or cart widget is displayed. If you know explicitly which pages that includes, you could remove it from all other pages.

**Comment by cferdinandi** [comment]
@pippinsplugins I just realized this has never affected me because I'm using the custom add to cart links option instead of the built-in shortcodes. All makes sense now.

Digging through the source code, I noticed that I can re-disable AJAX with the `'edd_is_ajax_disabled'` filter. Will this be around for the foreseeable future, or are you planning to phase that out as well?

**Comment by pippinsplugins** [comment]
We plan to leave that there but I cannot make definite promises that the filter will always work. While we will not likely intentionally prevent it from working, non-ajax stores are not a feature we're actively maintaining either.

**Comment by cferdinandi** [comment]
Totally fair, and I would never expect you to commit to that indefinitely. Thanks again, Pippin!
