### ISSUE TITLE
Coupon code status switching to Inactive after every use

### ISSUE THREAD

**Issue by mathetos** [easydigitaldownloads/easy-digital-downloads#4759]
Since the 2.6 update we're noticing that coupon codes that have a lot of uses and expire later by date, are being automatically switched to Inactive status after every use.

**Comment by pippinsplugins** [comment]
@mathetos see https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4735

**Comment by mathetos** [comment]
Hey @pippinsplugins 

Ya, I'm aware of that issue and we experienced it last week when we upgraded. But I don't believe this occurrence is connected with an upgrade. I'll keep watch again. If it happens again without an upgrade I'll circle back on this.

**Comment by pippinsplugins** [comment]
It was introduced in 2.6 and then fixed with 2.6.3.
