### ISSUE TITLE
CSV imports: default status mapping

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#4764]
In the event products are imported with statuses that aren't recognized, we can at least catch some of the obvious ones. For example, if importing a product with a status of `published`, the import will fail. We should catch `published`, `live`, and anything else that obviously means `publish` and map it automatically.

**Comment by cklosowski** [comment]
@SDavisMedia ready for some testing.

The way I did this, leaves us the ability to quickly add more arrays like `draft_statuses` where we can just tack on another `else if` to detect those as well.

**Comment by topher1kenobe** [comment]
Confirmed fail on master, success on this branch
