### ISSUE TITLE
PayPal: Negative fees getting included twice

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#4770]
When an order has negative fees (such as through Discounts Pro), the discounts are taken into account twice once the customer reaches PayPal. See screenshots below.

![mgcgbnhfodjfhfea](https://cloud.githubusercontent.com/assets/1034109/16620134/e0ae2d4e-4356-11e6-98df-ac10387c027c.png)
![digcpgldelgfnijd](https://cloud.githubusercontent.com/assets/1034109/16620289/7d11e0cc-4357-11e6-8ea4-bf2bf823a7bd.png)

This is almost certainly due to changes introduced in #4632 and #4658 

The issue affects PayPal Standard for sure but I believe it also affects at minimum the PayPal Pro / Express and 2Checkout gateways. We may have to fix it in the gateways in order to prevent undoing our bug fixes with negative fees.

**Comment by pippinsplugins** [comment]
See https://secure.helpscout.net/conversation/223432769/37472/?folderId=180504

**Comment by pippinsplugins** [comment]
The bug happens because cart items now properly include the discount from negative fees assigned to them in the `cart_details` array.

**Comment by pippinsplugins** [comment]
This needs tested. Please test with Discounts Pro _and_ manually created fees that do _not_ have a `download_id` assigned. The key here is that both product-specific and global fees need to work in the same cart.

Sample call for adding a global fee:
```
EDD()->fees->add_fee( array( 'amount' => '-1', 'label' => 'Test' ) );
```

**Comment by cklosowski** [comment]
Tested and looks good on my end.

**Comment by topher1kenobe** [comment]
I made a discount with discounts pro, and a manual discount, $1 each. With a $20 product, PayPal wanted to take off $3.
![selection_551](https://cloud.githubusercontent.com/assets/341412/16628811/382dfcdc-4381-11e6-88af-4ff26f79f515.png)
![selection_550](https://cloud.githubusercontent.com/assets/341412/16628812/3b1402a2-4381-11e6-8e7e-4f30f0b7be50.png)

Testing the fix now.

**Comment by topher1kenobe** [comment]
On branch 4770, PayPal only wants to take $2, which seems proper.
![selection_552](https://cloud.githubusercontent.com/assets/341412/16628911/aa0d519a-4381-11e6-87f8-0466920c4747.png)

**Comment by pippinsplugins** [comment]
Thanks guys!
