### ISSUE TITLE
Customer address cannot be edited if no address is present

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#4777]
If a customer does not have an address already set, it is impossible to add one as the fields on the edit screen do not get displayed.
![screen shot 2016-07-06 at 1 30 01 pm](https://cloud.githubusercontent.com/assets/1034109/16629957/c516b2e6-437d-11e6-83e8-e8575f0a1a72.png)

**Comment by cklosowski** [comment]
There is a limitation here, in that currently the address information is stored on a User ID. So until #4622 is completed, we'll only have this for customers attached to users.

**Comment by pippinsplugins** [comment]
Moving to 2.7 then so we can do both simultaneously.

**Comment by cklosowski** [comment]
ok, it's a very minor fix do to this for the 2.6.7 release, if we want to keep it, I've almost got it done.

**Comment by cklosowski** [comment]
Actually it is done. Was a VERY minor change.

**Comment by cklosowski** [comment]
Moving back to 2.6.7, this is a good change to have incrementally.

**Comment by pippinsplugins** [comment]
Ah, I just re-read what you said. Misunderstood you :)

**Comment by michaelbeil** [comment]
Working well here.

**Comment by SDavisMedia** [comment]
This is working well for me. :+1:
