### ISSUE TITLE
Store refund date when payment is manually set to refunded

### ISSUE THREAD

**Issue by norcross** [easydigitaldownloads/easy-digital-downloads#4779]
When manually changing a payment record from "completed" to "refunded", the refund date isn't stored in the `_edd_refunded_date` meta key.

**Comment by cklosowski** [comment]
According to a search of EDD, we've never had one of those:
```
Searching 2163 files for "_edd_refunded_date" (regex)

0 matches
```

But we should probably add one, that might be a good thing.

**Comment by norcross** [comment]
weird. then I must have added it myself

**Comment by cklosowski** [comment]
Yeah I'm not seeing it in any of the extensions I have installed locally, but I rather like this idea. Thoughts @pippinsplugins?

**Comment by norcross** [comment]
just did a check and realized I'm setting that value in the External API I built.

**Comment by pippinsplugins** [comment]
Yep, let's add it!

**Comment by cklosowski** [comment]
Pretty sure this will get resolved with 3.0 and the refunds api we're building out. Closing this since by default all modifications will have a last modified date, as well as per item refunds which will be line items with dates.

**Comment by norcross** [comment]
and it comes full circle, 2 years later while hanging out on the Florida shore 😎

**Comment by cklosowski** [comment]
@norcross yeah, was doing some grooming and came across this. had a nice little laugh when I saw you reported it.

:+1: You're just a forward thinker.
