### ISSUE TITLE
On Product imports, urls are being split on /

### ISSUE THREAD

**Issue by topher1kenobe** [easydigitaldownloads/easy-digital-downloads#4780]
You can see the issue and screenshot here: https://secure.helpscout.net/conversation/222883353/37373/?folderId=180504

**Comment by pippinsplugins** [comment]
Another instance of this: https://secure.helpscout.net/conversation/230351923/38651/?folderId=180499

**Comment by pippinsplugins** [comment]
@cklosowski let's go ahead and get this in 2.6.5

**Comment by cklosowski** [comment]
@topher1kenobe @pippinsplugins give that a shot.

**Comment by pippinsplugins** [comment]
Looks good to me.

**Comment by topher1kenobe** [comment]
Failed on master, verified fixed on #4780 .

**Comment by pippinsplugins** [comment]
Thanks @topher1kenobe!

Merging.
