### ISSUE TITLE
PHPUnit Clover Code Coverage Doesn't Work

### ISSUE THREAD

**Issue by sunnyratilal** [easydigitaldownloads/easy-digital-downloads#4782]
When our unit tests are run, the code coverage report isn't actually being generated.

Current output is `Generating code coverage report in Clover XML format ...%` when it should be `Generating code coverage report in Clover XML format ... done`.

Subsequently, the code coverage is then not uploaded to Scrutinizer.

**Comment by pippinsplugins** [comment]
Nice :D
