### ISSUE TITLE
Resend receipt metabox visible when payments not complete

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/easy-digital-downloads#4785]
In #1942 we hid the Resend Receipt button when the payment is not Complete. However, that button was later moved to its own metabox and that container appears regardless of the payment status. The button honors the status but not the box. If the payment is not complete, the following is output:
```
<div id="edd-order-resend-receipt" class="postbox edd-order-data">
	<div class="inside">
		<div class="edd-order-resend-receipt-box edd-admin-box">
			<div class="clear"></div>
		</div><!-- /.edd-order-resend-receipt-box -->
	</div>
</div>
```
![screenshot 2016-07-09 13 24 41](https://cloud.githubusercontent.com/assets/4993131/16709224/87a3e4da-45d8-11e6-896f-fa9ae1c749ed.png)

Should be an easy fix.

**Comment by brashrebel** [comment]
Should a PR go into master or wait for the `release/2.7` branch?

**Comment by pippinsplugins** [comment]
@brashrebel `master` please so we can fix it in a point release.

**Comment by pippinsplugins** [comment]
Thanks @brashrebel !
