### ISSUE TITLE
Sales/Earnings inadvertence 

### ISSUE THREAD

**Issue by danieltoma** [easydigitaldownloads/easy-digital-downloads#4789]
Hello,
Case:
In Downloads page I have one product with 2 sales and $9 earnings;
If I click on sales link, to see sales details I have 3 sales and $36 earnings($7, $7, $22);
And I observed that many of my downloads are listed like this, incomplete.

First time I  thought that is a filter by period applied but this view has no period filter.

Regards,
Daniel

![img_1](https://cloud.githubusercontent.com/assets/2263690/16727146/5d727adc-4768-11e6-8c1a-f9588ed73db2.png)
![img_2](https://cloud.githubusercontent.com/assets/2263690/16727147/5d9de578-4768-11e6-9a1c-a58d827047bb.png)

**Comment by pippinsplugins** [comment]
This can sometimes happen during testing. You can resolve it by using the recount tool in Downloads > Tools.
