### ISSUE TITLE
edd_add_schema_microdata

### ISSUE THREAD

**Issue by kiarashi** [easydigitaldownloads/easy-digital-downloads#4791]
EDD 2.6.4 / WP4.5.3

When using variable prices, microdata doesn't show by default. 
I looked into the core code and saw in _includes/template_functions.php_ that microdata is included.

```
if( edd_add_schema_microdata() ) {
  echo '<meta itemprop="price" content="' . esc_attr( $price['amount'] ) .'" />';
  echo '<meta itemprop="priceCurrency" content="' . esc_attr( edd_get_currency() ) .'" />';
}
```
Where in the EDD admin area can I enable this?

**Comment by pippinsplugins** [comment]
Do you see microdata on non-variable priced products?

**Comment by kiarashi** [comment]
No microdata on non-variable priced products either.

Also one more thing, you need to adjust the price microdata inside shortcode-content-price.php as well. The code below will throw an error inside Google. You need to use `itemprop="price"` and `itemprop="priceCurrency` instead.

```
<?php $item_props = edd_add_schema_microdata() ? ' itemprop="offers" itemscope itemtype="http://schema.org/Offer"' : ''; ?>
	<div<?php echo $item_props; ?>>
		<div itemprop="price" class="edd_price">
			<?php edd_price( get_the_ID() ); ?>
		</div>
	</div>
```

**Comment by pippinsplugins** [comment]
It sounds like you have microdata disabled. Try deactivating all other plugins on the site. Does the microdata show up then?

**Comment by pippinsplugins** [comment]
Ok that means the Sale Price plugin is disabling or modifying the schema microdata. Please contact Jeroen directly for assistance in resolving that.

**Comment by kiarashi** [comment]
Yes, that's right and will do. 
Don't forget to add microdata for non-variable prices. :)
