### ISSUE TITLE
Product-specific sales and earnings report (graph) show no earnings

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#4792]
Ticket: https://secure.helpscout.net/conversation/224558178/37662/?folderId=321418 Confirmed locally and also by @cklosowski.

View the earnings graph for a specific product and the Earnings part of the graphic is flatlined for **This Month**. **This Year** seems to work fine.

**Comment by cklosowski** [comment]
@SDavisMedia ready for some testing when you have a few cycles.

**Comment by sunnyratilal** [comment]
@cklosowski Just tested and confirm it is working.

`master`:
![image](https://cloud.githubusercontent.com/assets/1525554/16996497/7d555854-4ea9-11e6-9904-72f71229f32c.png)


`issue/4792`:
![image](https://cloud.githubusercontent.com/assets/1525554/16996508/86aa2330-4ea9-11e6-8164-012a1fc1fc78.png)
