### ISSUE TITLE
tooltip for payment details page

### ISSUE THREAD

**Issue by hiddenpearls** [easydigitaldownloads/easy-digital-downloads#4794]
Tooltip at the right sidebar 'Save Payment' widget is taking all the space on screen.  

I produced this issue at Mac 10.11.5, Chrome.

posting screenshot at Skitch https://www.evernote.com/l/AMoHBy97XLBOhbK_x16GcODcamPyyt4fEUkB/image.png

**Comment by pippinsplugins** [comment]
Could you do a hard refresh of your cache? Does that fix it?

**Comment by hiddenpearls** [comment]
I did that but it still is the same.

**Comment by pippinsplugins** [comment]
I cannot replicate: https://cloudup.com/cSa6piLliCz

Make sure you don't have a CDN that needs refreshed.

**Comment by SDavisMedia** [comment]
@hiddenpearls I think something else is interfering. Our tooltips do not have a white background and the typography is different.

You might have another plugin activated (or maybe your theme) with conflicting styles. Can you temporarily deactivate all other plugins besides EDD and check? Temporarily switch themes if that doesn't fix it. Be sure to clear caches/CDN during testing if you have them.

**Comment by pippinsplugins** [comment]
I haven't seen any reports of this from other users.

@hiddenpearls still happening to you?

**Comment by cklosowski** [comment]
Closing this out. Haven't had any other reports of this.
