### ISSUE TITLE
Issue with "Redirect to Checkout" setting.

### ISSUE THREAD

**Issue by sujaypawar** [easydigitaldownloads/easy-digital-downloads#4797]
When "Redirect to Checkout" setting is enabled, parameters in the URL are NOT maintained.
This is important, especially when the links are affiliate, like one example below - 

http://example.com/checkout/?ref=10&edd_action=add_to_cart&download_id=7511&edd_options[price_id]=1&campaign=dynamic

Case 1 - When "Redirect to Checkout" is enabled - 
http://example.com/checkout

Case 2 - When "Redirect to Checkout" is disabled - 
http://example.com/checkout/?sujay=10&campaign=dynamic

Here's a video I quickly recorded if that could help understand the issue better - https://www.youtube.com/watch?v=2wIRwP1Y0ak

This at the least affects to affiliates that might be using "Add to Cart" link to the store.

**Comment by pippinsplugins** [comment]
Thanks for the report. We'll look into it!

**Comment by michaelbeil** [comment]
The PR needs to be reworked to maintain non-EDD URL query parameters.

**Comment by Nikschavan** [comment]
@michaelbeil, @pippinsplugins Just submitted a PR for this.

**Comment by michaelbeil** [comment]
Thanks for this @Nikschavan. This works great when other URL queries are present. @pippinsplugins thoughts? 

A URL like http://site.dev/checkout/?ref=1&edd_action=add_to_cart&download_id=1722&edd_options[price_id]=1&campaign=urlparams works great.

**Comment by michaelbeil** [comment]
http://site.dev/checkout/?edd_action=add_to_cart&download_id=1722&edd_options[price_id]=1 works fine too.

**Comment by michaelbeil** [comment]
@easydigitaldownloads/core-devs I think we can close #4798 and merge #4900.

**Comment by pippinsplugins** [comment]
I'd like to fully test it first.

**Comment by SDavisMedia** [comment]
Replicated on `master`. Checked out @Nikschavan's PR locally and it fixes the issue for me. :+1:

**Comment by cklosowski** [comment]
This seems to be working great for me. I've been using Google UTM tags to test it out and things seem to be maintaining through the redirects. I think in the future I'd like to get this to be a little more unit testable but for now I comfortable with this.

(unit tests can't be run ATM b/c of the redirects, we'd need to break out the url generation into a new function/method)

**Comment by cklosowski** [comment]
Going to merge and close this
