### ISSUE TITLE
Settings section need to be set even for 1 section

### ISSUE THREAD

**Issue by turtlepod** [easydigitaldownloads/easy-digital-downloads#4800]
currently EDD only add section to the settings when there are more than one section.
this will make sanitize filter didn't run when there's only one section (e.g only one ext. installed with settings).

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/admin/settings/register-settings.php#L942

**Comment by cklosowski** [comment]
We are currently refactoring settings sanitization in #4799

**Comment by turtlepod** [comment]
Many thanks 
:+1:
