### ISSUE TITLE
batch payments import - missing rows on import 

### ISSUE THREAD

**Issue by selul** [easydigitaldownloads/easy-digital-downloads#4803]
According to [this](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/admin/import/class-batch-import-payments.php#L32) setting on each import step, it should save 5 payments, but if we follow the algorithm there are just 4 saved, missing one, the last one, at each iteration. 

[Here](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/admin/import/class-batch-import-payments.php#L83) the default value is 1 and because the break loop condition is before the payment creation, [here] (https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/admin/import/class-batch-import-payments.php#L102) , the iteration will always be with +1 greater than the no. of payments imported. 

Also [this] (https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/admin/import/class-batch-import-payments.php#L84) if/else statement is not needed because if the` $step` propriety is zero, `$this->per_step * ( $this->step - 1 )` will also return zero.

**Comment by pippinsplugins** [comment]
Thanks for the report! We'll double check it and get this resolved.

**Comment by cklosowski** [comment]
The break should only happen if `$i > $this->per_step`. The if else is right though because `5 * ( 0 - 1 )` is `5 * -1` or `-5`

**Comment by cklosowski** [comment]
Having that logic in place just protects us from having some bad value passed in and being used to throw off the numbers and create bad data.

**Comment by cklosowski** [comment]
@easydigitaldownloads/core-devs could really use a bunch of eyes on this in `issue/4803` it's a super minor change, but I want to make sure the importer is working correctly still with this modification.

**Comment by pippinsplugins** [comment]
To test, we just need to make sure an import with 20 items creates 20 items. Yes?

**Comment by selul** [comment]
@cklosowski , if i'm right, this will break on `if( $key + 1 < $offset ) ` duplicating the payments 

let's say we have an import with 13 rows which will be done in 3 steps, 

Let's simulate the iteration: 
```

$step = 1;
$offset = 0;
	$i=1;
	foreach iterations
	1. 
		$key = 0;
		1 < 0 FALSE
		1 > 5 FALSE
		$i = 2;
	2.  		
		$key = 1;
		2 < 0 FALSE
		2 > 5 FALSE
		$i = 2;
	3.  	
		$key = 2;
		3 < 0 FALSE
		3 > 5 FALSE
		$i = 3;
	4.  
		$key = 3;
		4 < 0 FALSE
		4 > 5 FALSE
		$i = 4;
	5.  
		$key = 4;
		5 < 0 FALSE
		5 > 5 FALSE
		$i = 5;
	6. 
		$key = 5;
		6 < 0 FALSE
		6 > 5 TRUE => break  	
$step = 2;
$offset = 5;
	$i=1;
	foreach iterations
	1. 
		$key = 0;
		1 < 5 TRUE =>continue
	2. 
		$key = 1;
		2 < 5 TRUE =>continue
	3. 
		$key = 2;
		3 < 5 TRUE =>continue
	4. 
		$key = 3;
		4 < 5 TRUE =>continue
	5. 
		$key = 4;
		5 < 5 FALSE
		1 > 5 FALSE
		$i ++ // will insert the payment again, from $step = 1;
```

**Comment by cklosowski** [comment]
@selul Can you take a look at that commit? I think that should resolve the issue you are explaining. I worked out the math here:
```
$step = 1;
$offset = 0;
    $i=1;
    foreach iterations
    1. 
        $key = 0;
        1 <= 0 FALSE
        1 > 5 FALSE
        Insert 0;
        $i = 2;
    2.          
        $key = 1;
        2 <= 0 FALSE
        2 > 5 FALSE
        Insert 1;
        $i = 2;
    3.      
        $key = 2;
        3 <= 0 FALSE
        3 > 5 FALSE
        Insert 2;
        $i = 3;
    4.  
        $key = 3;
        4 <= 0 FALSE
        4 > 5 FALSE
        Insert 3;
        $i = 4;
    5.  
        $key = 4;
        5 <= 0 FALSE
        5 > 5 FALSE
        Insert 4;
        $i = 5;
    6. 
        $key = 5;
        6 <= 0 FALSE
        6 > 5 TRUE => break
$step = 2;
$offset = 5;
    $i=1;
    foreach iterations
    1. 
        $key = 0;
        1 <= 5 TRUE => continue
    2. 
        $key = 1;
        2 <= 5 TRUE => continue
    3. 
        $key = 2;
        3 <= 5 TRUE => continue
    4. 
        $key = 3;
        4 <= 5 TRUE => continue
    5. 
        $key = 4;
        5 <= 5 TRUE => continue
    6.
        $key = 5;
        6 <= 5 FALSE
        1 > 5 FALSE
        Insert 5;
        $i = 2;
    7.
        $key = 6;
        7 <= 5 FALSE
        2 > 5 FALSE
        Insert 6;
        $i = 3
    8.
        $key = 7;
        8 <= 5 FALSE
        3 > 5 FALSE
        Insert 7
        $i = 4
    9.
        $key = 8;
        9 <= 5 FALSE
        4 > 5 FALSE
        Insert 8
        $i = 5
    10.
        $key = 9;
        10 <= 5 FALSE;
        5 > 5 FALSE;
        Insert 9;
        $i = 6;
    11.
        $key = 10;
        11 <= 5 FALSE;
        6 > 5 TRUE => BREAK
$step = 3;
$offset = 10;
    $i=1;
    foreach iterations
    1. 
        $key = 0;
        1 <= 5 TRUE => continue
    2. 
        $key = 1;
        2 <= 5 TRUE => continue
    3. 
        $key = 2;
        3 <= 5 TRUE => continue
    4. 
        $key = 3;
        4 <= 5 TRUE => continue
    5. 
        $key = 4;
        5 <= 5 TRUE => continue
    6.
        $key = 5;
        6 <= 10 => continue;
    7.
         $key = 6;
        7 <= 10 => continue;
    8.
        $key = 7;
        8 <= 10 => continue;
    9.
        $key = 8;
        9 <= 10 => continue;
    10.
        $key = 9;
        10 <= 10 => continue;
    11.
        $key = 10;
        12 <= 5 FALSE;
        1 > 5 FALSE;
        Insert 10;
        $i = 11;
    12.
        $key = 11;
        13 <= 5 FALSE;
        2 > 5 FALSE
        Insert 11;
        $i = 12;
    13.
        $key = 12;
        14 <= 5 FALSE;
        3 > 5 FALSE
        Insert 12;
        $i = 13
```

**Comment by selul** [comment]
@cklosowski yes, it should work just fine now. Thank you for taking care of this :)

**Comment by pippinsplugins** [comment]
@cklosowski just merged but then remembered that we need to do the same for the product import and the base class.

**Comment by cklosowski** [comment]
@pippinsplugins yep, doing that now, will do another PR.

**Comment by cklosowski** [comment]
Note: the base class doesn't have a reference to these logic issue, only the specific classes.
