### ISSUE TITLE
Update register_meta() for WP 4.6

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#4807]
WP 4.6 is changing how `register_meta()` works. We need to update our use of it to match while also maintaining backwards compatibility for pre 4.6

**Comment by pippinsplugins** [comment]
See https://core.trac.wordpress.org/ticket/35658

**Comment by cklosowski** [comment]
@pippinsplugins @chriscct7 can you guys look over that commit. I've not applied the patch and things seems to still be working. Curious if I interpreted the needed updates differently than I did.

**Comment by pippinsplugins** [comment]
I'm pretty sure that is correct.

**Comment by sunnyratilal** [comment]
All looks good to me

**Comment by cklosowski** [comment]
There is an open issue #4523 where we need to do some extra sanitization of prices, I'm going include that in this issue as well.

**Comment by pippinsplugins** [comment]
@cklosowski https://make.wordpress.org/core/2016/07/20/additional-register_meta-changes-in-4-6/

**Comment by pippinsplugins** [comment]
@sunnyratilal we'll need this retested shortly once @cklosowski pushes up some changes for the adjustments just made to core.

**Comment by sunnyratilal** [comment]
Can confirm all is working:
1. Meta is being registered in the WordPress global `$wp_meta_keys`
2. `register_meta()` returns `true` as expected.

Good to merge methinks.

**Comment by sunnyratilal** [comment]
I'm setting up instances of WordPress 4.5.x to ensure backwards compatibility.

**Comment by sunnyratilal** [comment]
Backwards compatibility is maintained with all versions of WordPress 4.5.x (4.5 -> 4.5.3). No bugs found for me.

**Comment by cklosowski** [comment]
@sunnyratilal did you get a chance to verify that this branch also resolves #4523 ?

**Comment by pippinsplugins** [comment]
All good here.
