### ISSUE TITLE
Wait for mailchimp to complete double opt-in before allowing download

### ISSUE THREAD

**Issue by tedderpd** [easydigitaldownloads/easy-digital-downloads#4819]
I'm trying to add website visitors to my Mailchimp subscribers list via EDD.  I have the Mailchimp add-on installed .  Technically, everything works great ....Except that the EDD download does not wait until the user has completed Mailchimp's double opt-in.  As a result, the user gets the download, then does not reply to Mailchimp's email as the second part of the opt-in.

Rather than just "give away" my downloads without collecting email addresses, I've had to 'turn off' EDD  
:(

Any chance of adding an enhancement to the EDD /Mailchimp add-on to wait for the second part of the double opt-in to complete before continuing with download?

**Comment by pippinsplugins** [comment]
Hi @tedderpd,

This GitHub repository is for the core plugin only. Add-on plugins are managed separately so I'll need to close this issue as invalid.

Regarding the suggestion, it's certainly something we've seen requested a few times and an option we'd like to consider but at this time there is not an option for it.
