### ISSUE TITLE
Quantity and Price Range (EDD)

### ISSUE THREAD

**Issue by prabhanarayan** [easydigitaldownloads/easy-digital-downloads#4822]
Hello Everyone,

I am new to PHP and Wordpress. I have installed EDD and am facing the following issue

Suppose there are price range for licenses based on number of users -
Range 1: Between 1 to 10 Users – $5.00 per user
Range 2: Between 11 to 20 Users – $4.00 per user
Range 3: Between 21 to 30 Users – $3.00 per user

If one wants the license for 5 users, he should be billed for $25 (5 * $5.00 per user) based on price range.
If one wants the license for 15 users, he should be billed for $60 (15 users * $4.00 per user) based on price range.
If one wants the license for 25 users, he should be billed for $75 (25 users * $3.00 per user) based on price range.

I have tried using "Enable variable pricing" option on the download page and "Allow item quantities to be changed." option (Downloads > Settings > Misc > Item Quantities). These sort of resolve my issue half way. I can't control the value in the text box based on price range (like if Range 2 is chosen, the value in the quantity textbox should be between 11 and 20). Additionally these quantity figures can also be altered on the cart page. 

So I have two issues
1) Either change price range based on quantity or restrict the value in the quantity textbox based on price range selected.
2) I also need a way to stop quantities from being altered in the cart while retaining them on individual download pages.

Could someone please guide me to achieve this using EDD.

Thank you.

**Comment by chriscct7** [comment]
Hi there,
GitHub is used for tracking bugs and enhancements in the core project. Please feel free to contact our support via easydigitaldownloads.com
