### ISSUE TITLE
CSV imports: "The file you uploaded does not appear to be a CSV file"

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#4823]
A number of users have experienced issues when uploading CSV files for import. Instead of accepting the CSV file, EDD gives an error that `The file you uploaded does not appear to be a CSV file`. This error is occurring even when the file is definitely a proper CSV.

It happens intermittently and appears to be browser or computer specific. The same file that fails on one computer succeeds fine on another.

Example ticket: https://secure.helpscout.net/conversation/230558279/38684/?folderId=180499

**Comment by cklosowski** [comment]
Marking as a duplicate of #4769 so we're only tracking one. I'll move this data over to it.
