### ISSUE TITLE
Product Import allows assigning non-existent author

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#4824]
When you import downloads and use the Author field, it's possible to have the downloads assigned to an author ID that's non-existant. We should verify that a user with the ID exists before using it in the Post Data, and if it is not, maybe resort to the admin Id.

**Comment by cklosowski** [comment]
I think best solution here is that if we don't identify an author with that ID, we just assign the post to the user importing it?

**Comment by pippinsplugins** [comment]
>>>I think best solution here is that if we don't identify an author with that ID, we just assign the post to the user importing it?

I agree.
