### ISSUE TITLE
Update EDD_SL_Plugin_Updater.php

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#4827]
In SL 3.4.8 we're releasing version `1.6.5` of the `EDD_SL_Plugin_Updater` class. We'll need to get that into Core as well, to make sure we've got the fixes for duplicate notifications in networks resolved for EDD Addons.

**Comment by cklosowski** [comment]
100% Work in progress for testing only. Will mark as ready for testing when it's officially ready for EDD Core, this is here to make testing SL easier for now.

**Comment by pippinsplugins** [comment]
This is good to merge once we confirm the changes are final in https://github.com/easydigitaldownloads/EDD-Software-Licensing/issues/271
