### ISSUE TITLE
EDD 2.6.5 spelling mistakes

### ISSUE THREAD

**Issue by webaware** [easydigitaldownloads/easy-digital-downloads#4828]
* [nubmer](https://plugins.trac.wordpress.org/browser/easy-digital-downloads/trunk/includes/class-edd-register-meta.php#L89) => number
* [assocaited](https://plugins.trac.wordpress.org/browser/easy-digital-downloads/trunk/includes/class-edd-register-meta.php#L231) => associated
* [Identifes](https://plugins.trac.wordpress.org/browser/easy-digital-downloads/trunk/includes/class-edd-register-meta.php#L287) => Identifies

**Comment by chriscct7** [comment]
Thanks @webaware

**Comment by sunnyratilal** [comment]
Typos have been fixed - we need to rerun the Grunt file to ensure the POT file gets updated

**Comment by cklosowski** [comment]
Thanks @sunnyratilal we'll run the grunt tasks just prior to tagging.
