### ISSUE TITLE
Spelling mistakes "arguements" instead of "arguments"

### ISSUE THREAD

**Issue by boluda** [easydigitaldownloads/easy-digital-downloads#4829]
Tiny typo, "arguements" instead of "arguments".

- [class-edd-register-meta.php](https://plugins.trac.wordpress.org/browser/easy-digital-downloads/trunk/includes/class-edd-register-meta.php#L356)
- [customer-actions.php](https://plugins.trac.wordpress.org/browser/easy-digital-downloads/trunk/includes/admin/customers/customer-actions.php#L509)
- [process-download.php](https://plugins.trac.wordpress.org/browser/easy-digital-downloads/trunk/includes/process-download.php#L742)
- [process-download.php](https://plugins.trac.wordpress.org/browser/easy-digital-downloads/trunk/includes/process-download.php#L743)
- [process-download.php](https://plugins.trac.wordpress.org/browser/easy-digital-downloads/trunk/includes/process-download.php#L763)
- [process-download.php](https://plugins.trac.wordpress.org/browser/easy-digital-downloads/trunk/includes/process-download.php#L764)

**Comment by sunnyratilal** [comment]
Good catch @boluda, thanks!
