### ISSUE TITLE
Login Shortcode - redirect to purchase_history_page

### ISSUE THREAD

**Issue by kiarashi** [easydigitaldownloads/easy-digital-downloads#4834]
Users that use the` edd_login` gets redirected to the purchase history page, 
regardless of whether a login redirect page is selected in the admin area.

edd/includes/shortcodes.php

```
function edd_login_form_shortcode( $atts, $content = null ) {
	$redirect         = home_url();
	$purchase_history = edd_get_option( 'purchase_history_page', 0 );

	if ( ! empty( $purchase_history ) ) {
		$redirect = get_permalink( $purchase_history );
	}

	extract( shortcode_atts( array(
			'redirect' => $redirect
		), $atts, 'edd_login' )
	);

	if ( empty( $redirect ) ) {
		$redirect = get_permalink( edd_get_option( 'login_redirect_page', '' ) );
	}

	return edd_login_form( $redirect );
}
add_shortcode( 'edd_login', 'edd_login_form_shortcode' );
```

As far as I know, `purchase_history_page` is required in the backend. But if this is set, we can't use `login_redirect_page`.  Or am I wrong?
If possible, also add a filter so developers can tweak the $redirect as well.

**Comment by pippinsplugins** [comment]
You can set the redirect on the short code itself: `[edd_login redirect="http://yoursite.com/page"]`

**Comment by kiarashi** [comment]
I'm aware. :)

But what's the point of the extra option "Login redirect page".
If the redirect parameter isn't used, but the Purchase History page is set, the Login redirect page doesn't work. 

Shouldn't the code be modified that if the redirect parameter is empty and the login_redirect_page is empty too, use purchase_history_page.

![img-edd](https://cloud.githubusercontent.com/assets/7079137/17205770/adb30f60-54ac-11e6-8929-b0d968cc7e5f.png)

**Comment by chriscct7** [comment]
Yeah, it should read:

```
function edd_login_form_shortcode( $atts, $content = null ) {
   $redirect = '';
    extract( shortcode_atts( array(
            'redirect' => $redirect
        ), $atts, 'edd_login' )
    );

    if ( empty( $redirect ) ) {
        $redirect = get_permalink( edd_get_option( 'login_redirect_page', '' ) );
    }

    if ( empty( $redirect ) ) {
           $redirect         = home_url(); 
           $purchase_history = edd_get_option( 'purchase_history_page', 0 );

           if ( ! empty( $purchase_history ) ) {
                  $redirect = get_permalink( $purchase_history );
           }
    }

    return edd_login_form( $redirect );
}
add_shortcode( 'edd_login', 'edd_login_form_shortcode' );
```

**Comment by chriscct7** [comment]
The current shortcode uses the priority (top being most priority):
- Redirect param on shortcode if set
- Purchase confirmation page
- Home URL

In the current iteration, $redirect is never empty by the time we check for the login redirect page, so it's never used

The code above correctly does
- Redirect param on shortcode if set
- Login redirect page
- Purchase confirmation page
- Home URL

**Comment by pippinsplugins** [comment]
Ahh, I see the issue now. Sorry, I mis-read the issue before.
