### ISSUE TITLE
Incorrect state/province sometimes used in tax calculations

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#4835]
We've seen a few reports of tax calculations being incorrect due to the calculations using the wrong state/province. It's been a strange issue to track down but today I believe I finally found it.

A customer was having a problem with taxes getting applied incorrectly to shipping fees but _only_ after going to PayPal from the checkout screen.

- Taxes configured to apply only to US customers in New Jersey
- Site uses Simple Shipping (any fee that does not set `no_tax` to `true` will result in same behavior
- Shipping fees are properly taxed to New Jersey customers
- Checkout shows proper tax of 0.00 for customers not in New Jersey
- On PayPal tax is shown improperly

On checkout, we do an AJAX request to calculate the tax. When we do this, we pass `billing_country` and `state` as POST parameters. These are then used in `edd_get_tax_rate()` to determine which rate to use:

```php
/**
 * Get taxation rate
 *
 * @since 1.3.3
 * @param bool $country
 * @param bool $state
 * @return mixed|void
 */
function edd_get_tax_rate( $country = false, $state = false ) {
	$rate = (float) edd_get_option( 'tax_rate', 0 );

	$user_address = edd_get_customer_address();

	if( empty( $country ) ) {
		if( ! empty( $_POST['billing_country'] ) ) {
			$country = $_POST['billing_country'];
		} elseif( is_user_logged_in() && ! empty( $user_address ) ) {
			$country = $user_address['country'];
		}
		$country = ! empty( $country ) ? $country : edd_get_shop_country();
	}

	if( empty( $state ) ) {
		if( ! empty( $_POST['state'] ) ) {
			$state = $_POST['state'];
		} elseif( is_user_logged_in() && ! empty( $user_address ) ) {
			$state = $user_address['state'];
		}
		$state = ! empty( $state ) ? $state : edd_get_shop_state();
	}

	if( ! empty( $country ) ) {
		$tax_rates   = edd_get_tax_rates();

		if( ! empty( $tax_rates ) ) {

			// Locate the tax rate for this country / state, if it exists
			foreach( $tax_rates as $key => $tax_rate ) {

				if( $country != $tax_rate['country'] )
					continue;

				if( ! empty( $tax_rate['global'] ) ) {
					if( ! empty( $tax_rate['rate'] ) ) {
						$rate = number_format( $tax_rate['rate'], 4 );
					}
				} else {

					if( empty( $tax_rate['state'] ) || strtolower( $state ) != strtolower( $tax_rate['state'] ) )
						continue;

					$state_rate = $tax_rate['rate'];
					if( 0 !== $state_rate || ! empty( $state_rate ) ) {
						$rate = number_format( $state_rate, 4 );
					}
				}
			}
		}
	}

	if( $rate > 1 ) {
		// Convert to a number we can use
		$rate = $rate / 100;
	}
	return apply_filters( 'edd_tax_rate', $rate, $country, $state );
}
```

Once the checkout form has been submitted, the POST data is processed by `edd_process_purchase_form()`, which retrieves tax like this:

```php
'tax' => edd_get_cart_tax(), 
```

`edd_get_cart_tax()` adds up the tax for items and fees an then returns a summed total. The fee tax is retrieved with `edd_get_cart_fee_tax()`:

```php
/**
 * Get cart tax on Fees
 *
 * @since 2.0
 * @uses EDD()->fees->get_fees()
 * @return float Total Cart tax on Fees
 */
function edd_get_cart_fee_tax() {

	$tax  = 0;
	$fees = edd_get_cart_fees();

	if( $fees ) {

		foreach ( $fees as $fee_id => $fee ) {

			if( ! empty( $fee['no_tax'] ) || $fee['amount'] < 0 ) {
				continue;
			}

			// Fees must (at this time) be exclusive of tax
			add_filter( 'edd_prices_include_tax', '__return_false' );

			$tax += edd_calculate_tax( $fee['amount'] );

			remove_filter( 'edd_prices_include_tax', '__return_false' );

		}
	}

	return apply_filters( 'edd_get_cart_fee_tax', $tax );
}
```

For each fee, we retrieve the tax with `$tax += edd_calculate_tax( $fee['amount'] );`. Note that no country or state is supplied. Since neither state or country are supplied, `edd_calculate_tax()` retrieves the state and country from the POST data.

`edd_calculate_tax()` retrieves the state from two places:

1. the POST field of `state`
2. the `state` field from the customer's stored address if logged in.

Problem: `state` is _not_ available in the POST data after checkout is submitted. `card_state`, however _is_ available.

To fix the problem, we either change our JS to send a POST parameter of `card_state` and then update `edd_calculate_tax()` accordingly or we add a second conditional check for `card_state` in POST data.

**Comment by cklosowski** [comment]
I can't get this to happen.

I've got a single tax rate for california. 0 for a fallback rate.
![screen shot 2016-07-29 at 2 41 13 pm](https://cloud.githubusercontent.com/assets/1390124/17264242/8c3ee11c-559a-11e6-8bd6-134743755695.png)

If i choose California on checkout it properly updates my cart with the tax and at paypal it's the correct amount:
![screen shot 2016-07-29 at 2 40 41 pm](https://cloud.githubusercontent.com/assets/1390124/17264256/9f3b1d8a-559a-11e6-9cba-2ed520218204.png)
![screen shot 2016-07-29 at 2 40 45 pm](https://cloud.githubusercontent.com/assets/1390124/17264261/a42f4668-559a-11e6-8a9a-665aff496b93.png)
![screen shot 2016-07-29 at 2 40 57 pm](https://cloud.githubusercontent.com/assets/1390124/17264264/a7b69d54-559a-11e6-8235-d503b6e2d301.png)


If I choose Arizona on checkout it sets my tax to 0 on my cart and at PayPal is not charging tax:
![screen shot 2016-07-29 at 2 39 54 pm](https://cloud.githubusercontent.com/assets/1390124/17264272/b3b77cea-559a-11e6-9913-83bb0f1da998.png)
![screen shot 2016-07-29 at 2 39 43 pm](https://cloud.githubusercontent.com/assets/1390124/17264269/af4a1942-559a-11e6-9a8a-7b347ad49b79.png)
![screen shot 2016-07-29 at 2 40 14 pm](https://cloud.githubusercontent.com/assets/1390124/17264274/b6979a08-559a-11e6-8729-f183e5cd685d.png)

**Comment by cklosowski** [comment]
@mintplugins @SDavisMedia you guys have been doing stuff with Simple Shipping lately if I remember, are you setup to test this pretty easily?

Basic testing:
1 product with shipping enabled
Taxes enabled for a state
PayPal Standard Configured
Verify that when no tax on the cart, PayPal shows no taxes
Verify that when tax on the cart, PayPal shows the tax.

**Comment by pippinsplugins** [comment]
@cklosowski you need to be logged out.

**Comment by cklosowski** [comment]
@pippinsplugins sorry forgot to update here. Tested logged out, and all is well.
