### ISSUE TITLE
Check for local files fails on Windows servers

### ISSUE THREAD

**Issue by bseddon** [easydigitaldownloads/easy-digital-downloads#4844]
I've just updated to 2.6.5 to discover that downloads no longer do.  The issue is the introduction (in 2.5.10  according to function header notes) of the function 'edd_is_local_file' which performs tests that cannot work on windows.  The tests assumes that either the file is hosted on a Linux machine so starts with a forward slash or if 'http(s)://' is removed it will start with a forward slash.  On Windows local files do not start with a forward slash so it is necessary to use the 'file' scheme to reference local files, for example:

`file:///c:\myfolder\myfile.xxx`

The test in question is on line 336 of 'process-download.php' (version 2.6.5) or line 335 of version 2.5.10:

`$requested_file = preg_replace('#^https?://#', '', $requested_file );`

This can be modified to accommodate the file scheme:

`$requested_file = preg_replace('#^(https?|file)://#', '', $requested_file );`

It may also be useful to include some additional checks for Windows users:

1) Check to see if the second character of $requested_file is a colon and the third is a backslash as these are indicators of a file on a locally mapped drive;
2) Check to see if the file name begins with a double backslash (\\) as these are indicators of a locally connected volume using the universal naming convention (UNC).

**Comment by pippinsplugins** [comment]
@bseddon by `I've just updated to 2.6.5 to discover that downloads no longer do.` do you mean that the file downloads fail?

**Comment by bseddon** [comment]
Yes, the files do not download.  Because the test to check if the download is a local file returns false, edd_deliver_download is called on line 150 with the 'redirect' parameter set to true.  Since the file to be downloaded really is a local file (on Windows) the redirect method cannot work.

**Comment by pippinsplugins** [comment]
Thanks. I've updated the issue title to more accurately reflect the problem.

**Comment by cklosowski** [comment]
@chriscct7 Is it possible for you or @bseddon to test out this patch in `issue/4844`? I don't have a Windows based environment to test in just yet.

**Comment by bseddon** [comment]
This patch works for me.  I downloaded the issue/4844 branch, applied it to my test site and am able to download files successfully.  Thanks.

**Comment by pippinsplugins** [comment]
Looks good to me!

**Comment by cklosowski** [comment]
Awesome, thanks @bseddon! I'll go ahead and merge this in and we'll keep our eyes open for any other unintended consequences.

**Comment by bseddon** [comment]
Are you aware the resolution to this issue did not make it into 2.6.6?  I updated to 2.6.6 this evening thinking everything would be OK but a purchaser was unable to download their file.

**Comment by michaelbeil** [comment]
Hey @bseddon!

This issue was milestoned for 2.6.7, so it should be out in the next several days.
