### ISSUE TITLE
Sequential payment number not assigned when creating payments with EDD_Payment

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#4845]
When purchases are created with `EDD_Payment`, the sequential order numbers are not properly assigned. This happens because the sequential number is only set in `edd_insert_payment()`. The logic for setting the number should be moved to the `insert_payment()` method of `EDD_Payment`.

Extensions definitely affected by this include Manual Purchases and Recurring Payments.

**Comment by SDavisMedia** [comment]
Relevant ticket: https://secure.helpscout.net/conversation/233418973/39121/?folderId=180504

**Comment by cklosowski** [comment]
Something isn't right with the code committed, going to dig it...but it's incrementing the prefix, not the number itself:
![screen shot 2016-08-16 at 2 28 13 pm](https://cloud.githubusercontent.com/assets/1390124/17716494/c415fa9a-63bd-11e6-819a-4636818dd465.png)

Notice it's DE`V`, DE`W`, DE`X`

**Comment by cklosowski** [comment]
Ok, got that fixed:
![screen shot 2016-08-16 at 2 49 57 pm](https://cloud.githubusercontent.com/assets/1390124/17717095/bd81c170-63c0-11e6-8150-ff45275a89f6.png)

**Comment by cklosowski** [comment]
@easydigitaldownloads/core-devs Could someone else give this a test, if it's good i'll merge it.

**Comment by pippinsplugins** [comment]
Just tested and works fine for me!
