### ISSUE TITLE
Fix horizontal alignment of items in the dashboard widget

### ISSUE THREAD

**Issue by michaelbeil** [easydigitaldownloads/easy-digital-downloads#4848]
PR: #4847 

TODO: minify

**Comment by SDavisMedia** [comment]
We'll bring the convo over here, @NateWr. Here's my comment on the PR: https://github.com/easydigitaldownloads/easy-digital-downloads/pull/4847#issuecomment-238393583

I think this is a `wontfix`. According to @michaelbeil, you're on Linux right, Nate? This change would definitely negatively affect more users than it would help.

For most, it would change:
![2016-08-08 at 3 15 pm](https://cloud.githubusercontent.com/assets/2359131/17498394/fd57ab5c-5d7b-11e6-9aca-fb28701f5771.png)

To:
![2016-08-08 at 3 15 pm 1](https://cloud.githubusercontent.com/assets/2359131/17498402/05c46000-5d7c-11e6-82c4-f427a617d578.png)

**Comment by NateWr** [comment]
No worries. I just threw it together quickly. If you want to vertically align the elements across different font sizes (or different fonts) you're probably better off using a consistent `line-height` rather than trying to fudge the `padding-top`. It's no biggy either way though.

**Comment by SDavisMedia** [comment]
@NateWr Good point! With the `padding-top` removed, how does something like the following look on your end? 

```css
.edd_dashboard_widget .b, .edd_dashboard_widget .t {
    line-height: 1.5;
    vertical-align: middle;
}
```

All good here:

![screen shot 2016-08-09 at 6 49 28 am](https://cloud.githubusercontent.com/assets/2359131/17518619/82dc84c4-5dfd-11e6-9216-42d9f5c385a1.png)

That should actually be future proof once they move to system fonts.

**Comment by NateWr** [comment]
Looks good!

![selection_025](https://cloud.githubusercontent.com/assets/2306629/17545277/244b5926-5ed4-11e6-8608-f4e5851da3f2.png)

**Comment by SDavisMedia** [comment]
@natewr Perfect! If you wanna refresh your PR we can get it in there. Thanks!

**Comment by NateWr** [comment]
Ok I've updated the PR.

**Comment by SDavisMedia** [comment]
Looks great to me. Thanks!

**Comment by pippinsplugins** [comment]
Merged!
