### ISSUE TITLE
is there a way to upgrade the user's license manually from backend ?

### ISSUE THREAD

**Issue by hiddenpearls** [easydigitaldownloads/easy-digital-downloads#4849]
Is there a way to upgrade the user's license manually from backend ?

I know license upgrades mentioned in the docs http://docs.easydigitaldownloads.com/article/381-software-licensing-usage-instructions 

but I want to upgrade for some of our users manually. Is it possible ?

**Comment by michaelbeil** [comment]
Hi @hiddenpearls, 

For any support-related questions, we ask that you send a ticket to https://easydigitaldownloads.com/support as we reserve this repository for development purposes.
