### ISSUE TITLE
Fee actions have no hookable actions

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#4850]
When adding and removing fees from the cart, there are no actions in the process. This causes extensions to not be able to listen to fee related additions or removals of fees, much like they can with downloads.

**Comment by cklosowski** [comment]
@easydigitaldownloads/core-devs Anyone have opinions on these two hooks added? Pretty simple addition.

**Comment by pippinsplugins** [comment]
Looks good, merged.

**Comment by michaelbeil** [comment]
Looks good here.
