### ISSUE TITLE
Per Product Emails / Software Licensing compatibility issue when trying to send emails for products without keys

### ISSUE THREAD

**Issue by Kairo89** [easydigitaldownloads/easy-digital-downloads#4851]
This issue occurs, when EDD is trying to send an E-Mail for a product that has no product key generation associated with it.

It crashes in the `edd-per-product-emails/includes/email-functions.php` on line `326`, because `$license_key` is undefined.

The fix that I currently employ is the following:

```
    // used by the body
    if (isset($license_key))
      $input = str_replace( '{license_key}', $license_key, $input );
    else
      $input = str_replace( '{license_key}', '', $input );
```

I am not sure, if it is part of the issue, but I use a custom method of generating keys that I register in my functions.php via:

`add_filter( 'edd_sl_generate_license_key', 'my_custom_key_function', 10, 5 );`

Greetings

**Comment by cklosowski** [comment]
I just verified this seems to be working on all current `master` versions of the mentioned extensions while generating my own license keys via a filter.

Closing.
