### ISSUE TITLE
edd_complete_download_purchase won't run for payment->save()

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#4852]
It doesn't because the license key is created on the checkout flow `edd_complete_download_purchase`  [1] which isn't inside of the payment class, and is triggered by edd_complete_purchase.  

That makes sure the created_date is empty, that way it only runs once [2]. But when you do the above, the save() actually sets the date to the real date [3] via [4]. Setting it back to pending works because setting it to pending clears the meta key, thus when you save it again, the hook will run because when edd_complete_purchase runs, the date will now be set to empty.

Essentially, this is completely caused by the fact that in the purchase class, edd_complete_download_purchase is called after the meta is saved to the order. This is required, since otherwise anyone that needs to know the cart details wouldn't get it (those would in a real order already be in meta prior to the action since they are saved there when the order is made in the pending status pre-gateway). But since we don't do that in the payment class it has to so those work. The downside of this is that certain meta keys are additionally saved before the `edd_complete_download_purchase` hook is run in the payment class, allowing for the completed date to be saved, and thus the empty() check to fail. [6]. The reason that the hook comes after the meta key being saved is itself caused by the switch routine in the save() method that runs the meta_keys in order.

It should be noted that the allowing of the created_date to be cleared causes bugs where you can rerun actions over and over again that shouldn't be possible (because of the logic that the condition of empty() says should only be run once). Although SL fences for this issue, if it didn't you would see a bug where license keys would be made for an order every time you flipped between publish and pending, thus allowing for many unintentional keys. As it is, anyone who expects that action to run once, as it says it will, will find that's not the case since the payment object was introduced into EDD.

Refs:
[1] https://github.com/easydigitaldownloads/easy-digital-downloads/blob/99cbf1fa422504d9155018d3ee0e2d365a8040ca/includes/payments/actions.php#L63
[2] https://github.com/easydigitaldownloads/easy-digital-downloads/blob/99cbf1fa422504d9155018d3ee0e2d365a8040ca/includes/payments/actions.php#L60
[3]https://github.com/easydigitaldownloads/easy-digital-downloads/blob/99cbf1fa422504d9155018d3ee0e2d365a8040ca/includes/payments/class-edd-payment.php#L1724
[4]https://github.com/easydigitaldownloads/easy-digital-downloads/blob/99cbf1fa422504d9155018d3ee0e2d365a8040ca/includes/payments/class-edd-payment.php#L782
[5]https://github.com/easydigitaldownloads/easy-digital-downloads/blob/99cbf1fa422504d9155018d3ee0e2d365a8040ca/includes/payments/class-edd-payment.php#L1639
[6]https://github.com/easydigitaldownloads/easy-digital-downloads/blob/99cbf1fa422504d9155018d3ee0e2d365a8040ca/includes/payments/class-edd-payment.php#L1455

The deletion for the completed date is in the pending status function here: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/99cbf1fa422504d9155018d3ee0e2d365a8040ca/includes/payments/class-edd-payment.php#L1639

There's more actually, so when you call payment->save(), it calls set_status which calls the hook to complete a payment. Since right now the completed_date is set, the hook doesn't run so SL doesn't make a license key. However,  in the completed function that doesn't fire the action, it actually calls payment->save() itself, which of course calls update_status() which as we know calls edd_complete_order. So literally the only thing preventing a crazy infinity loop is this conditional here: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/99cbf1fa422504d9155018d3ee0e2d365a8040ca/includes/payments/class-edd-payment.php#L1424, and each payment saved using save() runs through the edd_complete_payment method twice

The most ideal solution imo is to make a new process_complete function in EDD that takes all of the stuff out of edd_complete_purchase and save/update_status, so that there's 1 function that runs to save a new order, and thus leaving save() as an any status function for saving

**Comment by cklosowski** [comment]
@chriscct7 I've just done some work in EDD SL and I'm using the `$payment->save()` and it's generating licenses just fine. I'll look this over again, but I'm not seeing this behavior.

**Comment by sunnyratilal** [comment]
Punting to 2.7.3 for further discussion

**Comment by pippinsplugins** [comment]
PR that should address this https://github.com/easydigitaldownloads/easy-digital-downloads/pull/5487

**Comment by pippinsplugins** [comment]
This is fixed. Re-open if you see it again.
