### ISSUE TITLE
Purchase Email Subject ampersands getting improperly HTML encoded

### ISSUE THREAD

**Issue by pderksen** [easydigitaldownloads/easy-digital-downloads#4853]
EDD Settings:
![image](https://cloud.githubusercontent.com/assets/79667/17496557/b6a87744-5d72-11e6-971f-c732a9c4fe12.png)

Gmail view:
![image](https://cloud.githubusercontent.com/assets/79667/17496577/cde5f5e4-5d72-11e6-8832-0d85bc91b8ba.png)

Looking at my email logs it looks like it started happening on 7/28/16. Not sure what/if any EDD updates would've been around that time.

I'm also on WP Engine and using Postmark for delivery. Both long before 7/28 as well.

**Comment by pippinsplugins** [comment]
Thanks, we should be able to resolve this easily.

**Comment by SDavisMedia** [comment]
Replicated and confirmed fixed. :+1:
