### ISSUE TITLE
Support all_blank on text inputs

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/easy-digital-downloads#4854]
It is likely that I'm missing something but in #2808 the matter of allowing blank values in settings (rich text in that case) was discussed and it was agreed that blank values should be allowed by default. This would mean that the `std` value for a setting would be applied initially (I think) but it would still be possible to save an empty value.

However, it seems that the `std` value for settings of any kind are always used instead of a blank value so it is impossible to save an empty field. The `allow_blank` argument defaults to `true` but doesn't seem to do anything.

So I'm just seeking clarification. I came across an extension using an `std` value and a customer who wants to save the field as empty but they can't so I experimented and confirmed that it can't currently be done. Perhaps this is intentional. If so, I'd like to understand it better.

**Comment by cklosowski** [comment]
@brashrebel Can you try and replicate with an earlier version of 2.6, like 2.6.4? My guess is #4799 might be messing with it.

**Comment by brashrebel** [comment]
Confirmed:

- `2.6.1` empty values are 👎 
- `2.6.4` empty values are 👍 
- `2.6.6` empty values are 👎

**Comment by cklosowski** [comment]
@brashrebel mind looking this over, seeing if it fixes things up?

**Comment by cklosowski** [comment]
ignore that commit

**Comment by brashrebel** [comment]
Doesn't seem to be working for me. Gotta make sure I'm testing the right thing. Since `allow_blank` defaults to true, all text settings that don't explicitly set that to `false` should allow blank values, right? So I'm testing now with the `thousands_separator` and `decimal_separator` settings in core plus some in extensions like Free Downloads. Those do not allow blank values currently on this branch.

**Comment by cklosowski** [comment]
The `allow_blank` is only supported in Rich Editors currently.

**Comment by cklosowski** [comment]
@brashrebel

**Comment by brashrebel** [comment]
Huh. So what about text inputs? It seems they can't currently be saved as empty. Are you saying I'm talking about two unrelated things?

**Comment by cklosowski** [comment]
Yes @brashrebel the allow_blank was specifically built to support an empty Rich Editor text area editor. not the Text inputs.

**Comment by brashrebel** [comment]
Thanks for clarifying. So how do we handle empty text inputs? Do we allow them at all? There's text inputs in core EDD and in extensions which cannot be saved as empty. Should we extend that argument to work for text inputs too?

**Comment by cklosowski** [comment]
I don't see why not, but I think that should be an enhancement for 2.7. There's some inherent risk to that with some settings. I'm going to convert this as an enhancement and put in 2.7.

**Comment by sunnyratilal** [comment]
@brashrebel @cklosowski Commit added that allows `allow_blank` to work on text inputs too.

**Comment by pippinsplugins** [comment]
Updated PR from `release/2.7` and tests are running.

**Comment by pippinsplugins** [comment]
Unit tests are passing now.

**Comment by sunnyratilal** [comment]
@pippinsplugins good to merge?

**Comment by pippinsplugins** [comment]
Testing further now.

**Comment by pippinsplugins** [comment]
Works great, merging.
