### ISSUE TITLE
Allow custom Arguments for Settings API Callbacks

### ISSUE THREAD

**Issue by michaelbeil** [easydigitaldownloads/easy-digital-downloads#4856]
Making an issue for this.

PR #4832.

**Comment by cklosowski** [comment]
This seems to be working fine, would love another set of eyes on testing to make sure we don't break our settings.

**Comment by pippinsplugins** [comment]
Appears to be working fine.

I'd like one more test from another please.

**Comment by SDavisMedia** [comment]
I tested the settings of several of our extensions on `d4mation:settings-changes`. They all seem to be working fine here. :+1:
