### ISSUE TITLE
EDD Reporting CSV > Excel UTF-8 auto formatting 

### ISSUE THREAD

**Issue by gst4158** [easydigitaldownloads/easy-digital-downloads#4859]
In excel Chinese characters by default do not display in UTF-8. Using a BOM enabled correct character formatting when other methods, such as mb_convert_encoding(), did not work.

Inside of: 
plugins\easy-digital-downloads\includes\admin\reporting\class-export.php

Line 48: public function headers() include echo "\xEF\xBB\xBF"; as the last item before the close of the function.

```
public function headers() {     
    ignore_user_abort( true );
    if ( ! edd_is_func_disabled( 'set_time_limit' ) && ! ini_get( 'safe_mode' ) )
        set_time_limit( 0 );

    nocache_headers();
    header( 'Content-Type: text/csv; charset=utf-8' );
    header( 'Content-Disposition: attachment; filename=edd-export-' . $this->export_type . '-' . date( 'm-d-Y' ) . '.csv' );
    header( "Expires: 0" );
    echo "\xEF\xBB\xBF"; // send the UTF-8 BOM for Excel
}
```

**Comment by chriscct7** [comment]
@gst4158 Are you using Excel on Windows or Mac?

**Comment by gst4158** [comment]
Windows PC
Excel: Microsoft Office Professional Plus 2013

**Comment by cklosowski** [comment]
Milestoning to get on the radar. So far a single report so we'll have to try and replicate this.

**Comment by cklosowski** [comment]
BTW, I finally have a windows machine, no Excel, but I believe I get a free 30 day trial, so if someone else doesn't pick this off, i'll try it out on my end and make sure adding these lines fixes the issue, but does't break on other platforms.

**Comment by cklosowski** [comment]
@gst4158 What exactly is the problem that occurs? Is the file corrupt, does it not download?

**Comment by gst4158** [comment]
@cklosowski  The file is fine. If we had some chinese characters, say '大股东' we'd end up with 'å¤§è‚¡ä¸œ'. Once the BOM was included than we were g2g.

**Comment by gst4158** [comment]
@cklosowski Are there any updates on this issue?

**Comment by sunnyratilal** [comment]
Replicated the issue in Excel 2016 for Mac.

Adding the BOM fixes the issue and the CSV export still displays correctly in Numbers for Mac and Google Sheets.  PR incoming.

**Comment by sunnyratilal** [comment]
Fixed and merged.
