### ISSUE TITLE
Symlinked file downloads result in 0 byte

### ISSUE THREAD

**Issue by nbastreet** [easydigitaldownloads/easy-digital-downloads#4861]
i'm using the latest version and when i use redirect method with symlink enabled, the size of download is 0 bytes. how can i solve this problem? any server configurations is needed?

**Comment by pippinsplugins** [comment]
Hi there!

Please go ahead and open a support ticket through our support portal: https://easydigitaldownloads.com/support

we use GitHub for development tracking only.
