### ISSUE TITLE
Properly catch default case for license activation callback

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#4862]
Right now the `default` for the license key callback is to just run a `print_r` on the results. We should catch this, and if the key is actually a bundle, we should throw a different error, if possible.

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/admin/settings/register-settings.php#L2065

**Comment by pippinsplugins** [comment]
@cklosowski Let's please include the `error` in the default message, that way it's not impossible to identify what the error actually was.

**Comment by cklosowski** [comment]
Sounds good. I can't see any other cases, I'll make sure error is actually somethign first as well.

**Comment by cklosowski** [comment]
@pippinsplugins added.

**Comment by pippinsplugins** [comment]
Looks good.

**Comment by mintplugins** [comment]
Working great:

<img width="367" alt="screen shot 2016-08-26 at 5 58 41 pm" src="https://cloud.githubusercontent.com/assets/1638128/18021627/da6d7434-6bb6-11e6-9b2a-ce086bd4999f.png">

**Comment by cklosowski** [comment]
Cool thanks @mintplugins
