### ISSUE TITLE
Add filters to API endpoints

### ISSUE THREAD

**Issue by ghost1227** [easydigitaldownloads/easy-digital-downloads#4866]
Currently, it's not possible to add content to existing API endpoints. We should add filters to allow dynamically adding content to them. 

RE: https://github.com/easydigitaldownloads/EDD-Software-Licensing/issues/577

**Comment by pippinsplugins** [comment]
@ghost1227 could you work on this today?

**Comment by ghost1227** [comment]
@pippinsplugins Sure can! How thoroughly do we want to be?

**Comment by pippinsplugins** [comment]
@ghost1227 let's please add `$this` as a parameter to each filter so that the API object can be used within the filters.

**Comment by ghost1227** [comment]
oh good call!

**Comment by ghost1227** [comment]
Done!

**Comment by pippinsplugins** [comment]
Ready for testing.

**Comment by sunnyratilal** [comment]
Tested and working well

**Comment by ghost1227** [comment]
👍

**Comment by pippinsplugins** [comment]
@sunnyratilal did you happen to test in conjunction with https://github.com/easydigitaldownloads/EDD-Software-Licensing/issues/577?,

**Comment by sunnyratilal** [comment]
Nope just tried and couldn't it wouldn't show any license data.

```json
{
    "ID": 1709,
    "transaction_id": 1709,
    "key": "fb3fb08b4ede56cf0fda83758912d295",
    "subtotal": 12,
    "tax": "0.75",
    "fees": [
        {
            "amount": "0.00",
            "label": "PayPal Standard Fee",
            "type": "fee",
            "no_tax": false,
            "download_id": 0,
            "price_id": null,
            "id": "gateway_fee"
        }
    ],
    "total": "12.75",
    "gateway": "manual",
    "email": "dev@local.dev",
    "date": "2016-08-15 05:33:13",
    "discounts": [],
    "products": [
        {
            "id": 1568,
            "quantity": 1,
            "name": "Endless Possibilities",
            "price": 12.75,
            "price_name": "Flac Audio Files Version"
        }
    ]
},
```

**Comment by sunnyratilal** [comment]
Licensing information is displayed on the `products` enabled but not the `sales` endpoint

**Comment by sunnyratilal** [comment]
Ahh found the issue. The licensing data isn't found on the `v2` endpoint.  With a normal URL it works as expected: `http://edd.dev/edd-api/sales?key=0297466f18855a1ea1d7d64508fa38b6&token=98fdb0adda9099b23cfd1b7646f0c5d6&date=last_month` but with the same URL being v2 it fails: `http://edd.dev/edd-api/v2/sales?key=0297466f18855a1ea1d7d64508fa38b6&token=98fdb0adda9099b23cfd1b7646f0c5d6&date=last_month`

**Comment by ghost1227** [comment]
That could be a thing! Didn't even think about the v2 API

**Comment by ghost1227** [comment]
Updated both PRs to support V2 API!

**Comment by sunnyratilal** [comment]
@ghost1227 Can confirm it's all working now

**Comment by ghost1227** [comment]
Woot!

**Comment by pippinsplugins** [comment]
Should V2 and V1 use the same filter names and then rely on developers checking which version of the API is bing used if their manipulations are version-dependent? That would keep integration with these filters simpler.

**Comment by ghost1227** [comment]
I used the `_v2` suffix because the V2 API already had a filter or two that used it (and matched V1 filters). Kept it to maintain uniformity with those existing filters.

And you're supposed to be on vacation 😛

**Comment by pippinsplugins** [comment]
I think we should keep the filters the same.

>>>And you're supposed to be on vacation 😛

Hush you :D

**Comment by pippinsplugins** [comment]
@ghost1227 I'd like to keep the filters with the same name please.

**Comment by ghost1227** [comment]
Ok

**Comment by ghost1227** [comment]
Done
