### ISSUE TITLE
Enable variable pricing checkbox displaying the wrong .edd_pricing_fields div on page refresh (in Firefox)

### ISSUE THREAD

**Issue by dtsap** [easydigitaldownloads/easy-digital-downloads#4872]
When reversing the state of the variable pricing checkbox (name='_variable_pricing') in Firefox and reload the page (without updating the post), it keeps the state of the checkbox it had before reloading the page, regardless the saved value causing to display the wrong .edd_pricing_fields div on checking/unchecking after the reload.  

I tried to prevent this by adding the autocomplete attribute to the input and set it to "off" (autocomplete="off").

**Comment by pippinsplugins** [comment]
I cannot replicate this bug and it appears to be fixed.
