### ISSUE TITLE
Excessive queries when applying discounts on checkout

### ISSUE THREAD

**Issue by kiarashi** [easydigitaldownloads/easy-digital-downloads#4873]
I noticed a mayor spike (800+) in database queries when using discounts on the checkout page.
![img-discount](https://cloud.githubusercontent.com/assets/7079137/17663606/083de99c-62ee-11e6-8bb2-d230e629301a.png)

I also noticed a similiar spike (+/-100) when using `if( ! ( affwp_is_affiliate() && affwp_is_active_affiliate() )` a while back that I haven't reported yet.

Other than that, what I wanted to know if there's a function available inside EDD that display the actual discount price when a discount _percentage_ is used.
Just using "DiscountCode - 15%" isn't enough on a checkout page. The amount that's subtracted is important too.

**Comment by michaelbeil** [comment]
Thanks for letting us know @kiarashi. Regarding the issue with AffiliateWP, I have added that to our issue tracker since that is a separate project.

**Comment by kiarashi** [comment]
You're most welcome. 

And there's more actually; I also saw an increase when using `FES_Vendors->vendor_is_vendor` and some things related to `EDD_Payment`.  You'll surely spot them all with Query Monitor. :)

**Comment by sunnyratilal** [comment]
I've done a considerable amount of testing here and am unable to replicate the spike in database queries.

### Test Cases
- Adding a discount code to a cart with 10 items
- Adding a discount code to a cart with 25 items
- Remove a discount code from a cart with 10 items
- Remove a discount code from a cart with 25 items
- Adding three discount codes to a cart with 10 items
- Removing two out of three discount codes to a cart with 10 items

If there's any other test case that I may have missed, let me know.

**Comment by pippinsplugins** [comment]
Good work @sunnyratilal. Let's close as invalid.
