### ISSUE TITLE
EDD & Multisite -- Create new Site with Recurring Subscription?

### ISSUE THREAD

**Issue by lazharichir** [easydigitaldownloads/easy-digital-downloads#4874]
Currently owning an EDD/STRIPE license, I am looking at setting up my multisite network and use Recurring Payments to handle subscriptions.

I want users to be able to create a new website when signing up to a subscription.

Is that possible, I do not mind custom coding (at thank you page, etc.) but was wondering if there was something simpler or already done for that?

**Comment by sunnyratilal** [comment]
Hi,

This repo is for development of Easy Digital Downloads. Please open a ticket [here](https://easydigitaldownloads.com/support/) for more assistance regarding this matter,
