### ISSUE TITLE
Can't set a placeholder for Text Inputs via the Settings API

### ISSUE THREAD

**Issue by d4mation** [easydigitaldownloads/easy-digital-downloads#4881]
Addressed in PR #4879

I personally like to put things like desired input examples in a placeholder that you may not want to otherwise put in the Field's Description.

**Comment by pippinsplugins** [comment]
I like this. PR looks good at first glance too.

**Comment by SDavisMedia** [comment]
All good here. Works for @sunnyratilal as well. :+1:
