### ISSUE TITLE
edd_payment_meta filter needs to be moved to support it's proper use

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#4887]
Related: https://secure.helpscout.net/conversation/238096412/39968/?folderId=375162

When edd_payment_meta is run, it's being overwritten if you touch any of the content within the default arrays (think $meta['user_info']['address']['country']`). We'll just need to move where it's used and some fallbacks to make sure all necessary fields exist.

**Comment by cklosowski** [comment]
FYI, this is Semi-Working if we move the filter to `EDD_Payment::get_meta` however say for instance you modify one section of the `user_info`, it'll overwrite all the values. So we need to look at a more in depth `array_merge`, I tried `array_merge_recursive` however this caused a few bugs so just need to dig a little deeper into that.

**Comment by cklosowski** [comment]
For testing I used something like the following:
```
function ck_test_payment_meta( $meta, $payment ) {
	$meta['user_info']['address']['country'] = 'PL';

	return $meta;
}
add_filter( 'edd_payment_meta', 'ck_test_payment_meta', 10, 2 );
```

We should be sure to test modifying information as well as adding custom information to this. Which I did and works for me but more eyes the better :)

**Comment by pippinsplugins** [comment]
Quick way to test this: make a purchase that includes fees. Those are recorded through payment meta: 
```php
class EDD_Fees {

	/**
	 * Setup the EDD Fees
	 *
	 * @since 1.5
	 */
	public function __construct() {
		add_filter( 'edd_payment_meta', array( $this, 'record_fees' ), 10, 2 );
	}
```

**Comment by mintplugins** [comment]
Using Simple Shipping, this branch is currently stripping out all shipping fees upon checkout. When I click "Checkout" my final purchase has no shipping fees.

**Comment by cklosowski** [comment]
Thanks guys, just noticed that it's killing the unit tests here too. I'll work on this further. Removing the needs testing for now.

**Comment by cklosowski** [comment]
ok @mintplugins and @pippinsplugins can you try this again? I think I got it working with the fees, as well as with my example above.

**Comment by cklosowski** [comment]
I used simple shipping for my fees.

**Comment by mintplugins** [comment]
@cklosowski Fees are retained successfully for me now 👍

**Comment by cklosowski** [comment]
Woot! @pippinsplugins take a look over this, let me know if you see any issues with it. It got a little 'ugly' when it came time to start merging nested arrays, but this seems to do the trick for us.

**Comment by pippinsplugins** [comment]
@cklosowski looks good but I'd like to see a few more axillary tests written for this:

1. Please add a test that creates a payment, then sets `$payment->address` to a new address. Confirm all data saved in `$payment->address` and `$payment->user_info['address']`
2. Do the same thing for `$payment->discounts`

**Comment by cklosowski** [comment]
@pippinsplugins discounts already has one of these. I actually caught a bug in my solution because of it. I'll add some more address checks in though.

**Comment by pippinsplugins** [comment]
New tests look good!

**Comment by SDavisMedia** [comment]
@cklosowski guided me through [the test here](https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4887#issuecomment-243846596)... the code did its job on `issue/4887` where it failed on `master`.  So that's a yes from me. :+1:

**Comment by pippinsplugins** [comment]
Merge away!
