### ISSUE TITLE
Add a view receipt page

### ISSUE THREAD

**Issue by michaelbeil** [easydigitaldownloads/easy-digital-downloads#4897]
From a user:

> Could a link on the transaction page to a "view receipt" page like .../?payment_key=...&edd_action=view_receipt be added? This would make it a lot easier for admins to open the receipt and make print or create a PDF manually, either for own use or to include in customer communication later.

**Comment by lalunecreative** [comment]
Yes please, that page also needs to include the download so to not so heavily rely on emails to get their products.

**Comment by pippinsplugins** [comment]
We already have this. See `{view_receipt}`.
