### ISSUE TITLE
Post status bug within pre_fetch method in class-edd-tools-recount-single-customer-stat.php

### ISSUE THREAD

**Issue by DevinWalker** [easydigitaldownloads/easy-digital-downloads#4898]
Notice this variable is set and never used:

![screenshot at aug 23 13-24-58](https://cloud.githubusercontent.com/assets/1571635/17908380/19604c54-6935-11e6-9328-25414c111107.png)

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/admin/tools/class-edd-tools-recount-single-customer-stats.php#L226

**Comment by pippinsplugins** [comment]
Good catch, thanks!
