### ISSUE TITLE
Filter "edd_get_cart_discounts_html" does not pass relevant arguments

### ISSUE THREAD

**Issue by zackkatz** [easydigitaldownloads/easy-digital-downloads#4902]
`edd_get_cart_discounts_html()` contains a `foreach` loop for each discount code, but the `edd_get_cart_discounts_html` filter is passed a single `$rate` and `$remove_url` variable. These are not helpful if there are multiple discounts applied.

**Comment by pippinsplugins** [comment]
Let's get this in 2.6.7. Nice improvement.

**Comment by cklosowski** [comment]
Tested and working as expected, thanks @zackkatz
