### ISSUE TITLE
Remove hyphen and Go Back button from discount screens

### ISSUE THREAD

**Issue by lisag** [easydigitaldownloads/easy-digital-downloads#4907]
I noticed there is a hyphen after the heading on both the `Add New Discount` and the `Edit Discount` pages, as well as a `Go Back` button. As far as I can see, the hyphen and button don't appear on any other pages in Easy Digital Downloads, and we don't use it in AffiliateWP, nor can I see it on any other core WordPress pages.

I wonder if it is worth removing the `Go Back` button? My vote is it's kind of redundant, as users can simply go back to the main `Discount Codes` page in the menu bar.

At the very least, it would be good to remove the hyphen to tidy up the heading.

<img width="1062" alt="screen shot 2016-08-27 at 11 35 07 am" src="https://cloud.githubusercontent.com/assets/11830108/18023236/c336bfe8-6c4a-11e6-9fe8-40449dcdf5c0.png">

<img width="1069" alt="image 2016-08-27 at 11 38 59 am" src="https://cloud.githubusercontent.com/assets/11830108/18023251/f84ec644-6c4a-11e6-87e2-6bb7dd892e6d.png">

**Comment by pippinsplugins** [comment]
I'm fine with removing them. One less piece of UI clutter.

**Comment by sumobi** [comment]
I'm going to throw this one out there. As per core, there seems to be only a back link once the page has been updated. Currently, once you update a discount you're thrown back to the main discounts screen. I think you should stay on the same page and see a notice similar to this:

Before updating a download category:

![screen shot 2016-08-29 at 9 27 01 pm](https://cloud.githubusercontent.com/assets/52581/18047193/b41b0596-6e2f-11e6-8df7-571875449946.png)

After updating a download category:

![screen shot 2016-08-29 at 9 27 14 pm](https://cloud.githubusercontent.com/assets/52581/18047194/b41fb1e0-6e2f-11e6-9e4c-1f3555cb1269.png)

**Comment by pippinsplugins** [comment]
:+1:

**Comment by sunnyratilal** [comment]
PR: #6187

**Comment by SDavisMedia** [comment]
Ran into an error while editing a discount to test this. It's outlined and taken care of here: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6389

With that out of the way:

1. The `Go Back` button is removed from both the Edit and the Add screen. ✅ 
2. After _editing_ a discount, the new notice works fine and the `Back to Discounts` link works fine. ✅ 
3. After _adding_ a discount, you're still automatically returned to the Discounts table. HOWEVER, when you click the button to add another new discount, the notice shows up. ❌ 
<img width="553" alt="screenshot 2018-02-15 11 32 02" src="https://user-images.githubusercontent.com/2359131/36276845-f5fa68b2-1243-11e8-8167-65e8ad378d65.png">

**Comment by pippinsplugins** [comment]
@JJJ isn't the bug @SDavisMedia mentioned above what you showed me you found and fixed along with the other 3.0 changes? If so, we can ignore that and proceed with merging this.

**Comment by JJJ** [comment]
Yep! This is fixed and pushed to `issue/6331` as part of the database table refactoring.
