### ISSUE TITLE
Undefined index: display_type when adding download details widget in customizer

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/easy-digital-downloads#4912]
If you use the customizer and add the Download Details widget to any widgetized area, without specifying any options for the widget, a series of PHP notices will be displayed. Setting or changing any of the options for that widget removes the errors and the widget renders properly.

**Comment by mindctrl** [comment]
Maybe related: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/3661

**Comment by cklosowski** [comment]
@brashrebel Mind testing this out? Should take care of things for you.

**Comment by mintplugins** [comment]
@cklosowski With your PR I am able to add the widget without any errors through the Customizer.
