### ISSUE TITLE
Custom icons via edd_accepted_payment_icons are unwrapped

### ISSUE THREAD

**Issue by flowdee** [easydigitaldownloads/easy-digital-downloads#4917]
When registering custom payment icons

```
function pw_edd_payment_icon( $icons = array() ) {
    $icons['url/to/your/image/icon.png'] = 'Name of the Payment Method';
    return $icons;
}
add_filter( 'edd_accepted_payment_icons', 'pw_edd_payment_icon' );
```

the images are unwrapped out of the label container:

![bildschirmfoto_2016-09-01_um_08_41_36](https://cloud.githubusercontent.com/assets/2278756/18157926/60de0f98-7020-11e6-94f6-5b0e4217a661.png)

and being be displayed incorrectly on the settings screen:

![bildschirmfoto 2016-09-01 um 08 43 39](https://cloud.githubusercontent.com/assets/2278756/18157936/6cd5c7e6-7020-11e6-98c0-9720c65525ac.png)

Any idea why the label breaks?

**Comment by pippinsplugins** [comment]
I'm not immediately sure but we'll look into it.

**Comment by flowdee** [comment]
First time I saw it was when testing your [Sofort Banking](https://github.com/easydigitaldownloads/edd-sofort-banking) addon and afterwards I saw that it happens with other plugins as well. 🙈

**Comment by cklosowski** [comment]
To test this you just need to install and activate any 3rd party gateway that registers an icon. 2Checkout and Sofort are two that register one.

**Comment by flowdee** [comment]
Worked! Now it looks like it should! 👍 

![bildschirmfoto 2016-10-27 um 09 17 54](https://cloud.githubusercontent.com/assets/2278756/19757987/5f1c4f44-9c26-11e6-826b-0eaead16e968.png)
