### ISSUE TITLE
payment_meta['date'] should be updated to match the post_date

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#4918]
If you edit a Payment's date through the Downloads > Payment History page, the post_date is properly updated but the date stored in the payment_meta is not updated. 

Sample Payment:
```
  [date:protected] => 2016-09-01 22:33:00
  [completed_date:protected] => 2016-08-29 22:33:30
  
       ... edited out for brevity....

    [payment_meta:EDD_Payment:private] => Array
        (
     
            [date] => 2016-08-29 22:33:30
```

The last date above should match the "date" - not the "completed_date". This date exists purely for legacy purposes.

**Comment by michaelbeil** [comment]
This is due to some legacy code saving the date in `post_meta`: 

```php
if ( empty( $meta['date'] ) ) {
                $meta['date'] = get_post_field( 'post_date', $this->ID );
            }
```

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/47dd05e946d29b274fb90325e846c79332a67f23/includes/payments/class-edd-payment.php#L1513-L1515

**Comment by cklosowski** [comment]
@michaelbeil taht's where the entry is coming in, we just simply need to make sure that when a post is edited, that we also update this meta key.

**Comment by michaelbeil** [comment]
Yep. Just wanted to leave it here for posterity's sake based on the Slack convo.
