### ISSUE TITLE
Not all data removed when EDD is uninstalled

### ISSUE THREAD

**Issue by slaFFik** [easydigitaldownloads/easy-digital-downloads#4924]
When plugin is deleted an `uninstall.php` is loaded and executed.
But EDD doesn't clean things up after itself. There are obsolete tables left (like `edd_customers`) and lots of options in `wp_options` table.

Were that info left on purpose in DB?

**Comment by sunnyratilal** [comment]
As you can see, the [`uninstall.php`](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/uninstall.php) file contains all the code to delete the options and the custom tables.

The only instance when this won't happen is if you are on a multisite and the site you're trying to install EDD from isn't the primary site in the multisite network.

What is your environment setup? Single or multisite?

**Comment by slaFFik** [comment]
It was a single site.
But I'm not sure about `uninstall_on_delete` option - was it on or off on my site. That can be the reason why tables are not deleted. 
BUT I had much more than 2 options (see https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/uninstall.php#L74) that are deleted here. So it seems anyway not all options are deleted.

Also, what about `widget_edd_`?

**Comment by pippinsplugins** [comment]
Could you provide a list of all options that were left behind for your install?

**Comment by slaFFik** [comment]
already removed them manually, but I will try to find time today to install, configure, and then remove EDD locally to see that.

**Comment by pippinsplugins** [comment]
We'll look into it further.

**Comment by slaFFik** [comment]
I install EDD from trunk, activated, set all options that I can, checked the box to delete everything when plugin is uninstalled. And here is my report:

1. `wp_term_relationships` are not cleared.
2. List of options that are not cleared (12 total):
![image](https://cloud.githubusercontent.com/assets/282234/18340624/ae452490-75ae-11e6-84f8-5c38d3824a36.png)
3. I have not checked all the service records, that are created in wp_comments table, when purchase is made and processed. But looking at the code - you are using `wp_delete_post()`, so all comments for your post types should be deleted as well.

**Comment by pippinsplugins** [comment]
Thanks!

**Comment by slaFFik** [comment]
Also, not checked (might not be relevant for EDD), but a good thing not to forget: run `wp_clear_scheduled_hook()` too.

**Comment by SDavisMedia** [comment]
This was leftover for me on `master` (ignore the Software Licensing stuff):

<img width="932" alt="screenshot 2016-10-05 12 51 02" src="https://cloud.githubusercontent.com/assets/2359131/19128993/7345b060-8afa-11e6-916d-3533544a9886.png">

I'm not sure how to check the `wp_term_relationships` data.

-----

Here's what's left over after uninstalling on `issue/4924`:

<img width="714" alt="screenshot 2016-10-05 12 53 58" src="https://cloud.githubusercontent.com/assets/2359131/19129100/dd98ee50-8afa-11e6-9184-8551dd9f7230.png">


I'm not sure `edd_version_upgraded_from` should still be there. Everything else looks temporary or unrelated?

**Comment by pippinsplugins** [comment]
Try again now.

Some of those are from extensions / themes so cannot be deleted by core.

**Comment by SDavisMedia** [comment]
All good. Everything removed except extension related options. :+1:

**Comment by pippinsplugins** [comment]
Merging then.
