### ISSUE TITLE
Can't Uncheck All Checkboxes in Multi-Check

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/easy-digital-downloads#4928]
1. Visit Payment Gateways and enable two gateways.
2. Uncheck one. It unchecks/saves fine.
3. Uncheck the second one so it is empty and it will not save.

This happens on any multicheck instance (CC icons, payment gateways, etc).

- EDD. 2.6.6 (from .org)
- Twenty Fifteen
- No other plugins

Likely #4799 related

**Comment by spencerfinnell** [comment]
Also happens in master

**Comment by pippinsplugins** [comment]
PR submitted. Ready for testing!
