### ISSUE TITLE
Remove discount cron - Discount codes are changing to inactive without warning

### ISSUE THREAD

**Issue by michaelbeil** [easydigitaldownloads/easy-digital-downloads#4932]
I am seeing an issue on a user's site where 25 discount codes are being set to inactive every time the cron job is run: 
![screen shot 2016-09-09 at 15 30 39](https://cloud.githubusercontent.com/assets/4752949/18401903/71331c52-76a2-11e6-926d-350cd577f281.png) 

We may need to remove this cron for now until all discounts the world around will feel cherished and respected with their appropriate statuses in life.

Related: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4838

**Comment by pippinsplugins** [comment]
Let's disable the cron for now but leave all the code present. Once we absolutely nail down why the issue occurs _and_ also introduce a logging system of some kind, we can restore it.
