### ISSUE TITLE
Taxes to specific country

### ISSUE THREAD

**Issue by paparent** [easydigitaldownloads/easy-digital-downloads#4942]
I'm in Quebec (Canada), and depending the province, we have two taxes.. So for every sales in Canada, we have one tax (TPS) which is 5%. For sales in Quebec, we have that 5% of TPS, plus another one for quebec (TVQ), which is 9.975%. Is it doable with the current options? For international sales, no tax at all of course!

Thanks.

**Comment by paparent** [comment]
The big problem is that taxes like they are right now is harmonized, but in Quebec, we need them separated.

**Comment by pippinsplugins** [comment]
@paparent You can set tax rates up for each province separately. We do not, however, support setting up multiple tax rates for the same province.

**Comment by pippinsplugins** [comment]
As Github is purely for development tracking, I'm going to close this.

If you're like further assistance, please open a support ticket: https://easydigitaldownloads.com/support
