### ISSUE TITLE
Output Errors via Hook

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/easy-digital-downloads#4943]
Checkout errors are output via a hook which allows them to be removed/changed which is great. However shortcodes call `edd_print_errors()` directly which does not allow for manipulation. It would be nice if instead of calling the function directly it was attached via a hook.

It would be a backwards compatible template change since overwritten templates would just continue to call the function directly. 

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/templates/shortcode-register.php#L7

to

`do_action( 'edd_print_errors' );`

Thoughts?

**Comment by pippinsplugins** [comment]
Seems like a good idea to me!

**Comment by pippinsplugins** [comment]
Now might be a good time to introduce a `$context` parameter to the hook as well:
```php
do_action( 'edd_print_errors', 'checkout' );
do_action( 'edd_print_errors', 'profile' );
do_action( 'edd_print_errors', 'customer-edit' );
```

**Comment by michaelbeil** [comment]
For this PR we could add `checkout` as the `$context` parameter. Do you want to go over any other instances of `edd_print_errors`? Or should we make a separate issue for that?

**Comment by pippinsplugins** [comment]
Related #3242

**Comment by michaelbeil** [comment]
Oh, got it. We could wait until we add the `$context` parameter to `edd_has_errors` and then add contexts to all instances of edd_print_errors.

**Comment by spencerfinnell** [comment]
Love the idea of the context param!

**Comment by sunnyratilal** [comment]
I'm going to go ahead and merge this without the context as #3242 is milestoned for 2.8
