### ISSUE TITLE
Make quantity box optional per download

### ISSUE THREAD

**Issue by michaelbeil** [easydigitaldownloads/easy-digital-downloads#4945]
When `Item Quantities` is enabled within Settings > Misc, all downloads have an item quantity option at checkout. It would be great to be able to disable item quantity on a per download basis.

**Comment by pippinsplugins** [comment]
Related #2955

**Comment by pippinsplugins** [comment]
Ready for testing!

**Comment by pippinsplugins** [comment]
![screen shot 2016-10-06 at 3 00 04 pm](https://cloud.githubusercontent.com/assets/1034109/19168396/975cd1be-8bd5-11e6-9d43-0b86ba512789.png)

**Comment by SDavisMedia** [comment]
I can't break it anywhere. The quantity still outputs on the purchase confirmation template, as if the customer actually chose "1" but that's not a big deal, I don't think. :+1:

**Comment by pippinsplugins** [comment]
I don't think that's an issue.

**Comment by pippinsplugins** [comment]
Assigned to @cklosowski for a final code review before merging.

**Comment by SDavisMedia** [comment]
@cklosowski reminder that this needs a final review

**Comment by sunnyratilal** [comment]
Tested and working as expected 👍

**Comment by sunnyratilal** [comment]
Merged into `release/2.7`

**Comment by pippinsplugins** [comment]
:+1:
