### ISSUE TITLE
PayPal security issues

### ISSUE THREAD

**Issue by bseddon** [easydigitaldownloads/easy-digital-downloads#4947]
PayPal has been sending out emails recently alerting us to impending changes to their use of security.

Are there any potential issues with EDD?

**Comment by cklosowski** [comment]
@bseddon I'm assuming this is an email about the TLS 1.2 updates? If so yes, we've already taken measures to assist in this on the EDD side. The other layers that need to be updated are with your hosting provider. There is a plugin you can install to test your server's compatibility:
https://wordpress.org/plugins/tls-1-2-compatibility-test/

In the future questions like this are better posed via the support form as they are not necessarily for specific development issues: https://easydigitaldownloads.com/support
