### ISSUE TITLE
[edd_license_keys] shows wrong expiration date for Bundles

### ISSUE THREAD

**Issue by Netzberufler** [easydigitaldownloads/easy-digital-downloads#4951]
I'm selling a Lifetime Bundle with unlimited sites and no expiration date. When I release a new theme I add it to the Bundle and re-generate the license keys. 

Everything works fine, but the license page shows the wrong expiration date for the newly added theme. Instead of using the expiration date of the Bundle (never), it shows the expiration date of the single download, which is one year.

So I get contacted by customers why some of their licenses expire although they have purchased a Lifetime Bundle.

Screenshot: 
![screen-shot-2016-09-16-at-11-08-40-am](https://cloud.githubusercontent.com/assets/6862755/18606985/8428fc82-7cbf-11e6-993b-9ce6d5adc834.png)

**Comment by pippinsplugins** [comment]
@Netzberufler This bug is actually for the Software Licensing extension so I'll need to close this and open it in the extension repo. It's a private repo so it won't be accessible but I'll be sure it gets logged!

**Comment by Netzberufler** [comment]
Thank you!
