### ISSUE TITLE
PHP Notice on script.php

### ISSUE THREAD

**Issue by Moonomo** [easydigitaldownloads/easy-digital-downloads#4952]
With Easy Digital Downloads active, every time a hit on 404 page generates the following notice:

> Notice:  Trying to get property of non-object in ~/wp-content/plugins/easy-digital-downloads/includes/scripts.php on line [38](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/scripts.php#L38).

A simple `isset( $post->post_content )` checks would fix the error. Thanks.

**Comment by pippinsplugins** [comment]
Thanks for the report! We'll get that resolved.

**Comment by pippinsplugins** [comment]
Another report: https://secure.helpscout.net/conversation/254658034/43030/?folderId=180499

**Comment by pippinsplugins** [comment]
PR: https://github.com/easydigitaldownloads/easy-digital-downloads/pull/4966

**Comment by spencerfinnell** [comment]
Might be better to check if the post object exists at all instead? I think that is the real issue; not that there is no content filled out. 

`is_a( $post, 'WP_Post' )` around the ID and post_content usage.
