### ISSUE TITLE
Repeatable rows not properly adding data keys for variable price select boxes

### ISSUE THREAD

**Issue by ghost1227** [easydigitaldownloads/easy-digital-downloads#4953]
We discovered this morning that there is a bug in the Content Restriction plugin caused by a bug in EDD core. In the `admin-scripts.js` file, when a repeatable row is added it sets a `data-key` property for the new `tr` item defined as the `data-key` value for the last row item + 1. However, variably priced items in repeatable rows depend on having the same property added to the price ID select box (second select box in the row). Right now, this isn't being added, so the row is being added with an ID of `0`. The result of this is that when variably priced items are added through repeatable rows, only the final item is saved.

**Comment by SDavisMedia** [comment]
I've tested this within the context of Content Restriction issue 45. All good there. :+1: 

I'd assume it needs more testing, though. Feel free to list additional testing ideas.

**Comment by cklosowski** [comment]
This seems to be working just fine, not seeing any major issues with hit. You good with this change @pippinsplugins ?

**Comment by pippinsplugins** [comment]
Approved
