### ISSUE TITLE
Add a per-download hook to the edd_receipt shortcode

### ISSUE THREAD

**Issue by ghost1227** [easydigitaldownloads/easy-digital-downloads#4956]
The receipt page allows customization in and after the main table, and per-file in the Products table, but not per-download. I propose adding a per-download action at the end of each row in the Products table.

**Comment by ghost1227** [comment]
Correction, it should be at the end of the first table cell (just before the `</td>`).

**Comment by sunnyratilal** [comment]
Merged into `release/2.7`
