### ISSUE TITLE
edd_update_payment_status() creates new blank payment record if given an invalid payment ID

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#4962]
If an invalid payment ID is supplied to `edd_update_payment_status()`, the function will instantiate a new instance of `EDD_Payment` and then call `save()` without checking if the payment was successfully setup.

**Comment by michaelbeil** [comment]
How can we test this?

**Comment by ghost1227** [comment]
The console plugin for Debug Bar. Run `edd_update_payment_status()` through it.

**Comment by cklosowski** [comment]
Working great. Tested with debug bar console, returns `false` when the ID isn't a payment and `true` when passed a valid license ID.
