### ISSUE TITLE
Allow exporting a download history of a specific product

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#4964]
It's currently not possible to export the file download history of a specific download. We need to support this.

**Comment by sanketio** [comment]
Hi @cklosowski 

I have sent a PR ( https://github.com/easydigitaldownloads/easy-digital-downloads/pull/5045 ). Please let me know if you need any change in that.

**Comment by cklosowski** [comment]
Working up a new PR, I've merged the current work into `issue/4964` to add a few enhancements.

**Comment by cklosowski** [comment]
Ok, looking at the changes needed in order to support the download ID within the file name, we'll have to rewrite the export classes a bit. I'm going to make a future enhancement for that.

**Comment by mintplugins** [comment]
@cklosowski Working properly for me in my tests. Should we include the payment ID attached to the file download in the CSV as well?

**Comment by SDavisMedia** [comment]
Working well on my end. :+1:

**Comment by cklosowski** [comment]
@mintplugins see my above comment. To do it is going to take an extensive rewrite, I've opened an issue to make the file names exported to be more flexible #5097

**Comment by mintplugins** [comment]
@cklosowski It's above my pay grade :P But I'm confused as to why the filename needs to change for us to include a payment ID column in the exported CSV.

**Comment by cklosowski** [comment]
Oh sorry, I misread your comment @mintplugins. Forgive me as I was mobile at the time. I'd say let's open another ticket and milestone that for 2.8 for now. Since it's out of the scope of the current request for this issue.
