### ISSUE TITLE
Upload file text is missaligned

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#4975]
Tested in Safari, Firefox, and Chrome.
![screen shot 2016-09-23 at 9 15 48 am](https://cloud.githubusercontent.com/assets/1390124/18793154/5cc1f4ce-816e-11e6-9045-259927883573.png)

**Comment by ghost1227** [comment]
Pretty sure that if this is fixed in core it'll carry over to fields in most plugins, but we might want to double check the big ones once this is fixed. Particularly of note, I know that SL currently has the same issue.

**Comment by cklosowski** [comment]
yeah, the problem is a single pixel alignment. I'll make sure to test with a few major extensions @ghost1227

**Comment by ghost1227** [comment]
👍
