### ISSUE TITLE
Why add a new download is not the latest display of the site?

### ISSUE THREAD

**Issue by kinkf** [easydigitaldownloads/easy-digital-downloads#4980]
Add a new download posts, in the download directory in the normal display, but does not show in the site's home page.
for example:
www.example.com/index.php/downloads/11111      (Normal display)
www.example.com/index.php                    (Only show the original new posts, do not show ‘easy-digital-downloads’ inside the post)

**Comment by kinkf** [comment]
Why 'easy-digital-downloads' below the post is not displayed on the home page?

**Comment by chriscct7** [comment]
As Github is purely for development tracking, I'm going to close this.

If you're like further assistance, please open a support ticket: https://easydigitaldownloads.com/support
