### ISSUE TITLE
PayPal: disable redirect on Buy Now buttons if PayPal gateway is disabled

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#4981]
We've seen it happen numerous times where a site is set up with Stripe, 2Checkout or any other gateway that supports Buy Now buttons and when a purchase button is clicked, the customer is redirected to PayPal.

Typically this means there is a JS error or something blocking the Stripe Checkout JS but regardless the redirect to PayPal should not occur.

If the PayPal gateway is disabled, let's bail before redirecting to PayPal.

**Comment by pippinsplugins** [comment]
I'm not really sure what should happen here if PayPal is disabled and the other buy now action (such as Stripe) fails, maybe a wp_die() with an error message?

**Comment by cklosowski** [comment]
I think a wp_die() with an error message would be fine...might be able to find a classier way to do this via `edd_add_error` once #4943 is instituted with a `context` parameter that we can latch onto?

**Comment by pippinsplugins** [comment]
If we can make it pretty, let's make it pretty.

**Comment by cklosowski** [comment]
Ok I've got this working, I believe. What happens is, if an error occurs ( I forced mine by enabling stripe checkout, doing a buy now purchase link, and editing the JS in stripe to cause an error. Drop this on line 1352 of edd-stripe-new.php `aler('here');`

This will cause stripe buy now to fail for the purchase link on a page, and fallback to the defaults, which is `paypal`.

What will then happen is...we'll look at the information that was supposed to go straight to the gateway, and add it to the cart, and then redirect the person to the cart with an error messaging asking them to try their purchase again.

**Comment by pippinsplugins** [comment]
This looks good to me.

**Comment by sunnyratilal** [comment]
This is really neat!

Great work as always @cklosowski 👍

**Comment by sunnyratilal** [comment]
Merged into `release/2.7`
