### ISSUE TITLE
Support iOS app one-click configuration

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#4986]
The upcoming release of the iOS app will support the `edd://` link scheme. We'll be able to offer people a link to configure their site instead of having to copy and paste a bunch of keys and tokens. The link format is:
`edd://new?sitename=?&siteurl=?&key=?&token=?`

**Comment by pippinsplugins** [comment]
Awesome!

**Comment by cklosowski** [comment]
I have this written in a helper plugin already, just need to move it into core. shouldn't be too much effort.

**Comment by cklosowski** [comment]
This will require the beta 2.0 app or the live one (if it's live by the time you're testing).

**Comment by cklosowski** [comment]
![screen shot 2016-10-25 at 2 19 13 pm](https://cloud.githubusercontent.com/assets/1390124/19704826/3166889e-9abe-11e6-840c-ab4aeb5d4c60.png)

**Comment by cklosowski** [comment]
If you are testing this on non-mobile, you'll need to install the Chrome User Agent Switcher (or a similar extension for our browser) as it's wrapped in a `wp_is_mobile()` check, which is based on User Agent.

**Comment by SDavisMedia** [comment]
@cklosowski I'm missing something about testing this. Where's your screenshot from?

**Comment by pippinsplugins** [comment]
@SDavisMedia your user profile page

**Comment by SDavisMedia** [comment]
@pippinsplugins Derp, thanks.

@cklosowski This is great. Worked perfectly for me on my iPad. :+1:

**Comment by cklosowski** [comment]
Merging, but leaving as open so we remember to write the doc updates.

**Comment by cklosowski** [comment]
Talked with @sunnyratilal we're going to get a gif or a screencast for the docs that show whgere to find the button in admin, clicking it, and ending up in the app with it loaded. I think that'll be a huge selling feature of this new version

**Comment by cklosowski** [comment]
Doc is ready to publish with changes in draft. closing.

**Comment by michaelbeil** [comment]
Works great!

**Comment by michaelbeil** [comment]
Can we remove the needs docs label?

**Comment by sunnyratilal** [comment]
Yep it's all been updated.

**Comment by michaelbeil** [comment]
🎉
