### ISSUE TITLE
payments query wrong end_date calculation

### ISSUE THREAD

**Issue by selul** [easydigitaldownloads/easy-digital-downloads#4988]
hello, 

I think there is an error when we use end_date in payments query class. 

For instance if you have this code: 

```
$query = new EDD_Payments_Query(
                array( 
                    "start_date"   =>time()-100,
                    "end_date"   =>time()  
                )
            );
```

this should get all the payments from the last 100 seconds, but in fact it returns none. 

When analyzing the query, it turned out that for date conversion from timestamp we hardcode the format for hours/minute/seconds: 

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/class-edd-stats.php#L524

i think it should follow the same logic as for the start_date: 

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/class-edd-stats.php#L512

Thanks

**Comment by pippinsplugins** [comment]
We can look at adjusting this for 2.7.

**Comment by selul** [comment]
also, i found out that if i set the correct format there, when the end_date si not set in arguments array and the start_date is present, they will have the same value, which is not ok: 

https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4988#issuecomment-250015712 


I think if the end_date is not present it should use time() 

Thanks !

**Comment by ghost1227** [comment]
I agree with the first recommendation, but I'm not sold on the second recommendation. Thoughts on using time() if end_date isn't present @pippinsplugins?

**Comment by pippinsplugins** [comment]
Current time would be fine when an end date isn't set. No reason for payments to be in the future.

**Comment by ghost1227** [comment]
This looks good, but we'll need to remember to update the unit tests for it @sunnyratilal

**Comment by pippinsplugins** [comment]
@sunnyratilal can you update the unit tests for this please?

**Comment by sunnyratilal** [comment]
Fixed in 519a661ab25f96e547da2b64c300668257665d1c

We won't be able to expect a predefined return value anymore hence the `assertEquals` was removed from the unit test.  This is because we set `$end_date` to `time()`.

**Comment by ghost1227** [comment]
This looks good to me!

**Comment by pippinsplugins** [comment]
Part of the changes here need to be reverted: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5603
