### ISSUE TITLE
Billing address fields are not saving in the payment details page

### ISSUE THREAD

**Issue by michaelbeil** [easydigitaldownloads/easy-digital-downloads#4989]
There is an issue preventing users from adding/changing an address in the payment details page. One would expect to be able to type in the address and save it, but the Address Line 1 and Address Line 2 lines clear out on save. Other address fields seem to be affected as well.

**Comment by mindctrl** [comment]
This was introduced in either 2.6.7 or 2.6.8, because it works in 2.6.6.

**Comment by pippinsplugins** [comment]
Probably here https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4777

**Comment by cklosowski** [comment]
Not sure how these are related, yet, but #4777 only affected the customer screen and customer actions. Saving on the payment is specific to the payment actions file. Will dig in to see what's going on.

**Comment by cklosowski** [comment]
It's related to the changes for #4887. Looking to see if I can fix it up.

**Comment by SDavisMedia** [comment]
Replicated this issue as well as Issue 5020 on `master` and confirmed both are fixed in `issue/4989`. :+1:

**Comment by ghost1227** [comment]
I'll second @SDavisMedia's confirmation. Bug squashed

**Comment by pippinsplugins** [comment]
Fix confirmed here as well.
