### ISSUE TITLE
EDD user names : some special characters may not be parsed and displayed correctly

### ISSUE THREAD

**Issue by Nikeo** [easydigitaldownloads/easy-digital-downloads#4991]
Use case : a user name is Bronko**ł**ajewic (see the specific ł character)

- in the admin > user the name is properly filtered and displayed Bronkolajewic ("ł" has been replaced by "l" )
- but in EDD users it is displayed Bronko**ł**ajewic

=> this leads to **problems when generating the invoice**, because the special character will be turned into a "?", and the user will see the following name in his invoice : Bronko**?**ajewic

Privacy Note : Bronko**ł**ajewic is an example name and his not taken from a real person.

**Comment by pippinsplugins** [comment]
@Nikeo which invoice plugin are you seeing the issue with?

**Comment by Nikeo** [comment]
Easy Digital Downloads - PDF Invoices

**Comment by pippinsplugins** [comment]
Ok that's going to be a bug with the PDF Invoices plugin then, not the core Easy Digital Downloads.

This repository is for core only.

Could you go ahead and open a support ticket so the support team can assist you? https://easydigitaldownloads.com/support
