### ISSUE TITLE
Easy digital download and 3d secure (3ds)

### ISSUE THREAD

**Issue by DaTribe** [easydigitaldownloads/easy-digital-downloads#4997]
It would be good if this plugin supported this feature. This has been recommended by my merchant since there seems to be a lot of fraud with digital purchases.

https://en.wikipedia.org/wiki/3-D_Secure

Is this something that has been done already or in the works or can be achieved using another EDD plugin?

**Comment by sunnyratilal** [comment]
Hi,

EDD isn't a payment processor a merchant. We pass data to merchants such as PayPal/Stripe who then handle the transaction.

3D Secure is also something you set up with bank account alongside Verified by Visa so if it's not set up with your bank account then you won't have to do the verification when making a transaction.

**Comment by DaTribe** [comment]
So what you are saying that if 3ds needed to be implemented then there would be no coding involved from and EDD perspective and I could just simply set it up through my merchant even if payment are taken directly on my website?

**Comment by sunnyratilal** [comment]
From my understanding, that is the case.

More information about 3D Secure and PayPal (the default gateway bundled with EDD) is available here: https://www.paypal.com/uk/webapps/mpp/3dsecure-faqs

**Comment by DaTribe** [comment]
Okay, thanks for your help. I will try to set it up and hopefully won't be revisiting this issue.
