### ISSUE TITLE
Negative fees not affected product earnings

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#5000]
When the `download_id` parameter is set, the fee amount is supposed to affect the earnings stats of the product when it is purchased.

That does not, however, appear to be happening but it used to.

Example fee recorded in payment meta:

```
Array
(
    [0] => Array
        (
            [amount] => -1.67
            [label] => 10% - Discount Pro Test
            [no_tax] => 1
            [type] => fee
            [download_id] => 6465
            [price_id] => 
            [id] => dp_0
        )

)
```

Order details:
![screen shot 2016-10-03 at 4 14 55 pm](https://cloud.githubusercontent.com/assets/1034109/19054333/90f04534-8984-11e6-9d46-8eeea6af95ae.png)

Note how the item amount says $20 instead of $18.33.

**Comment by pippinsplugins** [comment]
Ah, it's probably due to the empty `price_id`.

**Comment by chriscct7** [comment]
This is caused by EDD having at one point switched where the price_id was stored. Right now, Discounts Pro looks for it in the old location, which was based on some EDD functions that are currently looking in the wrong place. This has been corrected in Discounts Pro for next release.

We should find every place that looks in `$item['item_number']['options']['price_id']` or `$item['options']['price_id']` with the helper function we added for this reason edd_get_cart_item_price_id( $item ) and use that if it's not === null.

**Comment by chriscct7** [comment]
#5002 needs to be cleaned up and a slight reworking but it would make a nice addition to partially unit test this issue in the future.

**Comment by chriscct7** [comment]
Among the major core EDD functions broken are edd_get_cart_content_details, and also edd_build_straight_to_gateway_data which means that the order data saved for all buy now created orders is broken (you'll be able to process it fine, but the data saved is broken because of https://github.com/easydigitaldownloads/easy-digital-downloads/blob/64d11791d42897a8b0b3da62ecf071baf91feec6/includes/gateways/functions.php#L212.

We might need to do an upgrade routine that fixes order data that was incorrectly saved for buy it now purchases as a result.

**Comment by chriscct7** [comment]
Actually the way that's used, it doesn't even look like buy it now amount retrieval will work for non-default option variable price purchases. Testing...

**Comment by chriscct7** [comment]
Confirmed, buy it now is broken. See #5018

**Comment by chriscct7** [comment]
Giving this high pri, as this is breaking other extensions and even other parts of EDD core.

**Comment by cklosowski** [comment]
So here's the question though...are we talking about specifc line items or earnings...we do affect earnings totals here: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/3763

Now, this is when asking for the earnings totals of a download, not for a specific line item on a sale, which I don't remember us ever doing because fees specific to a download have never affected the actual `price, total, and subtotal` of a cart/payment line item.

Ok..Let's say I have a download with a price Id in my payment details. That download has a price of $10. If I then have a `$1 discount` via fee, yes, the product earnings are `$9`, but technically, the item price is $10, and we have a new line item of the fee for `-$1`. So the key is, do we actually modify the `$payment->cart_details[0]['price']` or no? I don't think we should be modifying what the item costs in the cart specifically since the fee is a line item affecting the cart total, but only in the case that the product with the proper price ID is in the cart.

**Comment by cklosowski** [comment]
@pippinsplugins @chriscct7 ^^

**Comment by chriscct7** [comment]
I'm super tired but having re-read it a few times now just to make sure I'm not misreading anything I think I buy that. Let me re-reead this tomorrow when I get a chance.

**Comment by cklosowski** [comment]
No worries @chriscct7 it's a super complex issue to dig into, and one if we're going to make any modifications to, we have to make sure we do it right since it's far reaching.

**Comment by pippinsplugins** [comment]
`EDD_Payment_Stats` takes into account negatives fees, but the value of `_edd_earnings_stats` does not, so seems all we need to do is adjust the amount passed to `increase_earnings()`. Yes?

**Comment by cklosowski** [comment]
@pippinsplugins I can agree that we should alter the `_edd_earnings_stats` when we increase or decrease it's earnings. We'd have to do it on both. I don't vote for a line item having it's amounts modified. I think once we rework the payment structure to have a better line item distinction, this will work itself out to read easier to the end user.

**Comment by pippinsplugins** [comment]
I disagree. Line items must show the proper amount. Maybe that means we need to visually reveal subtotal and total for line items.

**Comment by cklosowski** [comment]
@pippinsplugins maybe it's time that 'fees' get their own line item instead of being an asside in the metabox to the right?

**Comment by cklosowski** [comment]
I think including fees inline (not editable) would make things VERY clear to what's happening with the line items on a purchase.

**Comment by pippinsplugins** [comment]
I support that 100%.

**Comment by cklosowski** [comment]
Ok i'll take this on and get something worked up. @pippinsplugins thoughts on how to handle past purchases? I think we could do this with a simple 'notice' that can be dismissed, that tells them to go update the download earnings after the upgrade with a Downloads stats recount.

**Comment by pippinsplugins** [comment]
I don't think we affect past purchases in any way beyond maybe in documentation / faqs

**Comment by cklosowski** [comment]
Ok, this does a few things.

1) It makes it so when a payment adds/removes a download from a payment, fees are taken into account when increasing or decreasing the download's total earnings.

2) This updates the View Order Details screen to be a little more clear about how fees are affecting the downloads in the payment. Item specific fees are shown nested under their related product, and then include a 'total' line to help identify how the fee affects it's actual 'cost' in the end.

Global cart fees are now shown after all the downloads, and are designated with `Fee:`.

The fees have been removed from the sidebar metabox and recalculations now run off the items in the main area. This actually fixes a few bugs too.

1) Removing an item from the cart that had a specific fee on it, also now removes the fee associated with it.
2) The `EDD_Download::update_meta` method would return false if you passed in an `empty $meta_value`. This made it so you could not update a download's earnings total to `0`.

@easydigitaldownloads/core-devs

**Comment by cklosowski** [comment]
Ok, fully reverted. None of the above is relevant so i'm removing it :). This simply looks at the cart item fees, and if they are negative, it modifies the 'price' of the item.

**Comment by SDavisMedia** [comment]
After everything that has happened in this issue, what's left that I should be looking for in testing? I have a $50 product with a 50% Discounts Pro discount applied. Here's what I get on `master` vs `issue/5000`:

Master:
<img width="1269" alt="screenshot 2016-10-18 15 42 46" src="https://cloud.githubusercontent.com/assets/2359131/19499123/9540856a-9549-11e6-9233-dda0bca11ddc.png">

issue/5000:
<img width="1270" alt="screenshot 2016-10-18 15 43 40" src="https://cloud.githubusercontent.com/assets/2359131/19499136/aa8a16a2-9549-11e6-8013-02af489a6e23.png">

-----

On `issue/5000`, what's with the total price showing $0.00? Should be $25.

Please list what's being tested for and I'll gladly do it.

**Comment by pippinsplugins** [comment]
Total price should not be `0.00`, it should be `$25`.

Both item price and total should be 25 in this case, so something is wrong here.

**Comment by cklosowski** [comment]
@SDavisMedia any other extensions running?

**Comment by SDavisMedia** [comment]
I'm replicating this easily with nothing activated but EDD and Discounts Pro. Here's my discount:

<img width="965" alt="screenshot 2016-10-18 21 57 49" src="https://cloud.githubusercontent.com/assets/2359131/19506167/ff4417ea-957d-11e6-8eb3-adc8da435f95.png">

I was able to replicate with an older product as well as a new product. `master` is good but easily replicated on `issue/5000`. Discounts Pro `master`.

No clue what's causing it.

**Comment by SDavisMedia** [comment]
Oh I think the discount is being "doubled" somehow. Just tried a Fixed Price discount of $5 on a $50 product and the Total Price came out to $40 ... or two times the discount. 

Went back and changed my 50% discount to 25% and it ended up taking 50% off the Total Price, or two times the discount.

<img width="1274" alt="screenshot 2016-10-18 22 09 09" src="https://cloud.githubusercontent.com/assets/2359131/19506334/850c44be-957f-11e6-89bb-4122b487ce95.png">

🤔

**Comment by pippinsplugins** [comment]
I think that's exactly what's happening. The negative fee is reducing the item price but then it's also reducing the total amount _after_ the item price has already been reduced.

**Comment by cklosowski** [comment]
Going to verify this on both Discounts Pro `master` and `release/1.5` I wasn't seeing this happen but I'm unsure what branch of DP I was on when it happened.

**Comment by cklosowski** [comment]
@SDavisMedia ok ready for testing again, please pull latest `issue/5000` and see how that works for you. I saw the same behavior on both branches of Discounts Pro.

**Comment by SDavisMedia** [comment]
@cklosowski Everything looks right for me now. :+1:

**Comment by pippinsplugins** [comment]
@SDavisMedia @cklosowski can you both please test with purchases that go to PayPal standard and also ones that go to 2Checkout? Both of those gateways adjust item amounts at the merchant side for fees so we need to ensure no item amounts are wrong there.

**Comment by cklosowski** [comment]
@pippinsplugins PayPal:
![screen shot 2016-10-19 at 12 47 38 pm](https://cloud.githubusercontent.com/assets/1390124/19534818/3d8f2ffe-95fa-11e6-8bab-a5f277297ac5.png)

I have to go through and configure 2Checkout. Been a minute since I had that one setup and working.

**Comment by pippinsplugins** [comment]
Let's be extra thorough and do PayPal Express too please.

**Comment by cklosowski** [comment]
already done, getting you screenshots

**Comment by SDavisMedia** [comment]
I'm good to go already with PayPal Standard. Gonna test PayPal Express & 2Checkout once I get them set up.

**Comment by cklosowski** [comment]
Express does have a problem, pro seemed fine when I did it, re-checking

**Comment by cklosowski** [comment]
oh, that's why i had the wrong of the two `PayPal` options selected on my checkout. let me disable standard quick and try again.

**Comment by cklosowski** [comment]
PayPal Express ($100 product with a 50% Discounts Pro discount)
![screen shot 2016-10-19 at 2 04 25 pm](https://cloud.githubusercontent.com/assets/1390124/19537516/20229bf8-9605-11e6-95bd-d7a9c1023e5a.png)

![screen shot 2016-10-19 at 2 04 33 pm](https://cloud.githubusercontent.com/assets/1390124/19537524/23d7d858-9605-11e6-947c-954783a1480d.png)

**Comment by cklosowski** [comment]
I'm punting this to 2.6.10. We have a few concerns with how gateways are handling fees. Since in the way we would 'like' to solve this it would reduce the `price` value of the download on the payment when the fee is negative. The problem is that some gateways account for this and some do not. This means that you could end up with a negative fee reducing twice at the gateway tier.

We need to come up with a solid plan for this.

**Comment by cklosowski** [comment]
After a little more discussion (moments later) we're going to elect to allow negative fees to affect the download earnings, but not the payments themselves past just being how it currently works in master.

**Comment by cklosowski** [comment]
New branch to test `issue/5000-alt`

**Comment by pippinsplugins** [comment]
@cklosowski @SDavisMedia I just ran through and tested this in multiple ways. Everything looks great!

I did the following:

- Made a purchase without any fees to confirm nothing odd was effected
- Made a purchase with Simple Shipping and confirmed the shipping fee did _not_ get included in the earnings increase
- Made a purchase with Discounts Pro and a 50% discount and confirmed the discounted price _was_ included in the earnings increase
- Refunded the purchase without any fees and confirmed the earnings decrease was correct
- Added new item to the purchase with shipping fees, recalculated totals, and confirmed amounts were all correct
- Removed the item with shipping fees from the payment, recalculated total, and confirmed the shipping fees were _not_ included in the earnings decrease
- Remove the item that had a Discounts Pro discount and confirmed the fee was properly removed from the payment and that the earnings decrease properly accounted  for the discount

**Comment by SDavisMedia** [comment]
@pippinsplugins Solid. We've all hit quite a few scenarios now and still can't break it. Thumbs up from me! :+1:

**Comment by mintplugins** [comment]
Want another set of eyes on this?

**Comment by pippinsplugins** [comment]
@mintplugins yes please!

**Comment by mintplugins** [comment]
I just ran a test with Volume Discounts using quantity. It is showing earnings of $300 in the product when the store has actually only earned $200. 

<img width="266" alt="screen shot 2016-10-20 at 10 46 09 am" src="https://cloud.githubusercontent.com/assets/1638128/19564713/7ca6d3f0-96b2-11e6-8db4-c4289115d705.png">
<img width="1262" alt="screen shot 2016-10-20 at 10 46 28 am" src="https://cloud.githubusercontent.com/assets/1638128/19564714/7ca8674c-96b2-11e6-9e16-ae2d44ccfcbd.png">
<img width="1269" alt="screen shot 2016-10-20 at 10 46 57 am" src="https://cloud.githubusercontent.com/assets/1638128/19564740/8ed12e4a-96b2-11e6-91c2-86f3853e4eeb.png">

**Comment by SDavisMedia** [comment]
@mintplugins You still get $300 if you recount your earnings?

**Comment by mintplugins** [comment]
@SDavisMedia After running a recount, it is still showing $300 in the product. However I noticed the "sales" changed from 3 to 2 - which is actually incorrect. There were 3 sales of it - but it has only earned $200.
<img width="276" alt="screen shot 2016-10-20 at 10 50 02 am" src="https://cloud.githubusercontent.com/assets/1638128/19564911/142ba840-96b3-11e6-8cbb-8a18358b67bc.png">

**Comment by pippinsplugins** [comment]
Fairly certain that's a Volume Discounts issue. It does not assign the discounts to individual products.

**Comment by mintplugins** [comment]
I have gone through these steps and everything looks good to me:

- Made a purchase without any fees to confirm nothing odd was effected
- Made a purchase with Simple Shipping and confirmed the shipping fee did not get included in the earnings increase
- Made a purchase with Discounts Pro and a 50% discount and confirmed the discounted price was included in the earnings increase
- Refunded the purchase without any fees and confirmed the earnings decrease was correct
- Refunded Shipping purchase
- Recalculated total, and confirmed the shipping fees were not included in the earnings decrease
- Remove the item that had a Discounts Pro discount and confirmed the fee was properly removed from the payment and that the earnings decrease properly accounted for the discount

**Comment by cklosowski** [comment]
Awesome thanks @SDavisMedia @mintplugins and @pippinsplugins I think, @pippinsplugins that as soon as you are good with this go ahead and merge.

**Comment by pippinsplugins** [comment]
Merge!
