### ISSUE TITLE
When adding fee to cart, precision in decimal spot can be lost

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#5003]
Inserting a fee with the amount of 50.00 will result in the fee getting stored as 50.0 due to PHP rounding it. We should ensure when decimal place 1 is set, that decimal place 2 is a zero if not set so people can do basic precision reliant comparisons.

**Comment by sunnyratilal** [comment]
PR opened at #5315

**Comment by pippinsplugins** [comment]
@sunnyratilal we'll need unit tests added for this before we can merge it.
