### ISSUE TITLE
Can add fees to cart for download / price ID that do not exist in cart

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#5004]
Should you be able to add a fee to the cart that specifies the download ID and price ID if that pair does not exist in the cart?

I'm thinking that should return false when add fee is called (signifying fee cannot be added), true (or the index of the fee in the fees array for cart) when added, and a new param to override it not being allowed to be applied to cart when no match is in cart. Thoughts?

This idea came up while looking at #5000

**Comment by pippinsplugins** [comment]
I do not think that should be permitted. Let's prevent it.

**Comment by cklosowski** [comment]
Since this currently returns an array of `$fees`, we can't make it return `true` if it was successful, I think that causes a breaking change if something is expecting the fees to be returned, but we can deff return `false` if it wasn't added correctly.

**Comment by cklosowski** [comment]
To test this out, I used debug bar to verify it wasn't adding to the cart:
1) Add an item to the cart (noting it's download ID)
2) Using debug bar run the following:
`var_dump( EDD()->fees->add_fee( array( 'amount' => '20.00', 'label' => 'Arbitrary Item Fee', 'download_id' => <download_id>, 'id' => 'arbitrary_fee' ) ) );`
3) The fee should be in the cart
4) Empty the cart (dev tools works well)
5) Open debug bar and try and run the following:
`var_dump( EDD()->fees->add_fee( array( 'amount' => '20.00', 'label' => 'Arbitrary Item Fee', 'download_id' => <download_id>, 'id' => 'arbitrary_fee' ) ) );`

Step 5 should var_dump out `false` as it does not allow the fee for the download ID to be added when it's not in the cart.

**Comment by SDavisMedia** [comment]
All checks out here. :+1:

**Comment by cklosowski** [comment]
Awesome thanks @SDavisMedia, @chriscct7 this looking good for you from a code standpoint?

**Comment by cklosowski** [comment]
Looks like I forgot the case of Download ID + price ID. So if the fee contains both download and price IDs, and that specific price ID isn't in the cart we need to not allow it either. Should be a simple fix. I'll get it pushed up and more unit tests around it.

**Comment by cklosowski** [comment]
Ignore more, it's totally there:
```
		if ( ! empty( $args['download_id'] ) ) {
			$options = isset( $args['price_id'] ) ? array( 'price_id' => $args['price_id'] ) : array();
			if ( ! edd_item_in_cart( $args['download_id'], $options ) ) {
				return false;
			}
		}
```

**Comment by cklosowski** [comment]
merging away!
