### ISSUE TITLE
Exported CSVs show "Complete" status as "publish"

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#5006]
When exporting a CSV of Payments, the "status" column will show "publish" for posts. When exporting, the verbiage is to export "Complete" payments. Should we show "Complete" as the status instead of "publish"?

<img width="150" alt="screen shot 2016-10-04 at 2 23 27 pm" src="https://cloud.githubusercontent.com/assets/1638128/19087168/18da04e8-8a3f-11e6-9322-c51d45a2867f.png">

**Comment by jaredatch** [comment]
Seemingly at the same time this was introduced, Date is no longer properly exported. All Date values are empty.

**Comment by pippinsplugins** [comment]
Dates have been fixed in #4994

**Comment by jaredatch** [comment]
Whoops, sorry about that!

**Comment by cklosowski** [comment]
There's two sides of this.
1) Do we make it human readable and make it `complete` into which, the importer will simply change it to `publish`.
2) Do we keep it `publish` so that it's matching whatever the end result of the import is going to be.

Thoughts @easydigitaldownloads/core-devs

**Comment by pippinsplugins** [comment]
I vote for `complete`

**Comment by michaelbeil** [comment]
complete seems better.

**Comment by sanketio** [comment]
@pippinsplugins 

I have sent PR ( https://github.com/easydigitaldownloads/easy-digital-downloads/pull/5042 ). Let me know if there is any change in that.

**Comment by pippinsplugins** [comment]
PR looks fine to me.

**Comment by sanketio** [comment]
Great. :)

**Comment by SDavisMedia** [comment]
Exporting on the PR branch producing "complete" for all the payment statuses is importing just fine for me on `master`. :+1:

**Comment by pippinsplugins** [comment]
:+1:

**Comment by SDavisMedia** [comment]
I'm not sure what else this needs.

**Comment by pippinsplugins** [comment]
@SDavisMedia nothing else :)
