### ISSUE TITLE
Question: Could I use this in place of prosites to sell sites on a multisite install?

### ISSUE THREAD

**Issue by beatelite** [easydigitaldownloads/easy-digital-downloads#5011]
We run a small agency that hosts all of our client's sites. Right now, we're using wpmudev's prosites. This basically allows us to run as SAAS service and limit access to themes, plugins, posting amounts, to levels we set up. 

Well, it's driving us nuts and we want to see our options. I searched to see if EDD could manage this but didn't see anything. Is there any extension or docs that could allow this to work? I'd love to also sell services so it would be great to use one option vs both. 

Let me know and thanks

**Comment by pippinsplugins** [comment]
EDD does not have an option for this but our sister project, Restrict Content Pro, does: https://restrictcontentpro.com/downloads/site-creation/

**Comment by beatelite** [comment]
Funny, I just stumbled upon them. Looking into them now. 

do you happen to know if they allow trials before requiring payment? That is one thing we are trying to avoid.

**Comment by pippinsplugins** [comment]
There are some basic free trial options. Submit a question through the support channel if you'd like more details: https://restrictcontentpro.com/support
