### ISSUE TITLE
Export Payment History Issues

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#5013]
I am using the latest version of EDD and when I use the "Export Payment History" function for a set date range the following issues are arising:

1. The date column has no dates for the transactions, just empty calls with the column header. This occurs regardless of date range set. The correct transaction range is being exported.

2. The status shows "publish" instead of "Completed".

3. My site processes transactions in GBP, within the admin panel no issues with the currency character exist. However on the export it displays like this throughout the report: Â£. As a side note, this issue doesn't occur with my other websites or Woo Commerce store.

Thanks,
David

**Comment by pippinsplugins** [comment]
@davidsherlock The date has been fixed already.

See https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4994

The status is logged but not yet fixed.

See https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5006
