### ISSUE TITLE
New user email strips login link on plain text email

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#5014]
When a new customer signs up for a user account at checkout, an email is sent like this:

<img width="647" alt="screenshot 2016-10-07 09 04 41" src="https://cloud.githubusercontent.com/assets/2359131/19197148/3190393c-8c6d-11e6-9d5d-24e57ca10a46.png">

If you go to EDD's email settings and switch the email template to **_No template, plain text only_**, you get the following for the same email:

<img width="687" alt="screenshot 2016-10-07 09 05 10" src="https://cloud.githubusercontent.com/assets/2359131/19197203/710f3d88-8c6d-11e6-8abf-5da9dc20c76c.png">

**Comment by pippinsplugins** [comment]
Oops

**Comment by pippinsplugins** [comment]
Ready for testing.

**Comment by SDavisMedia** [comment]
@pippinsplugins Fatal error:

```
Fatal error: Uncaught Error: Cannot access private property EDD_Emails::$html in /app/public/wp-content/plugins/easy-digital-downloads/includes/user-functions.php on line 528

Error: Cannot access private property EDD_Emails::$html in /app/public/wp-content/plugins/easy-digital-downloads/includes/user-functions.php on line 528
```

**Comment by pippinsplugins** [comment]
Doh! Fixing.

**Comment by pippinsplugins** [comment]
Try again now.

**Comment by SDavisMedia** [comment]
Working well for me now. :+1:
