### ISSUE TITLE
Store or root API endpoint

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/easy-digital-downloads#5016]
We've got some great endpoints right now for the EDD REST API. But there's still a few things third party apps may want to access but can't. In particular, data pertaining to the EDD store's global configuration could be useful in some cases. I encountered a customer request for a way to get the currency for a store which is currently not possible.

Some other APIs I've come across do have account endpoints or root endpoints. Like Mail Chimp which has a API root endpoint which returns some global account information and a list of available endpoints.

Should EDD have a root endpoint that returns some global settings like currency, store URLs, store location, etc.? Or maybe a `/store` endpoint through which any exposed store settings could be accessed?

**Comment by pippinsplugins** [comment]
We have an `info` endpoint now. See #4661 

Anything not shown there you'd like added?

**Comment by brashrebel** [comment]
Nope, not at this time! Looks like we just need to get that in our docs. I didn't know about it but I think it addresses the purpose of this issue. Closing.
