### ISSUE TITLE
Country and state chosen fields on view order details broken

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#5020]
When we converted the view order details to load chosen fields for the country and states, there is a small bug that prevents this from working correctly.

For one, we've already loaded all the options to the input field so there is no need to run an AJAX call. And there was no ID, which caused our Chosen triggers to fail.

This will be included with #4989 
1) Add an ID to the select field
2) Add support for a `no_ajax` `data-search-type` when it comes to our chosen fields, for people who load up the `select` with `chosen` that already has all the options passed into it during creation and doesn't require AJAX.

**Comment by SDavisMedia** [comment]
Replicated on `master` and confirmed fixed in `issue/4989`. :+1:

**Comment by pippinsplugins** [comment]
Works great.
