### ISSUE TITLE
Add framework for the new SL beta support

### ISSUE THREAD

**Issue by ghost1227** [easydigitaldownloads/easy-digital-downloads#5027]
With https://github.com/easydigitaldownloads/EDD-Software-Licensing/issues/662 we've added beta support to Software Licensing. EDD core needs to be updated to implement handlers for beta support in our own products (and any products using the default licensing class).

**Comment by ghost1227** [comment]
![screen shot 2016-10-11 at 1 30 00 pm](https://cloud.githubusercontent.com/assets/36433/19283277/d9f1e110-8fb6-11e6-8602-d0253e5048ec.PNG)

**Comment by ghost1227** [comment]
Utilizing the framework is a two-part process. First, plugins wishing to utilize betas need to add themselves to the `has_beta_support` array:

```
function add_me_to_betas( $products ) {
    $products['my-slug'] = 'My Product';

    return $products;
}
add_filter( 'edd_has_beta_support', 'add_me_to_betas' );
```

Once added, the item will be added to the beta list on the Tools page. Checked items will be saved under the option `enabled_betas`. To actually enable beta notification, you have to pass an extra argument to `EDD_License` as follows:

```
new EDD_License( __FILE__, 'My Product', 'Product Version', Author', 'API URL', edd_is_beta_support_enabled( 'my-slug' ) );
```

**Comment by ghost1227** [comment]
Forgot to tag this for testing.

**Comment by pippinsplugins** [comment]
>>>Utilizing the framework is a two-part process. First, plugins wishing to utilize betas need to add themselves to the has_beta_support array

We need this to be handled entirely by core.

I would vote that all plugins that utilize our `EDD_License` class automatically get an opt-in option showing, otherwise we have to push an update for every extension before we can release betas for extensions, which is kind of silly.

**Comment by ghost1227** [comment]
I'm not against that... tbh, it never occurred to me.

**Comment by pippinsplugins** [comment]
Let's go ahead and go with that route please.

**Comment by ghost1227** [comment]
@pippinsplugins how's that?

**Comment by SDavisMedia** [comment]
@ghost1227 What exactly am I testing here? Outline testing steps for this please.

**Comment by ghost1227** [comment]
There's really very little to test here. The real testing is in the related beta support issue for SL (which we already tested). This PR is pretty straightforward... any plugin that uses the core `EDD_License` class is automatically added to the `Beta` tab under `Tools`. If checked, it adds the beta flag to the upgrade checks. I suppose, if you want to test it, create a site that acts as the 'parent' (storefront) site, and one for the 'client', switch to `https://github.com/easydigitaldownloads/EDD-Software-Licensing/issues/662` on SL and this issue on core, and add a product with both stable and beta versions to the parent site. Ensure that stable updates pull if the beta option is disabled, and beta updates pull if it's enabled for a given product.

**Comment by ghost1227** [comment]
I should note that no extra code is required on the part of the plugin. This automatically detects anything using `EDD_License` and does all the hard work.

**Comment by ghost1227** [comment]
@SDavisMedia If you want to `var_dump` the API data, it'd go here: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/15183842457757776f1991955a7b2d471a62d84d/includes/EDD_SL_Plugin_Updater.php#L326 

```
var_dump( $api_params );
exit;
```

**Comment by SDavisMedia** [comment]
Alright everything checks out here. The *Beta Support* tab shows, the checkbox values save properly, and that's confirmed by the beta flag on the api call. :+1:

**Comment by pippinsplugins** [comment]
Good deal!

A couple of small changes needed. See review on PR.

**Comment by cklosowski** [comment]
@SDavisMedia @pippinsplugins I think I've got the 2 concerns from the PR fixed up, let me know if that is what you were thinking.

**Comment by pippinsplugins** [comment]
Look good to me!

**Comment by pippinsplugins** [comment]
I'm happy with this if everyone else is.

**Comment by sunnyratilal** [comment]
Yep all good here :+1:

**Comment by SDavisMedia** [comment]
All good here.

**Comment by cklosowski** [comment]
Looks good to me, going to merge this now, and get 2.6.11 on the EDD site and look to deploy this afternoon
