### ISSUE TITLE
WP CLI: Customers command does not support searching by user ID

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#5029]
The `customers` command does not currently support specifying a user ID lookup. We should add it so we can do this:

```
wp edd customers --user_id=23266
```

**Comment by sanketio** [comment]
Hi @pippinsplugins 

I have sent a PR for this enhancement. Let me know if there is any change in that.

**Comment by michaelbeil** [comment]
The PR works great @sanketio!

**Comment by sanketio** [comment]
@michaelbeil Great. :)
