### ISSUE TITLE
"Email already in use" error if capitalization does not match 

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#5030]
The `Email already in use` error is designed to show up when a purchase is attempted with an email address that belongs to a different user/customer.

I've found that it also gets shown when the email address on the user profile has different capitalization as the address on the customer record.

For example, if the user account has `SomePerson@site.com` but customer record has `someperson@site.com`, the `Email already in use` error will be shown even though the addresses are the same.

**Comment by ghost1227** [comment]
That's clever!

**Comment by pippinsplugins** [comment]
Ready for testing.

**Comment by chriscct7** [comment]
Has this been tested in other areas, like for example manual purchases when making a payment and using the email to ensure it attaches to an existing customer email? Also discount codes by email?

**Comment by pippinsplugins** [comment]
@chriscct7 This error message is only ever shown during checkout as part of `process-purchase.php`.

**Comment by cklosowski** [comment]
@pippinsplugins I think @chriscct7 point is are we sure that this bug isn't affecting other parts. Like adding an email address to a customer (does a lowercase and uppercase allow the same email to be added twice), and if doing a lookup if a customer has used a discount code, which searches by email.

**Comment by pippinsplugins** [comment]
I intentionally did not modify any other parts to ensure this change only affects checkout.

Does this bug exist elsewhere? Quite possibly, but I'd prefer that we address those separately when (and if) they present themselves.

**Comment by SDavisMedia** [comment]
Replicated the checkout error on `master` by modifying my own WP user profile (admin) to have different email capitalization than what's already in my customer record and trying to checkout. Confirmed fix on `issue/5030`. :+1:

**Comment by pippinsplugins** [comment]
Thanks @SDavisMedia!
