### ISSUE TITLE
Allow download admin icon to be more easily customized 

### ISSUE THREAD

**Issue by michaelbeil** [easydigitaldownloads/easy-digital-downloads#5033]
It would be nice to make the admin download icon swappable. 

 PR: https://github.com/easydigitaldownloads/easy-digital-downloads/pull/5032

**Comment by pippinsplugins** [comment]
I believe the CSS was only necessary for older versions of WP before dashicon support was added so this should be safe to do.

**Comment by SDavisMedia** [comment]
Might be time to update the Insert Download button's icon too. 
<img width="259" alt="screenshot 2016-10-26 10 25 37" src="https://cloud.githubusercontent.com/assets/2359131/19737022/a19f46b6-9b66-11e6-9a48-d3e66f019d89.png">

**Comment by pippinsplugins** [comment]
Yeah separate issue please.
