### ISSUE TITLE
Chosen dropdowns cause a horizontal scroll bug in RTL

### ISSUE THREAD

**Issue by Ismail-elkorchi** [easydigitaldownloads/easy-digital-downloads#5037]
When using an RTL language the view order details have an unwanted/huge horizontal scroll bar, and the reason is that, in Chosen, the 'chosen-drop' div is positioned using a negative 'left' which creates a horizontal scroll instead of 'hiding' the element.

To fix this issue, the dropdowns should have the 'chosen-rtl' class.

Will provide a PR.

**Comment by pippinsplugins** [comment]
Thanks for the report and the PR! We'll get it tested as soon as we can.

**Comment by SDavisMedia** [comment]
Easily replicated. The PR fixes it. :+1: [Based on research](https://harvesthq.github.io/chosen/#right-to-left-support), the PR is right on point. :+1:

**Comment by pippinsplugins** [comment]
Going to put this in 2.6.9.
