### ISSUE TITLE
Remove black icons and scrolling/ Please can you help me ❤

### ISSUE THREAD

**Issue by Lovestorm-people** [easydigitaldownloads/easy-digital-downloads#5048]
Hello, i want to delete the black icons (see attached file) and the scrolling cause it looks not nice. 

Please can you help me ❤

![easy](https://cloud.githubusercontent.com/assets/22880410/19427257/0ec64daa-9443-11e6-9296-dc857aa53541.jpg)

**Comment by chriscct7** [comment]
For any support-related questions, we ask that you send a ticket to https://easydigitaldownloads.com/support as we reserve this repository for development purposes.

**Comment by Lovestorm-people** [comment]
Thank you and sorry
