### ISSUE TITLE
edd_empty_cart not working on payment gateway

### ISSUE THREAD

**Issue by carazo** [easydigitaldownloads/easy-digital-downloads#5049]
Good morning,

And thanks for your plugin, it is great. I have prepared a payment gateway for it and some clients are working correctly with.

But in one case we have a problem. Although I try to empty the cart after the payment is done, it is not working.

Which is the code:
`edd_insert_payment_note( $payment_id, sprintf( 'RedSys transacción con ID: %s', $id_trans ) );
edd_empty_cart();					
edd_set_payment_transaction_id( $payment_id, $id_trans );
edd_update_payment_status( $payment_id, 'publish' );`

I have inserted some pieces of code there to see if it is really executing and yes, all the functions are being execute and no error or warning raises.

Which can be the problem?

Thanks in advance.

**Comment by pippinsplugins** [comment]
Is that being done during a postback request from the gateway? If so, that won't work as that would be a different session than the customer's session.

**Comment by carazo** [comment]
Yes, it can be the problem. 

How should I do it? How can I empty the cart of the client in the POST callback?

Thanks.

**Comment by pippinsplugins** [comment]
You can't. It has to be emptied from within the client session.

Note: github is not for support so for any future support inquiries, please open a ticket at https://easydigitaldownloads.com/support
