### ISSUE TITLE
Z-index of tool tips needs increased

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#5050]
If a tool tip sits close to the WP admin menu, it shows up underneath the menu.
![screen shot 2016-10-17 at 12 22 59 pm](https://cloud.githubusercontent.com/assets/1034109/19447741/892458b4-9464-11e6-8237-19f1834fb2b3.png)

**Comment by ghost1227** [comment]
This has bugged me for a while.
