### ISSUE TITLE
Better checks for if a given download ID exists.

### ISSUE THREAD

**Issue by michaelbeil** [easydigitaldownloads/easy-digital-downloads#5055]
There are times when a user wants to delete a download. There is a lot of data that can be connected to a download, but removing it does not remove the conglomeration of information that may be present elsewhere on the site (renewal notices, payment history, etc.).  

It would be good to add some type of notice that says, "Are you sure?" or something like that when a user attempts to delete a download.

**Comment by ghost1227** [comment]
To expand on this, rather than just saying "Are you sure?", given the consequences to actually deleting a download with attached sales, it might be prudent to say "Are you sure / would you like to disable this product instead?" and set it to draft if they choose to disable.

**Comment by SDavisMedia** [comment]
I personally don't think anything should happen. I don't see the need. Instead, I think everything else that depends on a past download still existing needs to do better checks (assuming a problem even exists anywhere). The example mentioned in Slack was a license renewal email going out for a   deleted download. I think that's the problem, and an enhancement here does not fix it. Just my 2 cents.

**Comment by pippinsplugins** [comment]
>>>Instead, I think everything else that depends on a past download still existing needs to do better checks.

I agree with this.

**Comment by cklosowski** [comment]
I could get behind that.

**Comment by pippinsplugins** [comment]
Going to close this as it's too generic. When we come across specific cases where deleted downloads cause problems, we can open those as distinct issues.

**Comment by SDavisMedia** [comment]
The example mentioned in Slack back when this issue was opened was a license renewal email going out for a deleted download. Not sure that's going to happen very often but that's the only case I know of where this might be important.

**Comment by pippinsplugins** [comment]
That's a good example. I'll open a new issue on SL for that.
