### ISSUE TITLE
South Korea Zip/Postal Code Validation Issue

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#5056]
A customer recently contacted me who was having issues proceeding with his order due to the address validation on the EDD checkout screen. He was from Germany but living in North Korea and while the VAT plugin I use asks for location confirmation (if the Geo IP lookup reports a different country to the billing address), it doesn't interfere with the core EDD checkout functionality.

He explained that the actual zip code system changed from 6 digits to 5 digits recently (this year I believe) and this was the potential reason for the validation issue. Apparently a "transition period" is taking place while the change over occurs and it's causing issues on some sites.

This prompts a few thoughts:
1. When an error like this occurs the transaction isn't created (in pending, draft or otherwise) and thus it's hard to figure out what's going on and help the customer, if other customers from different countries are experiencing similar problem they might not reach out like this customer did (who purchases from my other websites) and sales might be getting lost due to address validation. If a checkout error occurs (such as address validation on postal code, etc) it would be useful to have a "pending" transaction created with all the details entered for customer support and EDD bug reporting reasons.
2. Where are the address validation rules stored and can they be disabled? This "could" be a potential future setting within EDD.

Thanks,
David

**Comment by pippinsplugins** [comment]
@davidsherlock Your issue title says South but your description says North. Could you confirm which one it is?

**Comment by davidsherlock** [comment]
Apologies @pippinsplugins, i believe it to be South Korea.

**Comment by pippinsplugins** [comment]
Thanks.

**Comment by cklosowski** [comment]
Confirmed this change via FedEx. Details:
South Korea
Going from: 6 digits
Going to: 5 digits

http://www.fedex.com/bm/koreapostalcode/index.html

**Comment by cklosowski** [comment]
From the sound of things, major shipping companies have already ditched the 6 digits format and are only accepting the 5 digits.

UPS: August 1, 2015
FedEx: April 4, 2016

I think it's safe for us to convert to just 5 digits as well.

**Comment by cklosowski** [comment]
@davidsherlock I logged an issue about the possibility of using our payment error logs for validation issues.

Right now the only address validation we do is for the Postal Code, and that can be overridden via a filter:
`return apply_filters( 'edd_is_zip_valid', $ret, $zip, $country_code );`

**Comment by sunnyratilal** [comment]
Looks all good here.
