### ISSUE TITLE
Products endpoint returns empty response on v2 of the API

### ISSUE THREAD

**Issue by sunnyratilal** [easydigitaldownloads/easy-digital-downloads#5057]
When querying the `products` endpoint using `v2` of the API, an empty response is generated.

The title of this [doc](http://docs.easydigitaldownloads.com/article/1334-edd-rest-api-v2-products) implies that `products` should work with `v2` but the examples using the `v1` API

Examples:
Empty response: https://easydigitaldownloads.com/edd-api/v2/products
Correct response: https://easydigitaldownloads.com/edd-api/products

**Comment by michaelbeil** [comment]
I think this must've been oversight to not include products in v2.

**Comment by pippinsplugins** [comment]
Bugger. It broke in 2.6.7 and worked in previous versions.

**Comment by pippinsplugins** [comment]
Fairly certain is was the new filters that broke it https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4866

**Comment by pippinsplugins** [comment]
Fixed and ready for testing.

**Comment by SDavisMedia** [comment]
Undefined variable: `issu/5057` in branch/name. :)

Replicated on `master` using v2 and fixed for me on `issu/5057`. :+1:

**Comment by cklosowski** [comment]
Verified.

On Master calling `{{edd_url}}/edd-api/v2/products?key={{key}}&token={{token}}`:
`Unexpected '<'`

On Issue Branch:
Product results show.
