### ISSUE TITLE
EDD API returning version 1 by default

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#5059]
The API is supposed to be set to version 2 by default but `v1` is being set instead: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/install.php#L184

@pippinsplugins is aware of whatever's causing that.

**Comment by pippinsplugins** [comment]
@SDavisMedia give that a try?

**Comment by SDavisMedia** [comment]
@pippinsplugins Doesn't seem to do the trick for me. Here's my request:
`localhost/edd/edd-api/customers?key={the_key}&token={the_token}&customer=2`

That customer record has multiple email address but only primary is in the results. Manually adding `v2` to the URL shows them all.

**Comment by pippinsplugins** [comment]
Was that after a brand new install?

**Comment by SDavisMedia** [comment]
Nope.

**Comment by SDavisMedia** [comment]
Working by default on another site. :+1:

Does this mean everyone's been using version 1 by default?

**Comment by pippinsplugins** [comment]
We can only affect brand new installs as we have no way of knowing if someone has already used v1.

**Comment by pippinsplugins** [comment]
And yes, everyone has been using v1 by default :(

**Comment by michaelbeil** [comment]
I noticed this the other day unfortunately, which is why Sunny opened this, but glad we are working it out.

**Comment by SDavisMedia** [comment]
@cklosowski I assume the last round of testing is for you.

**Comment by cklosowski** [comment]
Working well for me. Existing site gave me `v1`, new install gave me `v2`
