### ISSUE TITLE
Add action hook called "edd_payment_saved"

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#5068]
There is currently an action hook called edd_payment_save but it isn't really useful for firing functionality when the payment is saved since it could fire more than once. 

Proposal:
Add a filter called "edd_payment_saved" which only fires once the payment has actually, fully saved.

Perhaps somewhere around here:
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/payments/class-edd-payment.php#L908

**Comment by SDavisMedia** [comment]
Based on @mintplugins' test below, all is well on my end. :+1:

```php
function my_custom_payment_note( $payment_id, $payment ){
    edd_insert_payment_note( $payment_id, 'edd_payment_saved is running.' );
}
add_action( 'edd_payment_saved', 'my_custom_payment_note', 10, 2 );
```

Add the above snippet anywhere and save a payment. The payment note should show up.
