### ISSUE TITLE
Bug: discount expire check

### ISSUE THREAD

**Issue by moorscode** [easydigitaldownloads/easy-digital-downloads#5071]
We've been having strange problems with discounts suddenly becoming inactive without the environment dictating that they should be.

While investigating I ran into a couple of problems (see also https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5070)

It seems that the date in our database cannot be matched without an explicit type cast.

This means that in order to have it work as intended, the meta query needs to have a specific `"type" => "DATETIME"`.

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/discount-functions.php#L1584

(edit: provide more context)

**Comment by moorscode** [comment]
It seems that this does not work as expected after some more testing. Sorry for that.

**Comment by pippinsplugins** [comment]
See https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4932
