### ISSUE TITLE
CSV import tool not importing Download Files

### ISSUE THREAD

**Issue by michaelbeil** [easydigitaldownloads/easy-digital-downloads#5077]
When mapping the Download Files to the Files CSV column, the Download Files (URLs) do not get imported to the download file meta box.

**Comment by michaelbeil** [comment]
Just had another ticket come in regarding this.

**Comment by pippinsplugins** [comment]
@michaelbeil could you link to the tickets here please?

**Comment by michaelbeil** [comment]
1: https://secure.helpscout.net/conversation/266646277/45061/?folderId=725711
2: https://secure.helpscout.net/conversation/267628201/45192/?folderId=725711

**Comment by pippinsplugins** [comment]
This was broken with https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4969

The logic that checks for a file condition is wrapped around the logic that sets up the file URL, so the array sent to `update_post_meta()` is empty.

**Comment by pippinsplugins** [comment]
@michaelbeil ready for testing!

**Comment by michaelbeil** [comment]
Tests pass here!

**Comment by cklosowski** [comment]
Something isn't right here...it's again starting the price ID index at `0` on import instead of `1`, so it's broken the file import with conditions, going to fix it up quick.

**Comment by cklosowski** [comment]
@michaelbeil is this still working for you with price conditions?

**Comment by michaelbeil** [comment]
What did you do to test?

**Comment by cklosowski** [comment]
My setup to export...then try and import making sure it still works:
Variations:
![screen shot 2016-10-27 at 11 44 56 am](https://cloud.githubusercontent.com/assets/1390124/19780660/d9621112-9c3a-11e6-92d4-9264229fb78d.png)

Files (focus on the conditions):
![screen shot 2016-10-27 at 11 44 50 am](https://cloud.githubusercontent.com/assets/1390124/19780674/e2fbb908-9c3a-11e6-914c-b93b108c3595.png)

**Comment by michaelbeil** [comment]
Getting an issue where the starting price ID index is at 0 on import instead of 1. ![screen shot 2016-10-27 at 6 58 48 pm](https://cloud.githubusercontent.com/assets/4752949/19781792/5b7d7c22-9c8b-11e6-8878-11d60a1f6511.png)

**Comment by cklosowski** [comment]
@michaelbeil verify your price IDs match too? Does the price IDs column of your export site and import site match?

**Comment by michaelbeil** [comment]
They are not matching. When I add via the UI, I get a price ID of 1 on the export site, but when I run the import through, the price ID starts at 0.

**Comment by cklosowski** [comment]
@pippinsplugins @michaelbeil I'll dig in and see why this isn't setting the proper price ID keys.

**Comment by cklosowski** [comment]
@michaelbeil Can you pull down the latest and try this again? I've made it so the file IDs reset as well.

**Comment by michaelbeil** [comment]
That fixes it @cklosowski!

**Comment by mintplugins** [comment]
@cklosowski Tested and confirmed as well: Broken before and fixed after 👍 

Doin' awesome work you's guys!
