### ISSUE TITLE
[l18n] > String doesn't get translated

### ISSUE THREAD

**Issue by fxbenard** [easydigitaldownloads/easy-digital-downloads#5078]
Please use sprintf in https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/admin/settings/register-settings.php#L286

![2016-10-24_17-56-30](https://cloud.githubusercontent.com/assets/802114/19653082/763e05b0-9a13-11e6-9e40-540908257db5.png)

**Comment by michaelbeil** [comment]
@fxbenard how does that look?

**Comment by fxbenard** [comment]
It looks good. Check it out ! Ready to merge

![2016-10-25_19-06-26](https://cloud.githubusercontent.com/assets/802114/19696154/4bf6757a-9ae6-11e6-897f-4aad02260356.png)

**Comment by fxbenard** [comment]
@michaelbeil Don't forget to push a grunt makepot with it ;)

**Comment by cklosowski** [comment]
@fxbenard I'l be sure to do that.
