### ISSUE TITLE
Improve edd_readfile_chunked function to support resume

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#5087]
Suggested: https://secure.helpscout.net/conversation/268267024/0/

We should see if we can support resuming with the chunked readfile. Will need to verify this works with SL

**Comment by sunnyratilal** [comment]
PR: #6173

**Comment by cklosowski** [comment]
Commented on the PR that it all works well. My only thing to point out is that if the download link expiration takes longer than the file download itself (chunked file downloads are usually used for things like 'streaming', and if left open too long without continuing the download may surpass the expiration time. In that case I think we should just inform users who use it for 'streaming' content to extend out their expiration time to something longer than 24 hours to be safe.
