### ISSUE TITLE
Array to string conversion

### ISSUE THREAD

**Issue by rahilwazir** [easydigitaldownloads/easy-digital-downloads#5092]
## Steps to reproduce

- Install Fresh WP
- Enable `WP_DEBUG`
- Install EDD (stable or master trunk)
- Navigate to Downloads > Settings > Taxes
- Warnings under **Tax Rates** data table
![screen shot 2016-10-26 at 20 54 14](https://cloud.githubusercontent.com/assets/1818941/19733752/684447d8-9bbe-11e6-8e12-962849a7497d.png)

## Tested with:
EDD: Stable (2.6.10) and latest master trunk
WP: 4.6.1

**Comment by SDavisMedia** [comment]
Replicated on EDD `master` and WP 4.6.1: https://cl.ly/073e1F2x1Z3X

The proposed fix does clear the notices.

**Comment by pippinsplugins** [comment]
PR looks good to me.

**Comment by SDavisMedia** [comment]
Thanks, @rahilwazir! 

@pippinsplugins Did you mean to reopen this issue?

**Comment by pippinsplugins** [comment]
Nope :)

**Comment by rahilwazir** [comment]
@SDavisMedia @pippinsplugins Thanks guys
