### ISSUE TITLE
Block self-pings in tracking check ins

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#5094]
We need to ensure that the tracking class cannot try and ping our own site. Fairly certain that has been the culprit in several server melt downs we've seen recently immediately following an EDD core update.

**Comment by cklosowski** [comment]
We shouldn't be sending a checkin to ourselves at all: https://cl.ly/0H2r0G2o442p/Screen%20Shot%202016-10-26%20at%204.28.42%20PM.png

**Comment by cklosowski** [comment]
Seems like with this disabled, we aren't pinging ourselves, even on upgrades...so that makes me think it's not the case.

**Comment by pippinsplugins** [comment]
@cklosowski let's put the logic in any way to be safe.

**Comment by cklosowski** [comment]
@pippinsplugins I added the logic to check if it's ourselves, but also added a filter so we could stop affwp, rcp, and pp from checking in.

**Comment by pippinsplugins** [comment]
I want those two to track so all good :+1:

**Comment by cklosowski** [comment]
Cool. Well we can leave it in there anyway, allows a quick way to disable it programattically if need be for any reason. Good to merge?

**Comment by pippinsplugins** [comment]
Good to merge.
