### ISSUE TITLE
API Key list table is unreadable on modile

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#5099]
<img width="830" alt="screenshot 2016-10-26 12 01 32" src="https://cloud.githubusercontent.com/assets/2359131/19740586/1572b6c4-9b74-11e6-9dd7-f8771174cca4.png">

**Comment by pippinsplugins** [comment]
I suspect we need to define a primary column.

**Comment by SDavisMedia** [comment]
@cklosowski Thanks beautiful. 👌
