### ISSUE TITLE
Tooltip style conflict with Gravity Forms

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#5115]
With Gravity Forms activated:

<img width="327" alt="screenshot 2016-10-27 15 03 16" src="https://cloud.githubusercontent.com/assets/2359131/19787234/8e5de74c-9c56-11e6-8b20-3c718a13d827.png">

Gravity Forms deactivated:

<img width="296" alt="screenshot 2016-10-27 15 03 26" src="https://cloud.githubusercontent.com/assets/2359131/19787241/965473d0-9c56-11e6-8936-870f01346c2a.png">

Just for reference, here's Gravity Forms tooltip design:

<img width="323" alt="screenshot 2016-10-27 15 04 56" src="https://cloud.githubusercontent.com/assets/2359131/19787275/c0b48232-9c56-11e6-8e4e-cba65cf4727d.png">

-----

Gonna see if I can set some default styles in EDD to address that.

**Comment by SDavisMedia** [comment]
Seems to only happen on product edit screens since Gravity Forms use the Add Form media button with tooltips in the modal. EDD settings tooltips are fine.

**Comment by SDavisMedia** [comment]
Not a fan of the important declarations but we don't have much to work with here. This change tightens up the styles for EDD specifically and doesn't affect any other system's tooltips using the same library.

Gravity Forms activated:

<img width="281" alt="screenshot 2016-10-27 15 26 36" src="https://cloud.githubusercontent.com/assets/2359131/19787950/8773725e-9c5a-11e6-8efe-0a930fdd218c.png">

**Comment by SDavisMedia** [comment]
Fixed the box-shadow too.

**Comment by pippinsplugins** [comment]
Looks good to me!

**Comment by cklosowski** [comment]
Yeah I'm fine with the `!important`. Just the nature of styling it the way we've done it.
