### ISSUE TITLE
edd_stats_{key} transients are still a problem

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#5118]
In #4742 we introduced a cron job to clear out `edd_stats` transients. It wasn't enough. Our own live EDD site quickly builds up over 4,000 transients in no time at all.

This is likely in part due to the custom reporting dashboard we have that refreshes reports every few minutes, but I'm not content with saying we shouldn't do that. Us doing that simply indicates a problem with the underlying caching method used for these stats.

I'm putting this in 2.6.11 last minute because it's a real problem that we need to fix as soon as possible. These transients are causing severe performance problems on our site and, quite possibly, many, many others.

**Comment by sunnyratilal** [comment]
We need to move this to store our data in a single transient

**Comment by sunnyratilal** [comment]
Unit tests need to be updated for the switchover to a single transient

**Comment by sunnyratilal** [comment]
Unit tests don't need fixing - code needs fixing!

**Comment by sunnyratilal** [comment]
@cklosowski @pippinsplugins Ready for testing.

**Comment by sunnyratilal** [comment]
For testing, only four rows should now exist in the database:
`_transient_timeout_edd_stats_earnings`
`_transient_edd_stats_earnings`
`_transient_timeout_edd_stats_sales`
`_transient_edd_stats_sales`

**Comment by pippinsplugins** [comment]
It's working fine for most reports but if you try and view a _large_ date range, like 2013-2016, it fatal errors:

```
Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 40960 bytes) in /Users/pippin/Sites/edd/wp-includes/functions.php on line 443
```

Apparently `maybe_serialize()` is failing on that big of data sets.

**Comment by pippinsplugins** [comment]
I think we need to come up with an alternate method.

**Comment by cklosowski** [comment]
@pippinsplugins could se switch to using `json_encode` for the args? I think that might speed it up and help with the memory usage since `serialize` does some PHP magic methods still

**Comment by pippinsplugins** [comment]
I don't think so. It's not serializing the args that's failing. It's
serializing the array passed to set_transient()

**Comment by cklosowski** [comment]
@pippinsplugins gotcha.

**Comment by pippinsplugins** [comment]
@cklosowski confirmed the same thing happens with `json_encode()`

**Comment by chriscct7** [comment]
> It's working fine for most reports but if you try and view a large date range, like 2013-2016, it fatal errors:

After 1 mb in the transient, it can no longer be cached by memcache, and thus what probably happened is your transient was dropped and thus PHP had to now subsequently calculate that whole thing from scratch.

**Comment by sunnyratilal** [comment]
Currently, this is the best solution I can think of (although it is going to require quite a bit of work):

1. Create new functions which query the database directly and run MySQL `GROUP` functions to group by day, month, year
2. Create a `md5` hash of the entire database query and use that as the array key in the `edd_stats_earnings` transient.
3. Store the data returned from the query as an object (`stdClass`)
4. Update the transient with the object

This seems like a big task for a _minor_ release and I think it needs to be punted to 2.7.

**Comment by pippinsplugins** [comment]
We have to come up with a solution that improves the current behavior, that much isn't optional at the moment because it's destroying the performance of our site and probably others.

**Comment by TimothyBJacobs** [comment]
What about a custom table, something like `edd_stats_cache`? That won't bloat the options table and would probably be even faster than transients for sites w/o an object cache. For sites that are object cached, use the WP Object Cache API directly under an `edd-stats` group or similar.

**Comment by sunnyratilal** [comment]
@TimothyBJacobs We don't want to move to a custom table just yet. Perhaps in the long term we may need to but our focus for now is just getting the number of transients down to 1.  We do appreciate the suggestion though!

**Comment by chriscct7** [comment]
Getting the number of transients down to 1 isn't the solution, because if you get a single large transient it won't be cachable

**Comment by sunnyratilal** [comment]
Yes but I'm adjusting our queries to minimise the dataset that is cached in the transient.

I've got a demo EDD store which has over 158,000 sales. It failed with the single transient solution I adopted before but it works now after I rewrote all of our queries and it works significantly faster too.

**Comment by sunnyratilal** [comment]
@pippinsplugins @cklosowski Ready for testing

**Comment by pippinsplugins** [comment]
@sunnyratilal something isn't quite right here.

Graph of `this year` on `master`:
![screen shot 2016-11-01 at 10 40 45 am](https://cloud.githubusercontent.com/assets/1034109/19895682/b43f271a-a01f-11e6-9b7e-22e194555b1f.png)
And on `issue/5118`:
![screen shot 2016-11-01 at 10 41 37 am](https://cloud.githubusercontent.com/assets/1034109/19895709/ca8e4d2a-a01f-11e6-8d46-08fae418f55e.png)

Earnings and sales show correctly but the graph is wrong. Especially notice how the sales / earnings points do not line up any more.

**Comment by pippinsplugins** [comment]
In `master`, each date on the graph has a value, even if that value is `0` to enforce the line to be drawn. This doesn't (but should) happen on `issue/5118`.

**Comment by sunnyratilal** [comment]
Ready for retesting

**Comment by pippinsplugins** [comment]
Graph looks correct now.

PHP notice though: https://cloudup.com/cAocSNM7YFW

**Comment by sunnyratilal** [comment]
@pippinsplugins notice should be gone now

**Comment by pippinsplugins** [comment]
Tested on staging site.

On `master`:

- `Last Year` report resulted in 731 transients being set. YIKES!
- Custom `Jan 1` to `March 31` resulted in 182 transients being set.

On `issue/5118`:

- `Last Year` report resulted in 368 transients being set. Request took 10.69 seconds for initial page load. 2.19 seconds for follow up loads of the same report.
- Custom `Jan 1` to `March 31` resulted in 93 transients being set. Request took 3.47 seconds.

On `master`, the `Last year` report showed `5,747` sales. On `issue/5118` it showed `5,738` sales. Earnings were identical.

On `master`, the custom date range showed `2,195` sales. On `issue/5118` the custom range showed `2,194` sales. Not sure with the `1` sale went . . . earnings reported were identical.

This is a significant improvement!

We need to find where those missing sale counts went though.

**Comment by sunnyratilal** [comment]
Missing sale should now show up

**Comment by pippinsplugins** [comment]
Will test tomorrow: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5118

**Comment by pippinsplugins** [comment]
@sunnyratilal sale counts are still wrong for me.

**Comment by sunnyratilal** [comment]
@pippinsplugins did you delete the cached transients?

**Comment by pippinsplugins** [comment]
@sunnyratilal Yes, refreshed transients without any difference.

Two PHP warnings when no sales or earnings are in the selected range: https://cloudup.com/cDOldD92cnP

**Comment by cklosowski** [comment]
Seeing the same php notices:
![screen shot 2016-11-02 at 1 17 29 pm](https://cloud.githubusercontent.com/assets/1390124/19945749/c131919e-a0fe-11e6-918e-d59ef28af4dc.png)

**Comment by cklosowski** [comment]
Initially these graphs worked, and then after a refresh they broke. You'll see the earnings
![screen shot 2016-11-02 at 1 18 25 pm](https://cloud.githubusercontent.com/assets/1390124/19945796/ead78594-a0fe-11e6-80bd-488b5034b0c6.png)
 are there, but the sales are not.:

**Comment by cklosowski** [comment]
Fixed the notice. found an oddity though. I ran the report for 'Last month' however It looks like it's including sales from the first day of this month.

If you look here, the earnings bar stops at Oct 31st, but the sales bar goes to November 1st.
![screen shot 2016-11-02 at 4 21 33 pm](https://cloud.githubusercontent.com/assets/1390124/19950998/7d102cc2-a118-11e6-96d6-e58dac8de686.png)

**Comment by sunnyratilal** [comment]
That's done here: `$consolidated_date = $month === end( $month_keys ) ? cal_days_in_month( CAL_GREGORIAN, $month, $year ) : 1;`

We can remove that line and just the day to default to 1 but it causes another report to look odd.  Can't remember which one but some reports have earnings spanning to the end of that month - I think `Last Year` does

**Comment by cklosowski** [comment]
Quarterly reports need first of month to last of month. We should be able to fix this again. It was fixed with the previous stats.

**Comment by cklosowski** [comment]
Since this doesn't happen for `earnings` just `sales` we should be able to fix that part up.

**Comment by cklosowski** [comment]
Ok interesting enough, the two sets of data are pulling different date ranges:
```
Sales Dates
10/25,10/26,10/01,10/02,10/03,10/04,10/05,10/06,10/07,10/08,10/09,10/10,10/11,10/12,10/13,10/14,10/15,10/16,10/17,10/18,10/19,10/20,10/21,10/22,10/23,10/24,10/27,10/28,10/29,10/30,10/31,11/01,
Earnings Dates
10/1,10/2,10/3,10/4,10/5,10/6,10/7,10/8,10/9,10/10,10/11,10/12,10/13,10/14,10/15,10/16,10/17,10/18,10/19,10/20,10/21,10/22,10/23,10/24,10/25,10/26,10/27,10/28,10/29,10/30,10/31,
```

**Comment by cklosowski** [comment]
In the sales data, it put the 25th and 26th at the beginning, they do'nt exist where they should exist, and it tacked on `11/1` to the end where as with the earnings dates, everything is in line.

**Comment by cklosowski** [comment]
Found the issue, it was in the `EDD_Payment_Stats` class, we were adding `+1 day` to the end date, when really we should be doing `midnight` on taht date.

**Comment by pippinsplugins** [comment]
I still get inconsistent sales between `master` and `issue/5118`.

**Comment by cklosowski** [comment]
ok inconsistant wasn't what I was aiming for, I was aiming for the date range thing. Will dig into the inconsistancies.

**Comment by cklosowski** [comment]
@pippinsplugins also, note `master` could be wrong with that report due to the date range thing being incorrect. So we might need a little manual verification of what one is correct vs incorrect.

**Comment by pippinsplugins** [comment]
@cklosowski this is on EDD staging if you want to take a direct look .

**Comment by cklosowski** [comment]
Already have been. Working through the data to see which is actually correct.

**Comment by michaelbeil** [comment]
It appears to work locally just fine for me after a hard refresh and deleting all transients.

**Comment by cklosowski** [comment]
On EDD staging there is a discepency. Oddnly enough, `master` is wrong, so is `issue/5118`, but `issue/5118` is closer than `master`.

I counted each month's sales individually.

`issue/5118` was +4 and `master` was +13. Something is calculating off there but I'm not 100% sure this isn't bad data.

Earnings data was the same between the two branches.

**Comment by sunnyratilal** [comment]
Could it be the SQL query? It could have something to do with the `WHERE` clause in the query. Do we add another other payment statuses on our site?

**Comment by chriscct7** [comment]
It could be one of the bugs with reporting I reported earlier, but another thing is @cklosowski when you were counting the monthly sales were you only including completed sales? Because the counter functions for sales in EDD both in the standalone versions the graphing pages uses (edd_get_sales_by_date) and the payment query API include completed and revoked payments in sales count.

**Comment by cklosowski** [comment]
@chriscct7 I was counting each month in the graph, not running data directly. It seems like if we're reporting the data in the graph, that's the data we should be using to output below the graph, so at least those are consistant.

**Comment by sunnyratilal** [comment]
After talking with @cklosowski, we both have come to conclusion that there is an issue with the data held on our staging site which is causing the incorrect stats.

I've created 10 completely separate EDD installs with `master` and `issue/5118` and both branches show the correct stats (with payments created with random dates).  They correspond to the stats displayed on Payment History too.

As staging was displaying the stats incorrectly on `master` as well, it does further suggest that some of the payments on staging aren't _correct_.  Also the fact that I nor @cklosowski can replicate incorrect stats being displayed on any other EDD install.

**Comment by pippinsplugins** [comment]
Ok in that case I'm good with this

**Comment by sunnyratilal** [comment]
#5119 merged

**Comment by pippinsplugins** [comment]
:+1:
