### ISSUE TITLE
[Discuss] Frontend public user profiles

### ISSUE THREAD

**Issue by rubengc** [easydigitaldownloads/easy-digital-downloads#5120]
Using EDD FES you have the ability to add a vendor page where you can display information about this user like contact information, download, social networks, etc

If you add more plugins like EDD Reviews, EDD Wishlist, etc creates the need to create a public profile for your users

Posibilities that offers this to display:
User public wishlists
User favorites downloads
User recent comments
User recent reviews
And if you like, enable comments to let users talk

Adding a field description to the user edit profile shortcode will allow the user to add a description about him

what do you think?

**Comment by pippinsplugins** [comment]
@rubengc This discussion will need to be done in the FES repo. I'll add you to it.
