### ISSUE TITLE
Incorrect output for [download_history] and [purchase_history] when most recent Order is Pending

### ISSUE THREAD

**Issue by jchristopher** [easydigitaldownloads/easy-digital-downloads#5124]
This is a bit strange and I'm not sure what the cause is but I can recall the steps I took, what appears to be a bug, and what fixed it.

I was deploying a new version of my theme and ran a test purchase first through PayPal.

I only got so far as the order screen on PayPal and then went 'back' because I realized in order to test it I would have had to pay myself from my own account. I don't recall if I hit the back button on my browser or used the link on PayPal's payment confirmation page.

Once I was back on my site in my cart I went to Stripe and filled everything out and submitted.

The checkout reloaded saying there was an error creating the payment in Stripe. The Order was (properly) marked as Pending.

Fast forward a few hours, I forgot about that test and was checking out the CSS on the Account page (EDD-powered) and realized that the `[download_history]` output was saying I didn't have any downloads.

Then I realized that the `[payment_history]` output said I didn't have any payments.

I definitely did have payments for the account as I had run 20 test checkouts prior, so I thought that was strange.

I did some debugging and saw something buggy... I popped into `edd_get_users_purchases()` and `print_r()`'d `$customer` from https://github.com/easydigitaldownloads/easy-digital-downloads/blob/2.6.10/includes/user-functions.php#L70

The resulting `EDD_Customer->purchase_count` did equal 20, which is expected

Here was the issue: `EDD_Customer->payment_ids = 12345` where `12345` was the Order ID of that Pending order. My existing past successful orders were not returned as expected.

I'm pretty sure that's what caused `[download_history]` and `[purchase_history]` to return nothing, but both should have returned the successful downloads/orders. It looks like the Pending order derailed everything. Unfortunately I can't recall what the Stripe ID was 😕

**Comment by jchristopher** [comment]
Whoops I forgot to follow up with what 'fixed' it: deleting the Pending order. Once it was deleted the output for `[download_history]` and `[payment_history]` was accurate again.

**Comment by pippinsplugins** [comment]
@jchristopher after deleting it, did `$customer->payment_ids` show the expected IDs?

**Comment by jchristopher** [comment]
@pippinsplugins I can't say for sure because after deleting it the Shortcode output was expected, so I assumed `$customer->payment_ids` was correct. I can dig in deeper and set it up again if need-be.

**Comment by cklosowski** [comment]
I've been unable to replicate this. If it's still happening, let me know and we can reopen and investigate.
