### ISSUE TITLE
State/Province in edit profile shortcode shows state/province code

### ISSUE THREAD

**Issue by rubengc** [easydigitaldownloads/easy-digital-downloads#5125]
How to reproduce:

1. Go to your edit profile page (EDD shortcode ones), choose Spain as country and write anything as state/province (here state/province is a text field)
2. Purchase something
3. In checkout your state/province will be empty (here is a select element), choose one from the select element
4. After a success purchase go to your edit profile page, now you will see the code of your state/province instead of his label

**Comment by sunnyratilal** [comment]
I'm unable to replicate this bug.

To address the points listed above:
1. State/Province displays a dropdown menu not a text field when choosing Spain
3. This was populated to what I had set earlier from the profile editor page
4. Edit profile page had the state selected which I had chosen and saved earlier

**Comment by sunnyratilal** [comment]
@SDavisMedia just tried to replicate and couldn't either.

**Comment by sunnyratilal** [comment]
Closing as `invalid`.
