### ISSUE TITLE
Styles on Recount/Reset tool lost

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#5128]
Not sure where/when this happened, but our nice styles on the recount tool have gone. The 'Admin notice' style exists, but the gray background is missing.

**Comment by SDavisMedia** [comment]
Looks like we added a new class and forgot to put it in a few places. I updated the Customer card tools as well. I believe that's everything.

Side note: we should really try to do better with class names as neither of the affect areas here are import/export tools. I know it's easy to copy and paste for a one-time enhancement but as we add more features, the inappropriate naming scheme becomes way more apparent and that much harder to fix if we ever decide to. :+1:
