### ISSUE TITLE
Correct branding of necessary assets

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#5130]
@chriscct7 found that we have an asset file that still contains our old logo, which has the WP logo within it:
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/assets/images/edd-logo.png

We need to update that one to contain:
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/assets/images/edd-logo.svg.

For backwards compatibility (other extensions could be using it) we'll need the file name and size to remain the same, just modify the information within it.

**Comment by SDavisMedia** [comment]
@cklosowski that'll do it

**Comment by sunnyratilal** [comment]
Merged
