### ISSUE TITLE
Stop unit tests from hitting the network

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#5132]
I noticed this the other day when I was tethered for internet. The Unit tests were running SUPER slow, and out of curiosity, I disconnected from my phone's internet and they sped right up. This tells me something is hitting the network when we run, and I'm sure we can significantly speed up theses tests by stopping that.

**Comment by sunnyratilal** [comment]
Merged. Tested it locally.
