### ISSUE TITLE
Allow EDD_Payment to be instantiated with a transaction ID

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#5135]
We should create a lookup payment by Transaction ID with `EDD_Payment`, which would allow gateways to easily find refund payments, etc by transaction in case the ID passed isn't something we need (like with Recurring renewal payments)

**Comment by pippinsplugins** [comment]
Brings this in line with `EDD_Customer`, `EDD_Subscription`, and `EDD_SL_license`. :+1:

**Comment by cklosowski** [comment]
Committed with unit tests.

**Comment by pippinsplugins** [comment]
PR looks great at first glance. Will test further though.

**Comment by pippinsplugins** [comment]
Works great.
