### ISSUE TITLE
_edd_download_limit isn't checked for existence before accessing it, leading to fatal error

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#5140]
In the save routine for the downloads metabox, _edd_download_limit isn't checked for existence before attempting to access it on line 119

**Comment by chriscct7** [comment]
https://github.com/easydigitaldownloads/easy-digital-downloads/pull/5141

**Comment by pippinsplugins** [comment]
@chriscct7 can you give me steps to replicate the fatal?

**Comment by chriscct7** [comment]
Removing the meta box from the page should do it

**Comment by chriscct7** [comment]
(and then trying to save the download)

**Comment by sunnyratilal** [comment]
Tested and working fine. Thanks @chriscct7

**Comment by sunnyratilal** [comment]
Merged into `master`
