### ISSUE TITLE
Add filter for new user notification email

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#5146]
Would be nice if this email could be filtered: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/eb82eaaf84f88b214025b763b05721254db5d73b/includes/user-functions.php#L494

**Comment by SDavisMedia** [comment]
New request: https://secure.helpscout.net/conversation/290372101/48989/?folderId=180499

**Comment by SDavisMedia** [comment]
New request: https://secure.helpscout.net/conversation/371861612/60098/

**Comment by cklosowski** [comment]
@SDavisMedia ready for testing and PR review (assigned)

**Comment by SDavisMedia** [comment]
@cklosowski all the filters are working fine for me 👌
