### ISSUE TITLE
Display message when customer is logged in on [edd_register] page

### ISSUE THREAD

**Issue by michaelbeil** [easydigitaldownloads/easy-digital-downloads#5147]
If a customer is already logged in and navigates to a page where the [edd_register] shortcode has been added, we show a blank page. It might be nice to show a message similar to something that follows:

`You are logged in with your customer account.`

Another option is to add a redirect to the my account page or downloads page when a logged in customer visits this page.

**Comment by spencerfinnell** [comment]
Related/duplicate #4922

**Comment by SDavisMedia** [comment]
Closing as duplicate.
