### ISSUE TITLE
[Hook Request] edd_profile_editor_before_name

### ISSUE THREAD

**Issue by rubengc** [easydigitaldownloads/easy-digital-downloads#5148]
Currently there is no form to add anything before name form in profile editor

I request this hook because I need to add an avatar field at top of this form

**Comment by michaelbeil** [comment]
That seems like a definite possibility to add that hook. Would you care to send us a PR @rubengc?

**Comment by SDavisMedia** [comment]
Agreed. Just _below_ this line, I'd say: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/templates/shortcode-profile-editor.php#L30

**Comment by rubengc** [comment]
Added, on merge, I will close it

**Comment by michaelbeil** [comment]
Added a PR: #5174

**Comment by SDavisMedia** [comment]
@michaelbeil We already have a PR and ongoing discussion from the person contributing. https://github.com/easydigitaldownloads/easy-digital-downloads/pull/5162

**Comment by michaelbeil** [comment]
Oh, I did not see that. Closing in favor of #5162.

**Comment by pippinsplugins** [comment]
PR on this looks fine. Moving to 2.6.12.
