### ISSUE TITLE
Actually use the new iPhone icon

### ISSUE THREAD

**Issue by michaelbeil** [easydigitaldownloads/easy-digital-downloads#5149]
We have the wrong image source in payments-history.php on line 63: assets/images/icons/iphone.png

Should be templates/images/icons/iphone.png.

**Comment by michaelbeil** [comment]
Before: ![screen shot 2016-11-04 at 6 23 44 pm](https://cloud.githubusercontent.com/assets/4752949/20015457/dc2af922-a2bb-11e6-92b0-30550c51ec98.png)
After: ![screen shot 2016-11-04 at 6 23 50 pm](https://cloud.githubusercontent.com/assets/4752949/20015459/e07c2078-a2bb-11e6-90a0-1a48fea7cb08.png)

**Comment by SDavisMedia** [comment]
@michaelbeil @cklosowski Can we get the `alt=""` attribute added while we're in there?

**Comment by SDavisMedia** [comment]
Also, why was the `assets/images/icons/` location wrong? It's our asset and that one should have been replaced with the new icon. Just curious if I missed some other detail.

**Comment by cklosowski** [comment]
@SDavisMedia what do you want on the Alt Tag? What we should do is move that .png file over to the assets dir. It doesn't belong in the template images.

**Comment by SDavisMedia** [comment]
Looks perfect to me! Thanks.
