### ISSUE TITLE
Report query broken on year-change reports

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#5152]
Running an earnings report of
Dec 31, 2014 - Dec 31, 2014 and Jan 1, 2015 - Jan 1, 2015 individually work
Running an earnings report of
Dec 31, 2014 - Jan 1, 2015 returns 0 sales and earnings

It appears the bug is limited to reports with the following format:
December {1-31}, {year}  - Jan {1-31}, {year + 1}

**Comment by sunnyratilal** [comment]
Sales are working correctly (based on the changes implemented in #5118). Just the earnings it seems.

**Comment by cklosowski** [comment]
Looks good, merged, @chriscct7 mind just checking over and making sure it's working as you need? Seemed fine to me.

**Comment by chriscct7** [comment]
Looks good
