### ISSUE TITLE
Payment count for date range on payments list table off when custom range used

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#5153]
Possibly related to #5152 and/or #5118, when the date range Jan 1, 2015 - Dec 31, 2015, manually adding up the totals given for each status on the admin payments list table does not match the total in the "All" div on that page. On EDD's site, it's off by 1 for 2015. Didn't check other years.

**Comment by sunnyratilal** [comment]
Closing as this can't be replicated on a local install.

@chriscct7 found it on the EDD site and as we already know - there's something incorrect with the payments and payment statuses on the EDD site causing issues with stats/payment counts.
