### ISSUE TITLE
Incorrect date ranges on Earnings Graph Report when using invalid date search

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#5155]
When running a custom range from Feb 29, 2015, - Feb 31, 2015, which is a date range that doesn't exist, the graph while correctly showing no data, weirdly has an axis starting at March 1.

**Comment by cklosowski** [comment]
I'm still getting the same results on `master` as I am on `issue/5155`

![screen shot 2016-11-14 at 5 05 09 pm](https://cloud.githubusercontent.com/assets/1390124/20287883/9457a752-aa8c-11e6-8519-814cd87382c8.png)

Cleared my transients even and nothing changed. Curious, why don't we simply use some JS to update the dropdown to only contain the number of days in the month?

**Comment by cklosowski** [comment]
This seems to be working much better. @chriscct7 you good with these?

**Comment by chriscct7** [comment]
+1

**Comment by sunnyratilal** [comment]
Sweet - I'll get it merged in.

**Comment by sunnyratilal** [comment]
Merged into `master`
