### ISSUE TITLE
Remove use of global $edd_options

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#5160]
It's not uncommon for a developer to look at the source code of a parent project when trying to get best practice methods for writing an extension. 

In EDD a long time ago, we used to use global $edd_options to access settings. However, for years now, we've recommended people use the helper function as it's safer (don't have to exist check on the array when accessing it) and better (can easily set default).

Over time, many uses of  $edd_options have been removed from EDD core, but some have not. We should remove the last remaining ones.

**Comment by pippinsplugins** [comment]
PR submitted that removes most of them.

I have not removed usage from tests.

**Comment by chriscct7** [comment]
Still a couple uses in:
includes/admin/tools.php
includes/admin/tracking.php

**Comment by sunnyratilal** [comment]
@chriscct7 I don't see these in the files you have mentioned - please can you add line numbers?

**Comment by chriscct7** [comment]
In tracking file line 64, 77, 182, 202, etc it's all over that file

**Comment by chriscct7** [comment]
In tools 381 and 409

**Comment by sunnyratilal** [comment]
Are you looking at the correct branch? They have already been fixed. 

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/2.7/includes/admin/tracking.php#L76
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/2.7/includes/admin/tools.php#L407

**Comment by chriscct7** [comment]
Oh, I thought these went out already. Theyre on the changelog for the .12
release so I was looking at master.

**Comment by sonicviz** [comment]
I'm working on a project using EDD, FES and the Amazon S3 plugin and discovered the S3 plugin used edd_options in the init function
