### ISSUE TITLE
edd_get_users_purchases docs needs to be updated

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#5163]
Cross referencing from https://github.com/easydigitaldownloads/edd-recurring/issues/562

The docs of the `$status` variable need to be updated to say it supports as an array. Maybe even the same casting logic from https://github.com/easydigitaldownloads/edd-recurring/pull/563 could be used, and make the default an array. Also, unit tests should be added that use that function as an array.

**Comment by sunnyratilal** [comment]
PR ready for testing

**Comment by sunnyratilal** [comment]
Merged into `master`
