### ISSUE TITLE
Cannot copy API keys from user profile

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#5167]
<img width="739" alt="screenshot 2016-11-07 10 05 46" src="https://cloud.githubusercontent.com/assets/2359131/20069507/c6b85784-a4d1-11e6-8c3e-7a483a9a2659.png">

Those fields are totally disabled. You can't copy the API keys.

**Comment by pippinsplugins** [comment]
Oops. They're supposed to be readonly, not disabled.

**Comment by SDavisMedia** [comment]
This method seems useless (note, this is the `EDD_API` class): https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/api/class-edd-api.php#L1869

Why's it there?

**Comment by sunnyratilal** [comment]
As @cklosowski mentioned in Slack, the function is there for backwards compatibility. We used to use that function but don't anymore.
