### ISSUE TITLE
Implement a better way of determining if the main settings section is empty for a tab

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#5171]
In EDD, if the main tab is not used, or is empty, we have since the introduction of setting sections used the following code to find the new default ("main") section to use for a tab:
```
	// Let's verify we have a 'main' section to show
	ob_start();
	do_settings_sections( 'edd_settings_' . $active_tab . '_main' );
	$has_main_settings = strlen( ob_get_contents() ) > 0;
	ob_end_clean();
	$override = false;
	if ( false === $has_main_settings ) {
		unset( $sections['main'] );
		if ( 'main' === $section ) {
			foreach ( $sections as $section_key => $section_title ) {
				if ( ! empty( $all_settings[ $active_tab ][ $section_key ] ) ) {
					$section  = $section_key;
					$override = true;
					break;
				}
			}
		}
	}
```
From: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/admin/settings/display-settings.php

What this code does is say if we're on the main tab, and we determine the section has no input fields, then we'll check the other sections to find the first one that isn't empty to use as the main section.

The problem with this code is two fold. 

First, if you have a tab with a section called "main" or on a tab without a section called "main" whose first non-empty section becomes the main section, this means that the tab contents have already run one time before being output. This is highly problematic in the case that actions, filters, or outputted scripts/css are tied to the settings only being run once.

For example, in EDD we offer a rich_editor, which uses wp_editor's tiny_mce abilities. In commissions and in FES, it's been noted that the media buttons don't have the correct CSS. This is because the wp_editor function which creates an instantiated WP_Editor class, outputs the scripts for the buttons containing the CSS "missing" by using a static variable (` self::$editor_buttons_css `) that gets set to ensure the scripts are only output once [here](https://github.com/WordPress/WordPress/blob/493f76a3d2ef8c030ab5dcd4333f9a401208f534/wp-includes/class-wp-editor.php#L197). However, because EDD pre-runs the settings and discards them, if a rich_editor field is used, WP will instantiate the field, creating the wp_editor object, and outputting the CSS file, however because EDD then discards it, subsequently when the section is rendered the second time to show it, the static variable is still set to not show because it doesn't know EDD has discarded it's first output of the CSS file. There are other features that are blocked the same way.

Second, it's not unreasonable to assume that people will want to hook in things like actions, filters or even JS/CSS to only display once, but EDD prevents them from doing so.

Attaching a PR with a proposed change that detects an empty section without needing to pre-render the settings. As no output is required and then discarded, there is also a performance increase to rendering the page. Because the main tab was pre-loaded regardless of the section in a tab you were actively on, this performance benefit extends to the rendering time of any section whose tab has a defined main section and is particularly noticeable if the main section has several or more "heavy" fields such as rich_editor.

**Comment by chriscct7** [comment]
PR: https://github.com/easydigitaldownloads/easy-digital-downloads/pull/5172

**Comment by chriscct7** [comment]
Just noticed #4211 which is an issue where plugins not using sections won't have their settings registered in main, they just output there currently. I think I've got a better solution for that.

We know $all_settings[ $tab ] contains the array of all settings in EDD for a particular tab. 
If registered as a section, the settings for a section will be in 
`$all_settings[ $tab ][ $section ]`

In a post-section world, items for the main section would be in
`$all_settings[ $tab ][ 'main' ]` 
In a pre-section world, items for the main would be in
`$all_settings[ $tab ]` 

So all you have to do is loop through `$all_settings[ $tab ]` until you find an array key that's not in `edd_get_settings_tab_sections( $active_tab );`

Updated PR with this. Tested by using a combination of active/inactive current SL and old Amazon s3.

**Comment by pippinsplugins** [comment]
Good work tracking this down!

I haven't tested this yet but the logic seems sound. We will want to be very, very careful with this, however, as we have broken it several times already. It's a little fragile :)

**Comment by cklosowski** [comment]
This leaves me with a blank 'main' section again when all the active extensions are registered with subsettings.

![screen shot 2016-11-11 at 3 58 59 pm](https://cloud.githubusercontent.com/assets/1390124/20232775/dc4adbc2-a827-11e6-8269-d00ae179b513.png)

**Comment by cklosowski** [comment]
Found the issue and pushed it up. Please repull if you've already checked this out and test again.

**Comment by chriscct7** [comment]
+1

**Comment by cklosowski** [comment]
@easydigitaldownloads/core-devs This needs some HEAVY testing please, with all sorts of combinations of extensions installed. Ones that add their sections to the `Extensions` tab, as well as gateways and emails. FES might be another good one to test out.

**Comment by pippinsplugins** [comment]
This appears to work perfectly for me. I've tested as many combinations as I can think of, including 1st and 3rd party extensions.

**Comment by ghost1227** [comment]
This is working in my tests, but I've been testing newer extensions... Does this work cleanly with something that uses the pre-section settings configuration?

**Comment by chriscct7** [comment]
I'd recommend testing outdated versions of Discounts Pro & Amazon S3 as they implement the old settings methods

**Comment by pippinsplugins** [comment]
Good idea @chriscct7

**Comment by cklosowski** [comment]
These aren't 'older' extensions, but an extension built a while back but never finished and one that doesn't use the subsections at all:

![screen shot 2016-11-14 at 4 38 42 pm](https://cloud.githubusercontent.com/assets/1390124/20287296/dfa791bc-aa88-11e6-838d-a305697371c1.png)

**Comment by pippinsplugins** [comment]
That appears to work correctly.

**Comment by cklosowski** [comment]
Also confirmed that things like gateways that don't use subsections include their settings still on the main gateways tab. Going to merge this in and close.
