### ISSUE TITLE
The  EDD_SL_Plugin_Updater->check_update function is called twice

### ISSUE THREAD

**Issue by Tymvie** [easydigitaldownloads/easy-digital-downloads#5173]
The  `EDD_SL_Plugin_Updater->check_update` function is called twice. Because of that, 2 identical POST requests are sent.

This happens because the `update_plugins` transient is set twice inside the `wp_update_plugins` function, whereas the `EDD_SL_Plugin_Updater->check_update` function  is hooked like this:
```
add_filter( 'pre_set_site_transient_update_plugins', array( $this, 'check_update' ) );
```

**Comment by michaelbeil** [comment]
Hi @Tymvie,

Thanks for the heads up. I believe this is done on purpose as we add the filter hook on `init`. We remove our filter on the site transient in `show_update_notification()` for multisite purposes, and then we restore the filter for `check_update` here: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/64d11791d42897a8b0b3da62ecf071baf91feec6/includes/EDD_SL_Plugin_Updater.php#L181

**Comment by cklosowski** [comment]
I've verified that this only runs twice when in Multisite. Every single site that I run this on, only gets called once. It's required that we run this twice on multisite only due to the hooks and filters that are in place. We've looked into this multiple times, but there simply isn't a good way around it as the first is for the specific site (blog ID 1) AND for the network admin interface that we have to check.

This is currently working as intended. I think we can improve it though, but this is going to need some MAJOR testing and should be pushed upstream into EDD SL as well once we know it's working as expected.

**Comment by cklosowski** [comment]
@easydigitaldownloads/core-devs this is going to need a bunch of testing. Would love to have a few people make sure this doesn't break anything on single and multisite.

**Comment by cklosowski** [comment]
actually a slight change.

We have to use the license key in the cache key. The reason @Tymvie that there are two calls is this.

On a network site, your actually running on the main site when you are in admin. but subsites would have their own license key, not the same as the main site. We cannot use the same request for a multisite network as we do for a subsite.

What i've done with this 2nd commit is that the license key used for the POST request is part of the cache key, meaning that if the same license key makes a 2nd request, it'll use the cached response, but if two sites on a network make the same request in a page laod it's going to fire 2 calls, no way around that as they need to get their respective package URLs.

**Comment by Tymvie** [comment]
@cklosowski I did not talk about Multisite. 2 requests was sent when the version, received during POST request was not bigger than the current version. In this case, these lines was skipped:
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/EDD_SL_Plugin_Updater.php#L104
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/EDD_SL_Plugin_Updater.php#L95

Your first commit solves the problem. Thank you

**Comment by pippinsplugins** [comment]
@cklosowski this looks good at first glance.

Note: we'll need to take these changes over to SL too.

**Comment by Tymvie** [comment]
@cklosowski is it possible to add a hook for the transient time?

**Comment by pippinsplugins** [comment]
@Tymvie That is already filterable. See https://developer.wordpress.org/reference/functions/set_transient/

**Comment by cklosowski** [comment]
To test this, have quite a few EDD extensions installed and activated.

1) Install something like Query Monitor
2) Go to the Updates page in WP Admin
3) Make sure that `EDD_SL_Plugin_Updater` makes one call for each of your EDD extensions.
4) Verify that a transient exists for the plugin data (name is hashed, will have to look at data).

Further testing for Multisite
5) Activate with 2 different license keys on the main site and a sub-site. There should be 2 transients for the same extension, one for the sub-site and one for the main site.

**Comment by pippinsplugins** [comment]
@cklosowski I'm seeing two transients being set for most extensions. Oddly it does only set one for some of them while setting two (with different IDs) for other.

Also seeing something weird with Manual Purchases. That plugin is setting a transient on _every_ page load of plugins.php:
![screen shot 2016-11-16 at 12 16 17 pm](https://cloud.githubusercontent.com/assets/1034109/20359786/f113958a-abf6-11e6-87da-eb227c25161e.png)

Same thing happens with it on `master`, actually. Do you see that?

**Comment by cklosowski** [comment]
@pippinsplugins is this on multisite? and Are there different keys set for subsites?

**Comment by pippinsplugins** [comment]
Yes it is multisite. 

Why two transients for sub vs main site?

**Comment by cklosowski** [comment]
If Main site and subsite have two different License keys (b/c license keys are on full url, not host), they have to be separate transients. Otherwise, main site could be 1 license key with unlimited activations, subsite could be single site, but if we key on one or the other, isntead of both, you'd be polluting the updates for the subsites. Meaning, that a subsite might be looking at data requested with the licnese key from the main site, or the main site could be looking at data requested by the subsite, in which case the package URLs would be different for the version information.

**Comment by cklosowski** [comment]
So the cache key contains the license key, if the subsite and main site have the same license key, we should only get 1 cache transient.

**Comment by pippinsplugins** [comment]
Ok makes sense.

**Comment by SDavisMedia** [comment]
Though a bit tricky to tell, this is looking good for me on single site as well as multisite.

On single site (non-multisite) EDD `master`, there was still only one request but no transient. I switched to `issue/5173` and now there's one request but there’s also a transient. So all good there. :+1:

Multisite was a little less clear, though. My setup is a fresh multisite install with EDD and Software Licensing activated (and a couple of utility plugins). The network has two subsites: blog 1 is the main site and blog 2 is a subsite that I created. Software Licensing is network activated. I then activate 2 different SL license keys on the two subsites.

From the **Updates** admin page of the entire network, I can see only one request and one transient. That transient corresponds to the license key activated on blog 1. For blog 2, I was able to view a different request and transient from the **Plugins** admin page specifically for that subsite. Again, that transient matches the license key for SL on that subsite.

So even though I haven't been able to see all of it in one place, that's two separate requests and two transients for the two activated licenses. :+1:

**Comment by cklosowski** [comment]
Thanks @SDavisMedia i'm going to merge this through and get it on the EDD site for some verificaiton.

**Comment by Tymvie** [comment]
@cklosowski please replace this line
 https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/EDD_SL_Plugin_Updater.php#L261
with:
`$cache_key = 'edd_api_request_' . md5( serialize( $this->slug . $this->api_data['license'] ) );`
since the `$this->api_data` is array

**Comment by chriscct7** [comment]
:+1: on that change

**Comment by pippinsplugins** [comment]
Fixed.

**Comment by shivapoudel** [comment]
@pippinsplugins Does EDD SL Plugin Updater supports WP 5.5 auto-updates?
