### ISSUE TITLE
Per item tax editation

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#5176]
Currently when viewing an order within the admin panel only the total tax for the order is visible.

Since some items may have different tax classes assigned (or exclude tax) on a per item basis, it's difficult to know without exporting a full report to which items in the order had which rates/amounts applied at the time of sale.

Having the ability to view and optionally edit tax on a per line basis would be extremely useful for fixing issues with the order.

Additionally the "Ignore Tax" metabox wording is a little confusing as "Exclusive" in the context of sales taxes typically means an 'addition' at the checkout (item price + tax). Better wording would be "Mark this product as exempt of tax".

**Comment by pippinsplugins** [comment]
Thanks for the feedback! This is definitely an area I'd love to see improved.

**Comment by pippinsplugins** [comment]
This has been completed through #3802. Closing as a duplicate.
