### ISSUE TITLE
Reword the Ignore Tax option

### ISSUE THREAD

**Issue by michaelbeil** [easydigitaldownloads/easy-digital-downloads#5180]
Per a comment in #5176 (which should remain open): 

> Additionally the "Ignore Tax" metabox wording is a little confusing as "Exclusive" in the context of sales taxes typically means an 'addition' at the checkout (item price + tax). Better wording would be "Mark this product as exempt of tax".

**Comment by sunnyratilal** [comment]
Merged

**Comment by pippinsplugins** [comment]
@sunnyratilal reverted the PR. It was put into `master` but this is for `2.7` so needs to go into `release/2.7`.

**Comment by sunnyratilal** [comment]
This was moved into `release/2.7` in 946dd0ef5569eddd2e6ef92fcd3a7b41f266aef8
