### ISSUE TITLE
Undefined notice when new plugins installed with SL Updater

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#5182]
`( ! ) Notice: Undefined index: beta in /app/public/wp-content/plugins/easy-digital-downloads/includes/EDD_SL_Plugin_Updater.php on line 324`

**Comment by cklosowski** [comment]
To replicate this, just have EDD active and run plugin updates or install a new plugin. That's how I was able to replicate it.

**Comment by pippinsplugins** [comment]
Oops.
