### ISSUE TITLE
edd_get_users_purchased_products() fails if first product ID doesn't exist

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#5184]
The `edd_get_users_purchased_products()` will fail to return the purchased products for a customer if the first product ID in the list is not a valid product, as would happen if the product was deleted.

```php
$post_type 	 = get_post_type( $product_ids[0] );
```

To fix this we can simply pass `download` directly to the get post args. These args are filterable so if anyone needs to adjust the post types that are returned with this function, they can do that via the `edd_get_users_purchased_products_args` filter.

**Comment by SDavisMedia** [comment]
All good here. Thanks! :+1:
