### ISSUE TITLE
Update the current time to get GMT

### ISSUE THREAD

**Issue by michaelbeil** [easydigitaldownloads/easy-digital-downloads#5196]
> If you live in a UTC+0 timezone this doesn't affect you, but if you live in a UTC+2 i.e. timezone, without getting GMT time, the first time the cron will start, is after two hours.

Tracking PR https://github.com/easydigitaldownloads/easy-digital-downloads/pull/5074.

**Comment by sunnyratilal** [comment]
Tested and confirmed that it's working.

`wp_schedule_event()` does actually require `time()` or `current_time( 'timestamp', true )` so the fix makes sense.

**Comment by sunnyratilal** [comment]
Merged into `master`
