### ISSUE TITLE
Partial Refund Status

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#5201]
In instances where a customer makes a large order but wants a single item refunded, the only applicable status to apply is "Refunded". When integrated with FES, the vendors are able to see the orders and will see a "Refunded" status on that specific order even though the customer still has paid for certain items in the order and has been awarded a commission.

It would be useful to have a status for "Partial Refund" for instances where only a single item is partially refunded in an order.

**Comment by sunnyratilal** [comment]
This will be in conjunction with #5112

**Comment by nitun** [comment]
Yeah! `Partial refund` status would be great. 👍
