### ISSUE TITLE
TypeError: a(…).ajaxForm is not a function

### ISSUE THREAD

**Issue by remcotolsma** [easydigitaldownloads/easy-digital-downloads#5204]
> Upgraded to latest WP core (WordPress 4.6.1) and now when editing pages, this JS error is thrown, preventing other popups and actions on the page:
> 
> “TypeError: a(…).ajaxForm is not a function”
> /wp-content/plugins/easy-digital-downloads/assests/js/admin-scripts.min.js:1:24505
> 
> I am running latest EDD 2.6.8 with Stripe Payment Gateway add-on 2.5.4.
> 
> Disabling EDD allows the correct execution of editing pages. Please advise.

**Source:** https://wordpress.org/support/topic/wordpress-4-6-1-js-error/

It look likes [`admin-scripts.js`](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/2.6.11/assets/js/admin-scripts.js#L1561-L1567) requires [`jquery-form`](https://github.com/WordPress/WordPress/blob/4.6.1/wp-includes/js/jquery/jquery.form.js)  for the jQuery [`ajaxForm`](https://github.com/WordPress/WordPress/blob/4.6.1/wp-includes/js/jquery/jquery.form.js#L789) function.

* https://github.com/easydigitaldownloads/easy-digital-downloads/blob/2.6.11/includes/scripts.php#L183-L195
* https://github.com/WordPress/WordPress/blob/4.6.1/wp-includes/js/jquery/jquery.form.js
* https://developer.wordpress.org/reference/functions/wp_enqueue_script/
* https://github.com/WordPress/WordPress/blob/4.6.1/wp-includes/script-loader.php#L236-L237

**Pull request:** https://github.com/easydigitaldownloads/easy-digital-downloads/pull/5205

**Comment by sunnyratilal** [comment]
Good catch, thanks!
