### ISSUE TITLE
PHP Warning:  Illegal string offset 'email'

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#5206]
This is showing up in error logs:

PHP Warning:  Illegal string offset 'email' in /dom8333/wp-content/plugins/easy-digital-downloads/includes/payments/class-edd-payment.php on line 1609

**Comment by cklosowski** [comment]
It seems odd that this is failing:
`$current_meta['user_info']['email']  = $meta_value;`

Need to see if I can reproduce this in some way.

**Comment by pippinsplugins** [comment]
I saw this on the live EDD site, if that helps.

**Comment by sunnyratilal** [comment]
Looks like for some reason a `string` is being returned from the `get_meta()` call for it to report an `Illegal string offset`. Best way around it would just be to wrap [this](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/payments/class-edd-payment.php#L1608) in an `is_array()` check.

**Comment by sunnyratilal** [comment]
Any further thoughts @easydigitaldownloads/core-devs?

**Comment by pippinsplugins** [comment]
I think adding type checks will be fine.
