### ISSUE TITLE
Toggling variable pricing checkbox hides all price inputs

### ISSUE THREAD

**Issue by tnorthcutt** [easydigitaldownloads/easy-digital-downloads#5214]
Current behavior:

![toggl](https://cloud.githubusercontent.com/assets/796639/20325360/eff531b6-ab49-11e6-8a01-05d7b5007a15.gif)

Checking and then unchecking the variable pricing option hides all pricing inputs completely. PR incoming.

**Comment by cklosowski** [comment]
Actually there's a 2nd bug here in that the single price field sticks around when you enable variable pricing. I'll get that merged in with your PR @tnorthcutt thanks!

**Comment by SDavisMedia** [comment]
Replicated both problems on `master` and confirmed both are fixed for me on `issue/5214`. :+1:

**Comment by mintplugins** [comment]
Was not able to replicate this on master but it's still working on issue/5214 so I guess that's a thumbs-up from me too.

**Comment by cklosowski** [comment]
Thanks guys, merging.
