### ISSUE TITLE
Earnings missing from report graphs

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#5219]
When viewing reports, the graphs don't include any sales.

I suspect this was introduced in one of these:

https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5153
https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5154
https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5155
https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5156

**Comment by sunnyratilal** [comment]
@pippinsplugins Could you pull the PR submitted for #5220 and that should fix this issue too.  I think you mean that earnings aren't being displayed?  The sales are displaying fine for me and were displaying on the graph posted in Slack too

**Comment by SDavisMedia** [comment]
Assuming Pippin meant Earnings and not Sales, I replicated this when testing #5220. `issue/5220` fixed both. :+1:

If you truly mean Sales, I cannot replicate at the moment.

**Comment by sunnyratilal** [comment]
Fixed in #5221
