### ISSUE TITLE
"Total earnings for period shown" always 0.00

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#5220]
When viewing reports, the "Total earnings for period shown" is always 0.00

I suspect this was introduced in one of these:

https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5153
https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5154
https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5155
https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5156

**Comment by SDavisMedia** [comment]
Replicated on `master` and confirmed fixed on `issue/5220`.

**Comment by sunnyratilal** [comment]
Thanks @SDavisMedia

**Comment by sunnyratilal** [comment]
Merged into `master`
