### ISSUE TITLE
Add ability to filter Payment History by gateway

### ISSUE THREAD

**Issue by michaelbeil** [easydigitaldownloads/easy-digital-downloads#5223]
It might be nice to add a column to the payment history page to view the different gateways used to purchase.

Perhaps we could add a screen option to toggle what columns are enabled to make the this more feasible due to screen space.   

@easydigitaldownloads/core-devs thoughts?

**Comment by chriscct7** [comment]
I'm not too sure how useful that would be. Why would you want to be able to
quickly see that information all of the time?

**Comment by SDavisMedia** [comment]
I personally don't see the need for it.

**Comment by chriscct7** [comment]
Yeah I agree with Sean, if there's a usecase for it it'd be trivial to do, but I'm not sure why the avg user would gain from being able to do that. The one thing I could see is a filter above the list table to filter by gateways, which might be useful if you have a bug in the gateways, but frankly I think that would be clutter itself. Perhaps that could be implemented as a url-only filter (no UI)

**Comment by sunnyratilal** [comment]
I agree with @SDavisMedia and @chriscct7 - not seeing the gain here personally. If a user _really_ wants it, it can be added in simply via filters.

**Comment by pippinsplugins** [comment]
I personally had numerous cases where I wanted a way to view just the payments that came through a specific gateway, so I think it's it a great feature.

I do not think, however, that it needs to be a column in payment history. I would, instead, like to see it available as a drop down filter above the table.

**Comment by cklosowski** [comment]
I think available dropdown is the way to go, like filtering a category on the Post List Table. I'll update the issue to reflect this.

**Comment by pippinsplugins** [comment]
Note, when this is done, it should be done in a way that also facilitates additional filters being added by add-ons, like this https://github.com/easydigitaldownloads/EDD-Software-Licensing/issues/984

**Comment by ghost1227** [comment]
@pippinsplugins Ok, I'm not 100% sure I'm thinking the same way you are. I've got a partial implementation of a function that uses `restrict_manage_posts` to add a dropdown for filtering by payment type. Seems to be basically what you're looking for, but i'm not sure what you mean by 'facilitates additional filters' in this context. Wouldn't addons just use the same `restrict_manage_posts` filter I'm using?

**Comment by ghost1227** [comment]
Just realized we're already doing that. I should be modifying the existing `edd_add_download_filters` function rather than adding a new one.

**Comment by pippinsplugins** [comment]
I'd like to see it added in the same way that the date filters are added.

**Comment by ghost1227** [comment]
Oops, not `edd_add_download_filters`, wrong post type

**Comment by ghost1227** [comment]
The date filter is a search, not a filter. I assumed you wanted something akin to the category and tag filters in the download post type. Are you saying you want the filter to be added to the existing payment search form?

**Comment by pippinsplugins** [comment]
@ghost1227 I'd like a dropdown but I want it placed inline with the date filters.

**Comment by ghost1227** [comment]
<img width="1084" alt="screen shot 2017-02-23 at 3 58 10 pm" src="https://cloud.githubusercontent.com/assets/36433/23280953/ea8abba2-f9e0-11e6-9090-96d1afc2062f.png">

@pippinsplugins Something like this then? That filter bar is getting super crowded.

**Comment by ghost1227** [comment]
I should note, if I'm on the right track, it looks like you want a new action added in the `edd-payment-filters` div just before the `Apply` button. Sound right?

**Comment by pippinsplugins** [comment]
Yep, looks right to me.

**Comment by cklosowski** [comment]
Can we put an action in here?

I wanted to drop one of these in for SL 'renwals and upgardes' but there wasn't a way to add it BEFORE the Apply button.

**Comment by ghost1227** [comment]
@cklosowski yea, that's what I was thinking

**Comment by ghost1227** [comment]
First pass at actually adding the field and associated action. No search logic yet, I'm still trying to sort out the right way to adjust the payment query using the `EDD_Payment_Query` class to filter by gateway. @cklosowski Let me know if that action is where you want it.

**Comment by pippinsplugins** [comment]
@ghost1227 EDD_Payment_Query supports the standard `meta_query` of `WP_Query` :)

**Comment by ghost1227** [comment]
I figured as much, just had to track down the meta key used for gateway :P

**Comment by ghost1227** [comment]
@pippinsplugins filter now works, but I'm having trouble getting it to update counts

**Comment by pippinsplugins** [comment]
You will also have to pass it to the edd_count_payments() function

**Comment by ghost1227** [comment]
@pippinsplugins I knew that. Was having issues with the `$wpdb` code. Never was great at direct queries. Got it though!

**Comment by pippinsplugins** [comment]
@ghost1227 could we fix the slight misalignment?
<img width="510" alt="screen shot 2017-02-24 at 9 48 31 am" src="https://cloud.githubusercontent.com/assets/1034109/23309985/70f7a94e-fa76-11e6-9595-a227b01de6cc.png">

**Comment by pippinsplugins** [comment]
Besides that, this appears to work great!

**Comment by ghost1227** [comment]
@pippinsplugins How would you like that done? It's technically not a misalignment in the usual sense... dropdowns take more space natively than other fields, so the new dropdown is forcing the filter bar to grow to fit its contents.

**Comment by pippinsplugins** [comment]
Perhaps a negative top margin?

@SDavisMedia would have better methods.

**Comment by SDavisMedia** [comment]
Taking a look now. Standby.

**Comment by SDavisMedia** [comment]
@ghost1227 as you mentioned, all of the elements won't be the same height unless we force them. They're just different by default.

So just give the text input fields `vertical-align: middle;` to get everything vertically centered.

<img width="737" alt="screenshot 2017-02-24 09 46 13" src="https://cloud.githubusercontent.com/assets/2359131/23314274/19ce024e-fa76-11e6-8a59-2127c46c36e4.png">

**Comment by ghost1227** [comment]
@SDavisMedia Makes sense to me!

**Comment by ghost1227** [comment]
@pippinsplugins See if that's better. (submit fail... apparently didn't actually hit the comment button)

**Comment by pippinsplugins** [comment]
@ghost1227 The select field is not an `input`, so your last commit removed the alignment.

**Comment by SDavisMedia** [comment]
@pippinsplugins not sure what you mean... the last two commits should be correct. Are they not aligned for you?

**Comment by ghost1227** [comment]
@pippinsplugins @SDavisMedia It's aligning correctly for me...

**Comment by pippinsplugins** [comment]
I don't see any change in the alignment. Still looks like my screenshot
above.

**Comment by SDavisMedia** [comment]
@pippinsplugins something has to be wrong on your end. You mentioned that the select field is not an input. That's fine because WP admin CSS already vertically aligns select menus to the middle. That's why I told Dan to just target the text elements. 

Perhaps something else is interfering. Does your CSS for the select menu look different than this?
<img width="1044" alt="screenshot 2017-02-24 11 57 17" src="https://cloud.githubusercontent.com/assets/2359131/23318739/74b42230-fa88-11e6-8b2e-551e78b9caef.png">

**Comment by pippinsplugins** [comment]
I had script debug disabled. All good here :D

**Comment by pippinsplugins** [comment]
Let's get some unit tests added to this before we merge it in, otherwise it's good to go.

**Comment by ghost1227** [comment]
What do you want tested? Just the new gateway payment query arg?

**Comment by pippinsplugins** [comment]
@ghost1227 I want unit tests that query payments for specific gateways and then check the results.

**Comment by pippinsplugins** [comment]
Let's move this up in priority. No need to let it sit so long.

**Comment by pippinsplugins** [comment]
All working well here. I'm going to merge now.
