### ISSUE TITLE
Currency Name Misspelling

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#5230]
Within the Currency Settings, the currency name "Pounds Sterling" should be "Pound Sterling".

Similarly, cosmetically the "Currency Position" symbol should reflect the currency selected.

**Comment by sunnyratilal** [comment]
@davidsherlock These are two separate issues - please could you open another one regarding the `Currency Position` as it is an enhancement not a bug.
