### ISSUE TITLE
Request-URI Length Issue

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#5233]
I had to selectively bulk delete pages and pages of transaction/purchase history records within EDD on my staging server. By default WordPress/EDD bulk deletion doesn't "reset" the browser URI when doing so, meaning that after a few pages of bulk selection/deletion the server gives the following error due to the size of the URI/string:

414 Request-URI Too Large

This happens in both Apache and nginx environments for the same reason.

I believe this issue is related to WordPress natively rather than EDD, due to the way it handles bulk actions and tables. Though felt it was worth reporting regardless.

**Comment by davidsherlock** [comment]
The only way to fix the issue is to force a refresh within the browser to reset the URI.

**Comment by pippinsplugins** [comment]
Related https://github.com/easydigitaldownloads/easy-digital-downloads/issues/2387

**Comment by cklosowski** [comment]
This is a WordPress core bug, as we've stated in #2387. Closing and labeling for .org.
