### ISSUE TITLE
Update edd_get_payment_by() to do direct DB queries when looking up by purchase key / number

### ISSUE THREAD

**Issue by stephywells** [easydigitaldownloads/easy-digital-downloads#5234]
I'm having a lot of trouble with the downloads page. Take a look.
<img width="1264" alt="screen shot 2016-11-21 at 2 36 35 pm" src="https://cloud.githubusercontent.com/assets/1116876/20501660/fda019a4-aff7-11e6-982c-6049d8b53443.png">

The get_post queries that include the post meta are horribly long on my site. It cuts it way down from 18 to 2 seconds by using two queries instead of one. This is line 72 of payments/functions.php

		global $wpdb;
		$post_ids = $wpdb->get_col( $wpdb->prepare(
			"SELECT post_ID FROM {$wpdb->postmeta} WHERE meta_key = %s AND meta_value=%s",
			'_edd_payment_purchase_key', $value
		) );
		$payment = edd_get_payments( array(
			'include'       => $post_ids,
			'posts_per_page' => 1,
			'fields'         => 'ids',
		) );

It also helps to only load completed payments here. In history-downloads.php, change:
$purchases = edd_get_users_purchases( get_current_user_id(), 20, true, 'any' );

to:
$purchases = edd_get_users_purchases( get_current_user_id(), 20, true );

and then the extra check can also be skipped if ( edd_is_payment_complete( $payment->ID ) )

But if you really want non-completed payments to show there, how about changing these checks to use the payment you already have rather than checking the database again?

**Comment by stephywells** [comment]
If you're okay with this, I can go ahead with a PR.

**Comment by pippinsplugins** [comment]
@stephywells is this just on the frontend with the [purchase_history] shortcode?

We intentionally show all payment status to customers. That's definitely something you may want to change but changing it globally for all EDD users won't work well for us.

I have no qualms with changing `edd_get_payment_by()` to do a direct SQL query. That's a great idea. Might as well change it for both payment keys and payment numbers.

I'm going to update the issue title to reflect that change.

**Comment by stephywells** [comment]
This is using in [downloads_history] shortcode. Maybe it could use options like [downloads_history status=all] and [downloads_history status=complete]?

Since 2 seconds is still a bit high and there are a lot of similar queries, I got it down to 0.25 by getting all the cart details at once instead of getting the payment object and looping through each payment.
https://gist.github.com/stephywells/e33c2a298f5810136bdb746970614d3e

Let me know your thoughts on this one too before a PR?

**Comment by pippinsplugins** [comment]
Let's start by just changing `edd_get_payment_by` to do direct queries.

We could definitely considering supporting status options in the shortcode in a separate issue.

**Comment by SDavisMedia** [comment]
Ping here as well. Removing `Needs Testing` until PR comments are addressed.

**Comment by stephywells** [comment]
The PR has been updated and is ready to go.

**Comment by pippinsplugins** [comment]
There are some tests failing here but they are unrelated to these changes so I'm going to adjust those in master if need be https://travis-ci.org/easydigitaldownloads/easy-digital-downloads/builds/181837966
