### ISSUE TITLE
Don't get notes twice in new EDD_Customer()

### ISSUE THREAD

**Issue by stephywells** [easydigitaldownloads/easy-digital-downloads#5239]
The database queries when a customer is fetched look like this:
SELECT * FROM wp_edd_customers WHERE user_id = '6' LIMIT 1
SELECT notes FROM wp_edd_customers WHERE id = '2' LIMIT 1;

Would it cause any problems if the get_raw_notes function looks like this to prevent the extra query?

	private function get_raw_notes() {

		if ( isset( $this->notes ) ) {
			$all_notes = $this->notes;
		} else {
			$all_notes = $this->db->get_column( 'notes', $this->id );
		}

		return (string) $all_notes;

	}

**Comment by pippinsplugins** [comment]
No issues at all that I see!

**Comment by stephywells** [comment]
I've got a PR ready for this.

**Comment by pippinsplugins** [comment]
@stephywells After seeing the unit tests fail due to the changes, I think we should alter this slightly. See my comment on the PR. Thanks!

**Comment by SDavisMedia** [comment]
Ping.

Removing `Needs Testing` until the PR is updated.
