### ISSUE TITLE
Switch schema markup method from microdata to JSON-LD

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/easy-digital-downloads#5240]
After doing some research, I'm finding some compelling reasons to implement an alternate structured data markup method. Specifically switching from *microdata* (current method) to *[JSON-LD](https://en.wikipedia.org/wiki/JSON-LD)*. Here's my case:

First off, we have some minor issues with our structured data already. I'll open another issue shortly but [here](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/templates/shortcode-content-price.php#L5) for example we're outputting the currency and price together which [isn't recommended](http://schema.org/price).

Secondly, JSON-LD is potentially easier to manage and less problematic from a theme perspective. It separates the data from the markup thereby making our templates much simpler.

[WooCommerce just did it two months ago](https://github.com/woocommerce/woocommerce/pull/11455). Long discussion about it over there with lots of great information. Really sounds like a good move. Also it being recommended by Google gives it serious weight.

**Comment by pippinsplugins** [comment]
Doing this would get rid of the infamous "HTML characters in titles" title we get all the time due to improper use of `the_title()` in attributes.

**Comment by spencerfinnell** [comment]
Would love to see this!

**Comment by brashrebel** [comment]
Want me to try and tackle this?

**Comment by pippinsplugins** [comment]
Go for it!

**Comment by brashrebel** [comment]
Here's what I think we need to do to make this happen:

- Introduce new `class-edd-structured-data.php` file
- Build a class which generates the JSON for our data types
- Output the data on `wp_footer`
- Remove schema markup from templates
- Deprecate `edd_add_schema_microdata()` *or* use that to hook into `wp_footer` and output the JSON

Looking for input to make sure I'm thinking about this correctly and not missing anything important.

**Comment by pippinsplugins** [comment]
@brashrebel that approach seems right to me!

**Comment by Shelob9** [comment]
@brashrebel  Did you see my JSON-LD plugin? https://gitlab.com/caldera-labs/caldera-jsonld It's lacking a UI and isn't PHP5-friendly, but please to borrow code.

**Comment by amdrew** [comment]
@brashrebel Would love to see this! 👍

**Comment by cklosowski** [comment]
We also need to add support for Fragments, which would help theme developers as well: https://github.com/json-ld/json-ld.org/issues/107 h/t @inetbiz

**Comment by sunnyratilal** [comment]
@cklosowski I've looked into fragments but not sure how it would apply to us?

**Comment by inetbiz** [comment]
@sunnyratilal not apply to you. When WE add json+ld, we can reference that hash id.

**Comment by sunnyratilal** [comment]
@amdrew As we've deprecated the existing schema functions, we'll need to push out an update to Themedd as it makes use of the `edd_add_schema_microdata` function.

**Comment by sunnyratilal** [comment]
@SDavisMedia The same applies for [Vendd](https://github.com/easydigitaldownloads/vendd/blob/177ca9ecebf4b8d5494fb268777fb36082f6e5a7/content/content-advanced-search.php#L16) as well.

**Comment by sunnyratilal** [comment]
Merged!
