### ISSUE TITLE
Separate price and currency in templates for schema.org microdata

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/easy-digital-downloads#5241]
Currently, using [Google's structured data testing tool](https://search.google.com/structured-data/testing-tool/u/0/), pages with `edd_price()` on them show a warning because the currency and amount are combined in the same element. [Schema.org recommends](http://schema.org/price) using a `priceCurrency` property to notate the currency characters and using the `price` property only for the numeric amount.

If we don't move forward with #5240 then this might be tricky. Maybe add an argument to `edd_price()` for determining whether to include the currency? Or modify our templates to get the price and currency via alternate methods?

**Comment by michaelbeil** [comment]
Seems to be a good way to move core forward as  #5240 already has traction.

**Comment by brashrebel** [comment]
This was previously brought up in #3355. #4566 addressed for variable products in 2.6. #4567 was supposed to have addressed single products and @pippinsplugins indicated there that it was merged but it doesn't look like it was. Pippin can you confirm? I'm on master and have no `edd_purchase_single_pricing()` function which was what the PR introduced.

Maybe these two PRs which separately addressed variable and non-variable products got mixed up and the latter wasn't actually merged?

**Comment by pippinsplugins** [comment]
Looks like it may have only been done for variable products:

In `edd_purchase_variable_pricing()` we have:
```
if( edd_add_schema_microdata() ) {
	echo '<meta itemprop="price" content="' . esc_attr( $price['amount'] ) .'" />';
	echo '<meta itemprop="priceCurrency" content="' . esc_attr( edd_get_currency() ) .'" />';
}
```

Currency is definitely missing from single prices and the `[edd_price]` shortcode.

**Comment by pippinsplugins** [comment]
Reopened https://github.com/easydigitaldownloads/easy-digital-downloads/pull/4567

**Comment by pippinsplugins** [comment]
PR is good. Made a couple of tweaks to it and merged.
