### ISSUE TITLE
"Today" report doubling actual value

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#5242]
In 2.6.12 changes were made to reports that has caused an issue with the `Today` report.

`Today` in dashboard:
![screen shot 2016-11-21 at 9 13 57 pm](https://cloud.githubusercontent.com/assets/1034109/20509607/7477d7b0-b02f-11e6-8558-1e326d242436.png)

`Today` in reports:
![screen shot 2016-11-21 at 9 14 30 pm](https://cloud.githubusercontent.com/assets/1034109/20509619/83aa36f6-b02f-11e6-989b-784008904250.png)

It appears to be taking the entire value for the day, assigning it to `12:00` and then adding each hour's revenue onto that, resulting in double the day's value.

**Comment by sunnyratilal** [comment]
It's a bug in `edd_get_earnings_by_date()`. Fixing it should be pretty simple.

**Comment by pippinsplugins** [comment]
Works great.
