### ISSUE TITLE
Add support for user-defined locales

### ISSUE THREAD

**Issue by ramiabraham** [easydigitaldownloads/easy-digital-downloads#5247]
WordPress 4.7 introduces `get_user_locale()` ([changeset](https://core.trac.wordpress.org/changeset/38705)), which falls back to the standard `get_locale()`.

Areas affected:

- The EDD `load_textdomain()` loader method ([line link](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/easy-digital-downloads.php#L384)) to support user locales.

- `EDD_Tracking::setup_data()`, specifically `$data['locale'] `.

**Comment by ramiabraham** [comment]
Added a PR: https://github.com/easydigitaldownloads/easy-digital-downloads/pull/5248

**Comment by sunnyratilal** [comment]
Merged into `master`
