### ISSUE TITLE
This Week and Last Week reports do not display sales

### ISSUE THREAD

**Issue by sunnyratilal** [easydigitaldownloads/easy-digital-downloads#5250]
Reporting changes introduced in 2.6.12 have broken the sales from being displayed for the `This Week` and `Last Week` reports

**Comment by sunnyratilal** [comment]
PR ready for testing

**Comment by sunnyratilal** [comment]
To anyone testing: you will need to clear transients in order for the correct data to show up

**Comment by pippinsplugins** [comment]
Works great.
