### ISSUE TITLE
Deleting item from order doesn't delete the sale log for that download

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#5252]
If you have an order with download ID 1 and ID 2, you have a order post type post, plus meta keys which contain the product ID's for the order. Additionally EDD also makes a log, of the edd_log post type for each download sold in a order. We do this to make it easy (and db cheap) to query for orders containing download items. However, if you remove an item from an order and save it, the edd_log post that says Download ID 1 was sold in order ID XXX is not removed, and the EDD payment query, when using the download arg parameter to limit by orders containing downloads, looks up and limits posts using this. This leads to situations where orders limited to a download are still returned in edd_get_payments and the EDD Payment Query class in general, when the download was formerly but no longer in an order.

The relevant code for the Query Class's lookup for limiting by downloads is below:
```
	public function download() {

		if ( empty( $this->args['download'] ) )
			return;

		global $edd_logs;

		var_dump( $this->args['download'] );

		$args = array(
			'post_parent'            => $this->args['download'],
			'log_type'               => 'sale',
			'post_status'            => array( 'publish' ),
			'nopaging'               => true,
			'no_found_rows'          => true,
			'update_post_term_cache' => false,
			'update_post_meta_cache' => false,
			'cache_results'          => false,
			'fields'                 => 'ids'
		);

		if ( is_array( $this->args['download'] ) ) {
			unset( $args['post_parent'] );
			$args['post_parent__in'] = $this->args['download'];
		}

		$sales = $edd_logs->get_connected_logs( $args );

		if ( ! empty( $sales ) ) {

			$payments = array();

			foreach ( $sales as $sale ) {
				$payments[] = get_post_meta( $sale, '_edd_log_payment_id', true );
			}

			$this->__set( 'post__in', $payments );

		} else {

			// Set post_parent to something crazy so it doesn't find anything
			$this->__set( 'post_parent', 999999999999999 );

		}

		$this->__unset( 'download' );

	}
```

All we need to do is ensure when an item is removed from the order, either programically or via the interface, that the related log is also deleted. Additionally, the log post has two meta keys, one to tie the download to the order it's in, and the other to specify which price ID the order contains for a download. Both need to be deleted.

This also means we need an upgrade routine to fix this for all existing orders with the same problem. Shouldn't be hard to fix the issue + write the routine for, it's pretty straightforward.

**Comment by chriscct7** [comment]
EDD has code for this here: 
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/payments/class-edd-payment.php#L689

It's somehow not working correctly. Problem starts around here likely:
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/payments/class-edd-payment.php#L1205

**Comment by pippinsplugins** [comment]
Bug confirmed.

**Comment by pippinsplugins** [comment]
PR ready to test.

**Comment by pippinsplugins** [comment]
@SDavisMedia @mintplugins could one of you test this for me?

**Comment by mintplugins** [comment]
This removed sales logs for products removed from a payment. However, it only removes the sales log if the item is deleted from the payment after switching to the 5252 branch. If I re-save a payment  it doesn't delete previously existing sales logs. 

1 - Should there be an upgrade routine for this which removes orphaned sales logs that already exist?
2 - Perhaps alternatively, should resaving a payment check for any pre-existing orphaned sales logs and remove them?

**Comment by pippinsplugins** [comment]
I did not intend this to work retroactively. Doing so would require a large upgrade routine.

**Comment by mintplugins** [comment]
Cool - in that case it is working perfectly. I don't think it requires retroactivity unless we start getting requests for it personally.

**Comment by chriscct7** [comment]
I think we should, personally, as it messes up all the queries for getting
all orders that have a user's product in them. Just a thought

On Tue, Dec 13, 2016 at 4:59 PM, Pippin Williamson <notifications@github.com

**Comment by pippinsplugins** [comment]
It's not a realistic upgrade routine to write though, unfortunately. It would require going through every single payment record, then looping through every item on a payment, querying for the sale logs associated with that item, comparing the found logs to the items on the payment, determining the ones that don't match any more, then deleting those, and then repeating that process for every line item and every payment record.

It could be done for smaller sites but any reasonably large site (think those that are even 1/5th the size of our own), it wouldn't be feasible.

**Comment by chriscct7** [comment]
What? This is exactly what we do, literally, when you run the Recount Download Stats for All Downloads tool in the EDD Tools page.

**Comment by pippinsplugins** [comment]
No it's not. That queries the sale logs directly. An upgrade routine for this would be 3x more queries or more.

**Comment by chriscct7** [comment]
The sales logs do not have the updated sales information, for example if you change an order after it was first submitted, so for each sales log, we then pull each payment's cart information attached to the sales log (by first querying the meta table for the payment id for each sales log):
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/admin/tools/class-edd-tools-recount-download-stats.php#L86

In the recount download earnings we:
1. Get all sales logs for download
2. For each payment ID in the sales log, we then query to get all payments (the post table db row)
3. For each payment as an object, we then check to see if it is complete, and it if so, we pull the cart information via edd_get_payment_meta_cart_details

To do the upgrade routine:
1. For each payment row (as pulled from DB)
2. We pull the attached sales logs for that payment
3. And the cart details from edd_get_payment_meta_cart_details

It's literally the same exact thing.

In fact, you could even use the same exact routine we use for recounting a download's earnings, and instead of doing the addition of each download as we do now, just do the comparison, and drop there, thus the whole thing can be done by taking https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/admin/tools/class-edd-tools-recount-download-stats.php#L86 and replacing this addition for loop and insert the drop condition: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/admin/tools/class-edd-tools-recount-download-stats.php#L101

**Comment by chriscct7** [comment]
If the only thing the recount earnings sales thing was query the sales logs, you'd actually have run into this exact same bug because download earnings would be off for orders that had them when created but removed them later. This is why the earnings routine works right now.
