### ISSUE TITLE
Customers not receiving download link email

### ISSUE THREAD

**Issue by SewHappyMe** [easydigitaldownloads/easy-digital-downloads#5255]
Once customers have completed a purchase and made payment, they are not receiving their email with the download link. On some occasions it appears that it has gone into their spam folder, but on other occasions the customers cannot find it in their spam folder either. This is a recent issue. I am using Wordpress 4.6.1

**Comment by pippinsplugins** [comment]
Hi there!

Please go ahead and open a support ticket through our support portal: https://easydigitaldownloads.com/support

we use GitHub for development tracking only.
