### ISSUE TITLE
Add download attribute to downloads

### ISSUE THREAD

**Issue by schlessera** [easydigitaldownloads/easy-digital-downloads#5259]
Given the name of the plugin, it should assume that the links it generates within receipt emails and shortcodes should be identified as downloads through the HTML5 `download` attribute on that `<a>` tag.

This tag does two things:

1. It allows to specify a clean filename that is used for saving the file on the customer's computer, instead of the random string that gets generated for security purposes.
2. It forces the browser to consider this link to be a download, instead of a file that should be played inline if possible. This avoids such scenarios where clicking on a purchased media file just plays that media file in the browser instead of downloading it.

Usage example:
```HTML
<a href="https://example.domain/index.php?eddfile=830%3A360%3A1%3A0&ttl=1480163556&file=1&token=33b98290c9ada42f94ef10ac92ae9441" download="myfile.mp3">
```

This will let the browser immediately download the file instead of playing it in the browser window, and it will save the file as `myfile.mp3` instead of whatever the file happened to be called on the server side.

I was hoping that I could just use a filter to add this attribute, but the link generation seems to be hard-coded without obvious extension points.

**Comment by chriscct7** [comment]
Duplicates of #2794 and #2798

**Comment by pippinsplugins** [comment]
I really wish we could add this but it breaks download link error messages.
