### ISSUE TITLE
reCAPTCHA Support

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#5262]
Spam bot registrations are a constant problem for any online store that accepts user registrations out with the checkout form. Jetpack and various other plugins help minimize the problem but don't stop it eliminate it. Can reCAPTCHA support be added to EDD core in a future release?

**Comment by chriscct7** [comment]
reCAPTCHA support is already available in our Checkout Fields Manager addon for the checkout page.

For the standalone shortcodes, it can be found here: https://wordpress.org/plugins/recaptcha-for-easy-digital-downloads/

**Comment by chriscct7** [comment]
It should also be noted EDD employs a basic honeypot on the register form

**Comment by davidsherlock** [comment]
Chris, the problem isn't the checkout form (which a spam-bot can't easily reach) but the user profile/registration shortcodes EDD provides. This isn't protected by the CFM and thus is prone to getting high numbers of spam registrations.

The functionality in that plugin would be better suited in core EDD in my opinion, to offer a lighter and consolidated approach.

**Comment by davidsherlock** [comment]
One way to mitigate this is to force auto account creation at checkout and remove the need for the registration forms.

**Comment by chriscct7** [comment]
We have an existing free plugin for both of these ideas:
For auto registering at checkout: https://wordpress.org/plugins/edd-auto-register/
For protecting the shortcodes: https://wordpress.org/plugins/recaptcha-for-easy-digital-downloads/

**Comment by pippinsplugins** [comment]
I agree that we do not want to put this in core. It's better as a free add-on.
