### ISSUE TITLE
Multiple quantities can be added even when quantitys turned off

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#5263]
When quantity support is turned off, you shouldn't be able to add more than 1 of a product to the cart, but EDD will let you do it through the use of add to cart links. EDD core doesn't support this functionality, and it messes up when calculating the taxes + discounts in these cases. We should just have the add to cart functionality check to see if item is already in cart + item quantitys turned off, then ignore.

**Comment by pippinsplugins** [comment]
Quantities being disabled does not mean the cart items must be unique. It's still permitted to purchase multiple of the same item, but each item will be a separate cart item.

**Comment by chriscct7** [comment]
cc @pippinsplugins ^

**Comment by pippinsplugins** [comment]
Yes please open issues.
