### ISSUE TITLE
Apply & remove discount ajax needs to set total amount (unformatted) data attribute value.

### ISSUE THREAD

**Issue by pderksen** [easydigitaldownloads/easy-digital-downloads#5265]
For the Stripe checkout overlay amount in EDD-Stripe (https://github.com/easydigitaldownloads/edd-stripe/issues/169) and possibly other payment gateways/add-ons, the unformatted total amount after applying or removing discount codes needs to set the appropriate data attribute in jQuery (in addition to the formatted displayed amount/cart total).

**Comment by pippinsplugins** [comment]
PR https://github.com/easydigitaldownloads/easy-digital-downloads/pull/5266

**Comment by pippinsplugins** [comment]
PR works great.
