### ISSUE TITLE
Reports: December plot point is wrongly positioned

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#5274]
When viewing a yearly report, december gets improperly positioned.

This happened a while ago and was fixed in https://github.com/easydigitaldownloads/easy-digital-downloads/issues/3072. Looks like it is back.

**Comment by pippinsplugins** [comment]
Looks like it is the earnings portion of the graph that's causing the issue. Note how in the screenshot below the sales point for december is correctly positioned.
![screen shot 2016-12-06 at 3 50 05 pm](https://cloud.githubusercontent.com/assets/1034109/20945156/bfb19e80-bbcb-11e6-92d7-074d461c3e56.png)

**Comment by pippinsplugins** [comment]
The timestamp for the sales count is December 1 but the timestamp for earnings is December 31.

**Comment by sunnyratilal** [comment]
Tested and merged into `master`
