### ISSUE TITLE
Custom Software license activation field (idea/request)

### ISSUE THREAD

**Issue by loxai** [easydigitaldownloads/easy-digital-downloads#5276]
Hi,

I've been looking at the documentation but couldn't find a relevant reference.
My concern is about software keys being shared: one key can be activated/validated by many users.
I know there's the activation limit, but this can impact the genuine buyer (eg. re-installing/re-validating).
Is there a way to make the activation and verification API calls to have an extra validation field?
This could be used to match a unique PC identifier (license tied to one machine):
- send activation with extra field value
- validation requires a match for the extra field
- new activation attempt requires a match for the extra field, if such extra was already set before
- [optional] activation/validation returns an extra field (for "license": "invalid") called reason that may return something like "reason":"invalid_key" and "reason":"extra_field_mismatch". This would be to differentiate wrong/expired keys and key activated by other user/PC, and notify user accordingly

Kind regards

**Comment by sunnyratilal** [comment]
This repository is used for tracking development of Easy Digital Downloads.  As this is a support request, please open a ticket at http://easydigitaldownloads.com/support where you will be assisted on this matter.
