### ISSUE TITLE
Per-Item Tax Rate

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#5286]
I may be missing something here, but I believe the per-item tax rate isn't stored within the cart item array for each individual item within the purchase. While the subtotal, tax amount and item price are stored it's not possible to calculate the tax rate using a calculation because the tax amount collected is stored as 2 decimal places instead of as a float (like the the item price after discounts, tax, etc.).

Because different items may have different tax classes (rates) applied, this would be a useful addition to have for marketplaces where tax responsibility is passed to the vendors.

**Comment by pippinsplugins** [comment]
@davidsherlock see #4105

**Comment by davidsherlock** [comment]
@pippinsplugins, the tax rate doesn't technically need to be stored on a per item basis if the tax amount is saved as a float instead of as 2 decimals. A simple calculation can be done to figure out the inclusive (or exclusive) rate based on the sale price and tax amount collected. 

I already wrote the math for this but because of the misalignment between the values, the only solution is to roundup to get the rate which would cause problems for more specific tax rates like 6.52%.

**Comment by pippinsplugins** [comment]
Requiring math to determine the rate is silly, in my opinion. No reason to not store the actual rate itself as that removes _all_ doubt and possibility for error.

**Comment by davidsherlock** [comment]
Ha! well that's that then...:)
