### ISSUE TITLE
adjust "post type attribute" metabox label for downloads

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#5289]
WordPress 4.7 introduces support for custom post type templates like the familiar Page Templates. See feature info: https://make.wordpress.org/core/2016/11/03/post-type-templates-in-4-7/

Just like how the "Featured Image" label became customizable for post types during registration ([info](https://github.com/easydigitaldownloads/easy-digital-downloads/issues/3422)), the same can be done for the `{post_type} Attributes` metabox when download templates are introduced.

Gonna adjust the metabox label just the same here, otherwise it will read `Post Attributes`. Code coming.

**Comment by SDavisMedia** [comment]
<img width="300" alt="screenshot 2016-12-11 14 12 41" src="https://cloud.githubusercontent.com/assets/2359131/21083744/ec3b2fdc-bfab-11e6-92dd-76f03a25feb6.png">

**Comment by SDavisMedia** [comment]
If you want to test this, add a file to your active theme called something like `download-template.php`.

Add this to the file:

```php
<?php
/**
 * Template name: Downloads Template
 * Template Post Type: download
 */
echo "yay!";
```

Edit a download and look for the `Downloads Attributes` metabox. The fact that it says `Download` in that label is the test. But also feel free to switch the template, save, and view the download if you want to see the new feature in action.

**Comment by pippinsplugins** [comment]
Wonderful :+1:
