### ISSUE TITLE
Download links in emails over escaped

### ISSUE THREAD

**Issue by Shelob9** [easydigitaldownloads/easy-digital-downloads#5292]
My email receipts are over-escaped and therefore don't work, which is bad.

Here is an example, the & is being encoded.

https://new-cf.dev/wp/index.php?eddfile=34476%3A565%3A1%3A1&#038;ttl=1481992962&#038;file=1&#038;token=84c31976f264e5b067f8ad02426ac356

My solution (PR incoming) is to use `esc_url_raw` instead of `esc_url` in `edd_email_tag_download_list` ~L430

**Comment by Shelob9** [comment]
System info: 
production -https://pastebin.com/rREvJb47
development -  https://pastebin.com/8cLszVHy

This wasn't happening on old site, which was PHP5. Hard to say if PHP7 is to blame, as many things changed.

**Comment by Shelob9** [comment]
BTW, my quick fix until this is fixed in main plugin (easier than switching my composer.json to use my fork) https://pastebin.com/3wjYhW1u

**Comment by pippinsplugins** [comment]
@Shelob9 We'll get this included with 2.6.14, thanks!
