### ISSUE TITLE
Merge Manual Purchase extension into core

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#5295]
We will stop distributing this extension separately and merge it into core. Any enhancements to the functionality that need to be made will happen as it is merged. https://github.com/easydigitaldownloads/edd-manual-purchases/issues/57

**Comment by xberg** [comment]
Hello,
Are you able to share a date at which this integration of Manual Purchases into the core is planned?

**Comment by chriscct7** [comment]
@xberg we do not release dates publicly for any ticket as ideas can come and go, and software is very fickle in the sense things can be done faster and slower than expected, and are constantly being re-prioritized. We'd encourage you to sign up for our newsletter at easydigitaldownloads.com, follow us on Twitter, and follow our blog at easydigitaldownloads.com/blog for any major announcements such as this one if/when they become finalized and dates and/or proposed versions are released.

**Comment by Nate82** [comment]
@chriscct7 Can you at least say if this merge is still planned? I don't want to buy the extension and then a week later it's merged into core. EDD is at 2.8.10 now.

**Comment by cklosowski** [comment]
@Nate82 there is currently no milestone attached, which means it's not planned to even be looked at until it get's a milestone. And as @chriscct7 stated above, we don't provide dates like that due to many number of reasons as he stated above.

I can tell you, that since this isn't even milestoned, it's VERY UNLIKELY it'll be merged within a week.

**Comment by pippinsplugins** [comment]
I'd estimate 3-6 months at best.

**Comment by Nate82** [comment]
@pippinsplugins Ok, thanks. It's definitely worth the $29 purchase if we're talking 3-6 months before it's merged, just wanted to make sure it wasn't in the pipeline a lot sooner.

**Comment by sunnyratilal** [comment]
Merged into Core. 🎉
