### ISSUE TITLE
Average monthly order # & $ amounts are broken when you run year-long reports

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#5297]
On https://easydigitaldownloads.com/wp-admin/edit.php?post_type=download&page=edd-reports&view=downloads&download-id=74950&exclude_taxes=0&range=other&year=2016&year_end=2016&m_start=1&m_end=12&day=1&day_end=31

Average monthly order # & $ amounts are broken when you run year-long reports, ex jan 1->dec 31, 20{14/15/16} all have identical numbers when you change the years

**Comment by pippinsplugins** [comment]
It would be nice to see this show the average for the shown time period.
