### ISSUE TITLE
User not getting pulled in earnings report list

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#5298]
On https://easydigitaldownloads.com/wp-admin/edit.php?post_type=download&page=edd-reports&tab=logs&view=sales&download=74950 notice that for some rows the user is missing, but they are attached correctly on payments

**Comment by pippinsplugins** [comment]
We should update the logs page to say `Customer` instead and to properly pull the name from the `EDD_Customer` object.

**Comment by pippinsplugins** [comment]
Ready for testing/

**Comment by SDavisMedia** [comment]
Can't replicate the original issue locally but the table column header is adjusted and all customers are properly linked for me on `issue/5298`. :+1:

**Comment by pippinsplugins** [comment]
Merging.
