### ISSUE TITLE
Quantity not set in cart items when adding multiple price options with custom link

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#5299]
When adding a multiple price options of a product to the cart, the `quantity` key does not get set properly.

For example, use a URL like this: http://local.wp/vendor/?edd_action=add_to_cart&download_id=1669&edd_options[price_id]=1,2,3

Now call `edd_get_cart_quantity()`. The result should be 3 but it will actually be zero.

**Comment by pippinsplugins** [comment]
Ready for testing.

**Comment by dipakcg** [comment]
@pippinsplugins, Tested and it works.

Fixed the issue I've asked via support ticket (ticket # 20342). Waiting for the core updates as many of my client sites uses the custom code ( I've shared with you in the support conversation ).

**Comment by cklosowski** [comment]
This seems to have broken a unit test. Is that because the unit tests needs fixing or because the unit test is incorrect?

```
There was 1 failure:

1) Test_Cart::test_add_to_cart_multiple_price_ids_array_with_quantity
Array (...) does not match expected type "integer".

/Users/cklosowski/Development/sites/edd/app/public/wp-content/plugins/easy-digital-downloads/tests/tests-cart.php:137
```

`$this->assertEquals( 2, edd_get_cart_item_quantity( $this->_post->ID, array( 'price_id' => 0 ) ) );`

**Comment by pippinsplugins** [comment]
Looks to me like the unit test is wrong. An array is expected here.
