### ISSUE TITLE
"File not found" error occurring in 2.6.14

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#5308]
With https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5268 we introduced a check to  programmatically determine if files exist before attempting to download it.

This appears to be causing false "404" reports of files, so even files that do exist and download properly are getting flagged with a 404.

Example tickets reporting the problem:

https://secure.helpscout.net/conversation/294998207/49530/?folderId=180499
https://secure.helpscout.net/conversation/293511498/49361/?folderId=180504
https://secure.helpscout.net/conversation/294560263/49483?folderId=180504

I do not yet know why it happens.

**Comment by pippinsplugins** [comment]
Customer reported fixing it:

>>>I found the issue. It's the htaccess file in the edd folder that is causing the issue. It is only permitting images to be accessed. Once I modified the file to allow the file types that I am uploading , everything started working fine again.

**Comment by pippinsplugins** [comment]
Will probably update this to only run the head check on external URLs.

**Comment by nosegraze** [comment]
I'm also getting this error with the Git Update Downloads add-on.

**Comment by pippinsplugins** [comment]
Another report: https://secure.helpscout.net/conversation/295388441/49592/?folderId=180499

**Comment by pippinsplugins** [comment]
PR ready for testing.

**Comment by nosegraze** [comment]
PR works with the Git add-on now.

**Comment by pippinsplugins** [comment]
Thanks @nosegraze!

**Comment by SDavisMedia** [comment]
On 1issue/5308`:

* file uploaded through EDD's product file UI is downloading fine
* file with invalid URL is giving me a 403 https://cl.ly/2y0G092O0b1q
* file with valid URL but hosted off-site is downloading fine

**Comment by pippinsplugins** [comment]
Perfect, thanks! Merging and deploying.
