### ISSUE TITLE
Credit Card Info and Billing Details fields shown at checkout with no payment gateways selected

### ISSUE THREAD

**Issue by sumobi** [easydigitaldownloads/easy-digital-downloads#5309]
Set up a new sub-site with v2.6.15. Without touching any settings and going to checkout, the `Credit Card Info` and `Billing Details` sections are shown. These should not be shown unless a compatible CC gateway is installed.

<img width="1256" alt="screen shot 2016-12-21 at 9 28 09 am" src="https://cloud.githubusercontent.com/assets/52581/21366714/dc79afea-c75f-11e6-99e5-d4acaa854e30.png">

___

<img width="916" alt="screen shot 2016-12-21 at 9 28 27 am" src="https://cloud.githubusercontent.com/assets/52581/21366715/dc7ab692-c75f-11e6-990c-2135bd0d6310.png">

___

Can anyone else replicate?

**Comment by SDavisMedia** [comment]
Definitely replicated on a fresh site.

**Comment by pippinsplugins** [comment]
This is technically intentional and has been this way since 1.0 (or shortly after).

I have no idea why I did it this way and would definitely agree that it should be considered a bug now.

**Comment by sumobi** [comment]
👍  Weird, I've set up many EDD sites and have never seen it like this. The checkout had always only shown the "you must enable a payment gateway" message.

**Comment by SDavisMedia** [comment]
Hmmm... pretty sure that has been in experience as well. Several times. But I wasn't paying close attention so...

**Comment by ghost1227** [comment]
@pippinsplugins There's one way to do it, though you might prefer a different method.

**Comment by pippinsplugins** [comment]
Looks like a fine approach to me. Haven't tested yet but looks fine.

**Comment by pippinsplugins** [comment]
Works great, merged.
