### ISSUE TITLE
Wrong RU translation on checkout page in user info

### ISSUE THREAD

**Issue by Dreaminsider** [easydigitaldownloads/easy-digital-downloads#5313]
I have found some bug in EDD/includes/checkout/template.php

in function edd_user_info_fields() {
```
...
<p id="edd-first-name-wrap">
			<label class="edd-label" for="edd-first">
				<?php _e( 'First Name', 'easy-digital-downloads' ); ?>
				<?php if( edd_field_is_required( 'edd_first' ) ) { ?>
					<span class="edd-required-indicator">*</span>
				<?php } ?>
			</label>
			<span class="edd-description"><?php _e( 'We will use this to personalize your account experience.', 'easy-digital-downloads' ); ?></span>
			<input class="edd-input required" type="text" name="edd_first" placeholder="<?php _e( 'First Name', 'easy-digital-downloads' ); ?>" id="edd-first" value="<?php echo esc_attr( $customer['first_name'] );
}


<input class="edd-input required" type="text" name="edd_first" placeholder="<?php _e( 'First name', 'easy-digital-downloads' ); ?> 
```  

have to be changed to:

`<input class="edd-input required" type="text" name="edd_first" placeholder="<?php _e( 'First Name', 'easy-digital-downloads' ); ?>`

because now plaseholder on First Name contains Last Name translation on RU language.

**Comment by ghost1227** [comment]
@pippinsplugins I'm not sure I understand this. other than dropping the input and value, it looks like the proposed change is identical... and I'm pretty sure we don't want to drop those. Do you understand this?

**Comment by pippinsplugins** [comment]
Only difference I see is the capitalization of `name`. `Name` vs `name`.

**Comment by sunnyratilal** [comment]
PR opened at #5588
