### ISSUE TITLE
Beta tab checkboxes not displaying state correctly

### ISSUE THREAD

**Issue by ghost1227** [easydigitaldownloads/easy-digital-downloads#5319]
Seems that somehow we made a mistake with the beta support tab. We're echoing the value of `$checked` to determine whether or not support is enabled, but `$checked` is a bool. This results in checked plugins having an extra `1=""` param instead of `checked="checked"`.

**Comment by ghost1227** [comment]
@pippinsplugins Pretty important little bug here.

@SDavisMedia This resolves the issue you mentioned on https://github.com/easydigitaldownloads/EDD-Software-Licensing/issues/514

**Comment by pippinsplugins** [comment]
Merged.
