### ISSUE TITLE
Add to cart links for variable option without specifying price option broken

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#5345]
If you create an add to cart link for a variable price item, but do not include the option to choose in the url, EDD correctly defaults to 1 (though I didn't test what happens if you set default variation to non-1, so it's possible there's another bug here; this should be tested). However, despite showing the correct price for the first variation on the checkout page, the product variation title does not display next to the product name, and when the order is completed, this isn't fixed, and the order meta contains this cutoff product name

**Comment by pippinsplugins** [comment]
I'm seen this happen numerous times. Definitely a bug.

**Comment by mintplugins** [comment]
Related: If you enable variable pricing for a product, it's possible to purchase a single price version using a custom "Add To Cart" link. Technically you would be purchasing a product that doesn't exist.

This should likely either throw a cart error or default to the default price.

**Comment by chriscct7** [comment]
I don't think it purchases the single price version (or at least it shouldn't) I think it's purchasing the default (or first variation), not sure which.

I think if the optionID isn't specified, the default variation should be added to teh cart

**Comment by mintplugins** [comment]
A quick test shows that's not true. It purchases a product with no variation:

<img width="635" alt="screen shot 2017-03-04 at 2 46 48 am" src="https://cloud.githubusercontent.com/assets/1638128/23577105/ee780e5e-0084-11e7-8bc7-62decf763a72.png">

**Comment by chriscct7** [comment]
What happens if you don't set a simple product up and leave those blank? It seems to be using option 1 (which === default on the setup I'm testing on)

**Comment by mintplugins** [comment]
@chriscct7 When you say "Don't set up a single product", what are you meaning?

**Comment by chriscct7** [comment]
To clarify it's not buying a product without variation, it's buying either (I haven't tested to see which one) variation 1 or the default variation, except the checkout excludes the name of the variation (but it knows it is a variation product that's why it uses the - ). If you set variation 1 to have a price of 5 and then try adding to card, it will add a product with no variation but a cost of $5. It's buying the variation, it's just not including the name of it in the display.

**Comment by sunnyratilal** [comment]
PR opened at #5591 and ready for testing

**Comment by pippinsplugins** [comment]
Fix confirmed.

**Comment by ghost1227** [comment]
You beat me to it by three minutes!
