### ISSUE TITLE
about edd_log

### ISSUE THREAD

**Issue by hamedmoody** [easydigitaldownloads/easy-digital-downloads#5356]
Hi
What is edd_log post type and can i delete them from database?
Thanks

**Comment by cklosowski** [comment]
Hi @hamedmoody 

These are entries that are for various logs we create for interacting with Easy Digital Downloads items. If you don't want them you can remove 'some' of them, but some are associated to sales logs and used for reporting.

Github is only used for the development tracking of Easy Digital Downloads. Questions like this are better served from our support team at https://easydigitaldownloads.com/support.
