### ISSUE TITLE
Auto-format spaces in credit card number field.

### ISSUE THREAD

**Issue by pderksen** [easydigitaldownloads/easy-digital-downloads#5369]
Because it improves checkout usability.

See http://baymard.com/blog/credit-card-field-auto-format-spaces

How about simply using https://github.com/stripe/jquery.payment and adding:

`$('.card-number').payment('formatCardNumber');`

I'm personally going to move to using the Stripe checkout overlay soon (which already does this), but this might be good for folks to have out of the box enabled for any credit card merchant.

**Comment by pderksen** [comment]
Related example using a jQuery trigger: #4148

**Comment by pippinsplugins** [comment]
I really like this idea.

**Comment by cferdinandi** [comment]
I'm currently using [Cleave](https://nosir.github.io/cleave.js/) on [my site](https://gomakethings.com/checkout/) to do this AND highlight the credit card type being used (example, the Visa card under accepted payment types changes color when a Visa card is entered).

**Comment by pippinsplugins** [comment]
We already highlight the card type used. Screenshot (ignore spacing):
<img width="978" alt="screen shot 2017-06-23 at 12 36 02 pm" src="https://user-images.githubusercontent.com/1034109/27493755-8fa57ce8-5810-11e7-8b69-b10de8fd8b61.png">

**Comment by DevinWalker** [comment]
+1 for adding formatted CC spaces. I was surprised it wasn't already.

**Comment by DevinWalker** [comment]
For whoever is eager to get this working like myself, I've put together this quick snippet which uses `jquery.payment.js` from Stripe:

```
/**
 * Auto format EDD's CC fieldset.
 *
 * Note you must enqueue Stripe's jQuery Payment library
 *
 * Repo: https://github.com/stripe/jquery.payment
 * CDN: https://cdnjs.cloudflare.com/ajax/libs/jquery.payment/3.0.0/jquery.payment.min.js
 */
function edd_checkout_add_cc_formatting() {

	echo "<script>

		(function( $ ) {
		  $(function() {
		    
	        // Trigger formatting function when gateway changes.
			$(document).on('edd_gateway_loaded', function ( e ) {
			  
			    var form            = $('#edd_purchase_form');
				var card_number = form.find('.card-number'),
					card_cvc    = form.find('.card-cvc'),
					card_expiry = form.find('.card-expiry');
	
				//Only validate if there is a card field
				if ( card_number.length && 'function' === typeof card_number.payment) {
					card_number.payment('formatCardNumber');
					card_cvc.payment('formatCardCVC');
					card_expiry.payment('formatCardExpiry');
				}
			  
			});
		   
		  });
		})(jQuery);
	
	</script>";
}
add_action( 'wp_footer', 'edd_checkout_add_cc_formatting' );
```

Now, we have pretty CC fields:

![2017-06-30_09-30-34](https://user-images.githubusercontent.com/1571635/27745077-d7ff8f4a-5d76-11e7-94c8-347c09072f0b.gif)

**UX side note:** I don't really like how the field borders turn red while the user is initially entering their CC number. This is distracting and implies there is already a CC error which could stall their input. I believe it would be best UX to only validate when the user focuses out.

**Comment by cferdinandi** [comment]
@DevinWalker This is great, dude! Thank you SO much for doing this. I can now remove another dependency from my stack. Cheers!

**Comment by DevinWalker** [comment]
No problem. Note: you still need to enqueue `jquery.payment.js` for the above to work.

**Comment by pippinsplugins** [comment]
Love it! We'll get this in really soon.

**Comment by sunnyratilal** [comment]
PR opened at #5908

**Comment by SDavisMedia** [comment]
This is working well for me. Very nice. :+1:

**Comment by DevinWalker** [comment]
Nice guys. Glad to see this making it in.

**Comment by cklosowski** [comment]
Found an issue with this. If Stripe is your only gateway, or it's your default gateway, the JS never gets loaded to run the formatter.

It appears it's due to `edd_gateway_loaded` not getting triggered in the `edd-ajax.js`.

I'll see if I can fix it up.

**Comment by cklosowski** [comment]
Fixed.
