### ISSUE TITLE
EDD_Payments_Query "downloads" filter skips renewal payments. 

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#5377]
If you want to query payments based on the download(s) purchased, you would do something like this

```
$args = array(
	'download' => array( DOWNLOAD_ID_HERE, ANOTHER_DOWNLOAD_ID_HERE ),
	'number'   => -1,
);
$query    = new EDD_Payments_Query( $args );
$payments = $query->get_payments();
```

However, because the query uses "[post_parent](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/payments/class-payments-query.php#L521)" and  "[post_parent__in](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/payments/class-payments-query.php#L534)", payments that share the same post parent are not returned (For example, renewal payments from EDD Recurring).

In order to make those renewal payments get returned as well, we would have to use "post__in" instead of "post_parent" and "post_parent__in" (see above links).

This section could then be removed as well:
```
if ( is_array( $this->args['download'] ) ) {
	unset( $args['post_parent'] );
	$args['post__in'] = $this->args['download'];
}
```

**Question:**
Is the current way expected? That is, is it expected that EDD_Payments_Query::downloads only gets the subscription's original payment? Personally I would expect all matching payments to be returned whether they are renewal payments or original payments.

**Comment by pippinsplugins** [comment]
I don't think this is expected.

**Comment by sunnyratilal** [comment]
@mintplugins @pippinsplugins PR opened at #5590 and ready for testing

**Comment by pippinsplugins** [comment]
@sunnyratilal we use `post__in` for handling payment searches. The PR looks good but I think we should account for cases where two separate `post__in` fields need to be merged.

**Comment by pippinsplugins** [comment]
This PR does break the download search functionality in payments so it's not ready to go.

**Comment by pippinsplugins** [comment]
Using `post__in` for the logs query won't work as that parameter would need the post IDs of the log entries, not of the products the logs are related to.

Going to punt out of 2.7.6 for further consideration.

**Comment by chriscct7** [comment]
Related: #5680

**Comment by sunnyratilal** [comment]
This issue may not require a PR as `EDD_Payments_Query` has been significantly refactored as per #4576 which may have fixed the issue here.

**Comment by sunnyratilal** [comment]
Fixed.
