### ISSUE TITLE
EDD_Payments_Query "downloads" returns all payments when it should return none. 

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#5378]
Using the EDD_Payments_Query::downloads method, if your query does not match any results, all payments are returned. 

For example: 

```
$args = array(
	'download' => array( **DOWNLOAD_ID_THAT_DOES_NOT_EXIST** ),
	'number'   => -1,
);
$query    = new EDD_Payments_Query( $args );
$payments = $query->get_payments();
```

The above code will return all payments. I believe this is incorrect as I expect it should behave the same way a standard WP_Query works and return none.

**Comment by sunnyratilal** [comment]
This has been automatically fixed in #4576 as I had to refactor `EDD_Payments_Query` to work with the new query methods and the new tables.
