### ISSUE TITLE
[Filter request] edd_download_inner_class

### ISSUE THREAD

**Issue by rubengc** [easydigitaldownloads/easy-digital-downloads#5386]
Much themes for EDD uses bootstrap and manages `[downloads]` columns adding `.row` to `edd_downloads_list_wrapper_class` filter and desired columns sizes on `edd_download_class` filter

After adding this classes your downloads will get a padding (from bootstrap col-* styles), so you will apply styles to the `edd_download_inner` class

Adding a filter to this class will let us add third party helper classes (like ones coming from animate.css)

This is the code in question at [shortcodes.php L:585](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/shortcodes.php#L585):
```php
<div class="<?php echo apply_filters( 'edd_download_inner_class', 'edd_download_inner', get_the_ID(), $atts, $i ); ?>">
```

If this issue is approved, I have a PR ready to submit

**Comment by pippinsplugins** [comment]
Milestoned for 2.7.5.

**Comment by pippinsplugins** [comment]
Merged!
