### ISSUE TITLE
Adjust error message when discount is not active yet

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#5387]
Here's the current error shown when trying use a discount code that is not yet active:

<img width="754" alt="screenshot 2017-01-16 13 06 24" src="https://cloud.githubusercontent.com/assets/2359131/21999007/bcea5638-dbec-11e6-8894-7b6a67b7af38.png">

I think that's too much information for customers _and_ would probably cause them to freeze and abandon the purchase. Slightly changing that to the basic `This discount is invalid.` may not be that much better but at least it won't encourage waiting until a future date to purchase.

**Comment by sunnyratilal** [comment]
Ready to merge once unit tests pass

**Comment by sunnyratilal** [comment]
Merged into `release/2.7`.

Thanks @SDavisMedia 👍
