### ISSUE TITLE
Recount Stats

### ISSUE THREAD

**Issue by PEYMANTBT** [easydigitaldownloads/easy-digital-downloads#5391]
my Recount Stats not work any.
i whant Deletes all payment records, customers, and related log entries
please help me.

Version:                  4.7.1
Version:                  2.6.17

**Comment by pippinsplugins** [comment]
Hi there!

Please go ahead and open a support ticket through our support portal: https://easydigitaldownloads.com/support

we use GitHub for development tracking only.
