### ISSUE TITLE
Adjust UI for discount start date and expiration date time picker

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#5392]
When creating a discount, you have the option to set a Start Date and an Expiration Date. Both fields use a date picker, which appears when you click into the field. Once you make your date selection, the data turns to text similar to this for both the Start Date and the Expiration:

`01/16/2017`

When you save the discount, you will be redirected to the discounts table (not sure I like that, I see nothing wrong with staying on the edited discount screen). Click to Edit that same discount you just created. Now the text in the field is formatted like so:

Start Date - `01/16/2017 00:00:00`
Expiration Date - `01/17/2017 23:59:59`

Here are the bugs:

- [ ] until we get a TIME picker implemented, the text the time should show right after the date is selected... not after going back in to edit the discount
- [ ] the Expiration Date time text will not save as any other value than `23:59:59` (which I've been told is intentional... meaning the UI is misleading)

--

Unless we go all the way now and get a Date Picker and Time Picker full UI implemented, we at least need to:

1. show the time text as soon as the date is picked
2. do not show time text for the Expiration Date field

**Comment by ashleyfae** [comment]
Closing as EDD 3.0 allows you to set the time, so this is no longer an issue:

![Screenshot from 2021-05-20 12-54-16](https://user-images.githubusercontent.com/6324272/118976657-29469f00-b96d-11eb-829a-209cb7d65503.png)
