### ISSUE TITLE
Set Price Assignment default when uploading product files

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#5394]
When you enable variable pricing, a Price Assignment column appears in the Download Files metabox so that you can upload product files and optionally set them specific pricing options. Though you haven't uploaded a product file yet, the default Price Assignment for that first file is set to `All` for you:

<img width="1028" alt="screenshot 2017-01-16 16 39 52" src="https://cloud.githubusercontent.com/assets/2359131/22003703/885e313c-dc0a-11e6-894c-73267056e35f.png">

All good.

When you add another row, no default value is set for its price assignment:

<img width="1032" alt="screenshot 2017-01-16 16 41 40" src="https://cloud.githubusercontent.com/assets/2359131/22003719/acd7aeee-dc0a-11e6-8893-c1fe9588364e.png">

Once you you upload that second product file, if you do not manually set the Price Assignment value to whatever you want it to be before you save the product, purchasing that product results in that file not being delivered to the customer.

Let's force the Price Assignment default to `All`.

**Comment by chriscct7** [comment]
This has a related ticket on the recurring payments extension. The same
thing happens for it's row values

**Comment by SDavisMedia** [comment]
@chriscct7 Yup, 567 on Recurring's repo.

**Comment by SDavisMedia** [comment]
Tried but I can't replicate this anymore. Pretty sure it was addressed in https://github.com/easydigitaldownloads/easy-digital-downloads/issues/2704

If you agree with me, let's close it!
