### ISSUE TITLE
Software Licensing: Bundle download not generating license keys for bundled products

### ISSUE THREAD

**Issue by mngarwood** [easydigitaldownloads/easy-digital-downloads#5401]
(Sorry if this needs to be filed in another repo...I couldn't find one for the Software Licensing extension)

Running v 3.5.1 of the Software Licensing extension on WordPress 4.7.1

Before the 3.5 update of Software Licensing, I had our EDD store bundle downloads configured like [option #2 of the setup guide](http://docs.easydigitaldownloads.com/article/698-bundle-licensing). We had "enable license creation" checked for each of the bundled products, but _not_ for the bundle listing itself. This was correctly generating keys only for the bundled products. Since we updated to 3.5 (and now 3.5.1), I've had to re-enable the license generation option for the bundle in order to get the bundled products' keys to generate. If I leave that option unchecked on the bundle listing, EDD will no longer generate the bundled products' keys. Even when I attempt to manually generate the keys, the key generator tells me that none need to be created.

**Comment by pippinsplugins** [comment]
@mngarwood We identified this issue and resolved in Software Licensing 3.5.4. Cheers!
