### ISSUE TITLE
Remove "Settings" Suffix in Settings Subsection Titles

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/easy-digital-downloads#5404]
https://cloudup.com/cwqU_UZPSgC

We already know we are in the Settings section. And it's inconsistent across tabs. I think "Misc" should be "Misc." with a period as well.

**Comment by spencerfinnell** [comment]
This PR removes extraneous "Settings" suffixes on subpanel labels, and removes section titles on pages that only have one section to avoid duplicate (and usually inconsistent) titles.

**Comment by sunnyratilal** [comment]
Merged
