### ISSUE TITLE
Product erroneously removed from payment record after removing different product

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#5405]
Tricky, I know. Do this:

1. Go to the order details screen for a payment record
2. Add a product to the payment record with whatever price you want and click the `Add Download to Payment` button (but don't save the payment)
3. Now click the Remove link for the product you added in step 2 (but don't save the payment)
4. Now add another new product to the payment and click the `Add Download to Payment` button... make sure _something_ about it is different from the one you added in step 2 just so you remember them both
5. observe all the products on the payment so you know what's there
6. Save the payment. The product just above the one you added should have disappeared.

Note: step 3 is important. Without it, you cannot replicate. That should probably hint at the solution as well.

**Comment by pippinsplugins** [comment]
Bug confirmed!

**Comment by pippinsplugins** [comment]
Looks like we possibly have some array keys mixed up.

The key on a newly added product is `2` (as it should be) but the `data-key` attribute for the remove link is `0`.

<img width="873" alt="screen shot 2017-03-06 at 9 26 11 am" src="https://cloud.githubusercontent.com/assets/1034109/23616328/0c187234-024f-11e7-8227-ee45fd8e8a22.png">
<img width="1147" alt="screen shot 2017-03-06 at 9 25 59 am" src="https://cloud.githubusercontent.com/assets/1034109/23616327/0c1774f6-024f-11e7-991d-5db7640bcdc1.png">

**Comment by pippinsplugins** [comment]
PR ready to go.

**Comment by SDavisMedia** [comment]
@pippinsplugins I'm still getting the same exact behavior following the steps I outlined above.

**Comment by SDavisMedia** [comment]
It was a cache issue on my end. Everything's good for me on `issue/5405`. :+1:

**Comment by pippinsplugins** [comment]
Good deal!
