### ISSUE TITLE
REST API - file-download-logs endpoint shows invalid customer

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#5406]
When using the the `file-download-logs` endpoint I am getting this error:

```
Notice: Undefined variable: invalid_customer in /Users/philjohnston/Documents/wps/edd2.dev/wp-content/plugins/easy-digital-downloads/includes/api/class-edd-api.php on line 1680
```

This is the URL:
http://edd2.dev/sl/edd-api/file-download-logs/?key=KEYHERE&token=TOKENHERE

**Comment by pippinsplugins** [comment]
PR looks good at first glance.

@mintplugins please test and confirm.

**Comment by mintplugins** [comment]
Confirmed fixed! 👍
