### ISSUE TITLE
Old edd_submit class usages found

### ISSUE THREAD

**Issue by rubengc** [easydigitaldownloads/easy-digital-downloads#5409]
Concretely on profile editor and login templates

**Comment by pippinsplugins** [comment]
I don't think we should remove the old class in case anyone has styled it. Let's do go ahead and add the new standardized class though.

**Comment by rubengc** [comment]
You are right, should I add a comment pointing edd_submit is deprecated and will be removed?

**Comment by rubengc** [comment]
I updated the PR
