### ISSUE TITLE
Software Licenses - Error when reading cached version info

### ISSUE THREAD

**Issue by yoancutillas** [easydigitaldownloads/easy-digital-downloads#5413]
Hello,

Go to Dashboard / Updates and click twice on **"View version x.x.x details"** of one of the extensions managed by Software Licensing which needs to be updated (the first load works well because you don't read the cached version). You will get that error: 

> **Cannot use object of type stdClass as array in ...wp-admin\includes\plugin-install.php on line 500**

A quick fix is to add on line 276 of EDD_SL_Plugin_Updater.php

`$edd_api_request_transient->sections = (array) $edd_api_request_transient->sections;
$edd_api_request_transient->banners = (array) $edd_api_request_transient->banners;`

Best :)

___
Using 
WP 4.7.1
Easy Digital Downloads - Software Licensing 3.5.3
EDD_SL_Plugin_Updater.php 1.6.9
EDD 2.6.17

**Comment by pippinsplugins** [comment]
Thanks for the heads up!

We have a private repo for Software LIcensing so I have added this bug to our issue tracker there. I'm closing this one to keep the dev tracking there.
