### ISSUE TITLE
Item card views size improperly

### ISSUE THREAD

**Issue by ghost1227** [easydigitaldownloads/easy-digital-downloads#5414]
As mentioned by Pippin [here](https://github.com/easydigitaldownloads/EDD-Commissions/issues/148#issuecomment-275167120), card views don't maintain column size when edit links are clicked (or any data change occurs). Rather than adding the necessary CSS to each product, I believe it should be added globally through EDD core since it's the same ID and classes in each product.

**Comment by ghost1227** [comment]
@pippinsplugins think we can squeeze this one in?

**Comment by pippinsplugins** [comment]
I'm good with this if @SDavisMedia is.

**Comment by SDavisMedia** [comment]
@ghost1227 @pippinsplugins yup I'm good. Appears to hold up fine with license and subscription views as well. Doesn't apply to customer cards so they're good. Also looks like it'll be future-proof for anything else that adopts this structure. :+1:
