### ISSUE TITLE
Disable Redownload? setting does not remove links from purchase confirmation

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#5424]
Ticket: https://secure.helpscout.net/conversation/310900487/0/?folderId=180499

I was able to replicate. It will remove the link from `[download_history]` but the links are still present on the purchase confirmation. Not sure if it broke or if that is a long-time oversight.

No matter where product links are displayed, if they have already been used once, they should be removed.

**Comment by pippinsplugins** [comment]
Ok this is ready for testing!

Note for when `Re-download` is disabled: Download links should _always_ show when viewing the purchase confirmation page and the purchase session data is still present. Once the purchase session expires, the download links should no longer show.

**Comment by SDavisMedia** [comment]
I believe I did everything I could to force end a purchase session but the link is still showing up on the purchase receipt. So either the purchase session has not actually ended (though I manually cleared cookies) or I can't confirm this is working just yet.

**Comment by pippinsplugins** [comment]
@SDavisMedia do download links show up for past purchases (ones made more than 24 hours in the past)?

**Comment by SDavisMedia** [comment]
@pippinsplugins I had to go check from another computer's local dev since I don't have the transactions necessary to check on this one.

It _seems_ that this is working properly as long as I don't load up the purchase receipt before before enabling the Disable Redownload setting. If I view that purchase receipt before checking that setting, even if the file has been downloaded already, the link won't go away once the setting is enabled. But then when I view other/older receipts that I believe should show the link, the link is not there.

So I think that's an indication that it's working. If you agree, then it's all good on my end. :+1:

**Comment by pippinsplugins** [comment]
I think that indicates it's working properly. Let's get one more test from @mintplugins, @brashrebel , or @cklosowski.

**Comment by brashrebel** [comment]
Just tested. Works great. Checked out `issue/5424` and tried with the `[edd_receipt]` shortcode both with the disable redownload setting on and off. Works great on this branch and does indeed fail to remove the links on master.

**Comment by pippinsplugins** [comment]
Merging.
