### ISSUE TITLE
Banned emails tld blocking

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#5440]
Having the ability to block troublesome tlds (such as ones associated with spam and fraud) would in some instances be a lot more useful than blocking domains and emails.

**Comment by davidsherlock** [comment]
the ltds could each be on a new row with a .tld style. Multi-part tlds like .co.uk and alike would need to be taken into account also.

**Comment by pippinsplugins** [comment]
This is a nice idea. I like it.

**Comment by JeroenSormani** [comment]
Created a PR for this here: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5440

**Comment by pippinsplugins** [comment]
This works  great for me. Once the unit tests pass, I'll merge it in.

**Comment by SDavisMedia** [comment]
It's working but should something like `.co` block `.co.uk` as well? It's not at the moment. If that's intentional, everything's good on my end.

**Comment by pippinsplugins** [comment]
No I don't think it should since those are technically two different TLDs
