### ISSUE TITLE
EDD()->html->select doesn't support 0 as selected key

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#5443]
We have a few lines where `selected` could be `0` but will result in a non-expected behavior

```
if ( ! isset( $args['selected'] ) || empty( $args['selected'] ) || ! $args['selected'] ) {
	$selected = "";
}
```

And:
```
if ( $args['multiple'] ) {
	$selected = selected( true, in_array( -1, $args['selected'] ), false );
} elseif ( isset( $args['selected'] ) && ! empty( $args['selected'] ) && ! is_array( $args['selected'] ) ) {
	$selected = selected( $args['selected'], -1, false );
}
```

We shouldn't be looking at `empty` here only, so that keys of `0` can be passed as selected.

**Comment by sunnyratilal** [comment]
@cklosowski Ready for testing

**Comment by sunnyratilal** [comment]
To test, if we want to create an `select` element which has an `<option value="0">` and the argument to the function has `selected` set to `0`.

**Comment by sunnyratilal** [comment]
Merged
