### ISSUE TITLE
Impossible to import media from same domain unless already in media library

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/easy-digital-downloads#5447]
The issue is in the code here:
```
private function set_image( $download_id = 0, $image = '', $post_author = 0 ) {

        $is_url   = false !== filter_var( $image, FILTER_VALIDATE_URL );
        $is_local = $is_url && false !== strpos( $image, site_url() );
        $ext      = edd_get_file_extension( $image );

        if( $is_url && $is_local ) {

            // Image given by URL, see if we have an attachment already
            $attachment_id = attachment_url_to_postid( $image );
```
Found here: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/admin/import/class-batch-import-downloads.php#L345

If you put images in a different directory on your server like, say, the root and try to import with the URL in your CSV set to `http://currentsite.com/my-image.jpg` it will not import the image. This is because `$is_local` is `true` and so it only attempts to get the attachment ID from the URL. So there's no way to import a file from the same domain unless it exists in the media library already.

**Comment by pippinsplugins** [comment]
We've had at least two tickets on this. Let's get this addressed in 2.7 please.

@sunnyratilal could you do a quick PR for this?

**Comment by sunnyratilal** [comment]
Had a look at this and the behaviour I'm seeing is the file being assigned correctly to the download.

However, is the expected result, the file ending up in the media library and in the `uploads/edd` directory?

**Comment by sunnyratilal** [comment]
The file I'm importing is set to point to `http://edd.dev/2.jpg`

![image](https://cloud.githubusercontent.com/assets/1525554/22762114/a6f1426c-ee55-11e6-87ac-4c43892e1155.png)

And that's what happens when importing.  Is this incorrect behaviour?

**Comment by pippinsplugins** [comment]
@sunnyratilal The bug mentioned here is specific to the Featured Image.

**Comment by sunnyratilal** [comment]
Simple fix - the `needle` and `haystack` were passed the opposite way around in `strpos` which caused the error.

**Comment by sunnyratilal** [comment]
@brashrebel @pippinsplugins PR opened at #5451.

**Comment by sunnyratilal** [comment]
To test:

1. Have an image file at your document root (e.g. if your host is `http://edd.dev/` place a file in the root such that the URL becomes `http://edd.dev/filename.jpg`
2. Import a CSV of a download post with the featured image set as `http://edd.dev/filename.jpg`
3. Check the download created and the featured image should display as expected

**Comment by pippinsplugins** [comment]
Looks good here! Merged.
