### ISSUE TITLE
Introduce class `EDD_Customers_Query`

### ISSUE THREAD

**Issue by felixarntz** [easydigitaldownloads/easy-digital-downloads#5448]
Queries against the customers table are currently run in singular methods of the `EDD_DB_Customers` class. A dedicated query class like WordPress core's ones (for things like posts, comments,...) could improve the performance, extendability and possibilities to query without bloating the `EDD_DB_Customers` class itself. The `get_customers()` method and several other methods of the class could then become wrappers for making a query through an instance of `EDD_Customers_Query`. The new class would also bring enhanced caching for all queries (I was just wondering why https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/class-edd-db-customers.php#L510 is in there --> were there issues with caching?).

I would suggest building the class after one of the more recent core classes, like `WP_Comment_Query` or `WP_Site_Query`. I'd be happy to work on it in a PR if this idea gets positive feedback.

**Comment by pippinsplugins** [comment]
I _love_ this idea.

**Comment by felixarntz** [comment]
Great! I'll start working on it this weekend or early next week.

**Comment by pippinsplugins** [comment]
@felixarntz I've milestoned this for 2.8. We'll do some testing and see about getting it in. Thanks!

**Comment by SDavisMedia** [comment]
Everything I'm checking seems to be good on `issue./5448`. Can't find any breaking output or functionality. :+1:

**Comment by sunnyratilal** [comment]
Working well and as expected 👍

**Comment by sunnyratilal** [comment]
Merged into `release/2.8`
