### ISSUE TITLE
Custom "Complete Purchase Text" button text changes if payment submission results in error

### ISSUE THREAD

**Issue by evanluzi** [easydigitaldownloads/easy-digital-downloads#5449]
When submitting a payment on the checkout page that's missing information (and results in error), the custom button text ("Complete Purchase Text") defined in Downloads > Settings > Misc > Button Text is overwritten.

See attached screenshot for phrase defined in settings:
![screen shot 2017-02-08 at 3 24 52 pm](https://cloud.githubusercontent.com/assets/5759355/22755873/114f14c4-ee13-11e6-86b1-787162bf7327.png)

See video of the issue here: https://www.dropbox.com/sc/czzmdoef8zent9g/AAAYhKRQrLHaRbdoWYeGY6Q9a

**Comment by evanluzi** [comment]
I noticed this on my local dev site, but I can replicate it on my live site as well: **https://www.theblackandblue.com/checkout/?edd_action=add_to_cart&download_id=10819**

Both running WP 4.7.2 and EDD 2.6.17

**Comment by pippinsplugins** [comment]
I noticed this not too long ago. It shouldn't be too hard to resolve :+1:

**Comment by ghost1227** [comment]
Tested this and wasn't able to replicate. @pippinsplugins can you tell me what caused you to notice? Specific settings? Anything?

**Comment by ghost1227** [comment]
@SDavisMedia pinging you on this as requested!

**Comment by pippinsplugins** [comment]
@ghost1227 Set the custom text, go to checkout, submit checkout without all fields set. After the errors are shown the custom text reverts to just `Purchase`,.

**Comment by SDavisMedia** [comment]
@ghost1227 I replicated but I had to do it with Stripe. Doesn't seem to replicate if you leave a Personal Info field empty.

Choose Stripe as your gateway and then don't fill out any CC fields. Submit the form and it should replicate.

**Comment by ghost1227** [comment]
@SDavisMedia That helps! Thanks

**Comment by ghost1227** [comment]
I still can't replicate it. I've tested every error I can think of using Stripe (no personal info, no billing info, no cc info, and various combinations of missing/included data), always results in either the inline missing field notification or the notification displayed below, always with the correct custom button displayed.

<img width="805" alt="screen shot 2017-03-13 at 3 51 16 pm" src="https://cloud.githubusercontent.com/assets/36433/23874797/ede50730-0804-11e7-8486-1451613b1d66.png">

**Comment by pippinsplugins** [comment]
@SDavisMedia able to give exact replication steps?

**Comment by SDavisMedia** [comment]
@pippinsplugins @ghost1227 What I posted above is all I have. It was really easy to replicate.

Stripe as the selected gateway (no Stripe Checkout), submitted the form without touching any of the Credit Card Info fields. Here are my settings: https://cl.ly/1W1B1v1U1Y0O

**Comment by ghost1227** [comment]
Tested again, still can't replicate

**Comment by pippinsplugins** [comment]
@SDavisMedia @ghost1227 please get together in slack and video chat if need be to cover the disconnect here.

**Comment by ghost1227** [comment]
@pippinsplugins Traced it back to this: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/scripts.php#L65

Not 100% sure what causes it to sometimes work and sometimes fail (for me at least), but that's definitely the line causing it. We need to adjust that to honor custom settings.

**Comment by ghost1227** [comment]
@SDavisMedia and... GO!

**Comment by SDavisMedia** [comment]
`issue/5449` fixes it for me. :+1:

**Comment by pippinsplugins** [comment]
Looks good, merged!
