### ISSUE TITLE
edd_check_file_url_head() causes many false positives

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#5450]
Since introducing `edd_check_file_url_head()` for #5268 and then updated with #5308, we have seen a _lot_ of tickets reporting Forbidden errors and other 400/500 errors when attempting to download files.

Using the Redirect download method typically resolves the issue.

Sadly we do not know exactly _why_ this is happening but it appears to be certainly related to `edd_check_file_url_head()`.

I propose we remove the check until such time as we can really track down the issues within it.

**Comment by pippinsplugins** [comment]
Exhibit A: we had three tickets about it today alone.

**Comment by sunnyratilal** [comment]
Albeit we're receiving an incorrect error code from the function, it doesn't make sense in terms of logic.

We're using `wp_remote_head()` which sends a `HEAD` request to the file.  A `HEAD` request is the same as a `GET` except the server doesn't return the body (even if `Content-Length` > 0, just the headers.

If `HEAD` is failing here, `GET` _should_ be failing too.

**Comment by sunnyratilal** [comment]
Nevertheless, if we want to proceed with removing, a PR has been opened.

**Comment by pippinsplugins** [comment]
@sunnyratilal let's just comment out the add_filter for now. I'd like to bring it back once we track down the irregularities so let's leave the function in.

**Comment by sunnyratilal** [comment]
Merged
