### ISSUE TITLE
Introduce a wp_schedule_single_event for when a payment is marked as completed

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#5453]
There are many actions that get run on marking a payment as complete. Most of these are critical to the process, but some aren't critical to the purchase at all and just cause the checkout to take longer to process than it needs to. Some instances of `non-critical`

- Sending pushover notifications for payments.
- Sending pushover notifications for commissions.
- Sending commissions emails.

These types of actions are ones that don't affect data or earnings or anything they are just used for 'notification' type setups.

This would allow us to schedule a `wp_schedule_single_event` for the payment ID to happen maybe 30 seconds to a minute later (even further if needed), and they are triggered via `WP_Cron` which means they don't affect the page load of a customer directly, which would allow our checkout to run faster.

First step is implementing the events, and the next would be updating necessary extensions (and any core functions we can think of that could benefit from this) to do it.

The 'cons' of it are that in some hosting environments WP_Cron isn't always persistent...but like I said, these are not to be used for mission critical events...just things that are 'nice to have'.

**Comment by SDavisMedia** [comment]
I think that's a sweet idea if it speeds up the more important parts of the process and reduces the chances of an issue. As of now, I'm all for it.

**Comment by pippinsplugins** [comment]
Let's do it.

The key here is limiting it to non-critical events, as @cklosowski outlined. :+1:

**Comment by cklosowski** [comment]
Yes, very much so.

As I mentioned, I can't think of many cases where something in EDD core should need to delay, but there are plenty of extensions where it could be beneficial.

**Comment by cklosowski** [comment]
First draft of this is ready to play with. No plugins are using it yet but it is logging a payment note and a meta item so we know if it's already been run.

One of these will likely leave for the final product, but it's easier to see during testing/development.

Next step is getting an extension to use this. I'll start with:
- [ ] Pushover Notifications
- [ ] Commissions Emails

This way it'll be really easy to test as these are easy tests to setup.

**Comment by spencerfinnell** [comment]
WooCommerce had issues with this in 3.0. They've since switched to using their background processing library which only falls back on crons for health checks. 

https://github.com/woocommerce/woocommerce/pull/14344
https://github.com/woocommerce/woocommerce/pull/14035

I wouldn't rely on it for anything that is required; even if it's not critical.

**Comment by cklosowski** [comment]
Yeah. The goal is notification type stuff. Nothing that is a dependency of
business.

**Comment by SDavisMedia** [comment]
@cklosowski What else is even happening when a payment is marked as complete besides send the email receipt?

I can't find anything else. That email is still sending properly on `issue/5453`. So unless I'm missing something, that's all the testing needed here for core functionality specifically.

**Comment by cklosowski** [comment]
@SDavisMedia the goal here is for Core to not change a thing, just log when it's run, so if you're seeing the payment note and the post meta key then it's doing it's job.

This is really just an enhancement that will exist for extensions to use, fundamentally.

**Comment by SDavisMedia** [comment]
Yea everything's good for core functionality. :+1:

**Comment by pippinsplugins** [comment]
I'm happy with this, merging.

**Comment by cklosowski** [comment]
Was just thinking, we should be able to detect the following constant as well:
`define('DISABLE_WP_CRON', 'true');`

If we detect that, we should assume no cron and fallback to using immediate actions.

**Comment by pippinsplugins** [comment]
Good catch!

**Comment by KingYes** [comment]
Hey @pippinsplugins & @cklosowski 

We using with `DISABLE_WP_CRON` constant to handle my Cron by wp-cli. How I get this ability with this?

**Comment by pippinsplugins** [comment]
We have removed the check for DISABLE_WP_CRON so your after-payment actions should still fire even if DISABLE_WP_CRON is set to true.

**Comment by KingYes** [comment]
@pippinsplugins It's fire? yes.. But I want to fire this from my wp-cli (cron). Is still we be?

**Comment by cklosowski** [comment]
@KingYes as long as your WP-CLI is running the WP_CRON it will fire.

**Comment by KingYes** [comment]
But I see this code: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/31a14d183f2ea35158064889ab86bdfeb3b05d47/includes/payments/actions.php#L136

It's run the events immediately.. And I want to delay this..

Just for reference (WP-Cli + WP_Cron): https://pressjitsu.com/blog/wordpress-cron-cli/

**Comment by cklosowski** [comment]
The hash you referenced is an old commit:
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/2.8/includes/payments/actions.php#L135
