### ISSUE TITLE
License Handler $item_id usage causes issues.

### ISSUE THREAD

**Issue by danieliser** [easydigitaldownloads/easy-digital-downloads#5454]
If you pass the download ID rather than the name then the shortnames will break and as such all saved options as well.

This also causes empty top label on the extend page in the dashboard.

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/class-edd-license-handler.php#L43-L49

As you can see if its numeric then $item_name never gets set, which means all usage of $item_shortname will get an invalid result.

**Comment by pippinsplugins** [comment]
@danieliser we found this recently too. Please see https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5232
