### ISSUE TITLE
Rewrite readme.txt file

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#5456]
Our readme.txt file has barely changed in several years. I would like to take a good, hard look at where we can improve it to help better market Easy Digital Downloads on WordPress.org.

**Comment by sumobi** [comment]
@pippinsplugins:

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/readme.txt#L24

`and new translation are being added` > `and new translations are being added`

**Comment by sumobi** [comment]
`Payment gateways supported through free or premium extension:` > `Payment gateways supported through free or premium extensions:` (missing s)

**Comment by sumobi** [comment]
There's inconsistency in the `FAQ` headings. Most are sentence-case, but the following are not:

`My Payments Marked as Pending` - Grammar is also slightly off. Should be something like `My payments are being marked as "pending"`

`How do I Show the User’s Purchase History?` - `How do I show the user’s purchase history?`

`Can I Setup an Affiliate System?` - `Can I set up an affiliate system?`

**Comment by pippinsplugins** [comment]
Fixed https://github.com/easydigitaldownloads/easy-digital-downloads/pull/5703
