### ISSUE TITLE
Customer name can be empty...making an odd output

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#5461]
It was discovered that you can crate a customer with an empty name, but this presents a unique situation where things look like they don't have a customer association b/c the name is empty, when it actually does have a customer attached.

We need a proper fallbakc.

**Comment by pippinsplugins** [comment]
<img width="1277" alt="screen shot 2017-11-09 at 2 58 08 pm" src="https://user-images.githubusercontent.com/1034109/32631756-6d7f9430-c55e-11e7-8e37-e4154d774996.png">

This mainly needs to be fixed on the payment history screen.

**Comment by pippinsplugins** [comment]
It's also a problem on sales logs:
<img width="1268" alt="screen shot 2017-11-09 at 3 01 40 pm" src="https://user-images.githubusercontent.com/1034109/32631913-ee079210-c55e-11e7-87f4-7b4e056197ba.png">

**Comment by sunnyratilal** [comment]
PR: #6247

**Comment by sunnyratilal** [comment]
This has been solved by following the same display as that on the Customers list table.  If a customer doesn't have a name, it displays the customer ID followed by `Unnamed Customer`.

**Comment by nosegraze** [comment]
This is working well for me. 👍

**Comment by nosegraze** [comment]
Just a thought:

In https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5848 the customer name is _always_ prefixed with the ID number, whether there's a name or not. In this PR the ID is only there if there is no customer name. Perhaps we should always include the ID number at the start for consistency?

**Comment by cklosowski** [comment]
I like that suggestion @nosegraze, If we're going to show the ID number let's always show it. Otherwise it'll look inconsistent.

**Comment by pippinsplugins** [comment]
@nosegraze please go ahead and commit that change then we can merge this in.

**Comment by nosegraze** [comment]
Updated!
