### ISSUE TITLE
Checkout showing wrong total price when certain fees in cart

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#5463]
Only able to replicate in two scenarios:

- Recurring product in the cart with a sign up fee:

<img width="819" alt="screenshot 2017-02-13 20 09 24" src="https://cloud.githubusercontent.com/assets/2359131/22915366/a005ec12-f22b-11e6-955a-763df1d937bf.png">

- EDD Wallet deposit

<img width="763" alt="screenshot 2017-02-13 20 33 25" src="https://cloud.githubusercontent.com/assets/2359131/22915390/af0b0da0-f22b-11e6-84a1-32359a5f1a07.png">

-----

The total price is incorrect in the checkout cart and the output above the complete purchase button.

**Comment by SDavisMedia** [comment]
@pippinsplugins Fixed for me on `issue/5463`. Both the Recurring and EDD Wallet carts display properly now. Data after the purchase looks as it should. 👍

**Comment by pippinsplugins** [comment]
:+1:

**Comment by sunnyratilal** [comment]
Tested and working well here

**Comment by pippinsplugins** [comment]
Re-opening @sunnyratilal. Unit tests failed.

**Comment by cklosowski** [comment]
@sunnyratilal @pippinsplugins ready for some lookover., PR has submitted

**Comment by cklosowski** [comment]
@SDavisMedia can you re-run your test please?

**Comment by SDavisMedia** [comment]
Everything's still looking good here for me. Tested both Recurring and Wallet and also checked the data over on Stripe. :+1:

**Comment by cklosowski** [comment]
Sweet. Thanks!

**Comment by cklosowski** [comment]
Merging, closing, and releasing.
