### ISSUE TITLE
edd_register_batch_exporters may fire before includes in extensions

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#5465]
The EDD hook which sets up batch exporters fires upon plugins_loaded. However, if an extension also includes extension-integration scripts upon plugins_loaded, if the integration has a batch exporter, it won't be included before edd_register_batch_exporters is fired. Thus it won't get registered and causes a tough-to-track 500 error in the ajax call while doing a batch export. 

To fix this, I propose setting the priority of this hook to 99:

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/admin/reporting/export/export-actions.php#L80

**Comment by pippinsplugins** [comment]
We could lower the priority of `edd_register_batch_exporters` so it fires earlier on `plugins_loaded`.

**Comment by mintplugins** [comment]
That's an even better idea 👍

**Comment by mintplugins** [comment]
Actually on second though, I don't think that would work. 

We need edd_register_batch_exporters to fire later as opposed to earlier.

**Comment by ghost1227** [comment]
Derp. Commented on the PR instead of the issue. @pippinsplugins His method works well in my tests.

**Comment by pippinsplugins** [comment]
This breaks the `EDD_Batch_Sales_Export` export option/

**Comment by pippinsplugins** [comment]
Nevermind, it was already broken on `master`.

**Comment by ghost1227** [comment]
99 little bugs in the code, 99 little bugs...
