### ISSUE TITLE
checkout - email address

### ISSUE THREAD

**Issue by colomet** [easydigitaldownloads/easy-digital-downloads#5467]
![captura de pantalla 2017-02-14 a las 18 26 03](https://cloud.githubusercontent.com/assets/3929177/22940696/2ad24932-f2e3-11e6-93b6-07e73daf800f.png)

If once I whant to pay/download one item I have to be log-in, and i can not write the email of other user, why I have the option to write an email? why if I have to be log-in I have to write my personal information?

**Comment by colomet** [comment]
I believe the current Checkout page is too complicate. 

thanks

**Comment by pippinsplugins** [comment]
Hi there!

Please go ahead and open a support ticket through our support portal: https://easydigitaldownloads.com/support

We use GitHub for development tracking only.
