### ISSUE TITLE
"Add New" admin page body links to http://docs.easydigitaldownloads.com/article/229-purchaselink

### ISSUE THREAD

**Issue by mavej** [easydigitaldownloads/easy-digital-downloads#5471]
![edd-bug](https://cloud.githubusercontent.com/assets/25431977/22969663/9db45238-f36f-11e6-9934-4d2a2b872a94.png)
Hi, I've got this serious problem:
Any time I click to a form field or anywhere else on Add New page, I'm redirected to this page:
http://docs.easydigitaldownloads.com/article/229-purchaselink
I'm using EDD 2.7.1, WP 4.7.2
Thank you
Martin

**Comment by sunnyratilal** [comment]
This repository is used for the development of Easy Digital Downloads. Please open a ticket here and our support team will be able to assist you: https://easydigitaldownloads.com/support/
