### ISSUE TITLE
File download URLs blank for recovered purchases

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#5472]
In some cases, when a bundle has variable prices, the file download links delivered in the purchase receipt are blank.

Correction: file download URLs do not show up when a purchase is recovered. This happens because the payment key isn't getting reset properly, resulting in two different payment keys on the purchase, which then causes `edd_get_payment_by( 'key', $params['download_key'] )` to fail inside of `edd_get_download_file_url()`.

**Comment by pippinsplugins** [comment]
Might require that the items inside of the bundle have variable prices as well.

We've seen at least 2-3 reports of this so far since 2.7 was pushed.

Introduced by changes in #2612

**Comment by pippinsplugins** [comment]
Bug is actually introduced by #5351, not #2612

**Comment by pippinsplugins** [comment]
To replicate the original  bug:

1. Checkout `master`
2. Add item to cart, go to checkout, and submit payment to PayPal
3. Do not complete PayPal purchase
4. Return to the site and go to Purchase History
5. Click "Complete Purchase" on the pending payment record
6. Finish purchase with Test Mode
7. Download links will fail

Repeat steps on `issue/5472` to confirm the fix.

**Comment by SDavisMedia** [comment]
replicated and confirmed fixed on `issue/5472` :+1:

**Comment by mintplugins** [comment]
also replicated and confirmed fixed on 5472

**Comment by pippinsplugins** [comment]
Great, merging ones tests pass/.
