### ISSUE TITLE
EDD_Batch_Sales_Export broken. Class not found error.

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#5475]
When attempting to export sale records with the `EDD_Batch_Sales_Export` class, a `class not found` fatal error is returned.

**Comment by mintplugins** [comment]
Replicated and confirmed fixed on `issue/5475`

**Comment by SDavisMedia** [comment]
Replicated and confirmed fixed on `issue/5475` :+1:
