### ISSUE TITLE
EDD_Payments_Query should maintain an initial values

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#5477]
Currently in EDD_Payments_Query, all the logic happens for the `edd_pre_get_payments` filter, and modified the args used to setup the class, however anything filtering later on, is left with the remnants of what's been modified already, making it nearly impossible to do some specific logic.

We should store the initial set of arguments in an array (that isn't used to actually make the query) so that other extensions and filters into the `edd_pre_get_payments` can see what the original request was.

**Comment by cklosowski** [comment]
To test this, you can use https://github.com/easydigitaldownloads/edd-recurring/issues/658 as it requires this.

**Comment by pippinsplugins** [comment]
Is this the same as https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5377

**Comment by cklosowski** [comment]
Not quite the same no. That issue is you cannot get renewal payments of a specific download ID. This is that no matter what you send into EDD_Payments_Query, if recurring is enabled, it'll always pull all payments.

**Comment by cklosowski** [comment]
All this is doing is setting up an array of items, that are unchanged by the core EDD logic, so that filters can actually see what the original query was, even after core has modified and unset things.
