### ISSUE TITLE
sanitize_text_field removes the + sign from the email address

### ISSUE THREAD

**Issue by mangesh** [easydigitaldownloads/easy-digital-downloads#5482]
In the latest update of the plugin, On [this line](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/emails/actions.php#L52) sanitize_text_field function removes the `+` sign from the email address. Which causes error in email sending. For example `abc.def+1@pqr.xyz` email address becomes `abc.def 1@pqr.xyz` which is invalid email format.

**Comment by pippinsplugins** [comment]
Thanks for the headsup! We'll get that fixed.

**Comment by cklosowski** [comment]
This isn't working right, it's actually stripping the `+` completely.

The first one was sent via checkout, the other, via the resend:
![screen shot 2017-02-20 at 10 15 34 am](https://cloud.githubusercontent.com/assets/1390124/23135403/ba7950b4-f755-11e6-8b36-ec983ea9f77c.png)

**Comment by cklosowski** [comment]
Running `var_dump` of the email address confirms:
```
$email = ! empty( $_GET['email'] ) ? sanitize_email( $_GET['email'] ) : '';
var_dump($email); exit;
```
`/Users/cklosowski/Development/edd.dev/wp-content/plugins/easy-digital-downloads/includes/emails/actions.php:53:string 'christesting@easydigitaldownloads.com' (length=37)`

**Comment by cklosowski** [comment]
Looks like we're sanitizing too early on.

**Comment by cklosowski** [comment]
Going ot fix it up and commit.

**Comment by cklosowski** [comment]
This is happening b/c the `+` character is actually a ` ` when sent via GET requests...so therefore it's coming into the `actions` as a space, instead of a `+`.

**Comment by cklosowski** [comment]
Ready for testing.

**Comment by pippinsplugins** [comment]
Works well for me.
