### ISSUE TITLE
can't select variable pricing option when adding download to payment

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#5483]
Perhaps we broke this with #4197. The variable price options do not show up after selecting a product that has price options. It works as expected in 2.6.17.

@cklosowski perhaps some JS was missed?

**Comment by SDavisMedia** [comment]
Steps to see the issue:

1. Checkout EDD `2.6.17`
2. View a payment record (any record...doesn't matter) and add a new download the payment. Be sure to select one that has variable pricing.
3. Confirm that when the download is selected, a new select menu for variable price options appears.
4. Checkout EDD `master`.
5. Repeat steps 2 & 3 (be sure to clear browser cache on payment details screen).
6. Confirm that the select menu for variable price options does _not_ appear. That's the bug.

To test:

1. Checkout `issue/5483`, clear browser cache, see if the select menu appears as it should.

**Comment by mintplugins** [comment]
Tested the above steps from @SDavisMedia and confirmed both the bug and the fix on `issue/5483`

**Comment by pippinsplugins** [comment]
Thanks @mintplugins @SDavisMedia !
