### ISSUE TITLE
Add amount filters to Payment History

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#5485]
It would be really nice to have filters in Payment History that allow us to filter results down to just payments that have an amount greater than, equal to, less than, or between certain amounts.

**Comment by ashleyfae** [comment]
Closing as this is now available in 3.0:

![Screenshot from 2021-05-20 13-12-14](https://user-images.githubusercontent.com/6324272/118976529-06b48600-b96d-11eb-949d-9e1a900983a6.png)
