### ISSUE TITLE
Address State Saving Issue

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#5489]
The address state isn't being saved properly when the customer/account country is changed, state changed and then resaved. This happens for both countries with preset states and also manually entered states.

**Comment by SDavisMedia** [comment]
Replicated. We'll get it taken care of. Thanks!

**Comment by cklosowski** [comment]
@SDavisMedia if you remember off hand was there any special steps to replicate?

**Comment by SDavisMedia** [comment]
@cklosowski sorry, never saw your reply.

Go to EDD's profile editor. You most likely have a country and state saved for your billing address already. Change the country and allow the state/province list to repopulate. Once it does, select an option from the list and save the form. On refresh, it won't be there. You can then select a state/province and save again... it will save.

So the point is that if you change the country selection first and then (before saving the form) change the state/province, the state/province selection will not save.

**Comment by cklosowski** [comment]
Ok this is happening because the name changes on the input. On load it's `edd_address_state`, but when the AJAX brings in the new field, it's `card_state`.
