### ISSUE TITLE
PDF download files converted to JPG

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#5491]
Several tickets related to this, I'll update this post once I gather them. 

Edit: here are the tickets I could find.
https://secure.helpscout.net/conversation/321829298/53376?folderId=180502
https://secure.helpscout.net/conversation/321731106/53362?folderId=180502
https://secure.helpscout.net/conversation/321268280/53301?folderId=321418
https://secure.helpscout.net/conversation/319749101/53080?folderId=180504
https://wordpress.org/support/topic/download-is-jpg-not-a-pdf/

Introduced in 2.7.x, can't replicate in 2.6.17.

**Comment by pippinsplugins** [comment]
This was introduced through #5389

**Comment by SDavisMedia** [comment]
Everything seems to be working fine for me on `issue/5491`. :+1:

**Comment by mintplugins** [comment]
I tried with a jpg, a zip, and a pdf and all downloaded correctly here.

**Comment by nevinstarr** [comment]
I have been having this same problem since yesterday. Please advise.

**Comment by cklosowski** [comment]
@nevinstarr We've released EDD 2.7.3 that should fix this, please update and retest.

**Comment by nevinstarr** [comment]
My bad! I saw that right after I sent my message. It works fine now. Thanks for the quick reply!
