### ISSUE TITLE
"Loading" text visible on Add to Cart buttons since EDD 2.7

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#5495]
There have been several tickets about it and some have been written off as theme issues, like so: https://github.com/easydigitaldownloads/Digital-Store/issues/65

Gotta get to the bottom of exactly why it happens if we want to avoid reverting the EDD core change. Or at least know exactly why we have to revert.

I'll try to dig in today.

**Comment by Nate82** [comment]
I believe `.screen-reader-text` has no style set in edd.min.css. I inspected the CSS on EDD's website and the screen reader text had the following style but it was in forms.min.css which is from the wp-affiliate plugin.

```
.screen-reader-text {
    position: absolute;
    margin: -1px;
    padding: 0;
    height: 1px;
    width: 1px;
    overflow: hidden;
    clip: rect(0 0 0 0);
    border: 0;
    word-wrap: normal!important;
}
```

I added the above to my theme style sheet and now the "Loading" text is hidden.

**Comment by pippinsplugins** [comment]
Yep looks like that could be it. Another report of it with a similar solution: https://secure.helpscout.net/conversation/322604601/53533/?folderId=180505

**Comment by pippinsplugins** [comment]
Another report https://secure.helpscout.net/conversation/322995174/53601/?folderId=180499

**Comment by samikeijonen** [comment]
Yeah that's the reason and I did know it was coming. We could change this to using aria-label text or add the CSS in the plugin. I prefer the first choice.

**Comment by pippinsplugins** [comment]
@samikeijonen could you go over the cons/benefits of each? I don't really know the difference between the two.

**Comment by pippinsplugins** [comment]
Another report: https://secure.helpscout.net/conversation/313597072/52176/?folderId=180505

We'll need to ship this today.

**Comment by SDavisMedia** [comment]
@samikeijonen @pippinsplugins yup, it's the lack of screen reader text CSS in some themes, which is unfortunate. But it's not a forcible standard. 

I'm gonna go with aria-label, since it's a more friendly solution and we're already starting to do it in EDD's admin area. I'll get this worked up shortly.

**Comment by SDavisMedia** [comment]
That should take care of it across the board.

**Comment by pippinsplugins** [comment]
Looks good to me. Merging and preparing to deply.

**Comment by samikeijonen** [comment]
Yes like @SDavisMedia said the cons are that not all themes use `screen-reader-class`. It's because it's older theme or they want to be screen reader text visible for everyone. Note that Core uses `screen-reader-class` also in the front-end.

`aria-label` is good alternative for assistive technology (AT) users because they can read it. I just don't personally like to use it on empty DIVs or SPANs. That's bad semantics for me.

Anyways I'm good with the PR 👍
