### ISSUE TITLE
Create ability to add message to email receipt if no files exist. 

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#5500]
For extensions like "Downloads as Services", the product likely does not have any files attached for download. This results in a confusing email that looks like this:

<img width="686" alt="screen shot 2017-02-23 at 11 24 53 am" src="https://cloud.githubusercontent.com/assets/1638128/23268109/bc466c8a-f9ba-11e6-8527-6bc010ef7c34.png">

**Proposal:**
Add a message in email receipts if no files are attached:

<img width="659" alt="screen shot 2017-02-23 at 11 24 36 am" src="https://cloud.githubusercontent.com/assets/1638128/23268382/8d53147c-f9bb-11e6-8cf2-4ad9aad7beff.png">

This message could then be filterable so the message could be modified based on the product using a custom snippet.

**Comment by mintplugins** [comment]
To test:

1. Create a product with files attached and purchase. Check the email receipt to make sure everything looks good. 

2. Create a product with no files attached and purchase. Check the email receipt to make sure the "No downloads available" message is in the email.

**Comment by pippinsplugins** [comment]
I'm okay with this, though I worry that a lot of users that don't sell downloads will be irritated with the new text is added to their email receipts. It can definitely be disabled through the filter (Downloads as Services will need updated).

**Comment by mintplugins** [comment]
@pippinsplugins We could default it to have no output but still be filterable. Just brainstorming, I think this could also be useful for things like 

- Bookings - which could output booking information automatically into the email receipts. 
- Simple Shipping - to output tracking information automatically.

**Comment by mintplugins** [comment]
@pippinsplugins Check the latest commit to see how I think this could work without affecting existing setups: https://github.com/easydigitaldownloads/easy-digital-downloads/pull/5501/commits/5e9b330aca051fac7cb4414074c3685704a31449

**Comment by pippinsplugins** [comment]
I like the idea of having a filter that _can_ be used but not using it by default :+1:

**Comment by cklosowski** [comment]
We already show something like this on the front end when there are no downloadable files, and plugins like Downloads as a service simply filter it...could we have it, and just use thew same filter, so they all just work out of the box?

**Comment by cklosowski** [comment]
The filter mentioned above is: `edd_receipt_no_files_found_text`

It wraps the `'No downloadable files found.` on the purchase confirmation, as long as we use it in the email text too, I see no reason to not do this.

**Comment by mintplugins** [comment]
Excellent :) Added!

So again to test:

Create a product with files attached and purchase. Check the email receipt to make sure everything looks good. 

Create a product with no files attached and purchase. Check the email receipt to make sure the "No downloadable files found" message is in the email.

I have tested this myself and everything works properly in my tests.

**Comment by ghost1227** [comment]
@mintplugins Other than the one change Chris requested, this looks great! Initial testing says nothing breaks either, so 👍 from me!

**Comment by mintplugins** [comment]
@ghost1227 Just to confirm, what do you mean about Chris's requested change? I think all his changes are in there. 

I'm confused by the review process system on github...

**Comment by ghost1227** [comment]
@mintplugins looks like you've fixed it, all good!
