### ISSUE TITLE
Outputting extra dash on download history/email receipt when there are no price options

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#5504]
Relevant code: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/templates/history-downloads.php#L42

Relevant commit: https://github.com/easydigitaldownloads/easy-digital-downloads/commit/a8d070dd35d80a88cb7b77a4c05881e0bdfd75a6

`is_numeric()` doesn't seem to be a good check here.

**Comment by SDavisMedia** [comment]
We replaced `! empty( $price_id )` with `is_numeric( $price_id )` in that commit. The former seems correct. 

Whether `$price_id` returns `0` or another price ID,  `is_numeric( $price_id )` will be true. `! empty( $price_id )` is false if `$price_id` returns `0`.

**Comment by pippinsplugins** [comment]
Should be `if( ! empty( $price_id ) && 0 !== $price_id )` I think.

**Comment by SDavisMedia** [comment]
I considered that and thought it was overkill. At the same time, _something_ drove us to change it in the first place (maybe @cklosowski remembers). So at least that's safe. I'm good with it if y'all are.

**Comment by pippinsplugins** [comment]
Price IDs used to start with `0`, so to be backwards compatible with old products, we have to check for `0` too.

**Comment by SDavisMedia** [comment]
Oh yea, forgot about that. PR should do the trick then.

**Comment by ghost1227** [comment]
👍 Looks good!

**Comment by sunnyratilal** [comment]
PR looks good from this end

**Comment by pippinsplugins** [comment]
Merged.
