### ISSUE TITLE
PayPal Standard: Positive fees should only be added as items when download_id is empty

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#5505]
Fees are added as line items in PayPal Standard:
```
$discounted_amount = 0.00;
if ( ! empty( $purchase_data['fees'] ) ) {
	$i = empty( $i ) ? 1 : $i;
	foreach ( $purchase_data['fees'] as $fee ) {
		if ( && floatval( $fee['amount'] ) > '0' ) {
			// this is a positive fee
			$paypal_args['item_name_' . $i ] = stripslashes_deep( html_entity_decode( wp_strip_all_tags( $fee['label'] ), ENT_COMPAT, 'UTF-8' ) );
			$paypal_args['quantity_' . $i ]  = '1';
			$paypal_args['amount_' . $i ]    = edd_sanitize_amount( $fee['amount'] );
			$i++;
		} else if ( empty( $fee['download_id'] ) ) {

			// This is a negative fee (discount) not assigned to a specific Download
			$discounted_amount += abs( $fee['amount'] );
		}
	}
}
```

This, however, causes problems when `download_id` is set for the fee since we already add the fee amount to the product's amount.

We should only add the fee if `download_id` is empty.

**Comment by pippinsplugins** [comment]
See https://github.com/easydigitaldownloads/EDD-Simple-Shipping/issues/51 for an example.

**Comment by pippinsplugins** [comment]
@mintplugins or @SDavisMedia could one of you test this please?

**Comment by pippinsplugins** [comment]
To replicate original bug:

1. Setup Simple Shipping and purchase an item
2. When going to PayPal, final amount will be incorrect. It will charge shipping 2x.

**Comment by mintplugins** [comment]
@pippinsplugins 

Replicated on master: fees were doubled on Paypal Standard checkout. 

Confirmed fixed on `issue/5505`

**Comment by ghost1227** [comment]
@mintplugins beat me to it, but confirmed fix
