### ISSUE TITLE
Improvement - Actions and filter within edd_has_user_purchased()

### ISSUE THREAD

**Issue by daigo75** [easydigitaldownloads/easy-digital-downloads#5511]
**Background**
I stumbled across an issue that was caused by the `edd_has_user_purchased()` function. Using that function on a page caused the active currency to be replaced with the one used by the last payment queried by the function.

**Cause of the issue**
The issue occurred because, when a payment is loaded, the currency is indeed replaced with the one in which the order was placed. This is necessary to ensure that payments are processed correctly. Unfortunately, this has the side effect of triggering the currency change when `edd_has_user_purchased()` goes through the payment history.

**Solution**
I wrote a workaround for the client, but I reckon that a more permanent solution should be implemented. At the moment, function `edd_has_user_purchased()` doesn't provide actions or filters. Due to that, there is no way to know that a payment is loaded within the function's context, and that those payments should not alter the currency. 

My fix is simply the addition of one action, to notify 3rd parties of the upcoming operation, and one filter, to notify of its completion (and, eventually, override the result). I already prepared a patch, I'm going to send a PR shortly.

**Comment by pippinsplugins** [comment]
PR for this looks like it should be fine. Milestoning for 2.7.6.

**Comment by pippinsplugins** [comment]
New PR: https://github.com/easydigitaldownloads/easy-digital-downloads/pull/5607

Note, I changed the result filter to `edd_has_user_purchased`.

Also see https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5605

**Comment by daigo75** [comment]
Thanks for letting me know. :+1:
