### ISSUE TITLE
Spaces in URLs for files and featured images can cause import problems.

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#5513]
The problem is that when we do an import and process the `str_to_array` method, the last check delimiter is for `/`, but we also check a `filter_var` to validate if it's a URL. If there are spaces in the URL at all, it is not a valid format URL, technically.

Right now users can just change spaces in URLs to `%20` but we should see if we can try and detect that.

**Comment by pippinsplugins** [comment]
I vote for str_replace for a quick fix.

**Comment by sunnyratilal** [comment]
`str_replace` gets my vote too

**Comment by ghost1227** [comment]
Quick fix applied

**Comment by pippinsplugins** [comment]
PR looks good to me. Let's merge once tests pass.
