### ISSUE TITLE
Browser cache flush required when EDD admin CSS is updated

### ISSUE THREAD

**Issue by scottbuscemi** [easydigitaldownloads/easy-digital-downloads#5515]
The 2.7 update included new EDD admin styling via the edd-admin.min.css file. If the user does not clear their browser cache, viewing an order can result in strange styling.

The query string associated with that stylesheet is the current WordPress version rather than the current version of EDD. I'd recommend swapping out the query string for all js/css files to be related to the EDD version instead.

**Comment by sunnyratilal** [comment]
Thanks for the report - we'll get it addressed in the next point release.

**Comment by ghost1227** [comment]
I'm a bit confused on this one. We're defining version for the admin scripts with `EDD_VERSION` (https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/scripts.php%23L257) @pippinsplugins Any thoughts?

**Comment by scottbuscemi** [comment]
![screen shot 2017-03-03 at 11 53 53 am](https://cloud.githubusercontent.com/assets/4336848/23566755/178333c8-0008-11e7-86bd-c21c365313a1.png)

I'm seeing some things are the EDD version and some are the WordPress version...

**Comment by scottbuscemi** [comment]
@ghost1227 on line 257, it looks like the EDD_VERSION is being set as the third parameter rather than the fourth ... https://codex.wordpress.org/Function_Reference/wp_register_style. This would be the issue.

**Comment by ghost1227** [comment]
That'd do it! Good catch, sometimes we need someone who doesn't look at it every day.
