### ISSUE TITLE
EDD auto-completes non-complete PayPal eCheck transactions

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#5516]
It appears EDD is automatically completing PayPal eCheck transactions again. A while ago (#196) in the IPN we had fixed this to remain as pending until the notification that it cleared. It seems that has broken.

**Comment by chriscct7** [comment]
Actually this is a PayPal Express gateway bug. Not sure if caused by recurring. Will log when I figure that part out.

**Comment by pippinsplugins** [comment]
In the PayPal Express settings is an option to auto complete purchases.

**Comment by chriscct7** [comment]
That's not it. Autocomplete is when you come back you don't have to explicitly authorize it. I'm referring to PayPal eCheck payments done through that. So when I get back, if I have that option on I should still not have to authorize it, but eCheck payments should never clear before the payments are done in PayPal.

So with that option on, debit, credit or paypal funds should auto complete, but eCheck should not because unlike the former 3, an eCheck doesn't clear PayPal for 3 - 6 business days. This is why we have that check for this in the PayPal standard IPN
