### ISSUE TITLE
"Click here to to request a new verification URL" literally has no URL

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/easy-digital-downloads#5519]
A customer reported that their customers were complaining about their user activation emails expiring and the link to request a new one was not working. This lead me to discover our code here: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/user-functions.php#L830

`...__( 'Sorry but your account verification link has expired. <a href="#">Click here</a> to request a new verification URL.', 'easy-digital-downloads' ) )...

Notice anything missing? :wink:

So our solution I think is to make this URL go to...the purchase history page? Not positive where users should be redirected and whether a new message needs to be shown to them like "Please check your email for your new verification link" or something.

Does anyone have any thoughts on where the user should end up and what they should be shown?

**Comment by ghost1227** [comment]
Oh that's all sorts of special. I'm not sure where that one should be pointed. @pippinsplugins Thoughts?

**Comment by pippinsplugins** [comment]
@ghost1227 it needs to point to an action link that resends the verification email with new links. There is one already setup that's shown on the account pages, so you can reuse that.

**Comment by ghost1227** [comment]
Sounds good!

**Comment by pippinsplugins** [comment]
PR submitted.

**Comment by ghost1227** [comment]
@pippinsplugins looks good!

**Comment by pippinsplugins** [comment]
@ghost1227 no it doesn't. I missed the place holder for `sprintf`.

**Comment by pippinsplugins** [comment]
Fixed.

**Comment by ghost1227** [comment]
Wow... I guess the brain really does read what it wants to read. Live testing coming up

**Comment by ghost1227** [comment]
Tests good!
