### ISSUE TITLE
Recovered payments not updating payment date to the day it was completed.

### ISSUE THREAD

**Issue by danieliser** [easydigitaldownloads/easy-digital-downloads#5520]
Using EDD SL & Recurring.

Had a user fail a __renewal__ transaction on Oct 27, 2016.

On Feb 28, 2017 they came back, recovered the transaction and processed a paypal payment, successfully renewing and creating a new subscription.

I received the typical emails from Paypal about the payment & subscription. But when I checked the dash the sale was not reflected in the daily or monthly totals or reports.

Further inspection I found the subscription which lead me to the attached payment. It was marked complete on Oct 27 2017 which now also appears in October's reporting.

I was able to get it to appear in reporting correctly by manually adjusting the date, but it still doesn't appear in the dash recent transactions list either.

Seems like status is maybe being set to complete but the payment date isn't being updated to the current date. This could be renewal specific as well.

**Comment by pippinsplugins** [comment]
PR submitted!

**Comment by SDavisMedia** [comment]
Replicated the issue on `master` and confirmed fixed on `issue/5520`. :+1:

**Comment by mintplugins** [comment]
Replicated on Master by doing this:

1. Add product to cart and go to paypal but don't complete payment. 
2. Edit Payment to have date set to last month. 
3. Use the recovery URL to purchase the product. 
4. Confirmed date of payment does not change. 

Confirmed fixed on `issue/5520`

**Comment by danieliser** [comment]
Awesome :) :+1:
