### ISSUE TITLE
No URL to updated product in the product update emails sent.

### ISSUE THREAD

**Issue by Hensa** [easydigitaldownloads/easy-digital-downloads#5521]
Many(but not all) my customers are reporting that they no longer see a url for their download in the emails for their product updates.
Additionally they cannot see their purchase history when logged in, its just blank.

After some investigating, Ive gone through and manually reconnected their User ID's because for some of them that was the problem and it fixed it. But now its happening to people whose User ID's are connected. Odd how this is happening, seemingly out of now where. Super frustrating.

![4qjpoqr](https://cloud.githubusercontent.com/assets/26099536/23438759/2c797c7a-fdc8-11e6-9d9c-7d8baf00a2d2.png)

**Comment by pippinsplugins** [comment]
Hi there!

Please go ahead and open a support ticket through our support portal: https://easydigitaldownloads.com/support

we use GitHub for development tracking only.

**Comment by Hensa** [comment]
Apologies. Ive already done that, as well as paid for priority support from
you but in a weeks time ive not gotten many answers for my problem from you.

Just trying to get help/answers as this is a very important and time
sensitive issue for me.

On Tue, Feb 28, 2017 at 3:13 PM, Pippin Williamson <notifications@github.com

**Comment by pippinsplugins** [comment]
@Hensa I last emailed you on the 26th requesting more information; an email which you never responded to. Please check your spam folder. I'll follow up there shortly.

**Comment by Hensa** [comment]
I went ahead and did that this morning. At the time, i had no example
because I thought I had fixed the issue but I have more now.

Thank you.

On Tue, Feb 28, 2017 at 3:21 PM, Pippin Williamson <notifications@github.com
