### ISSUE TITLE
EDD 2.7.4 Discount Codes not working and Unable to bulk delete existing codes or upload new codes

### ISSUE THREAD

**Issue by complexi** [easydigitaldownloads/easy-digital-downloads#5522]
Latest WordPress and Wordfence. Upgraded to latest EDD 2.7.4 and discount codes are no longer working with each application resulting in "discount code does not meet requirements" even though it does. I can manually add a new code which does work. CSV Coupon Importer is licensed but cannot import files any longer. The bulk delete on Discount Codes does not work and will divert user to home page of the site. Individual code delete work (but have over 6000 codes). Where are these codes stored?

**Comment by pippinsplugins** [comment]
@complexi we've received your support ticket in our support dashboard so we will work with you there on it. GitHub is only for development tracking.
