### ISSUE TITLE
You can purchase single price even if variable pricing enabled

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#5524]
If you enable variable pricing for a product, it's possible to purchase a single price version using a custom "Add To Cart" link. Technically you would be purchasing a product that doesn't exist. 

This should likely either throw a cart error or default to the default price.

**Comment by chriscct7** [comment]
This is a duplicate of https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5345
