### ISSUE TITLE
EDD_Discount: insert_discount() stores empty metadata

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#5533]
The `insert_discount()` method of the new `EDD_Discount` class does not check to see if the `$value` is empty before storing the metadata. This can result in unexpected behavior, such as product requirements never being fulfilled.

Discovered here: https://secure.helpscout.net/conversation/326802359/54236/?folderId=180505

**Comment by mintplugins** [comment]
Confirming that this prevents meta from being saved if blank. 

What I did to test:

```
function add_bogus_discount(){
	$new_discount = new EDD_Discount( 'issue5534' );
	$new_discount->save();
}
add_action( 'init', 'add_bogus_discount' );
```

On master DB results are:
<img width="440" alt="screen shot 2017-03-06 at 11 33 18 am" src="https://cloud.githubusercontent.com/assets/1638128/23619178/d361bcd6-0260-11e7-9538-538da6bb6947.png">

On `issue/5533' results are:
<img width="480" alt="screen shot 2017-03-06 at 11 33 10 am" src="https://cloud.githubusercontent.com/assets/1638128/23619194/e09a41a2-0260-11e7-8f50-ead533779c57.png">
