### ISSUE TITLE
Discounts: product requirements check fails if requirements meta is an empty string

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#5534]
If the `_edd_discount_product_reqs` meta data is set to an empty string, the check when applying the discount will always fail and report `The product requirements for this discount are not met.`.

Related #5533

**Comment by mintplugins** [comment]
Replicated issue on master by running this to make the field empty:

`update_post_meta( $discount_id, '_edd_discount_product_reqs', ' ' );`

Confirmed fixed on `issue/5534`. Discount codes applies without issue now.

**Comment by pippinsplugins** [comment]
@mintplugins could you test again please?

**Comment by mintplugins** [comment]
@pippinsplugins I ran the same test again. Replicated the issue on master and confirmed fixed on `issue/5533`.
