### ISSUE TITLE
No error messages shown on [edd_register]

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#5537]
When the `[edd_register]` form has errors, nothing is displayed. Page reloads without errors.

**Comment by pippinsplugins** [comment]
Introduced by https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4943

**Comment by mintplugins** [comment]
Replicated and confirmed fixed on `issue/5537`. 

Error messages are now showing:
<img width="475" alt="screen shot 2017-03-06 at 10 37 59 am" src="https://cloud.githubusercontent.com/assets/1638128/23616853/1b385036-0259-11e7-9743-0fb88f786663.png">
