### ISSUE TITLE
Export Sales missing variable pricing options and quantity

### ISSUE THREAD

**Issue by poweringphilanthropy** [easydigitaldownloads/easy-digital-downloads#5552]
Running EDD Version 2.7.5.  

Along with issue pointed out here - https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5551

The Sales Export does not currently list out the downloads variable pricing option linked to the download and also does not list quantity of downloads. The example below has sizes (small, medium large) variable pricing options and log 22166 is for 2x quantity. Would be helpful to have a row per unique purchase of a particular download and option combo and show the quantity of that transaction.

![image](https://cloud.githubusercontent.com/assets/18558697/23687476/dfaac90e-036b-11e7-9102-40c98a074998.png)

**Comment by ashleyfae** [comment]
Reopening as this issue was reported as still being a problem by someone using beta-1: https://secure.helpscout.net/conversation/1443199224/179101?folderId=180499

**Comment by mihaijoldis** [comment]
Ran an export on 3.0:
https://prnt.sc/10cun4l https://prnt.sc/10cuntz https://prnt.sc/10cuoax

It appears that the variation and quantity is all in one field `Vaiable product (4) - Option C - $15.00` but it does show up

**Comment by mihaijoldis** [comment]
One Issue I noticed is the "user" field that shows "guest" but I did all the purchases and export while logged in as admin

**Comment by ashleyfae** [comment]
Definitely seems to me like we could have a separate, dedicated column for quantity at the very least.

**Comment by mihaijoldis** [comment]
Agree there but how will that work for the entry where cart had more than 1 items in it 
`Vaiable product (2) - Option A - $5.00 / Simple Download - $599.00` in this case you have 2 and 1 as quantity for each products

**Comment by ashleyfae** [comment]
Right, this is for exporting _payments_. If it was one row per order item it would work, but not for the entire payments.

@mihaijoldis can you get back to the customer with your findings. If they still feel it's not working for them, get a screenshot or copy of their CSV export.

I'm closing this for now, but will re-open if we discover there is a problem.
