### ISSUE TITLE
HTML Elements class, user_dropdown method broken

### ISSUE THREAD

**Issue by ghost1227** [easydigitaldownloads/easy-digital-downloads#5554]
While testing Commissions 3.3, we discovered that if a site has more than 30 users, and a saved user isn't within the first 30 selected, it doesn't properly set on load. This is because the chosen dropdown doesn't include a user with the specified ID.

**Comment by pippinsplugins** [comment]
Oops, merged too early. `get_user()` should be `get_userdata()`.
