### ISSUE TITLE
Amazon Payments: payment fields no longer show after redirect back from Amazon

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#5557]
After being redirected back to a store from Amazon.com, customers are supposed to see the personal info fields and their available payment methods from their Amazon account. Since 2.7, however, the checkout screen is reloaded and simply shows the gateway selectors again.

To replicate:

1. Enable _more_ than one gateway (at least two)
2. Go to checkout and select Amazon
3. Go to Amazon to authorize
4. Return to checkout and problem is obvious

I believe this was caused by changes for https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5082

**Comment by pippinsplugins** [comment]
Here's a better set of replication steps with screenshots to show what you'll see when replicating the bug.

1. Go to checkout and select Amazon.
2. Click Pay with Amazon. This will open a modal that looks like this:
<img width="1206" alt="screen shot 2017-03-08 at 4 47 05 pm" src="https://cloud.githubusercontent.com/assets/1034109/23727753/e9496c32-041e-11e7-8fa5-ec96c98c3282.png">
3. Click the sign in button (you may be shown a second authorization step in the model)
4. The modal will close and the EDD checkout screen will reload and look like this:
<img width="1101" alt="screen shot 2017-03-08 at 4 48 21 pm" src="https://cloud.githubusercontent.com/assets/1034109/23727781/0fd29ae0-041f-11e7-9604-2a6a0481c914.png">
Amazon will be selected as the gateway. Your browser URL will look like this: 

`https://edd.com/checkout-page/?payment-mode=amazon&state=authorized&amazon_reference_id=S01-3981352-8798048`

The `state` and `amazon_reference_id` parameters are very important. The presence of those confirms that you successfully authorized with Amazon and have replicated the bug.

If you do _not_ see `state=authorized` and `amazon_reference_id` something else has gone wrong and you'll need to double check your Amazon payments configuration before you can replicate the bug and test the fix.

**Comment by cklosowski** [comment]
Looks like it's working to me. Confirmed on `master` i'm just redirected back to have the `Pay with Amazon` button. On `issue/5557` I get the proper checkout widgets:
![screen shot 2017-03-09 at 10 50 20 am](https://cloud.githubusercontent.com/assets/1390124/23763316/4abf4fa8-04b6-11e7-9089-595d052b4355.png)

**Comment by pippinsplugins** [comment]
:+1: merging.
