### ISSUE TITLE
User pending verification message repeated if multiple shortcodes exist on same page

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/easy-digital-downloads#5561]
Pretty loosely qualifies as a bug but I think users who encounter it will perceive it that way. The problem is that if site owners put multiple shortcodes on the same page which generate the account pending verification message, the message just gets repeated.
![Screen Shot 2017-03-09 at 1.08.28 PM](http://static.gitscout.com/bacfbd52fef097fb20282a2aaeefa25e5c0edbc3449ee59218c8cbbc58912646.png)

Shortcodes used here:
[download_history]
[edd_profile_editor]
[purchase_history]
[edd_license_keys] < - can open an issue on SL for this if it isn't just a core fix.

I don't really think it is a bizarre use case, having a couple account related shortcodes on the same page like this customer is doing: https://secure.helpscout.net/conversation/325494630/54003/?folderId=448801

I think we should explore ways to prevent the message from being duplicated in the same post.

**Comment by pippinsplugins** [comment]
We can easily limit it to a single display per page load with a static variable.

**Comment by sunnyratilal** [comment]
Tested and working as expected.
