### ISSUE TITLE
Missing filter - Cannot alter a product-specific discount

### ISSUE THREAD

**Issue by daigo75** [easydigitaldownloads/easy-digital-downloads#5563]
Cart discounts use function `edd_get_discount_amount()`, which provides a convenient way to alter the amount of a discount before it's applied. Product-specific discount follow a different logic, and call `edd_get_discounted_amount()` instead. That function relies on `EDD_Discount::get_discounted_amount()`, which doesn't allow such processing to take place.

**Proposed solution**
Alter `EDD_Discount::get_discounted_amount()` to call the  `edd_get_discount_amount` filter. PR to follow.

**Comment by pippinsplugins** [comment]
This looks good to me.

@cklosowski @sunnyratilal any objections?

**Comment by pippinsplugins** [comment]
@daigo75 looks like the filter got added during the 2.7 release. Please re-open this if I've missed something and a filter is still needed.
