### ISSUE TITLE
On subsequent payment, Customer name not updated if blank.

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#5566]
If you are using the Free Downloads extension, it's possible you'd have a lot of payments with Customers who did not enter their name. 

If those same customers come back later and make a real purchase, their Customer name remains blank despite the fact that they filled it out when making that second purchase.

**Comment by pippinsplugins** [comment]
Related https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6043

**Comment by sunnyratilal** [comment]
This has been added in 2c7b9010e9ec5ab3a437e4114cdc83b735ab65c8 with the new order creation flow.
