### ISSUE TITLE
edd-page body class added to all pages when test mode is activated

### ISSUE THREAD

**Issue by sumobi** [easydigitaldownloads/easy-digital-downloads#5572]
The `edd-page` body class is being added to all pages when test mode is activated. I can't think of a reason this should be there so I say we remove it:

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/template-functions.php#L929

**Comment by sumobi** [comment]
PR: https://github.com/easydigitaldownloads/easy-digital-downloads/pull/5573

**Comment by pippinsplugins** [comment]
Merged.
