### ISSUE TITLE
Typo in CSS ID selector, combine CSS selectors

### ISSUE THREAD

**Issue by sumobi** [easydigitaldownloads/easy-digital-downloads#5574]
`#edd_checkeout_form_wrap` should be `#edd_checkout_form_wrap`:
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/templates/edd.css#L384

Also, there's duplicate `#edd_profile_editor_form .edd-profile-emails` selectors which can be combined.

**Comment by sumobi** [comment]
PR: https://github.com/easydigitaldownloads/easy-digital-downloads/pull/5575

**Comment by sunnyratilal** [comment]
All good here

**Comment by sunnyratilal** [comment]
Merged
