### ISSUE TITLE
PHP Warning:  array_values() expects parameter 1 to be array, null given

### ISSUE THREAD

**Issue by shazahm1** [easydigitaldownloads/easy-digital-downloads#5576]
I'm getting this in my PHP error log since upgrade to 2.7:

PHP Warning:  array_values() expects parameter 1 to be array, null given in ../wp-content/plugins/easy-digital-downloads/includes/class-edd-download.php on line 549

I' do not have any bundle pricing variations setup but I have 3 bundles which were setup prior to this bundle variation feature.

Perhaps there is a need for a check for an array ...

OR

Is there a bug somewhere here?

**Comment by pippinsplugins** [comment]
Please see https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5567

**Comment by shazahm1** [comment]
Thx... my google fu failed me. Sorry for the duplicate!
