### ISSUE TITLE
EDD-SL: phpDoc error in get_license_by_purchase()

### ISSUE THREAD

**Issue by shazahm1** [easydigitaldownloads/easy-digital-downloads#5577]
Hoping you can move this to the EDD-SL repository easily since it is private.

The was throwing for me a few minutes in PHP Storm...

The return value of EDD_Software_Licensing::get_license_by_purchase() is now EDD_SL_License and not WP_Post. Causing issue with code completion in the IDE.

**Comment by pippinsplugins** [comment]
@shazahm1 I've granted you access for it
