### ISSUE TITLE
EDD Payment object: Add discounts_total property

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#5580]
I'd be nice if the EDD Payment class had a discounts_total property, to make it easier to get that number (otherwise you have to do total - ( fees_total + tax ).

As a note, there's no standardized total names, they're all completely different atm:
`subtotal`, `fees_total`, `tax` <-- all of these are totals

Maybe in the magic get/set/isset we should map these properties to new standardized property names.

**Comment by cklosowski** [comment]
Ok i've added a property and a getter. I'm going to hold off on the renaming, and do that along side the custom tables in #4576, so it'll be a smooth transition and we can just include it in our backcompat layer for that.
