### ISSUE TITLE
Czech Republic is now Czechia

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#5581]
Early last year, the Czech Republic decided to adopt the official name of "Czechia" for the English language. This change is now the official country name for business, politics, sports, commerce, and more for the English language. As EDD is written in English, we should update the country list (and subsequent unit test) to use this new name.

Google Maps and many others have already switched over: http://cloud.supportally.com/2t0N2I3B1t3N. Google switched over all products on Jan. 19th, 2017 to the new name.

**Comment by cklosowski** [comment]
As a note, the currency _*did not*_ change. It is still the `Czech Koruna`

**Comment by chriscct7** [comment]
> As a note, the currency did not change. It is still the Czech Koruna

That's affirmative

**Comment by SDavisMedia** [comment]
All good here. Can't think of anywhere else it needs to be updated.
