### ISSUE TITLE
Support export of daily earnings/sales for any time period selected

### ISSUE THREAD

**Issue by lisag** [easydigitaldownloads/easy-digital-downloads#5582]
I couldn't find an issue for this anywhere, so apologies if it already exists. 

I think it would be extremely useful for customers to be able to export daily Earnings/Sales count. It would be awesome to be able to see earnings/sales count daily per week, daily per month, daily per quarter, daily per year, daily per custom date range, etc. 

Adding this feature would make the sales data easier to filter and use, and would be incredibly handy for customers who have daily sales. 

We can see the daily totals when we filter by date or select "Today" or "Yesterday", or even in the Reports per week and per month, but there is currently no simple way to see these daily numbers easily (that I have seen), as the exported file only shows a total based on the period selected, rather than the daily amounts that add up to that total.

**Comment by sunnyratilal** [comment]
Implemented in https://github.com/easydigitaldownloads/easy-digital-downloads/commit/7f129a66c2232bd6db5a6a3013e5e4e156f4df74.
