### ISSUE TITLE
Improve error message for receipts for guest payment.

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#5594]
If a guest checkout customer tries to view their receipt after their purchase session is expired - or in another browser, they see "Sorry, trouble retrieving payment receipt.".

I wonder if we could improve that error message to give them an idea why. For example, the message could be changed to something like:

 "Sorry, trouble retrieving payment receipt because the purchase session is expired".

It could be filterable to allow Site Admins to add their own error message like - "Contact support to request a new receipt".

**Comment by pippinsplugins** [comment]
@mintplugins Let's update this to allow the `edd_user_can_view_receipt` filter to still be run in case someone wants to allow receipts to always be visible: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/81c2ebc0c2ab8e103d1ef9b5526186c15dc78e46/includes/shortcodes.php#L771

**Comment by mintplugins** [comment]
@pippinsplugins Good call. Latest commit makes use of that filter in the check.

**Comment by pippinsplugins** [comment]
I don't love the text `Sorry, trouble retrieving payment receipt because the Guest Checkout purchase session is expired.`

How about changing it to: `Receipt could not be retrieved, your purchase session has expired.`?

**Comment by cklosowski** [comment]
@pippinsplugins @mintplugins updated the error message.

**Comment by mintplugins** [comment]
@cklosowski Looks good here 👍
