### ISSUE TITLE
Bump min WP version to 4.4

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#5599]
It's time that we get the min WP version increased. We currently advertise support for 4.0 and later. I propose we bump this to 4.4.

Our usage stats show:

3.5: 0% (2)
3.6: 0% (4)
3.7: 0% (3)
3.8: 0% (10)
3.9: 0% (13)
4.0: 0% (51)
4.1: 0% (82)
4.2: 0% (143)
4.3: 0% (305)
4.4: 1% (965)
4.5: 8% (8,093)
4.6: 11% (11,584)
4.7: 18% (18,886)

Doing so gives us the following benefits:

- encourages those that are slow to update to get their sites updated
- dramatically decreases the time it takes to run unit tests (we currently test back to 4.0)
- allows us to use new functions introduced in 4.4+

**Comment by michaelbeil** [comment]
I'm all for this.

**Comment by sunnyratilal** [comment]
Initial PR setup at #5650 which just alters the readme and unit test matrix, for now.

**Comment by chriscct7** [comment]
Something is up with your data from the looks of it, only 38% of users are accounted for. Might want to double check that

**Comment by pippinsplugins** [comment]
@chriscct7 that's because we have a lot of old data in the database that is no longer reliable. The numbers above are the _known_ sites.

**Comment by chriscct7** [comment]
ah ok

On Mon, Apr 24, 2017 at 1:48 PM, Pippin Williamson <notifications@github.com
