### ISSUE TITLE
Last Month reports incorrect in dashboard summary widget

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#5603]
Since 2.7.6, the `Last Month` stats are showing incorrect in the sales summary widget. This bug was introduced by changes made for https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4988

When querying the stats for `last month`, the `end_date` is getting set to today.

**Comment by pippinsplugins** [comment]
It's because of this in `setup_dates()`:
```
if( empty( $_end_date ) ) {
	$_end_date = time();
}
```
When querying pre-defined date ranges, `$_end_date` is passed as false and then set up later in the class

**Comment by SDavisMedia** [comment]
Replicated on `master` and confirmed fixed on `issue/5603`. :+1:
