### ISSUE TITLE
File assignment fails when set to the first price on old products that still use 0 as the first price ID

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#5610]
Reported by @chriscct7: old products with variable prices that start at 0 instead of 1 do not properly support price assignment to the first price on files.

PR to fix it: https://github.com/easydigitaldownloads/easy-digital-downloads/pull/5602

Related: https://github.com/easydigitaldownloads/edd-fes/issues/1152
Related: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5443

**Comment by cklosowski** [comment]
Looks like we missed one when doing #5443. Looks good to me.
