### ISSUE TITLE
Error: The email address demo@example.com is already in use.

### ISSUE THREAD

**Issue by ufdpoint1** [easydigitaldownloads/easy-digital-downloads#5611]
Hi Team,

My existing client can't buy product because an error showing when enter the email address.

Error: The email address waseemnazar2015@gmail.com is already in use.

I am using  Version 2.7.6

Regards,
Taufeeq

![img1](https://cloud.githubusercontent.com/assets/26720525/24368175/79abe3c2-12ed-11e7-9501-b9f6effe7a88.jpg)

**Comment by pippinsplugins** [comment]
Hi there!

Please go ahead and open a support ticket through our support portal: https://easydigitaldownloads.com/support

we use GitHub for development tracking only.

Also please see http://docs.easydigitaldownloads.com/article/1389-email-address-already-in-use

**Comment by ufdpoint1** [comment]
Thank you
