### ISSUE TITLE
Complete purchase button text is not flexible with translations

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#5614]
```
function edd_get_checkout_button_purchase_label() {
	$label = edd_get_option( 'checkout_label', '' );

	if ( edd_get_cart_total() ) {
		$complete_purchase = ! empty( $label ) ? $label : __( 'Purchase', 'easy-digital-downloads' );
	} else {
		$complete_purchase = ! empty( $label ) ? $label : __( 'Free Download', 'easy-digital-downloads' );
	}

	return apply_filters( 'edd_get_checkout_button_purchase_label', $complete_purchase, $label );
}
```

Basically since we allow both of the strings `Purchase` and `Free Download` to be translated, if the user as entered anything in the `Complete purchase button text` it will always use that, so translations for `Free download` and `Purchase` are completely ignored, even though they are very different cases.

**Comment by pippinsplugins** [comment]
We could add a new setting for 0.00 checkout button text.

**Comment by cklosowski** [comment]
I think that's probably the best solution

**Comment by cklosowski** [comment]
We should also passed that string through the translation with an_X so we can get some context

**Comment by pippinsplugins** [comment]
Looks good, merged!
