### ISSUE TITLE
Forward Slashes for Download Files create a new Product

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#5620]
A customer is experiencing an error with CSV product imports. The Download Files field is supposed to allow for forward slashes for the location of the file. 

The documentation states that 
```
This field can accept a valid web address of a file, an absolute path 
on a filesystem, or the bucket/filename.ext on an Amazon S3 instance. 
Muitlple files are separated by vertical bar like |. 
Note that file names can not be entered separately but will be 
automatically generated using the file's name.
```

However, when using forward slashes, they are acting the way `|` is supposed to act and creating new files for each

For example, this in the CSV file:
<img width="238" alt="screen shot 2017-03-30 at 2 12 05 pm" src="https://cloud.githubusercontent.com/assets/1638128/24519375/ee0fc2ee-1552-11e7-9c6c-356c40e28ad8.png">

Results in this in EDD after import:
<img width="929" alt="screen shot 2017-03-30 at 2 12 48 pm" src="https://cloud.githubusercontent.com/assets/1638128/24519396/fe0bd61a-1552-11e7-91ae-4a34e2f0d036.png">

**Comment by sunnyratilal** [comment]
I believe in order to fix this, we'd need to remove `/` as one of the delimiters: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/admin/import/class-batch-import.php#L234

**Comment by pippinsplugins** [comment]
@sunnyratilal we can't; the `/` is used in some of the other columns.

**Comment by sunnyratilal** [comment]
Bug only exists if using relative URLs because means it bypasses PHP's `FILTER_VALIDATE_URL`

**Comment by cklosowski** [comment]
We've battled stuff like this before with #5513 as well.

**Comment by pippinsplugins** [comment]
Instead of appending the site URL to relative files, I've gone with a different approach where we simply don't use `/` as the delimiter if the first character of the string is `/`. I can't think of any scenario where `/` would be the first character on a string that is also using `/` as the delimiter.

It works properly in my tests.

**Comment by mintplugins** [comment]
This is still an issue because the string doesn't begin with a slash. The affected customer is attempting to enter AmazonS3 links - which don't begin with a slash. For example, amazonS3 file look like this in my setup:

<img width="1001" alt="screen shot 2017-10-12 at 2 03 58 pm" src="https://user-images.githubusercontent.com/1638128/31519129-423a1b2e-af56-11e7-94f6-bf5bb0257fcc.png">

**Comment by brashrebel** [comment]
I have another customer complaining about this exact issue. Importing S3 files by referencing `bucket/file.ext` as _[our docs prescribe](http://docs.easydigitaldownloads.com/article/1341-importing-products-from-csv)_.

**Comment by cklosowski** [comment]
Updating the milestone so we can re-address this.

**Comment by sunnyratilal** [comment]
I have played around with a few solutions here and none seem to work that still allow `/` as a delimiter and allow relative URLs at the same time.

I'll look again tomorrow with a fresh mind.

**Comment by cklosowski** [comment]
@sunnyratilal ok i'm going to kick this to 2.9

**Comment by pippinsplugins** [comment]
Punting this out of 2.9 for the time being.

**Comment by dgoldak** [comment]
Another report of this issue, preventing the ability to import downloads located on Amazon S3. https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7199

**Comment by mintplugins** [comment]
Resolved in https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7199
