### ISSUE TITLE
Lots of 'A non-numeric value encountered' errors with php 7.1

### ISSUE THREAD

**Issue by nextgenthemes** [easydigitaldownloads/easy-digital-downloads#5623]
As Travis shows here. https://travis-ci.org/easydigitaldownloads/easy-digital-downloads/jobs/217205739

**Comment by cklosowski** [comment]
Interesting, since i'm running PHP 7.1 locally and not getting them when I'm using EDD in testing. Related PR #5622

**Comment by cklosowski** [comment]
I've got 7.1 now installed for the CLI Too. going to take that PR that's opened and make an issue branch from it to fix the issues and get 7.1 added as well.

**Comment by cklosowski** [comment]
This is going to need to be done along with #5457.

What I'm finding is that I can fix unit tests for PHP 7.1...and they break in others, or I can fix them for others and they break in PHP 7.1

This tells me we have a ton of poisoned data from all the tests running, and updating them to be static fixtures should help that out.
