### ISSUE TITLE
wrong end date in query for "last_month" in EDD_stats class

### ISSUE THREAD

**Issue by hor-net** [easydigitaldownloads/easy-digital-downloads#5626]
In the last version of edd (2.7.6) the method setup_dates in EDD_Stats has changed from:

        public function setup_dates( $_start_date = 'this_month', $_end_date = false ) {

		if( empty( $_start_date ) ) {
			$_start_date = 'this_month';
		}

		if( empty( $_end_date ) ) {
			$_end_date = $_start_date;
		}

		$this->start_date = $this->convert_date( $_start_date );
		$this->end_date   = $this->convert_date( $_end_date, true );
	}

To:
        public function setup_dates( $_start_date = 'this_month', $_end_date = false ) {

		if( empty( $_start_date ) ) {
			$_start_date = 'this_month';
		}

		if( empty( $_end_date ) ) {
			$_end_date = time();
		}

		$this->start_date = $this->convert_date( $_start_date );
		$this->end_date   = $this->convert_date( $_end_date, true );
	}

This changes breaks the evaluation in EDD_Stats::convert_date of the end_date if the start_date is set to last_month. in fact $this->end_date is always set to time() instead of the last day of last month.

**Comment by pippinsplugins** [comment]
This has been fixed already https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5603
