### ISSUE TITLE
User ID not always set on customers for existing user accounts when importing payments

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#5627]
When importing payments that have existing user accounts, the `user_id` property of the customer records is not always properly set to the found user account.

See https://secure.helpscout.net/conversation/324879946/53918/?folderId=180505 for an example.

The fix is to update the customer at line 207 of the payment import class if a user ID is found:

```php
$customer = new EDD_Customer( $payment->customer_id );

if( empty( $customer->user_id ) ) {
	$customer->update( array( 'user_id' => $user->ID ) );
}
```

**Comment by pippinsplugins** [comment]
To test:

1. Reset store data from Downloads > Tools
2. Create one or more user accounts
3. Import a CSV of purchase records, at minimum mapping the email column
4. The customers will be created but no user ID will be connected

**Comment by cklosowski** [comment]
I've seen this in a few occasions locally. PR looks good. Can test tomorrow if no one else gets to it too

**Comment by pippinsplugins** [comment]
This fix was also tested on a customer's site that was experiencing the problem.

**Comment by brashrebel** [comment]
Finally got this working. "at minimum mapping the email column" mislead me to believe the "user" column wasn't needed and it is. If I import on `master` with both username and email set, the user ID is not attached. On `issue/5627` when importing with both user and email mapped, the user ID does get attached to the new customer.

**Comment by pippinsplugins** [comment]
@brashrebel can I see a screenshot of the mapping that did not work?

**Comment by pippinsplugins** [comment]
Nvm, re-read what you wrote. Merged.
