### ISSUE TITLE
Payment Export: Country Name - Report export improvement

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#5629]
Having the ISO country code is technically more accurate than the country name, but for ease of reading (and filing taxes) it's quicker to have the actual country name. Could an additional column be added called "Country Name" to the report export?

**Comment by pippinsplugins** [comment]
I don't see any reason why not.

**Comment by cklosowski** [comment]
@davidsherlock Are you referring to the Payment Exports?

**Comment by davidsherlock** [comment]
@cklosowski, yes I am.

**Comment by cklosowski** [comment]
I'm going to add both, I don't see any harm in making the sales export both human and machine readable at the same time.
