### ISSUE TITLE
Tax rate of 1 or less amounts to incorrect total

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#5635]
If you enter a tax rate (country or fallback) of 1 or less, the calculation is incorrect. Confirmed by @SDavisMedia

**Comment by mintplugins** [comment]
The tax calculation is working for me now. 

However, I'm not sure if this is related but if I enter a tax rate for a country/state, it is falling back to the fallback rate even when it shouldn't.

**Comment by cklosowski** [comment]
@mintplugins can you replicate that on master?

**Comment by mintplugins** [comment]
Hmm - it's not happening for me on master or `issue/5635` for me now. Maybe it was a weird cached situation or something. Disregard - this looks fine to me now 👍

**Comment by SDavisMedia** [comment]
This is working as it should for me for both tax rate entries. :+1:
