### ISSUE TITLE
`EDD_Payments_Query::get_payments()` may mess up global `$post`

### ISSUE THREAD

**Issue by felixarntz** [easydigitaldownloads/easy-digital-downloads#5636]
`EDD_Payments_Query::get_payments()` uses `wp_reset_postdata()` to reset the original post (as well as other globals), which generally works fine as long there _is_ a global `$wp_query` that has been run.

This is not always the case though. When editing a post in the admin, the `$post` global as well as other related globals are set manually. Since `wp_reset_postdata()` only looks at `$wp_query`, it doesn't work in this case, resulting in the last payment result of the query suddenly being the `$post`.

I had some custom logic in the admin editing screen for my downloads, and was querying payments for that download. This caused most functionality to break, since the `$post` was suddenly set to the payment, not the download anymore.

The following is an alternate version, that fixes that bug. Not optimal, but that's what I used for a quick fix (sorry, I altered the code directly, since it was critical :) ); we can probably improve that a bit more.

        public function get_payments() {

		do_action( 'edd_pre_get_payments', $this );

		$query = new WP_Query( $this->args );

		$custom_output = array(
			'payments',
			'edd_payments',
		);

		if ( ! in_array( $this->args['output'], $custom_output ) ) {
			return $query->posts;
		}

		if ( $query->have_posts() ) {
			$has_post = isset( $GLOBALS['wp_query'] ) && isset( $GLOBALS['wp_query']->post );
			$original_post = isset( $GLOBALS['post'] ) ? $GLOBALS['post'] : null;

			while ( $query->have_posts() ) {
				$query->the_post();

				$payment_id = get_post()->ID;
				$payment    = edd_get_payment( $payment_id );

				if ( edd_get_option( 'enable_sequential' ) ) {
					// Backwards Compatibility, needs to set `payment_number` attribute
					$payment->payment_number = $payment->number;
				}

				$this->payments[] = apply_filters( 'edd_payment', $payment, $payment_id, $this );
			}

			if ( $has_post ) {
				wp_reset_postdata();
			} elseif ( $original_post ) {
				$GLOBALS['post'] = $original_post;
			} else {
				unset( $GLOBALS['post'] );
			}
		}

		do_action( 'edd_post_get_payments', $this );

		return $this->payments;
	}

**Comment by cklosowski** [comment]
I've replicated the problem with the EDD Dev Tools plugin (which now contains the last 5 payments of a download) when editing the download.

And after the table is done and the class is called `edd_payment` is the value for `$post->post_type`, not `download`.

Going to see if I can work up a fix with the provided example.

**Comment by cklosowski** [comment]
Ok this one is a little tricky to replicate since it really only presents itself in a specific set of scenarios.

Easiest way is with the EDD Dev Tools (at latest `master`) and Edit a download.

You'll have to edit the `includes/downloads.php` file in Dev Tools to contain this `var_dump`
![screen shot 2017-06-23 at 1 28 15 pm](https://user-images.githubusercontent.com/1390124/27499292-fe27d2b8-5817-11e7-8299-7424531a42aa.png)

On `release/2.8` of EDD Core, you'll see an `ID` that matches the last `EDD_Payment` in the list table, and a `post_type` of `edd_payment`.

On `issue/5636`, you'll see the `Download ID` and `download`.

**Comment by cklosowski** [comment]
@pippinsplugins, mind just peeking over this? I feel pretty good about how it turned out, but just another set of eyes might be nice.

**Comment by pippinsplugins** [comment]
@cklosowski one other minor change posted to PR.

**Comment by cklosowski** [comment]
@pippinsplugins Fixed.

**Comment by pippinsplugins** [comment]
Looks good!
