### ISSUE TITLE
Payment History date filter not working

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/easy-digital-downloads#5637]
Reported by two separate customers today so far and confirmed on my local dev site and a live site. If you select a start and end date when viewing payment history, the results will get filtered but they will be wrong. Still trying to figure out a pattern. So far the actual results which get returned are confusing. But so far, very consistently wrong as in not actually from the specified date range.

**Comment by SDavisMedia** [comment]
Replicated here as well. It appears to break in `2.7.6`. `2.7.5` and before are all good, it seems.

**Comment by brashrebel** [comment]
Customer just replied with potentially relevant commentary:

> It's happening elsewhere - I just ran a EDD-VAT Submission - tried to get it to sort in Ascending order (to find all the zeroes) and it just "randomly" presented them in a different order!

**Comment by sunnyratilal** [comment]
There appears to be a bug in the SQL query; it's missing off the `wp_posts.post_date` condition in the `WHERE` clause.

`master`:
```sql
SELECT SQL_CALC_FOUND_ROWS wp_posts.ID FROM wp_posts WHERE 1=1 AND wp_posts.post_type = 'edd_payment' AND ((wp_posts.post_status = 'publish' OR wp_posts.post_status = 'pending' OR wp_posts.post_status = 'refunded' OR wp_posts.post_status = 'failed' OR wp_posts.post_status = 'revoked' OR wp_posts.post_status = 'abandoned' OR wp_posts.post_status = 'edd_subscription')) ORDER BY wp_posts.ID DESC LIMIT 0, 30
```

pre-2.7.5:
```sql
SELECT SQL_CALC_FOUND_ROWS wp_posts.ID FROM wp_posts WHERE 1=1 AND wp_posts.post_type = 'edd_payment' AND ((wp_posts.post_status = 'publish' OR wp_posts.post_status = 'pending' OR wp_posts.post_status = 'refunded' OR wp_posts.post_status = 'failed' OR wp_posts.post_status = 'revoked' OR wp_posts.post_status = 'abandoned' OR wp_posts.post_status = 'edd_subscription')) AND wp_posts.post_date >= '2017-03-01 00:00:00' AND wp_posts.post_date <= '2017-04-01 23:59:59' ORDER BY wp_posts.ID DESC LIMIT 0, 30
```

**Comment by sunnyratilal** [comment]
Bug was introduced in 60124d85433d967d9a0d49acba5abccb0d9f9361 where  `$this->date_filter_post();` was placed before the action call to `edd_pre_get_payments`.

`$this->date_filter_post();` is supposed to hooked on to `edd_post_get_payments` so needed to be moved down after the query had executed.

The current order meant that was removed before the payments query was executed.

**Comment by pippinsplugins** [comment]
@sunnyratilal let's actually hook it to `edd_post_get_payments` just in case it becomes necessary to unhook and/or modify it.
