### ISSUE TITLE
Discounts: Use once per customer does not respect case of codes

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#5642]
The `Use once per customer` setting on discount codes is designed to prevent customers from redeeming discount codes more than once.

If a discount code is created with capital letters, the use once setting will not work because we are using `strtolower` before comparing the applied discount to the already used discounts, but we are only using `strtolower` on one side of the comparison, not both.

Reported https://wordpress.org/support/topic/a-serious-issue-with-edd-discount-codes/

Related #5634

**Comment by pippinsplugins** [comment]
To replicate:

1. Create a discount with mixed capitalization, like `freeSTUFF`
2. Enable `One use per customer`
3. Purchase something and redeem the discount
4. Go back and try to purchase a new item with the same discount

**Comment by mintplugins** [comment]
Replicated on Master and confirmed fixed on `issue/5642`

<img width="708" alt="screen shot 2017-04-06 at 10 40 55 am" src="https://cloud.githubusercontent.com/assets/1638128/24760084/92f826ea-1ab5-11e7-924e-f791bf6dce45.png">

**Comment by SDavisMedia** [comment]
Also replicated on `master` and confirmed fixed on `issue/5642`. :+1:
