### ISSUE TITLE
Admin Responsive Issues

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#5644]
I regularly manage my store from my iPhone 6s Plus and I've noticed some responsive CSS issues within the admin panel/tables.

Here are some screenshots:

Checkbox width:

![2017-03-29 22 57 19](https://cloud.githubusercontent.com/assets/22668877/24799564/c429903a-1b93-11e7-8838-fa354d9df308.png)

Start and End Dates should be properly aligned:

![2017-03-29 22 57 32](https://cloud.githubusercontent.com/assets/22668877/24799569/d3064846-1b93-11e7-986a-5ec19a577bd9.png)

On a mobile device, the form fields would look better at full width:

![2017-03-29 22 58 04](https://cloud.githubusercontent.com/assets/22668877/24799580/e7a44b90-1b93-11e7-8c7e-2f4871e98b0c.png)

Customer management tab issue.

![2017-03-29 22 59 09](https://cloud.githubusercontent.com/assets/22668877/24799596/f3fd2a56-1b93-11e7-9f03-e4d5d10b584a.png)

**Comment by davidsherlock** [comment]
Following on from my previous post, I did further testing and discovered more responsive issues needing fixed to make stores easily manageable from a mobile device. All testing was done on an iPhone 6s Plus using Safari for compatibility reasons.

Discount code checkbox has incorrect width set.

![edd - discout edit screen](https://cloud.githubusercontent.com/assets/22668877/25048077/4ca759ee-2132-11e7-92fd-8c009c4ef365.png)

On purchase edit screen the download/product select would look better at 100% width to accommodate longer product titles.

![edd - edit purchase iphone 6s plus](https://cloud.githubusercontent.com/assets/22668877/25048087/5e8836d8-2132-11e7-8c5c-fdb5d135d22e.png)

Selects would look/function best at full width. The start/end dates should be stacked with the button at the bottom (with a margin) for best UX experience.

![edd - export page iphone 6s plus](https://cloud.githubusercontent.com/assets/22668877/25048117/877269f6-2132-11e7-889f-bdfd6dba7ec9.png)

As per above, the date boxes would look best look when split precisely to occupt 100% of the width. The button could be below with a margin.

![edd - export page 2](https://cloud.githubusercontent.com/assets/22668877/25048143/ac887f82-2132-11e7-9d8e-04d92afcdbf0.png)

On the payment history page the checkbox width has issues, additionally rather than showing no data, the primary key (the email address) would be best to be shown on a per order basis so it's easy to see orders in a glance (without hitting the expander).

![edd - payment history page iphone 6s plus](https://cloud.githubusercontent.com/assets/22668877/25048178/e0b8fa8e-2132-11e7-8182-cf2a376e2a22.png)

This is a pretty major one, on the download overview page, this is happening. This data should be within the drop down. 

![edd - product edit screen](https://cloud.githubusercontent.com/assets/22668877/25048201/0e03459e-2133-11e7-9fcc-20eeb21cbccb.png)

On mobile devices, these fields should be 100% width and stacked for best user experience and to easily see the file paths/names, change download names, etc.

![edd - purchase history edit iphone 6s plus](https://cloud.githubusercontent.com/assets/22668877/25048223/29b117c6-2133-11e7-8d45-91e9fc506c22.png)

Button would be best at 100% width with a margin separating it from the select.

![edd - recout stats iphone 6s plus](https://cloud.githubusercontent.com/assets/22668877/25048245/4e168970-2133-11e7-820b-5eaf0b4b97b9.png)

As per above, widths and margins need fixed for a usable user experience.

![edd - report logs iphone 6s plus](https://cloud.githubusercontent.com/assets/22668877/25048259/5d7ab0c6-2133-11e7-9632-bfd210d84d3e.png)

This is a small one, but the system info box isn't responsive.

![edd - system info iphone 6s plus](https://cloud.githubusercontent.com/assets/22668877/25048271/6f409230-2133-11e7-930e-ee470e2d6ab8.png)

While making the tables responsive easy (while maintaining WordPress standards isn't easy) a good solution here would be to make all the fields 100% so longer country names are visable.

![edd - tax edit](https://cloud.githubusercontent.com/assets/22668877/25048280/8193bac0-2133-11e7-9180-4eaa1191d5e9.png)

**Comment by pippinsplugins** [comment]
Thanks for all those screenshots @davidsherlock!

**Comment by davidsherlock** [comment]
Just a few additional fixes needed:

The spacing/margins between the checkboxes needs fixed.

![edd - checkbox spacing](https://cloud.githubusercontent.com/assets/22668877/25180093/90fedd8a-2504-11e7-922a-57a7f1fb129d.png)

The drop down "expander" currently has no purpose. Ideally it would show the author/vendor, assigned categories, creation date, etc.

![edd - order page expander](https://cloud.githubusercontent.com/assets/22668877/25180273/3fa2f77c-2505-11e7-9fe1-c3bba9413e26.png)

Radio buttons and tax page messed up:

![edd - tax page](https://cloud.githubusercontent.com/assets/22668877/25180350/8eb2426e-2505-11e7-95e3-06c222870db3.png)

**Comment by cklosowski** [comment]
The list:
- [ ] Payment History - Checkboxes
- [ ] Payment History - Search box alignment
- [ ] View Order Details - Address fields full width
- [ ] Customer Card Tabviews
- [ ] Add/Edit Discount Code - Checkbox widths
- [ ] View Order Details - Add new Download fields full width
- [ ] Tools - Fields full width and stacked
- [ ] Download List table - Wrapping issues
- [ ] Tools - Save button full width
- [ ] Reports/Logs - Buttons/fields width improvements
- [ ] System info is not responsive
- [ ] Responsive Tax settings
- [ ] EDD Settings checkboxes - Margins/Spacing
- [ ] Payment Method Icon setting needs help


Wont' Fix:
* Primary key of list table set to emails, WP Core doesn't support (from my knowledge) changing what is the primary key for different view ports, and ID is the primary key that allows the most functionality.
* Download files has been rewritten by the new repeatable fields
* The drop down "expander" currently has no purpose. Ideally it would show the author/vendor, assigned categories, creation date, etc. (This is an FES issue)


Cannot Replicate:
* Download list table issues (please verify all other addons are disabled when reporting, this look like something has the incorrect colspan or something)

**Comment by cklosowski** [comment]
@SDavisMedia @sunnyratilal could I get you guys to look this over for me?

**Comment by davidsherlock** [comment]
@cklosowski, which branch is the new file upload meta box functionality featured on? Keen to try this out as I might fork it for my new EDD audio player plugin.

**Comment by sunnyratilal** [comment]
The radio buttons are being stretched out:
![image](https://user-images.githubusercontent.com/1525554/31045838-5b87953c-a5e4-11e7-8b32-d559e6721742.png)

Besides that, everything looks _much_ better! 👍

**Comment by davidsherlock** [comment]
@cklosowski, great work on the responsive fixes. I did, however, notice a few more minor ones needing fixed:

![screenshot 2017-09-30 22 31 06](https://user-images.githubusercontent.com/22668877/31049767-441ddfca-a632-11e7-9cde-42fef732aaaf.png)

Recount stats select box width.

![screenshot 2017-09-30 22 29 40](https://user-images.githubusercontent.com/22668877/31049769-55f109de-a632-11e7-9aee-1a17b23b8575.png)

Discounts edit/add checkbox width.

![screenshot 2017-09-30 22 29 15](https://user-images.githubusercontent.com/22668877/31049772-5fe71bfe-a632-11e7-8a9c-010120706ec3.png)

Customer count text issue.

![screenshot 2017-09-30 22 28 22](https://user-images.githubusercontent.com/22668877/31049779-91a17c98-a632-11e7-9e73-392ed54b5781.png)

Downloads page checkbox width issue.

![screenshot 2017-09-30 22 28 06](https://user-images.githubusercontent.com/22668877/31049787-9f16bbc2-a632-11e7-8538-88b185aaa663.png)

Overlapping text on customer edit/view screen.

**Comment by sunnyratilal** [comment]
Unable to reproduce with the `Recount Stats` box:
![image](https://user-images.githubusercontent.com/1525554/31049902-9b6d3d40-a635-11e7-89b0-ee6cbf005906.png)

Unable to replicate discounts edit/add checkbox width:
![image](https://user-images.githubusercontent.com/1525554/31049948-ac8131b2-a636-11e7-8bb9-2fbf3e167b8e.png)

Unable to replicate overlapping text:
![image](https://user-images.githubusercontent.com/1525554/31049952-c2f8ed18-a636-11e7-8bad-8421dea81126.png)

**Comment by sunnyratilal** [comment]
@cklosowski I believe this is ready to merge

**Comment by cklosowski** [comment]
@sunnyratilal radio buttons fixed.

**Comment by sunnyratilal** [comment]
Radio buttons look great now!
