### ISSUE TITLE
If Customer Name/Info blank upon new purchase, use data from checkout. 

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#5646]
Currently, if a customer has no name entered (Unnamed Customer), and then they buy a new product and fill out their name on checkout, that information does not get added to the customer record. 

I propose that if a Customer has blank data and completes a payment, that newly entered info be added to the customer.

**Comment by sunnyratilal** [comment]
PR opened at #5664 and ready for testing!

**Comment by mintplugins** [comment]
@mintplugins Note to self to test this on Monday

**Comment by mintplugins** [comment]
@sunnyratilal It's not working for me here. 

Here's the process I am taking:

1. Using the Free Downloads extension, I "purchase" a free product - which auto-creates an EDD user but not a WordPress user. The customer name and data is blank as well (correctly).

2. I then (theoretically) decide I like this store and actually buy a product that costs money. At checkout, I also register a user account and fill in my first and last name.

3. I get sent an email asking me to verify my account. When I do, I get access to the account. However my First and Last name in the customer profile are still blank.

**Comment by pippinsplugins** [comment]
Moved to 2.8 for further development.

**Comment by SDavisMedia** [comment]
Doesn't appear to be working for me either. I used the same testing method as Phil. When completing an actual purchase and providing a name at check (step 2 above), however, I got an error when submitting the checkout form:

```
Notice: Undefined index: user_id in /Applications/MAMP/htdocs/edd/wp-content/plugins/easy-digital-downloads/includes/process-purchase.php on line 78

Warning: implode(): Argument must be an array in /Applications/MAMP/htdocs/edd/wp-content/plugins/easy-digital-downloads/includes/process-purchase.php on line 97
```

**Comment by mintplugins** [comment]
I'm going to remove the 'needs testing' for now.

**Comment by cklosowski** [comment]
ok @SDavisMedia and @mintplugins I think I got this working. Give it a whirl

**Comment by mintplugins** [comment]
It looks like it worked as the name was added to the customer. However, I also got this output on the screen. Not sure why yet:

```
array(6) { ["id"]=> int(38) ["email"]=> string(33) "johnstonphilip+56465646@gmail.com" ["first_name"]=> string(4) "Test" ["last_name"]=> string(4) "Test" ["discount"]=> string(4) "none" ["address"]=> array(0) { } } 
Warning: Cannot modify header information - headers already sent by (output started at /Users/philjohnston/Documents/wps/edd2.dev/wp-content/plugins/easy-digital-downloads/includes/process-purchase.php:77) in /Users/philjohnston/Documents/wps/edd2.dev/wp-includes/pluggable.php on line 1182
```

**Comment by mintplugins** [comment]
Confirmed It's still happening. I got it 2 tests in a row.

**Comment by cklosowski** [comment]
Gah, forgot a debug line :P https://github.com/easydigitaldownloads/easy-digital-downloads/pull/5664/files#diff-7f3dc644a147bd7fae6a2a48439fed9fR77

Other than that @mintplugins it's working?

**Comment by cklosowski** [comment]
Should be fixed @mintplugins. just pull latest.

**Comment by mintplugins** [comment]
@cklosowski Working great now! 👍
