### ISSUE TITLE
edd_delete_option() does not work

### ISSUE THREAD

**Issue by joelworsham** [easydigitaldownloads/easy-digital-downloads#5647]
This function unsets the key you pass and then attempts to update the new settings array to the database.

```
// First let's grab the current settings
$options = get_option( 'edd_settings' );

// Next let's try to update the value
if( isset( $options[ $key ] ) ) {

	unset( $options[ $key ] );

}

$did_update = update_option( 'edd_settings', $options );
```

This is all fine and well, but the issue is in updating the option. `edd_settings_sanitize()` is hooked into updating this option and there's a line in there that is problematic:

```
// Merge our new settings with the existing
$output = array_merge( $edd_options, $input );
```

The issue is that the global `$edd_options` used here *still contains the value we're trying to delete*. So by merging, we're simply adding that value back into the settings. This completely overrides what `edd_delete_option()` is trying to do. It seems that the simple fix is to unset this key from the global within `edd_delete_option()`. So like this:

```
global $edd_options;

// First let's grab the current settings
$options = get_option( 'edd_settings' );

// Next let's try to update the value
if( isset( $options[ $key ] ) ) {

	unset( $options[ $key ] );

}

if( isset( $edd_options[ $key ] ) ) {

        unset( $edd_options[ $key ] );

}

$did_update = update_option( 'edd_settings', $options );
```

**Comment by cklosowski** [comment]
Quick way to test this out with this code in console:
```
<?php
edd_update_option( 'testing_setting', 'this is a test' );
var_dump(edd_get_option( 'testing_setting' ));
edd_delete_option( 'testing_setting' );
var_dump(edd_get_option( 'testing_setting' ));
```

On `master` you'll see:
`this is a test` twice

On `issue/5647` you'll see:
`this is a test`
`false`

**Comment by SDavisMedia** [comment]
Replicated bug on `master`. Confirmed fixed on `issue/5674`. :+1:
