### ISSUE TITLE
Search Filters

### ISSUE THREAD

**Issue by kiarashi** [easydigitaldownloads/easy-digital-downloads#5651]
Not sure if it's been asked before (either by me or by someone else) but will EDD offer search filters (e.g. a slider for price filters, checkboxes with tags/categories/custom taxonomy) in the future?

**Comment by davidsherlock** [comment]
@kiarashi, a better way of handling this is using FacetWP which works with EDD out the box. This allows you to create a fully AJAX filtering interface using different 'facet' options such as sliders, checkboxes, radio buttons, etc without messing around with query_args and alike.

**Comment by davidsherlock** [comment]
It's also a cleaner solution since it utilizes caching and has no page reloads.

**Comment by kiarashi** [comment]
Hmm, most people I know expect filters to be available inside the core without the need of an additional plugin; as one can see with woocommerce, prestashop, etc.  I was hoping something similar could be seen in EDD too (in the future). 

But I agree, the plugin you mentioned is a good alternative.

**Comment by pippinsplugins** [comment]
We have considered it but at this time we do not have plans to add those kind of filters.
