### ISSUE TITLE
Improve checkout field flexibility

### ISSUE THREAD

**Issue by ghost1227** [easydigitaldownloads/easy-digital-downloads#5652]
Right now, there's no way for plugins to add custom fieldsets to the checkout form. This has resulted in some seriously janky implementations like this: 

<img width="802" alt="screen shot 2017-04-06 at 9 37 23 am" src="https://cloud.githubusercontent.com/assets/36433/24759955/c142798c-1aac-11e7-8267-56575477f8d1.png">

Let's add some new actions to make it easier for plugins to extend the checkout form.

**Comment by pippinsplugins** [comment]
PR looks good to me.
