### ISSUE TITLE
Possible fatal error with strict PHP standards in EDD_Payment::get_meta

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#5658]
```
$bad_meta = $meta[0];
unset( $meta[0] );
```
With some error handling configs this can trigger a warning of:
```
PHP Fatal error: Cannot unset string offsets in /home/yrevamp/public_html/wp-content/plugins/easy-digital-downloads/includes/payments/class-edd-payment.php on line 1784
```

This was an attempt to fix #5228, but I think we'll have to allow the merge to take care of it, which it should.

**Comment by sunnyratilal** [comment]
After discussion with @cklosowski, a fix is going to be made for the Simple Shipping upgrade routine and he's going to send a patched version to the customer.

For the time being, this is being punted.

**Comment by cklosowski** [comment]
Sorry @sunnyratilal going to have to bring this one back into 2.7.8. I got word from the customer that it's not a Simple Shipping bug, and my attempt to circumvent the issue failed. I've requested a login to their site so I can get a coy of the meta that's failed.

Related ticket: https://secure.helpscout.net/conversation/347654732/57158/?folderId=375162

**Comment by sunnyratilal** [comment]
No worries, I'll see if I can make any further progress here.

**Comment by sunnyratilal** [comment]
@cklosowski I am correct in saying this error is getting triggered when a string is being read as `$meta` in lieu of an `array`?  If this is the case, can we not do an `is_array()` check so that the conditional becomes `if ( is_array( $meta ) && isset( $meta[0] ) ) {`

**Comment by cklosowski** [comment]
@sunnyratilal I believe so, but I want to see exactly what this meta looks like first, so we aren't assuming.

**Comment by cklosowski** [comment]
@sunnyratilal ok, I think what you're suggesting is valid. Let's go that route.
