### ISSUE TITLE
Software Licensing: activate plugin on a sub site, see updates on the Network > Plugin page

### ISSUE THREAD

**Issue by Tymvie** [easydigitaldownloads/easy-digital-downloads#5661]
It seems that the third recipe does not work: http://docs.easydigitaldownloads.com/article/937-why-do-my-plugin-updates-not-show-up

Steps to reproduce:
1. Activate plugin on sub site `ok`
2. Activate license key on sub site `ok`
3. Visit Plugins page on sub site (or just trigger the update check somehow) `ok`
4. This caches the available plugin updates in a network-wide transient `ok`
5. Now you can visit Network > Plugins and see the update 

We do not see the update because the `$_transient_data` is returned too early:
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/EDD_SL_Plugin_Updater.php#L91

**Comment by pippinsplugins** [comment]
Hi there!

Please go ahead and open a support ticket through our support portal: https://easydigitaldownloads.com/support

We use this GitHub repository for core EDD development tracking only.
