### ISSUE TITLE
Reports: Earnings - "This Month" shows future dates in the month

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/easy-digital-downloads#5662]
When viewing the earnings report for `This Month`, the days in the month that have yet to arrive are shown in the report.

![image](https://cloud.githubusercontent.com/assets/1254870/25046503/d12aebc8-20ff-11e7-9c01-3112e19be1bd.png)

It would be great to show month to date, as it isn't really helpful to see dates that haven't arrived yet.

**Comment by pippinsplugins** [comment]
I don't actually think we should change the `This Month` view as that logically represents a calendar month. Instead I think we should introduce a new default view that shows the last 30 days.

**Comment by sunnyratilal** [comment]
I agree with @pippinsplugins

**Comment by sunnyratilal** [comment]
PR opened at #5665 and ready for testing!

**Comment by sunnyratilal** [comment]
PR opened at #5665 and ready for testing!

**Comment by pippinsplugins** [comment]
Works perfectly, merged.
