### ISSUE TITLE
Give better instruction for "Email already used" error on checkout.

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#5669]
When checking out, if you already have a WordPress user account and try to create a new user account using the already-used email, it simply says "Email already used". 

While most people would realize they should log in since their email has already been used, people like me don't realize that :)

I propose we add a simple instruction to that so the error message becomes "Email already used. Log in or use a different email to complete your purchase."

**Comment by pippinsplugins** [comment]
Looks good to me.
