### ISSUE TITLE
edd_get_users_purchased_products returns payments with any status

### ISSUE THREAD

**Issue by stephywells** [easydigitaldownloads/easy-digital-downloads#5671]
$status isn't used in the function `edd_get_users_purchased_products( $user = 0, $status = 'complete' )`. All payments are being returned.

It would be ideal if there were more filtering options for the new customer object to cut down on queries so $customer->payment_ids could only include completed payments.

**Comment by pippinsplugins** [comment]
Thanks @stephywells, we can get that fixed!

**Comment by chriscct7** [comment]
Related: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5680
