### ISSUE TITLE
Include Tax Rates data in settings export/import

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#5673]
Currently, the **Tax Rates** data is not included in the EDD settings export. It only includes the **Fallback Tax Rate** data.

**Comment by cklosowski** [comment]
This should do it, even has backwards compatibility checks so that if you import a pre-2.8 export file it still imports the settings.

In addition I removed a call to `screen_icon` which was removed when the WP Admin was redesigned...so it outputs nothing anymore.

**Comment by pippinsplugins** [comment]
Works great, merged.
