### ISSUE TITLE
Add hi-res banner

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/easy-digital-downloads#5675]
Right now we have these images:
![Screen Shot 2017-04-20 at 3.11.18 PM](http://static.gitscout.com/45a70badb2e31e7a47f3767ba6d4062b9a8baacbd8a9fc04768c19b64a9b4b04.png)
But we are allowed one more for hi DPI supported screens. [This super old article](https://make.wordpress.org/core/2012/07/04/fun-with-high-dpi-displays/) indicates that `banner-1544x500.jpg` is also supported and if you look at popular plugins like Jetpack and WooCommerce you'll see their using those sizes. [This post and discussion](https://make.wordpress.org/meta/2017/03/30/announcing-the-new-wordpress-plugin-directory/#comment-8806) indicate some clarification may be pending though so @cklosowski is seeking guidance directly.

Anyway, it would be nice to have a crisp hi res banner.

**Comment by cklosowski** [comment]
@SDavisMedia can you get one of these created with dimensions of:
`1544 x 500` and drop it into the brand assets of Dropbox? I'll get this going to see if we can make it happen in a point release.

**Comment by SDavisMedia** [comment]
Coming up with something now.

**Comment by SDavisMedia** [comment]
Been looking at different banners for a while now. Really torn on what we should do. I spent some time getting fancy and actually ended up back at something suuuuper simple, much like bbPress and WP Super Cache. Need to know how y'all feel about that. Take note that the tagline is removed. Cc: @pippinsplugins 

![banner-1544x500](https://user-images.githubusercontent.com/2359131/29598776-f4fab0a6-877f-11e7-849d-a6ed4d587cc3.png)

More than willing to get more fancy.

**Comment by brashrebel** [comment]
I like what you've done here @SDavisMedia. I thought maybe there were a few little improvements which could be made though so, since I know a lot about design, I went ahead and made for you. Here you go:
<img width="1019" alt="screen shot 2017-08-23 at 9 31 20 am" src="https://user-images.githubusercontent.com/4993131/29618420-171d1c62-87e6-11e7-8051-3a58d599ff25.png">

**Comment by SDavisMedia** [comment]
I don't think I've ever laughed so hard so early in the morning. 😂 I love it

**Comment by SDavisMedia** [comment]
I don't think I've ever laughed so hard so early in the morning. 😂 I love it

**Comment by pippinsplugins** [comment]
YES YES YES! That's it @brashrebel!

**Comment by SDavisMedia** [comment]
LOL I'm taking the thumbs up on my comment as vote yes. Uploading the banner to the Dropbox, @cklosowski.

**Comment by cklosowski** [comment]
This is done and pushed to .org
<img width="1137" alt="screen shot 2017-09-11 at 1 19 32 pm" src="https://user-images.githubusercontent.com/1390124/30295002-f3a0f2fa-96f3-11e7-884a-1a80acd9f24f.png">
