### ISSUE TITLE
Collect some up-to-date, compelling testimonials and add to the readme

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/easy-digital-downloads#5676]
We have a few on our [features page](https://easydigitaldownloads.com/edd-features/) but we would like to have some quotes on our readme as well. Should look at some of our old ones and also gather some newer ones too.

**Comment by cklosowski** [comment]
@brashrebel I think this is a great idea. Can you spearhead this and get the readme updated with these? I'm going to milestone it for the 2.9 release, but if we get it done earlier it can go in the next point release.

**Comment by brashrebel** [comment]
@cklosowski yes, I'd like to move forward with this. I'm working in Trello to build a list of contacts for soliciting testimonials and will also be looking through our survey data. I can definitely take this on.

**Comment by cklosowski** [comment]
Punting to 3.0

**Comment by sunnyratilal** [comment]
@brashrebel Will this be done for 3.0 or shall I punt to 3.1?

**Comment by brashrebel** [comment]
We have a few new ones received and drafted within our site. I could probably squeeze it in. Anyone have an opinion on where in the readme a few testimonials would be best?

**Comment by cklosowski** [comment]
@brashrebel I'd be curious what the ones we want to use are about. It'd be awesome to kind of nest them under the subheads they support. Like for instance if one is about ease of use, the first heading in our main Readme section is `Sell effortlessly`. A quite supporting that would go great after this topic and before the 'Localized for your language' section.

**Comment by cklosowski** [comment]
@brashrebel Do we have progress for this? As we get closer and closer to 3.0 I'd like to finalize things like the readme earlier rather than later, so we don't miss it in the rush of pushing to the beta.

**Comment by pippinsplugins** [comment]
@cklosowski see `Testimonials` update here https://trello.com/c/IwjJggEb/1178-december?menu=filter&filter=wordcam

**Comment by brashrebel** [comment]
Heck yeah @cklosowski. We've got an abundance of testimonials collected and still coming in. I can pick out a few of the very best ones for the readme if you like, unless you want to do it yourself.

**Comment by cklosowski** [comment]
@brashrebel Go ahead and get a few that you think fit, and we'll get them into the readme.

**Comment by brashrebel** [comment]
We've collected a _lot_ of new testimonials lately. Here are a few of my favorites which we can use in the readme:

> If anyone asks me what they should use for downloadable products on their WordPress site, it’s a no-brainer as far as EDD goes.
Bob Dunn - BobWP

> If you're searching for a WordPress plugin to sell digital products, EDD is first class.
Bernhard Kux - JSON Content Importer

> I started an online music supply with EDD this year and I am loving it. I purchased the EDD Extended Pass to set up a marketplace where I sell original, royalty-free music and my investment has already paid for itself in the first 6 months. Freakin' love it!
Christopher Postill - Sounds Like an Earful

> After trying various e-commerce plugins to sell digital products and subscriptions on multiple websites, we decided to give EDD a try. It's been 5 years, and we never looked back. In comparison to other e-commerce plugins, EDD is lightweight, stable, fast, straightforward to use, and has one of the richest add-ons environment available on WordPress.
Nicolas Martin - Flea Market Insiders

> EDD is a great tool for selling something on your website. I use it to sell a service and found the setup to be easy.
Tara Claeys - Design TLC

> Why would anybody use any other plugin to sell digital products? If you want an easy-to-implement checkout cart, EDD does everything you need. And it's easy to use for a simpleton like me. Not having to worry about how money gets from our website to our Stripe and PayPal accounts is a magical feeling.
Joe Howard - WP Buffs

> I've never considered selling on any other platform than Easy Digital Downloads. No other platform is built with digital products in mind that has the features and years of experience that EDD has.
Scott Deluzio - WP1099

> EDD has been a long standing, rock-solid e-commerce solution for WordPress. The team lives and breathes WordPress, understand the platform, and is embedded in the community. 
Joe Casabona - Creator Courses

There's a lot more where these come from. @cklosowski you want to pick favorites or let me? And you want a PR against...develop? Or which branch?

**Comment by cklosowski** [comment]
@brashrebel I you can pick a few. I'd like them to be full testimonials, especially the one from Christopher since it mentions the Extended Pass. I'd say go ahead and pick 4 or 5.

Create a branch from `release/3.0` and submit the PR against `release/3.0`

**Comment by brashrebel** [comment]
Okee dokee, there you go @cklosowski! I added much more than was requested and stepped slightly outside of the scope of the issue. But I figure it is easier to trim down than figure out what more to add.

Let me know if you would like me to make any changes! I know there's a lot.

**Comment by DrewAPicture** [comment]
Merged #7159. Thanks @brashrebel!
