### ISSUE TITLE
Large product CSV exports include duplicate entries and missing products

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/easy-digital-downloads#5678]
This has been oh so much fun tracking down. Here's what I've discovered:

For stores with a large number of products (tested with as many as 5k+ and as few as 2.7k), a product CSV export generates a file which has the _correct number of items_ but the items are not all correct. *Some* of those items are duplicates while others are missing.

For example, if I had one product for every letter of the alphabet, I'd run the export and there would be 26 items. But there might be four "J"s and no "V", "L" and "Q". I encountered it first in [this ticket](https://secure.helpscout.net/conversation/351557376/57605/?folderId=448801) and then was able to replicate locally after removing the duplicates from that customer's store, importing them into mine and exporting again. Some products would appear in the export more times than they appear in WordPress.

**Comment by pippinsplugins** [comment]
@brashrebel could you try adding `'orderby' => 'ID'` to `get_data()` and let me know if that works.

**Comment by brashrebel** [comment]
@pippinsplugins that appears to have worked! My CSV after that change now seems to match exactly what's in WP. Would love to know how you figured that one out. 🕵️

**Comment by pippinsplugins** [comment]
Excellent! PR incoming.
