### ISSUE TITLE
EDD Success Page vs. View Invoice

### ISSUE THREAD

**Issue by KrashKartMedia** [easydigitaldownloads/easy-digital-downloads#5681]
As of now, When We use the EDD Shortcode: [edd_subscriptions] or [purchase_history], there is a link to View Invoice or View Details and Downloads.

See: https://cloudup.com/c3E7BGRGv4P

When you click on "View Invoice" or "View Details" link, it takes you back to the success page.
What we would like to see, is this take you to the purchase history. 

Our Issue:

As of now, we have our clients purchase a download, and we want to take them to a success page with a gravity form so they can fill out a little more information.  Then, when the user goes to view the invoice, or details, they are taken to a page with the {edd_subscriptions} shortcode.

So essentially, kind of like WooCommerce does. After checkout, they see a success page 1 time, and never again.

Please let me know if you need more clarification. 
Happy To Provide a video demo or jump on a hangout call.

**Comment by cklosowski** [comment]
@KrashKartMedia We've already got this issue logged in #3529. Thanks for our feedback.
