### ISSUE TITLE
Can't remove the "offer" schema

### ISSUE THREAD

**Issue by DarioBF** [easydigitaldownloads/easy-digital-downloads#5682]
Hello!
I'm trying to remove the Offer schema from generated on [purchase_link] shortcode, but it's impossible to undo the apply_filters: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/template-functions.php#L772

I've tried with remove_all_filters with no results. Also tried overriding the apply_filters, neither again.

How can I solve this issue? It should be optional to print the schema...

Regards!

**Comment by cklosowski** [comment]
@DarioBF You should be able to simply use the following:
`add_filters( 'edd_add_schema_microdata', '__return_false' );`

Github is used for development tracking only. If you need further support please use our support form at:
https://easydigitaldownloads.com/support
