### ISSUE TITLE
Card views should use is_callable, not function_exists

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#5687]
Our card views all use a dynamic set of views with callback functions, however if you try and integrate with the card views within a Class, you do not have a function but a method, which `function_exists` will return `false` for.

To test this you can try and register a new view within a class with something like:
```
private static display_view( $customer ) {
```

And then register your view to have a callback of `Class_Name::display_view`, however this will fail on the `function_exists`. Changing to `is_callable` allows this to work in both a function and a static method.

**Comment by cklosowski** [comment]
Easy way to test this is with the EDD Dev tools extension. On EDD `master`, while the tab is registered, clicking the tab takes you to the main Customer view, where as on `issue/5687` you will see the registered view.

**Comment by pippinsplugins** [comment]
I think we need to use `call_user_func` [here](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/bde52160cec6d9edc3f26220a68a36e2d24ee5b1/includes/admin/customers/customers.php#L167) so that we can use non-static classes / methods for our callbacks.

**Comment by cklosowski** [comment]
Updated
