### ISSUE TITLE
Add EDD_Customer object to complete purchase hooks

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#5690]
Actions like `edd_complete_purchase` currently do not provide any access to the `EDD_Customer` object. The payment ID is available but accessing the customer requires setting up a new instance of `EDD_Customer`.

We should add the customer object as a parameter to the `edd_complete_purchase` hook and possibly others.

**Comment by cklosowski** [comment]
If we do this we'll need to be sure we add it also inside #5453

**Comment by sunnyratilal** [comment]
I've added the objects to the hook - we could refactor `edd_email_purchase_receipt()` to accept an `EDD_Payment` object as a parameter which would reduce the calls to `edd_get_payment_` methods from within the method.

**Comment by cklosowski** [comment]
@sunnyratilal I think we still need to support the ID for backwards compatibility, but I see no harm in avoiding all the calls to `edd_get_payment_` instead of just instantiating a single `EDD_Payment` object once we're within the function.

**Comment by sunnyratilal** [comment]
The `$payment_id` is still passed as the first parameter.

**Comment by cklosowski** [comment]
@sunnyratilal correct, but what i'm saying is all the calls to `get_` could be avoided if we simply did ```
$payment = edd_get_paymetn( $payment_id );
$payment->email
```

The only difference is that we need to maintain the main `meta` content for all the hooks.

**Comment by sunnyratilal** [comment]
Ah, I misunderstood :)
