### ISSUE TITLE
Changing currency & prices based on User's IP

### ISSUE THREAD

**Issue by PhoenixA** [easydigitaldownloads/easy-digital-downloads#5698]
I have 2 payment gateway's, out of which 1 payment gateway requires that the site uses a specific currency. So, what I am trying to accomplish is changing the currency & prices for users based on their IP. 

I am thinking if setting EDD_USE_PHP_SESSIONS to true will be able to help with this. I am succesful in getting user's country from her IP via ipinfo.io, creating a php session... I have spent many days going through EDD's documentation and don't seem to find any solution. Please guide me in the right direction, also apologies if this is not the right place to ask this question.

Thanks.
Abhi

**Comment by pippinsplugins** [comment]
Check out the Currency Switcher plugin: https://aelia.co/shop/currency-switcher-for-easy-digital-downloads/

For future questions like this, please use our support page: https://easydigitaldownloads.com/support
