### ISSUE TITLE
High priced item tax not displaying within the admin panel

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#5699]
I put through a product valued at £12,000 to test calculations on an extension I am building for EDD. I noticed an issue with the admin display of high tax amounts, here is a screenshot:

![screenshot 2017-05-01 23 39 15](https://cloud.githubusercontent.com/assets/22668877/25597620/a98f2126-2ec7-11e7-8b63-2d89baa00e4e.png)

Notice how the tax isn't displayed but it was correctly recorded within the `cart_details` array:

```
[cart_details] => Array
        (
            [0] => Array
                (
                    [name] => High Price Item
                    [id] => 2109
                    [item_number] => Array
                        (
                            [id] => 2109
                            [quantity] => 1
                            [options] => Array
                                (
                                    [quantity] => 1
                                    [price_id] => 0
                                )

                        )

                    [item_price] => 12000.35
                    [quantity] => 1
                    [discount] => 0
                    [subtotal] => 12000.35
                    [tax] => 2400.07
                    [fees] => Array
                        (
                        )

                    [price] => 14400.42
                )

        )

```

**Comment by cklosowski** [comment]
Probably just a limit based on the element size. I'll look into it.

**Comment by cklosowski** [comment]
so interestingly enough, this was due to having a `type="number"` attribute. The price column is a `type="text"` so it doesn't display this type of behavior, but change it to a `type="number"` and it does.

@SDavisMedia you have any insight on this? I was able to replicate it with a product costing `12000.35` and a tax rate of `25%`

**Comment by davidsherlock** [comment]
@cklosowski, I believe this is due to the way currency amounts are formatted like strings with comma separation and alike used, The `type="number"` attribute does not support this I believe and thus causes problems unless `type="number"` is used.
