### ISSUE TITLE
Customer user account deletion functionality

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#5707]
One of the more common customer enquiries I receive is to delete a customers account because they are no longer needed (or wanted) due to a clean up. Usually it's not deleting a customer record per say, but a Wordpress user account associated with the customer. Because everything is stored transactionally purchase history wise this shouldn't create any issues unless they are a vendor or a user receiving commissions (which could both be checked at time of deletion).

From a UX/UI point of view it would be useful to have the ability to enable this functionality within the EDD customer account page so the customer has the ability to delete the account if they wish.

**Comment by pippinsplugins** [comment]
While this is certainly a process that does have to happen in some cases, I don't feel this is ever a feature we can enable, at least not in the core plugin.

Deleting a user account is one thing. Deleting a customer records and the associated transactions is entirely another. For example, a customer records should rarely ever be deleted, but a user account could be easily deleted. Deleting a customer breaks transaction records.

**Comment by JaxomUK** [comment]
Hi Everyone.
I am new to EDD but am finding it a lot of fun to work with and am also enjoying the github conversations that are both interesting and informative.
I thought I would pipe in on this issue as it effects the GDPR (Global Data Protection Regulations) that come in to force later this year and apply to all business operating or providing the ability to be viewed online in any EU country.  An Individual must be able to delete there profile but as a business we are required to maintain there records for 5 years. So you are only allowed to delete the actual profile account not the sales account. It might be worth looking at building a plugin that would delete the profile and zip file the account data this way the client has the ability to delete there account but the website owner still maintains the account data. Just an Idea.

**Comment by davidsherlock** [comment]
Thanks for your reply @JaxomUK, some interesting information here since I am based in the UK myself! Can you define further the following statement:

> apply to all business operating or providing the ability to be viewed online in any EU country

"Viewed Online" is narrow in scope, can you expand on this a bit or link to reference articles in relation to the EU?

**Comment by lalunecreative** [comment]
If this actually comes to fruition there needs to be an option to allow this in user history or something relevant on the FRONT end. We actually disable access to the wordpress dashboard for our users, not only for security reasons, but because EDD provides all of the same information via the front end shortcodes, and we only use the EDD account page. I do agree that this needs to be an option at some point with the ability to archive a clients details.

**Comment by pippinsplugins** [comment]
I've spent a while thinking about this and have decided that we will not be implementing this in the core EDD plugin. I don't feel there is adequate enough demand for it and so it is not a feature that should take up UX.

This could change in the future but at this time I'm going to close as wontfix.

**Comment by cklosowski** [comment]
👍
