### ISSUE TITLE
Invoice details input field width improvement

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#5714]
As per my previous suggestions regarding responsive improvements, I feel the width of the invoice details (customer address, zip code, etc) fields could be extended to better utilize the space available on desktop view.

Here is a screenshot to demonstrate:

![screenshot 2017-05-06 21 37 31](https://cloud.githubusercontent.com/assets/22668877/25775848/790967fe-32a6-11e7-9bcb-04643b535a26.png)

As you can see, scrolling is required to view the full address street details which isn't very efficient when quickly viewing the customer details.

**Comment by cklosowski** [comment]
@davidsherlock I'm assuming this is our `Billing Address` metabox? Yours states `Invoice: Address`, but contains all the same input fields. I just want to make sure that what you are showing is Core and not the one for EDD Invoices or something similar.

Granted I see that the space can be optimized better in EDD Core, but I want to make sure we don't need to open issues in other places as well.

**Comment by davidsherlock** [comment]
@cklosowski, I am referring to core EDD which appears to use the same field widths as the invoice addition.

**Comment by sunnyratilal** [comment]
@SDavisMedia I've opened a PR here and made the fields bigger, but they look a bit _too_ big. Would love your input here? Perhaps the width should be 95% to allow for some breathing room between the gutters of the columns?

![image](https://user-images.githubusercontent.com/1525554/30828480-b398589a-a235-11e7-802b-e4b6b41494e5.png)

**Comment by SDavisMedia** [comment]
@sunnyratilal I like anywhere from 90%. I think it looks best and handles responsiveness well.

Side note, not sure why we're forcing the zip field width. Think we need that? It gets ugly at certain screen widths. Seems pretty unnecessary.

**Comment by sunnyratilal** [comment]
@SDavisMedia this better?

![image](https://user-images.githubusercontent.com/1525554/30906926-31bd401e-a371-11e7-83da-48b8acd7e005.png)

**Comment by sunnyratilal** [comment]
The ZIP field wasn't a _forced_ width as such, I kept the `medium-text` class applied because it just looked odd (to me) having a ZIP field that large.

**Comment by cklosowski** [comment]
Looks like we have some intermediate widths where we break down a bit if you change the browser size but I believe that's more of an issue with the Chosen system, since it's the Chosen select fields.

:+1: from me.
