### ISSUE TITLE
Amazon Payments Stops ALL payments (all gateways) and even shows error on Profile page

### ISSUE THREAD

**Issue by jcollake** [easydigitaldownloads/easy-digital-downloads#5716]
AWS is throwing a 'misconfigured' error, despite being configured properly (or it was before the last update weeks/months ago, afaik). It was popularly used. Then an update came and broke the site and it has never been resolved. I've got little to not clues, because I've found none.

**Comment by pippinsplugins** [comment]
Hi there!

Please go ahead and open a support ticket through our support portal: https://easydigitaldownloads.com/support

we use GitHub for development tracking only.

**Comment by cklosowski** [comment]
@pippinsplugins I've been working with him on this, I cannot find anything that causes it.

The error message received is:
`ERROR: here is an error in your Amazon Payments configuration`

**Comment by jcollake** [comment]
Any old data that might cause it to think it is misconfigured? Aside from
that, when the error occurs, as you can surely make happen, it blocks ALL
gateways. That is the more serious issue really if the config is isolated
to me.

#mobile

**Comment by amdrew** [comment]
Similarly, I'm seeing this message in many places that you shouldn't, except I don't have it configured at all. I purposely enabled `Amazon` from Downloads -> Settings -> Payment Gateways but haven't entered anything in the Amazon Payments section.

It affects quite a few areas:

___

It kills FES's `Vendor Details` page:

<img width="1639" alt="screenshot 2017-06-18 22 48 33" src="https://user-images.githubusercontent.com/52581/27260136-46319858-5478-11e7-8212-3a6faa392302.png">

___

The Download grid. Though the amazon notice will only show when no checkout page is configured in EDD.

<img width="889" alt="screenshot 2017-06-18 22 50 21" src="https://user-images.githubusercontent.com/52581/27260149-9aaa4812-5478-11e7-998b-f09b85fe9e8f.png">

___

Profile editor shortcode
<img width="884" alt="screenshot 2017-06-18 22 53 21" src="https://user-images.githubusercontent.com/52581/27260156-f9f8a318-5478-11e7-9026-5b95ac9bbaf1.png">

___

Register shortcode

<img width="862" alt="screenshot 2017-06-18 22 52 50" src="https://user-images.githubusercontent.com/52581/27260157-04423eb0-5479-11e7-8a65-2b866d3b8f96.png">

___

Login shortcode

<img width="872" alt="screenshot 2017-06-18 22 56 05" src="https://user-images.githubusercontent.com/52581/27260171-5ab30edc-5479-11e7-9b44-4b4501989dc0.png">

___

Single download page:

<img width="903" alt="screenshot 2017-06-18 22 56 55" src="https://user-images.githubusercontent.com/52581/27260175-72890066-5479-11e7-9604-7755fa9da145.png">

___

You get the point

And yeah it prevents the checkout. I can't download this free download:

<img width="901" alt="screenshot 2017-06-18 22 59 36" src="https://user-images.githubusercontent.com/52581/27260191-dee5e198-5479-11e7-8855-c1e7212c57c8.png">

**Comment by jcollake** [comment]
Thank goodness someone validated this! Amazon Payments was very popular,
and now I can't even enable it.


*Jeremy Collake - *
*Personal Account - Public Key <http://pastebin.com/f7gxNXy1>*

**Comment by pippinsplugins** [comment]
Moving up in priority.

**Comment by pippinsplugins** [comment]
PR submitted. @amdrew could you test?

**Comment by sunnyratilal** [comment]
Tested and all good here 👍

**Comment by pippinsplugins** [comment]
We can merge once tests pass.

**Comment by jcollake** [comment]
That's great to know. Where did the other report come from that was so
detailed?

I can tell you something is very wrong, and has been, if the time is taken
to set up proper test bed.

This is PHP 7, MySQL 5.7, Ubuntu 16.04, FWIW... MySQL was in strict mode,
not anymore, but that didn't seem to matter.

Further, breakage of this *one* payment gateway should *never* cause the
entire order infrastructure to go down, so it should be audited with an
'intentional break' to see what happens!

Thanks,


*Jeremy Collake - *
*Personal Account - Public Key <http://pastebin.com/f7gxNXy1>*

**Comment by jcollake** [comment]
If the test passes then I will be stunned. Nothing I can do about it
though. I dare you to have any one *other* person to test an intentional
mis-config to see if it stops all payment activity on the site. ;)


*Jeremy Collake - *
*Personal Account - Public Key <http://pastebin.com/f7gxNXy1>*

**Comment by pippinsplugins** [comment]
@jcollake I know why it was breaking the other gateways and that is part of what I have fixed. That was an unintentional design flaw.

**Comment by cklosowski** [comment]
Merged this into master.
