### ISSUE TITLE
Avoid hard-coding classes for table striping in the importer UIs

### ISSUE THREAD

**Issue by DrewAPicture** [easydigitaldownloads/easy-digital-downloads#5717]
Working on field mapping for AffWP importers as inspired by EDD, noticed that striping in the tables is achieved using the old core method of hard-coding the `alternate` class on opposite table rows. Core has since made this much more straightforward with CSS3 and the implementation of the `striped` class.

**Comment by DrewAPicture** [comment]
PR: #5718

**Comment by pippinsplugins** [comment]
Thanks @DrewAPicture!
