### ISSUE TITLE
Payment user ID set to -1 is not handled correctly

### ISSUE THREAD

**Issue by jonmarkhall** [easydigitaldownloads/easy-digital-downloads#5720]
I received a message from a customer that the checkout was asking them to log in to their account and they didn't know what to do. Upon investigation, I found that the customer did not have an associated user ID, and their payment user ID value was -1. The error message in question is shown when the payment user ID is empty() and the user is not logged in, so it was incorrectly treating this payment as if it was created by a logged in user.

**Comment by pippinsplugins** [comment]
PR https://github.com/easydigitaldownloads/easy-digital-downloads/pull/5721
