### ISSUE TITLE
Detect when non-email is entered in From Email field and auto-correct it

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#5724]
I had a site owner try and configure the emails like this:
<img width="1355" alt="screen shot 2017-05-10 at 3 43 47 pm" src="https://cloud.githubusercontent.com/assets/1034109/25920525/db177b54-3597-11e7-9bd9-1e808ca6acfc.png">

That resulted in a (silent) fatal error anytime an EDD email was sent.

I think we should do a few things here:

1. Automatically fallback to the main site admin email if the entered email does not pass `is_email()` during send.
2. Prevent the field from saving when a non-email is entered. We can show a notice to the admin.
3. Change the settings field type to `email` so it auto validates with HTML5.

**Comment by pippinsplugins** [comment]
Actually I don't think there's any need for an admin notice.

**Comment by SDavisMedia** [comment]
Everything's working as expected for me. :+1:
