### ISSUE TITLE
Chosen search has poor select element targeting

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#5731]
While working to track down https://github.com/easydigitaldownloads/edd-manual-purchases/issues/61, I discovered that select element targeting for the ajax search in our chosen drop downs isn't very reliable. In the case of Manual Purchases, the search function didn't work once a second product drop down was added. It failed because the search results were getting appended to the first select element on the page instead of the newly created one. This happened because both select elements shared the same ID attribute of `downloads`.

To resolve this, we need to make the select element targeting more specific to _this_ instance of the chosen field.

**Comment by cklosowski** [comment]
Seems to resolve the issue for me.

**Comment by pippinsplugins** [comment]
Happy with merge?
