### ISSUE TITLE
Make it known that more gateways exist in gateway settings

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/easy-digital-downloads#5736]
Potentially contentious idea but just think about it. What if we included a simple line below the list of currently available gateways indicating that other options exist? Something like this:
![Screen Shot 2017-05-12 at 5.10.47 PM](http://static.gitscout.com/e2a31a7a85a232834c687f6b2602f42486c8702d20fbc3ee347806812270476c.png)

**Comment by cklosowski** [comment]
100%. Great idea.

**Comment by pippinsplugins** [comment]
Yes!
