### ISSUE TITLE
Discount code label missing when no coupon code used

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#5740]
I noticed that when no discount code is used, the admin purchase history doesn't show the label just a "None".

![screenshot 2017-05-13 12 54 19](https://cloud.githubusercontent.com/assets/22668877/26025262/831a9a12-37db-11e7-89e8-405f1035175b.png)

**Comment by cklosowski** [comment]
I'm not seeing this on my end:
![screen shot 2017-05-15 at 7 08 23 am](https://cloud.githubusercontent.com/assets/1390124/26061639/560f609e-393d-11e7-8170-714a0c0a925a.png)

Are you running a translation file or something that might have cleared it?

**Comment by davidsherlock** [comment]
@chriscct7, no translation file but I am using a GB install of WordPress, could that be an issue?

**Comment by cklosowski** [comment]
Looks like you pinged the wrong "Chris" :). I'm looking at the en_GB translation file and they seem to have the string `Discount Codes` properly translated. Are you running locally on trunk? Or is this a live site?

**Comment by davidsherlock** [comment]
Fixed :) I am developing locally but can't seem to track down where this issue is coming from. It may be worth noting I am using "Test Mode" (payments).

**Comment by cklosowski** [comment]
@davidsherlock When you say `fixed` did you need to do anything, or was there simply something interfering with it?

**Comment by cklosowski** [comment]
Closing as invalid.

**Comment by davidsherlock** [comment]
@cklosowski, for some reason this has reappeared again. Here is a screenshot for reference:

![screenshot 2017-09-30 21 07 55](https://user-images.githubusercontent.com/22668877/31049084-a004c40c-a623-11e7-88e2-65cb178384ff.png)

Here is my system log (locally developing):

### Begin System Info ###

-- Site Info

Site URL:                 http://themedd.dev
Home URL:                 http://themedd.dev
Multisite:                No

-- Hosting Provider

Host:                     DBH: localhost, SRV: themedd.dev

-- User Browser

Platform:                 Apple 
Browser Name:             Chrome  
Browser Version:          61.0.3163.100 
User Agent String:        Mozilla/5.0 (Macintosh; Intel Ma 
			  c OS X 10_13_0) AppleWebKit/537.
                          36 (KHTML, like Gecko) Chrome/61
                          .0.3163.100 Safari/537.36
                          
-- WordPress Configuration

Version:                  4.8.2
Language:                 en_GB
Permalink Structure:      /%postname%/
Active Theme:             Themedd 1.0.2
Show On Front:            page
Page On Front:            Front Page (#67)
Page For Posts:           Blog (#69)
ABSPATH:                  /app/public/
Remote Post:              wp_remote_post() works
Table Prefix:             Length: 3   Status: Acceptable
WP_DEBUG:                 Disabled
Memory Limit:             40M
Registered Post Stati:    publish, future, draft, pending, private, trash, auto-draft, inherit, refunded, failed, revoked, abandoned, processing, active, inactive

-- EDD Configuration

Version:                  2.8.6
Upgraded From:            2.8.6
Test Mode:                Enabled
AJAX:                     Enabled
Guest Checkout:           Enabled
Symlinks:                 Disabled
Download Method:          Direct
Currency Code:            GBP
Currency Position:        before
Decimal Separator:        .
Thousands Separator:      ,
Upgrades Completed:       upgrade_payment_taxes,upgrade_customer_payments_association,upgrade_user_api_keys,remove_refunded_sale_logs,migrate_commissions,remove_legacy_commissions
Download Link Expiration:  hour(s)

-- EDD Page Configuration

Checkout:                 Valid
Checkout Page:            http://themedd.dev/checkout/
Success Page:             http://themedd.dev/checkout/purchase-confirmation/
Failure Page:             http://themedd.dev/checkout/transaction-failed/
Downloads Slug:           /downloads

-- EDD Gateway Configuration

Enabled Gateways:         Test Payment
Default Gateway:          Test Payment

-- EDD Tax Configuration

Taxes:                    Enabled
Tax Rate:                 20
Display On Checkout:      Displayed
Prices Include Tax:       Yes
Country / State Rates:    
                          Country: GB, State: , Rate: 20

-- WordPress Active Plugins

Easy Digital Downloads: 2.8.6
Easy Digital Downloads - Commissions: 3.4.1
Easy Digital Downloads - Frontend Submissions: 2.5.7
Easy Digital Downloads - Gateway Fees: 1.5.1
Easy Digital Downloads - Persistent Audio Player: 1.0.0
Subtitles: 3.0.0

-- WordPress Inactive Plugins


-- Webserver Configuration

PHP Version:              7.1.4
MySQL Version:            5.6.34
Webserver Info:           nginx/1.10.1

-- PHP Configuration

Memory Limit:             256M
Upload Max Size:          1000M
Post Max Size:            1000M
Upload Max Filesize:      1000M
Time Limit:               900
Max Input Vars:           3000
Display Errors:           On (1)
PHP Arg Separator:        &

-- PHP Extensions

cURL:                     Supported
fsockopen:                Supported
SOAP Client:              Installed
Suhosin:                  Not Installed

-- Session Configuration

EDD Use Sessions:         Enabled
Session:                  Enabled
Session Name:             PHPSESSID
Cookie Path:              /
Save Path:                
Use Cookies:              On
Use Only Cookies:         On

### Begin FES Debugging Information ###

Dashboard URL:        http://themedd.dev/vendor-dashboard/
Settings:
Array
(
    [purchase_page] => 4
    [success_page] => 5
    [failure_page] => 6
    [purchase_history_page] => 7
    [base_country] => GB
    [currency] => GBP
    [currency_position] => before
    [thousands_separator] => ,
    [decimal_separator] => .
    [test_mode] => 1
    [gateways] => Array
        (
            [manual] => 1
        )

    [default_gateway] => manual
    [accepted_cards] => Array
        (
            [mastercard] => Mastercard
            [visa] => Visa
            [americanexpress] => American Express
            [discover] => Discover
            [paypal] => PayPal
        )

    [enable_taxes] => 1
    [prices_include_tax] => yes
    [display_tax_rate] => 1
    [checkout_include_tax] => yes
    [edd_persistent_audio_player_playlist_placement] => before_content
    [edd_persistent_audio_player_preview_button_placement] => before_content
    [edd_persistent_audio_player_enable_audio_downloads] => 1
    [fes-vendor-dashboard-page] => 190
    [fes-vendor-page] => 191
    [fes-submission-form] => 192
    [fes-profile-form] => 193
    [fes-registration-form] => 194
    [fes-login-form] => 195
    [fes-vendor-contact-form] => 196
    [fes-allow-registrations] => 1
    [fes-allow-applications] => 1
    [fes-auto-approve-vendors] => 1
    [fes-auto-approve-edits] => 1
    [fes-allow-vendors-to-create-products] => 1
    [fes-allow-vendors-to-edit-products] => 1
    [fes-allow-vendors-to-delete-products] => 1
    [fes-allow-vendors-to-view-orders] => 1
    [fes-admin-new-app-email-toggle] => 1
    [fes-admin-new-submission-email-toggle] => 1
    [fes-admin-new-submission-edit-email-toggle] => 1
    [fes-vendor-new-app-email-toggle] => 1
    [fes-vendor-app-approved-email-toggle] => 1
    [fes-vendor-app-declined-email-toggle] => 1
    [fes-vendor-new-auto-vendor-email-toggle] => 1
    [fes-vendor-app-revoked-email-toggle] => 1
    [fes-vendor-suspended-email-toggle] => 1
    [fes-vendor-unsuspended-email-toggle] => 1
    [fes-vendor-new-submission-email-toggle] => 1
    [fes-vendor-submission-approved-email-toggle] => 1
    [fes-vendor-submission-declined-email-toggle] => 1
    [fes-vendor-submission-revoked-email-toggle] => 1
    [cm_messages] => Array
        (
            [0] => Array
                (
                    [conditions] => Array
                        (
                            [0] => Array
                                (
                                    [conditions] => Array
                                        (
                                        )

                                    [type] => EddCm\Lib\Conditions\ItemInCartCondition
                                    [negation] => 
                                    [data] => Array
                                        (
                                            [item] => 10
                                            [undefined] => 
                                        )

                                )

                        )

                    [message] => Please make sure you use the following codes to use this product!
                    [style] => EddCm\Lib\Styles\EddStyleSuccess
                )

        )

    [edd_gf_flat_manual] => 2
)

### End FES Debugging Information ###


### End System Info ###

**Comment by sunnyratilal** [comment]
@davidsherlock I can't seem to replicate this at all either.

Does the `span` tag get generated for you as displayed here?
![image](https://user-images.githubusercontent.com/1525554/31049841-2840b3b6-a634-11e7-8373-9b61d0217439.png)

And could you just try editing this string to static text and see if anything is displayed: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/admin/payments/view-order-details.php#L145

**Comment by davidsherlock** [comment]
@sunnyratilal, it's very intermittent and hard to replicate, but it's happened to almost all my EDD sites at some point. At first, I thought it might be localized to UK/GB sites, but I don't believe this is the case.

Here is what is generated:

![screenshot 2017-09-30 23 17 45](https://user-images.githubusercontent.com/22668877/31049903-a1c8d938-a635-11e7-9433-e89bec04ccff.png)

If I manually add a static string it will work, which localizes the issue to the `_n` function in my opinion.

**Comment by davidsherlock** [comment]
As an important side note, no discount codes were used on the order.

**Comment by davidsherlock** [comment]
It _could_ potentially fail if the translation text isn't available, but since I don't have access to the PO files for the `easy-digital-downloads-en_GB.mo` file I can't say if the string exists or not for "Discount Code".

**Comment by davidsherlock** [comment]
I think I have confirmed it, the string is missing from the file. I changed to "United States" in the WordPress settings and the label shows up again.

**Comment by sunnyratilal** [comment]
@davidsherlock The string is located in the `po` file:
![image](https://user-images.githubusercontent.com/1525554/31049998-57ea4cfa-a637-11e7-86ce-43b0deccdc86.png)

All translations for EDD are handled on WordPress.org: https://translate.wordpress.org/projects/wp-plugins/easy-digital-downloads

Specifically, GB translations are located here: https://translate.wordpress.org/projects/wp-plugins/easy-digital-downloads/dev/en-gb/default

The `po` file is available to export at the bottom of the page.

**Comment by davidsherlock** [comment]
Confirmed, the plural is missing from the GB translation:

![screenshot 2017-09-30 23 32 42](https://user-images.githubusercontent.com/22668877/31050015-b5293228-a637-11e7-8e6e-362d2c33fb9d.png)

**Comment by sunnyratilal** [comment]
@davidsherlock would you be able to add the translation please?

**Comment by davidsherlock** [comment]
Done!

**Comment by sunnyratilal** [comment]
Thank you!
