### ISSUE TITLE
EDD_Payment does not have a delete or add meta method.

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#5744]
These will be imperative moving forward when we get to custom tables for payments. We need to mimic WP Core meta as closely as possible, which includes deleting and adding (instead of updating) meta.

**Comment by cklosowski** [comment]
Oh, going to get some unit tests in place quick before we start merging.

**Comment by pippinsplugins** [comment]
PR looks good, merged.
