### ISSUE TITLE
Set download process to use binary method to avoid corrupt files due to line endings

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#5748]
As pointed out in a support thread, a suggestion to change the following:
```
In this file : process-download.php
This is wrong: $handle = @fopen( $file, 'r' );
Should be: $handle = @fopen( $file, 'rb' );
```

According to the [PHP Docs](http://php.net/manual/en/function.fopen.php), you can pass in `b` as a flag, which will switch the download mode to `binary` and will avoid interpreting the line ending, for cases where the file generated on one OS can have different line endings than the OS delivering the file, which can lead to a corrupt file as it tries to 'translate' the file on the fly.

We'll need to test this out quite extensively on all platforms (Windows, Linux, OS X) to make sure that we're covering our bases.

**Comment by mintplugins** [comment]
FWIW This is working fine for me downloading on MacOSX hosted on Ubuntu for jpg, png, and zip files.

**Comment by cklosowski** [comment]
@easydigitaldownloads/core-devs if we have someone with a Windows machine that can create a `.txt` file and upload it to a OSX/Linux machine that'd be ideal for testing. OSX/Ubuntu are both `*nix` based systems and typically have the same line ending format by default.

**Comment by pippinsplugins** [comment]
I do not own a windows machine any more :(

**Comment by nosegraze** [comment]
I have a Windows machine.

So:

- Create a `.txt` file.
- Upload it as a download in EDD (my server uses Ubuntu).
- Test downloading the file.

Is that what I'm doing? :P

**Comment by cklosowski** [comment]
@nosegraze yep! That should apparently do it.

**Comment by nosegraze** [comment]
No issues here! Also tested with `jpg` `png` and `zip` files - all worked fine.

**Comment by pippinsplugins** [comment]
Excellent, merging.
