### ISSUE TITLE
Start date not set properly in reports all pre-set ranges

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#5749]
When viewing the `This Year` and `Last year` reports, the `day` parameter is getting set to the current day of the month instead of `1`.

**Comment by pippinsplugins** [comment]
It's also getting set improperly for the quarterly views.

**Comment by mintplugins** [comment]
I'm not sure I am replicating. This is what I am getting on master for `this year`

<img width="1266" alt="screen shot 2017-05-22 at 1 15 56 pm" src="https://cloud.githubusercontent.com/assets/1638128/26320425/d55b170e-3ef0-11e7-947f-bb14d5326ff7.png">

**Comment by pippinsplugins** [comment]
Take a look at the URL and find the `day` parameter. It will be set to the current day of the month instead of `1`. This results in 1-30 days missing from the earnings amount.

**Comment by mintplugins** [comment]
Ah yeah I see it now. replicated on master and fixed on `issue/5749`.

**Comment by mintplugins** [comment]
This is still an issue if you are using "Last Month" so we should set the `day` value to 1 in that case as well.

**Comment by cklosowski** [comment]
@mintplugins this is working just fine on `Last Month` for me, I get the same results as the years:
`&day=1&day_end=31`
![screen shot 2017-06-21 at 10 12 36 am](https://user-images.githubusercontent.com/1390124/27397130-327b4428-566a-11e7-8242-9eee8827316f.png)

**Comment by cklosowski** [comment]
Tested and working fine here.
