### ISSUE TITLE
Add filter to output of variable prices

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#5754]
In EDD All Access, we want to give the site owner the option to show or hide the price amount. In this issue, we'll add a filter to EDD Core to make that possible. 

All Access issue:
https://github.com/easydigitaldownloads/edd-all-access/issues/99

**Comment by pippinsplugins** [comment]
PR looks good to me.

@cklosowski any objections or changes to this?

**Comment by cklosowski** [comment]
Yep, looks all good to me @mintplugins. Merging it for 2.8
