### ISSUE TITLE
Plain text links still look like buttons

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/easy-digital-downloads#5756]
If `Plain text` is selected for the `Default Button Style` the links still appear as buttons since there's a grey border and rounded corners. The EDD stylesheet is adding this from the `edd-submit` selector as seen below.

I propose moving the border and border-radius styling to another CSS class so it only affects buttons.

The box shadow on the bottom of the links is something Twenty Sixteen is doing so ignore that.

![screen shot 2017-05-22 at 3 22 26 pm](https://cloud.githubusercontent.com/assets/52581/26291508/d8657342-3f02-11e7-8acc-cac7a4995ff9.png)
___
![screen shot 2017-05-22 at 3 22 18 pm](https://cloud.githubusercontent.com/assets/52581/26291510/d8693126-3f02-11e7-8958-621c5a7906f9.png)
___
![screen shot 2017-05-22 at 3 23 42 pm](https://cloud.githubusercontent.com/assets/52581/26291509/d8663836-3f02-11e7-98a2-a21bd6156a49.png)

**Comment by pippinsplugins** [comment]
Let's try and address this right after 2.8

**Comment by sunnyratilal** [comment]
@amdrew PR opened at #5907

**Comment by SDavisMedia** [comment]
@sunnyratilal `issue/5756` works perfectly on my end. I made a small formatting tweak (replaced spaces with tabs). This is good to go. :+1:

**Comment by sunnyratilal** [comment]
Thanks @SDavisMedia - PHPStorm is acting up a bit with formatting :/
