### ISSUE TITLE
Update login and register form styling

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/easy-digital-downloads#5757]
The login and register forms could do with some love.

# Twenty Seventeen

### Login form

![screen shot 2017-05-22 at 10 45 46 pm](https://cloud.githubusercontent.com/assets/52581/26304676/6f3abc18-3f40-11e7-95e8-3a2d0e78409b.png)

___

The hover effect on the button is a bit weird

![screen shot 2017-05-22 at 10 45 52 pm](https://cloud.githubusercontent.com/assets/52581/26304677/6f3d52f2-3f40-11e7-9bdd-6d2534e26522.png)

___

### Register form

![screen shot 2017-05-22 at 10 46 08 pm](https://cloud.githubusercontent.com/assets/52581/26304792/cc00e90e-3f40-11e7-8513-2c252f005f27.png)
___
Note how the button hover doesn't look strange on the register form:

![screen shot 2017-05-22 at 10 46 12 pm](https://cloud.githubusercontent.com/assets/52581/26304791/cbf7dc06-3f40-11e7-9d4c-0826bf0e98c5.png)

# Twenty Sixteen

### Login form

![screen shot 2017-05-22 at 10 46 47 pm](https://cloud.githubusercontent.com/assets/52581/26304888/1e8721fc-3f41-11e7-8837-764aa75ea186.png)
___
Button hover: 
![screen shot 2017-05-22 at 10 46 53 pm](https://cloud.githubusercontent.com/assets/52581/26304889/1e89bd54-3f41-11e7-94d6-32fc34b519db.png)

### Register form

![screen shot 2017-05-22 at 10 46 26 pm](https://cloud.githubusercontent.com/assets/52581/26304933/56fc10e2-3f41-11e7-96ef-ddfff1cd8ec0.png)
___
Button hover:

![screen shot 2017-05-22 at 10 52 36 pm](https://cloud.githubusercontent.com/assets/52581/26304946/5f6106c0-3f41-11e7-844d-a8fd9bacdebf.png)

I'd like to propose:

1. Consistency with the buttons between the login and register form
2. A fixed hover state for the login form
3. Remove the `fieldset` border
4. Do something a bit nicer with the `legend` so it looks like a heading (see examples below for AffWP)
5. Remove the `display: inline-block;` and `width: 200px` for the form's `label`'s. We did this for AffiliateWP (https://github.com/AffiliateWP/AffiliateWP/issues/1538) and Restrict Content Pro (https://github.com/restrictcontentpro/restrict-content-pro/issues/251)

For reference, here's AffiliateWP's login and register forms:
![screen shot 2017-05-22 at 11 00 37 pm](https://cloud.githubusercontent.com/assets/52581/26305250/9f8be750-3f42-11e7-9728-c2a1ab1d7c26.png)

![screen shot 2017-05-22 at 11 00 18 pm](https://cloud.githubusercontent.com/assets/52581/26305251/9f8d11de-3f42-11e7-9bbf-74af98099276.png)

**Comment by lalunecreative** [comment]
I agree that it needs to be updated. I totally stripped ours and made it looks more modern for today's standards with our site - https://lalunecreative.com/login/

I also hired a developer to make some changes because the intuitiveness of the whole thing is a mess. Why do you login only to be sent to a screen that says "you're already logged in"? That makes zero sense. There should be a way to redirect after login. I had our developer force it to take you to our account page instead.

There are some things I don't get, like why remember me and lost your password aren't inline with each other.

And why NONE of the buttons on the site are consistent with the ajax spinner, on the login/register buttons they don't even show up at all. On the individual download pages it loads within the button itself, everywhere else it loads on the OUTSIDE of the button (who does that???) and it's inconsistent across EDD. Some do it one way and the others do it another.

**Comment by sunnyratilal** [comment]
@amdrew pushed an initial commit that incorporate all but one of the things listed above which is the hover state. This is the CSS by default for `edd-button` and `edd-submit` - how do you propose we move ahead with the hover state issue?

**Comment by amdrew** [comment]
@sunnyratilal Huge improvement! 💯 

For those watching, here's Twenty Sixteen:

___
Login:

<img width="852" alt="screenshot 2017-09-01 17 33 29" src="https://user-images.githubusercontent.com/52581/29956513-bdf90634-8f3b-11e7-8fa4-02d650307aff.png">

___

Register:

<img width="839" alt="screenshot 2017-09-01 17 33 33" src="https://user-images.githubusercontent.com/52581/29956517-c290ab8e-8f3b-11e7-9b77-c067b95285ad.png">

___

Button hovers: From what I can see, if you change EDD's `Default Button Color` setting It changes the button background and text color everywhere **except** for:

1. The login form
2. The register form
3. The profile form

<img width="690" alt="screenshot 2017-09-01 17 46 25" src="https://user-images.githubusercontent.com/52581/29956775-800d0e9a-8f3d-11e7-81dc-a57d62efadd6.png">

As we know this setting changes standard add to cart buttons, the checkout purchase button, apply discount button, update cart button, "next" button at checkout (when ajax is disabled), save cart button etc (just skimming through the code). So why doesn't it affect those 3 forms? 

To be consistent, I think that color setting should also affect the login, register, and profile editor form buttons. Each one of the colors in the CSS has the hover text color configured already. 

@SDavisMedia Do you agree on that?

We'd then get something like this:

<img width="844" alt="screenshot 2017-09-01 18 03 47" src="https://user-images.githubusercontent.com/52581/29957161-03ecb240-8f40-11e7-8b83-39179774c5a0.png">

And the hover (slightly darker green with white text, problem solved!):

<img width="842" alt="screenshot 2017-09-01 18 03 52" src="https://user-images.githubusercontent.com/52581/29957160-03e9ee3e-8f40-11e7-94ca-fd81a631f6ca.png">

___

The original issue of the grey text color on hover is caused by this CSS rule:

```css
input[type="submit"].edd-submit:hover,
input[type="submit"].edd-submit:focus,
.edd-submit.button:hover,
.edd-submit.button:focus {
	color: #333333;
	text-decoration: none;
}
```

Since grey is actually the default for buttons (/** Gray (Default) */) I think we can then remove that entire block of CSS above. All buttons would then have a color, grey being the default, unless the color was changed. So the above CSS seems redundant.

PS. I'm seeing `edd_submit` twice on the input class of both the login and register forms:

<img width="529" alt="screenshot 2017-09-01 17 57 59" src="https://user-images.githubusercontent.com/52581/29957011-1b374b46-8f3f-11e7-8ac8-60affe543f5d.png">

**Comment by sunnyratilal** [comment]
@amdrew @SDavisMedia fixed in 8fc748e4ca918c8e46be8196c4da660be8dae04c

**Comment by lalunecreative** [comment]
Well that's definitely much better for average users, I'm glad it's being fixed finally. 

Now if only #5742 could be fixed this would wrap up the registration/login issues completely I think.

**Comment by amdrew** [comment]
@sunnyratilal Looks good. Any thoughts on making the button use the EDD setting so they all look the same?

**Comment by amdrew** [comment]
@sunnyratilal Actually, ignore the above. Thinking about it some more, the buttons should **not** use the EDD button color setting since a site may have other forms with buttons and that would look out of place. The theme should have control over the button colors (which is probably why we've always done it this way). 👍 

I think this is ready to go!
