### ISSUE TITLE
Quick edit fields not being populated

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#5759]
When you click "Quick Edit" within the Downloads grid, the fields aren't pre-populated with the existing post data meaning if you forget to fill in a field you can easily re-save and lose your title, slug, tags, etc.

Similarly the download tags and category selections aren't being pulled in, so adding (or editing) an existing tag isn't possible and feels like a poor workflow since most people will simply want to tweak existing settings.

**Comment by cklosowski** [comment]
This is all populating just fine for me:
![screen shot 2017-05-23 at 6 16 18 am](https://cloud.githubusercontent.com/assets/1390124/26355974/612028ea-3f7f-11e7-81a4-3fd655f3cc62.png)

Are you getting any JS errors in the process? Does the quick edit work for regular posts or pages?

**Comment by davidsherlock** [comment]
@cklosowski, no JS errors just nothing being populated. Here are the screenshots:

![screenshot 2017-05-23 14 18 15](https://cloud.githubusercontent.com/assets/22668877/26356065/c48160fa-3fc2-11e7-8948-254f4301bdcf.png)

![screenshot 2017-05-23 14 18 04](https://cloud.githubusercontent.com/assets/22668877/26356067/c76fbcd0-3fc2-11e7-83ac-d7ec4179834e.png)

I am developing locally using nginx, etc. But this is just a "stock" EDD install fundamentally.

**Comment by cklosowski** [comment]
Looks like FES is active there, what happens when you disabled FES does it work?

**Comment by davidsherlock** [comment]
Yep, that fixed it! My theory is this the "Author" box function as issue as "Admin" was pulled down twice...

**Comment by cklosowski** [comment]
Ok closing this issue, and moving it over to FES
