### ISSUE TITLE
Incorrect cookie for rememberme option

### ISSUE THREAD

**Issue by cdillon** [easydigitaldownloads/easy-digital-downloads#5761]
At login, the auth cookie expiration is always 2 days instead of 14 due to a name mismatch. 

The input field name in shortcode-login.php is "rememberme" but the value sent by edd_process_login_form to edd_log_user_in is "remember".

**Comment by pippinsplugins** [comment]
Thanks, we'll get that fixed!

**Comment by sunnyratilal** [comment]
PR opened at #5961
