### ISSUE TITLE
Question: How to create dynamic downloads in EDD?

### ISSUE THREAD

**Issue by muesliq** [easydigitaldownloads/easy-digital-downloads#5763]
I have an editor that my customers use to create/edit digital files that they will then purchase. I would like to use EDD for shopping cart, customer management and discount codes. (Ignoring all product listing or catalogue functions.)

How do I connect these dynamic downloads to EDD? I can create generic product types (one per price category) in EDD but EDD would also have to handle the custom created download files plus the custom product name that the customer specifies.

Is this possible? Do I have to write software that writes directly into the database to create new product IDs that I can then reference via a shortcode? If yes, do I do this via the Wordpress REST API? (I understand that the EDD API is read only.)

Thanks for any hints on how to achieve this!

**Comment by pippinsplugins** [comment]
Hi there!

Please go ahead and open a support ticket through our support portal: https://easydigitaldownloads.com/support

we use GitHub for development tracking only.
