### ISSUE TITLE
Allow discount expiration time to be set

### ISSUE THREAD

**Issue by leewillis77** [easydigitaldownloads/easy-digital-downloads#5766]
On the discount setup screen, when creating a discount, the text advises:

> Enter the expiration date for this discount code in the format of mm/dd/yyyy. For no expiration, leave blank

However, when editing a discount the expiration is shown in the format:

```m/d/Y H:i:s```

Allowing a discount code to have an expiry "time", not just date would support short-term discounts, e.g. "10% off for the next 4 hours". Internally the expiration is stored as a date/time, and I can't see any technical reason why the expiration "date" couldn't also support a time element. [I've seen #5619 but I can't see anything there that would preclude us from keeping a time element]

However - it looks like the current code loses (or deliberately overwrites) the time with 23:59:59 whenever the discount is saved. Try modifying an existing discount code expiry time and saving - it reverts back to 23:59:59. 

This comes from the EDD_Discounts class and affects discount codes created programatically as well. The relevant code is https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/class-edd-discount.php#L1067 

It seems that this code will accept any input format that strtotime() supports and converts it to ```m/d/Y 23:59:59```. 

I did attempt to do a PR to go with this report, but it seems difficult to reliably detect whether someone is just passing in a date, and wants 23:59:59 set as the time, or if they're passing in a full date and time unless we're happy to just assume that if the result of strtotime has an hours/minutes/seconds of 00:00:00 then it's a date only and we should bump the time to 23:59:59. 

This would effectively cause issues for anyone trying to set the expiry time to 00:00:00 but seems like the only sensible solution in absence of the data being passed in a more sensible format. 

Happy to put together a PR for that if it's worthwhile?

**[Note]** It seems that strtotime always sets the time to 00:00:00 when given just a date. I've confirmed with a quick test on [3v4l.org](https://3v4l.org/ofrlA) - and it's sensible, however I don't believe it's documented behaviour.

**Comment by leewillis77** [comment]
Just a follow up. Manually setting the _edd_discount_expiration meta after discount code creation *does* work correctly. The discount code becomes unusable after the specified time.

**Comment by pippinsplugins** [comment]
@leewillis77 setting it to 23:23:59 is intentional but I don't see any reason we cannot extend it to support specific expiration times.

**Comment by cklosowski** [comment]
I really think we need to do this alongside #5619. Right now our format for expiration dates isn't in a MySQL format so doing queries by date don't work without some 'fuzzy' logic. 

If we do the time alongside this other issue we can just use the native MySQL support for times, which will lead to a much more accurate and smooth transition to supporting expiration times

**Comment by SDavisMedia** [comment]
Got a request for this: https://secure.helpscout.net/conversation/463575914/69992/?folderId=180499

**Comment by cklosowski** [comment]
Since #6224 now implements a `DATETIME` MySQL column, going to punt this to 3.0, so it can be properly done instead of 'bolted onto' our existing incorrect format.

**Comment by sunnyratilal** [comment]
Merged.
