### ISSUE TITLE
"Some required information is missing or incomplete"

### ISSUE THREAD

**Issue by lostlogo** [easydigitaldownloads/easy-digital-downloads#5772]
I have filled out every field and am using the correct API settings from paypal, I have no idea what is going wrong. Button is on this page: http://imaginechanges.com/pain-relief-e-book/

I started using this app because Paypal apparently is only letting people who already applied for Express checkout digital goods before some date use it, and no new applications are being accepted. Does that also apply to users of the app or does the app circumvent that necessity?  http://imgur.com/a/58qMs

Error reads: Some required information is missing or incomplete. Please correct your entries and try again.

**Comment by chriscct7** [comment]
Hi there!

Please go ahead and open a support ticket through our support portal: https://easydigitaldownloads.com/support

we use GitHub for development tracking only.

**Comment by lostlogo** [comment]
I don't have a key so I guess I'm just out of luck :D

<http://thenerdy.ninja>
[image: logo]
*Amber Kat Smith* *Web Design, Web Development, E-commerce, Social Media
Help**, The Nerdy Ninja - Formerly Lostlogo Design*
347.514.1452 | kat@thenerdy.ninja | http://thenerdy.ninja
<http://twitter.com/nerdyninjablog> <http://www.facebook.com/nerdyninjadev>
<http://us.linkedin.com/in/lostlogodesign>
IMPORTANT: The contents of this email and any attachments are confidential.
They are intended for the named recipient(s) only. If you have received
this email by mistake, please notify the sender immediately and do not
disclose the contents to anyone or make copies thereof.

**Comment by chriscct7** [comment]
Keys are not required to use our support

**Comment by lostlogo** [comment]
When I tried to open a ticket, The form asks for a registrion key with a *
next to it like it's required. I'll look again

**Comment by cklosowski** [comment]
@lostlogo If you are using PayPal Standard that is included with Easy Digital Downloads Core just choose 'No' for `Is your issue / question about an Extension or Theme?`.

**Comment by cklosowski** [comment]
@lostlogo please include a screenshot of your PayPal Standard settings in your support request.

**Comment by lostlogo** [comment]
I unchecked the box paypal standard and it at least added it to the cart
and let me go to checkout, but now it says "*Error*: You must enable a
payment gateway to use Easy Digital Downloads"     - I have the api for
paypal standard, shouldn't that make it work?

<http://thenerdy.ninja>
[image: logo]
*Amber Kat Smith* *Web Design, Web Development, E-commerce, Social Media
Help**, The Nerdy Ninja - Formerly Lostlogo Design*
347.514.1452 | kat@thenerdy.ninja | http://thenerdy.ninja
<http://twitter.com/nerdyninjablog> <http://www.facebook.com/nerdyninjadev>
<http://us.linkedin.com/in/lostlogodesign>
IMPORTANT: The contents of this email and any attachments are confidential.
They are intended for the named recipient(s) only. If you have received
this email by mistake, please notify the sender immediately and do not
disclose the contents to anyone or make copies thereof.

**Comment by cklosowski** [comment]
@lostlogo You need one gateway active...PayPal Standard. Please use our support form to contract us about this, this is for development tracking only, not support requests. As I stated above, since your issue is related to EDD Core, and not a plugin, you can simply state 'No' for the 'Is your issue / question about an Extension or Theme?` question and you should be able to submit a request to us without license key.

**Comment by lostlogo** [comment]
When you said "If you are using PayPal Standard that is included with Easy
Digital Downloads Core just choose 'No' " it sounded like you wanted me to
uncheck paypal standard box, couldn't tell it had to do with the form.
either way, checked or unchecked, same warning, will open a ticket ..
thanks.


<http://thenerdy.ninja>
[image: logo]
*Amber Kat Smith* *Web Design, Web Development, E-commerce, Social Media
Help**, The Nerdy Ninja - Formerly Lostlogo Design*
347.514.1452 | kat@thenerdy.ninja | http://thenerdy.ninja
<http://twitter.com/nerdyninjablog> <http://www.facebook.com/nerdyninjadev>
<http://us.linkedin.com/in/lostlogodesign>
IMPORTANT: The contents of this email and any attachments are confidential.
They are intended for the named recipient(s) only. If you have received
this email by mistake, please notify the sender immediately and do not
disclose the contents to anyone or make copies thereof.

**Comment by lostlogo** [comment]
got it! for some awful reason, needed an new api key. despise paypal and
api. Thanks!!!!


<http://thenerdy.ninja>
[image: logo]
*Amber Kat Smith* *Web Design, Web Development, E-commerce, Social Media
Help**, The Nerdy Ninja - Formerly Lostlogo Design*
347.514.1452 | kat@thenerdy.ninja | http://thenerdy.ninja
<http://twitter.com/nerdyninjablog> <http://www.facebook.com/nerdyninjadev>
<http://us.linkedin.com/in/lostlogodesign>
IMPORTANT: The contents of this email and any attachments are confidential.
They are intended for the named recipient(s) only. If you have received
this email by mistake, please notify the sender immediately and do not
disclose the contents to anyone or make copies thereof.
