### ISSUE TITLE
Stripe Modal won't go away

### ISSUE THREAD

**Issue by greggbanse** [easydigitaldownloads/easy-digital-downloads#5773]
I created a download and setup Stripe payments. I used the EDD checkout pages first then wanted to see how Stripe modal window would look and function. I didn't like it so I disabled it but it still keeps coming up. I've tried it in 3 different browsers, cleared the cache, cleared the cache on the server (WPEngine) but it still keeps coming up.

**Comment by SDavisMedia** [comment]
Hi @greggbanse. Please open a support ticket here: https://easydigitaldownloads.com/support/ Be sure to specify Stripe in the support form and provide all of the necessary information. This isn't the correct place to troubleshoot Stripe extension issues.

**Comment by greggbanse** [comment]
Sorry SDavisMedia, This is where I was sent when I clicked a support link.

**Comment by SDavisMedia** [comment]
@greggbanse no worries! Can you let me know where you found that link?
