### ISSUE TITLE
WP Cli Sales Command

### ISSUE THREAD

**Issue by bryancisler** [easydigitaldownloads/easy-digital-downloads#5774]
I was looking through the EDD WP CLI commands this weekend and was wondering what your thoughts were about adding an enhancement to the wp edd sales command? I have a PR coming that would rework the functionality so someone could filter sales by email. Something like wp edd sales –email=bryan.cisler@strategynewmedia.com

**Comment by pippinsplugins** [comment]
@bryancisler that would be a great improverment!

**Comment by sunnyratilal** [comment]
PR checked and it's good to be merged
