### ISSUE TITLE
Credit card and CVC field are not intuitive

### ISSUE THREAD

**Issue by Shelob9** [easydigitaldownloads/easy-digital-downloads#5785]
My specific issues are:
1) Credit card number fields do not show card type or validate based on card type, which makes it easier to know you're typing the card right or wrong.
2) Credit card field doesn't automatically space as it is printed on the card.
3) CVC field minimum length doesn't change to 3 or 4 to the card type.

I'd love to see something like Stripe's jQuery plugin for credit card fields used to improve the look and experience of CC and CVC fields. https://github.com/stripe/jquery.payment

**Comment by pippinsplugins** [comment]
1. The card type shows up as soon as you type the first four numbers.

2. This has been allowed through https://github.com/easydigitaldownloads/edd-stripe/issues/151. It's in the new beta version https://easydigitaldownloads.com/development/2017/05/24/stripe-gateway-2-6-beta-and-recurring-payments-adds-support-for-existing-cards/

3. This would be a nice improvement.

I would like to at some point include the Stripe payment jQuery library. It's 💯.

**Comment by Shelob9** [comment]
Interesting. I will upgrade my Stripe plugin re: point 2. I'm not sure why I don't get the first one on my site.

**Comment by pippinsplugins** [comment]
@Shelob9 is this on CalderaForms.com?

**Comment by Shelob9** [comment]
@pippinsplugins Correct

**Comment by pippinsplugins** [comment]
I'm going to close this as a duplicate. See #5369
