### ISSUE TITLE
Tax rate percentage not showing

### ISSUE THREAD

**Issue by herofive2424** [easydigitaldownloads/easy-digital-downloads#5790]
Hi,

since 2 days my tax rate percentages (on single-download page and checkout page) is not showing up.

I already tried deleting all custom css and deactivating all plugins. In my backup from 2 days ago it still shows up (To make it clear: It's only the percentage which is not showing up, tax calculation and numbers are still correct on checkout).

I also use the EDD EU VAT Compliance Plugin : https://wordpress.org/plugins/edd-eu-vat-compliance/

Any idea how this can be possible?

**Comment by cklosowski** [comment]
GitHub is only used for development tracking. Please visit https://easydigitaldownloads.com/support to receive technical support.
