### ISSUE TITLE
Add "Enable Product Reviews" link to product edit screen

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#5791]
To help encourage people to add the Product Reviews plugin, let's add a `Enable Product reviews` metabox / link to the product edit screen when the EDD Reviews plugin is not activated.

**Comment by danieliser** [comment]
I will say that these in dash contextual upsell links generate a substantial portion of Popup Makers revenue. Much more than say the Extensions/Addons page in dash.

**Comment by cklosowski** [comment]
Ok updated this to a metabox. It has 2 statuses:
1) When `EDD-Reviews/edd-reviews.php` or `edd-reviews/edd-reviews.php` is a valid plugin installed (but not activated), it shows a button to `Activate Reviews`
![screen shot 2017-06-26 at 12 13 06 pm](https://user-images.githubusercontent.com/1390124/27558709-f7201784-5a72-11e7-92f1-6cb697ab35ee.png)

2) If the plugin is not found, it gives this message to send them to our sales store with UTM tags in a new tab:
![screen shot 2017-06-26 at 1 24 43 pm](https://user-images.githubusercontent.com/1390124/27558730-113bcfd2-5a73-11e7-912c-3a64a3a02393.png)

**Comment by cklosowski** [comment]
Updated to be `Product Reviews`

**Comment by cklosowski** [comment]
Once CI Passes, I'll merge this.
