### ISSUE TITLE
Notes for Discounts

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#5794]
It'd be nice to have a textarea in the discounts screen to add notes for discounts (notably why a particular one exists).

**Comment by pippinsplugins** [comment]
I typically use the name or description field for this since neither of those is shown publicly (unless using the discounts widget).

Name: Susan Jones
Description: Discount for Susan for being awesome.

**Comment by chriscct7** [comment]
The problem using the name is the field is not long enough. For example, if I want to reference a helpscout ticket by including the URL and some explanation text. Also it overflows the All Discounts table, and also means that search for discounts doesn't work (or as well) for that discount.

As for the description field, this doesn't exist (at least in stock EDD core). Are you using an addon to add it?

**Comment by cklosowski** [comment]
Since this is a custom post type, we're currently not using the `post_content` field. I feel like that would give us an ample way to store any 'description' of a discount and allow quite a bit of detail if we want.

This opens up an interesting couple of use cases too:
1) Something like @chriscct7 is wanting for administrative use
2) Someone would add custom descriptions to their codes and display them on the front end if they want.

I'm going to 'bless' this and put it on the 3.0 milestone.

**Comment by mathetos** [comment]
Would love to see this happen, and I'd say pretty much in the same manner as Payments have notes. That will enable multiple people to add notes and have a log of the notes.

As our team gets larger we have more hands in the discount pot. So being able to just add notes prevents having to @channel in Slack "Hey! Who created this 100% off coupon!?"

**Comment by SDavisMedia** [comment]
Duplicate. https://github.com/easydigitaldownloads/easy-digital-downloads/issues/3871 But I'm all for it this time around too. For those who actually want it, it would be super useful.

**Comment by sunnyratilal** [comment]
This will now be implemented once #5277 and #6278 are both merged as it will rely on the updated `EDD_Discount` class and the new `edd_notes` table.

**Comment by sunnyratilal** [comment]
@easydigitaldownloads/core-team This is ready for testing.

**Comment by sunnyratilal** [comment]
Merged!

**Comment by pippinsplugins** [comment]
🎉

**Comment by SDavisMedia** [comment]
❤️

**Comment by pippinsplugins** [comment]
I'm getting a fatal error in `release/3.0` now when I try and view a discount code that has notes on it:


PHP Fatal error: Uncaught Error: Cannot access protected property EDD\Notes\Note::$id in /var/www/html/wp/wp-content/plugins/easy-digital-downloads/includes/admin/discounts/discount-functions.php:44

**Comment by sunnyratilal** [comment]
Closing this out as it has been fixed by @JJJ.
