### ISSUE TITLE
upload file on another server and put link in to edd for purchase

### ISSUE THREAD

**Issue by PicaName** [easydigitaldownloads/easy-digital-downloads#5796]
hi.
i have problem with edd, when i upload file to my own server , it work great and hide main download url , but when i put my file on other server and try to put link in edd and then download that, url not hidden and link redirect me to main file!
any suggestion for that?
Best Regards

**Comment by cklosowski** [comment]
@PicaName Github is only used for development tracking. Please use our Support form at https://easydigitaldownloads.com/support.
