### ISSUE TITLE
Auto-map fields during CSV import

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#5797]
I had to move products from one EDD install to another, and while the export/import functions work well, I feel mapping shouldn't be required (or at least pre populated) if the structure (headings) are using the EDD export schema.

The fields should be automapped (and selected) to save time and potential errors while importing to speed the process up.

**Comment by pippinsplugins** [comment]
This is definitely something we wanted to make happen when first building the import tool but it didn't happen.

👍

**Comment by pippinsplugins** [comment]
This is _lovely_!
