### ISSUE TITLE
Improve WP-CLI payment creation

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#5798]
This is both an enhancement and bug fix.

**Bug Fix**
Previously when you requested to create payments if you did not define a `price_id` argument, it just used `false`, which was then used to randomly generate a price ID for products, however it overwrite the `$price_id` variable, so once a price Id is selected, all variable prices were using that price ID, instead of randomly selecting.

**Enhancement**
When getting downloads to add to a payment, the number was hard coded to getting `1` download but by making the number `rand(1, 3)` we can randomly generate payments with 1,2, or 3 downloads on them, making our testing data more 'realistic'

**Comment by pippinsplugins** [comment]
Looks good to me!
