### ISSUE TITLE
Per User Language Setting Bug 

### ISSUE THREAD

**Issue by DevinWalker** [easydigitaldownloads/easy-digital-downloads#5800]
## Issue Overview
Currently, if you set the global language of your site to Deutsch within WP-Admin > Settings > General and then _your user_ profile to English under WP-Admin > Users > Your Profile you will still see the plugin translated to Deutsch incorrectly:

![2017-06-09_16-06-12](https://user-images.githubusercontent.com/1571635/26997327-9b3c9336-4d2d-11e7-8562-9e6423ed57b5.gif)

## Expected Behavior
The per-user language settings are respected.

## Current Behavior
Only global settings are respected. 

## Steps to Reproduce (for bugs)
1. Install EDD
2. Change site's global language to Deutsch
3. Change your profile's to English
4. Upload or update translation files to `wp-content/languages/plugins/`
![2017-06-09_15-53-22](https://user-images.githubusercontent.com/1571635/26997083-c9c3712c-4d2b-11e7-880d-a3eab33c1493.png)

## Cause
The `EDD()` function is ran too early, causing EDD to bypass WP's built in i18n functionality. Note, this also causes a conflict with WPML. See https://github.com/WordImpress/Give/issues/1609 for more info.

## Possible Solution
Hook `EDD()` with the `plugins_loaded` action.

**Comment by cklosowski** [comment]
We've tried moving `EDD()` to a `plugins_loaded` before and it ends poorly. We can try and revisit it, but it broke a lot of extensions last time we tried.

**Comment by DevinWalker** [comment]
Really? Can you provide me an example? All plugins should be hooking in when EDD() is ready. I loading on `plugins_loaded`, perhaps with a super early priority and also suggest added a `edd_init` action here: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/easy-digital-downloads.php#L168

```
/**
 * Fire the action after EDD core loads
 *
 * @param EDD The EDD class instance.
 */
 do_action( 'edd_init', self::$instance );```

**Comment by cklosowski** [comment]
I'd have to revisit them. Honestly we've updated a lot of plugins since then to run on `plugins_loaded` instead of at runtime (which is what caused most of the problems), which is why I said I had to revisit it.

**Comment by DevinWalker** [comment]
Sounds good. I just tried it out quickly and came across some core php errors that upon initial glance look easy to fix:

![2017-06-09_16-29-24](https://user-images.githubusercontent.com/1571635/26997732-ec362448-4d30-11e7-86c4-822373e01af6.png)

**Comment by cklosowski** [comment]
Since this might end up changing the load order (possibly), I'm going to milestone it for a major release, instead of a point release.

**Comment by cklosowski** [comment]
I'm going to move this to 3.0, since we may be changing the load organization in that major update.

**Comment by sunnyratilal** [comment]
EDD now hooks on to `plugins_loaded` meaning this bug should be fixed.

See commit https://github.com/easydigitaldownloads/easy-digital-downloads/commit/be4c2af55eab7bcd4c379f4f83efc1862f0c6951
