### ISSUE TITLE
Checkout: Auto-fill customer's billing address if logged in and it exists

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#5807]
If a customer's billing address exists in the customer profile or a previous payment, could it be automatically pre-filled into the checkout if they are logged in? Potentially, this could work similarly to the recent update to Simple Shipping with saved shipping addresses.

**Comment by pippinsplugins** [comment]
We already do when logged in. Are you not seeing it?

**Comment by mintplugins** [comment]
Ah yep I see it now - I must not have been logged in. Disregard!
