### ISSUE TITLE
EDD Admin CSS responsive improvements

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#5812]
We have some CSS in our `edd-admin.css` that adds in `overflow:hidden` and on a mobile device it causes the checkbox to be cut off:
![screen shot 2017-06-14 at 2 27 47 pm](https://user-images.githubusercontent.com/1390124/27155495-0f3562d4-510e-11e7-8a38-2e4810e92c69.png)

Removing that makes it look correct:
![screen shot 2017-06-14 at 2 28 17 pm](https://user-images.githubusercontent.com/1390124/27155511-1a94bc88-510e-11e7-96f7-1801965f682c.png)

**Comment by SDavisMedia** [comment]
@cklosowski ^^

**Comment by cklosowski** [comment]
Adding in one that limits our `.edd-select-chosen` as well since that was discovered in EDD Core as well.
