### ISSUE TITLE
Don't show "Error: No checkout page has been configure" error message so many times

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/easy-digital-downloads#5815]
I propose we don't show the `Error: No checkout page has been configured. Visit Settings to set one.` error message so many times. This is the download grid:

<img width="889" alt="screenshot 2017-06-18 22 50 21" src="https://user-images.githubusercontent.com/52581/27260207-33b2e766-547a-11e7-802e-04fdc1d8eebe.png">

**Comment by cklosowski** [comment]
That seems completely logical @amdrew
