### ISSUE TITLE
Update library for array2xml.php

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#5826]
We had a [PR for updating some of the code](https://github.com/easydigitaldownloads/easy-digital-downloads/pull/4116) in the `array2xml.php` file, but this is a 3rd party library, so we should really see if there's a newer version or rewrite of this.

**Comment by cklosowski** [comment]
Possible candidate? https://github.com/Jeckerson/array2xml/blob/master/array2xml.php

**Comment by cklosowski** [comment]
Found one here: https://raw.githubusercontent.com/jmarceli/array2xml/master/ArrayToXML.php

This one seems to solve some of our issues, I think we'll have to make some slight changes to it for backwards compatibility, but that shouldn't be too bad.

**Comment by cklosowski** [comment]
Actually, not sure we can remain backwards compatible here. I think it might be best to just add the new class and throw a deprecated notice on the old one

**Comment by cklosowski** [comment]
Easiest way to replicate this is to have a site with Software Licensing enabled.

Use the following endpoint `/edd-api/v2/products/?format=xml`

In my experience the easiest way to make sure the error was triggered is by having variable pricing enabled on products.

**Comment by sunnyratilal** [comment]
Tested and the correct XML is being generated
