### ISSUE TITLE
"Quantities" shouldn't display on the cart widget when not enabled 

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#5832]
It dosen't make sense to show the item cart quantities within the EDD Cart widget when they are disabled by default. It adds extra (unneeded) real estate to the widget that would be better kept for longer product titles.

Here is what I am referring to:

<img width="264" alt="screenshot 2017-06-26 13 53 59" src="https://user-images.githubusercontent.com/22668877/27540200-3fa427b2-5a77-11e7-89fe-5cdb6f3a3643.png">

**Comment by davidsherlock** [comment]
For clarity I am not referring to the "Number of items in basket:" section but the per-item quantities.

**Comment by SDavisMedia** [comment]
Agreed. That doesn't make much sense.

**Comment by pippinsplugins** [comment]
Perfect, merged.
