### ISSUE TITLE
allow hyphen in discount codes

### ISSUE THREAD

**Issue by webzunft** [easydigitaldownloads/easy-digital-downloads#5839]
I noticed that hyphens are not allowed in the pattern for discount codes anymore.
Hyphens make such codes more readable and I would really like to see them being allowed.

**Comment by BFTrick** [comment]
If this tweak is likely to be approved I can send the PR.

**Comment by pippinsplugins** [comment]
I have no qualms with allowing hyphens in discount codes.

**Comment by cklosowski** [comment]
This seems like a simple enough fix...we'll have to be sure to update any comparison and validation code that goes along with the sanitization.

**Comment by cklosowski** [comment]
@sunnyratilal mind giving this a run through?
