### ISSUE TITLE
Support Variable Price IDs in the payment import/export

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#5841]
As it stands you can only import the item amount and tax. The tax is denoted inside `{}` and is always included. We could just append another item that gives the price ID...this allows an import and export of payments with prices, tax and price IDs for variable pricing.

**Comment by cklosowski** [comment]
For testing, the new Raw Products format would be:
`Download Name|Price{tax}{price_id}` or for an actual item:
`Download Name|199.00{19.90}{1}` (for Download Name price ID 1)

**Comment by pippinsplugins** [comment]
Looks good, merged.
