### ISSUE TITLE
Add support for a currency to edd_currency_decimal_filter

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#5844]
Right now the `edd_currency_decimal_filter` function uses 2 as the default, but it might be nice to allow passing in a currency, so that the filter can easily return for any currency, not just the store default.

For instance, right now if you were a shop running both bitcoin and USD, the function would only ever run the bitcoin `8` digit accuracy during the purchase, but if you allow multi currency, you could allow someone to use this function to determine the decimal points at will.

**Comment by sunnyratilal** [comment]
Merged.
