### ISSUE TITLE
Run negative luhn check on card name field

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#5845]
Moved from Stripe: https://github.com/easydigitaldownloads/edd-stripe/issues/231

In short, it's possible to put a valid credit card number into the card name field. While this would classify as 'user error', we could prevent it by checking if the name matches a Luhn format, and stop the submission. This is a problem b/c if a card number is then passed into all kinds of fields it should not be in full text.

**Comment by cklosowski** [comment]
This is completed. I'm not sure we need to go a long way to help the user out here, but I'm simply adding the `error` class on the Card Name field when the content there matches the `Luhn` format. If it passes the luhn check, this field is highlighted in red, and the purchase button is disabled.

If it does not match the format, it is cleared and the purchase can be completed.

I would say that, simply stopping checkout and making the red border is enough to tell the user `Hey Don't do that`.

**Comment by cklosowski** [comment]
To test, enable Stripe or any other CC gateway.

1) Use anything other than a CC card format - For success
2) Use anything in the form of a CC card format - For Failure
3) Type in a CC card number...then change it, and type in something valid - Should pass
4) Type in any name, then delete it and add in a CC card format - Should fail.

**Comment by cklosowski** [comment]
@leewillis77 Pinging you so we can keep you posted on this.

**Comment by SDavisMedia** [comment]
@cklosowski all testing steps behaved as expected on `issue/5845`. :+1:

**Comment by leewillis77** [comment]
Thanks Chris!
