### ISSUE TITLE
Unneeded validation of billing fields when cart total is $0

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#5846]
Initially reported here: https://github.com/easydigitaldownloads/edd-stripe/issues/234

The function `edd_purchase_form_validate_cc` runs Zip Code validation against a country, even when the cart is $0. This needs to be removed. There is no reason to run this validation unless those fields are present on the screen.

To replicate do the following ( I used stripe ):
1) Add product to the cart
2) Use Stripe
3) Set a postal code/zip
4) Remove country and state (set to blank)
5) Apply a 100% discount
6) Purchase.

What's happening is that in some cases, someone might change the fields that are required for checkout. If they initially used no fields (like stripe allows), when the stripe card/customer is created it may not have those fields, however, if you then change the validation to require country/zip or full address, the card data may not exist for it, and since the field forms are empty, it won't pass CC validation, even though it's free.

**Comment by SDavisMedia** [comment]
Easily replicated again on EDD and Stripe `master`. Confirmed fixed on EDD `issue/5846`. :+1:

**Comment by pippinsplugins** [comment]
@SDavisMedia could you retest now?

**Comment by SDavisMedia** [comment]
Hmmm... testing on EDD `issue/5846` (pulled down the latest) and Stripe `master`, now I'm back to getting a checkout error:

`Error: The zip / postal code you entered for your billing address is invalid`

**Comment by SDavisMedia** [comment]
Just confirmed that without the last commit, it works as expected.

Shouldn't the login be:

`if ( ! empty( $card_data['card_zip'] ) && edd_get_cart_total() > 0 ) {`

instead of

`if ( ! empty( $card_data['card_zip'] ) && ! edd_get_cart_total() > 0 ) {`

?

**Comment by SDavisMedia** [comment]
Testing.

**Comment by sunnyratilal** [comment]
Yes, you're right @SDavisMedia

**Comment by sunnyratilal** [comment]
Once last test - sorry @SDavisMedia!

**Comment by SDavisMedia** [comment]
I deleted my comment... thought I was trippin lol. But yes, the last patch work now. :+1:
