### ISSUE TITLE
Add customer column to users page

### ISSUE THREAD

**Issue by collizo4sky** [easydigitaldownloads/easy-digital-downloads#5848]
I would love for EDD to add a customer column to WordPress users listing page.

![image](https://user-images.githubusercontent.com/4140659/27785662-3d91619c-5fd6-11e7-8567-bf68c8e7b27d.png)

I get lot's of demo/spam users and with that column added, i can be able to once in a while delete them without accidentally deleting a customer account.

Can we get this added?

**Comment by pippinsplugins** [comment]
@collizo4sky we can certainly consider it!

**Comment by collizo4sky** [comment]
Please do.

**Comment by cklosowski** [comment]
Going to milestone this for 3.0 so we can keep it on the radar to take a look when the time comes.

**Comment by sunnyratilal** [comment]
PR: #6246

**Comment by collizo4sky** [comment]
Long love EDD 😎

**Comment by nosegraze** [comment]
Left one comment on the PR, but otherwise it's working well!
