### ISSUE TITLE
HTML ID "edd_profile_billing_address_wrap" added to verify password field on [edd_profile_editor]

### ISSUE THREAD

**Issue by themeblvd** [easydigitaldownloads/easy-digital-downloads#5855]
Hi,

No biggy, but I believe the ID `edd_profile_billing_address_wrap` being added here is probably a bug:

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/0a76db1b8d7a9191146bb7e348d0f4c83b6e004a/templates/shortcode-profile-editor.php#L202

I noticed this today because I had a customer tell me they couldn't change their password on my site. It turns out I have had CSS in place awhile that hides the billing address fields. But now, hiding element `#edd_profile_billing_address_wrap` actually hides the verify password field, thus not allowing the user to actually change their password.

Anyway, I assume that is some kind of bug as this isn't a logical ID for that element and used to be in a different place on the profile page; so I just wanted to point that out. Thanks for all you guys do with this plugin!

**Comment by SDavisMedia** [comment]
That's a mistake indeed! Thanks and sorry for the inconvenience. We'll get that fixed for the next release.

**Comment by pippinsplugins** [comment]
Merged.
