### ISSUE TITLE
easy-digital-downloads-remove-past-transactions-and-logs

### ISSUE THREAD

**Issue by rachidaitouaissi** [easydigitaldownloads/easy-digital-downloads#5858]
easy-digital-downloads-remove-past-transactions-and-logs plugin wont activate with this current version of easy digital download, i get a " Plugin could not be activated because it triggered a fatal error."

Plugin link : https://github.com/nickast/easy-digital-downloads-remove-past-transactions-and-logs/blob/master/easy-digital-downloads-remove-past-transactions-and-logs.php

Any help thank you

**Comment by cklosowski** [comment]
This github repository is for the tracking of Easy Digital Downloads core development, and the plugin you're referring to is not built by this team. You will need to lave an issue with that developer to correct their plugin code.

I apologize if that plugin isn't working but we're not able to support 3rd party add-ons.
