### ISSUE TITLE
Two Different WebHooks. Docs Vs. Options Page.

### ISSUE THREAD

**Issue by KrashKartMedia** [easydigitaldownloads/easy-digital-downloads#5861]
What Up. How are you guys? We just launched the new maintainn.com with EDD & Software licensing. I love it. The only issue we're having is with the webhooks. 

Our site tells us to use: 

https://cloudup.com/cl6x975xrkL

Your documentation tells us to use:

https://cloudup.com/cF8VMZI6NXq

Can you please clarify the webhook to use? We have two subscriptions we're trying to import. we have the correct transaction ID and subscription Id. But the renewal failed and the license is set to "expired"

**Comment by KrashKartMedia** [comment]
Here's the system INFO

### Begin System Info ###

-- Site Info

Site URL:                 https://maintainn.com
Home URL:                 http://maintainn.com
Multisite:                No

-- Hosting Provider

Host:                     WP Engine

-- User Browser

Platform:                 Apple 
Browser Name:             Chrome  
Browser Version:          59.0.3071.115 
User Agent String:        Mozilla/5.0 (Macintosh; Intel Ma 
			  c OS X 10_12_5) AppleWebKit/537.
                          36 (KHTML, like Gecko) Chrome/59
                          .0.3071.115 Safari/537.36
                          
-- WordPress Configuration

Version:                  4.7.5
Language:                 en_US
Permalink Structure:      /%postname%/
Active Theme:             Maintainn-2017 1.0.0
Show On Front:            page
Page On Front:            Homepage (#61)
Page For Posts:           News (#199)
ABSPATH:                  /nas/content/live/maintainn/
Remote Post:              wp_remote_post() works
Table Prefix:             Length: 3   Status: Acceptable
WP_DEBUG:                 Disabled
Memory Limit:             40M
Registered Post Stati:    publish, future, draft, pending, private, trash, auto-draft, inherit, refunded, failed, revoked, abandoned, processing, active, inactive, acf-disabled, cancelled, edd_subscription, preapproval

-- EDD Configuration

Version:                  2.7.11
Upgraded From:            None
Test Mode:                Disabled
AJAX:                     Enabled
Guest Checkout:           Enabled
Symlinks:                 Disabled
Download Method:          Direct
Currency Code:            USD
Currency Position:        before
Decimal Separator:        .
Thousands Separator:      ,
Upgrades Completed:       upgrade_payment_taxes,upgrade_customer_payments_association,upgrade_user_api_keys,remove_refunded_sale_logs,upgrade_24_subscriptions,fix_24_stripe_customers,sl_add_bundle_licenses,sl_deprecate_site_count_meta,recurring_27_subscription_meta,stripe_customer_id_migration

-- EDD Page Configuration

Checkout:                 Valid
Checkout Page:            http://maintainn.com/checkout/
Success Page:             http://maintainn.com/welcome-to-maintainn/
Failure Page:             http://maintainn.com/checkout/transaction-failed/
Downloads Slug:           /downloads

-- EDD Gateway Configuration

Enabled Gateways:         PayPal Standard, Stripe
Default Gateway:          Stripe

-- EDD Tax Configuration

Taxes:                    Disabled
Tax Rate:                 0
Display On Checkout:      Not Displayed
Prices Include Tax:       No

-- Must-Use Plugins

Force Strong Passwords - WPE Edition: 1.6.4
ManageWP - Worker Loader: 
Stop long comments: 0.0.4
wds-mu-plugins-include.php: 
WP Engine System: 3.2.1

-- WordPress Active Plugins

Advanced Custom Fields PRO: 5.5.14
Easy Digital Downloads: 2.7.11
Easy Digital Downloads - Auto Register: 1.3.9
Easy Digital Downloads - PDF Invoices: 2.2.20
Easy Digital Downloads - Recurring Payments: 2.7.3
Easy Digital Downloads - Software Licenses: 3.5.16
Easy Digital Downloads - Stripe Payment Gateway: 2.6.2
Easy Digital Downloads Custom WDS: 0.6
Gravity Forms: 2.2.3
If Menu: 0.6
Maintainn Master Plugin: 2.0.0
Post Types Order: 1.9.3.1
Really Simple CAPTCHA: 2.0
Recently Registered: 3.4.3
User Switching: 1.0.9
WordPress Importer: 0.6.3
WP Migrate DB Pro: 1.7.2
WP Migrate DB Pro CLI: 1.3
WP Migrate DB Pro Media Files: 1.4.7
Yoast SEO: 4.9

-- WordPress Inactive Plugins

Akismet Anti-Spam: 3.3.2
Configure SMTP: 3.1
Easy Digital Downloads - External Products: 1.1.0
Easy Digital Downloads - Fraud Monitor: 1.1
Easy Digital Downloads - Mail Chimp: 2.5.6
Easy Digital Downloads - PayPal Website Payments Pro and PayPal Express Gateway: 1.4.2.4
Easy Digital Downloads integration for HelpScout: 1.1
Google Sitemap by BestWebSoft: 3.0.9
Gravity Forms Coupons Add-On: 2.5
Gravity Forms Help Scout Add-On: 1.4
Gravity Forms HipChat Add-On: 1.1
Gravity Forms Stripe Add-On: 2.2
Gravity Forms User Registration Add-On: 3.7
Hash Link Scroll Offset: 0.1.8
InstaGo: 1.0.1
iThemes Sync: 2.0.0
Jetpack by WordPress.com: 5.0 (needs update - 5.1)
Limit Login Attempts: 1.7.1
Maintainn - Notifications: 0.1-alpha
Maintainn Account: 1.0.0
Maintainn Announcements: 1.0.0
Maintainn Clients: 1.0.0
Maintainn Customer Meta: 1.0
Maintainn Dashboard Widget: 1.3.0
Maintainn Emphasis: 1.0.0
Maintainn Expirator: 0.1
Maintainn FAQ: 1.0.0
Maintainn Features: 1.0.0
Maintainn Home Page Options: 1.0.0
Maintainn KPI: 1.0.0
Maintainn Plans: 1.0.0
Maintainn Team: 1.0.0
Maintainn Tools: 2.0.2
Maintainn User Info: 1.0
ManageWP - Worker: 4.2.19
Page Links To: 2.9.9
Peter's Login Redirect: 2.9.1
Plugins Admin Bar: 1.4
Public Post Preview: 2.6.0
Query Monitor: 2.13.4
Reactor: Core: 0.2.5
Soliloquy: 2.4.0.2
Stripe Recurring Payments: 1.7
WDS Custom Login Page: 1.0.0
WDS Custom Login Page: 1.1
WDS Post Editor Updates: 1.0.0
WDS Simple Page Builder: 1.5
WordPress Zero Spam: 3.0.6
WP-PageNavi: 2.91 (needs update - 2.92)
WP Engine Automated Migration: 1.48
WP REST API: 1.2.5
WP User Profiles: 2.1.0

-- Webserver Configuration

PHP Version:              5.6.30-1+wpengine8
MySQL Version:            5.6.36
Webserver Info:           Apache

-- PHP Configuration

Memory Limit:             512M
Upload Max Size:          50M
Post Max Size:            100M
Upload Max Filesize:      50M
Time Limit:               3600
Max Input Vars:           1000
Display Errors:           N/A
PHP Arg Separator:        &

-- PHP Extensions

cURL:                     Supported
fsockopen:                Supported
SOAP Client:              Installed
Suhosin:                  Not Installed

-- Session Configuration

EDD Use Sessions:         Enabled
Session:                  Enabled
Session Name:             PHPSESSID
Cookie Path:              /
Save Path:                /var/lib/php/sessions
Use Cookies:              On
Use Only Cookies:         On

### End System Info ###

**Comment by cklosowski** [comment]
@KrashKartMedia github is used for development tracking of Easy Digital Downloads core. The information in question is related to the Recurring and Stripe addons.

The short answer is either of them will work. WordPress, will use `index.php` in the backend when it is not defined explicitly...so:
`domain.com/?edd-listener=stripe` and `domain.com/index.php?edd-listener=stripe` is the same thing.

Please use contact us via https://easydigitaldownloads.com/support for future support requests.
