### ISSUE TITLE
Unable to Configure Checkout Page

### ISSUE THREAD

**Issue by CelesteMit** [easydigitaldownloads/easy-digital-downloads#5868]
My Checkout Page was configured until the latest update.  Now All of my blue Add to Cart and Purchase now Buttons for my Store and Checkout pages show this error message in place of those buttons: **Error: No checkout page has been configured. Visit Settings to set one.**  

Why can I no longer configure any pages for my WP Website pages in EDD?  The General Settings/Pages Drop Down Menus no longer work.  When I click on any of them I get nothing but a blank blue space, no list of pages that I can configure. Why is this happening all of a sudden?  I am now unable to test or launch my website because of this error. HELP ME!!!  PLEASE!!

**Comment by pippinsplugins** [comment]
Hi there!

Please go ahead and open a support ticket through our support portal: https://easydigitaldownloads.com/support

we use GitHub for development tracking only.

**Comment by CelesteMit** [comment]
Okay, I will.  I was confused as where to go since that GitHub site was mentioned as one to go to for support.  Thank you!

 

Celeste Mitchell
