### ISSUE TITLE
WPLANG is no longer used

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#5869]
In system info exporter, it gets the language the site is set to using the WPLANG constant. That is no longer used by WordPress and can cause an incorrect value to be placed in the system info file. 

One customer has their site set to Swedish but the system info file says it is en_US because that is the default.

**Comment by spencerfinnell** [comment]
`get_locale()` would be a good replacement.

**Comment by sunnyratilal** [comment]
Merged
