### ISSUE TITLE
Issues: Broken Feature Image + Broken Checkout + Your Website is down!!!

### ISSUE THREAD

**Issue by SIMONuser1** [easydigitaldownloads/easy-digital-downloads#5871]
Dear EDD,

2 major issues: 

1. When adding a new product as a vendor, the the featured image is removed when saved. It has to be reuploaded a second time in the edit screen. TERRIBLE! 

2. I cannot checkout a product (Both paid and non-paid) as the Paypal API DOES NOT WORK. 

3. Your Website has been down for days. I cannot do anything with your business if I cannot contact. FIX. 

Blake

**Comment by SDavisMedia** [comment]
Okay, Blake.

1. Open a ticket. We can troubleshoot. https://easydigitaldownloads.com/support/

2. The PayPal API wouldn't have anything to do with a "non-paid product," so something else is wrong with your configuration. Mention this problem when you open your ticket.

3. The site has not been down for days. I am 100% sure of that. If the support form does not work, email us directly at support@easydigitaldownloads.com. Be sure to include your license key for Frontend Submissions and also attach your system info file (Downloads -> Tools -> System Info).
