### ISSUE TITLE
HTTP Issue - When Uploading Image

### ISSUE THREAD

**Issue by SIMONuser1** [easydigitaldownloads/easy-digital-downloads#5872]
Dear EDD,

When as a vendor, I upload an image, I cannot upload certain images due to HTTP error. 

Why? 

![example](https://user-images.githubusercontent.com/15627406/28207214-1f787310-6889-11e7-981d-711b84e997f9.PNG)

Blake

**Comment by SDavisMedia** [comment]
Please do not request support on GitHub. I replied to your other issue letting you know how to contact support.
