### ISSUE TITLE
Core plugin integration suggestions

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#5873]
There are a few smaller (free) plugins developed by members of the EDD team I feel should be part of core EDD. This keeps the base plugin load light, since everything will be included by default in core.

Here are my suggestions:

**edd-variable-pricing-descriptions** - https://github.com/easydigitaldownloads/edd-variable-pricing-descriptions

**edd-auto-register** - https://github.com/easydigitaldownloads/edd-auto-register

**edd-downloads-as-services** - https://github.com/easydigitaldownloads/edd-downloads-as-services

**edd-empty-cart** - https://github.com/easydigitaldownloads/edd-empty-cart

**Comment by cklosowski** [comment]
Thanks for the suggestions @davidsherlock. At this time we're not looking to merge any add-ons into EDD core, although it is something that we revisit from time to time. I'll add these to the list of things to discuss in our next go through, but at this time we're not looking to do any 'Feature Plugin' additions.
