### ISSUE TITLE
Purchase Receipt Notification Email NOT Being Sent To Buyer After PayPal Sale

### ISSUE THREAD

**Issue by 6white6** [easydigitaldownloads/easy-digital-downloads#5877]
Hi

My issue is that Purchase Receipt emails are not being triggered after a successful PayPal sale.
Attempted the trouble-shooting solutions mentioned within EDD but no success. 
Can anyone help?

These are the only Plugins that are installed:

WP Meta and Date Remover
Kirki Toolkit
Limit Login Attempts
Disable Comments
Akismet Anti-Spam

Thanks

J-White

**Comment by pippinsplugins** [comment]
Hi there!

Please go ahead and open a support ticket through our support portal: https://easydigitaldownloads.com/support

we use GitHub for development tracking only.

Also please see this guide: http://docs.easydigitaldownloads.com/article/189-email-receipts-are-not-being-sent
