### ISSUE TITLE
Missing Purchase Receipt on Checkout and Payment 

### ISSUE THREAD

**Issue by CelesteMit** [easydigitaldownloads/easy-digital-downloads#5878]
Here's the issue I am having:
My customer purchased a download but there is no link on the Purchase Confirmation Page for the download and her purchase history isn't showing.  She received an error message: Sorry, trouble retrieving payment receipt.  When I looked in the Customers Account it shows she paid but her status is pending. What step did I miss?

I am using the buttons I created on Paypal not the EDD purchase buttons.  I disabled the EDD purchase link in the Download Settings for each digital download product.

In edit Paypal Payment Buttons, under advanced features I checked  Take customers to the URL when they finish checkout: https://www.wisertravelagents.com/purchase-confirmation/

On the purchase confirmation page in WP, I just noticed Add New Custom Field - Name  edd_download_files

I do not have that custom field selected nor do I know what VALUE I am supposed to add next to that field.  What am I doing wrong that the purchase receipt does not show on the purchase  confirmation page? What is the Value needed for the download files next to custom field?  
Thanks!

![missing_purchase_receipt_7 18 17](https://user-images.githubusercontent.com/30058057/28332838-f7c3474e-6baa-11e7-9885-37cabef60a05.png)

![purchase_confirmation_setup](https://user-images.githubusercontent.com/30058057/28332845-fcb4890c-6baa-11e7-8023-c8f0f4ffb923.png)

**Comment by cklosowski** [comment]
@CelesteMit Github is used for development tracking only. Please head over to https://easydigitaldownloads.com/support and reach out to us there.
