### ISSUE TITLE
Sales exports contain correct number but incorrect items

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/easy-digital-downloads#5880]
Same as #5678 but for sales exports instead of downloads. PR coming. [Reported ticket](https://secure.helpscout.net/conversation/398940702/63232/).

**Comment by brashrebel** [comment]
Ok, a little confused about my PR for some reason getting other commits included. Only [04d8f83](https://github.com/easydigitaldownloads/easy-digital-downloads/commit/04d8f83a1528bd04a27c75992d1e9d0dc2774d45) pertains to this issue.

**Comment by pippinsplugins** [comment]
Looks good, merged.
