### ISSUE TITLE
EDD()->html->product_dropdown includes products in trash

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#5884]
The product_dropdown element includes products that are in the trash. To replicate, make sure you have a product in the trash and then in EDD Recurring, attempt to make a new subscription. When adding the product for that subscription, search for the product in your trash and it will appear. 

Proposal: 
Make product dropdown only include products that are not in the trash by default.

**Comment by SDavisMedia** [comment]
Agreed. I went to modify [these args](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/8f75211c9c26321ff81c15eee64d6dcf6921c315/includes/class-edd-html-elements.php#L50) for get_posts() and it made no difference. 🤔 Curious to see why that didn't work.

**Comment by cklosowski** [comment]
This has to be done in two places...since we only load the first X number of downloads for the dropdown, and then use Chosen to do an AJAX request for the rest, we need the AJAX handler to also restrict to items not in the trash.

**Comment by cklosowski** [comment]
Looking at it closer,

The initial check for products will not include trashed items, since it just simply calls `get_posts`, however the AJAX download search WILL return `trashed` posts for user wo have the `edit_prodcuts` cap.

```
	// If the user can't edit products, limit to just published items
	if( ! current_user_can( 'edit_products' ) ) {
		$where .= "AND `post_status` = 'publish' ";
	}
```

It's only restricting the downloads to the `publish` status if the user viewing the dropdown can't `edit_products`.

What type of expected behavior should we do here? I think admins should be able to see all post statuses in some cases....

**Comment by SDavisMedia** [comment]
Definitely confirmed the behavior you described, @cklosowski. `issue/5884` fixes it. :+1:

Not sure about the filter, though. It appears to work with the pre-populated list but it doesn't seem to search the rest. For example, I used this:

```php
function test( $product_args ) {
	$product_args = array(
		'post_type'      => 'download',
		'orderby'        => 'title',
		'order'          => 'ASC',
		'post_status'    => array( 'trash', 'publish' ),
		'posts_per_page' => $args['number'],
	);
  	return $product_args;
}
add_filter( 'edd_product_dropdown_args', 'test' );
```

I named one trashed item to be first in the list. I named another to be towards the end of the list (alphabetically). The trashed item starting with an A showed up in the pre-populated list just fine. The one relying on search can't be found.

**Comment by SDavisMedia** [comment]
Disregard my filter issues above. Wrong filter. Still working.

**Comment by SDavisMedia** [comment]
Got some help with the filter offline. Tested and it's working well. :+1:

**Comment by cklosowski** [comment]
Example filters to use:
```
function test_dropdown_status( $status ) {
	return array_unique( array_merge( $status, array( 'trash' ) ) );
}
add_filter( 'edd_product_dropdown_status', 'test_dropdown_status', 10, 1 );
```

```
function test_dropdown_status( $status ) {
    return array( 'trash', 'publish' );
}
add_filter( 'edd_product_dropdown_status', 'test_dropdown_status', 10, 1 );
```

```
function test_dropdown_status( $status ) {
    return array( 'publish', 'draft' );
}
add_filter( 'edd_product_dropdown_status_nopriv', 'test_dropdown_status', 10, 1 );
```

**Comment by mintplugins** [comment]
Confirmed fixed!
