### ISSUE TITLE
Update notice error - Trying to get property of non-object

### ISSUE THREAD

**Issue by stillatmylinux** [easydigitaldownloads/easy-digital-downloads#5889]
The plugins page displays an warning on the update notice.  

`Notice: Trying to get property of non-object in /wp-admin/includes/update.php on line 364`

The bug is due to adding an array instead of an object when saving the _site_transient_update_plugins transient.

EDD_SL_Plugin_Updater.php v1.6.13 (Line 115)

    else {

        $_transient_data->response[ $this->name ][ 'slug' ] = $this->slug;

    }

Also, if you update this code so it is an object instead of an array, the plugin says there is an upgrade even if the version is current.

**Comment by pippinsplugins** [comment]
We've fixed this. See #https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5897
