### ISSUE TITLE
Variable pricing bundle purchases give access to incorrect product files

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#5894]
To replicate:

* Create Product One: two price options, two files ... one assigned to each price option:
<img width="1032" alt="image 2017-07-26 at 7 43 39 pm" src="https://user-images.githubusercontent.com/2359131/28653956-7eafe334-7245-11e7-8153-affa2eba3b9e.png">

* Create Product Two: two price options, two files ... one assigned to each price option (same as above):
<img width="1031" alt="image 2017-07-26 at 7 44 31 pm" src="https://user-images.githubusercontent.com/2359131/28653958-827f9996-7245-11e7-829d-b84202f5ab77.png">

* Create Bundle: two price options, bundle type, a row for each of the above price options (so 4 total) and just make sure the price assignments cover all of the included product price options:
<img width="1032" alt="image 2017-07-26 at 7 45 08 pm" src="https://user-images.githubusercontent.com/2359131/28653960-85ad886c-7245-11e7-9f87-92f1d88d374b.png">

* Purchase bundle first option and confirm that the receipt matches the configuration (it does):
<img width="752" alt="image 2017-07-26 at 7 47 24 pm" src="https://user-images.githubusercontent.com/2359131/28653961-87bc2636-7245-11e7-9246-864d66d2e3d8.png">

* Purchase receipt email and sales notification email with the {download_list} tag:
<img width="669" alt="image 2017-07-26 at 7 48 13 pm" src="https://user-images.githubusercontent.com/2359131/28653963-8b65274c-7245-11e7-87a0-906739f083c1.png">

-----

You gain access to all files, not just the ones you purchased.

**Comment by pippinsplugins** [comment]
PR submitted and ready for testing.

**Comment by SDavisMedia** [comment]
Confirmed fixed on new purchases as well as resending the purchase receipt for purchases made when the bug existed. :+1:

**Comment by ciorici** [comment]
Sorry for writing in a closed ticket, but I think I have the same problem, but not in the email receipt, but in the actual [download_history] shortcode. In short, even if I purchase a bundle product with a pricing option that should give access to specific downloads, I get access to all downloads.
I have also opened a new ticked on easydigitaldownloads.com - #78392.


Let's say I have a product with 2 pricing options:

![foodica-theme](https://user-images.githubusercontent.com/1674706/37567659-459b942e-2aca-11e8-8736-d469f40fbb8b.png)

and here is the bundle where only the 2nd pricing option called Pro should have access to both files.

![bundle](https://user-images.githubusercontent.com/1674706/37567667-6ce13520-2aca-11e8-9d35-687666834e87.png)

Now when I try to buy the Standard option, I also get access to the file from Pro option as well:

![screen shot 2018-03-18 at 15 54 19](https://user-images.githubusercontent.com/1674706/37567674-86560954-2aca-11e8-8ea6-e20d0d708f89.png)

**Comment by cklosowski** [comment]
@ciorici it does not look like you defined a variable price for your first option in the bundle, only the 2nd one where you've connected it to the `extended` license. 

Your first bundle, needs to be connected to the `Single License` to do what you are expecting.
<img width="638" alt="screen shot 2018-03-19 at 10 30 36 am" src="https://user-images.githubusercontent.com/1390124/37611788-951377a6-2b60-11e8-9ee3-15af94df5d9c.png">

**Comment by ciorici** [comment]
@cklosowski I've tried that too. In fact I've tried a lot of combinations, and for some reasons, a bundle with 2 different pricing can give you access to files that should be a part of a specific pricing option only.

If we assume that Single License = access to 1 file (theme), and Extended License = access to 2 files (theme+psd), then I had the impression that it would be enough to select just the product Foodica (without one of its pricing option) and it would automatically pick the Default option (which is in fact Single License). However, even after selecting there "Foodica: Single License", it will grant me access to the PSD file which should be a part only of the Pro (Extended) option.

Let's try again to check in the following screenshots if I did everything correctly:

![foodica-product](https://user-images.githubusercontent.com/1674706/37613766-22875754-2ba9-11e8-9cda-c092b3c019a7.png)

and the bundle options:

![bundle-options](https://user-images.githubusercontent.com/1674706/37613789-2ff817fc-2ba9-11e8-950b-0e368854dfdc.png)

Also, some side notes about a few confusions I have right now:

- If I import a CSV with payments where the product name is "Foodica", but the product has 2 pricing options, it won't assign the imported payments to the default pricing option which is "Foodica: Single License", but it would simply add access to "Foodica" download and all its files. Good thing that I've found some info about Product (Raw) thing in your documentation and I can solve this problem by replacing name of the product in CSV with "Foodica|69.00{0}{1}". Maybe you can note this for future, and would be great if the Default pricing option will be automatically assigning when importing payments.

- I'm still confused about your suggestion that I didn't defined a variable price. Why then in the list appear 3 items for Foodica when it has only 2 pricing options?

![pasted_image_3_19_18__19_15](https://user-images.githubusercontent.com/1674706/37614136-3bcb8018-2baa-11e8-9c1c-a78b3248d33f.png)

**Comment by SDavisMedia** [comment]
This is definitely a bug, not a configuration issue. It's pretty much the same issue I originally opened but instead of presenting itself in the email receipt, it's in the `[download_history]` output.

To replicate, simply follow [my original instructions](https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5894#issue-245919295). Then after the purchase, look at the `[download_history]` output (the email receipt is still fixed).

**Comment by SDavisMedia** [comment]
@cklosowski I've been playing with this for hours but not having much luck. In the `[download_history]` template, we display all download link rows as individual products, even if they were purchased as part of a bundle. We completely ignore bundles as purchased products: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/templates/history-downloads.php#L32

As each purchased product is listed, all of its files are listed [which is the bug that needs fixing]. The problem I'm running into is keeping this approach while reverse engineering each row to see if it was part of a bundle, and adjusting the links accordingly.

Without rewriting that entire section of the template to respect bundles, I don't see any other way to approach this besides what I've been attempting.

Thoughts?

**Comment by cklosowski** [comment]
The download history template is deeply flawed, even without this issue. I would say, let's see if we can rewrite that template to not be so 'half-baked'.

I would say however that the 'bug' in this issue isn't the same 'bug' we're seeing from the download history. The reason being, if you ask an individual bundle for it's download files it will respect the proper file listing, as we fixed in the email and the purchase confirmation.

The bug (which I think should be a new issue/enhancement/bug) is that the download history shortcode is far too forgiving and inflexible just due to the way it displays. EDD 3.0 will make this much easier since we'll have an easier way to query this data in the `order_items` table, instead of having to foreach through serialized data.

@SDavisMedia if you think that's the right approach, i'd suggest closing this issue, and formulating a new one with a plan on re-designing/improving the `download_history` shortcode, as that's what is lacking the ability to do the needful here.

**Comment by SDavisMedia** [comment]
@cklosowski yup we can do that. Closing.

@ciorici I would advise not using the `[download_history]` shortcode right now. Consider using `[purchase_history]` instead, as it was built to replace `[download_history]` some years ago. We will rebuild `[download_history]` some time after our major 3.0 release. But for now, if you need the aforementioned bundle configuration, it's best to avoid that shortcode.
