### ISSUE TITLE
Error: Missing Stripe token. Please contact support.

### ISSUE THREAD

**Issue by anamwp** [easydigitaldownloads/easy-digital-downloads#5902]
Hello,
I am using stripe extension. When I select stripe payment option from checkout page, fill the all necessary fields in the checkout fields and hit the Purchase button in the checkout field then its gives me this error.

**Error: Missing Stripe token. Please contact support.**

I choose stripe modal for the checkout page but it also give no modal. 

**My site is running on NGINX**

Its works fine on local but in the live version its doesn't work. I also set my live and secret key in my site. 

What should I do ? 
I appreciate fast response. 
Thanks.

**Comment by pippinsplugins** [comment]
Hi there!

Please go ahead and open a support ticket through our support portal: https://easydigitaldownloads.com/support

we use GitHub for development tracking only.
