### ISSUE TITLE
Amazon S3 Extension

### ISSUE THREAD

**Issue by KimberleyMorrison** [easydigitaldownloads/easy-digital-downloads#5903]
Hi

I am struggling to connect my Amazon S3 account via the extension.

While your documentation is good, it unfortunately doesn't relate to the changed Amazon S3 IAM interface and so I just can't get them to connect.

Any help would be appreciated

Kim

**Comment by pippinsplugins** [comment]
Hi there!

Please go ahead and open a support ticket through our support portal: https://easydigitaldownloads.com/support

we use GitHub for development tracking only.
