### ISSUE TITLE
Empty Base State / Province displayed when no pre-populated data present

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#5905]
I posted this a while back but can't find the original issue, so re-posting it again for reference. 

There is an issue with choosing a default store location country without pre-populated states and saving the settings. An empty "State" select continues to show even though it's not required after saving.

See here: 

![screenshot 2017-07-29 18 49 31](https://user-images.githubusercontent.com/22668877/28747097-f810af06-748e-11e7-9cf1-292821149c2a.png)

**Comment by SDavisMedia** [comment]
To replicate:

1. Select `United Kingdom` as your base country. The `Base State/ Province` setting will go away.
2. Save the page.
3. `Base State/ Province` comes back as an empty select.

**Comment by cklosowski** [comment]
Since this one has A PR. I'm closing #5200 as a duplicate.
