### ISSUE TITLE
Full stops missing from various core EDD setting descriptions

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#5906]
To maintain consistency across the admin panel settings, full stops should be used to terminate all descriptions for uniformity.

Here the list of (fixed) descriptions:

**Currency**

`The symbol (usually , or .) to separate thousands.`

`The symbol (usually , or .) to separate decimal points.`

**Payment Gateways**

`Don't see what you need? More Payment Gateway options are available here.`

`You will also need to configure your gateway settings if you are accepting credit cards.`

**Purchase Receipts**

`Enter the subject line for the purchase receipt email.`

`Enter the heading for the purchase receipt email.`

**New Sale Notifications**

`Enter the subject line for the sale notification email.`

`Enter the email address(es) that should receive a notification anytime a sale is made, one per line.`

I'm aware this is a bit OCD, but worth mentioning nonetheless :)

**Comment by davidsherlock** [comment]
A few more:

**Add New Discount**

`The name of this discount.`

`Enter the expiration date for this discount code in the format of mm/dd/yyyy. For no expiration, leave blank.`

**Comment by SDavisMedia** [comment]
:+1: I'll go through and look for more.

**Comment by SDavisMedia** [comment]
That should cover it. This will change some translation-ready strings, so I don't know if the guys will want to merge it yet or not. But I would definitely rather have consistency. That did always annoy me.

**Comment by pippinsplugins** [comment]
I'm good with it, merged!
