### ISSUE TITLE
Undefined offset 0 in customer query, breaks pagination control

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/easy-digital-downloads#5911]
I _think_ this is cause and effect but am not 100% certain. Anyway, [a customer](https://secure.helpscout.net/conversation/406181491/64031/?folderId=180499) reported that pagination controls disappear on the customers list page after you navigate past page 1. Only page 1 shows the pagination controls and no others do. I replicated on multiple sites and locally see this PHP error:

```
Notice: Undefined offset: 0 in /Users/kylemaurer/Documents/Websites/edd.dev/wp-content/plugins/easy-digital-downloads/includes/class-edd-customer-query.php on line 363
Notice: Trying to get property of non-object in /Users/kylemaurer/Documents/Websites/edd.dev/wp-content/plugins/easy-digital-downloads/includes/class-edd-customer-query.php on line 363
```

**Comment by pippinsplugins** [comment]
I've confirmed the bug on our own EDD site.

**Comment by sunnyratilal** [comment]
PR opened at #5913

**Comment by SDavisMedia** [comment]
Replicated on `master`. Confirmed fixed on `issue/5911`. :+1:
