### ISSUE TITLE
Processing status brackets empty when no data present

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#5915]
Pretty simple one, the new "Processing" status shows like this for me: 

Processing () 

When other statuses that contain no data, they show like this Abandoned (0). For uniformity purposes it should display the same for processing.

<img width="784" alt="screenshot 2017-08-01 12 46 59" src="https://user-images.githubusercontent.com/22668877/28823957-de977c1e-76b7-11e7-8491-8d84ec6b8545.png">

**Comment by SDavisMedia** [comment]
Any reason why this status can't be set using Bulk Edit?

**Comment by SDavisMedia** [comment]
Added. I see no reason why it shouldn't be there.

**Comment by pippinsplugins** [comment]
Looks good, thanks @SDavisMedia!
