### ISSUE TITLE
Introduce a SUPPORT file

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#5928]
GitHub now supports a SUPPORT markdown file.

What this does is amends the notice currently made on opening a new ticket (the one we made by having a CONTRIBUTING markdown file) and adds a link to the markdown file which should describe where people can find support:
![image](https://user-images.githubusercontent.com/1324637/29007071-8fae58f0-7ac9-11e7-85a7-17466dc6bf71.png)

This allows users opening tickets to instead be redirected to the proper support channel.

Given the number of tickets we refer to for support, we should draft a SUPPORT file for here and then add them to the other popular repos.

More information on this new file is found here: https://help.github.com/articles/adding-support-resources-to-your-project/

**Comment by cklosowski** [comment]
Nice. Top priority for me tomorrow.

**Comment by chriscct7** [comment]
https://github.com/resin-io/etcher/blob/master/SUPPORT.md is sort of an example of this

**Comment by chriscct7** [comment]
```
Getting help with Easy Digital Downloads, EDD themes and EDD addons
========================

We look forward to helping resolve any issues or relaying any feedback or ideas you have about Easy Digital Downloads. To report an issue, receive support, give us feedback, or send us an idea please send us a support ticket.

Support Ticket
------

We recommend all users with support questions email us via the support form found [at easydigitaldownloads.com/support/][https://www.easydigitaldownloads.com/support/]. GitHub is used for core development only, and is not the place to seek help or report non-developer issues for Easy Digital Downloads, or EDD addons or themes.

Make sure to mention the following information to help us provide better
support:

- {items tbd}
```

**Comment by chriscct7** [comment]
Opened PR https://github.com/easydigitaldownloads/easy-digital-downloads/pull/5929

**Comment by pippinsplugins** [comment]
Excellent! Let's get a link to documentation added here.

**Comment by pippinsplugins** [comment]
Done and done!

**Comment by chriscct7** [comment]
:+1:
