### ISSUE TITLE
Inconsistent display of the total price when discount is applied directly or via URL for products w/ a free trial period

### ISSUE THREAD

**Issue by eugenesp** [easydigitaldownloads/easy-digital-downloads#5930]
Total price is displayed differently for products with a free trial period when discount code gets applied directly by clicking "Have a discount code? Click here to apply" or as a URL parameter.

### Discount code added by clicking "Have a discount code? Click here to apply"  link:

Prior to applying a discount code:
http://prntscr.com/g57396

After applying a discount code:
http://prntscr.com/g573ek

After removing the discount code:
http://prntscr.com/g573ij

### Discount code added via URL:

After applying discount code via URL:
http://prntscr.com/g574de

**Comment by cklosowski** [comment]
It's likely this is an issue with Recurring Payments, not EDD Core. If you remove Recurring Payments from the equation @eugenesp do you see the same behavior? Does EDD core provide inconsistent results when applied via URL or via the form?

**Comment by eugenesp** [comment]
Good day,

Yes, it seems like the problem gets reproduced only for products w/ recurring payments. See the last screenshot below:

### Product w/o recurring payment: ###

Via "Have a discount code? Click to enter it" link
http://prntscr.com/g5zqai

Via URL parameter "discount"
http://prntscr.com/g5zr0n

### Product WITH recurring payment and FREE trial: ###

Via "Have a discount code? Click to enter it" link
http://prntscr.com/g5zrqm

Via URL parameter "discount"  *** BUG ***
http://prntscr.com/g5zrzv

**Comment by eugenesp** [comment]
I hope to see that coupons work for products w/ recurring payments and free trial in such a way that:
a) Customer still sees that his Total Due is $0 because of a FREE trail
b) Customer can see that the coupon was applied for all subsequent months

**Comment by eugenesp** [comment]
I believe that the fix should span both EDD core and Recurring payments such that EDD is able to display both $0 price due today a discounted price for the subsequent billing periods.

**Comment by mintplugins** [comment]
This is an issue in Recurring. I will log it and we can work on it from there. Thanks @eugenesp
