### ISSUE TITLE
FES related, same filter names

### ISSUE THREAD

**Issue by kiarashi** [easydigitaldownloads/easy-digital-downloads#5931]
Just noticed that the `fes_form_legend` filter isn't unique; it appears twice.

```
return apply_filters( 'fes_form_legend', '<legend class="fes-form-legend" id="fes-' . $this->name() . '-form-title">' . $this->title() . '</legend>', $this );
return apply_filters( 'fes_form_legend', '<legend class="fes-form-legend" id="fes-submission-form-title">' . $legend . '</legend>', $this );
```

edd-fes\classes\abstracts\class-form.php (1 hit)
edd-fes\classes\forms\submission.php (1 hit)

**Comment by cklosowski** [comment]
This Github repository is for Easy Digital Downloads core development tracking _only_, not for the extensions. I'll go ahead and log an issue to investigate this, but if you find issues for extensions in the future, please use https://easydigitaldownloads.com/support.
