### ISSUE TITLE
#edd_product_notes_field should be full-width

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#5937]
For some reason the #edd_product_notes_field is 98% instead of 100%. Just a slight case of OCD, but it looks better at 100%.

**Comment by cklosowski** [comment]
Seems logical to me. @SDavisMedia, from a front end perspective, does this make sense to you too?

**Comment by davidsherlock** [comment]
On a similar note, the widths are inconsistent in certain areas within the admin panel in responsive layout.

![screenshot 2017-08-10 21 54 59](https://user-images.githubusercontent.com/22668877/29191915-433a7034-7e17-11e7-9ce6-0e78d7554a1c.png)

**Comment by SDavisMedia** [comment]
Taxonomy add/edit fields don't need to change. Those are all WordPress core styles, as inconsistent as they are. You'll get the same behavior for post cats/tags.

I agree with the product notes field. It should match the WordPress core Excerpt field CSS. @davidsherlock wanna submit a PR?

**Comment by SDavisMedia** [comment]
All goody. :+1:

**Comment by davidsherlock** [comment]
Apologies @SDavisMedia, missed your request above! Looks like the issue is fixed now though.
