### ISSUE TITLE
Bundled Products

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#594]
Need to be able to bundle products into a single product.

**Comment by DeysonOrtiz** [comment]
A suggestion would be to have an option:  Add All Digital Downloads.  This way we do not have to add all 70+ of our products individually and any new products get added on to the bundle automatically.  

Thank you :)

**Comment by pippinsplugins** [comment]
@DeysonOrtiz That's not feasible for sites that have hundreds or thousands of products.

**Comment by DeysonOrtiz** [comment]
I thought it would be an option we could turn on or off.

**Comment by pippinsplugins** [comment]
It's something we can definitely consider.

**Comment by DeysonOrtiz** [comment]
Great!  Also, here is a screenshot of how my previous service did in case you need some inspiration: https://cloudup.com/ctbhfgfnArW
I think all it would need is an additional radio button to read “All Current & New Digital Downloads”  or something like that. :)
