### ISSUE TITLE
Negative product fees not properly affecting subtotal used for tax calculation

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#5940]
When negative fees that are product-specific are added to the cart, they are not properly discounting the item subtotal that is used to calculate tax, resulting in taxes being too high.

To replicate:

- Create $100 item
- Enable taxes with a 10% rate
- Enable item quantities
- Enable Discounts Pro and create a discount for `Products in Cart` that applies when the quantity is 3 or greater

Incorrect checkout amount:

<img width="1028" alt="screen shot 2017-08-10 at 5 17 47 pm" src="https://user-images.githubusercontent.com/1034109/29194570-d933f254-7def-11e7-816b-1a9367a9cdf4.png">

Correct display would be: 

<img width="873" alt="screen shot 2017-08-10 at 5 15 51 pm" src="https://user-images.githubusercontent.com/1034109/29194552-c2870f14-7def-11e7-96b8-96d7ad2870ae.png">

Cart total should be $165.

- $150 item total
- $15 tax

Related https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4632  https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4658

Discovered through Discounts Pro https://github.com/easydigitaldownloads/edd-discounts-pro/issues/128

**Comment by SDavisMedia** [comment]
Replicated on `master` and confirmed fixed on `issue/5940`. Tested other fee-related cart configurations I could think of and I don't see anything else being impacted by this change. :+1:

**Comment by pippinsplugins** [comment]
Excellent!

We'll get @cklosowski's review on it and wait for unit tests to pass before merging.
