### ISSUE TITLE
Use download['name'] in download history shortcode instead of title

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/easy-digital-downloads#5945]
Ticket [here](https://secure.helpscout.net/conversation/412919570/64733/) with screenshot of the symptom which I replicated. Basically there are instances where the download name can show HTML in plain text. Receipt shortcode uses the `name` property and it works great but download history currently uses `get_the_title()`. Making a simple PR now that switches to the former to maintain consistency and fix this bug manifesting when Digital Badges is in use.

**Comment by brashrebel** [comment]
Well that commit should do it but I'm not sure which branch to PR against.

**Comment by cklosowski** [comment]
@brashrebel when it's a minor release `master` is fine.

Only do a release branch for a major point release `X.X`
