### ISSUE TITLE
Editing item price of item on payment fails when item contains decimal separators

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#5946]
Make a payment and then go edit it, and set the value of one of the downloads to `1,000.99` and it'll look fine on initial save...but trying to edit it again will make the 'Download Total' fail and revert to $1. If you have the Dev Tools installed, the payment meta would have an invalid value for the `price` of the item as well.

**Comment by SDavisMedia** [comment]
I had some super shaky behavior replicating. A little more extreme than you described. But I guess that's still replicating. Everything did work on `issue/5946`, though.

**Comment by SDavisMedia** [comment]
This is still working for me after the last change.
