### ISSUE TITLE
Change "Show Title" text on Download Details widget

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/easy-digital-downloads#5953]
I think it would be better to change `Show Title` to `Show Download Title`. I got this checkbox setting briefly confused with the `Title` input field, thinking I could disable it from showing, when actually it's referring to the download title.

<img width="414" alt="screenshot 2017-08-15 20 10 27" src="https://user-images.githubusercontent.com/52581/29307391-cf62e19a-81f5-11e7-8554-541d97e72805.png">

**Comment by amdrew** [comment]
PR: https://github.com/easydigitaldownloads/easy-digital-downloads/pull/5954

And after:

<img width="416" alt="screenshot 2017-08-15 20 15 45" src="https://user-images.githubusercontent.com/52581/29307597-a039c04a-81f6-11e7-9615-ccea670d29ed.png">

**Comment by pippinsplugins** [comment]
Merged.
