### ISSUE TITLE
Customer Emails display issue in admin

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#5955]
<img width="900" alt="0dd3076d8292631d8ad4a4d95c398fd7 _image 2017-08-15 at 7 56 07 am" src="https://user-images.githubusercontent.com/2359131/29321710-3073282a-8190-11e7-80b9-4b282c28de04.png">

**Comment by SDavisMedia** [comment]
This element appears to be here for some JS to use: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/admin/customers/customers.php#L416

But it's actually displaying styles because of CSS from AffiliateWP. https://github.com/AffiliateWP/AffiliateWP/blob/607c3e6b26d60309189d4a9325b62f23db438b1a/assets/css/admin.css#L394

Do y'all think this should be fixed in EDD or is it really necessary for AffiliateWP's CSS file to load on EDD customer records? @amdrew @pippinsplugins

**Comment by pippinsplugins** [comment]
I'm not seeing the issue . . . unless the blurred out email address itself is the issue. Could you elaborate?

**Comment by SDavisMedia** [comment]
@pippinsplugins not only should the HTML element here not show, if it's going to show for any reason, it shouldn't spill outside of its container.

<img width="926" alt="6e828e6aada267ba5f3285889f42a58e _image 2017-08-15 at 7 56 07 am" src="https://user-images.githubusercontent.com/2359131/29323911-31a1fe04-8197-11e7-9135-9998dba0a424.png">

**Comment by pippinsplugins** [comment]
Oh that! Sorry I didn't see that at all :P

**Comment by SDavisMedia** [comment]
Ha! Not sure why my screenshots are small and centered all of a sudden. 🤔 

I was gonna look into fixing this in EDD but I wonder if it's better to not load AffiliateWP resources here [and other unrelated pages].

**Comment by SDavisMedia** [comment]
I didn't explain this display issue well, I don't think. My bad.

To replicate:

1. Make sure you have EDD and AffiliateWP activated.
2. Go to an EDD customer record and you should see the unneeded HTML container with bad borders like my screenshots above.

Note: the purpose of the HTML container is to hold email management UI errors when necessary. For example, try to add a new email address that matches an email address that is already on the customer record and you'll see an actual error message display there.

The display issue happens because AffiliateWP uses the same class name `notice-wrap` and for some reason, AffiliateWP resources are loaded on that page. So some shared styles make the container show when it shouldn't.

While this can be addressed in AffiliateWP, I would also argue that the `notice-wrap` class shouldn't be used here in EDD. We use that class for things like the loading bar during batch processing, the [checkbox notice when resetting your store](https://cl.ly/0H1e3N350Z3l), etc. It's meant to display a pretty specific way, as a separate section at the bottom of another container.

In this case, it was never meant to display that way. It was supposed to look like [this](https://cl.ly/012k3s440C3M).

My PR changes the name of that class and the corresponding CSS/JS, taking it back to its original look and resolving the AffiliateWP conflict.

**Comment by cklosowski** [comment]
@SDavisMedia looks good, we still have a slight vertical alignment issue but the compatibility issue with AffiliateWP is fixed:
![screen shot 2018-04-02 at 12 22 24 pm](https://user-images.githubusercontent.com/1390124/38211822-87014d6c-3670-11e8-9d40-f6f81d4dabf0.png)


![screen shot 2018-04-02 at 12 21 44 pm](https://user-images.githubusercontent.com/1390124/38211802-79092946-3670-11e8-98a3-571bdb4409a8.png)

**Comment by cklosowski** [comment]
Confirmed that card notices for Recurring are not affected by this change as well.

**Comment by SDavisMedia** [comment]
@cklosowski PR updated. Should be good to merge.
