### ISSUE TITLE
EDD_Customer->update_meta throws notice

### ISSUE THREAD

**Issue by Spreeuw** [easydigitaldownloads/easy-digital-downloads#5958]
customer meta is added by a plugin using `update_meta()` on a customer object:
``` php
$customer = new EDD_Customer( $customer_id );
$customer->update_meta( $meta_key, $value );
```
Everytime this happens, PHP throws the following notice:
```
call_user_func_array() expects parameter 1 to be a valid callback, first array member is not a valid class name or object
```
It appears that this line is the culprit:
```php
add_action( 'added_customer_meta', array( EDD()->customers, 'set_last_changed' ) );
```

It seems that `EDD()->customers` is `null` when the meta is added, hence the notice. This action is executed via AJAX, at the `wp_ajax_nopriv_wp_{$action}` hook. Since this is AJAX, there's not really an easy way to do this at another hook. Would it be possible to make sure `EDD()->customers` is set before this?

**Comment by cklosowski** [comment]
@Spreeuw do you have an example function that causes this? You mentioned `wp_ajax_nopriv_wp_{$action}`, can you provide the exact function you are using, keeping the priorities and all in tact?

**Comment by Spreeuw** [comment]
Hi! I can't provide the exact function because it's integrated into other code quite deeply, but I was able to replicate the issue on a vanilla EDD install with the following code (apologies in advance for some coder laziness, it's just to quickly replicate):
```php
add_action( 'init', 'edd_ajax_test_page' );
function edd_ajax_test_page() {
	if (!isset($_GET['edd_ajax_test'])) {
		return;
	}
	?>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script>
	jQuery( function( $ ) {
		$('button.edd_ajax_test').click( function( event ) {
			var data = {
				security:      "<?php echo wp_create_nonce('edd_ajax_test'); ?>",
				action:        "edd_ajax_test",
			};

			xhr = $.ajax({
				type:		'POST',
				url:		"<?php echo admin_url( 'admin-ajax.php' ); ?>",
				data:		data,
				success:	function( response ) {
					console.log(response);
				}
			});
		});
	});	
	</script>
	<button class="edd_ajax_test">Test</button>
	<?php
	die();
}

add_action( 'wp_ajax_nopriv_edd_ajax_test', 'edd_ajax_test' );
function edd_ajax_test() {
	check_ajax_referer( 'edd_ajax_test', 'security' );
	$customer = new EDD_Customer( 1 );
	$customer->update_meta( 'testing_customer_meta', '1...2...3...' );
	error_log('test');
	wp_send_json_success();
}
```

With this code any url on the site with `?edd_ajax_test=true` added to it _**while NOT LOGGED IN**_ will trigger this nopriv ajax.
Also note that the meta will be added successfully, it's just that the `added_customer_meta` hook is throwing an error with `EDD()->customers` not loaded.

FYI the wp_ajax_nopriv_ action is called by [WP Background Processing](https://github.com/A5hleyRich/wp-background-processing), used to defer resource intensive tasks out of the checkout process.

**Comment by pippinsplugins** [comment]
Attached PR looks good to me.
