### ISSUE TITLE
Deleted products can't be deleted from Payments

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#5959]
If you sell a product and then delete it, the Payment record shows an item without a title. You can't delete that product from the payment. After removing it and saving the product, it is still there.

This can also happen if you do a CSV import of payments which contains products that do not exist in the store. 

<img width="948" alt="screen shot 2017-08-17 at 10 29 32 am" src="https://user-images.githubusercontent.com/1638128/29420223-fef913e2-8336-11e7-8c82-69ea4025378a.png">

**Comment by cklosowski** [comment]
@mintplugins The Import should create a download if it doesn't exist, using the name of the download.

Going to look into a way to handle this process of removing a deleted item.

**Comment by mintplugins** [comment]
Looks perfect. Doesn't get better than that!

<img width="245" alt="screen shot 2017-09-06 at 4 50 35 pm" src="https://user-images.githubusercontent.com/1638128/30138057-92306402-9323-11e7-8375-53cf8dbc923f.png">
