### ISSUE TITLE
Fix console error for edd_scripts.is_checkout

### ISSUE THREAD

**Issue by nerrad** [easydigitaldownloads/easy-digital-downloads#5960]
This is in my browser console:

> TypeError: undefined is not an object (evaluating 'edd_scripts.is_checkout')

Traced the problem to this line in `edd-paypal-pro-express.php`:

```
if( edd_scripts.is_checkout == '1' && jQuery('select#edd-gateway, input.edd-gateway').length && parseFloat( jQuery('.edd_cart_total .edd_cart_amount').data('total') ) > 0 ) {
```

That is being rendered before the `edd_scripts` object is declared in the source so when `edd_scripts` is called it is undefined.

This may be caused by #4401 although I see PayPal express was checked off as being tested.

Current version of EDD installed: 2.8.4
Current version of EDD Paypal Pro & Express extension: 1.4.3

I also have the `paypal_in_context` option set to true.  So its possible whoever tested PayPal express in #4401 might not have had that set to true.

This may already be a known issue in whatever repository is used for the extension but I don't have visibility so just reporting here.

**Comment by nerrad** [comment]
Again, not sure if this is already addressed with the PayPal express add-on but the below code snippet works for me if I apply it instead of the current callback `eppe_after_purchase_form` hooked into `edd_after_purchase_form`:

```php
/**
 * Add sync attribute to paypal express script tag output. We use this filter to ensure we don't escape the spaces and
 * quotes for the new attribute (which would happen if we used script_loader_src).
 */
add_filter('clean_url','unclean_url',10,3);
function unclean_url( $good_protocol_url, $original_url, $_context){
    if (false !== strpos($original_url, 'paypalobjects.com/api/checkout.js')){
      remove_filter('clean_url','unclean_url',10,3);
      $url_parts = parse_url($good_protocol_url);
      return $url_parts['scheme'] . '://' . $url_parts['host'] . $url_parts['path'] . "' async";
    }
    return $good_protocol_url;
}

add_action('wp_enqueue_scripts', function(){
   global $edd_options;
   if ( ! empty( $edd_options['paypal_in_context'] ) && ! empty( $edd_options['gateways']['paypalexpress'] ) ) {
       $merchant_id = edd_is_test_mode() ? trim($edd_options['test_paypal_merchant_id']) : trim($edd_options['live_paypal_merchant_id']);
       $environment = edd_is_test_mode() ? "sandbox" : "production";
       wp_enqueue_script('eppe-in-context', 'https://www.paypalobjects.com/api/checkout.js', array('edd-ajax', 'jquery'));
       wp_add_inline_script(
               'eppe-in-context',
               "
               if ( !jQuery('select#edd-gateway, input.edd-gateway').length && parseFloat( jQuery('.edd_cart_total .edd_cart_amount').data('total') ) > 0 ) {
					inContextSetup( 'setup' );
				}
				if( edd_scripts.is_checkout == '1' && jQuery('select#edd-gateway, input.edd-gateway').length && parseFloat( jQuery('.edd_cart_total .edd_cart_amount').data('total') ) > 0 ) {
					if ( jQuery('select#edd-gateway, input.edd-gateway').val() == 'paypalexpress' ) {
						setTimeout( function() {
							inContextSetup( 'reset' );
						}, 1500);
					}
				}
				jQuery('select#edd-gateway, input.edd-gateway').change( function (e) {
					if( jQuery(this).val() == 'paypalexpress' ) {
						setTimeout( function() {
							inContextSetup( 'reset' );
						}, 1500);
					}
				});
				function inContextSetup( method ) {
					if ( ! jQuery('#edd-purchase-button').length ) {
						setTimeout( function() {
							inContextSetup( method );
						}, 500);
						return;
					}
					var options = {
						buttons: ['edd-purchase-button'],
						environment: '{$environment}',
						condition: function () {
							var valid = true;
							if(jQuery('#edd-email').val() == '' || jQuery('#edd-last').val() == '') {
								valid = false;
							}
							return valid;
						}
					};
					if( method == 'setup' ) {
						window.paypalCheckoutReady = function () {
							paypal.checkout.setup( '{$merchant_id}', options );
						}
					}
					else if( method == 'reset') {
						paypal.checkout.setup( '{$merchant_id}', options );
					}
				}
               "
        );
   }
});
```

 Note: I wouldn't submit this as a pull request because I realize EDD Paypal Pro & Express extension may support PHP5.2 and also it means it can't be easily unhooked.  But I think its far better to use `wp_inline_script` to setup any additional scripts as opposed to printing them inline.  That also helps with ensuring dependencies are properly handled as well.

I'd be happy to do this as a pull request in the repository for the Paypal Express extension if needed.

**Comment by cklosowski** [comment]
Thanks @nerrad I'll get this over to the developer of the PayPal Pro & Express extension to look over. Appreciate the detailed report. In future cases where you see things like this for extensions you don't see a public repo for, simply hitting us up at https://easydigitaldownloads.com/support and providing links to Gists (gist.github.com) would be fine.

**Comment by nerrad** [comment]
ya will do.  Ideally, I'd love to just contribute to a repo because email threads suck for working out code issues.

It turns out that I'm able to just implement my fix by removing the action the PayPal extension hooks into and registering my fixes using actions.  So no urgency for a fix in the extension core files in my case.

**Comment by benjaminprojas** [comment]
@nerrad I've made you a contributor on the PayPal Express repo.  If you have the time to make a PR that would be great. I'm on vacation this week, so I can't get to it until next week.  Thanks!

**Comment by nerrad** [comment]
@benjaminprojas awesome thanks :)  I may not get a chance to do so until the weekend but I definitely will get something up for you.
