### ISSUE TITLE
Illegal string offset 'User-Agent' warning in error logs

### ISSUE THREAD

**Issue by ericnicolaas** [easydigitaldownloads/easy-digital-downloads#5963]
I'm seeing a bunch of these:
```
[21-Aug-2017 00:32:09 UTC] PHP Warning:  Illegal string offset 'User-Agent' in /path/to/wp/wp-content/plugins/easy-digital-downloads/includes/misc-functions.php on line 887
```
This is with 2.8.4.

**Comment by cklosowski** [comment]
This seems like something is wrong with the server configuration as no user
agent is being sent to nginx.

**Comment by cklosowski** [comment]
As a note, the code here is using a `foreach` over supplied headers...so it had to find `User-Agent` somewhere in the array of headers:
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/misc-functions.php#L883

And note that the line may change between versions, much like the repot showing on line 887, but the current master has it at 883.

**Comment by ericnicolaas** [comment]
#5993 should fix this issue. The problem is that `$headers` is defined as a string, so `$headers['anystring']`  triggers that warning.

**Comment by ericnicolaas** [comment]
OK, just finished testing this and yes, this issue is resolved by #5993.

**Comment by sunnyratilal** [comment]
PR reviewed and changes look good to me.

Good to merge, @cklosowski?

**Comment by pippinsplugins** [comment]
Merged.
