### ISSUE TITLE
Add support for Angola in country list

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#5970]
This would include the following ([based off this PR](https://github.com/easydigitaldownloads/easy-digital-downloads/pull/5866/files))

Reference for Country code and currency code: https://en.wikipedia.org/wiki/Angola
Reference for Province Codes: https://en.wikipedia.org/wiki/Provinces_of_Angola (must visit each one individually)
- [ ] Add Angola to the country list (ISO 3166 code `AO`)
- [ ] Add the provinces to the list (18 in total)
- [ ] Add support for the `Kwanza` Currency with an ISO 4217 code of `AOA`

I'm going to make an issue branch from the existing PR, and close that PR so I can resolve some minor issues with it.

**Comment by pippinsplugins** [comment]
PR looks good, merged.
