### ISSUE TITLE
Database error  Not unique table/alias: 'wp_termmeta'

### ISSUE THREAD

**Issue by zeromajstor** [easydigitaldownloads/easy-digital-downloads#5972]
Hi, 

today I noticed I have some problem with my categories, tags and extra taxonomy from EDD.

I turned wp_debug in config file and this is what I see:

WordPress database error: [Not unique table/alias: 'wp_termmeta']
`SELECT DISTINCT t.*, tt.* FROM wp_terms AS t INNER JOIN wp_termmeta ON ( t.term_id = wp_termmeta.term_id ) INNER JOIN wp_term_taxonomy AS tt ON t.term_id = tt.term_id INNER JOIN wp_termmeta ON ( tt.term_id = wp_termmeta.term_id ) WHERE tt.taxonomy IN ('category', 'post_tag', 'post_format', 'download_tempo', 'download_artist', 'wp_log_type', 'download_category', 'download_tag', 'feature-category', 'testimonial-category') AND ( wp_termmeta.meta_key = 'rcp_restricted_meta' ) AND ( wp_termmeta.meta_key = 'rcp_restricted_meta' ) ORDER BY t.name ASC `

anyone know how to fix this?

Thanks

**Comment by cklosowski** [comment]
@zeromajstor this doesn't appear to be an EDD specific issue, or related to our codebase at all. This appears to be an issue with your WordPress core database table. I cannot replicate it with a stock EDD installation. If you have further questions please direct them to:
https://easydigitaldownloads.com/support

github is for development and feature tracking only, not support requests.
