### ISSUE TITLE
edd_store_discount should fail/bail if no code is provided.

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#5974]
Reported by @ramiabraham

**Comment by cklosowski** [comment]
To test this, you'll have to do it programmatically, since our form uses HTML5 validation to require the code.

Fail:
`var_dump( edd_store_discount( array( 'name' => 'test name' ) ) );`

Pass: `var_dump( edd_store_discount( array( 'name' => 'test name', 'code' => 'TESTING' ) ) );`

**Comment by SDavisMedia** [comment]
Verified that creating the discount without an actual discount code works on `master`. Confirmed that it fails on `issue/5974`. :+1:
