### ISSUE TITLE
Expose 'preview' metadata on API

### ISSUE THREAD

**Issue by alvinwoon** [easydigitaldownloads/easy-digital-downloads#5976]
Hi, is there any plan to expose preview data via api?

**Comment by cklosowski** [comment]
@alvinwoon What "preview" data are you expecting to see in the API. Could you be more specific?

**Comment by alvinwoon** [comment]
@cklosowski  Perhaps this is theme specific and non-EDD related but basically exposing these fields on API.

http://i.imgur.com/hMyko7h.png

**Comment by cklosowski** [comment]
@alvinwoon Yes, that is theme data, and they could expose this in the API by using the `edd_api_products_product` filter, to include their own data in the output.
