### ISSUE TITLE
Edd empty_cart function does not unset edd_is_renewal session setting.

### ISSUE THREAD

**Issue by abushoaib** [easydigitaldownloads/easy-digital-downloads#5980]
If user try to renew license with renewal discount and ignore the cart . If user again add to cart same product with different price . If we here call  EDD()->cart->empty_cart(); function here edd does not remove  edd_is_renewal settings from session as a result double discount is applying. One for renewal discount another for product update. 

Solution we applied 

add_action("edd_empty_cart","edd_clear_cart");
function edd_clear_cart(){
if (EDD()->session->get('edd_is_renewal')) {
                EDD()->session->set('edd_is_renewal', null);
                EDD()->session->set('edd_renewal_keys', null);
`}`
}

**Comment by cklosowski** [comment]
Thanks @abushoaib, this belongs in the Software Licensing codebase, so I'll close this issue here, and move it into our development queue for Software Licensing. Appreciate the feedback and suggested fix.

**Comment by cklosowski** [comment]
@abushoaib So we're trying to replicate this, and I've seen it happen before but we're not able to replicate it at all now.

Can you please contact me at support@easydigitaldownloads.com with a site and License key I can try with?
