### ISSUE TITLE
admin-scripts.js missing full stop in class selector

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#5988]
On line 304 of `admin-scripts.js`, you have this line:

`clone.find( 'edd_repeatable_thumbnail_size_field' ).val( selectedSize );`

Should be:

`clone.find( '.edd_repeatable_thumbnail_size_field' ).val( selectedSize );`

**Comment by SDavisMedia** [comment]
@davidsherlock good eye. Would you like to submit a PR?

**Comment by davidsherlock** [comment]
Done @SDavisMedia! #5990

**Comment by SDavisMedia** [comment]
Thanks!

**Comment by SDavisMedia** [comment]
@cklosowski I think I remember incorrectly when I added this to the 2.9 milestone... I was meaning to skip a major milestone, as you requested previously. But this may be simple enough to keep on 2.9 if you're good with it.

**Comment by sunnyratilal** [comment]
This already went out in 2.8.7
