### ISSUE TITLE
Product dropdown losing selections

### ISSUE THREAD

**Issue by stephywells** [easydigitaldownloads/easy-digital-downloads#5991]
v 2.8.4

To replicate:
1. Create a product with variations. Rearrange the variations. I ended up with pricing variations like this:
```php
Array
(
    [1] => Array
        (
            [index] => 0
            [name] => 1 site
            [amount] => 20.00
            [license_limit] => 1
            [recurring] => no
        )

    [2] => Array
        (
            [index] => 1
            [name] => 3 sites
            [amount] => 25.00
            [license_limit] => 3
            [recurring] => no
        )

    [4] => Array
        (
            [index] => 2
            [name] => 5 sites
            [amount] => 27.00
            [license_limit] => 0
            [recurring] => no
        )

    [3] => Array
        (
            [index] => 3
            [name] => 50 sites
            [amount] => 30.00
            [license_limit] => 50
            [recurring] => no
        )

    [5] => Array
        (
            [index] => 
            [name] => 100 sites
            [amount] => 35.00
            [license_limit] => 0
            [recurring] => no
        )
)
```

The index is missing on the 5th variation, but the index would be 5, the same as the array key.

2. Create a bundle. Make sure the variation does not show on load. It needs to hit line 146
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/class-edd-html-elements.php#L146-148

```php
$index  = isset( $value['index'] )  ? $value['index']  : $key;
if ( $name && $index && (int) $parsed_item['price_id'] === (int) $index  ) {
```

3. The value will not be added to the options because 5 !== 0.

The same block of code is used three times here. Maybe this can be pulled into its own function?
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/class-edd-html-elements.php#L141-L152

The first iteration of this function checks if the index is empty.
`$index  = ! empty( $value['index'] )  ? $value['index']  : $key;`

**Comment by stephywells** [comment]
Oh, one more thing that may be causing issues I'm seeing. In this example the output for the value won't be correct:

$options[ absint( $product->ID ) . '_' . $index ]

Would create <option value="25_0"> when it should be <option value="25_5">

**Comment by stephywells** [comment]
Possible fix that hasn't been tested much.

Change each iteration of this:
$name   = isset( $value['name'] )   ? $value['name']   : '';
$index  = isset( $value['index'] )  ? $value['index']  : $key;

or this:
$name   = ! empty( $value['name'] )   ? $value['name']   : '';
$index  = ! empty( $value['index'] )  ? $value['index']  : $key;

to this:
$name   = ( isset( $value['name'] ) && ! empty( $value['name'] ) )   ? $value['name']   : '';
$index  = ( isset( $value['index'] ) && ! empty( $value['index'] ) )  ? $value['index']  : $key;

**Comment by stephywells** [comment]
I'm seeing more issues with this. I have 6 price ids on a product, in this order:
1, 2, 5, 6, 3, 4

The options in the dropdown are by key:
0, 1, 2, 3, 4, 5

I have a bundle with the last option selected. It is selected by key, but is attaching the product by price id. So the wrong price ids are being attached to the bundles.

It looks like this needs to always use the price id in order to be consistent. The key can change, so reordering the price levels would also mess up any bundles.

Can this dropdown always save the price id?

**Comment by cklosowski** [comment]
Going to try and tackle this this week. I've got some of it fixed up in a other issue (the _/absint thing).

**Comment by cklosowski** [comment]
@stephywells can you do me a favor...and shoot me a product export? I think that might give me exactly what i'm looking for configured the way you have it without me mucking with the details and screwing it up.

Trying to get this perfect and I think I'm missing something in the process just slightly.

**Comment by cklosowski** [comment]
With the CSV I can just import your configuration directly to my development environment. chris@easydigitaldownloads.com is fine, as is including it here.

**Comment by cklosowski** [comment]
@stephywells is this what you mean?
<img width="564" alt="screen shot 2017-09-28 at 11 30 54 am" src="https://user-images.githubusercontent.com/1390124/30975550-8c91d9f8-a440-11e7-9990-1af4dd7a65c2.png">

Mine is showing all but the first option.

**Comment by stephywells** [comment]
Yes, that's part of it. My change above makes all the options selectable.

There is also an issue when the order doesn't match the price id.
1. Add 4 price IDs to the non-bundled product
2. Move them around to be ordered like this:
Price 1 (index 0)
Price 4 (index 1)
Price 3 (index 2)
Price 2 (index 3)

3. Now go to the bundle. Add 4 price IDs, and assign each one a different Price ID from the first product.

4. Save and refresh the bundle page. Some selections will be lost (without my changes above).
5. Purchase the bundle.
6. Now you'll see that the wrong price IDs are attached to the bundled purchase. The bundle gets the Price IDs by the ID, but it saves the index. So If I selected Price 3 (that has an index of 2 saved), Price 2 is attached to the bundle purchase.

Is that more clear? Sorry for my long explanations.

**Comment by cklosowski** [comment]
Perfect thanks @stephywells I've been able to replicate both of them now. 
Appreciate the long explanations, so much better than vague ones :)

**Comment by cklosowski** [comment]
@easydigitaldownloads/core-devs I think we have a backcompat breakage that has to happen here...i cannot find a way around it.

the problem is that The product dropdown with variable prices is using the 'index' not the 'price_id' for it's identifier...but the index can change since that is what is updated when someone drags to re-organize their variable prices.

We need to be using price ID, however, changing to do that will break people currently using it...how do we want to proceed with this?

The fix from @stephywells above does allow the items to show initially, so i'll commit that up, so you can see what I mean.

See (this comment)[https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5991#issuecomment-332906722] for replication steps.

**Comment by cklosowski** [comment]
Ok @stephywells and @easydigitaldownloads/core-devs this is ready for some testing.

**Comment by sunnyratilal** [comment]
Tested and confirmed the patch assigns the correct price IDs to the bundle.

**Comment by sunnyratilal** [comment]
⚠️  We need to ensure we mention in the changelog that this breaks backwards compatibility.

**Comment by stephywells** [comment]
Looks great! Thanks for switching that.

Technically, it doesn't change reverse compatibility since it now selects the price ID in the dropdown that was being attached to the purchase before. But the settings do need to be checked and updated to make sure the correct price IDs are selected.

**Comment by cklosowski** [comment]
@stephywells correct, it's not a complete backwards incompatibility, but does require that store owners do a quick check. We're planning on sending out a couple tweets about it.
