### ISSUE TITLE
Enhance Earnings by Category to be earnings by Taxonomy

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#6006]
Right now our Earnings by Category are only categories, but in a store with tags and other custom taxonomies, a store owner could expand on the reporting pretty easily but just supporting all `download` taxonomies.

**Comment by sunnyratilal** [comment]
Implemented in:

- https://github.com/easydigitaldownloads/easy-digital-downloads/commit/d95586f8d758c08b56e4130312355042c01184c6
- https://github.com/easydigitaldownloads/easy-digital-downloads/commit/47f5635e302f882b26ae7c109a834b617e82f709
- https://github.com/easydigitaldownloads/easy-digital-downloads/commit/425750fc15fe106ca30d82b48782c9caafb9a2ae
- https://github.com/easydigitaldownloads/easy-digital-downloads/commit/80d55bd3679c444fbc4b2fc166334bf330ce49d2
- https://github.com/easydigitaldownloads/easy-digital-downloads/commit/59b425add84565d12fdafb37a8f298bb4bb7a09c

See #6298.
