### ISSUE TITLE
Plugin could not be activated

### ISSUE THREAD

**Issue by corvannoorloos** [easydigitaldownloads/easy-digital-downloads#6019]
Sorry for the general title, but I'm currently experiencing some dificulties installing this plugin using the master branch.

`Plugin could not be activated because it triggered a fatal error.`

`Fatal error: Uncaught ArgumentCountError: Too few arguments to function edd_add_rewrite_endpoints(), 0 passed in C:\apache\htdocs\wordpress\wordpress\wp-includes\class-wp-hook.php on line 286 and exactly 1 expected in C:\apache\htdocs\wordpress\wp-content\plugins\easy-digital-downloads\includes\cart\actions.php:23 Stack trace: #0 C:\apache\htdocs\wordpress\wordpress\wp-includes\class-wp-hook.php(286): edd_add_rewrite_endpoints() #1 C:\apache\htdocs\wordpress\wordpress\wp-includes\class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #2 C:\apache\htdocs\wordpress\wordpress\wp-includes\plugin.php(515): WP_Hook->do_action(Array) #3 C:\apache\htdocs\wordpress\wordpress\wp-admin\includes\plugin.php(1916): do_action_ref_array('init', Array) #4 C:\apache\htdocs\wordpress\wordpress\wp-admin\plugins.php(172): plugin_sandbox_scrape('easy-digital-do...') #5 {main} thrown in C:\apache\htdocs\wordpress\wp-content\plugins\easy-digital-downloads\includes\cart\actions.php on line 23`

Note, I have WordPress installed within a subdirectory called `wordpress`.

**Comment by cklosowski** [comment]
@corvannoorloos Can we get a little more information bout your environment? PHP Versions, other plugins installed? I'm not able to replicate this locally at all, with a subdirectory.

**Comment by corvannoorloos** [comment]
@cklosowski I'm using PHP 7.1.9 + Apache 2.4.27 on Windows 10 Pro with no other themes or plugins installed.
Reading the notification I initially thought this might have been caused by this plugin, but it appears to be caused by a change somewhere in between WordPress 4.8.2 and WordPress master.
I'll get back on this asap.

**Comment by corvannoorloos** [comment]
@cklosowski the error is caused by this commit https://github.com/WordPress/WordPress/commit/aff467e1cb73874e40649c5c410e80a3b5c4800a.
I have to admit though I'm not really sure if this means it's caused by this plugin or WordPress or how to continue further.

**Comment by chriscct7** [comment]
There are other reports of issues with this: https://core.trac.wordpress.org/ticket/39766#comment:14

**Comment by chriscct7** [comment]
Appears to be a WP core issue with that patch

**Comment by chriscct7** [comment]
Also see https://core.trac.wordpress.org/ticket/21622

**Comment by corvannoorloos** [comment]
@chriscct7 I had to look more into this. Thanks!

**Comment by cklosowski** [comment]
Ok marking as something to follow on .org for now.

**Comment by chriscct7** [comment]
The WP core ticket for this has been resolved: https://core.trac.wordpress.org/ticket/21622
