### ISSUE TITLE
Signing URLs for improved security

### ISSUE THREAD

**Issue by bradyvercher** [easydigitaldownloads/Easy-Digital-Downloads#603]
Pippin asked me to go ahead and open an issue here for discussion on a new implementation for improving the security of URLs that I built out as an add-on at the moment. Considering the implications of something like this, it'd be ideal to roll it into the core plugin, but may require breaking some currently valid URLs.

The basic premise is that URLs can be signed using a unique string, in this case `wp_salt()`, and when requested, the token can be checked to ensure none of the variables in the query string have been tampered with. This allows for passing non-sensitive data through the URL in the clear and being certain that it hasn't been changed. It essentially allows for more secure and concise URLs.

### Code

My implementation is available here for anyone wanting to try it out and offer feedback on how it could be improved or integrated: https://github.com/bradyvercher/EDD-Signed-URLs

The first three functions simply hook into EDD to modify and check the URLs, while the last three functions provide the API for signing URLs.

The concept will work with any URL structure, so my method of condensing everything into a colon delimited `eddfile` query arg isn't required (and that arg could even be renamed with a simple filter if desired).

### Breakage

As far as potentially breaking changes, existing URLs that haven't expired would quit working with this solution. It might be possible to run things side by side for a short while, but the current method would need to be deprecated at some point.

This would also decrease the reliance on using the `download_key` to look up a payment, instead using actual payment IDs, which might make things a little easier to work with. In that case, the current API utilizing the `download_key` might need to be augmented, or a new solution could be run side by side. I'm not sure if anyone is using the existing functions directly or not.

### Improvements

In any case, we're opening this up to see if anyone has ideas on implementing a solution like this without breaking anything. Feedback about improvements, suggestions on the default URL structure (is it worth trying to simplify?), and increasing security is welcome.

Feel free to correct me if I got anything wrong, Pippin.

**Comment by pippinsplugins** [comment]
Hmm, that's a good point. Without the separate URL parameters, it's more difficult to determine the expiration dates.

What if we were to add an expiration date parameter that is checked only if the token is verified? The expiration date could be included as its own parameter and also part of the token creation, that way it can't be changed.

**Comment by cklosowski** [comment]
We have a ```ttl``` parameter, maybe we could use that. Will look into making that happen.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by cklosowski** [comment]
Need to figure out how to get the payment ID into the file download logs:
![image](https://cloud.githubusercontent.com/assets/1390124/5665859/6ea2c8f2-9729-11e4-9174-881b610b4a18.png)

**Comment by pippinsplugins** [comment]
How about we add the payment ID just like we do the expiration date?

**Comment by cklosowski** [comment]
yeah, could be possible. I'll look into this gain after I'm done with a couple other tasks.

**Comment by cklosowski** [comment]
Ok, above Payment ID issue should be resolved.

**Comment by pippinsplugins** [comment]
Extensions to test with this:
- [ ] Software Licensing
- [ ] Recurring Payments
- [ ] Free Download Link
- [ ] PDF Stamper
- [ ] Amazon S3
- [ ] Dropbox File Store
- [ ] Limit File Download IP
- [ ] Product Updates
- [ ] Download Attachments
- [ ] PDF Vouchers

**Comment by cklosowski** [comment]
After some discussion in our meeting last night, I'm not sure I 100% agree with using wp_hash...it's hard coded to only use md5, not allowing anything stronger, like sha256, which we have working:
```
return hash_hmac('md5', $data, $salt);
```

@pippinsplugins @chriscct7 Care to chime in?

**Comment by pippinsplugins** [comment]
If I recall, there's a timing attack vulnerability in hash_hmac() that wp_hash() doesn't have. Am I remembering wrong?

**Comment by cklosowski** [comment]
wp_hash uses hash_hmac...

**Comment by pippinsplugins** [comment]
No idea what I'm remembering then . . .

**Comment by pippinsplugins** [comment]
@sdavis2702 @sumobi @ghost1227 @mindctrl @chriscct7 To prevent more support tickets than we want to even imagine, this needs to be perfect. Can we get some solid testing on this? Extensions we need to test with are listed [above](https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/603#issuecomment-70010909)

**Comment by sdavis2702** [comment]
@pippinsplugins @cklosowski Mind giving a quick brief on how to test? I'm guessing anywhere a download link is used, make sure it works?

**Comment by pippinsplugins** [comment]
Yep!

For core functionality:

1. Checkout `master`
2. Make a purchase and get the download URLs
3. Checkout `issue/603`
4. Make sure the file URLs in 2 still work
5. Make a new purchase (or generate new URLs on old purchase) and ensure they still work

For extensions:

1. Checkout `issue/603`
2. Test feature of extension and ensure it still works.

**Comment by pippinsplugins** [comment]
I've created a pull request for easy testing.

**Comment by pippinsplugins** [comment]
@ghost1227 Tokenized URLs break with PDF Stamper active. This error is shown (only when PDF Stamper is active):
![screen shot 2015-02-15 at 6 42 57 pm](https://cloud.githubusercontent.com/assets/1034109/6205876/877e7592-b542-11e4-9644-6f4f60174f5c.png)

**Comment by pippinsplugins** [comment]
PDF Stamper fails because it's using `$_GET['download_id']`, which is no longer available in the URL:
```php
add_filter( 'edd_requested_file', array( $this, 'stamp_file' ), 10, 3 );
......
 /**
         * Override edd_requested_file
         *
         * @access      public
         * @since       1.0.0
         * @param       string $file The URL of the file to be processed
         * @param       array $download_files Array of download files
         * @param       string $file_key The key of this download
         * @return      string The URL of the stamped file, or the original URL if the file is not a PDF
         */
        public function stamp_file( $file, $download_files, $file_key ) {
            $post_id = absint( $_GET['download_id'] );
.....
````

We will have to fix that. Too many other plugins have the potential of breaking without that.

**Comment by pippinsplugins** [comment]
@ghost1227 PDF Stamper will need to be updated to not call `edd_verify_download_link()` anymore.

**Comment by pippinsplugins** [comment]
The biggest issue I'm running into so far is plugins that called `edd_verify_download_link()` themselves during `process-download.php`. Those plugins (such as PDF Stamper) are failing due to some issues with populating the `$_GET` super globals.

**Comment by pippinsplugins** [comment]
A change needs to be made to PDF Stamper @ghost1227: https://trello.com/c/dsmMHdfl/291-pdf-stamper

**Comment by pippinsplugins** [comment]
`PDF Vouchers` breaks. When you try to download a voucher, it errors: https://cloudup.com/cSrVWkRS6gs

**Comment by pippinsplugins** [comment]
PDF Vouchers breaks because our new signed URLs are not adding the custom variables that PDF Vouchers appends to download URLs.

New URL:

http://edd/index.php?eddfile=2231%3A514%3A0&ttl=1424167604&token=4d0a86fb8f8be40cf9927222076a5ced

Old URL:

http://edd/index.php?download_key=7211cce2df06b572890934752a4c0896&email=pippin%40pippinsplugins.com&file=edd_vou_pdf&price_id=1&download_id=514&expire=MTQyNDE2NzcyOQ%3D%3D&edd_voucher=1

**Comment by pippinsplugins** [comment]
PDF Vouchers adds the extra args with the `edd_download_file_url_args` filter:
```php
add_filter( 'edd_download_file_url_args', array( $this, 'edd_vou_order_download_file_url_args' ) );
...
	/**
	 * Display Download Voucher Link
	 * 
	 * Handles to display download voucher link for user
	 * 
	 * @package Easy Digital Downloads - Voucher Extension
	 * @since 1.0.0
	 */
	public function edd_vou_order_download_file_url_args( $params ) {
		
		global $edd_receipt_args, $edd_payment_id;
		
		$payment	= get_post( $edd_receipt_args['id'] );
		$order_id	= isset( $payment->ID ) ? $payment->ID : '';		
		
		if( empty( $order_id ) ) {
			
			$order_id = $edd_payment_id;
		}
		$downloadid 	= isset( $params['download_id'] ) ? $params['download_id'] : '';
		
		// If product is variable then take variavle option id
		$price_id = !empty($params['price_id']) ? $params['price_id'] : '';
		
		// If product is variable then making product key
		if( !empty($price_id) ) {
			$product_data_id = $downloadid . '_' . $price_id;
		} else {
			$product_data_id = $downloadid;
		}
		
		if( $this->model->edd_vou_check_enable_voucher( $downloadid ) ) { //check enable voucher
			
			$vou_codes_key	= array();
			$vou_codes_key	= $this->model->edd_vou_get_multi_voucher_key( $order_id, $params['download_id'], $price_id );
			
			if( !is_admin() && isset( $params['download_key'] ) && isset( $params['file'] ) && !empty( $params['file'] )
				&& ( $params['file'] == 'edd_vou_pdf' || in_array( $params['file'], $vou_codes_key ) ) ) { // Check front side & edd voucher pdf
				
				$voucher_key = $product_data_id;
				$meta_query = array(
									array( 
												'key' 	=> '_edd_payment_purchase_key',
												'value' => $params['download_key']
											)
								);
				$payment_data  	= edd_get_payments( array( 'meta_query' => $meta_query ) );
				$payment  		= isset( $payment_data['0'] ) ? $payment_data['0'] : array();
				
				//get voucher order details
				$ordervoudata = $this->model->edd_vou_get_post_meta_ordered( $payment->ID );
				$downloadvoudata = isset( $ordervoudata[$voucher_key] ) ? $ordervoudata[$voucher_key] : array();
				
				if( !empty( $downloadvoudata ) ) { // Check voucher download data
					
					$params['edd_voucher'] = '1';
				}
			}
		} // end enaable check
		
		return $params;
	}
```

**Comment by pippinsplugins** [comment]
We've broken how the `edd_download_file_url_args` filter works. It used to filter the final URL that is returned, now it just filters the parameters sent to `edd_get_download_token()`.

**Comment by pippinsplugins** [comment]
We need to make sure that any custom arguments registered through `edd_download_file_url_args` still get appended to URLs, while also making sure we don't append all of our default arguments, since that would largely defeat the entire purpose of signed URLs.

I've just about got this working by looking at the difference between the starting parameters and the final parameters (after it goes through the filter) and then just appending any custom ones:
```php
// Ensure all custom args registered with extensions through edd_download_file_url_args get added to the URL, but without adding all the old args
$args = array_merge( $args, array_diff_key( $params, $old_args ) );
```

**Comment by pippinsplugins** [comment]
`EDD Partial Downloader` is going to fail completely due to how they're overwriting our download process: https://github.com/EhsaanF/edd-partial-downloader/blob/master/edd-partial-downloader.php#L38

I'll get in touch with them and ask them to update it.

**Comment by pippinsplugins** [comment]
Extensions that have to be updated to be compatible (ones that are checked off have been updated):
- [ ] PDF Stamper
- [ ] PDF Vouchers
- [ ] Partial downloads

**Comment by pippinsplugins** [comment]
Aside from the three extensions above, every extension on the [known-to-be-affected list](https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/603#issuecomment-70010909) works properly.

**Comment by pippinsplugins** [comment]
Good news: this has been live on pippinsplugins.com for 3 days and not a single ticket about customers being unable to download files.

**Comment by pippinsplugins** [comment]
This is also live on affiliatewp.com and has not presented any issues yet.

**Comment by pippinsplugins** [comment]
I'm putting in on the EDD site now.

**Comment by pippinsplugins** [comment]
So issues so far! Closing for now.
