### ISSUE TITLE
Newly register user's ID is not set on pre-existing payments

### ISSUE THREAD

**Issue by ericnicolaas** [easydigitaldownloads/easy-digital-downloads#6031]
`edd_add_past_purchases_to_new_user()` doesn't do what it's supposed to; any past guest purchases are left with their user ID set to 0.

PR forthcoming.

**Comment by pippinsplugins** [comment]
PR https://github.com/easydigitaldownloads/easy-digital-downloads/pull/6032

**Comment by sunnyratilal** [comment]
Tested and working fine, just waiting on unit tests before merge
