### ISSUE TITLE
View order details > Add new download responsive issues

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#6035]
The input fields for downloads and adding a new download to an existing payment get a little cramped when on mobile. We've recently updated this area, but I think it'll take a little more work on the markup to make it easily flexible for both desktop and mobile.

**Comment by sunnyratilal** [comment]
@cklosowski Are you referring to this:
![image](https://user-images.githubusercontent.com/1525554/34320483-2b75b17a-e7f3-11e7-8e2a-c75a4b525418.png)

There doesn't seem to be an issue with the size of the inputs on mobile.

**Comment by pippinsplugins** [comment]
Just tested and it works well for me. Closing as invalid now.

**Comment by cklosowski** [comment]
Was probably fixed during an overhaul of the EDD Responsiveness in #6036
