### ISSUE TITLE
3.0 - Country-wide tax rates are confusing.

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#6037]
Which tax rate gets used in this scenario?
<img width="1252" alt="screen shot 2017-09-27 at 3 38 13 pm" src="https://user-images.githubusercontent.com/1638128/30941405-1800b5c4-a39a-11e7-9082-11198361e7d5.png">

Can we make the UI better for this in any way?

**Comment by mintplugins** [comment]
It will use the last entered rate (in this case 12%). But that isn't clear at first glance. Perhaps this could be improved upon.

**Comment by cklosowski** [comment]
This is similar to an issue I already opened about the tax settings
responisveness. Maybe close mine as a dip and include responsiveness In
this one?

**Comment by mintplugins** [comment]
@spencerfinnell What are your thoughts on doing something about this alongside https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7109

The same confusion still exists with the current tax system in EDD3. Both of these tax rates are set to "Apply to whole country"
<img width="1015" alt="Screen Shot 2019-04-17 at 5 04 58 PM" src="https://user-images.githubusercontent.com/1638128/56320874-2300eb80-6133-11e9-95da-66501d2e3226.png">

**Comment by spencerfinnell** [comment]
It should be pretty easy to determine if a country-wide rate exists now and stop the addition of another, and alert the user of its existence and to deactivate and add again if needed.

**Comment by mintplugins** [comment]
That sounds like a good flow to me

**Comment by cklosowski** [comment]
I would agree here, however I think we might run into some issues during the migration? What happens if we have two tax rates that are defined both to apply to the whole country...wouldn't we want to 'deactivate' one of them upon migration? If we detect that the country wide tax rate being inserted upon migration will override a previous one, we should deactivate the previous one when we insert this new one (assuming the iteration works in the same order)

I would agree we need some sort of UI to prevent the confusion state.

**Comment by spencerfinnell** [comment]
@cklosowski Yes, any country-wide rate that's added during migration should be able to safely deactivate any existing country-wide rate as long as the iteration order is correct. Then the 3.0 UI will reflect what has been used in their Checkout accurately, and a new check during rate addition can be added to prevent further duplicates/ensure the UI remains accurate.

**Comment by spencerfinnell** [comment]
PR #7575 prevents multiple country wide rates from being added via the UI:

<img width="477" alt="Screen Shot 2020-02-10 at 2 09 25 PM" src="https://user-images.githubusercontent.com/491124/74181283-fdd3f100-4c0e-11ea-8494-230edfb7e8e2.png">

**Comment by cklosowski** [comment]
@spencerfinnell I’ve created #7602 to handle the migration aspect of this.
