### ISSUE TITLE
Wrap discount fields in <span>

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/easy-digital-downloads#6041]
It would be cool to get an extra `<span>` that wrapped the discount input fields at checkout. This would allow themes to use CSS flexbox and have the input and "apply" button perfectly aligned, taking up all the space they need.

<img width="817" alt="screenshot 2017-09-28 20 42 19" src="https://user-images.githubusercontent.com/52581/30954764-dd4c6fc8-a48d-11e7-8468-d0c98991cf82.png">

We could even do this ourselves (add the required CSS) to improve the default checkout experience but it's a great first step.

**Comment by amdrew** [comment]
PR: https://github.com/easydigitaldownloads/easy-digital-downloads/pull/6042

**Comment by pippinsplugins** [comment]
I like it, merged!
