### ISSUE TITLE
Provide a hook to conditionally disable edd_record_download_in_log()

### ISSUE THREAD

**Issue by eugenesp** [easydigitaldownloads/easy-digital-downloads#6048]
I am using EDD's All Access Pass extension which allows limiting the max number of downloads per Pass. I keep getting complaints from the customers who accidentally ran out of the download limit by clicking the button more than once. A temporary hack that I use is replacing the button with a direct link once the is file downloaded (via JavaScript and on the template level), but this solution does not feel reliable. In addition, I don't want to have multiple records for the same file in the log as I use the EDD_API.get_download_logs() to provide customers with a list of previously downloaded files that they can redownload with any limitations. 

For these reasons, it would be great to have a hook that can be used to conditionally disable edd_record_download_in_log(), so file download can be performed end-to-end without adding a new record to the log.

**Comment by cklosowski** [comment]
This seems like an edge case. Your stating that you want to stop using the feature that All Access provides to prevent download limits...

@mintplugins does this make sense? Is there a use case for somehow preventing someone from running up their download limit that makes sense to bypass it?

**Comment by eugenesp** [comment]
I want to allow users unlimited re-downloads, so only the first download gets counted towards the download limit. This would allow providing a user-friendly experience similar to other popular website offering limited digital downloads like Shutterstock (stock photos) where you a have limit for the total number of downloads per month and an unlimited number of redownloads from your account history.

**Comment by pippinsplugins** [comment]
Unlimited re-downloads makes sense to me, though that needs to be an enhancement made to All Access itself. In that situation I would not expect All Access to record duplicate log entries.

If @mintplugins is fine with that, let's close this as wontfix and then log an enhancement for All Access.

**Comment by eugenesp** [comment]
IMO a filter for edd_record_download_in_log() would provide more flexibility.

**Comment by mintplugins** [comment]
This is a planned enhancement to All Access:
https://github.com/easydigitaldownloads/edd-all-access/issues/133

However, I do think any and all file downloads need to be logged purely for true statistical purposes.

There is also a planned enhancement to  add a shortcode to show products perviously downloaded using All Access. Those would not show duplicates as they would be filtered out. 

That is here:
https://github.com/easydigitaldownloads/edd-all-access/issues/134

We can close this issue as I think preventing file download logs would result in poor statistical tracking.
