### ISSUE TITLE
Auto formatted card numbers reported as invalid by Firefox

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#6055]
In #5369 we introduced automatic formatting for card numbers. This appears to not be working, however, in Firefox. The formatting is applied to show the numbers with spaces but then Firefox reports the number as invalid. See:

<img width="865" alt="screen shot 2017-10-02 at 4 11 12 pm" src="https://user-images.githubusercontent.com/1034109/31099675-69d53212-a78c-11e7-95ca-d090335977b4.png">

Related https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5933 and https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5845

**Comment by pippinsplugins** [comment]
New report https://secure.helpscout.net/conversation/442696467/67817/?folderId=180499

**Comment by cklosowski** [comment]
Not replicating this issue in Firefox with PayPal Pro (which uses our EDD core credit card form).

I've tried on Firefox 55.0.3 (reported in the issue above) as well as the latest which is version 56, but not seeing the red border on valid cards, even the one posted in the screenshot above.

**Comment by cklosowski** [comment]
As a note, i'm also not able to replicate it with Stripe (which has their own form).

**Comment by cklosowski** [comment]
This issue doesn't belong in EDD core it belongs in Stripe. Stripe did not get the proper pattern update, that EDD core got:

```
^[0-9!@#$%^&* ]*$
```
