### ISSUE TITLE
Debugger Console Issue

### ISSUE THREAD

**Issue by Basilakis** [easydigitaldownloads/easy-digital-downloads#6056]
Hey,

At the debugger I saw today the following Issue

`TypeError: e(...).ajaxForm is not a function ->   admin-scripts.min.js:1:28085`

You might need to know.

Cheers!

**Comment by cklosowski** [comment]
@Basilakis This is a difficult one to track down with minified lines.

Is it possible for you to try this with `define( 'SCRIPT_DEBUG', true );` in your `wp-config.php`? I'm not seeing this come up and also what were you doing when you had this occur?

**Comment by Basilakis** [comment]
@cklosowski Sorry you are 100% right. When your day is not good, you do such reports that help noone.

I have been on Edit Page, Latest all versions EDD and a theme of mine - just a fork of _s with no extra JS or something

**Comment by Basilakis** [comment]
define( 'SCRIPT_DEBUG', true );

That does remove the error.
Notice:

Without that, everything works as I tested but when I enable Elementor or Visual Composer ( builders or anything that is related to tinymce also ( example: Prevent HTML markup to be removed ) those plugins return JS error as Uncaught ReferenceError: jQuery is not defined . 

**If I disable EDD it works just fine.**

**Comment by cklosowski** [comment]
I'm closing this as of now, we haven't had any other reports of this and it's quite old. If we have it happen again we can reopen.
