### ISSUE TITLE
Payment gateway dropdown doesn't include manual payments option

### ISSUE THREAD

**Issue by scottbuscemi** [easydigitaldownloads/easy-digital-downloads#6063]
On the Payment History page, the "payment gateway" dropdown doesn't include manual payments.

![screen shot 2017-10-04 at 10 56 31 am](https://user-images.githubusercontent.com/4336848/31191377-c2492cfc-a8f2-11e7-8f5a-9ca4403b973b.png)

**Comment by cklosowski** [comment]
This is mostly due to 'Manual' isn't a registered gateway, it's a fallback gateway. We can get that added though.

**Comment by scottbuscemi** [comment]
This seems to be getting pushed, so I ended up adding this to line 148 of /includes/admin/payments/class-payments-table.php in the meantime:

`$gateways['manual'] = "Manual Purchases";`

**Comment by cklosowski** [comment]
So this is different than just adding the gateway.

If you use Free Downloads or import payments without a gateway (which is what I believe happened with @scottbuscemi), those use `manual` as the gateway. If you use our Manual Purchases extension that uses a gateway slug of `manual_purchases`.

So what we really need to do is have a way to look at imported ones in core (which will allow ones from Free Downloads as well), but the Manual Purchases extension should add it's own 'gateway' to that list for filtering.

**Comment by sunnyratilal** [comment]
PR: #6141 

Two filters have been added as part of this issue. The first way is wrapped around the list of gateways that are displayed in the dropdown as part of the payments filter.  The second is wrapped around `$gateway` which is used in `payments_data()`.

The purpose of the second filter is to determine what `manual` means in a specific context. This effectively modifies the payment search.

@scottbuscemi the line you added only changes the label of the dropdown item from `Test Payment` to `Manual Purchases` hence it hasn't been added in the PR.
