### ISSUE TITLE
Improve Debug Log View Usability

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#6067]
A few things to fix in the usability of the Debug Log View added in #4864 

- [x] Add some spacing between the two buttons to Download and Clear the log:
<img width="341" alt="screen shot 2017-10-06 at 11 57 49 am" src="https://user-images.githubusercontent.com/1390124/31286905-9d91e308-aa8d-11e7-9fac-c8baabbcdcc4.png">

- [x] Allow highlighting of certain lines. Currently the entire debug log is highlighted, like our system info. There is a use case for just allowing copying specific lines. We could have a 'Copy entire log' button somewhere to enable a fully copy.

**Comment by sunnyratilal** [comment]
PR: #6102
