### ISSUE TITLE
edd_purchase_receipt_after_files $price_id action addition

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#6068]
Within the `edd_purchase_receipt_after_files` function hook, it would be useful to also have the `$price_id` passed in to save on looping over the cart meta to find the option ids.

I will submit a PR for this.

**Comment by pippinsplugins** [comment]
I agree. PR https://github.com/easydigitaldownloads/easy-digital-downloads/pull/6069 looks good, megring.
