### ISSUE TITLE
Fatal error when using [downloads] shortcode

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/easy-digital-downloads#6072]
I did something really dumb and caused a fatal error. As silly as it was, it should probably fail silently.

I placed the `[downloads]` shortcode on a single download page...

```
PHP Fatal error:  Maximum function nesting level of '256' reached, aborting! in /wp-includes/cache.php on line 724
```

**Comment by spencerfinnell** [comment]
Attached a PR. I think having [downloads] inside a single download isn't that silly and can be used to easily create related products, upsells, etc. The PR allows this.

Marked @since 3.0 but can update to something after that since there are template changes that need some testing.

**Comment by SDavisMedia** [comment]
This appears to be working very well for me. Nice. Tested in Themedd, Vendd, and Twenty Eleven. It's being handled consistently in all of those themes. I can't find an issue. :+1:

**Comment by cklosowski** [comment]
Let's make this a 3.0 thing. Since it's a template section and has been around for quite a while, i do'nt see the need to rush to get it out.

**Comment by cklosowski** [comment]
This is looking much better @spencerfinnell thanks.
