### ISSUE TITLE
Store tax rate for each order item

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#6079]
I can't find my existing issue for this, but it would be very useful to store the tax rate along with the tax amount for reporting purposes.

**Comment by pippinsplugins** [comment]
@davidsherlock this was done at the payment-level a while back: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4105

**Comment by davidsherlock** [comment]
@pippinsplugins, I believe this issue needs to be re-opened and I should be able to submit PR for it shortly.

EDD provides filters to allow you to override per item tax rates, which I have implemented in my "Product Taxes" plugin (allowing different tax classes to be used on per-product or category basis). This presents a problem however, at present the tax rate is stored at payment level which isn't ideal when you need the `tax_rate` stored within the `cart_items` array.

The View Details admin view needs to include the tax rate on each cart item row, like this:

![screenshot 2017-12-03 23 31 46](https://user-images.githubusercontent.com/22668877/33531252-3e3a7ab4-d882-11e7-88a0-5710f2574ef4.png)

These rates would only show if the rates were different among the items, otherwise the tax rate would show as it is present.

**Comment by pippinsplugins** [comment]
@davidsherlock I think changing it so the tax rate is shown on a per-item level instead of at the whole payment level makes sense. We can introduce a new helper method for `get_item_tax_rate()` that, if present, returns the tax rate on the item and, if not present, returns the rate on the payment.

**Comment by pippinsplugins** [comment]
@davidsherlock I think changing it so the tax rate is shown on a per-item level instead of at the whole payment level makes sense. We can introduce a new helper method for `get_item_tax_rate()` that, if present, returns the tax rate on the item and, if not present, returns the rate on the payment.

**Comment by cklosowski** [comment]
I think this needs to be added along side the migration to custom tables. so that these tax rates are just simply part of the cart item row.

**Comment by sunnyratilal** [comment]
The name has been updated to reflect how the implementation of this will work.  We will not be adding it to `cart_details` as that will be used for backwards compatibility as of EDD 3.0.

The tax rate will be stored in `edd_order_adjustments` and have a relationship to an order item in the `edd_order_items` table.

This will be accessible using the new query methods.

**Comment by sunnyratilal** [comment]
Just to clarify, if a `tax_rate` is passed within the `cart_details` array from the checkout, it will respect that and store it correctly otherwise it will fall back to the `tax_rate` applied to the entire order.

@davidsherlock This will allow you to add a `tax_rate` key to items in `cart_details` based on the existing filters.

**Comment by sunnyratilal** [comment]
Merged.
