### ISSUE TITLE
Product notes div being rendered when no product notes added to download

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/easy-digital-downloads#6080]
On the purchase confirmation page, the product notes div is being outputted when there are no product notes for the download. `$edd_receipt_args` shows notes as `true`, hence why the div is being outputted.

To replicate, purchase a download with no product notes and view the HTML source on the purchase confirmation page.

<img width="426" alt="screenshot 2017-10-16 00 59 26" src="https://user-images.githubusercontent.com/52581/31584570-64daf07c-b20d-11e7-9780-be5f81c63ff5.png">

**Comment by sunnyratilal** [comment]
PR: #6101
