### ISSUE TITLE
Windows file system issues with stream_get_wrappers

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#6081]
In #5725 there is an issue in the way that PHP detects the 'wrapper' for the files in that it's stating `C`, since `get_attached_file` is actually returning the full path, and not a discoverable URL.

We should just avoid this check on Windows machines as it appears we do not have a valid detection method.

**Comment by sunnyratilal** [comment]
@cklosowski I may be wrong here but I believe `PHP_OS` reports the OS that `PHP` was built on and not the OS that PHP is running on. This will be fine in most cases but we may see an edge case somewhere, perhaps?

If may be better to use a Windows-specific constant from [this list](http://php.net/manual/en/info.constants.php) instead?

So it could just be `if ( defined( 'PHP_WINDOWS_VERSION_MAJOR' ) )`?

**Comment by cklosowski** [comment]
@sunnyratilal `PHP_WINDOWS_VERSION_MAJOR` was [added in PHP 5.3](http://php.net/manual/en/migration53.global-constants.php), so we cannot use it. I think in most cases we'll be fine checking the OS that it was built upon.

In fact WP Core uses this check (where I got it from) in the SMTP class:
```
        // SMTP server can take longer to respond, give longer timeout for first read
        // Windows does not have support for this timeout function
        if (substr(PHP_OS, 0, 3) != 'WIN') {
            $max = ini_get('max_execution_time');
            // Don't bother if unlimited
            if ($max != 0 && $timeout > $max) {
                @set_time_limit($timeout);
            }
            stream_set_timeout($this->smtp_conn, $timeout, 0);
        }
```

**Comment by sunnyratilal** [comment]
Ah ok, yeah, the PR is fine then. Let's get it merged.
