### ISSUE TITLE
EDD_Payment::add_note should escape HTML

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#6082]
This should be done in EDD core's method so that any notes added have it run.

**Comment by sunnyratilal** [comment]
PR: #6171

**Comment by pippinsplugins** [comment]
We have to unescape it as well or else our in-comment links will break.

**Comment by sunnyratilal** [comment]
PR refreshed

**Comment by SDavisMedia** [comment]
All good in both directions on my end. :+1:
