### ISSUE TITLE
Add 'Advanced Filters' to EDD Payment History

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#6086]
In [Free Downloads](https://github.com/easydigitaldownloads/edd-free-downloads/issues/128), it was mentioned it'd be nice to be able to filter out free purchases when viewing the Payment History. 

I think this ability should exist in EDD core, rather than Free Downloads for a number of reasons, but mostly because adding more filters here can only make our payment history more useful.

My _very rough_ thought is something like this (adds an `Advanced Filters` button, which when clicked, expands the other filters available)
![screen shot 2017-10-18 at 3 32 36 pm](https://user-images.githubusercontent.com/1390124/31746289-7fc03cd4-b41b-11e7-9e46-a11eff1c1d79.png)

In my example we have the ability to filter by the payment total with options "Greater than" or "Less than"

This could be an area that contains an action, which would then allow us to move other extensions 'filters' into this area as well. Things like the Software Licensing filters would be nice to move here since they take up so much room, and restrict adding more filters when it's active:
![screen shot 2017-10-18 at 3 47 27 pm](https://user-images.githubusercontent.com/1390124/31746317-ac0a8bc8-b41b-11e7-8164-d775419e9302.png)

**Comment by sunnyratilal** [comment]
Implemented & merged.
