### ISSUE TITLE
Improve visibility of Apps & Integrations

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#6088]

**Comment by cklosowski** [comment]
![screen shot 2017-10-19 at 12 02 02 am](https://user-images.githubusercontent.com/1390124/31758073-cc046418-b460-11e7-8c6a-01bd5a93341b.png)

![screen shot 2017-10-19 at 12 02 11 am](https://user-images.githubusercontent.com/1390124/31758080-d22ac86e-b460-11e7-84c1-f0be09d4fc62.png)

**Comment by cklosowski** [comment]
After discussions with @pippinsplugins, here's the new route:
![screen shot 2017-10-19 at 9 47 09 am](https://user-images.githubusercontent.com/1390124/31783281-9415f5b0-b4b2-11e7-9acf-3a78fb8c35fb.png)
![screen shot 2017-10-19 at 9 47 14 am](https://user-images.githubusercontent.com/1390124/31783282-945d4e7e-b4b2-11e7-990e-a0fe2c7e0161.png)

**Comment by pippinsplugins** [comment]
Merged!
