### ISSUE TITLE
Upgrade to latest version of Chosen

### ISSUE THREAD

**Issue by sunnyratilal** [easydigitaldownloads/easy-digital-downloads#6091]
EDD core uses Chosen 1.1.0 whereas the latest released on 5 Sep 2017 is **1.8.2**.

If we upgrade Chosen to the latest version, this may also fix #4662.

Note: testing would need to be done it doesn't break any extensions that are using Chosen (namely FES and CFM).

**Comment by sunnyratilal** [comment]
PR: #6100

**Comment by sunnyratilal** [comment]
Places to test:

- [ ] Discounts page
- [ ] FES
- [ ] CFM
- [ ] View Order Details page
- [ ] Settings page

**Comment by pippinsplugins** [comment]
All working great here, merging!
