### ISSUE TITLE
Downloads > All Downloads > Add New : Incorrect Internal Dev Link

### ISSUE THREAD

**Issue by GeniiPress** [easydigitaldownloads/easy-digital-downloads#6093]
2.8.9 has an incorrect internal dev URL for the _Downloads > All Downloads > Add New_ button.

It's currently linking to : http://edd.dev/wp-admin/post-new.php?post_type=download

**Comment by sunnyratilal** [comment]
@GeniiPress good catch, we'll push out a fix ASAP
