### ISSUE TITLE
Allow customers to grant their own refunds within a set date range

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#6097]
I am merely logging this suggestion as I've seen a few other eCommerce stores allowing this recently and it's great for building customer trust This might however be better placed as a third party plugin.

Basically, if you have a 30 day refund period, within that period the customer can grant their own refund and have it processed automatically via Stripe/PayPal API via their payment history. After the 30 days passes, the option is no longer available.

This obviously saves a lot of admin/support work as well and builds customer trust. The ability to select a "reason" (maybe from a radio list) for the refund could also be added.

**Comment by cklosowski** [comment]
While I understand the 'good will' angle here, I really don't think this is something that belongs in EDD Core. For instance, take this Tweet as an example of what offering a 'good will' solution to customers can do:
https://twitter.com/carter2422/status/917804230815174656

Now, granted, some stores it makes sense to offer this feature, but I think less than 20% of EDD store owners would probably use it, and therefore I think it belongs in an extension.
