### ISSUE TITLE
Unused display_price argument in edd_get_purchase_link()

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#6106]
There is a `display_price` argument set up on line 136 that is entirely unused. Looks to have been left behind at some point when reworking some of the logic in `edd_get_purchase_link()`.

**Comment by cklosowski** [comment]
My only concern is that it's passed into a filter on line ~176 within the `$args`
`$args = apply_filters( 'edd_purchase_link_args', $args );`

Do we think it's an issue to deprecate it in a minor release?

**Comment by pippinsplugins** [comment]
It's passed to the filter but not used for anything, so unless someone is looking for it _and_ adjusting display based on its presence, I think we're safe to just remove it.
