### ISSUE TITLE
No permissions to download file

### ISSUE THREAD

**Issue by wolffe** [easydigitaldownloads/easy-digital-downloads#6108]
Hi Pippin!

I am getting the "You do not have permission to view this file." error message. I have full permissions, all arguments are in proper order.

I have even used the `edd_validate_url_token` filter, as described on your knowledge base section.

What else should I try?

Thanks!

**Comment by pippinsplugins** [comment]
Hi there!

Please go ahead and open a support ticket through our support portal: https://easydigitaldownloads.com/support

we use GitHub for development tracking only.
