### ISSUE TITLE
Add a filter for edd_get_errors()

### ISSUE THREAD

**Issue by zackkatz** [easydigitaldownloads/easy-digital-downloads#6109]
Having a filter here would allow modifying error messages before they are shown. This is valuable for multiple reasons, including showing gateway-specific error messages based on error codes.

**PR forthcoming.**

**Comment by zackkatz** [comment]
Example usage: https://gist.github.com/zackkatz/4ab374218d5ce3714bcaf52e9e2ce15c

**Comment by pippinsplugins** [comment]
Thanks for sharing!
