### ISSUE TITLE
Discount validation error when recovering pending payment

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#6111]
To replicate:

1) Start to purchase something with a discount code that can be used only once per user (PayPal gateway)
2) Bail on the payment process once you get to PayPal, that way the payment record is left as Pending in EDD
3) Use the recovery URL to try to complete this payment

You should run into this error:

```
Error: This discount has already been redeemed.
Error: One or more of the discounts you entered is invalid
```

**Comment by sunnyratilal** [comment]
PR: #6112

**Comment by sunnyratilal** [comment]
@easydigitaldownloads/core-devs Ready for testing

**Comment by SDavisMedia** [comment]
Replicated again to be sure. `issue/6111` definitely appears to fix the issue. :+!:

**Comment by sunnyratilal** [comment]
Perfect, thanks @SDavisMedia :)
