### ISSUE TITLE
User URL field not saving

### ISSUE THREAD

**Issue by PixelKhaos** [easydigitaldownloads/easy-digital-downloads#6113]
I saw this was pushed as a fix in the recent update, just wanted to note that it still isn't fixed in profile form.

**Comment by chriscct7** [comment]
Are you referring to the profile form in the Frontend Submissions addon?

**Comment by cklosowski** [comment]
@PixelKhaos, I believe @chriscct7 is correct. EDD Core's profile editor does not contain a user URL field. Is this something related to Frontend Submissions (FES)?

**Comment by chriscct7** [comment]
Closing as this has to be the EDD FES field in reference to. @PixelKhaos if you're still having issues, please contact us at easydigitaldownloads.com/support/ so we can take a look.
