### ISSUE TITLE
Registration Form Honeypot Check

### ISSUE THREAD

**Issue by mikeyhoward1977** [easydigitaldownloads/easy-digital-downloads#6115]
Hi,

The registration form (_[edd_register]_) includes a [Honeypot field](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/eb881ef270d43d815754690270074940e9158faa/templates/shortcode-register.php#L43) however I see no validation of this field during the registration process.

I'm being hit with a large number of registrations despite having processes in place to protect against BOT registrations on the main WP registration forms. I guess therefore that these registrations are coming from the EDD form.

PR submitted adding a new `edd_do_honeypot_check()` function and being referenced during registration process

Thanks
Mike

**Comment by davidsherlock** [comment]
@mikeyhoward1977, I recommend installing and using this plugin which uses Google reCAPTCHA service: https://wordpress.org/plugins/recaptcha-for-easy-digital-downloads/

I believe EDD team have no intention of adding this feature in core anytime soon (I asked prior).

**Comment by mikeyhoward1977** [comment]
Thanks @davidsherlock I may take a look. Still feel the honeypot validation should be performed in addition though given the field exists within the form already
