### ISSUE TITLE
Trying to export sales from one day results in "no data" error message

### ISSUE THREAD

**Issue by scottbuscemi** [easydigitaldownloads/easy-digital-downloads#6126]
![screen shot 2017-10-31 at 2 17 20 pm](https://user-images.githubusercontent.com/4336848/32249442-47aab7ae-be46-11e7-8d92-482f3d6060f3.png)

If you try to export data from one day, an error message states there is no data. It looks like the "end date" day's data isn't included in exports. If you do 10/20-10/22, only 10/20 and 10/21 are included when the 10/22 should be included as well in that range.

**Comment by mindctrl** [comment]
Just ran into this bug exporting sales. The sales that happen on the end date are never included in the export.

**Comment by cklosowski** [comment]
I believe we fixed a bug like this in Commissions recently: 
https://github.com/easydigitaldownloads/EDD-Commissions/issues/295

**Comment by cklosowski** [comment]
@sunnyratilal can you see if this is the same type of bug we found in Commissions.

**Comment by sunnyratilal** [comment]
@cklosowski yep it's the same issue.

![image](https://user-images.githubusercontent.com/1525554/33333986-61e3beb0-d460-11e7-9e87-0beded5ce609.png)

**Comment by sunnyratilal** [comment]
PR: #6211
