### ISSUE TITLE
Reports: custom date ranges for detailed product earnings break on multi-month views

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#6128]
The detailed product earnings report has a significant problem when using custom date ranges to show earnings over a multi-month period.

https://easydigitaldownloads.com/wp-admin/edit.php?post_type=download&page=edd-reports&view=downloads&download-id=284975&exclude_taxes=0&range=other&year=2017&year_end=2017&m_start=9&m_end=10&day=27&day_end=31

<img width="1252" alt="screen shot 2017-11-01 at 11 01 25 am" src="https://user-images.githubusercontent.com/1034109/32284067-10be5756-bef4-11e7-839e-11a7b49ffbab.png">

https://easydigitaldownloads.com/wp-admin/edit.php?post_type=download&page=edd-reports&view=downloads&download-id=284975&exclude_taxes=0&range=other&year=2017&year_end=2017&m_start=9&m_end=10&day=27&day_end=31

<img width="1265" alt="screen shot 2017-11-01 at 11 01 40 am" src="https://user-images.githubusercontent.com/1034109/32284068-10e28284-bef4-11e7-866c-cdac5cd39d38.png">

 
First link / image shows Sep 27 - Nov 1

Second link / image shows Sep 27 - Oct 31

Note the different in earnings and the graph.

**Comment by pippinsplugins** [comment]
This is partially related to the logic that sets `$day_by_day` when the graph displays more than two months.

**Comment by sunnyratilal** [comment]
PR: #6139

**Comment by pippinsplugins** [comment]
Works great, merged.

**Comment by pippinsplugins** [comment]
Crud, sorry, spoke too soon.
<img width="1275" alt="screen shot 2017-11-02 at 4 44 11 pm" src="https://user-images.githubusercontent.com/1034109/32351923-11cf9df4-bfed-11e7-879c-cc84680d7718.png">

Most of October is skipped in the example screenshot above.

See https://easydigitaldownloads.com/wp-admin/edit.php?post_type=download&page=edd-reports&view=downloads&download-id=284975&exclude_taxes=0&range=other&year=2017&year_end=2017&m_start=9&day=27&day_end=1&m_end=11

**Comment by sunnyratilal** [comment]
@cklosowski applied the patch and all is working as expected now.

![image](https://user-images.githubusercontent.com/1525554/32355605-7827b4b2-c027-11e7-9e2c-8c5149a2ee2f.png)
