### ISSUE TITLE
Link IP addresses in File Downloads log to American Registry for Internet Numbers (ARIN)

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#6135]
This is arguably the best "lookup" tool for IP addresses and thus it would be useful to have the IP addresses in the "File Downloads" log clickable to this resource. This would make the log more useful and informative for support purposes.

I will submit PR for this.

**Comment by davidsherlock** [comment]
Submitted PR here: #6136

**Comment by chriscct7** [comment]
I have to disagree with the place this links to. While it's certainly a much more official source, the number one reason that I look up IP addresses (and I'm pretty confident this is the same for most users) is to see where the user is from for fraud detection purposes. There really isn't much you can actually learn/use the ARIN presented data for.

 I think the IP Address in payment records and in the file downloads table really should link to https://www.iplocation.net/?query={IP} or something similar.

**Comment by chriscct7** [comment]
Any thoughts @sunnyratilal

**Comment by sunnyratilal** [comment]
I agree with @chriscct7 - the main reason would be to see the location of the user.

I think `ipinfo.io` would be better - it's what we use in EDD Fraud Monitor I believe.

**Comment by davidsherlock** [comment]
I have updated the PR to point to `ipinfo.io`.

**Comment by pippinsplugins** [comment]
I really like this and am happy with merging it.

**Comment by chriscct7** [comment]
Sweet! Nice work @davidsherlock :-)
