### ISSUE TITLE
Last Year report gets wrong end date of 12/01 rather than 12/31

### ISSUE THREAD

**Issue by danieliser** [easydigitaldownloads/easy-digital-downloads#6137]
To easily duplicate this go to Reports -> Earnings -> Change to Last Year. The december shows 0. If I then change it to custom the end date is December 1 2016, correcting it to 12/31 then shows stats for December.

**Comment by cklosowski** [comment]
@sunnyratilal is this like the one you have already tackled?

**Comment by sunnyratilal** [comment]
No I believe this is a different bug...

**Comment by danieliser** [comment]
Think the fix is simple. If the selected option is This or Last year, forcibly override the value of the date fields to match. I think currently it modifies the query args, but not the values passed as current to the filter form fields.

**Comment by sunnyratilal** [comment]
Closing this out as Carbon is now used to handle report dates meaning this issue is no longer valid.
