### ISSUE TITLE
Add user agent to payment meta

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#6138]
Since user agents are used as a fraud detection metric/variable on Stripe, MaxMind and alike, it would be useful to store this as part of the payment meta for retention purposes.

This makes it's easy to see for example that a user purchased on a mobile device but downloaded on a desktop device. Similarly it _may_ be useful for providing software support.

I already have this working with the appropriate classes/functions updated for both file download logs and payments, will submit the PR shortly after I clean up the user-agent parsing function.

**Comment by chriscct7** [comment]
@davidsherlock you might want to consider building the PR using EDD's built in browser.php library. It will give you what you need (see the system info page on EDD for use of it).

**Comment by davidsherlock** [comment]
Thanks for the heads-up @chriscct7, will check it out!

**Comment by ashleyfae** [comment]
Closing in favour of https://github.com/easydigitaldownloads/easy-digital-downloads/issues/8364
