### ISSUE TITLE
POSTING ON THE FRONT END

### ISSUE THREAD

**Issue by studyce** [easydigitaldownloads/easy-digital-downloads#6142]
Hi, I have installed your plugin and it is pretty good. however, is there any way the users can post their products without going to the back end. Also, My site is dealing with Custom Essays and writing services. Is there any way I can check the documents uploaded by the sellers to check if they meet our standards?

**Comment by spencerfinnell** [comment]
The Frontend Submission extension adds this functionality: https://easydigitaldownloads.com/downloads/frontend-submissions/
