### ISSUE TITLE
Store activation limit in license meta

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#6156]
Currently the activation limits refers back to the settings on the product itself. 

The problem with that is this for example: 
If you sell 2-site activation licenses, and later decide you want to sell 1-site activation licenses, customers who purchased a 2-site activation license will be downgraded to only have 1-site activation. 

If the activation limit was stored in the license meta instead, customers would be "grandfathered" and keep their activation limit at the time of purchase. 

This would also require an upgrade routine to save the activation limit into the license meta for each existing license.

**Comment by cklosowski** [comment]
Currently we store it if you change an individual licences activation
count. I think we should make this an option that we present. Personally I
would expect licenzes to maintain the products activation count, not retain
it's original.

**Comment by chriscct7** [comment]
I honestly don't this should even be an option. Decisions not options. With
the ticket in Edd core for hiding price options if you want to grandfather
people you'd just make a new price option for new users.

**Comment by cklosowski** [comment]
I agree. There is a general flow that our products follow that we don't store meta If we don't need to and fallback to the conical limit on the download. Altering a specific license will add it, as we talked about @mintplugins
