### ISSUE TITLE
Incorrect discount errors shown at checkout

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#6159]
To replicate:

1. create a simple discount that **excludes a specific product** and **also has a minimum cart amount** (make sure the specific product you selected costs more than the minimum amount you set
2. go add that excluded product to the cart and apply your discount

You'll end up with an error saying you have not met the cart minimum when you actually have. The real error is that you have an excluded item in the cart.

**Comment by sunnyratilal** [comment]
PR: #6160
