### ISSUE TITLE
Introduce way to retrieve all IP addresses of a customer

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#6177]
Requested here: https://secure.helpscout.net/conversation/463406402/69972?folderId=375162

It might be nice to be able to go get all IP addresses of a customer. This will be a one-to-many relation, and I'd like to not have a ton of duplicate data, but it shouldn't be to difficult to retrieve that data.

**Comment by SimonChaw** [comment]
Would the IP address of the customer be gathered at each purchase? Or would it factor in signing in from a new IP address and accessing downloads?

**Comment by sunnyratilal** [comment]
This could be done really nicely with the `edd_payments` table and just using `SELECT DISTINCT`

**Comment by pippinsplugins** [comment]
Is there a reason not to have a `get_ips()` method inside of `EDD_Customer`?

**Comment by sunnyratilal** [comment]
@pippinsplugins Added in https://github.com/easydigitaldownloads/easy-digital-downloads/commit/52af472f005601c7ecd3401d3a74c801ea79e9f3

**Comment by pippinsplugins** [comment]
@sunnyratilal EDD_Customer's method should hold all the logic. `edd_get_customer_ip_addresses()` should just be a wrapper to the class method.

**Comment by sunnyratilal** [comment]
Merged.
