### ISSUE TITLE
Variable price advanced settings not saving

### ISSUE THREAD

**Issue by giovanisci** [easydigitaldownloads/easy-digital-downloads#6199]
I have variable pricing enabled and have created 3 price options for one single download. Both the Software Licensing Settings and the Recurring Payments Settings will not save when I click update. I've included a video of the problem. [](https://youtu.be/f4Q8g1n3bW0)

**Comment by pippinsplugins** [comment]
Hi there!

Please go ahead and open a support ticket through our support portal: https://easydigitaldownloads.com/support

we use GitHub for development tracking only.
