### ISSUE TITLE
Add a helper to retrieve and filter discount status labels

### ISSUE THREAD

**Issue by DrewAPicture** [easydigitaldownloads/easy-digital-downloads#6203]
In working to implement discounts in SellBird, we discovered that the status labels for discounts are essentially hard-coded into the list table class. I hesitate to _also_ hard-code derivation of the status label as it could easily fall out of date with EDD core should other statuses come in later, or some add-on needs to change something in the future.

The attached PR introduces `edd_get_discount_status_label()` which wraps `EDD_Discount::get_status_label()`. The `get_status_label()` method introduces a `edd_get_discount_status_label` filter.

Also includes four tests for `edd_get_discount_status_label()`.

**Comment by DrewAPicture** [comment]
PR: #6204

**Comment by pippinsplugins** [comment]
PR looks good to me. @sunnyratilal @cklosowski let's get the since tags updated and merged in!

**Comment by sunnyratilal** [comment]
Merged
