### ISSUE TITLE
Improve tax reporting functionality

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#6223]
The tax report provided within EDD is extremely limited, basically just select a `year` and it shows you the tax collected for that period. However, most people pay sales taxes quarterly (or monthly) making this report somewhat redundant.

I believe this report page should be expanded to function as follows:

- Ability to set a custom date range, with some presets like "Last 3 months", etc.

- Ability to group by country (optionally) and display the results in a table.

- Display four columns - item price sum (before tax), tax amount sum, total orders and total item sales (i.e. some items may exempt of tax).

This would make it easy to report VAT MOSS and similar reports.

**Comment by cklosowski** [comment]
Ruplicate/Related #1490
