### ISSUE TITLE
Introduce new report views with reports API

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#6237]
Once the reports API is built (#6236), we will begin implementing the API in order to rebuild out reporting options.

Tentative report sections:

- Dashboard (default view)
- Products
- Refunds
- Payment Gateways
- Taxes
- File Downloads
- Discounts
- Customers
- Export

Related report issues: 
- https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4714
- https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4487
- https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4114
- https://github.com/easydigitaldownloads/easy-digital-downloads/issues/3575
- https://github.com/easydigitaldownloads/easy-digital-downloads/issues/1490
- https://github.com/easydigitaldownloads/easy-digital-downloads/issues/1427
- https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5582

**Comment by sunnyratilal** [comment]
Each view has been registered and the implementation of each report is being tracked in #6296.
