### ISSUE TITLE
Create an API for registering reports (tabs)

### ISSUE THREAD

**Issue by DrewAPicture** [easydigitaldownloads/easy-digital-downloads#6254]
| Tracking | PR | Project |
------------- | -------------| -----------
| #6236 | #6263 | [3DD™: Reporting API Reboot](https://github.com/easydigitaldownloads/easy-digital-downloads/projects/2)  

**Background**

For the new Reports API, we're going to need to extend the new `Registry` superclass to be introduced in #6253 for registering new tabs.

**Comment by DrewAPicture** [comment]
WIP PR: #6263

**Comment by DrewAPicture** [comment]
Merged #6263. 🎉

**Comment by pippinsplugins** [comment]
:tada: !
