### ISSUE TITLE
The schema div can be output at strange times

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#6262]
Some plugins may run "the loop" in the head of the document to check things, and then use [rewind_posts](https://codex.wordpress.org/Function_Reference/rewind_posts) or some equivalent to reset the query. 

In EDD, the schema div is opened and closed by hooking to [loop_start](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/02573df313d1339b6438f74619b9137889daa78a/includes/template-functions.php#L838) and [loop_end](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/02573df313d1339b6438f74619b9137889daa78a/includes/template-functions.php#L862). 

However, we currently have no way of determining which part of the page we are at while `loop_start` is running. This can cause the schema div to be output in strange places, like the `head` tag of the page. This causes the [schema to break](https://search.google.com/structured-data/testing-tool).

If @pippinsplugins' proposed [did_filter](https://core.trac.wordpress.org/ticket/35357) function were to get merged into WordPress core, we could use it to check if `body_class` has been run, and only output the schema div if it has. This would at least prevent it from being output into the `head` of the page. 

Until such a function exists in WordPress, this is difficult to fix or prevent, and affected users may have to deactivate problematic plugins which cause this.

**Comment by pippinsplugins** [comment]
We could check for `did_action( 'wp_head' )` to ensure it only gets added after the header, and then `! did_action( 'wp_footer' )` as well.

**Comment by mintplugins** [comment]
I had considered the wp_head hook, but it seems that if the 3rd party plugin has hooked to `wp_head and is running `the loop` in it, `did_action( 'wp_head' )` will return `1`, because it seems to begin counting at the start of the hook, not once all hooked functions have been completed. So that doesn't guarantee that wp_head is finished running completely.

**Comment by mintplugins** [comment]
In my tests it is my own page building plugin (*ducks*)

**Comment by cklosowski** [comment]
This would be resolved with #6307 wouldn't it? Since we wouldn't be outputting DIVs any longer?

**Comment by mintplugins** [comment]
I believe it would because the structured data is hooked to the footer...if I am reading that PR correctly.
