### ISSUE TITLE
Require Login & Show Registration / Login Forms not updating after 'Save Changes'

### ISSUE THREAD

**Issue by protrolium** [easydigitaldownloads/easy-digital-downloads#6267]
In Settings > Misc > Checkout . . . . I am finding that I can't get EDD to update to the desired setting when I check the 'Require Login' checkbox nor changing the 'Show Registration / Login Form' dropdown umenu variable. When I 'Save Changes' the 'Require Login' checkbox defaults back to unchecked and the umenu defaults back to 'Login Form Only'.

**Comment by pippinsplugins** [comment]
Do you use either the Auto Register or Recurring Payments plugin? Both of those set restrictions on what is permitted for log in and registration forms.

**Comment by protrolium** [comment]
Ah, it appears I have the Auto-Register plug-in. Is there any additional info in the documentation about this ?

**Comment by pippinsplugins** [comment]
There is not at this time. If you can open a support ticket, however, the support team will be happy to assist in answering any questions for you (github is for development only): https://easydigitaldownloads.com/support
