### ISSUE TITLE
Add filed to product page 

### ISSUE THREAD

**Issue by rohollaramezani** [easydigitaldownloads/easy-digital-downloads#6268]
Hi 
I want to add some fields to the product page and user choose this fields and when user click the add to cart button, EDD sends the fields data to the user cart. Please help me.
Also, I need when the user clicks on the payment button the user data and products to be sent to my email not send to the Paypal site. Please help me thank you

**Comment by chriscct7** [comment]
Hi there,

Please go ahead and open a support ticket through our support portal: https://easydigitaldownloads.com/support

We use GitHub for development tracking only.
