### ISSUE TITLE
Earnings export does not trigger edd_export_csv_cols_earnings_report filter

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#6269]
The `print_csv_cols()` method of `EDD_Batch_Earnings_Report_Export` is hard-coding the CSV columns instead of setting them up with the `csv_cols()` method, which results in the `edd_export_csv_cols_earnings_report` filter not being run. This means extensions cannot register custom columns in the export.

**Comment by pippinsplugins** [comment]
Could you look into this? It is blocking Recurring Payments from being able to add renewal earnings to the CSV export.

**Comment by cklosowski** [comment]
I found another number of oddities here while getting this fixed. The `Sales` column, while only includes the number of `published` payments as the `count` column, the `Gross Amount` column is a sum of the amounts of all statuses.

```
$row_data .= isset( $data['publish']['count'] ) ? $data['publish']['count'] . ',' : 0 . ',';

$publish_total   = isset( $data['publish']['amount']   ) ? $data['publish']['amount'] : 0;
$refunded_total  = isset( $data['refunded']['amount']  ) ? $data['refunded']['amount'] : 0;
$cancelled_total = isset( $data['cancelled']['amount'] ) ? $data['cancelled']['amount'] : 0;

$row_data .= '"' . edd_format_amount( $publish_total + $refunded_total + $cancelled_total ) . '",';
```

Seems to me it's either one or the other, a sum of all statuses, or a sum of only completed payments.

I'm going to continue fixing this up but would love some feedback @pippinsplugins @SDavisMedia

**Comment by cklosowski** [comment]
Ok this is ready for testing, easiest way to test the additional order statuses is to have Recurring active and running on `issue/725`.

**Comment by SDavisMedia** [comment]
Looking good to me:

<img width="1707" alt="screenshot 2018-02-02 10 00 48" src="https://user-images.githubusercontent.com/2359131/35747686-f8ed8660-07ff-11e8-9071-54c7ee67a660.png">

**Comment by sunnyratilal** [comment]
PR tested and working as expected 👍
