### ISSUE TITLE
Base class for all custom tables

### ISSUE THREAD

**Issue by JJJ** [easydigitaldownloads/easy-digital-downloads#6277]
See: #6224, #5277, #4576, #3841, #6278 

With the number of custom database tables that EDD 3.0 will introduce, the codebase will benefit from a simple base class to manage the database tables themselves.

Not to be confused with an interface for CRUD actions, this base class is literally only for automating the scope and maintenance of custom database tables themselves.

My plan is as follows:
* Introduce `/includes/database/` as a new directory for the base class to start in
* That directory will eventually contain 1 class per additional database table (including meta tables)
* Each object table should have a complimentary `meta` table for plugin support, following the standard WordPress meta table schema. If that schema ever changes, we would want ours to follow suit.

Table logic:
* Each table will be versioned in `wp_options`, and schema changes will trigger automatic upgrades by comparing versions and calling appropriate methods
* Each table can be independently upgraded as the needs of the application change
* Each table is automatically added to the `$wpdb` interface, so querying them is magically supported
* Each table could be marked as global for explicit multisite support. By default, tables are not global, meaning in a multisite installation EDD is per-site. We could choose to have a canonical EDD site, or a different schema for global tables that includes a `site_id` column. We won't right away, but who knows.

History:
* This same approach is already pushed to Sugar Calendar and a number of my personal plugins, and works great
* I've opened a core ticket to consider moving all core tables to a similar approach. See: https://core.trac.wordpress.org/ticket/37692
* BuddyPress has not moved to this yet, but it probably should 💯 

----

Work on this issue will begin immediately in an issue branch, and I'll defer final merge back to someone else after a thorough review. 👍

**Comment by sunnyratilal** [comment]
Closing this out as we have classes for all the custom tables and they are all working sufficiently.
