### ISSUE TITLE
Introduce an Endpoint API

### ISSUE THREAD

**Issue by DrewAPicture** [easydigitaldownloads/easy-digital-downloads#6280]
| PR | Relies On | Tracking | Project |
------ | ------------ | ----------- | ------------
| #6283 | ~#6254~ | #6236 | [3DD™: Reporting API Reboot](https://github.com/easydigitaldownloads/easy-digital-downloads/projects/2)

**Background**

Endpoints will represent any data-based container to be consumed by reports tab. They will take the form of a variety of view types: tile, table, chart, graph, or any other form of visual representation of data. The endpoint object will dictate which view types are supported and supply callbacks for retrieving and displaying data in the expected format.

Endpoints will be registered (like report tabs) with structured data and rendered using an instantiated `Endpoint` object. The view type dictates what form the ultimate object will take. It will also need to be possible for endpoints to be instantiated on the fly during report object creation.

**Comment by DrewAPicture** [comment]
WIP PR: #6283

**Comment by DrewAPicture** [comment]
Merged #6283 🎉

**Comment by pippinsplugins** [comment]
:tada:!
