### ISSUE TITLE
Invalid argument supplied for foreach() in class-edd-register-meta.php on line 464 when importing Themedd demo data

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#6294]
While setting up a fresh install of WordPress, Easy Digital Downloads and Themedd (using the demo data supplied) locally, the demo data imported fine but the "Andrew Munro" user triggered this error:

`Invalid argument supplied for foreach() in /app/public/wp-content/plugins/easy-digital-downloads/includes/class-edd-register-meta.php on line 464`

**Comment by sunnyratilal** [comment]
We need to wrap an `is_array` check around `$files` in the `sanitize_files()` method.
