### ISSUE TITLE
Invalid argument supplied for foreach() in graphing.php on line 579

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#6295]
To replicate:

1. Delete all payment records.
2. Goto "All Downloads" and click the URL to the "earnings" on a download (assuming earnings have been accrued)
3. This error triggers.

**Comment by cklosowski** [comment]
Since we're completely rewriting the Reporting for EDD 3.0, this will no longer be something we'll have to fix. I'm going to close for now, if we continue to have issues after the new Reporting APIs are done we can re-open it, but the likelihood it'll remain is very very low.
