### ISSUE TITLE
3.0 Reports: Products tab

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/easy-digital-downloads#6298]
Tracking issue: #6296 

### Filters
Date, product, and product price option filters.

Default filter settings will be `Last 30 days` and `All products`, unless another value is persisting due to being previously selected by the user.

### Tiles
- [x] Most valuable product (product with highest earnings)
- [x] Average product earnings (unclear what was wanted with this one)
- [x] Earnings for product price option
- [x] Product vs Product earnings comparison (requires 2 product selections)
- [x] Earnings by category

**Comment by sunnyratilal** [comment]
Report implemented.
