### ISSUE TITLE
3.0 Reports: Payment gateways tab

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/easy-digital-downloads#6300]
Tracking issue: #6296 

### Filters
Date and payment gateway filters.

Default date filter will be `Last 30 days` and `All gateways`, unless another value is persisting due to being previously selected by the user.

### Tiles
- [x] Earnings per gateway
- [x] Sales per gateway
- [x] Refunds per gateway
- [x] Average order value per gateway

**Comment by sunnyratilal** [comment]
Report implemented.
