### ISSUE TITLE
3.0 Reports: Taxes tab

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/easy-digital-downloads#6301]
Tracking issue: #6296 

### Filters
Date, product, and locale filters.

### Tiles
- [x] Total tax collected
- [x] Tax collected per country/state

**Comment by mintplugins** [comment]
Just to get caught up, is there a specific class I should use while building this report?

**Comment by mindctrl** [comment]
We'll have an API for this soonish. Will discuss it in Slack and on #6296 when it's ready.

**Comment by sunnyratilal** [comment]
Report implemented. Locale filters left to do but will be implemented once #6667 is done.

**Comment by sunnyratilal** [comment]
Report implemented.
