### ISSUE TITLE
3.0 Reports: File downloads tab

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/easy-digital-downloads#6302]
Tracking issue: #6296 

### Filters
Date and product filters.

Default filter settings will be `Last 30 days` and `All products`, unless another value is persisting due to being previously selected by the user.

### Tiles
- [x] Number of file downloads
- [x] Average downloads per customer
- [x] Most download products
- [x] Average downloads per order

### Charts
- [x] Number of downloads for selected period and/or product

**Comment by sunnyratilal** [comment]
Report implemented.
