### ISSUE TITLE
3.0 Reports: Customers tab

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/easy-digital-downloads#6304]
Tracking issue: #6296 

### Filters
Date

`*` indicates the tile will not use filters

### Tiles
- [x] Average lifetime value of all customers [*]
- [x] Average customer value for selected period
- [x] Average number of orders per customer
- [x] Average customer age

### Tables
- [x] Most valuable customers for selected period
- [x] Top 5 customers for all time

### Charts
- [x] New customers for selected period

**Comment by sunnyratilal** [comment]
PR opened at #6625 and ready for testing.

**Comment by pippinsplugins** [comment]
This is looking _excellent_!!! :tada: 

A few things I have noticed.

1. The list tables are showing pagination for _all_ customers, not just the most valuable of all time and the current time period. While it could be argued that the pagination here is correct, I don't think we should show any pagination on these tables. Instead I would suggest we show a `View all` link in the bottom right that links to the main customers page sorted accordingly.

![image](https://user-images.githubusercontent.com/1034109/40816244-7414be80-6511-11e8-83a8-9774e76b50a6.png)

2. The `Top Five Customers of All Time` isn't sorting customers right. It's showing all 0.00 customers for me even though my site has customers with a greater than 0.00 lifetime value.

3. `Most Valuable Customers of {period}` is never showing any results for me.

4. We have a deprecated notice here:

>>>The edd_report_views hook is deprecated since Easy Digital Downloads version 3.0! Use the edd_reports_get_tabs hook instead.

Might be coming from one of the other reports that hasn't been updated, just noting it in case.

**Comment by sunnyratilal** [comment]
I believe the issues with 2 and 3 are because you won't have anything data in the new order tables as of yet. Once the migration has been written and run for the payments -> orders, it will display valid data.

Deprecated notices will continue to show until all of the existing reports have been rewritten to use the new APIs.

**Comment by mindctrl** [comment]
Seeing some PHP notices. Not sure why yet. Just pasting here so I don't forget.

```
PHP Warning:  Illegal string offset 'range' in /app/public/wp-content/plugins/easy-digital-downloads/includes/admin/reporting/reports.php on line 250
PHP Stack trace:
PHP   1. {main}() /app/public/wp-admin/edit.php:0
PHP   2. require_once() /app/public/wp-admin/edit.php:10
PHP   3. do_action() /app/public/wp-admin/admin.php:224
PHP   4. WP_Hook->do_action() /app/public/wp-includes/plugin.php:453
PHP   5. WP_Hook->apply_filters() /app/public/wp-includes/class-wp-hook.php:310
PHP   6. edd_reports_page() /app/public/wp-includes/class-wp-hook.php:286
PHP   7. EDD\Reports\Init->__construct() /app/public/wp-content/plugins/easy-digital-downloads/includes/admin/reporting/reports.php:31
PHP   8. do_action_ref_array() /app/public/wp-content/plugins/easy-digital-downloads/includes/reports/class-init.php:128
PHP   9. WP_Hook->do_action() /app/public/wp-includes/plugin.php:515
PHP  10. WP_Hook->apply_filters() /app/public/wp-includes/class-wp-hook.php:310
PHP  11. edd_register_customer_report() /app/public/wp-includes/class-wp-hook.php:286

PHP Notice:  Uninitialized string offset: 0 in /app/public/wp-content/plugins/easy-digital-downloads/includes/admin/reporting/reports.php on line 250
PHP Stack trace:
PHP   1. {main}() /app/public/wp-admin/edit.php:0
PHP   2. require_once() /app/public/wp-admin/edit.php:10
PHP   3. do_action() /app/public/wp-admin/admin.php:224
PHP   4. WP_Hook->do_action() /app/public/wp-includes/plugin.php:453
PHP   5. WP_Hook->apply_filters() /app/public/wp-includes/class-wp-hook.php:310
PHP   6. edd_reports_page() /app/public/wp-includes/class-wp-hook.php:286
PHP   7. EDD\Reports\Init->__construct() /app/public/wp-content/plugins/easy-digital-downloads/includes/admin/reporting/reports.php:31
PHP   8. do_action_ref_array() /app/public/wp-content/plugins/easy-digital-downloads/includes/reports/class-init.php:128
PHP   9. WP_Hook->do_action() /app/public/wp-includes/plugin.php:515
PHP  10. WP_Hook->apply_filters() /app/public/wp-includes/class-wp-hook.php:310
PHP  11. edd_register_customer_report() /app/public/wp-includes/class-wp-hook.php:286

PHP Notice:  Undefined index:  in /app/public/wp-content/plugins/easy-digital-downloads/includes/admin/reporting/reports.php on line 250
PHP Stack trace:
PHP   1. {main}() /app/public/wp-admin/edit.php:0
PHP   2. require_once() /app/public/wp-admin/edit.php:10
PHP   3. do_action() /app/public/wp-admin/admin.php:224
PHP   4. WP_Hook->do_action() /app/public/wp-includes/plugin.php:453
PHP   5. WP_Hook->apply_filters() /app/public/wp-includes/class-wp-hook.php:310
PHP   6. edd_reports_page() /app/public/wp-includes/class-wp-hook.php:286
PHP   7. EDD\Reports\Init->__construct() /app/public/wp-content/plugins/easy-digital-downloads/includes/admin/reporting/reports.php:31
PHP   8. do_action_ref_array() /app/public/wp-content/plugins/easy-digital-downloads/includes/reports/class-init.php:128
PHP   9. WP_Hook->do_action() /app/public/wp-includes/plugin.php:515
PHP  10. WP_Hook->apply_filters() /app/public/wp-includes/class-wp-hook.php:310
PHP  11. edd_register_customer_report() /app/public/wp-includes/class-wp-hook.php:286
```

**Comment by mindctrl** [comment]
These notices happen when there's no filter value saved in the transient here: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/a0c3af1f021ad61de8282a1544f4244c7f0715d5/includes/reports/reports-functions.php#L425

We need to return a default filter value somewhere. cc @DrewAPicture

**Comment by sunnyratilal** [comment]
Merged into `issue/6296`.

**Comment by sunnyratilal** [comment]
Report implemented.
