### ISSUE TITLE
Edit download lifetime checkbox does not save first time around

### ISSUE THREAD

**Issue by scottrpaterson** [easydigitaldownloads/easy-digital-downloads#6306]
Editing a download with variable pricing enabled and the software licensing add-on and you click "Add New Price".

In this newly created price option box, if you check the "lifetime" checkbox and then save the page, it does not save that checkbox value. You have to go back and click it again, then save a second time.

![untitled](https://user-images.githubusercontent.com/11578353/34900123-9cee1aaa-f7ba-11e7-9c27-4fe1cffd9953.png)

**Comment by cklosowski** [comment]
Just making a note, that while this references Software Licensing, it is possible that this is due to something in EDD Core not fixing the `index` of the input when the clone happens on the row. So before we close and move to SL, we should just verify if this belongs in Core or SL.

**Comment by SDavisMedia** [comment]
I think this is core. It happens with the All Access "Exclude from All Access?" setting as well. I can only replicate the behavior with checkbox settings. Everything else seems fine.

To be clear, we want all fields in their default state for a newly created row, correct? @cklosowski

**Comment by cklosowski** [comment]
@SDavisMedia correct. they should be in their unmodified state, and their `index` updated for the new row ID.

**Comment by SDavisMedia** [comment]
Just taking a stab at starting this. Not sure if there's a better way, but the above PR will uncheck any checkboxes when the repeatable row is cloned.

**The problem with the checkbox not saving on the first save is still present, though.**

**Comment by cklosowski** [comment]
i feel like this line is ithe one that's failing @SDavisMedia https://github.com/easydigitaldownloads/easy-digital-downloads/pull/6315/files#diff-4e07975920906985a5fbbe3afd720629R56

Will do some testing today to see what I can figure out.

**Comment by cklosowski** [comment]
Ignore my previous statement, the problem is here:
https://github.com/easydigitaldownloads/easy-digital-downloads/pull/6315/files#diff-4e07975920906985a5fbbe3afd720629R50

We are setting the `value` attribute of all `inputs` to `''` or empty string, meaning that the checkbox is getting an empty value, instead of keeping it at `1`, so saving doesn't work. We need a way to break that out so that we don't reset the `value` on checkboxes, but still do all the key updates.

**Comment by SDavisMedia** [comment]
@cklosowski I think you are absolutely right. I should be able to sort that out then. I have two approaches in mind already. I'll play with them and push something up for feedback later on.

Thanks!

**Comment by SDavisMedia** [comment]
@cklosowski Let me know what you think about that. Working well on my end.
