### ISSUE TITLE
EasyEngine/NginX missing from this page on your support site 

### ISSUE THREAD

**Issue by TerenceMilbourn** [easydigitaldownloads/easy-digital-downloads#6316]
Missing from this page [http://docs.easydigitaldownloads.com/category/301-server](url) on your support site is the following explanation on editing the EasyEngine/NginX server config.

--------------

In order to protect your EDD product upload directory when using EasyEngine and NginX, add the following config under server {} block at `/etc/nginx/sites-available/yourdomain.tld`

`location ~ ^/wp-content/uploads/edd/(.*?)\.zip$ { rewrite / permanent; }`

Also, depending on your PHP version, you can prevent page caching for logged-in users by adding/updating the following code here...

`/etc/nginx/common/redis-php7.conf `

or here...

`/etc/nginx/common/redis.conf`

I am going to assume you are using the Redis page cache and, in which case just need to add `edd_items_in_cart|` to the beginning of this line, so that it looks like this...

`# Don't use the cache for logged in users or recent commenter if ($http_cookie ~* "edd_items_in_cart|comment_author|wordpress_[a-f0-9]+|wp-postpass|wordpress_no_cache|wordpress_logged_in") { set $skip_cache 1; }`

--------------

And that's all folks!

**Comment by SDavisMedia** [comment]
Thanks @TerenceMilbourn! I've broken this down and added it to the relevant docs. :+1:
