### ISSUE TITLE
PHP 7.2 fatal error

### ISSUE THREAD

**Issue by afragen** [easydigitaldownloads/easy-digital-downloads#6317]
There's a PHP fatal error in PHP 7.2 when `count()` is not a countable object or array, like when it's null.

This issue can exist for https://github.com/easydigitaldownloads/easy-digital-downloads/blob/c91cfd9cd984c856b345f88fa9fc0b00887a737c/includes/emails/class-edd-email-tags.php#L211

**Comment by JJJ** [comment]
I just ran into this today, while testing on 7.2.

**Comment by pippinsplugins** [comment]
Put into the 3.0 milestone for now. If we encounter this more, we can move to a point release if necessary.

**Comment by sunnyratilal** [comment]
All unit tests that use `count()` need to be updated as well - PHP 7.2 changed the way the `count()` method is used: https://wiki.php.net/rfc/counting_non_countables.

**Comment by sunnyratilal** [comment]
Currently we have 61 unit tests failing on PHP 7.2 with the same error as above - I'll go ahead and open a PR with so that our test matrix can also test against PHP 7.2 as it was released as of 30 November 2017.

**Comment by sunnyratilal** [comment]
Core build now passes with PHP 7.2

**Comment by sunnyratilal** [comment]
Closing this out as the build currently passes with no issues when tested against PHP 7.2.
