### ISSUE TITLE
User agent in usage tracking portal

### ISSUE THREAD

**Issue by shivapoudel** [easydigitaldownloads/easy-digital-downloads#6320]
Hey folks can you explain me what's the use of this user-agent during tracking.

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/c91cfd9cd984c856b345f88fa9fc0b00887a737c/includes/admin/tracking.php#L141

If that does some checks and create new tracked data if no match found and updates the tracked data if matched found then please share some snippet how to do that check.

CC @pippinsplugins

**Comment by pippinsplugins** [comment]
We do not use the user agent for any form of identification. Each site is identified by its URL only.
