### ISSUE TITLE
EDD Suscriptions and Managment

### ISSUE THREAD

**Issue by Basilakis** [easydigitaldownloads/easy-digital-downloads#6330]
Hey Guys,

I would like to bring a discussion into topic, so we can be able to identify and bring a solution to the problem.
On the SAAS world, we are trying to find ways to improve things like Churn. As EDD can be used for the " front end " platform to manage payments and then use the API to manage the info on the backed.

Going forward, I am actually using it for many clients for the front end work I do.
There are some problems although, when going to subscriptions.

- There should be an option to " Pause " subscription and not only Cancel. That is supported from Stripe and from PayPal also. It could potential increase the earnings.
- Going further, there should be also hooks / filters into the Cancel / Pause subscriptions. For example, before the process go through I would like to add a question-air, so I can eliminate churn, or I would like to go through a " Keep alive " plan, where the subscription can go into a lower cost, like 4$ / month, but I can still have the client around to re-engage. With 500 clients instead of canceling, going to that 4$ it can potential bring 2K extra / month. That is a great amount of money, right? That again needs a process, so the Susped / Cancel should have an option to allow the client confirm. A second page would be a lot better than a popup, as you understand so any other functionality can be created by developers.

Would love your thoughts.

**Comment by pippinsplugins** [comment]
@Basilakis I'm going to add you to our Recurring Payments repo. Could you please re-open this there once added?

**Comment by Basilakis** [comment]
Ofcourse, I will do once there.

Thank you

**Comment by Basilakis** [comment]
Hi,

I haven't received something yet.

**Comment by mindctrl** [comment]
@Basilakis check your spam folder? The invitation is pending.

![image](https://user-images.githubusercontent.com/1254870/35472473-e48d8222-033d-11e8-8a3f-1c1fb38dbe94.png)

**Comment by Basilakis** [comment]
@mindctrl Nothing there actually also. Can u point me the link, so I can see the notification and accept it please?

**Comment by Basilakis** [comment]
I also updated the email - to make sure nothing is getting blocked, would appreciate if you can send it again please.

Thank you

**Comment by tobeyadr** [comment]
I would like to see paused subscriptions as well!
