### ISSUE TITLE
Security issue reporting issue

### ISSUE THREAD

**Issue by pjeby** [easydigitaldownloads/easy-digital-downloads#6336]
I tried to report a vulnerability today, but received the following response from Google:

> We're writing to let you know that the group you tried to contact (security) may not exist, or you may not have permission to post messages to the group. A few more details on why you weren't able to post:
> 
> * You might have spelled or formatted the group name incorrectly.
> * The owner of the group may have removed this group.
> * You may need to join the group before receiving permission to post.
> * This group may not be open to posting.

**Comment by pippinsplugins** [comment]
@pjeby the address is `security@easydigitaldownloads.com`. I've just tested and it is working. Is that the address you sent it to?

**Comment by pjeby** [comment]
Yes.  Is the group open to posting from non-members?

**Comment by pippinsplugins** [comment]
Try it again now please/

**Comment by JJJ** [comment]
Address is working, and @pjeby and I are chatting back and forth now.

Thanks everyone!
