### ISSUE TITLE
License renewal report broken for the last 30 days

### ISSUE THREAD

**Issue by tijmensmit** [easydigitaldownloads/easy-digital-downloads#6338]
When I check the default sales report for the last 30 days, then it works fine.

If I then select 'License renewal' and apply that it shows no output on the graph, it only shows the 1th of Jan in the middle and no data.

When I then change to 'This month', then it works as expected.

**Comment by mindctrl** [comment]
Hi @tijmensmit, we use GitHub for development tracking only, and the software licensing extension is managed in its own repo. I'll open an issue in that repo. In the future please go ahead and open a support ticket here: https://easydigitaldownloads.com/support/

**Comment by cklosowski** [comment]
This will likely get completely rewritten (and is actually part of EDD Software Licensing, not EDD core), once EDD 3.0 is done and the reporting is totally rewritten. We've also added some data into Software Licensing that will make this report more accurate once we implement it.
