### ISSUE TITLE
the default status is Pending !

### ISSUE THREAD

**Issue by mou74** [easydigitaldownloads/easy-digital-downloads#6343]
https://alkhaironline.com/
In a problem with the wordpress Easy Digital Downloads plugin

After payment is successful or failed

is converted to site without sent to the database 
or admin panel that its success payment or failed
it just add it only in payment-history without status!
the default status is Pending i changed it to SUCCESSFULLY, FAILD Manual its not auto changed ! 
![screen shot 2018-01-31 at 3 33 32 pm](https://user-images.githubusercontent.com/34809886/35626694-89ae3e6a-06a7-11e8-89b3-9162fb918083.png)

**Comment by mindctrl** [comment]
Hi @mou74, 

Please open a support ticket at https://easydigitaldownloads.com/support/. We use Github for development tracking only.
