### ISSUE TITLE
Tracking timeout and blocking

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#6367]
We don't really care about the server result of the optin tracking nor does it need to be blocking.

We could/should change the wp_remote_post to blocking->false and timeout to either 3 or 5 seconds

**Comment by cklosowski** [comment]
@chriscct7 yeah the only reason we block is so we know if it was successful or not. I guess that's not really super important, we can just assume it was successful, I think.

**Comment by chriscct7** [comment]
Yeah but we don't do anything if it actually fails.

It returns early here: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/admin/tracking.php#L146

so it doesn't save the time of last save, but it doesn't actually matter because regardless of whether or not it succeeded, and whether or not the last_time is updated, send_checkin, the function involved, is only called on the edd_weekly_cron, so regardless it will always be sent again in exactly a week: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/977bdc5237d3989e2b6807e7b0a6bee717ca4506/includes/class-edd-cron.php#L73

The only thing this really allows for is disallowing someone from manually using something like crontrol and re-sending the tracking if an error occurs, but there's no visual indication of failure to receive, so no one would use (much less have the interest) in manually installing a tool and resending that specific cron event.
