### ISSUE TITLE
Preview changes not working on wordpress

### ISSUE THREAD

**Issue by damien34000** [easydigitaldownloads/easy-digital-downloads#6368]
When i click Preview Changes on wordpress, i have this page coming : Not Found

The requested URL /downloads/how-to-become-a-successful-model/ was not found on this server.

How can i make it work ?

Thank you,

**Comment by cklosowski** [comment]
@damien34000 
Github is for development tracking only. Please contact our support team here:
https://easydigitaldownloads.com/support
