### ISSUE TITLE
Warning: count(): Parameter must be an array or an object that implements Countable in widgets.php on line 311

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#6372]
Did a fresh install of WordPress, EDD with Themedd locally and setup the default widgets. On download pages, this error is displaying:

`Warning: count(): Parameter must be an array or an object that implements Countable in /app/public/wp-content/plugins/easy-digital-downloads/includes/widgets.php on line 311`

**Comment by davidsherlock** [comment]
It fails because of this line:

`$tag_count    = count( get_the_terms( $download_id, 'download_tag' ) );`

I am using the Themedd demo data, which contains no tags and the count function is being run without any checks before hand, thus resulting in this error.

**Comment by amdrew** [comment]
Have seen this also, appears on plugin activation. Same as: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6314

**Comment by mrirmak** [comment]
I used this way (add to line 77):

`if( get_the_terms( $download_id, 'download_tag' ) !=null){
			$tag_count    = count( get_the_terms( $download_id, 'download_tag' ) );
			}
			else{$tag_count=0;}`
