### ISSUE TITLE
Incorrect locale sent from EDD_Tracking

### ISSUE THREAD

**Issue by sunnyratilal** [easydigitaldownloads/easy-digital-downloads#6391]
In #5247 we introduced support for `get_user_locale()` but the tracking data sent is actually incorrect.

I was speaking to @chriscct7 and the example he gave was:
>if you have a site where the main language is german, but let's say a user logs in who uses the english locale
> this is going to send back english, despite the fact its a german language site

[This line](https://github.com/easydigitaldownloads/easy-digital-downloads/pull/5248/commits/33cb6ba8533a38beb0ee49aabb61ca08b28bf284#diff-16d5726d2bd6201efff83c104b354a22R104) needs to be reverted.

**Comment by sunnyratilal** [comment]
@cklosowski @pippinsplugins I've opened a PR but would like your thoughts just before I merge this in. @chriscct7's example makes sense because the tracking is based entire on the site.

**Comment by pippinsplugins** [comment]
All agreed here, merging.
