### ISSUE TITLE
EDD is showing in language espanol-all other items in dashboard menu in English. 

### ISSUE THREAD

**Issue by silverhoopedge** [easydigitaldownloads/easy-digital-downloads#6397]
customer concern about language display issue in WP dashboard
similar experience replicate in my test site----
1-all plugins off except for EDD, 
2-theme=twenty fifteen.
3-language of user=English, 
4-language for site settings=espanol,
result: EDD is showing in language espanol-all other items in dashboard menu in English. 

source of issue: https://secure.helpscout.net/conversation/526013683/76413?folderId=1847248

**Comment by cklosowski** [comment]
Duplicate of #5800.
