### ISSUE TITLE
Add context 'codes' to the You do not have permission to download this file error message

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#6398]
There are a few cases where the message `You do not have permission to download this file` is displayed that we could improve the support/docs so that when users get this error it can lead them to documentation.

For instance this doc is a pretty easy thing for us to detect that we could give a specific error code for to help support identify the actual failure case:
https://docs.easydigitaldownloads.com/article/1351-invalid-download-links-due-to-query-string-order-modification

**Comment by sunnyratilal** [comment]
Merged.

The error codes have been added to Trello: https://trello.com/c/1y7BooGg/73-file-download-error-messages
