### ISSUE TITLE
Links break when using SendGrid link tracking

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/easy-digital-downloads#6413]
In the URLs, things like `&` get converted to `#038;`, which can break some links when passed through their link tracking.

We experienced a similar thing in [RCP #1585](https://github.com/restrictcontentpro/restrict-content-pro/issues/1585). Our fix was to search/replace those occurrences of `#038` with `&amp;` in the `text_to_html()` method of the email class. https://github.com/restrictcontentpro/restrict-content-pro/pull/1708/files

The difference I see is in RCP we use `make_clickable()`, which may make a difference here. We'll need to test and confirm.

Previously #3998, which was closed without a code resolution.

**Comment by cklosowski** [comment]
Thanks @mindctrl Submitted a PR that does those replacements, and also added the `make_clickable` with a filter to be able to turn it off, like we do for `wpautop`.

**Comment by SDavisMedia** [comment]
I replicated the original issue by testing "View it in your browser" links from the purchase receipt on `master`. With link tracking on in SendGrid, I end up with:

`http://localhost/edd-dev/?payment_key=f76a457db44d01044bc4a49fae973f15#038;edd_action=view_receipt`

On `issue/6413`, I get:

`http://localhost/edd-dev/?payment_key=d1ef88ee1d0c686cd1d0e3f7b862e8dd&edd_action=view_receipt`

Based on my experience with the bug, that's a confirmed fix. :+1:

**Comment by mustafaekim** [comment]
I've faced the same problem. My link below

- /tr/test/t64/sanofi-turkiye-diabetes-2018?invitationCode=9536bcab-c187-4d91-a6ed-10345a275264&isGoal=y

is replaced with

- /tr/test/t64/sanofi-turkiye-diabetes-2018?invitationCode=9536bcab-c187-4d91-a6ed-10345a275264& amp; isGoal=y

end our website cannot understand the type of invitation because of this bug. We have been completely out of service

**Comment by cklosowski** [comment]
@mustafaekim please contact our support channels. Looking at your example and the code implementation we used to fix this, it would not be affecting your specific use case currently.

Submit a ticket to https://easydigitaldownloads.com/support and supply your system info so our support team can take a closer look.
