### ISSUE TITLE
Update billing address fails with error

### ISSUE THREAD

**Issue by alpipego** [easydigitaldownloads/easy-digital-downloads#6422]
When I tick the checkbox `edd-stripe-update-billing-address` at checkout without changing the data, it fails with the following error:

> Error: You cannot set 'address_line2'to an empty string. We interpret empty strings as NULL in requests. You may set obj->address_line2 = NULL to delete the property

Edit: 'card_address2' is empty at this point.

**Comment by SDavisMedia** [comment]
Replicated. Even if you do change the other fields, this error still occurs if you leave `Billing Address Line 2` blank.

**Comment by SDavisMedia** [comment]
Actually, this is a Stripe issue. I'm going to close this issue and open it up on our Stripe repo. Thanks for reporting, @alpipego!
