### ISSUE TITLE
Better error reporting for usernames with UPPERCASE letters.

### ISSUE THREAD

**Issue by adampickering** [easydigitaldownloads/Easy-Digital-Downloads#643]
We need to display a better warning/error message for users who try to use any uppercase letters or strange symbols within there username as currently the message just says: Invalid Username which isn't enough information for the customer to correct the issue and proceed in the checkout.

I'm not sure what it should say but something like, Please do not use uppercase letter in the username. Or Please use all lowercase letters in the username.

**Comment by JJJ** [comment]
Update: https://core.trac.wordpress.org/ticket/17904#comment:63

**Comment by pippinsplugins** [comment]
Thanks @JJJ!
