### ISSUE TITLE
Warning: count(): Parameter must be an array or an object that implements Countable in display-settings.php

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#6434]
As per the title, when you visit the "Licenses" tab this PHP error is triggered. Across the board, PHP 7.2 compatibility need's some work in EDD in relation to the usage of `count()`. Will keep an eye out for anywhere else I see it flagging up.

**Comment by SDavisMedia** [comment]
@cklosowski now that I finally got my environment running PHP 7.2.X, I was able to replicate the warning and confirm that it's fixed on `issue/6434`. :+1:
