### ISSUE TITLE
Add .test to valid local/dev domain in software licensing when activating a license

### ISSUE THREAD

**Issue by collizo4sky** [easydigitaldownloads/easy-digital-downloads#6435]
I am too lazy to open an email support ticket for this.

I hope the title says it all.

**Comment by SDavisMedia** [comment]
@collizo4sky I'm going to close this as it isn't an EDD core issue. I see nothing wrong with the suggestion, though. I'll open an issue on the Software Licensing repo instead if the team agrees with the enhancement.
