### ISSUE TITLE
Add class parameter support to [downloads] short-code arguments

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#6436]
Having the ability to append an additional (_optional_) class onto the `[downloads]` wrapper when outputting the  short-codes/grids would be extremely useful when you want to apply different styling to different page elements.

**Comment by SDavisMedia** [comment]
I know `edd_downloads_list_wrapper_class` filter is available but I do think this is a good idea to be able to do from the shortcode attributes.

**Comment by cklosowski** [comment]
As a note, we'll need to make sure before the output of them (after the filter runs) we should be sure to run a `unique` check so we're adding the classes only once.
