### ISSUE TITLE
Incorrect setting title for completing free purchase button

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#6437]
I think the title of this setting is incorrect, unless I'm missing something:

![image 2018-03-18 at 1 09 37 pm](https://user-images.githubusercontent.com/2359131/37570508-d275030c-2aad-11e8-894b-8e4d8851d18b.png)

Added here: https://github.com/easydigitaldownloads/easy-digital-downloads/pull/5722/files

What exactly does `Register Text` represent? I think that should probably be changed to `Complete Free Purchase Text`.

**Comment by cklosowski** [comment]
Probably a Copy/Paste Error. It should be to change the final complete purchase button when the total is `$0.00`

**Comment by SDavisMedia** [comment]
<img width="909" alt="screenshot 2018-03-19 10 35 15" src="https://user-images.githubusercontent.com/2359131/37612033-3b42a052-2b61-11e8-8b61-9921a18db70f.png">
