### ISSUE TITLE
Update Grunt configuration

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#6439]
I just need a placeholder issue.

**Comment by SDavisMedia** [comment]
This is becoming difficult to manage because testing the config is causing changes (that's a good thing) I don't want to be part of this issue. 😄 So pushing up and opening a PR now to try to keep this stuff isolated.

This covers just the basics:

* Minify CSS files (individually) in the `assets/css` folder, excluding `.min.css` files and files with `jquery` in the name.
* Minify CSS files (individually) in the `templates` folder.
* Uglify JS files (individually) in the `assets/js` folder, excluding `.min.js` files and files with `jquery` in the name.
* Check all plugin translation functions for missing or incorrect text domains. Since there are a few that are missing on purpose, the command will continue to run, but the "problems" will display in command line just so you know where they are.
* Update the .pot file
* Build a `build/` directory in the root of the plugin that includes a clean copy of the version of EDD you're releasing as well as a .zip copy. This directory will not include any dev/tool related files and it will be ignored by git. So it's basically just for you locally (can easily be used to drop over an SVN checkout to update the files... until we have a better solution for that process).

-----

With NPM and Grunt set up for the project and everything updated based on the new config, the following command should handle all of the above:

`grunt build`

**Comment by SDavisMedia** [comment]
I've actually decided to approach minifying the CSS files from the opposite direction.

In both the `assets/css` folder and the `templates` folder, there's actually just one file in each that we edit. The rest are libraries. I left the file specifications in long form (doesn't hurt anything) because we could end up adding more files. Plus, I'm curious if we usually minify those library files ourselves.

`chosen.css`, for example... do we usually download both versions of the file or do we get the regular file and then minify it "manually"? If the latter, I can adjust this to minify them with the grunt script. I just wanted to be sure first. Same is true of the other files that are libraries (both CSS and JS).

**Comment by SDavisMedia** [comment]
Been trying to find a good tool for building a changelog rough draft based on Issue titles under a specific milestone. Not having much luck.

Feel free to drop ideas, preferences, and requirements... anything to make the release process easier to handle.

**Comment by cklosowski** [comment]
@SDavisMedia this _might_ work, but i've not tested. https://github.com/conventional-changelog/grunt-conventional-github-releaser

**Comment by spencerfinnell** [comment]
Linking to the comparison view in Github also provides helpful information on point releases. 

https://github.com/easydigitaldownloads/easy-digital-downloads/compare/2.8.17...2.8.18

Wouldn't be as useful on larger releases though.

**Comment by SDavisMedia** [comment]
Just improved the `copy` task. Thanks for the tip, @spencerfinnell.

Will play with the other suggestions shortly.

**Comment by cklosowski** [comment]
@SDavisMedia we shouldn't minify the vendor files, we usually upload both the non-minified and minified versions we get directly from the libraries.

I would say though, if we can 'ignore' those, and just run on anything in that directory that isn't a vendor file, I would think that would be ideal.

**Comment by SDavisMedia** [comment]
@cklosowski It's tough to make that approach future proof for the `cssmin` task. It's already done that way for `uglify`.

For the `uglify` task, I'm ignoring anything that's already uglified or has `jquery` in the file name: `[ '*.js', '!*.min.js', '!*jquery*.js' ]`.

For the `cssmin` task, though, we've got vendor files like `chosen.css`, `colorbox.css`, and others. When I took a step back and looked at EDD's overall CSS files, it boiled down to `edd.css` and `edd-admin.css`. Not only that, I can't see any reason why we'd introduce any other files that would be used in the same fashion as those two. If you agree with that, it makes more sense to just target them specifically to minify.

**Comment by SDavisMedia** [comment]
@cklosowski As for all of the git release-focused tasks I've seen, they're going to require us to start keeping up with setting the EDD version number in the package.json file. The majority of the tasks (if not all of them) will depend on it. I dismissed nearly everything decent task I saw because I don't think we should introduce that step to the release process (updating the package.json version number). How do you feel about it?

**Comment by cklosowski** [comment]
@SDavisMedia 

RE: CSS Minification. Sure, just focus on our two files, that should be fine. :+1:

RE: package.json file. I usually update that step anyway in my process (and forget to sometimes), but making it a requirement is a good thing. I say :+1: to focusing on using the package.json.

**Comment by cklosowski** [comment]
@SDavisMedia is this good to go then after our discussions about using the `package.json` version we had on Zoom and in person last week?

**Comment by SDavisMedia** [comment]
@cklosowski This can be merged as-is right now, yes. I still have to explore other enhancements... mainly things focused on tagging and creating a rough draft changelog. But I would like for that to be separate from what's here already as the current PR is more pre-release tasks.

The next set of enhancements would end up depending on `package.json` and focus on actual release functionality.

**Comment by cklosowski** [comment]
:+1: Thanks @SDavisMedia

**Comment by cklosowski** [comment]
This looks 🥇 to me. Merging!

**Comment by SDavisMedia** [comment]
@pippinsplugins (assuming you haven't played with this yet) all you should need to run once you pull down master is `npm install`. If there's more to run, you should see a prompt for it. Then `grunt build` will run through some tasks for you before releases. More tasks coming later.

**Comment by pippinsplugins** [comment]
@SDavisMedia thanks!
