### ISSUE TITLE
Incorrect or missing textdomains

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#6443]
This issue _does not_ include missing textdomains that are meant to be missing (to match WP core):

#### Missing

* https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/admin/discounts/add-discount.php#L21
* https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/admin/discounts/edit-discount.php#L35
* https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/admin/settings/register-settings.php#L2034

#### Wrong

* https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/admin/class-edd-notices.php#L150
* https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/admin/payments/class-payments-table.php#L142
* https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/tests/bootstrap.php#L39

#### Needs Feedback

* Why are these translation-ready? https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/template-functions.php#L347-L348

**Comment by SDavisMedia** [comment]
@cklosowski can you check out that Needs Feedback one for me please? I don't think that needs to be translation-ready.

**Comment by cklosowski** [comment]
@SDavisMedia I cannot see any reason to make those translation ready. Go ahead and just swap them out for `echo esc_attr()`. Only thing I could think is so that they didn't need an `echo` statement before them 😆

**Comment by SDavisMedia** [comment]
That's exactly what I figured. :joy: Will fix.

**Comment by SDavisMedia** [comment]
According to our `checktextdomain` Grunt task, that's everything. There's only one other string with a missing textdomain and it's intentional to match WP core. :+1:
