### ISSUE TITLE
Discounts Pro can get applied to Free Downloads, causing negative price and Advanced Sequential Order Numbers issue

### ISSUE THREAD

**Issue by mathewlane** [easydigitaldownloads/easy-digital-downloads#6452]
This occurs in following case:
When customer has filled a Cart where a Discounts Pro discount rule is automatically being applied,
and then (with Cart still filled) is going for a direct Free Download elsewhere on the site.

The causes the calculated discount of the filled Cart to be applied to the Free Download, resulting in a negative purchase amount and a 'Completed' Advanced Sequential Order Number applied to it, rather then a 'Free' Advanced Sequential Order Number and a zero purchase amount.

While in the end the customer of course still pays nothing, the issue here is dual:
- Negative purchase amounts will affect statistics
- Wrongly assigned 'Completed' Advanced Sequential Order Numbers mess up with sequential ordered invoices of actual paying customers.

An easy solution to implement would be that when clicking on a direct Free Download, the current Cart is first emptied before processing the direct Free Download.

**Comment by cklosowski** [comment]
@mathewlane When you say 'Direct Free Downloads' are you referring to the Free Downloads extension?

**Comment by SDavisMedia** [comment]
@cklosowski yes, he's referring to Free Downloads. I've replicated. We'll probably need to move this issue.

**Comment by SDavisMedia** [comment]
@mathewlane I'm going to close this issue. I've opened a new issue on the Free Downloads repo. We'll take care of it there. Thanks for the report!
