### ISSUE TITLE
Text fields unset when saving settings from another section

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#6455]
Issue for PR: https://github.com/easydigitaldownloads/easy-digital-downloads/pull/6454

I replicated this. It seems to only unset a text field when the text field is on the "Main" section of the Extensions tab. Other field types have not been tested yet.

<img width="466" alt="screenshot 2018-03-26 11 15 28" src="https://user-images.githubusercontent.com/2359131/37924538-03ee59f8-30e7-11e8-9b3c-a9788b206bd9.png">

**Comment by SDavisMedia** [comment]
@JeroenSormani's is working well for me. Thanks for the report and PR, Jeroen. Will have to team look over your PR soon.

**Comment by cklosowski** [comment]
Let's see if we can just get this text field thing fixed, with minimal code impact. The overhaul caused some major issues as seen in #6469.

For this issue let's just focus on fixing the main issues without refactoring the sensitive save routine of settings.
