### ISSUE TITLE
how can i show my EDD downloads as products on my sahifa theme ?

### ISSUE THREAD

**Issue by sasansss** [easydigitaldownloads/easy-digital-downloads#6468]
i use sahifa theme and i have some downloads on my EDD plugins but my theme dosen't understand my downloads as product and i can't show my downloads as product in my theme's shop and my theme don't show my downloads categories on my shop and product's category 
how can i fix this issue ? Please HELP me to fix it .
Thanks

**Comment by pippinsplugins** [comment]
Hi there!

Please go ahead and open a support ticket through our support portal: https://easydigitaldownloads.com/support

we use GitHub for development tracking only.
