### ISSUE TITLE
Some settings types do not save any longer

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#6469]
The changes introduced in #6455 have caused some settings types to not save. Known to be affected types include:

- radio
- select

**Comment by pippinsplugins** [comment]
PR ready for testing.

**Comment by SDavisMedia** [comment]
Interesting. I could only replicate this with _some_ radio/select fields while it works fine with others. I think it has to do with where the settings are within the tabs.

I tested every setting I could here and they all work on issue/6469. :+1:

**Comment by SDavisMedia** [comment]
Scratch that. Fallback tax rate field is not working while others are. 😳 Trying to figure out why.

**Comment by SDavisMedia** [comment]
Fields that are not working on `issue/6469`:

* Fallback Tax Rate
* Base State / Province
* Thousands/Decimal Separator
* Default Gateway
* All PayPal Standard fields except the checkbox 🤦‍♂️ 

Gonna stop here before I lose all of my settings. Looking at the code now.

**Comment by SDavisMedia** [comment]
Yea something's not right but I can't tell what. Please check [some of] the settings I listed above to see if you get the same behavior. I can't put my finger on a pattern here. On both `master` and `issue/6469`, some settings work and some don't.

Also just a reminder that none of this has been released yet. #6455 is merged for 2.9.1, which isn't out yet. If that's already understood, ignore me.

**Comment by JeroenSormani** [comment]
Damn! Sorry for not noticing that when doing the initial PR..

Can I suggest to refactor the entire `edd_settings_sanitize()` a bit? When I was looking into the other bug I found the entire function very confusing to work with.

Iterating through the setting types within a sanitize function didn't (still doesn't) really make sense to me. I'd expect to iterate through each (registered) setting and sanitize the value accordingly to the type. 

Happy to send in a suggestion for this as a PR if a small refactor is indeed desired.

**Comment by cklosowski** [comment]
I'm going to revert #6455 out of `master`. We can reassess it then.

**Comment by cklosowski** [comment]
I'm going to remove the labels and close the PR for this for now. We'll rethink #6455, so it's not as invasive into the save process and less risky. If we still have issues or feel like a refactor is necessary, we'll go ahead and continue development here (and rename the title if necessary).

**Comment by cklosowski** [comment]
with the fixes in #6455 being merged, this should no longer be an issue.
