### ISSUE TITLE
Payment Method Icons Using Filesystem Path Instead of URL

### ISSUE THREAD

**Issue by mfisher31** [easydigitaldownloads/easy-digital-downloads#6477]
### Expected behavior
Payment Icons to actually be displayed on checkout page.

### Actual behavior
404 error instead of icons

### Steps to reproduce the behavior
1) Go to the checkout page

### Information (if a specific version is affected):
PHP Version: not sure

EDD Version (or branch): 2.9

WordPress Version: 4.9.4

Any other relevant information:
The icons used to display perfectly until upgrading to a recent version of EDD.  The code is setting the images src attribute to the absolute path on the server's filesystem.

<img width="326" alt="icons-missing" src="https://user-images.githubusercontent.com/880111/38325682-b9dbd570-3811-11e8-8d89-9498f71f193c.png">
<img width="678" alt="src-full-path" src="https://user-images.githubusercontent.com/880111/38325687-bf1a62b8-3811-11e8-9c0e-c29e04709641.png">

**Comment by SDavisMedia** [comment]
Possibly broken here: https://github.com/easydigitaldownloads/easy-digital-downloads/pull/6384 I can't replicate at the moment, though. This isn't happening for everyone, so simply going to the checkout page is not enough.

@mfisher31 Off the top of your head, is there anything special about your configuration in regard to plugin path, uploads path, or anything related?

Can you share your EDD system info?

**Comment by mfisher31** [comment]
Nope, paths are all the standard locations. I run EDD with apache behind a load balancer.  It's always worked in previous versions.  I'm really not sure which version of EDD it started happening in.  I just happened to notice it this morning while testing a payment gateway.

```
### Begin System Info ###

-- Site Info

Site URL:                 https://kushview.net
Home URL:                 https://kushview.net
Multisite:                No

-- Hosting Provider

Host:                     .......

-- User Browser

Platform:                 Apple 
Browser Name:             Chrome  
Browser Version:          65.0.3325.181 
User Agent String:        Mozilla/5.0 (Macintosh; Intel Ma 
			  c OS X 10_12_6) AppleWebKit/537.
                          36 (KHTML, like Gecko) Chrome/65
                          .0.3325.181 Safari/537.36
                          
-- WordPress Configuration

Version:                  4.9.4
Language:                 en_US
Permalink Structure:      /article/%postname%/
Active Theme:             Kushy 1.0.0
Parent Theme:             Divi 3.0.106
Show On Front:            page
Page On Front:            Home (#2)
Page For Posts:           News (#118)
ABSPATH:                  ....
Remote Post:              wp_remote_post() works
Table Prefix:             Length: 3   Status: Acceptable
WP_DEBUG:                 Disabled
Memory Limit:             40M
Registered Post Stati:    publish, future, draft, pending, private, trash, auto-draft, inherit, refunded, failed, revoked, abandoned, processing, active, inactive, preapproval, cancelled

-- EDD Configuration

Version:                  2.9
Upgraded From:            None
Test Mode:                Disabled
AJAX:                     Enabled
Guest Checkout:           Disabled
Symlinks:                 Disabled
Download Method:          Direct
Currency Code:            USD
Currency Position:        before
Decimal Separator:        .
Thousands Separator:      ,
Upgrades Completed:       upgrade_payment_taxes,upgrade_customer_payments_association,upgrade_user_api_keys,remove_refunded_sale_logs,sl_add_bundle_licenses,sl_deprecate_site_count_meta,stripe_customer_id_migration,upgrade_mailchimp_api3,upgrade_mailchimp_api3_default_list,eddmc_304_interests_fix
Download Link Expiration: 48 hour(s)

-- EDD Page Configuration

Checkout:                 Valid
Checkout Page:            https://kushview.net/checkout/
Success Page:             https://kushview.net/checkout/purchase-confirmation/
Failure Page:             https://kushview.net/checkout/transaction-failed/
Downloads Slug:           /products

-- EDD Gateway Configuration

Enabled Gateways:         PayPal Standard, Stripe, GoUrl Bitcoin/Altcoin
Default Gateway:          PayPal Standard

-- EDD Tax Configuration

Taxes:                    Enabled
Tax Rate:                 7
Display On Checkout:      Displayed
Prices Include Tax:       No
Country / State Rates:    
                          Country: US, State: IN, Rate: 7

-- Must-Use Plugins

kushview.php: 

-- WordPress Active Plugins

Amazon Web Services: 1.0.5
Contact Form 7: 5.0.1
Contact Form 7 MailChimp Extension: 0.4.50
Easy Digital Downloads: 2.9
Easy Digital Downloads - Amazon S3: 2.3.6
Easy Digital Downloads - Copy Protection: 1.0.2
Easy Digital Downloads - Discounts Pro: 1.4.8
Easy Digital Downloads - External Products: 1.1.0
Easy Digital Downloads - MailChimp: 3.0.5
Easy Digital Downloads - Manual Purchases: 2.0.5
Easy Digital Downloads - PDF Invoices: 2.2.21 (needs update - 2.2.22)
Easy Digital Downloads - Software Licensing: 3.5.23
Easy Digital Downloads - Stripe Payment Gateway: 2.6.13
Easy Digital Downloads - Xero: 1.2.12
Easy Digital Downloads integration for HelpScout: 1.1
EDD Enhanced eCommerce Tracking: 1.0.8.2 (needs update - 1.1.0)
GoUrl Bitcoin Payment Gateway & Paid Downloads & Membership: 1.4.3
GoUrl Easy Digital Downloads (EDD) - Bitcoin Altcoin Payment Gateway: 1.0.2
Kushview: 1.0.0
Post Types Order: 1.9.3.6
Shield Security: 6.6.3
WP Mail SMTP: 1.2.5
WP Offload S3 Lite: 1.3.2
WP Smush: 2.7.8
Yoast SEO: 7.1 (needs update - 7.2)

-- WordPress Inactive Plugins

Advanced Custom Fields PRO: 5.6.10
Easy Digital Downloads - Free Downloads: 2.1.9

-- Webserver Configuration

PHP Version:              5.5.9-1ubuntu4.24
MySQL Version:            5.6.34
Webserver Info:           Apache

-- PHP Configuration

Memory Limit:             256M
Upload Max Size:          10M
Post Max Size:            10M
Upload Max Filesize:      10M
Time Limit:               30
Max Input Vars:           1000
Display Errors:           N/A
PHP Arg Separator:        &

-- PHP Extensions

cURL:                     Supported
fsockopen:                Supported
SOAP Client:              Installed
Suhosin:                  Not Installed

-- Session Configuration

EDD Use Sessions:         Enabled
Session:                  Disabled

### End System Info ###
```

**Comment by SDavisMedia** [comment]
Did you copy the `templates/images` folder over from EDD into your theme? It looks like you did (which of course should not cause a problem).

I'll do that in my test environment shortly and see if that replicates the issue. I can't do it right this second. If you want to check to see if that's related in the meantime, temporarily change the name of the `edd_templates/images` directory in your theme, clear cache, and see if the icons show up properly.

**Comment by SDavisMedia** [comment]
Yea, this is a direct result of having the images from EDD core copied into the theme. I just replicated.

@mfisher31 If you don't actually need the `templates/images/icons` folder moved over into your theme at `edd_templates/images/icons`, the fastest solution would be to remove that folder and let EDD use its own resources. Unless you've uploaded your own custom payment icons into that folder in your theme, there's no reason to have it copied over.

We'll still address the bug and get the fix out in an upcoming release.

**Comment by mfisher31** [comment]
Thank you for having a look.  I do in fact have custom icons.  For now I'll just keep them turned off.  Thank you again for addressing my issue!

**Comment by SDavisMedia** [comment]
@mfisher31 No problem! I think I got it figured out. If you're familiar with git, you're free to test my changes. They're in branch `issue/6477`, the above PR. I've tested and I believe it will not only solve the problem, but also [slightly] improve the output if images are broken.
