### ISSUE TITLE
Add support for a Privacy Policy checkbox

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#6484]
### Explain your enhancement (please be detailed)
We should add support for a separate Privacy Policy checkbox. This checkbox should be allowed to be independent of the Terms of Agreement checkbox.

It should also allow the support of a single checkbox "Terms of Agreement" but also display the content or a Privacy Policy on checkout.

It should support pulling the content of any created Privacy Policy page, which is being added to WordPress core, so that a store owner does not have to keep to copies active. It can simply pull the `page_for_privacy_policy` option, and use `get_post_field( 'post_content'...` to get the information for it.

### Justification or use case
To allow compliance for GDPR

**Comment by SDavisMedia** [comment]
All working well for me now! :+1:
