### ISSUE TITLE
Stripe Payment Updates

### ISSUE THREAD

**Issue by Basilakis** [easydigitaldownloads/easy-digital-downloads#6489]
Hey,

I am sorry but as I do not have access to the Stripe Extension on GitHub, would like to ask:

1. https://stripe.com/docs/stripe-js/elements/quickstart
Can that be integrated and update the stripe payment method, is it possible?

2. Stripe new feature, that allows to create " Custom Plans " to send the price over
https://stripe.com/docs/billing/migrating

will that new API been integrated to take those features further with Stripe?

Thank you all of your really hard work.

**Comment by pippinsplugins** [comment]
@Basilakis both of these are on our todo list for Stripe :)
