### ISSUE TITLE
EDD API Keyappearing on bbPress forum Edit Profile screen 

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#6490]
### Expected behavior

The ability to generate EDD API keys should not be present on the bbPress edit profile screen. Apparently this was removed prior, but has re-appeared for some unknown reasons.

### Actual behavior

As per this customers ticket (https://secure.helpscout.net/conversation/556461455/79926/?folderId=180499), the included screenshot demonstrates the unexpected behaviour.

**Comment by cklosowski** [comment]
I cannot find anywhere in the past that we've actively moved it from the bbPress profile editor, but I found this which was a conflict with the bbPress Profile editor:
https://github.com/easydigitaldownloads/easy-digital-downloads/issues/3578

I don't think we actively removed it at any point, so not sure how they are just now seeing it as no modifications were recently made, my guess is it's been there this whole time. We can do some work around though to make it hidden (with a filter to allow showing it on the front end, in the event someone _is_ using it.)

**Comment by cklosowski** [comment]
Initial thought is just doing something like this in `edd_show_user_api_key_field`:
```
$show_fields = apply_filters( 'edd_show_user_api_key_fields', is_admin(), $user_id );
if ( ! $show_fields ) {
    return;
}
```

**Comment by SDavisMedia** [comment]
All good here. :+1: 

@davidsherlock in the future, please go ahead and describe the problem and replication steps when you open the issue. Use the parts of the issue template where necessary. Not only does it help with clarity, it makes sure we have something to search for later.
