### ISSUE TITLE
Add confirmation alert when clicking "Disconnect User" on customer page

### ISSUE THREAD

**Issue by nosegraze** [easydigitaldownloads/easy-digital-downloads#6495]
Disconnecting an account from the customer seems like kind of a big move, but there's no alert asking you to confirm you really want to do that. I just clicked it accidentally and panicked a little. I was aiming for the user ID number link, which is super close by. I doubt I'm the first to accidentally click `Disconnect User` instead.

**Comment by SDavisMedia** [comment]
Yup. That's a bit too easy.

**Comment by nosegraze** [comment]
Works perfectly - thank you!
