### ISSUE TITLE
Add helper functions for anonymizing customer data

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#6498]
## Enhancement Request
EDD needs some helper functions centered around customer data to facilitate anonymizing the unnecessary data.

### Justification or use case
This is a [GDPR](#6216) issue. While core hasn't finished their tools yet, we should start building our helper functions and making sure things don't break when used, so that when core is ready we have working functions/methods.

**Comment by SDavisMedia** [comment]
This is working great for me so far. Current concern is how WordPress core is going to handle the actual user account. EDD's anonymization works well on `issue/6498` but the customer record is still attached to a WP user. And with that, the user can make a new purchase after the anonymization and that new customer record is attached to the same user account. That indicates that EDD's anonymization worked properly, but there's a data link between the anonymized customer record and the new customer record thanks to the WP user account.

So I believe we'll have to wait a bit and see what WP has in store.

**Comment by cklosowski** [comment]
@SDavisMedia in my latest commit, I unlink the user, no matter what. Since the anonymized customer now has no email or name assocaited with a user, no matter what WP core does, EDD's data will be deleted and disconnected.

**Comment by cklosowski** [comment]
The above simply means that if WP leaves the user account in tact, and we anonymize a customer, if that customer decides to come back and purchase again, using a real email address, it will generate a new customer and be linked to the user that WP core left in place.

If WP core goes with deleting that user, instead of leaving it in place, then we'll also just create our customer, and if need be (settings for user creation/auto register) a new user will be generated and connected to that new customer. It would be like they are a 100% new customer, because in EDD's eyes, they are.

**Comment by SDavisMedia** [comment]
@cklosowski yep, we're saying the same exact thing.
