### ISSUE TITLE
Add email psudo-masking helper function

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#6502]
## Enhancement Request
For some upcoming changes across EDD and it's add-ons, we need a build in way to anonymize an email address, and we can use psudo-masking to make this possible. This masking should take an email like:
`customer@example.org`

and convert it to:
`c******r@e*****e.org`

### Justification or use case
This is to facilitate some changes upcoming in EDD for [GDPR](#6216 )

**Comment by pippinsplugins** [comment]
Functions look good. Noticed just one small typo on the PR (see review).

**Comment by danieliser** [comment]
Just want to confirm, has anyone checked this goes far enough to anonymize the user data? You would still be able to link multiple purchases together for that user. Just not completely sure what the legal requirement is.

**Comment by cklosowski** [comment]
@danieliser The linking of purchases together is fine, so long as you cannot determine _who_ that person is to market/profile them.

This isn't for purchase data though in particular. This is for things like emails being sent and stored in logs. Things like this make it so we don't know the full email but we could still troubleshoot email sending issues as we can get _close_ to being able to know if something is correctly logged.
