### ISSUE TITLE
Add pie chart support to the chart endpoint

### ISSUE THREAD

**Issue by DrewAPicture** [easydigitaldownloads/easy-digital-downloads#6511]
| PR | Tracking | Project |
------ | ------------ | ----------
| ~#6515~ | #6236 | [3DD™: Reporting API Reboot](https://github.com/easydigitaldownloads/easy-digital-downloads/projects/2)

Chart endpoint support was added in #6287, but without pie chart support. Let add it.

**Comment by DrewAPicture** [comment]
Started a WIP PR: #6515

**Comment by pippinsplugins** [comment]
:heart:

**Comment by DrewAPicture** [comment]
#6515 was merged.
