### ISSUE TITLE
Move applying the WP offset out of the EDD\Utils\Date constructor

### ISSUE THREAD

**Issue by DrewAPicture** [easydigitaldownloads/easy-digital-downloads#6513]
The `EDD\Utils\Date` object (extending `Carbon` and therefore `DateTime`) is being introduced in 3.0. Currently, it's automagical in that it assumes whatever date/time being passed in is UTC and needs "conversion" to "WP time". The way this is facilitated is by instantiating the object with the WP timezone then manually applying the offset via passing a `DateInterval` object via `DateTime->add()`.

The main problem with this is that this effectively means that any incoming time with the offset already applied will have it applied twice. This has already come up in one place, which necessitated the adding of an optional `$apply_offset` parameter to the `EDD\Utils\date()` helper, which doesn't really solve the problem, it just reverses the manual `DateInterval` change after the fact.

This issue serves to directly address the problem in `Date` instead of bolting something on in the `EDD\Utils\date()` helper.

Date functionality was originally introduced via #6236, but later moved out to the `release/3.0` branch for visibility by other feature projects.

**Comment by DrewAPicture** [comment]
By virtue of inheritance rules with constructors in PHP, we can't just add the `$apply_offset` method to the constructor as a third optional parameter – the parameters have to match upstream with `Carbon` and `DateTime`. So I'm thinking the best option to accomplish this would be to move applying the offset to a separate method and then instantiate in `EDD\Utils\date()` via a static method that accepts its own arguments. This new method would be considered the "best practice" for instantiating an `EDD\Utils\Date` object.

**Comment by sunnyratilal** [comment]
Closing as @JJJ, @mindctrl and I have done a lot of work over the past few days to fix this.
