### ISSUE TITLE
Add notice for sites on PHP 5.3 and 5.2 about upcoming EOL for support

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#6514]
## Enhancement Request
We need to add a notice to customers running PHP 5.2 and 5.3 before EDD 3.0 releases that contains information about running PHP 5.2 and 5.3. This goes along with #6290.

### Justification or use case
Since EDD 3.0 will drop support for PHP 5.2 and 5.3 in #6290 we need to let people know in advance of this so they can start the conversations with their hosting provider, server admin, or find a new host.

This should coincide with an official blog post on the main EDD blog about the upcoming changes so the user can get more information as to why the changes are coming.

**Comment by JJJ** [comment]
See #6533 for more discussion on how exactly to communicate this to new installations of EDD (and add-ons.)

**Comment by cklosowski** [comment]
going to punt this along for now, until we're ready for the customer level communication. We've already voiced it to developers in our blog post (even by relation to using namespaces) as they mentioned it in the comments: 
https://easydigitaldownloads.com/development/2018/04/13/easy-digital-downloads-3-0-development-update/

**Comment by cklosowski** [comment]
I'm going to get this notice going for the 2.9.23 release, so that we can get the word out.

**Comment by cklosowski** [comment]
As a note, we'll need to update our title here, and make sure that we include the proper new minimums for 3.0

**Comment by cklosowski** [comment]
Here is my initial thought for a notice (in order to show it, I altered my version compare, that is why it says 7.2.x is old):
Collapsed:
![image](https://user-images.githubusercontent.com/1390124/78839584-a2737480-79ad-11ea-86b9-74c31c24c644.png)

Fully Expanded:
![image](https://user-images.githubusercontent.com/1390124/78839549-94255880-79ad-11ea-8a61-a4416f2ee140.png)

Here is the plain text:
```
Your site is running PHP version <php version>, which will not be supported in an upcoming release of Easy Digital Downloads. Learn more about this upcoming change.

We are changing our PHP version support:
In version 3.0 of Easy Digital Downloads, we will be raising the minimum version of PHP that we will support.

Easy Digital Downloads 3.0 will require PHP 5.4 or greater in order to keep your store online and selling. While 5.4 is the minimum version we will be supporting, we would encourage you to update to the most recent version of PHP that your hosting provider offers you.

We have made this decision based off data, in order to affect the least amount of stores as possible, while still gaining improvements in features supported in newer versions of PHP.

For more information about upgrading your version of PHP, WordPress.org has published an article to assist you.
```

**Comment by cklosowski** [comment]
@SDavisMedia @robincornett @LisaCee thoughts on the copy?

**Comment by cklosowski** [comment]
The "published an article" will contain a link to this URL:
https://wordpress.org/support/update-php/

**Comment by robincornett** [comment]
Suggested revision:

```
 Your site is running PHP version <php version>, which will not be supported in an upcoming release of Easy Digital Downloads. Learn more about this upcoming change.

**Easy Digital Downloads 3.0 is a major upgrade which will change our PHP version support:**
Easy Digital Downloads 3.0 will require PHP 5.4 or greater in order to keep your store online and selling. While 5.4 is the minimum version we will be supporting, we encourage you to update to the most recent version of PHP that your hosting provider offers.
 
Based on our user data, this decision affects the fewest number of stores possible, while still gaining improvements in features supported in newer versions of PHP.

Learn more about updating PHP on WordPress.org.
```

Some of the suggested changes are just language; some are to bring the language more in sync with the similar dashboard widget introduced in WordPress 5.1, which reads ([ref](https://github.com/WordPress/wordpress-develop/blob/master/src/wp-admin/includes/dashboard.php#L1722-L1756)):

> 
> WordPress has detected that your site is running on an insecure/outdated _(rgc: word choice depends on detected PHP version)_ version of PHP.
> 
> **What is PHP and how does it affect my site?**
> PHP is the programming language we use to build and maintain WordPress. Newer versions of PHP are both faster and more secure, so updating will have a positive effect on your site&#8217;s performance.
> 
> Button text: Learn more about updating PHP

Note that this is entirely separate from the Site Health widget.

Since this is a preemptive notice which will not prevent users updating to EDD 2.9.x, I think it's worth pushing to 5.6.x, which is the same as WordPress has been recommending since 5.1. Since EDD has already implemented the `Requires PHP` tag set to 5.3, a recommendation of 5.4 only is a lot of work for a very narrow set of users (those still on 5.2 have already been left behind).

**Comment by cklosowski** [comment]
> very narrow set of users

It’s over 10,000 users by current counts, which is not a narrow set. That’s 10,000 stores that, if they choose to update would lose their source of income.

We are already including our supported PHP version in the readme.txt.

One of our values is “Compatibility” over “Deprecation”. We only have one other initiative that would drive the PHP version to be bumped and that’s related to gateway compatibility. Besides that supporting PHP 5.4 takes very little effort from our part, and WordPress core actually only started making the minimum PHP 5.6 with version 5.1, which was posted just a week over 1 year ago. We’re committed to supporting as many stores as possible, and as such are going for WordPress 4.9 and greater (at this time).

Because WordPress 4.9 and 5.0 both support PHP 5.2, the only reason we’re jumping to 5.4 is that less than 1% combined are using PHP 5.2 and 5.3. Our goal is to support as many WordPress installs as possible and at this point we’re committing to a larger breadth of WordPress versions as many still have not updated to 5.0 even.

**Comment by cklosowski** [comment]
I need to have a discussion with @spencerfinnell and @lisag this week to determine what needs to happen here. We have a few things in play that might change the position here and I want to make sure we get them figured out before we commit to messaging.

**Comment by robincornett** [comment]
Food for thought:
- [WooCommerce 4.3 will set 7.2 as minimum PHP recommendation](https://wptavern.com/woocommerce-4-3-beta-available-for-testing)
- [WordPress bumps minimum PHP recommendation to 7.2](https://wptavern.com/wordpress-bumps-minimum-php-recommendation-to-7-2)
