### ISSUE TITLE
edd_checkbox_callback does not allow for setting an input as 'disabled'

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#6518]
## Enhancement Request
Registering a checkbox setting should permit the same types of things that using the EDD HTML Elements class permits like `readonly` and `disabled`.

### Justification or use case
Since edd_checkbox_callback does not actually call the HTML Elements class, none of the options are are used. By being able to pass in disabled and readonly, settings can conditionally be available based on other environmental factors.

For instance, in [Free Downloads](https://github.com/easydigitaldownloads/edd-free-downloads/issues/264), we would like to disable the checkbox to show the privacy policy if the privacy policy page is not defined in the EDD settings. Right now we can change the description telling the user to go set it, but it should be disabled until that privacy policy page is defined.

**Comment by JJJ** [comment]
I've started a bit on this already in 3.0.

There are a bunch of gaps & anomalies in the settings callbacks like this, with regards to attributes like placeholders, description text, etc...

Co-assigned to myself to keep an eye on this later.

**Comment by cklosowski** [comment]
@JJJ I'm just going to punt this for 3.0. It isn't super requested.

**Comment by sunnyratilal** [comment]
Fixed & merged.
