### ISSUE TITLE
GDPR Consent implementation

### ISSUE THREAD

**Issue by aristath** [easydigitaldownloads/easy-digital-downloads#6521]
After reading #6216 there's one thing that was just mentioned in passing but is one of the key elements of GDPR: **asking for consent before storing user-data**.

In [Recital 49](http://www.privacy-regulation.eu/en/recital-49-GDPR.htm) for Article 6, Point [f]:

> “The processing of personal data to the extent strictly necessary and proportionate for the purposes of ensuring network and information security, i.e. the ability of a network or an information system to resist, at a given level of confidence, accidental events or unlawful or malicious actions that compromise the availability, authenticity, integrity and confidentiality of stored or transmitted personal data, and the security of the related services offered by, or accessible via, those networks and systems, […] by providers of electronic communications networks and services and by providers of security technologies and services, constitutes a legitimate interest of the data controller concerned. This could, for example, include preventing unauthorised access to electronic communications networks and malicious code distribution and stopping ‘denial of service’ attacks and damage to computer and electronic communication systems.”

There is lawful basis to store the user IP and other user-data since we're talking about purchases and we have to ensure the security of the transactions etc.

From http://www.privacy-regulation.eu/en/dossier_consent_demo.htm:

> (11) ‘Consent’ of the data subject means any freely given, specific, informed and unambiguous indication of the data subject's wishes by which he or she, by a statement or by a clear affirmative action, signifies agreement to the processing of personal data relating to him or her;

The purchase is a clear affirmative action, BUT **the user should still be informed somehow about what kind of data we get from the payment gateway.**

The only other area I can think if where we store user-data is their profile, but they only add their details there if they wish, so no consent is necessary for that.

**Comment by aristath** [comment]
As for storing site-URLs on licenses (for the EDD-SL plugin), if they add the site-url from the store's pages, they add it themselves so no need for consent there.
However this is not the case when validating the license from the client site itself. In that case however, I don't think that an EDD site has to do anything... The consent form should be on the plugin/theme/product license-submission form.

**Comment by cklosowski** [comment]
@aristath In 2.9.1 #6484 we added a 'Privacy Policy' checkbox that can be required and link off to the privacy policy, which under GDPR, should contain all of this relevant information.

That would suite this need would it not?

**Comment by aristath** [comment]
Sorry it took me almost a week to get back to you on this one but lots of things going on with GDPR so I'm catching up now. 👍 

I hadn't seen that checkbox, yes that will do.
Thank you! Closing this thread.

**Comment by cklosowski** [comment]
No worries @aristath! Thanks for your feedback.
