### ISSUE TITLE
Searching payments by discount codes no longer works

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#6522]
## Bug Report

Searching payment history for payments with a specific discount code doesn't work.

### Expected behavior

Entering `discount: CODE` in the search field should return a list of payments that used that discount code.

### Actual behavior

No payment records are returned.

### Steps to reproduce the behavior
1. Enable sequential order numbers
2. Make a discount code
3. Use the discount on a purchase
4. Try to search for payments with that discount

**Comment by pippinsplugins** [comment]
Bug was introduced with https://github.com/easydigitaldownloads/easy-digital-downloads/commit/a493b3c49b9227ae3b1eb6aec51fedabc8d05c9b for https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6178

**Comment by pippinsplugins** [comment]
PR ready for testing.

**Comment by SDavisMedia** [comment]
Related: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6471

There are some considerations mentioned in that issue and [its corresponding PR](https://github.com/easydigitaldownloads/easy-digital-downloads/pull/6472).

**Comment by SDavisMedia** [comment]
@cklosowski based on a convo with Pippin, we're going to go with #6472 as the fix here if it's approved. If you can look into that PR again, we may be able to close this issue and PR.

**Comment by SDavisMedia** [comment]
Keep in mind that means that the PR is good simply for fixing the discount (and similar) search functionality.

[My additional issue](https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6471#issuecomment-383165099) that led to the 3DD discussion could perhaps be broken off into a new issue.
