### ISSUE TITLE
Add Privacy Policy placeholder for the WP Core Privacy Policy builder

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#6530]
### Explain your enhancement (please be detailed)
EDD needs to have a privacy policy placeholder for the Privacy Policy Page builder that core is working on.

### Justification or use case
GDPR

**Comment by cklosowski** [comment]
![screen shot 2018-04-27 at 12 36 31 pm](https://user-images.githubusercontent.com/1390124/39381835-56d6ce3a-4a18-11e8-9aea-7471e3b561e4.png)

A work in progress screenshot. I have a bit of work to do on building out the 'additional' section so that it can be extended by EDD Add-ons to add any necessary data.

**Comment by pippinsplugins** [comment]
@cklosowski could you please provide a reference for the wp_add_privacy_policy_content() function? I missed seeing that being introduced / proposed in core and my google fu is weak today.

**Comment by SDavisMedia** [comment]
Yes please. ^^^

**Comment by dennyf** [comment]
You can find the function defined here:
https://core.trac.wordpress.org/browser/trunk/src/wp-admin/includes/plugin.php#L2037
It takes only plugin name and policy text as parameters.

**Comment by cklosowski** [comment]
@pippinsplugins @SDavisMedia was added as part of this Trac ticket: https://core.trac.wordpress.org/ticket/43620

And part of this revision: https://core.trac.wordpress.org/browser/trunk/src/wp-admin/includes/plugin.php?rev=42980

**Comment by SDavisMedia** [comment]
Tested and working well for me. Tweaked and commented on the PR. All good. :+1:

**Comment by mintplugins** [comment]
Looks good here!
