### ISSUE TITLE
tag noindex

### ISSUE THREAD

**Issue by uhanna** [easydigitaldownloads/easy-digital-downloads#6539]
On a number of meta tag noindex pages contract.
view-source:https://keyluck.ir/checkout/
What should you do to fix this?

**Comment by pippinsplugins** [comment]
Hi there!

Please go ahead and open a support ticket through our support portal: https://easydigitaldownloads.com/support

we use GitHub for development tracking only.

Note: the noindex on checkout and several other pages is intentional and should not be removed without good reason.
