### ISSUE TITLE
How to echo meta_key in easy digital downloads receipt (Purchase Confirmation page)

### ISSUE THREAD

**Issue by Mor-raj** [easydigitaldownloads/easy-digital-downloads#6541]
I was used Easy Digital Downloads plugin for selling services (via "downloads as services" addon). I want to display several custom field of every download items in Easy Digital Downloads receipt(Purchase Confirmation page) by their meta_key.

I was tried following codes, but it seems I need to worked on sessions... Please guide me.

Thanks
Regard

`<?php echo get_post_meta(get_the_ID(), 'seat_number', true); ?>`

and

`<?php echo get_post_meta( $payment->ID, 'seat_number', true ); ?>`

and

`<?php echo strip_tags( esc_html( get_post_meta( absint( $payment->ID ), 'seat_number', true ) ) ); ?>`

**Comment by SDavisMedia** [comment]
Hi @Mor-raj. We use GitHub for development tracking only. If you are in need of support, please open a support ticket here: https://easydigitaldownloads.com/support/

**Comment by Mor-raj** [comment]
Hi @SDavisMedia 
You're right. Excuse me...

Regard
