### ISSUE TITLE
WP GDPR: Add customer billing data to GDPR Data Export

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#6543]
### Explain your enhancement (please be detailed)
We need to build support for all order billing data to be in the WP Core data exporter

### Justification or use case
GDPR

**Comment by cklosowski** [comment]
This is ready for some testing...to use it you must:
1) Be on the latest nightly of WordPress core
2) Go to `Tools > Export Personal Data`
3) Add a data export request using the form 
![](https://cl.ly/2r0N1h451I1Y/Image%202018-05-07%20at%202.53.57%20PM.png)
4) Once submitted, you should have an email with a link to 'Confirm Action'. If using Local or you'll find this in your MailHog:
![](https://cl.ly/1l3D1j1S3f0g/Image%202018-05-07%20at%202.54.48%20PM.png)
5) Once confirmed, you can go back to (or refresh) the Export Data list, and click the 'action' link to view the data...once you have clicked it, it will add `again` to the end of the string...just fyi:
![](https://cl.ly/2N3J1S0N2y3F/Image%202018-05-07%20at%202.55.52%20PM.png)

**Comment by mintplugins** [comment]
Looks good @cklosowski! Do we plan to add this stuff as well?

- Payment history
- Download logs
- When they agreed to privacy policies

**Comment by mintplugins** [comment]
Oh - you have order history - my bad!

**Comment by cklosowski** [comment]
@mintplugins This one contains some of the payment information that's necessary as `billing information`. Download logs is in #6499 and the logging of the terms and privacy already has a Pull Request available and is being done in #6432.

For a full list of GDPR related issues, see https://github.com/orgs/easydigitaldownloads/projects/1

**Comment by cklosowski** [comment]
I'm going to do some more work on this. I think we should add more data to the output, not just billing information but the items purchased, completed date, and maybe the order total? This way there are less questions from the users, and we already have the data queued up anyway as we're looping over it. I'll work up some changes today.

**Comment by cklosowski** [comment]
@easydigitaldownloads/core-team This is the new output of orders:
![](https://cl.ly/2a302X153j1C/Image%202018-05-09%20at%203.58.04%20PM.png)

If pending, notice that the `completed date` is left empty. If there are more than one items purchased they are comma separated items, and they always include the quantity.
