### ISSUE TITLE
Changing Cart Quantity Doesn't Update Payment Gateway Price

### ISSUE THREAD

**Issue by dgoldak** [easydigitaldownloads/Easy-Digital-Downloads#6547]
## Bug Report
Customer found that when using Stripe checkout modal, when the quantity is updated, Stripe does not reflect the new price.

The reason I'm opening this here and not under the Stripe extension is that I suspect this behavior applies if PayPal Express modal is used. Also, I found that Discounts Pro prevents this behavior when changing the quantity.

I'm wondering if the refresh that occurs with Discounts Pro should be applied to EDD's core instead of individual plugins.

### Expected behavior
When the cart quantity is updated the new price should be reflected in the payment gateway modal.

### Actual behavior
When the cart quantity is updated, payment gateway modal does not reflect the new price.

![screen_shot_2018-05-02_at_12_07_14_pm](https://user-images.githubusercontent.com/30910807/39761912-f1f28416-529e-11e8-974d-60f7cbc0d156.png)

![screen_shot_2018-05-02_at_12_07_36_pm](https://user-images.githubusercontent.com/30910807/39761924-f5cef02e-529e-11e8-90f1-8cb586938c4a.png)

### Steps to reproduce the behavior
1) Enable cart quantities & Stripe modal
2) Add item to cart
3) Checkout to trigger Stripe modal
4) Close modal and update quantity of an item
5) Cart total will update to the correct price
6) Checkout to trigger Stripe modal, modal should show wrong price

### Information (if a specific version is affected):
PHP Version: 7.0

EDD Version (or branch): Master - 2.9.1
Stripe: 2.6.13

WordPress Version: 4.9.5

**Comment by SDavisMedia** [comment]
Opened the Stripe issue for you, @dgoldak: https://github.com/easydigitaldownloads/edd-stripe/issues/305

**Comment by SDavisMedia** [comment]
Oops, Daniel, I just saw the part about why you opened the issue here.

@pippinsplugins can you confirm that you read that part and still believe it is a Stripe issue?

**Comment by pippinsplugins** [comment]
@SDavisMedia yes definitely still Stripe. The amount shown in the modal is controlled by the JS in the Stripe gateway.
