### ISSUE TITLE
Improve File download Log accuracy and remove PII from log meta

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#6548]
### Explain your enhancement (please be detailed)
Currently the file download log uses a meta key of `_edd_log_user_info` to store information like 
`a:3:{s:5:"email";s:15:"admin@local.dev";s:2:"id";i:1;s:4:"name";s:15:"Chris Klosowski";}`. This information is pulled from the customer associated with the purchase record.

While used to do some download count checks, we can be far more accurate, as well as remove PII from these log entry meta values by simply storing the customer ID. Since a customer can have more than one email address, and also set their primary email address from their profile editor, this could end up being in accurate when we do a download count using this function:
`edd_count_file_downloads_of_user( $customer_obj->email );`

My proposal will be to do the following:
1) Remove the `_edd_log_user_info` for file download logs _only_, with a migration routine.
2) Add in a new meta entry for file download logs of `_edd_log_customer_id`, with the above migration routine.
3) Add a new function of `edd_count_file_downloads_of_customer` which accepts a customer Id or email (since the customer object can find a customer with any email address associated with the customer)
4) Change any calls to get this count to the new method.

### Justification or use case
I realized this was possibly an issue while researching the implementation of #6499. This data isn't necessary and can be looked up elsewhere.

**Comment by SDavisMedia** [comment]
Ran the migration with about 25,000 logs and everything looks to have updated correctly. If there's some real-world functionality you want me to test, just let me know. Otherwise, this looks neato to me. 👍

**Comment by pippinsplugins** [comment]
@SDavisMedia could you please test on the EDD staging site?

**Comment by cklosowski** [comment]
@pippinsplugins yeah I'll get it on the staging site prior to merging
