### ISSUE TITLE
Reports API: fatal error on Windows when displaying table view

### ISSUE THREAD

**Issue by nosegraze** [easydigitaldownloads/easy-digital-downloads#6549]
### Expected behavior
See reports table rendered.

### Actual behavior
There's a fatal error preventing the whole report from loading.
```
Fatal error: Uncaught Error: Class 'EDD_Gateawy_Reports_Table' not found
```

### Steps to reproduce the behavior
1) Install example report plugin: https://gist.github.com/DrewAPicture/69acc0a74af184f11443687802ac89a4
2) Be on Windows. :P 
3) Visit report page/tab
4) See fatal error about `EDD_Gateawy_Reports_Table` class table not existing.

### Information (if a specific version is affected):
Windows local environment.

This issue is due to the usage of `validate_file()` here in `EDD\Reports\Data\Table_Endpoint`:

```php
	private function set_class_file( $file ) {
		if ( 0 === validate_file( $file ) ) {
			$this->class_file = $file;
		}
	}
```

In Windows this function returns `2` - not `0`. This results in the class file never getting loaded, but the class gets used later on.

**Comment by JJJ** [comment]
Someone else noticed this typo a few days ago.

I have a plan to address this, so assigning to me and I'll work up a PR.

**Comment by JJJ** [comment]
Fixed via #6550, so closing here.

Thanks @nosegraze for testing & reporting this here. 👍

**Comment by nosegraze** [comment]
This issue isn't related to the typo. It's related to the class file not getting loaded at all due to `validate_file()` returning `2` instead of `0` in a Windows environment. (the class name is irrelevant).

**Comment by nosegraze** [comment]
I'm afraid not. `wp_normalize_path()` just enforced forward slashes, but `validate_file()` returns `2` if `:` is found at the start of the file path and that part didn't ch ange.

Before `wp_normalize_path()` : 

```
C:\wamp\www\edd\wp-content\plugins\easy-digital-downloads/includes/admin/reporting/class-gateways-reports-table.php
```

After `wp_normalize_path()` : 

```
C:/wamp/www/edd/wp-content/plugins/easy-digital-downloads/includes/admin/reporting/class-gateways-reports-table.php
```

This is in `validate_file()` : 

```php
// Absolute Windows drive paths are not allowed:
if (':' == substr( $file, 1, 1 ) )
	return 2;
```

**Comment by sunnyratilal** [comment]
@misulicus Tested a patch for me which seems to work. We need to change the validation logic otherwise files will not load on Windows due to way file paths work.

I suggested we change the conditional on line 160 to:
```php
if ( false === strpos( $file, '..' ) && false === strpos( $file, './' ) ) {
```

And we alleviate the call to `validate_file()` entirely.

@JJJ @DrewAPicture Thoughts?

**Comment by sunnyratilal** [comment]
Automattic have done something similar too: https://github.com/Automattic/amp-wp/issues/255

**Comment by sunnyratilal** [comment]
Fix merged.
