### ISSUE TITLE
Email address that contains a + will not remove via [edd_profile_editor]

### ISSUE THREAD

**Issue by dgoldak** [easydigitaldownloads/easy-digital-downloads#6553]
## Bug Report
Email address that contains a + will not remove via [edd_profile_editor]. 
Example: hello+1@mydomain.com cannot be removed, while hello1@mydomain.com CAN be removed.)

### Expected behavior
When you click remove, to remove an email address containing a +, it should successfully remove that email.

### Actual behavior
When clicking remove for an email that contains a + (hello+1@mydomain.com), page refreshes but email does not remove.

### Steps to reproduce the behavior
Note, This can be tested from the admin account
1) Go to Downloads > Customers. Click on a customer account (easier to test using the customer with the same email address as your admin account)
2) Add a standard email address: test@test.com
3) Add an email address containing a +: hello+1@mydomain.com
4) Go to page with [edd_profile_editor] shortcode.
5) Remove the email address containing a +
6) Remove the email address w/out a +.
7) Both emails should successfully be removed.

### Information (if a specific version is affected):
PHP Version: 7.0

EDD Version (or branch): 2.9.1

WordPress Version: 4.9.5

**Comment by SDavisMedia** [comment]
This is ready for a quick test.

**Comment by dgoldak** [comment]
@SDavisMedia tested`issue/6553` and confirmed email with "+" was removed.
