### ISSUE TITLE
Updating Payment Status causes incorrect Download Total when price is inclusive of tax

### ISSUE THREAD

**Issue by dgoldak** [easydigitaldownloads/easy-digital-downloads#6563]
## Bug Report
When status of payment is updated for a price that is inclusive of tax, "Download Total" changes from:
![screen shot 2018-05-16 at 9 11 40 am](https://user-images.githubusercontent.com/30910807/40122360-3ad1b616-58e9-11e8-9f3b-8781339e7a30.png)

To:
![screen shot 2018-05-16 at 9 11 59 am](https://user-images.githubusercontent.com/30910807/40122368-3f60caa0-58e9-11e8-8fad-c66a9e27e382.png)

Note, Total Price is not affected:
![screen shot 2018-05-15 at 6 27 24 pm](https://user-images.githubusercontent.com/30910807/40122444-74d973da-58e9-11e8-9b99-8e9609c08664.png)

### Expected behavior
When updating a payment status, "Download Total" should not change (or recalculate and add tax amount).

### Actual behavior
When updating the payment status, "Download Total" recalculates "Download Total" and adds the tax to the price instead of keeping the price the same.

### Steps to reproduce the behavior
1)  Enable a tax rate and set prices inclusive of tax.
2) Test a purchase.
3) Update payment status and observe "Download Total"
Note, this was discovered using Check Payment gateway since the store owners has to manually update the status. But it appears to be unrelated to the gateway, any status changes triggers the price change.

### Information (if a specific version is affected):
PHP Version: 5.6 and 7.0

EDD Version (or branch): 2.9.1

WordPress Version: 4.9.5

Any other relevant information:
Reported by customer: https://secure.helpscout.net/conversation/578806700/81976?folderId=1847242

**Comment by SDavisMedia** [comment]
Definitely a bug. It doesn't depend on a status change. Simply clicking the **Save Payment** button without any changes to the payment record will display the behavior.

This appears to affect reports. I can't tell how severe it is, though. 👎

**Comment by cklosowski** [comment]
Ok @SDavisMedia and @dgoldak I have this working, good news is simply saving a 'broken' payment fixes it.

On a further note, I'm going to do some extra work here, that prevents un-modified items from even entering a modification pattern.

Currently we iterate over each item in the download list, even if it doesn't have any modifications. I'm going to update it so that we don't even try and process a row if no changes were made to it's columns, to help prevent issues like this in the future.

**Comment by cklosowski** [comment]
Actually I'm going to hold off on the 2nd part of that statement. With 3.0 coming, there is a whole new concept of view order details that might make this a moot point and it doesn't really cause that many issues.

**Comment by SDavisMedia** [comment]
@cklosowski replicated again and it appears to be working correctly when trying to replicate on `issue/6563`. But I'm not seeing it fix a payment record that experienced the problem on `master`. Is that part of the code to come or should that be working now?

**Comment by cklosowski** [comment]
@SDavisMedia it should have fixed old ones. I'll try again and make sure I stated that correctly.

**Comment by cklosowski** [comment]
@SDavisMedia ah, sorry incorrect statement, I must have gotten confused in my testing, it _does not_ correct items that were hit by this bug. I'll _try_ to see if I can correct them, but no promises.

**Comment by cklosowski** [comment]
@SDavisMedia ready for another test, of an item that previously had gotten incorrectly modifid.

**Comment by SDavisMedia** [comment]
@cklosowski Replicated again on `master`. Confirmed that switching to `issue/6563` and re-saving an affected payment record correctly updates the total. Also confirmed again that the original bug cannot be replicated on `issue/6563`. 👍
