### ISSUE TITLE
[download] shortcode, orderby "random" breaks pagination

### ISSUE THREAD

**Issue by bryan-farris** [easydigitaldownloads/easy-digital-downloads#6564]
### Expected behavior
When setting the "orderby" parameter on the download shortcode to random, the list of downloads should be in random order and display pagination. 

### Actual behavior
When I set the "orderby" parameter of the download shortcode to random, pagination does not display. Pagination does display with the other parameters (id, price, post_date, title). 

### Steps to reproduce the behavior
1) Add the download shortcode to a page or template file with the "orderby" parameter set to "random" and the "number" parameter set to a value that will trigger pagination (if needed). 
`[downloads orderby="price" number="10" ]`
2) See that the pagination does not display.
3) Change the "orderby" parameter to "price" and see that the pagination does display.

### Information (if a specific version is affected):
PHP Version:  7.1.0

EDD Version (or branch): 2.9.1
 
WordPress Version: 4.9.5

Any other relevant information: We offer users an option to "toggle" the random orderby parameter on their downloads list within our theme's options panel. The random parameter was working properly when we first added that option. This issue was brought to our attention this week by a user who was experiencing this on their own site. I was able to recreate this on my own installation both through the theme options settings and through a manual addition of the shortcode to a theme file.

**Comment by spencerfinnell** [comment]
This was removed in https://github.com/easydigitaldownloads/easy-digital-downloads/pull/4550 to prevent duplicate results from showing as you page through. 

See: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/3600

**Comment by bryan-farris** [comment]
Thanks @spencerfinnell, was looking through the issues list to see if this had already been noted. Apparently I missed that! You can close this.

**Comment by SDavisMedia** [comment]
Thanks, @spencerfinnell. 

Sorry about that, @bryan-farris. I've added it to our [downloads] shortcode doc so it's more obvious. :+1:

**Comment by bryan-farris** [comment]
Thanks @SDavisMedia!
