### ISSUE TITLE
Make Privacy Agreement page use the WP core Privacy Policy page ID if it is set

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#6569]
## Enhancement Request
WP Core released a site wide option called `wp_page_for_privacy_policy` where people can identify the page they use for their Privacy Policy. If that has been chosen, we could automatically make it use that for the Privacy Policy link in the EDD settings under "Settings" > "Misc" > "Terms and Conditions" > "Privacy Agreement Page". 

### Justification or use case
Makes the Privacy Policy page experience more uniform and less prone to mistakes. Also, one less thing for the user to make a decision about.

**Comment by SDavisMedia** [comment]
Tested and working well. Left a comment on the PR. :+1:

**Comment by SDavisMedia** [comment]
I went ahead and pushed up my suggested tweaks.
