### ISSUE TITLE
Allow reordering of Gateways and Payment Icons

### ISSUE THREAD

**Issue by JJJ** [easydigitaldownloads/easy-digital-downloads#6574]
I heard from @kerijacoby on Friday that the occasional support request comes in from folks who would like the ability to set an order on their payment gateways and icons.

I mocked up the admin UI quickly, and (excuse the graininess) it looks like...

![order](https://user-images.githubusercontent.com/88951/40275951-501ddc66-5bc3-11e8-9062-4eef4521b596.gif)

These would later be ordered on checkout pages, or anywhere these functions are used.

I'll create a PR based on the `release/3.0` branch, for easy merging if/once blessed.

**Comment by pippinsplugins** [comment]
@JJJ this is looking _great_! A lot of people have wanted this for a long time.

The admin sorting looks to work properly but I'm not seeing the order reflected on the checkout screen.

**Comment by pippinsplugins** [comment]
Looks like the order changes sometimes but not always. I moved gateways around and saw the order reflected on checkout once or twice but it's not always reflecting the order I have saved.

Settings: 
![image](https://user-images.githubusercontent.com/1034109/40280218-be484abc-5c15-11e8-95f4-61848a060d9e.png)

Checkout:
![image](https://user-images.githubusercontent.com/1034109/40280222-c37ef328-5c15-11e8-977a-1cea2450e9a6.png)

**Comment by JJJ** [comment]
Might be cache related, or maybe a filter priority problem with add-ons. Will test further.

**Comment by JJJ** [comment]
Got theme-side output working. Pushed & merged fixes to the `issue/6574` branch (along with an upwards merge from `release/3.0` to play catch-up.

cc @pippinsplugins

**Comment by JJJ** [comment]
A final thought I had while working on this, is that it's now possible to remove the "default gateway" setting, along with some of the confusion around enabling & disabling them.

The only reason _to_ keep the setting, is if for some reason, someone wanted the default gateway to _not_ also be the first one in the list. That seems unlikely to me, but it's possible to do now.

**Comment by pippinsplugins** [comment]
@JJJ order looks to be working now.

I did notice, however, that the order fails to work when no default gateway is set.

For now let's leave the default gateway option as is.

**Comment by JJJ** [comment]
I think it's working, but when no default gateway is set, the "sort" flag has nothing to re-do.

I'll test with some add-ons. Could also be an action-order issue, if there's anything clever happening with action orders & priorities.

**Comment by JJJ** [comment]
Merged, so let's close this.

Confirmed that both gateways and icons are working OK for me with vanilla EDD, but I'll keep an eye out for bugs with add-ons or other filters.
