### ISSUE TITLE
Add in customer deletion case into data anonymization requests

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#6582]
### Explain your enhancement (please be detailed)
When a customer requests to be anonymized/deleted, after all actions are taken for the customer and the payments, we should also delete the customer if no more payments exist.

### Justification or use case
If a customer only has payments that the store owner has set to `delete` when the Privacy Eraser/Anonymizer tools run, and no more payments exist for that customer, we should just delete the customer. There is no reason to keep that record around if no payments exist any longer.

**Comment by cklosowski** [comment]
This should do it. To test, you need a customer, with only payments that will have the `delete` action taken on them.

Once all of them are deleted, the customer is checked again, and deleted.
<img width="1227" alt="screen shot 2018-05-21 at 9 42 30 pm" src="https://user-images.githubusercontent.com/1390124/40342501-e38cb9f4-5d3f-11e8-9057-92d325ce82f9.png">

**Comment by SDavisMedia** [comment]
In tests where all of a customer's data can't be deleted, the customer remains (just wanted to check and make sure that didn't break). 

<img width="680" alt="screenshot 2018-05-22 09 42 45" src="https://user-images.githubusercontent.com/2359131/40376941-8075bdc4-5da4-11e8-9a9c-86322980562b.png">

In tests where all payments for a customer are deleted, so is the customer.

<img width="620" alt="screenshot 2018-05-22 09 43 28" src="https://user-images.githubusercontent.com/2359131/40376969-98869082-5da4-11e8-8014-42334c9061e1.png">

All is working well for me. 👍
