### ISSUE TITLE
EDD Mailster Integration 

### ISSUE THREAD

**Issue by Stiofan** [easydigitaldownloads/easy-digital-downloads#6591]
I built a simple EDD - Mailster integration and forked it over here https://github.com/easydigitaldownloads/edd-mailster

Feel free to use it anyway you want, if you want to sell or give it away feel free, do with it as you please.
I'm just trying to give back to EDD a bit, if you want me to add some backend options i can, or if you are not interested just let me know and i'll release it on wp.org.

Thanks,

Stiofan

**Comment by pippinsplugins** [comment]
Thank you for building that!

We would love to see you release it on WordPress.org. You built it so it should be credited to you :)
