### ISSUE TITLE
Privacy Policy checkbox shown even when disabled

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#6595]
## Bug Report
Agree to privacy policy checkbox is shown even when setting is disabled.

### Expected behavior
When the option to show the checkbox is disabled, the box should not show.

### Actual behavior
It shows even when disabled in settings.

**Comment by pippinsplugins** [comment]
This is happening because the conditional that checks `show_agree_to_privacy_policy_on_checkout` is not wrapped around the checkbox. The checkbox output comes after the `endif`.

**Comment by pippinsplugins** [comment]
Might be a false alarm. Reported here https://secure.helpscout.net/conversation/588012245/82924?folderId=180499

**Comment by pippinsplugins** [comment]
Second similar report https://secure.helpscout.net/conversation/588203311/82953?folderId=180499

**Comment by flowdee** [comment]
I tested another site with the following result:

The issue only occurs when you activated the checkbox the first time. After updating EDD to the latest version, the problem does not occur. Only after I use the new function for the first time, it occurs again.

**Comment by mintplugins** [comment]
@flowdee Yep we are working on it- thanks
