### ISSUE TITLE
Privacy Policy checkout error when Privacy Policy isn't enabled

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#6596]
## Bug Report

Customers receive checkout error for not agreeing to Privacy Policy, even when Privacy Policy is disabled.

### Expected behavior
If Privacy Policy is disabled, it should not be required at checkout.

### Actual behavior
Privacy Policy is required at checkout no matter what, regardless of its settings or any other settings (like Agree to Terms, which it has had conflicts with in the past).

### Steps to reproduce the behavior
1) Disable the Privacy Policy (all settings).
2. Attempt to complete checkout.

### Information (if a specific version is affected):
PHP Version: N/A

EDD Version (or branch): 2.9.2

WordPress Version: 4.9.6

**Comment by SDavisMedia** [comment]
Appears to have been introduced here: https://github.com/easydigitaldownloads/easy-digital-downloads/commit/342aa810880271d4340a12dacaed851137bb8ae1#diff-c92bee519791ea4aff27d8facc099a0b

Those changes were put in place when it was reported (by me) that privacy policy toggle link was displaying on checkout even when **Show the Privacy Policy on checkout** was disabled.

**Comment by cklosowski** [comment]
@SDavisMedia kind of, it's actually in the process purchase logic, that needs to follow the same logic.

**Comment by mintplugins** [comment]
Combos to test:

Privacy Options - With no PP page selected in core
- 1st checkbox only
- 2nd checkbox only
- Both Checkboxes
Privacy Options - With PP page selected in core
- 1st checkbox only
- 2nd checkbox only
- Both Checkboxes

- Terms disabled

**Comment by pippinsplugins** [comment]
All combinations are working for me.

**Comment by mintplugins** [comment]
All scenarios look good - green light from me!
