### ISSUE TITLE
Chosen delay when typing

### ISSUE THREAD

**Issue by JJJ** [easydigitaldownloads/easy-digital-downloads#6606]
When typing inside of any Chosen input search field, there's a weird delay where the text jumps around in between results appearing.

I've fixed it, along with a bunch of smaller Chosen related JavaScript issues, so I'm creating this issue to immediately create an issue branch and PR to merge into `release/3.0`.

Related to #2758, #4662. We haven't switched to Select2 yet, and may never, so let's make sure Chosen works great.

**Comment by pippinsplugins** [comment]
This is _lovely_.
