### ISSUE TITLE
Option to not store customer IP address

### ISSUE THREAD

**Issue by arturi** [easydigitaldownloads/easy-digital-downloads#6607]
## Enhancement Request

Thank you for EDD! It’s awesome.

I would like to have an option to *not* store customer’s IP address. Because that’s not something I need/use in a particular store, and see no justifiable explanation for storing the IP, especially with GDPR.

Maybe a hook exists I could already use? Looked through docs, code, and EDD GDPR issues — just found that it’s ok to store, since it is needed for the service.

Thanks!

**Comment by cklosowski** [comment]
@arturi Currently a filter `edd_get_ip` exists where you could change all IPs to something that is not identifiable. The EDD core GDPR tools anonymizes these by removing `/32` (or last octet of data), so for example `192.168.1.200` becomes `192.168.1.0`. This is enough to anonymize the user yet still allow you to get a general location at the city level, allowing you to handle any possible tax issues necessary.

Using the filter above you could simply always set the `/32` to `0` for now. We can look at just always logging anonymized IPs, however that would cause some issues with extensions like 'Fraud Monitor' so we'll have to keep that in mind when allowing this setting to be used and to what effect.

**Comment by chriscct7** [comment]
Bare in mind, their IP address would be stored by 99.999999% of servers in their access logs. I think we should support the ability to anonymize individual ip addresses after the fact, to avoid breaking valid and existing current use cases.

**Comment by arturi** [comment]
Thank you!
