### ISSUE TITLE
Payment history status filters don't work within searches

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/easy-digital-downloads#6628]
### Expected behavior
When searching payments, filtering payments by status should be possible.

### Actual behavior
If you try to filter the status (for example, Completed) in search results, the filters don't work and all results still show.

Screenshot:
![image](https://user-images.githubusercontent.com/1254870/40856637-9314eafe-65a6-11e8-8ced-fa4517de6bd8.png)

### Steps to reproduce the behavior
1) Search payments, for example: `discount: abc`
2) See list of payments that match your search
3) Try filtering by a status

### Information (if a specific version is affected):
EDD Version (or branch): 2.9.3

WordPress Version: 4.9.6

**Comment by sunnyratilal** [comment]
Fixed and merged.
