### ISSUE TITLE
Hour and minute select drop downs too skinny

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#6629]
The drop down field when selecting the hour and minute for discount start and expiration is too skinny:
![image](https://user-images.githubusercontent.com/1034109/40869615-ea2803c0-65e3-11e8-8456-f225375804f0.png)

**Comment by sunnyratilal** [comment]
Fixed by @JJJ and pushed to `release/3.0`.
