### ISSUE TITLE
Incorrect "No notes." message shown after deleting a note

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#6630]
If you add two notes to a discount code and then remove one of them, an improper `No notes` message will be shown:
![image](https://user-images.githubusercontent.com/1034109/40869632-281eb9d0-65e4-11e8-9dfc-e906a5a8661e.png)
Refreshing the screen shows the notes properly without the message so it's only an issue in the JS processing.

**Comment by pippinsplugins** [comment]
This happens on orders too:
![image](https://user-images.githubusercontent.com/1034109/40869816-3b81dedc-65e7-11e8-9f3e-39a78a72255d.png)

**Comment by sunnyratilal** [comment]
Tested and merged.
