### ISSUE TITLE
Delete Payment links no longer work

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#6633]
The `Delete Payment` links on the Orders list table triggers a page reload but nothing is removed from the database.

**Comment by pippinsplugins** [comment]
The `Delete Order` from `View Order Details` also fails.

**Comment by sunnyratilal** [comment]
Fixed by @JJJ bfe14e343a64ecddf5e73dee25f3670cb1643d71

**Comment by sunnyratilal** [comment]
Unit tests have been added in #4576.
