### ISSUE TITLE
3.0 System Info textarea text color

### ISSUE THREAD

**Issue by misulicus** [easydigitaldownloads/easy-digital-downloads#6636]
You can't see the textarea contents unless you click inside.
Missing CSS perhaps

**Comment by mindctrl** [comment]
I see this without clicking inside the area.

![image](https://user-images.githubusercontent.com/1254870/40989914-451599f6-68bd-11e8-931a-4b807c7dc933.png)

**Comment by misulicus** [comment]
Its fixed now. I believe last commits last night might have fixed this. Closing.
