### ISSUE TITLE
UI/UX Improvements

### ISSUE THREAD

**Issue by sunnyratilal** [easydigitaldownloads/easy-digital-downloads#6642]
@JJJ has done a whole load of UI/UX improvements for 3.0.

This issue serves as a tracking issue for all the commits making it easier for us when it comes to writing the changelog.

**Comment by sunnyratilal** [comment]
In commit f27945b9eb0302ea02dffa4f9f353018878073f0

- Remove references to "ID" for customers & order.
- Allow order numbers to be searched and sorted.
- Use "Number" for orders instead.

In commit 5ff14454cb83ade0e23ff7a03ce81e172737b58e

- Introduce bulk actions for customers.

In commit bec275ce7422058267921925b868989f14bc0e0e

- Improve `View Order Details` page styling.

In commit 8b073a719fa321159af05319cd93afc3cfcbabfc

- Introduce top-level admin-bar menu to show `Store Status`.

In commit 986b2960fb18f094389b94105ab6965f4a5facd9:

- Split some settings into more logical sections & parts.

**Comment by sunnyratilal** [comment]
@JJJ In testing, @spencerfinnell, found that fixed widths on the Order Details page will cause an issue with translations.  We did try fixed widths back in #2518 but it didn't work, unfortunately.


It causes an issue with Transaction ID too.

![image](https://user-images.githubusercontent.com/1525554/41315470-79a4541c-6e87-11e8-8824-d181a27c8bf6.png)

**Comment by spencerfinnell** [comment]
Few other quick things:

- On the Orders table it would be nice if the "Number" column link was set to `display: block` to make the full row clickable -- especially helpful on mobile. https://cloudup.com/ckbNv-rXWcM
- Use `readonly` vs `disabled` in https://github.com/easydigitaldownloads/easy-digital-downloads/commit/bec275ce7422058267921925b868989f14bc0e0e#diff-ae5d42d35edee09a75b937efb622d946R300 to make selection easier.
- 10px on the title action buttons seems very small. Letting them inherit the 11px styles from the base CSS (and moving it up 1 more px) makes things much clearer in my opinion.

I know it's all a work in progress just wanted to jot these down. Looking awesome!

**Comment by JJJ** [comment]
>On the Orders table it would be nice if the "Number" column link was set to display: block to make the full row clickable -- especially helpful on mobile. https://cloudup.com/ckbNv-rXWcM

This one is made difficult because of "states". WordPress shows them in situations where some specific criteria makes sense to show to users in a list-table row, and I've implemented them into EDD's columns as well.

Specifically right now to Orders, we use states to denote non-complete statuses in other views. We can add other attributes here anytime.

<img width="653" alt="screen shot 2018-08-28 at 1 17 52 pm" src="https://user-images.githubusercontent.com/88951/44742161-ccbc3b00-aac4-11e8-8e24-7711028745a6.png">

I do want to find something we can add there to make the clickable area naturally longer though.

**Comment by cklosowski** [comment]
As a testing note, we should be sure to verify that these columns all still look good with Fraud Monitor and Campaign Monitor enabled (two items that I know add their own columns to the orders/payments list table).

**Comment by JJJ** [comment]
That’s a good point.

I propose 2 things:
* We should set a max width on all custom columns
* We should educate add-on maintainers that having their own column widths is strongly encouraged and polite 💕

**Comment by SDavisMedia** [comment]
The only thing left unaddressed in this issue has been moved to: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7239

Closing.
