### ISSUE TITLE
Add Limit Login Attempt support to checkout user login form

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#6647]
## Enhancement Request
A customer ticket came in recently where an EDD website was being brute forced using the checkout login form, causing high AJAX requests/resource usage on the server (which was flagged by Kinsta).

The login form in Restrict Content Pro already includes support for the "Limit Login Attempts" plugin to prevent against these types of attacks, I believe EDD should also.

All forms, be it checkout or short-code (login and registrations) should have protection against this using the same method as RCP already has.

### Justification or use case

To prevent against brute force attacks at checkout.

**Comment by davidsherlock** [comment]
This is a secondary issue, but it would definitely be nice to see Google reCaptcha support in the EDD forms, since the plugins that exist already no longer function properly with the plugin.

**Comment by davidsherlock** [comment]
100% behind this @mindctrl.

**Comment by dgoldak** [comment]
Another request for recaptcha support: https://secure.helpscout.net/conversation/820962638/0/?folderId=1847242

**Comment by cklosowski** [comment]
For testing, I've used `Limit Login Attempts Reloaded` as a plugin to test that integration. Also, be sure to test with the EDD Auto Register extension to make sure auto registration still works.
