### ISSUE TITLE
Random release/3.0 clean-up

### ISSUE THREAD

**Issue by JJJ** [easydigitaldownloads/easy-digital-downloads#6650]
This issue is used to track random clean-up commits.

Some of these may be from internal conversations we've had in Slack. Others might just be whitespace or code-formatting type changes, or _small_ bug fixes from regressions that don't necessarily warrant their own issue tracking.

(Similar to #6642.)

**Comment by sunnyratilal** [comment]
83c245dea4806887f3affb60350bc1ae7d0760bb - `EDD_Customer` class vars were all set to `protected` with the introduction of magic methods to access them.

**Comment by DrewAPicture** [comment]
Closing this tracking issue. Going forward, please create an issue for anything warranting a commit against `release/3.0`, large or small, just so we can keep track of what's in progress and stay on top of all of the moving parts.
