### ISSUE TITLE
Object immutability

### ISSUE THREAD

**Issue by JJJ** [easydigitaldownloads/easy-digital-downloads#6651]
While there is a core PHP [request for comments](https://wiki.php.net/rfc/immutability) about creating a specific type of immutable object, that is a ways away, as is bumping our minimum PHP version to include that.

For EDD 3.0, we're going to enforce class property immutability with a series of magic methods, properly scoped variables, base classes, and class extending.

This issue is a general tracker for ongoing work specific to code changes that pertain to this initiative.

**Comment by sunnyratilal** [comment]
Closing as we've achieved immutability across all of the new core objects.
