### ISSUE TITLE
Refund Window

### ISSUE THREAD

**Issue by JJJ** [easydigitaldownloads/easy-digital-downloads#6652]
At Sandhills, our support team works quite a bit with customers who are in search of some kind of refund. One of the frequent workflow items for refunds involves looking at the original purchase date, comparing it to our refund policy, and concluding whether a refund is warranted.

It would be handy if EDD came bundled with setting(s) to define a default period of time where refunds can easily be processed, with accompanying UI warnings and concessions for what to do when inside or outside of that refund window.

I imagine this working in the following ways:

* A `Refund Window` setting with minutes/hours/days options
* A non-refundable option inside of individual Downloads (useful for all-access-pass type products)
* A `date_refundable` column in the `edd_orders` database table
* When an order is created, `date_refundable` is the `date_created` + the refund window
* A new column in the Orders list table to denote the refundable status
* Conditionally allow/disallow refunds when outside of the refund window (maybe hide behind an additional capability check so that super-admins can still perform them?)
* Require a Note when refunding outside the refund window

IMO, the above workflow would simplify one very common (and overly time consuming) type of support request.

Related to #2721.

**Comment by nosegraze** [comment]
I like this a lot. :+1:

**Comment by kerijacoby** [comment]
Looks good to me. Do it to it!

See what you can do about partial refunds while you're at it.

**Comment by pippinsplugins** [comment]
Looking good!

Let's adjust `Number of days refunds...` to `Number of days after purchase refunds ....`

**Comment by kerijacoby** [comment]
Can we add a non refundable box to the Download Settings?

**Comment by JJJ** [comment]
<img width="772" alt="screen shot 2018-06-13 at 18 54 47" src="https://user-images.githubusercontent.com/88951/41384423-48a83810-6f3b-11e8-8f01-4cd4fa6dbb94.png">

**Comment by JJJ** [comment]
#6555 merged into `release/3.0`.

There are a few UI and database schema changes still todo, as part of #6656.
