### ISSUE TITLE
Introduce transactions table

### ISSUE THREAD

**Issue by sunnyratilal** [easydigitaldownloads/easy-digital-downloads#6657]
After a discussion with the team, it's been decided that we should introduce a table called `edd_order_transactions`.

The purpose of this table is to handle transactions from the payment gateway and will store transaction IDs.

The schema will have columns that will allow for a relationship to either an `order` or an `order_item`; similar to how `edd_order_adjustments` currently works.

In the longer term, this is also the first step to allow recurring and non-recurring items to be purchased at the same time.

**Comment by pippinsplugins** [comment]
For extensions like recurring payments, should automatic renewals be recorded as multiple transactions on a single order record?

Right now each renewal would be considered a new order record.

**Comment by sunnyratilal** [comment]
Merged.
