### ISSUE TITLE
View customer download log does not return correct logs

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#6660]
### Expected behavior
Clicking on the "View customer download log" link within a payment shows _all_ customer download logs for all customers, and not that specific customer. While this is potentially intentional behaviour, it is confusing within the scope/context of the payment record, where I expect to see only the file download logs for all _that_ customers purchases.

### Actual behavior
Clicking on the "View customer download log" shows all custom download logs, for your entire customer base.

**Comment by mindctrl** [comment]
This was fixed in https://github.com/easydigitaldownloads/easy-digital-downloads/pull/6639.
