### ISSUE TITLE
Shop accountant role cannot specify products as exclusive of tax

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#6662]
### Expected behavior

The `Exclusive of tax` option should be visible to the Shop Accountant role.

### Actual behavior

The `Exclusive of tax` option on products isn't shown to the Shop Accountant role.

## Enhancement Request

Shop Accountants need to have that option available to them.

### Justification or use case

It should be permitted for Shop Accountants to enable / disable that flag since it's directed related to accounting responsibilities.

**Comment by cklosowski** [comment]
I think I'm going to go with the `view_shop_reports` here. The roles that currently have that are Admins, shop_manager, shop_accountant. This should give the proper access to the tax enabling :P

**Comment by cklosowski** [comment]
As a note I was thinking `edit_products` but the `shop_vendor` role has that capability ability as well.

**Comment by SDavisMedia** [comment]
Replicated on `master`. The setting is available and works properly for Shop Accountants on `issue/6662`. :+1:
