### ISSUE TITLE
Standardise customer addresses

### ISSUE THREAD

**Issue by sunnyratilal** [easydigitaldownloads/easy-digital-downloads#6667]
After talking with @JJJ, we need to standardise the way we store customer addresses in order to allow us to do the following for 3.0:

1. See tax collected by country/state as per #6301 
2. Filter purchases by country/state as per #3003 

Addresses for orders are currently stored as a serialised array in meta which makes it expensive to run queries on. In order for this to be performant, it needs to be follow a data structure that allows for easy querying.

This allows for more complex analytics further down the road such as seeing most used discounts in a country or even most popular country (in terms of orders).

Unless we move the address out of meta, the aforementioned will lead to very inefficient and expensive queries.

**Comment by JJJ** [comment]
Without standardizing addresses, the types of tax reports being requested will be impossible to perform, without crippling the database while the report is being compiled. 

I am still working out exactly what the schematic balance  is between scaling and usability.

I would like to have a similar place/way to standardize customer email addresses also, not just physical ones. 

So, I’m chewing on this while I digest the transaction table we need for orders.

**Comment by JJJ** [comment]
My first guess at flexible address columns:

id
customer_id
type
status
address
country
region
postal_code

**Comment by sunnyratilal** [comment]
Implemented & merged.
