### ISSUE TITLE
Show ajax indicator while taxes are being recalculated

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#6682]
Whenever the address fields on checkout are changed we recalculate the tax amount with an ajax request. Right now, however, this happens without any visible indicator that calculations are happening. The only indication of it happening is after it's complete and the purchase total is adjusted.

I'd like to propose that we show an loading indicator while the taxes are being recalculated.

**Comment by SDavisMedia** [comment]
Tested and working. But placement of the loading icon needs to be adjusted. Left comments on the PR.

**Comment by SDavisMedia** [comment]
All good now. :+1:
