### ISSUE TITLE
3.0: Undefined index: show_option_all on Order Details

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#6692]
The order details screen is triggering a PHP notice:

>>>Undefined index: show_option_all
>>>wp-content/plugins/easy-digital-downloads/includes/class-edd-html-elements.php:216

**Comment by sunnyratilal** [comment]
Fixed in a5680f120dfe9822a45b15001b69b01092a983ee.
