### ISSUE TITLE
3.0: Recalculate button zeros out totals

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#6693]
The `Recalculate` button on the order details screen isn't working properly. Instead of recalculating the total it just sets the total to 0.00, regardless of what the real value should be.

**Comment by SDavisMedia** [comment]
The `Recalculate` buttons isn't doing anything for me at all. But I'm posting here to say saving the payment without even changing anything on the screen will zero out totals for me. All I have to do is complete a purchase, go save the Order, and only the order subtotal will survive: https://cl.ly/2r2M431d2124

**Comment by sunnyratilal** [comment]
Gone ahead and removed the `Recalculate` as JavaScript handles these values dynamically for manually adding an orders and orders themselves are immutable rendering this button redundant.
