### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined function PayWithAmazon\edd_get_shop_country()

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/easy-digital-downloads#6695]
Latest `release/3.0`

```
PHP Fatal error:  Uncaught Error: Call to undefined function PayWithAmazon\edd_get_shop_country()  in /wp-content/plugins/easy-digital-downloads/includes/gateways/amazon-payments.php:232
```

<img width="827" alt="screen shot 2018-06-28 at 5 04 48 pm" src="https://user-images.githubusercontent.com/52581/42014256-69e8af6c-7af5-11e8-98a9-6befe1f8a48f.png">

Seems to occur with and without Amazon enabled.

**Comment by sunnyratilal** [comment]
Unable to replicate this, sorry @amdrew.  Which version of PHP are you running?

**Comment by amdrew** [comment]
@sunnyratilal 7.2.1

**Comment by amdrew** [comment]
Fixed it. Deleted my `edd_settings` option row and it came right.

@sunnyratilal I'll DM you the previous value for that option row - there are some Amazon related settings in there that you might be able to reproduce the error with.

**Comment by JJJ** [comment]
That screen shot does not look like EDD3.0 to me.

It should look more like:

<img width="824" alt="screen shot 2018-07-02 at 15 48 21" src="https://user-images.githubusercontent.com/88951/42185667-601bc8ee-7e0f-11e8-9798-5865c4d77b77.png">

**Comment by JJJ** [comment]
The fatal here is pretty weird. Namespaces aren't supposed to work like that.

I wonder if this was just some quirk that hit the error log between PHP & EDD versions?

**Comment by amdrew** [comment]
Yeah, the first screenshot is using latest master, hence the old settings screen. The fatal error occurred when switching from `master` branch to `release/3.0`. Thought I would show what the settings were before the switch. 

The PHP version didn't change between the two, only the branch. The fatal error prevented 3.0 from loading (or running upgrade routines) so I couldn't see the new 3.0 settings screen. I was able to replicate the issue (at the time) consistently by switching between the two branches. 

My guess is something Amazon API setting related in my options row at the time of the upgrade, since I had API credentials saved. I sent my options row dump to Sunny (since I didn't want to expose them here) but let me know if you want to take a look @JJJ and I'll DM it to you.

I'll see if I can replicate again by entering Amazon API deets on master and then switching to 3.0.

**Comment by amdrew** [comment]
Yep, that worked. To replicate:

1. Switch to master branch
2. Enable Amazon Payment Gateway
3. On the Amazon Payments screen, fill out some API creds. To replicate I just used the following:

    <img width="1046" alt="screen shot 2018-07-03 at 10 04 47 am" src="https://user-images.githubusercontent.com/52581/42188606-ca0d7452-7ea8-11e8-9fa7-97e62538f2c2.png">

4.    Switch to 3.0 branch and reload the admin.

**Comment by sunnyratilal** [comment]
Replicated; this bug is odd.

**Comment by sunnyratilal** [comment]
This is because of Amazon loading too early and it's because we need to hook EDD on to `plugins_loaded`.

**Comment by sunnyratilal** [comment]
Fixed in https://github.com/easydigitaldownloads/easy-digital-downloads/commit/be4c2af55eab7bcd4c379f4f83efc1862f0c6951.

EDD now hooks on to `plugins_loaded`.
