### ISSUE TITLE
Can't set English as language

### ISSUE THREAD

**Issue by boluda** [easydigitaldownloads/easy-digital-downloads#6696]
### Expected behavior
When I set "English" as my dasboard language, I expect "English" as my dashboard language.

I'm talking about the setting "Language" under "My profile menu". (/wp-admin/profile.php)

I'm NOT talking about the general language setting. (/wp-admin/options-general.php)

Tried in several sites, always same behaviour. If the main site is in Spanish, and I change the language of my profile to English, the ONLY plugin that keeps using the Spanish strings is EDD.

### Actual behavior
When I set "English" as my dasboard language, the plugin is still in Spanish.

### Steps to reproduce the behavior
1) Set up SPANISH in general WordPress settings
2) Set up ENGLISH in "My profile" menu
3) That's it. It doesn't work

Any other relevant information: Tried in 5 diferent sites, hostings, PHPs, environments.

I would appreciate to fix this bug, please, because I want to work in the dashboard in English.

Thanks.

**Comment by pippinsplugins** [comment]
I believe this is the same bug as https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5800

**Comment by boluda** [comment]
It is! Thanks, I'll wait for that huge 3.0 update.

**Comment by pippinsplugins** [comment]
Closing as duplicate then.
