### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined method EDD\Logs\Log::add_meta()

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/easy-digital-downloads#6702]
PHP 7.2.1/latest 3.0 branch

After getting 3.0 going (by deleting my settings row: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6695#issuecomment-401644754) I ran the logs upgrade routine in the admin dashboard and got this:

```
PHP Fatal error:  Uncaught Error: Call to undefined method EDD\Logs\Log::add_meta() in /wp-content/plugins/easy-digital-downloads/includes/admin/upgrades/upgrade-functions.php:1692
```

<img width="846" alt="screen shot 2018-07-02 at 12 53 33 pm" src="https://user-images.githubusercontent.com/52581/42140725-fcde7550-7df6-11e8-8249-f424d135bc45.png">

**Comment by sunnyratilal** [comment]
Fix confirmed.
