### ISSUE TITLE
Error after resuming database upgrade: Call to a member function exists() on boolean

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/easy-digital-downloads#6703]
PHP 7.2.1/latest 3.0 branch

After the error on https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6702 I now see:

<img width="813" alt="screen shot 2018-07-02 at 12 58 32 pm" src="https://user-images.githubusercontent.com/52581/42140778-a52941e0-7df7-11e8-8183-de184ed4cbb0.png">

Clicking to resume the upgrade produces:

```
PHP Fatal error:  Uncaught Error: Call to a member function exists() on boolean in /wp-content/plugins/easy-digital-downloads/includes/admin/upgrades/upgrade-functions.php:1285
```

**Comment by sunnyratilal** [comment]
Fix confirmed.
