### ISSUE TITLE
Error when running customer database upgrade routine

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/easy-digital-downloads#6704]
PHP 7.2.1/latest 3.0 branch

Deleted the `edd_doing_upgrade` option row so I could see the list of upgrades again after https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6702.

<img width="894" alt="screen shot 2018-07-02 at 1 06 13 pm" src="https://user-images.githubusercontent.com/52581/42140891-ca4c390e-7df8-11e8-924a-40165fddc514.png">

When I run the first routine (customer database) I get:

```
Notice: Undefined offset: 0 in /wp-content/plugins/easy-digital-downloads/includes/compat/class-customer.php on line 71
```

@sunnyratilal Are these notices helpful for pinpointing upgrade specific edge cases, or is there something seriously borked with my local install? Can run through the list of upgrades and output each error (if one exists) if you think that would be helpful.

**Comment by JJJ** [comment]
>Are these notices helpful for pinpointing upgrade specific edge cases, or is there something seriously borked with my local install? Can run through the list of upgrades and output each error (if one exists) if you think that would be helpful.

I think so. 3 out of the 4 issues you just reported were valid, and the last 1 seems weird but could also be something weird. 👍

**Comment by amdrew** [comment]
👍 I ran through the rest of the upgrade routines after pulling down the latest fixes and everything seems to have gone smoothly.
