### ISSUE TITLE
Update purchase zip validation regex

### ISSUE THREAD

**Issue by misulicus** [easydigitaldownloads/easy-digital-downloads#6708]
### Expected behavior
A zip code for Mongolia for example 13371 will fail during checkout.

### Actual behavior
A zip code for Mongolia for example 13371 will not be able to checkout with Stripe.

### Steps to reproduce the behavior
1) Try to checkout using Mongolia as country and 13371 as ZIP

### Information (if a specific version is affected):
PHP Version: 7

EDD Version (or branch): Latest

WordPress Version: Latest

Any other relevant information:

### Explain your enhancement (please be detailed)
Issue comes from this line https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/process-purchase.php#L1045
I believe that restricts to a 6 digit zip code.

Found a more exhaustive list here : https://github.com/barbieswimcrew/zip-code-validator/blob/master/src/ZipCodeValidator/Constraints/ZipCodeValidator.php#L33-L214

This one seems to be from google: https://chromium-i18n.appspot.com/ssl-address

**Comment by cklosowski** [comment]
As a note all of these link to the 'ID' country code which is Indonesia, but the ticket is for 'Mongolia' which is 'MN'.

Looking at it yes, our regex for 'MN' was looking for a 6 digit string, but all research I can find is that Mongolia has 5 digits

**Comment by SDavisMedia** [comment]
Replicated on `master` and confirmed working on `issue/6708`.

Since this is checkout, I did a few other test purchases unrelated to the issue. I know the PR is as simple as a change can be. But still...

Everything's working. 👍

**Comment by cklosowski** [comment]
Since it affects the checkout process, I want @mintplugins and @misulicus to test this, that would make 3 confirmations besides myself that confirm things are still working.

**Comment by misulicus** [comment]
@cklosowski looks good here.

**Comment by mintplugins** [comment]
I completed 24 tests, covering the following combinations:

- a Canadian Address
- a US address
- a Mongolian address. 
- Taxes disabled, no address entered
- Taxes enabled/disabled, Stripe address fields present
- Taxes disabled, Stripe address fields set to "none"
- Taxes disabled, Test Gateway
- Taxes enabled, Test Gateway

All purchases went through successfully and as expected. Green light from me.
