### ISSUE TITLE
Download File URL inconsistency when manually changing

### ISSUE THREAD

**Issue by misulicus** [easydigitaldownloads/easy-digital-downloads#6713]
### Expected behavior
When manually changing a download`s file name and File URL by copy/pasting the full file link it should download the new uploaded file. File name changes correctly

### Actual behavior
The new file name changes but when clicking a download link it still serves the previous file url.

### Steps to reproduce the behavior
1) Create a Download and Upload a file and give it a file name
2) Upload another download file via WP media manager and copy the full file path.
3) Edit the download and change the file name to a new name and manually select the old full file url and paste in the newly uploaded file. Save the download
4) try to redownload from the purchase history page, the new file name will be visible but the download will serve the originally uploaded file and not the new one uploaded via the media manager

### Information (if a specific version is affected):
PHP Version: 7+

EDD Version (or branch): master

WordPress Version: latest

**Comment by cklosowski** [comment]
I believe what's essentially happening is that when you initially upload a file we've saving an attachment ID as a hidden input, then when you manually update the file name and URL (without picking from the media modal), that attachment ID isn't getting cleared.

When delivering files we attempt the attachment ID first (as it's just easier to get a URL and know where to get the file).

Basically when that field changes without the media modal, we need to clear the attachment ID hidden input field.

**Comment by cklosowski** [comment]
We discussed this at the retreat, since we're doing some nice work to clean up this area in 3.0, let's get this fix in there as well.

**Comment by cklosowski** [comment]
Gonna make an attempt at this.

**Comment by dgoldak** [comment]
I tested with `issue/6713` checked out and still get the same behavior with `release/3.0`. Original file is downloaded instead of file I copy/pasted.

**Comment by spencerfinnell** [comment]
@dgoldak This needs to be ported to the updated JS system. I'll fix it.

**Comment by spencerfinnell** [comment]
Oh never mind, it was implemented there. Make sure you are testing with SCRIPT_DEBUG enabled.

**Comment by cklosowski** [comment]
@dgoldak I'll retest this after all the latest updates. and push any necessary changes.

**Comment by cklosowski** [comment]
Just fixed the merge conflict, and tested it again and all seems right, I was delivered the correct file on clicking the download link.
