### ISSUE TITLE
3.0 Payment gateways settings nav

### ISSUE THREAD

**Issue by misulicus** [easydigitaldownloads/easy-digital-downloads#6716]
The gateways displayed should be only the ones currently "active" on the site.
Fresh setup and i see Amazon even its not active.
https://www.screencast.com/t/pyLbhETcEjI

**Comment by misulicus** [comment]
@sunnyratilal

**Comment by JJJ** [comment]
This is currently by design.

Just because the gateway isn’t currently active for use by customers, doesn’t mean it shouldn’t be configurable by shop managers.

Open to different ways to communicate this in the UI though.

**Comment by misulicus** [comment]
I compared it to current stable release and that’s why I thought sokmething might have changed for 3dd

**Comment by JJJ** [comment]
It did change. 😉

Previously, different gateways worked differently. Amazon needed to be active to see its settings page, PayPal Standard did not, and Stripe and PayPal Pro also did not, but other add-ons did. It was weird.

A payment gateway should be configurable by shop admins without being available to customers.

You’ll notice a lot of things that are different between 2.9 and 3.0. It’s OK to question them. 👌
