### ISSUE TITLE
Link to the site Subscribe page where necessary

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#6719]
### Expected behavior
Link to the EDD site `/subscribe/` page when we want people to subscribe to our newsletter.

### Actual behavior
From the _General -> Tracking_ settings page, we attempt to link to the site footer, which no longer has a newsletter sign up form.

### Steps to reproduce the behavior
1) Visit `/wp-admin/edit.php?post_type=download&page=edd-settings&tab=general&section=tracking`
2) Click "our newsletter"

### Information (if a specific version is affected):
EDD Version (or branch): `release/3.0`

-----

Link here instead: https://easydigitaldownloads.com/subscribe/

If there are anymore links to the site footer for the newsletter form, let's update those too while in here.

**Comment by sunnyratilal** [comment]
Merged.
