### ISSUE TITLE
Change 'Empty for global' terminoligy

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#6720]
One the Download edit screen, I noticed for the **File Download Limit** and the **Refund Window** sections we use the phrase `Empty for global.`

![screenshot_2018-07-08 edit download 3dd1 wordpress](https://user-images.githubusercontent.com/2359131/42425492-18ec7360-82d3-11e8-94aa-7fd0244427c4.png)

That's changed from `Leave blank for global setting` in previous versions. While I do agree that the current phrasing could be better, I don't think `Empty for global` provides nearly enough context. And it's not further explained in the tooltip.

My suggestion is `Leave blank to use global setting.` These are the only two times I've noticed it in admin. But I would suggest the same change for any other uses.

**Comment by JJJ** [comment]
The two problems with the original text and the new recommendation are:

* They spread out into 2 lines of text, which looks bad
* No amount of verbosity will explain away the double-duty this 1 box performs

I’d vote to leave as-is, or break these settings up into 2 for each: one to use the default, another for the override (0 or above)

**Comment by SDavisMedia** [comment]
> They spread out into 2 lines of text, which looks bad

I 100% disagree that multiple lines of text looks bad. Sure, this is subjective. But I think it's a major reach. 

I understand that this isn't a very important point worth staying on, so feel free to ignore. But since that was publicly stated, I want to publicly counter it for anyone reading. **Content begets design** and WP admin is designed well enough to where two lines of text don't make things funky for a setting label. If that is ever the case, adjust the design instead of sacrificing the text (assuming the text is already succinct and necessary). 

![screenshot_2018-07-16 add new download 3dd1 wordpress](https://user-images.githubusercontent.com/2359131/42771649-bffaa4e2-88dc-11e8-8034-1fbdb396ff1e.png)

-----

That said, two settings could definitely be better. I'm all for that.  :+1:

**Comment by mindctrl** [comment]
I agree with Sean.

**Comment by SDavisMedia** [comment]
After some slack discussion, it appears we'll try to go with two settings. A checkbox toggle to enable the setting, which then exposes a relevant text/number input field. :+1:

**Comment by cklosowski** [comment]
I'm 100% ok with this decision. mostly because it leaves a less ambiguous UI. :+1:

**Comment by spencerfinnell** [comment]
@SDavisMedia I'm not sure two options cover the necessary possibilities. 

- [ ] Enable file download limit

If unchecked like above it will use the global setting? But the global setting *could* impose a limit. So leaving it unchecked it not representing the setting label.

- [x] Enable file download limit
  [____] Download limit

This still presents the option of needing to enter 0 for unlimited, or blank for global (back to where we currently are)

---

I think it could be slightly improved with 

- [ ] Enforce custom file download limit

- [x] Enforce custom file download limit
  [___] Download limit

This still presents the need to show `0 for unlimited` though (and probably a mention of how the global will be applied if unchecked).

---

The "Refundability" section makes things a little more clear by letting the user know what their global setting is.

It's a tough one but my vote for the time being would be to switch back to `Leave blank to use global setting` and perhaps try to give users a better idea of *what* their global setting actually is.

**Comment by SDavisMedia** [comment]
@spencerfinnell Very good points. I personally don't think the old label was bad. At the most, it needed minor improvements in clarity. You're right that adding the additional setting(s) doesn't fully resolve anything without needing more explanation anyway.

Can't help but feel like this is all happening all because of a change in label terminology to avoid multiple lines of text. So let's take a step back to solve the actual problem.

Am I wrong in thinking that if the original input label simply stated the global value (if there is one), then told you to either leave it blank to use the global value or set a value to use for that product, then this would be as clear as day?

**Comment by JJJ** [comment]
There are 2 problems, that I’ll try again to recommunicate here in a different way:

* Text is too long so it bleeds on to multiple lines in an uneven way
* Long label text is a clear indication of one thing having too many responsibilities – users are going to confuse the values without knowing it.
* The values in the input box are dangerously ambiguous. `0` and `empty` shouldn’t do different things.
* Users shouldn’t be exposed to needing to understand that 0 and empty are different – that’s a technical limitation, and is one of the ways we take the “easy” out of easy digital downloads.
* These are essentially on/off switches for features, and the boundary only kicks in when the feature is on. There are form field controls available to us to communicate this.

**Comment by SDavisMedia** [comment]
@JJJ See Spencer's comment, the second section.

With that approach, we can make it to where once the box is checked displaying the input field, **the default behavior can be `unlimited`**... as in, if you check the box to control the behavior for the specific product, the default is `unlimited` and if you want to set a limit, add a value to the field.

That approach completely removes the need to enter `0` for anything.

**Comment by JJJ** [comment]
@SDavisMedia that introduces more issues

WordPress core already sets the precedent that settings are defaults and things have overrides. Posts, Comments, Users all work like this, etc...

In our case, if the default setting is `5` then the default in a post/object should be `5`, with an allowable override to unlimited or `2` or any other value.

Users should even be able to specifically enter `5` here and have that stay `5` when they change the default setting to `10`.

This was poorly designed to begin with, and it stuck & spread throughout extensions and other places in EDD. Reverting what's here now isn't right, because what we had before is very wrong.

Let's talk about iterating on what we have now: improving verbiage, using different words, etc...

**Comment by SDavisMedia** [comment]
@JJJ What would you consider the correct approach, as if this was being built for the first time? I'm trying my best to understand what you'd like to see, but it seems as if you're not only against your own suggestion, but also the other suggestions.

> Let's talk about iterating on what we have now: improving verbiage, using different words, etc...

I originally opened the issue asking that we do exactly that. So in your opinion, what does that look like?

**Comment by spencerfinnell** [comment]
My outline was to show that a checkbox doesn't solve anything. @JJJ can you outline the UI for these scenarios:

- Global default is blank, I want to use this global.
- Global default is 0, I want to use this global.
- Global default is 30, I want to use this global.
- Global default is blank, I want to overrider this global.
- Global default is 0, I want to override this global.
- Global default is 30, I want to override this global.

Also: "Text is too long so it bleeds on to multiple lines in an uneven way" becomes irrelevant with translations and designing user interaction around the length of a string seems backwards to me.

**Comment by SDavisMedia** [comment]
> Also: "Text is too long so it bleeds on to multiple lines in an uneven way" becomes irrelevant with translations and designing user interaction around the length of a string seems backwards to me.

💯💯💯

**Comment by spencerfinnell** [comment]
I think one of the main issues is that globally 0 and blank both mean unlimited. And passing that down to local overrides causes the confusion.

- Global 0: Unlimited
- Global Blank: Unlimited
- Global 30: 30

- Local 0: Unlimited
- Local Blank: Global value (could be anything)
- Local 30: 30

Eliminating the ability for a Blank global setting would help, but that would need to be masked in the UI as well, as showing a 0 default as unlimited is not any more clear.

---

Using a dropdown that has some (likely very annoyingly crafted) options might make things easier.

__Download Limit (when global is blank or 0):__
- Default (Unlimited)
- Custom limit

Selecting "Custom limit" exposes a text field.

__Download Limit (when global is set)__
- Default (25)
- Unlimited
- Custom limit

Selecting "unlimited" will save it as 0 behind the scenes. Selecting "Custom limit" exposes a text field.

This hides having to use 0 as unlimited which is the crux of a lot of confusion.

**Comment by spencerfinnell** [comment]
Should probably look at https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6891 before doing anything more here than adjusting the original string.

**Comment by pippinsplugins** [comment]
For the time being, I'd like to see us revert these text strings back to they were and leave as is. With as many moving items as there are in 3.0, we do not need to get caught up on items like this, especially when there is zero evidence they have caused any real issues for users nor in support.
