### ISSUE TITLE
Tax settings: State / Province field not clickable after changing Country

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#6723]
### Expected behavior
When I navigate to _Settings -> Taxes -> Rates_ and select a **Country** while creating a new Regional Rate for taxes, I expect the **State / Province** field to adjust based on the selected country (whether it becomes a dropdown or a text field).

### Actual behavior
When I select a **Country**, the **State / Province** field is disabled and does not populate.

### Steps to reproduce the behavior
1) Create a new Regional Rate for taxes, starting with the **Country** field. Try `United States` or `Canada`.
2) Observe the **State / Province** field.

### Information (if a specific version is affected):
PHP Version: `7.1.7`
EDD Version (or branch): `release/3.0`
WordPress Version: `4.9.7`

### Any other relevant information:

If I save the page after selecting a country, the state/province field is properly populated.

There are no errors in my console.

**Comment by JJJ** [comment]
Fixed in `release/3.0` and `master` for what will be 2.9.5.

See also #6747.
