### ISSUE TITLE
Privacy Policy does not show on checkout

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#6724]
### Expected behavior
Configure the Privacy Policy settings to display on checkout like so:
![screenshot_2018-07-08 easy digital downloads settings 3dd1 wordpress](https://user-images.githubusercontent.com/2359131/42426091-f587a2b2-82d9-11e8-9934-9d03ffa3425d.png)

With that configuration, a checkbox, label, and toggle link should show on checkout. The toggle link will expand to show your Privacy Policy page content. The Terms & Agreement settings work the same way.

### Actual behavior
The checkbox and label will show, but the toggle link will not.
![screenshot_2018-07-08 checkout 3dd1 1](https://user-images.githubusercontent.com/2359131/42426134-5d74b680-82da-11e8-859f-295b0077b92a.png)

### Steps to reproduce the behavior
1) Fully configure a Privacy Policy page in WordPress.
2) Enable EDD's Privacy Policy on checkout, choosing to show the checkbox, label, and enabling the **Privacy Policy on Checkout** setting. 
3) Add an item to the cart and view checkout.

### Information (if a specific version is affected):
PHP Version: `7.1.7`
EDD Version (or branch): `release/3.0`
WordPress Version: `4.9.7`

Any other relevant information:

Here's EDD `master` with the same configuration (totally different WordPress site): 
![screenshot_2018-07-08 edd checkout local development](https://user-images.githubusercontent.com/2359131/42426208-ec650354-82da-11e8-914e-674b1410c168.png)

**Comment by sunnyratilal** [comment]
Merged.
