### ISSUE TITLE
3.0 Reports: Overview displays dollar amount for sales count

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#6725]
### Expected behavior
Reports Overview tab accurately display an overview of sales, earning, etc.

### Actual behavior
On the Reports Overview, the `Sales` tab (Last 30 Days) displays a dollar amount (which appears to be the dollar version of the actual sales count).

For example, I have a single purchase on a fresh site. This purchase was for a $10 product, plus 10% exclusive tax. So 1 sale, with $11 earnings. Here's the overview:

![6aee098d-c3d6-4ad2-8ffe-39ffef40c61a](https://user-images.githubusercontent.com/2359131/42426423-bcbb9ae4-82dc-11e8-8ded-12006a461c7b.png)

### Steps to reproduce the behavior
1) Complete at least one purchase.
2) View Reports Overview `Sales` tile.

### Information (if a specific version is affected):
PHP Version: `7.1.7`
EDD Version (or branch): `release/3.0`
WordPress Version: `4.9.7`

**Comment by sunnyratilal** [comment]
Thanks @SDavisMedia.

Fixed in a133d52a81f2ff2418bdfec0e096743ee0502285.
