### ISSUE TITLE
Orders timestamped based on UTC

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#6726]
### Expected behavior
When I complete a purchase, I expect it to be timestamped based on my WordPress timezone settings.

### Actual behavior
Orders are timestamped based on UTC regardless of my WordPress timezone settings.

### Steps to reproduce the behavior
1) Make sure your WordPress install has a timezone set.
2) Complete a test purchase on a fresh site running 3DD.
3) View timestamp on the completed order.

### Information (if a specific version is affected):
PHP Version: `7.1.7`
EDD Version (or branch): `release/3.0`
WordPress Version: `4.9.7`

Any other relevant information:

I see a few issues from the past about timezones. It looks like they're all closed as fixed. Here's a search for `UTC`: https://github.com/easydigitaldownloads/easy-digital-downloads/issues?q=is%3Aissue+utc+is%3Aclosed

**Comment by sunnyratilal** [comment]
Fixed in https://github.com/easydigitaldownloads/easy-digital-downloads/commit/f9843c13b1c871dbab7b7263e793b644704e1a23.
