### ISSUE TITLE
3.0 Reports: Payment Gateways pie chart displays earnings as float

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#6727]
### Expected behavior
All output of Earning should displayed with currency symbol and properly formatted.

### Actual behavior
When hovering over a section of the `Gateway Earnings` pie chart, the tooltip displays the earnings amount as float like so:

![52a50ba3d16917a18898017b6bc4ba31 _image 202018-07-08 20at 208 12 14 20pm](https://user-images.githubusercontent.com/2359131/42429041-d9227932-82eb-11e8-847d-634f1e2873dc.png)

My earnings are `$9.90`. The tooltip displays the value as `9.9`.

### Steps to reproduce the behavior
1) Complete at least one purchase through your gateway of choice.
2) Navigate to the Payment Gateways tab on the Reports page and in the `Gateway Earnings` pie chart, hover over the gateway section you used. Observe the earnings total.

### Information (if a specific version is affected):
PHP Version:`7.1.7`
EDD Version (or branch): `release/3.0`
WordPress Version: `4.9.7`

**Comment by sunnyratilal** [comment]
Fixed in https://github.com/easydigitaldownloads/easy-digital-downloads/commit/8285b13ad81a3604d65dc7130dd885b5a18ece55.
