### ISSUE TITLE
3.0 Reports: Taxes unfiltered by region display ALL as a location

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#6728]
### Expected behavior
If I go to _Reports -> Taxes_ and I do not filter the report, meaning I'm viewing data for all downloads, all countries, and all regions, I expect tax data to display with no references to location.

### Actual behavior
There's a tile for total tax collected for location, and it displays `ALL, ALL` as the `Country, Region`.

![screenshot_2018-07-08 reports 3dd1 wordpress](https://user-images.githubusercontent.com/2359131/42429431-cd7cbdfc-82ed-11e8-8cb6-2476cc9dd760.png)

### Steps to reproduce the behavior
1) Complete a purchase with taxes enabled.
2) View Taxes report but do not filter the report based on location. 

### Information (if a specific version is affected):
PHP Version: `7.1.7`
EDD Version (or branch): `release/3.0`
WordPress Version: `4.9.7`

**Comment by sunnyratilal** [comment]
Fixed in https://github.com/easydigitaldownloads/easy-digital-downloads/commit/9dbcc30068d5369e1f16a2b75c190e3d2df5045d.
