### ISSUE TITLE
3.0 Reports: Discounts report displays Top Five Discounts amounts as float percentages

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#6729]
### Expected behavior
If, for example, I create a 10% discount and use it, I expect the Discounts report to list that discount amount as `10%`.

### Actual behavior
It actually lists the discount as `10.00%`.

![screenshot_2018-07-08 reports 3dd1 wordpress 1](https://user-images.githubusercontent.com/2359131/42429663-39e74cea-82ef-11e8-878d-645bb99aff79.png)

### Steps to reproduce the behavior
1) Create a new percentage based discount.
2) Use the discount in a purchase so that it will be one of your Top Five Discounts on the Discounts report. 
3) Look at the report and take note of the way the value of that discount is formatted in the **Amount** column of the Top Five Discounts table.

### Information (if a specific version is affected):
PHP Version:`7.1.7`
EDD Version (or branch): `release/3.0`
WordPress Version: `4.9.7`

**Comment by SDavisMedia** [comment]
I didn't report the right problem here. Obviously, there's nothing wrong with a percent displaying like `6.5%`. My beef is with the additional zeros, like `10.00%`.

So I guess is up for debate.

**Comment by sunnyratilal** [comment]
Closing as `wontfix` after a discussion on Slack.
