### ISSUE TITLE
3.0 Discounts: One use of new discount sets it as Inactive

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#6730]
### Expected behavior
If I create a new discount and I do not set **Max Uses**, I expect it to default to unlimited uses. The setting description even states `Leave blank for unlimited`, though the field will be populated with `0` once the discount is saved.

### Actual behavior
Creating a new discount without adding a value for **Max Uses**, and then using that discount, results in the discount being set as Inactive.

### Steps to reproduce the behavior
1) Create a new discount, only setting the Name, Code, Type, and Amount. Save the discount.
2) Use the discount in a purchase.
3) View the discount. It is now set as Inactive.

### Information (if a specific version is affected):
PHP Version:`7.1.7`
EDD Version (or branch): `release/3.0`
WordPress Version: `4.9.7`

### Any other relevant information:

If you _do_ set a value for **Max Uses**, it appears that the value is respected.

**Comment by sunnyratilal** [comment]
Think this is because `max_uses` is set to `0` as the default value in the database.

**Comment by sunnyratilal** [comment]
Fixed in https://github.com/easydigitaldownloads/easy-digital-downloads/commit/56e87a02b79de54ae93731a36c2a08bed7188560.
