### ISSUE TITLE
3.0: Consistency in admin page titles

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#6733]
### Expected behavior
From one admin page to another, I'd expect to see consistency, or some sort of standard for admin page titles.

### Actual behavior
Some pages include EDD branding while others do not. Some pages have no title at all.

Downloads - no page title
Orders - `Orders`
Customers - `Customers`
Discounts - `Discount Codes`
Reports - `Easy Digital Downloads Reports`
Settings - `Easy Digital Downloads Settings`
Tools - `Easy Digital Downloads Tools`
Extensions - no page title

### Steps to reproduce the behavior
1) Just view the various admin pages.

### Information (if a specific version is affected):
EDD Version (or branch): `release/3.0`

-----

I don't have a particular suggestion or preference. I just thought it was odd that there didn't seem to be a pattern at all. At least not one that I've noticed.

**Comment by sunnyratilal** [comment]
Fixed in https://github.com/easydigitaldownloads/easy-digital-downloads/commit/b57939dda8e65ddb418d373c3e703fca7ca6f58f.
