### ISSUE TITLE
Disable "Don’t allow guest purchases for an email address that has an existing user."

### ISSUE THREAD

**Issue by nabeghe** [easydigitaldownloads/easy-digital-downloads#6741]
How to disable the feature "Don’t allow guest purchases for an email address that has an existing user." in last update 2.9.4?!

**Comment by mintplugins** [comment]
Hey there,

You can open a support ticket to get a reply from us about this issue directly. You can do that here:
https://easydigitaldownloads.com/support/

Thanks
