### ISSUE TITLE
 Customer download log show all logs 

### ISSUE THREAD

**Issue by shamim2883** [easydigitaldownloads/easy-digital-downloads#6746]
### Expected behavior
in order details page when click "View customer download log" it should show download log from that customer. Also in customers page when click "Download log" it should behave same.

### Actual behavior
in order details page when click "View customer download log" it shows download log from all customers. Also in customers page when click "Download log" it behaves same.

**Comment by mindctrl** [comment]
We fixed part of this in `release/3.0` but we missed the one on the list table. Looks good to me.

**Comment by pippinsplugins** [comment]
Confirmed bug and tested PR. Works fine. Merging.
