### ISSUE TITLE
Can't create new discounts in release/3.0

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/easy-digital-downloads#6752]
### Expected behavior
In `release/3.0`, when attempting to add a new discount it fails. The following WP database error is thrown:
```
WordPress database error Unknown column 'min_charge_amount' in 'field list' for query INSERT INTO `wp_edd_adjustments` (`parent`, `name`, `code`, `status`, `type`, `scope`, `amount_type`, `amount`, `description`, `max_uses`, `use_count`, `once_per_customer`, `min_charge_amount`, `product_condition`, `date_created`, `date_modified`, `start_date`, `end_date`) VALUES (0, '20percent', '20percent', 'active', 'discount', 'global', 'percent', '20.00', '', '0', '0', '1', '0.00', 'all', '2018-07-11 20:04:46', '2018-07-11 20:04:46', '0000-00-00 00:00:00', '0000-00-00 00:00:00')
```

### Steps to reproduce the behavior
1) Check out `release/3.0` and try to create a new discount in the admin.

### Information (if a specific version is affected):
EDD Version (or branch): `release/3.0`

**Comment by SDavisMedia** [comment]
Replicated on `release/3.0`. Confirmed that I can create and delete a discount on `issue/6752`. :+1:
