### ISSUE TITLE
Prevent discounts from being deleted if they've been used

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/easy-digital-downloads#6753]
## Enhancement Request
Per discussion in Slack: if a discount code has been used, we should prevent it from being deleted.

### Justification or use case
Accurate reports, accounting, and just generally good data integrity.

**Comment by sunnyratilal** [comment]
Fixed in 6f0e173be93f0f5c262a1ced81b6744b0ea71631.
