### ISSUE TITLE
AJAX Add to Cart Animation Doesn't Stop And File Doesn't Deleted After Adding To Shopping Cart

### ISSUE THREAD

**Issue by meysam98** [easydigitaldownloads/easy-digital-downloads#6757]
AJAX Add to Cart Animation Doesn't Stop And File Doesn't Deleted After Adding To Shopping Cart!
The following object was printed to the js console:
`{readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}abort: ƒ (a)always: ƒ ()complete: ƒ ()done: ƒ ()error: ƒ ()fail: ƒ ()getAllResponseHeaders: ƒ ()getResponseHeader: ƒ (a)overrideMimeType: ƒ (a)pipe: ƒ ()progress: ƒ ()promise: ƒ (a)readyState: 4responseText: ""setRequestHeader: ƒ (a,b)state: ƒ ()status: 200statusCode: ƒ (a)statusText: "OK"success: ƒ ()then: ƒ ()__proto__: Object`

**Comment by SDavisMedia** [comment]
Hi @meysam98.

Please go ahead and open up a support ticket here: https://easydigitaldownloads.com/support/

Report the problem to the support crew and someone will assist you via email. We only use GitHub for development tracking.

Thanks!
