### ISSUE TITLE
An option to force customers to add only single item to card per purchase.

### ISSUE THREAD

**Issue by Mor-raj** [easydigitaldownloads/easy-digital-downloads#6758]
Is there any way to force customers to add only single item to card per purchase?
In other words, disable shopping card "completely", So that when a customer touches the download button of an item, if he returns to the download archive page, it will be deleted from his shopping cart.

an option like adding this filter to theme functions.php:
`add_filter( 'edd_pre_add_to_cart_contents', '__return_false' );`

I hope this option is useful (specially for "services" )
Thanks!

**Comment by davidsherlock** [comment]
In the future please direct all support requests to us here: www.easydigitaldownloads.com/support, where will will be able to help and respond to you quicker.

In relation to your question, the following code will work (I built this for my own service marketplace):

```
function ds_restrict_cart_items( $item ) {

       $cart_contents = edd_get_cart_contents();

        if ( count( $cart_contents ) >= 1 ) {
            return false;
        }

        return $item;
 }
add_filter( 'edd_add_to_cart_item', 'ds_restrict_cart_items', 10, 1 );
```

**Comment by cklosowski** [comment]
I'm closing this as it's a customization issue, not an issue with EDD core. The functionality to achieve this currently exists.
