### ISSUE TITLE
3.0 Reports: unfiltered by region display ALL as a location on specified downloads

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/easy-digital-downloads#6759]
### Expected behavior
Same as https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6728, but for Downloads report.

If I go to Reports -> Downloads and I do not filter the report by region, I expect it to display with no references to location. It will display ALL, ALL if you specify a download though.

### Actual behavior
When a specific download is selected, the tile that shows has a reference to location.

Config:
<img width="670" alt="image" src="https://user-images.githubusercontent.com/1254870/42648442-8fe76af0-85cc-11e8-9d56-0d1d5cc6b628.png">

Tile:
<img width="338" alt="image 2018-07-12 at 12 09 33 pm" src="https://user-images.githubusercontent.com/1254870/42648425-7e2dbfa8-85cc-11e8-8512-de98e43eb4c4.png">

### Steps to reproduce the behavior
See screenshots above

**Comment by sunnyratilal** [comment]
Fixed in https://github.com/easydigitaldownloads/easy-digital-downloads/commit/712200fb0d23afe2695eb4a8dd94e7219cfcfe7a.
