### ISSUE TITLE
3.0 Reports: Download filter on Downloads report doesn't show default value

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/easy-digital-downloads#6761]
### Expected behavior
When I select `All Downloads` in the dropdown and the page reloads, I expect it to show `All Downloads` when the page reloads.

### Actual behavior
Instead it says `Choose a Download`... which, as a secondary issue, is cut off.

<img width="477" alt="image" src="https://user-images.githubusercontent.com/1254870/42649402-3cfc4416-85cf-11e8-880c-a10309837a22.png">

### Steps to reproduce the behavior
1) Select a specific download and filter the report.
2) Select `All Downloads` and filter the report.

### Information (if a specific version is affected):

EDD Version (or branch): `release/3.0`

**Comment by sunnyratilal** [comment]
Fixed in https://github.com/easydigitaldownloads/easy-digital-downloads/commit/524103c21cd5572492d9c284b92ebc9a6890c989.
