### ISSUE TITLE
3.0 Reports: "Drag boxes here" is confusing in some contexts

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/easy-digital-downloads#6762]
### Expected behavior
When viewing the Downloads report, unfiltered, there's an empty metabox that says `Drag boxes here`.

<img width="1171" alt="image" src="https://user-images.githubusercontent.com/1254870/42649658-e25cf414-85cf-11e8-98d0-04e3771fcd71.png">

I think this is confusing because there are no boxes to drag there, unless you drag an existing one, in which case you just move the empty box to another location.

Of course the empty spot gets taken if you filter the report by a particular download, but when it's unfiltered it would be great to hide the box or something.

**Comment by JJJ** [comment]
I agree.

The `Drag boxes here` text comes from WordPress core. We can at least hide it.

**Comment by JJJ** [comment]
@mindctrl pull and test?

**Comment by mindctrl** [comment]
@JJJ looks great!
