### ISSUE TITLE
3.0 Purchase Confirmation: "No downloadable files" is showing list markup.

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#6765]
### Expected behavior
When a download has no files attached, a `<ul><li>` should be displayed that states:
`No downloadable files found.`
![image](https://user-images.githubusercontent.com/1390124/42706493-d6cbaa34-868b-11e8-8340-72ba13a094c3.png)

### Actual behavior
When a download has no files attached, a `<ul><li>` is be displayed that states:
`<li>No downloadable files found.</li>`
![image](https://user-images.githubusercontent.com/1390124/42706509-e513928c-868b-11e8-8a2d-563b775a0e22.png)

### Steps to reproduce the behavior
1) Purchase a product with no files available.

### Information (if a specific version is affected):
PHP Version: All

EDD Version (or branch): `release/3.0`

WordPress Version: All

Theme: Vendd

**Comment by sunnyratilal** [comment]
Fixed in https://github.com/easydigitaldownloads/easy-digital-downloads/commit/3dee1b627b40b8e3286833fbe21d7bb5d96cd73f.
