### ISSUE TITLE
3.0 Order List Table: Bulk deleting orders ends up in a weird list table state.

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#6766]
### Expected behavior
When bulk deleting orders, users should be returned to the order details page as if they just clicked on the 'Orders' menu item.

### Actual behavior
After bulk Deleting orders, I'm redirected to a page that shows an odd number of 'items', no pagination.
![image](https://user-images.githubusercontent.com/1390124/42711711-bc9c8c66-869d-11e8-9f4a-a6cb6f9c51c7.png)

### Steps to reproduce the behavior
1) From the Orders list table, select a number of items and use the bulk 'Delete' option.

### Information (if a specific version is affected):
PHP Version: All

EDD Version (or branch): `release/3.0`

WordPress Version: All

Any other relevant information:
It appears that the bulk action 'Apply' button is applying all of the filter items to the query string.

**Comment by sunnyratilal** [comment]
Fixed & merged.
