### ISSUE TITLE
Error: You must login to complete your purchase

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#6771]
## Bug Report

The `Error: You must login to complete your purchase` error message is shown even when guest checkout is enabled _and_ a purchase is being made with a brand new account.

### Expected behavior
When purchasing with a brand new account and guest checkout is enabled, an error about requiring registration or log in should _not_ happen.

### Actual behavior
New purchases cannot be made without registering or logging in.

### Steps to reproduce the behavior
1) Disable the requirement to register / log in
2) Enable the registration form on checkout (but make it optional)
3) Try to purchase something with a brand new account

**Comment by dgoldak** [comment]
Related ticket: https://secure.helpscout.net/conversation/619536170/85857?folderId=1847242
