### ISSUE TITLE
EDD 3.0 - Customer search no longer finds partial names

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#6774]
### Expected behavior
When searching for customer names, even a partial search should result in Customers being found.
EDD 2.9.x
![image](https://user-images.githubusercontent.com/1390124/42787086-c91a09e2-890d-11e8-843d-d176864224fb.png)

### Actual behavior
When searching for customers by name, only a full _exact_ match is returned.

`release/3.0`
![image](https://user-images.githubusercontent.com/1390124/42787100-de0708a0-890d-11e8-99c3-2256c566fdbe.png)
![image](https://user-images.githubusercontent.com/1390124/42787106-e6750bae-890d-11e8-927b-e3b84d0246b8.png)
![image](https://user-images.githubusercontent.com/1390124/42787128-f70c01e8-890d-11e8-9b0a-aa77f8d844b6.png)
![image](https://user-images.githubusercontent.com/1390124/42787157-1f30ceec-890e-11e8-84a8-b9f71a15dcb2.png)

### Steps to reproduce the behavior
1) Find a customer name to search by
2) Enter only last name (no results)
3) Enter only first name (no results)
4) Enter partial last/first name (no result)
5) Enter in full first and last name (results)

### Information (if a specific version is affected):
PHP Version: All

EDD Version (or branch): `release/3.0`

WordPress Version: All

**Comment by sunnyratilal** [comment]
Fixed in https://github.com/easydigitaldownloads/easy-digital-downloads/commit/7b83fb22019e22a19a00d0f905330141d4fae9a7.
