### ISSUE TITLE
3.0 Reports - Docs

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#6775]
### Explain your enhancement (please be detailed)
A link to a doc on our docs site regarding each of the EDD Core reports, how tiles work (trends vs static), what earnings means (what statuses are included in that), and other types of information that will demystify the reports screen would be ideal.

Since a lot of time and effort was put into making reports useful, let's be more clear about what reports contain.

### Justification or use case
Docs are good.

**Comment by ashleyfae** [comment]
Closed in favour of https://3.basecamp.com/4226849/buckets/12407027/todolists/3181435287
