### ISSUE TITLE
3.0 Reports - Downloads > Top selling downloads variable prices not being displayed

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#6776]
### Expected behavior
When viewing the Top selling downloads, variably priced products should be able to be distinguished.

### Actual behavior
It appears the variable price names are being cut off in the top selling downloads list:
![image](https://user-images.githubusercontent.com/1390124/42795057-13ed1058-8937-11e8-84ec-649d0e545848.png)

### Steps to reproduce the behavior
1) View Reports > Downloads
2) Have purchases in the range that make a variably priced product in the top 10.

### Information (if a specific version is affected):
PHP Version: All

EDD Version (or branch): `release/3.0`

WordPress Version: All

**Comment by cklosowski** [comment]
Also notice the 'price' is set to `$0.00` when in fact these do have prices on them.

**Comment by sunnyratilal** [comment]
@cklosowski Unable to replicate this: 
![image](https://user-images.githubusercontent.com/1525554/43051092-aabb69f2-8e0b-11e8-99ef-d0d92574d491.png)

Have the variable prices for the download been altered by any change such that the variable price at the index would no longer exist perhaps?

**Comment by SDavisMedia** [comment]
I'm also unable to replicate.

**Comment by cklosowski** [comment]
No alterations to the product. Brand new install. Onyl difference is I used the client generate orders. I'll try again.

**Comment by sunnyratilal** [comment]
@cklosowski Are you still seeing this?

**Comment by cklosowski** [comment]
@sunnyratilal Yes I experienced this today. Have you tried generating the orders via the WP CLI? Maybe that is the trigger?

**Comment by sunnyratilal** [comment]
Just generated the orders via CLI.

Before:
![image](https://user-images.githubusercontent.com/1525554/44616577-97101b80-a852-11e8-93e3-e14c116edf59.png)

After:
![image](https://user-images.githubusercontent.com/1525554/44616585-a55e3780-a852-11e8-8a64-4030c5711c50.png)

Still unable to replicate this issue.

@cklosowski Could you post a MySQL dump on Slack before/after you generate orders via CLI  and I'll see if I can figure out what the issue is.

**Comment by pippinsplugins** [comment]
This is working fine for me:
![image](https://user-images.githubusercontent.com/1034109/48108563-38c7c780-e209-11e8-84f4-20a1a5b29813.png)

**Comment by cklosowski** [comment]
This appears to be fixed, seems to have been related to `0` based indexes. I use the import file that exists in the `assets` folder of EDD, since it has data that replicates older EDD sites with price IDs at `0` instead of `1`.

I did go through and make a bunch of changes to places where we were incorrectly using the `index` instead of `price_id`, so that probably fixed it. Going to close this out now.
