### ISSUE TITLE
edd_cart_amount data attributes not updated when quantities change

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#6779]
### Expected behavior
When updating quantities, the cart total data attributes should be updated accordingly.

### Actual behavior
When updating cart quantities, the cart total data attributes are not updated.

### Steps to reproduce the behavior
_The easiest way to test is with Stripe and the Stripe Checkout modal enabled_
1) Enable Cart Quantities
2) Add an item to the cart
3) At checkout fill out the form and click complete purchase to open the Stripe Checkout Modal 
4) Close the Stripe Checkout modal and update the cart quantity
5) Verify all EDD checkout values look correct
6) Click to complete purchase and open the Stripe Modal
7) The total will not match the EDD total field

### Information (if a specific version is affected):
PHP Version: All

EDD Version (or branch): `master`

WordPress Version: All

Any other relevant information:
Chrome and Firefox 'inspector' do not show the update of the `data-` attributes when done this way, but the actual Code does, so you have to click through to get the Stripe Checkout modal to see it working.

**Comment by cklosowski** [comment]
@SDavisMedia this fixes a bug you reported for Stripe which made it so the Checkout Modal didn't have the correct value when quantities were updated.

**Comment by SDavisMedia** [comment]
Strange. This is hard to replicate now on `master`. I mean, it's easy to replicate if I re-open the modal before the EDD checkout has had the chance to update all the totals after changing the quantity. But as far as letting EDD totals update, then re-opening the modal, all seems well on `master`.

That said, I'm getting the same behavior on `issue/6779`. As long as the fact that the quantity change has adjusted EDD's totals, the modal is accurate. 

So I can't help but say it's working as expected. :+1:

**Comment by cklosowski** [comment]
@SDavisMedia was all that testing in Firefox? Can you test Chrome on `master` and `issue/6779`?

I know that sometimes Firefox does some weird stuff with inputs.

**Comment by SDavisMedia** [comment]
All good now. Simply couldn't replicate on my main test site. On another site, replicated on `master` and confirmed fixed on `issue/6779`. :+1:

**Comment by mintplugins** [comment]
Replicated on `master` and confirmed fixed on `issue/6779`. 

I tested 6 scenarios: 

- Stripe Checkout enabled
- Purchase with more-than-1 quantity 
- Purchase with quantities enabled & 1 quantity 
- Purchase with quantities disabled

- Stripe Checkout Disabled
- Purchase with more-than-1 quantity 
- Purchase with quantities enabled & 1 quantity 
- Purchase with quantities disabled

All went through as expected, with the Stripe modal showing the correct amount each time. Green light from me.
