### ISSUE TITLE
3.0 - Can't dismiss upgrade notices

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/easy-digital-downloads#6782]
### Expected behavior
When I click to dismiss a notice I expect the notice to be removed.

### Actual behavior
After dismissing the first notice, the other two are not able to be dismissed.

<img width="1311" alt="screen shot 2018-07-19 at 5 08 59 pm" src="https://user-images.githubusercontent.com/52581/42922801-786f917c-8b76-11e8-93ad-4cee54ff0ce3.png">

### Information (if a specific version is affected):
PHP Version:
7.2.1

EDD Version (or branch):
`release/3.0`

WordPress Version:
4.9.7

**Comment by amdrew** [comment]
Also, in the last box, `Please backup your` should be `Please back up your`.

https://en.wikipedia.org/wiki/Backup

> The verb form is "back up" (a phrasal verb), whereas the noun and adjective form is "backup".

**Comment by cklosowski** [comment]
Honestly we should just remove that if we can. They don't need to be 'dismissable'

**Comment by sunnyratilal** [comment]
@cklosowski I've removed the dismiss button for anything that removes the batch exporter: I wasn't 100% sure if this would break other things so I've requested your review before merging in.
