### ISSUE TITLE
3.0: Trying to get property of non object error on Reports > Downloads screen

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#6784]
The Reports > Downloads screen is showing me a bunch of non object errors:
<img width="1953" alt="screen shot 2018-07-23 at 8 33 34 am" src="https://user-images.githubusercontent.com/1034109/43079633-409b7a74-8e53-11e8-8347-14eb29442085.png">

Perhaps related: none of my products show up in the top selling table.

**Comment by sunnyratilal** [comment]
Fixed in https://github.com/easydigitaldownloads/easy-digital-downloads/commit/b0a6d683f7fb545ea58a44ac89a95670decbaa4c.
