### ISSUE TITLE
3.0: Misalignment of order filters when filters are added by extensions

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#6785]
<img width="1080" alt="screen shot 2018-07-23 at 8 59 15 am" src="https://user-images.githubusercontent.com/1034109/43081061-c4036bb2-8e56-11e8-8345-dc970bc5ab45.png">

**Comment by SDavisMedia** [comment]
❤️ so far

**Comment by cklosowski** [comment]
I feel like this is solved now in `release/3.0` with the UI update:
![image](https://user-images.githubusercontent.com/1390124/43861366-74aeca36-9b0b-11e8-9edb-2250a4b8fc49.png)

**Comment by SDavisMedia** [comment]
The new UI is indeed supposed to solve this issue, but is the implementation done yet? I thought it was still in progress when I played around with it a couple of days ago.

**Comment by JJJ** [comment]
I fixed it for software licensing specifically, at least.

If there are other add-ons that add stuff here, I can add some CSS for them. What's here now is pretty primitive, but I think should work _OK_ for most fields.

**Comment by sunnyratilal** [comment]
Closing as the implementation is done for this issue.
