### ISSUE TITLE
3.0 DB upgrades not all running properly

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/easy-digital-downloads#6786]
On `release/3.0` I've seen some columns that didn't get added or renamed.

@pippinsplugins and I both have experienced the `customer_id` column in `customermeta` not being renamed to `edd_customer_id`.

I'm seeing this:
`WordPress database error Unknown column 'date_modified' in 'field list' for query UPDATE wp_edd_customers`

Pippin saw this:
`WordPress database error Unknown column 'parent' in 'field list' for query INSERT INTO wp_edd_orders`

**Comment by cklosowski** [comment]
I saw this once with the `customers` table and `date_created`. I know @jjj fixed it up pretty quickly, do we have more cases where the default columns are being _assumed_ JJJ?

**Comment by JJJ** [comment]
>I saw this once with the customers table and date_created. I know @JJJ fixed it up pretty quickly, do we have more cases where the default columns are being assumed JJJ?
These are all fixed up now.

EDD does not make assumptions on primary columns anymore. Should be OK now.

**Comment by cklosowski** [comment]
Yesterday I went through the `master` -> `release/3.0` process and migration twice and never ran into this error anymore. I believe it would have been from an earlier alpha, going to close this for now as fixed.
