### ISSUE TITLE
3.0: Tax rates not calculated properly on Add New Order screen

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#6788]
When manually creating an order, the tax rates of items is calculated automatically, but it's not correctly using the billing address specified in the customer section.

For example, here's an order showing $0.25 to be attributed to tax, but this order shouldn't have any taxes since the address selected is not within the configured tax rates.
<img width="1672" alt="screen shot 2018-07-23 at 9 35 54 am" src="https://user-images.githubusercontent.com/1034109/43083362-ed81425c-8e5b-11e8-99fb-da44cbc0be1e.png">
<img width="1977" alt="screen shot 2018-07-23 at 9 36 01 am" src="https://user-images.githubusercontent.com/1034109/43083364-ed94f5d6-8e5b-11e8-8cbe-93043675cc5b.png">

Changing the customer address also does not appear to trigger a re-calculation of the tax rate.

**Comment by SDavisMedia** [comment]
While the UI does not update as expected, it does appear that the calculations are correct once the payment is saved.

**Comment by sunnyratilal** [comment]
Yeah; just need to add an AJAX call to fix this.

**Comment by sunnyratilal** [comment]
Fixed & merged.

**Comment by SDavisMedia** [comment]
Yup, working for me now.
