### ISSUE TITLE
3.0: Fatal error when creating new order for a new customer

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#6791]
## Bug Report

Creating a new customer and a new order triggers a fatal error when `Save Order` is clicked.

### Steps to reproduce the behavior
1) Go to Orders > Add New
2) Enter order details
3) Create a new customer
4) Click `Save Order`
4) The following is triggered:

>>>Fatal error: Uncaught Error: Call to a member function attach_payment() on boolean in /Users/pippin/Sites/edd/wp-content/plugins/easy-digital-downloads/includes/orders/functions.php:958 Stack trace: #0 /Users/pippin/Sites/edd/wp-includes/class-wp-hook.php(286): edd_add_manual_order(Array) #1 /Users/pippin/Sites/edd/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #2 /Users/pippin/Sites/edd/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #3 /Users/pippin/Sites/edd/wp-content/plugins/easy-digital-downloads/includes/actions.php(56): do_action('edd_add_order', Array) #4 /Users/pippin/Sites/edd/wp-includes/class-wp-hook.php(286): edd_post_actions('') #5 /Users/pippin/Sites/edd/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #6 /Users/pippin/Sites/edd/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #7 /Users/pippin/Sites/edd/wp-settings.php(450): do_action('init') #8 /Users/pippin/Sites/edd/wp-config.php(106): require_once('/Users/pippin/S...') #9 /Users/pippin/Sites/ed in /Users/pippin/Sites/edd/wp-content/plugins/easy-digital-downloads/includes/orders/functions.php on line 958

**Comment by cklosowski** [comment]
@sunnyratilal can you verify that this regression of Manual Purchases is fixed up with the merge into core?

**Comment by SDavisMedia** [comment]
For some reason I couldn't replicate this error. However, I'm noticing that the customer is created without a name, even though I entered one.

**Comment by sunnyratilal** [comment]
Fixed in https://github.com/easydigitaldownloads/easy-digital-downloads/commit/45764fff0d2d2b811786709ee6dca2cb591b2f6a.

**Comment by cklosowski** [comment]
I just tested this on `release/3.0` and it appears to be resolved now.

I Went to create a new order, and created a new customer and both the order and customer were successfully created.
