### ISSUE TITLE
3.0: edd_insert_payment hook is missing

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/easy-digital-downloads#6793]
In latest `release/3.0`, the `edd_insert_payment` hook does not run. I think we need some backwards compatibility for this, as we use it in our own add-ons quite a bit and I know of a few custom integrations off the top of my head that rely on it.

**Comment by cklosowski** [comment]
This one is critical to keep working @sunnyratilal @JJJ , could you please investigate to make sure this is in the unit tests as well (if possible?)

**Comment by sunnyratilal** [comment]
Yep, I'll ensure it's fixed.

**Comment by sunnyratilal** [comment]
Fixed & merged.
