### ISSUE TITLE
3.0: Add New Order cannot remove Order Item while editing

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#6796]
### Expected behavior
When I am manually adding a new Order, I expect to be able to remove an added item (product) before I save the payment. As in, if I accidentally add the wrong product to the order, I want to be able to remove it before I save the payment.

### Actual behavior
Once the product is added to the payment using the `Order Items` UI, it is not removable until the payment has been saved and revisited.

### Steps to reproduce the behavior
1) Go to Downloads -> Orders -> Add New (button) to add a new Order,
2) Click the `Add Item` button to add a new product to the `Order Items` table. Choose a product from the select menu and click the `Add` button to fully add the product to the Order.
3) Observe the face that once the product is part of the table as added, it cannot be removed.

### Information (if a specific version is affected):
EDD Version (or branch): `release/3.0`

**Comment by sunnyratilal** [comment]
Fixed.
