### ISSUE TITLE
3.0: Totals in transaction table incorrect

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/easy-digital-downloads#6798]
In latest `release/3.0`, when purchasing an item, the total in the transaction row in `wp_edd_order_transactions` is incorrect. It's stored as `0.000000000` instead of the amount of the transaction.

**Comment by sunnyratilal** [comment]
Fixed in https://github.com/easydigitaldownloads/easy-digital-downloads/commit/24d020b2cfec3fcfb97103f522448c7c675409d8.

**Comment by mintplugins** [comment]
This is happening again.

**Comment by mintplugins** [comment]
Confirmed fixed
