### ISSUE TITLE
Add date generated to system info

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#6799]
### Explain your enhancement (please be detailed)

I would like to see a `Date Generated: yyyy-mm-dd H:i:s` added to the bottom of the system info file.

### Justification or use case

Occasionally we get old copies of the system info file that makes the file not very helpful. By adding the date the file was generated, support techs can know for certain if it's an up to date version of the system info.

**Comment by cklosowski** [comment]
:+1: for using the Enhancement template. ;)

**Comment by spencerfinnell** [comment]
Attached a PR for this. I added it to the start to reduce unneeded scrolling. 😛 Can put it at the bottom if you want though.
