### ISSUE TITLE
3.0: Order History date range filters not working properly

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/easy-digital-downloads#6800]
### Expected behavior
When filtering by date range, orders from that date range should only be shown.

### Actual behavior
Orders that fall outside the range are shown, both before the start date and after the end date.

### Steps to reproduce the behavior
1) Go to Downloads > Orders
2) Filter the view by date range, for example: 2018-07-01 to 2018-07-21
3) Note that orders before and after those dates are shown

![image 2018-07-26 at 11 13 36 am](https://user-images.githubusercontent.com/1254870/43271267-15d79b32-90c5-11e8-8e35-75a635eac7c4.png)

![image 2018-07-26 at 11 13 02 am](https://user-images.githubusercontent.com/1254870/43271271-18853aa6-90c5-11e8-976a-1084791cf856.png)

### Information (if a specific version is affected):
EDD Version (or branch): latest `release/3.0`

**Comment by sunnyratilal** [comment]
Fixed in https://github.com/easydigitaldownloads/easy-digital-downloads/commit/ab546f4206aab109cef6f3998d37c7c1066be606.
