### ISSUE TITLE
3.0: Order History amount filter doesn't allow floats

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/easy-digital-downloads#6801]
### Expected behavior
The amount filter should accept floats, like `80.10`.

### Actual behavior
It does not. It prompts to enter a valid value.

### Steps to reproduce the behavior
1) Go to Downloads > Orders
2) Click the More button to expose the amount filter
3) Enter a float amount and try to filter

![image 2018-07-26 at 11 26 35 am](https://user-images.githubusercontent.com/1254870/43272049-0dd93a6a-90c7-11e8-85f6-74cf76ed21bd.png)

### Information (if a specific version is affected):
EDD Version (or branch): latest `release/3.0`

**Comment by sunnyratilal** [comment]
Fixed in https://github.com/easydigitaldownloads/easy-digital-downloads/commit/45302e7d4839a15b7571278afe5bb32e65ab284f.
