### ISSUE TITLE
3.0: Order History filter by country doesn't work as expected

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/easy-digital-downloads#6802]
### Expected behavior
When filtering orders by country, only orders from that country should be shown.

### Actual behavior
Orders from other countries are shown. The view is filtered in some fashion, though I'm not sure what's being filtered out yet.

![image 2018-07-26 at 11 36 50 am](https://user-images.githubusercontent.com/1254870/43272649-85bda736-90c8-11e8-9f2a-e98180f3fed4.png)

![image 202018-07-26 20at 2011 36 18 20am](https://user-images.githubusercontent.com/1254870/43272655-883c028c-90c8-11e8-83df-d6c63c3fb22d.png)

![image 2018-07-26 at 11 38 01 am](https://user-images.githubusercontent.com/1254870/43272657-8ab8d350-90c8-11e8-9957-dbfbc9299c63.png)

### Steps to reproduce the behavior
1) Go to Downloads > Orders
2) Filter by Canada
3) See orders not from Canada

### Information (if a specific version is affected):
EDD Version (or branch): `release/3.0`

**Comment by sunnyratilal** [comment]
Fixed in https://github.com/easydigitaldownloads/easy-digital-downloads/commit/ab546f4206aab109cef6f3998d37c7c1066be606.
