### ISSUE TITLE
3.0: Order history search returns all results when no matches found

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/easy-digital-downloads#6803]
### Expected behavior
When searching for something, if there are no relevant matches, I expect to see no search results.

### Actual behavior
All results are returned instead. This is a regression from 2.9.x behavior.

### Steps to reproduce the behavior
1) Go to Downloads > Orders
2) Search for `this won't match anything`
3) See all orders instead of no orders.

### Information (if a specific version is affected):
EDD Version (or branch): `release/3.0`

**Comment by mindctrl** [comment]
Related: searching for a customer by name returns all results instead of the orders for the desired customer.

**Comment by mintplugins** [comment]
This is happening again.

**Comment by cklosowski** [comment]
I'm pretty sure search is just not working in general here now @mintplugins I'll dig in and figure this out.

**Comment by mintplugins** [comment]
Confirmed fixed.
