### ISSUE TITLE
3.0: Order discount adjustments are stored with a value of 0

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/easy-digital-downloads#6804]
### Expected behavior
When using a coupon on an order, the adjustment entry should reflect the amount of the discount.

### Actual behavior
The amount is stored as `0.000000000`.

### Steps to reproduce the behavior
1) Make a purchase with a discount
2) Check the row in `wp_edd_order_adjustments`.

![image 2018-07-26 at 12 37 03 pm](https://user-images.githubusercontent.com/1254870/43275759-b5ff3574-90d0-11e8-83b0-5af2ca3a0226.png)

![image 2018-07-26 at 12 38 03 pm](https://user-images.githubusercontent.com/1254870/43275791-cbc6a46e-90d0-11e8-8e66-e3c40c0ca56f.png)

### Information (if a specific version is affected):
EDD Version (or branch): `release/3.0`

**Comment by sunnyratilal** [comment]
Fixed in https://github.com/easydigitaldownloads/easy-digital-downloads/commit/dbf258aee119731c3e563f8268eeb8ee5dac0df7

**Comment by sunnyratilal** [comment]
Oops, that just fixed the list table.

**Comment by sunnyratilal** [comment]
Database now stores the correct value too.
