### ISSUE TITLE
3.0: Issues with programmatic discount creation

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/easy-digital-downloads#6806]
#### Actions/Filters
When creating a discount programmatically with `edd_add_discount()`, the actions/filters that ran in 2.9x should still run in 3.0. Those are:
- [x] `edd_insert_discount`
- [x] `edd_pre_insert_discount`
- [x] `edd_post_insert_discount`

Related to action/filters, in `EDD_Discount:add()` the `@since` notation for the `edd_insert_discount` filter was updated to say `@since 3.0`, but it should remain `@since 2.7`.

---
#### Discount status
Also, the default status is no longer `active`. If you do not pass a status to `edd_add_discount()`, the new discount is stored as `draft`.

---
#### Duplicate discount codes
Also, and this part is not a regression but I think we should handle it now while we're here, there is nothing preventing duplicate discount codes from being created programmatically. EDD's admin UI prevents it, but that's the wrong place in the stack to do it. We should prevent the duplication in the method that does the insertion.

### Actual behavior
The actions and filters do not run.

The default status should be `active`

### Steps to reproduce the behavior
Run this code:
```
	$did = edd_add_discount(
		[
			'code' => '3dd-edd-add-discount-1',
			'name' => '3DD edd_add_discount_1',
			'amount' => 10,
			'amount_type' => 'percent'
		]
	);
```

Note that:
- the actions/filters listed above don't run
- the status of the newly created code isn't `active`
- running it multiple times results in duplicate discount codes

### Information (if a specific version is affected):
EDD Version (or branch): `release/3.0`

**Comment by mindctrl** [comment]
Also, when the discount has a status of `draft`, this is not reflected in the edit UI because the dropdown only has `active` and `inactive`, so the edit screen will show it as `active` even though the list table shows it as `draft`. I'm assuming `draft` should be `inactive` in this case.

**Comment by mindctrl** [comment]
It would also be great to phpdoc all the accepted args on `edd_add_discount()`.

**Comment by mindctrl** [comment]
The `uses` array key is no longer working. In 3.0 it must be `use_count` to work.

**Comment by mindctrl** [comment]
In the arguments array, `start` and `expiration` are no longer used. It must be `start_date` and `end_date`. That's definitely better naming, but do we want to make this new function work with the old args too?

**Comment by cklosowski** [comment]
We should 100% write some `if/then` logic to detect the old args/properties. That way anyone attempting to use the old values still get things created. We could even throw some warnings into the debug log about the new naming convention to bring it to light.

**Comment by sunnyratilal** [comment]
There is a static method in `EDD_Discount` that I created called `convert_legacy_args` that handles what you said, @cklosowski.

[`edd_add_discount()`](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/admin/discounts/discount-actions.php#L23) existed prior to 3.0 for creating discounts on the admin side. It hooked on to `edd_add_discount`.  In 3.0, we've renamed this method to `edd_admin_add_discount` and `edd_add_discount` has been repurposed to match the naming convention for all other objects @JJJ and I have introduced.

We decided that `edd_store_discount()` would handle legacy arguments and `edd_add_discount()` would work similarly to the new object creation methods.

Anything you pass to `edd_store_discount()` continues to work how it did in 2.9; it takes the legacy arguments, converts them, and then passes them to `edd_add_discount()`.

I can address the other bits that you mentioned, @mindctrl.

**Comment by sunnyratilal** [comment]
I don't agree with the default status being `active`. The orders table sets the default status as `pending`. Similarly, `wp_insert_post()` sets the default status as `draft`.

For regression purposes, I'll set the default status as `active` if anyone is using `edd_store_discount()` but it should remain as `draft` if using `edd_add_discount()` (the new method) for adding discounts.
