### ISSUE TITLE
3.0: Improve discount code bulk deletion messaging

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/easy-digital-downloads#6807]
### Expected behavior
In 3.0 if a discount has been used, the UI doesn't allow you to delete it. Great. However, when using bulk actions, if you select discounts that have been used and select Delete from the list, the page reloads and gives no indication that the codes were not deleted.

It would be nice to show a message to indicate that they were not deleted.

### Information (if a specific version is affected):
EDD Version (or branch): `release/3.0`

**Comment by sunnyratilal** [comment]
9ab4a0895ea1c35859dd54e310544f32ec5bcc0f

**Comment by sunnyratilal** [comment]
After a discussion in Slack with @JJJ, we've decided the best way of moving forward with this is to disable the checkbox if a discount cannot be deleted. It makes sense in terms of UX and a message has been added to the checkbox via the `title` attribute to let the user know why the checkbox has been disabled.
