### ISSUE TITLE
3.0 - Taxes: From/To/Action fields show incorrectly when no tax rates have ever existed.

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#6814]
### Expected behavior
Tax rates should show the from and to fields when no tax rates have existed.

### Actual behavior
When you go to enter tax rates for the first time (does not replicate if you delete all tax fields, but that's for a new issue), the to and from fields do not show:

![image](https://user-images.githubusercontent.com/1390124/43426443-80d7b352-940a-11e8-9ada-219703608735.png)

### Steps to reproduce the behavior
1) On a new install, visit the tax rates area.

### Information (if a specific version is affected):
PHP Version: All

EDD Version (or branch): `release/3.0`

WordPress Version: all

Any other relevant information:
If you have previously entered in tax rates, you would need to go into the `edd_adjustments` table and delete all tax rate adjustments.

**Comment by sunnyratilal** [comment]
Fixed in #6819.
