### ISSUE TITLE
Better handling of extension checking for remote URLs

### ISSUE THREAD

**Issue by polevaultweb** [easydigitaldownloads/easy-digital-downloads#6817]
### Explain your enhancement (please be detailed)

I'm using EDD (and Easy Digital Downloads - Free Download) with WP Offload S3 which swaps out local file URLs with secure URLs from S3. But this means that the file extension is incorrectly detected with `edd_get_file_extension()` as there is a query string after the extension, e.g. `.pdf?secure=blah`

This means the `edd_get_file_ctype()` is always incorrectly determined as `application/force-download`.

It would be great to have a filter on the return value of `edd_get_file_extension()` or better still remove query strings by default in that function.

**Comment by cklosowski** [comment]
Thanks for the report @polevaultweb I'll see if we can get that worked in. I think it'd best exist in EDD Core, and allow for both a filter and better detection of things with query strings. :+1:
