### ISSUE TITLE
3.0: fresh install requires multiple database upgrades

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#6824]
### Expected behavior
When I install 3DD fresh on a new site, I expect the database schema to be configured and ready for use.

### Actual behavior
When I install 3DD fresh on a new site, I am required to run `customer`, `payment` (twice), `API Key`, and `file download logs` database upgrades.

<img width="662" alt="image 2018-08-02 at 5 13 37 pm" src="https://user-images.githubusercontent.com/2359131/43617525-70af56b4-9677-11e8-8e95-5c2fb10dbf43.png">

### Steps to reproduce the behavior
1) Install and activate EDD 3.0 on a brand new site that has never had EDD activated before.
2) The upgrade nags should display through admin.

### Information (if a specific version is affected):
EDD Version (or branch): `release/3.0`

### Any other relevant information:
It _appears_ that the database structure is correct already without running the upgrade routines:
![screenshot_2018-08-02 database local - adminer](https://user-images.githubusercontent.com/2359131/43617559-c76998ac-9677-11e8-80ee-5c526d954947.png)

**Comment by cklosowski** [comment]
Just a note, I'm also seeing this on a fresh install

**Comment by cklosowski** [comment]
I think this and #6825 are directly related. The installation of the pages (#6825) and this issue of marking past upgrades as 'completed' on new installs are all part of the `edd_run_install` function. I'll see if I can work out why this isn't running.

**Comment by sunnyratilal** [comment]
I think it may be to do with `register_activation_hook( EDD_PLUGIN_FILE, 'edd_install' );` and the fact that we moved the `Easy_Digital_Downloads` class to `includes/class-edd.php`?

**Comment by cklosowski** [comment]
@sunnyratilal yeah that would be the reason, the call to `register_activation_hook` is inside the plugins loaded work, so it isn't able to call it, we'd have to have the inclusion in the main file I think.

I've read somewhere that the inclusion of the register activation hook needs to be outside of any logic in order to work correctly. Which means the include to the file `install.php` and the call to `register_activation_hook` needs to be outside of the loading. I could be wrong, but I've seen that cause problems in the past.

**Comment by sunnyratilal** [comment]
Yeah according to https://codex.wordpress.org/Function_Reference/register_activation_hook, R
registering the hook inside the `plugins_loaded` hook will not work.

**Comment by sunnyratilal** [comment]
This could be quite complex to solve because `edd_install()` calls certain functions such as `edd_set_upgrade_complete()` and `edd_create_protection_files()` so if we call `register_activation_hook()` in the `EDD_Requirements_Check` class, it'll fatal because Core wouldn't be loaded at that point.

**Comment by sunnyratilal** [comment]
Fixed in eb3fa480aa1d0186897ed17fa5c307ad1a56bf0e and fbe146b9c3b7d8f536b004e131b1457a04e56beb.
