### ISSUE TITLE
3.0: plugin pages not created on fresh install

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#6825]
### Expected behavior
When I install 3DD fresh on a new site, I expect the default [plugin pages](https://docs.easydigitaldownloads.com/article/625-plugin-pages) to be created. 

### Actual behavior
When I install 3DD fresh on a new site, the plugin pages are not created. And therefor, the EDD page settings aren't properly configured, triggering an admin notice about the Checkout page not being configured

### Steps to reproduce the behavior
1) Install and activate EDD 3.0 on a brand new site that has never had EDD activated before.
2) You should see an admin notice about the Checkout page needing to be configured, indicating the fact that the page (and its buddies) does not exist.

### Information (if a specific version is affected):
EDD Version (or branch): `release/3.0`

**Comment by cklosowski** [comment]
Just a note, I'm also seeing this on a fresh install

**Comment by sunnyratilal** [comment]
We didn't change anything with `register_activation_hook()` or `edd_run_install()`. Maybe it has something to do with hooking `EDD` on to `plugins_loaded`?

**Comment by sunnyratilal** [comment]
Fixed in eb3fa480aa1d0186897ed17fa5c307ad1a56bf0e and fbe146b9c3b7d8f536b004e131b1457a04e56beb.
