### ISSUE TITLE
3.0: Reposition Download Settings metabox tooltips

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#6826]
Currently in `master`, the Download Settings metabox on the download edit screen looks a bit rough and can be difficult to follow in certain cases. The tooltips are jagged, because they display at the ends of setting labels, which vary in length. Furthermore, some of the tooltips describe an entire section of the metabox, though they display beside content that needs explaining. Depending on your perspective, that can be confusing.

What I want to do for 3.0 is reposition the Download Settings tooltips to always be right-aligned and in the heading of a section. And from there, whether a section has one setting, or multiple settings, the tooltip can explain them all piece by piece.

This enhancement depends on 3.0.

**Comment by SDavisMedia** [comment]
![screenshot_2018-08-03 edit download edd3 wordpress](https://user-images.githubusercontent.com/2359131/43652946-7e8946c6-96fb-11e8-997e-062950eb72df.png)

**Comment by JJJ** [comment]
Yup. Way better. Merged!
