### ISSUE TITLE
3.0: Reset Tool is broken

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#6831]
### Expected behavior
Using the reset tool in `Tools -> Recount Stats` should remove all articles of customers and orders from the EDD site. 

### Actual behavior
Customers and orders are all still present.

### Steps to reproduce the behavior
1) In Tools > General from the `Recount Stats` section choose 'Reset Store'
2) Check the box and run the reset.

### Information (if a specific version is affected):
PHP Version: All

EDD Version (or branch): `release/3.0`

WordPress Version: All

Any other relevant information:

**Comment by pippinsplugins** [comment]
Pretty sure this broke as a result of #6977

**Comment by cklosowski** [comment]
@pippinsplugins it broke long before that. Now it's just double broken, b/c the AJAX Batch/Export processor isn't being loaded.

I'll fix both of those up at the same time.

**Comment by cklosowski** [comment]
Been thinking about this, now that everything is custom tables, couldn't we just truncate the tables and reset the auto-increment attribute on the tables?

This would make our reset tool go SUPER fast, only issue there is that we would have to fix our reset tool integration for extensions as well, but those are mostly custom tables (SL and Commissions) so those would be super fast as well.

@JJJ a truncate wouldn't even need to use the AJAX process would it?

**Comment by cklosowski** [comment]
I think we'll move forward with using a `truncate` command, we'll just have to put hooks in place to allow other extensions to truncate their tables as well.

**Comment by cklosowski** [comment]
I'd love a review of this, to see if this is the approach we want to take with the reset tool, instead of sticking with the ID based deletion.

**Comment by mintplugins** [comment]
Testing now

**Comment by mintplugins** [comment]
@cklosowski Should this still be doing "steps" in ajax?

**Comment by cklosowski** [comment]
@mintplugins yes, it's doing it per table to truncate.

**Comment by mintplugins** [comment]
Working here for me.

**Comment by pippinsplugins** [comment]
Everything working here for me. Merging.
