### ISSUE TITLE
3.0: Adding new tax rate does not allow 'To' and 'From' Chosen fields to be triggered.

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#6833]
### Expected behavior
When I add a new tax rate, I expect the 'To' and 'From' fields to trigger the chosen date picker.

### Actual behavior
Adding a new tax rate should allow the 'To' and 'From' fields to trigger the chosen date picker.

### Steps to reproduce the behavior
1) View the Tax Rates section.
2) Click 'Add Tax Rate'
3) Click on the 'To' or 'From' fields.

### Information (if a specific version is affected):
PHP Version: All

EDD Version (or branch): `release/3.0`

WordPress Version: All

**Comment by sunnyratilal** [comment]
I'm not sure I understand the bug here?

This is what happens I click on the `To` and `From` fields:
![image](https://user-images.githubusercontent.com/1525554/43887997-46dd36ee-9bb8-11e8-96c0-aeb8421f2bc6.png)

**Comment by cklosowski** [comment]
That is an existing tax rate. On that same page click "Add Tax Rate", and on the new line you're creating, the To and From don't trigger the chosen fields. The rows that existed on the page load work, but clicking to add a new one does not allow them to be triggered.

**Comment by sunnyratilal** [comment]
Fixed & merged.
