### ISSUE TITLE
3.0: Order Adjustments are added for orders with no tax on them (only when taxes enabled)

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#6834]
### Expected behavior
When a purchase is made that does not have a tax rate, but taxes are enabled, no entries should be made for the order items in the `order_adjustments` table.

### Actual behavior
When a purchase is made that does not have a tax rate, but taxes are enabled, a row is entered with `0.000000000` for the values:
`2503	5032	order_item	0	tax_rate	""	0.000000000	0.000000000	0.000000000	2018-08-07 19:09:38	2018-08-07 19:09:38	urn:uuid:7f1f4d0f-1683-4f18-942e-d2af38e87bed`

### Steps to reproduce the behavior
1) Enable Taxes
2) Make a purchase that does not include tax
3) View the database to see a new `order adjustment` for the items in the purchase made in step 2, with all `0.000000000` values.
etc, etc

### Information (if a specific version is affected):
PHP Version: All

EDD Version (or branch): `release/3.0`

WordPress Version: All

**Comment by sunnyratilal** [comment]
Fixed & merged.
