### ISSUE TITLE
Discounts can be saved but not created with 0 as an amount.

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#6849]
### Expected behavior
When I create a new discount, I should be able to set the amount to `0`.

### Actual behavior
When I try and create a new discount with a value of `0`, an error is prompted.

### Steps to reproduce the behavior
1) Go to the Add new Discount screen
2) Enter in any values you want but for the `Amount` set the value to `0`.
3) Click 'Add Discount Code`
4) See error.
5) Set the amount to `1`
6) Click 'Add Discount Code'
7) You'll be directed back to the discount list.
8) Edit the same discount you just created.
9) Set the `Amount` to `0`.
10) Click 'Update Discount Code'
11) The discount will save and be updated.

### Information (if a specific version is affected):
PHP Version: All

EDD Version (or branch): `master` and `release/3.0`

WordPress Version: All

Any other relevant information:
For what it's worth, I think we should allow the `0` discount amount as there can be a number of ways discounts are used (like the negative discounts). For instance the person reporting this wanted a discount code so they could not give a discount, but to 'claim a free book' to be shipped to the customer.

**Comment by sunnyratilal** [comment]
Fixed & merged.
