### ISSUE TITLE
Update the plugin updater bundeled in EDD

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#6850]
### Explain your enhancement (please be detailed)
Update the plugin updater to the latest version.

### Justification or use case
To keep the newest changes that are distributed with SL, in EDD core.

**Comment by SDavisMedia** [comment]
Tested this change to the updater in relation to SL https://github.com/easydigitaldownloads/EDD-Software-Licensing/issues/1405 Replicated the original problem there and confirmed that the new approach resolves the issue. :+1:

**Comment by cklosowski** [comment]
Reopening after some changes, will submit a new PR. It was causing the health check on every page load in admin.

**Comment by cklosowski** [comment]
Related PR within the SL repo: https://github.com/easydigitaldownloads/EDD-Software-Licensing/pull/1429

**Comment by SDavisMedia** [comment]
I ran through the same tests that we did for SL: https://github.com/easydigitaldownloads/EDD-Software-Licensing/issues/1405#issuecomment-413344305

All is well still. :+1:
