### ISSUE TITLE
Implementing CSS Grid (and keeping CSS floats)

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/easy-digital-downloads#6852]
It's CSS Grid time 🎉 

PR: https://github.com/easydigitaldownloads/easy-digital-downloads/pull/6939

## Why we should implement CSS Grid

1. CSS Grid is well supported: https://caniuse.com/#feat=css-grid
1. It will eventually allow us to move away from our current implementation of CSS floats
1. It will cut down our CSS (once floats are removed), and allow us to do some interesting things in the future
1. We've been slowly working towards it for quite some time. https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6808, https://github.com/easydigitaldownloads/easy-digital-downloads/issues/3489, https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5847
1. It will allow for better designed themes
1. EDD Blocks (https://github.com/easydigitaldownloads/edd-blocks) will have blocks for outputting a grid of downloads, download categories, and possibly download tags (or 1 block for all). Since the Gutenberg block(s) will eventually exist in EDD core, now's a good time to refactor the CSS and move ourselves into the future of layout.
1. It fixes an issue where the download grid is slightly indented and does not align with headings and other elements around it. This is caused by each download having padding and margin to space themselves apart. Usually a workaround (which we don't do in core) is to use negative margins on the main wrapping div. CSS Grid has a gap property for spacing, but the gaps are only in between each item in the grid meaning everything aligns nicely.
1. We'll be implementing a mobile-first approach. With the current implementation of floats we don't account for mobile devices. Downloads overlap each other at smaller device widths, making things illegible. This time around we stack the downloads, then expand into columns at larger device widths. Note, while we could also fix the floating issue in this PR (which would probably mean slightly more code), I think we should leave the current implementation exactly as-is, solely focusing on CSS grid going forward.

## Goals

1. Keep the existing HTML markup to avoid any disruption
1. Use CSS Grid for modern browsers while still using floats for crappy browsers (IE10 and below)
1. Get us in the position to drop floats completely when the time is right

## How it works

- An older browser sees the current implementation of CSS floats and uses that for the layout.
- Modern browsers will see floats _and_ CSS Grid, preferring the latter. When `display: grid` is set on the parent `div`, any `float` or `clear` property is completely ignored.
- All downloads are stacked (mobile-first approach) until the 768px breakpoint grid, where they are then displayed in a 2 column layout (except for when `columns="1"` is defined in the shortcode). Once the browser width reaches the 1200px breakpoint, the true column count is used.
- The `@supports` feature query is used to tell modern browsers to reset any widths, margin or padding. Widths interfere (since we're using the `fr` unit) with the download grid and there's no longer a need for margin and padding on each individual download.

## Other notes

- Tested with modern browsers
- Tested with IE10 (will use floats) and IE11 (will use CSS Grid)
- Vendd overrides widths based on the column class used. Because of the CSS specificity, it will override the `width: auto` rule added to reset the widths. All Vendd will need is to remove the widths and it's method of using `display: inline-block`. It can use CSS grid and floats will be provided as a fallback.
- This PR relies on what is happening in https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6808. The pagination can't be a sibling of the downloads.
- This should be tested thoroughly with other themes just in case.

## Caveats

There is a _slight_ issue when specifying a 6 column layout in EDD, i.e . E.g.`[downloads columns="6"]`. 

With the current implementation of CSS floats and using the Twenty Sixteen theme, here's the 6 column layout:

<img width="901" alt="screen shot 2018-08-14 at 6 34 01 pm" src="https://user-images.githubusercontent.com/52581/44075379-b71ac91c-9ff0-11e8-9514-2f430ad5485a.png">

Everything is bunched up and doesn't look great at all. But it "stays" (well mostly) within the confines of the div.

With CSS grid, 6 columns looks like the following, slightly overflowing outside of the div since there's not enough space inside:

<img width="1051" alt="screen shot 2018-08-14 at 6 30 18 pm" src="https://user-images.githubusercontent.com/52581/44075240-22f09780-9ff0-11e8-84e5-4b945d06910a.png">

This _can_ be fixed using a combination of CSS Grid's `minmax() function`, and either `auto-fit` or `auto-fill`, but not for our use-case (which is why I'm also using media queries at all). We need to specifically set the number of columns chosen by the user.

In any case, I see this as a non issue for 3 reasons:

1. Showing 6 columns is not exactly common (I don't think we support it in either Vendd or Themedd). Themes like Twenty Sixteen have narrow widths.
2. It looks better (even though it overlaps) than the existing float technique we use.
3. If you're really going to show 6 columns of downloads, the theme should provide ample space.

## How CSS Grid looks

Here's how each download grid with a column set looks with the Twenty Sixteen theme. Ignore the black line, that's caused by the full-page screenshot:

![screenshot_2018-08-14 grid test twentysixteen](https://user-images.githubusercontent.com/52581/44075726-f3b66fd8-9ff1-11e8-9a02-3e8ce6fcbe20.jpg)

Sidenote: we should add some CSS in the future to reset any top margins on h3 headings within the download grid (as seen by the large space above each heading above).

And finally, Firefox has an amazing Grid inspector for testing/viewing grids:

![screen recording 2018-08-14 at 06 47 pm](https://user-images.githubusercontent.com/52581/44076007-c09ef2f4-9ff2-11e8-81a2-4e8f03eaa449.gif)

**Comment by amdrew** [comment]
@SDavisMedia @cklosowski Updated the PR now that the pagination has been merged into master. Just the one CSS file to gawk at. Will be running my eyes over this again but otherwise ready for testing.

**Comment by cklosowski** [comment]
@amdrew My upfront reaction is since it's such a drastic change to the thinking of how we build the download grid, it should be a 3.0 thing.

Ideally it wouldn't matter since it appears as though it's fully backwards compatible, but it would be a nice thing to give in a major release so that people 'expect' changes like this in a major, instead of a minor.

**Comment by amdrew** [comment]
@cklosowski My thoughts as well, will re-submit against 3.0 👍

**Comment by amdrew** [comment]
New PR: https://github.com/easydigitaldownloads/easy-digital-downloads/pull/6939
