### ISSUE TITLE
Cart contents price is incorrect when using fees

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/easy-digital-downloads#6859]
# Description:
When you attach a fee in EDD to an item, the $item['price'] is set incorrectly. This causes:
- Order report totals to be wildly incorrect
- Extensions that utilize this feature get the wrong numbers (which if fed into accounting systems or used in tax audit software (to save an independent-of-edd-record) or to back calculate taxes paid (to say generate the taxes to pay to a state)) will be completely wrong

# Instructions (to replicate):
To make this easy, I'm going to use Discounts Pro, but this affects *all EDD Fees* it does not require Discounts Pro.

1. Install Discounts Pro
2. Make a download with a price of $20
3. Give this download a $20 discount in Discounts Pro
4. Hook into edd_payment_saved (picked for simplicity in testing, any hook works, even non-hooks, ie new EDD_Payment also works).
5. Dump $payment_meta = edd_get_payment_meta( $payment_id );
 in this data, $payment_meta['cart_details'] is the cart details, which contains the prices of each product. For each product in the cart details $item['price'] is supposed to contain the "net" (post-tax, post-discount) number for the product ($item['item_price'] contains the pre-number)

Notice, that despite the order being free, and the Fee being directly applied to the product, and the cart details item information having that fee there as -20, it still shows it as $20.

![image](https://user-images.githubusercontent.com/1324637/44251745-8531d700-a1c7-11e8-8fd0-3b9121e5850e.png)

Now, repeat this, but instead of using a fee (turn discounts pro off) use a discount code. Note how this adjusted to the correct ($0).

### Information (if a specific version is affected):
I've tested EDD versions between 2.9.4 and 2.6.0. They all seem to have this issue.

This is not a big deal to fix, but it needs to be fixed. And ideally there needs to be a routine that goes through previous orders (we could do this on the 3.0 since we're already migrating them, we could fix them as we insert them), and fixes this.

**Comment by chriscct7** [comment]
Fixing this would notably also solve other issues like #4708

**Comment by chriscct7** [comment]
The usecase of a non-shipping EDD Fee also breaks commissions

**Comment by chriscct7** [comment]
Actually we might be even able to get away with not doing fix retroactively if its not stored. The formula broken is here: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/payments/class-edd-payment.php#L1150 it just needs a - $fees literally.

**Comment by chriscct7** [comment]
So the new formula would be `$total = $subtotal - $discount + $tax - $args['fees']`

**Comment by dancameron** [comment]
I just proposed a pull request. I think it's rather simple change that will solve **a lot** of issues for me, since I'm using fees instead of discounts.

Also, when you review this PR I suggest a filter of the item array.

**Comment by chriscct7** [comment]
Dan's patch also seems to resolve #4708 as well which is a bug caused by this ticket's same issue (just another way it causes an issue). After application & rerunning the totals tools, the graphs are seemingly accurate now with discounts applied.

**Comment by chriscct7** [comment]
Since we're planning to re-run the totals as part of the 3DD migration anyways, we can just merge this patch, close this ticket and #4708 and call it a day 👍

**Comment by JJJ** [comment]
The pull-request at #6969 fixes this issue for me.

+1 to merge to `master` as the PR suggests, and I can merge from `master` into `release/3.0`.
