### ISSUE TITLE
3.0: WordPress database error Unknown column 'date_refundable' on admin load

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#6867]
When I load the wp-admin on latest `release/3.0`, I see a series of SQL errors stating `WordPress database error Unknown column 'date_refundable'`.

![image](https://user-images.githubusercontent.com/1034109/44560696-94a8a700-a716-11e8-9194-a8502cb11298.png)

**Comment by pippinsplugins** [comment]
This is happening because my tables don't have a `date_refundable` column:
```php
/**
	 * Upgrade to version 201807270003
	 * - Add the `uuid` varchar column
	 *
	 * @since 3.0
	 *
	 * @return boolean
	 */
	protected function __201807270003() {

		// Look for column
		$result = $this->column_exists( 'uuid' );

		// Maybe add column
		if ( false === $result ) {
			$result = $this->get_db()->query( "
				ALTER TABLE {$this->table_name} ADD COLUMN `uuid` varchar(100) default '' AFTER `date_refundable`;
			" );
		}

		// Return success/fail
		return $this->is_success( $result );
	}
```

**Comment by pippinsplugins** [comment]
Only the orders table should have a `date_refundable` column I believe. It should be AFTER `date_modified`.

**Comment by sunnyratilal** [comment]
Merged.
