### ISSUE TITLE
3.0: Unable to add discount codes

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#6871]
When trying to create a discount code, a generic error is returned `There was a problem adding that discount code, please try again.`.

It does not appear to matter which fields are or are not filled in.

**Comment by pippinsplugins** [comment]
This looks to be happening partially because the following array keys are passed into the `insert()` method instead of being stripped:

- 'start_date_minute'
- 'start_date_hour'
- 'end_date_minute'
- 'end_date_hour'

They need to be stripped in the  `edd_admin_add_discount()` function.

**Comment by sunnyratilal** [comment]
Fixed.

**Comment by pippinsplugins** [comment]
@sunnyratilal sorry, still doesn't work for me. Same error.

**Comment by sunnyratilal** [comment]
I wonder if it's because the database table is outdated?

@pippinsplugins Could you confirm that you have all of these columns, please?

![image](https://user-images.githubusercontent.com/1525554/44658026-fe66d080-a9f6-11e8-8bff-90f3ca912c7f.png)

**Comment by sunnyratilal** [comment]
@JJJ Are you able to replicate this issue?

**Comment by pippinsplugins** [comment]
It works on my iMac.

I'll check my laptop (Ubuntu) when I get home tonight.

**Comment by Zebedeu** [comment]
I still have a similar problem. The rate is always 0

**Comment by cklosowski** [comment]
@Zebedeu Could you try on a brand new 3.0 install? Since this issue was opened there have been multiple DB Schema changes, and we found that some people having issues hadn't gotten the proper schema updates that were made while in the internal development phases.

**Comment by cklosowski** [comment]
This appears to be cleared up in the current `release/3.0` branch. Closing.
