### ISSUE TITLE
Old js causing Easy Digital Downloads to open Crayon Syntax Highlighter

### ISSUE THREAD

**Issue by dgoldak** [easydigitaldownloads/easy-digital-downloads#6873]
Customer reported a problem with Easy Digital Downloads & Crayon Syntax Highlighter Interference.

According to the customer Crayon Syntax Highlighter Opens once when Easy Digital Downloads is enabled. 

They found it was because this file is very old (2012)…
`wp-content/plugins/easy-digital-downloads/assets/js/jquery.colorbox-min.js`

He updated colorbox to v1.6.4 and fixed the issue.

Unfortunately I was unable to recreate the issue but wanted to go ahead and document this behavior to at least evaluate if  `jquery.colorbox-min.js` should be updated.

Reported on WordPress support forum: https://wordpress.org/support/topic/interference-with-crayon-syntax-highlighter/#post-10620150

**Comment by cklosowski** [comment]
Going to flag for 3.0. I know @jjj has done quite a bit of refreshing of our admin UI and our JS dependencies. We should double check this to see if we've updated this library in the process.

**Comment by sunnyratilal** [comment]
We haven't updated Colorbox with 3.0 yet so it'll need to be updated to the latest version. As far as I know, Colorbox is only used for the email template preview.

I think we should switch to using Thickbox only and remove the dependency entirely.  Currently, we're enqueuing Colorbox on every admin page for something that Thickbox can easily handle.

**Comment by cklosowski** [comment]
I would be 100% ok with removing the requirement to keep it just for that reason if thickbox can do the trick.

**Comment by JJJ** [comment]
It doesn't appear that Colorbox is used at all, even used for email templates. The `edd_email_template_preview()` function shows that clicking the "Preview Purchase Receipt" button opens in a new `_blank` browser tab, and I'm unable to find any matching `#email-preview-wrap` element IDs in our markup any longer.

Working on just removing all traces of Colorbox entirely in a PR.

**Comment by JJJ** [comment]
Merged and fixed in 3.0.
