### ISSUE TITLE
Remove "Styles" Tab from Settings

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/easy-digital-downloads#6877]
## Enhancement Request

Remove "Styles" tab from Settings.

### Justification or use case

The new 3.0 UI feels great using and very light weight. But I think the "Styles" tab in the settings could be combined with existing tabs/sections to reduce the initial visual weight of the settings page even more.

My suggestions:

- The "Disable Styles" should be moved to the "General" section of the "Misc" tab. 
- The "Button Text" section in the "Misc" tab should be renamed to "Purchase Buttons" and the "Button Styles" section from "Styles" settings moved here.
- Change "Misc" to "Misc."

Not sure the tab has been touched since it was introduced 6 years ago: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/52

**Comment by spencerfinnell** [comment]
Thoughts on backwards compatibility needed for this?

**Comment by spencerfinnell** [comment]
The "Styles" tab can be removed by default but in order for the least amount of backwards compatibility code the sections will be left the same.

So if there is a plugin that adds a setting to the "Main" section in the Styles tab it will show the Styles tab but it will include both the "Main" and "Buttons" (empty) sections. I think this is reasonable.

**Comment by cklosowski** [comment]
I can't think of any off hand. My search locally doesn't find any. As long as the filters will remain for it as a 'registered' area, I think we should be ok.
