### ISSUE TITLE
3.0: Applying invalid checkout discount returns "null" error message

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/easy-digital-downloads#6879]
Trying to apply an invalid discount at checkout returns an error message of `null`.  I have one discount listed in the admin.

<img width="875" alt="screen shot 2018-08-27 at 8 02 36 pm" src="https://user-images.githubusercontent.com/52581/44648286-b070bd80-aa34-11e8-86e3-76dfaf6708e1.png">

**Comment by sunnyratilal** [comment]
Fixed.
