### ISSUE TITLE
3.0 - Add New Order: Variable priced products do not insert correctly

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#6882]
### Expected behavior
When I add a new variably priced item to the 'Add New' order screen, the variable price name should show and the price should be found for the price ID.

### Actual behavior
When I add a new variably priced item to the `Add New` order screen, the product is shown with `Product Name -` and the price is $0.00

![image](https://user-images.githubusercontent.com/1390124/44692464-d9cf2080-aa17-11e8-8d83-14b67500ff70.png)

### Steps to reproduce the behavior
Be sure to use a product that has not had their prices re-ordered, it would be best to create a new product. For further testing, choose a product that has variable pricing and re-order all the variable prices to a different display position, so that the price ID no longer matches the 'order index'.
1) Add New Order
2) Click 'Add Item'
3) Select a variably priced item.

### Information (if a specific version is affected):
PHP Version: All

EDD Version (or branch): `release/3.0`

WordPress Version: All

Any other relevant information:

**Comment by pippinsplugins** [comment]
I can't seem to replicate this. It works properly for me.

**Comment by cklosowski** [comment]
@pippinsplugins I'm not sure how, the code to do this was looking in the completely wrong place for the data.

**Comment by pippinsplugins** [comment]
It's definitely working for me . . . are you selecting the price option from the drop down or the product name without the price option? For example, a product with two price options will have three possible selections.

**Comment by cklosowski** [comment]
@pippinsplugins nope, picking the correct one. what PHP version are you on?

**Comment by cklosowski** [comment]
@pippinsplugins also what does your `$d->get_prices()` output look like?

**Comment by pippinsplugins** [comment]
7.1.17-0ubuntu0.17.10.1

**Comment by pippinsplugins** [comment]
Ok managed to replicate! PR fixes it so merging.
