### ISSUE TITLE
3.0 - Add New Order: Not respecting prefix and suffix

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#6885]
### Expected behavior
When adding new orders, I expect the sequential order number prefix and suffix to be included.

### Actual behavior
They are not being included.

### Steps to reproduce the behavior
1) Enable a prefix and suffix on order numbers in the Account Settings
2) Orders > Add New

![image](https://user-images.githubusercontent.com/1390124/44695925-481cde80-aa2a-11e8-91ca-7cf3ceb00171.png)

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): `release/3.0`

WordPress Version:

Any other relevant information:

**Comment by sunnyratilal** [comment]
Fixed in https://github.com/easydigitaldownloads/easy-digital-downloads/commit/148b8492cf3539aa6c14801f97703e81b95ef009.
