### ISSUE TITLE
Download files in mobile error

### ISSUE THREAD

**Issue by misulicus** [easydigitaldownloads/easy-digital-downloads#6886]
### Expected behavior
Clicking a download link while mobile should start the file download. In this case it was a PDF file

### Actual behavior
A page is shown with weird characters on it and a php notice at the top.
set_time_limit() cannot set max execution time limit due to system policy

### Steps to reproduce the behavior
Not sure on actual steps besides just trying to download.
Original report here: https://secure.helpscout.net/conversation/651073236/88771?folderId=2048992
I believe it depends on the hosting setup.

### Information (if a specific version is affected):
PHP Version:  7.1.19

EDD Version (or branch) :2.9.6

WordPress Version: 4.9.8

Any other relevant information:

in process-download.php i see this
````
if ( ! edd_is_func_disabled( 'set_time_limit' ) ) {
            @set_time_limit(0);
}
````
but then down below on line 803 there is another use of `set_time_limit(0)` which is where the customers error is coming from. Maybe this line should also use the IF condition as above ?

**Comment by misulicus** [comment]
Customer just confirmed that commenting `set_time_limit(0)` on line 803 fixes the issue and downloads work again.
Hist hosting replied that the function is disabled and the limit is set to 50 and can`t be changed

**Comment by misulicus** [comment]
i was able to replicate this partially locally by blocking the `set_time_limit` function.
On PC testing the file downloads allows you to download the file but the downloaded file can't be opened on the PC. Tested with .zip and .pdf and both throw an error when trying to open them and also a notice in the debug.log file:

```
[28-Aug-2018 16:55:55 UTC] PHP Warning:  set_time_limit() has been disabled for security reasons in D:\MAMP\htdocs\edd\wp-content\plugins\easy-digital-downloads\includes\process-download.php on line 803
```

Adding the edd_is_func_disabled check fixes the issue, no notices and file downloads work correctly.

Same broken behaviour if i try to download using Chrome's device emulator. Applying the function check fixes the download issue again.

**Comment by cklosowski** [comment]
:+1: I'll get a fix for this @misulicus

**Comment by SDavisMedia** [comment]
I can't replicate this for some reason.

I've managed to disable `set_time_limit` at the PHP level and confirm that it's disabled through `phpinfo` but downloads still work and open as expected.

Any other ways to replicate on demand?

**Comment by SDavisMedia** [comment]
Okay, all set now. Replicated the error on `master` and confirmed fixed on `issue/6886`. :+1:
