### ISSUE TITLE
3.0 - Add Order: The '+ New' admin bar menu needs to have 'Order' added.

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#6887]
### Expected behavior
When I want to add a new Order, I should be able to do this from the `+ New` menu in the admin bar. This was something added in Manual Payments initially.

### Actual behavior
The `Order` item is missing.

### Steps to reproduce the behavior
1) As an admin, view the `+ New` menu.

### Information (if a specific version is affected):
PHP Version: All

EDD Version (or branch): `release/3.0`

WordPress Version: All

Any other relevant information: All

**Comment by spencerfinnell** [comment]
Attached a PR.

**Comment by sunnyratilal** [comment]
PR tested & merged. Thanks @spencerfinnell!
