### ISSUE TITLE
3.0 Taxes Reports: Tax Collected by Location table displays incorrect totals

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#6893]
## Bug Report

**Tax Collected by Location** (TCL) table on the **Taxes** tab in Reports displays incorrect Gross and Net totals compared to actual payment records.

### Expected behavior

TCL table display Gross and Net values based on purchases that have been made, regardless of the tax rate's status (`active` vs `inactive`).

### Actual behavior

When a tax rate that has been used in purchases is inactive, it displays incorrect Gross and Net values on the TCL table. (please read every word below)

### Steps to reproduce the behavior

Forgive me, I'm laying this out how I reproduce the issue. I'm just listing stuff as I do it... live action!

This is a brand new site, activated and configured directly on EDD `issue/6869`. All test purchases of different tax rates will be with the same $100 product. Taxes exclusive.

1) I first set up three different regional tax rates. https://cl.ly/d4b55f23a345 They show up on the TCL table as expected, with values of 0 (notice the error, which I am not reporting right now): https://cl.ly/0de813de574f 
2) Now I'm going to complete a purchase with each of those tax rates (changing my state at checkout). Orders completed: https://cl.ly/e531baf5bafa Tax reporting looks correct: https://cl.ly/eb8e36f90a2e
3) Now I'm deleting one of the tax rates that I've made a purchase with already. Florida tax rate deleted, TCL table stayed exactly the same... so that's working.
4) Now I'm adding a new Florida tax rate, but this time it will be for a different percentage (30%). Quick snapshot of the database shows everything above: https://cl.ly/0ca6a6213c3b I am now completing a purchase at this new Florida rate. Boom, replicated... explaining below.

When you delete a tax rate for a specific country/state, then add a new tax rate for that same country/state but with a different _rate_, then complete a purchase with that new rate, the TCL table properly displays the new rate row but its Gross and Net columns display values from the old, deleted rate.

Take note of the Order with the new Florida rate at 30%: https://cl.ly/af7d07d56246

Now notice the TCL table showing the 30% Florida rate as if it has a 20% rate purchase: https://cl.ly/464b92005679

### Information (if a specific version is affected):
PHP Version: `7.1.7`
EDD Version (or branch): `issue/6869`

**Comment by pippinsplugins** [comment]
Tracked it down.

PR ready for testing!

**Comment by pippinsplugins** [comment]
Note: if the date range appears wonky on the report, see https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7016

**Comment by SDavisMedia** [comment]
@pippinsplugins unfortunately, I still get the same behavior. For testing, I first replicated again on `release/3.0`. Then I tested `issue/6893` as well as `release/3.0` again, because it seems this has been merged already?

For testing, what I'm doing is following my replication steps from the opening issue, specifically steps 3 and 4. Notice in the table below all of the FLORIDA tax rate changes. But for each one, the Gross/Net values are the same:

![screenshot_2018-11-07 reports edd3 wordpress](https://user-images.githubusercontent.com/2359131/48150986-fd62e280-e274-11e8-98d2-d333c6a12406.png)

Are you replicating and testing differently?

**Comment by pippinsplugins** [comment]
I didn't merge it but I think I did accidentally push my issue/6893 commit into release/3.0.

Are the amounts correct for California and Delaware?

**Comment by SDavisMedia** [comment]
@pippinsplugins The amounts are correct for Cali and Delaware, as well as Florida _the first time it shows up_. So the first three rows are all correct.

The issue is that after those first three rows, pick one of the aforementioned rates and delete (deactivate) it, then add a new rate for the same state you just deleted, but make sure the rate is different (see the subsequent rows for Florida and notice their tax rate changes), then purchase again. The tax table indicates that the new tax rate has been used (by adding a new row), but it displays Gross/Net values based on the old deleted tax rate for that state.

**Comment by pippinsplugins** [comment]
Here's what I think should happen:

1. We remove the rate from the report. Seeing the rate collected isn't important in this context.
2. The Gross/Net amount shown should be the sum of all rates that were active during the specified period.

@SDavisMedia would you agree?

**Comment by pippinsplugins** [comment]
Update to proposal above:

1. We remove the rate from the report. Seeing the rate collected isn't important in this context.
2. The Gross/Net amount shown should be the sum of all rates that were active during the specified period.
3. We show a single row per region, not a row per rate in region.

**Comment by pippinsplugins** [comment]
@SDavisMedia I believe I've tracked it down and fixed it!

Now looks like this:
![image](https://user-images.githubusercontent.com/1034109/48682507-29803c80-eb6e-11e8-882b-15c9b0403360.png)

Note: orders that are charged a tax under the default global rate are not yet shown here but I'm working on it.

**Comment by pippinsplugins** [comment]
Global rate support added. A `Global Rate` row is now shown at the bottom of the table when there are orders in the specified time frame that collected tax but do not fall under one of the existing tax rates:
![image](https://user-images.githubusercontent.com/1034109/48683690-00fb4100-eb74-11e8-92c4-d93db29987e4.png)

**Comment by SDavisMedia** [comment]
@pippinsplugins Everything appears to be working for me now. The displayed columns properly adjusted, duplicate regions are condensed into a single row with proper Gross, Tax, and Net values, and the Global Rate row shows up for taxes collected outside of regions with specific rates. :+1: Very nice.

**Comment by pippinsplugins** [comment]
Awesome, thanks for testing @SDavisMedia! Merging.
