### ISSUE TITLE
Checkout inconsistencies

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/easy-digital-downloads#6911]
I've noticed a number of inconsistencies at checkout that we can improve. Listed below are some of the issues I've spotted and examples.

## Legends
Some legends are sentence case, some are title case. E.g.

`Create an account (optional)`

vs

`Personal Info`
`Billing Details`
`Select Payment Method`
`Name on the Card`

## Placeholders
Some placeholders are sentence case, some are title case. E.g. 

`Email address`
`Confirm password`
`Card number`
`Your username or email address`
`Enter discount`

vs

`First Name`
`Last Name`
`Zip / Postal Code`

## Links
Some links at checkout have a period after the link, some don't. E.g.

`Have a discount code? Click to enter it`
`Already have an account? Login`

vs

`Need to create an account?	Register or checkout as a guest.`

## Error notices
Some error notices have a period at the end, some don't. E.g.

`Error: There is an error with the Amazon Payments configuration.`

vs

`Error: You must register or login to complete your purchase`

## Slashes
Some words in labels and placeholders contain spaces before and after slashes, some don't. E.g.

`Billing State / Province`
`Billing Zip / Postal Code`
`Zip / Postal Code`

vs

`Expiration (MM/YY)`

___

### Suggestions: 

**Legends, placeholders (and any labels)**

I propose we always use sentence case, where only the first word of the sentence is capitalized. Many sites I've seen use sentence case. It's easier on the eyes and looks friendlier. This looks strange: `Name on the Card`.

**Links**

I propose we do not include periods after links.

**Slashes**

I propose we remove any spaces from before and after slashes.

> Many people wonder whether to use a space before and after slashes in a sentence. The answer is typically no on both fronts. Spaces before slashes should be avoided. The only time it’s acceptable to use a space after a slash is when breaking up lines of a poem, song, or play.

Source: https://www.grammarly.com/blog/slash/

Amazon is a good example which demonstrates no spaces before and after slashes, Sentence case for labels, placeholders and legends:

<img width="505" alt="screen shot 2018-09-05 at 6 12 52 pm" src="https://user-images.githubusercontent.com/52581/45074437-8f485500-b137-11e8-84ed-c43c3cf22e79.png">

___

@easydigitaldownloads/core-team If we agree on the above I'll put together a PR. We'll need to go over our payment gateways also.

**Comment by amdrew** [comment]
We should also make sure we're consistent with our login and registration shortcode forms, and any other UI we provide.

**Comment by cklosowski** [comment]
Since these are possibly places where people have customized the output via `remove_action` etc, we should get them in 3.0 if we can. It's a pretty small update but that way as we are possibly releasing quite a few updates to templates on a major version jump, some of these types of changes are expected.

**Comment by amdrew** [comment]
Good point, I'll submit a PR against 3.0 👍

**Comment by SDavisMedia** [comment]
I agree with all points here. 👍

**Comment by JJJ** [comment]
I agree with @amdrew's Coupon to Discount suggestion.

**Comment by amdrew** [comment]
The button text on our checkout login form should be `Log in`, not `Login`:

<img width="859" alt="screen shot 2018-09-19 at 8 54 30 pm" src="https://user-images.githubusercontent.com/52581/45795013-538caf80-bc4e-11e8-84fe-f999627f9e88.png">

We've correctly named the button with the `[edd_login]` shortcode:

<img width="851" alt="screen shot 2018-09-19 at 8 54 20 pm" src="https://user-images.githubusercontent.com/52581/45795033-63a48f00-bc4e-11e8-8f26-a16d3ac72f0b.png">

**Comment by SDavisMedia** [comment]
Just a random thought about the terminology: that conversation happened over 5 years ago. With the rise of social media advertising, I would _assume_ customers are a _lot_ more familiar with "discount code" at this point. It's everywhere these days.

This is speculation.

**Comment by amdrew** [comment]
@pippinsplugins Made a few more small tweaks to review (see updated PR).

## Removed the period from "This is a secure SSL encrypted payment."

No `label`s or `legend`s use a period so this text seems inconsistent. Only the field descriptions use periods.

_Before_

<img width="609" alt="screen shot 2018-11-08 at 1 26 02 pm" src="https://user-images.githubusercontent.com/52581/48169880-ecd86800-e359-11e8-8967-a139c0561db6.png">

_After_

<img width="592" alt="screen shot 2018-11-08 at 1 27 05 pm" src="https://user-images.githubusercontent.com/52581/48169893-02e62880-e35a-11e8-8336-d65aabab5746.png">

## Removed space on each side of slash in HTML

Removed the space on either side of the slash which appears between the expiration inputs.

```html
<span class="exp-divider"> / </span>
```

to

```html
<span class="exp-divider">/</span>
```

Any extra space (if needed) should be applied to the `exp-divider` class. Visually there are no changes. Before _and_ after:

<img width="450" alt="screen shot 2018-11-08 at 1 31 05 pm" src="https://user-images.githubusercontent.com/52581/48170018-915aaa00-e35a-11e8-8a52-66b2b96adfd8.png">

## Added a period to some error messages

Nearly all error messages at checkout include a period at the end of the sentence except a few. I've added a period to these error messages so they are consistent.
