### ISSUE TITLE
Support WordPress Dark Mode

### ISSUE THREAD

**Issue by JJJ** [easydigitaldownloads/easy-digital-downloads#6913]
## Enhancement Request

The Dark Mode plugin has a merge proposal for WordPress core, posted here:

https://make.wordpress.org/core/2018/08/30/merge-proposal-dark-mode/

### Justification

Having been running the Mojave macOS beta for a few months now, I quite like dark mode there, and find myself preferring dark-everything whenever it's available (IDEs, etc...)

Much of the EDD styling works naturally with Dark Mode already. Some places that define their own colors do not, specifically: Customers, Reports, and some Navigation elements

**Comment by JJJ** [comment]
Here's a snippet of a Customer view in EDD 3.0, to show the kind of styling gaps that need filling.

<img width="890" alt="screen shot 2018-09-05 at 4 17 12 pm" src="https://user-images.githubusercontent.com/88951/45121572-2a84fe80-b127-11e8-8080-a46653fa87cd.png">

**Comment by cklosowski** [comment]
Looks like this is no longer proposed for WP Core:
https://core.trac.wordpress.org/ticket/41928#comment:19

Right now the plugin has only 2k active installs. This would be a pretty low priority if we ever get to it.

**Comment by JJJ** [comment]
OK to close this IMO. Dark mode adoption has not increased since we last checked. Can always reopen anytime.
