### ISSUE TITLE
"customer missing" on new payments

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#6921]
### Expected behavior
In guest mode, when I purchase a product, I expect the customer to be attached to the payment. 

### Actual behavior
In guest mode, when I purchase a product, while the customer is created, "customer missing" is shown on the payment.

### Steps to reproduce the behavior
1) In the EDD Settings under "Misc" > "Checkout", uncheck "Require Login". 
2) Add a product to the cart and complete your purchase.
3) Check the payment record in wp-admin to see if a customer was attached. 

### Information (if a specific version is affected):
PHP Version: 7.2

EDD Version (or branch): master

WordPress Version: 5.0-alpha-43556

Any other relevant information:
There have been 6 tickets about this in support, and I suddenly began replicating it on my local installation. However, (@misulicus) tried to replicate and was not able to.

**Comment by mintplugins** [comment]
For me this is happening because my database schema is on `3.0`, but I'm on `master`.

**Comment by amdrew** [comment]
Just noticed this happening for me today (see orders from March 11):

<img width="1467" alt="Screen Shot 2020-03-11 at 5 25 18 PM" src="https://user-images.githubusercontent.com/52581/76382359-58eb3600-63bd-11ea-9e59-5003bc08d7e2.png">

Each order also has a blank Customer Details section:

<img width="908" alt="Screen Shot 2020-03-11 at 5 26 51 PM" src="https://user-images.githubusercontent.com/52581/76382416-8a640180-63bd-11ea-844d-a99908fb1159.png">

The only thing I recall doing differently was switching over to the 3.0 branch to test something with AffiliateWP and then switching back to master.

**Comment by amdrew** [comment]
Back in business and customer is now correctly listed: 

<img width="1109" alt="Screen Shot 2020-03-11 at 5 31 57 PM" src="https://user-images.githubusercontent.com/52581/76382627-3ad20580-63be-11ea-8591-fac93122b0eb.png">

<img width="918" alt="Screen Shot 2020-03-11 at 5 32 13 PM" src="https://user-images.githubusercontent.com/52581/76382640-44f40400-63be-11ea-89f7-5a0049e5c9bd.png">

I deleted a bunch of option rows related to EDD (upgraded_from, customers_db_version etc), deactivated EDD, and then reactivated. The rows have regenerated and the issue has gone away.

**Comment by cklosowski** [comment]
Going to close this out as it looks like it’s just a case of testing EDD 3.0 on a site, then going back to `master`. These two versions of EDD have different database schemas, and therefore can’t be swapped at will.
