### ISSUE TITLE
Enhancement: System Info page to show plugin author or URI

### ISSUE THREAD

**Issue by mihaijoldis** [easydigitaldownloads/easy-digital-downloads#6923]
### Expected behavior
On the System info page for plugins to show the author and/or the URL

### Actual behavior
At the moment it only shows the plugin name and sometimes its hard or takes a while to locate the developers of a specific plugin

### Steps to reproduce the behavior
1) Generate system report

### Information (if a specific version is affected):
PHP Version: All

EDD Version (or branch): Master

WordPress Version: latest

Any other relevant information:
Would make it easier for Support staff to find out quickly who is the developer of plugin X and point the customer in their direction for issues regarding a 3`rd party plugin.

Something as simple as this could work https://www.screencast.com/t/VyEYy99FkeQA

**Comment by mihaijoldis** [comment]
Sent a PR here however I notice with our extensions that some use `Plugin URL` and some `Plugin URI` others use `Author URI` or just `Author`

**Comment by robincornett** [comment]
@ashleyfae This is set for milestone 3.0.5 but @mihaijoldis has a working/approved PR for 2.11, and I think it would be helpful to support to have this in sooner, if that's okay.

**Comment by ashleyfae** [comment]
Yep that's fine.
