### ISSUE TITLE
Improve default display of the legend element at checkout

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/easy-digital-downloads#6924]
I'd like to suggest we fix our default legend styling so it looks nicer on the default WP themes as well as our themes. This may help prevent support tickets from customers wanting to make the styling a little bit nicer in their theme (saw one this morning)

With EDD's current CSS styling, the `legend` is positioned outside the `fieldset` element, sitting right on top of the `fieldset`. 

Here's how it looks with Twenty Seventeen, Twenty Sixteen and Vendd:

<img width="874" alt="screen shot 2018-09-14 at 9 40 32 am" src="https://user-images.githubusercontent.com/52581/45517497-6b090a00-b802-11e8-876d-5b54f6477043.png">

___

<img width="553" alt="screen shot 2018-09-14 at 9 40 55 am" src="https://user-images.githubusercontent.com/52581/45517501-6fcdbe00-b802-11e8-9465-c534229027bc.png">

___

<img width="751" alt="screen shot 2018-09-14 at 9 41 12 am" src="https://user-images.githubusercontent.com/52581/45517506-74927200-b802-11e8-84a6-06d8442fc2ef.png">

___

Note also the large space above the "Email Address" label in each screenshot. EDD intentionally positions the legend above the fieldset by setting a bottom margin of 21 pixels. Doing this pushes down on the rest of the content creating the extra space shown in the screenshots above.

In my opinion, having the legend sit awkwardly on the fieldset border and the increased space caused by the bottom margin is something we can improve. Increasing the bottom margin wouldn't work since it would just push the other content down further, creating a larger gap. 

## Default legend styling

HTML-wise, a `legend` is a child element of the `fieldset`:

```
<fieldset>
  <legend>Personalia:</legend>
  Name: <input type="text"><br>
  Email: <input type="text"><br>
  Date of birth: <input type="text">
</fieldset>
```

The default styling for the `<legend>` element looks like the following, with the legend positioned inline with the fieldset border:

<img width="539" alt="screen shot 2018-09-14 at 9 37 39 am" src="https://user-images.githubusercontent.com/52581/45517319-d8686b00-b801-11e8-96fa-bc1a4c51ff19.png">

Source: https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_legend_default_css

## How to fix

There _is_ an `align` attribute but it's not supported in HTML5: https://www.w3schools.com/tags/att_legend_align.asp

Recommended at the above link (and also how I achieve this in Themedd) is to use floating. Since EDD's styling already has a width of 100% on the `legend`, there's no need for clearing the float.

## Proposal

Use `float: left;` on the legend element. This places the legend inside the fieldset (consistent with the HTML markup), fixes the large space, and overall looks nicer.

The themes from earlier with floating now applied:

<img width="749" alt="screen shot 2018-09-14 at 10 25 27 am" src="https://user-images.githubusercontent.com/52581/45519290-8ecf4e80-b808-11e8-9849-c16fd5267add.png">

<img width="544" alt="screen shot 2018-09-14 at 10 25 14 am" src="https://user-images.githubusercontent.com/52581/45519291-8ecf4e80-b808-11e8-94cd-c9558dcf6c7f.png">

<img width="880" alt="screen shot 2018-09-14 at 10 24 54 am" src="https://user-images.githubusercontent.com/52581/45519293-8f67e500-b808-11e8-9aa1-6d3e6ea225ac.png">

**Comment by amdrew** [comment]
PR: https://github.com/easydigitaldownloads/easy-digital-downloads/pull/6925

**Comment by SDavisMedia** [comment]
I agree with this. Previously, we considered the only alternative to be the default display, which would cause even more support tickets when the fieldset has a background color (super common):

![screenshot_2018-09-14 checkout easy digital downloads](https://user-images.githubusercontent.com/2359131/45560807-fb435100-b7fa-11e8-9df4-d1e68bedceb3.png)

Ew.

This is a much better alternative to the last approach and doesn't appear to cause any issues. :+1:

**Comment by cklosowski** [comment]
@SDavisMedia @amdrew being that this is affecting checkout, and we've already chosen to affect some more 'major' changes to templates in the 3.0 release, is this something that we should put there? Or do you see no issues with it going in a minor release?

**Comment by amdrew** [comment]
@cklosowski No issues that I can think of, though now that you mention it, it would be better off with the other 3.0 issues. It's not super important, so it can wait. @SDavisMedia agree?

**Comment by SDavisMedia** [comment]
@amdrew @cklosowski Yea I agree. I don't see it hurting anything now. But since 3.0 is coming soon and changes will be expected, I do think it's smarter to wait. Mainly because this is checkout.

**Comment by cklosowski** [comment]
@amdrew @SDavisMedia perfect, i just updated the PR to be against `release/3.0` instead of `master`, all should still check out and if we're good with this we can merge.

**Comment by SDavisMedia** [comment]
@cklosowski Good to merge. Checks out fine on 3.0. :+1:
