### ISSUE TITLE
Remove clearfix rule from CSS

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/easy-digital-downloads#6926]
We have the following clearfix rule in the EDD stylesheet:

```
#edd_checkout_form_wrap label:after {
	display: block;
	visibility: hidden;
	float: none;
	clear: both;
	height: 0;
	text-indent: -9999px;
	content: ".";
}
```

Usually you would do something like the above to clear a float. This would be the case if the labels were floated but they're not (perhaps they used to be).

The only selectors that use floats in the current CSS file are:

`#edd_checkout_form_wrap .edd-payment-icons img.payment-icon`
`.edd_download`
`#edd_checkout_cart td img`

So unless there are labels being added by another plugin of ours (in which case they should be updated to _not_ be floated) then I suggest we remove the CSS listed above.

Tested with Twenty Seventeen, Twenty Sixteen and Vendd. All themes look the same as before with the CSS removed.

**Comment by amdrew** [comment]
PR: https://github.com/easydigitaldownloads/easy-digital-downloads/pull/6927

**Comment by SDavisMedia** [comment]
That's been there for quite some time. Looks like it has been useless for years. :+1:

**Comment by cklosowski** [comment]
Looks like it's been here a LONG time:
#949 and #438 were the original issues related to the commits that added these.

**Comment by SDavisMedia** [comment]
@mintplugins Take a quick look at this if you would please. Very simple change. But let's get one more set of eyes on it since it's checkout. Thanks!

**Comment by mintplugins** [comment]
Looks good here 👍 I tested with the Marketify Theme and Twenty Seventeen. For plugins I also tested with the Checkout Fields Manager and Upload File extensions and everything looks and works properly on checkout in all scenarios there.
