### ISSUE TITLE
3.0 - Reports: Download report throws warning  when checking for variable prices.

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#6930]
### Expected behavior
When viewing the Downloads Report, no PHP errors should be thrown when determining when a price ID name is needed

### Actual behavior
The way that price IDs are getting found is nulling the array out, we need to not use the array_filter for the `index` as that is used when items are reordered, not their actual price ID.

### Steps to reproduce the behavior
1) Purchase a variable priced product
2) View the Downloads Report

### Information (if a specific version is affected):
PHP Version: All

EDD Version (or branch): `release/3.0`

WordPress Version: All

Any other relevant information:
We saw this issue with #6882, so just need to apply that change here too.

**Comment by JJJ** [comment]
PR fixed this issue, so it's been merged. Thanks @cklosowski!
