### ISSUE TITLE
3.0 - Orders List: List table seems to be misisng some data and looks 'sparse'

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#6934]
## Enhancement Request

Affected View:
![image](https://user-images.githubusercontent.com/1390124/45642420-f71e6a00-ba6c-11e8-8812-946fa8ffdc6a.png)

### Explain your enhancement (please be detailed)
The current list Table view of orders looks pretty sparse, and is missing the column for 'status' (intentional?)

### Justification or use case
This view, while nice and simple, seems like we've missed something or not thought about the overall design of it with all the whitespace after the order ID.

In previous versions we had a column for 'status' which, I think would still be ideal to have here when viewing the 'All' filter, so you can get a quick read on what type of orders are coming in.

**Comment by SDavisMedia** [comment]
@cklosowski The status column is being replaced by "states" for each row... the WordPress core feature: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6642#issuecomment-416689340

White space after the order number is more of an issue with the order number lengths themselves. We're talking about ways to make them more clickable here: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6642#issuecomment-419687790 Would love your feedback on my comment there.

Unless there's other data you feel is missing, as in data that should have its own column, I think this issue should be part of the UI/UX discussion I've linked above.

**Comment by cklosowski** [comment]
:+1: I'll close and have the discussion there.
