### ISSUE TITLE
3.0 - Fix SVG lock icon at checkout

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/easy-digital-downloads#6941]
Looks like the SVG lock icon is no longer displaying at checkout when SSL is enabled (I probably broke it).

**Comment by amdrew** [comment]
PR: https://github.com/easydigitaldownloads/easy-digital-downloads/pull/6942

**Comment by amdrew** [comment]
@cklosowski That's the lock icon from the Stripe extension (which we'll update for 3.0). If you enable the Amazon gateway you'll be able to replicate.

**Comment by cklosowski** [comment]
:+1: testing.
