### ISSUE TITLE
I need to configure custom file uploader instead of FES native file uploader

### ISSUE THREAD

**Issue by jsarkar85** [easydigitaldownloads/easy-digital-downloads#6945]
I'm Using [EDD](https://easydigitaldownloads.com/) [FES](https://easydigitaldownloads.com/downloads/frontend-submissions/) and S3 I need to configure the [fileuploader](https://innostudio.de/fileuploader/) or [fineuploader](https://fineuploader.com/) in the vendor submission form for feature image, Product/Main file, instead of FES native file uploader.

Please help me how can I do. I was requested to my developer and he was tried but FES not allowing to upload file over the [fileuploader](https://innostudio.de/fileuploader/)

I really need to done this.

**Comment by cklosowski** [comment]
Hi there! This issue is related to Frontend Submissions, not Easy Digital Downloads core, of which this repository is dedicated to.

Please go ahead and open a support ticket through our support portal: https://easydigitaldownloads.com/support

we use GitHub for development tracking only.
