### ISSUE TITLE
Billing address details forgotten on free purchases

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#6949]
### Expected behavior

Billing address information should be retained, regardless of purchase "cost" or if taxes are enabled/disabled globally on the site.

### Actual behavior

Customer details are wiped on free purchases and when store taxes are toggled.

### Steps to reproduce the behavior

As per this customer ticket (https://secure.helpscout.net/conversation/668779441/90705/), there is a bug with the customer address details being deleted in various situations.

**Free Purchases**

If you purchase a paid product, then go back and purchase a free product (going through the checkout), the next time you try to purchase a paid product the billing address details are no longer present in the customer record and need to be re-entered.

Similarly, if the site owner switches from using taxes to not using taxes, this also clears the customer billing details.

**Comment by SDavisMedia** [comment]
Definitely replicated on `master`. Will check it out on `release/3.0`.

**Comment by SDavisMedia** [comment]
This appears to be taken care of in 3.0. Same replication steps do not wipe the Customer Address clean on the customer record. So I'd say all is well there.

@cklosowski Should this issue be saved for 3.0?

**Comment by cklosowski** [comment]
@SDavisMedia yeah, I've already milestone'd for 3.0 so I'll close it out as it's resolved in the `release/3.0` branch.
