### ISSUE TITLE
3.0: Some discount getters no longer work

### ISSUE THREAD

**Issue by DrewAPicture** [easydigitaldownloads/easy-digital-downloads#6956]
### Expected behavior
When I use `$discount->get_ID()` or `$discount->get_name()` I expect them to still work in EDD 3.0.

### Actual behavior
Instead, when I use either I get `null` values. It seems that the `get_name()` and `get_ID()` methods that previously existed in the discount object are now gone. Shouldn't they at the very least be properly deprecated? I checked the inheritance tree and don't see anything that would even enable these methods to still work via magic methods.

Currently the best available option is to access the properties directly, `->name` / `->id`, which is less than ideal.

### Steps to reproduce the behavior
Use `$discount->get_name()` or `$discount->get_ID()`.

### Information (if a specific version is affected):
EDD Version (or branch): 3.0

**Comment by spencerfinnell** [comment]
Direction this should go? Happy to open a PR with the proposed solution.

Looking around at the other classes it looks like the `get_` methods are used more for data that requires a bit of manipulation before being returned instead of just the property directly.

**Comment by cklosowski** [comment]
the `get_ID` and `get_name` methods previously were just part of the magic getter since this was an absraction of a `WP_Post` object before 3.0.

The name being the `get_the_title` and the ID being the post ID.

We should probably properly deprecate those methods. @JJJ I'm assuming the current model of an `Adjustment/Row` is to use properties instead of magic getters?

**Comment by sunnyratilal** [comment]
I believe we used the `__call` magic method to handle this case for backwards compatibility.  Though it's likely that it has changed since its original implementation due to the restructuring of the classes.

**Comment by pippinsplugins** [comment]
The __call() method doesn't handle this. For simplicity, I've restored the getters for name and ID.
