### ISSUE TITLE
Update Amazon Payments onboarding URL

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#6958]
### Explain your enhancement (please be detailed)
Amazon is changing their on boarding URL for setting up Amazon Payments. The new URL needs to be:
https://payments.amazon.com/register?registration_source=SPPD&spId=A3JST9YM1SX7LB

### Justification or use case
Amazon reached out to tell us about this.

**Comment by cklosowski** [comment]
Ok this is ready for testing...per the Representative this is all we should need. I asked the following questions:

```
Question 1:
Currently we're sending to 3 possible URLs
UK: https://payments.amazon.co.uk/preregistration/lpa
DE: https://payments.amazon.de/preregistration/lpa
All Other: https://sellercentral.amazon.com/hz/me/sp/signup

Do we switch all of these to the URL you provided?

Question 2:
Right now we also send 4 query string parameters to the registration process:
solutionProviderId
marketplaceId
solutionProviderToken
solutionProviderOptions
```

And the response was to reference the link she previously provided me via the email thread...of which there was only one, non-country specific, URL. It also only contained 2 query string params (which you'll see in this PR), and removed some of the previous ones.

Since this is what I've been told is the new confirmed URL (regardless of locale), we should go with it.

**Comment by SDavisMedia** [comment]
Looks good to me. The new URL worked all the way through to a successful account setup for me. :+1:

**Comment by dgoldak** [comment]
I confirmed the Register with Amazon button goes to the new URL. I assume that confirms we are good to go.

**Comment by cklosowski** [comment]
Awesome thanks @SDavisMedia @dgoldak I'll get a release worked up for this.
