### ISSUE TITLE
Country/State incorrectly nonce verification throws debug error when only the country field is visible.

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#6987]
### Expected behavior
When just the country field is shown, no errors should be logged.

### Actual behavior
When only the country field is shown, a debug log entry is shown for the nonce missing.

### Steps to reproduce the behavior
1) Setup Stripe to use Zip/Postal Code and Country Only
2) Go to checkout, select Credit Card and change the Country.
3) Likewise you can also go to the profile editor and add a new card and change the country field
4) Go to the EDD DEbug log

### Information:
PHP Version: All

EDD Version (or branch): `master` (Anything after EDD 2.9.4)

WordPress Version: All

Any other relevant information:
Stripe is the easiest way to see this happen.

No purchase information is stopped from processing, and the nonce isn't needed here since we don't actually load the state field in this case. If the state field is present

**Comment by pippinsplugins** [comment]
Replicated and confirmed the fix.
