### ISSUE TITLE
State field does not recover from Text field input

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#6988]
### Expected behavior
When I choose a country that does not have a pre-defined list of states, and then switch back to a country that does have a predefined list of states, the Text Field should be replaced with a select field of the States.

### Actual behavior
When I choose a country that does not have a pre-defined list of states, and then switch back to a country that does have a predefined list of states, the text field is not replaced by the select field.

### Steps to reproduce the behavior
1) At checkout have State and Country fields visible (Either via taxes or with Stripe's address selector dropdown set to full address)
2) At checkout change the Country to 'Afaganistan'
3) The state field becomes a text field
4) Change the Country to Canada
5) The state field remains a text field instead of changing to a select dropdown of a list of Canadian provinces.

### Information (if a specific version is affected):
PHP Version: All

EDD Version (or branch): `master`

WordPress Version: All

Any other relevant information:
I noticed this when testing #6987

**Comment by cklosowski** [comment]
@SDavisMedia @mintplugins could you try and replicate this? If you can I'll investigate further.

**Comment by mintplugins** [comment]
I am not replicating this. When I switch from USA to Aruba, then to USA, the states dropdown appears again.

**Comment by mintplugins** [comment]
I tested with both Stripe (taxes disabled) and Test Gateway (taxes enabled), and both times I could switch from countries with states (USA) to countries without states (Aruba) and back (USA). I always get the dropdown of states back.

**Comment by cklosowski** [comment]
Ok so this is somethign locally for me, I'll go ahead and close it
