### ISSUE TITLE
3.0: Document arguments accepted by all new 3.0 functions

### ISSUE THREAD

**Issue by DrewAPicture** [easydigitaldownloads/easy-digital-downloads#7010]
When I read the source for basically all of the `edd_add_*()` functions, I expected to see the documentation for what arguments these functions accept. Turns out, it's actually not just the `edd_add_*` functions, it's many of the add/update functions added in 3.0.

We absolutely have to have these docs to ship :-)

I started a tracking list for what still needs inline docs and it's a lot. A lot of docs missing. Off the top of my head:

* [x] `edd_add_customer()`
* [x] `add_add_order()`
* [x] `add_add_adjustment()`
* [x] `edd_add_discount()`
* [x] `edd_add_log()`
* [x] `edd_add_customer_address()`
* [x] `edd_add_customer_email_address()`
* [x] `edd_add_api_request_log()`
* [x] `edd_add_file_download_log()`
* [x] `edd_add_order_address()`
* [x] `edd_add_order_adjustment()`
* [x] `edd_add_order_item()`
* [x] `edd_add_order_transaction()`

OK, there's actually _a lot_ more though. Apparently pretty much all of the add/update functions for all of these components are also lacking argument docs.

**Comment by JJJ** [comment]
The documentation for these convenience functions is going to be an exact mirror of the objects they wrap. We chose not to duplicate these arrays because they are all rather large, and were changing a lot more in the earlier days.

If you have a preferred way to refer to existing class arguments, you have my blessing (not that you need it) to tie all those references together.

If you think it's better to have them duplicated, that's gonna end up being a lot of extra work, and I'd love to have any help you can give. <3

**Comment by DrewAPicture** [comment]
> The documentation for these convenience functions is going to be an exact mirror of the objects they wrap. We chose not to duplicate these arrays because they are all rather large, and were changing a lot more in the earlier days.

For what it's worth, before I created this issue, I looked around for the missing docs and still didn't really find them. Normally I'd be in favor of keeping one set of canonical argument docs, except in this case I can't find them even on the objects. So can you ... give an example for, say, where I might find arguments accepted by `edd_add_customer()` and `edd_update_customer()`?

**Comment by DrewAPicture** [comment]
Basically the problem is that I don't really see docs at the object level either. I see properties and `@property` annotations for magic properties, but there really isn't any kind of hash notation explaining what arguments these functions or object constructors accept. We gotta find a way to lower this barrier.

**Comment by DrewAPicture** [comment]
With the way the new database stuff is designed, it's very much abstracted in responsibility, but the major downside of this approach is that we largely lose the opportunity to create canonical documentation at the API level because now all queries are run through the same pipe.

We can't rely on documenting arguments accepted by `Orders->add_item()` for `edd_add_order()` because all queries are run through `EDD\Database\Query->add_item()`. So maybe we create CRUD methods that we _can_ canonically document and reference from the global abstraction wrappers, or maybe we just document the arguments at the wrapper level. All ideas.

**Comment by sunnyratilal** [comment]
PR opened at #7013 with first round of documentation added.

**Comment by pippinsplugins** [comment]
@sunnyratilal PR complete?

**Comment by JJJ** [comment]
Yeah. This is ready for merge.

**Comment by pippinsplugins** [comment]
Merged.

**Comment by pippinsplugins** [comment]
I accidentally overwrote the merge when I committed to the wrong branch and pushed.

PR that restores it https://github.com/easydigitaldownloads/easy-digital-downloads/pull/7028

Ping @DrewAPicture
