### ISSUE TITLE
Gateway Sales and Earnings Pie Charts Not Rendering

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/easy-digital-downloads#7023]
### Expected behavior

I should be able to render a pie chart.

### Actual behavior

If a pie chart contains zero values it will error.

### Steps to reproduce the behavior
1) Use https://github.com/easydigitaldownloads/easy-digital-downloads/pull/7022
2) View gateway report when there is a gateway that has not been used.

Current data generated outputs: https://cloudup.com/cO8JT_P5pR3

Where there is only 1 piece of data in the set, but 3 labels. This causes a JS error.

Original implementation code: https://github.com/easydigitaldownloads/easy-digital-downloads/pull/6515

**Comment by spencerfinnell** [comment]
Caused by https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6763

**Comment by spencerfinnell** [comment]
I have fixed this in https://github.com/easydigitaldownloads/easy-digital-downloads/pull/7022

**Comment by pippinsplugins** [comment]
This is all working great for me. Merged.
