### ISSUE TITLE
3.0 - Set "Default Button Color" to blue

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/easy-digital-downloads#7029]
EDD's default button color is set to `blue` as determined by `edd_get_option( 'checkout_color', 'blue' )` in various parts of the codebase. The button color on the front-end is therefore blue also.

However, when you first install EDD, and no settings are yet saved, the default button color is actually "White":

<img width="593" alt="screen shot 2018-11-09 at 12 15 09 pm" src="https://user-images.githubusercontent.com/52581/48233161-22905600-e419-11e8-885a-7110233758a8.png">

If you happened to save this tab after installing EDD the button color would then be set to white. Since we've already deemed the default to be blue when you first install it (when no settings are yet saved), I would expect `Default Button Color` to also be `blue`.

___

Affects both `master` and `release/3.0` but fixing for 3.0 only.

**Comment by amdrew** [comment]
PR: https://github.com/easydigitaldownloads/easy-digital-downloads/pull/7030

**Comment by JJJ** [comment]
👍
