### ISSUE TITLE
Edit Payment Screen - Address state cannot be updated when country changed

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#7035]
### Expected behavior

If you try to edit a payment that has no address fields pre=populated and change the `country` select field, the `state` select does not appear, so it's impossible to change the state properly.

### Actual behavior

As per the above.

### Steps to reproduce the behavior
1) Select any existing payment record. In my case, taxes were disabled.
2) Change the payment country select field
3) The state select does not appear.

### Information (if a specific version is affected):
PHP Version: 7.2

EDD Version (or branch): 2.9.8

WordPress Version: 4.9.8

**Comment by SDavisMedia** [comment]
Looks like this broke in 2.9.4.

**Comment by SDavisMedia** [comment]
This is ready for testing on `issue/7035`.

To test, just switch to the issue branch and attempt to replicate the original replication steps. It should work properly.
