### ISSUE TITLE
EDD 3.0: Improve “Download Instructions” label description

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#7040]
### Explain your enhancement (please be detailed)

At present the label description for the "Download Instructions" is worded as follows:

> Special instructions for this download. These will be added to the sales receipt, and may be used by some extensions or themes.

For the sake of congruency it should probably say "purchase receipt" instead of "sales receipt", since this more accurately describes the template within EDD.

### Justification or use case

Cosmetic/congruency reasons.

**Comment by SDavisMedia** [comment]
I agree this should probably be "purchase receipt" as it is in EDD pre-3.0. I looked around 3.0 and I'm not any other changes to that wording.

@JJJ @pippinsplugins  Are we overlooking any specific reason why the wording changed?

**Comment by JJJ** [comment]
Without looking, I remember experimenting with using "sales" in more places to coincide with changes to the `Orders > Sales/Refunds` screens, and their related settings, labels, and so on.

I don't remember off the top of my head if we settled on exact verbiages. Sorry.

I'm fine with changing this back to "purchase receipt".

**Comment by SDavisMedia** [comment]
Merged.
