### ISSUE TITLE
3.0: Sales and Earnings report has a currency sign on the sale count label

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#7048]
The `Sales` label has a currency sign on the sale count when it clearly shouldn't.

<img width="494" alt="screen shot 2018-11-21 at 12 51 58 pm" src="https://user-images.githubusercontent.com/1034109/48862671-a8eb5700-ed8c-11e8-9f50-895a71895d77.png">

**Comment by SDavisMedia** [comment]
Probably same as what happened here: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6725

**Comment by spencerfinnell** [comment]
The tooltip generation in the updated JavaScript shouldn’t have changed. If the chart data is correct and not marking that value as a currency then I can fix it. 

The dataset can pass a special type of value (currently just a currency) which is handled here: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/assets/js/admin/reports/charts/utils.js#L37

**Comment by spencerfinnell** [comment]
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/reporting/reports.php#L549

Doesn’t look like it! Only Earnings should have it. I’ll fix it soon.

**Comment by spencerfinnell** [comment]
Looking at this now I'm now it seems like the original Javascript had this issue as well. The current logic will apply currency filtering to all items if one dataset in the report is set to currency.

@sunnyratilal Do you remember why the currency formatting was setup in the Javascript, and not the returned data? 

https://github.com/easydigitaldownloads/easy-digital-downloads/commit/0cccc828ec0cce6387502ec5d779826fdf22c454

Doing it in Javascript doesn't use a lot of the customizable formatting options users may have set.

**Comment by spencerfinnell** [comment]
Attached a PR that keeps the Chart response data float values (which I realized is needed to allow plotting to work).
