### ISSUE TITLE
3.0: Finalize View/Edit Order Details

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#7052]
### Explain your enhancement (please be detailed)
Make the final changes to the UI/UX for the view/edit order details.

### Justification or use case
For 3.0 changes. I'll get a list of the changes to verify as I finalize things.

- [x] Remove Edit/Delete from individual Items on an order
- [x] Remove Edit/Delete from Bulk Actions
- [x] Add `type="email"` to the input for the Email tab when customer only has one email address
- [x] Fix Copy Download File actions
- [x] Fix Add Order JS from loading on View/Edit Order page (which caused JS conflicts)
- [x] Improve the Customer Section
- [x] Improve the Email Section when multiple email addresses exist.

**Comment by spencerfinnell** [comment]
In the "Email" tab of "Order Details" the input is missing `type="email"` which leads to missing styles.

**Comment by cklosowski** [comment]
@easydigitaldownloads/core-team could I get some review on this page now? just to make sure things that should exist, exist, and functionality still works now that I've done some clean up?

Keep in mind 'refunding' isn't quite fully complete. I still need to hook up the 'refund' actions to create refund orders.

**Comment by pippinsplugins** [comment]
A few items I'd like to see:

1. In the `Customer` tab, I'd like to see the `New` and `Reassign` links visually separated / distinct from the customer name. They blend together too much right now.
<img width="556" alt="screen shot 2018-12-05 at 11 35 37 am" src="https://user-images.githubusercontent.com/1034109/49532395-0221b300-f882-11e8-9075-8cfc935842cb.png">

2. I do not like the right aligment of the field names in the right metaboxes. I'd like to see the labels left aligned.
<img width="469" alt="screen shot 2018-12-05 at 11 37 12 am" src="https://user-images.githubusercontent.com/1034109/49532443-1fef1800-f882-11e8-8af6-0e4c232ec7d4.png">

3. In the `Email` tab I'd like to see the email address(s) of the customer shown by default. The button jump when revealing the select field is jarring. There's a ton of real estate available so I don't see any reason to hide that select menu.

**Comment by spencerfinnell** [comment]
> In the Customer tab, I'd like to see the New and Reassign links visually separated / distinct from the customer name. 

Buttons would be nice.

> I do not like the right aligment of the field names in the right metaboxes. I'd like to see the labels left aligned.

This has been mentioned a few times because it fails extra with non-English installs. I thought there was a ticket somewhere but I can't find it now.

**Comment by SDavisMedia** [comment]
@spencerfinnell https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6787

**Comment by SDavisMedia** [comment]
I dig the alignment as well. Compared to what it is right now pre-3.0, I think it's _much_ better.

However, in usual Sean fashion, I don't think it's 100% necessary for label/value to be inline. I know it's the norm, but it clearly presents consistency issues.

If readability is an issue, having one line for the label and a new line for the value (with word wrap) simply makes sense. This isn't the greatest example, but it illustrates what I'm referring to:

![screenshot_2018-12-06 dashboard easy digital downloads wordpress](https://user-images.githubusercontent.com/2359131/49604771-a586cc80-f943-11e8-99ce-f900b4e9fb55.png)

I understand that the content would take up more vertical space, but I value balancing all concerns over just one of them. It doesn't have to take up a dramatic amount of space either. Font sizes and padding go a long way.

I'll toss in one more example just for fun:

![screenshot_2018-12-06 edit download edd3 wordpress](https://user-images.githubusercontent.com/2359131/49605093-7a50ad00-f944-11e8-97e2-b7f890d43fe8.png)

**Comment by pippinsplugins** [comment]
Let's leave them as is.

**Comment by spencerfinnell** [comment]
There also seems to be some extraneous or incomplete code in the update order routine:

`$new_total` is defined as current total or a new input value, which doesn't exist on the page.

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/payments/actions.php#L118

It's never updated then checked against what will always be the original value:

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/payments/actions.php#L336

(That condition also has an undefined variable `$status` but never errors because the first condition will always fail)

If the total is meant to be updated based on added/removed download's subtotals and taxes then somewhere around https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/payments/actions.php#L224 `$new_total` should be recalculated.

**Comment by cklosowski** [comment]
Updated to change the Customer Overview section as well as the resend receipt section:
![image](https://user-images.githubusercontent.com/1390124/51645314-fae95e00-1f30-11e9-8ec4-d01497c10cd3.png)

![image](https://user-images.githubusercontent.com/1390124/51645324-03419900-1f31-11e9-9ee6-6d4f930b7dab.png)

**Comment by cklosowski** [comment]
@SDavisMedia @spencerfinnell at a quick glance am I committing any faux pas?

**Comment by spencerfinnell** [comment]
@cklosowski Added a branch with a few tweaks ^

- Makes button actions more clear
- Uses a `<button>` for Cancel links instead of an anchor.
- Changes "View" button to a standard link.

**Comment by cklosowski** [comment]
Oh, I like those @spencerfinnell I'll go ahead and merge those into my branch
