### ISSUE TITLE
3:0 Search Hidden on Chosen

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/easy-digital-downloads#7054]
### Expected behavior

Chosen should allow searching on certain inputs.

### Actual behavior

Search input is always disabled.

### Steps to reproduce the behavior

1) Try to add a download to a bundle. (#6760)

---

The search was effectively removed on the majority of Chosen instances with this commit: https://github.com/easydigitaldownloads/easy-digital-downloads/commit/61f1059c439af79ef5ee95394e77437de3169ba1#diff-4e07975920906985a5fbbe3afd720629R10

@JJJ I assume this was for things like settings that only have a few options?

Not sure the best way this. Perhaps another argument in the HTML class to disable search for that specific field?

**Comment by JJJ** [comment]
@spencerfinnell correct.

13 was picked specifically for hours in the am/pm, and month lists. It also felt, to me, like a decent starting off point for all Chosen fields. If we have a need to allow search in specific fields, we can override them, and I'd recommend documenting in the code why, so it doesn't get removed later.

**Comment by spencerfinnell** [comment]
@JJJ I went with allowing it on `select`s that have a defined `data-search-type`. Realizing it's a bit flawed though because of how many places Chosen is reinitialized when something happens. 

Thinking...

**Comment by spencerfinnell** [comment]
Updated to reverse the logic (search off by default) and ensure reinitialized Chosen instances use the correct variables.

**Comment by dgoldak** [comment]
Confirmed search box appears with `issue/7054`. Search doesn't appear to work as it doesn't find any downloads but the search box appears now.

**Comment by cklosowski** [comment]
This is getting merged directly into #6760 as I'm fixing the search results and improving the behavior over there.
