### ISSUE TITLE
3.0 - Orders: Payment Meta item is still being saved to order meta

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#7057]
### Expected behavior
There should be no `_edd_payment_meta` stored on the new orders, as this data is now stored elsewhere.

### Actual behavior
Orders still get an `_edd_payment_meta` entry added to the order meta table.

### Steps to reproduce the behavior
1) Create an order
2) Either use the dev tools plugin or view the data in the database.

### Information (if a specific version is affected):
PHP Version: All

EDD Version (or branch): `release/3.0`

WordPress Version: All

**Comment by cklosowski** [comment]
Thinking on this, we might have to keep the general structure of it around, for backwards compatibility for people who store things in this array. @easydigitaldownloads/core-team any thoughts on the status of this array.

I really want to ditch it as we've moved all this data out of here, and written backwards compatibility, but I wonder how many people are relying on it.

**Comment by JJJ** [comment]
If there are examples in the wild of people calling methods or functions and expecting to get/set an array of data, we should matinain back-compat for it also.

That said, I don’t think we should store it in the database that way new should build support for it, but not use it internally ourselves, and instead use the most efficient way.

**Comment by cklosowski** [comment]
Yeah my concern is someone modifying that meta (which most of it has been moved to the new tables/columns), and expecting it to change things, which it would not.

**Comment by ashleyfae** [comment]
Duplicate: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7289 ?

**Comment by cklosowski** [comment]
Closing as duplicate.
