### ISSUE TITLE
selector.tooltip is not a function

### ISSUE THREAD

**Issue by jgreys** [easydigitaldownloads/easy-digital-downloads#7062]
## Bug Report
"selector.tooltip is not a function at edd_attach_tooltips"

### Steps to reproduce the behavior
Any EDD admin pages

### Information (if a specific version is affected):
PHP Version: 7.2

EDD Version (or branch): 2.9.8, 2.9.9

WordPress Version: 4.9.8

**Comment by jgreys** [comment]
The problem comes from the WooCommerce Block plugin. I close.

**Comment by jgreys** [comment]
The problem comes from the WooCommerce Block plugin. I close.

**Comment by JiveDig** [comment]
I hit this same issue, but don't have WooCommerce or the Woo Block plugin installed.

**Comment by JiveDig** [comment]
Mine is a conflict with EDD Github Updater.

**Comment by cklosowski** [comment]
I'm not seeing this happen with the EDD Github Updater plugin causing this. It's likely that it's coming from somewhere else, where maybe another plugin is unhooking the WP Core tooltip library that comes with jQuery UI (which is what we are using).

**Comment by JiveDig** [comment]
Very strange. I disconnected from GitHub, then created a new app in our GH Organization and connected to that one, and it works again.

**Comment by JiveDig** [comment]
Thanks for checking 👍

**Comment by cklosowski** [comment]
No worries, if it comes up again, let us know and we can dig deeper into what might be causing it. Likely it's just a JavaScript conflict somewhere.
