### ISSUE TITLE
Add a 'Manual' gateway option when adding a payment

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#7067]
### Explain your enhancement (please be detailed)
Add a 'manual' option for the gateway dropdown when adding a payment manually.

### Justification or use case
Right now our gateways listed there are only ever the registered gateways, including 'Test Payment'. If however you choose to manually create a payment for a customer for some reason, but don't want to assign it to a gateway like Stripe, and don't want 'Test Payment' to show up to the user on the front end, we should have a 'Manual'.

We had this come up previously with #6063 when doing filters.

**Comment by dgoldak** [comment]
@cklosowski, to confirm, would this apply to Test Payment not appearing on a receipt when it's a $0 purchase?

![Screen Shot 2019-08-22 at 3 15 55 PM](https://user-images.githubusercontent.com/30910807/63546619-d3229e80-c4ef-11e9-9a2e-1349745d9c74.png)

https://secure.helpscout.net/conversation/936179441/129531?folderId=180499

**Comment by pippinsplugins** [comment]
Easiest fix for this, I think, would be to just rename `Test Payment` to `Manual`.

**Comment by cklosowski** [comment]
My only thing with `Manual` is that this doesn't account for Free Downloads, and really just makes sense for adding a payment manually. I think something like 'Internal Gateway' or 'Store Gateway' makes sense.

**Comment by ashleyfae** [comment]
Do we need a tooltip or something to explain what `Store Gateway` means? Is that clear enough? `Test Payment` is pretty clear in its implications, but `Store Gateway` may not be. (I am happy with the label, just wondering if need an explanation somewhere.)

**Comment by robincornett** [comment]
Something like this?
![image](https://user-images.githubusercontent.com/4853066/86019552-bfd83d80-b9f4-11ea-91cb-a325c42404f9.png)

I think my personal preference would be to add it to the description text below, but can do this if preferred.

**Comment by spencerfinnell** [comment]
@robincornett What about:

> This is an internal payment gateway that does not process money and can be used for manually added orders or test purchases.

"process money" isn't my favorite but I think something that explains that there is no monetary transaction would be helpful.

**Comment by robincornett** [comment]
Alternatively, what about this--the long sentence feels a bit stilted?
> This is an internal payment gateway which can be used for manually added orders or test purchases. No money is actually processed.

**Comment by spencerfinnell** [comment]
@robincornett Much better. I think that explains things well.
