### ISSUE TITLE
3.0 - Reports: Gateway report can be confusing

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#7076]
### Expected behavior
The pie graphs for gateways should render correctly.

### Actual behavior
The pie graphs are showing incorrect amounts. As you can see I have 4 stripe purchases and 2 test payment gateways, however the pie graph shows 100% test payment gateway.
![reports-gateways-bug](https://user-images.githubusercontent.com/1390124/49825152-f67e3280-fd40-11e8-933a-ebf654b0927f.png)

### Information (if a specific version is affected):
PHP Version: All

EDD Version (or branch): `release/3.0`

WordPress Version: all

**Comment by spencerfinnell** [comment]
@cklosowski Is the chart data in the page source correct?

**Comment by cklosowski** [comment]
@spencerfinnell Debugging it now to determine what's happening. When I say 'render' it was a generic term, not necessarily about the graph itself.

**Comment by cklosowski** [comment]
Appears to be a data issue, not a library issue:
`data":[0,1,0,0]}],"labels":["PayPal Standard","Test Payment","Amazon","Stripe"]}`

**Comment by cklosowski** [comment]
Ok this looks to be an issue of data 'confusion'. The 30 day report here is what's default, but the table isn't respecting the range...it's giving totals lifetime, while the pie graphs are respecting the date ranges.

**Comment by cklosowski** [comment]
I'm going to update this issue, as there are some confusing parts about the gateway report. Being that the table is listing _all_ data, and the graphs are reporting only the range data, we should call this out in the reports tables, just so we don't get confusing reports and tables.

**Comment by cklosowski** [comment]
After review, this is a bug, the table is being sent the range, it's just not using it.

**Comment by cklosowski** [comment]
This is ready for some testing:
![fixed-gateway-reports](https://user-images.githubusercontent.com/1390124/49900339-88f30480-fe1b-11e8-8a6a-4d2e940b7fcf.png)

**Comment by pippinsplugins** [comment]
This looks to be working perfectly for me!
