### ISSUE TITLE
3.0 - Reports: Gray box appears on larger screens in the bottom-left corner

### ISSUE THREAD

**Issue by zackkatz** [easydigitaldownloads/easy-digital-downloads#7080]
On Reports tabs, there is a gray box at the bottom-left of each content area that grows and shrinks with the window size:

![Little gray box!](https://share.gravityview.co/Rz9tuC+)

Here are my browser details: https://whatsmybrowser.org/b/YPS6QPF

Here's a video showing it expanding: http://share.gravityview.co/TdCFkn

**Comment by SDavisMedia** [comment]
I've replicated this. The high of the nav elements needs to be more than the height of the content, I believe.

Activating Recurring, Software Licensing, and Cross-sell and Upsell should do it. There's a `br` element causing the issue. I can't tell what it's being used for yet. It's for clearing, obviously, but I don't see why it's needed yet.

![ef983e2c6d6abb50a1fd677ad437a229 _image 202018-12-12 20at 202 18 44 20pm](https://user-images.githubusercontent.com/2359131/49902535-09fccc80-fe19-11e8-90ce-6ffe1ba41b58.png)

**Comment by cklosowski** [comment]
@SDavisMedia you mind fixing this up for me? If you have any questions on the new webpack setup for 3.0 let me know and we'll get you fixed up.

**Comment by SDavisMedia** [comment]
I need to know why it exists first. Do you know, @JJJ?

**Comment by spencerfinnell** [comment]
@SDavisMedia it's the gradient here: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/assets/css/edd-admin.css#L2999

Not sure why that is set up like that though.

**Comment by spencerfinnell** [comment]
Attached a PR that explores a different technique for the column heights instead of using the background gradient.

**Comment by JJJ** [comment]
The gradient was responsible for drawing the vertical line between two block elements that couldn't both be 100% height. Browsers that don't support flex-box also have a hard time with `calc()`, so both would likely fail, and fallback to fixed width with the gradient.

Kind of opaque; not ideal, and y'all found it. :)

@spencerfinnell's PR seems OK to me, if the gradient is tripping folks up.

**Comment by SDavisMedia** [comment]
The PR is better but I think it creates another undesirable scenario:

<img width="873" alt="image 2018-12-14 at 11 08 59 am" src="https://user-images.githubusercontent.com/2359131/50022527-4f440a00-ff91-11e8-96d7-1ab7eba19693.png">

-----

Displaying the main elements as a table should work.

```css
.edd-vertical-sections { display: table; }
.section-nav, .section-wrap { display: table-cell; }
```

(`.section-nav` would need to lose its float)

**Comment by spencerfinnell** [comment]
@SDavisMedia does that happen in non-legacy panels too?

I tested that scenario I thought but it was just using default tabs.

**Comment by SDavisMedia** [comment]
Yea it can happen in any panel as far as I can tell.

![screenshot_2018-12-14 reports easy digital downloads 3 0 wordpress](https://user-images.githubusercontent.com/2359131/50023323-a6e37500-ff93-11e8-89c1-7bc2b1b92873.png)

If this is all about background color (forgive me if it's about something else), then the most straightforward solution is making sure both `.section-nav` and `.section-wrap` are always the same height (when side by side). That can be done with my CSS above.

If it's not about that, I'm not quite sure I understand the goal.

**Comment by spencerfinnell** [comment]
@SDavisMedia yes that is the goal -- and I tried that solution originally but wasn't happy with it. Your rendered page looks a bit off compared to mine: https://cloudup.com/csa01sykwFf

Does your `#edd-item-wrapper` have a background of white? That should exist even in the `release/3.0` branch: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/assets/css/edd-admin.css#L2501

When that is changed to red you can see how it should be filling in that column: https://cloudup.com/c4F1qF17WHy

What browser are you testing in? There's also a missing border on the bottom of your stat tile.

**Comment by SDavisMedia** [comment]
> Does your #edd-item-wrapper have a background of white? That should exist even in the release/3.0 branch: /3.0/assets/css/edd-admin.css@release#L2501

It does have a background of white. But it doesn't show up that way, which is weird. https://cl.ly/2167a1d79fdd

I'm in Firefox.

**Comment by spencerfinnell** [comment]
It looks like when the floats are forcefully cleared (setting `overflow: hidden`) I get the same results as you. Argh. I'll keep messing with it and see if I can find a solid solution with the `table` method as that was my initial direction as well.

**Comment by SDavisMedia** [comment]
Thanks, man!

**Comment by spencerfinnell** [comment]
@SDavisMedia Try that. Test on Chrome, Firefox, and Safari.

**Comment by JJJ** [comment]
`issue/7080` broke browser resizing/responsiveness, and also removed the percentage width on the vertical tabs and forced them to `200px` resulting in some wasted horizontal space.

I'm sure there's a better way than what I have in `release/3.0` but I don't think `issue/7080` is there quite yet. <3

**Comment by spencerfinnell** [comment]
Ugh this is like 3 lines with `flexbox` :(

I'll try something else.

**Comment by SDavisMedia** [comment]
Use JS to calculate tab/nav height and apply it as a minimum height for the content pane? Not ideal probably the closest we'll get to more advanced CSS behavior, which probably isn't an option.

**Comment by spencerfinnell** [comment]
Simplified PR that just shows white instead of the alternate column color if `flexbox` is not available: https://github.com/easydigitaldownloads/easy-digital-downloads/pull/7092
