### ISSUE TITLE
3.0 - Reports: Discount report has incorrect and missing data.

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#7083]
### Expected behavior
The discount report should give total savings and average savings. And the most popular discount should be accurate.

### Actual behavior
As per this screenshot. The Average and Total savings don't show up, even though I have used discounts, and the most popular discount is inaccurate.
![3-0-discount-report-issues](https://user-images.githubusercontent.com/1390124/49901153-ad4fe080-fe1d-11e8-8078-8bb8d6bf2d99.png)

### Information (if a specific version is affected):
PHP Version: All

EDD Version (or branch): `release/3.0`

WordPress Version: All

**Comment by cklosowski** [comment]
Ok so the tiles, the main issue is due to the way the prepare is altering the column name.

The code generates this:
`SELECT AVG('total')` which results in `0`

If I type manually in MySQL Workbench:
`SELECT AVG(total)` it calculates correctly.

**Comment by pippinsplugins** [comment]
Replicated and confirm the PR fixes it!
