### ISSUE TITLE
3.0 - Payment icon no longer shown when validating credit card number

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/easy-digital-downloads#7087]
## Bug Report

- Latest EDD `release/3.0`
- WP v5.0.1

### Expected behavior
When I enter a credit card number at checkout, I expect a credit card payment icon to appear like this:

<img width="888" alt="screen shot 2018-09-14 at 3 55 28 pm" src="https://user-images.githubusercontent.com/52581/45531148-74b26200-b842-11e8-8a5d-aedfa34f3957.png">

### Actual behavior
When I enter a credit card number, no payment icon is shown. 

This previously worked, as the work done here https://github.com/easydigitaldownloads/easy-digital-downloads/pull/6866#issuecomment-421235608 was merged in https://github.com/easydigitaldownloads/easy-digital-downloads/commit/0d2a3597f38637f7e4bfe5326829a13d394dab57

It seems the svg() function shown below has been removed the codebase since:
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/0d2a3597f38637f7e4bfe5326829a13d394dab57/assets/js/edd-checkout-global.js#L96-L134

There was also a slight tweak to the `edd_validate_card()` function to load the `svg()` function.

### Steps to reproduce the behavior
1) Go to checkout
2) Start typing 4242
3) The Visa icon is not shown near the credit card field

**Comment by spencerfinnell** [comment]
I can get this added back in.

**Comment by spencerfinnell** [comment]
PR attached.

**Comment by SDavisMedia** [comment]
Tested and working perfectly on my end. :+1:
