### ISSUE TITLE
3.0 - Orders: Finalize 'complete' status designation

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#7089]
We need to finalize the status terminology for orders/refunds. In the past we've always set a 'completed' order (previously a payment) to a status of `publish`.

We even went as far as catching people trying to set the status of `complete` or `completed` to `publish` in the code. With the introduction of refunds, they have a completed status of `complete`. This causes some weird issues with the query and stats classes, as they are 'completed' but don't have a status of `publish` like most of our code is looking for.

We should finalize this and choose one 'final' state for order types.

My vote is try move everything to `complete`, which would signify that an order or refund has reached it's end state of either collecting funds or sending funds back to the gateway.

I want to do this in a single branch and I believe it will solve things like #7088. Things we'll have to do:
1) Update our migration to change orders to 'complete' that are publish.
2) Update our order status update method to catch publish and 'completed' and convert it to complete.
3) Update query classes and stats classes to include 'complete' instead of 'publish'.
4) Update any UI where a dropdown sets the status to 'publish' when 'Completed' selected.

**Comment by cklosowski** [comment]
I'm going to do this alongside #7088 since it affected much of the same code and fixes.

**Comment by cklosowski** [comment]
Due to the far reaching changes here, I think it's best to get this tested as quickly as possible @mintplugins, so that we can merge it and move forward with the rest of 3.0

**Comment by mintplugins** [comment]
Code looks good to me, and I've tested purchases and refunds, all seems to be working well.
