### ISSUE TITLE
Extend discount requirements

### ISSUE THREAD

**Issue by kiarashi** [easydigitaldownloads/easy-digital-downloads#7090]
### Explain your enhancement (please be detailed)
In general, product x needs to be in the cart for a discount to work. This means that any customer can use the discount. 
I wish to create a discount code that can only be used by a selected group of customers based on their previous purchases.

### Justification or use case
I've created monthly subscriptions based products. Customers who purchase these types of products are called VIPS.  For these VIPS only I want to provide a discount for selected products in cart.

**Comment by cklosowski** [comment]
@kiarashi This is actually something we're looking to add to our Discounts Pro extension. We've got an open issue for development/feature tracking for a future release.
