### ISSUE TITLE
PDT amount validation sometimes fails due to some accounts not sending payment_gross

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#7105]
We currently use the `payment_gross` field during PDT for validating the payment amount. In some cases, this can result in the validation failing because the `payment_gross` field is not present.

Example report: https://wordpress.org/support/topic/pdt-validation-problem/#post-11057229

PayPal's documentation is inconsistent and unclear on which of these three variables should be used:

- amt
- payment_gross
- mc_gross

In some places they say `payment_gross` is deprecated; in some places they show PDT coded examples using `payment_gross`; and in some places they show a `amt` field that is specific to PDT.

What @cklosowski and I have found:

- `mc_gross` appears to always be set
- `payment_gross` is deprecated and only sometimes set
- `amt` doesn't seem to exist at all in PDT data

We have decided to do a four step check to be certain:

1. Check if `mc_gross` is present and use it if so
2. If `mc_gross` is not present, check for `payment_gross` and use it
3. If `payment_gross` is not present, check for `amt` and use it
4. If `amt` is not set, bail and leave payment as pending

Issue #4008 corroborates the theory that `mc_gross` is always set, even though PayPal documentation possibly indicates otherwise.

**Comment by cklosowski** [comment]
A note, and clarification...it's not that the `payment_gross` isn't present, it is present, but set to `0` in cases where it isn't being used.
