### ISSUE TITLE
Woocommerce vs EDD Issue

### ISSUE THREAD

**Issue by ramseygman** [easydigitaldownloads/easy-digital-downloads#7114]
I installed woocommerce first, EDD second.

EDD products can be added to cart but I cannot add woocommerce products to cart. Please help.

The woocommerce products are greyed out. I have variable options as well for the woocommerce products and the drop down cannot be selected.

It works on mobile but not desktop.

**Comment by cklosowski** [comment]
@ramseygman I apologize for your issues however Github is for development tracking only. Please contact our support team here:
https://easydigitaldownloads.com/support
