### ISSUE TITLE
3.0 - Profile Editor: Editing the Customer billing address in the [edd_profile_editor] does not seem to save

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#7124]
### Expected behavior
When editing my Customer billing address in the `[edd_profile_editor]` shortcode, my information should be saved.

### Actual behavior
My information is not saved.

### Steps to reproduce the behavior
1) Create a page with just the `[edd_profile_editor]` shortcode, or if you are using Vendd, create a blank page with the EDD Members page template.
2) Visit this page as a logged in user and edit your Billing Address
3) click to save changes
4) A page refresh happens and says your information was saved, however the form fields are not updated.

### Information (if a specific version is affected):
PHP Version: All

EDD Version (or branch): `release/3.0`

WordPress Version: All

Any other relevant information: None

**Comment by spencerfinnell** [comment]
@JJJ since the `[edd_profile_editor]` shortcode is option and not automatically added to a page on installation I wonder if site owners would be confused by seeing all the customer accounts created if they have a non-ecommerce portion of their site as well.

I can submit a PR for 2 -- I think that's a good starting point that would still allow your option in the future.

**Comment by JJJ** [comment]
Agree. Good point. Could always make it an option later, etc…

**Comment by cklosowski** [comment]
The interesting thing here, is that I do have a customer attached to this user. It's my admin user I was experiencing it with. I'll check the PR though, see if that catches my use case here.

**Comment by cklosowski** [comment]
Yep this added it to my existing customer, notice the 'first used' on the address I just added.
![image](https://user-images.githubusercontent.com/1390124/51516542-09bafe00-1dd5-11e9-93c1-96dbeec1b57a.png)

Also, it didn't create a new customer, which is ideal here, and added it to my existing customer. :+1: from me.

**Comment by cklosowski** [comment]
@jjj we have had an open discussion, a while back about a customer merge tool. I think that would be ideal in the long term future. hopefully in the 3.x life cycle.
