### ISSUE TITLE
Make it possible to add products to product-less payments

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#7132]
### Expected behavior
When a payment has no product attached (for some strange, unknown reason), I expect to be able to add a product to that payment to fix it. 

### Actual behavior
I cannot add a product to the payment, because the JS duplicates the HTML element for an already-existing payment. The problem? There's no already-existing payment to duplicate, so instead it duplicates the header row:

<img width="944" alt="screen shot 2019-01-22 at 10 40 14 am" src="https://user-images.githubusercontent.com/1638128/51546438-22a5cc80-1e32-11e9-940a-791f2f513295.png">

### Steps to reproduce the behavior
1) Purchase a product
2) In your database's post_meta table, delete the `_edd_payment_meta` row for that payment
3) View the payment in wp-admin
4) Attempt to add a product to the payment. You won't be able to. 

### Information (if a specific version is affected):
PHP Version: 7.0.2

EDD Version (or branch): master

WordPress Version: 5.0.3

**Comment by mintplugins** [comment]
The fix for this will need to be a bit of a workaround in order to work with the existing JS cloning approach. In order to give the JS something to clone, the simplest approach is to give it an empty element to clone. If no products are attached to a payment, it will now look like this:

<img width="1036" alt="screen shot 2019-01-22 at 11 05 29 am" src="https://user-images.githubusercontent.com/1638128/51548114-a6ad8380-1e35-11e9-95b4-e44256b8760f.png">

You can then add products to the order because the JS has something to duplicate.

**Comment by mintplugins** [comment]
## Steps to test the fix
1. Purchase a product
2. In your database's post_meta table, delete the _edd_payment_meta row for that payment
3. View the payment in wp-admin
4. You should now be able to add a product to the payment successfully.

**Comment by mintplugins** [comment]
Affected customer tickets:
https://secure.helpscout.net/conversation/738686267/97253?folderId=180502
https://secure.helpscout.net/conversation/756540606/98766?folderId=749231

**Comment by cklosowski** [comment]
This seems like a logical approach, I just have one concern. If the `_edd_payment_meta` item is deleted, there is a host of other order information that is also deleted.

Are we recovering/rebuilding that in anyway or just planning on adding an item to the order?

**Comment by mintplugins** [comment]
@cklosowski I'm not totally sure if I understand, but for the scenarios affected here, I don't think there is any `_edd_payment_meta` that exists in the first place.  

These are just weird edge-cases where a payment was created without any products attached, rogue code deleted the `_edd_payment_meta`, or the `_edd_payment_meta` was deleted by a site admin who didn't fully understand what they were doing. 

This purely gives them a way to re-build those broken payments. I've put that (deleting `_edd_payment_meta`) purely as a testing step just so that we can create this weird edge-case ourselves.

**Comment by pippinsplugins** [comment]
PR works!

Only thing I think we should adjust: when a payment is loaded without any download items and then a download is added, we should remove the placeholder, otherwise we end up with this (until the order is updated and screen reloads):
![image](https://user-images.githubusercontent.com/1034109/55849461-4665de00-5b16-11e9-9551-3d3670063dbe.png)

**Comment by pippinsplugins** [comment]
PR updated to remove the place holder row. Ready for new testing.

**Comment by mintplugins** [comment]
Nice - that's super smooth now. PR re-tested and confirmed fixed

**Comment by cklosowski** [comment]
Working fine for me.
