### ISSUE TITLE
Discount Code "Uses" not properly sorting

### ISSUE THREAD

**Issue by dgoldak** [easydigitaldownloads/easy-digital-downloads#7139]
### Expected behavior
Use count should sort in numeric order. For example; 7, 79, 703

### Actual behavior
It appears it's sorting in alphabetical order instead of numeric.

![screen shot 2019-01-23 at 3 15 40 pm](https://user-images.githubusercontent.com/30910807/51637576-c621da80-1f21-11e9-83fe-1d5b6eba7875.png)

### Steps to reproduce the behavior
1) Create 3 discount codes and see the number of uses to 7, 79 and 703 (I did it directly via the db)
2) Sort by use count under Downloads > Discounts

### Information (if a specific version is affected):
PHP Version: 7.0

EDD Version (or branch): `release/3.0`

WordPress Version: 5.0.1

Any other relevant information:
I suspect we need to confirm other numeric only columns are properly sorting.

**Comment by JJJ** [comment]
This is still happening in EDD3.0.

**Comment by cklosowski** [comment]
Looks like it's probably due to a compare being 'string' based instead of 'numerically based'.

`703` would precede `7`, because of the `0`, and `79` would follow `7` due to the `9`.

**Comment by JJJ** [comment]
> Looks like it's probably due to a compare being 'string' based instead of 'numerically based'.
> 
> `703` would precede `7`, because of the `0`, and `79` would follow `7` due to the `9`.

That was my first guess, but I don't think so.

Here's what I'm seeing when sorting by "Uses"
URL: `edit.php?post_type=download&page=edd-discounts&orderby=use_count&order=asc`

<img width="155" alt="jjj-on-2021-08-31-at-17-49-51@2x" src="https://user-images.githubusercontent.com/88951/131585696-f0525b3a-b54f-4b86-b362-3c54e443f35e.png">

My next guess is that it's just sorting by some other column, possibly the default one.

**Comment by JJJ** [comment]
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/c595891648adf2395baa42ad0a2a5909b8004f92/includes/database/schemas/class-adjustments.php#L139-L146

The Column in the Schema isn't defined as being sortable. Adding `'sortable' => true` might wake it up?

**Comment by JJJ** [comment]
Fixed and merged in the `release/3.0` branch.

Made the necessary review and milestone adjustments.
