### ISSUE TITLE
Discount is_started should be checking in UTC

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#7156]
## Bug Report

Discount codes are saved in UTC, which is good. They are entered in UTC as well, which is not good, as it can be confusing for site owners. Additionally, logic performed on that date is done as though it was entered and saved in the local WordPress timezone. 

### Expected behavior
When I have a discount code set to start at 03:00:00 UTC, I expect it to start at 03:00:00 UTC, regardless of my WordPress timezone.

### Actual behavior
When I have a discount code set to start at 03:00:00 UTC, it only starts working after 03:00:00 UTC if my WordPress Timezone is also UTC. Otherwise it starts working at 03:00:00 in my local timezone. 

The problem with this approach is that if I move to another timezone, changing my WP timezone will adjust the start-time of _all_ my discount codes as well. Certain start-times are customer specific, such as discount codes created by EDD Reviews. Changing the start times to match the WP timezone throws it out of sync from the customer's timezone. 

Therefore, the date should always be in-sync with UTC. 

### Steps to reproduce the behavior
1) Set your WP timezone to be your local timezone. I'm in the EST timezone, which is UTC-5 at this time of year (it's February, taking into account daylight savings).

2) Create a discount code, setting the start time to today's date, starting at the current time in your local timezone. For me, that's 2:38PM EST, which is 14:38:00 EST in 24 hour time.

<img width="564" alt="screen shot 2019-02-06 at 2 41 47 pm" src="https://user-images.githubusercontent.com/1638128/52368853-66e1c100-2a1d-11e9-811f-df32578205f3.png">

2) Notice the discount works
<img width="748" alt="screen shot 2019-02-06 at 2 44 18 pm" src="https://user-images.githubusercontent.com/1638128/52368999-b3c59780-2a1d-11e9-81d6-02466325fb1f.png">

3) Pretend you moved west, and change your WP Timezone to be something at least an hour earlier than your timezone. For me that's UTC-6. 

4) Notice the discount does not work now. 
<img width="734" alt="screen shot 2019-02-06 at 2 45 55 pm" src="https://user-images.githubusercontent.com/1638128/52369109-eec7cb00-2a1d-11e9-8d13-fbb6d8da2bdb.png">

5) My expectation is that the discount start time is not affected by the WordPress timezone, but rather, that all logic that is executed is based on the time in UTC. 

The date can and should be converted the the local timezone upon display, but saving and logic should be performed with the UTC time. 

### Information (if a specific version is affected):
PHP Version: 7.2

EDD Version (or branch): master

WordPress Version: 5.0.3

**Comment by nutsandbolts** [comment]
Sent to a customer for testing via ticket https://secure.helpscout.net/conversation/771198160/100069?folderId=2657915

**Comment by cklosowski** [comment]
@nutsandbolts did we get a response from the custoemr? this is the last open issue for the release.

**Comment by nutsandbolts** [comment]
@cklosowski No reply from the customer so I’ll assume it resolved the issue.

**Comment by cklosowski** [comment]
@nutsandbolts can we reach out and confirm? Before we release I just want to make sure

**Comment by nutsandbolts** [comment]
@cklosowski Yep, just asked and I’ll let you know as soon as I hear something back from her.

**Comment by nutsandbolts** [comment]
@cklosowski FYI the customer did not try the patched version.

**Comment by cklosowski** [comment]
Ok unit tests are passing for this, we'll go ahead and merge and get it on our site and release once we've let it bake.
