### ISSUE TITLE
EDD_SL & _site_transient_update_plugins

### ISSUE THREAD

**Issue by kiarashi** [easydigitaldownloads/easy-digital-downloads#7160]
This topic is neither a bug or an enhancement request. Instead it's more of a discussion. ;)

Most EDD plugins uses the Software Licensing extension for auto updates and I noticed one drawback.
The transient (_site_transient_update_plugins) is saving way too much information inside my database that I actually don't want. I fully understand what this transient does and I can understand product details, but those long changelog info are becoming an issue. 
![db-improvements](https://user-images.githubusercontent.com/7079137/52540743-5ae35f80-2d8d-11e9-8319-cc206dfd5c19.png)

WishList, Reviews, FES, Commission are plugins with such long changelogs. Isn't there something we can do about it?

Kind regards, 
Kiarashi

**Comment by cklosowski** [comment]
@kiarashi Thanks for the suggestion. This is actually something that needs to be done in the Software Licensing addon (since we use it to deliver our own software) and we already have an issue opened to try and come up with a solution for this. Appreciate the feedback.
