### ISSUE TITLE
3.0 - Migration: Error logged while migrating discount codes

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#7169]
### Expected behavior
When Migrating discount codes, no errors should be thrown in the AJAX request.

### Actual behavior
The following PHP error was produced during the migration process for discount codes:
```
{"type":"notice","message":"Undefined property: QM_DB::$edd_discountmeta","file":"wp-includes/wp-db.php","line":666,"stack":["EDD\\A\\U\\v\\Base->find_legacy_id()","EDD\\A\\U\\v\\Discounts->get_data()","EDD\\A\\U\\v\\Base->process_step()","edd_do_ajax_export()","do_action('wp_ajax_edd_do_ajax_export')"],"component":"Plugin: debug-bar"}
```
We can ignore the fact taht it says debug bar, that's just the one that caught it, It seems that maybe we aren't registering the meta db table for the discounts codes or something simliar.

### Steps to reproduce the behavior
1) Have a 2.9.x store, and create multiple discounts.
2) Start the migration

### Information (if a specific version is affected):
PHP Version: 7.0

EDD Version (or branch): `release/3.0`

WordPress Version: 5.1

Any other relevant information: The migration seems to have completed successfully. My discount codes came over in tact.

**Comment by mintplugins** [comment]
This may have been fixed here:
https://github.com/easydigitaldownloads/easy-digital-downloads/commit/8a776adf601f074d4ea5236c1c27f067421960e0

**Comment by cklosowski** [comment]
Yeah I haven't noticed this sneak up any more times. Closing :+1:
