### ISSUE TITLE
apiFetch call resulting in invalid JSON response

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/easy-digital-downloads#7174]
### Expected behavior

When making a request to the EDD API using WordPress' API Fetch utility (https://github.com/WordPress/gutenberg/tree/master/packages/api-fetch), I'd expect the resulting JSON to be valid.

### Actual behavior

When making a request, the returned JSON is invalid.

This is causing EDD Blocks to fail and no downloads can be retrieved. See: https://github.com/easydigitaldownloads/edd-blocks/issues/43

I'm not 100% certain if this is an issue with WP 5.1, or with EDD (because of the changes made).

### Steps to reproduce the behavior
1) Install and activate EDD v2.9.11, with WordPress 5.1. EDD is the only required plugin to test.
2) Go to Pages -> Add New (so the API Fetch utility is available)
3) In the browser console run:

```
wp.apiFetch( { url: '/?edd-api=products' } ).then( downloads => { console.log( downloads ); } )
```

You should then see:

```
Unhandled promise rejection 
Object { code: "invalid_json", message: "The response is not a valid JSON response." }
```

Screenshot:

<img width="857" alt="screen shot 2019-03-05 at 10 06 23 am" src="https://user-images.githubusercontent.com/52581/53762970-5e9e7800-3f2e-11e9-9743-6ad576829eff.png">

Switching over to `Network` -> `XHR` (testing with Firefox) and clicking on the GET request, you will see this in the `Response` tab:

```
SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 354 column 2 of the JSON data
```

Screenshot (see pink line):

<img width="2026" alt="screen shot 2019-03-05 at 10 08 31 am" src="https://user-images.githubusercontent.com/52581/53763067-acb37b80-3f2e-11e9-8456-88866e14507f.png">

At the bottom of the response payload, on line 354, you can see the data that's causing the invalid JSON response:

```
{"code":"wp_die","message":"","data":{"status":400},"additional_errors":[]}
```

Screenshot:

<img width="1202" alt="screen shot 2019-03-05 at 10 09 46 am" src="https://user-images.githubusercontent.com/52581/53763144-d79dcf80-3f2e-11e9-8595-8dad0b555d8a.png">

### Information

EDD Version (or branch): v2.9.11 or `release/3.0` branch

WordPress Version: 5.1 seems to be the issue (at least for me). On WP versions below 5.1 I can make the fetch request and the JSON response is valid, and EDD Blocks works fine.

~~@misulicus however is seeing this issue with WP 5.0.1. I cannot replicate the issue on anything below WP 5.1.~~ Edit: It does only affect WP 5.1 

From what I can see so far, WP 5.1 introduced a new handler function for `wp_die()` when processing JSON requests: `_json_wp_die_handler()`:
https://github.com/WordPress/WordPress/blob/master/wp-includes/functions.php#L3224

We call `edd_die()` which calls `wp_die()` here: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/api/class-edd-api.php#L1913

The new `_json_wp_die_handler()` function is causing the invalid JSON response in my testing, since if I kill it just before this line (https://github.com/WordPress/WordPress/blob/master/wp-includes/functions.php#L3243) the JSON is valid.

**Comment by misulicus** [comment]
@amdrew i wanted to write 5.1 instead of 5.0.1. I was mobile at that time.
so the issue i reported was on the latest release of WP which is 5.1 not 5.0.1

**Comment by amdrew** [comment]
@misulicus Ahh! Thanks for the clarification 👍

**Comment by amdrew** [comment]
It's probably worth noting that requesting posts from WordPress with v5.1 is fine, there's no invalid JSON response:

```
wp.apiFetch( { url: '/wp-json/wp/v2/posts' } ).then( posts => { console.log( posts ); } )
```

or
```
wp.apiFetch( { path: '/wp/v2/posts' } ).then( posts => { console.log( posts ); } )
```

**Comment by spencerfinnell** [comment]
`edd_die()` just needs to be removed. Maybe replace with `exit` but it’s likely fine with nothing there or a `return`. I’ll try to test soon!

**Comment by amdrew** [comment]
I think I tried removing `edd_die()` as a test but the JSON response came back even more messed up (with the rest of the page's HTML in it). I didn't test exit or return though. Will test soon also.

**Comment by amdrew** [comment]
No bueno with removing edd_die() or using `return`. `exit` however seemed to do the trick in my quick test!

**Comment by pippinsplugins** [comment]
`edd_die()` was added to make unit tests of the API work.

Looking at it I'm not yet sure exactly how it works but I'm looking.

**Comment by pippinsplugins** [comment]
PR submitted that I believe fixes it and allows unit tests to continue to operate as is.

**Comment by misulicus** [comment]
Could be related perhaps.
A customer reported that the Android app( https://play.google.com/store/apps/details?id=com.mmetting.edd&hl=en ) fails to sync anymore ever since his site updated to 5.1

The developer of the app investigated and sent him this
```
I was playing around a bit and could see, that your Wordpress replies sometimes with a HTTP status 400 Bad request.
{
    "earnings": {
        "today": 0,
        "current_month": 454.6200000000000045474735088646411895751953125,
        "last_month": 1009.6499999999999772626324556767940521240234375,
        "totals": 54321.4000000000014551915228366851806640625
    },
    "request_speed": 0.005960941314697265625
}{"code":"wp_die","message":"","data":{"status":400},"additional_errors":[]}
```

When i saw the extra {} in there i thought its related to this if not the same issue so i'm posting here.

**Comment by misulicus** [comment]
@pippinsplugins customer from above reply applied your PR and the android app now works again without any issues for his site

**Comment by cklosowski** [comment]
This is broken the unit tests:
```
 ✘ cklosowski@Turing  ~/Development/edd-dev/wp-content/plugins/easy-digital-downloads   issue/7174  phpunit
Installing...
Running as single site... To run multisite, use -c tests/phpunit/multisite.xml
Not running ajax tests. To execute these, use --group ajax.
Not running ms-files tests. To execute these, use --group ms-files.
Not running external-http tests. To execute these, use --group external-http.
Installing Easy Digital Downloads...
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

....%  
```

Vs on `master`
```
 cklosowski@Turing  ~/Development/edd-dev/wp-content/plugins/easy-digital-downloads   master  phpunit
Installing...
Running as single site... To run multisite, use -c tests/phpunit/multisite.xml
Not running ajax tests. To execute these, use --group ajax.
Not running ms-files tests. To execute these, use --group ms-files.
Not running external-http tests. To execute these, use --group external-http.
Installing Easy Digital Downloads...
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

.........................................................I.....  63 / 638 (  9%)
............................................................... 126 / 638 ( 19%)
............................................................... 189 / 638 ( 29%)
............................................................... 252 / 638 ( 39%)
...I.....................................I..................... 315 / 638 ( 49%)
..................................................I.I......I... 378 / 638 ( 59%)
............................................................... 441 / 638 ( 69%)
............................................................... 504 / 638 ( 78%)
............................................................... 567 / 638 ( 88%)
I.............................................................. 630 / 638 ( 98%)
........                                                        638 / 638 (100%)

You should really fix these slow tests (>150ms)...
 1. 914ms to run Tests_Emails:test_fallback_for_invalid_from_address
 2. 897ms to run Tests_API:test_query_vars
 3. 386ms to run Tests_Activation:test_edd_install_roles_on_network
 4. 218ms to run Tests_Payments:test_payments_date_query
 5. 212ms to run Tests_Tools:test_system_info
 6. 198ms to run Tests_Customers:test_edd_add_past_purchases_to_new_user
 7. 196ms to run Tests_Payment_Class:test_remove_with_multiple_same_price_by_price_id_different_prices
 8. 192ms to run Tests_Discounts:test_is_used_case_insensitive
 9. 190ms to run Tests_Payment_Class:test_remove_with_multiple_same_price_by_price_id_same_prices
 10. 173ms to run Tests_Stats:test_get_earnings_by_date_of_download
...and there is 1 more above your threshold hidden from view

Time: 33.29 seconds, Memory: 50.25MB

OK, but incomplete, skipped, or risky tests!
Tests: 638, Assertions: 2225, Incomplete: 7.
```

Also, while Travis CI says it passes, it is not, no tests are running on Travis, this method just exits with a code of `0` instead of `1`, which means as far as travis knows nothing failed...however it never failed b/c nothing was run:
`issue/7174`
https://travis-ci.org/easydigitaldownloads/easy-digital-downloads/jobs/502370362#L557

`master`
https://travis-ci.org/easydigitaldownloads/easy-digital-downloads/jobs/499441700#L551

**Comment by cklosowski** [comment]
Just pushed up some changes that should fix the unit tests as well as prevent the issue from occuring. @amdrew can you verify this still fixes the front end? Appeared to fix it for me.

**Comment by spencerfinnell** [comment]
Adding (and keeping everything else the same)

`add_filter( 'wp_die_json_handler', '_edd_die_handler', 10, 3 );`

Fixes responses for me, and allows unit tests to run.

**Comment by cklosowski** [comment]
@pippinsplugins @spencerfinnell the single line addition does resolve the issue without the use of checking constants and logic.

I think that's the better approach. I'm going to push up a new commit with this change.

**Comment by amdrew** [comment]
@cklosowski @spencerfinnell Working beautifully here 👍

**Comment by pippinsplugins** [comment]
Merged.
