### ISSUE TITLE
API v2 strpos expects string

### ISSUE THREAD

**Issue by tobeyadr** [easydigitaldownloads/easy-digital-downloads#7175]
### Expected behavior
No PHP Warnings

### Actual behavior
PHP Warning: strpos() expects parameter 1 to be string, array given in /wp-content/plugins/easy-digital-downloads/includes/api/class-edd-api-v2.php on line 76

### Steps to reproduce the behavior
1) Pass an array of categories to the product api v2

### Information (if a specific version is affected):
PHP Version: 7.3
EDD Version (or branch): 2.9.11
WordPress Version: 5.1

Any other relevant information:
Just add this to the if condition to solve. is_string( $args['category']  )

**Comment by tobeyadr** [comment]
See #7176 for solution

**Comment by pippinsplugins** [comment]
I think instead of checking if it's a string, we should force it to be an array, otherwise passing in an array will fail. Both strings and arrays should be supported.

**Comment by tobeyadr** [comment]
I agree 100%, in that case I beleive the best solution would be something like this.

`if ( is_string( $args[ 'categrory' ] )  ) {
					$args['category'] = explode( ',', $args['category'] );
				}
`

**Comment by tobeyadr** [comment]
see #7176
