### ISSUE TITLE
Stripe Costumer ID missing on database

### ISSUE THREAD

**Issue by planetahuevo** [easydigitaldownloads/easy-digital-downloads#7185]
Hi, 
I am trying to create a custom form for my users to be able to update their card on Stripe. 
I have everything ready using this
 https://stripe.com/docs/recipes/updating-customer-cards

But there is a problem: 
"One important thing to note here is you'll need the Stripe customer ID to make the update request. Presumably you have some sort of user table that tracks your users and allows them to log in. This table could also store the user's Stripe customer ID, created when they first registered at your site."

But I cannot find the customer ID anywhere on your database. 
Can we incorporate this in the future?

Thanks

**Comment by cklosowski** [comment]
@planetahuevo Stripe is not part of EDD core and so this data is not part of the EDD user data. It is stored on the customer meta for the customer record.

I'm closing this as it's not a feature of EDD core but of Stripe, and the customer Id does exist.

**Comment by planetahuevo** [comment]
Sorry for that. 
Is there a github for the stripe addon? 
Any docs that show the customer id (not the EDD but the stripe one)?

**Comment by planetahuevo** [comment]
Found it. Thanks for the tip.
