### ISSUE TITLE
PayPal PDT should limit when it is sent.

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#7190]
### Expected behavior
PayPal PDT verification should only be run when the purchase session matches that of the PDT payment trying to be verified.

### Actual behavior
If you have a valid purchase session, but revisit (via bookmark) the purchase confirmation page that you visited while using PDT, the purchase confirmation will be for your valid purchase session, however, PDT will still fire.

### Steps to reproduce the behavior
** Ensure Debug Logging is enabled **
1) Make a purchase with PayPal Standard with PDT enabled. (Take note of the payment ID)
2) When complete, bookmark the purchase confirmation page that should contain `payment-id` and `txn` (at a minimum)
3) Make another purchase (I used stripe to prove the differences)
4) Once at the purchase confirmation page, make note of the new payment ID
4a) Clear your EDD Debug Log to make this easier.
5) Click on the bookmark you created from step 2
6) Notice that the purchase confirmation page is loaded for the payment in step 4
7) Check your debug log, and notice a PDT verification was sent.
etc, etc

### Information (if a specific version is affected):
PHP Version: All

EDD Version (or branch): 2.8.13 or greater

WordPress Version: All

**Comment by mintplugins** [comment]
I replicated step 6, but not step 7. No PDT verification was logged in my debug log. Confirming EDD debug mode is on.
