### ISSUE TITLE
Invalid REST API Responses with WP 5.1+

### ISSUE THREAD

**Issue by justinstern** [easydigitaldownloads/easy-digital-downloads#7194]
### Expected behavior

When I perform a REST API request I expect a valid JSON document in response, e.g.

```
GET /edd-api/discounts

{"discounts"=>[
  {
    "ID"=>1, 
    "name"=>"10OFF", 
    "code"=>"10OFF", 
    "amount"=>10, 
    "min_price"=>50, 
    "type"=>"percent",
    "uses"=>0, 
    "max_uses"=>0, 
    "start_date"=>"", 
    "exp_date"=>"03/28/2019 23:59:59", 
    "status"=>"active", 
    "product_requirements"=>[], 
    "requirement_condition"=>"", 
    "global_discount"=>false, 
    "single_use"=>false
  }], 
  "request_speed"=>0.005810976028442383
}
```

### Actual behavior

Invalid JSON response, notice the unexpected "wp_die" block at the end:

```
GET /edd-api/discounts

{"discounts"=>[
  {
    "ID"=>1, 
    "name"=>"10OFF", 
    "code"=>"10OFF", 
    "amount"=>10, 
    "min_price"=>50, 
    "type"=>"percent",
    "uses"=>0, 
    "max_uses"=>0, 
    "start_date"=>"", 
    "exp_date"=>"03/28/2019 23:59:59", 
    "status"=>"active", 
    "product_requirements"=>[], 
    "requirement_condition"=>"", 
    "global_discount"=>false, 
    "single_use"=>false
  }], 
  "request_speed"=>0.005810976028442383
}{"code":"wp_die","message":"","data":{"status":400},"additional_errors":[]}
```

### Steps to reproduce the behavior

1. Update to WP 5.1+
2. Perform any EDD REST API request and inspect the response

### Information (if a specific version is affected):

WordPress Version: 5.1+

Any other relevant information:

This seems to be the result of the existing call to `edd_die()` here:

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/68cc2532f811a1965d0343a08dfa5db677d0930f/includes/api/class-edd-api.php#L1913

In conjunction with this handling of json requests within the `wp_die()` method added in 5.1:

[wp-includes/functions.php#L2983-2991](https://github.com/WordPress/WordPress/blob/6b6201ed8937f56ff2d2e65c387db834e76b78f5/wp-includes/functions.php#L2983-2991)

``` php
	} elseif ( wp_is_json_request() ) {
		/**
		 * Filters the callback for killing WordPress execution for JSON requests.
		 *
		 * @since 5.1.0
		 *
		 * @param callable $function Callback function name.
		 */
		$function = apply_filters( 'wp_die_json_handler', '_json_wp_die_handler' );
```

Replacing the `edd_die()` call with `die()` or `exit()` resolves the issue, there's other potential solutions as well.

**Comment by cklosowski** [comment]
@justinstern have you tested with ED D 2.9.12 which was released today to address this?

**Comment by justinstern** [comment]
d'oh, we ran into this earlier today with (the at the time latest) version of 2.9.11 and I just now got around to adding the issue without first checking for a hot fix. testing now

**Comment by cklosowski** [comment]
Thanks.

Possibly related/duplicate: #7174

**Comment by justinstern** [comment]
@cklosowski yup working perfectly now, apologies for the extraneous issue!

**Comment by cklosowski** [comment]
No worries at all!
