### ISSUE TITLE
Save post_date_gmt when updating a payment

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#7195]
### Expected behavior
When I change the date of a payment, I expect the `post_date_gmt` column to be adjusted as well as the `post_date` column. 

### Actual behavior
Only the `post_date` column is adjusted to reflect the updated date. 

### Steps to reproduce the behavior
1) Edit a payment's date to be a different day
2) View the payment in the database
3) Notice the post_date column reflects that change, but the post_date_gmt column does not.

**Comment by cklosowski** [comment]
Honestly, this won't be an issue with 3.0, I believe. Can you verify?

**Comment by mintplugins** [comment]
In 3.0 it shouldn't be a problem.

**Comment by cklosowski** [comment]
Ok, if that's the case let's not do anything with this for now. I'd like to keep things like this to a minimum as they are sure to cause a merge conflict as we move forward.
