### ISSUE TITLE
Download import tool Amazon S3 path issue

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#7199]
### Expected behavior
Within my CSV file I have my download path set like this for each product:

`bucketname/BEPE_EnglishDaisy_20180518_2.jpg`

However, when the import tool is used it breaks this up into two separate files within the "download", based on the /. I would expect this to be treated like an Amazon S3 path and a single file created.

### Actual behavior
We end up with two files assigned with the incorrect names and paths. For a single path, we should only see one file.

### Steps to reproduce the behavior
1) Create a basic CSV file with a single download, give the "download files" field this data: bucketname/BEPE_EnglishDaisy_20180518_2.jpg
2) Map and import the contents of the file.
3) Check the download and you will see this:

<img width="819" alt="Screenshot 2019-04-03 21 45 48" src="https://user-images.githubusercontent.com/22668877/55508288-deb51c00-5659-11e9-86b5-2297720f9580.png">

### Information (if a specific version is affected):
PHP Version: 7.2

EDD Version (or branch): 2.9.12

WordPress Version: 5.1.1

**Comment by davidsherlock** [comment]
It's due to this function str_to_array. This line to be exact:

```
		} elseif( false !== strpos( $str, '/' ) && ! filter_var( str_replace( ' ', '%20', $str ), FILTER_VALIDATE_URL ) && '/' !== substr( $str, 0, 1 ) ) {

			$delimiter = '/';

		}
```

**Comment by davidsherlock** [comment]
Commenting out `$delimiter = '/';` fixes the issue.

**Comment by mintplugins** [comment]
Related: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5620

**Comment by pippinsplugins** [comment]
I've attached a PR that resolves the issue successfully.

@dgoldak could you test it?

**Comment by pippinsplugins** [comment]
Here's a sample CSV that can be used to test it:
```
Name, Files, Price
Product 1, http://site.com/file.jpg, 10
Product 2, http://site.com/file1.jpg|http://site.com/file2.jpg, 5
Product 3, bucket/file.jpg, 20
```

**Comment by mintplugins** [comment]
Replicated on master and confirmed fixed on `issue/7199`

<img width="944" alt="Screen Shot 2019-10-29 at 2 57 19 PM" src="https://user-images.githubusercontent.com/1638128/67799797-6fbb6c80-fa5c-11e9-9511-9b179aea92ec.png">

<img width="928" alt="Screen Shot 2019-10-29 at 2 57 45 PM" src="https://user-images.githubusercontent.com/1638128/67799821-7c3fc500-fa5c-11e9-964a-b86b966caf80.png">

<img width="944" alt="Screen Shot 2019-10-29 at 2 58 03 PM" src="https://user-images.githubusercontent.com/1638128/67799835-8661c380-fa5c-11e9-84a8-d78d7c23ff97.png">
