### ISSUE TITLE
Use New wp_initialize_site Action

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/easy-digital-downloads#7200]
### Expected behavior

When creating a new site in a multisite environment there should be no errors.

### Actual behavior

There is a warning about deprecated hook usage in 5.1+

### Steps to reproduce the behavior
1) Use WordPress 5.1+
2) Create a new site using `wp_insert_site()`

### Information (if a specific version is affected):

PHP Version: All
EDD Version (or branch): master
WordPress Version: 5.1+

Any other relevant information:

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/install.php#L251

https://github.com/WordPress/WordPress/blob/0607371f845102cba675f74dbff57a656fb12fde/wp-includes/ms-site.php#L95

**Comment by SDavisMedia** [comment]
Replicated on `master` and WP 5.1.1. Confirmed no install warnings/notices/errors on `issue/7200`, and all install steps seem to work properly. :+1:
