### ISSUE TITLE
Incorrect conditional check when removing discounts from checkout cart

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#7204]
## Bug Report
We use AJAX to remove a discount from the cart. In `edd-checkout-global.js`, we check the AJAX response to see if there are any discounts remaining in the cart in order to make other adjustments. This check assumes that an empty array evaluates as false, but it actually evaluates as true.

### Expected behavior
When your checkout cart has discounts, removing the last discount should result in the entire `.edd_cart_discount_row` element being removed (hidden) from the HTML structure.

### Actual behavior
In my custom HTML structure (working on EDD site redesign), the row element containing discounts is not removed when the last discount is removed, even though the JS targets this element for removal.

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/assets/js/edd-checkout-global.js#L251-#L255

This is happening because `discount_response.discounts` is an empty array. So `if( ! discount_response.discounts ) {...}` evaluates as false and the enclosed code will not run.

### Steps to reproduce the behavior
I'm not 100% clear on why my HTML structure exposed this issue, while a standard EDD core HTML structure doesn't seem to have any problems.

### Information (if a specific version is affected):
EDD Version (or branch): `master`

### Any other relevant information:
@spencerfinnell Helped pinpoint the problem. I'm working with my own custom JS file that is very similar to EDD core's JS, so I'm good to go by changing:

`if( ! discount_response.discounts ) {...}`

to

`if( 0 === discount_response.discounts.length ) {...}`

I won't assign this issue, but Spencer wants to explore and make sure we implement the most logical fix since we could also change the type of data in the response, remove the check altogether, etc.

**Comment by cklosowski** [comment]
This seems like a valid enough change. I would also suggest...that we fix it upstream not just in the JS. We shouldn't have a function that returns two types (`boolean` and `array`).

This makes it extremely likely we'll run into PHP 7.3 issues if someone assumes a `count` can be run on it.

**Comment by spencerfinnell** [comment]
@cklosowski It looks like it does only return one type: https://github.com/easydigitaldownloads/easy-digital-downloads/commit/6ca09f239a485011e2bcc21f22cf731c04d7a0bc

The JS just needs to be updated to reflect that change.

**Comment by spencerfinnell** [comment]
> I'm not 100% clear on why my HTML structure exposed this issue, while a standard EDD core HTML structure doesn't seem to have any problems.

@SDavisMedia An install with taxes enabled will cause the full cart HTML to get refreshed, which will properly hide the row: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/f2e066353974ba053b0a2d5479d114d5fc854e46/templates/checkout_cart.php#L108

Without taxes the JS linked above is used and the rest of the cart remains untouched, exposing the issue.

**Comment by spencerfinnell** [comment]
PR #7595 

Before (notice empty space)
<img width="822" alt="Screen Shot 2020-02-21 at 8 34 56 AM" src="https://user-images.githubusercontent.com/491124/75038796-25378300-5485-11ea-9690-da9f9252d355.png">

After
<img width="817" alt="Screen Shot 2020-02-21 at 8 35 13 AM" src="https://user-images.githubusercontent.com/491124/75038800-29fc3700-5485-11ea-89de-043cd5b17f6f.png">

To test, ensure taxes are disabled to prevent full cart refreshing.
