### ISSUE TITLE
3.0 - Payment/Order bookmarks

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#7209]
### Expected behavior
When I migrate my database as a test, and I want to compare a pre3.0 payment to a post3.0 order, I copy the URL from my live site, change the URL to my test site, and paste it into the browser. 

I expect the order/payment to be the same one.

### Actual behavior
The order/payment now shows a different one at that same URL. 

### Steps to reproduce the behavior
1) Have a live site and a test site
2) Copy the live's site's database over to the test site
3) Switch the test site to 3.0 and do the migration
4) Copy the URL of a payment on your live site
5) Replace the URL with the URL of your test site and go.
6) Notice the data that shows is not for the same order/product as your live site.

### Information (if a specific version is affected):
EDD Version (or branch): 3.0

**Comment by pippinsplugins** [comment]
I think the easiest way to address this is to:

1. Change `payment_id` to `order_id` in the URL
2. When `payment_id` is present, use that ID to look up the proper ID from the legacy ID stored during migration
3. When `payment_id` is present, automatically redirect to the new URL

**Comment by mintplugins** [comment]
Related: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7210

**Comment by cklosowski** [comment]
This won't be an issue with #7210, as the Order IDs will remain the same, so all bookmarks will just bring up the proper order.
