### ISSUE TITLE
3.0 - Update Prices Include Tax wording

### ISSUE THREAD

**Issue by dgoldak** [easydigitaldownloads/easy-digital-downloads#7212]
### Explain your enhancement
Update Prices Include Tax wording to be more clear.
![Screen Shot 2019-04-16 at 3 45 55 PM](https://user-images.githubusercontent.com/30910807/56244192-eadda800-6061-11e9-94d1-578a6431ad30.png)

### Justification or use case
As silly as it may sound, I for some reason initially miss-read `No prices include tax` as `No, prices include tax` or more likely overlooked No and just read `prices include tax`. 

Regardless, the wording should be very clear so someone illiterate :) doesn't select the wrong setting.

**Comment by dgoldak** [comment]
Some possible suggestions:

Yes, prices include tax
No, prices do not include tax

Prices include tax
Prices do not include tax

Tax included in product price
Tax excluded from product price

**Comment by pippinsplugins** [comment]
I like this one:
>Prices include tax
>Prices do not include tax

**Comment by mintplugins** [comment]
I just got caught off guard with this myself for half a second. I almost thought that changing this setting would adjust the price of all my products for me in bulk.

I read it like this:
```
- Adjust all of my store's prices so they include the tax 
- Adjust all of my store's prices so they do not include the tax
```

When stepping back and looking at how taxes work, it's obvious that no setting could accomplish this. But in the moment of setting this option, I'm not sure it's currently clear enough to avoid the possibility of users thinking that. 

I'm not sure if the current change does enough to avoid that expectation. What if we added a description for each:

```
Prices include tax
- On checkout, calculate taxes so that they are included in the price entered.

Prices do not include tax
- On checkout, calculate taxes so that they are added to the price entered.
```

**Comment by mintplugins** [comment]
Would anyone be opposed to setting these back to what they were Pre3DD?

<img width="497" alt="Screen Shot 2019-05-03 at 1 39 26 PM" src="https://user-images.githubusercontent.com/1638128/57155249-f55da880-6da8-11e9-98f0-67ab98011521.png">

As far as I can remember/tell this wasn't something we got a lot of complaints about in support.

**Comment by cklosowski** [comment]
@mintplugins I think the @easydigitaldownloads/support team can probably attest to if there is confusion here. I know i've heard of 2 cases that it was confusing to customers.

@dgoldak is this something that came up from customers?

**Comment by dgoldak** [comment]
I'm not aware of any confusion about taxes so returning to Pre3DD should be fine. If fact, woo uses the exact same wording:
![Screen Shot 2019-05-03 at 1 26 53 PM](https://user-images.githubusercontent.com/30910807/57157731-2937ce80-6da7-11e9-8b22-42bd7cc2e539.png)

**Comment by cklosowski** [comment]
@dgoldak can you give a screenshot of what their tooltip shows as well please?

**Comment by cklosowski** [comment]
![Screen Shot 2019-05-03 at 20 56 39](https://user-images.githubusercontent.com/1390124/57173530-1abcd780-6de6-11e9-9e62-023db0212767.png)

**Comment by cklosowski** [comment]
So it appears that this is a 'stateful' thing for WC. Theirs says that updating this setting will _not_ update current products....ours does. When you update this, it really just affects the tax calculation, not the actual price of the product.

**Comment by cklosowski** [comment]
I'm 100% fine leaving this if it's the same wording that WC is using.
