### ISSUE TITLE
Avoid forEach with NodeList

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/easy-digital-downloads#7213]
### Expected behavior

Looping over a `NodeList` should work in IE 11.

### Actual behavior

It will fail.

### Steps to reproduce the behavior

1) View charts, email tags, or taxes in IE 11.

### Information (if a specific version is affected):

Any other relevant information:

https://developer.mozilla.org/en-US/docs/Web/API/NodeList

Since `underscore` is a dependency of all admin scripts and this is the only place `forEach` is used with a `NodeList` we can use https://underscorejs.org/#each

**Comment by spencerfinnell** [comment]
PR #7214 -- turns out just Email Tags used it with `NodeList`

**Comment by cklosowski** [comment]
@easydigitaldownloads/developers Anyone else here with an IE 11 capable machine able to replicate and confirm this?

I'll work on getting a VM setup that I can test in.

**Comment by cklosowski** [comment]
I got this working just fine.

Will fix up the merge conflict and merge.

**Comment by SDavisMedia** [comment]
Definitely replicated the behavior and error on IE11. Confirmed fixed on `issue/7213`. :+1:
