### ISSUE TITLE
3.0 - Addressing discount codes in user meta

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#7215]
Discount codes were previously stored in the `$payment->user_info` in an array like this:

```Array ( [first_name] => Test [last_name] => Test [discount] => test [id] => 1 [email] => me@gmail.com [address] => Array ( ) )```

On EDD3, that discount says "none" despite one having been used for the payment.

```Array ( [id] => 1 [first_name] => Test [last_name] => Test [discount] => none [email] => me@gmail.com )```

This results in anything using discounts in the user meta to think that no discount was used. 

From what I can tell this affects at least these places so far:
- [Purchase Confirmation](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/templates/shortcode-receipt.php#L80) (no discount shown despite one having been used)
- [PDF Invoice](https://github.com/easydigitaldownloads/edd-pdf-invoices/blob/0ce9494cca46ae51a60cacced4c154645f68def1/includes/templates/template-blue-stripe.php#L210)
- Anywhere else discounts are shown or used

What is the correct way forward here?
A) Break backwards compatibility, and go through every possible place where discounts might be referenced and update those? If so, what is the correct way to do that?
B) Filter the discount into the user meta (despite not storing it there) to maintain backwards compat, but also go through every possible place where discounts might be referenced and update those

**Comment by pippinsplugins** [comment]
I prefer option B.

**Comment by mintplugins** [comment]
Turns out this wasn't an intentional break, but just a race condition. The user meta requires the discounts data, but the discounts data was set up _after_ the user meta. The PR flips that and now the discount shows on purchase confirmation and in PDF invoices. 

While this addresses backwards compatibility, do we want to change the way this is coded in https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/templates/shortcode-receipt.php#L80 in order to provide an example of the new "right way"? 

If so, what is that new "right way".

**Comment by mintplugins** [comment]
P.S. to test the fix on `issue/7215`:

1. Purchase a product using a discount
2. On the purchase confirmation page, make sure you can see the discount listed
