### ISSUE TITLE
3.0 - Renewal Payments do not get the date_completed column populated upon migration. 

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#7225]
### Expected behavior
When I migrate from 2.9 to 3.0 and do the upgrade routines, for renewal payments through EDD Recurring, I expect the "date_completed" column to be populated like normal payments are. 

### Actual behavior
When I migrate from 2.9 to 3.0 and do the upgrade routines, for renewal payments through EDD Recurring, the "date_completed" column is all 0s. 

<img width="581" alt="Screen Shot 2019-04-26 at 6 49 22 PM" src="https://user-images.githubusercontent.com/1638128/56840162-0875f300-6854-11e9-8a1e-773e2d736d54.png">

### Steps to reproduce the behavior
1) Migrate a store that has renewal payments from EDD Recurring Payments. 

### Information (if a specific version is affected):
EDD Version (or branch): 3.0

**Comment by mintplugins** [comment]
Interesting. This isn't really a migration issue after looking further. Renewal payment don't seem to have added `_edd_completed_date` to the renewal payment meta, so the migrator has nothing to migrate.

**Comment by cklosowski** [comment]
This is likely due to the fact that renewal payments never hit the `completed` state which is where that is added. The main reason this exists is for things like pending payments and check payment gateways.

A renewal never hits a state like `pending` so it never needs to be different than it's insert date`. We should probably get something into `recurring` prior to 3.0 that adds this for all renewal payments, so we have a predictive system in place...

**Comment by mintplugins** [comment]
Yeah good call. I feel like it should be there for all so it is predictive, like you said. 

I am using that in All Access here:
https://github.com/easydigitaldownloads/edd-all-access/pull/292/files#diff-344f4e1343ef465d51ea1943f27d695bR1423

**Comment by mintplugins** [comment]
Another thought would be to set it to the payment date in the migrator if the status is edd_subscription. Thoughts?

**Comment by cklosowski** [comment]
@mintplugins I don't really want to have code for recurring in EDD's migrator. I think the best solution is to 'pre-fill' that prior to the migration.

**Comment by mintplugins** [comment]
Normally I would agree, I don't think any extension logic should be in core. 

However, since EDD 3.0 is a special/intense situation, @chriscct7 mentioned that it might make sense to handle all major extension migrations in core itself, since we wouldn't need to make sure they are active during migration, and we wouldn't need to do any "pre-fill checking" either (which we would have to do to make sure the pre-fill happens before the migration, even if recurring is temporarily-disabled). 

I think it's something worth having a discussion about anyway, regardless of the final decision.

**Comment by pippinsplugins** [comment]
Even if we don't do 100% of the extension migrations in core, I think it's best to at minimum add support for cases like this. Here's it's really just a case of adding support for the `edd_subscription` payment status.

**Comment by cklosowski** [comment]
I'll put together a PR for this.

**Comment by cklosowski** [comment]
@mintplugins ready for testing.

**Comment by mintplugins** [comment]
Migrating database on `issue/7225` to test now...

**Comment by mintplugins** [comment]
Looks good. I like defaulting to setting the date_completed for all statuses unless they are known as a non-complete. 👍 
<img width="594" alt="Screen Shot 2019-04-30 at 4 25 00 PM" src="https://user-images.githubusercontent.com/1638128/56991084-d8389800-6b64-11e9-8abb-708285a13338.png">
