### ISSUE TITLE
CSV Import not properly setting variable Price Assignments

### ISSUE THREAD

**Issue by dgoldak** [easydigitaldownloads/easy-digital-downloads#7226]
### Expected behavior
For variable pricing, CSV Import should properly set the Price Assignment upon import.

### Actual behavior
Price Assignment is properly set via the Download settings:
![Screen Shot 2019-04-29 at 10 34 20 AM](https://user-images.githubusercontent.com/30910807/56907703-73991280-6a6a-11e9-9025-1ff999f14d81.png)

BUT, when you purchase there is no download files available:
![Screen Shot 2019-04-29 at 10 33 30 AM](https://user-images.githubusercontent.com/30910807/56907621-43ea0a80-6a6a-11e9-8b4d-46b71890ab83.png)

If you click `Update` in the Download settings (without changing any settings), the Price Assignment begins to work.

Database Price Assignment after CSV import:
`a:1:{i:1;a:2:{s:4:"file";s:59:"http://edd.test/wp-content/uploads/2019/04/logo_example.png";s:4:"name";s:16:"logo_example.png";}}`

Database Price Assignment after Updating Download settings:
`a:1:{i:1;a:6:{s:5:"index";s:1:"1";s:13:"attachment_id";s:1:"0";s:14:"thumbnail_size";s:0:"";s:4:"name";s:16:"logo_example.png";s:4:"file";s:59:"http://edd.test/wp-content/uploads/2019/04/logo_example.png";s:9:"condition";s:3:"all";}}`

This behavior is the same whether a price assignment is specified or not in the CSV file column. For example:
- `http://edd.test/wp-content/uploads/2019/04/logo_example.png`
- `http://edd.test/wp-content/uploads/2019/04/logo_example.png;all`
- `http://edd.test/wp-content/uploads/2019/04/logo_example.png;1`

Also tested specifying multiple price assignments:
- `http://edd.test/wp-content/uploads/2019/04/logo_example.png;1 | http://edd.test/wp-content/uploads/2019/04/logo_example.png;2`

### Steps to reproduce the behavior
1) Import a product via CSV with variable price options.
CSV Example: https://www.dropbox.com/s/x8bn1fk1b6c0035/CSV%20Import%20Example.csv?dl=1
2) Test purchase of imported product
3) Purchase conformation should include proper download link. Not `No downloadable files found`

### Information (if a specific version is affected):
PHP Version: 7.0

EDD Version (or branch): `master`

WordPress Version: 5.1.1

Any other relevant information:
Reported by customer and replicated on my test site.
https://secure.helpscout.net/conversation/816449878/104110?folderId=1847242

**Comment by dgoldak** [comment]
Customer is requesting this be fixed as soon as possible, as it requires updating each download after an import. When you import a large number of products this adds additional manual labor.

I personally think this is import to fix along with EDD3 (or sooner) to encourage migrations.

**Comment by pippinsplugins** [comment]
It should be noted that we've never supported price assignments in the import, so this isn't really a bug but rather a missing feature. My previous `type-bug` label assignment was incorrect.

**Comment by pippinsplugins** [comment]
@dgoldak This is working properly for me.

Here's my CSV that works properly:
```
Name, Files, Price
Product 1, http://site.com/file.jpg, 10
Product 2, http://site.com/file1.jpg;1|http://site.com/file2.jpg;2, Price One:5 | Price Two:10
Product 3, bucket/file.jpg, 20
```

Can you test again and, if it fails, show me the CSV you're using?

**Comment by pippinsplugins** [comment]
Result of the above CSV:
<img width="1552" alt="Screen Shot 2019-10-28 at 4 07 28 PM" src="https://user-images.githubusercontent.com/1034109/67718189-3b34ab80-f99d-11e9-8608-3dfcc11f3fa7.png">

**Comment by dgoldak** [comment]
@pippinsplugins did you test the purchase to confirm the proper download links appear? They appear to work after the import but upon purchase there is no download available. 

The CSV i'm using is here: https://www.dropbox.com/s/x8bn1fk1b6c0035/CSV%20Import%20Example.csv?dl=1

**Comment by pippinsplugins** [comment]
@dgoldak Ok I have replicated it with your CSV.

Note: so far it seems the problem only happens when a price assignment is _not_ specified for files. If a price is specified, it works properly.

**Comment by pippinsplugins** [comment]
Tracked it down! PR submitted that's ready for testing.
