### ISSUE TITLE
3.0 - Fees not being applied to orders

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#7243]
### Expected behavior
When I have a fee set up through Discounts Pro or Simple Shipping, I expect that fee to be applied to the order upon completion.

### Actual behavior
While a row is added to the order adjustments table, and the amount seems to be correct, it is not reflected on the order itself. 

### Steps to reproduce the behavior
1) Set up a 20% discount with Discounts Pro.
2) Purchase a $5 product. With the discount it should come to $4
3) Upon purchase completion, note that you paid $5, despite the cart showing $4. 

Here's a screenshot of the order adjustment in the table:
<img width="863" alt="Screen Shot 2019-05-03 at 9 19 06 AM" src="https://user-images.githubusercontent.com/1638128/57139953-8cfcd000-6d84-11e9-826e-05d3cdf74ee8.png">

However, notice it was not applied to the order:
<img width="1270" alt="Screen Shot 2019-05-03 at 9 20 04 AM" src="https://user-images.githubusercontent.com/1638128/57140005-be759b80-6d84-11e9-846f-3c67bd363742.png">

Side question: Why does "adjustments" show on the order screen alongside "discounts"? What is the expectation for the "adjustments label? Does/Should it show discounts?

### Information (if a specific version is affected):
EDD Version (or branch): `release/3.0`

**Comment by mintplugins** [comment]
As far as I can tell, the only place the order total gets set is here:

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/payments/class-edd-payment.php#L991

But none of the order adjustments are applied to that.

**Comment by mintplugins** [comment]
Confirming that both positive and negative fees are ignored

<img width="712" alt="Screen Shot 2019-05-07 at 1 15 48 PM" src="https://user-images.githubusercontent.com/1638128/57319378-70390300-70ca-11e9-8237-0a8b3cc358d5.png">
<img width="719" alt="Screen Shot 2019-05-07 at 1 16 31 PM" src="https://user-images.githubusercontent.com/1638128/57319380-70390300-70ca-11e9-88ad-105d12d952ba.png">

Other adjustments such as `tax_rate` and `discount` do get applied:

<img width="1111" alt="Screen Shot 2019-05-07 at 1 20 20 PM" src="https://user-images.githubusercontent.com/1638128/57320196-539dca80-70cc-11e9-9793-9b991e0a53de.png">

**Comment by mintplugins** [comment]
As far as I can tell, adjustments are not used for anything at this time. 

The tax and discount that were applied above appear to be coming-from/stored-on the order itself, and not from the order_adjustments table:

<img width="425" alt="Screen Shot 2019-05-07 at 1 36 12 PM" src="https://user-images.githubusercontent.com/1638128/57320652-5baa3a00-70cd-11e9-9c6a-f909504671c5.png">

**Comment by cklosowski** [comment]
The good news here, is that the gateway got the correct amount:
![image](https://user-images.githubusercontent.com/1390124/59233334-dff44f00-8b9c-11e9-92a6-6afd6b8f8720.png)

This leads me to believe we just need to record the order with item specific fees in place, affecting the totals. I believe that's where our issue lies. Cart level fees seem to be working fine, but the item specific ones (Discounts Pro and Simple Shipping) aren't showing their fees in the front end or admin.

So we have two things
1) Find a way to display item level fees (front end and backend)
2) Find why the order entry into the DB (Gateway get's the right amount, so it's purely once we know we can create the order where the problem occurs) isn't calcuating using item level fees.

**Comment by mintplugins** [comment]
That's very interesting. That tells me that what gets sent to the gateway is not using the same logic as the order. I wonder if we should track down where the duplicate logic is and make sure the same logic is used for everything.

**Comment by cklosowski** [comment]
@mintplugins Basically the same logic is being used to build the cart and talk to the gateway, the problem comes with the payment creation process, when we move from session -> database.

I'll see if I can tear it down and figure it out.

**Comment by mintplugins** [comment]
Fix committed and PR opened. Testing is working for me.

# Steps to test the fix
1. Set up a 20% discount with Discounts Pro.
2. Purchase a $5 product. With the discount it should come to $4
3. Upon purchase completion, note that you now correctly show as having paid $4, and not $5.
