### ISSUE TITLE
CSV importing download products - always returns some error

### ISSUE THREAD

**Issue by var-che** [easydigitaldownloads/easy-digital-downloads#7246]
### Expected behavior
When I want to import a CSV to Import Download Products. I want them to be created based on the information that I have given. 
### Actual behavior
When I go and Import a CSV from Downloads > Tools > Import Download Products, I always get "The file you uploaded does not appear to be a CSV file." message. I am sure that I am providing a proper CSV format. No matter what, I always get that error.
### Steps to reproduce the behavior
1) Go to: Downloads
2) Tools
3) Import Download Products,
4) select some CSV
5) Import

### Information (if a specific version is affected):
PHP Version: 7.3.4

EDD Version (or branch): 2.9.12

WordPress Version: 5.1.1

Additional info: 
Platform:                 Windows 
Browser Name:             Chrome  
Browser Version:          73.0.3683.103

**Comment by cklosowski** [comment]
I just tested this for another issue Friday and didn't have this issue.
Could you provide a CSV file your using? How are you creating this CSV?

**Comment by var-che** [comment]
Sure. Here is a one product example of my CSV file. I am sure that I got all the fields right with right formating, but maybe not.

`"salim","Ebook","2019-05-23 18:44:51","Simple descr","exceprt","https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Artist_Ben_Stahl_Sarasota%2C_Florida.jpg/470px-Artist_Ben_Stahl_Sarasota%2C_Florida.jpg","product notes","10.00","SKU","small-slug011","published","tag1 | tag2","Title test","http://example.com/wp-content/uploads/edd/2016/05/WCCHI_2014_page_speed.pdf","34","0","24"`

**Comment by mintplugins** [comment]
@var-che Try adding a header row like this:


[mourad - with header row.csv.zip](https://github.com/easydigitaldownloads/easy-digital-downloads/files/3148854/mourad.-.with.header.row.csv.zip)

**Comment by var-che** [comment]
I have tested it, and still the same error.

![Screenshot_6](https://user-images.githubusercontent.com/480649/57239372-fa7e5a00-702b-11e9-96aa-031a60e0b86e.png)

**Comment by mintplugins** [comment]
@var-che Double check that you unzipped it first (Github required a zip file). 

I unzipped it and it didn't give the error.

**Comment by var-che** [comment]
So, I have made a screencast uploading the CSV file that you have zipped. Here is a short screencast of it.

https://drive.google.com/file/d/1wcbsd5m21aVQWK1A-cHsPQnY0udeugo0/view

**Comment by mintplugins** [comment]
@var-che It's working here. See screeshot:

<img width="1253" alt="Screen Shot 2019-05-06 at 2 53 09 PM" src="https://user-images.githubusercontent.com/1638128/57247797-c6487080-700e-11e9-8311-d594d047d1b8.png">
<img width="1267" alt="Screen Shot 2019-05-06 at 2 53 17 PM" src="https://user-images.githubusercontent.com/1638128/57247798-c6487080-700e-11e9-9c19-e89bdfb9856f.png">


Perhaps something is strange with the way you're unzipping the file. Rather than simply using mine, re-create yours from scratch but make sure you add a header row. 

Also, I noticed you use Google Drive so perhaps try using Google Sheets to create/export the csv file.

**Comment by var-che** [comment]
OK, so, when I opened and saw that unzipped CSV file that you have sent to me, there was an error. Missing one column name in the header row:
![Screenshot_1](https://user-images.githubusercontent.com/480649/57275161-eecb7b80-709d-11e9-8562-f5d8d5d76ebd.png)
But when I corrected it, I still had the same problem. So I visited google sheets and filled the tables
![Screenshot_2](https://user-images.githubusercontent.com/480649/57275210-191d3900-709e-11e9-81f9-2b03fde0ce87.png)
exported it as a CSV file, got this:
[Untitled spreadsheet - mourad - with header row.zip](https://github.com/easydigitaldownloads/easy-digital-downloads/files/3150996/Untitled.spreadsheet.-.mourad.-.with.header.row.zip)
uploaded it and again, the same problem.

**Comment by mintplugins** [comment]
I have confirmed the file works (see my screenshots above). Therefore, this looks like it's not a bug with the CSV importer, but just an issue with the formatting of the CSV file being used on your end. Please reach out to the support team over on https://easydigitaldownloads.com/support and they can dig into it further with you.
