### ISSUE TITLE
White screen when completing a purchase

### ISSUE THREAD

**Issue by Zebedeu** [easydigitaldownloads/easy-digital-downloads#7247]
This happens when no payment method is activated. It may not be a serious problem, but I believe that white screen is not a good way of presenting something that went wrong for a user

There should be a message saying that no method was selected or anything of the sort

### Steps to reproduce the behavior

1.Disable all payment methods
2. Choose a product
3. fill in the form (Personal Info)
4. click 2 or 3x consecutively on the button to finalize the purchase

PHP Version:
PHP 7.2
EDD Version (or branch):
EDD v 2.9.12
WordPress Version:
wp version  5.2
Any other relevant information:

**Comment by Zebedeu** [comment]
Sorry for my English. I am using the translator

**Comment by cklosowski** [comment]
Thanks for the report. I'll get something worked up.

**Comment by cklosowski** [comment]
We show a notice on the checkout if no gateways are defined, we should probably just hide the ability to complete the purchase if there isn't a gateway enabled.

**Comment by SDavisMedia** [comment]
@cklosowski Can't go through the purchase process with a 0.00 cart total on `issue/7247`. Free Downloads works, but the Complete Purchase button on checkout isn't present when Free Downloads is not in use, and the cart total is 0.00.

**Comment by SDavisMedia** [comment]
I think free payments should still work with no gateway enabled, if possible.

**Comment by cklosowski** [comment]
@SDavisMedia good find, fixing

**Comment by cklosowski** [comment]
@SDavisMedia actually....I'm not sure that'll work...you'd at least need the test gateway, otherwise it can't set a gateway on the purchase, but i'll see what I can do.

**Comment by SDavisMedia** [comment]
@cklosowski Is Free Downloads bypassing something to make it work? Not saying that's right, but the inconsistency would probably raise some eyebrows. This whole thing is rare anyway, I'm sure.

**Comment by cklosowski** [comment]
@SDavisMedia yeah it's hard setting the gateway when you use Free Downloads, since it creates the purchase record in the background.

**Comment by cklosowski** [comment]
@SDavisMedia it seemed to work, give it a try?

**Comment by SDavisMedia** [comment]
:+1: Appears to be working correctly for me as well. 0.00 carts work, Free Downloads works, carts with a total work, Recurring does not work with a free trial (good thing). I'm not seeing any weird behavior.

**Comment by cklosowski** [comment]
Thanks @SDavisMedia I'll get @pippinsplugins to review it since this affects checkout before we merge.
