### ISSUE TITLE
3.0 - Order details hook "edd_view_order_details_billing_after" moved to different context.

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#7251]
### Expected behavior
When I sell a product with Shipping, I expect to see the Shipping details metabox on the Order Details page. 

### Actual behavior
The Shipping information metabox is not shown in the place I expect. Rather it is sort of "hidden" under the "Customer Addresses" tab. 

### Steps to reproduce the behavior
1) Install EDD3 and Simple Shipping.
2) Create/Purchase a shipped product.
3) View the order details and locate the shipping details. 

### Considerations
While it is logical to put this hook in the new Customer Addresses tab based on its name (`edd_view_order_details_billing_after`), the hook itself has changed contexts:

- Pre3DD: The hook was outside a metabox and could be used to attach new metaboxes. 
- Post3DD: The hook is inside a metabox. 

For backwards compatibility I think the hook should remain outside a metabox despite its name. 

### Information (if a specific version is affected):
EDD Version (or branch): 3.0

**Comment by mintplugins** [comment]
Screenshot on `release/3.0`:
<img width="991" alt="Screen Shot 2019-05-08 at 2 28 36 PM" src="https://user-images.githubusercontent.com/1638128/57398727-b90dbc00-719d-11e9-91a0-2e42cdb69d6e.png">

Screenshot on `issue/7251`
<img width="997" alt="Screen Shot 2019-05-08 at 2 29 35 PM" src="https://user-images.githubusercontent.com/1638128/57398731-bb701600-719d-11e9-8ee8-3cdfdba312b0.png">

**Comment by cklosowski** [comment]
@mintplugins I would suggest that we add a new hook while where in here with a different name, and actually work to deprecate this hook. I want to get shipping details into that tabbed interface.

**Comment by mintplugins** [comment]
Added that to Simple Shipping here:
https://github.com/easydigitaldownloads/edd-simple-shipping/issues/90
