### ISSUE TITLE
You do not have permission to download this file after upgrading to 2.9.14

### ISSUE THREAD

**Issue by Ratcreamsoup** [easydigitaldownloads/easy-digital-downloads#7258]
We're getting hit by this same problem as described in issue #7249 after upgrading to 2.9.14. In our case the issue lies one step deeper, as we have symlinked wp-content/uploads to a path outside of the wordpress documentroot directory. In that case, wp_normalize_path doesn't resolve the issue that PHP's realpath( $requested_file ) uses the canonical path.

As a workaround we have moved the uploads directory to the canonical path, thus getting rid of the symlink, but this messes with our file storage and backup procedures.

Even though this may not be an issue for 99.9% of EDD installations, I have the feeling that it is a valid use case to move images and other binaries to a different file system or different path anyway than the code and use a symlink to keep the original directory layout intact.

So I'd like to re-open this bug report. Steps to reproduce are the same as in the original issue report.

Information:
PHP Version: `7.0.33-6+0~20190412071436.12+stretch~1.gbp26747c`
EDD Version (or branch): 2.9.14
WordPress Version: 5.2
OS : Debian 9.9 (Stretch)

_Originally posted by @Ratcreamsoup in https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7249#issuecomment-490900563_

**Comment by cklosowski** [comment]
@Ratcreamsoup 

First off, this should only affect you if you're putting in your files as absolute paths. If you are using the normal 'upload file' process, and not typing in the absolute path of the file it shouldn't cause a problem.

If for some reason that's still causing a problem, you can always use this filter:
```
add_filter( 'edd_local_file_location_is_allowed', '__return_true` );
```

This will bypass this entire process, but should be done so with knowledge that is bypasses a protection in place to prevent store owners from accidentally putting the absolute path to important system files in the input for what file to deliver to customers.

**Comment by Ratcreamsoup** [comment]
After adding the filter (along with a path check for our symlinked directory) we're now back to the original symlinked setup and I can confirm that it is indeed working as expected, so thank you very much for your quick response.
