### ISSUE TITLE
Add filter to conditionally show nginx warning

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#7259]
## Enhancement Request
The nginx warning about file protections shows for every site running nginx. However, some webhosts (like Kinsta) already have the required/specific protections in place for this, and this warning is not needed. A filter to conditionally remove that admin_notice can be used to prevent that. 

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/b3b09b718d04ded5611b8b34194cbb77190a2c47/includes/admin/class-edd-notices.php#L59

**Comment by cklosowski** [comment]
We have a host detection method that maybe we could use to do this. If you notice sometimes we have the system info detect the host. If Kinsta has a specific type of header or something on the server level we could detect, they could be added to that.

**Comment by mintplugins** [comment]
Do you mean here?
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/b3b09b718d04ded5611b8b34194cbb77190a2c47/includes/misc-functions.php#L208

**Comment by mintplugins** [comment]
To test this, create a new site on an nginx server, and make sure the notice shows properly. 

I have confirmed it is for me.

<img width="795" alt="Screen Shot 2019-05-24 at 3 33 02 PM" src="https://user-images.githubusercontent.com/1638128/58352373-55d88680-7e39-11e9-8e59-b7399518aab4.png">

Related ticket:
https://secure.helpscout.net/conversation/846146047/119766?folderId=749231
