### ISSUE TITLE
3.0 - Remove option to bulk refund orders

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#7262]
## Enhancement Request
Refunding orders in bulk seems too easy, heavy-handed, and prone to accidents. I was just testing the "trash" order issue (#7245) and accidentally clicked on "refund" instead of "delete", and suddenly all my orders were refunded. 

I propose we remove the option of bulk-refunding orders:
<img width="146" alt="Screen Shot 2019-05-15 at 5 37 08 PM" src="https://user-images.githubusercontent.com/1638128/57811395-1d99bf80-7738-11e9-9ba7-01c209ce7d7c.png">

**Comment by cklosowski** [comment]
I think the main reason for this is due to the new Refund API and flow that's in #7233, which provides ways to properly apply refunds and in the future credits, etc.

**Comment by ashleyfae** [comment]
@LisaCee There are two things to update:

1. The option in the dropdown. That's here: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/payments/class-payments-table.php#L652
2. The logic for actually changing the status on submit. That's here: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/payments/actions.php#L634-L636

**Comment by LisaCee** [comment]
PR #8277
