### ISSUE TITLE
3.0 - Discount code required products do not save initially, but do on re-save.

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#7263]
### Expected behavior
When I create a discount code with required products, I expect those required products to be saved.

### Actual behavior
The required products are not initially saved, but are if I edit re-add, and re-save.

### Steps to reproduce the behavior
1) Create a discount code and attach required products.
2) Save it. 
3) Notice they are not saved after refreshing.

### Information (if a specific version is affected):
EDD Version (or branch): 3.0

**Comment by cklosowski** [comment]
This was caused by the `Add` looking for product requirements in the `product_reqs` array key, which is what the edit discount field is named.

In fact the input on the page was only `products`. I've changed the input name on the Add Discount page to follow suit with `product_reqs` instead of just `products` to make it clear these are requirements and make it standard between editing and adding a discount.

**Comment by mintplugins** [comment]
I am getting `There was a problem adding that discount code, please try again.` when I try to create a new discount code on this branch. I also get this error on `release/3.0`, but not on #7264 

<img width="459" alt="Screen Shot 2019-05-22 at 2 44 43 PM" src="https://user-images.githubusercontent.com/1638128/58200189-2f331800-7ca0-11e9-8787-a1ead8ca6980.png">

**Comment by mintplugins** [comment]
oh...haha that's because I don't have the column from when I was working on #7264

**Comment by mintplugins** [comment]
Confirmed fixed on #7263

**Comment by mintplugins** [comment]
Oh hang on. The products required are being automatically added to the excluded products.

**Comment by cklosowski** [comment]
@mintplugins I'm not experiencing this on a pure branch from 3.0

![image](https://user-images.githubusercontent.com/1390124/58201905-e0837f00-7c9b-11e9-97b4-b37d30b6aaf3.png)

**Comment by cklosowski** [comment]
Just tested adding another one to make sure I wasn't looking at one done during developmnet:
![image](https://user-images.githubusercontent.com/1390124/58201981-0d379680-7c9c-11e9-92a1-2d2a18458943.png)

**Comment by mintplugins** [comment]
Hmm yeah it's not happening to be anymore. Seems okay now.

**Comment by JJJ** [comment]
I'm seeing a database error, from the `product_condition` column not existing.

The `__201906030001()` method needs a `column_exists()` check before it can be removed.

New PR incoming...
