### ISSUE TITLE
Modify file download url in [edd_receipt]

### ISSUE THREAD

**Issue by andrastudio** [easydigitaldownloads/easy-digital-downloads#7269]
Hi,

Is there a way to modify the download links produced by [edd_receipt] shortcode?

I'm offering freebies to my site visitors and I wanted to earn extra revenue by redirecting the downloaders to adf.ly first and adf.ly will redirect them back to the original download inks.

The only hooks I can find are only to add text/elements before or after the download links.

**Comment by cklosowski** [comment]
Github is for development tracking only. Please contact our support team here:
https://easydigitaldownloads.com/support
