### ISSUE TITLE
Occasional PHP Unit test failure - timestamps off by 1 second

### ISSUE THREAD

**Issue by JJJ** [easydigitaldownloads/easy-digital-downloads#7270]
### Expected behavior
When I run PHP Unit, I expect tests that compare timestamps to not fail simply because they happen to be off 1 second, which is presumably from the test executing.

### Actual behavior
When I do run PHP Unit, occasionally, randomly, a test will fail from comparing timestamps that are only different because of the page/test execution time.

### Steps to reproduce the behavior
1) Run PHP Unit a few dozen times
2) Wait for a random test failure
3) Notice it's a timestamp comparison problem

### Information (if a specific version is affected):
PHP Version: Any
EDD Version (or branch): Any
WordPress Version: Any

**Comment by JJJ** [comment]
The reason this happens randomly, is because EDD frequently uses the WordPress function `current_time()` when comparing. Internally, it uses the PHP function `time()` which is always _now_ down to the second.

The 2 values _might sometimes_ be different depending on the microsecond when tests begin, and the microsecond when the test ends.

Using `current_time()` could have strange repercussions in real world scenarios. For example, if an EDD customer makes a purchase, and that needs to make a remote request to a third party API, and that request takes 2 seconds to respond, which timestamp should we use: the customer request, or after the response was received?

If EDD stores a draft order, then flips it to complete, which timestamp is more "accurate" for our needs? In addition, for related records in EDD3 (like the items in an order) we probably want to make sure every item uses the exact same timestamp as the primary order, because it would only be more confusing if 2 items were saved at 06:30:29 and 2 other items were saved at 06:30:30.

----

My recommendation is that EDD introduce a helper function (`edd_get_request_time()` or something) for accessing some shared timestamp value. It could be locally static to EDD, or use the `$timestart` WordPress global - I'm not sure it ultimately matters too much what it is, so long as they're using the same value.

Here's an example function that uses the global:

```
/**
 * Return the current time, according to the page load.
 *
 * This is a more precise & predictable version of the current_time() function
 * included with WordPress.
 *
 * @since 3.0.0
 *
 * @global float $timestart
 * @return float
 */
function edd_get_request_time( $type = 'timestamp', $gmt = 0 ) {
	global $timestart;

	// Should never be empty, but just in case...
	if ( empty( $timestart ) ) {
		$timestart = microtime( true );
	}

	// Get the offset for
	$offset = get_option( 'gmt_offset' ) * HOUR_IN_SECONDS;

	switch ( $type ) {
		case 'mysql':
			return ! empty( $gmt )
				? gmdate( 'Y-m-d H:i:s' )
				: gmdate( 'Y-m-d H:i:s', ( $timestart + $offset ) );
		case 'timestamp':
			return ! empty( $gmt )
				? $timestart
				: $timestart + $offset;
		default:
			return ! empty( $gmt )
				? gmdate( $type )
				: gmdate( $type, $timestart + $offset );
	}
}
```

This introduces a bit of complexity, because there are legitimate use cases for wanting the exact time _now_ and not wanting to use some shared value, and there will need to be clearly defined reasons to avoid unintentionally making things worse.

----

To prevent similar problems with AJAX requests, EDD would want to explore passing the timestamp around in a localized variable, probably with a separate hash so some kind of checksum can be verified to prevent tampering:

```
array(
    'edd_timestamp' => edd_get_request_time( 'timestamp' ),
    'edd_timestamp_checksum' => md5( edd_get_request_time( 'timestamp' ) . get_option( 'nonce_salt' ) )
)
```
...or something like it, and then compare the checksum inside the AJAX request. Somewhat weak, but probably fine enough for our use cases.

Implementing this isn't _super_ easy, as it will require auditing `current_time()` usages, deciding if each needs replacing, and confirming nothing gets broken unintentionally.

**Comment by ashleyfae** [comment]
Is this the test you're referring to?

![Screenshot from 2020-03-19 09-03-41](https://user-images.githubusercontent.com/6324272/77049874-c18b7180-69c0-11ea-8d23-8baea1342fd1.png)

**Comment by cklosowski** [comment]
That’s the one. When it fails we can just restart that single job on Travis and it’ll pass like 99% of the time.

**Comment by JJJ** [comment]
I reread my original commentary, and it all still sounds accurate, so let me know if anything needs clarification. Otherwise, I might submit a PR for this because I've already implemented it for Sugar Calendar (See: [`sugar_calendar_get_request_time()`](https://github.com/sugarcalendar/lite/blob/4f995b0c52b2c1c9bf29cb7a2bce73e1b6883b91/sugar-event-calendar/includes/common/time.php#L36))

**Comment by cklosowski** [comment]
@JJJ That is an interesting approach, and for sure bypasses any runtime differences.

**Comment by ashleyfae** [comment]
Closing this as I think it's been fixed here: https://github.com/easydigitaldownloads/easy-digital-downloads/commit/77fb338091567ba86e33b12d9a7872ea3275796e I also haven't seen this error in a while. We can reopen it if I missed something or if it happens again.
