### ISSUE TITLE
3.0 - The "status" column does not appear to be needed for the customer_email_addresses table

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#7272]
The customer_email_addresses table has 2 columns which relate to the "Status" of an email address:

| Table Column  | Description |
| ------------- | ------------- |
| type  | Stores whether this email address is "primary" or "secondary". |
| status | Currently stores the word "active" for all email addresses. |

I would argue that adding the option to have an "inactive" email address does not serve a real-world purpose, or at least one not worth supporting because of the number of edge-cases it could cause. 

For example, if an email address is `inactive`, but a new customer attempts to purchase using that email address, what should happen? 

1. Should the purchase be prevented? 
2. Should the purchase be allowed?
3. If the purchase is allowed and a new customer is created, what happens if the original customer attempts to reactivate the email address. Is it now attached to 2 different customers?

These questions lead me to believe that "active" and "inactive" email addresses are not something we actually need, and therefore I am thinking we should just remove the "status" column altogether. 

If there's a future purpose for the status column that I've overlooked, let me know.

**Comment by cklosowski** [comment]
@mintplugins  if we can have a status column, we can more easily support integrations. A couple things it would allow:
1) Fraud Monitor could use it instead of a massive list of blocked emails
2) Services like mailchimp/Postmark/etc could update an email address as 'invalid' or 'bounced' and display notices.

While EDD core isn't currently using it, it could be and could allow further functionality to be built around the 'working state' of an email address associated with a customer.

**Comment by mintplugins** [comment]
I both agree and disagree. I think the examples provided are best served by meta, as opposed to a single status column. To use the provided examples, what happens if Fraud Monitor stores a value in here, like `blocked`, but then Postmark stores `bounced` in the same column?

**Comment by cklosowski** [comment]
That is a fair argument @mintplugins. I'm still suggesting we leave the column, even if we're not using it at the moment. As with a lot of the 3.0 tables, we've worked towards making data immutable. I'd much rather leave a column for a status currently that we'll be likely working into the process later. We built out taxes with a status column, and later used it for the immutable tax rates.

By having this column it lends us some freedoms later in the development process when it comes time to allow further integrations with how we handle the concept of this table.

I propose we leave it for now and until we finish the release and get a little more integration work done we can assess it.

**Comment by mintplugins** [comment]
Just for my own clarification and understanding, is adding columns to the table later more difficult than adding them now? My current understanding is that columns can be added later without a lot of work. If true, I would lean towards adding that column if/when we actually need it for a particular purpose.

**Comment by cklosowski** [comment]
It's far more risky to add them later. An alter table by adding a column after the table has hundreds, or thousands of rows is a locking action.

**Comment by mintplugins** [comment]
I see, makes sense. 

Regarding this column, my mind is still the same. I can't imagine any scenario where this column would/should be used, now or in the future. I think it's too generic. But that's just my perspective. Ultimately it is your call.

At the very least though, I think we should stop storing the word "active" and leave it blank. That would allow it to be used for a purpose other than "Active"/Inactive" in the future.

**Comment by cklosowski** [comment]
Closing for now, we can come back to this if we can need to further flesh this out.
