### ISSUE TITLE
Download URL issues with wp.com-hosted sites since 2.9.13

### ISSUE THREAD

**Issue by nutsandbolts** [easydigitaldownloads/easy-digital-downloads#7279]
Opening this issue per Pippin to describe what we're seeing in support since 2.9.13 with sites on wp.com business plans.

Once customers update, all download URLs lead to a screen like this:

![Screen Shot 2019-05-31 at 12 06 45 PM](https://user-images.githubusercontent.com/5407366/58722246-96398680-839c-11e9-87c5-e5a5bc24c6ec.png)

Changing the download method to Redirect works, but _only_ if the download files are a zip. If they are any kind of media (image, audio, video, PDF), the files open in the browser with no obvious way to download or save. 

From an email thread between wp.com support and one of our customers:

```As I alluded to in my previous email and in emails previous to this, Our servers are NGINX and we don't allow the environment changes that EDD requires to work on NGINX. Easy Digital Downloads is primarily meant for Apache environments. Thus, the best way forward is to just store everything via Dropbox. Dropbox is a dedicated file host, and they will have better performance and stability and EDD has a Dropbox integration.```

However, Dropbox handles images and audio files and the like in the same way, by opening them in the browser. This could be handled by zipping all the download files, but (1) that's not feasible for sites with thousands of products and (2) a lot of end users have no idea what to do with a zip file once they download it.

Adding the filter `add_filter( 'edd_local_file_location_is_allowed', '__return_true' )` (via plugin, because wp.com also doesn't allow FTP access) does resolve this issue. This may not be a good long-term strategy, especially for stores that use FES.

**Comment by nutsandbolts** [comment]
Also @mintplugins has dealt with a number of these tickets as well, so he probably far more details than I do.

**Comment by mintplugins** [comment]
I have seen a few tickets about this, but really got nowhere with wp.com support. Ultimately I had to tell someone to move to a better host, and I think they did. 

They must be blocking something at the nginx level because there's no reason a 403 should be showing there otherwise, at least that I am aware of.

**Comment by jfarthing84** [comment]
My guess is that they are using a symlinked downloads directory. So am I. 2.9.13 breaks this. Because of changes in 3237efb.

**Comment by cklosowski** [comment]
For now, please use the filter to get past this in this situation:
```
add_filter( 'edd_local_file_location_is_allowed', '__return_true' );
```

This was a fix for a security issue that allowed a store owner to input a system level file that could then be downloaded by customers. @jfarthing84 are you using absolute paths or URLs for your file uploads?

**Comment by jfarthing84** [comment]
@cklosowski I am using the media library with locally uploaded files.

**Comment by cklosowski** [comment]
@jfarthing84 ok, that shouldn't ever trigger this unless there is something happening in the way the URL is being converted to the path. We'll dig in further to see if we can figure out why this is happening on the hosting platform. For now, that filter above will allow files to be downloaded, just know it bypasses that check for where the file is hosted.

**Comment by cklosowski** [comment]
We've had a few really interesting configurations come in, symlinks, subhosted domains that report different in code and on the front end. I have PR here that will by pass the checks on paths if we are getting the file by attachment ID (and we found an actual file to deliver with that Attachment ID).

We'll need to get some hosting accounts setup to try and replicate this and test.

**Comment by cklosowski** [comment]
Ok, so locally I was able to replicate this with the following:
1) Set your download method to 'Forced'
2) `cd` into `wp-content`
3) `mv uploads ../test-dir`
4) `ln -s ../test-dir uploads`

Then if you try and download a file, you should get the error.

**Comment by cklosowski** [comment]
@mintplugins when you get some time, can you try this out? If you need help, let me know.

**Comment by dgoldak** [comment]
@cklosowski customer gave us permission to test the fix on his site: https://secure.helpscout.net/conversation/965875771/132696?folderId=1847242

**Comment by cklosowski** [comment]
@dgoldak I've added this to the customer's site and tested it and it seems to work. Please have them confirm and reply here.

**Comment by dgoldak** [comment]
Gave a customer who's site is hosted on Flywheel this update when they reported  `Sorry, this file could not be downloaded`. Updating addressed the error. 

@cklosowski the update you installed on the customer site has been working as well.

**Comment by mintplugins** [comment]
The code looks good to me, and it's working in my tests:

<img width="958" alt="Screen Shot 2019-10-16 at 12 06 02 PM" src="https://user-images.githubusercontent.com/1638128/66937655-d462da00-f00d-11e9-9d50-273d46a81136.png">

👍
