### ISSUE TITLE
Wrong earning stats when used with Discounts Pro

### ISSUE THREAD

**Issue by hor-net** [easydigitaldownloads/easy-digital-downloads#7281]
### Expected behavior
When a new purchase is made that contains a negative fee added by Discounts Pro I expect the earnings stats for the download to be updated correctly by the discounted amount

### Actual behavior
Stats are lower than what they should be because negative fees are applied twice, first by EDD_Cart::get_contents_details() then by every stat method removing the fees for each item from $item['price'] (already reduced by the previous method) instead of $item['item_price] 

### Steps to reproduce the behavior
1) Create a download of 10$ price
2) Create a discount ind Discounts Pro valid only for that download of a fixed value of 8$
3) Complete a purchase of that download
4) Look at the earnings for that downlaod and sales stat, it will still show 0 because the total would be less than 0

### Information (if a specific version is affected):
PHP Version: N/A

EDD Version (or branch): 2.9.15

WordPress Version: 5.2.1

Any other relevant information:
Fees specific to an item are first removed for each item in the cart on line 242 of class-edd-cart.php

```
foreach ( $fees as $fee ) {
    $fee_amount = (float) $fee['amount'];
    $subtotal  += $fee_amount;

    if( $fee_amount > 0 ) {
        continue;
    }
    $subtotal_for_tax += $fee_amount;
}
```

Then $subtotal is used to compute $total that in line 276 is then used as the "price" element for the item details in the cart.

Then for example if you look into edd_complete_purchase() on line 69 of actions.php the $increase_earnings variable is given the $download['price'] value (this value already contains the $total from before, so ($item_price * $quantity) - $discount + $fees + $tax) and on line 71 negative fees are removed again:

```
$increase_earnings = $download['price'];
if ( ! empty( $download['fees'] ) ) {
    foreach ( $download['fees'] as $fee ) {
        if ( $fee['amount'] > 0 ) {
            continue;
        }
        $increase_earnings += $fee['amount'];
    }
}
```

**Comment by pippinsplugins** [comment]
@hor-net I've replicated the behavior you're seeing.

**Comment by pippinsplugins** [comment]
PR that should fix this has been submitted to #7507

**Comment by pippinsplugins** [comment]
The PR attached #7507 fixes part of this but we'll still need to adjust the earnings meta key adjustment to account for fees properly.

**Comment by pippinsplugins** [comment]
The PR on #7507 now addresses this bug fully.
