### ISSUE TITLE
3.0 - Payment Gateway errors are not being logged. 

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#7283]
### Expected behavior
When I attempt to log a payment gateway error using `edd_record_gateway_error`, I expect that error to be logged in the edd_logs table. 

### Actual behavior
No log is added.

### Steps to reproduce the behavior
1) Add this code:
```
function my_gateway_log_tester() {
	edd_record_gateway_error( 'Test gateway error title', 'Test gateway error content' );
}
add_action( 'init', 'my_gateway_log_tester' );
```
2) Notice that no log is added to the edd_logs table. 

### Information (if a specific version is affected):
EDD Version (or branch): 3.0

**Comment by mintplugins** [comment]
This fixes the issue in my tests using the steps above.

**Comment by mintplugins** [comment]
Here's the tests I am running. These could be turned into unit tests:
```
edd_record_gateway_error( 'Test gateway error', 'Test gateway error content' );

	edd_add_log( array(
			'object_type' => null,
			'object_id' => 0,
			'title' => 'Test log with null object type and no ID'
		)
	);
	edd_add_log( array(
			'object_type' => null,
			'object_id' => 1,
			'title' => 'Test log with null object type but an ID (should fail)'
		)
	);
	edd_add_log( array(
			'object_type' => 0,
			'object_id' => 0,
			'title' => 'Test log with empty object type and no ID (should fail)'
		)
	);
	edd_add_log( array(
			'object_type' => 0,
			'object_id' => 1,
			'title' => 'Test log with empty object type and an ID (should fail)'
		)
	);
```

**Comment by mintplugins** [comment]
I have my unit tests working for EDD core now. Working up these tests now...

**Comment by mintplugins** [comment]
Unit tests have now been added for these changes. 

Note that a lot of tests in EDD 3 are failing right now. In order to test these you will have to call them individually using this method:

```
phpunit --filter test_edd_record_gateway_error Tests_Logging /app/public/wp-content/plugins/easy-digital-downloads/tests/tests-logging.php

phpunit --filter test_edd_add_log_with_null_type_and_no_id Tests_Logging /app/public/wp-content/plugins/easy-digital-downloads/tests/tests-logging.php

phpunit --filter test_edd_add_log_with_null_type_and_an_id Tests_Logging /app/public/wp-content/plugins/easy-digital-downloads/tests/tests-logging.php

phpunit --filter test_edd_add_log_with_empty_type_and_no_id Tests_Logging /app/public/wp-content/plugins/easy-digital-downloads/tests/tests-logging.php


phpunit --filter test_edd_add_log_with_empty_type_and_an_id Tests_Logging /app/public/wp-content/plugins/easy-digital-downloads/tests/tests-logging.php
```

**Comment by cklosowski** [comment]
@mintplugins if you remerge `release/3.0` I fixed a lot of the failing unit tests.

**Comment by mintplugins** [comment]
I pulled in `release/3.0` and this was my phpunit result:

`ERRORS!
Tests: 1734, Assertions: 3065, Errors: 43, Failures: 53, Risky: 7.`

Is that accurate/expected at this time?

**Comment by cklosowski** [comment]
@mintplugins Nope, something is up. When I run things on `release/3.0` they are much cleaner.

**Comment by mintplugins** [comment]
@cklosowski What are you getting on issue/7283?

**Comment by cklosowski** [comment]
On the branch alone, lots of errors...but it doesn't appear that you merged `release/3.0` into the current branch. I just did this and all is cleaner:
```
git checkout release/3.0
git pull origin release/3.0
git checkout issue/7283
git merge release/3.0
```
`Tests: 1734, Assertions: 3124, Failures: 1.`

**Comment by cklosowski** [comment]
I'll push up the merge of `release/3.0` so you can pull down. The errors were because you didnt' have the updated tests from changing addresses from `frist/last name` to just `name`

**Comment by mintplugins** [comment]
That's better now

`FAILURES!
Tests: 1734, Assertions: 3124, Failures: 1.`
