### ISSUE TITLE
_edd_payment_meta backwards compatibility.

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#7289]
As we've moved to using order items, and order item meta, we no longer need to populate the `_edd_payment_meta` array, however we should still back-port data to it, for a period of backwards compatibility, including the order item options array we moved to meta in #7197 .

**Comment by nosegraze** [comment]
In https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7545 the order item options array is now included in `payment_meta` order meta. That's available when running `edd_get_payment_meta( 34, '_edd_payment_meta', true )`. If I'm understanding the discussion right, I believe that's the functionality that's wanting to keep for ~1 major version.

**Comment by cklosowski** [comment]
This just needs testing with the current `release/3.0` branch to see if it works as expected.

**Comment by ashleyfae** [comment]
I did some testing and there was one line that was causing `payment_meta` (old `_edd_payment_meta` key) to still be saved to order meta. This PR stops that happening: #7760 

After this change, the meta is no longer saved while making a new order, but all our code does still dynamically fetch, build, and return it as expected.

Note: there are still a couple lines adding it in the migrator that I haven't looked at.
