### ISSUE TITLE
edd_get_payment_status() always return false if status label is translated.

### ISSUE THREAD

**Issue by cloudinstone** [easydigitaldownloads/easy-digital-downloads#7292]
the code below in function edd_get_payment_status() is search value instead of key, which will cause always return false if status label is translated (Not English).

`return array_search( strtolower( $post_status ), array_map( 'strtolower', $statuses ) );`

**Comment by cklosowski** [comment]
I've confirmed this is the case.

The main issue here is we're attempting to get the status on something that is translatable...we'll need to find a way around that for sure.

**Comment by cklosowski** [comment]
This is ready for testing, but needs some extensive testing with additional extensions that add a status like Stripe and Recurring.

**Comment by mintplugins** [comment]
Confirmed fixed.
