### ISSUE TITLE
3.0 - Add schema description README.md file

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#7293]
## Enhancement Request
I am working on descriptions for all of the columns in all of the custom tables being added in 3.0. I will commit that here.

**Comment by mintplugins** [comment]
The best way to review this is probably to view it formatted here:
https://github.com/easydigitaldownloads/easy-digital-downloads/tree/issue/7293/includes/database

**Comment by cklosowski** [comment]
@mintplugins I'm marking this as blocked by #7285, as that will require a change to the DB structure, so we'll have to be sure to update this PR to account for it.
