### ISSUE TITLE
3.0 - Clicking "Add Note" for an order does not work

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#7294]
### Expected behavior
When I try to add a note to an order, I expect the note to be saved and added.

### Actual behavior
The "Add Note" button appears to be doing nothing. 

### Steps to reproduce the behavior
1) attempt to add a note to an order
2) notice the "Add note" button has no affect.

<img width="1440" alt="Screen Shot 2019-06-11 at 4 43 07 PM" src="https://user-images.githubusercontent.com/1638128/59305422-3d090700-8c68-11e9-8f39-28f12c986b7c.png">

### Information (if a specific version is affected):
EDD Version (or branch): 3.0

**Comment by spencerfinnell** [comment]
`edd-admin-notes` should be set as a dependency of `edd-admin-orders` (and maybe `edd-admin-payments`)

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/assets/js/admin/notes/index.js

**Comment by cklosowski** [comment]
Ah missed that whole file. It's payments it needs to be a dependency of. We need to rename those. Payments is for edit and orders is for add...that's confusing.

**Comment by mintplugins** [comment]
FWIW this is working for me now

**Comment by cklosowski** [comment]
@mintplugins yeah I fixed it the _wrong_ way though. i'll get it fixed up the _3.0 way_

**Comment by cklosowski** [comment]
Ok just fixed and pushed up the fix the right way, far less complex, and nicer for sure.

**Comment by mintplugins** [comment]
I see now. I am confirming that that fixed it as well.
