### ISSUE TITLE
3.0: "More" button on Orders list-table page not working

### ISSUE THREAD

**Issue by JJJ** [easydigitaldownloads/easy-digital-downloads#7297]
### Expected behavior
When I click "More" I expect the drop-down to appear.

### Actual behavior
When I click "More" nothing happens.

### Steps to reproduce the behavior
1) Visit Admin > Downloads > Orders
2) Click "More"
3) See nothing...

### Information (if a specific version is affected):
PHP Version: Any
EDD Version (or branch): 3.0
WordPress Version: Any

**Comment by JJJ** [comment]
I think this is related to some clean-up that happened as part of #7052.

**Comment by JJJ** [comment]
After the proposed PR, the "More" button & drop-down are restored.

<img width="610" alt="Screen Shot 2019-06-11 at 10 40 32 PM" src="https://user-images.githubusercontent.com/88951/59321996-eddbca00-8c99-11e9-8cc0-fd7d5ff0a032.png">

**Comment by spencerfinnell** [comment]
Noticed this too. 

> I’m unsure about the duplication between add & edit. If it is indeed a problem, we probably need a new & separate script registered for the Orders & Refunds list-table pages. That will require re-splitting the Orders JavaScript, because right now that’s all that’s in orders/index.js.

@cklosowski mentioned possibly renaming the pretty confusing `edd-admin-payments` and `edd-admin-orders` script handles to something more appropriate based on where they need to be loaded. There are new in 3.0 so no compatibility issues changing them now. 

Happy to help shuffle things around if needed.

**Comment by cklosowski** [comment]
I think this should do the trick @mintplugins we do have a small bug i'm going to log for `Post Beta` which is if you want to filter non-free items you have to use `0.00` instead of simply `0`, as it likely equates to `empty` and therefore like the field wasn't filled out.

**Comment by mintplugins** [comment]
Replicated on `release/3.0`. The more button is now working on `issue/7297`. 

However, the states do not appear to be refreshing if you change the country. 

<img width="445" alt="Screen Shot 2019-08-20 at 11 05 38 AM" src="https://user-images.githubusercontent.com/1638128/63359405-b002be00-c33a-11e9-8d10-c9e7f32768e4.png">

**Comment by cklosowski** [comment]
Ok we can fix that in a later issue.

**Comment by cklosowski** [comment]
@mintplugins as far as the scope of the filters being exposed, would you consider this resolved? If so we can open a new issue for the updating of the States/regions by country.

**Comment by JJJ** [comment]
@cklosowski _I_ think it's fine to fix that in a separate issue, as it's likely related to the server-side AJAX and the selectors having changed over time.

**Comment by mintplugins** [comment]
Opened a separate issue for that here: #7382. Note that it requires this issue in order for the "more" button to operate.

**Comment by cklosowski** [comment]
@mintplugins mind going a head and either requesting any changes or approving the PR attached to this one?
