### ISSUE TITLE
Add note to discount settings that date/time is UTC

### ISSUE THREAD

**Issue by dgoldak** [easydigitaldownloads/easy-digital-downloads#7299]
### Explain your enhancement 
It's assumed that a discount code's start or end time is the timezone set in WordPress settings, but it's actually UTC. We need to note in the settings that the time that appears is UTC.

![Screen Shot 2019-06-12 at 2 15 46 PM](https://user-images.githubusercontent.com/30910807/59379938-941ce380-8d1d-11e9-9cd6-c08c54ac41e9.png)

We should add something to the extent of "Timezone is UTC, not the the WordPress selected timezone."

### Justification or use case
Causes confusion, resulting in support requests, due to the time not working the way you would expect.

**Comment by ashleyfae** [comment]
This is now available in 3.0. (It shows your current time zone, as that's what you can start entering it as in 3.0.)

![Screenshot from 2021-05-20 12-54-16](https://user-images.githubusercontent.com/6324272/118974643-f4d1e380-b96a-11eb-9717-c23f1603081f.png)
