### ISSUE TITLE
3.0 - Add a "type" column to the Order Addresses table. 

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#7300]
While the Customer Addresses table has a "type" column to signify whether the address is "billing" or "shipping", the Order Addresses table does not. 

If Simple Shipping should/will be updated to store the Shipping Address for an order in the Order Addresses table, currently it cannot indicate that the address is for "shipping". 

Keeping in line with what we decided in https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7254, we should add a `type` column to the Order Addresses table, which will contain the purpose of the address (billing/shipping/etc).

**Comment by cklosowski** [comment]
100% agree with that. Let's add a new column there.
