### ISSUE TITLE
3.0 - Handle "name" column in the Customer/Order Addresses tables

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#7302]
## Enhancement Request
The Order Address table includes columns for the first_name and last_name. 

The Customer Addresses table does not. 

In the Order Addresses table, we should replace those 2 columns with 1 (proposed by @jjj on basecamp). Perhaps replacing `first_name` and `last_name` with a column called `name`. 

To the Customer Addresses table, we should also add a `name` column, as a "Customer" could actually be multiple people, and would also be consistent with the understanding of a complete "Address" as seen in the Order Addresses table.

**Comment by cklosowski** [comment]
Been researching this, and for the upgrade routine I believe we'll need to do this in 3 steps:
1) Run a routine to create the new `name` column after the `last_name` column.
2) Run a query that will concat `first_name` and `last_name` columns into the new `name` column
3) Delete the `first_name` and `last_name` columns.

With those three steps existing in the upgrade routine I believe we should be able to do this without issue for anyone who's already been using this table in their testing.

**Comment by cklosowski** [comment]
We'll also need to update the create statement and schema to just use the one new columns, so that any new installs don't have to run through the full upgrade routines if needed.

**Comment by cklosowski** [comment]
So the things we need here are:

- [ ] Add a new column to the `order_addresses` table called `name`
- [ ] Combine the `order_addresses` columns of `first_name` and `last_name` to the `name` column
- [ ] Remove the `first_name` and `last_name` columns from the `order_addresses` table
- [ ] Add a `name` column to the `customer_addresses` table.

**Comment by mintplugins** [comment]
Should we also handle this during 2.9x->3.0 migration?

**Comment by cklosowski** [comment]
@mintplugins yes, adding to the list.

**Comment by cklosowski** [comment]
I'm looking more into this...why are we using `MEDIUMTEXT` for a name column?

`TEXT: 65,535 characters - 64 KB maximum storage with 2 byte overhead`

`MEDIUMTEXT: 16,777,215 - 16 MB maximum storage with 3 byte overhead`

The space is not an issue, however I'm just wondering if we should just restrict that a bit. I think `MEDIUMTEXT` is overkill for a name column. I realize we're looking for flexibility, but I feel like we can reign in this data type in order to maximize optimization. Many small optimizations spread across the tables, leads to larger optimizations overall.

**Comment by JJJ** [comment]
I’m not sure about this column specifically, but I recall us going through all of these together and deciding them based on the following factors:

* to match what WordPress usually does for string fields of equal intent
* to keep them familiar, trying to reduce the learning curve of having too many different unique column types
* some byte-to-flexibility trade-offs just seemEd wrong not to prepare for

Without looking, I don’t think WordPress uses regular TEXT columns anywhere.

**Comment by cklosowski** [comment]
@jjj sounds good we'll keep using the medium. I had forgotten those conversations. I like familiarity when it comes down to a 1 byte change. 👍
