### ISSUE TITLE
3.0 - The order_adjustment meta is not required for fees

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#7305]
### Expected behavior
When I place an order containing an item with a fee (like shipping), I expect the ID and Price ID of that item to be stored in a single place. 

### Actual behavior
The Download ID and Price ID of the fee is stored in multiple places:

- It is stored in the order_items table in the `product_id` and `price_id` columns.
- It is also stored as meta on the order_adjustment. 

Instead of storing it as meta on the order adjustment, it can be pulled directly from the order_items table whenever needed, since the order_adjustment contains the id of the order_item in the object_id column.

<img width="1425" alt="Screen Shot 2019-06-18 at 1 13 55 PM" src="https://user-images.githubusercontent.com/1638128/59711817-d476d880-91d9-11e9-9a35-99486d7dfcb4.png">

The code where the meta is added is here:
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/payments/class-edd-payment.php#L637-L638

There are a few places where that code is used and could be replaced:
<img width="795" alt="Screen Shot 2019-06-18 at 1 10 15 PM" src="https://user-images.githubusercontent.com/1638128/59704586-80182c80-91ca-11e9-8a73-8619233ff8f9.png">

The code to replace:
`edd_get_order_adjustment_meta( $item_fee->id, 'download_id', true );`

The code to replace it would be:
`$item->product_id`, where `$item` is an `Order_Item` object.

**Comment by cklosowski** [comment]
As noted by @jjj we'll need to make sure backcompat still works to get order item details.

**Comment by JJJ** [comment]
I have a foggy memory of us saving this to meta because they might be different.

Is it possible for a download ID to be different than a product ID? Maybe with bundles or multiple files per download, or something else?

**Comment by cklosowski** [comment]
For a purchase no. If you purchase a bundle that is just a download/product ID. Multiple files per download aren't part of the order item at all.

They are basically duplicate data at this point. I still need to vet if there is an issue with backwards compatibility though

**Comment by mintplugins** [comment]
For EDD 3.0 backwards compatibility, do we ever intercept call to `get_post_meta` and return table values? I can see how this would be both a good idea and a bad idea. Just curious if we do it anywhere already.

**Comment by cklosowski** [comment]
@mintplugins I believe we do our best to intercept those. We'll need to verify that as part of the backwards compatibility.
