### ISSUE TITLE
add Forgot password form

### ISSUE THREAD

**Issue by iftikharalam73** [easydigitaldownloads/easy-digital-downloads#7310]
Hey guys, I suggest you add the forgot password functionality where my customers can request for resetting their password.
one more thing, please add recapture option on login and forgot password form.

**Comment by mintplugins** [comment]
@iftikharalam73 Is there a specific context where you want this to happen? Are you using a specific shortcode? 

Also, when opening issues, please use the auto-pre-filled template provided as opposed to erasing/ignoring it. It is there to help us understand issues faster and with more clarity, which ultimately helps everyone.

**Comment by spencerfinnell** [comment]
Previously/duplicate: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/3827

**Comment by iftikharalam73** [comment]
first of all, I don't think so it's an issue it's a request for a new feature.
you guys have a feature like if I paste a specific shortcode on a page there will be login from ( right ? ) I am suggesting you, add a similar feature like that for forget password form.

**Comment by mintplugins** [comment]
Thanks @spencerfinnell. Closing in favour of https://github.com/easydigitaldownloads/easy-digital-downloads/issues/3827
