### ISSUE TITLE
 if checkout page they will be redirected to a specific page

### ISSUE THREAD

**Issue by iftikharalam73** [easydigitaldownloads/easy-digital-downloads#7311]
if the checkout page is empty when they visit the checkout page they will be redirected to a specific page.

**Comment by mintplugins** [comment]
@iftikharalam73 I'm not sure if I understand what you mean here. Can you clarify what you mean when you say a `specific page`?

**Comment by tride1997** [comment]
7311


Vào 22:32, T.2, 24 Th6, 2019 Phil Johnston <notifications@github.com> đã
viết:

**Comment by iftikharalam73** [comment]
there will be an option to choose a specific page where they will be redirected

**Comment by mintplugins** [comment]
You can already choose a custom page for the user to be directed to for checkout under "Dashboard" > "Downloads" > "Settings" > "General" > "Pages" > "Primary Checkout Page". See screenshot:

<img width="1189" alt="Screen Shot 2019-06-24 at 12 10 14 PM" src="https://user-images.githubusercontent.com/1638128/60034682-32436e80-9679-11e9-85ca-2fc68d676cf7.png">

**Comment by iftikharalam73** [comment]
I mean if the checkout page is empty when they visit the checkout page they will be redirected to a specific page.

**Comment by cklosowski** [comment]
@iftikharalam73, Are you saying,

If the customer hits checkout and they have nothing in the cart you want to redirect them?

**Comment by iftikharalam73** [comment]
yeap, you are right.

**Comment by cklosowski** [comment]
@iftikharalam73 This can already be done via a filter:
```
function eddwp_empty_cart_redirect() {
	$cart     = function_exists( 'edd_get_cart_contents' ) ? edd_get_cart_contents() : false;
	$redirect = site_url( 'pricing' ); // Change to whatever page you want to redirect them to.
	if ( function_exists( 'edd_is_checkout' ) && edd_is_checkout() && ! $cart ) {
		wp_redirect( $redirect, 302 );
		exit;
	}
}
add_action( 'template_redirect', 'eddwp_empty_cart_redirect' );
```
