### ISSUE TITLE
3.0 - The order_number column will collide for refunds if you enable Sequential Order Numbers after an order has come in.

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#7314]
### Expected behavior
I expect the value in the order_number column to be unique no matter what.

### Actual behavior
The value in the order_number column is not always unique. See scenario below:

### Steps to reproduce the behavior
1) On a brand new installation of release/3.0, purchase a product.
2) Refund that order.
2) Enable `Sequential Order Numbers` under `Dashboard > Downloads > Settings > Misc > Accounting`.
3) Purchase another product. 
4) Refund that order.
5) Notice you now have 2 orders containing `1-R-1` in the `order_number` column, but they actually relate to different orders.

<img width="704" alt="Screen Shot 2019-06-21 at 3 54 49 PM" src="https://user-images.githubusercontent.com/1638128/59948034-eb693500-943c-11e9-9e83-dfe4c9f08a97.png">

For more context, see the parent orders here:
<img width="690" alt="Screen Shot 2019-06-21 at 4 21 22 PM" src="https://user-images.githubusercontent.com/1638128/59949893-739e0900-9442-11e9-8e3f-f774b7ad0942.png">

### Information (if a specific version is affected):
EDD Version (or branch): 3.0

**Possible recommended fix to consider:**
Instead of generating the refund's order_number using the parent's `order_number`, it could be generated using the parent's `id`. Which is guaranteed to be unique.

Additionally, perhaps the order_number column should have a UNIQUE for the table structure to enforce this at the DB level.

**Comment by mintplugins** [comment]
In order to test this you'll likely want to merge in #2721

Testing Steps:

Purchase an order with multiple items
Refund one off the items
In the orders table, confirm whether the format of the order_number for the refund order is now using the ID instead of the order_number column value from the parent.

<img width="439" alt="Screen Shot 2019-07-02 at 4 56 53 PM" src="https://user-images.githubusercontent.com/1638128/60546238-e9c82880-9cea-11e9-99bd-55e03e3cef48.png">

**Comment by cklosowski** [comment]
@mintplugins #2721 was merged into `release/3.0` already, in preparation for the Office Hours live we did. So if it's not in your branch we should re-merge `release/3.0` into this branch so it's most like the release branch.
