### ISSUE TITLE
3.0 - Orders - Improve/Refine Javascript assets for Orders/Payments

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#7317]
### Explain your enhancement (please be detailed)
As it stands we have two Javascript assets. One for Orders and one for Payments. One is used when viewing an existing order. One is used when adding a new order. This can be confusing as there is a bit overlap with the logic included in these that means we need to update it in both places.

### Justification or use case
To avoid confusion and make maintenance easier, we should isolate shared functionality between the two screens and include those in a more 'global' payments/orders Javascript file, and only include specific functions with when necessary.

**Comment by mintplugins** [comment]
Related: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7297

**Comment by spencerfinnell** [comment]
PR #7519 

This reimplements what previously existed in `edd-admin-payments.js` and `edd-admin-orders.js`. Both scripts were loaded on all order-related pages previously, and still are, however all code now lives in `js/admin/orders`. `edd-admin-payments` is still enqueued so anything setting that as a dependency will still be properly enqueued.

Not all of the script applies when viewing an existing order but those event bindings will just be ignored as the elements won't exist on the page. `edd-admin-orders.js` is now ~19kb where before `edd-admin-orders.js` and `edd-admin-payments.js` added up to ~30kb, so loading some "unused" bindings still result in a smaller bundle.
