### ISSUE TITLE
3.0 - On the orders table, the user_id is inconsistently updated to reflect changes to the customer.

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#7321]
## Bug Report
When I update the user attached to a customer, all of that customer's orders get updated so that the `user_id` column reflects the new user. 

However, if I simply unlink a user from a customer, it does not set the user for those orders to `0`. It leaves them what they were before. 

### Expected behavior
When I unlink a user from a customer, I expect that customer's order's `user_id` columnb to be set to `0`. This would match what happens when you assign a new user to a customer.

### Actual behavior
The `user_id` column is not updated.

### Steps to reproduce the behavior
1) Have a few products purchased by a customer with a user attached.
2) Edit the customer and unlink the user by clicking the broken chain icon.
3) Look at the edd_orders table and notice that the user_id column for those orders was not updates to be `0`, but still matches what the user _id previously was.

### Information (if a specific version is affected):
EDD Version (or branch): 3.0

<img width="620" alt="Screen Shot 2019-06-25 at 12 58 05 PM" src="https://user-images.githubusercontent.com/1638128/60117904-1effd400-9749-11e9-8b71-4e322abdb777.png">

**Comment by cklosowski** [comment]
Originally I was going to do this on the actions performed in admin, but thinking we should make this part of the customer class, so that any time that a customer class runs the update, and the `user_id` column is supplied as one of the changing values, we run the update on the orders.

This would mean that it's done at a system level, not just when the admin action is run from the customer interface.

**Comment by cklosowski** [comment]
I do have one major concern that this would take place, in possibly places that are unintended...do you have some thoughts @mintplugins ?

**Comment by mintplugins** [comment]
@cklosowski I like that approach more. I think it will cover all of the possible issues where these could get out of sync, while also only running when necessary.
