### ISSUE TITLE
3.0 - Discount amounts are not being logged on order_items

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#7323]
### Expected behavior
When I purchase an order that has a discount applied, I expect the item-specific discount amount to be recorded in the order_items table in the discount column.

### Actual behavior
The discount column in the order_items table is always 0, even if a discount has been applied to the order.

### Steps to reproduce the behavior
1) Add an item to the cart
2) Add a discount code on checkout
3) Complete the purchase
4) Look at the order_items table and note that the discount column is `0`.

### Information (if a specific version is affected):
EDD Version (or branch): 3.0

**Comment by mintplugins** [comment]
For the more visually inclined, here's a screenshot:

<img width="1440" alt="Screen Shot 2019-06-25 at 4 04 17 PM" src="https://user-images.githubusercontent.com/1638128/60129976-4f08a080-9764-11e9-94fe-8f089a6a9cfb.png">

**Comment by mintplugins** [comment]
Modifying the steps for replicating this:

# Steps to reproduce the behavior
1. Create a discount code and add product requirements.
2. Save it. 
3. Remove the product requirements. 
4. Add an item to the cart
5. Add a discount code on checkout
6. Complete the purchase
7. Look at the order_items table and note that the discount column is 0.

**Comment by mintplugins** [comment]
I have tracked this down to the product requirement check here:
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/cart/class-edd-cart.php#L666

The `! is_empty` check is returning true, with the supposed non-empty value being:

```
Array
(
    [0] => 0
)
```

Ultimately, PHP seems to see that as `not empty`. The value is coming from `edd_get_discount` which then pulls in the `product_reqs` value here:

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/discount-functions.php#L652

Several abstracted functions down that calls `EDD\Compat\Discount_Query` which extends `EDD\Database\Queries\Adjustment` which extends `EDD\Database\Query`.


From there I get a little bit lost as to how `product_reqs` is getting populated.

**Comment by mintplugins** [comment]
@JJJ Would you be able to help me find the place where that value gets populated as an array?

**Comment by mintplugins** [comment]
I assume it has something to do with the value being fetched as meta, and that by default it is set to return an array, the same way `get_post_meta` works, but I am curious to learn where that is happening in the EDD 3 code.

**Comment by cklosowski** [comment]
@mintplugins it's working the same way essentially. The meta tables for EDD 3 are registered meta tables, so they can use the `get_metadata` functions, which supports all the `single` arguments. this is returning an empty array b/c we didn't find any due to the code fixed in #7349 

Closing this out as that's been merged.
