### ISSUE TITLE
3.0 - Multiple discounts at checkout is broken

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#7324]
### Expected behavior
When I apply 2 discount codes to an order at checkout, I expect them both to be applied.

### Actual behavior
To be honest, I'm not sure how the math is getting here, but it isn't right.

<img width="745" alt="Screen Shot 2019-06-25 at 4 23 23 PM" src="https://user-images.githubusercontent.com/1638128/60130727-d1459480-9765-11e9-9fe0-ea226cf42953.png">

Result:
<img width="722" alt="Screen Shot 2019-06-25 at 4 26 22 PM" src="https://user-images.githubusercontent.com/1638128/60130820-03ef8d00-9766-11e9-844f-1df5d8d550e7.png">

### Steps to reproduce the behavior
1) Enable multiple discounts per cart in the EDD settings.
2) Create 2 discount codes.
3) Apply them both to a new order
4) See if the amount you pay is correct.

### Information (if a specific version is affected):
EDD Version (or branch): 3.0

WordPress Version:

Any other relevant information:

**Comment by cklosowski** [comment]
@mintplugins have we verified this is a regression? Just to make sure we have an expected and actual

**Comment by mintplugins** [comment]
Confirming this is a regression. Screenshots from 2.9:

<img width="620" alt="Screen Shot 2019-07-08 at 1 43 35 PM" src="https://user-images.githubusercontent.com/1638128/60830990-7b6de500-a186-11e9-91d4-2a7b94714de0.png">
<img width="631" alt="Screen Shot 2019-07-08 at 1 43 44 PM" src="https://user-images.githubusercontent.com/1638128/60830991-7b6de500-a186-11e9-9eae-dac7ab8ee1ef.png">

Note that the amounts here might look wrong, but that's a display issue being addressed in https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4833

**Comment by pippinsplugins** [comment]
Multiple discounts is working properly for me. Here's an order with 2x 10% discounts applied:
<img width="654" alt="Screen Shot 2019-12-17 at 2 18 00 PM" src="https://user-images.githubusercontent.com/1034109/71030977-1aa0ec00-20d8-11ea-80e0-4432b5218538.png">
<img width="697" alt="Screen Shot 2019-12-17 at 2 18 38 PM" src="https://user-images.githubusercontent.com/1034109/71030993-22f92700-20d8-11ea-967a-a1219e496680.png">

I did find, however, that the second discount code isn't recorded in the adjustments:
<img width="1826" alt="Screen Shot 2019-12-17 at 2 19 02 PM" src="https://user-images.githubusercontent.com/1034109/71031029-399f7e00-20d8-11ea-93ba-100c15bac4f4.png">

**Comment by pippinsplugins** [comment]
Found the problem. The discount object was getting passed into the `description` parameter of `edd_add_order_adjustment()` instead of `$discount->code`.
