### ISSUE TITLE
3.0 - EDD_Payments_Query needs a way to get the "found_posts" equivalent from WP_Query

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#7336]
The `found_posts` value in WP_Query returns the total number of posts, regardless of your `posts_per_page` or `offset` parameters.

In order to fully replace all usages of WP_Query (where payments are being queried), a "found_posts" value will need to be part of the `EDD_Payments_Query` class.

**Comment by cklosowski** [comment]
@mintplugins is this a backwards compatibility thing for 3.0?

**Comment by mintplugins** [comment]
@cklosowski It is yeah.

**Comment by mintplugins** [comment]
Just noting that the database engine appears to already get this in the `found_items` value.

However, I am not sure yet whether this works the same way as WP core's `found_posts`, in that it ignores the posts_per_page and offset values:

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/database/engine/class-query.php#L228

I need to test that further.

**Comment by ashleyfae** [comment]
Closing this, as BerlinDB has full support for it: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/database/engine/class-query.php#L592-L628
