### ISSUE TITLE
3.0 - Orders - Add a new line in the order summary metabox for each adjustment type

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#7341]
Each adjustment type could/should probably have it's own line in the order summary, as opposed to summing them together as seen in this screenshot:

<img width="1270" alt="image_from_ios" src="https://user-images.githubusercontent.com/1638128/61000673-edcbfa00-a32b-11e9-8745-5dceab0bc51c.png">

**Comment by cklosowski** [comment]
The big issue I have with this is that we could potentially have some non-frontend friendly adjustment types. Even with a UCFirst there is some issues we could run into unless we have a 'registered adjustment types' array, much like we do with order status where we have a key (used in the column) and a label, that can be translated.

**Comment by spencerfinnell** [comment]
@mintplugins What is the benefit of having the rows duplicated there alongside what exists in the separate box?

The Subtotal item doesn't have any individual order items listed under it (which would be a similar pattern to what is suggested for Adjustments).

**Comment by mintplugins** [comment]
@spencerfinnell Good point. I don't think there is any benefit to the duplication. For some reason my brain wasn't seeing those as "totals". I wonder if re-naming the box to something like "Order Amount Totals" would help, or something to help indicate that those are the summed-values. Not totally sure if anything needs to be done at all, but just noting my own confusion with it. 

The word "adjustments" isn't something I've ever seen on a receipt before, and I guess I wouldn't assume that taxes are included in the word "adjustments", which appears to be missing, unless you know tax is an adjustment of course. I also wouldn't assume that taxes and fees would be summed together and shown on a receipt that way. 

I realize this isn't a receipt, but to the site owner it kind-of is I think.

**Comment by mintplugins** [comment]
I'm fairly sure that if you have a $-1 fee (like in discounts pro) and $1 of tax, the adjustments total will be $0, which I feel is confusing. I haven't tested this in a while though so I'm not totally sure if that's how it works.

**Comment by spencerfinnell** [comment]
@mintplugins Makes sense. I like "Order Amount Totals". I've experimented a little with combining order line items and adjustment line items in the UI so it's more obvious that adjustments are directly affecting the totals, and then we could put the totals directly under all line items. But I couldn't quite get there.

It might be worth exploring showing a negative or positive symbol on Taxes, Adjustments, and Discount rows or styling them slightly differently to help indicate they are the difference between Subtotal and Total.

**Comment by mintplugins** [comment]
@spencerfinnell Looks like I was wrong about taxes being summed in with adjustments. 

But it looks like negative fees are shown as positive fees, like you mentioned. 

<img width="299" alt="Screen Shot 2020-01-23 at 2 02 56 PM" src="https://user-images.githubusercontent.com/1638128/73015014-33907180-3de9-11ea-80e6-bbb31d2cfe94.png">

**Comment by mintplugins** [comment]
Sorry that wasn't a fee, that was just a discount code. So discounts are being duplicated in the Order Amounts metabox at the moment, under both "Discount" and under "Adjustments".

**Comment by spencerfinnell** [comment]
@mintplugins Is that an existing order, or when manually creating one? https://github.com/easydigitaldownloads/easy-digital-downloads/pull/7541 tweaks calculations slightly.

**Comment by mintplugins** [comment]
That was a new order, but was done on `release/3.0` directly. 

Here's another scenario I just tested on `issue/7541`:

- $10 product
- $10 Shipping Fee
- $1 discount via Discounts pro
- 10% tax

Here's how it shows on the order record:
<img width="1255" alt="Screen Shot 2020-01-23 at 2 25 54 PM" src="https://user-images.githubusercontent.com/1638128/73016747-76077d80-3dec-11ea-92d9-7615f5b42216.png">

**Comment by spencerfinnell** [comment]
@mintplugins Okay, so `+$10` should be shown for Adjustments, which should eliminate some confusion. I'll check calculations for orders created via the Checkout (references to "manually creating one" before was creating an order in the admin) and try to adjust the UI so it's obvious what is being added and what is being subtracted.

**Comment by mintplugins** [comment]
@spencerfinnell technically the adjustments total should show $9, as the $11 shipping fee shown includes $1 of tax (though that is not explicitly shown), and there's a -$1 fee from discounts pro, totally $9 of adjustments.

**Comment by mintplugins** [comment]
@spencerfinnell But yes it should probably also have a `+` or `-` in front in the Order Amount Totals metabox.

**Comment by spencerfinnell** [comment]
@mintplugins 👍 

The tax is stored separately on the adjustment so we should probably display a `Tax` column in Adjustments Items just like Order Items to help clear up what is happening with adjustments.

This pulls adjustment line items further away from "discount" line items and closer to matching up standard order item line items.
