### ISSUE TITLE
3.0 - Unable to remove Product Requirements for a discount code

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#7347]
I set up a completely fresh EDD 3 to confirm this. Related:
https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7263

### Expected behavior
When I add a product requirement to a discount code, but then attempt to remove it later, I expect the products I removed to be gone after save.

### Actual behavior
After save, the required products are still there, as though I had not removed them.

### Steps to reproduce the behavior
1) Create a discount code
2) Add product requirements
3) Save the discount code
4) Attempt to remove the product requirements
5) Save the discount code
6) Notice the product requirements still exist.

### Information (if a specific version is affected):
EDD Version (or branch): 3.0

**Comment by cklosowski** [comment]
@mintplugins I just tested this and it's working. I'm guessing that it was related to #7349. Will close this for now and if we still have issues with it we can re-open.
