### ISSUE TITLE
3.0 - Discounts: Product conditions are not being saved to meta.

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#7349]
### Expected behavior
When adding a production condition to a discount, the production condition should be saved to the adjustment meta.

### Actual behavior
The product conditions are not stored anywhere.

### Steps to reproduce the behavior
1) Add a discount code and add a product requirement, and select a product condition
2) Save the discount and verify that the `wp_edd_adjustmentmeta` does not contain a product condition.

**Comment by cklosowski** [comment]
While working on this I also found that deleting product requirements/exclusions...does not remove them. including that in the update.

**Comment by mintplugins** [comment]
Related: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7323

**Comment by mintplugins** [comment]
This is working in my tests, and also resolved the issue in #7323
