### ISSUE TITLE
EED not for german market

### ISSUE THREAD

**Issue by zoulhh** [easydigitaldownloads/easy-digital-downloads#7365]
It is illegal to let customers check privacy checkbox only. What we need in addition is a checkbox (and link) to "General trade terms" and "Right of withdrawal". Any ideas how to add that?

Thanks

Michael

**Comment by cklosowski** [comment]
Hey @zoulhh 

Github is for development tracking only. Please contact our support team here and they can get you guided in the right direction:
https://easydigitaldownloads.com/support
