### ISSUE TITLE
EDD 3.0 - Reports: File Download Report filter does not appear to be working

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#7367]
### Expected behavior
The File Download report's filtering option allows file download reports to be filtered to a specific product. 

### Actual behavior
The filtering option does not appear to have any affect on the results shown.

<img width="1252" alt="Screen Shot 2019-08-08 at 4 48 19 PM" src="https://user-images.githubusercontent.com/1638128/62736971-b882fc80-b9fc-11e9-944b-71751383c416.png">

### Steps to reproduce the behavior
1) View the File Download reports page
2) Attempt to filter the results to just a specific product.
3) You still see all file download reports. 

### Information (if a specific version is affected):
EDD Version (or branch): 3.0

**Comment by mintplugins** [comment]
Oh wait...it does appear to be working, it's just below the fold on my laptop, so it seemed like the filter wasn't changing anything, because it wasn't changing anything above the fold:

<img width="1249" alt="Screen Shot 2019-08-08 at 4 54 06 PM" src="https://user-images.githubusercontent.com/1638128/62737188-2fb89080-b9fd-11e9-8ce7-09cd1d2ed669.png">

**Comment by mintplugins** [comment]
I wonder if the cards and generalized data should be hidden if the filter is set to anything other than the default.

**Comment by robincornett** [comment]
@ashleyfae I think we can maybe close this one--the cards and report output have been changed significantly based on if a single download has been selected.

**Comment by ashleyfae** [comment]
Yep, good catch @robincornett .
