### ISSUE TITLE
3.0 - Order History: Filters require `0.00` to filter non-free orders instead of just `0`

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#7375]
### Expected behavior
When I try and filter orders in the list table for non-free orders, I expect `0` to be a valid number.

### Actual behavior
`0` does not filter the order history, it only works if you use `0.00`

### Steps to reproduce the behavior
1) Have a mix of free and non-free purchases
2) Go to Downloads > Orders
3) Click "More"
4) In the dropdown choose 'Greater Than'
5) Type in `0` for the amount and 'Filter'
6) See no items have been filtered, and all orders show
7) Click "More" and type in `0.00` and "Filter"
8) See that free orders have been filtered out.

### Information (if a specific version is affected):
PHP Version: All

EDD Version (or branch): `release/3.0`

WordPress Version: All

Any other relevant information:
As stated above, I believe we're just doing an `empty` check, which needs to allow for `0`. Either that or we set a format on the field which seems overly complex from a UI pespective

**Comment by pippinsplugins** [comment]
PR submitted.
