### ISSUE TITLE
3.0 - The [edd_profile_editor] does not show the complete address

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#7378]
### Expected behavior
When I view/change my address using the edd_profile_editor shortcode, I expect my full address to be shown. 

### Actual behavior
Despite saving the country, it is not populated on the screen.

Before save:
<img width="715" alt="Screen Shot 2019-08-20 at 11 15 46 AM" src="https://user-images.githubusercontent.com/1638128/63360298-25bb5980-c33c-11e9-9c08-a1d82019824d.png">

After save:
<img width="737" alt="Screen Shot 2019-08-20 at 11 16 53 AM" src="https://user-images.githubusercontent.com/1638128/63360271-120ff300-c33c-11e9-9f50-ffe2a16df9e2.png">

### Information (if a specific version is affected):
EDD Version (or branch): 3.0

**Comment by nosegraze** [comment]
PR: #7460

For me the country wasn't being saved in the database at all, so this is what the PR solves. Not sure if you were seeing differently, but that's what I saw when I tested.
