### ISSUE TITLE
Can't Decrease Tax With `modify_cart_item()`

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/easy-digital-downloads#7385]
### Expected behavior

When using 

```
$payment->modify_cart_item( 123, array(
  'tax' => 0,
) );
```

I expect the tax amount for the payment amount to be adjusted by the difference.

### Actual behavior

The line item amount is _doubled_ and added to the total.

### Steps to reproduce the behavior
1) Not implemented anywhere in core

### Information (if a specific version is affected):
PHP Version: 7.x
EDD Version (or branch): master
WordPress Version: 5.2

Any other relevant information:

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/payments/class-edd-payment.php#L1443

`increase_tax()` is always called instead of `decrease_tax()`. If the initial tax amount is $1 it will add $2 ($1 - 0 = $1 which then gets added to the initial $1)

The test case doesn't account for decreases: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/tests/tests-payment-class.php#L886-L898

**Comment by ashleyfae** [comment]
Confirmed. Here's how I reproduced:

Started with an order that had $0 tax. Ran this to set tax to $5:

```php
$payment = new EDD_Payment( 334 );
$result = $payment->modify_cart_item( 0, [
	'tax' => 5
] );
$payment->save();
```

Tax was increased to $5.

Then I ran this to decrease it to $1:

```php
$payment = new EDD_Payment( 334 );
$result = $payment->modify_cart_item( 0, [
	'tax' => 1
] );
$payment->save();
```

The tax for the individual order item became $1, but the overall tax became $6.
