### ISSUE TITLE
Start and end time for discount codes

### ISSUE THREAD

**Issue by kerijacoby** [easydigitaldownloads/easy-digital-downloads#7389]
## Enhancement Request
Give users the option to enter not only a start and end date for a discount code, but also a specific time.
Similar to [this issue,](https://github.com/easydigitaldownloads/edd-discounts-pro/issues/150) but for EDD core.

### Explain your enhancement (please be detailed)
When entering a new discount code you can select a start and end date. The request is to add time functionality so that a discount may start and end at a specific time on a specific date.

### Justification or use case
Customer request for feature.
https://secure.helpscout.net/conversation/949050390/130721?folderId=180504

**Comment by ashleyfae** [comment]
This is added in 3.0:

![Screenshot from 2021-05-20 12-54-16](https://user-images.githubusercontent.com/6324272/118974263-85f48a80-b96a-11eb-8558-dda7833360d1.png)
