### ISSUE TITLE
3.0 - Cannot query orders by country/region

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#7397]
### Explain your enhancement (please be detailed)
We should be able to query orders by country/region.

### Justification or use case
The current ability does not exist, yet we expose on the order list table the interface to restrict the list table by country/region.

**Comment by cklosowski** [comment]
@JJJ Can you check out this work, in the draft PR?

In order to do what I think we kind of talked about I had to set the private methods to protected so the orders query class could use them, however, if I use `edd_get_orders` I get `NULL` however if I trace through the `query` method and then the `get_item_ids` call, I get the right Item IDs.

**Comment by mintplugins** [comment]
To test, you'll need orders from multiple countries and regions. Then, attempt to filter the order history by country and country+region to ensure the correct orders appear.
