### ISSUE TITLE
3.0 - Set proper value for refund filters

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#7400]
The filters [edd_should_process_order_refund](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/orders/functions/refunds.php#L125) and [edd_should_process_partial_refund](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/orders/functions/refunds.php#L351) should be passing a boolean variable, but instead are passing a string that says `'__return_true'`.

Props @spencerfinnell

**Comment by spencerfinnell** [comment]
The conditionals below should also be explicit truth checks:

```php
if ( true !== $should_refund ) {
	return false;
}
```

**Comment by spencerfinnell** [comment]
PR #7401 ensures a bool is the initial value, and updates the logic below to check against bool values.
