### ISSUE TITLE
Add support for customer tags.

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#7402]
### Explain your enhancement (please be detailed)
Being able to add "tags" to customers (rather than notes) and also search and filter by these tags would be extremely useful. The tags could display (potentially) on the customer list table and be color coded by the users choice. Different extensions could add (or remove) tags such as "High Value Customer" or "Return Customer", "New Address", etc.

### Justification or use case
Better customer classification and marketing potential.

**Comment by davidsherlock** [comment]
Some example tags would be:

`Has Refunds`
`Multiple Addresses`
`Recurring`
`High Value Customer`

I could think of a more cohesive list, but stuff along these lines would be really useful.

**Comment by cklosowski** [comment]
Updating the title as this isn't a 3.0 specific change, just a feature request.
