### ISSUE TITLE
Meta Key EDD Customer

### ISSUE THREAD

**Issue by mohammadr3z** [easydigitaldownloads/easy-digital-downloads#7411]
Hi,
I want to display user purchase information in the user panel.
Information such as: number of purchases, total value of purchase, date of registration
Where do I get this meta user key information?

**Comment by cklosowski** [comment]
@mohammadr3z

All of that information exists on the customer object and is stored in the customer database tables. You can instantiate the EDD_Customer object by using the user_id and the true flag:

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/class-edd-customer.php#L111
