### ISSUE TITLE
Download Notes duplicated in email receipt

### ISSUE THREAD

**Issue by dgoldak** [easydigitaldownloads/easy-digital-downloads#7415]
### Expected behavior
When multiple variable priced options are purchased for the same core product, {download_list} should only display Download Notes once per core product.

### Actual behavior
{download_list} duplicates Download Notes for each variable priced option that is purchased.

### Steps to reproduce the behavior
1) Purchase 2 or more variable options for a single product
2) {download_list} in the email receipt should only display Download Notes once.

### Information (if a specific version is affected):
PHP Version: 5.4.4

EDD Version (or branch): 2.9.17

WordPress Version: 4.9.11

Any other relevant information:
https://secure.helpscout.net/conversation/978365525/134068?folderId=180499

**Comment by cklosowski** [comment]
I think we should rework this entire process, so that the download notes are not attached directly inline with the product names. 

For instance, if you purchase:
Product A - Price 1
Product B
Product A - Price 2

You will end up with:
```
Product A - Price 1 - <notes>
Product B - <notes>
Product A - Price 2
```

Instead I think it'd be best to do somethign like the following:
```
Product A - Price 1
Product B
Product A -Price 2

Notes:
Product A 
<notes>

Product B
<notes>

**Comment by cklosowski** [comment]
What are your thoughts on this @ashleyfae @robincornett @LisaCee 

Before changes:
![image](https://user-images.githubusercontent.com/1390124/112206583-537d1a00-8bd3-11eb-8486-ab808d9368df.png)


After changes:
![image](https://user-images.githubusercontent.com/1390124/112206454-30eb0100-8bd3-11eb-9095-2d97a1237705.png)

**Comment by robincornett** [comment]
Seems like a reasonable approach to me!

**Comment by LisaCee** [comment]
I like it.  It more closely resembles the way notes are handled in Invoices.

**Comment by ashleyfae** [comment]
Yep, I'm happy with it. :+1:
