### ISSUE TITLE
Problem with EED software Licensing

### ISSUE THREAD

**Issue by mohammadr3z** [easydigitaldownloads/easy-digital-downloads#7417]
I use the edd software Licensing plugin
All the steps are done correctly, the license also accepts within the destination site but the new update does not appear.
What can i do

**Comment by cklosowski** [comment]
@mohammadr3z  Github is for development tracking only. Please contact our support team here:
https://easydigitaldownloads.com/support

Since this about Software Licensing, and not the core Easy Digital Downloads plugin, please contact support to get your issues looked into.
