### ISSUE TITLE
PHP Notice: register_meta was called incorrectly

### ISSUE THREAD

**Issue by dashkevych** [easydigitaldownloads/easy-digital-downloads#7422]
## Bug Report

I am currently see the following PHP notice on the site (via the Query Monitor plugin): "register_meta was called incorrectly. When registering an "array" meta type to show in the REST API, you must specify the schema for each array item in "show_in_rest.schema.items". Please see Debugging in WordPress for more information. (This message was added in version 5.3.0.)"

![PHP notice](https://snipboard.io/QdGZPg.jpg)

### Information (if a specific version is affected):
PHP Version: 7.2.23

EDD Version (or branch): 2.9.17

WordPress Version: 5.3-beta3-46455

**Comment by cklosowski** [comment]
Thanks @dashkevych You beat me to it, I was just getting ready to type up this issue and cook up a fix.

**Comment by cklosowski** [comment]
Well I managed to update the call to clear that notice, and another one popped up:
```

Notice | Undefined index: items | 3 | -array_reduce()wp-admin/edit-form-blocks.php:77rest_preload_api_request()Unknown locationrest_do_request()wp-includes/rest-api.php:1539rest_get_server()wp-includes/rest-api.php:429do_action('rest_api_init')wp-includes/rest-api.php:471create_initial_rest_routes()wp-includes/class-wp-hook.php:288WP_REST_Posts_Controller->register_routes()wp-includes/rest-api.php:201WP_REST_Posts_Controller->get_collection_params()wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php:67WP_REST_Controller->get_collection_params()wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php:2393WP_REST_Controller->get_context_param()wp-includes/rest-api/endpoints/class-wp-rest-controller.php:311WP_REST_Posts_Controller->get_item_schema()wp-includes/rest-api/endpoints/class-wp-rest-controller.php:356WP_REST_Meta_Fields->get_field_schema()wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php:2212WP_REST_Meta_Fields->get_registered_fields()wp-includes/rest-api/fields/class-wp-rest-meta-fields.php:463WP_REST_Meta_Fields->default_additional_properties_to_false()wp-includes/rest-api/fields/class-wp-rest-meta-fields.php:436WP_REST_Meta_Fields->default_additional_properties_to_false()wp-includes/rest-api/fields/class-wp-rest-meta-fields.php:554wp-includes/rest-api/fields/class-wp-rest-meta-fields.php:554
-- | -- | -- | --
```

I've asked the development team to update the official documentation, since all we have right now is just examples that don't work.

**Comment by cklosowski** [comment]
Ok, talked to Timothy Jacobs over on the making WP slack, and got things worked out.

Since our price Ids with variable pricing _could_ be `0` or `1` based, depending on when the product was created, we need to use the `object` as the type and treat everything as `additionalProperties` so that WP Core doesn't reindex them before writing them.

**Comment by cklosowski** [comment]
Props @TimothyBJacobs for the help on this one.

**Comment by cklosowski** [comment]
@mintplugins if you could test this out first thing in the AM on Friday so I can get it running on our sites over the weekend to deploy on Monday, I'd appreciate it. You might have to use the Beta Tester Plugin to install nightlys, which would put you on WP 5.3 beta/RC.

**Comment by JJJ** [comment]
@cklosowski Testing this against WordPress 5.3, it looks right to me.

* Notices are gone
* REST still works
* In WordPress Core, `additionalProperties` is a hot mess (as is `rest_validate_value_from_schema()`) but neither of these are EDD's fault

I am +1 to running this over the weekend to let it soak.

**Comment by mintplugins** [comment]
Working for me here as well. I also created some new products with variable pricing as well and no issues or problems appeared.

**Comment by cklosowski** [comment]
awesome, thanks @JJJ and @mintplugins i'm going to merge this into the release branch and get it on our site over the weekend

**Comment by mintplugins** [comment]
We will have to port this over to the 3.0 branch as well, as WP 5.3 is throwing this error on `release/3.0` at the moment.

**Comment by nosegraze** [comment]
> We will have to port this over to the 3.0 branch as well, as WP 5.3 is throwing this error on `release/3.0` at the moment.

Done here: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7479
