### ISSUE TITLE
Pressing enter in the email configuration opens SendWP instead

### ISSUE THREAD

**Issue by scottbuscemi** [easydigitaldownloads/easy-digital-downloads#7427]
### behavior
When typing in the "From Name" and "From Email" fields on the Settings > Emails > General page, hitting the enter key submits the "Connect SendWP" form rather than saving the page.

### Steps to reproduce the behavior
1) Click into the "From Name" field
2) Press the enter key on your keyboard

### Information (if a specific version is affected):
PHP Version: 7.3.2

EDD Version (or branch): 2.9.18

WordPress Version: 5.2.4

Any other relevant information:

**Comment by mintplugins** [comment]
Replicated

**Comment by mintplugins** [comment]
Confirmed fixed in https://github.com/easydigitaldownloads/easy-digital-downloads/pull/7446
