### ISSUE TITLE
Add Provinces of the Netherlands to Billing State/Province Dropdown

### ISSUE THREAD

**Issue by kerijacoby** [easydigitaldownloads/easy-digital-downloads#7432]
### Explain your enhancement (please be detailed)
On the checkout page, when a customer selects the United States or Canada as their country the Billing State/Province field is a dropdown menu of the available states/provinces.
<img width="384" alt="Screen Shot 2019-10-29 at 2 03 57 PM" src="https://user-images.githubusercontent.com/30249621/67800305-0be17580-fa55-11e9-834e-fddafde5cadf.png">

The idea is to introduce the same behavior for the Netherlands (and I imagine other countries as well) so customers can select the appropriate province from the menu instead of typing it in.
<img width="440" alt="Screen Shot 2019-10-29 at 2 04 20 PM" src="https://user-images.githubusercontent.com/30249621/67800340-1865ce00-fa55-11e9-9d32-ebe9d1cdfd0b.png">

### Justification or use case
This behavior exists for some countries but not all.
Customer request conversation # 135185

> Would it be possible to add the Dutch (The Netherlands) provincies to the purchase form in a next update, please? Currently I need add them manually after every update. ;-)

**Comment by cklosowski** [comment]
I think this should be possible, here is a list of the provinces:
https://en.wikipedia.org/wiki/Provinces_of_the_Netherlands

I’m going to reach out to some people in the Netherlands and see if they consider the Caribbean Netherlands provinces as part of that same list.

**Comment by cklosowski** [comment]
Based off what I can see, we should include the Caribbean provinces to.

**Comment by spencerfinnell** [comment]
WooCommerce doesn't currently have a set list because payment gateways do not require a state for The Netherlands, but I think we can still add it.

https://github.com/woocommerce/woocommerce/issues/25113#issuecomment-558597642

**Comment by spencerfinnell** [comment]
PR #7656
