### ISSUE TITLE
Add promotional elements to admin screens

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/easy-digital-downloads#7449]
We'll occasionally use our own admin real estate to display information and/or promotions.

**Comment by SDavisMedia** [comment]
@mintplugins The implementation for EDD ended up being a little more complex than the other plugins, but it should all make sense.

All that's happening is for a time period, based on timestamps, we're going to display some promotions in the admin. We're only using our real estate. If you want to see a few simpler implementations, see [Restrict Content](https://github.com/restrictcontentpro/restrict-content/pull/49) and [Sugar Calendar](https://github.com/sugarcalendar/lite/pull/26).

With that understanding, some of this is context based. EDD has more screens to play with, so it gets more action. The easiest way to see it in action is to...

1. Pull down and check out `issue/7449`
2. Go to _easy-digital-downloads/includes/misc-functions.php_ and change:
`$start = strtotime( '2019-11-29 06:00:00' );` to
`$start = strtotime( '2019-11-07 06:00:00' );`
3. Visit these three pages:
_/wp-admin/edit.php?post_type=download&page=edd-settings_
_/wp-admin/edit.php?post_type=download&page=edd-addons_
_/wp-admin/post-new.php?post_type=download_

On the first two pages, you should immediately see the promo.

On the third page, the Add New/Edit Download screen, what you're looking at is the sidebar of metaboxes. Here's the scoop.

We already display a Product Reviews upsell. It displays when Product Reviews is not installed at all (so that's the first "testing" scenario). If you have it installed, just change its folder name for a second and refresh. You'll see that just another couple of sentences are added to that metabox. And when that's the scenario, the UTM param values change accordingly.

When Product Reviews _is_ installed, but _not_ activated, we display an Activate button. That's when a new metabox appears, completely unrelated (visually) to the Product Reviews metabox. It has promotional text in it. It will display with Product Reviews installed but not activated, as well as when Product Reviews is activated.

---

That's all that's going on here. Code was added to make everything work, but some existing code was modified as well. I refactored a couple of things (mainly with the metaboxes) so I could write DRY code.

Couple of notes:

1. I have to sweep back through all of the plugins and add UTM params where they don't exist. So that's coming.
2. Implementation is already set in stone unless there's an obvious problem. We can't call home from the plugins, or anything like that. So this year, this is how we're making the promos happen.
3. You da man.

I see no `release/2.9.20` branch, so I didn't open a PR. I'll open one as soon as you let me know where you want it.

Thanks in advance for checking this out! Hoping to give you all something to merge and push by Monday morning.

**Comment by mintplugins** [comment]
@SDavisMedia Sounds good :) 

We already [merged](https://github.com/easydigitaldownloads/easy-digital-downloads/pull/7429) a couple of 2.9.20 issues directly into master, so we'll likely go without a release branch this time. So you can just set up the PR to merge into master directly.

**Comment by SDavisMedia** [comment]
@mintplugins PR opened against `master` with all changes in place. So this would be a final review.

**Comment by mintplugins** [comment]
Re-opening this as I am getting a PHP warning when I view a settings page now:
```
Warning: implode(): Invalid arguments passed in /app/public/wp-content/plugins/easy-digital-downloads/includes/admin/settings/display-settings.php on line 133 Call Stack #TimeMemoryFunctionLocation 10.0001366728{main}( ).../edit.php:0 20.0009367400require_once( '/app/public/wp-admin/admin.php' ).../edit.php:10 30.55609375232do_action( ).../admin.php:254 40.55609375608WP_Hook->do_action( ).../plugin.php:478 50.55609375608WP_Hook->apply_filters( ).../class-wp-hook.php:312 60.55609376736edd_options_page( ).../class-wp-hook.php:288 70.56719478392implode ( ).../display-settings.php:133 wp-clearfix">
```

I think we likely need to make sure that `$wrapper_class` is always an array, even if it is an empty array.
