### ISSUE TITLE
Require user to be logged to download

### ISSUE THREAD

**Issue by ZeroGravityWeb** [easydigitaldownloads/easy-digital-downloads#7456]
### Explain your enhancement (please be detailed)
When a user clicks on the link in their email to download the file require them to login to their account before they are able to download the file. Also restricting them to only download files that are in their account.

### Justification or use case
Currently there is nothing to prevent someone sharing the link and having others download their purchase. A Download Link Expiration time can be set and a number of downloads but these still don't prevent someone else from downloading until the parameters are met or expire

**Comment by mintplugins** [comment]
@ZeroGravityWeb There is a custom snippet to force logins here:
http://library.easydigitaldownloads.com/misc/require-login-to-download-files.html
