### ISSUE TITLE
3.0 - "$ is not a function" error in admin JavaScripts in WP 5.3

### ISSUE THREAD

**Issue by nosegraze** [easydigitaldownloads/easy-digital-downloads#7457]
### Expected behavior
I expect all admin JavaScript to be working and I expect to not see any console errors.

### Actual behavior
When visiting any EDD page that loads `edd-admin-downloads.js`, this JavaScript error appears in the console:

![Screenshot from 2019-11-13 14-27-04](https://user-images.githubusercontent.com/6324272/68772540-ea21ea00-0621-11ea-9e66-a5906eec4dbd.png)

Note, the error isn't necessarily exclusive to that file, but that's the one that keeps popping up for me.

### Steps to reproduce the behavior
1) Make sure you're on WordPress 5.3.
2) Visit an EDD page, such as Downloads > Settings or Downloads > Downloads.
3) Check your console for the error. You'll also notice that JavaScript actions don't work, such as clicking to add a new variable price option on a download.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): `release/3.0`

WordPress Version: 5.3

Any other relevant information:

I had Phil confirm this because I thought I was going nuts. This error wasn't there last week and suddenly now it is. After some testing, we believe this to be related to the WordPress 5.3 update, which I did today, and then Phil also saw this error immediately after updating to WordPress 5.3.

This DOES NOT look to be a problem in master branch.

**Comment by nosegraze** [comment]
Just found this, which looks to be relevant and may fix the issue: https://core.trac.wordpress.org/ticket/48568

**Comment by spencerfinnell** [comment]
We need to make sure `jquery` is a dependency of all scripts using `$`, and that `$` is mapped from the global `jQuery` before using it.

**Comment by nosegraze** [comment]
It does look like we are listing `jquery` as a dependency already, and it does look like we're mapping `$` from `jQuery`. Here's an example from `assets/js/admin/downloads.index.js` : 

```js
jQuery( document ).ready( function( $ ) {
	EDD_Download_Configuration.init();
} );
```

At the above point in time, `$` is properly a function. However, as soon as you go inside `init()`, `$` is suddenly undefined.

```js
var EDD_Download_Configuration = {
	init: function() {
            // $ is undefined
```

**Comment by nosegraze** [comment]
I guess it's because at the time the `EDD_Download_Configuration` variable is created `$` isn't defined?

**Comment by spencerfinnell** [comment]
PR #7462 uses `webpack.ProvidePlugin` to ensure `$` always resolves to the `jquery` module, which points to the external `jQuery` library.

**Comment by nosegraze** [comment]
Well that's super useful. Works perfectly!
