### ISSUE TITLE
3.0 - Use @wordpress/scripts in Webpack

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/easy-digital-downloads#7463]
### Explain your enhancement (please be detailed)

Since we originally introduced Webpack in 3.0 the Gutenberg project has helped WordPress create a lot of very helpful Javascript packages.

One of the most useful is [`@wordpress/scripts`](https://github.com/WordPress/gutenberg/tree/master/packages/scripts) which provides scripts and configurations for common build tooling.

Using the [Webpack config](https://github.com/WordPress/gutenberg/blob/master/packages/scripts/README.md#webpack-config) ensures our assets are processed with WordPress-best practices in mind.

It will automatically provide the necessary Babel configuration and allows for our Webpack configuration to stay updated easily.

**Comment by spencerfinnell** [comment]
PR #7503 introduces Babel, ESLint, Browserlist, and Webpack configuration tooling configuration management through a single `@wordpress/scripts` package. This means we have one mono dependency to update and helps prevent the tooling from conflicting due to incompatible version updates.

To test you may need to `rm -rf node_modules` then `npm install`. Then `npm run dev` and run through various components that require JS (Checkout, admin reports, etc).

**Comment by nosegraze** [comment]
@spencerfinnell `npm run dev` works well for me, but I get this error on `npm run build` : 

> npm ERR! missing script: i18n

**Comment by spencerfinnell** [comment]
@nosegraze Good catch. There wasn't really a complete`build` command before either, as we still need it to run a few `Grunt` tasks for CSS and the `.pot` generation after it handles the JS. I'll get that fixed.

**Comment by spencerfinnell** [comment]
@nosegraze Fixed in PR.

**Comment by nosegraze** [comment]
@spencerfinnell Works well now!
