### ISSUE TITLE
3.0 - Orders - Errors Updating Existing Order

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#7464]
### Expected behavior
When I update an order via the admin "Edit Order" page, I expect to not have any PHP notices when saving.

### Actual behavior
When I update an order, I get this notice:

```
[14-Nov-2019 16:01:50 UTC] PHP Notice:  Undefined index: edd-current-customer in /var/www/edd3/wp-content/plugins/easy-digital-downloads/includes/admin/payments/actions.php on line 122
```

### Steps to reproduce the behavior
1) Edit an existing order via Downloads > Orders.
2) Click "Save Order". No need to make any changes.
3) Check the error log.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): `release/3.0`

WordPress Version: 5.3

Any other relevant information:

**Comment by spencerfinnell** [comment]
A similar error also occurs when creating and assigning a new customer to an existing order. 

<img width="814" alt="Screen Shot 2020-01-23 at 1 16 47 PM" src="https://user-images.githubusercontent.com/491124/73011660-b19d4a00-3de2-11ea-9c7d-977dc54ac7c6.png">

The notice should be updated to "Error updating order." as well.

**Comment by spencerfinnell** [comment]
A few other things:

`$status` is not defined: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/payments/actions.php#L350

Setting `date_created` seems like it should be `date_modified`, but I lack historical context to be sure: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/payments/actions.php#L230

With those tweaks the Order still fails to update with the following arguments:

```
array(5) {
  ["date_modified"]=>
  string(19) "2020-02-05 10:29:00"
  ["user_id"]=>
  string(1) "0"
  ["email"]=>
  string(13) "test@test.com"
  ["tax"]=>
  float(0)
  ["total"]=>
  string(4) "0.00"
}
```

**Comment by spencerfinnell** [comment]
Fix for `edd-current-customer` included in #7557

**Comment by cklosowski** [comment]
@spencerfinnell I’ve merged in the fix that was in #7557. If we need this open for anything else, go ahead and submit it as a separate PR, if all issues are resolved with that commit, go ahead and close this out then.

**Comment by robincornett** [comment]
I created a new order today and did not assign a customer. When I saved the order, I got an error:

```
PHP Warning:  Invalid argument supplied for foreach() in ...includes\admin\payments\orders.php on line 273
```

I also have error/notices when viewing an order with no assigned customer:
```
PHP Warning:  Invalid argument supplied for foreach() in ...includes\admin\payments\orders.php on line 271
Trying to get property 'email' of non-object in ...includes/admin/payments/orders.php:269
Trying to get property 'emails' of non-object in ...includes/admin/payments/orders.php:271
```

I also have this one in my log but am not 100% sure of when exactly it happened, but it was in between the creation and viewing of the order:
```
PHP Warning:  array_map(): Expected parameter 2 to be an array, null given in ...includes\admin\payments\actions.php on line 687
```

**Comment by spencerfinnell** [comment]
I'm going to try to get this cleared up now that the new Add/Edit flow is in. There is also a fair amount of code that deals with totals/downloads that can be removed since none of that changes on Orders any more:

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/payments/actions.php#L116-L222

**Comment by robincornett** [comment]
@spencerfinnell yesterday I was trying to track down what happens when an order is added in the admin, because as far as I can tell, the [`edd_complete_download_purchase`](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/payments/actions.php#L108) hook does not fire (in the `edd_complete_purchase` function--there are other hooks in there as well), which is an issue for Software Licensing. Is this correct? It seems like other related work does happen, like updating totals, etc., but I was getting a bit lost trying to trace the path.

**Comment by spencerfinnell** [comment]
@robincornett I believe that only runs when an Order transitions status, so creating one in the admin that is already set to Complete won't trigger it. 

Earnings and what not are adjusted in [`edd_add_manual_order()`](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/orders/functions/actions.php#L23)

I'm not 100% sure, but I think that was the behavior when using the Manual Purchases extension with 2.9.x and Software Licensing.

**Comment by robincornett** [comment]
@spencerfinnell I've found that sending a receipt also does not occur when manually creating an order, even with the "send receipt" option checked. I am able to resend a receipt.

The order is correctly set to `pending` and then updated to `complete`, but some standard payment completion things do not appear to be happening.

**Comment by spencerfinnell** [comment]
PR #7831 addresses the "Save Order" routine for _existing_ Orders. It should ensure the following items can change:

- Customer
- Address (this is an Order billing address, not a Customer address)
- Date
- Time
- Status
- Unlimited Downloads

It should also allow a new Customer to be created and assigned to the Order.

**Comment by ashleyfae** [comment]
1. Edit a `complete` payment`.
2. Change status to `pending`.
3. Save.
4. Upon refresh, it was actually refunded.

I don't think this has anything to do with your PR thusfar, @spencerfinnell, so if you want me to make a new issue for this I can.

---

Otherwise confirmed changing address, customer, date, time, and unlimited downloads all work.

**Comment by spencerfinnell** [comment]
@ashleyfae Check out https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7782

**Comment by ashleyfae** [comment]
Oh whelp. Didn't connect that. Thanks!
