### ISSUE TITLE
Hooks on cart fees actions column

### ISSUE THREAD

**Issue by rubengc** [easydigitaldownloads/easy-digital-downloads#7469]
## Enhancement Request
On cart fees HTML ([checkout_cart.php](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/templates/checkout_cart.php#L73-L78) file) there is no action or filter to insert custom content to this column to, for example, add a "Remove" action when a custom fee is not assigned to an item

### Explain your enhancement (please be detailed)
The unique solution is to include a new hook, probably an action like 'edd_cart_actions' but inside the fee's actions column to allow third party plugins add custom content here

### Justification or use case
I want to add custom cart fees and add custom actions on their rows

**Comment by mintplugins** [comment]
@rubengc The items that are displayed in the cart are controlled by the cart object. If you'd like to add custom things to the cart, you'll want to look at doing it at the data/object level, as opposed to doing it in the display layer. 

Adding it in the display layer won't actually result in the fee being charged, but only shown. 

You can play with having a totally customized checkout if you follow this guide in the docs:
https://docs.easydigitaldownloads.com/article/279-customizing-the-checkout-cart-template

For adding custom fees, you'll want to investigate the fees api in EDD:
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/b3b09b718d04ded5611b8b34194cbb77190a2c47/includes/class-edd-fees.php#L22
