### ISSUE TITLE
Mouseover "Deactivate" link for discount codes leaves status as "Active"

### ISSUE THREAD

**Issue by nutsandbolts** [easydigitaldownloads/easy-digital-downloads#7472]
### Expected behavior
When I hover over a discount code and click the Deactivate link below the title, I expect the discount code to be deactivated and the status to be changed to Inactive.

### Actual behavior
When I hover over a discount code and click the Deactivate link below the title, the discount code is deactivated, but the status column still says Active.

### Steps to reproduce the behavior
1) Create a discount code that is active.
2) From the list of all discounts, hover over the discount and click Deactivate.
3) Note that the discount status still says Active, but if you hover over the title again, the link has changed to Activate instead of Deactivate. So the link is working, but the status column just doesn't update to reflect the change.

If you actually click to edit the discount and change the dropdown to Inactive, the status column does update appropriately.

**Comment by cklosowski** [comment]
This was fixed in 3.0 in the revamp of our list tables and new 'status' system for cart adjustments.
