### ISSUE TITLE
3.0 - edd_settings_styles deprecation passes args incorrectly

### ISSUE THREAD

**Issue by Spreeuw** [easydigitaldownloads/easy-digital-downloads#7476]
This code https://github.com/easydigitaldownloads/easy-digital-downloads/blob/31a05ecfbc7787aef40c80bcc4a0e3b10cb38d2b/includes/admin/settings/register-settings.php#L1153-L1161 throws the following notice:
```
PHP Notice:  Undefined offset: 0 in \wp-includes\plugin.php on line 249
```
because the `$args` should be an array of the arguments (it needs one more level):
```php
$edd_settings['styles'] = edd_apply_filters_deprecated(
	'edd_settings_styles',
	array(
		array(
			'main'    => array(),
			'buttons' => array(),
		),
	),
	'3.0',
	'edd_settings_misc'
);
```

**Comment by spencerfinnell** [comment]
PR #7563 ensures using the `edd_settings_styles` filter does not produce a PHP Notice (just an EDD deprecation notice).
