### ISSUE TITLE
Download sidebar shows down of the page on mobile

### ISSUE THREAD

**Issue by emyabdel** [easydigitaldownloads/easy-digital-downloads#7477]
Hi, the issue is that on the download page, Download sidebar shows down of the page on mobile and it's better to show it just after content before the comments section or at least on the top of the page.

**Comment by mintplugins** [comment]
They there.

This is likely an issue with your theme and where it displays widgets, as opposed to anything in EDD itself. I would recommend reaching out to your theme provider for assistance on this one.

**Comment by emyabdel** [comment]
I use vendd theme. Do you know how to make this modification, please!

**Comment by mintplugins** [comment]
Reach out to the support desk over at https://easydigitaldownloads.com/support/ and they can help point you in the right direction.

**Comment by emyabdel** [comment]
I contacted them and hope they have the solution. Thanks
