### ISSUE TITLE
3.0 - merge master branch into release/3.0

### ISSUE THREAD

**Issue by nosegraze** [easydigitaldownloads/easy-digital-downloads#7479]
The release/3.0 branch needs to be updated with master. There have been many changes to master that have not been ported over, including a fix for this really annoying notice: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7422

**Comment by nosegraze** [comment]
PR:  #7480

## Notes

### Travis Config

release/3.0 had way, way fewer entries in the matrix. I'm not sure if that was intentional. I copied over all the ones from master for now. Let me know if that should be adjusted. 
master: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/.travis.yml
release/3.0: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/.travis.yml

---

### Orders

I did not copy over the changes from this PR: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7132 It looks like 3.0 has no concept of being able to add new order items at all so I think this is irrelevant now?

---

### edd_get_payment_status() changes

We should re-test this: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7292
Relevant commit: https://github.com/easydigitaldownloads/easy-digital-downloads/commit/79138ad053a48545b44b4e51291007932d372772#diff-ea8e4198fcb891a0b9f5590f49573271

There were a lot of differences in that function and I just want to double check and make sure I got it all right.

---

### BFCM Promos

https://github.com/easydigitaldownloads/easy-digital-downloads/pull/7452/files

There have been some significant changes on both the "Downloads > Extensions" page and "Downloads > Settings" page so we should check to make sure the promos still look the way they're supposed to. I did a quick visual check and it looked fine to me, but should still be more carefully compared against master.

---

### SendWP

PR: https://github.com/easydigitaldownloads/easy-digital-downloads/pull/7266
This should probably be fully tested again. I rewrote the JavaScript due to the general JS changes we see in 3.0. I tested as far as clicking the "connect" button and verifying I am correctly forwarded to the authentication page. But it should probably be tested further, including the disconnect option.

**Comment by mintplugins** [comment]
PR:  #7480

## Notes

### Travis Config

It seems logical to me that they remain. 

---

### Orders

I believe it is irrelevant, yes. 

---

### edd_get_payment_status() changes

Re-tested this and all is well.

---

### BFCM Promos

Promo elements all look correct. I was seeing a strange new style on the promo element in the extensions list but that ended up being a separate issue, not introduced here. 

---

### SendWP

I tested this as well, all is well. 

All looks good to me. Amazing work @nosegraze!

**Comment by mintplugins** [comment]
I also ran as many of the unit tests relating to this as I could find. Unfortunately the unit test situation needs some love as well, with many failing, but those are unrelated to anything here. I wonder if that's something we should tackle next.
