### ISSUE TITLE
3.0 - First element is styled differently when viewing extensions in wp-admin

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#7481]
### Expected behavior
I expect all elements to by styled the same when viewing extensions in wp-admin.

### Actual behavior
The first element is styled differently, and the text is a bit difficult to read. 

<img width="1132" alt="Screen Shot 2019-11-27 at 3 29 52 PM" src="https://user-images.githubusercontent.com/1638128/69757469-144bcf80-112b-11ea-9435-4875214ee822.png">

### Steps to reproduce the behavior
1) View the extensions page under "Dashboard" > "Downloads" > "Extensions".
2) Notice the first one has a different style.

### Information (if a specific version is affected):
EDD Version (or branch): release/3.0

This appears to have come into effect here:
https://github.com/easydigitaldownloads/easy-digital-downloads/commit/624c3536ad258c3cc3d907666598eb10d06fe298

**Comment by cklosowski** [comment]
I'm closing this as @SDavisMedia and I are in the process of working on a revamped version of this screen that better displays both the Passes and the Jilt integration.
