### ISSUE TITLE
3.0 - Reports that get start & end dates from Reports\get_filter_value() may use incorrect ranges

### ISSUE THREAD

**Issue by nosegraze** [easydigitaldownloads/easy-digital-downloads#7482]
### Expected behavior
When I visit reports and have a date range set that I set days/weeks/months ago, I expect the reports to use dates that are determined based on today. So if it says "last 30 days" and today is 29 November, I expect the data to be shown from 30 October - 29 November.

### Actual behavior
The date range is not always relative to today. The "Tax Collected by Location" may be using a start/end date that was calculated days/weeks/etc. ago. For example, today is 29 November 2019, yet look at the ranges being used:

![Screenshot from 2019-11-29 13-50-42](https://user-images.githubusercontent.com/6324272/69873092-4e45de80-12af-11ea-9cc8-8c5bfb596916.png)

It's using the last 30 days, relative to November 17th, which is when I first saved the date filter.

### Steps to reproduce the behavior
1) Set a _relative_ date filter, like "last 30 days".
2) Wait a day or two.
3) Check the query being run to see that it's using start/end dates relative to when you saved the filter, rather than relative to today.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0

WordPress Version: 5.3

Any other relevant information:

This problem is caused by actually saving the calculated `from` and `to` dates in `\EDD\Reports\set_filter_value`, which saves the information in a transient that does not have an expiration date. So it's saved possibly forever, unless the range is changed and overwritten with new dates.

I have noticed that not all reports actually use the `from` and `to` dates from `EDD\Reports\get_filter_value` so not all reports have this issue. For example, it looks like the Stats class just takes in a range (like `last_30_days`) then dynamically builds the start and end dates on the fly: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/class-stats.php#L2751-L2834 So this does not have any caching issues. But at least some reports that do not use this class are using cached start and end dates when they shouldn't be.

**Comment by mintplugins** [comment]
@nosegraze Just curious, does this happen on https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7016 as well?

**Comment by mintplugins** [comment]
Ah yup it's still pulling from that same transient.

**Comment by nosegraze** [comment]
PR: #7534

I have my date range set to last 30 days. I manually edited the transient to change the start date to 2018-12-24 and end date to 2019-01-23. Note the _years_ in the `From` / `To` columns in the two comparisons below:

### release/3.0

![Screenshot from 2020-01-23 13-29-32](https://user-images.githubusercontent.com/6324272/72988567-671ccd00-3de4-11ea-9283-a378b16dbeb9.png)

### issue/7482

![Screenshot from 2020-01-23 13-29-57](https://user-images.githubusercontent.com/6324272/72988604-78fe7000-3de4-11ea-991c-6840c4154062.png)
