### ISSUE TITLE
Remove Forced Clientside Form Validation When Applying a Discount

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/easy-digital-downloads#7487]
## Bug Report

Previously https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4325
Previously https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4645

### Expected behavior

When applying a discount in the Checkout, other checkout inputs should not be modified.

### Actual behavior

The inputs are marked `required`

---

After a discount is applied if the resulting price is not $0.00 then the checkout form forces certain inputs to be `required` before submitting the form (via HTML5 browser validation). This is done to "undo" any changes that would be made if the price did get to $0.00 which allows the purchase to be made without requiring those inputs.

### Steps to reproduce the behavior
1) Enable EDD Stripe + saved cards. **Disable billing addresses**.
2) Make a purchase.
3) Create another cart and apply a discount that does not result in the cart price being $0.00
4) Checkout with an existing saved card

Observe the `"card_name" is not focusable` error in the console.

Any other relevant information:

While this is currently specific to the Saved Cards feature in Stripe, I am opening a core issue because the way the inputs are targetted in core do not create an easy solution to prevent this behavior in the extension, and it could possibly affect other extensions in the future.

~~The [selectors used](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/assets/js/edd-checkout-global.js#L177) in core to find inputs would require removing `.edd-input` on the [custom card form](https://github.com/easydigitaldownloads/edd-stripe/blob/master/includes/template-functions.php#L96) in the extension which currently provides help with auto styling the Stripe Elements input.~~ 

See: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7487#issuecomment-737520495

**Comment by spencerfinnell** [comment]
After discussion with @mintplugins we have decided we are going to fix this in core by tracking the required state of inputs based on their original properties vs. the broad selectors used currently.

**Comment by dgoldak** [comment]
Noting that this just happened on our own site for the 2nd time that I'm aware of: https://secure.helpscout.net/conversation/1221630665/159695

**Comment by nosilver4u** [comment]
We are also waiting on this for ewww.io so we can begin offering a new discount to our customers. Looking forward to a fix!

**Comment by spencerfinnell** [comment]
This is actually a much simpler fix than I originally thought. The issue is in this "logic":

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/assets/js/edd-checkout-global.js#L187

The bug appears when _any gateway_ disables the `.card-address-2` input. For Stripe this is any address setting besides "Full Address".

The code is trying to exclude that field from being marked as required but instead is marking all fields require if that particular field _doesn't_ exist.

```js
if (!inputs.is('.card-address-2')) {
	inputs.attr('required','required');
}
```

Should be something like:

```js
inputs.each( function( input ) {
  input.prop( 'required', ! input.hasClass( '.card-address-2' ) );
} );
```

It's still rigid but it should behave as intenteded.

A workaround now is to do a hard refresh of the Checkout when a discount is applied: https://gist.github.com/spencerfinnell/55650e36f57f9238956278d6bd71ce3a
