### ISSUE TITLE
Access to download update date

### ISSUE THREAD

**Issue by mohammadr3z** [easydigitaldownloads/easy-digital-downloads#7490]
Hi
How do I set the post update date in the Downloads section?
Attached in the image

http://prntscr.com/q7x956

**Comment by mintplugins** [comment]
Hey there,

This Github repo is actually not for customer or user support. Sorry about that!

To get some free help from volunteers for the free product, open a support ticket on the forums here:
https://wordpress.org/support/plugin/easy-digital-downloads/

For support for the paid extensions, open a ticket on the website here:
https://easydigitaldownloads.com/support/
