### ISSUE TITLE
Easy Digital Downloads needs to complete a database upgrade that was previously started, click here to resume the upgrade.

### ISSUE THREAD

**Issue by enowtech** [easydigitaldownloads/easy-digital-downloads#7494]
Easy Digital Downloads needs to complete a database upgrade that was previously started, click here to resume the upgrade.

Each time the client clicks on to continue it, reloads to the wordpress dashboard with same message.

**Comment by mintplugins** [comment]
@enowtech This github repository is actually not for user support, sorry about that. Please reach out to the Easy Digital Downloads support team over here:

https://easydigitaldownloads.com/support
