### ISSUE TITLE
3.0: Admin notices improperly positioned

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#7495]
On 3.0, the positioning of the tracking opt-in notice is wonky:
<img width="1345" alt="Screen Shot 2019-12-17 at 1 07 29 PM" src="https://user-images.githubusercontent.com/1034109/71026179-47500600-20ce-11ea-95e0-e375c758d734.png">

**Comment by pippinsplugins** [comment]
Actually it appears to be all notices

**Comment by pippinsplugins** [comment]
Problem is only when on our own admin screens. The rest of the dashboard shows the notices properly.
<img width="1107" alt="Screen Shot 2019-12-17 at 1 11 39 PM" src="https://user-images.githubusercontent.com/1034109/71026409-d1986a00-20ce-11ea-9f94-393e0b406a0e.png">
![Uploading Screen Shot 2019-12-17 at 1.11.43 PM.png…]()

**Comment by nosegraze** [comment]
I think the JS just needs rebuilding, if you'd like to confirm? I was able to reproduce the issue on `release/3.0` but after running `npm run dev` or `npm run build` the problem went away.

**Comment by pippinsplugins** [comment]
I get a syntax error when doing that:
```
> cross-env NODE_ENV=default webpack --watch

/Users/pippin/Sites/edd/wp-content/plugins/easy-digital-downloads/node_modules/cross-env/dist/index.js:42
    });
    ^
SyntaxError: Unexpected token }
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/pippin/Sites/edd/wp-content/plugins/easy-digital-downloads/node_modules/cross-env/dist/bin/cross-env.js:4:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

npm ERR! Darwin 18.7.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! easy-digital-downloads@2.9.20 dev: `cross-env NODE_ENV=default webpack --watch`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the easy-digital-downloads@2.9.20 dev script 'cross-env NODE_ENV=default webpack --watch'.
npm ERR! This is most likely a problem with the easy-digital-downloads package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=default webpack --watch
npm ERR! You can get their info via:
npm ERR!     npm owner ls easy-digital-downloads
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/pippin/Sites/edd/wp-content/plugins/easy-digital-downloads/npm-debug.log
```

Sorry, webpack is still pretty foreign to me :(

**Comment by spencerfinnell** [comment]
@pippinsplugins Try installing the latest version of `node` and `npm:` https://stackoverflow.com/questions/47730815/cross-env-dist-index-js42-unexpected-token (try without `sudo` first)

**Comment by spencerfinnell** [comment]
@pippinsplugins #7463 makes the package list a lot simpler as well which might help you.

I have confirmed that the notice placement does appear correctly after running `npm run build` or `npm run dev`.

**Comment by pippinsplugins** [comment]
Thanks.

Closing as invalid.
