### ISSUE TITLE
3.0: Notice: Undefined index: status

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#7497]
## Bug Report

On a brand new install, I'm seeing the following notice displayed on the order details screen after completing a purchase:

Notice: Undefined index: status in /Users/pippin/Sites/edd/wp-content/plugins/easy-digital-downloads/includes/misc-functions.php on line 1589

<img width="1826" alt="Screen Shot 2019-12-17 at 2 15 56 PM" src="https://user-images.githubusercontent.com/1034109/71030790-c269ea00-20d7-11ea-9fe0-9068d44de03b.png">

### Steps to reproduce the behavior
1) On `release/3.0` make a purchase
2) Go to the Edit Order screen
3) The notice is shown just above the Order Adjustments section

### Information (if a specific version is affected):
PHP Version: 7.0.15

EDD Version (or branch): release/3.0

WordPress Version: latest

**Comment by nosegraze** [comment]
Looks like it only happens if you have an order adjustment, so having an order with a discount is also required in the steps.

**Comment by nosegraze** [comment]
PR: #7498
