### ISSUE TITLE
3.0 - edd_get_component_interface() with "schema" as the interface argument returns false

### ISSUE THREAD

**Issue by nosegraze** [easydigitaldownloads/easy-digital-downloads#7499]
### Expected behavior
When I run `edd_get_component_interface( 'adjustment', 'schema' )` I expect to have the registered adjustment schema returned.

### Actual behavior
When I run `edd_get_component_interface( 'adjustment', 'schema' )`, I get `false` returned.

### Steps to reproduce the behavior
Run `edd_get_component_interface( 'adjustment', 'schema' )` in your console.

This issue was triggered here while testing if you want a real-life case: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7161#issuecomment-567074582

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0

WordPress Version:

Any other relevant information:

I think this is caused by the schema class names being incorrect in `edd_setup_components()`.

Example:

```php
edd_register_component( 'adjustment', array(
	'schema' => '\\EDD\\Database\\Schema\\Adjustments',
	'table'  => '\\EDD\\Database\\Tables\\Adjustments',
	'meta'   => '\\EDD\\Database\\Tables\\Adjustment_Meta',
	'query'  => '\\EDD\\Database\\Queries\\Adjustment',
	'object' => '\\EDD\\Adjustments\\Adjustment'
) );
```

`'\\EDD\\Database\\Schema\\Adjustments',` is incorrect. It should be `'\\EDD\\Database\\Schemas\\Adjustments',` plural `Schemas`.

**Comment by nosegraze** [comment]
PR: #7500

**Comment by pippinsplugins** [comment]
Bug and fix confirmed. Merged.
