### ISSUE TITLE
3.0 - Use specific return types in PHP DocBlocks

### ISSUE THREAD

**Issue by nosegraze** [easydigitaldownloads/easy-digital-downloads#7501]
Vague return types are driving me nuts in my IDE. They break auto complete and make it hard to jump to a method that's being used, etc.

Just as one example:

```php
/**
 * Get an EDD Component object
 *
 * @since 3.0
 * @param string $name
 *
 * @return mixed False if not exists, EDD_Component if exists
 */
function edd_get_component( $name = '' ) {
	$name = sanitize_key( $name );

	// Return component if exists, or false
	return isset( EDD()->components[ $name ] )
		? EDD()->components[ $name ]
		: false;
}
```

According to the comments, this very clearly returns an instance of `EDD_Component` or `false`, but the return type is just `@return mixed`. Instead, this should be corrected to `@return EDD_Component|false`. We should only use `mixed` if we truly have no idea what it is (example: a meta value).

This is just one example but I know I've seen others.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0

WordPress Version:

Any other relevant information:

I'm filing this under 3.0 because I think it's just a lot of the new 3.0 functions that are affected.

**Comment by cklosowski** [comment]
Would you mind going ahead and owning this one?

**Comment by cklosowski** [comment]
@nosegraze ^^ sorry forgot to ping you

**Comment by nosegraze** [comment]
PR: #7533
