### ISSUE TITLE
Critical Error in Google Search Console

### ISSUE THREAD

**Issue by ttaylor100** [easydigitaldownloads/easy-digital-downloads#7506]
### Expected behavior
All information is entered into EDD pages. Expected indexing of the EDD items/pages to be indexable. 

### Actual behavior
Google returns this information:

Search Console has identified that your site is affected by 10 Products issues:

Top Errors

Errors can prevent your page or feature from appearing in Search results. The following errors were found on your site:

Missing field "name"

Top Warnings

Warnings are suggestions for improvement. Some warnings can affect your appearance on Search; some might be reclassified as errors in the future. The following warnings were found on your site:

Missing field "aggregateRating"

Missing field "sku"

Missing field "review"

Missing field "image"

No global identifier provided (e.g., gtin, mpn, isbn)

We recommend that you fix these issues when possible to enable the best experience and **coverage in Google Search.**

Page Google references in the error report: https://davegardner.biz/downloads/100-insights-actionable-ideas-for-business-growth-and-sustainability/

EDD Version (or branch): 2.9.20

WordPress Version: 5.3.2

Any other relevant information: Theme: Hestia Version: 2.5.6

**Comment by cklosowski** [comment]
We are moving over to using the JSON-LD system in EDD 3.0. We'll handle all issues related to Search Console warnings over here: #7571
