### ISSUE TITLE
Download Product Earnings report incorrect when item-specific fees are present

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#7507]
### Expected behavior
When viewing the earnings report for a single product, the revenue numbers should represent the money earned after fees are collected/deducted.

For example, if a $10 product is sold with a negative 50% fee (a discount), the earnings should be reported as $5 on the graph.

### Actual behavior
The current behavior is that fees are getting deducted from the actual earnings _twice_ when viewing a report.

For example, a $10 product with a negative 50% fee is getting reported as $0.00.

This is happening due to the changes made for #6859. Previously, the `$item['price']` key was the _pre fees_ amount, but after #6859 was merged, `$item['price']` became (correctly) the _post fees_ amount, but we forgot to adjust reports accordingly.

### Steps to reproduce the behavior
1) Set up a $10 product
2) Using the Discounts Pro extension, set up a 50% cart discount
3) Purchase the product
4) Go to Downloads, locate your product, click on the Earnings column value
5). The earnings will show as $0.00 but should show $5.00

To resolve this, we have a few options:

1. In the `get_earnings()` method of `EDD_Payment_Stats`, we can adjust the base amount off of `item_price` instead of `price`. This corrects the problem but has the unfortunate side effect of making the earnings data incorrect for any products sold with item fees prior to the #6859 fix being applied.

2. We can remove the item-specific fees from the calculation in the `get_earnings()` method of `EDD_Payment_Stats`. This has a similar side effect as option 1 because the `price` key is incorrect for products sold prior to that fix being applied.

3. We could do one of the above options combined with a date check to adjust the logic used when payments were placed before `DECEMBER 3, 2018`, which is the date that our fix for #6859 was released.

I have not yet verified it, but this may only be a problem with _negative_ fees, per the information in #7281.

Related: #3763, #6859, #7281

**Comment by pippinsplugins** [comment]
Working PR submitted.

Everything appears to be working to me but more extensive testing is needed, especially with both negative and positive fees.

**Comment by pippinsplugins** [comment]
I've dug a little deeper and found that the changes in #6859 also impacted the following:
- The amount that earnings are increased by and stored in `_edd_download_earnings` when a purchase is completed
- The recount stats tool for a single product
- The recount stats tool for all products

I've updated the PR to also fix those three items.

**Comment by mintplugins** [comment]
Replicated on `master` and confirmed fixed on `issue/7507`. The only weird thing is that when viewing sales for a single product, the "Item Amount" column shows the pre-fee amount ($10), which could throw some people off if they are manually adding up those columns. But the amounts reported are correct, which is the scope of this issue. 

<img width="1268" alt="Screen Shot 2020-01-03 at 11 04 18 AM" src="https://user-images.githubusercontent.com/1638128/71734118-26e7b180-2e19-11ea-9d1f-486b25668c1b.png">

<img width="1262" alt="Screen Shot 2020-01-03 at 11 07 16 AM" src="https://user-images.githubusercontent.com/1638128/71734181-55fe2300-2e19-11ea-95a3-81fadfb55864.png">

👍

**Comment by pippinsplugins** [comment]
@mintplugins Was Log ID 12 a sale made on `master` or on `issue/7507`?

**Comment by mintplugins** [comment]
@pippinsplugins It was actually made on that date, likely on master. I happened to have a really old purchase in my discounts pro local site.

**Comment by pippinsplugins** [comment]
Oh, lol, I completely missed the purchase date column.

We could fix it with an upgrade routine that runs through and finds every payment record with negative item-specific fees and corrects those amounts.

**Comment by cklosowski** [comment]
I feel like we should avoid the upgrade routine at this point, and let 3.0 shake out the details here.

**Comment by cklosowski** [comment]
Tested this and it works fine, a recalculation of the product also updates the product specific stats.Going to get this merged, and we'll test this out on our site.
