### ISSUE TITLE
3.0 - Orders - Reduce Steps for Assigning Customers

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/easy-digital-downloads#7520]
## Enhancement Request

Some previously: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7052#issuecomment-458265857

### Explain your enhancement (please be detailed)

Show a searchable dropdown of Customers by default when creating or editing an order.

### Justification or use case

When manually creating a new Order a Customer is required to be associated with it before it can be saved. Currently you can either assign an existing customer or create a new customer.

Since we know one of these actions has to be taken we can help users realize a Customer is required and reduce the number of clicks it takes to attach a Customer by showing the searchable dropdown automatically. This will likely cover the majority of use cases and hides the (I think) less used option under a toggle.

This also allows more validation to focus the dropdown if attempting to save the order without assigning a Customer.

<img width="799" alt="Screen Shot 2020-01-21 at 3 49 09 PM" src="https://user-images.githubusercontent.com/491124/72842532-91488080-3c66-11ea-9255-c22a635b9a59.png">
<img width="796" alt="Screen Shot 2020-01-21 at 3 49 45 PM" src="https://user-images.githubusercontent.com/491124/72842533-91488080-3c66-11ea-97b0-390452ed4bf9.png">

When selecting a Customer the information below the dropdown will automatically be updated.

The only thing I'm not 100% on is the `or`, but I think there needs to be some separation from the existing Customer search.

**Comment by spencerfinnell** [comment]
A few things left to wire up, but this feels nice:

![2020-02-04 15 01 15](https://user-images.githubusercontent.com/491124/73782006-45fe9980-475f-11ea-9881-fa808bbd287a.gif)

**Comment by spencerfinnell** [comment]
PR #7557

**Comment by pippinsplugins** [comment]
I really like this flow when creating a new order, but I'm not sure it works as well when viewing an existing order.

It feels a bit weird for the customer's name to be shown exclusively in a drop down menu when viewing an existing order. The existing UI in `release/3.0` feels more natural when viewing existing orders:
![image](https://user-images.githubusercontent.com/1034109/73998185-6fb5ed00-4926-11ea-825c-a4391ec41721.png)

**Comment by spencerfinnell** [comment]
@pippinsplugins I was thinking yesterday that the larger name should be restored at least. I'll play with making sure it's clear switching a Customer is still possible when editing an Order.

**Comment by spencerfinnell** [comment]
@pippinsplugins What about a more clear label above the Customer search?

![2020-02-10 09 28 04](https://user-images.githubusercontent.com/491124/74158264-c43bbf80-4be7-11ea-83b4-b85f8c3b7981.gif)
<img width="792" alt="Screen Shot 2020-02-10 at 9 28 24 AM" src="https://user-images.githubusercontent.com/491124/74158269-c69e1980-4be7-11ea-938e-a97a49b68525.png">

**Comment by pippinsplugins** [comment]
@spencerfinnell That's much better. Let's proceed with that.

**Comment by spencerfinnell** [comment]
#7557 updated to match above screenshots.
