### ISSUE TITLE
3.0 - Orders - "Manually Enter Pricing" Adjustments

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/easy-digital-downloads#7522]
### Explain your enhancement (please be detailed)

- Move "Add Item" below the list of added items.
- Rename "Add Item" to "Add $singular_label"
- Always show Download selector
- Move "Override Amounts" to the top of the item list.
- Change "Override Amounts" button to a switch

### Justification or use case

The current "Override Amounts" button (previously https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6789) is in the "Order Amounts" box. However when this button is clicked the thing that actually changes is in a different box.

<img width="1095" alt="Screen Shot 2020-01-22 at 4 06 48 PM" src="https://user-images.githubusercontent.com/491124/72934233-3e87cb00-3d31-11ea-94a8-efb36eb2813e.png">

The switch might need to be shrunk slightly.

Moving and renaming the button to a switch to the area where items are actually adjusted helps provide clarity to what is actually happening.

Always showing the Download dropdown and "Add Download" button below the list is also a similar UI to the tax rate list.

Adjustments would be _adjusted_ similarly.

**Comment by spencerfinnell** [comment]
PR #7550 implements:

<img width="806" alt="Screen Shot 2020-02-04 at 10 14 01 AM" src="https://user-images.githubusercontent.com/491124/73758032-1ab48400-4738-11ea-9291-cbeed44e3927.png">
<img width="812" alt="Screen Shot 2020-02-04 at 10 14 18 AM" src="https://user-images.githubusercontent.com/491124/73758033-1ab48400-4738-11ea-9b1e-300286607799.png">

**Comment by pippinsplugins** [comment]
@spencerfinnell This is a great improvement!

Can we have the select field pre-populated with 15-20 downloads? Right now you have to click on the select menu then enter a search phrase before any products show up. That seems like an extra step.

**Comment by spencerfinnell** [comment]
@pippinsplugins Good idea! I set a limit in `issue/7522` but a follow up is required in #7551 for it to take effect fully.
