### ISSUE TITLE
3.0 - Orders - Rename "Sales" Tab to "Orders"

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/easy-digital-downloads#7527]
### Explain your enhancement (please be detailed)

Rename "Sales" tab to "Orders".

### Justification or use case

At first I thought the "Sales" tab was just for non-refunded orders but since both `refund` and `sale` order types appear in the list the tab should be named to reflect the display of both order types.

**Comment by spencerfinnell** [comment]
I guess `refund` order types aren't being shown in the list since a refunded Order is still an `order` -- but that further enforces that the tab should reflect that just Orders are being shown.

**Comment by spencerfinnell** [comment]
After working with `sale` and `refund` order types from the development side, I get the reasoning for the tab names more. I do think there may still be confusion from users though.

If "Sales" is kept then I think the menu item should be renamed to "Sales".  If you click "Downloads" in the menu you are taken to a "Downloads" tab. If you click "Customers" you are taken to a "Customers" tab, etc. These pages all have secondary views but the menu item you click on still takes you to a tab named the same as the menu item you clicked.

**Comment by pippinsplugins** [comment]
I prefer `Orders`.

`sale` makes sense in a development sense but not so much as in a user context because "sale" could very easily be confused with "discount".

**Comment by spencerfinnell** [comment]
@pippinsplugins So menu item and tab as "Orders"?

Current:
<img width="519" alt="Screen Shot 2020-02-07 at 10 24 12 AM" src="https://user-images.githubusercontent.com/491124/74041632-040a6900-4994-11ea-9bef-37d19b68f3bc.png">

Both:
<img width="631" alt="Screen Shot 2020-02-07 at 10 24 37 AM" src="https://user-images.githubusercontent.com/491124/74041660-11275800-4994-11ea-9565-cb31ac988540.png">

Both as "Orders" works for me.

**Comment by pippinsplugins** [comment]
Yes, the tab and the item under `Downloads` should both be `Orders` in my opinion.
