### ISSUE TITLE
3.0 - Orders - Key Not Generated for Manually Created Order

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/easy-digital-downloads#7529]
### Expected behavior

When manually creating an Order and leaving the "Key" field blank, a key should be generated.

### Actual behavior

No key is generated.

### Steps to reproduce the behavior
1) Switch to `release/3.0`
2) Manually create a new order.

When a Refund is created a key is automatically generated and attached to that record.

**Comment by LisaCee** [comment]
PR #7988
