### ISSUE TITLE
Link to WordPress Privacy Settings Incorrect in 5.3+

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/easy-digital-downloads#7531]
### Expected behavior
When I click "Set your Privacy Policy here" when editing the EDD Privacy Policy settings in "Settings > Privacy > Privacy Policy".

### Actual behavior

In WordPress 5.3+ linking to `privacy.php` links to the core About page's privacy. 

### Steps to reproduce the behavior
1) Install WordPress 5.3+
2) Click "Set your Privacy Policy here"

### Information (if a specific version is affected):
WordPress Version: 5.3

Any other relevant information:

If 5.3 or above the link should be to `options-privacy.php`

https://core.trac.wordpress.org/ticket/43895

**Comment by spencerfinnell** [comment]
Adding to this, since we support back to `4.4`, the link will go nowhere if people are using `4.4-4.9.6` and won't have the ability to set a page manually. 

Previously https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6569

**Comment by cklosowski** [comment]
@spencerfinnell going to set this for 3.0 where we're likely jumping the minimum supported WP version to 4.9, which drastically lowers our footprint of people that aren't supported by `options-privacy.php`
