### ISSUE TITLE
3.0 - Manual SL renewals not working due to cart_details => cart/cart item meta routing

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#7545]
### Expected behavior

When I manually renew a SL license, I expect the existing license to be renewed.

### Actual behavior

When I manually renew an existing license key, I get a whole new license key instead of the existing one being renewed.

### Steps to reproduce the behavior
1) Purchase a license key (no recurring).
2) Manually renew that license key.
3) You will see that you've now been issued an entirely new license key as if this was a new purchase instead of a renewal.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0

WordPress Version:

Any other relevant information:

Split off from this issue here: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7399#issuecomment-556055500

This is an issue with `$payment->cart_details` not correctly routing to the new order meta table, where the flags are being set.

**Comment by nosegraze** [comment]
Maybe this is related? https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7289

(Not sure because it's been a while since I originally looked into this.)

**Comment by nosegraze** [comment]
Just making some notes to myself because I'm really feeling like I'll only get short windows of time to look into this and want to remember everything I find...

I tried to renew an existing license key and the following information was added to `edd_order_itemmeta`, which I believe is exactly what we want:

`_option_is_renewal` = `1`
`_option_license_id` = `6`
`_option_license_key` = {license key I'm renewing}

So I think the meta is getting set exactly how we want; the issue is that "reading it" some time later isn't correctly routing it to order item meta.

`edd_sl_set_renewal_flag()` looks for `$payment->cart_details[]['item_number']['options']['is_renewal']` and that no longer exists.

**Comment by nosegraze** [comment]
WIP PR: https://github.com/easydigitaldownloads/easy-digital-downloads/pull/7555

So far I've tackled the issue of `$payment->cart_details[]['item_number']['options']` not being retrievable.

However, there's a new problem.

EDD SL saves a renewal flag:

```php
add_post_meta( $payment->ID, '_edd_sl_is_renewal', '1', true );
```

Then it checks for it later:

```php
$is_upgrade = $payment->get_meta( '_edd_sl_is_renewal' );
```

(lol that variable name is wrong)

So the issue here is that SL is adding meta using `add_post_meta()` and _this is not routing to order meta_. Therefore it's literally being saved in `wp_postmeta`. Then when `$payment->get_meta()` checks for it later, it's properly checking in order meta, and it doesn't exist there.

The reason `add_post_meta()` isn't porting it over to order meta is that only a whitelist of meta keys is being routed over in \EDD\Compat\Payment`:

```php
$meta_keys = array(
	'_edd_payment_purchase_key',
	'_edd_payment_transaction_id',
	'_edd_payment_meta',
	'_edd_completed_date',
	'_edd_payment_gateway',
	'_edd_payment_user_id',
	'_edd_payment_user_email',
	'_edd_payment_user_ip',
	'_edd_payment_mode',
	'_edd_payment_tax_rate',
	'_edd_payment_customer_id',
	'_edd_payment_total',
	'_edd_payment_tax',
	'_edd_payment_number',
);

// Bail early of not a back-compat key
if ( ! in_array( $meta_key, $meta_keys, true ) ) {
	return $check;
}
```

@cklosowski Do you know if there's a reason for this? I'd personally route over all meta being saved to a post ID that's a `edd_payment` post type.

**Comment by pippinsplugins** [comment]
Chiming in. We should white list _every_ known meta key that's ever been used for payments, including ones from every extension we've build and every extension we know about. And we should include a filter that allows extension developers to register their own meta keys to port.

**Comment by cklosowski** [comment]
@nosegraze This is very simliar to what the register meta does in WP core for custom post types.

@pippinsplugins I think that's unmaintainable for 3.0...but I like where it's going. I think we should do the following:
1. Add a filter here to allow adding custom meta keys
2. If the key is not found, throw a `__doing_it_wrong()` telling them to register their meta by 3.1.
3. Until 3.1 continue to store the custom meta.

**Comment by nosegraze** [comment]
We also need to double check what we might be migrating in the 3.0 migration. We don't want to end up in a situation where we're migrating all meta, but then only porting over the get_meta() calls for our whitelist, or vice versa. Everything we migrate over should be caught in the add/update/get meta calls.

**Comment by pippinsplugins** [comment]
At minimum we can register all of our own keys from our extensions.

**Comment by cklosowski** [comment]
@pippinsplugins That I would be hesitant on as well, I think we should add the filter, and pre-release versions that register the meta, to give people an example of doing it right. I'm not keen on the idea of a registered meta existing form an extension within EDD core in this case.

**Comment by pippinsplugins** [comment]
So register the keys in our extensions instead of core? I'm fine with that. In the end, as long as they are registered somewhere.

**Comment by cklosowski** [comment]
Yes, I'd prefer we add them in prior to 3.0 (since the filter isn't used until 3.0 launches, it'll be 'dead' code) but then we're ready to go upon release.

**Comment by nosegraze** [comment]
Updated PR. Pretty sure it's finalized now.

SL license renewals are now working with this PR and SL branch `issue/1557`.

SL now adds the following keys to `order_itemmeta`:

_option_is_renewal
_option_license_id
_option_license_key

And the following to `ordermeta`:

_edd_sl_is_renewal
_edd_sl_renewal_key

This keeps things working exactly the same in EDD 3.0 as they do in 2.x. The ordermeta could be dropped now I think, but that would require updates to SL itself, which can be done separately.

**Comment by spencerfinnell** [comment]
Why do `add_post_meta()`, `get_post_meta()`, and `update_post_meta()` compat filters have whitelists but accessing `( new EDD_Payment( 123 ) )->get_meta()` does not?

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/payments/class-edd-payment.php#L2007

Couldn't the direct function calls be routed to `EDD_Payment` which has its own compatibility handling?

**Comment by cklosowski** [comment]
@spencerfinnell that was because WP Core was not allowing us to update custom post type meta without them being registered (without throwing a massive number of notices/warnings).

Since moving to our custom tables. I don't see the need to route those through if we're going to ditch them in the near future by moving to our custom tables...or am I misunderstanding the question/

**Comment by spencerfinnell** [comment]
@cklosowski I guess I'm unclear how the filter in #7555 actually registers any custom meta that would change the compatibility already present in `EDD_Payment`.

I think the idea would be that:

```php
var_dump( get_post_meta( 123, 'foo', true ) );
```

Would be have the same compatibility as:

```php
$payment = edd_get_payment( 123 );
var_dump( $payment->get_meta( 'foo', true );
```

If that is the case it seems like we could just call those `EDD_Payment` methods which contain much more backwards compatibility logic than the filtering of `get|add|update_post_meta()`.

It seems to me like `add|update_post_meta()` is mostly doing that already but is just limiting it to a certain set of keys which are already properly dealt with in `EDD_Payment::update_meta()`

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/7de9c4dee4a8ad86a8e9b309d5603492b0559147/includes/compat/class-payment.php#L261-L267

**Comment by ashleyfae** [comment]
> Why do `add_post_meta()`, `get_post_meta()`, and `update_post_meta()` compat filters have whitelists but accessing `( new EDD_Payment( 123 ) )->add|get|update_meta()` does not?
> 
> https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/payments/class-edd-payment.php#L2007
> 
> Couldn't the direct function calls be routed to `EDD_Payment` which has its own compatibility handling?

I think the reason we need a whitelist in the post meta calls is because post meta is way more overarching. With `EDD_Payment()->add|get|update_meta()` we know the person is adding meta to an EDD payment so we know exactly what their intentions are.

But with post meta, we just have a key and an object ID. We don't know for sure what post type they're trying to work with. Having a whitelist of keys allows us to know for sure they're updating meta for an EDD payment as opposed to some random post or whatever. It's possible that eventually a new order ID will share the same ID as some completely unrelated post object so it's not reliable to just run this:

```php
// Bail if order does not exist
$order = edd_get_order( $object_id );
if ( empty( $order ) ) {
	return $value;
}
```

Because you could have an order with ID 12345 and a blog post with order 12345, which would then result in getting/updating meta on order 12345 when actually someone was aiming for the blog post with that same ID.

(If I am missing an obvious solution here for ensuring the call is for an EDD payment then I'm all for it, but that's the potential problem I see right now.)

**Comment by spencerfinnell** [comment]
Unfortunately I think that makes sense. 😠

**Comment by cklosowski** [comment]
We'll need to make sure we call this out in a blog post and maybe in documentation. We can keep the filter as a 'bandaid' for customers, and then tell them that they should update to using the `add/get/update` methods of the `EDD_Order` class.

**Comment by ashleyfae** [comment]
@robincornett Can you test this branch with Software Licensing master branch? Primarily focus on renewals and upgrades, because those are directly related to what we've fixed in this issue. Also feel free to test anything else you can think of.

Anything that works, check off here: https://github.com/easydigitaldownloads/easy-digital-downloads/projects/10#card-32374765

If there's something that doesn't work but does work in master, make a note of it and we can see if we need to create new issues for them.

**Comment by robincornett** [comment]
I've tested with the master SL branch and upgrades and renewals, both by the customer and the admin, are working (recurring still pending).

I did encounter a weird issue where a license key is showing as active and expired, but cannot be renewed. When I view the license details, I see two related payments. The first one was refunded; the second one was not. When I look at the license meta, the `payment_id` in the database is for the first/refunded payment. I have no idea how I managed to get a second payment on this key--did it about three weeks ago. But somehow the key is showing in the front end list of keys. When I click the "renew now" link, it is not added to the cart--no message in the site, but the URL is:

```
https://edd30.local/checkout/?edd-sl-error=payment_not_complete&message=The+purchase+record+for+this+license+is+not+marked+as+complete
```

This may be a one-off issue that I inadvertently created while testing something at the beginning of April, but noting here in case it's not.

**Comment by ashleyfae** [comment]
Just leaving this open for the docs reminder.

**Comment by cklosowski** [comment]
Docs should be about the new way to register and save cart meta.

**Comment by ashleyfae** [comment]
See https://3.basecamp.com/4226849/buckets/12407027/todolists/3181435287
