### ISSUE TITLE
implode(): Passing glue string after array is deprecated

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/easy-digital-downloads#7556]
### Expected behavior

When viewing a Download there should be no PHP errors.

### Actual behavior

In PHP 7.4 there is a deprecation notice regarding `implode()` usage.

### Steps to reproduce the behavior
1) Use PHP 7.4
2) View a Download.

### Information (if a specific version is affected):
PHP Version: 7.4

EDD Version (or branch): master

Any other relevant information:

https://www.php.net/manual/en/function.implode.php

---

Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /Users/spencerfinnell/dev/edd3/wp-content/plugins/easy-digital-downloads/includes/template-functions.php on line 282

We should try to audit any other usage.

**Comment by cklosowski** [comment]
@spencerfinnell I have this fixed in https://github.com/easydigitaldownloads/easy-digital-downloads/pull/7554/files#diff-978209e01c6c9e4491c170874c427461L281

**Comment by spencerfinnell** [comment]
@cklosowski Nice!

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/process-purchase.php#L114

Is missing a `$glue` parameter. It's defaulting to an empty string currently, but should be defined.

That's the only other one I see.

**Comment by cklosowski** [comment]
@spencerfinnell I'll go ahead and open up a new PR for that one.

**Comment by cklosowski** [comment]
Actually we do'nt do this in 3.0, so we can close this. In the current release branch for 3.0 we don't use the implode in that location for address info.

Closing.
