### ISSUE TITLE
3.0 - Downloads - Combine Refund Settings in "Download Settings"

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/easy-digital-downloads#7560]
### Explain your enhancement (please be detailed)

Combine the "Refundability" and "Refund Window" sections in the "Download Settings" metabox.

### Justification or use case

This metabox is already quite large, and each section having only one setting and including a tooltip creates quite a lot of repetition. 

I also think using the (what I believe to be) uncommon term "Refundability" alongside a dropdown containing only two options adds extra cognitive load. 

| Before | After |
| --- | --- |
|  <img width="292" alt="Screen Shot 2020-02-06 at 2 28 35 PM" src="https://user-images.githubusercontent.com/491124/73972014-01553880-48ee-11ea-86e6-60142f3fd5be.png"> | <img width="293" alt="Screen Shot 2020-02-06 at 2 30 36 PM" src="https://user-images.githubusercontent.com/491124/73972025-087c4680-48ee-11ea-8ce5-a9a4abb24481.png"> |

A single tooltip can be used to further explain the settings contained in the section, however I think there is less confusion with adjusted setting types.

---

Not a blocker by any means, so it doesn't necessarily need to be assigned to the 3.0 milestone yet.

**Comment by cklosowski** [comment]
I would say lets get this into 3.0 so that it all goes out seamlessly.

**Comment by spencerfinnell** [comment]
PR #7642

**Comment by spencerfinnell** [comment]
@ashleyfae What do you think about this for the default refundable state:

| Before | After |
| --- | --- |
| <img width="742" alt="Screen Shot 2020-03-19 at 11 29 31 AM" src="https://user-images.githubusercontent.com/491124/77084147-f1447480-69d4-11ea-8e18-06ad6453e0f3.png"> | 
<img width="749" alt="Screen Shot 2020-03-19 at 11 27 46 AM" src="https://user-images.githubusercontent.com/491124/77084167-f99caf80-69d4-11ea-996b-3e0bf1f2ed30.png"> |

**Comment by ashleyfae** [comment]
@spencerfinnell I like it!

**Comment by cklosowski** [comment]
Ok there is a weird case here when toggling these settings in tandem.

1. Set the store to `Refundable`
2. Override on a product by un-checking the box for `Refundable`
3. Re-enable the product to be `Refundable`
4. Set the store's status to 'Non-Refundable`
5. Go back to the download and see that the product is un-checked for the `Refundable` box.

Seems like the logic around [here](https://github.com/easydigitaldownloads/easy-digital-downloads/pull/7642/files#diff-5a826cd653ecb50541b5987b8ec010a2R948-R952) might be causing some unexpected behavior:

**Comment by spencerfinnell** [comment]
@cklosowski Switched it back to a dropdown that now allows for a true "blank" value to exist (which forces the global/default value).

<img width="300" alt="Screen Shot 2020-03-23 at 11 35 22 AM" src="https://user-images.githubusercontent.com/491124/77333933-85c31580-6cfa-11ea-9812-27024aa169f6.png">
<img width="316" alt="Screen Shot 2020-03-23 at 11 36 11 AM" src="https://user-images.githubusercontent.com/491124/77333934-865bac00-6cfa-11ea-8bb4-81c6e4a2c545.png">
