### ISSUE TITLE
3.0 - Discounts - Redeeming a Discount Resets Some Discount Settings

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/easy-digital-downloads#7576]
### Expected behavior

When a Customer redeems a Discount the Discount settings should remain the same.

### Actual behavior

Certain settings (such as Download requirements) are reset/removed.

### Steps to reproduce the behavior
1) Create a Discount with Download Requirements
2) Purchase a Download with the Discount applied.

### Information (if a specific version is affected):
EDD Version (or branch): `release/3.0`

**Comment by spencerfinnell** [comment]
This is likely related to another issue where "Apply discount only to selected Downloads." is checked but the discount is applying to all Order Items/Downloads.

**Comment by nosegraze** [comment]
PR: #7608
