### ISSUE TITLE
3.0 - Database version numbers are too long for 32-bit environments

### ISSUE THREAD

**Issue by nosegraze** [easydigitaldownloads/easy-digital-downloads#7579]
## Bug Report

The BerlinDB database version numbers (i.e. `201906030001`) are too long for 32-bit environments. They work fine in 64-bit, but not 32.

This problem was identified in RCP when we started using BerlinDB: https://github.com/restrictcontentpro/restrict-content-pro/issues/1922 I cut the format down to:

`{YYYY}{mm}{dd}{1}`
instead of
`{YYYY}{mm}{dd}{0001}`

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0

WordPress Version:

Any other relevant information: 32-bit

**Comment by cklosowski** [comment]
@nosegraze is there something we can do to make sure that we can programmatically update any current version/settings to match so that as we work through this we don’t have to manually modify or run anything?

**Comment by nosegraze** [comment]
@cklosowski I'll see what I can do...

**Comment by nosegraze** [comment]
PR: #7598

This will convert and update the stored version numbers automatically. If the stored version is 12 digits (old format) and larger than the table's defined version number then I convert it to the new format (9 digits) and update the saved version accordingly.
