### ISSUE TITLE
3.0 - Discounts - Amount type dropdown extends outside input field

### ISSUE THREAD

**Issue by nosegraze** [easydigitaldownloads/easy-digital-downloads#7580]
### Expected behavior

I expect the percentage/flat dropdown to not extend beyond the input field it sits on top of.

### Actual behavior

![Screenshot from 2020-02-12 15-39-13](https://user-images.githubusercontent.com/6324272/74350595-d5cec400-4dad-11ea-9142-fe8780bc64fd.png)

I zoomed in to more clearly see the problem. You can see that the grey background extends beyond the border of the input field, which makes it look odd. It should be fully contained within the bordered area.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0

WordPress Version:

Any other relevant information:

**Comment by spencerfinnell** [comment]
This is likely new in WordPress 5.3+

**Comment by spencerfinnell** [comment]
PR #7588 

<img width="462" alt="Screen Shot 2020-02-13 at 3 09 38 PM" src="https://user-images.githubusercontent.com/491124/74474260-2825e880-4e73-11ea-93e6-b11cad7e084f.png">
<img width="472" alt="Screen Shot 2020-02-13 at 3 10 14 PM" src="https://user-images.githubusercontent.com/491124/74474262-28be7f00-4e73-11ea-88c8-340d02e9d11b.png">
