### ISSUE TITLE
3.0 - Discounts - Saving a discount with no start/end date shows start & end dates as being today

### ISSUE THREAD

**Issue by nosegraze** [easydigitaldownloads/easy-digital-downloads#7581]
### Expected behavior

When I add (or edit) a discount and leave the start and end date fields blank, I expect them to still be blank when the page refreshes.

### Actual behavior

The start and end values are correctly saved in the database, but the UI prints out the start and end dates as being today.

Pre-save:

![Screenshot from 2020-02-12 15-56-22](https://user-images.githubusercontent.com/6324272/74352469-745c2480-4db0-11ea-8f94-5a029032be1d.png)

Post-save:

![Screenshot from 2020-02-12 15-56-36](https://user-images.githubusercontent.com/6324272/74352474-77efab80-4db0-11ea-86eb-f3ce9024ac1e.png)

Database:

![Screenshot from 2020-02-12 15-58-24](https://user-images.githubusercontent.com/6324272/74352500-84740400-4db0-11ea-8ac9-16c40fce5d39.png)

### Steps to reproduce the behavior
1) Add a new discount code.
2) Leave start and end dates blank.
3) Save.
4) When page refreshes, see incorrect dates displayed.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch):

WordPress Version: release/3.0

Any other relevant information:

**Comment by spencerfinnell** [comment]
PR #7587
