### ISSUE TITLE
Audit Use of "Chosen" Dropdowns

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/easy-digital-downloads#7583]
### Explain your enhancement (please be detailed)

Remove use of [`Chosen`](https://harvesthq.github.io/chosen/) `<select>` tags when not needed.

### Justification or use case

There are many instances of using Chosen in the admin area where the list of available options is limited and predefined. These smaller lists that do not need the ability to quickly filter them or search for dynamic results should use standard `<select>` fields.

Items with just two options should either be a checkbox or list of radio options.

Limiting Chosen usage improves accessibility (currently cannot access a Chosen dropdown with a keyboard) and reduces possible UI bugs/discrepancies with core style changes.

**Comment by spencerfinnell** [comment]
Once the number of items is down we should look at deprecating Chosen (which itself has been Deprecated https://github.com/harvesthq/chosen) and replacing it with a more maintained alternative, such as:

- https://github.com/jshjohnson/Choices
- https://github.com/woocommerce/selectwoo

Related https://github.com/easydigitaldownloads/easy-digital-downloads/issues/2758 https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4375

**Comment by cklosowski** [comment]
We’ll have to be congnisant of the fact that some of these lists might have filters on them, allowing them to eventually have more than a few options, so we need to be careful not to convert to a massive radio list if multiple extensions have hooked into that filter.

Overall I’m a :+1: for this though for sure.

**Comment by spencerfinnell** [comment]
Also, since Chosen doesn't transform `<select>` inputs/run at all on touch-enabled devices any of the fields that rely on AJAX search do not work on mobile devices.

**Comment by cklosowski** [comment]
That is a fair point @spencerfinnell.

**Comment by spencerfinnell** [comment]
Having a terrible time with my keyboard so I'm going to chunk this up so maybe we can get some in 3.0.

Removing some in settings via #7671

**Comment by spencerfinnell** [comment]
@cklosowski I’d like to keep this open as a tracking issue for smaller PRs. There are some more places that can still be removed.

**Comment by cklosowski** [comment]
No problem @spencerfinnell, thanks for the heads up.

**Comment by robincornett** [comment]
Just noting here that select fields using `chosen` are not accessible at all for keyboard users or for screen readers.

**Comment by ashleyfae** [comment]
@spencerfinnell Please close this issue if the changes in https://github.com/easydigitaldownloads/easy-digital-downloads/pull/7956 covered everything you had in mind. If not, we can leave this open.
