### ISSUE TITLE
3.0 - Discounts - Cart Not Respecting Discount Product Requirements

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/easy-digital-downloads#7593]
### Expected behavior

When a Discount is created with product requirements, those requirements should be respected when applying in the Checkout.

### Actual behavior

Setting "Apply discount only to selected Downloads" is not honored.

### Steps to reproduce the behavior
1) Create "Product A" for $100.
2) Create "Product B" for $100.
2) Create a 10% Discount that requires "Product A" and only applies to that product.
3) Create a 10% Discount that applies to all products.

### Information (if a specific version is affected):
EDD Version (or branch): `release/3.0`

Any other relevant information:

### `master`:

<img width="826" alt="Screen Shot 2020-02-20 at 3 18 08 PM" src="https://user-images.githubusercontent.com/491124/74975093-70ee1c00-53f4-11ea-8e1f-328ab3b1ec78.png">

```
Download B: ( $100 * .10 ) + ( $100 * .10 ) = $20
Download A: ( $100 * .10 ) = $10

$200 - $30 = $170
$170 * .10 = $17.00
✅$170 + $17 = $187
```

### `release/3.0`:

<img width="826" alt="Screen Shot 2020-02-20 at 3 19 36 PM" src="https://user-images.githubusercontent.com/491124/74975357-efe35480-53f4-11ea-919c-e659112ee914.png">

```
❌Download B: ( $100 * .10 ) + ( $100 * .10 ) = $20
Download A: ( $100 * .10 ) + ( $100 * .10 ) = $20

❌$200 - $40 = $160
❌$160 * .10 = $16.00
❌$160 + $16 = $176
```

These incorrect values follow through to the database.

**Comment by cklosowski** [comment]
@spencerfinnell wouldn't Download B's calculation be the one that's wrong? If we have a discount for All and a discount for Product A, then it should have 2 discounts, and Download B should only have one discount (the all discount)

**Comment by spencerfinnell** [comment]
@cklosowski Oopps, yes. Moved the ❌

**Comment by spencerfinnell** [comment]
PR #7594
