### ISSUE TITLE
3.0 - Discounts - Can't Apply Bulk Actions to Used Discounts

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/easy-digital-downloads#7596]
### Expected behavior

I should be able to select all Discounts and apply relevant Bulk Actions.

### Actual behavior

If a Discount has been used the checkbox to add to Bulk Actions queue is disabled.

### Steps to reproduce the behavior
1) Create a Discount.
2) Make a purchase using the Discount.
3) Attempt Bulk Actions.

### Information (if a specific version is affected):
EDD Version (or branch): `release/3.0`

Any other relevant information:

This is done because you cannot delete a Discount that has been used for record keeping reasons. However I believe we should keep the checkbox active for all items and simply skip previously used Discounts when performing the Delete Bulk Action.

As it stands you cannot perform Activate/Deactivate Bulk Actions on previously used Discounts.

**Comment by robincornett** [comment]
The `edd_delete_discount` function does perform a check on whether the discount can be used, so technically, all that would _need_ to happen would be to remove the additional logic from the checkbox column.

However, I think if a used discount is included in a bulk delete, it would help the user know why the discount was not deleted--is there a way to add an admin notice if a discount is _not_ deleted during a bulk action?
