### ISSUE TITLE
3.0 - JavaScript error while updating EDD Recurring payment method (Stripe)

### ISSUE THREAD

**Issue by nosegraze** [easydigitaldownloads/easy-digital-downloads#7609]
### Expected behavior

When I update a payment method I do not expect to get any JavaScript errors.

### Actual behavior

When I update my payment method for a Stripe subscription via EDD Recurring, adding a new card gives me a JavaScript error:

![Screenshot from 2019-11-19 16-32-48](https://user-images.githubusercontent.com/6324272/69165918-44232380-0aea-11ea-991a-023610a44207.png)

```
TypeError: name_field.validateCreditCard is not a function
```

Error is coming from `/js/frontend/checkout/index.js` https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/assets/js/frontend/checkout/index.js#L108-L111

### Steps to reproduce the behavior
1) Sign up for a new subscription via Stripe.
2) Go to the page with the `[edd_subscriptions]` shortcode and click to update your payment method.
3) Select the option to add a new card.
4) Click into the "Name on the Card" field.
5) After un-focusing the input field, the error triggers.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): EDD `release/3.0` branch, recurring `master` branch.

WordPress Version:

Any other relevant information:

I'm still able to actually update my card just fine, so this doesn't break that.

I only tested with Stripe but I suspect this would also cause a problem with any other payment gateways that allow you to update your payment method directly on-site.

**Comment by spencerfinnell** [comment]
@nosegraze That `jquery.validate.min.js` wasn't a registered script in 2.9.x so the file was kept but nothing enqueues it:

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/assets/js/jquery.validate.min.js

Are we sure this doesn't happen in 2.9.x as well?

**Comment by nosegraze** [comment]
@spencerfinnell I haven't tested on a blank install with a default theme but this doesn't happen on the RCP site right now.

**Comment by nosegraze** [comment]
@spencerfinnell I can confirm this does _not_ happen on 2.9.x. `edd-ajax.js` is still loaded, but the contents of this file are different. It doesn't have any code in it for validating a card.

Looks like the `EDD_Checkout` object is included in the 3.0 version of `edd-ajax.js` and that's where the card validation is. This object is NOT included in the 2.9.x version of that same file.

**Comment by spencerfinnell** [comment]
@nosegraze #7610 moves the `recalculateTax` function outside of the file that automatically executes `EDD_Checkout` to avoid having that run any time the function is imported.

**Comment by nosegraze** [comment]
- Confirmed original problem is fixed.
- Also tested checkout and confirmed that my tax rate gets recalculated when my billing region ch anges.
