### ISSUE TITLE
3.0 - EDD Commissions payouts not working due to "EDD_Export" JS no longer being loaded

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#7614]
### Expected behavior

When I fill out the form to generate a payout, I expect to get a prompt to download the CSV file.

![Screenshot from 2020-03-03 12-49-11](https://user-images.githubusercontent.com/6324272/75777181-66fdde80-5d4d-11ea-972a-d043a0ba24e3.png)

### Actual behavior

When I press "Generate File" the page just reloads. No CSV file is generated.

### Steps to reproduce the behavior
1) Be on EDD `release/3.0` branch.
2) Install EDD Commissions.
3) Go to Downloads > Commissions and fill out the form to generate a payout.
4) Upon selecting `Generate File`, you'll notice the page just reloads.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0

WordPress Version:

Any other relevant information: EDD Commissions `master` branch

---

In EDD `master` branch, the `admin-scripts.js` file is naturally loaded on the EDD Commissions page ( https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/assets/js/admin-scripts.js ). This file contains the [EDD_Export object](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/assets/js/admin-scripts.js#L1576), which handles all the logic for processing exports. EDD Commissions is purely relying on this to handle all exporting logic. However, in EDD `release/3.0` branch, this object is now in a brand new `edd-admin-tools-export.js` file and is conditionally loaded on very specific pages -- not this one.

We could handle this in one of two ways:

1. Update EDD core to load `edd-admin-tools.export.js` on more pages. This would maintain backwards compatibility. Consider other third party plugins that are relying on this built-in export functionality for their own tools.
2. Update EDD Commissions to specifically enqueue this new file on EDD 3.0+. It's possible this issue is in other add-ons too so we'd also need to update any others with this problem.

**Comment by spencerfinnell** [comment]
@nosegraze Oops, looks like https://github.com/easydigitaldownloads/easy-digital-downloads/pull/7535 was merged in to the wrong base.

**Comment by nosegraze** [comment]
@spencerfinnell Looks related but I'm not sure if that would fix this issue anyway since that's just enqueuing it on reports? This isn't a report so presumably it still wouldn't be enqueued on the EDD Commissions screen.

**Comment by spencerfinnell** [comment]
Sorry, you're right. 

In that case I would lean towards option 2. While it would be nice to not need to update extensions I think this having bit us in core already shows that the lack of explicit script enqueuing when utilizing core's batch exporter will continue to cause issues until we create some sort of standardization.

**Comment by cklosowski** [comment]
I would agree, this should be resolved in the extensions themselves.
