### ISSUE TITLE
3.0 - UI bug on legacy reports - old date filters overlap with graph

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#7615]
### Expected behavior

When I view a legacy report I expect it to render without any issues.

### Actual behavior

When I view a legacy report the date filters overlap with the report.

![Screenshot from 2020-03-03 13-16-37](https://user-images.githubusercontent.com/6324272/75779260-391a9900-5d51-11ea-808b-288584da8d04.png)

### Steps to reproduce the behavior
1) Install an add-on that contains a legacy report. Examples include: EDD SL or EDD Commissions. I'm using EDD Commissions.
2) Go to Downloads > Reports and select the legacy report.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0

WordPress Version:

Any other relevant information: EDD Commissions master branch.

**Comment by spencerfinnell** [comment]
We should be able to just remove this duplicate output completely by blanking out `edd_reports_graph_controls()` because `EDD\Reports\display_dates_filter()` is always called.

**Comment by spencerfinnell** [comment]
#7645 removes duplicate filters and ensures legacy compatibility.

**Comment by spencerfinnell** [comment]
Added a few more CSS tweaks to help address concerns in https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7626

<img width="585" alt="Screen Shot 2020-03-19 at 10 03 07 AM" src="https://user-images.githubusercontent.com/491124/77075610-f8fe1c00-69c8-11ea-8e49-adeb7458014c.png">
<img width="481" alt="Screen Shot 2020-03-19 at 10 03 18 AM" src="https://user-images.githubusercontent.com/491124/77075614-fa2f4900-69c8-11ea-8e0c-68c55cd426e8.png">
