### ISSUE TITLE
3.0 - Tooltips not working on legacy report graphs

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#7616]
### Expected behavior

When I view a legacy report graph, I expect hovering over a point on the graph to show me a tooltip.

### Actual behavior

When I hover over a point on the graph, no tooltip is shown.

### Steps to reproduce the behavior
1) Install an add-on that contains a legacy report. Examples include: EDD SL or EDD Commissions. I'm using EDD Commissions.
2) Go to Downloads > Reports and select the legacy report.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0, EDD Commissions master branch

WordPress Version:

Any other relevant information:

**Comment by spencerfinnell** [comment]
PR #7643 ensures tooltips are visible with Flot charts:

<img width="352" alt="Screen Shot 2020-03-11 at 11 29 05 AM" src="https://user-images.githubusercontent.com/491124/76434078-91721c00-638b-11ea-9d0e-dc5ae1bdd769.png">
