### ISSUE TITLE
3.0 - Orders table - edd_payment_row_actions filter not being applied

### ISSUE THREAD

**Issue by nosegraze** [easydigitaldownloads/easy-digital-downloads#7617]
### Expected behavior

When I install the PDF Invoices add-on, I expect a `Download Invoice` row action to appear when I hover over an order.

### Actual behavior

No such row action appears. This is due to the `edd_payment_row_actions` filter missing. This filter was used to hook in to add additional row actions.

### Steps to reproduce the behavior
1) Install PDF Invoices add-on.
2) Go to Downloads > Orders and hover over an order.
3) No `Download Invoice` link appears.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0 / PDF Invoices `master` branch

WordPress Version:

Any other relevant information:

All the logic for this is there in the `column_email()` payments table method. I suspect what happened is that the email column was at one point the primary, then it got swapped to `column_number()` and the filter just got missed off.

Related-ish: the `Resend Purchase Receipt` link from EDD core is also missing. Was this intentional or should we add it back in?

**Comment by pippinsplugins** [comment]
I use the `Resend Purchase Receipt` row action pretty frequently and I'm fairly certain I'm not alone on that. I feel we should keep it.

**Comment by spencerfinnell** [comment]
My guess about `Resend Purchase Receipt` no longer being there is the new support for selecting which email address to send the receipt to when viewing the order ([see UI here](https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7569#issuecomment-584186702)).

A link in the main table could always send it to the default email address or it could bring up a selector in a modal to let the user still pick the email address.

**Comment by pippinsplugins** [comment]
We've had a UI for selecting the email to send to for several years now. The row action just defaults to the primary email.

**Comment by nosegraze** [comment]
PR: #7618

![Screenshot from 2020-03-03 14-29-08](https://user-images.githubusercontent.com/6324272/75785593-e85c6d80-5d5b-11ea-831b-511d9b7a2611.png)

If you want to add a modal, @spencerfinnell I leave that up to you! :P

**Comment by spencerfinnell** [comment]
@nosegraze Matching current behavior by sending to the default email address makes sense to me.

**Comment by nosegraze** [comment]
Current PR sends it to the email address associated with the order record. I guess that's the email that was used for the order, which may not necessarily be the primary email for the customer? (If it has since changed or whatever.)
