### ISSUE TITLE
3.0 - Add automatic retry to upgrade routine AJAX upon failure

### ISSUE THREAD

**Issue by danieliser** [easydigitaldownloads/easy-digital-downloads#7624]
### Explain your enhancement (please be detailed)
Adding a simple and finite automatic retry method to the upgrade routine AJAX calls upon failure.

1. If the call was not a success and no valid error is returned, retry the call in 3-5s.
2. Repeat this up to 3 times.
3. Upon 3rd failed retry, show alert to notify admins it failed, **maybe include a link to restart at the correct step and reload the page at the same time**
4. If it succeeds before the 3rd attempt reset the counters in case its interrupted again later.

### Justification or use case
Had a couple connection interruptions while processing the v3 upgrades during testing. This required refreshing the page and starting the entire process over again. Imagine being at 98% on logs for a 5 year old store and having to restart (ours took over an hour).

**Comment by cklosowski** [comment]
The good news is, that if we've found that an order has already been migrated, we skip over it, so while it goes through the steps, it isn't actually doing the time consuming part of the migration.

**Comment by danieliser** [comment]
@cklosowski Strange, having been dealing with connection issues and the bugs in #7620 & #6880 I've had to run the first one and last 2 multiple times. The last time was no faster than the first half a dozen attempts.

Seems it processes each one anyways, so the back and forth connection to the server still occurs I'm guessing even if no data migration occurs.

Wonder if your still querying all orders, rather than only querying the ones that haven't been processed if that is possible?

**Comment by cklosowski** [comment]
We're going handle all upgrade routine changes in the existing issues #6880 and #6810. Closing and removing the milestone.
