### ISSUE TITLE
3.0 - "Legacy" reports do not have consistent padding

### ISSUE THREAD

**Issue by danieliser** [easydigitaldownloads/easy-digital-downloads#7626]
### Actual behavior
When viewing some legacy report pages there is no tab container padding.

### Steps to reproduce the behavior
1) Install v3.0 & ( All Access Passes or Recurring Payments or Software Licensing etc )
2) View the legacy reports

There are 2 main issues I see.

- [x] Top padding on all Legacy sections is not consistent with the older ones. There is an empty div now that seems to make this issue.

**Solution**: this was a simple solution, tried to target it somewhat so it wasn't hiding all tablenavs.
```
.download_page_edd-reports .section-content .tablenav.top {
    display: none;
}
```

- [x] All Access Pass report has no left padding 

![image](https://user-images.githubusercontent.com/847818/75941561-04e0ce80-5e5e-11ea-8df3-4f1d32490178.png)

**Comment by spencerfinnell** [comment]
First issue is addressed in https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7615

**Comment by spencerfinnell** [comment]
Closing in favor of https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7615#issuecomment-601197081 which includes fixes for both.
