### ISSUE TITLE
3.0 - Refunds report queries missing "type = 'refund'" condition, resulting in incorrect counts

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#7637]
### Expected behavior

I expect the refunds report to show me accurate counts for number of refunded orders, refund amount, etc.

### Actual behavior

![Screenshot from 2020-03-10 15-48-11](https://user-images.githubusercontent.com/6324272/76331209-bb253780-62e6-11ea-9ded-1c70c5987fb3.png)

This shows I had 44 refunds last year. But in reality, I had 44 total orders and 1 refund. You can see the discrepancy in the numbers at the top versus the graph below.

Here's one of the refund queries:

```mysql
SELECT COUNT(id) AS total
FROM wp_edd_orders
WHERE 1=1 AND wp_edd_orders.status IN ('complete', 'partially_refunded')   AND wp_edd_orders.date_created >= '2019-01-01 00:00:00' AND wp_edd_orders.date_created <= '2019-12-31 23:59:59'
```

It's missing a condition for `AND type = 'refund'`

### Steps to reproduce the behavior
1) Make two sales.
2) Refund one of the sales.
3) Check refund report. Sale count should be 2, refund count should be 1, but refund count will be showing as 2.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0

WordPress Version:

Any other relevant information:

**Comment by nosegraze** [comment]
"Number of Fully Refunded Items" is also incorrect. Here's the query it's running:

```mysql
SELECT *
FROM wp_edd_order_items
WHERE 1=1   AND wp_edd_order_items.status IN ('refunded')   AND wp_edd_order_items.date_created >= '2019-01-01 00:00:00' AND wp_edd_order_items.date_created <= '2019-12-31 23:59:59'
```

This is coming up with two results, when actually I just have **one** refund, which contains **one item**.

The problem here is that both orders and refunds get order items inside `wp_edd_order_items`. So this query is picking up the `refunded` order items from both the original `type = order` and the corresponding `type = refund`.

I have an order ID 1827 with a status `refunded`.
This order has a corresponding entry in `wp_edd_order_items` for the original order.

This order has a refund ID 1922.
This refund has a corresponding entry in `wp_edd_order_items` for this new refund record.

This results in TWO entries being picked out from the above query when really it should just be one -- corresponding to the refund record.

**Comment by nosegraze** [comment]
Another issue in the `EDD\Stats\get_order_earnings()` query I believe, with regards to refunds.

The query is:

```mysql
SELECT SUM(total) AS total
FROM wp_edd_orders
WHERE 1 = 1
  AND wp_edd_orders.status IN ('complete', 'revoked')
  AND wp_edd_orders.date_created >= '2019-01-01 00:00:00'
  AND wp_edd_orders.date_created <= '2019-12-31 23:59:59'
```

It's not filtering by `type`, which means it's picking up refunds. That's fine, as I assume the intention is to output SALES - REFUNDS. However, it's only checking for `complete` and `revoked` statuses. So imagine you have two sales:

Sale 1: total = $100; status = complete
Sale 2: total = $100; status = complete

`get_order_earnings()` result = $200

Good so far.

Now refund one of those. Now the DB looks like this:

Sale 1: total = $100; status = refunded
Sale 2: total = $100; status = complete
Refund 1: total = -$100; status = complete

`edd_order_earnings()` picks up Sale 2 and Refund 1, which brings the result to $0. But it should be $100.

**Comment by nosegraze** [comment]
After some Slack input, going to work off the assumption that "Order Earnings" should be gross sales and not factor in refunds. Will make a new issue for some kind of net sales stat.

**Comment by nosegraze** [comment]
Refund rate is also a bit odd.

Query:

```mysql
SELECT SUM(ABS(wp_edd_orders.total)) / o.total * 100 AS `refund_rate`
FROM wp_edd_orders
         CROSS JOIN (
    SELECT SUM(id) AS total
    FROM wp_edd_orders
    WHERE 1 = 1
      AND wp_edd_orders.status IN ('complete', 'revoked')
      AND wp_edd_orders.total > 0
      AND wp_edd_orders.date_created >= '2019-01-01 00:00:00'
      AND wp_edd_orders.date_created <= '2019-12-31 23:59:59'
) o
WHERE 1 = 1
  AND status IN ('complete', 'partially_refunded')
  AND type = 'refund'
  AND wp_edd_orders.date_created >= '2019-01-01 00:00:00'
  AND wp_edd_orders.date_created <= '2019-12-31 23:59:59'
```

Two things:

1. In the cross join it's selecting `SUM(id)` . Summing the ID numbers lol. I assume that was meant to be `SUM(total)`.
2. I'm not sure I feel the logic matches the label. This is called a "Refund Rate". In my mind that should be `{number of refunds} / {number of orders} * 100`. Instead, it's looking at _monetary value_ - `{value of refund earnings} / {value of all total earnings} * 100`.
IMO, we should either do:
    1. Keep the label as `Refund Rate`, but base it on refund/order _counts_. Or:
    2. Change the label to better reflect what's going on... somehow condensing this description into a label: _percentage of earnings that were refunded_. (bit wordy, but better describes what it is)

**Comment by pippinsplugins** [comment]
Refund rate should, in my opinion, definitely `{number of refunds} / {number of orders} * 100`.

**Comment by ashleyfae** [comment]
New refund rate query:

```mysql
SELECT COUNT(id) / o.number_orders * 100 AS `refund_rate`
FROM wp_edd_orders
         CROSS JOIN (
    SELECT COUNT(id) AS number_orders
    FROM wp_edd_orders
    WHERE 1 = 1
      AND wp_edd_orders.status IN ('complete', 'revoked', 'refunded', 'partially_refunded')
      AND wp_edd_orders.total > 0
      AND wp_edd_orders.date_created >= '2020-02-01 08:00:00'
      AND wp_edd_orders.date_created <= '2020-03-01 07:59:59'
) o
WHERE 1 = 1
  AND status = 'complete'
  AND type = 'refund'
  AND wp_edd_orders.date_created >= '2020-02-01 08:00:00'
  AND wp_edd_orders.date_created <= '2020-03-01 07:59:59'
```

**Comment by ashleyfae** [comment]
Think this PR is ready for review now: #7638

In short, it should ensure all the queries on the `Reports` page are working as expected.
