### ISSUE TITLE
3.0 - Partial refunds not changing original order status to "partially_refunded"

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#7640]
### Expected behavior

When I refund part of an order, I expect the order's status to change to `partially_refunded` (both in the database and in the UI dropdown).

### Actual behavior

When I refund part of an order, the status in the database and UI remains `complete`. Also, there is no "Partially Refunded" dropdown option. I assume there is supposed to be one?

### Steps to reproduce the behavior
1) Have an order with at least two order items.
2) Refund just one of the order items.
3) The refund record will be created, but the original order status remains as "Completed".

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0

WordPress Version:

Any other relevant information:

**Comment by spencerfinnell** [comment]
Previously https://github.com/easydigitaldownloads/easy-digital-downloads/issues/2721#issuecomment-520607686

**Comment by spencerfinnell** [comment]
PR #7658
