### ISSUE TITLE
Chosen <select> Fields "Disabled" on Mobile

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/easy-digital-downloads#7649]
### Expected behavior

When I view a `<select>` field that is supposed use the Chosen library on desktop, it should appear like a normal `<select>` on mobile because Chosen is not invoked on touch devices.

### Actual behavior

Styles are applied that make it appear `disabled`

### Steps to reproduce the behavior
1) View any EDD page (such as Settings) that contains a Chosen `<select>` box.

<img width="527" alt="Screen Shot 2020-03-17 at 12 24 47 PM" src="https://user-images.githubusercontent.com/491124/76877814-5324a300-684a-11ea-8492-4aa9cd7bc270.png">

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): `release/3.0`

Any other relevant information:

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/assets/css/edd-admin-chosen.css#L6

**Comment by spencerfinnell** [comment]
Related #7583

**Comment by LisaCee** [comment]
Would something like this look better?  
![image](https://user-images.githubusercontent.com/18077352/77802965-4cabdd80-7039-11ea-938e-e3ca8b6ac15b.png)

**Comment by spencerfinnell** [comment]
@LisaCee Sorry, that initial screenshot is no longer valid after https://github.com/easydigitaldownloads/easy-digital-downloads/pull/7671

Take a look at the "Business Country" or "Business Region" on a touch-based device. [Chosen](https://harvesthq.github.io/chosen/) isn't applied when it detects a touch-based device, so to ensure you're seeing the native select you can emulate a touch device in Chrome: 

<img width="420" alt="Screen Shot 2020-03-30 at 9 06 17 AM" src="https://user-images.githubusercontent.com/491124/77915631-cde7b800-7265-11ea-8c09-3567f3431f29.png">

I think the original idea of 

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/db9ad79564f45d16c363fa859f254e8a366e9c81/assets/css/edd-admin-chosen.css#L4-L8

Was to have emulate a "loading" state while Chosen initialized. However if Chosen never initializes the `<select>` continues to look disabled even if it is not. We should just remove the `opacity` so if Chosen is not initialized on the `<select>` it is styled normally.

Looking again we can remove that whole rule because WordPress core styles define a `min-height` and `max-width` that we should not override either.
