### ISSUE TITLE
3.0: Custom payment status labels not shown in Orders page filters

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#7651]
### Expected behavior
When displaying the status filters on the orders page, we should be showing the label and not the slug of the payment status.

### Actual behavior
For custom statuses, such as `edd_subscription` the slug is currently displayed. The `edd_subscription` status should be shown as `Renewal`.

![image](https://user-images.githubusercontent.com/1034109/76969568-8cb3e780-68f8-11ea-8666-f4c070cb3410.png)

**Comment by spencerfinnell** [comment]
PR #7653
