### ISSUE TITLE
3.0: Overview report not counting renewal payments

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#7652]
### Expected behavior
The `Overview` report should display the total earnings from all payment records.

### Actual behavior
Renewal payments (status of `edd_subscription`) are not being included. It's likely that no custom payment statuses are getting included but I have not been able to confirm that.

### Steps to reproduce the behavior
1) View the `Overview` report with a store that has renewal payments from the Recurring Payments extension
2) Compare sale counts and earnings to see discrepancy

**Comment by cklosowski** [comment]
My guess is it is just a quick filter for the Recurring add-on that will come once it is tested. Let's keep this open in case we need any work in Core to allow for extensions that register am order status.

**Comment by pippinsplugins** [comment]
I look at the queries and am confused by them.

Unless I'm missing something, right now the overview stats are querying _all_ payment statuses, which would include failed, abandoned, refunded, etc.

**Comment by spencerfinnell** [comment]
@pippinsplugins I think it would need to be added to this list: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/class-stats.php#L172 (and similar)

A filter on all query vars before SQL is generated would allow extensions to detect if it was a `sale` Order type and append any necessary statuses for records that should be included when calculating sales.

**Comment by spencerfinnell** [comment]
A global filter might be nice, but we'll at least need to restore https://github.com/easydigitaldownloads/easy-digital-downloads/blob/808246b7af3c6519cc333e6bac103f136fe071d9/includes/payments/class-payment-stats.php#L313 on status lists.

**Comment by spencerfinnell** [comment]
#7654 Restores the filter to fix the regression of statuses not being included.
