### ISSUE TITLE
3.0 - Reports - Refunds should not be included in "Sales and Earnings" graph

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#7663]
### Expected behavior

I expect the Sales and Earnings graph to count orders only, and add up gross earnings. Refunds should not be factored in. There's a separate graph for that.

### Actual behavior

The query being executed for this graph is:

```mysql
SELECT COUNT(id) AS sales, SUM(total) AS earnings, date_created AS date
FROM wp_edd_orders edd_o
WHERE date_created >= '2020-02-01 08:00:00'
  AND date_created <= '2020-03-01 07:59:59'
GROUP BY DATE(date_created)
ORDER BY DATE(date_created) ASC
```

There's no `type = 'sale'` condition, nor are we checking any specific status. As a result, refunds are being counted as a "sale" count, and the refund amount is being added to the graph as a negative earning.

We should also be adding in a status check to ensure we don't pick up `abandoned` orders, for example.

### Steps to reproduce the behavior
1) Refund an order.
2) Go to Downloads > Reports > Overview and look at the "Sales and Earnings" graph.
3) You'll see your refund listed on the chart.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0

WordPress Version:

Any other relevant information:

**Comment by ashleyfae** [comment]
PR: #7664

New query:

```mysql
SELECT COUNT(id) AS sales, SUM(total) AS earnings, date_created AS date
FROM wp_edd_orders edd_o
WHERE date_created >= '2020-02-01 08:00:00'
  AND date_created <= '2020-03-01 07:59:59'
  AND type = 'sale'
  AND status IN ('complete', 'publish', 'revoked', 'refunded', 'partially_refunded', 'edd_subscription')
GROUP BY DATE(date_created)
ORDER BY DATE(date_created) ASC
```

**Comment by pippinsplugins** [comment]
Related #7652

**Comment by ashleyfae** [comment]
This PR contains the same `edd_payment_stats_post_statuses` filter that was re-added in that issue. :+1: https://github.com/easydigitaldownloads/easy-digital-downloads/pull/7664/files#diff-50509376cd8ea4f0bb9ec07de29c60b7R46

**Comment by pippinsplugins** [comment]
I think this is right.

One change from 2.9.x for us to keep in mind: we are counting renewal payments as sales now. Previously we did not count renewal payments as sales (which I feel was wrong).

If you compare 2.9.x counts to 3.0 counts and aren't sure why the counts are different, that's why.
