### ISSUE TITLE
3.0: Alignment and margins of filters in Tools > Logs > File Downloads messed up

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#7667]
## Bug Report
The alignment and margins of the filters in Tools > Logs is very messy:
![image](https://user-images.githubusercontent.com/1034109/77078457-9b67d080-69c4-11ea-884c-e053d9645691.png)

WordPress latest and Chrome on Ubuntu.

**Comment by spencerfinnell** [comment]
#7678 implements the "More" Advanced Filters to match the Orders table:

<img width="768" alt="Screen Shot 2020-03-20 at 1 49 19 PM" src="https://user-images.githubusercontent.com/491124/77191857-fd523400-6ab1-11ea-9165-062cb68531fa.png">

**Comment by spencerfinnell** [comment]
These additional filters might be removed via https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7668 but the CSS alignment fixes and allowing the Advanced Filters to work on all screens are still relevant changes.
