### ISSUE TITLE
3.0: Incorrect filter options shown on Tools > Logs > File Downloads

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#7668]
### Expected behavior
The file downloads log should not have filter options for the payment type (renewal / upgrade).

### Actual behavior
The payment type option is showing on the file downloads log table:
![image](https://user-images.githubusercontent.com/1034109/77078693-ef72b500-69c4-11ea-80b5-ba73c063200d.png)

**Comment by cklosowski** [comment]
@pippinsplugins I'm assuming this is a Software Licensing filter that needs to be handled. Without it, I don't have these:
![image](https://user-images.githubusercontent.com/1390124/77123566-b86cc580-69fd-11ea-9e20-c62667d51232.png)

We have 2 options then:
1) Update the actions/filters in extensions that add items to this filter form
2) Add context to the action/filter so that it can be directly targted.

**Comment by pippinsplugins** [comment]
Yes it comes from Software Licensing.

I am on the side of updating core 3.0 to match the behavior that 2.9 had as we have no way of knowing what other extensions are doing what Software Licensing is doing.

**Comment by spencerfinnell** [comment]
This is being output via https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/reporting/class-base-logs-list-table.php#L469

Which also exists here: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/payments/class-payments-table.php#L280

I think this might have been copied over accidentally as nothing similar exists in 2.9.

Related #7667

**Comment by spencerfinnell** [comment]
#7680 Removes the action to stop irrelevant output.

**Comment by cklosowski** [comment]
@spencerfinnell I fixed the merge conflicts...can you recheck this? I'm still seeing these filters: 
![image](https://user-images.githubusercontent.com/1390124/77592686-f52e3600-6eaf-11ea-8703-223b90a1273e.png)

**Comment by cklosowski** [comment]
Nevermind, fixed it, the merge conflict re-added the action.
