### ISSUE TITLE
3.0 - Migration (CLI) - Count of "New Records" for discounts is incorrect

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#7690]
### Expected behavior

I expect the `New Records` count to show me accurate information.

### Actual behavior

It just shows `1`.

![Screenshot from 2020-03-30 13-32-41](https://user-images.githubusercontent.com/6324272/77912759-08b01700-728b-11ea-8712-fd47a6258cb5.png)

But actual screenshot from new Discounts page:

![Screenshot from 2020-03-30 13-36-07](https://user-images.githubusercontent.com/6324272/77912994-73f9e900-728b-11ea-95af-13f61ebc3c99.png)

This is due to us using:

```php
$new_count = count( edd_get_discounts( array( 'number' => - 1 ) ) );
```

`-1` is no longer a valid way of retrieving all records. Instead we should be using `edd_get_discount_count()`.

I'm not sure if this is also a backwards compatibility issue we need to keep in mind. Perhaps we need to look for a `-1` argument in `edd_get_discounts()` and convert that to a really large number.

### Steps to reproduce the behavior
1) Run `wp edd migrate_discounts --force` via CLI.
2) See incorrect `New Records` printed.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0

WordPress Version:

Any other relevant information:

**Comment by cklosowski** [comment]
We’ve had a few discussions about if we should still support `-1` to mean `all the things`. In part, it can cause some serious scalability issues which was the goal to remove them and stop supporting them within the addition of BerlinDB.

I think we should maybe look at places where we stop supporting `-1` and throw a doing it wrong, but for this issue, we should just fix the usage to the correct function.
