### ISSUE TITLE
3.0 - Reports - "Exclude Taxes" also incorrectly excludes discounts

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#7692]
### Expected behavior

When I check on "Exclude Taxes", I expect the amounts to reflect the total price with only taxes subtracted.

### Actual behavior

When I check on "Exclude Taxes", the amounts reflect the pre-tax **and pre-discount** price.

Notice how the earnings actually _increase_ when I exclude taxes:

![Screenshot from 2020-03-30 13-49-13](https://user-images.githubusercontent.com/6324272/77914101-4dd54880-728d-11ea-943a-2becc3e0cb0c.png)

![Screenshot from 2020-03-30 13-49-24](https://user-images.githubusercontent.com/6324272/77914104-5037a280-728d-11ea-8779-17fdad088b35.png)

When unchecked, the query does `SUM(total)` . When checked, the query does `SUM(subtotal)`. That would be okay if the subtotal was just the total without taxes. However, the subtotal does not include discounts, so when you do have a discount, your actual earnings are reduced and that isn't considered.

Unless we want to make some major changes around what `subtotal` is, we can correct this by doing `SUM(total - tax)`

### Steps to reproduce the behavior
1) Ensure you have at least one order with a discount, and at least one order with tax.
2) Go to Downloads > Reports and look at the Overview.
3) Toggle Exclude Taxes and notice the differences.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0

WordPress Version:

Any other relevant information:

Related: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7644, https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7621 ("what is subtotal" discussion)

**Comment by spencerfinnell** [comment]
@ashleyfae `SUM(total - tax)` makes sense.

**Comment by spencerfinnell** [comment]
@ashleyfae Do you think it's worth adding a helper like `Reports\get_filter_sum_column()` or similar that performs a modified version of the existing logic that could also be expanded to do things like exclude the `discount` column if an "Exclude Discounts" filter was added in the future?

**Comment by ashleyfae** [comment]
@spencerfinnell I'd opt for keeping it simple for now, and then possibly look at introducing a helper down the line if we do add an option to exclude discounts or add something else that increase the complexity. (So don't introduce it until things get more complicated and we feel we need it.)
