### ISSUE TITLE
3.0 - Reports/Carbon - `last_month` date range not actually retrieving last month

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#7693]
### Expected behavior

When I change the report date range to Last Month, I expect to get results from the previous month (so, at the time of writing -- 30 March -- that would be February).

### Actual behavior

Last month is actually retrieving results from this month (March).

### Steps to reproduce the behavior

I think these steps will only work today and tomorrow (so until we tick over to April).

1) Go to Downloads > Reports.
2) Set date range to Last Month.
3) Notice how stats are exactly the same as This Month. If you print out the query you can also see that it's querying this month. You can also use `EDD\Reports\parse_dates_for_range( 'last_month' )` directly to check the dates.

![Screenshot from 2020-03-30 14-06-26](https://user-images.githubusercontent.com/6324272/77915607-ae658500-728f-11ea-8753-5cfeba980353.png)

![Screenshot from 2020-03-30 14-06-36](https://user-images.githubusercontent.com/6324272/77915610-aefe1b80-728f-11ea-8838-2bc43a7986ab.png)

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0

WordPress Version:

Any other relevant information:

This looks related: https://github.com/briannesbitt/Carbon/issues/428

I think it's a problem with today being March 30th and there not being a February 30th. Seems like changing `subMonth` to `subMonthNoOverflow` fixes the issue.

**Comment by ashleyfae** [comment]
Note this needs to be fixed in:

`EDD\Stats\set_date_ranges()`

and

`EDD\Reports\parse_dates_for_range()`

**Comment by spencerfinnell** [comment]
@ashleyfae Testing on April 8th, I see:

```
array(3) {
  ["start"]=> object(EDD\Utils\Date)#1711 (3) {
    ["date"]=> string(26) "2020-03-01 00:00:00.000000"
    ["timezone_type"]=> int(2)
    ["timezone"]=> string(3) "UTC"
  }
  ["end"]=> object(EDD\Utils\Date)#1710 (3) {
    ["date"]=> string(26) "2020-03-31 23:59:59.000000"
    ["timezone_type"]=> int(2)
    ["timezone"]=> string(3) "UTC"
  }
  ["range"]=> string(10) "last_month"
}
```

**Comment by ashleyfae** [comment]
@spencerfinnell I think this problem was only noticeable when testing it on a day that didn't exist in the previous month (so testing on March 30th, when there was no February 30th).

**Comment by spencerfinnell** [comment]
Sorry @ashleyfae, I missed that in your original report. PR #7729 attempts to fix this issue based on your original additional information.
