### ISSUE TITLE
3.0 - Illegal string offset in Customers report

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#7699]
### Expected behavior
When I view the Customers report, I want to see the report without errors.

### Actual behavior
When I view the Customers report, I get this warning:

```
PHP Warning:  Illegal string offset 'exclude_taxes' in \plugins\easy-digital-downloads.30\includes\reports\data\customers\class-top-five-customers-list-table.php on line 41
```

### Steps to reproduce the behavior
1) in my 3.0, I do not have taxes enabled at all. I do not know if it's a factor
2) in 3.0, visit the Reports screen and then click on Customers

### Information (if a specific version is affected):
PHP Version: 7.3.5
EDD Version (or branch): 3.0
WordPress Version: 5.4

Any other relevant information:
The conditional on that line checks if the value of the array key is false, but in my case, the key isn't set at all, so it looks like we could just add an `isset` check to it.

**Comment by spencerfinnell** [comment]
@robincornett Nice catch, I missed that when I updated things to use:

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/db9ad79564f45d16c363fa859f254e8a366e9c81/includes/reports/reports-functions.php#L770-L785

That helper can be used to check just for a `bool` vs. needing to see if the filter exists as well.

**Comment by robincornett** [comment]
@spencerfinnell I confess I was not able to track down exactly where the `exclude_taxes` would be set, so wasn't sure. Since this whole condition also has an `else`, are you saying the `$taxes` variable assignment should be changed to:

```php
$taxes = Reports\get_taxes_excluded_filter();
```
and then the conditional should just be `if ( ! $taxes )`? That changes the logic from what I was working with, but I would guess that my logic is incorrect, and if it's not set, it should be assumed to be false--which seems to be what your helper function is doing, right? I can update the PR if this is the case.
