### ISSUE TITLE
Update EDD_SL_Plugin_Updater to 1.8

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#7707]
### Explain your enhancement (please be detailed)
The base `EDD_SL_Plugin_Updater` class is being updated to version `1.7` in the upcoming Software Licensing release `3.6.10`. We should update the bundeled updater.

**Comment by cklosowski** [comment]
@robincornett do we have a quick follow up to this class in the sample plugin that we should put in here?

**Comment by robincornett** [comment]
The only PR pending is [1613](https://github.com/easydigitaldownloads/EDD-Software-Licensing/pull/1613), which removes the duplicate icons assignment; I think that would be easy to include.

I also encountered an issue with response object items not being set for my own plugins ([1610](https://github.com/easydigitaldownloads/EDD-Software-Licensing/issues/1610)) for the new `$no_update` variable, but am not 100% sure if it's best resolved in the samples, or the plugin, or both. (I pushed personal plugin updates and fixed it in my copy of the updater class, but I think making sure the response always has all items, even if empty/default, might be preferable.)

**Comment by cklosowski** [comment]
In light of a few things @robincornett found I'm going to punt this out a few versions to get those fixed up.

**Comment by robincornett** [comment]
@ashleyfae just pinging you on this to review as we held off initially to finish another SL version, and now we're looking at 1.8 for the updater class. I can do the PR against 2.10 when that's been finalized.

**Comment by ashleyfae** [comment]
Sounds good, thanks @robincornett !

**Comment by robincornett** [comment]
One additional question is whether we want to update EDD's use of the updater class to allow for auto-updates, or just update the updater itself.
