### ISSUE TITLE
3.0 - Dashboard widget recent purchases are missing the order ID

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#7708]
### Expected behavior
The "Recent Purchases" on the dashboard widget should show complete information, such as:

> 93 —  Synthia.Lemons@edd.local

### Actual behavior
Currently, the dashboard widget is not showing the order number, only the dash and customer email address:

>  — Synthia.Lemons@edd.local 

### Steps to reproduce the behavior
1) Make sure you have some recent orders in an EDD 3.0 store.
2) Visit the Dashboard

### Information (if a specific version is affected):
PHP Version: 7.3.5
EDD Version (or branch): release/3.0
WordPress Version: 5.4

Any other relevant information:
It looks like the output here uses [get_the_title](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/dashboard-widgets.php#L171) on the payment ID, and it should maybe just output it as `esc_attr( $payment->ID );` instead.

**Comment by spencerfinnell** [comment]
This can be updated to use 3.0's `edd_get_orders()` similar to how "Recent Orders" are output when editing a customer in the dashboard. This will give us access to the true order number (including custom prefixes, sequential, etc).

Lets also remove the space and dash from the "View All" link while we are at it: 

<img width="386" alt="Screen Shot 2020-04-06 at 12 50 51 PM" src="https://user-images.githubusercontent.com/491124/78583805-508fea80-7805-11ea-9083-8e32e16f6753.png">

**Comment by robincornett** [comment]
+1 on the "View All" link; thank you!

So the `order_number` property is only set, it looks like, if sequential order numbering is enabled--so the order number needs to either display the `order_number` if it has a value, or fall back to the `ID` if not?

**Comment by spencerfinnell** [comment]
@robincornett The Order history table uses `$order->get_number()`, which should use sequential if enabled or fallback to the ID.

**Comment by spencerfinnell** [comment]
@robincornett Those changes look good, but I'm wondering if we should take this a step further. It might be a good time to use a little more natural language and create more of an "activity panel" or "notifications feed" feel:

<img width="544" alt="Screen Shot 2020-04-08 at 10 42 23 AM" src="https://user-images.githubusercontent.com/491124/78797424-aab7b980-7985-11ea-9507-57d156231e35.png">

Thoughts?

**Comment by robincornett** [comment]
I would be open to something like that--as I was finishing the last commit, I confess I was dissatisfied that the current output for recent purchases now creates two cells for each purchase with identical links (outside of the link text). If we went with this, would it be okay to remove the table markup as it would no longer be needed?

**Comment by spencerfinnell** [comment]
@robincornett Yes, I think we can switch away from the `table` markup. That mockup was using a `<ul>` which WordPress already removes the list styling from on dashboard widgets.

If you want to move forward with this, check out `edd_get_order_item_counts()` to get the the amount of items in each Order.
