### ISSUE TITLE
3.0 - Dashboard widget "Today" shows total number of sales

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#7709]
### Expected behavior
The "Today" column of the dashboard widget should show the total number of sales made today.

### Actual behavior
The column is showing the total number of sales made through the store.

### Steps to reproduce the behavior
1) Make sure you have orders in your store covering a range of dates
2) Add an order with today's date
3) View the dashboard widget--the Earnings amount is correct, but the number of sales is the total number of sales in the shop

### Information (if a specific version is affected):
PHP Version: 7.3.5
EDD Version (or branch): release/3.0
WordPress Version: 5.4

Any other relevant information:
The [`get_sales()`](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/payments/class-payment-stats.php#L42) method accepts `0` for the download ID, to query payments for all downloads, but the main conditional doesn't factor in the time parameters if the download ID is `empty`. My guess is that the conditional needs to be adjusted to always check for the date, and not necessarily include the download ID in the date query, if that is possible.

**Comment by spencerfinnell** [comment]
These can likely be updated to use `EDD\Stats` directly (which power Reports) for more efficient numbers and consistency across the codebase.
