### ISSUE TITLE
3.0 - Trashed orders show in customer purchase history

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#7710]
### Expected behavior
If I delete an order, I expect that the customer should be unable to see it.

### Actual behavior
If I delete an order in 3.0, it still shows in the customer's purchase history, with "Trash" in the Details column.

### Steps to reproduce the behavior
1) create an order in 3.0 and assign it to a user who has a customer account
2) delete the order
3) log into the site as the customer and view the purchase history

### Information (if a specific version is affected):
PHP Version: 7.3.5
EDD Version (or branch): release/3.0
WordPress Version: 5.4

Any other relevant information:
In 2.9, it looks like clicking the "Delete" link on the order history permanently deleted an order, but in 3.0, the order is moved to the trash instead. This seems like a safer behavior, as it adds a confirmation step in there instead of doing something irrevocable with just one click, but since the order status in the purchase history is set to `any`, the result is that trashed orders are shown to the user as well as complete, refunded, etc. I prefer to have the intermediate trash location in use for admin deleted orders, but would think that those should not show to the customer in their history.

**Comment by spencerfinnell** [comment]
Right now the shortcode pulls all purchases by passing `any` as the status flag: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/templates/history-purchases.php#L11

As @robincornett said since Trash didn't previously exist we need to ensure that any `any` status flags fall back to our defined list of registered Order statuses, which doesn't include Trash.

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/a958ab79f3a5129a2964076433e09c6fb377e1c4/includes/payments/functions.php#L596-L615

**Comment by robincornett** [comment]
@spencerfinnell so should we add a final check in the `EDD_Payments_Query` `__construct` method to reset the `status` if `any` is present, so that we catch all uses of it? Something like this:

```php
if ( 'any' === $this->args['status'] || ( is_array( $this->args['status'] ) && in_array( 'any', $this->args['status'], true ) ) ) {
	$this->args['status'] = edd_get_payment_status_keys();
}
```
Adding in this change does fix the user view I reported.

Related: digging into this, I passed by this code:

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/a958ab79f3a5129a2964076433e09c6fb377e1c4/includes/user-functions.php#L81-L83

This condition will actually never be met, because any status passed to this function is already an array or is cast to an array in lines [42-56](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/user-functions.php#L42-L56), so it seems like that can be removed.

**Comment by spencerfinnell** [comment]
@robincornett There are some similar checks in place here:

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/a958ab79f3a5129a2964076433e09c6fb377e1c4/includes/payments/class-payments-query.php#L718-L727

Where I think instead of unsetting the status we can set it to the whitelist of keys like your example.

That does seem like dead code, but I think for the sake of this PR let's keep the changes just around the `EDD_Payments_Query` handling of `any` status.

cc @cklosowski Thoughts on this approach?

**Comment by robincornett** [comment]
So that block could be changed to this?

```php
// If the status includes `any`, we should set the status to our whitelisted keys.
if ( isset( $arguments['status'] ) && ( 'any' === $arguments['status'] || ( is_array( $arguments['status'] ) && in_array( 'any', $arguments['status'], true ) ) ) ) {
	$arguments['status'] = edd_get_payment_status_keys();
}
```
However, in digging through to figure out where `$arguments['status']` was actually set, it looks like in the `get_payments()` method that this is called:

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/a958ab79f3a5129a2964076433e09c6fb377e1c4/includes/payments/class-payments-query.php#L254-L266

It seems like this needs to be updated to prefer `status` and unset/remove `post_status`, because currently, when the code hits line 718, `status` has been removed and replaced with `post_status` and then changed back to `status`. It looks like we are taking `status`, mapping it to `post_status`, and then mapping it back to `status`.

**Comment by spencerfinnell** [comment]
> So that block could be changed to this?

Yes, I believe that is the right direction.

> It looks like we are taking status, mapping it to post_status, and then mapping it back to status.

The first version of querying for EDD Payments involved custom arguments like `status`. Those were then mapped to things like `post_status` so they could be fed in to `WP_Query` (the code you linked to). Now we are remapping back to arguments that can be used with the custom tables used by EDD 3.0; resulting in mapping it back to `status` via the `remap_args()` method. 

It is indeed a lot of back and forth but I am guessing another layer of mapping was added at the end vs. rewriting existing methods to help maintain backwards compatibility.
