### ISSUE TITLE
3.0 - AffiliateWP's "Trends" graphs not displaying

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/easy-digital-downloads#7714]
### Expected behavior
When I view the `Reports` screen in AffiliateWP I expect the "Trends" graphs to display for each tab.

### Actual behavior
When I view the `Reports` screen in AffiliateWP, the "Trends" graphs are no longer displaying for each tab.

### Steps to reproduce the behavior
1) Activate AffiliateWP 2.5.1
2) Activate EDD 3.0.0-beta-1
3) Visit Affiliates -> Reports.

Note how the Trends graph under the "Trends" heading does not display. The console shows an error:

```
Error: Time mode requires the flot.time plugin.
```

With EDD active there's no graph and a console error:

<img width="1406" alt="Screen Shot 2020-04-07 at 3 58 49 PM" src="https://user-images.githubusercontent.com/52581/78629541-83aca980-78eb-11ea-8f96-87dbc3da3d83.png">

With EDD disabled, there's a graph and no console error as expected:

<img width="1410" alt="Screen Shot 2020-04-07 at 3 58 18 PM" src="https://user-images.githubusercontent.com/52581/78629579-9cb55a80-78eb-11ea-84f5-47ab7f73667a.png">

### Information
PHP Version: 7.3.9

EDD Version (or branch): EDD 3.0.0-beta-1

WordPress Version: 5.4

Any other relevant information:

1. The graph shows as expected with the latest EDD master branch 
2. It looks like EDD's Flot JS script is being loaded in place of AffiliateWP's version on the Reports screen. This would explain the JS error which is preventing the graph from being displayed.

**Comment by spencerfinnell** [comment]
EDD and AffiliateWP share the same `jquery-flot` script handle. The issue is EDD 3.0 uses `0.8.0-alpha` of Flot, which separates the "time" functionality in to a different plugin. 

We'll either need to roll back to 0.7.0 (that does not have an official release so it cannot be managed by NPM easily), or change our script handle.

It should also be noted that 0.7.0 is over 6 years old and there is a Flot 4.20.0 release as recent as February of this year.

**Comment by cklosowski** [comment]
If we can get by with changing our script handle, let's try that.

**Comment by spencerfinnell** [comment]
PR #7763 prefixes Flot-related script handles with `edd-`. This is a "breaking" change for direct access to `jquery-flot`, but using `\EDD_Graph` for legacy graphing will not be affected.
