### ISSUE TITLE
3.0 - Orders - New Order Draft Uses Invalid Date

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/easy-digital-downloads#7717]
### Expected behavior

When I create a new Order the "Order Attributes" should show the current date and time.

### Actual behavior

The "Date" field has an invalid date prefilled, such as `-0001-11-30`

### Steps to reproduce the behavior
1) Visit "Downloads > Orders > Add New"

### Information (if a specific version is affected):
EDD Version (or branch): `release/3.0`

Any other relevant information:

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/a958ab79f3a5129a2964076433e09c6fb377e1c4/includes/admin/payments/add-order.php#L30-L32

**Comment by ashleyfae** [comment]
This is naturally fixed here: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7578#issuecomment-586281961 Because the dates in the code you quoted were changed from `0000-00-00 00:00:00` to current time.

**Comment by spencerfinnell** [comment]
I knew we had it logged somewhere... Thanks @ashleyfae
