### ISSUE TITLE
Payment processing icon markup needs to be updated

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#7732]
### Expected behavior
Icons should be output using `<span>` instead of `<i>`. Most of the EDD code base has been updated to reflect this.

### Actual behavior
The `edd-icon-spinner` icon still uses `<i>`:
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/e8b2162876019684edf1abadb0d1cbbc81752b91/templates/payment-processing.php#L3

### Steps to reproduce the behavior
n/a

### Information (if a specific version is affected):
PHP Version: 7.3.5
EDD Version (or branch): all
WordPress Version: 5.4

Any other relevant information:
The sections component also uses `<i>` but a WIP PR #7728 fixes this. It looks like all other usages of icons/dashicons use `<span>`.

**Comment by cklosowski** [comment]
@SDavisMedia Are we going to have any issues here with the theming community within the EDD Ecosystem if we change the markup around these elements?

**Comment by SDavisMedia** [comment]
@cklosowski There shouldn't be any problems. We should be using `span`. The HTML has classes. Theme devs should be using those instead of generic HTML tags. If anyone has an issue, which I doubt will happen, they need to correct their approach to CSS selectors. That's my 2 cents.
