### ISSUE TITLE
3.0 - Orders - Move "Send Receipt" to Top Bar

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/easy-digital-downloads#7738]
### Explain your enhancement (please be detailed)

Move "Send Receipt" checkbox to the top bar next to "Create Order" and have it checked by default. 
### Justification or use case

When creating an order the option to "Send Receipt" is the very last item on the page. You can resend the receipt once the Order is created, but I think presenting the option on initial creation already opted-in better matches the similar WordPress pattern of creating a user:

<img width="625" alt="Screen Shot 2020-04-14 at 9 53 54 AM" src="https://user-images.githubusercontent.com/491124/79232714-df1fef80-7e35-11ea-96d8-5499b6118b09.png">

**Comment by spencerfinnell** [comment]
@LisaCee I started [`issue/7738`](https://github.com/easydigitaldownloads/easy-digital-downloads/tree/issue/7738) that pulls a few changes from https://github.com/easydigitaldownloads/easy-digital-downloads/pull/7599 that should help the checkbox align better in the top bar.

**Comment by LisaCee** [comment]
Are you envisioning something like this?  (Please excuse my poor/hacky image editing)

![image](https://user-images.githubusercontent.com/18077352/79516308-dbd85f80-7fff-11ea-93b3-3bb5490a5cac.png)

**Comment by spencerfinnell** [comment]
@LisaCee Yep! I think we should also change the label to "Send purchase receipt"

**Comment by cklosowski** [comment]
I'm going to punt this to a point release for fast follow. This is a minor improvement and can wait, so we can get closer to beta.

**Comment by LisaCee** [comment]
PR #7854
