### ISSUE TITLE
Introduce before and after actions within the shortcode-receipt template out-with the table tags

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#7747]
## Enhancement Request
I recently wanted to add functionality directly above the purchase receipt table, but no actions exist for this. The closest one was within the table header:

`do_action( 'edd_payment_receipt_before', $payment, $edd_receipt_args );
`
I would like to see actions added directly above and below the `<table>` tags. This would allow for easier third-party integration, without overriding template files.

### Justification or use case
Third-party integration.

**Comment by spencerfinnell** [comment]
@davidsherlock 3.0 has one coming _above_ the tables: https://github.com/easydigitaldownloads/easy-digital-downloads/commit/a958ab79f3a5129a2964076433e09c6fb377e1c4

A matching one for the end of the file makes sense.

**Comment by ashleyfae** [comment]
I think there already is one below? [`edd_payment_receipt_after_table`](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/templates/shortcode-receipt.php#L115)

Closing this as 3.0 has one before, and master has one below. Let me know if I missed something though.
