### ISSUE TITLE
3.0 - Trigger "doing it wrong" when "-1" is passed to query function that no longer supports it

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#7748]
### Explain your enhancement (please be detailed)

Split from here: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7690#issuecomment-608116847

> We’ve had a few discussions about if we should still support `-1` to mean `all the things`. In part, it can cause some serious scalability issues which was the goal to remove them and stop supporting them within the addition of BerlinDB.
> 
> I think we should maybe look at places where we stop supporting `-1` and throw a doing it wrong, but for this issue, we should just fix the usage to the correct function.

This is relevant to functions that have been reworked with the introduction of BerlinDB in 3.0.

### Justification or use case

Conveying to developers that `-1` should no longer be used as a way to "get all results".

**Comment by cklosowski** [comment]
References to `-1` that are not used in `get_posts` calls, and other non-related calls:
includes/admin/reporting/class-export-customers.php:137 `'limit' => -1`
includes/admin/reporting/class-export-payments.php:105 `'number' => -1,`
includes/admin/upgrades/upgrade-functions.php:682 `'number'  => -1,`
includes/payments/actions.php
		325 `'number' => -1,`
		361 `'number' => -1,`
