### ISSUE TITLE
3.0 - Update Linked Hour/Minute Fields

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#7750]
### Explain your enhancement (please be detailed)
Where two separate inputs are used to set a time, update them to use number inputs. Additionally, update the markup to clearly and semantically indicate that these fields are related.

### Justification or use case
On the new/update order screen, the time is currently set using two separate `<select>` inputs, which also implement `chosen`. These two inputs are ideal for changing to an actual number input, because we can set the minimum/maximum values, and the values can be adjusted incrementally.

Similar hour/minute select fields are implemented on the discounts screens, but without implementing `chosen`.

> Also, thinking through our discussions about radio inputs and grouped controls, I did some more digging and I think the hour/minute inputs would benefit from being "grouped" using a `<fieldset>` as they are interdependent.
> - see especially the [SSN example](https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA17) on the W3 site
> - [address field](https://www.w3.org/WAI/WCAG21/Techniques/html/H71) as an example as well, so maybe we should consider doing the same with our address field groups
> - consider using `aria-labelledby` to provide additional context for [fields in groups](https://www.w3.org/WAI/tutorials/forms/grouping/#associating-related-controls-with-wai-aria)

_Originally posted by @robincornett in https://github.com/easydigitaldownloads/easy-digital-downloads/pull/7744_

**Comment by ashleyfae** [comment]
Fixed in https://github.com/easydigitaldownloads/easy-digital-downloads/pull/7956

(@robincornett feel free to reopen if you think that PR missed something)
