### ISSUE TITLE
3.0 - Add/Edit discount flat rate hard-codes USD symbol despite currency settings

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#7757]
### Expected behavior

When I select a currency that is not USD, I expect all references to amounts to reflect my currency settings. I shouldn't see `$` to indicate currency. If I've selected GBP as  my currency then I should see `£` instead.

### Actual behavior

When I add a discount and want to select a flat rate, I see the `$` symbol to indicate a flat amount instead of `£`.

![Screenshot from 2020-04-20 13-31-24](https://user-images.githubusercontent.com/6324272/79751890-4690e000-830b-11ea-97dc-8fc3376c1fa1.png)

![Screenshot from 2020-04-20 13-31-53](https://user-images.githubusercontent.com/6324272/79751911-4e508480-830b-11ea-90b0-5c55fc9532e8.png)

### Steps to reproduce the behavior
1) Go to Downloads > Settings > Currency and set your currency to anything that is not USD.
2) Go to Downloads > Discounts and add a discount.
3) For the `Amount` column, click the dropdown to change from `%` to a flat rate. You'll see a hard-coded `$` symbol.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0

WordPress Version:

Any other relevant information:

**Comment by robincornett** [comment]
@ashleyfae the `%` is included in the output as a translatable string. It doesn't seem like it should be. What do you think?

**Comment by ashleyfae** [comment]
@robincornett My instinct would say it doesn't need to be.
