### ISSUE TITLE
3.0 - Partially refunding an order removes ability to download all products from order

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#7758]
### Expected behavior

I have an order with two products: "WordPress Theme" and "WordPress Plugin". If I refund just "WordPress Theme" then I expect the customer is still able to download "WordPress Plugin" because this item was not refunded.

### Actual behavior

If one item in the order is refunded, then the download links for the **entire order** are removed.

Here are some screenshots:

**After purchase (before refund)**

![Screenshot from 2020-04-20 13-49-01](https://user-images.githubusercontent.com/6324272/79753811-6d044a80-830e-11ea-8373-c70af12ff095.png)

**Processed partial refund**

![Screenshot from 2020-04-20 13-49-58](https://user-images.githubusercontent.com/6324272/79753828-742b5880-830e-11ea-9e7e-a24f3a6cb6f9.png)

**Customer's view after partial refund**

![Screenshot from 2020-04-20 13-50-20](https://user-images.githubusercontent.com/6324272/79753848-7beafd00-830e-11ea-80b3-6a21d244d3bf.png)

![Screenshot from 2020-04-20 13-53-29](https://user-images.githubusercontent.com/6324272/79753853-7e4d5700-830e-11ea-9d0c-5de7d9f6b834.png)

### Steps to reproduce the behavior
1) Complete an order that contains at least two different products.
2) Refund just one of the line items.
3) Refresh your customer account page with the `[download_history]` and/or `[purchase_history]` shortcodes. Download links are removed.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0

WordPress Version:

Any other relevant information:

**Comment by ashleyfae** [comment]
This is ready for some testing. Things to check:

- After completing an order you should be able to download files as normal.
- If you place an order with two items, then one gets refunded, you should still be able to download the one that's not refunded.
- If you manually navigate to the download URL for the item that _was_ refunded (might be wise to copy this before refunding), then you should not be given access.
- Ensure everything displays as expected in purchase history and download history shortcodes.

**Comment by spencerfinnell** [comment]
Related https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6678 for the template changes. 

@ashleyfae Can we add some file header comments to the template files with the 3.0 changes outlined?

**Comment by ashleyfae** [comment]
@spencerfinnell :+1: Added.
