### ISSUE TITLE
3.0 - Cannot set 0 as the Refund Window. Always defaults back to 30.

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#7774]
### Expected behavior
When trying to set an infinite refund window with the value of `0`, after saving the settings the value of `0` should remain.

### Actual behavior
When trying to set the refund window to `0`, it is always reset back to `30`, which is the default value.

### Steps to reproduce the behavior
1) Go to Downloads > Settings > Refunds
2) Set the value of `Refund Window` to `0`.
3) Click 'Save'

### Information (if a specific version is affected):
PHP Version: All

EDD Version (or branch): `release/3.0`

WordPress Version: All

Any other relevant information:

**Comment by spencerfinnell** [comment]
@cklosowski Previously: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6891

**Comment by cklosowski** [comment]
@spencerfinnell I think that is a little overreaching...the key is that we don't have a 'number' type when we save register settings, and it doesn't respect the min/max of those fields (which are supported).

I think we can have a very minimal impact on saving settings by just adding a condition in the switch for the `number` type. I'm going to make a more surgical approach to this than an overhaul. Going to work up a PR and see if it is less impact-havy to the settings saving.
