### ISSUE TITLE
3.0 - Dropdown Options for "Export File Download Logs" Are Not Visible

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#7785]
### Expected behavior
When I click on the download selection input for the "Export File Download Logs", I expect to see the list of downloads.

### Actual behavior
When I click on it, I can only see the search box.
![image](https://user-images.githubusercontent.com/4853066/80240275-91726680-862f-11ea-8576-38fae4987ecf.png)

### Steps to reproduce the behavior
1) In 3.0, visit Reports > Export
2) Scroll down to the bottom of the page
3) Click to select a download

### Information (if a specific version is affected):
PHP Version: all
EDD Version (or branch): 3.0
WordPress Version: 5.4

**Comment by spencerfinnell** [comment]
@LisaCee I believe this can be fixed by removing some `overflow: hidden` rule somewhere in the vertical tabs CSS hierarchy that is likely left over from when it was using floats.

**Comment by LisaCee** [comment]
PR #7981
