### ISSUE TITLE
3.0 - Tax Rates - Pressing "Enter" while in rate field should create new tax rate

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#7787]
### Explain your enhancement (please be detailed)

When adding a new tax rate, when you're focused in the "Rate" input field, you should be able to press "Enter" to add the new rate (essentially trigger a click on "Add Rate" button).

![Screenshot from 2020-04-27 13-17-27](https://user-images.githubusercontent.com/6324272/80371228-74d16b00-8889-11ea-847f-6d9ed66cd5c0.png)

### Justification or use case

User experience.

**Comment by spencerfinnell** [comment]
Related #7629

**Comment by spencerfinnell** [comment]
PR #7994 adds the ability to add a rate via the "Enter" key.

Note: You can add a blank rate with the Enter key, just as you can add one by pressing the button currently. Further UX updates to prevent invalid rates can be added in a follow up at a later date.

**Comment by cklosowski** [comment]
@spencerfinnell Let's make sure we get a Post-Alpha issue opened up for UX improvements to the Tax Rates UI, including that you can re-activate a country wide tax when an existing country wide tax exists, leaving both active.

**Comment by spencerfinnell** [comment]
@cklosowski 👍 Follow up in https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7992
