### ISSUE TITLE
3.0 - Order Time is displaying incorrectly

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#7794]
### Expected behavior
When I create an order, I expect the displayed time of the order to match the time the order was placed.

### Actual behavior
When I create an order, the default time is set to the current time. When I save it and the screen reloads, the displayed time is five hours earlier. For example, I created an order today at 10:01. When I saved the order and the screen reloaded, the time displayed was 6:01.

### Steps to reproduce the behavior
1) In Settings > General, pick a time zone (mine is New York)
2) Add a new order. Note the time fields before clicking the create order button.
3) Save the order and watch the time change.

### Information (if a specific version is affected):
PHP Version: 7.3.5
EDD Version (or branch): release/3.0
WordPress Version: 5.4

Any other relevant information:
If I dump `EDD()->utils->date( $order->date_created, 'utc', true )` from where the [time is displayed](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/payments/orders.php#L922), the date string returned is `'2020-04-28 10:01:00.000000'`, so the value in the database is correct, but the display is not.

**Comment by LisaCee** [comment]
I'm still digging in to the fix, but I'm pretty sure the time is being changed in this block:

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/9465051f819b7a7f0cda4d6f8a881557d854308c/includes/admin/payments/orders.php#L1014-#L1028

**Comment by robincornett** [comment]
I was looking here:

If I dump this (before the conversion):

```php
EDD()->utils->date( $order->date_created, get_option( 'timezone_string' ), true )
```

I get:
```
object(EDD\Utils\Date)[15016]
  public 'date' => string '2020-04-28 10:21:00.000000' (length=26)
  public 'timezone_type' => int 2
  public 'timezone' => string 'UTC' (length=3)
```
which is correct, but then if I dump the `$order_item` variable, I get:
```
object(EDD\Utils\Date)[14917]
  public 'date' => string '2020-04-28 06:21:00.000000' (length=26)
  public 'timezone_type' => int 3
  public 'timezone' => string 'America/New_York' (length=16)
```

**Comment by LisaCee** [comment]
Still thinking this thing through, but please correct me if I'm wrong here @robincornett , @spencerfinnell 

![image](https://user-images.githubusercontent.com/18077352/80540890-04951900-895f-11ea-9148-c71709145065.png)

The first output should be UTC, right?  Because it's actually PST - the actual time I placed the order.  

I'm still researching time/date in PHP, especially `timezone_type`, but I think I'm getting closer.  Or maybe I'm way off...

**Comment by LisaCee** [comment]
> I was looking here ([link](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/9465051f819b7a7f0cda4d6f8a881557d854308c/includes/admin/payments/orders.php#L922)):
> 
> If I dump this (before the conversion):
> 
> ```
> EDD()->utils->date( $order->date_created, get_option( 'timezone_string' ), true )
> ```
> 
> I get:
> 
> ```
> object(EDD\Utils\Date)[15016]
>   public 'date' => string '2020-04-28 10:21:00.000000' (length=26)
>   public 'timezone_type' => int 2
>   public 'timezone' => string 'UTC' (length=3)
> ```
> 
> which is correct, but then if I dump the `$order_item` variable, I get:
> 
> ```
> object(EDD\Utils\Date)[14917]
>   public 'date' => string '2020-04-28 06:21:00.000000' (length=26)
>   public 'timezone_type' => int 3
>   public 'timezone' => string 'America/New_York' (length=16)
> ```

Clarifying question for you: Was the time you placed the order 6:20am EST or 10:20am EST?

**Comment by ashleyfae** [comment]
> Still thinking this thing through, but please correct me if I'm wrong here @robincornett , @spencerfinnell
> 
> ![image](https://user-images.githubusercontent.com/18077352/80540890-04951900-895f-11ea-9148-c71709145065.png)
> 
> The first output should be UTC, right? Because it's actually PDT - the actual time I placed the order.
> 
> I'm still researching time/date in PHP, especially `timezone_type`, but I think I'm getting closer. Or maybe I'm way off...

Yes you're right. The date passed into `edd_get_edd_timezone_equivalent_date_from_utc()` should be in UTC. The one returned back should be in your local site time.

Also, just to clarify: every date the user sees in the UI should be in their local site time. Then on save, that gets converted into UTC for storage.

Example:

- User adds new order. Date entered/displayed is in local time.
- User saves.
- Date in local time gets converted to UTC for storage.
- Page refreshes.
- Date is retrieved out of database in UTC, converted to local time, then this local time is displayed back to the user again.

**Comment by robincornett** [comment]
I was placing orders at 10am local time (which is how my server is set).

**Comment by ashleyfae** [comment]
Dug into this some more.

The issue is with the arguments being passed into `edd_add_manual_order()`. That accepts an array of `$args` and `edd-payment-date`, `edd-payment-time-hour`, and `edd-payment-time-min` are being passed in, and that's basically just the `$_POST` data, so it's in the user's time zone. If present (so before the `Parse args` bit), those dates need to be converted to UTC.

**Comment by spencerfinnell** [comment]
It looks like `edd_update_payment_details()` handles the conversion correctly. The process there should be ported to `edd_add_manual_order()`.

**Comment by LisaCee** [comment]
PR #7802
