### ISSUE TITLE
3.0 - Migration - Check if `edd_customer_id` exists in customer_email_addresses() before using

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#7806]
### Expected behavior

When I run the 3.0 migration I expect to not get any PHP notices.

### Actual behavior

I got the following notice:

```
PHP Notice:  Undefined property: stdClass::$edd_customer_id in /var/www/shop/wp-content/plugins/easy-digital-downloads/includes/admin/upgrades/v3/class-data-migrator.php on line 83
```

### Steps to reproduce the behavior

This is probably something weird with my site's data so not sure if it can be reproduced on command. I only got it once. We should just exit if `$data->edd_customer_id` isn't set.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0

WordPress Version:

Any other relevant information:

**Comment by ashleyfae** [comment]
Actually this may have been because I borked my install. Please hold. :D

**Comment by ashleyfae** [comment]
Yeah that was something I screwed up with my customer meta table. The issue no longer happens since fixing that.

However, this is an easy fix and a good idea to check for anyway, so let's still make the change. :+1:

**Comment by robincornett** [comment]
Since the function also expects `$data->meta_value` to be set (and doesn't use anything else that might be passed through in `$data`), should the condition at the beginning maybe just check to make sure that both `meta_value` and `edd_customer_id` are set, instead of checking the entire object?
