### ISSUE TITLE
3.0 - Downloads - "0" Values Saving Meta for Download Type

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/easy-digital-downloads#7811]
### Expected behavior

When saving a Download with the "Default" product type, no `_edd_product_type` metadata should be saved.

### Actual behavior

`_edd_product_type` saves a `0` value.

### Steps to reproduce the behavior
1) Save a Download with the "Default" product type.

### Information (if a specific version is affected):
EDD Version (or branch): `release/3.0`

Any other relevant information:

Introduced in https://github.com/easydigitaldownloads/easy-digital-downloads/commit/8da7e908d7e86920293ffc7c79e4329f3542b8f2

This is breaking things that rely on meta queries using `NOT EXISTS` comparators, such as the Products dropdown excluding Bundles.

**Comment by spencerfinnell** [comment]
I like the correction of the save behavior and don't think we should rely on a 0 value to delete a meta key, so special handling for that specific key for backwards compatibility might be the path forward.

**Comment by spencerfinnell** [comment]
We should also update the meta query to match what is in the AJAX search:

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/9893c4f5e7a5ebd3c00d7b549e45cc47b64b448b/includes/ajax-functions.php#L634-L641

vs the current `NOT EXISTS`

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/9893c4f5e7a5ebd3c00d7b549e45cc47b64b448b/includes/class-edd-html-elements.php#L84-L91

**Comment by LisaCee** [comment]
PR #7816
