### ISSUE TITLE
3.0 - Add Order UI - "Call to a member function get_meta() on bool" fatal error

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#7819]
### Expected behavior

When I go to the Add New Order page, I expect to not see any fatal errors.

### Actual behavior

The following error is thrown:

```
PHP Fatal error:  Uncaught Error: Call to a member function get_meta() on bool in /var/www/edd3/wp-content/plugins/easy-digital-downloads/includes/admin/payments/orders.php:278
```

Related to this change: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7788

We just missed the fact that this hook was also running on the Add Order UI, at which point the order (or `$payment`) doesn't yet exist.

Perhaps we should consider not triggering the `edd_payment_personal_details_list` hook at all if there's no order/payment. The hook didn't used to run on the manual payments Add Payment UI.

### Steps to reproduce the behavior
1) Go to Downloads > Orders and click to add a new one.
2) Error will immediately trigger.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0

WordPress Version:

Any other relevant information:

**Comment by spencerfinnell** [comment]
Checking if we are on the Add Order page and skipping that hook makes sense to me.
