### ISSUE TITLE
3.0 - Migration - Secondary customer email addresses can be added twice

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#7822]
### Expected behavior

When I perform the migration, I expect each customer email address to only be added once. There should not be any duplicates in the customer_email_addresses table.

### Actual behavior

A few email addresses are being duplicated. All of the duplicates are `secondary` emails. Here's where the issue is:

First, **orders** are migrated. During this step, emails are added here: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/upgrades/v3/class-data-migrator.php#L570-L574 With my data set, this is where a secondary customer address is added for the first time. This is coming from the order information record.

Second, the **customer email addresses** are migrated. This runs this segment: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/upgrades/v3/class-data-migrator.php#L76-L89 However, this block of code just blindly adds another record for a `secondary` email address. It doesn't first check to see if a record with that email already exists.

To fix this, we should check if the email already exists before adding it.

### Steps to reproduce the behavior

Don't have exact reproduction steps since this is coming from my live data set. From the code, it looks like this could happen when one customer has a set up like this:

- Primary email set to primary@test.com
- Has an `additional_email` saved in customer meta. Let's call this secondary@test.com.
- Has an order associated with secondary@test.com.

So they key is having an order record associated with that secondary email. That causes the email to get imported twice.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0

WordPress Version:

Any other relevant information:

**Comment by ashleyfae** [comment]
I have a good data set to actually test this, so @robincornett want to tackle working up a PR?

**Comment by robincornett** [comment]
As I'm working on this and inadvertently creating duplicate email addresses, I'm discovering some inconsistent behavior, but I'm not sure if it's an item of concern or not:
* on an individual customer screen, if a customer has multiple identical addresses in the database, the duplicates will not show
* on the customer list table for email addresses (`wp-admin/edit.php?post_type=download&page=edd-customers&page_type=emails`), duplicated email addresses for a customer will show
* if I attempt to delete an email address from the main lists table, I get an "Error: Invalid Customer ID Provided." message (I think this may be a real issue so will open that separately)

So when looking at an individual customer record, it is not readily apparent that there are duplicate addresses added to the database, but the duplicate addresses do show in the list table.
