### ISSUE TITLE
3.0 - CLI migration has confusing messaging on log migration 

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#7835]
### Expected behavior
When migrating logs I expect the count to be the same from the old and new logs.

### Actual behavior
The log numbers from old and new differ since we moved some of the data out of the logs an into other areas, so they are no longer considered logs.

While no data should be lost in the migration, it could appear to the user that there is a data loss here, so we either need to change the messaging with a note that this doesn’t include things like sales logs (which are now Order Items, and not logs)...or we just remove the count entirely, which I think is the proper way to go here.

### Information (if a specific version is affected):
PHP Version: All

EDD Version (or branch): `release/3.0`

WordPress Version: All

Any other relevant information:

**Comment by ashleyfae** [comment]
There is already an effort to combine the new counts across tables:

```php
$new_count = edd_count_logs() + edd_count_file_download_logs() + edd_count_api_request_logs();
```

I think what's actually inaccurate is the old count. The query for counting is different from the query for fetching results.

Count:

```php
$old_count = $wpdb->get_col( "SELECT count(ID) FROM {$wpdb->posts} WHERE post_type = 'edd_log'", 0 );
```

Getting results:

```php
$sql = "
	SELECT p.*, t.slug
	FROM {$wpdb->posts} AS p
	LEFT JOIN {$wpdb->term_relationships} AS tr ON (p.ID = tr.object_id)
	LEFT JOIN {$wpdb->term_taxonomy} AS tt ON (tr.term_taxonomy_id = tt.term_taxonomy_id)
	LEFT JOIN {$wpdb->terms} AS t ON (tt.term_id = t.term_id)
	WHERE p.post_type = 'edd_log' AND t.slug != 'sale'
";
```

The one for getting results has an extra WHERE clause that could affect the count.

**Comment by ashleyfae** [comment]
New results:

![Screenshot from 2020-05-12 14-08-27](https://user-images.githubusercontent.com/6324272/81695262-4ee7c100-945a-11ea-849c-14c27a699220.png)

**Comment by spencerfinnell** [comment]
Are the inconsistencies with Payments and Notes known? Testing #7872 matches the Logs count, but I see differences in Payments and Notes using your export @ashleyfae

**Comment by ashleyfae** [comment]
@spencerfinnell Hm that's odd. I'm not seeing any differences.

![Screenshot from 2020-05-12 14-49-10](https://user-images.githubusercontent.com/6324272/81699832-c704b580-945f-11ea-84cc-bc4df3ef057f.png)

This should be the same database I gave you. What do your numbers look like?

**Comment by spencerfinnell** [comment]
Sorry @ashleyfae, false alarm. I had some existing 3.0 records. 🤦
