### ISSUE TITLE
3.0 - Update #edd-item-wrapper CSS for backwards compatibility

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#7838]
### Expected behavior
When I view a screen using `#edd-item-wrapper`, I expect it to look the same in 2.9 and 3.0.

### Actual behavior
Due to CSS changes for the vertical sections, CSS floats have been removed from the admin CSS.

### Steps to reproduce the behavior
1) Enable an extension which uses `#edd-item-wrapper` markup (Software Licensing is one)
2) Visit a screen which uses it (`/wp-admin/edit.php?post_type=download&page=edd-licenses&view=overview&license_id=xx`)

### Information (if a specific version is affected):
PHP Version: any
EDD Version (or branch): release/3.0
WordPress Version: any

Any other relevant information:
Adding `display: flex;` to the [`#edd-item-wrapper` CSS](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/assets/css/edd-admin.css#L3095-L3102) should resolve the issue.

**Comment by LisaCee** [comment]
PR #7865
