### ISSUE TITLE
3.0 - CLI Migration - "EDD\Database\Tables\Base" is not a valid class  

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#7841]
## Bug Report

This doesn't show any errors or cause any specific problems _as long as you have the EDD3 tables installed already_.

The CLI has numerous instances of this:

```php
foreach ( $components as $component ) {
	/** @var EDD\Database\Tables\Base $table */
	$table = edd_get_component_interface( $component[0], $component[1] );

	if ( $table instanceof EDD\Database\Tables\Base && ! $table->exists() ) {
		@$table->create();
	}
}
```

However, `EDD\Database\Tables\Base` does not exist. The correct class is `EDD\Database\Table`.

Again, this doesn't cause any actual errors, but it would if for some reason you ran the command without the database tables having already installed.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0

WordPress Version:

Any other relevant information:

**Comment by spencerfinnell** [comment]
> Again, this doesn't cause any actual errors, but it would if for some reason you ran the command without the database tables having already installed.

Which can happen if you just switch branches and don't visit the WP install. This happened the first time I tested the migration. For the CLI migration to be fully automated can we run the DB install routine first?

**Comment by robincornett** [comment]
This may be what happened to me on my first migration attempt, because I finished the migration and a lot of the new customer related tables had not been created.
