### ISSUE TITLE
3.0 - Order Addresses - Changing country doesn't change region list

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#7842]
### Expected behavior

When I change the "Country" value, I expect the list of available regions to change according to the selected country.

### Actual behavior

The list of regions does not change. I can see the ajax request firing and the correct results appearing in that response, but the DOM doesn't change.

### Steps to reproduce the behavior
1) Go to Downloads > Orders and create a new order.
2) Go to the Address tab and change the country to something other than the default.
3) Then click the Region dropdown and you'll see the region list hasn't updated for the new country selection.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0

WordPress Version:

Any other relevant information:

**Comment by spencerfinnell** [comment]
Looks like this ID needs to get added back to the control wrapper: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/payments/orders.php#L455-L456

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/assets/js/admin/orders/order-details/address.js#L167

**Comment by LisaCee** [comment]
PR #7851
