### ISSUE TITLE
3.0 - Orders - Unwrapped Long Lines

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/easy-digital-downloads#7843]
### Expected behavior

When using `.edd-admin-box-inside--row` with items that have a long value, the values should be wrapped.

### Actual behavior

They overflow and cause scrollbars.

### Steps to reproduce the behavior
1) Create an order with a very long Transaction ID.
2) View Order.

### Information (if a specific version is affected):
EDD Version (or branch): `release/3.0`

Any other relevant information:

<img width="392" alt="Screen Shot 2020-05-07 at 10 55 46 AM" src="https://user-images.githubusercontent.com/491124/81309816-5883ba00-9051-11ea-9aaa-530641c544ae.png">

I think we should wrap long values when using `.edd-admin-box-inside--row` so they go to the next line.

**Comment by LisaCee** [comment]
`.edd-admin-box-inside--row` has a CSS rule `display: flex;` that keeps the id overflowing.  If I remove that rule, it wraps but it also moves the IP and Gateway to the left.
![image](https://user-images.githubusercontent.com/18077352/81451780-1f734480-913a-11ea-9ce7-95fa907e46db.png)

Would it be okay to add a CSS rule to `edd-order-tx-id` or is there a better way to handle this?

**Comment by spencerfinnell** [comment]
@LisaCee check out https://developer.mozilla.org/en-US/docs/Web/CSS/flex-wrap and https://developer.mozilla.org/en-US/docs/Web/CSS/word-break

**Comment by LisaCee** [comment]
PR #7852
