### ISSUE TITLE
3.0 - Assets - Localizations Not Always Loaded

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/easy-digital-downloads#7847]
### Expected behavior

When using `edd_load_scripts()` directly the relevant scripts should be enqueued and localized.

### Actual behavior

Scripts are only enqueued, not localized. 

### Steps to reproduce the behavior
1) Call `edd_load_scripts()` directly.

Observe `edd_global_vars` is not available.

### Information (if a specific version is affected):

EDD Version (or branch): `release/3.0`

Any other relevant information:

Related #7839

**Comment by LisaCee** [comment]
PR #7918
