### ISSUE TITLE
3.0 - Free Purchases Show Incorrrect Gateway in Orders List Table

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#7848]
### Expected behavior
When I view the Orders table, I expect to see the correct gateways.

### Actual behavior
Free purchases show as "Test Payment" in the orders list table. The gateway does show correctly as "Free Purchase" on the order details and customer details screens.

### Steps to reproduce the behavior
1) Create a free download and sell it.
2) View the order in the orders list table--it shows "Test Payment" as the gateway.
3) Click on the order to view the details--it shows "Free Purchase" as the gateway.
4) Click "View customer record" to view the customer details--the order shows as "Free Purchase" as the gateway.

### Information (if a specific version is affected):
PHP Version: 7.3.5
EDD Version (or branch): 3.0
WordPress Version: 5.4.1

**Comment by ashleyfae** [comment]
I think this would be covered by this: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7067 (which isn't clear in the title but implied with this comment: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7067#issuecomment-570465697)

**Comment by robincornett** [comment]
I think this may actually be a different issue. "Free Purchase" shows correctly in two different locations, but not in the main Orders table. I think this is coming from the function which displays/converts the admin labels, specifically:

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/a13528027b6cc0392a23bc88453d963a4e517401/includes/gateways/functions.php#L190-L198

On the order and customer screens, `$payment` is an integer because it's being defined by the `$_GET['id']`, which is not present on the list table and is therefore false. On the customer details screen, however, since the id is for a customer, not a payment, the gateway shows as "Test Payment" instead of "Free Purchase".

Note: I'm seeing this with new orders for free downloads and in migrated orders.

**Comment by robincornett** [comment]
Note: this code is the same in 2.9 but is not an issue because the gateway doesn't show on the payments list table.

**Comment by robincornett** [comment]
I think this could be fixed by adding the payment/order ID as an optional parameter to the `edd_get_gateway_admin_label` function:

```php
function edd_get_gateway_admin_label( $gateway, $payment = false ) {
	$gateways = edd_get_payment_gateways();

	$label = isset( $gateways[ $gateway ] )
		? $gateways[ $gateway ]['admin_label']
		: ucwords( $gateway );

	if ( ! $payment && isset( $_GET['id'] ) ) {
		$payment = absint( $_GET['id'] );
	}

	if ( 'manual' === $gateway && $payment ) {
		if ( ! edd_get_payment_amount( $payment ) ) {
			$label = __( 'Free Purchase', 'easy-digital-downloads' );
		}
	}

	return apply_filters( 'edd_gateway_admin_label', $label, $gateway );
}
```

If an ID is not passed because it's not available, or not needed, it will work as it has historically, but if one is, the function can now determine if the order was a free purchase, as in the order table or on the [receipt template](https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7067#issuecomment-524061615), or a manual (test?) purchase, if it was created manually and has a value attached. So historic purchase data for free downloads will show the correct gateway in the order table and on the customer details screens. @cklosowski does this feel workable?

**Comment by cklosowski** [comment]
So this is a long standing issue around manual and free payments. Manually crated payments (no matter the amount) use `manual` if no gateway is selected.

Free purchases on the front end, also get set to `manual` as the gateway.

```
	// Override to manual if no price
	if ( edd_get_cart_subtotal() <= 0 ) {
		$retval = 'manual';
	}
```

This leaves us in a weird state as orders with an actual amount manually created will say "Test Payment" when it really isn't a test.

Free purchases on manual payments will say "Free Purchase"

Front end, free purchases will say "Free Purchase".

I think we need to focus on #7067 To determine if we want to just 'rename' the `manual` gateway to something more generic. That would solve all of the problems as we could just get rid of all the logic of `Test Payment` or `Free Purchase`. It will also stop us from having two different labels for the same `manual` key, which causes some concerns since we shouldn't have two different labels for a single key.

**Comment by robincornett** [comment]
I agree that having two different labels for a single key is not ideal, but if we separate manual/paid and manual/free into two different keys, do we also need to add an evaluation/update for that into the migration routine, as not all previously existing manual purchases will also be free (or paid)?

I think expanding the scope/parameter of the `edd_get_gateway_admin_label ` function is a middle ground option which might be worth doing anyway--it allows the visual label to display appropriately based solely on the amount.

One area where two different keys would be helpful is the Downloads > Reports > Payment Gateways report, so that free purchases could be distinguished from manual/paid purchases.

**Comment by cklosowski** [comment]
I don’t think we can realistically achieve that with the scope of 3.0 at this time, as it would take an enormous amount of assumption made in the Free Downloads and Manual Purchases add on data that exist.

I would just prefer to focus on making a single label that we share for these two that is agnostic to both cases. We can look for a better way to achieve the designation between manually created and actual free purchases at a later time, but at this time simply updating the label resolves this conflict without completely changing the scope of the final 3.0
