### ISSUE TITLE
3.0 - Migration - "Trying to access array offset on value of type bool" when payment meta is invalid

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#7855]
### Expected behavior

I expect to not get any PHP notices when I run the migration.

### Actual behavior

I get the following error:

> PHP Notice:  Trying to access array offset on value of type bool in /var/www/eddexport/wp-content/plugins/easy-digital-downloads/includes/admin/upgrades/v3/class-data-migrator.php on line 338

The reason I get this error is because my install has a few corrupted post meta instances. The serialization is messed up, which means the payment meta cannot be unserialized. Therefore, this line returns `false` instead of an array:

```php
$payment_meta = maybe_unserialize( $meta['_edd_payment_meta'][0] );
```

Because that is `false`, this next line throws the notice:

```php
$user_info    = maybe_unserialize( $payment_meta['user_info'] );
```

Obviously this is largely an error with my data set, but if I have this problem then it's possible a few other people have this problem too. Our code could be written a bit more defensively to handle this.

### Steps to reproduce the behavior
1) Start on 2.9. Edit one of your `_edd_payment_meta` meta values to break the serialization somehow.
2) Do the 3.0 upgrade.
3) You'll see the notice when that broken order gets migrated.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch):

WordPress Version:

Any other relevant information:

**Comment by robincornett** [comment]
My dataset (from my own storefront) has the same error in it--had noted last week and was planning on opening an issue for it this week as well.

**Comment by robincornett** [comment]
I've tracked down the two affected orders in my dataset. The orders were partially migrated. Data which survived the migration includes:
- associated customer
- gateway
- associated license key
- whether the purchase was a renewal (both were)
- transaction ID
- key
- order date/time
- order notes

What did not survive the migration:
- any downloads in the order
- subtotal
- total
- customer address (this would have been collected as my storefront is required to collect sales tax for TN)

Both orders were for the same customer, but this customer has three other orders which migrated successfully.

**Comment by ashleyfae** [comment]
The downloads, address, subtotal, and total would have been stored in `_edd_payment_meta`. I think all the fields you mentioned that did make it through were stored in their own separate meta keys. So it sounds like `_edd_payment_meta` is corrupted for you but the others weren't.

---

Out of curiosity, @robincornett , what happens when you view an affected order in a 2.9 environment? If I remember rightly, when I tried, there were no downloads/order total/etc. present in 2.9, presumably also because the `get_post_meta()` call returned `false`. Is that the same for you?

If so, it's a crappy situation but would mean the end result in 3.0 isn't any different than what's currently going on in 2.9.

Ideally it would be nice to be able to fix the serialization, but ugh. That's a gross thing to do.

**Comment by robincornett** [comment]
Looking at the original orders in the storefront, you're right--the downloads which would have been in the cart are missing. However, the purchase **total** still shows, which means the order at least "looks" correct in the customer details screen (and the total is present on the edit order screen). And it looks like I could go ahead and attach the download in the original order by editing it, but 3.0 doesn't allow that anymore.

The customer lifetime value matches pre/post migration, even though the order totals look wrong.

**Comment by ashleyfae** [comment]
> Looking at the original orders in the storefront, you're right--the downloads which would have been in the cart are missing. However, the purchase **total** still shows, which means the order at least "looks" correct in the customer details screen (and the total is present on the edit order screen). And it looks like I could go ahead and attach the download in the original order by editing it, but 3.0 doesn't allow that anymore.
> 
> The customer lifetime value matches pre/post migration, even though the order totals look wrong.

Confirmed with mine as well.

In master, the total amount is fetched from a separate meta key - `_edd_payment_total` so that's still retained outside the corrupted payment meta.

**Comment by ashleyfae** [comment]
PR #7870 only partially fixes this.

What it does do is add a fallback to get the `total` and `tax` values into the database. However, the UI will still show the totals and subtotals as 0, because the UI relies on building the information from order items and we still have those.

Unless we actually fix the serialization issue this might be as good as we're going to get.
