### ISSUE TITLE
3.0 - Typo in text domain in "tmpl-order-refund.php"

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#7856]
### Expected behavior

I expect the text domain to be `easy-digital-downloads`

### Actual behavior

Here: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/views/tmpl-order-refund.php#L25 there's a typo and it's `easy-digitald-downloads` . The `digitald` just needs to be changed to `digital`.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0

WordPress Version:

Any other relevant information:

**Comment by LisaCee** [comment]
PR #7862
