### ISSUE TITLE
3.0 - SQL syntax/database error on initial activation

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#7857]
### Expected behavior
When I update from EDD 2.9 to 3.0, I expect not to have errors.

### Actual behavior
When I update to 3.0 (before doing a migration), I get this error:

`[08-May-2020 13:48:51 UTC] WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CURRENT_TIMESTAMP' at line 1 for query ALTER TABLE mce_edd_customers ALTER COLUMNdate_createdSET DEFAULT CURRENT_TIMESTAMP made by require_once('wp-admin/admin.php'), do_action('admin_init'), WP_Hook->do_action, WP_Hook->apply_filters, EDD\Database\Tables\Customers->maybe_upgrade`

@ashleyfae suggested changing line 105 to this:

```php
$this->get_db()->query( "ALTER TABLE {$this->table_name} MODIFY `date_created` datetime NOT NULL default CURRENT_TIMESTAMP" );
```
and after dropping tables and starting fresh with that, I did not get the error.

I dropped tables again, reverted the line of code, and got the error again.

### Steps to reproduce the behavior
I'm not sure how reproducible this is, although I get the error every time. I'm running MySQL 8.0.16, and I set up a fresh WordPress install with active EDD 2.9 data. Switch to EDD 3.0 and get the above error, but it appears to happen only once and then goes away, and migration proceeds more or less successfully.

### Information (if a specific version is affected):
PHP Version: 7.3.5
EDD Version (or branch): 3.0
WordPress Version: 5.4.1

Any other relevant information:
[Original report](https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7578#issuecomment-625895293)

**Comment by cklosowski** [comment]
`MODIFY` is the right choice here. The only time we cannot use `MODIFY` is when renaming a column. It can only be used to alter the definition of a column.
