### ISSUE TITLE
3.0 - PHP Notice When Viewing an Order for a Non-Existent User

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#7860]
### Expected behavior
When I view order details, I expect no errors.

### Actual behavior
After migrating to 3.0, when I view an order for a customer, I sometimes, but not always, get this notice:

`PHP Notice:  Trying to get property 'display_name' of non-object in \includes\admin\notes\note-functions.php on line 79`

I'm looking at a customer with five orders and one of them consistently triggers this notice multiple times on the order screen. I can't readily see a difference between the order details for this order and the ones which are not throwing the error.

### Steps to reproduce the behavior
Honestly not sure how to reproduce this. Looking at the affected order, these are notes for Stripe, Mailchimp, and general store info for this order--on the live site for this order, the customer name is showing as the note "author", but if I view another order for this customer, the note "author" is EDD Bot (or Store Bot in 3.0). So I think there may be some kind of data error with this order, maybe (it's not one of the ones which migrated incorrectly, but it is the same customer).

### Information (if a specific version is affected):
PHP Version: 7.3.5
EDD Version (or branch): 3.0
WordPress Version: 5.4.1

Any other relevant information:
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/cac1134dcb2276c543c3197f5d91a3a626d4d906/includes/admin/notes/note-functions.php#L78-L80

It does seem like we could separate the use of `get_userdata` from immediately retrieving the `display_name` in case `get_userdata` does not return an object.

**Comment by ashleyfae** [comment]
Perhaps three options:

1. `! empty( $user_id )` and we have a `WP_User` object -- display name
2. `! empty( $user_id )` but we failed to retrieve a user object -- Either `User ID #{id number}` or `[User Deleted]` or similar.
3. No user ID -- `edd_get_bot_name()`

**Comment by robincornett** [comment]
I feel a little weird about option 2, at least in this specific context, as the notes in question really all do seem like they should be assigned to the bot. But assuming that my context is an outlier it does make sense.

**Comment by ashleyfae** [comment]
If it has an associated user ID then I think we need to assume it was intended to be associated with an actual user. That association may have been incorrectly done at the time but I think that's the safest assumption.
