### ISSUE TITLE
3.0 - Orders - `edd_complete_purchase` Hook Not Called Manually Creating Orders

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/easy-digital-downloads#7864]
### Expected behavior

When manually creating an Order that has a status of `complete` the `edd_complete_purchase` hook should be called.

### Actual behavior

The hook is never called.

### Steps to reproduce the behavior
1) Create a new Order.
2) Check "Send Purchase Receipt"

- Observe the receipt is not sent.

### Information (if a specific version is affected)

EDD Version (or branch): `release/3.0`

Any other relevant information:

`edd_complete_purchase()` only runs if `date_completed` is empty. 

We are currently setting `date_completed` on initial Order creation (in `edd_add_manual_order()` regardless of the status -- instead `edd_complete_purchase()` should be handling this.

**Comment by robincornett** [comment]
Fixing this should resolve the issue reported in [software licensing](https://github.com/easydigitaldownloads/EDD-Software-Licensing/issues/1629) (license keys not being generated for manual orders) and [this comment](https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7464#issuecomment-622017779).

**Comment by LisaCee** [comment]
I'm pretty sure the fix for this is more than just removing `date_completed` from `edd_add_manual_order()`.  Even though it works, I imagine there are some unseen consequences that I'm missing.  Feedback?

**Comment by spencerfinnell** [comment]
@LisaCee I _believe_ that might be all that is required. Things to check for:

- Confirm it fixes the "Send Purchase Receipt" not sending
- Check the Order Notes and ensure they match the same notes that are added when creating an order on the frontend Checkout
- If possible confirm it fixes https://github.com/easydigitaldownloads/EDD-Software-Licensing/issues/1629

The check for an existing `completed_date` on the Payment exists in 2.9 https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/payments/actions.php#L108 so I think the only change in 3.0 is the forced setting of `date_completed` when manually creating the Order before we actually set the status to `complete`

**Comment by LisaCee** [comment]
PR #7868
