### ISSUE TITLE
3.0 - Backwards Compatible CSS Issue for #edd-item-card-wrapper

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#7866]
### Expected behavior
When I visit an admin screen with legacy wrapper markup, I expect it to look "correct".

### Actual behavior
PR #7095 partially addressed this, but the CSS appears to no longer be quite valid, specifically to add padding to the `.item-section` div. Example from Recurring:

![image](https://user-images.githubusercontent.com/4853066/81605180-146d1e00-939f-11ea-9a34-806aecd527fa.png)

### Steps to reproduce the behavior
1) In EDD 3.0, visit a subscription screen (EDD Recurring) or add a new commission (EDD Commissions)
2) There is no padding around the `.item-section` containers.

### Information (if a specific version is affected):
PHP Version: 7.3.5
EDD Version (or branch): 3.0
WordPress Version: 5.4.1

Any other relevant information:
I think the issue is in this CSS, as it's pretty specific:

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/8acae18587802b10b685a73cf0b074792b4458b4/assets/css/edd-admin.css#L3808-L3813

I believe that CSS is targeting an `#edd-item-card-wrapper` immediately following a `div` which is not `#edd-item-tab-wrapper`, but in both Commissions and Recurring, the card wrapper follows an `h2` (which should actually be an `h1` in both cases, as they are the page title), so no padding is applied (other CSS is missing, but the padding is the most noticeable).

**Comment by spencerfinnell** [comment]
@robincornett Do you know if Commissions and Recurring have made changes to their markup since https://github.com/easydigitaldownloads/easy-digital-downloads/pull/7095, or did we never actually have _some_ compatibility when we merged that?

I recall things looking slightly off for the extensions at that time, but definitely not like they do now.

**Comment by robincornett** [comment]
I'm not sure, but I can research.

**Comment by robincornett** [comment]
@spencerfinnell ... It looks like the last changes to those screens in each plugin were 3 years ago (Commissions) and 4-5 years ago (Recurring).

**Comment by spencerfinnell** [comment]
🤷 Switching it to `*:not(#edd-item-tab-wrapper) + ...` seems to help.

Some uses of `#edd-item-tab-wrapper` to check: https://github.com/search?q=org%3Aeasydigitaldownloads+edd-item-card-wrapper&type=Code

**Comment by spencerfinnell** [comment]
@LisaCee Can you set up a PR that implements the above CSS change so we can all run it through its paces on various extensions using the legacy markup?

**Comment by robincornett** [comment]
The suggested CSS does seem to resolve the issue on the two screens where I'm seeing it, and does not negatively impact the license details screen, which was mentioned in the original PR, but is currently displaying correctly.

**Comment by LisaCee** [comment]
PR #7875
