### ISSUE TITLE
3.0 - Physical Addresses May Be Added Multiple Times During Migration

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#7873]
### Expected behavior
When I migrate data from 2.9 to 3.0, I expect physical addresses not to be duplicated.

### Actual behavior
When I migrate data, a new physical address record is created for each order, which can result in multiple duplicates for a long time customer.

### Steps to reproduce the behavior
1) Migrate a storefront with physical addresses to 3.0.
2) Check address records for customers with multiple orders.

### Information (if a specific version is affected):
PHP Version: 7.4.1
EDD Version (or branch): 3.0
WordPress Version: 5.4.1

Any other relevant information:
Related: #7822, #7814 (empty addresses are also added multiple times)

**Comment by cklosowski** [comment]
I believe this is possibly due to the `edd_maybe_add_customer_address` function.

It is trying to determine if while migrating an order, we should also migrate the address. 

```
function edd_maybe_add_customer_address( $customer_id = 0, $data = array() ) {

	// Bail if nothing passed.
	if ( empty( $customer_id ) || empty( $data ) ) {
		return false;
	}

	$data['customer_id'] = $customer_id;

	$c = edd_count_customer_addresses( $data );

	// Add to the table if an address does not exist.
	if ( 0 === $c ) {
		$data['type'] = 'billing';
		return edd_add_customer_address( $data );
	}

	return false;
}
```

Once I complete #7254 I'll see if I can get this fixed up.

**Comment by cklosowski** [comment]
So it looks like this is an issue in that we move addresses over at the order level, AND the customer migration level. I'm going to see if we can reuse the `edd_maybe_add_customer_address` in both cases so we don't auto add multiples.

**Comment by robincornett** [comment]
I think part of the issue is that the `edd_maybe_add_customer_address` function is checking to see if a customer has _any_ addresses at all (as I read this?), not whether the address that's about to be added already exists for the user. My guess is that the logic in that function needs to be updated for both #7814 (not adding empty addresses) and this, so that duplicate addresses are not added.

This is actually not just a migration related issue--placing a new order for an existing user/customer and entering the same physical address information results in a new address being created for the customer as well.
