### ISSUE TITLE
3.0 - JavaScript error while viewing admin Orders table

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#7882]
### Expected behavior

I expect to not get any JavaScript errors.

### Actual behavior

When I visit the admin Orders table I get the following JavaScript error:

![Screenshot from 2020-05-13 13-26-20](https://user-images.githubusercontent.com/6324272/81811957-57ed9680-951d-11ea-88e3-d0b5138563f3.png)

Coming from `assets/js/admin/orders/order-details/address.js` line `21`

### Steps to reproduce the behavior
1) Go to Downloads > Orders.
2) Check your browser console to see the error.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0

WordPress Version:

Any other relevant information:

**Comment by spencerfinnell** [comment]
The imports in `/orders/index.js` could definitely be optimized, but I think the easiest fix for now is to stop the loading of `edd-admin-orders.js` on the List Table. I believe the JS used to handle the filters is not specific to the Orders screen and is handled inside of `edd-admin.js`

**Comment by LisaCee** [comment]
PR #7931
