### ISSUE TITLE
3.0 - Assets - jquery-ui-css No Longer Registered

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/easy-digital-downloads#7884]
### Expected behavior

When I set a style dependency of `jquery-ui-css` my custom styles should load.

### Actual behavior

The styles are not loaded because there is no `jquery-ui-css` style handle registered.

### Steps to reproduce the behavior
1) `wp_enqueue_style( 'my-custom-style', get_template_directory_uri() . '/style.css', array( 'jquery-ui-css' ) );`

### Information (if a specific version is affected):
EDD Version (or branch): `release/3.0`

Any other relevant information:

We don't need to use/enqueue it, but the style handle should still be registered. `release/2.9.x` also registers a different CSS file based on the admin color scheme, which we don't need to keep in `release/3.0`.

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/scripts.php#L274

**Comment by LisaCee** [comment]
PR #7924
