### ISSUE TITLE
3.0 - Migration - Mention CLI command on the upgrade UI page

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#7885]
### Explain your enhancement (please be detailed)

I'd like the `wp edd v30_migration` CLI command to be mentioned on the migration UI. Maybe somewhere in between the existing admin notice and `Step 1`

![Screenshot from 2020-05-13 14-14-23](https://user-images.githubusercontent.com/6324272/81817083-157b8800-9524-11ea-88cb-ff95084e2796.png)

### Justification or use case

The command is _only_ mentioned inside the admin notice if you click on `Learn more about this upgrade`. If you just `click here to start the upgrade`, you'd never know there even was a CLI command.

**Comment by robincornett** [comment]
Mentioned also in #7834:

> It may also be helpful to include at least some of the "learn more" text on the top of the migration page, in case a user navigates there without clicking the "learn more"...especially the note to back up the database and that the upgrade is irreversible.

**Comment by spencerfinnell** [comment]
Semi-related discussion around 3.0 migration UI: #6880
