### ISSUE TITLE
3.0 - "Confirm removal of legacy data." text not translation-ready

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#7887]
### Expected behavior

I expect all text to be outputted via helper functions like `_e()` to be translation-ready.

### Actual behavior

This text: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/upgrades/upgrade-functions.php#L1829 is not outputted via `_e()`. It's just written plainly:

```html
<label for="remove-legacy-data-confirm">Confirm removal of legacy data.</label>
```

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0

WordPress Version:

Any other relevant information:

**Comment by spencerfinnell** [comment]
There is a lot of `_e()` usage that should be `esc_html_e()` in `edd_upgrade_render_v30_migration()` that can be fixed up as well.

And things like

```php
<?php printf( esc_html__( 'Step %d: Upgrade Customer Notes', 'easy-digital-downloads' ), $step ); ?>
```

Are better as:

```php
<?php echo esc_html( sprintf( __( 'Step %d: Upgrade Customer Notes', 'easy-digital-downloads' ), $step ) ); ?>
```

**Comment by ashleyfae** [comment]
> There is a lot of `_e()` usage that should be `esc_html_e()` in `edd_upgrade_render_v30_migration()` that can be fixed up as well.

Yep yep. Though the attribute ones should be `esc_attr_e()`. Example:

```
value="<?php _e( 'Upgrade Database', 'easy-digital-downloads' ); ?>"
```

should be:

```
value="<?php esc_attr_e( 'Upgrade Database', 'easy-digital-downloads' ); ?>"
```

**Comment by LisaCee** [comment]
PR #7894
