### ISSUE TITLE
3.0 - Addresses show time, but not time zone

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#7889]
### Expected behavior
When I migrate my database, if times are shown, EDD 3.0 usually shows the time zone.

### Actual behavior
After PR #7867, addresses migrated using the order/customer creation date do not display the time zone.

### Steps to reproduce the behavior
1) Check out `issue/7859` and perform a database migration
2) Visit Downloads > Customers > Addresses (or Email Addresses)
3) The dates/times in the Date column do not show the time zone

### Information (if a specific version is affected):
PHP Version: 7.4.1
EDD Version (or branch): issue/7859
WordPress Version: 5.4.1

Any other relevant information:
The "First Used" time on the Customer Details screen does show the time zone.

**Comment by ashleyfae** [comment]
Correct me if I'm wrong, but I don't think this is a migration issue? I think it's just a display issue, which means it happens in release/3.0 right now and also happens for brand new customers.

**Comment by robincornett** [comment]
You are correct, it does happen for new customers as well--sorry for the oversight! I assumed it was something I had introduced with that PR. This does apply to all addresses in 3.0.

**Comment by ashleyfae** [comment]
We should check everything we can and make sure there aren't others missing in other places around the admin UI.
