### ISSUE TITLE
3.0 - Migrated Customer Agreements Show Two Different Times

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#7891]
### Expected behavior
When I migrate customer data, I expect the times to display consistently.

### Actual behavior
When I upgrade to 3.0, the customer details show two different times, which appear to be a time zone conversion/display issue:

![image](https://user-images.githubusercontent.com/4853066/81835000-b744aa00-950f-11ea-8b5e-21409bb2222f.png)

What is displaying in the 2.9 version of the site is the 16:09 time. The list tables show the 16:09 time (without the time zone).

### Steps to reproduce the behavior
1) In a site with customer data which has been migrated from 2.9 to 3.0, view the Customer Details.

### Information (if a specific version is affected):
PHP Version: 7.4.1
EDD Version (or branch): 3.0
WordPress Version: 5.4.1

Any other relevant information:
This may be similar to what was going on in #7794. Also, this happens with migrated customers, not new ones.

**Comment by robincornett** [comment]
This appears to happen because the privacy policy agreement is not an option in 2.9, so the date from the last payment is used instead. When the 2.9 terms agreement does exist, the two numbers are different (both in format and value):
- `$agreement_timestamp`: `'1585066174'` (string)
- `$last_payment_date`: `1585080574` (integer)

So I think that means that the agreement date in 2.9 was stored in the local timezone, and 3.0 is expecting UTC.

**Comment by robincornett** [comment]
@cklosowski with the difference in values on the timestamp, I'm not sure we can do anything about this--what do you think?

**Comment by cklosowski** [comment]
I'm going to go ahead and close this with a no action. If we find a need to change it later we can.
