### ISSUE TITLE
3.0 - Customer Details screen shows "Agreed to Privacy Policy" when disabled

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#7897]
### Expected behavior
If my site does not have a privacy policy, I should not see a notice that a customer agreed to it.

### Actual behavior
On my site with no privacy policy, and none enabled, the customer details screen shows that a customer has agreed to the privacy policy.

### Steps to reproduce the behavior
1) In EDD 3.0, set up a storefront and do not enable the privacy policy (Downloads > Settings > Privacy > Privacy Policy)
2) Create an order/customer
3 ) View the customer details screen, which shows that the customer agreed to terms and to the privacy policy

### Information (if a specific version is affected):
PHP Version: any
EDD Version (or branch): 3.0
WordPress Version: 5.4.1

Any other relevant information:
Looking at the `edd_customers_view` function, it seems that the "Terms & Agreements" likely has the same issue, as there is no check in the code for the setting for terms or for the privacy policy. (My test storefront has terms enabled, but not privacy.)

**Comment by cklosowski** [comment]
This is actually on purpose. As we don’t have a ‘date’ for when that setting is enable or disabled, we also don’t know that the customer you are viewing _didn’t_ agree to the terms or agreements when they checked out.

For legal ramifications, if a customer made a purchase and checked the box and at a later date a store owner disabled those, the customer and store are still bound to those agreements at the time of the purchase, no matter what the current status of the agreements checkbox setting is.

**Comment by robincornett** [comment]
I see what you're saying about not being able to tell if that was active at one point and then disabled, but if my store has no privacy policy and no way for customers to agree to it, it seems confusing to show me that they did.

**Comment by spencerfinnell** [comment]
@robincornett Maybe a notice in that area stating that while previous agreements exist, they are currently not being added to new orders?

**Comment by robincornett** [comment]
Or what about tweaking the conditional so that:

1. if _any_ agreements exist (because they were in effect at the point of purchase), the most recent one will be displayed, regardless of the current store options
2. if no agreements exist, then check to see if the store has terms/privacy policy in effect, and if it does, then use the most recent purchase date

?
