### ISSUE TITLE
3.0 - Order currency symbol can be incorrect

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#7900]
### Expected behavior
When I view an order details screen, I expect it to have the correct currency.

### Actual behavior
In a test storefront, I had the currency set to euros for a time, and placed several test orders. I've switched the storefront back to US dollars. The orders placed with euros show the correct currency symbol in the orders list table, but when I view the order details screen, all currencies display as `$` instead. However, if I click the "Issue Refund" button, the currency symbols are euros in the refund modal.

### Steps to reproduce the behavior
1) In an EDD 3 store with existing orders, change the currency.
2) Visit the orders list table. Existing orders should still show the old currency.
3) Click on an order to view the details. The currency symbol uses the storefront currency symbol, not the one for the order.

### Information (if a specific version is affected):
PHP Version: 7.3.5
EDD Version (or branch): 3.0
WordPress Version: 5.4.1

**Comment by spencerfinnell** [comment]
Right now various Order-related views create a new instance of the [`Currency`](https://github.com/easydigitaldownloads/easy-digital-downloads/tree/release/3.0/assets/js/packages/currency) class when needed:

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/a7d829363ef5a66d9317f00173e10d6296353e38/assets/js/admin/orders/order-overview/views/order-item.js#L8-L9
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/a7d829363ef5a66d9317f00173e10d6296353e38/assets/js/admin/orders/order-overview/views/order-item.js#L71-L74

The default instantiation uses the store's global currency settings.

Instead we should create a single instance of `Currency` (and probably `NumberFormat`) based on the current Order's settings and attach it to the Order-specific state: 

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/a7d829363ef5a66d9317f00173e10d6296353e38/assets/js/admin/orders/order-overview/index.js#L34-L41

**Comment by spencerfinnell** [comment]
PR #7913 uses stored Order currency when formatting amounts. It can only utilize the currency and derived currency symbol -- currency position, zero precision, thousands separators, and decimal separators will still use current store settings.
