### ISSUE TITLE
3.0 - Pre-Migration: change Dashboard Widget, add Orders notice

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#7902]
### Explain your enhancement (please be detailed)
For a storefront which has updated to 3.0, but not gone through the upgrade process yet, do not output the standard dashboard widget, and maybe add a notice to the orders list table.

### Justification or use case
Site owners who update to 3.0, but do not immediately complete the migration process, may be concerned to see no orders in the orders list table and all zero amounts in the Dashboard widget. Also, every time the WordPress heartbeat fires on the Dashboard, sites which have debugging on will see a PHP Notice that the `edd_report_views` hook is deprecated.

For these users, updating the Dashboard widget to say something like "This summary will be available once you have completed the migration", and adding a similar notice to the orders list table, may help communicate that their data has not been lost, but is just not available until the migration process is complete.

**Comment by spencerfinnell** [comment]
We can't do it for many reasons, but one of the nice things about automatic migrations would be not having lapses of blankness like this.

When WordPress core requires a database update you can't do anything in the WordPress admin until it happens. I agree making it more obvious that the migration **has to happen** in places like the ones mentioned would be helpful. It's also why I think making the notice more noticeable/urgent is important (https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7834#issuecomment-626760902)

**Comment by cklosowski** [comment]
@robincornett For historical reference, can you screenshot the results of your changes and drop them into a comment?

**Comment by robincornett** [comment]
Here's the dashboard widget with the updated message:
![image](https://user-images.githubusercontent.com/4853066/86963169-17338780-c132-11ea-9861-d47e4b68088f.png)

And the orders table (no link because of proximity to admin notice):
![image](https://user-images.githubusercontent.com/4853066/86963246-3205fc00-c132-11ea-9611-18a5342e1788.png)

**Comment by spencerfinnell** [comment]
With the Orders screen I'm wondering if there is any real value in showing the empty table at all. Even though the notice explains the Orders will reappear when the upgrade is complete there is still the initial shock of seeing an empty list.

Would it be too confusing to just redirect people to the upgrade screen when attempting to view Orders (not an automatic redirect when viewing other pages)?

**Comment by robincornett** [comment]
Personally, I would rather see the empty table with explanatory text than to be redirected without knowing why.

**Comment by spencerfinnell** [comment]
@robincornett The upgrade screen could have similar messaging explaining why they landed on that page. As-is the upgrade page would be confusing to be redirected to for sure; but some adjustments to that could make it less jarring.
