### ISSUE TITLE
3.0 - Reports - Graphs not showing complete data

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#7907]
### Expected behavior

I expect the graphs to show accurate data for the reported period.

### Actual behavior

It's possible all graphs are affected, but I'll focus on `Sales and Earnings`.

If I set the graph to `Last Year` then I get a month-by-month view. Each tick is supposed to show the total number of sales and total earnings in that period. However, the numbers don't add up. What's actually happening is that only the sale count/earnings for _the last day in that month that has data_ is being displayed.

This becomes particularly clear when you compare the values on the ticks with the tile further up that shows `Sales / Earnings`.

This is the problem: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/reporting/reports-callbacks.php#L86-L103

This is a `foreach` loop, but the values are being _overwritten_ each loop.

```php
$sales[ $timestamp ][1]    = $result->sales;
$earnings[ $timestamp ][1] = $result->earnings;
```

They should be getting added together like this:

```php
$sales[ $timestamp ][1]    += $result->sales;
$earnings[ $timestamp ][1] += $result->earnings;
```

### Steps to reproduce the behavior
1) Go to Downloads > Reports.
2) Look at the `Sales and Earnings` graph.
3) Count up the numbers for each tick and you'll see they're massively lower than the tile further up that reports the overall Sales / Earnings.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0

WordPress Version:

Any other relevant information:

**Comment by spencerfinnell** [comment]
@robincornett It looks like the same thing is happening for the Refunds chart. Can you verify that as well as any other time-based charts?

**Comment by robincornett** [comment]
@spencerfinnell I have fixed that one, and am reviewing similar code in [reports.php](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/reporting/reports.php#L879-L880) (there are multiple instances throughout that file). I'm thinking that anything like this in a foreach loop needs to be handled the same way. Does that seem reasonable?

**Comment by spencerfinnell** [comment]
@robincornett Or maybe not setting a `1` index each time in loops like that. I'm not super familiar with that code so I can't say why it's set up like it is currently, unfortunately.

**Comment by robincornett** [comment]
The first/`0` value in the array appears to be the actual timestamp and the `1` is the count for whatever is being done. I do think the rest of these need to be updated--overwriting the values in a foreach loop doesn't seem right regardless. I'll get those in this afternoon.

**Comment by cklosowski** [comment]
@robincornett is this one ready go to?

**Comment by robincornett** [comment]
@cklosowski yes, the PR should be ready to merge--I reverted the status lines yesterday, I think.
