### ISSUE TITLE
3.0 - Reports - Graph tick labels are misleading when showing month-by-month view

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#7908]
### Expected behavior

When I hover over a point on the graph, I expect the label to tell me exactly which period this covers.

### Actual behavior

When you're viewing a date range that shows data grouped by month ("This Year" and "Last Year" ranges do this), the ticks are formatted like this:

`July 1, 2019`

However, the data is actually covering the _full month_ of July -- not just the 1st. So the tick should be `July 2019`

### Steps to reproduce the behavior
1) Go to Downloads > Reports.
2) Set the date range to This Year or Last Year.
3) Hover over a point on the graph.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0

WordPress Version:

Any other relevant information:

**Comment by spencerfinnell** [comment]
PR #7930 fixes fixes the originally reported issue and optimizes formatting throughout time-based charts as a whole. 

Timezones are only shown on relevant hour-by-hour reports.

Date/Time formats are still rigid and don't necessarily respect the site's formatting options but until we have a reliable way to map PHP date/time formats to `moment.js`, I think it is fine. 

WP 5.0+ comes bundled with `wp.date` which handles a lot of the Moment timezone handling automatically, which will be nice to have: https://github.com/WordPress/gutenberg/blob/master/packages/date/src/index.js
