### ISSUE TITLE
3.0 - PHP notice on sales log page

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#7909]
### Expected behavior

When I views the sales log I expect to not get any PHP notices.

### Actual behavior

When I visit the sales log page via the `Downloads` table, I get the following notice:

```
PHP Warning:  Declaration of EDD_Sales_Log_Table::get_query_args() should be compatible with EDD_Base_Log_List_Table::get_query_args($paginate = true) in /var/www/eddexport/wp-content/plugins/easy-digital-downloads/includes/admin/reporting/class-sales-logs-list-table.php on line 112
```

### Steps to reproduce the behavior
1) Go to Downloads > Downloads.
2) Locate a download in the list, and click on the `Sales` number for that download.
3) PHP warning will trigger.

Confirmed this is an issue in 3.0, haven't yet tested in master.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0

WordPress Version:

Any other relevant information:

**Comment by robincornett** [comment]
This is not present in master.
