### ISSUE TITLE
FES email shortcode

### ISSUE THREAD

**Issue by matt70** [easydigitaldownloads/easy-digital-downloads#7915]
Hi at EDD,
I would like to have an Email shortcode in FES. Can not find one on this page?
https://docs.easydigitaldownloads.com/article/338-frontend-submissions-email-configuration

When I get an submission by a vendor and I have a question. There is acutally no way to see what's his email. When I have a question I have to look into the admin section for is email.
Would be great to see the vendor email in the submission...
Thanks
Matthias

**Comment by matt70** [comment]
Hm, this request did not get any labels yet. Is there something wrong with it. Is it the wrong place for FES requests?
Thanks
Matthias

**Comment by ashleyfae** [comment]
This repo is for the core EDD plugin only. We have a separate private repo for FES specifically. It would be better for you to go through our support team, then they can post your requests to the correct repo on your behalf: https://easydigitaldownloads.com/support/

Thanks!

**Comment by matt70** [comment]
> It would be better for you to go through our support team

Yes I did this already, but it takes very long to raise a support ticket. You have to upload system settings per txt-file, registration code etc.
And the support team told me, that I can post the requests as well and the development team is sorting them to the right place...
Thanks
Matthias
