### ISSUE TITLE
3.0 - Pie chart reports are incorrect for products with variations

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#7919]
### Expected behavior
When I view a download report for a product with variations, and I select "All Options", I expect the pie charts to show accurate data.

### Actual behavior
When I view a report for a specific download, the pie chart is one color and the numbers I see when I hover over it do not match the tile above. Example:

![image](https://user-images.githubusercontent.com/4853066/82084850-03cbe900-96ba-11ea-84e8-16f956c21294.png)

(If I hover over the first pie, the overlay says, "Unlimited Sites: 2 (100%)". Also, if the second chart overlay is supposed to indicate the percentage share, the math is definitely going wrong somewhere.

Also, the pie charts do not always show at all:
![image](https://user-images.githubusercontent.com/4853066/82085077-6de48e00-96ba-11ea-9db0-b080382642d5.png)

### Steps to reproduce the behavior
Not 100% sure, but here's what I've got:
1) In EDD 3.0, visit Downloads > Reports > Downloads
2) Select a download with variations and set the dates as you like
3) See if you get a pie chart?
4) My guess is that if one of the variations has zero sales for the time period in question, that's when things go sideways. The same download with a much longer time period renders an accurate pie chart.
5) Note: even if I get an accurate pie chart, the numbers in the "Sales by Variation" chart (the top one) do not add up to the number shown on the tile.
etc, etc

### Information (if a specific version is affected):
PHP Version: any
EDD Version (or branch): 3.0
WordPress Version: 5.4.1

Any other relevant information:
Possibly related: #7907, but the fix there does not fix pie charts.

**Comment by robincornett** [comment]
I think the issue may be in the SQL query run for `$stats->get_order_item_count()`. Dumping the [`$results`](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/class-stats.php#L974) when all options are selected for a download returns an array like this:

```
[18-May-2020 13:14:20 UTC] Array
(
    [0] => stdClass Object
        (
            [product_id] => 1234
            [price_id] => 3
            [total] => 2
        )

)
```
So only one `price_id` is in the array, and the total here is not correct. Running a report for a single variation returns accurate looking numbers.

**Comment by cklosowski** [comment]
So the pie charts show up now, but they don't respect the Country and Region filters.

Here is the All Countries & All Regions. We can see that the tile shows the sales amounts and the pie graphs show the distribution of the purchases:
![image](https://user-images.githubusercontent.com/1390124/82613643-a2ed5680-9b7a-11ea-9101-46ac7f7d369c.png)

If I change this to a Country/Region (of which I don't have any on this site, so nothing should show)
![image](https://user-images.githubusercontent.com/1390124/82613682-bf898e80-9b7a-11ea-86ae-fc849151a1c2.png)

Notice in the 2nd one, the tile has Zero sales and revenue, but the pie graphs and chart are showing data as if the region has sales. I think this for sure solves the bug of defaulting to the 'store' graph, but I think it needs some more testing around passing in that region, which might be one of the over-reaching areas that you mentioned in the original ticket.

**Comment by cklosowski** [comment]
@robincornett Fixed up the pie charts. but we need to look at the 'download_sales_earnings_chart` endpoint to see if there is a way to use the `$country, $region` data to filter that out as well.

**Comment by robincornett** [comment]
@cklosowski I looked at that one and am not sure I know how to tackle it--as it looks like it's creating its own SQL query, and adding region/country would be adding a second table into the query process? Is that what I'm looking at?

**Comment by cklosowski** [comment]
@robincornett yeah I think so. Let me look into that report a little closer.

**Comment by robincornett** [comment]
Looking over all of the reports, I'm wondering why Downloads includes a filter for Country/Region. Currently, the only other report which includes that as a filter is the Taxes report, which makes sense. However, no other reports include a location filter.

As for the exports, which appear to have some general parity with reports, only the Taxes export includes a filter for location.

@cklosowski I'm wondering if the location filter is necessary at all for this report, or (alternatively) if it is necessary to include at this time.

**Comment by cklosowski** [comment]
@robincornett yeah, that's a far assessment. Lets go ahead and just remove it all (including my latest commits) and remove them from the filters. I see no point in this currently.
