### ISSUE TITLE
3.0 - Reports - Tiles Alignment Incorrect

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/easy-digital-downloads#7928]
### Expected behavior

When viewing Reports the Tiles should align with other endpoint displays.

### Actual behavior

They are inset too far:

<img width="785" alt="Screen Shot 2020-05-18 at 10 05 19 AM" src="https://user-images.githubusercontent.com/491124/82222323-1ed36e80-98ef-11ea-9ab9-2d170232b960.png">

### Steps to reproduce the behavior
1) View "Reports > Customers"

### Information (if a specific version is affected):

EDD Version (or branch): `release/3.0`

Any other relevant information:

I believe the CSS might have been lost in a merge conflict, as I don't believe they were misaligned before. 

Previously: #7669 

Relevant CSS: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/assets/css/edd-admin.css#L2652-L2688

**Comment by LisaCee** [comment]
Do you want the `divs` matched up like this?  
![Screenshot at 15-15-14](https://user-images.githubusercontent.com/18077352/82383923-a6020e80-99e3-11ea-97b4-ab952dcee09a.png)

Or something more like this with the tile edge lined up with the heading?
![Screenshot at 15-18-42](https://user-images.githubusercontent.com/18077352/82384152-17da5800-99e4-11ea-8006-028b60622048.png)

**Comment by spencerfinnell** [comment]
@LisaCee Tile edge aligning with the heading edge/edge of the standard padding applied to the other sections:

<img width="327" alt="Screen Shot 2020-05-19 at 6 29 42 PM" src="https://user-images.githubusercontent.com/491124/82384919-ea4ed800-99fe-11ea-9c31-77e827aea602.png">

There is some margin on the individual tiles that needs to be offset in the container I think.

**Comment by LisaCee** [comment]
PR #7948
