### ISSUE TITLE
3.0 - Reports: When viewing graphs that group by 'month', tooltips show last date of month as date.

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#7932]
### Expected behavior
When I review a report that groups things by 'month' instead of day or hour, i would expect that the tooltip shows the month as a whole like "April 2019" .

### Actual behavior
The tooltip shows a date of the last day of the month taht the data was collected for, like "April 30, 2019"

### Steps to reproduce the behavior
1) From a earnings report choose 'Last Year'
2) Hover the tooltip of a point.

### Information (if a specific version is affected):
PHP Version: All

EDD Version (or branch): `release/3.0`

WordPress Version: All

Any other relevant information:

**Comment by spencerfinnell** [comment]
@cklosowski This should be fixed by https://github.com/easydigitaldownloads/easy-digital-downloads/pull/7930

<img width="926" alt="Screen Shot 2020-05-18 at 2 42 55 PM" src="https://user-images.githubusercontent.com/491124/82248306-e5622980-9915-11ea-86c6-d314788107d2.png">

**Comment by spencerfinnell** [comment]
This was fixed by #7930
