### ISSUE TITLE
3.0 - Reports: reports that support hour by hour don't show ticks

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#7933]
### Expected behavior
I would expect a report like 'today' to show hourly results.

### Actual behavior
When I view a report that should show hour by hour results (like Today or Yesterday), all values are lumped into a single tick at the beginning of the chart.

The reports I can think that should support this are:
1) Today
2) Yesterday
3) A custom date that spans only a single day.

### Steps to reproduce the behavior
1) View a report for `Today`, `Yesterday`, or a custom single date.
2) Notice that a single tick is registered.

### Information (if a specific version is affected):
PHP Version: All

EDD Version (or branch): `release/3.0`

WordPress Version: all

Any other relevant information:

**Comment by spencerfinnell** [comment]
@cklosowski This should be fixed by https://github.com/easydigitaldownloads/easy-digital-downloads/pull/7930

<img width="917" alt="Screen Shot 2020-05-18 at 2 41 41 PM" src="https://user-images.githubusercontent.com/491124/82248207-bcda2f80-9915-11ea-9e3d-0a7b3e1b2bba.png">

**Comment by cklosowski** [comment]
@spencerfinnell ok relating that PR to here too.

**Comment by spencerfinnell** [comment]
This was fixed by #7930
