### ISSUE TITLE
Review Extension - Sort order

### ISSUE THREAD

**Issue by matt70** [easydigitaldownloads/easy-digital-downloads#7939]
I'm missing a setting for changing the sort order of download reviews.
In wordpress there is a setting for changing the sort order of comments date ascending oder date descending. Would be nice if the review extension has a setting like this...
Thanks
Matthias

**Comment by spencerfinnell** [comment]
Hello @matt70,

This issue tracker is meant for the core Easy Digital Downloads plugin. We have a separate private repository for the Reviews extension. We do have an open issue there regarding introducing an option to control sorting order.

I will cross reference the issues to indicate this feature request.
