### ISSUE TITLE
Review Extension - Email Vendor if Product is commented

### ISSUE THREAD

**Issue by matt70** [easydigitaldownloads/easy-digital-downloads#7940]
I'm missing a setting for sending a notification email to vendors, when their product is reviewed by a customer.
At the moment the admin gets an email, when someone reviews a vendor product. But it would be much more community building to send a notification to the vendors, too.
Something like "Hey Vendor, User_1 wrote a comment on product_abc"
Thanks
Matthias

**Comment by spencerfinnell** [comment]
Hello @matt70,

I will cross reference this issue in an existing open request for this functionality in the private Reviews repository.
