### ISSUE TITLE
FES - Email managment

### ISSUE THREAD

**Issue by matt70** [easydigitaldownloads/easy-digital-downloads#7941]
FES Email System needs some additions
1. Option to change or at least translate the subject of the vendor emails.
2. Option to stop or change the "submission declined"-email. Sometimes the standard submission declined email needs some additional explanation...
3. When you start with FES it's not easy to understand, what all the notification emails are for. Especitally if you have to translate them in a different language. Some additional explanations will help new EDD users...
Thanks
Matthias

**Comment by spencerfinnell** [comment]
Hello @matt70 

I have cross referenced these requests in our private issue tracker for Frontend Submissions. Thank you for your input!
