### ISSUE TITLE
EDD - Community Extension

### ISSUE THREAD

**Issue by matt70** [easydigitaldownloads/easy-digital-downloads#7942]
As Mandy wrote in the EDD Blog a few weeks ago, it would be great to provide a personalized experience for you vendors and customers.
https://easydigitaldownloads.com/blog/providing-a-personalized-experience-on-your-digital-store/

I'm missing a community extension for that in EDD.
1. Vendor list with some sorting options like "number of products", "oldest vendor", "newest vendor"...
2. Different Product lists, like "Best rated products", "Most downloaded products", "Most reviewd products"
3. Connection between bbpress forum and FES. At the moment I have different profile pages in bbpress and EDD. Would be great to combine them.
4. A page where users can see the public wishlists of other users
5. There are already a lot of statistics in the background of EDD. Would be great to have options to show them to the vendors and cumstomers.

These are just some ideas. I think there is much more potential in such an extension...
Thanks
Matthias

**Comment by cklosowski** [comment]
Thanks for your feedback @matt70.

Github is for development tracking only. Please contact our support team here so we can get these suggestions to the correct team for assessment.
https://easydigitaldownloads.com/support
