### ISSUE TITLE
3.0 - Chosen dropdown can be too narrow

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#7953]
### Expected behavior
When I click on a select field, I expect the values to be readable.

### Actual behavior
This is occurring specifically on the Payment Gateways report screen:

![image](https://user-images.githubusercontent.com/4853066/82666812-a3323400-9c04-11ea-96c1-75e5e39d1a3e.png)

I think it's because the gateway select field is using the default "All", and when Chosen renders the field, it uses the first option to set the width of the entire element.

### Steps to reproduce the behavior
1) In EDD 3.0, go to Downloads > Reports > Payment Gateways.
2) Click to select a specific gateway.

### Information (if a specific version is affected):
PHP Version: 7.3.5
EDD Version (or branch): 3.0
WordPress Version: 5.4.1

Any other relevant information:
We could fix the issue on this specific screen by changing the label here to "All Gateways" instead of using the default, but I think it may be better to fix the rendering behavior so that other instances will display well.

**Comment by spencerfinnell** [comment]
@robincornett I think https://github.com/easydigitaldownloads/easy-digital-downloads/commit/5c41742d0e5fd76350588e7723366f1d0ef021d7#diff-06e056d2f15df70a64bd71e8c1f568e3 might have caused this. 

I still would like to see the `100% !important` removed, so we should see if there is a way to fix the initial render like you said. Also we need to continue removing unneeded use of Chosen #7583

**Comment by robincornett** [comment]
Interestingly, removing the `!important` resolves the issue on that dropdown--looking around to see why I would have done that in the first place.

Would love to consider updating the `chosen` dropdowns to look more like WP select fields--the box shadow, border, and arrow are all super different.
