### ISSUE TITLE
3.0 - Selecting an existing address for a manual order does not retrieve the region

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#7958]
### Expected behavior
When I manually create an order and select a customer's preexisting address, if it is within a region which collects taxes, I expect the taxes to be applied.

### Actual behavior
When I select the address, the `getTaxRate` JS function retrieves the country, but not the region/state, so the tax rate is not applied.

### Steps to reproduce the behavior
1) In an EDD store with taxes enabled for a region (not country wide), create a new order.
2) The order should be for an existing customer with an existing address which meets the criteria for being taxable (so I picked a customer with a TN address).
3) Add a product to the order. It will show a 0.00% tax rate.
4) Steps 2 and 3 can be done in reverse order; it doesn't seem to change it.

### Information (if a specific version is affected):
PHP Version: 7.3.5
EDD Version (or branch): 3.0
WordPress Version: 5.4.1

Any other relevant information:
I thought we had this resolved at one point ([ref](https://github.com/easydigitaldownloads/easy-digital-downloads/pull/7781#discussion_r414800661)), but maybe that applied to addresses being typed in, not retrieving an existing address.

**Comment by spencerfinnell** [comment]
PR #7973 adds more consistency between the markup and scripts when referencing IDs and ensures a valid selector is used when trying to fetch the state/region value for calculating tax rates.
