### ISSUE TITLE
PHP sessions enabled by default

### ISSUE THREAD

**Issue by viktorix** [easydigitaldownloads/easy-digital-downloads#7960]
### Expected behavior
Based on [the documentation](https://docs.easydigitaldownloads.com/article/501-edd-use-php-sessions), EDD should be using cookies/database for sessions.

### Actual behavior
On two sites, EDD is using PHP sessions to store data by default. I had to set `define( 'EDD_USE_PHP_SESSIONS', false );` to force EDD to stop using PHP sessions. Our custom session.save_path directory was full of sess_ files.

### Steps to reproduce the behavior
1) Install EDD.
2) Go through the basic setup, no custom coding.
3) Placing product into the cart generates sess_ file.

### Information (if a specific version is affected):

- PHP Version: 7.3
- EDD Version (or branch): 2.9.23 (was happening in previous versions too)
- WordPress Version: 5.4.1

### Any other relevant information:
Based on the documentation, this looks like a bug. I never set `define( 'EDD_USE_PHP_SESSIONS', true );` so I shouldn't need this constant set to false.

Unless I'm missing something?

**Comment by cklosowski** [comment]
@viktorix This is an error in the documentation. We've moved away from the database being the default as it is far less performance-friendly than the PHP sessions.

I'll get that updated. Sorry for the confusion. In the code we do automatic detection if the server supports the session handling, to take advantage of the different session handlers that hosting providers now support that are better than on disk sessions.

**Comment by cklosowski** [comment]
Docs updated: https://docs.easydigitaldownloads.com/article/501-edd-use-php-sessions

**Comment by viktorix** [comment]
@cklosowski thanks. I never paid attention to this until client's site hit inode limit on their hosting with thousands of empty session files. But that was a problem with garbage collection, not deleting old session files.
