### ISSUE TITLE
Display download list e count

### ISSUE THREAD

**Issue by phcaraujo** [easydigitaldownloads/easy-digital-downloads#7961]
How do I display on the user's panel the downloads he has already made through "All Access"?

Another question

How do I add to the product page how many times it has been downloaded?

I don't want to show sales, I want to show how many times it has been downloaded by all users.

**Comment by matt70** [comment]
Yes, I would like to have some all access shortcodes for each product, too.
Something like: [downloads_today] [downloads_week]  [downloads_month] [downloads_year] and [downloads_total]
I don't know, if it is a good idea, to have such a statistic for 10000 products, but at least [downloads_total] would be good starting point ;-)
Matthias

**Comment by ashleyfae** [comment]
Hi @phcaraujo ,

Please get in touch with our support team here to discuss: https://easydigitaldownloads.com/support/ They'll be happy to answer any of your questions.
