### ISSUE TITLE
3.0 - Reports: Improve filters for file download reports

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#7965]
### Expected behavior
When viewing the download reports in Downloads > Reports > Downloads, I expect the dropdown of my products to be easily readable.

### Actual behavior
The dropdown generated for the products is, in my opinion, severely undersized, causing wrapping of the product titles, making it hard to read.

![Screenshot from 2020-05-27 10-00-57](https://user-images.githubusercontent.com/1390124/83050802-ed028c00-a001-11ea-87b5-6a7b654e09ad.png)

### Steps to reproduce the behavior
1) Create a product with a title greater than ~17 characters
2) View the dropdown in the Downloads > Reports > Downloads

### Information (if a specific version is affected):
PHP Version: All

EDD Version (or branch): `release/3.0`

WordPress Version: All

Any other relevant information:

**Comment by spencerfinnell** [comment]
Previously https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7953

After #7953 mine are showing wider than your screenshot: 

Chosen sets the width to the currently selected item -- "All Downloads" in this case. Filter by a Download with a longer name causes the dropdown to be wider:

<img width="229" alt="Screen Shot 2020-05-27 at 5 31 59 PM" src="https://user-images.githubusercontent.com/491124/83074369-075b5a80-a040-11ea-8a2d-98ea4fc799aa.png">

It then gets restricted by the filter's max width:

<img width="329" alt="Screen Shot 2020-05-27 at 5 30 37 PM" src="https://user-images.githubusercontent.com/491124/83074392-1215ef80-a040-11ea-8508-22abdf7b9b09.png">

I think with flexbox we can make these filters a lot more fluid and remove some of the rigid defaults and add a few special cases for things like the Downloads filter.

Related https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7967
