### ISSUE TITLE
3.0 - CSS - Active vertical tab right border z-index issue when viewing reports with filters

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#7966]
### Expected behavior
When using the dropdown menus in reports, I expect them to visually appear above the UI elements.

### Actual behavior
When the active vertical tab appears beneath a dropdown element, the right border appears above the chosen dropdown section:

![white-line](https://user-images.githubusercontent.com/1390124/83051096-5a162180-a002-11ea-9faa-6777c8f9ccc9.png)

In this screenshot it is the white line right after the word 'Expensive'.

### Steps to reproduce the behavior
1) Have a download with a title that is ~17 characters appear in the initial download list.
2) Go to `Downloads > Reports > Downloads` and use the dropdown to select a product.

### Information (if a specific version is affected):
PHP Version: All

EDD Version (or branch): `release/3.0`

WordPress Version: All

Any other relevant information:

**Comment by LisaCee** [comment]
PR  #8173
