### ISSUE TITLE
3.0 - Checkbox input is enlarged on mobile screens (reports screen)

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#7967]
### Expected behavior
Viewing the admin on small screens, I expect inputs to remain recognizable.

### Actual behavior
On screens below 480px wide, the "Exclude Taxes" checkbox is stretched:

![image](https://user-images.githubusercontent.com/4853066/83053107-382a9800-a01e-11ea-818f-b8071fee443c.png)

### Steps to reproduce the behavior
1) Visit Downloads > Reports in 3.0
2) Open your browser's dev tools and emulate a phone sized screen
3) View any report with a checkbox filter (eg Exclude Taxes)

### Information (if a specific version is affected):
PHP Version: 7.3.5
EDD Version (or branch): 3.0
WordPress Version: 5.4.1

Any other relevant information:
The report inputs, especially on the Reports > Exports screen, feel unfinished on mobile devices (borders missing where two inputs are expected to be next to each other, for example, and no padding between inputs). Related: #7966

**Comment by LisaCee** [comment]
PR #8161
