### ISSUE TITLE
3.0 - Taxes - Block Activating Multiple Country Wide Rates in UI

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/easy-digital-downloads#7992]
### Expected behavior

When an existing country-wide rate is activated any other rates that apply to the same full country should not be allowed to be activated.

### Actual behavior

Duplicate tax rates that get migrated can be activated after the fact.

### Steps to reproduce the behavior
https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7602

### Information (if a specific version is affected):
EDD Version (or branch): `release/3.0`/`issue/7602`

Any other relevant information:

Blocked from adding via UI in #6037 and deactivated during migration in #7602

**Comment by spencerfinnell** [comment]
Another improvement we can do is prevent adding blank rates.

**Comment by robincornett** [comment]
@spencerfinnell I just ran into the blank rates issue yesterday and am glad to see you already know about it. Interestingly, I appear to be unable to deactivate the blank rate, and when I click "Save Changes", the blank rate is duplicated. I'm not sure on the order of this--it may be duplicated, and then recreated as active and empty, but I appear to be stuck with a completely empty tax rate (no country, no tax rate).

**Comment by spencerfinnell** [comment]
Empty tax rates prevented in https://github.com/easydigitaldownloads/easy-digital-downloads/issues/8401

**Comment by spencerfinnell** [comment]
PR #8648 prevents multiple tax rates with the same country/region combination (including country-wide) from being added or activated.

To test:

1. Add a country-wide tax rate.
2. Attempt to add the same country-wide tax rate.

- Observe the alert `Duplicate tax rates are not allowed. Please deactivate the existing "%s" tax rate before adding or activating another.` is shown.
- Observe the tax rate is not added.

---

1. Add a country-wide tax rate.
2. Duplicate the country-wide tax rate in the `wp_edd_adjustments` database table to force a duplicate-from-migration scenario. Set the status as `inactive`.
3. Attempt to activate the deactivated duplicate tax rate

- Observe the alert `Duplicate tax rates are not allowed. Please deactivate the existing "%s" tax rate before adding or activating another.` is shown.
- Observe the tax rate is not activated.

---

1. Add a tax rate with a country and region set.
2. Attempt to add another rate with the same country and region set.

- Observe the alert `Duplicate tax rates are not allowed. Please deactivate the existing "%s" tax rate before adding or activating another.` is shown.
- Observe the tax rate is not added
