### ISSUE TITLE
3.0 - Customer lifetime stats do not appear to be updated when they have

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#8004]
### Expected behavior
When I use the "Recount Stats" button (under Tools) for a single customer, and then click the Profile link to see the profile, I expect to see the correct/updated information.

### Actual behavior
Because the entire customer profile is loaded, and then shown selectively using JavaScript, the customer lifetime stats will not show the updated data until the page is reloaded.

### Steps to reproduce the behavior
It helps if you update a customer's `purchase_value` and `purchase_count` directly in the database to something obviously wrong first.

1) Visit the customer details screen for that customer.
2) Under Tools, click the "Recount Stats" button.
3) Click on Profile. The numbers are not updated.

### Information (if a specific version is affected):
PHP Version: 7.3.5
EDD Version (or branch): this may need to be done with issue/7947, which is updating customer lifetime stats
WordPress Version: 5.4.1

**Comment by ashleyfae** [comment]
We could return the new values in the final ajax request and use those to update the markup with JavaScript.
