### ISSUE TITLE
Reduce additional queries

### ISSUE THREAD

**Issue by danieliser** [easydigitaldownloads/easy-digital-downloads#8011]
## Enhancement Request

EDD custom tables using the EDD_DB class query SHOW TABLES LIKE 'table_name' on every request.

![image](https://user-images.githubusercontent.com/847818/84521235-b2a41a80-aca2-11ea-89fe-39f8f8b8bcf6.png)

I propose modifying the construction of these classes to follow a similar pattern to our plugin Popup Maker, or another similar pattern.

This is the guts of our [__constructor()](https://github.com/PopupMaker/Popup-Maker/blob/develop/classes/Abstract/Database.php#L38-L47).

```
		global $wpdb;

		$current_db_version = $this->get_installed_version();

		if ( ! $current_db_version || $current_db_version < $this->version ) {
			// Install the table.
			@$this->create_table();

			if ( $wpdb->get_var( "SHOW TABLES LIKE '{$this->table_name()}'" ) == $this->table_name() ) {
				$this->update_db_version();
			}
		}
```

Benefits here are that:
- we store table versions in an array of **table_name**=>**version**, so there is no additional query to get that info.
- we only process SHOW queries if there is a version mismatch and we are essentially checking the dbDelta call was successful at creating the table.
- we only update the version number if the table was created/updated successfully.
- no more extra queries on each page load.

**Comment by ashleyfae** [comment]
Thanks @danieliser ! This will be fixed when we migrate everything over to [BerlinDB](https://github.com/berlindb/core). That uses the exact method you mentioned, with storing the table version. EDD core will see this in 3.0. Extensions like Software Licensing (which is the one in your example) will take a bit longer.
