### ISSUE TITLE
3.0 - Orders - Country & region dropdown options not visible due to 0px width

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#8015]
### Expected behavior

When I view an order address, I expect to be able to see/use the country and region dropdown.

### Actual behavior

When I navigate directly to an order URL containing `#edd_general_address`, the dropdowns have a 0px width and I cannot view or select any options.

![Screenshot from 2020-06-16 11-49-47](https://user-images.githubusercontent.com/6324272/84765683-7dac0680-afc7-11ea-848b-6af4645abb1d.png)

### Steps to reproduce the behavior
1) Got o Downloads > Orders and click through to edit an order.
2) Click the "Address" tab. At this point it probably looks fine.
3) Ensure your URL contains `#edd_general_address` at the end and refresh the page.
4) The dropdowns are now broken.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0

WordPress Version:

Any other relevant information:

I have this message in my browser console:

> Autofocus processing was blocked because a document's URL has a fragment '#edd_general_address'.

**Comment by spencerfinnell** [comment]
😠 Chosen... #7583 

We don't use Chosen for Country or Region lists on the frontend Checkout. If the argument for Chosen everywhere is that it makes it easier to find items in long lists shouldn't we be using it to help convert carts?... In reality it's much easier to use native `select` selections by just typing on the keyboard with a usable input than trying to wrangle this thing.

#BanChosen

A previous attempt here: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7953

**Comment by robincornett** [comment]
Honestly, when I'm creating a manual order, I am tabbing through the address form and not being able to tab to the country/region select fields throws me every time.

**Comment by ashleyfae** [comment]
> In reality it's much easier to use native `select` selections by just typing on the keyboard with a usable input than trying to wrangle this thing.

Truth. That is 100% easier. I think the question is: do non-techy people know you can do that?

**Comment by spencerfinnell** [comment]
@ashleyfae I think if we felt it wasn't that obvious or it was a requirement for these lists it would have been included as default on the frontend Checkout for all of these years which surely holds the most importance in terms of "ease of use". I'm sure a lot of people customize it themselves though.

There is no right answer of course and we should discuss more on #7583. I'll get this somewhat usable for alpha and we can continue to discuss options afterwards.

**Comment by spencerfinnell** [comment]
#8017 is an attempt to fix this without CSS by using the native `<select>` field's width. Chosen _should_ be doing this normally but for some reason it doesn't work automatically in all instances.
