### ISSUE TITLE
3.0 - Add JavaScript confirmation when permanently deleting an order

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#8026]
### Explain your enhancement (please be detailed)

When _permanently deleting_ an order, we should add a JavaScript confirmation.

### Justification or use case

To prevent accidental permanent deletions.

---

Related discussion regarding permanent deletes here: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7937

EDD 2.9 has a confirmation.

**Comment by ashleyfae** [comment]
@LisaCee This is a good file to put the JavaScript: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/assets/js/admin/orders/list-table.js

The message itself needs to be localised. We already have that available from 2.9 here: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/scripts.php#L469 though we should change the wording to use "order".

If you want to see how the JavaScript is done in 2.9 (though will need some adjusting to work in 3.0), see here: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/assets/js/admin-scripts.js#L1279-L1284

**Comment by ashleyfae** [comment]
@spencerfinnell Do you have any thoughts on where this JavaScript should go? I originally said this file: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/assets/js/admin/orders/list-table.js but upon further digging it looks like:

1. I'm not entirely sure the `list-table.js` file is even being included anywhere? :thinking: (Obviously including it isn't a big deal, but just worth noting.)
2. `edd-admin-orders.js` isn't loaded on the order overview page.
3. If we enqueue `edd-admin-orders` on that page then there are a bunch of JS errors due to the `eddAdminOrderOverview` variable not being set.

**Comment by spencerfinnell** [comment]
@ashleyfae Hmm... the code in `list-table.js` was moved to https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/assets/js/admin/components/advanced-filters/index.js, which does get included.

We should probably just adjust [the check for `eddAdminOrderOverview`](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/assets/js/admin/orders/index.js#L10) and include the alert in that file.

**Comment by ashleyfae** [comment]
> Would it be so awful to just add an inline script against `edd-admin` on those pages?

I guess I'm fine with that. At least while it's only this one small snippet.

**Comment by spencerfinnell** [comment]
`edd-admin` is also still loaded on all EDD admin pages, so it could be stuck in there as well. However the original thinking was to only include things that apply to more than one place in that file. Putting Order-specific things back in it seems like working backwards.

Another option is to add another Webpack entry point and create a separate external script. Something similar to how `tools` is split up between `import` and `export`: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/webpack.config.js#L22-L23

**Comment by LisaCee** [comment]
PR #8474 Adds a JS pop-up to confirm intention before permanently deleting an order.
