### ISSUE TITLE
3.0 - Manually created orders add tax to non-taxable items

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#8029]
### Expected behavior
If a product is marked as non-taxable, I expect it to not have tax collected.

### Actual behavior
When manually creating an order, if tax rates are enabled for a storefront and the order address has a tax rate applied, tax is applied to items which have been marked as non-taxable. Orders placed through the front end are not affected.

### Steps to reproduce the behavior
1) In `release/3.0`, enable taxes.
2) Create a product and mark it as non-taxable.
3) Purchase the product through the front end and use an address which should collect tax.
4) Create a manual order and use an address which should collect tax.
5) The two orders will be different: the front end one is correct.

### Information (if a specific version is affected):
PHP Version: 7.4.1
EDD Version (or branch): release/3.0
WordPress Version: 5.4.2

Any other relevant information:
As I have been working on order adjustment issues, I have noticed that a lot of duplication has to happen to keep  `edd_build_order` (front end order creation) and `edd_manual_order` (admin order creation) in sync.

**Comment by spencerfinnell** [comment]
#8035 checks if an individual Download is taxable.
