### ISSUE TITLE
Maybe update edd_items_in_cart cookie behavior

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#8037]
### Explain your enhancement (please be detailed)
The `edd_items_in_cart` cookie attributes may need to be updated.

### Justification or use case
Adding an item to a cart on a customer site generated this in the dev tools console (Firefox):
>Cookie “edd_items_in_cart” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

**Comment by mihaijoldis** [comment]
Just got a new report/mention of this issue by a customer here https://secure.helpscout.net/conversation/1487714063/182808?folderId=180499
