### ISSUE TITLE
3.0 - get_address method needs to be updated

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#8039]
### Expected behavior
If a logged in user has a stored address, it should be retrieved as part of the checkout process, and `edd_get_customer_address` should work.

### Actual behavior
`EDD_Customer->get_address()` uses `$type = 'primary'` as its default query, so no address is returned, since `billing` is now the default address type, and `is_primary` is the new "primary" address value.

Additionally, when checking out for the first time, an address record is created, but is not assigned as the customer's primary address.

### Steps to reproduce the behavior
1) On a storefront which collects addresses, place an order as a new customer, filling out address data, and creating a new account so that the user will be logged in.
2) Look in the `edd_customer_addresses` table for the `type` and `is_primary` values.
3) Place a second order as this logged in customer. On the checkout screen, the address is not retrieved.

### Information (if a specific version is affected):
PHP Version: 7.4.1
EDD Version (or branch): `release/3.0`
WordPress Version: 5.4.2

Any other relevant information:
Looking at the `EDD_Customer->get_address()` method, I'm thinking that code which uses it needs to be checked and updated to account for the possible returned values (it can return either an `object`, if the type is set correctly, or an `array` of objects). The [checkout template](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/checkout/template.php#L324) is one example--it also does not pass a user ID in, so no address will be retrieved there.

Related: #7254, but creating this as a new issue due to discussion and code/database changes.

**Comment by cklosowski** [comment]
I'm working on this currently and I have the `get_address` method fixed up but seeing an interesting dilemma in the primary address getting added to the customer on first purchase.

Currently when checking out we just 'update' the primary address. I don't think that is ideal. What we should be doing is maybe seeing if this is a new address for the customer, if so, inserting it and setting the new address as the primary, and setting the old addresses as non-primary.

does that make sense @ashleyfae @robincornett ?

**Comment by ashleyfae** [comment]
@cklosowski Just to make sure I understand --

> Currently when checking out we just 'update' the primary address.

Are you saying that we literally do an UPDATE statement on the current primary address and _change_ that value?

If I've understood that correctly, then I definitely agree with this:

> What we should be doing is maybe seeing if this is a new address for the customer, if so, inserting it and setting the new address as the primary, and setting the old addresses as non-primary.

**Comment by robincornett** [comment]
I would also agree with that, although as far as I know, right now we have no [UI] methods to change which physical address is primary, the way we do with email addresses.

Additionally, if I remember correctly, the PR #7874 changed physical address behavior so that currently, new orders (at least manual orders) do not assign an address as primary ([ref](https://github.com/easydigitaldownloads/easy-digital-downloads/pull/7874#issuecomment-642897579)), so it is possible that a customer could have multiple physical addresses, but none of them designated as primary. Unless the work you are doing for this will change that?

**Comment by cklosowski** [comment]
@robincornett Yes, that's correct no UI (yet) and yes I'll be fixing the part that changes the primary address upon checkout. I think we could easily also add the ability to manage the primary address, I'll look into that effort as well.

**Comment by spencerfinnell** [comment]
> Additionally, when checking out for the first time, an address record is created, but is not assigned as the customer's primary address.

When an address is added to an existing Customer for the first time I'm seeing two entries added to the database. One is added with a type of `primary` and another `billing`. The rest of the information is the same until a second address is used during Checkout and then the `primary` entry is updated to the new address.
