### ISSUE TITLE
Export options should an All option in all dropdown boxes

### ISSUE THREAD

**Issue by dgoldak** [easydigitaldownloads/easy-digital-downloads#8046]
### Explain your enhancement 
Export options should always include an All option in the dropdown and should default to that. 

For example, in this screenshot Export Orders has an All Statuses option, selected by default. But Export Sales and Export Taxed Orders don't have All Downloads, All Customers or All Countries options.
<img width="974" alt="Screen Shot 2020-07-08 at 12 02 02 PM" src="https://user-images.githubusercontent.com/30910807/86948706-26570d00-c113-11ea-8752-837df6161e62.png">

### Justification or use case
We should be consistent for all export options. Also, it's not obvious to all users or a good user experience that no selection would export all.

**Comment by dgoldak** [comment]
I realized the Date selections are not populated either, can that get requested here or should I open a new request?

It's done for one of the reports but not the others. For example?
<img width="711" alt="Screen Shot 2020-07-13 at 9 09 42 AM" src="https://user-images.githubusercontent.com/30910807/87314312-a7821b80-c4e8-11ea-804e-f917c4d39913.png">

**Comment by robincornett** [comment]
@dgoldak I would raise that as a separate issue--those are two different kinds of fields (simple `select` fields for the first, actual date picker fields for the second), so changing them has, I think, deeper ramifications.
