### ISSUE TITLE
3.0 - Regions do not update for Reports > Export when the country is changed

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#8053]
### Expected behavior
When I change the country from the United States to "Export Taxed Orders", I expect the regions select field to update to use the new country's regions.

### Actual behavior
When I change the country, the regions do not change.

### Steps to reproduce the behavior
1) Visit Downloads > Reports > Export.
2) Under "Export Taxed Orders", select a country other than the United States.

### Information (if a specific version is affected):
PHP Version: 7.4.1
EDD Version (or branch): release/3.0
WordPress Version: 5.4.2

**Comment by ashleyfae** [comment]
This is also an issue when filtering by country in Downloads > Orders. Click on `More` to expand more filters and change the country.

**Comment by ashleyfae** [comment]
A few issues:

1. The country dropdown on the report page is missing:
    1. The class `edd_countries_filter`, which is required to get this working.
    2. The `data-nonce` attribute.
2. The region dropdown on the same page is missing the class `edd_regions_filter`.
3. It looks like the JavaScript logic for this is in `assets/js/admin/settings/index.js` (`edd-admin-settings`). But this isn't being loaded on the reports/orders pages.

What I think we should do:

1. Can we move the JS logic for the country selector to be in `edd-admin-scripts` instead?
2. Given all the required dependencies for the actual select box (specific class names, data attribute), I'm wondering if we should add new methods to the HTML elements class for `country_select()` and `region_select()`. That ensures all the pieces are in place.

**Comment by ashleyfae** [comment]
To clarify testing steps:

> Under "Export Taxed Orders", select a country other than the United States.

It's actually select a country other than your shop country. So in my case, my shop country was United Kingdom, and all the regions were loaded for that. In release/3.0 they never switch from UK ones.
