### ISSUE TITLE
3.0 - Improve the date field spacing in the Exports

### ISSUE THREAD

**Issue by dgoldak** [easydigitaldownloads/easy-digital-downloads#8054]
Date field spacing should be improved in EDD3 as they are spaced too close and almost overlap.

This spacing looks good:
<img width="447" alt="Screen Shot 2020-07-13 at 9 14 38 AM" src="https://user-images.githubusercontent.com/30910807/87314752-4c9cf400-c4e9-11ea-826a-121e1d4d1b8e.png">

But, all other date fields under Downloads > Reports > Exports hav not space between the fields which do not look good:
<img width="299" alt="Screen Shot 2020-07-13 at 9 15 39 AM" src="https://user-images.githubusercontent.com/30910807/87315007-8cfc7200-c4e9-11ea-9c5d-0cac27ff8a44.png">

Including the filter at the top for all Reports:
<img width="519" alt="Screen Shot 2020-07-13 at 9 17 05 AM" src="https://user-images.githubusercontent.com/30910807/87315117-aef5f480-c4e9-11ea-88ef-21c8f866aad3.png">

**Comment by robincornett** [comment]
I think this has been resolved by #8091 and can be closed.

**Comment by ashleyfae** [comment]
Yeah it's looking good to me right now. @dgoldak Feel free to reopen if you feel something is missing.
