### ISSUE TITLE
3.0 - Discount "Download Requirements" conditions toggle with each product added

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#8068]
### Expected behavior
Once a download/product has been added to the "Download Requirements" on the Discounts screens, I expect the product conditions field to show, and to persist.

### Actual behavior
When I add one product to the "Download Requirements", the product conditions select input shows. When I add a second one, the input is toggled to hide. With each new product added, the conditions toggle between show/hide.

### Steps to reproduce the behavior
1) Create a new discount.
2) Add a product to the "Download Requirements" field. The product conditions will show.
3) Add another product; the conditions input will disappear.

### Information (if a specific version is affected):
PHP Version: 7.4.1
EDD Version (or branch): release/3.0 (this does not toggle in 2.9.x)
WordPress Version: 5.4.2

Any other relevant information:
It looks like [the script is toggling the conditions input every time the download requirements input changes](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/assets/js/admin/discounts/index.js#L19), not just when the first/only item is added/removed.

**Comment by LisaCee** [comment]
PR #8120
