### ISSUE TITLE
3.0 - Discrepancy in refund screens

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#8069]
### Expected behavior
When I issue a refund, I expect the refund amounts to be consistent when I'm viewing the refund in the admin.

### Actual behavior
When a discount was used on an order, and I issue a refund, I am able to view a version of the refund which does not show the discount (or the correct total). It looks like there are two different links/screens which can be used to view a refund:
- `https://3dd.local/wp-admin/edit.php?post_type=download&page=edd-payment-history&view=view-refund-details&id=269` (the discount does not show)
- `https://3dd.local/wp-admin/edit.php?post_type=download&page=edd-payment-history&view=view-order-details&id=269` (the discount does show)

Looking in the database, the row for the order information appears to be correct, so this could maybe just be a display issue, but I do wonder why there are two different links for viewing a refund.

### Steps to reproduce the behavior
1) Create/run an order which uses a discount code.
2) Refund the order.
3) On the original order details screen, click the link to view the refund. The discount does not show as part of this refund.
4) Go back to the original order and click "View Customer Record". The refund amount on the Customer Details screen is correct.
5) Click the link to view the refund details. This will take you to the order screen which does show the discount as part of the refund.
6) Visit the orders list table and view the refunds. The title/Edit links for the refund are for the `view-refund-details` screen (the incorrect one).

### Information (if a specific version is affected):
PHP Version: 7.4.1
EDD Version (or branch): release/3.0
WordPress Version: 5.4.2

Any other relevant information:
I'm not sure if the `view-refund-details` screen needs to be updated, or removed (in favor of `view-order-details`), but I think the links to view the refunds should be consistent, so if the screen is updated to show the correct information, the link on the Customer Details screen should probably be changed to use `view-refund-details`, to be consistent with the order details and list table.

**Comment by spencerfinnell** [comment]
@robincornett The link when viewing the Customer should link to `view-order-refund`. That screen was introduced in https://github.com/easydigitaldownloads/easy-digital-downloads/pull/7559

Discounts can be added to the separate Refund view. We should keep fees/credits in mind as well. 

You can see how adjustments are added to the Order view [here](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/payments/orders.php#L692) if you'd like to move them to [refunds](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/payments/refunds.php#L98); or I can get it started.

**Comment by robincornett** [comment]
I went ahead and took a stab at it--thanks, @spencerfinnell for pointing me in the right direction.

**Comment by spencerfinnell** [comment]
@robincornett This actually needs to be a bit more nuanced as right now it's displaying the discount amount for the full Order, not the Order Items that were refunded. 

The refund flow/modal also doesn't offer the ability to refund fees so those should be excluded from the list as well.

...and credits do not show either -- the full item amount gets refunded, not the amount charged. That will need addressing too, but I'm not sure the best route...

**Comment by robincornett** [comment]
Should credits maybe have their own issue opened, @spencerfinnell ? I've opened one to query about tax rates, and we have this one. I didn't open one for discounts in general as so far they've seemed complete and correct.

**Comment by spencerfinnell** [comment]
Yes let's start a new issue for credits. 

Looking now it looks like refunding one Order Item in an Order that contains a Discount creates a new Adjustment for the total amount of the Discount not how much is applied to the specific Order Item -- we should address that separately as well too.
