### ISSUE TITLE
3.0 - Order Discounts Don't Work With Partial Refunds

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/easy-digital-downloads#8076]
### Expected behavior

When I refund one Order Item that has a discount amount applied to it, only the discount amount that applies to that particular Order Item should be refunded.

### Actual behavior

The full Discount is refunded.

### Steps to reproduce the behavior
1) Purchase two items (frontend Checkout) with a 10% Discount.
2) Refund 1 Order Item.

Note that an Order-level Adjustment is created for the Refund for the full amount of the Discount, not the amount applied to the individual Order Item that was refunded.

### Information (if a specific version is affected):

EDD Version (or branch): `release/3.0`

Any other relevant information:

When the Order is created a single Adjustment is added with the discount amount total. When a Refund is created all of the original Order's Adjustments are recreated: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/orders/functions/refunds.php#L345-L356

Related #8075

**Comment by ashleyfae** [comment]
Closing in favour of https://github.com/easydigitaldownloads/easy-digital-downloads/issues/8075 . It'll be handled there.
