### ISSUE TITLE
PHP 7.4 error for get_magic_quotes_runtime.

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#8083]
### Expected behavior
When on PHP 7.4, no errors should be thrown.

### Actual behavior
When on PHP 7.4 this error is thrown:
`PHP Deprecated: Function get_magic_quotes_runtime() is deprecated in /wp-content/plugins/easy-digital-downloads/includes/process-download.php on line 185'`

### Steps to reproduce
1) Download a file from the front end.

### Information (if a specific version is affected):
PHP Version: 7.4

EDD Version (or branch): `master`

WordPress Version: All

Any other relevant information:
We probably just need to reorder this logic so that the call to the funtion only happens if the PHP version check passes:
``if ( function_exists( 'get_magic_quotes_runtime' ) && get_magic_quotes_runtime() && version_compare( phpversion(), '5.4', '<' ) ) {``

**Comment by LisaCee** [comment]
PR #8084
