### ISSUE TITLE
EDD Login process should use wp_safe_redirect

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#8087]
## Bug Report
Processing of the EDD Login form should use wp_safe_redirect. See conversation here:
https://github.com/easydigitaldownloads/easy-digital-downloads/pull/8085#discussion_r471810627

**Comment by spencerfinnell** [comment]
I understand the safety advantage of `wp_safe_redirect()` but I wonder if it becomes too restrictive when there is a filter for the this redirect URL? SSO or multisite mentioned in the original comment https://github.com/easydigitaldownloads/easy-digital-downloads/pull/8085#discussion_r471810627 seems like a common enough reason not to force this?

**Comment by ashleyfae** [comment]
We could run it through `wp_safe_redirect()` it as it's passed into the filter. That way it's done by default, but people who filter it can change it to whatever they want.

**Comment by ashleyfae** [comment]
Actually I just realized what I said makes no sense. I shouldn't comment on GitHub issues in the morning. XD
