### ISSUE TITLE
Removing downloads from payments does not work in WordPress 5.5+

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#8092]
### Expected behavior
When viewing order details in admin, and clicking Remove download, no errors should present themselves, and the download should be removed.

### Actual behavior
When clicking remove download, a JS error is thrown:
`SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`

The page is refreshed, and the download is not removed.

This is caused by a change in jQuery that no longer supports the conditional checks of inputs without the `length` attribute being checked.

### Steps to reproduce the behavior
1) View an order in the admin that has no fees and/or taxes. And has multiple downloads.
2) Click 'Remove' on one of the products.
3) Watch the page refresh without removing, and if you have an extension to view JS errors, the error above (or view it in console, with Persist Logs enabled)
etc, etc

### Information (if a specific version is affected):
PHP Version: All

EDD Version (or branch): `2.9.23`

WordPress Version: 5.5+

Any other relevant information:

**Comment by spencerfinnell** [comment]
@cklosowski There were the only other instances I could find:

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/assets/js/edd-ajax.js#L73-L74
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/assets/js/edd-ajax.js#L215-L216

**Comment by cklosowski** [comment]
@spencerfinnell those seem to still work. Should they not?

**Comment by cklosowski** [comment]
@spencerfinnell gotcha, was testing those and didn't see errors, but just pushed a commit that does check `.length` on the `cart_wrapper` variable.
