### ISSUE TITLE
Some Export Select Fields Hidden

### ISSUE THREAD

**Issue by LisaCee** [easydigitaldownloads/easy-digital-downloads#8094]
### Expected behavior
When I resize the Downloads -> Reports -> Export screen I expect all select fields to be visible

### Actual behavior
On screens sized 481px - 542px there are fields hidden / half-hidden and inaccessible to chose.

Export Taxed Orders is the most noticeable example since the `Country` and `Region` fields are not visible.
![image](https://user-images.githubusercontent.com/18077352/90705778-94314100-e248-11ea-921b-e130d641c29f.png)

Also hidden or half-hidden:
- Export Sales and Earnings
- Export Orders
- Export Customers

### Steps to reproduce the behavior
1) Go to Downloads -> Reports -> Export
2) Resize screen to be between 481px - 542px and see hidden / half-hidden fields
3) Resize screen outside of 481px - 542px range and see all of the fields

### Information (if a specific version is affected):
PHP Version:
`7.3`
EDD Version (or branch):
`release/3.0`
WordPress Version:
`5.5`

Any other relevant information:
~~- This issue is not fixed in #7722~~
- Sort of related to #8054
- I tested in both Chrome and Firefox

**Comment by robincornett** [comment]
I don't think this is related to Chosen/JS, as it happens with JS disabled as well. If I add `clear:both;` to the rules for `.edd-reports-wrapper .postbox` then the issue resolves. But my personal feeling is that although that resolves the issue visually, it doesn't actually fix it, more of a bandaid fix.

I think the deeper issue is in [these lines](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/assets/css/edd-admin.css#L2403-L2422) of CSS which are applying a float to everything in the export forms, which breaks the display of the parent container. Resetting the styling for these forms and starting fresh would help, but are affected by the changes you're making to the date inputs, so my $.02 would be to fork off of that, maybe.

**Comment by LisaCee** [comment]
Looking more into this issue, if I try to get rid of the `display: float` and change it to `display: flex`, do we want to use this opportunity to determine exactly how we want the reports screen to look?  I can try to make it look as close as possible as it does currently, just making sure all of the selects are visible at all breakpoints or do we want to standardize it a bit more?  The Reports->Export screen can certainly use some more padding.  Anything else we want to change?  @robincornett @ashleyfae

**Comment by robincornett** [comment]
Since the Exports screen is part of the Reports, I think it would be really neat if it had the same kind of general visual setup as the other reports screens. This is rough, just tinkering in dev tools, but something like this, using CSS grid as the other reports screens do, and then the inputs would all have to get their styling updated:

![image](https://user-images.githubusercontent.com/4853066/92480635-2cb94200-f1b3-11ea-8c33-d92304d050b0.png)

I don't really like how the inputs themselves look, but I feel like the grid in general would give a better sense of separation of forms, and continuity of reports.

**Comment by ashleyfae** [comment]
I don't love how it looks now -- just one massive list. I'm definitely open to some design changes.

I think @robincornett makes a good point that the current design lacks continuity. It doesn't really feel like Exports is part of the Reports UI, even though it is. It clearly looks tacked on.

I'm open to the grid idea if we can work on making the inputs nicely uniform.

**Comment by spencerfinnell** [comment]
I love that idea @robincornett. It helps organize things a lot.

**Comment by LisaCee** [comment]
I'm sure I've broken some other things, but what are your thoughts about this layout for smallest breakpoints (480px)?

**Comment by ashleyfae** [comment]
I adore it! Awesome work @LisaCee !

**Comment by robincornett** [comment]
I think it looks fantastic! My only quibble is with the _to_ off to the right for the first one, but I don't know if there is a better way to manage that when the two groups of selects need to be on different lines, which they definitely do. One thought _might_ be to put the _to_ on its own line, maybe with dashes on either side, similar to what I think is done with the _or_ in the PRB work on Stripe? So on small screens it would be something like:

```
Sep 2020
-- to -- 
Sep 2020
```

but that may end up being awkward, too--if so, I can live with the offset as long as its consistent, which it is.

**Comment by LisaCee** [comment]
I agree with you Robin.  That was iffy for me, too.

**Comment by LisaCee** [comment]
Does anyone know why some of the export buttons have spinners and others do not?  Style-wise, it's causing the spacing difference seen here:
![image](https://user-images.githubusercontent.com/18077352/93276237-e8f6a780-f773-11ea-9ca5-72275d0d02e3.png)

**Comment by robincornett** [comment]
It's probably due to the length of time an export is expected to take, is my guess. If you add a `display:none;` to the spinner that's taking up space, that will resolve the spacing issue (may need to check and make sure that the spinner still displays when it's supposed to though). I have spent a lot of time with spinners in an extension for the last week or two.

**Comment by LisaCee** [comment]
PR #8106.  Help me figure out what I broke by accident.

**Comment by spencerfinnell** [comment]
So much easier to use @LisaCee! I left some feedback relating to the CSS that is currently targeting more than it should.
