### ISSUE TITLE
Failed login reset password link should not always go to the checkout page

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#8100]
### Expected behavior
When I click a password reset link and request a password reset, I expect the final redirect to take me back to where I was, or the front page of the site if that is not possible.

### Actual behavior
Since changes in 2.9.24, using an EDD login form and failing to log in (due to an incorrect username or password), the password reset link includes a redirect to the [EDD checkout screen](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/login-register.php#L147). This is the case even if the login shortcode is on the profile page, or the purchase history page.

### Steps to reproduce the behavior
1) Create a page with the EDD login shortcode.
2) Log in from that page with an invalid username or password.
3) Fill out the form. You are redirected to the checkout screen.

### Information (if a specific version is affected):
PHP Version: 7.4.1
EDD Version (or branch): master, 2.9.24
WordPress Version: 5.5.1

Any other relevant information:
Introduced in PR #8085.

**Comment by goldkast** [comment]
I have same problem!!!
