### ISSUE TITLE
Critical issue on flat amount discount

### ISSUE THREAD

**Issue by Codevz** [easydigitaldownloads/easy-digital-downloads#8113]
## Bug Report

When I set discount amount to any price more than product price EDD can't calculate proper price for checkout. For e.g. my item price is $39 and when I set discount amount to 40 for 3 quantity, EDD calculated 78 instead of 77 and this affected also on more quantity.

### Information (if a specific version is affected):
PHP Version: 7.2+

EDD Version (or branch): 2.9.25

WordPress Version: 5.5.1

**Comment by Codevz** [comment]
FYI, This problem only occurs when `Cart Item Quantities` from `Settings > Misc` is enabled.

**Comment by Codevz** [comment]
I found it in file class-edd-cart.php on line 707, this if statement:

`if ( $discounted_price < 0 ) {`

should be 

`if ( $discounted_price < 0 && ( ! empty( $item['quantity'] ) && $item['quantity'] <= 1 ) ) {`

**Comment by ashleyfae** [comment]
Thanks @Codevz . It looks like this issue is fixed in 3.0 already. :+1:
