### ISSUE TITLE
3.0 - Reloading migration screen during upgrade is not recoverable

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#8118]
### Expected behavior
If I do something I should not do during the UI migration process--namely, refresh the migration screen or leave it--I would hope that I could still finish the migration.

### Actual behavior
While checking something else, I refreshed the migration screen while it was in the middle of migrating the orders (yes, I know I should not have done it and there is a message, but I had reasons). So now my migration screen looks like this:

![image](https://user-images.githubusercontent.com/4853066/93895291-aaa24080-fcbd-11ea-8bd8-32c93bf00244.png)

Everything after "Update Orders" says, "Please complete the previous steps..." but I cannot interact with anything on the screen, so as a user, I'm stuck unless I switch to using CLI. Note also that the orders message says, "Your orders database has been upgraded." (The new database tables have been created and are partially populated, but the migration is not complete--not all orders have been migrated.)

### Steps to reproduce the behavior
1) Update a site from EDD 2.9 to 3.0.
2) Visit the migration screen (`/wp-admin/index.php?page=edd-upgrades&edd-upgrade=v30_migration`).
3) Begin the migration.
4) Interrupt the migration by refreshing the page (I did it during step 3, Orders).

### Information (if a specific version is affected):
PHP Version: 7.4.1
EDD Version (or branch): release/3.0
WordPress Version: 5.5.1

Related: #6880

**Comment by ashleyfae** [comment]
A JavaScript alert to not leave the page is another (or additional option).
