### ISSUE TITLE
Undefined index: total_spent when no Customer exists

### ISSUE THREAD

**Issue by mihaijoldis** [easydigitaldownloads/easy-digital-downloads#8128]
### Expected behavior
to not have any notices in the error logs

### Actual behavior
Customer reports:
Since your last plugin update the bug below shows up in your logs. Could you have a look at this bug:
[29-Sep-2020 10:28:31 UTC] PHP Notice: Undefined index: total_spent in /home/_redacted_/public_html/wp-content/plugins/easy-digital-downloads/includes/user-functions.php on line 353

### Steps to reproduce the behavior
I was able to replicate this via the Debug Bar console by running the code below but i deleted the EDD Customer record before running it.
```
<?php
	$stats = edd_get_purchase_stats_by_user( 2 );

	print $stats['total_spent'];
```

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): 2.9.25

WordPress Version: latest

Any other relevant information:
perhaps returning an empty array but with the indexes set to '' by default if no Customer exists here https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/user-functions.php#L316 ?

**Comment by ashleyfae** [comment]
To reproduce:

1. Create a new user. Do not make them a customer.
2. Manually run `edd_get_purchase_stats_by_user()` with their user ID.
