### ISSUE TITLE
3.0 - Update edd_get_ functions to access Berlin methods directly

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#8131]
### Explain your enhancement (please be detailed)
Based on a discussion with @JJJ, we are suggesting that `edd_get_` functions, which currently call `edd_get_*_by`, be updated to access and use Berlin's `get_item` method directly.

### Justification or use case
John started looking into this based on #8125, where I discovered that the store recount tool was sending a payment object, rather than an ID, to the `edd_get_payment_amount` function. The doc block for that function says that the parameter should be an integer, not an object, but it doesn't check for the parameter type, so an object can be passed to it without an obvious failure.

`edd_get_payment_amount` in turn calls `edd_get_order`, which also anticipates an ID, and in turn calls `edd_get_order_by`.

`edd_get_order_by` initializes `EDD\Database\Queries\Order()` and finally uses that.

John's suggestion is to allow `edd_get_order` to access the Berlin method directly, removing the last layer of abstraction, to something like this:

```php
**
 * Get an order by ID.
 *
 * @since 3.0
 *
 * @param int $order_id Order ID.
 * @return EDD\Orders\Order|false Order object if successful, false otherwise.
 */
function edd_get_order( $order_id = 0 ) {
	$orders = new EDD\Database\Queries\Order();
	// Return order
	return $orders->get_item( $order_id );
}
```

He says that with this change, the `$order_id` variable no longer has to be an integer, but could also be an array or object, because "`get_item()` internally shapes the ID from an object or an array if need be."

There are 14 `edd_get_` functions which could be updated similarly.

**Comment by JJJ** [comment]
See: https://github.com/sugarcalendar/core/issues/121
