### ISSUE TITLE
Imported CSV Accessible in Uploads Directory

### ISSUE THREAD

**Issue by WildeWebMarketing** [easydigitaldownloads/easy-digital-downloads#8162]
Are imported CSV files supposed to remain in the uploads directory?

All my CSV imports are openly accessible to the world after importing unless I manually delete them.

Is there any way to automatically delete after the the import is completed?

**Comment by ashleyfae** [comment]
We'll look into this. We should be removing it after the import.

**Comment by robincornett** [comment]
@ashleyfae this doesn't have a milestone yet--wanted to see if it was able to go into 2.10 possibly, or should wait.

**Comment by ashleyfae** [comment]
@robincornett Added it to 2.10. :+1:
