### ISSUE TITLE
3.0 - Manual Orders - Fatal error when adding discount to an order that contains a fee

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#8164]
### Expected behavior

I expect to be able to add a discount code to an order that contains a fee.

### Actual behavior

When manually creating an order, I get a fatal error when trying to apply a discount to an order that already contains a fee. The following error is triggered:

```
PHP Fatal error:  Uncaught Error: Call to a member function get_type() on bool in /var/www/edd3/wp-content/plugins/easy-digital-downloads/includes/ajax-functions.php:1453
```

### Steps to reproduce the behavior
1) Manually create an order via the admin area.
2) Add a download to the order.
3) Apply an adjustment to the order. I'm using: Type: Fee; Apply to: Entire order; Amount: $50. But I do not think the settings particularly matter.
4) Then attempt to add a discount code. Fatal error is triggered after selecting the discount from the dropdown and clicking "Add Discount".

### Information (if a specific version is affected):
PHP Version: 7.4

EDD Version (or branch): Using branch `issue/8159` due to the JavaScript error that's currently triggered when on `release/3.0`.

WordPress Version: 5.6-beta1-49280

Any other relevant information:

**Comment by robincornett** [comment]
I poked at this one a little bit today (I did not mean to move it) and think that the issue can be resolved in PHP [when the discount is retrieved from the database](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/ajax-functions.php#L1448)--we can add a check to continue in the loop if no discount is retrieved.

What appears to be happening is that the JavaScript is [retrieving all of the adjustments](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/assets/js/admin/orders/order-overview/collections/order-items.js#L84), not just the discounts, and sending the IDs to the PHP function. I tried a few different things and could not figure out how to adjust the script to check for the adjustment type and return only adjustment typeID for discounts. Fixing this directly could reduce the number of adjustments sent to the PHP loop, by weeding out fees and credits up front, but the PHP piece might be enough.

**Comment by spencerfinnell** [comment]
@robincornett You should be able to filter the collection via:

```js
state.get( 'adjustments' ).getByType( 'discount' );
```

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/assets/js/admin/orders/order-overview/collections/order-adjustments.js#L95-L107
