### ISSUE TITLE
3.0 - Download repeatable row changes are not backwards compatible for extensions

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#8195]
### Expected behavior
As much as possible, I expect 3.0 code to work with extensions, even if they need to be updated for full compatibility.

### Actual behavior
3.0 has made changes to the repeatable rows metabox markup and JS behavior (anything other than opening/closing divs have been removed to try to simplify):

```html
<!-- EDD 3.0 markup -->
<div class="widefat edd_repeatable_table">

	<div class="edd-file-fields edd-repeatables-wrap ui-sortable">

		<div class="edd_repeatable_upload_wrapper edd_repeatable_row">

			<div class="edd-repeatable-row-header edd-draghandle-anchor">
			</div> <!-- /edd-repeatable-row-header -->

			<div class="edd-repeatable-row-standard-fields">
			</div> <!-- /edd-repeatable-row-standard-fields -->
		</div> <!-- /edd_repeatable_row -->
	</div> <!-- /edd-repeatables-wrap -->

	<div class="edd-add-repeatable-row">
		<button class="button-secondary edd_add_repeatable">Add New File</button>
	</div> <!-- /edd-add-repeatable-row -->
</div> <!-- /edd_repeatable_table -->
```

In 2.9, the same repeatable rows' markup is:

```html
<!-- EDD 2.9 markup -->
<div class="widefat edd_repeatable_table">

	<div class="edd-file-fields edd-repeatables-wrap ui-sortable">
		<div class="edd_repeatable_upload_wrapper edd_repeatable_row">
			<div class="edd-repeatable-row-header edd-draghandle-anchor">
			</div> <!-- /edd-repeatable-row-header -->

			<div class="edd-repeatable-row-standard-fields">
			</div> <!-- /edd-repeatable-row-standard-fields -->
		</div> <!-- /edd_repeatable_row -->
				
		<div class="edd-add-repeatable-row">
			<div class="submit" style="float: none; clear:both; background: #fff;">
				<button class="button-secondary edd_add_repeatable">Add New File</button>
			</div>
		</div> <!-- /edd-add-repeatable-row-->
	</div> <!-- /edd-repeatables-wrap -->
</div> <!-- /edd_repeatable_table -->
```

Note that in 2.9, the `edd-add-repeatable-row` is a _child_ of the `edd-repeatables-wrap`; in 3.0, it is a _sibling_.

The changed markup necessitates changes in the related JS. In 2.9/2.10:

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/5978e87a735473da00675bc174c60b1a7c156933/assets/js/admin-scripts.js#L105

but in 3.0:

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/7a0b64839317b93c5e4619f2534fd8fd3a7f1a89/assets/js/admin/downloads/index.js#L114

### Steps to reproduce the behavior
1) Set up two different sites, one running 2.9.x/master and one running release/3.0.
2) Enable an extension which uses the repeatable row script/markup, such as Software Licensing (upgrade paths).
3) Attempt to click the "Add New" button for the extension in 3.0. It does not work.

### Information (if a specific version is affected):
PHP Version: 7.4.1
EDD Version (or branch): release/3.0
WordPress Version: 5.5.3

Any other relevant information:
I've been working on [PR 1642](https://github.com/easydigitaldownloads/EDD-Software-Licensing/pull/1642) in Software Licensing to attempt to get the markup and behavior consistent with EDD core and working, assuming that this is set in stone in 3.0. However, doing a search for extensions which use the repeatable row markup/script, I've come up with the following list, all plugins which I assume will be negatively impacted:
- [Software Licensing](https://github.com/easydigitaldownloads/EDD-Software-Licensing/blob/c32f4c7df172427a75493221ba1f7303d762d089/includes/admin/metabox.php)
- [Download Images](https://github.com/easydigitaldownloads/edd-download-images/blob/2bca9bbdcfc6834a0c85568e00f38b2df449ecbd/edd-download-images.php)
- [Content Restriction](https://github.com/easydigitaldownloads/EDD-Content-Restriction/blob/a758df9baeeb276f0e3b146d0073e6943e09fea2/includes/admin/metabox.php)
- [Commissions](https://github.com/easydigitaldownloads/EDD-Commissions/blob/4bdb7ef714f7ed889d8f6f34d791e15150d9d6b0/includes/admin/metabox.php)
- [Simple Shipping](https://github.com/easydigitaldownloads/edd-simple-shipping/blob/97b5a4fd3765c07ed0c5451a5443fb35cea5b8e1/includes/tracking.php)
- [Message](https://github.com/easydigitaldownloads/edd-message/blob/499887def32429411ce2efd17c25b9837999c254/includes/admin/customer.php)
- [Audio](https://github.com/easydigitaldownloads/edd-audio/blob/3a7bc435e1bb6a335c3c05e28528c940ce9791b9/edd-audio.php)
- [All Access](https://github.com/easydigitaldownloads/edd-all-access/blob/4870ddde9a3df4577b86b7cda276c877b1857c35/includes/integrations/plugin-restrict-content-pro.php)
- Git Download Updater uses the markup, but currently does not support adding new rows, so I'm leaving it off the list.

At this point, I'm wondering if the changes made in 3.0 can be revisited to fix this behavior. Looking through the markup, I think the new markup is the better choice, but I'm not sure how extensions could gracefully manage updating their markup and still retain 2.9 compatibility. The [blame takes me here](https://github.com/easydigitaldownloads/easy-digital-downloads/commit/c30cc01ef071a589cfb45140e9682127baad825c), but I can't really tell what the reasoning was. If the core markup/script is to remain unchanged, each of these extensions will have to have the "Add New" markup adjusted to work with both 2.9 and 3.0.

Marking this as a regression, but would love to have a discussion about how to proceed.

**Comment by spencerfinnell** [comment]
@robincornett Could we retrieve the row to clone via:

```js
row = button.closest( '.edd_repeatable_table .edd_repeatable_row:last-child' ),
```

**Comment by robincornett** [comment]
@spencerfinnell that isn't working for me. I think the issue is that the `:last-child` pseudo-element doesn't appear to work with a class, only when used with an element (tinkering here suggests that `:last-of-type` is the same...not sure why this is what I'm finding, but if I try to add a background to `.edd_repeatable_table. edd_repeatable_row:last-child` in dev tools, it's not a valid/existing selector). In 2.9, the `edd_repeatable_row` is not the last child--it's `edd-add-repeatable-row` in core, but in SL (for example), it's just a `tr` with no class.

**Comment by spencerfinnell** [comment]
@robincornett Testing with `row = button.closest( '.edd_repeatable_table' ).find( '.edd_repeatable_row' ).last(),` seems to work on both the Upgrade Path and core metaboxes.

**Comment by robincornett** [comment]
Super quick test here, too, suggests that you are correct. I think I would still want to leave the updated SL markup intact, as it feels more semantically correct, but if we do this, it means extensions which aren't updated right away won't be as "broken", at least not with this issue.

**Comment by robincornett** [comment]
Testing the suggested fix:
- [x] Software Licensing: works
- [ ] Audio: does not work (no `.edd_repeatable_table` class in markup)
- [x] Download Images: works
- [x] Content Restriction: does not work (`edd-admin-downloads.js` does not load on non-download post types)
- [x] Commissions: works
- [x] Simple Shipping: works
- [ ] Message: does not work (no `.edd_repeatable_table` class in markup)
- [ ] All Access: n/a; the repeatable row markup is used on the Tools screen, but without an "Add New" button

So I think @spencerfinnell's proposed fix is a good one, and we can create issues in the relevant repositories to bring them up to date, without it being a breaking change (for the most part).
