### ISSUE TITLE
3.0 - UI Migration does not mark everything complete

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#8197]
### Expected behavior
When I migrate from 2.9 > 3.0, I expect each migration step to be marked complete when it's done.

### Actual behavior
When I migrate via CLI, and then visit the migrations screen, all buttons show as inactive (migration is complete).

When I migrate via the UI, reloading the migration screen shows active buttons for ([noted as part of testing a separate issue](https://github.com/easydigitaldownloads/easy-digital-downloads/pull/7871#pullrequestreview-527268291)):

- Upgrade Orders
- Upgrade Notes
- Upgrade Customer Notes

### Steps to reproduce the behavior
1) Start with an EDD site running 2.9 and switch to 3.0.
2) Visit `/wp-admin/index.php?page=edd-upgrades&edd-upgrade=v30_migration` and run the migration from there.
3) Reload the screen when the migration is done. For me, the three buttons above show as active.
4) You can run the same migration via CLI and then visit the migration screen to see if the buttons are active.
etc, etc

### Information (if a specific version is affected):
PHP Version: 7.3.5
EDD Version (or branch): release/3.0
WordPress Version: 5.5.3

**Comment by ashleyfae** [comment]
Assigning this to myself because I might naturally fix it as I do https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6880 and https://github.com/easydigitaldownloads/easy-digital-downloads/issues/8118

**Comment by ashleyfae** [comment]
Closing this, as I believe it has generally been resolved by the fixes in #6880 and will be improved further in #8118 .
