### ISSUE TITLE
Update `test_get_payment_completed_date` test for a looser comparison

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#8206]
### Explain your enhancement (please be detailed)
Consider updating the `test_get_payment_completed_date` test (there may be others, not sure) to allow the time to be within a minute or two of the expected time.

### Justification or use case
If the time changes during the test (eg from `10:01` to `10:02`), the test fails because the two times are not identical. It seems like this is a common test failure, but not an unreasonable scenario. If the test granted a tiny bit of leeway on the comparison, that would save us looking into what are essentially false failures.

**Comment by ashleyfae** [comment]
Closing this in favour of the existing issue: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7270

(However, I agree with you that I'd rather have a looser comparison in the test. I don't think we need an entirely new function for this, as originally proposed.)
