### ISSUE TITLE
3.0 - Fails to parse time string when creating discount codes

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#8207]
### Expected behavior
When creating discount codes and setting any of the date input fields, Carbon fails due to being passed an invalid date format such as 2020-11-30 ::00. 

This happens when the hour/minute fields are empty and the following conditional logic fails:

`$start_date_hour   = (int) $data['start_date_hour'] >= 0 && (int) $data['start_date_hour'] <= 23 ? sanitize_text_field( $data['start_date_hour'] ) : '00';`

`$start_date_minute = (int) $data['start_date_minute'] >= 0 && (int) $data['start_date_minute'] <= 59 ? sanitize_text_field( $data['start_date_minute'] ) : '00';`

This can be fixed by adding a `null` check at the start, which resolves this issue and allows 00 to be an accepted value.

### Actual behavior
Results in the following error:

_Exception: DateTime::__construct(): Failed to parse time string (2020-11-30 ::00) at position 11 (:)_

### Steps to reproduce the behavior
1) Add a discount code and do not set the hour/minute fields, but set a date.
2) Try adding the discount.
3) It will fail with the error above.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): 3.0

WordPress Version: latest

**Comment by ashleyfae** [comment]
The following PHP notices are also thrown:

```
PHP Notice:  Undefined index: start_date_hour in /wp-content/plugins/easy-digital-downloads/includes/admin/discounts/discount-actions.php on line 83

Notice:  Undefined index: start_date_hour in /wp-content/plugins/easy-digital-downloads/includes/admin/discounts/discount-actions.php on line 84
```
