### ISSUE TITLE
3.0 - Refund total incorrect when negative fees applied on full order

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#8208]
### Expected behavior
When I process a refund, I expect the total to reflect the actual amount paid by the customer at the time of sale. When negative fees are applied to an order, the total is lower, however, when you submit a refund in the admin panel (on a single item order in this instance) it refunds the full amount (minus the fees) resulting in the refund order total being higher than that of the original transaction. This creates a mismatch from an accounting perspective since we are technically refunding money we did not receive.

### Actual behavior

See screenshots for reference:

<img width="1257" alt="Screenshot 2020-11-16 at 00 43 00" src="https://user-images.githubusercontent.com/22668877/99197630-c2211580-27a4-11eb-94b7-a8621401e9fa.png">

When issuing a refund:

<img width="1105" alt="Screenshot 2020-11-16 at 00 43 13" src="https://user-images.githubusercontent.com/22668877/99197635-c77e6000-27a4-11eb-9076-bb06bf329b7a.png">

### Steps to reproduce the behavior
1) Add a 50% off negative fee. I can provide code if needed. I was also applying 20% tax (exclusively).
2) Purchase an item worth £44 in this instance. The totals all appear correct.
3) Try refunding in the admin panel and you will see incorrect amounts.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): 3.0-beta

WordPress Version:

Any other relevant information:

**Comment by davidsherlock** [comment]
Here is the refunded order for reference:

<img width="1264" alt="Screenshot 2020-11-16 at 00 48 11" src="https://user-images.githubusercontent.com/22668877/99197756-758a0a00-27a5-11eb-8672-44e3f989fd0f.png">

**Comment by ashleyfae** [comment]
@davidsherlock We have an issue for fees/refunds already here: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/8203 Thanks though! We appreciate your testing/reports.
