### ISSUE TITLE
3.0 - Chosen item hover colour is white text on white background

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#8229]
### Expected behavior

I expect items in a Chosen dropdown to still be visible when I hover over them.

### Actual behavior

When I hover over an item in a Chosen dropdown, the text becomes white. It's a white background, so it essentially becomes invisible.

### Steps to reproduce the behavior
1) Go to any page containing a Chosen dropdown. Example: Downloads > Reports > Export. Any country or downloads dropdown.
2) Click on the dropdown to open it.
3) Hover over an item in the dropdown.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0

WordPress Version:

Any other relevant information:

**Comment by robincornett** [comment]
Note: this happens with the default (fresh) admin color scheme, which is not defined in the webpack mixin we are using.
