### ISSUE TITLE
3.0 – Unable to search discount codes (or names)

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#8230]
### Expected behavior
When viewing the discount codes table I expect to be able to search the discounts by either name or code. However, neither of these return any results.

### Actual behavior
No results are returned for any search terms.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): 3.0-beta

WordPress Version: Latest

Any other relevant information:

**Comment by ashleyfae** [comment]
@davidsherlock Can you test this again in the latest `release/3.0` branch? I'm unable to reproduce this behaviour.

If you still have the issue, then can you please reply with:

1. Your exact search term.
2. Screenshot of the settings on the discount that _should_ be appearing in results but isn't.

**Comment by robincornett** [comment]
@ashleyfae I'm getting a database error when doing any search. Here's the error when searching for a specific code (copied from the list table):

>[14-Dec-2020 14:04:48 UTC] WordPress database error Incorrect DATETIME value: '%PASTDUE15%' for query SELECT  edd_a.id FROM mce_edd_adjustments edd_a WHERE edd_a.type = 'discount' AND (parent LIKE '%PASTDUE15%' OR name LIKE '%PASTDUE15%' OR code LIKE '%PASTDUE15%' OR status LIKE '%PASTDUE15%' OR amount LIKE '%PASTDUE15%' OR description LIKE '%PASTDUE15%' OR start_date LIKE '%PASTDUE15%' OR end_date LIKE '%PASTDUE15%' OR date_created LIKE '%PASTDUE15%' OR date_modified LIKE '%PASTDUE15%') ORDER BY edd_a.id DESC LIMIT 30 made by require_once('wp-admin/admin.php'), do_action('download_page_edd-discounts'), WP_Hook->do_action, WP_Hook->apply_filters, edd_discounts_page, edd_adjustments_page, do_action('edd_adjustments_page_discount'), WP_Hook->do_action, WP_Hook->apply_filters, edd_discounts_page_content, EDD_Discount_Codes_Table->prepare_items, EDD_Discount_Codes_Table->get_data, edd_get_discounts, EDD\Compat\Discount_Query->query, EDD\Database\Query->query, EDD\Database\Query->get_items, EDD\Database\Query->get_item_ids

**Comment by ashleyfae** [comment]
@robincornett Maybe it's MySQL version specific. I think you're on a newer version than I am.

Anyway, related: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/8266 Removing the date columns from the search query will probably fix this.
