### ISSUE TITLE
Profile editor form password field labels have incorrect for attribute

### ISSUE THREAD

**Issue by amberhinds** [easydigitaldownloads/easy-digital-downloads#8232]
### Expected behavior
The password fields on the update user profile form will have associated labels.

### Actual behavior
The labels for the New Password and Re-enter Password fields have incorrect field for attributes and thus the fields do not have labels associated with them. This is a significant accessibility error that will stop blind/visually impaired users from being able to update their passwords.

### Steps to reproduce the behavior
1. View the form output by the [edd_profile_editor] shortcode
2. Inspect the fields and labels in edd_profile_password_fieldset

### Information (if a specific version is affected):
PHP Version:  N/A

EDD Version (or branch): 2.9.26 

WordPress Version: N/A

Any other relevant information:
Incorrect label 1:
```
<label for="edd_user_pass">New Password</label>
<input name="edd_new_user_pass1" id="edd_new_user_pass1" class="password edd-input" type="password">
```		
Fix 1: 
```
<label for="edd_new_user_pass1">New Password</label>
```
		
Incorrect label 2:
```
<label for="edd_user_pass">Re-enter Password</label>
<input name="edd_new_user_pass2" id="edd_new_user_pass2" class="password edd-input" type="password">
```
Fix 2:
```
<label for="edd_new_user_pass2">Re-enter Password</label>
```

**Comment by ashleyfae** [comment]
Thanks for the report @amberhinds !

**Comment by amberhinds** [comment]
@ashleyfae and @robincornett thanks for the fix!
