### ISSUE TITLE
Upload field does not display the full text on admin download page

### ISSUE THREAD

**Issue by napoleaowingert** [easydigitaldownloads/easy-digital-downloads#8244]
### Expected behavior
When I fill in the File URL field on admin download page (Download Files metabox) and the text cannot be seen in full (as it is very large), I hope that it will be possible to view all the text if I move my cursor to the end of the field.

### Actual behavior
But, when I do that, the end of the text is not being displayed because the field has no enough padding; and there is an anchor element over it.

### Steps to reproduce the behavior
1) On WP admin, visit Downloads > Add New or visit the Downloads page and open any download;
2) then go to the Download Files metabox and fill in the File URL field so that is not possible to display the full text;
3) now try to view all the text by moving your cursor to the end of the field;
4) you can't because there is no padding enough for the field... and there is the Upload a file link over the field.

### Information (if a specific version is affected):
PHP Version: 7.4.9

EDD Version (or branch): master

WordPress Version: 5.5.3

Any other relevant information:
It seems that this issue was reported before here https://github.com/easydigitaldownloads/easy-digital-downloads/pull/2075 and it was fixed. But now it is not working anymore. I think that WordPress has changed some CSS and now even with that fix, the WordPress CSS takes precedence over this fix. I suspect that the commits https://github.com/WordPress/WordPress/commit/6566808e8a1f9a63fdd7f3b11626373def3b3a12 and https://github.com/WordPress/WordPress/commit/165ac34260431329779f6899175e16fc04e8c9b3 are responsible for that behavior.

So I think the CSS selector in EDD needs to be changed like this:
from: .edd_upload_field
to: input[type="text"].edd_upload_field

Then it will work just fine.

**Comment by littlepackage** [comment]
I have also struggled with this. A lot. Thanks for reporting @napoleaowingert !
