### ISSUE TITLE
3.0/BerlinDB: Incorrect visibility on Query methods

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#8247]
### Expected behavior
When I filter orders in the WP admin (in this instance, by country/region), I expect it to work.

### Actual behavior
When I attempt this filter, I hit two different errors. The first is a PHP fatal error due to the `get_primary_column_name` method being `private` ([ref](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/database/engine/class-query.php#L743)).

If I change that to `protected`, the crash is less spectacular, but the filter still fails, because of the visibility on the `get_table_name` method ([ref](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/database/engine/class-query.php#L721)). Changing that to `protected` allows the filter to complete.

### Steps to reproduce the behavior
1) Check out `release/3.0`.
2) Go to Downloads > Orders.
3) Click the More button and filter the orders by country/region (this is what I did, but I think actually using any filter has the same issues).

### Information (if a specific version is affected):
PHP Version: 7.4.1
EDD Version (or branch): `release/3.0`
WordPress Version: 5.5.3

Any other relevant information:
I saw several methods in that class marked as `private` and it may be worth reviewing all of them to see if that is too restrictive.

**Comment by ashleyfae** [comment]
https://github.com/easydigitaldownloads/easy-digital-downloads/pull/8136 caused these changes. We'd changed them to `protected` and that PR switched them back to `private`.

**Comment by robincornett** [comment]
@ashleyfae so should all of the visibility changes be reverted? Or just the problematic ones as we find them? I'm going through the list and seeing that a lot were changed.

**Comment by ashleyfae** [comment]
We could either revert all of them, which would be faster. Or we look at the changed ones, see if they're being _used_ outside of BerlinDB core, and if so, only then update them. That would be slower, but would ensure we're only changing what we need to be.

I'm fine with either one. :shrug: One would think that if it was changed, there was a need for it at some point, so reverting all of them is probably fine.
