### ISSUE TITLE
3.0 - "More" filter options modal stays open when orders are filtered

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#8248]
### Expected behavior
When I use the "More" button to expose more filters for the Orders table, and apply them, I expect to be able to see the results.

### Actual behavior
The modal stays open even after the screen reloads, so the first four results are obscured.

### Steps to reproduce the behavior
1) Visit Downloads > Orders.
2) Use the "More" button to apply a filter to the results (note: you will have to change the visibility on some methods as described in #8247 to get it to work at the moment).
3) Click the "Filter" button.
4) The filtered results are displayed, but the modal is open. You can close it by clicking the "More" button.

### Information (if a specific version is affected):
PHP Version: 7.4.1
EDD Version (or branch): `release/3.0`
WordPress Version: 5.5.3

**Comment by ashleyfae** [comment]
What I'm about to say isn't really a must for 3.0 so maybe I'll create another issue later... but I also find it irksome that clicking outside the filter box doesn't close it. You have to re-click the button.

**Comment by robincornett** [comment]
Noting that the other place this filter button is potentially used is in the logs list table (Downloads > Tools > Logs), and it is not set to remain open when the filters are active.

I'm wondering about one of two options:
1. Just don't do the `$maybe_show_filters` [variable setup/use](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/payments/class-payments-table.php#L142-L147).
2. Rework the modal so that it's not a box overlaying the payment table, but more along the lines with the [original suggested screenshots](https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6086), so that the applied filters do show whenever they're active.

Personally, I think I would prefer 2, and maybe with the option to hide the "More" button altogether if advanced filters are active, as they do show what filters are applied. Then that removes the annoyance with not being able to close it. Thoughts @ashleyfae?

**Comment by ashleyfae** [comment]
For 3.0 lets go for the quick option -- 1. It's not a perfect solution but it's the quicker one.

You're welcome to open another issue for option 2 for us to look at sometime after 3.0, with the justification being that it's not currently clear when extra filters that are hidden are in use.
