### ISSUE TITLE
API - Extra output possible in API requests

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#8250]
### Expected behavior
When I query an API endpoint, I want just the data to be returned.

### Actual behavior
When I query an API endpoint and have a plugin such as Query Monitor active, there is extra output at the end of the data, which appears to be the QM stylesheet and a QM div.

### Steps to reproduce the behavior
1) Activate Query Monitor.
2) Query an EDD API endpoint (eg `http://example.com/edd-api/products/`)

### Information (if a specific version is affected):
PHP Version: 7.4.1
EDD Version (or branch): 2.9.x, release/3.0
WordPress Version: 5.5.3

Any other relevant information:
We dealt with a similar issue with exporting CSV files in EDD3 (#7883), where `edd_die()` needed to be replaced with `die()`.

**Comment by cklosowski** [comment]
This is causing the Unit tests to exit prematurely. I noticed this in #8908, I'm going to fix it in there.
