### ISSUE TITLE
Remove unneeded Colorbox script/style

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#8263]
### Explain your enhancement (please be detailed)
We enqueue an outdated version of the Colorbox script and style, but we do not use it. @dgoldak has a support conversation about this causing a conflict with another plugin, so I'd like to suggest that we remove it.

### Justification or use case
This has already been done in EDD 3.0:

>It doesn't appear that Colorbox is used at all, even used for email templates. The `edd_email_template_preview()` function shows that clicking the "Preview Purchase Receipt" button opens in a new `_blank` browser tab, and I'm unable to find any matching `#email-preview-wrap` element IDs in our markup any longer.
>
>Working on just removing all traces of Colorbox entirely in a PR.
>
>_Originally posted by @JJJ in https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6873#issuecomment-427137176_

But it would be nice to go ahead and get it done in 2.10 as well, to remove the conflict.

**Comment by ashleyfae** [comment]
> But it would be nice to go ahead and get it done in 2.10 as well, to remove the conflict.

I'm fine with that.
