### ISSUE TITLE
3.0 - "More" button appears on logs page, but there are no "more" filters

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#8273]
## Bug Report

![Screenshot from 2020-12-15 12-57-39](https://user-images.githubusercontent.com/6324272/102217890-208d0100-3ed5-11eb-92e3-7930ad622ec4.png)

### Steps to reproduce the behavior
1) Go to Downloads > Tools > Logs.
2) Click the "More" button.
3) It will appear, but be empty.

I suspect this is just a copy paste error from the payments list table. We should remove it.

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/reporting/class-base-logs-list-table.php#L460-L472

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0

WordPress Version:

Any other relevant information:

**Comment by robincornett** [comment]
There is a [check for the `edd_payment_advanced_filters_after_fields` action hook](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/reporting/class-base-logs-list-table.php#L460), but no corresponding `do_action` for it. But it seems a little confusing for that to be the hook name. Software Licensing does use that hook for the Orders table.

**Comment by ashleyfae** [comment]
Yeah that's why I think it's a copy paste error from the orders table. It makes sense there, but not in logs.

**Comment by LisaCee** [comment]
PR #8276
