### ISSUE TITLE
3.0 – Display order item count, names and prices within the orders table

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#8280]
### Explain your enhancement (please be detailed)

Borrowing (stealing...) this idea from Shopify, but being able to see what products were purchased without actually going into the order by hovering is really useful for quickly identifying orders. I propose we add a "Products" (or Items) column and display the data something like this:

<img width="1264" alt="Screenshot 2020-12-20 at 00 53 01" src="https://user-images.githubusercontent.com/22668877/102700391-fd0fe080-425d-11eb-88c2-82f0747ac88f.png">

I can push a PR for this, once I clean up and improve the code and layout. We could limit this to only showing a max of 5 products and you could click to view more (or something similar).

### Justification or use case

Easier account management and quicker overview support.

**Comment by ashleyfae** [comment]
I'm open to this, but I'd rather implement this in a way that means one extra query rather than 20 (or however items per page).

**Comment by ashleyfae** [comment]
Closing in favour of https://github.com/easydigitaldownloads/easy-digital-downloads/issues/8126
