### ISSUE TITLE
Undefined property: EDD_Payment::$post_date

### ISSUE THREAD

**Issue by webzunft** [easydigitaldownloads/easy-digital-downloads#8288]
This issue is currently filling our `debug.log`:

```
Undefined property: EDD_Payment::$post_date in /wp-content/plugins/easy-digital-downloads/includes/payments/class-edd-payment.php on line 362
```

I cannot say how to reproduce it.

EDD Version (or branch): 2.9.26, though I cannot say when it started
WordPress Version: 5.6

**Comment by ashleyfae** [comment]
Are you using any add-ons? It's likely coming from there.

**Comment by webzunft** [comment]
Thanks, @ashleyfae. Yes, we use a bunch of your add-ons. As I said, I don’t know which one is actually causing this, but if you know how to narrow it down, technically, then please let me know.

**Comment by ashleyfae** [comment]
@webzunft Feel free to get in touch with our support team here: https://easydigitaldownloads.com/support/ That way we can get a copy of the add-ons you have installed and help you troubleshoot.

**Comment by webzunft** [comment]
Sent, including site info and the full error stack
