### ISSUE TITLE
[download_checkout] page is not rendered correctly on localhost

### ISSUE THREAD

**Issue by tonysamperi** [easydigitaldownloads/easy-digital-downloads#8291]
## Bug Report

In localhost I can't load correctly the [download_checkout] shortcode.
Apparently `edd_enforced_ssl_asset_filter` forces https when using localhost (because not in the list of domains)

![image](https://user-images.githubusercontent.com/5957244/103577614-71d95080-4ed5-11eb-8258-2f13c51ecb74.png)

### Expected behavior
Localhost should be handled keeping the same protocol.

### Actual behavior
All the assets are loaded through https, which causes the page to break, because I don't have https on my local dev server.

### Steps to reproduce the behavior
1) Run wordpress locally
2) open the [download_checkout] page

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): 2.9.26

WordPress Version: 5.6

**Comment by tonysamperi** [comment]
I would fix it this way...
I'm not creating a pull because I see you have 72 pending pull requests...

![image](https://user-images.githubusercontent.com/5957244/103578042-2e331680-4ed6-11eb-9e1a-0d760dbcdb48.png)

**Comment by ashleyfae** [comment]
@tonysamperi Can you check if you have `Enforce SSL on Checkout` enabled in Downloads > Settings > Misc > Checkout?

**Comment by tonysamperi** [comment]
Yes, it was on. I figured out yesterday! I was about to close this issue. Thanks and sorry for the inconvenience!
