### ISSUE TITLE
3.0 - Add minimum PHP version to plugin header

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#8301]
### Explain your enhancement (please be detailed)
We should add our minimum PHP version to the main plugin header.

### Justification or use case
It will prevent users who do not have the minimum PHP version from being able to update their copy of the plugin to a version which may break their site (unless they update manually).

We just need to add this to the plugin header information:

```php
Requires PHP: 5.6
```

This is in addition to, but separate from, #6514 and #6715. Adding as an issue after meeting with @cklosowski.

**Comment by LisaCee** [comment]
PR #8302
