### ISSUE TITLE
3.0 - "inherit" order item status not properly implemented

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#8313]
## Bug Report

The default `edd_order_item` `status` is `inherit` https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/database/schemas/class-order-items.php#L109 However, this doesn't really feel like it's been properly implemented as a status.

To see one example:

1. Activate the Free Downloads add-on and set up a free download.
2. Download the free product.
3. This will have created a new order record, but the order item status is `inherit`. (Check in DB)
4. Go to your order history on the front-end and click through to "View Details and Downloads". The download links will not be available. That's due to this conditional being used in the receipt template:

```php
'complete' === $item->status
```

In this case, `$item->status` is `inherit` and not `complete`.

Other examples of `inherit` not being considered are with reporting. `EDD\Stats::get_order_item_earnings()` for example.. It only checks if the order item status is `complete`.

I'd actually never seen `inherit` in my database table until I ran this Free Downloads test. I don't think it is possible for it to appear in core at all. Therefore, for simplicity, I suggest we simply change the default to `pending`.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0

WordPress Version:

Any other relevant information:

**Comment by ashleyfae** [comment]
I actually just ran the test again and it didn't happen. The status was `complete`. So now I don't know what's up. :P

**Comment by robincornett** [comment]
I'm unable to replicate this happening with Free Downloads--with verification enabled, the status is `pending`; once I click the emailed link, it's `complete`.

**Comment by ashleyfae** [comment]
I haven't had it happen again either. :thinking: Wonder if it was some kind of weird race condition or something.

In any case, I still think there's merit to changing the default to `pending`.
