### ISSUE TITLE
3.0 - Review/update doc blocks for correct database column parameters

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#8315]
### Expected behavior
I expect the doc blocks to be correct.

### Actual behavior
Reviewing an issue for All Access, I referred to the [doc block for the file download logs](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/database/queries/class-log-file-download.php#L116-L118) and mistakenly recommended using the `payment_id__in` parameter for a query. It should be `order_id__in` (same for other columns).

### Steps to reproduce the behavior
n/a

### Information (if a specific version is affected):
PHP Version: 7.4.1
EDD Version (or branch): release/3.0
WordPress Version: 5.6

Any other relevant information:
It would be a good idea to check all of the log doc blocks, at least, while updating this, I think.

**Comment by ashleyfae** [comment]
Related-ish:

The docs for `edd_get_file_download_logs()` has an invalid `@return` type. It references a class that doesn't exist.

So does `\EDD\Database\Queries\Log_File_download::$item_shape` actually. They both reference `\EDD\Logs\File_Download_Log`, but the correct class name is `\EDD\Logs\File_Download_Log\File_Download_Log`
