### ISSUE TITLE
3.0 - URL payment parameter to filter logs do not work

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#8321]
### Expected behavior
If I click the "File Download Log for Order" link on an order details screen, I expect to see the download logs for that particular order.

### Actual behavior
I just see all of the file download logs, not filtered by order.

### Steps to reproduce the behavior
1. Visit the details screen for an order.
2. Click Logs.
3. Click the file download log link and see all logs.

### Information (if a specific version is affected):
PHP Version: 7.4.1
EDD Version (or branch): release/3.0
WordPress Version: 5.6

Any other relevant information:
I think it's possible the issue may just be in this [line](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/reporting/class-base-logs-list-table.php#L339), assigning the payment ID to `payment_id` as the parameter, and it should be `order_id` instead now. Changing it seems to work.

Note: this is also affecting the behavior of All Access, [per this PR](https://github.com/easydigitaldownloads/edd-all-access/pull/397), and possibly other extensions.

**Comment by LisaCee** [comment]
PR #8331
