### ISSUE TITLE
3.0 - Discounts - incorrectly able to select variable price option for download requirements/exclusions

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#8322]
### Expected behavior
When I set excluded or required downloads with specific price options on a discount, I expect the price options to be saved correctly.

### Actual behavior

The price options are not honoured and revert to "all options" in all instances. This means specific price options cannot be included (or excluded) from the cart discounts.

### Steps to reproduce the behavior
1) Add a discount and add a variable price "option" to the excluded (or required) to downloads.
2) Save the discount.
3) When you reload the page, you will it reverts to "All Options" for that price option.

### Information (if a specific version is affected):
PHP Version: 7.4

EDD Version (or branch): 3.0-beta

WordPress Version: 5.6

**Comment by ashleyfae** [comment]
Copying over some notes from the PR:

https://github.com/easydigitaldownloads/easy-digital-downloads/pull/8323#issuecomment-768192235

We think variations being available in the dropdown was actually unintentionally added as part of this PR: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7551 It wasn't a planned feature. So the current decision is to remove variations completely and we can revisit at another time (maybe in 3.1) if that is a feature we actually want to add.
