### ISSUE TITLE
$args['selected'] may not be an array for a multiselect dropdown

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#8332]
### Expected behavior
I expect to not have PHP errors when viewing an admin screen.

### Actual behavior
When I'm in the admin and viewing an All Access pass in which the categories are not restricted, the value passed to the HTML `select` method for `$args['selected'] is `all` (a string, not an array), and so the `in_array` check causes an error/warning. This is also present on the edit screen for the related download.

### Steps to reproduce the behavior
1. Create an AA pass which is not restricted to a specific category.
2. Generate an order for that pass.
3. Visit the individual pass screen in the admin.

### Information (if a specific version is affected):
PHP Version: 7.4.1
EDD Version (or branch): release/3.0
WordPress Version: 5.6

Any other relevant information:
I think hypothetically we could just make sure that `$args['selected']` is an array before we use it as one, or we can just cast it to an array in that line?

**Comment by ashleyfae** [comment]
Reproduced in EDD 2.9 as well.

The main issue should be fixed in All Access, but we can definitely account for it in the EDD core code too.
