### ISSUE TITLE
3.0 - EDD_Logging backwards compatibility not working on "post_parent" argument + file download logs

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#8333]
### Expected behavior

I expect to be able to use the `post_parent` argument when querying file download logs. EDD should be handling that backwards compatibility and rerouting accordingly.

### Actual behavior

EDD is rerouting it to `object_id`. That is valid for the `wp_edd_logs` table, but wp_edd_logs_file_downloads` uses `product_id` for the same purposes.

If the log type is set to `file_download` then we need to reroute `post_parent` to `product_id`

### Steps to reproduce the behavior
1) Execute a custom query using `EDD_Logging::get_connected_logs()`. Set `log_type` to `file_download` and `post_parent` to a download ID.
2) Notice that results include logs for **all** downloads and not the one you specified.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0

WordPress Version:

Any other relevant information:

**Comment by ashleyfae** [comment]
@LisaCee We'll want to turn this line: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/class-edd-logging.php#L527 into an if statement.

If `$r['log_type']` is not empty and is `file_download`, then we want to set `post_parent` to `product_id`.
Otherwise, use the existing code (setting it to `object_id`)

**Comment by LisaCee** [comment]
PR #8344
