### ISSUE TITLE
3.0 – Download category rows are hidden after quick editing

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#8357]
### Expected behavior
I expect the download category/tag functionality to remain the same as core.

### Actual behavior
When going in to make a "Quick Edit" to a category (or tag) within EDD 3.0, I can edit the fields but if I cancel (or update) the row is hidden. Meaning I need to refresh to show the field again.

### Steps to reproduce the behavior
1) Quick edit any category.
2) Don't make any changes then "cancel" it
3) The row is now hidden.

### Information (if a specific version is affected):
PHP Version: 8.0

EDD Version (or branch): 3.0 (latest)

WordPress Version: 5.6.1

**Comment by robincornett** [comment]
I've replicated this and done some digging. Oddly, it appears to not be something in our JS, but in using the [`inline-edit-post` script as a dependency here](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/scripts.php#L311). Removing that does not seem to affect quick edit functionality, and does resolve the issue for me locally. I can't tell, though, if removing it does break something.
