### ISSUE TITLE
3.0 - Admin menu "secondary separators" are a little off in 5.7

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#8360]
### Expected behavior
When I hover over the admin menu for Downloads, and then hover over the submenu items, I expect it to look "right".

### Actual behavior
In WordPress 5.7, it looks like Core is adding a `box-shadow` to basically create a border on the left side of the menu item being hovered. We have some menu items which have an `:after` element styled to give them a little more room, and the `box-shadow` is looking a little wonky with that:

![image](https://user-images.githubusercontent.com/4853066/106941823-64400200-66f1-11eb-84a9-6352adf2526d.png)

### Steps to reproduce the behavior
1. Set up a site running 5.7 (trunk/beta1) and release/3.0
2. From the dashboard, use your mouse to hover over Downloads, then Reports.

### Information (if a specific version is affected):
PHP Version: 7.4.1
EDD Version (or branch): release/3.0
WordPress Version: 5.7-beta1

Any other relevant information:
[Here's where our CSS to add the extra padding is done.](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/assets/css/admin/menu.scss#L13-L33)

**Comment by JJJ** [comment]
Fixed in Sugar Calendar: https://github.com/sugarcalendar/core/issues/171
