### ISSUE TITLE
3.0 – PHP 8.0 displays currency symbol in admin screens as "-$"

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#8365]
### Expected behavior
I expect the currency symbol to display without it prefixed with a "-".

### Actual behavior
It appears as "-$" on a default install with PHP 8.0. This does not occur on PHP 7.4.

No settings have been changed, just a base install.

### Information (if a specific version is affected):
PHP Version: 8.0

EDD Version (or branch): 3.0-beta (latest)

WordPress Version: 5.6.1

**Comment by ashleyfae** [comment]
@davidsherlock Can you please show a screenshot? And clarify which screen you're seeing this on? Maybe also share your currency settings?

I'm unable to reproduce this:

![Screenshot from 2021-02-08 12-19-14](https://user-images.githubusercontent.com/6324272/107218740-f143cd80-6a07-11eb-8b9b-e9ac1def789a.png)
![Screenshot from 2021-02-08 12-19-30](https://user-images.githubusercontent.com/6324272/107218742-f1dc6400-6a07-11eb-963c-58d2b2e8c1c2.png)

**Comment by davidsherlock** [comment]
@ashleyfae, apologies I should have stated where. It's on the new/edit Download screen on the price box.

**Comment by ashleyfae** [comment]
@davidsherlock I see it now - thank you!

**Comment by ashleyfae** [comment]
Just noting that this is also an issue in EDD 2.x.
