### ISSUE TITLE
PHP warning: No such file or directory when exporting a CSV

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#8369]
### Expected behavior
When I export a CSV, I expect to not have errors.

### Actual behavior
I believe this is specific to PHP 8, but when I export a CSV, I get this:

>component: "Core"
file: "/easy-digital-downloads/includes/admin/reporting/export/class-batch-export.php"
key: "1b8b8a86ff3fb3760035ecdc7cfd3513"
line: 145
message: "unlink(/wp-content/uploads/sites/3/edd-customers.csv): No such file or directory"
stack: (4) ["unlink()", "EDD_Batch_Export->process_step()", "edd_do_ajax_export()", "do_action('wp_ajax_edd_do_ajax_export')"]
type: "warning"

### Steps to reproduce the behavior
1. Use PHP 8.
2. Export a CSV.

### Information (if a specific version is affected):
PHP Version: 8
EDD Version (or branch): 2.10, release/3.0
WordPress Version: 5.6, 5.7-beta1

Any other relevant information:
If I switch to PHP 7.4.1, the warning does not occur. The CSV downloads either way.

**Comment by ashleyfae** [comment]
```php
@unlink( $this->file );
```

The `@` is to suppress errors. In PHP 8 that no longer works. We just need to check if the file exists before trying to delete it.
