### ISSUE TITLE
EDD_DB_Customers::update_customer_email_on_user_update() can cause memory issues when bulk running get_password_reset_key()

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#8370]
## Bug Report

Running this on a site with only 60 users causes memory issues:

```php
$users = get_users();

foreach( $users as $user ) {
	$key = get_password_reset_key( $user );
}
```

`get_password_reset_key()` eventually updates the user in question to set the new reset key. That update triggers `EDD_DB_Customers::update_customer_email_on_user_update()` which can very quickly lead to memory problems.

Customer issue here: https://secure.helpscout.net/conversation/1416421601/176850?folderId=3554290

In their use case, they are importing users into WordPress using a plugin, which uses `get_password_reset_key()` to send imported users a reset key. After only 5-7 users they run into memory problems and the process stops working. I was able to reproduce by just running the above snippet on a test site.

### Steps to reproduce the behavior
1) Run the provided code above.
2) Check your error logs. You'll likely run out of memory.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): 2.9

WordPress Version:

Any other relevant information:

**Comment by mihaijoldis** [comment]
@ashleyfae provided fix to the custome and from first attempt he reports the issue is fixed.
