### ISSUE TITLE
3.0 - Order/payment meta compatibility

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#8373]
### Expected behavior
In EDD 3.0, I expect to be able to use this code and have it work the same way it does in 2.x:

```php
edd_update_payment_meta( $payment_id, 'your_meta_key_here', 'your meta value' );
```

### Actual behavior
If the `your_meta_key_here` begins with `_edd_payment_`, that's removed from the meta key and saved to the database.

In updating extensions, I've been getting around it by checking if the new `edd_update_order_meta` function exists and using that, but my understanding is that the payment meta function should be backwards compatible, and that I should be able to use the two interchangeably.

### Steps to reproduce the behavior
I've run into this with a couple different extensions, most recently with Cross-Sell/Upsell (Simple Shipping was another). If you have an order with a `_edd_payment_upsell_total` meta key, then you can retrieve it with either of these functions:

```php
$order_id = 5;
var_dump( edd_get_payment_meta( $order_id, '_edd_payment_upsell_total', true ) );
var_dump( edd_get_order_meta( $order_id, '_edd_payment_upsell_total', true ) );
```

Now, run this code to change that meta value to `45` from whatever it was:

```php
$order_id = 5;
edd_update_payment_meta( $order_id, '_edd_payment_upsell_total', 45 );
// These will still show the original value.
var_dump( edd_get_payment_meta( $order_id, '_edd_payment_upsell_total', true ) );
var_dump( edd_get_order_meta( $order_id, '_edd_payment_upsell_total', true ) );
```

The meta value has not been updated in the database, but a new row has been added with the `meta_key` set to `upsell_total`.

### Information (if a specific version is affected):
PHP Version: 7.4.1
EDD Version (or branch): release/3.0
WordPress Version: 5.6.1/5.7-beta1

Any other relevant information:
I don't know if this needs to be resolved in the update or get functions--my inclination is in the update, so that the extension's meta key is not changed in 3.0.

**Comment by ashleyfae** [comment]
This doesn't feel right: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/payments/class-edd-payment.php#L2602

We should double check that's the only place we do something like that. If so, we can just remove it.

**Comment by robincornett** [comment]
I've scanned the code base for all uses of `str_replace` and it looks like there are no other uses like this on the payment meta. Commenting out that line makes the example code work correctly (and removes the need for the function checks in the extensions).
