### ISSUE TITLE
3.0 - Permanently delete trashed order to return on the same page

### ISSUE THREAD

**Issue by mihaijoldis** [easydigitaldownloads/easy-digital-downloads#8374]
### Expected behavior
When I click the Permanently Delete link next to an oder in the trash it should return me back to the Trash section.

### Actual behavior
Instead it redirects back to the ALL section which if not being careful and thinking you are back on the Trash section you could delete real orders

### Steps to reproduce the behavior
1) Trash an order
2) In the Orders filter section click on Trash then Delete permanently a trashed order

### Information (if a specific version is affected):
PHP Version: 7+

EDD Version (or branch): 3.0

WordPress Version:

Any other relevant information:

**Comment by LisaCee** [comment]
PR #8404
