### ISSUE TITLE
3.0 - EDD_Payment - getting meta, then updating meta, can result in duplicate fees being saved

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#8412]
## Bug Report

I ran into a weird scenario while testing EDD Invoices. When viewing an invoice for an order that contained a fee, each refresh was inserting a new fee into the database. This was caused by EDD Invoices fetching payment meta (which included fee data), then immediately updating the meta again. This caused the fees to get updated too, but an error in the setup_fees() logic meant that entirely new fees were being added.

### Steps to reproduce the behavior

I _think_ this is the correct set of circumstances/steps:

1. Have an order that contains both an `order` fee and an `order_item` fee.
2. Both of the `type_key` values should be `null`.
3. View the invoice for that order.
4. New fees will be added to the database.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0

WordPress Version:

Any other relevant information:

**Comment by ashleyfae** [comment]
Related-ish:

I'm seeing order item fees sometimes having this meta saved for download ID / price ID:

```php
edd_update_order_adjustment_meta( $adjustment_id, 'price_id', absint( $fee['price_id'] ) );
```

However, I don't think that's needed? The fee is attached to an order item, which should already have the download ID / price ID info in it. :thinking:

**Comment by robincornett** [comment]
That meta may be left over from when order item fees were being saved as both order item and order adjustments.
