### ISSUE TITLE
3.0 - Incorrect order object key set in payments class

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#8421]
### Expected behavior
When `edd_update_order` is used, I expect it to set a valid object key.

### Actual behavior
In this line of code, the `user_id` is set to `$this->user_id` as the key, so updating the order with the user ID will not work.

### Steps to reproduce the behavior
Not sure--I found it searching the code for a different issue involving `edd_update_order`.

### Information (if a specific version is affected):
PHP Version: 7.4.1
EDD Version (or branch): release/3.0
WordPress Version: 5.7-beta3

**Comment by ashleyfae** [comment]
Line in question: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/payments/class-edd-payment.php#L857-L859
