### ISSUE TITLE
3.0 - Physical Addresses table warning: Attempt to read property "email" on bool in easy-digital-downloads-release-3.0/includes/admin/customers/class-customer-addresses-table.php on line 219

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#8437]
### Expected behavior
I expect to not see PHP warnings on the physical address table. 

### Actual behavior
I see the above warning as per the title.

### Information (if a specific version is affected):
PHP Version: 8.0

EDD Version (or branch): 3.0-release

WordPress Version: 5.7

**Comment by davidsherlock** [comment]
This one is interesting, the customer was actually deleted from the database but the address still remained, triggering this warning.

**Comment by ashleyfae** [comment]
@LisaCee If `$customer` is empty, then let's set `$name` to `address ID {ID number here}`

**Comment by LisaCee** [comment]
PR #8449
