### ISSUE TITLE
How to set on Paypal default to work with currency RON

### ISSUE THREAD

**Issue by leagueofsmon** [easydigitaldownloads/easy-digital-downloads#8439]
### Justification or use case
When i setup to use currency RON and i try to pay with paypal and i receive this error "Things don't appear to be working at the moment. Please try again later." but when i try currency USD everything work just fine.. i setup with STRIPE with RON and work just fine.. 
PS: RON currency is from Romania.. can you guide me how to do it to work.

**Comment by ashleyfae** [comment]
@leagueofsmon Please contact our support team here: https://easydigitaldownloads.com/support/ GitHub is for tracking bugs/features only.

Thanks!
