### ISSUE TITLE
3.0 - Amazon Payments gateway code always runs

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#8440]
### Expected behavior
If the Amazon Payments gateway is not active, I expect its code to not affect the checkout screen.

### Actual behavior
With 3.0, the Amazon Payments code all runs, and one overt change is that the EDD scripts are forced to load in the header instead of the footer. This caused an issue with Software Licensing's use of `wp_add_inline_script` for the renewal form, specifically that the renewal form script was no longer loading. I think that can be improved/fixed in Software Licensing outside of this issue, but I think there is something wrong in 3.0.

### Steps to reproduce the behavior
1. Activate Software Licensing 3.7.0 and `release/3.0`.
2. Visit the checkout screen. The renewal form is fully open/displayed and the script for it is not loaded at all.

### Information (if a specific version is affected):
PHP Version: 7.4.1
EDD Version (or branch): release/3.0
WordPress Version: 5.6.2

Any other relevant information:
> In 2.9/master, there are some checks on the Amazon Payments gateway class which do not exist (yet?) in EDD 3.0:
>- [conditions in 2.9](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/gateways/amazon-payments.php#L38-L50)
>- [no conditions in 3.0](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/gateways/amazon-payments.php#L38-L50)
>
>The key one is that the [`edd_load_scripts_in_footer` filter is set to return `false` for the Amazon gateway](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/gateways/amazon-payments.php#L38-L50), and this is running whether or not Amazon is active in 3.0.
>
>I don't know if that's code that still needs to get copied over from 2.x to 3.0 (some conditions were removed relating to PHP 5.3, but the blame isn't showing me when the `edd_is_gateway_active` check was removed.
>
>_Originally posted by @robincornett in https://github.com/easydigitaldownloads/EDD-Software-Licensing/issues/1771#issuecomment-788186161_

**Comment by ashleyfae** [comment]
Looking at the file history, I think it got lost when merging master into release/3.0 at some point.
