### ISSUE TITLE
3.0 - Bump minimum WordPress requirement to 4.9

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#8443]
In our blog posts, discussions, and unit tests, we mention the minimum as being 4.9, but in the code it's set to 4.7. So this issue is just to bring the code (readme, requirements class) up to date with what we say the requirements are.

**Comment by robincornett** [comment]
@ashleyfae 3.0 still includes some specific checks for WP 4.7:
- https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/easy-digital-downloads.php#L473-L485
- https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/cart/template.php#L147
- https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/cart/template.php#L157
4.8:
- https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/misc-functions.php#L1246-L1253
- https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/misc-functions.php#L1271-L1278
4.6:
- https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/misc-functions.php#L1271-L1278
- https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/misc-functions.php#L1271-L1278
- There are actually multiple instances of this condition in that file but only those two have the comments.

Should updating these be part of this as well?

**Comment by ashleyfae** [comment]
> Should updating these be part of this as well?

Yes. :+1:
