### ISSUE TITLE
3.0 - Correct link to usage tracking documentation

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/easy-digital-downloads#8452]
### Expected behavior
When I click on the link in our tracking subsection of the general settings, I expect it to go to a page about our usage tracking.

### Actual behavior
When I click on the link it goes to a 404 because the page is in draft and also unfinished.

### Steps to reproduce the behavior
Go to Settings - > General - > Tracking - > Usage tracking - > This is what we track
That goes to https://easydigitaldownloads.com/tracking/ but it should probably go to https://docs.easydigitaldownloads.com/article/1419-what-information-will-be-tracked-by-opting-into-usage-tracking

Any other relevant information:
To my knowledge, the /tracking/ page has never actually existed. @SDavisMedia appears to have encountered the link to nowhere when testing 3.0 and took it upon himself to draft the page. We could _redirect_ that page to our docs OR just change the link to go directly to the doc and toss /tracking/ in the trash.

**Comment by LisaCee** [comment]
PR #8456 updates link, adds numbered placeholders and notes for translators.
