### ISSUE TITLE
3.0 - Importer fails using PHP 8.0 

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#8453]
### Expected behavior
When I import payments (or downloads) I expect the importer to display the field mapping and importer to work as normal.

### Actual behavior
 It fails with a 500/AJAX server error.

I haven't had a chance to look deeply into this but the issue does not happen on PHP 7.4.

**Comment by ashleyfae** [comment]
Probably related: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/8149
