### ISSUE TITLE
PayPal Express Gateway In-Context Checkout breaks renewal form on checkout

### ISSUE THREAD

**Issue by gra-mir** [easydigitaldownloads/easy-digital-downloads#8454]
### Expected behavior
Renewal form on checkout page is collapsed by default and works in general. edd_sl_checkout_js (script function) from edd-software-licensing (addon) loads on checkout page.

### Actual behavior
The script mentioned above is added via 
`if (function_exists('wp_add_inline_script')) {
		wp_add_inline_script('edd-ajax', $script);
	} else {
		echo "<script>{$script}</script>";
	}`

When the option "Enable PayPal Express In-Context Checkout" is enabled in the gateway settings, wp_add_inline_script seems to break.

### Steps to reproduce the behavior
1) Install EDD, Software Licensing Addon, Paypal Express Addon
2) Enable "Enable PayPal Express In-Context Checkout" under Downloads->Settings->Payment Gateways->PayPal Pro/Express
3) Make sure "Allow Renewals" is enabled under Downloads->Settings->Extensions->Software licensing

**Comment by ashleyfae** [comment]
Thanks @gra-mir . We have a fix for this ready to go in the next version. Closing this as our main issue for it is in a separate repository for PayPal Express. :)
