### ISSUE TITLE
3.0 - Retrieving cart total has become a slow process due to tax rate logic

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#8455]
## Bug Report

See this issue on EDD Wallet for a real example: https://github.com/easydigitaldownloads/edd-wallet/issues/65

EDD Wallet uses `edd_get_cart_total()` a few times, and in EDD 3.0 that suddenly results in thousands of extra queries. The main cause is the `edd_get_tax_rate()` function, which is used when determining the tax applicable to the cart. This can run multiple times throughout a single page load, which results in running the same queries to the database.

**Comment by ashleyfae** [comment]
Closing this in favour of https://github.com/easydigitaldownloads/easy-digital-downloads/issues/8179

**Comment by ashleyfae** [comment]
Actually reopening this. Although they're very similar we might still have some separate fixes.

**Comment by davidsherlock** [comment]
@ashleyfae, I run some tests on this and it works well - nice work. I haven't tested this fully as of yet, but I recall on the base 3.0 branch that even when taxes were disabled some of those queries were still being hit.

**Comment by ashleyfae** [comment]
@davidsherlock Thanks for testing that out. It's been a while since I've looked at that PR. I've brought it up to date with `release/3.0`. I'll take another look at it when I get a chance.
