### ISSUE TITLE
3.0 - It is not possible to create a report with no filters

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#8468]
### Expected behavior
I expect to be able to create a report with no filters in the filter bar.

### Actual behavior
When I use the `add_report` method, even if I set the `filters` parameter to `false` or `array()`, the default date/taxes filters are still added. Encountered while working on #8095. Exports are registered as a report, but they're not a true report, so the date/taxes filters do nothing and ideally should not display.

### Steps to reproduce the behavior
1. Update the [parameters for the export report](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/reporting/reports.php#L2526-L2532) to include `filters` set to `false` or an empty array.
2. Visit Downloads > Reports > Export. The filter(s) for date/taxes show anyway.

### Information (if a specific version is affected):
PHP Version: 8
EDD Version (or branch): release/3.0
WordPress Version: 5.7

**Comment by ashleyfae** [comment]
Yes we should support no filters. :+1: I think this will require two steps:

1. Allow `filters` to be empty. Right now it actually fails to register the report if you explicitly set `filters` to something empty. That might mean changing this: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/reports/data/class-endpoint-registry.php#L179 to this:
```php
$this->validate_attributes( $attributes, $report_id, array( 'filters' ) );
```
That will skip the empty check on `filters`.
2. However, with that fix, the filters still appear. So might need another adjustment somewhere in the display logic.

**Comment by robincornett** [comment]
I am able to remove the filters changing these two lines:
- https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/reports/data/class-report-registry.php#L122 (your suggested change)
- https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/reports/data/class-report.php#L61 (set to empty array)

I actually think the endpoint one doesn't need to be changed. Reverting that and adding in my two changes, plus setting the export filters to false, gets me what I want.
