### ISSUE TITLE
3.0 - Manual Order - Able to add credit to order item when I shouldn't be

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#8476]
### Expected behavior

I expect to not be able to add credit to an individual order item, because the UI doesn't allow for it.

![Screenshot from 2021-03-16 11-42-02](https://user-images.githubusercontent.com/6324272/111303634-a4799500-864c-11eb-9623-f3e02a3e3fea.png)

### Actual behavior

If you start out on a "Fee", select an order item, then switch to "Credit", the credit gets added to that individual order item.

### Steps to reproduce the behavior
1) Manually create an order and add an item.
2) Add an adjustment. Set it up like this:
![Screenshot from 2021-03-16 11-42-26](https://user-images.githubusercontent.com/6324272/111303749-c96e0800-864c-11eb-9ce4-43e0016f21b2.png)
3) Then, before adding, switch the "Type" to "Credit". Enter an amount and save.
4) Note how the credit is added to the order item.
![Screenshot from 2021-03-16 11-43-39](https://user-images.githubusercontent.com/6324272/111303815-e1458c00-864c-11eb-8482-40bef6f11c94.png)

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0

WordPress Version:

Any other relevant information:

**Comment by spencerfinnell** [comment]
Some checking/resetting needs to happen based on the selected type here: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/assets/js/admin/orders/order-overview/views/form-add-order-adjustment.js#L143

**Comment by spencerfinnell** [comment]
PR #8662 ensures both the UI are hidden correctly and the output does not link credits to order items. Testing can be done with original reproduction steps.
