### ISSUE TITLE
3.0 - Admin Orders - Amounts are wrong when customizing thousands/decimals separators

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#8477]
### Expected behavior

When I customize the thousands/decimals separators, I expect numbers and amounts to be shown correctly.

### Actual behavior

When adding/editing an order, they are a complete mess.

In Downloads > Settings > General > Currency, I configured as follows:

Currency: Euros (this doesn't particularly matter, I don't think, but I chose the euro format for the next settings)
Thousands Separator: `.` (period/full stop)
Decimal Separator: `,` (comma)

I have a product that costs `49`. When viewing an order with that product, here's how it looks:

![Screenshot from 2021-03-16 12-35-11](https://user-images.githubusercontent.com/6324272/111309987-6da77d00-8654-11eb-9b3c-034d1f3a5f8a.png)

### Steps to reproduce the behavior
1) Configure currency settings as shown above.
2) Manually create a new order (or edit an existing one).
3) View the order in the admin and look at the amounts.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0

WordPress Version:

Any other relevant information:

**Comment by spencerfinnell** [comment]
Do we want to log the currency settings at the time of the order creation so the formatted values never change? Or always output based on the current store settings?

**Comment by robincornett** [comment]
My understanding is that orders are immutable, so items/amounts cannot be adjusted once an order is created. I believe that would be the case for currency settings as well, since currency is saved as part of the order object.

**Comment by spencerfinnell** [comment]
@robincornett The currency/amounts don't change but the formatted output will display differently if you adjust the global store settings. An order originally displaying `$50.00` could become `50,00$` in the _display_.

There probably isn't a need to track/store the exact point-in-time settings but I thought I'd bring it up in case someone thinks it might be worth it.

**Comment by robincornett** [comment]
Ah, sorry, yes, that's a different question for sure! Storing the exact point-in-time settings seems onerous, but that's just me. $.02

**Comment by ashleyfae** [comment]
This is actually relevant to some multi currency stuff I'm looking at right now. With that in mind, here are my expectations:

1. Always use the currency code linked to the order.
2. Use the global store settings for separators, etc. Presumably it should still be easy to filter those store settings to then affect what's displayed on the order.

So, in short: there's no need to _store_ that information. Just use the global settings.

**Comment by spencerfinnell** [comment]
PR #8651 will output existing orders with the chosen currency separators and symbol positioning. No specific testing instructions besides general tests to see if you can break any input or output when using customized settings in "Settings > General > Currency".
