### ISSUE TITLE
3.0 - Manual order status changes get 2 notes

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#8480]
### Expected behavior

When I change the status of an order, I expect _one_ order note to be logged.

### Actual behavior

Two are logged:

![Screenshot from 2021-03-17 12-58-05](https://user-images.githubusercontent.com/6324272/111471257-a1e86f80-8720-11eb-9ab2-8dd6611c1470.png)

This is due to us firing the `edd_update_payment_status` hook twice: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/payments/class-edd-payment.php#L1993-L2000

The status change notes are added on that hook.

I propose we update our notes logic to use our new transition hook instead: `edd_transition_order_status`.

### Steps to reproduce the behavior
1) Edit a `Complete` payment.
2) Manually change the status to something else.
3) Check the order notes.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0

WordPress Version:

Any other relevant information:

**Comment by ashleyfae** [comment]
@LisaCee Some notes for you:

1. This is the code that will need updating: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/payments/actions.php#L255-L275
2. The _internal_ function logic (this: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/payments/actions.php#L266-L273) can remain exactly the same.
3. However, I propose we deprecate this entire `edd_record_status_change()` function and build a new one. I propose this because the arguments will need to be reordered. So this function can be moved to `deprecated-functions.php`. Add this to the top of the function like we do with others: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/deprecated-functions.php#L70-L72 The third parameter is the name of the new function to use instead (see below). 
The `add_action()` line should be removed.
4. Then, in the `actions.php` file, add a new function called `edd_record_order_status_change()`. The parameters are, in order: `$old_status, $new_status, $order_id` (same as before, but in a different order and change `$payment_id` to `$order_id`).
5. We'll also need an `add_action()` call like before, but instead of `edd_update_payment_status`, we'll use `edd_transition_order_status`.

**Comment by LisaCee** [comment]
PR #8485 deprecates `edd_record_status_change()` and replaces it with `edd_record_order_status_change()`.  The new function hooks into `edd_transition_order_status`.  It also updates the test with the new function name and adds numbered parameters and a note for translators.
