### ISSUE TITLE
3.0 - Audit trailing commas

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/easy-digital-downloads#8486]
## Bug Report

We have numerous cases of trailing commas in arrays and function calls that trigger fatal errors on some versions of PHP.

For example, @dgoldak encountered this on PHP 7.2:

```
2021/03/17 21:21:09 [error] 8379#8379: *721091 FastCGI sent in stderr: "PHP message: PHP Parse error: syntax error, unexpected ')' in /var/www/edd3.danielgoldak.com/wp-content/plugins/easy-digital-downloads/includes/admin/payments/actions.php on line 267" while reading response header from upstream, c
```
A quick look around showed several instances of trailing commas being used. I found three functions on my initial review that are problematic:

- edd_trigger_destroy_order()
- edd_trigger_trash_order()
- edd_trigger_restore_order()

Example:

```php
/**
 * New in 3.0, permanently destroys an order, and all its data, and related data.
 *
 * @since 3.0
 *
 * @param array $data Arguments passed.
 */
function edd_trigger_destroy_order( $data ) {

	if ( wp_verify_nonce( $data['_wpnonce'], 'edd_payment_nonce' ) ) {

		$payment_id = absint( $data['purchase_id'] );

		if ( ! current_user_can( 'delete_shop_payments', $payment_id ) ) {
			wp_die( esc_html__( 'You do not have permission to edit this order.', 'easy-digital-downloads' ), esc_html__( 'Error', 'easy-digital-downloads' ), array( 'response' => 403 ) );
		}

		edd_destroy_order( $payment_id );

		$redirect_link = add_query_arg(
			array(
				'page'        => 'edd-payment-history',
				'edd-message' => 'payment_deleted',
				'status'      => 'trash',
			),
			edd_get_admin_base_url(),
		);
		edd_redirect( $redirect_link );
	}
}
add_action( 'edd_delete_order', 'edd_trigger_destroy_order' );
```

The trailing comma after `edd_get_admin_base_url()` results in a fatal PHP error on PHP 7.2 and less.

**Comment by ashleyfae** [comment]
I think the only problematic one is in `edd_trigger_destroy_order()`. It's trailing slashes in _function arguments_ that we have to watch out for. Trailing slashes in _arrays_ are supported.

So this is a problem:

```php
$redirect_link = add_query_arg(
	array(
		'page'        => 'edd-payment-history',
		'edd-message' => 'payment_deleted',
		'status'      => 'trash',
	),
	edd_get_admin_base_url(),
);
```

because the trailing slash is after an _argument_ for the `add_query_arg()` function.

But this is okay:

```php
$redirect = edd_get_admin_url( array(
	'page'        => 'edd-payment-history',
	'edd-message' => 'order_trashed',
	'order_type'  => esc_attr( $data['order_type'] ),
) );
```

because the trailing slash is within an array.

I ran a code inspection in PhpStorm and the only issue it detected was the one in `edd_trigger_destroy_order()`.
