### ISSUE TITLE
Use "password" input type for edd_license_key_callback()

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#8493]
### Explain your enhancement (please be detailed)

Related: https://github.com/easydigitaldownloads/EDD-Software-Licensing/issues/1434

We should use a `password` input type for license key inputs (`edd_license_key_callback()`).

### Justification or use case

Although it's not a perfect way of masking, it would make the license keys less obvious to people who shouldn't really be able to see them.

Request: https://secure.helpscout.net/conversation/1458462583/180502?folderId=3554290

**Comment by mihaijoldis** [comment]
New request for hiding licenses as the user is installing it on clients websites https://secure.helpscout.net/conversation/1649218715/195381?folderId=2048992
