### ISSUE TITLE
3.0 - Fatal Error when upgrading DB, with different date format

### ISSUE THREAD

**Issue by Julius151** [easydigitaldownloads/easy-digital-downloads#8496]
## Bug Report

Error Log output: 
PHP Fatal error:  Uncaught Exception: DateTime::__construct(): Failed to parse time string (Januar 15, 2021 09:10:49) at position 0 (J): The timezone could not be found in the database in /src/wp-content/plugins/easy-digital-downloads/includes/libraries/Carbon.php:291
Stack trace:
#0 /src/wp-content/plugins/easy-digital-downloads/includes/libraries/Carbon.php(291): DateTime->__construct('Januar 15, 2021...', Object(DateTimeZone))
#1 /src/wp-content/plugins/easy-digital-downloads/includes/utils/class-date.php(37): Carbon\Carbon->__construct('Januar 15, 2021...', Object(DateTimeZone))
#2 /src/wp-content/plugins/easy-digital-downloads/includes/class-utilities.php(237): EDD\Utils\Date->__construct('Januar 15, 2021...', Object(DateTimeZone))

### Expected behavior
Upgrading databse without any issues.

### Actual behavior
Upgrade stops at 60.37% (of Customer Notes) when the fatal error occurs, databse can not be fully upgraded due the date time format of german orders made with EDD. 

Without uphrading the database further testing and updating other plugins is not possible.

### Steps to reproduce the behavior
1) have orders with different date time formats

### Information (if a specific version is affected):
PHP Version: 7.4.2

EDD Version (or branch):  3.0-beta1  

WordPress Version: 5.7

**Comment by ashleyfae** [comment]
We can fix the fatal error, but not sure about recovering the timestamp. :(
