### ISSUE TITLE
Add Recapture promo & plugin background install

### ISSUE THREAD

**Issue by pderksen** [easydigitaldownloads/easy-digital-downloads#8497]
### Explain your enhancement (please be detailed)

In **Settings > Email > General**, we need to add copy and a "connect" button for our new Recapture partnership. It should be our 3rd option on the page, replacing Jilt.

This needs to go in the next 2.10.x release of EDD if at all possible.

Related issues that probably make sense to do at the same time:
- #8290 
- #8498

Subheading:
**Recapture**

Label:
**Abandoned cart recovery**

Text:
We recommend Recapture for recovering lost revenue by automatically sending effective, targeted emails to customers who abandon their shopping cart. [Learn more here](https://recapture.io/abandoned-carts-easy-digital-downloads) (free trial available).

**[Connect with Recapture]** <-- call-to-action button

---
- The CTA button background installs the Recapture for EDD plugin, then redirects to https://recapture.io/register. This mimics the SendWP (and soon deprecated Jilt) behavior on the same settings page.

- Once the Recapture for EDD plugin is activated, instead of a CTA button, show a “notice-success” styled message.

> Recapture for EDD plugin activated. [Access your Recapture account.](https://recapture.io/account)

This mimics the way we replace the connect button with a notice for the Stripe connection workflow.
![image](https://user-images.githubusercontent.com/79667/111818749-c6695680-889c-11eb-92ca-1e9bd54fec45.png)

- The external links (i.e. "Learn more here" and "Access your Recapture account.") should open in a new tab.

Final order on email settings page should be:
- Email Configuration
- SendWP
- Recapture

Current page layout:
![image](https://user-images.githubusercontent.com/79667/111816213-ce73c700-8899-11eb-868e-54ea6b1ec4cd.png)

**Comment by cklosowski** [comment]
Here are all the states I could find that are required:

1) Not Installed / Not Activated:
![Screenshot_2021-03-22 Easy Digital Downloads Settings ‹  DEV  EDD — WordPress(3)](https://user-images.githubusercontent.com/1390124/112051815-9d043100-8b0f-11eb-9fe4-4834a53a1bb4.png)

2) Installed and Activated, but not yet connected:
![Screenshot_2021-03-22 Easy Digital Downloads Settings ‹  DEV  EDD — WordPress(4)](https://user-images.githubusercontent.com/1390124/112051872-abeae380-8b0f-11eb-8d7d-520b36fe42ad.png)

In this instance, clicking the action link
![Screenshot_2021-03-22 Recapture ‹  DEV  EDD — WordPress](https://user-images.githubusercontent.com/1390124/112051985-cae97580-8b0f-11eb-9e21-6ad5d0fa71f3.png)
 takes you to this page in the Recapture settings:


3) Installed, Activated, and Connected:
![Screenshot_2021-03-22 Easy Digital Downloads Settings ‹  DEV  EDD — WordPress(5)](https://user-images.githubusercontent.com/1390124/112051934-bad19600-8b0f-11eb-81f5-4cdb97eb7349.png)

In this screenshot the disconnect takes you to this page (which is a Recapture page)
![Screenshot_2021-03-22 ‹  DEV  EDD — WordPress](https://user-images.githubusercontent.com/1390124/112052019-d3da4700-8b0f-11eb-9e30-e2cb479ba0f7.png)
