### ISSUE TITLE
Update SendWP promo

### ISSUE THREAD

**Issue by pderksen** [easydigitaldownloads/easy-digital-downloads#8498]
### Explain your enhancement (please be detailed)

In **Settings > Email > General**, we need to:

- Move the SendWP promo to 2nd on the list (between Email Configuration and soon Recapture).
- Update copy in subheading, label, main text and CTA button.
- Display a notice in place of button after SendWP plugin is activated.

This needs to go in the next 2.10.x release of EDD if at all possible.

Related issues that probably make sense to do at the same time:
- #8290 
- #8497

Subheading:
**SendWP** <-- remove "Settings"

Label:
**Deliverability settings**

Text:
We recommend SendWP to ensure quick and reliable delivery of all emails sent from your store, such as purchase receipts, subscription renewal reminders, password resets, and more. [Learn more here](https://sendwp.com/) (free trial available).

**[Connect with SendWP]** <-- add "with"

---
The CTA button background _already_ installs the SendWP plugin and redirects to https://sendwp.com/_/signup/register (no change).

To add: Once the SendWP plugin is activated, instead of a CTA button, show a “notice-success” styled message:

> SendWP plugin activated. [Access your SendWP account.](https://sendwp.com/account/)

- The external links (i.e. "Learn more here" and "Access your SendWP account.") should open in a new tab.

This mimics the way we replace the connect button with a notice for the Stripe connection workflow.
![image](https://user-images.githubusercontent.com/79667/111820222-7a1f1600-889e-11eb-9be2-557f5c554bbd.png)

Final order on email settings page should be:
- Email Configuration
- SendWP
- Recapture

Current page layout:
![image](https://user-images.githubusercontent.com/79667/111817268-0e877980-889b-11eb-9462-ed9172c8a9bb.png)

**Comment by cklosowski** [comment]
@pderksen Here are the changes.

![Screenshot_2021-03-22 Easy Digital Downloads Settings ‹  DEV  EDD — WordPress(2)](https://user-images.githubusercontent.com/1390124/112031022-1d1e9c80-8af8-11eb-8c1f-14571867f1ef.png)
![Screenshot_2021-03-22 Easy Digital Downloads Settings ‹  DEV  EDD — WordPress(1)](https://user-images.githubusercontent.com/1390124/112031025-1d1e9c80-8af8-11eb-950d-9fbed717fbf5.png)

**Comment by cklosowski** [comment]
I'm working on this inside of `issue/8497`
