### ISSUE TITLE
3.0 - Missing File Types from File Select

### ISSUE THREAD

**Issue by qctechjunkie** [easydigitaldownloads/easy-digital-downloads#8505]
### Expected behavior
When selecting a file to insert into an EDD download I would expect to see all files uploaded to the Media Library, that I the user uploaded.

### Actual behavior
Only image files appear to be available. I can upload a ZIP or PDF while editing an EDD download and add it to a download. But, it still will not appear in the File select screen, but will show up in the normal Media library screen.

### Steps to reproduce the behavior
1) Upload a file other than an image to the media library
2) Attempt to add/edit an EDD download and select that file
3) File will not be available via the File select screen of an EDD download post type

### Information (if a specific version is affected):
PHP Version: 7.4.12

EDD Version (or branch): 3.0 beta1

WordPress Version: 5.7

Any other relevant information:
![image](https://user-images.githubusercontent.com/43458431/112059365-c16d0700-8b29-11eb-9e21-19343fa7ddc9.png)

**Comment by spencerfinnell** [comment]
Previously/related: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/8407

@qctechjunkie Thank you for the report. This [should be fixed](https://github.com/easydigitaldownloads/easy-digital-downloads/pull/8408) in the [`release/3.0`](https://github.com/easydigitaldownloads/easy-digital-downloads/tree/release/3.0) branch, but but the change has not been included yet in a released beta.

**Comment by ashleyfae** [comment]
Closing this for now. @qctechjunkie if you still notice this issue in the latest `release/3.0`, let us know and we can re-open this.
