### ISSUE TITLE
3.0 - Consider removing deprecation notice about "Publish" status

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#8524]
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/payments/class-edd-payment.php#L1993-L2001

When a payment's status changes from `complete` to anything else, we fire this hook for backwards compatibility:

```php
do_action( 'edd_update_payment_status', $this->ID, $status, 'publish' );
```

But we also trigger this notice:

```php
_edd_generic_deprecated( 'edd_update_payment_status', '3.0', __( 'The "publish" payment status has been replaced with "complete". Please check for both when listening for status changes.', 'easy-digital-downloads' ) );
```

That fires all the time, because we have no way of only firing it _only_ if code is listening for `publish`. But IMO this is actually kind of annoying because the notice can trigger just inside normal EDD core operations, even if nothing is hooked in.

1. Edit a "Complete" Payment.
2. Change the status to anything else (like "Pending").
3. Note deprecation notice in log.

I wonder if we should just remove the notice completely and convey deprecation through the blog (which we may have already done anyway).

**Comment by robincornett** [comment]
Looking up at line 1907 in that function, there is a check for if someone is passing `publish` into the function. Could that be a place to move this, so that if an extension or code is trying to change the status to `publish` and EDD core is overriding it, the notice will be triggered?

**Comment by ashleyfae** [comment]
This code is in place for anyone who is hooked into `edd_update_payment_status` and expecting the third parameter to be `publish` instead of `complete`. Example:

```php
add_action( 'edd_update_payment_status', function( $id, $new_status, $old_status ) {
    if ( 'publish' === $old_status ) {
        // Do something
    }
}, 10, 3);
```

The person hooking in may not be the person who actually triggered the save.

So I don't think that would work.

**Comment by ashleyfae** [comment]
@LisaCee Just remove this: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/payments/class-edd-payment.php#L1996-L1998
