### ISSUE TITLE
3.0 - PHP warning for edd_get_payment_status for custom statuses

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#8526]
### Expected behavior
When I view an order in the admin, I expect to not have any PHP warnings.

### Actual behavior
When I view an order with a custom payment status which is no longer registered, I get this warning:

```
PHP Warning:  array_key_exists(): The first argument should be either a string or an integer in \easy-digital-downloads\includes\payments\functions.php on line 564
```

### Steps to reproduce the behavior
1. Activate Fraud Monitor.
2. Mark an order to be flagged for review (so that the status is `pending_review`.
3. Deactivate Fraud Monitor.
4. View the order in the admin.

### Information (if a specific version is affected):
PHP Version: 7.4.1
EDD Version (or branch): release/3.0
WordPress Version: 5.7

Any other relevant information:
[The relevant code is here](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/payments/functions.php#L563-L564) ... in this case, `$found_key` is `false`, so we can't use `array_key_exists` for that. I'm guessing we just need to add a check to line 564 against `$found_key`.

Related, but worth looking into--in this same instance, the `edd_get_payment_status_label` outputs "Pending_review" as the status where it is used, because it uses `ucwords` to capitalize the words of the status for the default value. No error is thrown, but I'm thinking we could make it look a tiny bit better by replacing the `_` in the status with a space before running `ucwords` so that the fallback status "label" would look a bit better?

**Comment by ashleyfae** [comment]
I actually can't reproduce this. :thinking: 

However, it definitely does make sense to add that extra check.
