### ISSUE TITLE
3.0 - Reports - Export Payments by date range not working. 

### ISSUE THREAD

**Issue by padraigobeirn** [easydigitaldownloads/easy-digital-downloads#8537]
### Expected behavior
When I go to EDD reports and export payments by date range I expect the csv to contain only payments within the date range. 

### Actual behavior
When I go to EDD reports and export payments by date range ALL payments/orders ever made are exported. It doesn't matter if you select the status of the orders, all are exported regardless. 

### Steps to reproduce the behavior
1) Go to Reports > Export > Payments and enter a date range to export. All orders will be exported regardless of date range or status. 

### Information (if a specific version is affected):
PHP Version: 7.4.14

EDD Version (or branch): 3.0 beta 1

WordPress Version: 4.9

Any other relevant information:

**Comment by LisaCee** [comment]
I believe this issue was resolved with PR #8471.  @robincornett

**Comment by padraigobeirn** [comment]
Thanks a million Lisa. I'm sorry I missed that PR. Looking forward to the next 3.0 beta!
