### ISSUE TITLE
3.0 - Refund hooks have changed

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#8540]
In 2.x we have refund hooks in the payments class-- for example, `edd_post_refund_payment`. It appears that these hooks do not fire during the refund process in EDD 3.0. The comparable hook in EDD 3.0 is `edd_refund_order`, and it has different parameters, so the hooks are not really compatible.

I ran into this working on issue [1315 in Recurring](https://github.com/easydigitaldownloads/edd-recurring/issues/1315) and put together a solution, but wanted to ask, since core has been recommending the use of `edd_post_refund_payment` (and also pre, I think), and it's no longer part of the process, do we need to change anything in EDD 3.0, or just communicate the new hook(s) to use instead?

It looks like these extensions (of ours) use the [post refund payment hook](https://github.com/search?q=org%3Aeasydigitaldownloads+edd_post_refund_payment&type=code):
- Recurring
- Mailchimp
- Software Licensing
- Commissions

**Comment by ashleyfae** [comment]
I think we should continue supporting the old hooks. We can deprecate them, but keep them in. They just take an `EDD_Payment` object so it isn't a big deal to continue supporting them.
