### ISSUE TITLE
2.0 - Customer getting 404 error trying to access download

### ISSUE THREAD

**Issue by songdove** [easydigitaldownloads/easy-digital-downloads#8541]
### Expected behavior
When my customer makes a purchase, I expect them to have immediate access to their download.

### Actual behavior
A customer just made a purchase and was sent to a 404 error page instead of the download.

### Steps to reproduce the behavior
1) As customer: purchase time block
2) Open email and click on download link
3) Discover page not found error

I re-uploaded the file in question to the download item being sold, then copied and pasted the link for it into my browser while still logged into my admin area, and I also got the 404 error.  I can see the file in my media area, but I am blocked from viewing it.  This blocking feature is great for anyone who didn't buy the file, but as admin and as purchaser, I and my clients should see what they buy.  The file in question is a PDF document to be used like a gift card.

### Information (if a specific version is affected):
PHP Version: 7.3.27

EDD Version (or branch): 2.10.1 (just did a round of updates and EDD was not in that list?)

WordPress Version: 5.7

Any other relevant information:

**Comment by robincornett** [comment]
Hi @songdove, our support team would be happy to help you with this issue. You can begin the support process here: https://easydigitaldownloads.com/support/
