### ISSUE TITLE
3.0 - The end_date argument of edd_get_payments function is not working

### ISSUE THREAD

**Issue by napoleaowingert** [easydigitaldownloads/easy-digital-downloads#8542]
### Expected behavior
When I send "start_date" and "end_date" arguments to the "edd_get_payments" function, I expect that the retrieved records have their respective date between these two input dates.

### Actual behavior
When I send "start_date" and "end_date" arguments to the "edd_get_payments" function, there are no retrieved records - unless there are some records that have their respective date equal to "start_date".

### Steps to reproduce the behavior
1) Call the "edd_get_payments" function, sending "start_date" and "end_date" arguments.
2) Check the return value of the function and you will notice that something is wrong.

### Information (if a specific version is affected):
PHP Version: 7.4.12

EDD Version (or branch): 3.0-beta1

WordPress Version: 5.7

Any other relevant information:
It seems that the source code of "easy-digital-downloads/includes/payments/class-payments-query.php" file, is using "$this->start_date" instead of "$this->end_date" when building the "before" part of the query, inside the "remap_args" function. 

See below:
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/c869629d383b736a5d9cde091cc87c2d0f1a887e/includes/payments/class-payments-query.php#L610.

**Comment by napoleaowingert** [comment]
Hi @robincornett, do you know by when we can get an updated beta version with this fix? So that we can retest and verify this again.

**Comment by robincornett** [comment]
The pull request needs to be approved by another team member before it can be merged into the release/3.0 branch, but once it is, you can update your local copy of the beta with the release branch. We do not have a firm date yet for releasing the official beta-2.
