### ISSUE TITLE
3.0 - edd_add_discount parameters are inconsistent with 2.x

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#8544]
### Expected behavior
When I use a function which exists in both EDD 2.x and 3.0, I expect them to parse the same parameters.

### Actual behavior
When I pass `products` as an array key to `edd_store_discount`, it's ignored in EDD 3.0.

### Steps to reproduce the behavior
1. Easiest way is to install the Discount Code Generator extension and add new discounts using that.
2. Alternatively, use `edd_store_discount` with an array of parameters and generate the same discounts in 2.x and 3.0.
3. The key is to have `products` as a parameter with an array of download/products IDs.
4. In 2.x, the products will be added to the Download Requirements for the discount. In 3.0, they will not.

### Information (if a specific version is affected):
PHP Version: 7.4.1
EDD Version (or branch): release/3.0
WordPress Version: 5.7

Any other relevant information:
In 2.x, the `edd_store_discount` function calls the `add` method in the discounts class and ends up parsing the discount parameters as meta values ([products](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/class-edd-discount.php#L1351)).

In 3.0, `edd_add_discount` [uses `product_reqs` instead of `products`](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/discount-functions.php#L26), so the code that works in 2.x to add download requirements no longer works in 3.0.

**Comment by ashleyfae** [comment]
Sounds like we need to add `'products' => 'product_reqs'` to `EDD_Discount::convert_legacy_args()`

**Comment by robincornett** [comment]
I'm comparing the legacy args with what's in 2.x and finding some other inconsistencies. I _think_ that the `convert_legacy_args` method should be converting the parameters that the 2.x functions _expect_, rather than what the 2.x args actually are. The discount parameters in 2.x are converted in the `build_meta` method.

For example, that method [expects `not_global` as a parameter, and converts it to `is_not_global`](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/class-edd-discount.php#L1354), but in 3.x, the legacy args code is looking for [`is_not_global` and converting it to `scope`](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/class-edd-discount.php#L1900). So code that uses `not_global` successfully in 2.x is not working in 3.0. There are other key mismatches as well.

The big one is that in 3.0, the database column for the "minimum amount" is `min_charge_amount`, but the code throughout the plugin is referring to `min_cart_price`. So right now, that property is not being saved or used correctly at all, I think pretty much anywhere. You can replicate it by adding a discount with the "minimum amount" set to anything and it doesn't save.
