### ISSUE TITLE
3.0 - should the order class have recovery functions?

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#8550]
### Explain your enhancement (please be detailed)
In working on #8539, I'm seeing that when the `EDD_Payment` class is instantiated, that there are two "recovery" functions which are not available elsewhere:
- [`$payment->is_recoverable()`](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/payments/class-edd-payment.php#L2645)
- [`$payment->get_recovery_url()`](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/payments/class-edd-payment.php#L2664)

It might be nice for this logic to be available to an individual order.

### Justification or use case
On the purchase history, for example, having these functions available to an order would be one more step towards being able to not use the `EDD_Payment` class.

**Comment by ashleyfae** [comment]
Yes I think it makes sense to copy those methods to the order object. We'll need to handle backwards compatibility for this filter: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/payments/class-edd-payment.php#L2674
