### ISSUE TITLE
3.0 - update edd_maybe_refund_paypal_purchase to use new refund hook

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#8565]
### Explain your enhancement (please be detailed)
We need to change the PayPal refund function to use the new `edd_refund_order` hook.

### Justification or use case
Currently, the pre refund payment hook does not run at all. Adding it to the new hook, but deprecating it, is breaking unit tests.
> The problem with the unit tests is that we are hooking into `edd_pre_refund_payment` in `edd_maybe_refund_paypal_purchase()`.
> 
> Let's open a separate issue to rework `edd_maybe_refund_paypal_purchase() to use the new hook instead`. 
> 
> _Originally posted by @ashleyfae in https://github.com/easydigitaldownloads/easy-digital-downloads/issues/8556#issuecomment-819421325_

**Comment by ashleyfae** [comment]
I'm going to handle this here: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/8564
