### ISSUE TITLE
3.0 - Refunds Modal - Hide content added via hook after refund is processed

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#8568]
The refund modal has a hook `edd_after_submit_refund_table`. I think we should globally hide all that content after the refund is processed.

After implementing https://github.com/easydigitaldownloads/easy-digital-downloads/issues/8564 ("Refund Payment in PayPal" checkbox), here's how it looks by default after the form is submitted:

![Screenshot from 2021-04-14 14-00-58](https://user-images.githubusercontent.com/6324272/114714392-fc79e900-9d29-11eb-85ca-b8ac182bf70f.png)

The checkbox is still visible.

Although we could fix that individually for each item (@robincornett I noticed you had a good solution in Recurring, for example), I think we should have a single, global solution so that we don't have to repeat ourselves for each implementation.

**Comment by robincornett** [comment]
I was actually just thinking about this with PayPal Express--would love to also see a generic CSS rule added to get some margin added to whatever `edd-form-group` elements are added there (I did it in the Recurring PR, but PayPal Express doesn't have any CSS at all, and it would be nice to not have to add it just for this).
