### ISSUE TITLE
Unexpected checkout fields may become required when a discount is applied

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#8572]
### Expected behavior
I expect not-required checkout fields to not change unexpectedly to be required.

### Actual behavior
As reported in Barn2's EU VAT changelog:
> Fix: Fixed a issue introduced in EDD 2.10.1 which made the VAT number a required field on checkout when a discount code was applied.

### Steps to reproduce the behavior
I am actually unable to fully replicate because I went ahead and ran the update to 1.3.5 of the VAT extension. Assume we could replicate with 1.3.4. My guess would be that the extension used the `.edd-input` class for the VAT field--adding that class does reproduce the behavior and removing it fixes it.

### Information (if a specific version is affected):
PHP Version: 7.4.1
EDD Version (or branch): 2.10
WordPress Version: 5.7

Any other relevant information:
My guess is that the fix we applied for #7487 is causing this behavior. Reporting here because although they've resolved it on their end, if we have unintentionally broken similar behavior more universally, it would be great to fix it.

**Comment by cklosowski** [comment]
@ashleyfae can we get this into the next minor release of EDD core.
