### ISSUE TITLE
3.0 - Disable refund button during AJAX request

### ISSUE THREAD

**Issue by LisaCee** [easydigitaldownloads/easy-digital-downloads#8575]
### Expected behavior
If I click two times on the refund button, I expect to only have the first click register (or be acted on)
### Actual behavior
While testing issue/8564 (now merged into core) with a wonky mouse, I kept seeing an error saying "Order not refundable".  At first I thought it was a bug, but it turned out that my mouse was double clicking and causing two requests for a refund.  
### Steps to reproduce the behavior
1) Refund an order with your network speed throttled (slow 3G worked for me)
2) Click the refund button twice
3) You should see a confirmation followed by the error.

### Information (if a specific version is affected):
PHP Version: 7.4

EDD Version (or branch): 3.0

WordPress Version:5.7.1

Any other relevant information:

**Comment by ashleyfae** [comment]
It looks like the logic for this is already there, there's just a small problem with it. ;)

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/assets/js/admin/orders/order-overview/_refund.js#L224
