### ISSUE TITLE
3.0 - $order->get_discounts can return an empty array

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#8576]
### Expected behavior
When I have a proper `$order` from `edd_get_order()`, I expect that `$order->get_discounts()` will return the discounts applied to the order.

### Actual behavior
When I use `$order->get_discounts()` before otherwise getting the order adjustments, no discounts are returned. This is happening with the PR for #8508.

### Steps to reproduce the behavior
1. Check out `issue/8508`.
2. Create an order with a discount applied.
3. View the order receipt/confirmation. The discount does not show.

### Information (if a specific version is affected):
PHP Version: 7.4.1
EDD Version (or branch): release/3.0, but obvious in issue/8508
WordPress Version: 5.7

Any other relevant information:
`get_discounts` [accesses the adjustments property directly](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/orders/classes/class-order.php#L387), but if they have not been retrieved already, no discounts are returned.

I believe the `get_discounts` method needs to be updated to use the `get_adjustments` method the same way the [`get_fees` method](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/orders/classes/class-order.php#L414-L417) does.

**Comment by rottmann** [comment]
Had this problem in EDD-Version 3.1.0.6.

Call it here returns an empty array:
https://github.com/awesomemotive/easy-digital-downloads/blob/main/templates/shortcode-receipt.php#L85
