### ISSUE TITLE
3.0 - order subtotals are not consistent between the admin and front end

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#8578]
### Expected behavior
When I view an order in the admin, I expect the order details to match what the customer sees in the cart and on their purchase receipt.

### Actual behavior
If a discount is applied to an order, the subtotal shown in the admin includes the discount, but that is not the actual order subtotal.

### Steps to reproduce the behavior
It's easiest to see this in action with taxes enabled, as subtotals do not show in the cart unless they are. So enable taxes and make sure the order has a tax applied.
1. Create an order in EDD 3.0 with a discount applied.
2. Note that the subtotal shows the amount of the items in the cart before the discount and tax, and the total shows the amount after the discount and tax are applied.
3. View the order in the admin. Note that the subtotal is a different amount.

Examples:
![3 0-receipt](https://user-images.githubusercontent.com/4853066/115615091-7c6cf980-a2bc-11eb-9932-576bf978cfd0.png)

![3 0-admin](https://user-images.githubusercontent.com/4853066/115615116-8abb1580-a2bc-11eb-9195-c0012e50f407.png)

### Information (if a specific version is affected):
PHP Version: 7.4.1
EDD Version (or branch): release/3.0
WordPress Version: 5.7

Any other relevant information:
My feeling is that the admin JS needs to be updated here to use the actual subtotal value that's stored in the database, instead of recalculating it. [I think it's this section here.](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/assets/js/admin/orders/order-overview/models/state.js#L77-L92)

**Comment by spencerfinnell** [comment]
PR #8581 moves the "Subtotal" row above adjustments and taxes and calculates it as the total item amount.
