### ISSUE TITLE
3.0 - ( ! ) Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in easy-digital-downloads-release-3.0/includes/compat/class-discount.php on line 319

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#8579]
### Expected behavior
Testing the latest release branch, I get this error on the discounts class:

A few errors occurred as follows:

`( ! ) Warning: Undefined array key "where" in /app/public/wp-content/plugins/easy-digital-downloads-release-3.0/includes/compat/class-discount.php on line 319`

`Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /app/public/wp-content/plugins/easy-digital-downloads-release-3.0/includes/compat/class-discount.php on line 319`

### Actual behavior
Fatal error.

### Steps to reproduce the behavior
1)
2)
3)
etc, etc

### Information (if a specific version is affected):
PHP Version: 8.0

EDD Version (or branch): 3.0-release

WordPress Version: Latest

Any other relevant information:

**Comment by robincornett** [comment]
I'm guessing that a query was run treating discounts as a post type, but haven't run into this offhand myself. Looking at the code, it looks like `$clauses['where']` is assumed to be an array, and so line 319 is counting it, but it's possible that whatever query was being run would not have resulted in a `where` key being added to `$clauses`. Need to make sure that is not empty before attempting to count. Marking for beta2 since it's managing backwards compatibility.

**Comment by robincornett** [comment]
I was able to replicate by doing a `WP_Query` with `post_type` set to `edd_discount` and then throwing in a random `meta_query` array. `$clauses` was an empty array at that point, so the `count` threw the error.

**Comment by davidsherlock** [comment]
@robincornett, what is interesting is that I wasn't using any discount codes (or any related code) when this error appeared. It seems to be related to the backwards compatibility checks in some way. Though I didn't delve deep...

**Comment by davidsherlock** [comment]
@robincornett that fixes it, though it's hard to recreate that error on-demand.

**Comment by robincornett** [comment]
Thanks for confirming, @davidsherlock -- reopening until the PR is finalized and merged.
