### ISSUE TITLE
3.0 - manually created orders can have an incorrect subtotal

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#8580]
### Expected behavior
When I manually create an order, I expect the order details to be consistent with an identical order placed from the front end.

### Actual behavior
When I manually create an order with a discount, and do an identical order from the front end, the order subtotals are not consistent.

Manual order:
![image](https://user-images.githubusercontent.com/4853066/115615831-74fa2000-a2bd-11eb-82d8-63e273e5d8e6.png)

Storefront order:
![3 0-receipt](https://user-images.githubusercontent.com/4853066/115615878-80e5e200-a2bd-11eb-870c-c27dd7871a56.png)

(I know there is tax on the second one and not the first, but the subtotals are where the issue is, sorry.)

### Steps to reproduce the behavior
1. Create a discount code.
2. Create an order in the front end and use the discount code.
3. Manually create an order with the same discount code (or amount).
4. Compare the two order rows in the database.
5. The order created from the storefront will not have the discount included in the subtotal. This behavior is consistent with EDD 2.10.
6. The manually created order will have the discount applied to the subtotal, making the subtotal incorrect.

### Information (if a specific version is affected):
PHP Version: 7.4.1
EDD Version (or branch): release/3.0
WordPress Version: 5.7

Any other relevant information:
Related: #8578, but I think there is something going wrong here when the order is set up and added to the database.

**Comment by spencerfinnell** [comment]
PR #8581 calculates the subtotal as the total item amount to correct the value saved in the database.
