### ISSUE TITLE
Update EDD_SL_Plugin_Updater class

### ISSUE THREAD

**Issue by LisaCee** [easydigitaldownloads/easy-digital-downloads#8585]
### Expected behavior
I expect to not get any warnings

### Actual behavior
Following up on PR #[1749](https://github.com/easydigitaldownloads/EDD-Software-Licensing/pull/1749) in SL, and this [comment](https://github.com/easydigitaldownloads/easy-digital-downloads/pull/8287#issuecomment-771622988) in the original issue.
This warning occurs, though I'm not sure what triggers it.
```
Warning: Invalid argument supplied for foreach() in wp-content/plugins/easy-digital-downloads/includes/EDD_SL_Plugin_Updater.php on line 356
````
### Steps to reproduce the behavior
Unknown

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch):

WordPress Version:

Any other relevant information:

**Comment by ashleyfae** [comment]
Updated the title, because we can fix this by updating the `EDD_SL_Plugin_Updater` class we bundle.

**Comment by ashleyfae** [comment]
@LisaCee You should just be able to copy the `EDD_SL_Plugin_Updater` class from the Software Licensing samples into `includes/EDD_SL_Plugin_Updater.php` in core.
