### ISSUE TITLE
3.0 - Declaration of EDD\Utils\Date must be compatible with Carbon\CarbonInterface

### ISSUE THREAD

**Issue by Kubitomakita** [easydigitaldownloads/easy-digital-downloads#8586]
### Expected behavior
When Carbon is required by another plugin or package EDD doesn't throw Fatal Error

### Actual behavior
When Carbon is required by another plugin EDD  throws Fatal Error

### Steps to reproduce the behavior
1) In a separate plugin `composer require illuminate/support` or Carbon itself
2) Active both EDD and this new plugin
3) Fatal error is thrown

### Information (if a specific version is affected):
PHP Version: 7.4

EDD Version (or branch): 3.0.0-beta1

WordPress Version: 5.7.1

Any other relevant information:
Full error:
```
PHP Fatal error: 
Declaration of EDD\Utils\Date::__construct($time = 'now', ?DateTimeZone $timezone = NULL)
must be compatible with
Carbon\CarbonInterface::__construct($time = NULL, $tz = NULL)
in ...\plugins\easy-digital-downloads\includes\utils\class-date.php on line 32
```

**Comment by ashleyfae** [comment]
@Kubitomakita is the issue resolved if you adjust the constructor here: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/utils/class-date.php#L33 like this:

```php
public function __construct( $time = null, $timezone = null ) {
```

**Comment by Kubitomakita** [comment]
@ashleyfae I can confirm it does work after changing the declaration to:

```php
public function __construct( $time = null, $timezone = null ) {
```
