### ISSUE TITLE
3.0 - subtotal, tax, totals should be rounded when saved to the database

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#8599]
### Expected behavior
Data in the database should not be rounded:

> > @ashleyfae I'm not sure how you want to handle the refund issue. The order total is stored as `63.916250000` (cart and manual) but the refund flow JavaScript is using a rounded amount of `63.92` in the validator, creating a larger number than the order total value that is retrieved.
> 
> IMO we should be rounding it when storing it. We should store what we charged. `63.916250000` isn't a real amount that we charged; we should be storing `63.92` (with extra zeros on the end is fine)
> 

_Originally posted by @ashleyfae in https://github.com/easydigitaldownloads/easy-digital-downloads/issues/8581#issuecomment-831956679_

### Actual behavior
In EDD 3.0, the order item values are rounded when stored, but order and adjustment tax and totals are not.

### Steps to reproduce the behavior
1. The easiest way to see this in action is to set up a storefront with a tax rate which will generate non "round" (not end with two decimals really) numbers, or set prices which will result in the same with a tax rate applied. My tax rate is 9.25% so it lends itself well to this.
2. Create orders with taxes and taxable fees. Check the database rows.

### Information (if a specific version is affected):
PHP Version: 7.4.1
EDD Version (or branch): release/3.0
WordPress Version: 5.7.1

Any other relevant information:
This is affecting #8578 and breaking refunds, if an order total is stored as `63.916250000`, the refund validation fails when the refund total is `63.92`, because it's technically greater than the order total. #8578 should be finalized and merged before tackling this as its current focus is to get manual orders synced with cart orders.

**Comment by ashleyfae** [comment]
Is anything still needed here since https://github.com/easydigitaldownloads/easy-digital-downloads/commit/2adfb0ee1e360dd9273073200d658638bc9ab8db ?

**Comment by robincornett** [comment]
This is still needed--that commit just rounded values for order items, to make them consistent with cart rounding behavior. We opted to separate out rounding into a new issue because the goal with that PR was to make manual orders consistent with cart orders. At this point, both workflows round values for order items, but not for adjustments or orders. This issue is specifically just to make sure that everything saved to the database is rounded, which should resolve the current issue where a refund cannot be run for my `$63.92` order because the total in the database is actually `$63.91625` (It won't resolve existing orders, but will fix them going forward).
