### ISSUE TITLE
3.0 - review transaction ID migration

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#8604]
### Expected behavior
If data is migrated to new database tables, I expect it to not be saved to a meta table.

### Actual behavior
Transaction IDs are saved to the new `edd_order_transactions` database table, but they're also saved as order meta with the meta key `_edd_payment_transaction_id`.

### Steps to reproduce the behavior
1. Run a migration which includes transaction IDs (PayPal or Stripe transactions, for example).

### Information (if a specific version is affected):
PHP Version: 7.3.5
EDD Version (or branch): release/3.0
WordPress Version: 5.7.1

Any other relevant information:
I was scanning the data migrator code and ran across [this comment](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/upgrades/v3/class-data-migrator.php#L723-L724):

>		// Transaction IDs are no longer meta, and have their own table and data set, so we need to add the transactions.
>		// @TODO: Add support for multiple transaction IDs (from things like Stripe).

I didn't see an issue created for the `TODO` so am opening one. I'm guessing that the metadata is currently being retained since only one transaction ID is being migrated per order, maybe.

**Comment by ashleyfae** [comment]
@spencerfinnell Are there actually any legitimate cases _right now_ where a single payment could have multiple Stripe transactions? :thinking:

**Comment by spencerfinnell** [comment]
@ashleyfae Technically there is a `PaymentIntent` and a `Charge` that _could_ be linked to an EDD Payment. However, there is an established relationship between those two within Stripe so they are easy to track down within the dashboard. In Stripe we currently use the `PaymentIntent` ID on initial creation and then update it to the `Charge` ID once available (completed payment).

Beyond that Stripe would have a `Subscription` ID or a `Refund` ID, but those could be tied to other relevant EDD records.

**Comment by ashleyfae** [comment]
I think we can just remove that `@todo` comment then. It might be relevant to an overall feature, but not specifically relevant to the migrator, because EDD `master` is only saving one per order anyway.

**Comment by ashleyfae** [comment]
> What about the order meta key/value? Should that continue to be retained after migration in addition to the `edd_order_transactions` table data?

No we can remove it.

**Comment by ashleyfae** [comment]
The `@todo` comment is removed in https://github.com/easydigitaldownloads/easy-digital-downloads/pull/8669

**Comment by spencerfinnell** [comment]
PR #8672 ensures `_edd_payment_transaction_id` is not duplicated in to `wp_edd_ordermeta` during migration.

To test:

1. On `master` complete a purchase that creates an `_edd_payment_transaction_id` metadata entry (Stripe, PayPal, etc).
2. Check out `issue/8604`
3. Run the migration

- Observe an entry is created in `wp_edd_order_transactions` that matches the value of `_edd_payment_transaction_id`
- Observe `wp_edd_ordermeta` does not have an entry for `_edd_payment_transaction_id`
