### ISSUE TITLE
3.0 - Customer email address migration is retrieving customer by user_id, but using the customer ID

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#8616]
## Bug Report

This doesn't look right to me: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/upgrades/v3/class-data-migrator.php#L94

```php
$customer = edd_get_customer_by( 'user_id', absint( $data->edd_customer_id ) );
```

Since we have a customer ID, surely it should just be `edd_get_customer()`

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0

WordPress Version:

Any other relevant information:

**Comment by robincornett** [comment]
Confirmed--I checked my own storefront migration and a customer email has been duplicated and assigned to two different customers.
