### ISSUE TITLE
3.0 - migrated currency can be lowercase

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#8646]
### Expected behavior
When I view an order, I expect the currency to show as a symbol.

### Actual behavior
When I view a migrated order where the `_edd_payment_meta['currency']` is stored as lowercase (`usd` instead of `USD`), the currency is not converted/displayed as `$`.

![image](https://user-images.githubusercontent.com/4853066/119352727-08819080-bc70-11eb-8a44-ae671d5aeae9.png)

### Steps to reproduce the behavior
1. Really you could make this happen by manually changing the currency for an order from `USD` to `usd`, but I'm encountering it as part of a site migration.

### Information (if a specific version is affected):
PHP Version: 7.3.5
EDD Version (or branch): release/3.0
WordPress Version: 5.7.2

Any other relevant information:
I think there are a couple of places where we could tackle this, both for migrated orders and for future proofing:
- when migrating orders, I think we could `strtoupper` the currency value so that old orders have the currency properly stored.
- we could also `strtoupper` the `$currency` variable in `edd_currency_symbol()` to catch any orders with currency incorrectly stored (this fixes the display issue for an order with currency stored as `usd`).

Note that the order displays the same way in EDD 2.10, so this is not a regression; I think it's just incorrectly saved metadata.

**Comment by ashleyfae** [comment]
For now let's do this:

> when migrating orders, I think we could `strtoupper` the currency value so that old orders have the currency properly stored.

I don't want to do this yet:

> * we could also `strtoupper` the `$currency` variable in `edd_currency_symbol()` to catch any orders with currency incorrectly stored (this fixes the display issue for an order with currency stored as `usd`).

It's a good idea, but I've been working on a separate branch that handles some currency stuff like this. So it'll probably already happen at some point.

**Comment by ashleyfae** [comment]
Another thing we could do is add a custom validator to the BerlinDB schema, which will always ensure the currency is saved as uppercase. (Similar to what we did with amounts.)
