### ISSUE TITLE
3.0 - incorrect date string for custom range on reports breaks reports

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#8650]
### Expected behavior
If I set a date range for reports which is a normal date string (for me), I expect it to work.

### Actual behavior
I wanted to view reports for 2018, so instead of using the date picker to set the reports date range, I put dates in by hand, using `01-01-2018` and `12-31-2018`. The result was this:

```
[24-May-2021 17:25:27 UTC] PHP Fatal error:  Uncaught Exception: DateTime::__construct(): Failed to parse time string (12-31-2018) at position 0 (1): Unexpected character in easy-digital-downloads.30\includes\libraries\Carbon.php:291
```

At this point, I cannot view any reports on this site without white screening.

### Steps to reproduce the behavior
1. In EDD 3.0, go to Downloads > Reports.
2. Set the date to Custom.
3. Enter `1-1-2018` and `12-31-2018` as the start and end dates.
4. Click Filter.

### Information (if a specific version is affected):
PHP Version: 7.3.5
EDD Version (or branch): release/3.0
WordPress Version: 5.7.2

Any other relevant information:
It looks like the date picker output is `2018-01-01` for the format.

Related (kind of): #7911

**Comment by robincornett** [comment]
I think the issue is that I'm putting in a date in MM-DD-YYYY format, but the utilities/date class is reading it as DD-MM-YYYY and trying to convert it accordingly. So it's convinced that I have put in an invalid date. I think this is happening because at some point in the date process, basically this code should be running:

```php
$end_date = '12-1-2018'; // used so I would have a date that didn't crash the site
var_dump( EDD()->utils->date( sanitize_text_field( $end_date ), edd_get_timezone_id(), false ) );
```

which returns this:

```
EDD\Utils\Date Object
(
    [date] => 2018-01-12 00:00:00.000000
    [timezone_type] => 1
    [timezone] => +00:00
)
```

If I change the `$end_date` variable to `12-31-2018`, I get the Carbon error.

Additionally, I am not sure that the `other` date filter is working at all. On a site which I know has orders beginning in 2017, when I leave the "from" blank and put in `01-01-2018` (which is properly converted to `2018-01-01`, no data is returned for that range. The graphs show today/tomorrow as the range:

![image](https://user-images.githubusercontent.com/4853066/119562584-7e6f2000-bd74-11eb-9358-0f82b52bf3e5.png)

....so I think there is an issue with parsing custom dates, and an issue with a missing start date (a missing start date seems okay).

**Comment by ashleyfae** [comment]
There are going to be some dates that PHP doesn't like because `strtotime()` can't parse them properly. I think the main thing here, at least for now, is to avoid a fatal error and fall back to something else.

**Comment by ashleyfae** [comment]
For `other`, if you leave "from" blank it appears to default to today instead.
