### ISSUE TITLE
3.0 - Remove unneeded discount note functions

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#8665]
### Expected behavior

Not a bug _per-say,_ but the current 3.0 codebase has a few functions that are no longer required, since 'notes' are handled via standalone functions that accept the object type as a parameter.

The functions are as follows:

`edd_ajax_add_discount_note`
`edd_delete_discount_note`
`wp_ajax_edd_delete_discount_note`

**Comment by ashleyfae** [comment]
@davidsherlock Care to do a PR for this? :grin:

**Comment by davidsherlock** [comment]
Sure, but there is one caveat to this...

The discount functions explictially check for `manage_shop_discounts`, but the note function only checks for 'manage_shop_settings'. Thoughts?

**Comment by ashleyfae** [comment]
I think `manage_shop_settings` is fine here, since adding (or removing) a note to a discount doesn't actually affect the discount itself.

**Comment by ashleyfae** [comment]
Actually I had this backwards, didn't I? The risk isn't that a user can do more than they should be able to, but that someone can edit discounts who can't manage shop settings.

How about we do a switch on the object_type. Then we can check a few permissions explicitly (if it's discount, use `manage_shop_discounts`, etc.). Fall back to `manage_shop_settings` otherwise.

**Comment by davidsherlock** [comment]
Switching on object type is fine within that notes function, but that needs to be filterable for other extensions that use the notes (actually using it myself in one). 

It's really debatable if `manage_shop_settings` is sufficient here, as I feel it is...

Notes feel agnostic to object types and should be handled by this in my opinion.

**Comment by davidsherlock** [comment]
If we go this route, I propose we build a lookup function that has an array contain object types and callbacks, if none are valid then fallback on `manage_shop_settings`.

**Comment by ashleyfae** [comment]
The only weird thing would be if someone can view the UI to add a note, but then can't actually add one. (Because they can manage discounts, but not shop settings.)

Do you use notes in a case where `manage_shop_settings` won't be a good capability to check?

**Comment by davidsherlock** [comment]
Part of me thinks just stick with `manage_shop_settings` for now (for notes). That capability check is fine for me for now

**Comment by ashleyfae** [comment]
I'm fine with that and we can revise later as needed.

**Comment by davidsherlock** [comment]
Done!
