### ISSUE TITLE
3.0 - add a filter on migrated core payment metadata

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#8673]
However, it might be nice to add a filter on the core payment meta array, the way we did on the user info, so that extensions could append to that to save a step in the migration process (when I worked on the user history extension ([PR](https://github.com/easydigitaldownloads/edd-user-history/pull/26)), I added steps to update/delete the payment meta once the user history was migrated, but with a filter in place I would not have to do that).

_Originally posted by @robincornett in https://github.com/easydigitaldownloads/easy-digital-downloads/issues/8603#issuecomment-847978830_

**Comment by spencerfinnell** [comment]
@robincornett Is this referring to https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/upgrades/v3/class-data-migrator.php#L748 or https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/upgrades/v3/class-data-migrator.php#L1093

or both?

**Comment by robincornett** [comment]
That's a good question. I was thinking of it in context of the user history extension, so it would be the first one (748), as that data is added to the `_edd_payment_meta` data in 2.x.

Looking at the PR I have for that extension, it would have to be updated if the filter was applied, because it's using the payment meta that's been saved to the new order, not the data we're temporarily holding from the original order. Not a deal breaker, but I'm wondering if it might be tidier to leave this as is, because the new metadata is a little easier to access than the old. However, the concern I have there is that each plugin is then responsible for potentially updating/removing the payment meta if it's not needed, and if an extension did that incorrectly, then other data could be lost without realizing it.

Since the `_edd_payment_meta` is a bit of a junk drawer used by both extensions and EDD core, my thought was that a filter would allow extensions to prevent their data from being migrated somewhere unnecessarily.
