### ISSUE TITLE
easy digital downloads wallet

### ISSUE THREAD

**Issue by mansoooor** [easydigitaldownloads/easy-digital-downloads#8686]
Hello
I want to report a problem with the edd-wallet plugin.
In the class.edd-wallet-gateway.php file, the incorrect method was used to check the original plugin version.
This way the settings of this plugin are not currently displayed.
See this image: https://prnt.sc/14icviy
You can use version_compare, which is much better.
Now the way you used it, if a dot is added to the version, it will not work!

**Comment by AkramiPro** [comment]
i having the same issue . after update edd plugin the edd wallet settings not displayed anymore.

**Comment by ashleyfae** [comment]
I can confirm this will be fixed in the next version -- sorry for the inconvenience!

If you need further assistance please reach out to our support team here: https://easydigitaldownloads.com/support/
