### ISSUE TITLE
3.0 - email merge tags are not displaying on the settings screen

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#8696]
### Expected behavior
When I edit the purchase receipt email, I expect to see the list of email merge tags below the editor, the way I do in EDD 2.10.

### Actual behavior
No merge tags show below the email editor.

### Steps to reproduce the behavior
1. Visit `/wp-admin/edit.php?post_type=download&page=edd-settings&tab=emails&section=purchase_receipts`

### Information (if a specific version is affected):
PHP Version: 7.3.5
EDD Version (or branch): release/3.0
WordPress Version: 5.7.2

**Comment by ashleyfae** [comment]
Just noting: I assume it was removed because of this new button:

![Screenshot from 2021-06-30 10-56-03](https://user-images.githubusercontent.com/6324272/123941156-cb589e80-d991-11eb-8252-606387b8a4d0.png)

![Screenshot from 2021-06-30 10-56-24](https://user-images.githubusercontent.com/6324272/123941185-d27fac80-d991-11eb-8e06-0a1f0d5895ea.png)

**Comment by robincornett** [comment]
Ah, somehow I completely missed that button. So extensions need to adjust something, possibly, to get this added to their wysiwyg editors, as it's not currently happening. Also I would still ask to move the description below the editor, because when the description does show--especially for lists of the email tags--it feels awkward:

![image](https://user-images.githubusercontent.com/4853066/123956535-c9ceac80-d978-11eb-9df1-c480536b11f1.png)

**Comment by ashleyfae** [comment]
Guess I'm fine with this PR for now -- basically having both options available. We can eventually look at re-removing the hard-coded list, but we can have both for a while to ensure full backwards compatibility in case something doesn't appear in the modal.
