### ISSUE TITLE
Add custom button – All Access Pass

### ISSUE THREAD

**Issue by francescomiano** [easydigitaldownloads/easy-digital-downloads#8697]
## Enhancement Request
I like to add a custom button close to the purchase button, so users can decide whether to pick the single price or the subscription.
I already looked at edd all access pass settings for second button, but no luck!
Maybe it require a bit of custom code in EDD template files?
Just let me know.
Please check the attached image.
https://imgur.com/a/fSOcpc2

Thanks for your support
Frank

### Justification or use case
Very useful to sell both single products and subscriptions at the same time

**Comment by ashleyfae** [comment]
Hi @francescomiano ,

Please contact our support team here: https://easydigitaldownloads.com/support/ They'll be happy to help. :smiley:
