### ISSUE TITLE
Discounts endpoint - unable to filter by discount ID

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#8711]
### Expected behavior

I expect to be able to filter by a specific discount in the discounts endpoint using:

```
curl "https://yoursite.com/edd-api/discounts/?discount=DISCOUNT_ID&key=YOUR KEY&token=YOUR TOKEN"
```

### Actual behavior

The `?discount=DISCOUNT_ID` is ignored. This is happening because `edd_unset_discount_query_arg()` is running, which unsets `$wp->query_vars['discount']` and removes that value entirely.

### Steps to reproduce the behavior
1) Set up an API key for yourself and have a discount ID ready.
2) Run this request (replacing variables): `curl "https://yoursite.com/edd-api/discounts/?discount=DISCOUNT_ID&key=YOUR KEY&token=YOUR TOKEN"` Or just visit the URL in your browser.
3) It will show results for **all** discount codes instead of just the one you specified.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): 2.10.6

WordPress Version:

Any other relevant information:

**Comment by robincornett** [comment]
Confirmed. It looks like we can add a check for `edd-api` in the `query_vars` in the `edd_unset_discount_query_arg` function for the early return. Happy to put together a PR for either 2.11 or 2.10.7?

**Comment by ashleyfae** [comment]
> Confirmed. It looks like we can add a check for `edd-api` in the `query_vars` in the `edd_unset_discount_query_arg` function for the early return. Happy to put together a PR for either 2.11 or 2.10.7?

Let's go with 2.11. This has been around for years and no one has noticed.
