### ISSUE TITLE
3.0 - edd_store_discount($args, NULL) behaviour different

### ISSUE THREAD

**Issue by leewillis77** [easydigitaldownloads/easy-digital-downloads#8721]
### Expected behavior
The following code should produce a discount code in EDD.

```php
$args = array (
  'code' => 'DISCOUNT-41C2542E',
  'name' => 'DISCOUNT-41C2542E',
  'amount' => '10',
  'type' => 'percent',
  'end_date' => '2021-06-25 23:59:59',
  'max_uses' => 1,
  'scope' => 'global',
  'status' => 'active',
);
edd_store_discount( $args, NULL );
```

### Actual behavior
This code works on EDD 2.x, but fails to create a discount code on EDD 3.x. The cause is the use of NULL as a second argument. This causes the code at https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/discount-functions.php#L436 to try and update an existing discount code, instead of inserting one.

**Comment by leewillis77** [comment]
NB: The second arg to `edd_store_discount` defaulted to NULL, not 0 in the 2.x branch - see https://github.com/easydigitaldownloads/easy-digital-downloads/blob/2.10.6/includes/discount-functions.php#L198

**Comment by ashleyfae** [comment]
Thanks for the report!

**Comment by leewillis77** [comment]
Thank you :)
