### ISSUE TITLE
Remove page title from the System Info report

### ISSUE THREAD

**Issue by mihaijoldis** [easydigitaldownloads/easy-digital-downloads#8750]
### Explain your enhancement (please be detailed)
Based on this issue https://github.com/easydigitaldownloads/EDD-Site/issues/1669 I think we can simply remove the page title from the report.

We have seen reports in the past about customers not being able to upload the report on our support page but this is the first time we were able to replicate the issue. I don't think we have ever had any use for the page actual title as the Page ID is already in there so I think we can just drop that.

I made the change locally to just post the ID of the page, if needed I can send a PR with the change:
```
		$return .= 'Page On Front:            ' . ( $front_page_id != 0 ? '#' . $front_page_id : 'Unset' ) . "\n";
		$return .= 'Page For Posts:           ' . ( $blog_page_id != 0 ? '#' . $blog_page_id : 'Unset' ) . "\n";
```

**Comment by ashleyfae** [comment]
Yep I'm happy with that. Please do the PR against `release/2.11` :+1:
