### ISSUE TITLE
3.0 - `offset` has no effect when passed to `edd_get_payments()`

### ISSUE THREAD

**Issue by dimadin** [easydigitaldownloads/easy-digital-downloads#8783]
### Expected behavior
When I pass `offset` to `edd_get_payments()`, I expect that payments are offset for that value. 

### Actual behavior
When I pass `offset` to `edd_get_payments()`, it has no effect. It's not mapped in `EDD_Payments_Query::remap_args()`, it's always [calculated](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/aebe33952b1330bce68ec95ecf4439724868ddd8/includes/payments/class-payments-query.php#L718-L720).

### Information (if a specific version is affected):
EDD Version (or branch):
`release/3.0`

**Comment by ashleyfae** [comment]
Confirmed you can use `'offset'` in EDD 2.10, so this is a backwards compatibility issue / regression.
