### ISSUE TITLE
3.0 - set manual as default order gateway for CLI generated orders

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/easy-digital-downloads#8792]
### Expected behavior
When I generate a bunch of dummy orders using CLI, I'm generally doing so to test something like reports.

### Actual behavior
I generated a bunch of dummy orders and none showed in the Gateway Stats table in Reports because none of the orders had a gateway assigned at all. It seems like `manual` should be the default for CLI orders (if there could be another option, I'm not even sure).

### Steps to reproduce the behavior
1. In EDD 3.0, generate some orders using WP-CLI (something like `wp edd payments create --number=10 --date=random --range=30`)
2. Check the `edd_orders` table. None of those orders will have an assigned gateway.

### Information (if a specific version is affected):
PHP Version: 7.4.1
EDD Version (or branch): release/3.0
WordPress Version: 5.8

**Comment by ashleyfae** [comment]
Maybe `manual` should be the default at the database level. An order should never _not_ have a gateway. :thinking:

**Comment by robincornett** [comment]
I could live with that.

**Comment by cklosowski** [comment]
Agree with @ashleyfae. No order should be without a Gateway. That was the original behavior of manual purchases, and it has caused some odd behavior for years.
