### ISSUE TITLE
Automatically add an item to user account after purchase

### ISSUE THREAD

**Issue by WildeWebMarketing** [easydigitaldownloads/easy-digital-downloads#8793]
Just hoping you or another user can point me in the right direction to get me started with this:

I am currently using Chained Products (which works fine) to add required items to a user's cart. These items are free. Such as the free version of a WordPress plugin that is required to use the Premium version they are purchasing.

But sometimes one item gets removed from cart, but the chained item remains or vice versa, due to confusion or whatever. Instead of trying to display warnings or banners that might not translate well for everyone (international sales), is there a hook to automatically add the required item to this purchase in the background? 

The item is free, so it does not need to precede payment. Is there a hook AFTER payment that I could use to add it, preferably before the purchase confirmation is sent so it is in the email with the other item?

Any help would be awesome.

**Comment by cklosowski** [comment]
Hey @WildeWebMarketing, Github is for development tracking only. Please contact our support team here:
https://easydigitaldownloads.com/support
