### ISSUE TITLE
3.0 - Improve add tax rate UX by moving fields to modal

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/easy-digital-downloads#8800]
### Expected behavior
I mentioned this in another issue (as a comment i think), but having current add tax rate UI is pretty messy and would look a lot better in a modal rather than "bolted" onto the form.

### Actual behavior
Messy UI fields.

### Information (if a specific version is affected):
PHP Version: 8.0

EDD Version (or branch): 3.0-beta3

WordPress Version: latest

**Comment by spencerfinnell** [comment]
Previously: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/8405

**Comment by ashleyfae** [comment]
Thanks @spencerfinnell . I'm going to close this as a duplicate, as there was already some modal discussion in that issue. We can handle it there.
