### ISSUE TITLE
3.0 - "edd_update_payment_status" hook not triggering for orders

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/easy-digital-downloads#8804]
### Expected behavior

When an order's status changes, I expect the `edd_update_payment_status` hook to fire.

### Actual behavior

It doesn't fire unless you're running custom code and working with an `EDD_Payment` object.

### Steps to reproduce the behavior

See https://github.com/easydigitaldownloads/EDD-Software-Licensing/issues/1870 This issue was discovered with Software Licensing, which uses that hook to revoke license keys after a refund.

1. Be on EDD release/3.0
2. Purchase a new SL product.
3. Refund the payment.
4. Note that the license key is not disabled.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0

WordPress Version:

Any other relevant information:

Here's kind of what I'm thinking.

We should _remove_ this from `EDD_Payment::update_status()`:

```php
do_action( 'edd_update_payment_status', $this->ID, $status, $old_status );
```

and move that to trigger when the order status changes. So something like:

 ```php
add_action( 'edd_transition_order_status', function( $old_status, $new_status, $order_id ) {
	do_action( 'edd_update_payment_status', $order_id, $new_status, $old_status );
}, 10, 3 );
```

That will ensure `edd_update_payment_status` runs for orders. Removing it from `EDD_Payment` ensures it doesn't run twice. (Ultimately `EDD_Payment::update_status()` calls an update on the order, which should then trigger the hook.)

This change will require a lot of testing and potentially updates for add-ons. We want to make sure that we don't have any logic running twice.

A quick check revealed the following add-ons using this hook:

- AffiliateWP: `add_action( 'edd_update_payment_status', array( $this, 'revoke_referral_on_refund' ), 10, 3 );`
- All Access: `add_action( 'edd_update_payment_status', 'edd_all_access_check_updated_payment_on_status_change', 101, 3 );`
- Commissions: `add_action( 'edd_update_payment_status', 'eddc_record_commission', 10, 3 );`
- Conditional Emails: `add_action( 'edd_update_payment_status', 'edd_conditional_emails_status_change_email', 100, 3 );`
- Cross Sell / Upsell: `add_action( 'edd_update_payment_status', 'edd_csau_undo_purchase_on_refund', 100, 3 );`
- Fraud Monitor: `add_action( 'edd_update_payment_status', array( $this, 'remove_fraud_flag_on_update' ), 10, 3 );`
- Free Downloads: `add_action( 'edd_update_payment_status', 'edd_free_downloads_remove_optin', -10 );`
- Mailchimp: `add_action( 'edd_update_payment_status', array( $this, 'cancel_order' ), 10, 3 );`
- Slack: `add_action( 'edd_update_payment_status', array( $this, 'edd_failed_purchase' ), 10, 3 );`
- Software Licensing: `add_action( 'edd_update_payment_status', array( $this, 'revoke_license' ), 0, 3 );`
- Stripe: `add_action( 'edd_update_payment_status', 'edd_stripe_process_refund', 200, 3 );`
- Wallet: `add_action( 'edd_update_payment_status', array( $this, 'process_refund' ), 200, 3 );`
- Zapier: `add_action( 'edd_update_payment_status', 'edd_zapier_update_payment_status', 10, 3 );`

**Comment by robincornett** [comment]
Note that Stripe, for example, has updated code to use the new `edd_refund_order` hook:

```php
add_action( 'edd_refund_order', 'edd_stripe_maybe_refund_charge', 10, 3 );
```

SL also already rolls back the license expiration date on refunds of renewal payments, using the same hook.

**Comment by robincornett** [comment]
Current status:

1. Moving this has resulted in download stats not being updated on refund, so in addition to the transition hook, I've had to add the functions for decreasing download earnings/counts when the order items are added to the refund. I felt okay doing this as the related increase functions are used when adding an order.
2. Unit tests are failing in a few places:
    - Weirdly, we are getting errors related to email functions, like:
