### ISSUE TITLE
PayPal Commerce - Make active notice more visible

### ISSUE THREAD

**Issue by LisaCee** [easydigitaldownloads/easy-digital-downloads#8825]
### Expected behavior
I expect users to see a visual cue if they connect PayPal Commerce but it is not active.
### Actual behavior
Everything looks okay, but there is a line at the bottom of the PayPal connection status that says PayPal is not currently active.
We may want to move the notice up to the top or add a red 'x' to show that the gateway is not fully connected. This discussion started [here](https://github.com/easydigitaldownloads/easy-digital-downloads/pull/8596#issuecomment-869775059) and resurfaced due to a customer HS issue.

![image](https://user-images.githubusercontent.com/18077352/130475379-6444ca57-1bd5-4095-bd29-036281269a2a.png)

https://secure.helpscout.net/conversation/1609503277/192417?folderId=180499

**Comment by robincornett** [comment]
If we just do the red X without moving it, this is what we get:

![image](https://user-images.githubusercontent.com/4853066/130478333-9be3529d-e051-47ed-9217-3fa8dfb454ea.png)

It does help it stand out, but I might still vote for moving it to the top. I can go either way, though.

**Comment by cklosowski** [comment]
@robincornett for the time being, let's move forward with this Red X option in the current position. Least amount of change for now while we let this new UI bake a little bit.
