### ISSUE TITLE
PayPal Commerce: Intermittent Nonce Validation issues.

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/Easy-Digital-Downloads#8830]
### Expected behavior
PayPal Commerce should be able to validate a payment attempt is valid.

### Actual behavior
From time to time, we see a 403 nonce validation on the PayPal Commerce button. 

### Steps to reproduce the behavior
1)
2)
3)
etc, etc

### Information (if a specific version is affected):
PHP Version: All

EDD Version (or branch): 2.11

WordPress Version: All

Any other relevant information:
This is similar to what we were seeing with add to cart and remove from cart actions, that is the reason we introduced the tokenized actions (#8714).

**Comment by LisaCee** [comment]
Noting that the nonce validation issues may be causing duplicate and / or pending orders in EDD: https://secure.helpscout.net/conversation/1611612670
