### ISSUE TITLE
PayPal Commerce: Product name is missing inside PayPal

### ISSUE THREAD

**Issue by dgoldak** [easydigitaldownloads/easy-digital-downloads#8833]
### Expected behavior
PayPal transactions should include the product name in the Order details.

<img width="919" alt="CleanShot 2021-08-25 at 15 06 44@2x" src="https://user-images.githubusercontent.com/30910807/130857570-9d6d7ab1-0450-4747-a340-0c049e62c96b.png">

### Actual behavior
Product name is missing from the PayPal Order details. 

![CleanShot 2021-08-25 at 15 03 17@2x](https://user-images.githubusercontent.com/30910807/130857206-35b0d5d8-59b0-4b0c-9b00-58d5424b28cd.png)

### Steps to reproduce the behavior
1) Make a purchase with PayPal Commerce enabled
2) From EDD Order Details, click Transaction ID to open in PayPal. Confirm product is listed  under the order details.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): 2.11

WordPress Version:

Any other relevant information:
Reported by customer: https://secure.helpscout.net/conversation/1612030000/192611?folderId=180499
I replicated this issue on my site.

**Comment by cklosowski** [comment]
Since this is altering the data structure we're sending to PayPal, we're going to punt it to 2.11.2, so @ashleyfae has a chance to review it further before shipping it.

**Comment by mihaijoldis** [comment]
Just had a new report of this issue https://secure.helpscout.net/conversation/1628361472/193937?folderId=180499

**Comment by mihaijoldis** [comment]
A new report regarding this issue here https://secure.helpscout.net/conversation/1635350075/194443?folderId=180499

**Comment by mihaijoldis** [comment]
A new report https://secure.helpscout.net/conversation/1635141855/194432?folderId=180499
