### ISSUE TITLE
Custom checkout button markup can cause a JS error when clicked.

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/easy-digital-downloads#8834]
### Expected behavior
When I customize my checkout button, I expect it to work still when clicked.

### Actual behavior
Due to these changes in the `edd-ajax.js` file https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/assets/js/edd-ajax.js#L402-L405, a customized checkout button will not have the attribute, and therefore possibly fail. 

### Steps to reproduce the behavior
1) Customize your checkout button markup.
2) Try and checkout.

### Information (if a specific version is affected):
PHP Version: All

EDD Version (or branch): 2.11

WordPress Version: All

Any other relevant information:

**Comment by ashleyfae** [comment]
I don't think this change requires a _specific_ ID, it just requires _any_ ID.

But the feedback should be correct. I think we should be able to remove this line completely: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/assets/js/edd-ajax.js#L402

and change [this line](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/assets/js/edd-ajax.js#L405) to:

```js
$(this).attr('data-original-value', complete_purchase_val);
```

**Comment by cklosowski** [comment]
Steps to replicate:

1. Add this to an m plugin:
```
function ck_custom_purchase_button( $button_markup ) {
	$button_markup = '<input type="submit" class="edd-submit green button" name="edd-purchase" value="Complete Checkout"/>';
	return $button_markup;
}
add_filter( 'edd_checkout_button_purchase', 'ck_custom_purchase_button', 9999, 1 );
```
2. Go to the checkout and see the green button
3. Attempt to checkout with Stripe.
