### ISSUE TITLE
Auto-update feature doesn't work with multisite installations

### ISSUE THREAD

**Issue by brianleejackson** [easydigitaldownloads/easy-digital-downloads#8845]
## Bug Report

For full transparency, I opened up a support ticket with the EDD team regarding this on March 15, 2021. And have been in communication with EDD. But the only responses I've received was they are aware of the issue and are looking into it. I followed up on June 17, 2021, and then again on August 26, 2021. 

We've had some clients that are getting frustrated, and I thought it would be helpful to make this a public issue so that other EDD developers could also chime in.

### Expected behavior
_As of Software Licensing version 3.6.12, the plugin updater class is at version 1.8, and includes documented support for auto updates, which WordPress added in version 5.5_ (source: https://docs.easydigitaldownloads.com/article/383-automatic-upgrades-for-wordpress-plugins)

This works great, we moved to the newest updater class and are using the `init` hook. 

Everything works great for standard WordPress installations. However, the problem is that it doesn't work with multisite installations. 

### Actual behavior
When using an EDD plugin in a multisite the auto-update workflow fails at the network level. 

![mutest-edd](https://user-images.githubusercontent.com/186682/131749067-47f871fd-6037-4c8e-b7d3-2709ae6a15ad.png)

Now, you can just update one of the subsites manually and the rest of the subsites will get the update. That's how multisite has always worked. However, the problem is, we have multiple clients that have hundreds of separate multisite installations. 

So for example, we have a client that has 120 separate multisite installations. When auto-updating fails, it means he has to touch all 120 multisite installations. So for every update, we push out, the client has estimated that it takes him almost an hour sometimes to run all the updates. That's obviously not sustainable. 

### Steps to reproduce the behavior
1) Install an old EDD plugin (a version behind current is fine) and network activate it. 
2) Turn auto-updates on for the plugin.
3) Wait for it to fail at the network level.

### Information (if a specific version is affected):
PHP Version: 8.0

EDD Version (or branch): Latest EDD version and we tested with version 1.9 updater class for the plugin.

WordPress Version: 5.8

**Comment by ventureplatform** [comment]
+1 on this. I can confirm that this bug costs me around 50-60 min of dev time every time an update need to get installed. There have been at least 24 updates since last March and that's **twenty hours** of dev time WASTED because this issue hasn't been getting the attention it needs from EDD. 

Add to that, the hundreds of notifications we get when auto-updates fail and this is a serious pain point.

Please EDD, we're begging you, get this fixed. This isn't your usual level of detail and responsiveness and it's more than just an inconvenience, it's a major drain of time and resources.

**Comment by ashleyfae** [comment]
I'm sorry that we don't have a fix in place for this yet. Thus far we've been struggling to reproduce the problem ourselves, but we are actively working on doing so and hope we can have a fix in place soon.

**Comment by ventureplatform** [comment]
I appreciate the reply but it seems that it's something multiple users are experiencing. What additional information about the network environment is needed to demonstrate reproducing the error?

**Comment by ashleyfae** [comment]
Also can you please confirm which version of our `EDD_SL_Plugin_Updater` class you're using? It's noted at the top of the file. Example:

```php
/**
 * Allows plugins to use their own update API.
 *
 * @author Easy Digital Downloads
 * @version 1.9.0
 */
```

**Comment by ventureplatform** [comment]
I assume this instruction was meant for me, correct? https://github.com/easydigitaldownloads/easy-digital-downloads/issues/8845#issuecomment-916227659

And this one was meant for Brian? https://github.com/easydigitaldownloads/easy-digital-downloads/issues/8845#issuecomment-916232994

**Comment by brianleejackson** [comment]
Thanks for responding @ashleyfae. 

As mentioned in the original issue above, but also to confirm: 
```EDD Version (or branch): Latest EDD version and we tested with version 1.9 updater class for the plugin.```

I saw a mention of some MU changes in the last update so that's why we tested with the 1.9 updater class. We thought that might resolve the issue, but it didn't. 

We're going to add the email debug filter and we'll follow up with what we find.

**Comment by ashleyfae** [comment]
@ventureplatform You are both welcome to respond to both. The more information we can get from everyone the better.

Thanks @brianleejackson . I hope we can get some useful information out of that debug email. :crossed_fingers:

**Comment by brianleejackson** [comment]
OK, so I did a fresh test. We are using the latest 1.9 EDD updater class in the plugin. 

I enabled the debug email with the snippet of code you provided. 

![image](https://user-images.githubusercontent.com/186682/133673805-ce899a04-17b6-45c6-80ae-3162ad7d1d81.png)

Unfortunately, the email isn't very helpful. 

 _Updating plugin: Novashare
 Update package not available._

Any other ideas? Happy to provide any information you need to help debug the issue further. Thanks

**Comment by robincornett** [comment]
Hi @brianleejackson, I agree, that's not helpful at all. When I've been testing this locally, I have used two plugins to help me dig into what's going on:
- [Log HTTP Requests](https://wordpress.org/plugins/log-http-requests/): logs all of the requests your site makes, and the responses for each
- [WP Crontrol](https://wordpress.org/plugins/wp-crontrol/): shows the scheduled cron events and allows you to trigger any of them manually

If you have a place where you can do this (I would recommend a local site), you might use these tools to help. For example, triggering the `wp_version_check` event (which is what's used for automatic updates) resulted in this for my sample plugin:

![image](https://user-images.githubusercontent.com/4853066/133679372-895d1038-34bd-4d77-9406-3deee700087a.png)

So I can confirm the download/package URL, and what response my store/site sent back to me. This may be more helpful if you can get it. Thank you for your patience.

**Comment by mihaijoldis** [comment]
@brianleejackson @robincornett might be a long shot but I assume that plugin that failed is a paid/premium one. 
In that case does it have an active license registered on the website the update is running on?

**Comment by ashleyfae** [comment]
Thanks for following up @brianleejackson ! Glad you got it sorted. :raised_hands: Multisite can be tricky with licensing.
