### ISSUE TITLE
abandoned payment

### ISSUE THREAD

**Issue by mohammadr3z** [easydigitaldownloads/easy-digital-downloads#8855]
Hi
Is it possible to repay abandoned purchases?

For example, https://easydigitaldownloads.com/ has done this:

https://prnt.sc/1r4lxa3

<link removed>

**Comment by cklosowski** [comment]
If a user account is found the user and the gateway is used that is written to support the 'resume payment' feature of EDD then it is possible for a logged in user to go to their account to complete an abandoned purchase. But this depends on the gateway being used.

Github is for development tracking only. Please contact our support team here:
https://easydigitaldownloads.com/support
