### ISSUE TITLE
where should i insert facebook conversion pixel tracking?

### ISSUE THREAD

**Issue by DionGanteng** [easydigitaldownloads/easy-digital-downloads#8856]
where should i insert facebook sales tracking? because the success page page can be accessed many times by the user and if applied for facebook pixel tracking it will be triggered many times

**Comment by robincornett** [comment]
Hi @DionGanteng and thank you for reaching out! Our support team does not monitor GitHub, which we use for development tracking. Please reach out to the team using our support form: https://easydigitaldownloads.com/support/ and they will be happy to try to help you get started with this.
