### ISSUE TITLE
Easy Digital download invalid login error missing

### ISSUE THREAD

**Issue by shahnasir414** [easydigitaldownloads/easy-digital-downloads#8884]
hi i am using EDD on one of my site using Mayosis Theme which is fully capibale with EDD. when ever someone enter incorrect user and password login error message is not showing. check bellow page.
https://239.digital/dashboard/
enter any user and password you will note that error is not displaying only page refresh occurs.

Thanks
Nasir

**Comment by ashleyfae** [comment]
Hi Nasir,

Can you please contact our support team here: https://easydigitaldownloads.com/support/ They'll help walk you through some troubleshooting steps to rule out potential conflicts. If they can confirm it as a bug then they'll make an issue here.

Thanks!
