### ISSUE TITLE
nevermind

### ISSUE THREAD

**Issue by Programmer095** [easydigitaldownloads/easy-digital-downloads#8897]
### Expected behavior
A payment is created when a transaction is sent to Stripe so that a record exists if the process doesn't complete.

### Actual behavior
A payment is processed by Stripe but there are no payment details saved in EDD when the PHP process doesn't complete.

### Steps to reproduce the behavior
It's intermittent in the wild. But, it happens when the PHP process fails to complete after the charge has been sent to Stripe for processing, but before it returns the result. 

### Information (if a specific version is affected):
PHP Version: 7.4.23

EDD Version (or branch): 2.10.6 (I didn't see anything relevant in the changelogs for newer versions)

WordPress Version: 5.8

Any other relevant information:
The easiest solution of course would be to increase the max execution time for PHP. However, we're at the host's limit and host migration is troublesome. The goal is to avoid the 'ghost' charges that are happening now. We at least need to know that the charge was made from within EDD. Any suggestions are welcome.

**Comment by cklosowski** [comment]
Hey @Programmer095 if there was some insights into what you saw here or something we can help improve let us know.

Even if you saw this coming from a conflict or something else, it might give us a hint as to a way we can maybe prevent it?

**Comment by Programmer095** [comment]
@cklosowski I'll be back with details once I get to the bottom of the issue. It's being troublesome to track down the root cause and it doesn't appear to be as initially thought (it's probably not just due to a script timeout). Onward with the logging and waiting I suppose. :-)

**Comment by cklosowski** [comment]
@Programmer095 Okay, we're here if you find anything that we can implement on our end :+1:
