### ISSUE TITLE
Discount Coupon's activate/deactivate setting in the screen don't work

### ISSUE THREAD

**Issue by soyket** [easydigitaldownloads/easy-digital-downloads#8908]
### Expected behavior
When you go to EDD > Discount Codes > Hover over a Discount code > Click Activate / Deactivate to change the status, it should update the status but it doesn't. 

The status is only updated when I enter the discount code's edit screen fully and edit it there. 

I am on the latest version of the plugin btw.

**Comment by cklosowski** [comment]
Interestingly enough, the 'quick actions' show us the `Activate` link, meaning that I think we're caught up in an object level caching issue here.

**Comment by cklosowski** [comment]
Found the issue, the `update_status` method was only updating the `post_status` and not also updating the `status` meta value.

**Comment by soyket** [comment]
Nice. @cklosowski :) glad you found and resolved it soon
