### ISSUE TITLE
Add Support for X-Sendfile to Download Process

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#980]
X-Sendfile is one of the best ways (that I know of) for delivering large file downloads.

We should work on implementing it. We will have to do some detection for x-sendfile support, or simply add an option to enable it as it's not always enabled on all servers.

Here's a nice guide: http://stackoverflow.com/questions/3697748/fastest-way-to-serve-a-file-using-php/3731639#3731639

**Comment by davidsherlock** [comment]
@pippinsplugins, can mod_xsendfile be enabled within EDD using some custom function? I want to use it to server larger files to customers.

**Comment by pippinsplugins** [comment]
@davidsherlock I'd be more than happy to consider it. If you can send us a PR we can look into it.
